### PR TITLE
perf: Performance fixes for flight plans

### LINKED ISSUE #1341: [BUG] Performance degradation with mod since MSFS 1.9.5.0
**Mod Version**
master

**Describe the bug**
I am getting low performance (5-15 fps less) compared to the vanilla; this didn’t happen some days ago.

**To Reproduce**
Compare fps with mod and without mod

1.
2.
3.

**Expected behavior**
The mod should not affect performance so much.

**Actual behavior**
 Mod affect performance (5-15 fps less compared to the vanilla)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I noticed it today for the first time.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by XSJoJo**
Fixes #1341

## Summary of Changes
- Only reload flight plan if changed.
- Throttle Flight plan redrawing to 10fps
- Don't draw flight plan if display is turned off
- Get rid of some logic in BaseInstrument.js that is superfluous since FMGC already handles activating approach phase.

In total, I'm getting about 5-10fps more in CoherentGT limited scenarios when a flight plan is loaded. More importantly, this fixes the bad FPS drops every second which causes quite bad stuttering (see screenshots below).

## Screenshots (if necessary)
Before:
PXL_20210130_190932496

After:
PXL_20210130_190718425

## References
n/a

## Testing instructions
Load any flight plan and modify it. Ensure that ND updates with flight plan changes.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Review by beheh — APPROVED** [review]
Looks good. The versioning is actually very similar to what the upcoming flight plan manager already does, but this should improve performance in the mean time. The throttling looks appropriate.

**Comment by SaqibSiddiqi** [comment]
Category: QA Tester/Trial
Name: Discord User AssassinXpq#1079
Date of testing: 1/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3262
Tier of testing: 2
Changes to observe:
Only reload flight plan if changed.
Throttle Flight plan redrawing to 10fps
Don't draw a flight plan if the display is turned off

Testing technique: Load any flight plan and modify it. Ensure that ND updates with flight plan changes.
Steps you've made to test the Pull Request:
1. Load int EGKK
2. File a flight from the main menu
3. Load in the Flight Plan
4. Change the flight plan
5. Check if the ND updates
6. Check for performances changes

Check performance changes
ND screen on
 - 3-5 FPS gain till 60FPS
ND screen on
 - up to 15 FPS increase
Flight notes: EGKK DCT EGLL
2070 Super
i7 9th gen
32GB RAM

Media: ScreenShots here

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Positive and smoother FPS, performance increase noticed. If the ND is off, performance is increased and not drawn

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 1/2/21
Version of the sim: 1.12.13.0
PR Tested: #3262 
Tier of testing: 2
Changes to observe:
Flight plan 

Testing technique: Did a full flight
Steps you've made to test the Pull Request:
1. Loaded in 
2. manually loaded the flight plan
3. deleted waypoints and edited flight plan

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): Not sure if it is fully this PR's fault but when entering the flight plan in manually some waypoints took very long to load in while others loaded in instantly. It can also be quite "laggy" when moving through the flight plan in plan view as it takes different times to move between which could be because of the flight plan fps
Steps to achieve the issue

Overall Rating: To be improved
Conclusions of the testing: I myself noticed a small fps increase but Coherent GT Draw is now in the green but the flight planning itself can feel slow and unresponsive at times

**Comment by XSJoJo** [comment]
Are you sure this is a regression from this PR? Previously, flight plan was
reloaded every 100 frames to it wasn't instant either I think?

**Comment by MisterChocker** [comment]
Please rebase on latest master.

**Comment by XSJoJo** [comment]
> Please rebase on latest master.

Done.

**Comment by XSJoJo** [comment]
> Category: QA Tester
> Name: FlightSimmer7700#3468
> Date of testing: 1/2/21
> Version of the sim: 1.12.13.0
> PR Tested: #3262
> Tier of testing: 2
> Changes to observe:
> Flight plan
> 
> Testing technique: Did a full flight
> Steps you've made to test the Pull Request:
> 
> 1. Loaded in
> 2. manually loaded the flight plan
> 3. deleted waypoints and edited flight plan
> 
> Flight notes (When done a full flight):
> 
> Media: Insert screenshots, recordings, or anything relevant to the review here.
> 
> Issues (If Any): Not sure if it is fully this PR's fault but when entering the flight plan in manually some waypoints took very long to load in while others loaded in instantly. It can also be quite "laggy" when moving through the flight plan in plan view as it takes different times to move between which could be because of the flight plan fps
> Steps to achieve the issue
> 
> Overall Rating: To be improved
> Conclusions of the testing: I myself noticed a small fps increase but Coherent GT Draw is now in the green but the flight planning itself can feel slow and unresponsive at times

Ok, did some more testing, moving through flight plan definitely regressed. I fixed that issue (PTAL) and it seems that it's now even faster than Tip-of-Tree.

Same thing applies for inserting waypoints into the flight plan, should be more responsive than Tip-of-Tree.

**Comment by CaptainRafael** [comment]
Category: QA Tester ( Trial ) 
Name: Captain Rafael#0001
Date of testing: 06/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3262
Tier of testing: 2
Changes to observe:
Flight plan

Testing technique: Spawn in an airport
Steps you've made to test the Pull Request:

Load in C/D LFKJ
Imported Simbrief flight plan
deleted waypoints on sid  and edited flight plan route
Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
Before 
image
image
After : 
image


Issues (If Any): 
Overall Rating: Good 
Conclusions of the testing:  Noticed a  small fps increase
The CoherentGTDraw is almost null 
No spikes anymore 
FLP feels responsive comparing to before

**Comment by GlitchedYT** [comment]
Category: QA Tester
Name: Glitched#0740
Date of testing: Current date 2/6/2021
Version of the sim: 1.12.13.0
PR Tested: #3262
Tier of testing: 2
Changes to observe:
-Only reload flight plan if changed.
-Throttle Flight plan redrawing to 10fps
-Don't draw flight plan if display is turned off
-Get rid of some logic in BaseInstrument.js that is superfluous since FMGC already handles activating approach phase.
(Insert the Summary of changes, in order to remind what is to test)

Testing technique: Load any flight plan and modify it. Ensure that ND updates with flight plan changes.
Steps you've made to test the Pull Request:
(Non PR Build)
1. Loaded C&D at KATL gate C22
2. Made a flight from KATL to KSEA
3. Started adding random runways and SID's and STAR's and made sure everything still worked and showed correctly on the ND
(PR Build)
1. Loaded C&D at KATL same gate
2. Made a flight KATL to KSEA
3. Messed around with flight plan, added different SID's/STAR's and deleted and added waypoints to ensure it all worked and showed correctly

Flight notes (When done a full flight): N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
Without PR
image
With PR
image


Issues (If Any): None from my end!
Steps to achieve the issue

Overall Rating: Good, i didnt really have a perf increase but coherent GTDraw was deffinitely lower, almost zero with this PR
Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.

**Pull request merged**
