### PR TITLE
fix: use sensible defaults for non configured throttles

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #[issue_no]

## Summary of Changes

Adapted the default values for the detents when no calibration has been done yet. (I've used my thrustmaster TCA as reference but it is also applicable to other throttles)

The main goal is to allow usage of throttles without touching the calibration. 

## Additional context

Discord username (if different from GitHub):

## Testing instructions

* Delete existing throttle configuration in `work` folder
* Test PR contents

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by aguther — APPROVED** [review]

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 24/05/2021
Version of the sim: 1.15.10.0
PR Tested: #4663 
Tier of testing: 1
Changes to observe: Check throttle defaults prior to calibration

Testing technique: Tested on stand, no flight
Steps you've made to test the Pull Request:
1. Removed my throttle calibration files from the localstate fbw folders
2. Booted the sim and spawned C&D
3. Began to set up for flight and checked throttle calibration on stand with the defaults
4. Push and Start, and took off to check throttle detent "feel" during takeoff roll
5. Quick Circuit and landed again checking defaults without calibration

Flight notes (When done a full flight):
Hardware: Thrustmaster T-Flight Hotas X Full Flight Kit (yes, I know it's cheap!)

Media:

Issues (If Any): 

Overall Rating: Good
Conclusions of the testing: Detents seemed reasonable for defaults with my hardware, no issues. LGTM

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 24/05/2021
Version of the sim: 1.15.10.0
PR Tested: #4663 
Tier of testing: 1

Changes to observe:
use sensible defaults for non configured throttles

Testing technique: Try-out on a TCA Quadrant Airbus Edition

Steps you've made to test the Pull Request:
1. Deleted(backup) work folder from packages
2. C&D @ LIRN
3. checked flyPAD detents
4. checked throttle detents
5. see issue

Flight notes (When done a full flight):
N/A
Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A

Issues (If Any): 
Detents are not recognised 
Steps to achieve the issue:
Once loaded the throttle is on IDLE, moving towards TOGA goes nearly immediately to TOGA 
it doesn't go any other stage, reverting back to IDLE it stops on CL

Overall Rating: Needs improving
Conclusions of the testing: I think since the throttle config needs to be delete a new once is not made, which it doesn't do it when opening CALIBRATE or restart the AIRCRAFT.

**Comment by aguther** [comment]
> Category: QA Tester
> Name: David#2177
> Date of testing: 24/05/2021
> Version of the sim: 1.15.10.0
> PR Tested: #4663
> Tier of testing: 1
> 
> Changes to observe:
> use sensible defaults for non configured throttles
> 
> Testing technique: Try-out on a TCA Quadrant Airbus Edition
> 
> Steps you've made to test the Pull Request:
> 
> 1. Deleted(backup) work folder from packages
> 2. C&D @ LIRN
> 3. checked flyPAD detents
> 4. checked throttle detents
> 5. see issue
> 
> Flight notes (When done a full flight):
> N/A
> Media: Insert screenshots, recordings, or anything relevant to the review here.
> N/A
> 
> Issues (If Any):
> Detents are not recognised
> Steps to achieve the issue:
> Once loaded the throttle is on IDLE, moving towards TOGA goes nearly immediately to TOGA
> it doesn't go any other stage, reverting back to IDLE it stops on CL
> 
> Overall Rating: Needs improving
> Conclusions of the testing: I think since the throttle config needs to be delete a new once is not made, which it doesn't do it when opening CALIBRATE or restart the AIRCRAFT.

Well, there is no intend to provide a default config that works out of the box with the TCA. A calibration will still be needed. The default has the purpose to provide a sensible default to hopefully many people that do not have something like hardware detends…

**Comment by DavidEGTE** [comment]
>
> Well, there is no intend to provide a default config that works out of the box with the TCA. A calibration will still be needed. The default has the purpose to provide a sensible default to hopefully many people that do not have something like hardware detends…

So you're saying this is not appropriate for TCA users?
Because I'm still on this PR and it's not letting me set up any of detents!

**Comment by aguther** [comment]
> > Well, there is no intend to provide a default config that works out of the box with the TCA. A calibration will still be needed. The default has the purpose to provide a sensible default to hopefully many people that do not have something like hardware detends…
> 
> So you're saying this is not appropriate for TCA users?
> Because I'm still on this PR and it's not letting me set up any of detents!

Are you able to set it up on development version?

**Comment by Samueleonard** [comment]
Quality Assurance Tester Report

Discord: @1samueleonard1#0001
Object of testing: (#4663)
Tier of Testing: (1)
Date: (24/05/2021)

Testing Process: renamed old config, loaded into sim on runway, checked new file had overwritten detents in efb, moved throttle through ranges, checked deadzones etc
Negatives: n/a
Testing Results: (Passed)

Conclusions: throttle was using new ranges - i personally have my own detents anyway, and this config was made using a specific hotas, so it wont work for everyone - could it better to have a dropdown with different presets for popular sticks (out of the scope of this pr i know,)
Media: n/a

**Comment by DavidEGTE** [comment]
> > > Well, there is no intend to provide a default config that works out of the box with the TCA. A calibration will still be needed. The default has the purpose to provide a sensible default to hopefully many people that do not have something like hardware detends…
> > 
> > 
> > So you're saying this is not appropriate for TCA users?
> > Because I'm still on this PR and it's not letting me set up any of detents!
> 
> Are you able to set it up on development version?

yes, no problem on DEV version

**Comment by dragold** [comment]
Quality Assurance Tester Report

Discord: Mr.Blank#2638
testing: (#4663)
Tier of Testing: (1)
The version of the sim: 1.15.10.0
Date: (24/05/2021)

Testing Process: Tryout 
-Testing instructions
 --Delete existing throttle configuration in the work folder
 --Test PR contents
-Methodology
 --SOP flight
 --Non-SOP flight
 --rapid input test
 --Keyboard over thrust test

Negatives:
-references:
--https://ptb.discord.com/channels/738864299392630914/754130199804772372/846489180913008682 - 
when using the keyboard for throttle control after the pause and unpause it resets to idle power when the axis is set to idle, this was told to be a bug of the sim...
Testing Results:(Passed)

**Comment by Benjozork** [comment]
@Saschl state of this regarding @DavidEGTE's comment ?

**Comment by Saschl** [comment]
We talked on discord about it and I think we agreed on that it worked fine if you didn’t touch the calibration do I remember that right @DavidEGTE ?

**Review by tracernz — APPROVED** [review]
The detents are a little off for my TCA with linear input curve, but I was able to calibrate just fine.

**Comment by MisterChocker** [comment]
So is this good to me merged then?

**Comment by Saschl** [comment]
Let's do so

**Pull request merged**
