### PR TITLE
feat: glass and reflections

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

* Add back glass models
* Increase backlight strength and adjust LCD background

## Testing instructions

* Verify display appearance

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by AquazDev** [comment]
Quality Assurance Tester/Trainee Report

Discord: LunakisLeaks#7744
Object of testing: #PR 6848
Tier of Testing: 1
Date: 05/03/2022

Testing Process:

Started Cold and Dark - OK

Tested All Displays And Reflections - OK

Negatives: N/A

Testing Results: Passed

Conclusions: LGTM

**Comment by Letreivchen** [comment]
Quality Assurance Trainee Report

Discord          : Letreiv
Object of testing: #6848 
Tier of Testing  : 
Date             : 05/03/2022

Testing Process: 
Tested if all displays have glass and reflections- OK
Tested if the screen-brightness flickering issue while flying trough clouds is still present- OK
Tested if screen-brightness still increases while flying through clouds - Still happens
Tested brightness at max screen-brightness



-Tested brightness at 50% screen-brightness


-Tested brightness at max screen-brightness at night 


Tested auto-brightness of the ISIS- OK
Tested auto-brightness of the Clock- NOT OK ( see Negatives)





Negatives:       
-Personally the maximum screen brightness feels too dark
-The auto-brightness of the clock seems to be broken:
image
image
Compared to master:
image
image

-Screen brightness still increases while flying through clouds



Testing Results: 
NOT PASSED

Conclusions: 
The glass and reflection addition of the screens definitely makes it more realistic and are a beautiful addition, at the moment there are still some issues that need to be fixed( see Negatives) before this PR is ready to get merged :).
image

**Comment by Nufflee** [comment]
Not a QA tester but all displays are a lot dimmer following this change, crucially the RMP whose brightness can't be adjusted and is a litte hard to see. I only tested at night.

image

**Comment by gandalfthewhite19890404** [comment]
image
Digits on radios and tcas panel are too dark

**Comment by aguther** [comment]
I also think that the default brightness is now too low. This should be increased, otherwise the displays are often not readable.

Beside that the issue with clouds is not solved so it should not be merged anyway.

**Comment by Letreivchen** [comment]
> I also think that the default brightness is now too low. This should be increased, otherwise the displays are often not readable.
> 
> Beside that the issue with clouds is not solved so it should not be merged anyway.

Yep, we probably need to get more feedback from pilots regarding the brightness. The issue with clouds isn't too bad anymore because at least the nasty flickering got fixed. Apparently that remaining issue with clouds cannot be fixed so we probably have to weigh what is worth more, having the glass and reflections look or not having the brightness issue. Personally I think once the other stuff mentioned here is fixed it's good to go.

**Comment by pdeswardt** [comment]
I can concur - MCDU,Radio and Transponder windows are now very hard to read. It's way too dim, especially the transponder.

**Comment by dragold** [comment]
Quality Assurance Trainee Report
Discord : Mr.Blank#6197
Object of testing: #6848
Tier of Testing :1
Date : 10/03/2022

Testing Process:
Glass and reflection test
Flicker test
brightness test
Auto Brightness test (ISIS, Clock)
manual Brightness test (ISIS, Clock)(standard operations)
note
-all test where conducted on both quick start and from cold and dark
-variation in time and weather was introduced to further test the model

Negatives:
 Overall changes can be well improved, still feel bit sluggish on the clock, ISIS& Center pedestal panel(VHF) to me
variation of brightness is still observed wile flying through clouds or weather systems


Testing Results:
NOT PASSED

Conclusions: Many of the early told bugs are near fixed but can be improved

**Pull request closed without merging**
