### PR TITLE
Two small fixes for flightphase speeds

### LINKED ISSUE #2260: [BUG] Indecisive managed speed
**Mod Version**
 Latest development (Master)

{
  "built": "2020-12-06T08:38:03+00:00",
  "ref": "",
  "sha": "",
  "actor": "lukecologne <39596827+lukecologne@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

I'm not sure if this occurs randomly or closer to the destination airport, or during a turn. However, at some point in my flights the managed speed appears to be going back and fourth between my cruise speed and 250 kts. Once it begins doing this it will keep doing it for what will appear to be the rest of the flight, or once I hit a decel point. Turning on and off managed speed mode does not work as once managed speed mode gets re-engaged it continues to go back and fourth between these two speeds. I have had this bug on two consecutive flights so far. On my second flight it seemed to occur once for a short amount of time while I was in a turn on the climb out of Atlanta, however it ended up resolving itself. Later in the flight however, as I was much closer to my destination, it happened again and this time did not resolve itself and I had to turn the speed mode to selected. I do not have much memory from the first flight this happened but I'm pretty sure it was toward the end of the flight as well. I'm pretty sure that this bug continues until you hit the first decel point on the approach as that's when I turned it back to managed on the first flight and it started working again, however, I'm unsure if it really persists for this long. 

**To Reproduce**

1. Start a flight cold and dark and do not have a flight plan pre loaded (create your flight plan in the mcdu)
2.Set up the plane as normal 
3. Takeoff and proceed with the flight as normal - this bug occurred on two consecutive occasions like this. 

**Expected behavior**

The managed airspeed will stay at one speed unless it needs to be changed for any reason (speed restrictions, approach etc.) 

**Actual behavior**

The managed speed setting seems to switch constantly back and fourth between my cruise speed and 250kts at some point in the flight, usually closer to my destination.
**References**

 Airspeed mysteriously drops to 250
Screenshot (587)

about 5-20 seconds later increases to 290 again

Screenshot (588)

5-20 seconds later the airspeed decreases to 250 again and the cycle repeats

**Additional context**

Approach mode is confirmed not to have activated during this as I checked the mcdu as it was going on so it is not a bug with approach mode activating. 

Was this working before/when did the issue start occurring?

This seemed to start happening after World Update II, I couldn't really play the sim at the time due to the autopilot suicide bug but once that was fixed, I found out that this was an issue. I'm not sure if this issue was caused by the fixes or not. 

Is this a problem in the vanilla unmodded game?

Unknown 

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by Watsi01**
Fixes #2260 (maybe)

## Summary of Changes
Just fixed two tiny things:
1. In CDU Maindisplay a simvar was wrong ("feets" instead of "feet"). 
2. In FMC Maindisplay the calculation for the descent speed resulted in lower descent speeds, the higher the CI is set. This is now fixed.

## Screenshots (if necessary)
no

## References
no

## Additional context
none

Discord username (if different from GitHub): RogePete

## Testing instructions
I don't think this needs to be tested. But if someone wants to: just make a normal flight with full programmed MCDU and check, if the flightphase speeds are correct / nothing weird happens.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by MisterChocker** [comment]
don't forget to add changelog

**Comment by Watsi01** [comment]
@MisterChocker Thanks. But this fix is so tiny. I thought I shouldn't. But if it is important for documentation, I'll do it??

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date 29/12/20
Version of the sim: 1.12.13.0
PR Tested: #2699 
Object of test: Small fixes fixing descent speeds

Testing technique: Did 2 flights
Steps you've made to test the Pull Request:
1. Loaded up cold and dark
2. completed the flight while looking at the speeds on descent
3. loaded up for a second flight 
4.completed the second flight 

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: LGTM

**Pull request merged**
