### PR TITLE
feat: Pilot Avatars visible via flyPad setting

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes
Adds pilot avatars in cockpit view for pilot and first officers

Motivation is that many users still try to use a flightsim.to add-on to show avatars which constantly leads to issues and support cases with the A32NX. With this feature this add-on is not required any more and users who want to have the pilot avatars visible can simply turn it on in the flyPad. 

##  Screenshots (if necessary)
https://user-images.githubusercontent.com/16833201/189166377-e036851f-8600-428b-9cef-5efa49e6a4ef.mp4

Discord username (if different from GitHub): Cdr_Maverick#6475

## Note to Reviewers
- gltf files have been reformated (JSON) to be better manually editable - therefore no real diff 
- the camera.cfg file has also been correctly formatted which leads to many diff changes

## Testing instructions
- Per default avatars should not be visible
- Go to the flyPad Realsim Settings page and turn on pilot and first officer and check if avatars are visible in each combination

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by tracernz** [comment]
Do we need to edit the base model, or can we add the objects as normal with our model build script?

**Comment by ErikNL80** [comment]
Nice addition!

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7479
Tier of Testing  : 1
Date             : 19/09/2022

Testing Process: 
Per default avatars should not be visible - **OK**
Go to the flyPad Realsim Settings page and turn on pilot and first officer and check if avatars are visible in each combination - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

Media:       
image

**Review by tracernz — APPROVED** [review]

**Comment by tyler58546** [comment]
This needs to be reverted. Changes were made to the base model file which resulted in a double cockpit mesh, causing lots of flickering throughout the cockpit and duplicate gravity gear extension handles.
image

**Pull request merged**
