### PR TITLE
refactor: port SD to full react-based instrument

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #[issue_no]

## Summary of Changes

- [x] point panel.cfg entry to template.html
- [x] port permanent data area
- [x] port logic (auto switching etc.)
~~-[ ] ensure accuracy (font sizes, layout...)~~ (later, when systems are in place)

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Logic of the screens have not been touched by this PR so we don't expect any visual changes. However, here some points that can be checked.

1. Make sure all pages are selectable and show correct/meaningful data.
2. Test ECAM ALL button (pages should cycle in a one second interval)
3. Verify auto switching behaviour when no page is selected (non exhaustive list following)
   - Deselect any active ecam page when C&D and turn on the API -> APU page should appear
   - Start the engines -> ENG page should show up
   - While taxiing, move any control surface fully and verify the F/CTL page is showing up. When releasing controls, page should switch back after 20s
  - In cruise, CRZ page should be shown
4. General observation of any possible weird behaviour. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
SD on my phone, here we come

**Review by tracernz — APPROVED** [review]

**Comment by tracernz** [comment]
Fix lints.

**Comment by dragold** [comment]
QA Tester Report 

Name: Mr.Blank#6197
Date of testing MM/DD/YYYY:01/09/2023
PR Tested: 7556
Tier of testing:1

Testing technique: tryouts
Test Instructions:
The logic of the screens has not been touched by this PR so we don't expect any visual changes. However, here some points that can be checked.
Make sure all pages are selectable and show correct/meaningful data.
Test ECAM ALL button (pages should cycle in a one-second interval)
Verify auto-switching behaviour when no page is selected (non exhaustive list following)
Deselect any active ecam page when C&D and turn on the API -> APU page should appear
Start the engines -> ENG page should show up
While taxiing, move any control surface fully and verify the F/CTL page is showing up. When releasing controls, page should switch back after 20s
In cruise, CRZ page should be shown
Ps--
General observation of any possible weird behavior.


Methodology
All as per instruction 

Negatives: NIL
Testing Results: PASS 
Conclusions: results were of normal outputs

**Comment by MicahBCode** [comment]
Why don't you port the SD directly to the MSFS Avionics Framework, instead of React?

**Comment by Saschl** [comment]
Will come eventually. First step is to get rid of the old pure JS remainders so we unblock some progress (updated build pipeline + remote displays). Port to msfs avionics will take a bit longer as I did not touch the actual pages here.

**Pull request merged**
