### PR TITLE
feat: efb power button (physical)

### PR DESCRIPTION
**Pull request by ErickSharp**
## Summary of Changes

The physical power button on the EFB now works.

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub): Erick [Z-6]#6484

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by MisterChocker** [comment]
Short question, since we have a physical power button now, can we remove the "software power button" then?

To me it looks kind of odd having a permanent visible power button on a tablet.

**Comment by ErickSharp** [comment]
> Short question, since we have a physical power button now, can we remove the "software power button" then?
> 
> To me it looks kind of odd having a permanent visible power button on a tablet's ui.

The power button is realistic to life so it may be hard for people to press it within the sim. I am not sure if maybe we should make it an option, get rid of it, or keep it.

**Comment by lolisec** [comment]
keep it or make it an option as there are tablets in real life that have the little power icon.

**Comment by lolisec** [comment]
I was thinking maybe another tab could be added to the power icon so when you press it then it'll bring up 3 options restart, sleep and shutdown would be kind of nice and make things more realistic to represent an actual tablet.

**Comment by 2hwk** [comment]
> I was thinking maybe another tab could be added to the power icon so when you press it then it'll bring up 3 options restart, sleep and shutdown would be kind of nice and make things more realistic to represent an actual tablet.

This should be its own PR, not necessary for this to progress

**Review by 2hwk — APPROVED** [review]

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5697
Tier of Testing: 1
Date: 29.08.2021

Testing Process: 
Repeatedly turning on and off / testing old method (power symbol) / testing navigation

Negatives: none
Testing Results: Passed
Conclusions: LGTM

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5697
Tier of Testing: 1
Date: 29/08/2021

Testing Process:
- Loaded in C+D at a gate at EGSS.
- Moved around the cockpit and tested turning on and off the EFB from different perspectives with physical power button.

Negatives: N/A
Testing Results: PASS 

Conclusions:

Works as described, button isn't too difficult to click from any perspective where the user would be trying to look at the EFB. Although the on screen power button may stay forever, I like that on first start the EFB can still be started by clicking the screen if not aware that the physical button now powers the device on.

No other issues noted - had a mess around with the other EFB functions, all observed to be working as before. Concerns that this may be difficult to see unless otherwise aware to check for the button so may raise a few questions once merged if removing the on screen button but otherwise LGTM.

**Comment by Samueleonard** [comment]
Quality Assurance Tester/Trainee Report

Discord: 1samueleonard1
Object of testing: (#5697 )
Tier of Testing: (1)
Date: (29/08/2021)

Testing Process: 
. loaded in c+d
. pressed the button repeatedly lol - it behaved as expected
. tested different angles/zoom - clickspot works from other angles

Negatives: n/a
Testing Results: (Passed)

Conclusions: it works, nice addition
Media: n/a

**Comment by Benjozork** [comment]
> if removing the on screen button but otherwise LGTM.

I don't get what this means, is it removed or not ? Not able to test myself at the moment.

**Comment by Benjozork** [comment]
@NUTTTTTTTT

**Comment by NUTTTTTTTT** [comment]
> > if removing the on screen button but otherwise LGTM.
> 
> I don't get what this means, is it removed or not ? Not able to test myself at the moment.

The on-screen power button isn't currently removed but physical button works fine just the same, understood the intention would be to eventually remove the on-screen power button in favor of the physical. :)

**Comment by Benjozork** [comment]
I don't think we should remove it

**Comment by Benjozork** [comment]
@ErickSharp Please fix the lint

**Pull request merged**
