### PR TITLE
fix: upper ECAM showing engineering mode overlay

### PR DESCRIPTION
**Pull request by davidwalschots**
## Summary of Changes
When developing the a32nx in combination with WebUI-DevKit for debugging purposes, the upper ECAM often showed the engineering mode overlay instead of the normal view. Whenever this happened, there were many errors in the console stating an `update` function couldn't be found on the `eicas-common-display`.

I traced this issue to the loading of scripts using the `import-script` attribute. Scripts by default are loaded asynchronously, meaning the declaration order isn't the loading order. In practice, usually this doesn't lead to problems because the file system and browser cache provides files at a quick enough rate for the order to be respected in most cases. However, as WebUI-DevKit has cache-busting code which removes caching altogether, the issue was more likely visible with it. The issue did also affect regular users of the a32nx, albeit odds of running into the issue were much smaller.

The various ECAM templates and scripts depend on the `EICASTemplateElement` class, which is declared in `A32NX_BaseAirliners.js`. I've now configured the loading such that it will always load that file first, before loading the ECAM templates.

Loading the `NXDataStore.js` twice also caused errors, which I resolved by removing one of the imports.

## Additional context

Discord username (if different from GitHub): SjotgunSjonnie#9623

## Testing instructions

Test the ECAM displays function as expected.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by cianwhite** [comment]
Category: QA Tester
Name: Cian#3596
Date of testing: 12/01/2021
Version of the sim: 11.12.30.0
PR Tested: #2989 
Object of test: Test ECAM changes

Testing technique: Loaded in C+D and mid-air with multiple different tests to see if the ECAM works as expected.

1. Test if the ECAM automatically switches - Loaded in C+D at EGKK and start and pushed back as expected, the APU page showed up automatically when you start it and the ECAM updates to the give you the memo during taxi. 

2. On the ground I tested multiple ECAM messages, no functionality seems to be lost. I deliberately left things like TCAS/PWS off and got the right messages appearing. All the switching appears along with everything implemented in the current dev. I also got take-off warnings as expected for not having flaps on TO Flaps. 

3. On my climb to up to cruise I turned anti-ice on and the ECAM told me it was on as hoped. Once I reached my cruise altitude, I turned off ENG Master No.2 and the ECAM immediately recognised this and gave me a memo. On reignition, the memo disappeared and everything was back to normal.

4. Following this, I tested an airborne start on an approach to EGKK 26R, everything worked as expected, I was able to change ECAM modes and all the messages that I expected came up.

5. Looking for anything that could upset the changes, I saved mid air at my cruise level. I reloaded and the page was still in CRUISE and once more everything worked as anticipated. 

Issues (If Any): None 
Overall Rating: Good
Conclusions of the testing: Everything in the ECAM still works as in the current dev, testing multiple memos and messages.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919
Date of testing: 
Version of the sim: 1.12.13.0
PR Tested: #2989 
Object of test: ECAM

Testing technique: Tried out
Steps you've made to test the Pull Request:
1. Spawned in C&D at kiad
2. Flew to kord 
3. Monitored ECAM whole flight while testing functionality. 
4. Landed safely 

Flight notes (If required):
Packs were showing fault the whole flight
Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Ecam works fine looks good to me keep up the good work.

**Review by tyler58546 — APPROVED** [review]
LGTM

**Pull request merged**
