### PR TITLE
Loading screen tips

### PR DESCRIPTION
**Pull request by notleks2411**
Fixes #[issue_no]

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by notleks2411** [comment]
IGNORE WRONG REPO!!!!!!!

**Comment by notleks2411** [comment]
Sorry, I did the wrong thing. I'm just experimenting and did not mean to do this. Please disregard anything I have done here.

**Comment by tracernz** [comment]
They seem good tbh.

**Comment by Benjozork** [comment]
I'd drop the last one. Don't want any awkwardness if this ever ends up not being true anymore, imo.

**Comment by notleks2411** [comment]
> I'd drop the last one. Don't want any awkwardness if this ever ends up not being true anymore, imo.

Yeah good point. Don't ask me how I accidentally did what I did, it was a long day for me. I'm just winging most of it, trying to work it all out on my own, haha.

**Pull request closed without merging**
