### PR TITLE
[CDU] Altitude Constraints Logic recode 

### LINKED ISSUE #938: [BUG] ALT CSTR
**Mod Version**

Master latest version 

**Describe the bug**

The altitude on the PFD is wrong when set an ALT CSTR i.e. set an ALT CSTR at FL110 and when you set it at 11000 should appear in Cyan and if you set it less than the ALT CSTR it should appear FL110 but in magenta. 

**To Reproduce**

1. add an ALT CSTR on a waypoint 
2. set the ALT on the FCU same altitude as the ALT CSTR 
3. set the ALT on the FCU lower than the ALT CSTR

**Expected behavior**

if the ALT on the FCU is set lower than the ALT CSTR on the PFD it should appear on the PFD FL110 in magenta. 

**Actual behavior**

it shows the wrong ALT CSTR in magenta 

**References**

Desktop Screenshot 2020 09 24 - 16 25 46 51
Desktop Screenshot 2020 09 24 - 16 23 44 56

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
it is always been there 

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #938

## Summary of Changes

- Reworked Ascent, Cruise and Descent Logic
   - Ascent follows only `AT` or `AT OR BELOW` constraints
   - Cruise ignores all constraints
   - Descent follows only `AT` or `AT OR ABOVE` constraints

- Flight Phase as well as active waypoint changes trigger constraint updates. Changes to Constraints on VERT REF page are also followed with constraint update.

- The current flight phase change detection when changing from cruise to descent is very slow. Takes about 1500ft until phase change get's recognized. This can lead to constraints are not being followed correctly.

## References

image
image
image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by tareksabet** [comment]
is there any possibilities this PR is related to issue #938 or not related ?

**Comment by MisterChocker** [comment]
> is there any possibilities this PR is related to issue #938 or not related ?

This implements correct (real life) logic. If your problem is a related to wrong constraint logic, then yes.

**Comment by wpine215** [comment]
Still appears to be treating SID waypoint altitude predictions as altitude restrictions - both on the ND (shows up as constraint in magenta) and on MCDU - shows up with a "+" when predictions should not include any + or - symbols:

FlightSimulator_zGJvAVs7qd

On STAR/approach, the ND correctly only displays the constraints for the waypoints that have them, but the MCDU still incorrectly shows the "-" symbol next to predictions.

FlightSimulator_EzQ0JpzCXT

**Comment by wpine215** [comment]
Treating the altitude prediction of 20,350 feet at waypoint "JLI" as a constraint, even though it's not (cross check PFD and MCDU):
image

**Comment by wpine215** [comment]
Seems to be ignoring the 13,000 foot altitude restriction at SEAVU.

image

**Comment by MisterChocker** [comment]
> Treating the altitude prediction of 20,350 feet at waypoint "JLI" as a constraint, even though it's not (cross check PFD and MCDU):

Well no Idea how to filter false constraints then.

**Comment by MisterChocker** [comment]
> Seems to be ignoring the 13,000 foot altitude restriction at SEAVU.
> 

Yes because flight phase is still cruise, takes 1500ft to change to descent phase.

**Comment by beheh** [comment]
> Yes because flight phase is still cruise, takes 1500ft to change to descent phase.

So that's the FMGC flight phase logic that needs to be fixed at some point - it should be descent as soon as you start DES or OPEN DES leaving the cruise flight level.

**Comment by wpine215** [comment]
> 
> 
> > Treating the altitude prediction of 20,350 feet at waypoint "JLI" as a constraint, even though it's not (cross check PFD and MCDU):
> 
> Well no Idea how to filter false constraints then.

According to pilots in the discord, the finest-grain constraints are only multiples of 100 feet (e.g. 3300 feet on approaches, for example), so we can rule out anything that doesn't end with -00 to begin with.

**Comment by wpine215** [comment]
> 
> 
> > Yes because flight phase is still cruise, takes 1500ft to change to descent phase.
> 
> So that's the FMGC flight phase logic that needs to be fixed at some point - it should be descent as soon as you start DES or OPEN DES leaving the cruise flight level.

Will this be addressed in this PR, or a separate/future one?

**Comment by MisterChocker** [comment]
> > > Treating the altitude prediction of 20,350 feet at waypoint "JLI" as a constraint, even though it's not (cross check PFD and MCDU):
> > 
> > 
> > Well no Idea how to filter false constraints then.
> 
> According to pilots in the discord, the finest-grain constraints are only multiples of 100 feet (e.g. 3300 feet on approaches, for example), so we can rule out anything that doesn't end with -00 to begin with.

need to test this.



> > > Yes because flight phase is still cruise, takes 1500ft to change to descent phase.
> > 
> > 
> > So that's the FMGC flight phase logic that needs to be fixed at some point - it should be descent as soon as you start DES or OPEN DES leaving the cruise flight level.
> 
> Will this be addressed in this PR, or a separate/future one?

No, I'd like to address this in another pr.

**Comment by CaptainR3X** [comment]
Category: QA Tester
Name: GustavRex #4347
Date of testing: Current date 28/11/2020
Version of the sim: 1.11.6.0
PR Tested: #2092
Object of test: Test Altitude Constraints Logic recode

Testing technique: Flight; EKCH-ESGG
Steps you've made to test the Pull Request:
1. C/D EKCH, flight programming, P/S and takeoff
2. Climb, cruise - manually trying to put the AP off by adding constraints (lower than crz alt)
3. Arrival programming, manually programming STAR and constraints (otherwise the MCDU will display at/below)
4. Approach and landing at ESGG

Flight notes (If required): Online, VatSim

Issues (If Any): One constraint was not respected on descent
Overall Rating: Good, might need a bit of tweaking if the issue I had is general
Conclusions of the testing: I was not able to test the constraints during takeoff and climb since MCDU automatically programs constraints on SID as at/abv. During crz, AP ignored constraints of lower alt even when i tryed to mess with the contraints. AP respected all constraints except one on descent and approach, I do not know the reason why, but it flew straight through it (see attatched pic, and yes I know I'm overspeeding ;)). AP also respected constraints on an extented ILS approach nicely.  
image
image
image
image

**Comment by MisterChocker** [comment]
@CaptainR3X In the first picture, do you know the flight phase? looks like it was still in cruise.

**Comment by CaptainR3X** [comment]
Hmm yeah I think now that you mention it, it was in cruise but not sure however looking at the fact that the decel is on top of that wpt I reckon that it was in cruise as well. Normally when I test the alt constraints I activate app phase at FL150 but must have forgot to confirm it in the MCDU.

**Comment by CaptainR3X** [comment]
But yeah that would explain why it went straight through it. If that is the case, then there were no 
issues with it and LGTM

**Comment by MisterChocker** [comment]
It must have been, there is no other explanation, because it would have targeted the other constraints.
Sure.

**Comment by CaptainR3X** [comment]
Btw, do you know if anyone is working on the constraints being flipped from at/abv to at/below on approach and the other way around during climb?

**Comment by MisterChocker** [comment]
> Btw, do you know if anyone is working on the constraints being flipped from at/abv to at/below on approach/arrival and the other way around during climb?

you mean for entry? already done. You can now insert + for above and - for below.
I believe 5000 for level at 5000 is currently not supported as well as between -12000/+8000

**Comment by CaptainR3X** [comment]
I was unable to change the default constraints from -XXXX to +XXXX on approach the other day. If a constraint says -8000 and you try to change it to +8000 or +9000 it'll just go -8000 or -9000. Been busy the past two days or so, has it been fixed within there? That was the only reason why i manually program the STAR

**Comment by MisterChocker** [comment]
Actually this should be possible by now.

**Comment by CaptainR3X** [comment]
That'd be awesome, it's kinda long programming manually, the waypoints get inserted in the wrong places and switched around - it's just a mess. I'll try it tomorrow when it test this PR again - hopefully it works!

**Comment by CaptainR3X** [comment]
Just tested it again, will spare you all the text. Once i got the AP working after a few restarts, the PR worked flawlessly AND the constraints can be reprogrammed now, HALLELUJAH :)

**Pull request merged**
