### PR TITLE
Fix unable to disable mach speed mode

### PR DESCRIPTION
**Pull request by lukecologne**
**Summary of Changes**

* Fixes the issue after the 1.8.3 update where after switching to mach mode it was impossible to go back to normal mode

Example: 

This was from cold and dark, but it happens when spawned on the runway as well. Latest master

With the fix

### CODE REVIEW

**Comment by tyler58546** [comment]
The button works fine for me without this fix.

**Comment by NathanInnes** [comment]
Works as intended.

**Comment by RikvanD1997** [comment]
I had this issue yesterday after getting to cruise after the FMA switched to 'MACH' mode. I was not on the latest master build though, rather one from around 5 days ago.

**Comment by jacf182** [comment]
I had the same problem with the default A320. I think it's not a problem with this mod but with the official code.

**Comment by lukecologne** [comment]
Yes, pretty sure it is, but this fixes it. @tyler58546 are you sure? I know of at least two other people who have this bug, not including the ones that are in this thread

**Comment by DominikTV** [comment]
I had this issue too after I used the "Jump to" option (was using the mod)

**Comment by lukecologne** [comment]
See updated main post for a gif

**Comment by UncleClapton** [comment]
Confirmed working

**Comment by ErikNL80** [comment]
I have tested in the latest master branch. Flying at FL280. Speed switched to Mach. Cannot get it back to knots. See the image below:
[img]https://i.postimg.cc/PJx7Pww6/Naamloos.png[/img]

**Comment by lukecologne** [comment]
See this: 
grafik
It might be intended that when it switches to mach automatically, you cannot go back to speed mode. Some A320 pilot should confirm this though

**Comment by ErikNL80** [comment]
When descending, speed changes back to knots, and then it works again... But still, I am wondering if this is correct behaviour.

**Comment by NathanInnes** [comment]
This seems to be broken again. Can't switch from Mach to speed.

**Comment by lukecologne** [comment]
On the ground? or while cruising? because the only thing I fixed was being unable to switch on the ground

**Comment by NathanInnes** [comment]
Mid flight at cruise

**Comment by DesertRick13** [comment]
I'm a 
Mach button
Mach at altitude
IAS at altitude


747 guy, not A 320, but with a similar problem. Button is broken. The workaround is to configure a button in the menu

**Comment by Benjozork** [comment]
@DesertRick13 We cannot help you with 747 problems here.

**Comment by DesertRick13** [comment]
I wasn’t looking for help, I was showing a workaround to a problem that is common to both the 747 and the A 320.
Thank you

**Pull request merged**
