### PR TITLE
feat: Upscaled external airframe decals and fixed minor external typo.

### PR DESCRIPTION
**Pull request by FoxinTale**
## Summary of Changes

Upscaled the external airframe decals to 4k resolution and fixed a spelling error, specifically "portable water" is now "potable water". I have no idea where it appears on the airframe however. Somewhere towards the rear, but since it's in 33px font, good luck finding it.

## Screenshots (if necessary)

See #3798. I'm not repeating it again.

## Additional context

Discord username (if different from GitHub):  Aubrey Jane#7563

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by Samueleonard** [comment]
Category: QA Tester
Name: 1Samueleonard1#0001
Date of testing: Current date 05/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4282
Tier of testing: 1

Changes to observe: new external decals

Testing technique: Tryout
1. loaded on runway
2. went to exterior view and looked around at decals

Flight notes: decals look very high resolution, i look forward to having more decals once the model is editable

Media: n/a

Issues: n/a that i could see

Steps to achieve the issue n/a

Overall Rating: Good

Conclusions of the testing: decals look higher resolution, lgtm

**Comment by sidnov** [comment]
> Upscaled the external airframe decals to 4k resolution and fixed a spelling error, specifically "portable water" is now "potable water". I have no idea where it appears on the airframe however. Somewhere towards the rear, but since it's in 33px font, good luck finding it.

Found it :) 
image

QA review in a bit, PR downloading 🕙

**Comment by sidnov** [comment]
Category: Contributor/QA Tester
Name: sidnov#8337
Date of testing: 05/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4282
Tier of testing: 1

### Changes to observe: Decals upscaling

###  Steps you've made to test the Pull Request:
1. Spawned on runway
2. Checked decals around the airframe using drone cam

Issues (If Any): Arrow looks chopped off, can it be fixed given the model-decal situation?
image

Media:
image
image
image

Overall Rating: Good
Conclusions of the testing: Visible changes in case of jagged letters of "DANGER" and overall upscaling is visible. Good to go!

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 5.4.2021
Version of the sim: 1.14.6.0
PR Tested: #4282
Tier of testing: 1
Changes to observe: Decals upscale


Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned at LSZH
2. Flew around the Aircraft with the drone

Media:
Microsoft Flight Simulator Screenshot 2021 04 05 - 16 54 03 22
Microsoft Flight Simulator Screenshot 2021 04 05 - 16 54 16 86
Microsoft Flight Simulator Screenshot 2021 04 05 - 16 55 06 51
Microsoft Flight Simulator Screenshot 2021 04 05 - 16 56 16 89
Microsoft Flight Simulator Screenshot 2021 04 05 - 16 56 35 99


Issues (If Any):
- As already mentioned, the arrow looks a bit cut off on the right side
- The markings around the static port look a bit chopped at the edges

Overall Rating: Good
Conclusions of the testing: If the small issues are not fixable, its very good. Otherwise all Decals look very crisp now

**Comment by FoxinTale** [comment]
In the original texture, the cut off arrows are fully there. Seems to be model / UV oddities here.

**Pull request merged**
