### PR TITLE
MCDU Improvements

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Horizontal slew arrows now appear in the correct location
* Vertical slew arrows have been added on pages that can be scrolled
* The "F-PLN" title has been removed from the flight plan page
* The flight plan page now shows the flight number in the upper right corner
* The flight plan page now shows "TMPY" in the top line when displaying the temporary flight plan
* The "FROM" indicator on the flight plan page now is now in the top line

#### Before
image

#### After
image

#### Before
image

#### After
image

## References

Honeywell FMS manual

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Ensure the following modified pages work as described in the summary:
 * INIT A
 * INIT B
 * WIND/TEMP
 * F-PLN
 * DEPARTURE
 * ARRIVAL
 * DIR TO
 * AOC MSG DISPLAY
 * AOC SENT MSG

Please let me know if there are any other pages that require slew arrows.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by tjburni** [comment]
Category: QA Tester
Name:[Z+1]tjburni#0409
Date of testing: Current date 05.1.2021
Version of the sim: 1.12.13
PR Tested: #2877
Object of test: Mcdu improvements

Testing technique:full C&D
Steps you've made to test the Pull Request:
1. started C&D at Gate
2. started plane
3. programmed MCDU 
4. observed the in the PR described MCDU Pages
and looked for bugs
5.

Flight notes (If required):

Issues (If Any): none
Overall Rating: Good
Conclusions of the testing: Looks Good. I had no Bugs. Thanks for these Improments!

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 05.01.2021
Version of the sim: 1.12.13.0
PR Tested: #2877
Object of test: MCDU page improvements

Testing technique:
Steps you've made to test the Pull Request:

1. Spawned on runway powered up with flight plan
2. Checked the listed improvements
3. Crosschecked with Honeywell_R1A_FMS_Pilot_Guide_Jan._2009.pdf

Flight notes (If required):

Issues (If Any): -
Overall Rating: LGTM
Conclusions of the testing: Works as expected. Just a typo in your PR text @tyler58546: Point 4 Callsign is in the uper **right** corner

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 5.1.2021
Version of the sim: 1.12.13.0
PR Tested: #2877
Object of test: MCDU Improvements

Testing technique: Try out
Steps you've made to test the Pull Request:
1. Spawned C&D at LSZH Gate A44
2. Started up the Aircraft
3. tested through all MCDU pages


Flight notes (If required): none

Issues (If Any): INIT B has two arrows
Overall Rating: To be improved
Conclusions of the testing: Described Issue, otherwise works as described
Microsoft Flight Simulator Screenshot 2021 01 05 - 21 41 08 91

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 06/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2877
Object of test: MCDU

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Load up C&D at LFPG
2. Load Flight plan over Simbrief
3. Checked MCDU Page with focus on bugfix -> Double arrows on INIT B


Issues:  
- On departure page the arrow to the left is overlapping the airport a bit:
grafik

Overall Rating: To be improved
Conclusions of the testing: The Arrows on the INIT B page are correct now, but I found a new little bug as described above.

**Comment by tyler58546** [comment]
Thank you for the feedback, @Noxleee. I have adjusted the position of the arrows so they are no longer overlapping.
image

**Comment by Noxleee** [comment]
> 
> 
> Category: QA Tester
> Name: Noxlee #7727
> Date of testing: Current date 06/01/2021
> Version of the sim: 1.12.13.0
> PR Tested: #2877
> Object of test: MCDU
> 
> Testing technique: Description of how you tested the Pull Request
> Steps you've made to test the Pull Request:
> 
>     1. Load up C&D at LFPG
> 
>     2. Load Flight plan over Simbrief
> 
>     3. Checked MCDU Page with focus on bugfix -> Double arrows on INIT B
> 
> 
> Issues:
> 
>     * On departure page the arrow to the left is overlapping the airport a bit:
> 
> 
> Overall Rating: To be improved
> Conclusions of the testing: The Arrows on the INIT B page are correct now, but I found a new little bug as described above.



> 
> 
> Thank you for the feedback, @Noxleee. I have adjusted the position of the arrows so they are no longer overlapping.


Quickly tested the new Version. Issue is fixed now!

Overall Rating: Good
Conclusions of the testing: LGTM!

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
