### PR TITLE
[PFD] Improve text readability

### LINKED ISSUE #1813: [BUG] PFD tapes background too bright
**Mod Version**

DEVELOPMENT
built: 2020-11-08T18:02:05+00:00
ref: refs/heads/master
sha: 9ecc85c0d81df306c5b66b2a29bc94aa9ab56ea1
actor: lukecologne
event_name: push 

**Describe the bug**

Background on PFD tapes (SPEED, ALTITUDE, V/S, HEADING) are too bright, causes information on it nearly unreadable.

**To Reproduce**

1. Spawn at gate, ideally evening / night
2. Power on the FPD. set brightness 50 - 100%
3. Observe all tapes / notice effort needed to recognize numbers

**Expected behavior**

Contrast between text and background on tapes should be higher, backgroud should be much darker.

**Actual behavior**

To bright background of tapes on PFD.

**References**

Screenshot from A32nx

Snip from YT video of A320neo cockpit
01REF

**Additional context**

Was this working before/when did the issue start occurring?
Not sure.

Is this a problem in the vanilla unmodded game?
Not sure.

Discord username (if different from GitHub):
SteveX77 [Z+0!]#1407

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #1813

## Summary of Changes

- Improved text readability by adjusting contrast

## Screenshots (if necessary)

IRL colors and contrast does not change significantly when changing brightness, however in the sim it does.

| Captain PFD (before) | FOs PFD (after) |
| ----- | ----- |
|image|image|
|image|image|
|image|image|
|image|image|
|image|image|
|image|image|
|image|image|

This is a side by side comparison without any glare/bloom effect.
(Left after / right before)
image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by stevex77** [comment]
**Category:** QA Tester
**Name:** SteveX77 [Z+0!]#1407
**Date of testing:** 11/13/2020
**Version of the sim:** 1.10.11.0
**PR Tested:** #1896
**Object of test:** [PFD] Improve text readibility

**Testing technique:**
Review PFD readability under various light conditions and various brightness settings.
Content on AIRSPEED, ALT, V/S and HDG tapes should be readable in any case.

**Steps you've made to test the Pull Request:**
1. Spawn at away from any external lights (to be able to simulate dark external conditions).
2. Power on the aircraft.
3. Turn off all inside ambient lighting
3. Change time of day (dark night, evening, noon), go through brightness setting <10%, 100%> and review PFD readability.

**Notes:**
In most cases contrast on PDF tapes is good / acceptable.
The worst case is dark night and 100% brightness - still very poor contrast, but when brightness reduced to 50%, it's good enough.

**Issues (If Any):**
Exterme / marginal case - dark night + brightness set to 100%.

**Overall Rating:** GOOD
**Conclusions of the testing:** Better than before >>> LGTM now

**Comment by Benjozork** [comment]
@stevex77 FYI you need to wait until the PR has "Ready to Test" or "Testing started" to submit reports.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
Small enough fix,

**Comment by stevex77** [comment]
> @stevex77 FYI you need to wait until the PR has "Ready to Test" or "Testing started" to submit reports. This one should be fine

OK, thanks for clarification. Will do so next time.
This one was small and I'm OP of the related issue, so I knew the context enough.

**Pull request merged**
