### PR TITLE
feat: brake gauge visual improvements

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Changed brake gauge font to Poppins Medium (Futura alternative)
* Adjusted position and size of text on brake gauge
* Improved brake gauge markings

## Screenshots (if necessary)

Before:
image
After:
image

## References

image
image

## Testing instructions

Make sure the changes are accurate.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by hotshotp — APPROVED** [review]
LGTM

**Comment by sidnov** [comment]
@tyler58546 looks like the changes were not pushed 
image

**Comment by tyler58546** [comment]
> @tyler58546 looks like the changes were not pushed
Oops, forgot to commit the font.

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 23.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3672
Tier of testing: 1
Changes to observe: Brake gauge font
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. (Image1)
3.) Released parking brake (Image2)
4.) Turned on Engines

Media:


Image1


Image2

Font looks nice.

Issues: 

- The C is a little more open in the references
- There needs to be a little more space arround the "x", PSIx1000 vs. PSI x 1000

Issues (not related to this PR i think):

- Gauge behaves like monitor, even if this is a analog device
- Gauges switch from 2000 PSI to 0 when releasing the parking brake
- Braking will not move the dails

Overall Rating: Good

Conclusions of the testing: Maybe minor fixes.

Hope this helps :-)

**Comment by kberg93** [comment]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/23/2021
Version of the sim: 1.13.16.0
PR Tested: #3672
Tier of testing: 1
Changes to observe:
Brake gauge visual improvements.

Testing technique: Visual check.

Steps you've made to test the Pull Request: 
1. Spawned at gate.
2. Visual look at the brake gauge.
3. Release and apply parking brake.

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
oCjAZgttMa

Issues (If Any): As decribed in review above the C in ACCU seems a bit wrong, and same with that "X", but my addition is shouldnt the "PSIx1000" be more greyish reffering to the real one (check 2 on sc above).

Overall Rating: To be improved.

Conclusions of the testing: Would be nice to have smoother movement of the gauges when pressure gets applied or released maybe but thats probably for some other PR. :)

**Comment by crocket63** [comment]
I'm close to send first PR with brakes information really working. On previous gauges code I just had to change the simvar names to have the real brake pressures : is this will always be the same simvar mechanism ?  
Also one question, when power is off should this gauge still be visible? Not sure it was the case before.
Thanks!

**Comment by Benjozork** [comment]
@tyler58546 is this still being worked on ?

**Comment by tyler58546** [comment]
> is this still being worked on ?

Yes, it is now.

> The C is a little more open in the references

Unfortunately, this is because the real font, Futura cannot be used as it is not free. I am using a similar free font that is very close, but obviously not perfect.

> There needs to be a little more space arround the "x", PSIx1000 vs. PSI x 1000

Fixed.
image

**Comment by marcman86** [comment]
Please also add a space before the x.

PSI x 1000

PSI is the unit, x means 'times' and 1000 is the factor. So when the dail shows 2 it means 2000PSI.

**Comment by tyler58546** [comment]
> Please also add a space before the x.
> 
> PSI x 1000
> 
> PSI is the unit, x means 'times' and 1000 is the factor. So when the dail shows 2 it means 2000PSI.

I understand this, but there is no space before the x in the reference images.
image

**Comment by marcman86** [comment]
I think there is a space, but i agree that it is slimmer in the references.

**Comment by St54Kevin** [comment]
By looking at the reference the scale of each side changes above 2000psi. Should/can this be changed?

**Comment by Matse08** [comment]
Category: QA Tester
Name: Matse#7454
Date of testing: 21.03.21
Version of the sim: 1.14.5.0
PR Tested: #3672
Tier of testing: 1
Changes to observe:
Brake gauge visual improvements


Testing technique: Try-out
Steps you've made to test the Pull Request:
1. Spawned cold and dark
2. Turned on BAT 
3. Turn park brake on/off


Media: 
Microsoft Flight Simulator 21 03 2021 17_48_28
Microsoft Flight Simulator 21 03 2021 17_48_23


Issues (If Any): N/A
Steps to achieve the issue:


Overall Rating: nice job
Conclusions of the testing: Nice one

**Comment by Matse08** [comment]
> Category: QA Tester
> Name: Kberg#666
> Date of testing: Current date 02/23/2021
> Version of the sim: 1.13.16.0
> PR Tested: #3672
> Tier of testing: 1
> Changes to observe:
> Brake gauge visual improvements.
> 
> Testing technique: Visual check.
> 
> Steps you've made to test the Pull Request:
> 
> 1. Spawned at gate.
> 2. Visual look at the brake gauge.
> 3. Release and apply parking brake.
> 
> Flight notes (When done a full flight):
> 
> Media: Insert screenshots, recordings, or anything relevant to the review here.
> oCjAZgttMa
> 
> Issues (If Any): As decribed in review above the C in ACCU seems a bit wrong, and same with that "X", but my addition is shouldnt the "PSIx1000" be more greyish reffering to the real one (check 2 on sc above).
> 
> Overall Rating: To be improved.
> 
> Conclusions of the testing: Would be nice to have smoother movement of the gauges when pressure gets applied or released maybe but thats probably for some other PR. :)

Bra jobba trønder

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 22/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3672 
Tier of testing: 1

Changes to observe:
brake gauge visual improvements

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. Spawned C&D
2. Checked
3. Followed PR instructions

Flight notes (When done a full flight):
N/A

Media:
Microsoft Flight Simulator Screenshot 2021 03 22 - 13 35 34 21
Microsoft Flight Simulator Screenshot 2021 03 22 - 13 39 37 81


Issues (If Any): Write any issues
N/A
Steps to achieve the issue:
N/A

Overall Rating: Good
Conclusions of the testing: GTG

**Pull request closed without merging**
