### PR TITLE
feat: added more events for better interface to FCU

### PR DESCRIPTION
**Pull request by aguther**
## Summary of Changes
This PR introduces a new set of custom events to control the FCU:
- A32NX.FCU_AP_DISCONNECT_PUSH
- A32NX.FCU_ATHR_PUSH
- A32NX.FCU_ATHR_DISCONNECT_PUSH
- A32NX.FCU_HDG_INC
- A32NX.FCU_HDG_DEC
- A32NX.FCU_HDG_SET
- A32NX.FCU_ALT_INC
- A32NX.FCU_ALT_DEC
- A32NX.FCU_ALT_SET
- A32NX.FCU_VS_INC
- A32NX.FCU_VS_DEC
- A32NX.FCU_VS_SET

## Testing instructions

- Test all events according to documentation if they work as intended (read the documentation in docs), possible tools are for example SPAD.neXt or FSUIPC
- Test SPD, HDG and VS events also when modes are switched (SPEED/MACH or HDG/TRK + VS/FPA)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by frankkopp** [comment]
Category: QA Tester
Name: Cdr_Maverick#6475
Date of testing: Current date 09/05/2021
Version of the sim: 1.15.10
PR Tested: #4749
Tier of testing: 2

Changes to observe:
Test all events according to documentation if they work as intended (read the documentation in docs), possible tools are for example SPAD.neXt or FSUIPC
Test SPD, HDG and VS events also when modes are switched (SPEED/MACH or HDG/TRK + VS/FPA)

Testing technique: Test Flight starting on runway using SPAD to map events to Stream Deck for testing

Steps you've made to test the Pull Request:
1. Started on runway (simple flight plan) - take off to 5000 - then tested
2. Setup all events on Stream Deck with button push as trigger - watched cockpit
3. Tested variations and existing events (SIMCONNECT, MSFS, etc.) to make sure no changes to previous functionality

Tested:
01. A32NX.FCU_AP_DISCONNECT_PUSH: works (UI also still works, AP_MASTER also still works)
02. A32NX.FCU_ATHR_PUSH: works (UI also still works)
03. A32NX.FCU_ATHR_DISCONNECT_PUSH: works (does not turn ATHR back on as intended)
04. A32NX.FCU_HDG_INC: works (SIMCONNECT also still works)
05. A32NX.FCU_HDG_DEC: works (SIMCONNECT also still works)
06. A32NX.FCU_HDG_SET: works
07. A32NX.FCU_ALT_INC: works (SIMCONNECT never really worked as it does not use VAR:3)
08. A32NX.FCU_ALT_DEC: works (SIMCONNECT never really worked as it does not use VAR:3)
09. A32NX.FCU_ALT_SET: works (ALT INC/DEC always uses LVAR:XMLVAR_AUTOPILOT_ALTITUDE_INCREMENT as steps size. Event parameter is not used. Enhancement: use parameter if not 0 (to allow different buttons for 100 and 1000)
10. A32NX.FCU_VS_INC: works (also SIMCONNECT and UI still work)
11. A32NX.FCU_VS_DEC: works (also SIMCONNECT and UI still work)
12. A32NX.FCU_VS_SET: works - FCU does not display if VS is not a multiple of 100 -> 1999 will be 1900

TRK/FPA mode: same results. (remark: FPA is devided by 10 -> 30=3.0, 3=0.3)

Media: Insert screenshots, recordings, or anything relevant to the review here.
image

Issues:
ALT INC/DEC always uses LVAR:XMLVAR_AUTOPILOT_ALTITUDE_INCREMENT as steps size. Event parameter is not used.
Enhancement: use parameter if not 0 (to allow different buttons for 100 and 1000)
A32NX.FCU_VS_SET - FCU does not display if VS is not a multiple of 100 -> 1999 will be 1900

Overall Rating: **Good** - mentioned issues are not directly related to this PR

Conclusions of the testing: 
Enhancement: for ALT INC/DEC use parameter if not 0 (to allow different buttons for 100 and 1000)

**Review by MisterChocker — COMMENTED** [review]
I've checked the code so far but even tho I've seen the changes I am unsure whether the changes made by #4687 are still respected

**Comment by aguther** [comment]
> I've checked the code so far but even tho I've seen the changes I am unsure whether the changes made by #4687 are still respected

Those events have been added as well. To be sure it would be good if you test it.

**Comment by aguther** [comment]
> Category: QA Tester
> 
> Name: Cdr_Maverick#6475
> 
> Date of testing: Current date 09/05/2021
> 
> Version of the sim: 1.15.10
> 
> PR Tested: #4749
> 
> Tier of testing: 2
> 
> 
> 
> Changes to observe:
> 
> Test all events according to documentation if they work as intended (read the documentation in docs), possible tools are for example SPAD.neXt or FSUIPC
> 
> Test SPD, HDG and VS events also when modes are switched (SPEED/MACH or HDG/TRK + VS/FPA)
> 
> 
> 
> Testing technique: Test Flight starting on runway using SPAD to map events to Stream Deck for testing
> 
> 
> 
> Steps you've made to test the Pull Request:
> 
> 1. Started on runway (simple flight plan) - take off to 5000 - then tested
> 
> 2. Setup all events on Stream Deck with button push as trigger - watched cockpit
> 
> 3. Tested variations and existing events (SIMCONNECT, MSFS, etc.) to make sure no changes to previous functionality
> 
> 
> 
> Tested:
> 
> 01. A32NX.FCU_AP_DISCONNECT_PUSH: works (UI also still works, AP_MASTER also still works)
> 
> 02. A32NX.FCU_ATHR_PUSH: works (UI also still works)
> 
> 03. A32NX.FCU_ATHR_DISCONNECT_PUSH: works (does not turn ATHR back on as intended)
> 
> 04. A32NX.FCU_HDG_INC: works (SIMCONNECT also still works)
> 
> 05. A32NX.FCU_HDG_DEC: works (SIMCONNECT also still works)
> 
> 06. A32NX.FCU_HDG_SET: works
> 
> 07. A32NX.FCU_ALT_INC: works (SIMCONNECT never really worked as it does not use VAR:3)
> 
> 08. A32NX.FCU_ALT_DEC: works (SIMCONNECT never really worked as it does not use VAR:3)
> 
> 09. A32NX.FCU_ALT_SET: works (ALT INC/DEC always uses LVAR:XMLVAR_AUTOPILOT_ALTITUDE_INCREMENT as steps size. Event parameter is not used. Enhancement: use parameter if not 0 (to allow different buttons for 100 and 1000)
> 
> 10. A32NX.FCU_VS_INC: works (also SIMCONNECT and UI still work)
> 
> 11. A32NX.FCU_VS_DEC: works (also SIMCONNECT and UI still work)
> 
> 12. A32NX.FCU_VS_SET: works - FCU does not display if VS is not a multiple of 100 -> 1999 will be 1900
> 
> 
> 
> TRK/FPA mode: same results. (remark: FPA is devided by 10 -> 30=3.0, 3=0.3)
> 
> 
> 
> Media: Insert screenshots, recordings, or anything relevant to the review here.
> 
> image
> 
> 
> 
> Issues:
> 
> ALT INC/DEC always uses LVAR:XMLVAR_AUTOPILOT_ALTITUDE_INCREMENT as steps size. Event parameter is not used.
> 
> Enhancement: use parameter if not 0 (to allow different buttons for 100 and 1000)
> 
> A32NX.FCU_VS_SET - FCU does not display if VS is not a multiple of 100 -> 1999 will be 1900
> 
> 
> 
> Overall Rating: **Good** - mentioned issues are not directly related to this PR
> 
> 
> 
> Conclusions of the testing: 
> 
> Enhancement: for ALT INC/DEC use parameter if not 0 (to allow different buttons for 100 and 1000)
> 
> 
> 
> 

That's a good idea with the SET event for altitude. I will change it so if parameter is 0, !100, !1000 it will take the other variable, 100 then 100 or 1000 then 1000.

For the VS it is intentional that it rounds it. Same for Mach, heading etc. The FCU only supports multiple of 100 for V/S.

**Comment by frankkopp** [comment]
Retested ALT INC/DEC events: 

Tested ALT INC/DEC with parameter 0, 100, 1000 and 750:
0 uses the LVAR:XMLVAR_AUTOPILOT_ALTITUDE_INCREMENT
100 uses 100 as step size
1000 uses 1000
750 uses LVAR:XMLVAR_AUTOPILOT_ALTITUDE_INCREMENT

Question: if the current value is in between x.000 - say 4.500 - should the 1.000 step increase to 5.000 or 5.500?

**Comment by aguther** [comment]
> Retested ALT INC/DEC events:
> 
> Tested ALT INC/DEC with parameter 0, 100, 1000 and 750:
> 0 uses the LVAR:XMLVAR_AUTOPILOT_ALTITUDE_INCREMENT
> 100 uses 100 as step size
> 1000 uses 1000
> 750 uses LVAR:XMLVAR_AUTOPILOT_ALTITUDE_INCREMENT
> 
> Question: if the current value is in between x.000 - say 4.500 - should the 1.000 step increase to 5.000 or 5.500?

It should step to the next increment 1000, in that case 5000. So behavior is correct.

**Review by Saschl — APPROVED** [review]

**Review by MisterChocker — APPROVED** [review]
LGTM

**Pull request merged**
