### PR TITLE
feat(mcdu): Progress Page line 5R only shows GPS Primary when it is available

### LINKED ISSUE #4328: MCDU: Prog Page should only show GPS primary when available
**Is your feature request related to a problem? Please describe.**

The progress page always displays GPS Primary, even when it isn't available.

**Describe the feature you'd like to see implemented**

This should only be displayed when the navigation mode is GPS/IRS (i.e. the ADIRS is fully aligned). 

**References**

Honeywell Step 1A manual, prog page chapter, section on line 5R

**Additional context**

Discord username (if different from GitHub): NONAmr2433 #8777

### PR DESCRIPTION
**Pull request by Username23-23**
Fixes #4328 

## Summary of Changes

When the navigation mode is not GPS Primary (i.e. ADIRS is not fully aligned), line 5R of the progress page displays nothing. When it is (i.e. ADIRS is fully aligned), "GPS PRIMARY" is shown in green. 

## Screenshots (if necessary)

ADIRS not aligned:
Screenshot 2021-04-06 205747
Aligned (Line 5R shows the same thing as before this PR):
Screenshot 2021-04-06 205831

## References

Step 1A manual prog page chapter
Screenshot 2021-04-06 211441

## Additional context

Discord username (if different from GitHub): NONAmr2433#8777

## Testing instructions

- When spawning in C&D, line 5R of the progress page shouldn't say GPS PRIMARY until the ADIRS is fully aligned
- It should disappear with the GPS PRIMARY LOST scratchpad message and appear with the GPS Primary message

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by beheh — APPROVED** [review]

**Comment by tracernz** [comment]
I wonder what the accuracy field should display before ADIRS are aligned.

**Comment by TheSquirtingPantin** [comment]
Hello All, 

Found this document online. Could be used for future reference: 
[](https://hsi.arc.nasa.gov/flightcognition/download/appendix/A320/7_A320_LossDegradationofGPS%20.pdf)

**Comment by Username23-23** [comment]
> I wonder what the accuracy field should display before ADIRS are aligned.

The manual doesn’t specify, but maybe we could ask an IRL pilot.

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 08/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4329 
Tier of testing: 1
Changes to observe: PROG page GPS primary

**Steps you've made to test the Pull Request:**
1. Loaded C&D
2. Checked PROG page with IRS unaligned
3. Checked PROG page with IRS aligned

**Media:**

**Issues (If Any):** 
- Im experiencing this bug when selecting 1L - FMGC on the MCDU Menu page, selecting the pages with its button works
image


**Conclusions of the testing:** PR feature does work. Pls check the above bug

**Comment by beheh** [comment]
> Im experiencing this bug when selecting 1L - FMGC on the MCDU Menu page, selecting the pages with its button works
image

That is an unrelated bug, introduced by #4335 and fixed by #4348. But nonetheless the report is valid, this is broken and can't be fully tested until that's fixed.

**Comment by easyjetsimpilot** [comment]
Category: QA Tester
Name: Gavin (easyjetsimpilot)
Date of testing: 08/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4329
Tier of testing: 1
Changes to observe: PROG page GPS primary
Steps you've made to test the Pull Request:

Spawned cold and dark and confirmed on PROG page 'GPS PRIMARY' only shows when ADIRS aligned, 
Media:
pr1
pr2

Issues (If Any):
MCDU Menu bug - no systems are selectable any more. 


error


Conclusions of the testing: GPS Primary feature working, however, MCDU menu bug is present. Needs investigating.

**Pull request merged**
