### PR TITLE
fix: refactor overhead panel modelbehaviors (new sounds)

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

This changes the `FBW_Push_Toggle` template so that push buttons are not momentary by default.

- [x] Edit `FBW_Push_Toggle` template
- [x] Make necessary PBs momentary
- [x] Use new sound events for PBs and light switches

## References

image

Discord username (if different from GitHub): someperson#4953

## Testing instructions

* Complete flights using as many buttons on the overhead as possible - test if all their functions remain
* Test functionality of light switches
* Make sure sounds are proper and high quality, right volume

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by CookedTomato** [comment]
What does this fix do exactly?

**Comment by Benjozork** [comment]
@CookedTomato previously, all buttons on the overhead panel were momentary, which means they'd pop back in place after being pressed. This is not the case in the real A320 as you can see in the references. With this PR, this changes and only necessary buttons are momentary (not completely done yet).

In addition, this also enables the use of new button push sounds recorded by one of our A320 engineers in an actual cockpit.

**Comment by CookedTomato** [comment]
Thanks!

**Comment by Oberstumfuher** [comment]
> @CookedTomato previously, all buttons on the overhead panel were momentary, which means they'd pop back in place after being pressed. This is not the case in the real A320 as you can see in the references. With this PR, this changes and only necessary buttons are momentary (not completely done yet).
> 
> In addition, this also enables the use of new button push sounds recorded by one of our A320 engineers in an actual cockpit.

Just one question, you always talk about the real A320, correct? Okay, now why did you change the sound and put one that is not original? Because the sound of the "puppy", when starting the engine is real, another thing, the sound inside the cabin is very loud, the sound of the turbines, in reality the airbus cabin is silent and it is worth mentioning that the pilot and the co-pilot they use headphones for communication, which makes the sound inside even lower. It is not a criticism, it is only information about it.

**Comment by Benjozork** [comment]
@Oberstumfuher please go discuss this on our Discord if you have questions or concerns, this is not the place.

**Comment by hotshotp** [comment]
I see most buttons have been properly changed and sounds work. 👍

**Comment by hotshotp** [comment]
Tested - every button has been changed, all the momentary buttons are momentary as they should be. All the switches have the changed sound. No issues.

**Review by wpine215 — APPROVED** [review]

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date 24/1/21
Version of the sim: 1.12.13.0
PR Tested: #1877 
Tier of testing: 2
Changes to observe:
Overhead buttons and sounds

Testing technique: Did a full flight
Steps you've made to test the Pull Request:
1. Loaded in
2. Checked buttons worked as expected
3. Did the flight

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
Not lighting up while doing test 
image

Issues (If Any): 

- The area shown above does not light up while testing lights.
- The external power button is supposed to be momentary but is latching
- The Mode Select button under cabin pressure is supposed to be latching but is momentary
- The two reading light knobs on the overhead still have sound

Steps to achieve the issue

Overall Rating: To be improved
Conclusions of the testing: All other buttons that arent mentioned above work as expected just need these improvements added

**Comment by Benjozork** [comment]
Thanks @FlightSimmer7700, will be fixing,

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 24/1/21
Version of the sim: 1.12.13.0
PR Tested: #1877 
Tier of testing: 1
Changes to observe:
Fixed issued from previous test

Testing technique: Spawned at runway
Steps you've made to test the Pull Request:
1. Loaded in on the runway
2. Looked at the switches
3. pushed the switches

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): Write any issues
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: Issues encountered in the previous test are fixed and no more issues found

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: Current date 25/1/2021
Version of the sim: 1.12.13.0
PR Tested: #1877 
Tier of testing: 2
Changes to observe: Overhead panel model behavior 
 

Testing technique: Loaded c/d and tested every switch in the OHP 
Steps you've made to test the Pull Request:
1. Tested if push buttons are momentary or not
2. Tested if necessary PBs are momentary
3. Tested new sounds for PBs and light switches
 
Flight notes: N/A

Media: 
PBs momentary with new sound 

https://user-images.githubusercontent.com/74972083/105679055-e2015200-5f28-11eb-80bc-66bf4f0cd846.mp4

Noticed color differences in the annunciator lights but not sure if it matters or wrong. 

image

Issues: N/A  
 
Overall Rating: Good 
Conclusions of the testing: All worked as intended, just follow up with me regarding the lights color otherwise good job.

**Comment by cianwhite** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 24/1/21
Version of the sim: 1.12.13.0
PR Tested: #1877
Tier of testing: 2
Changes to observe: Changes to button sound and visual button pressing

Testing technique: Spawned cold and dark and completed a flight from EIDW-EGCC, pressing buttons on the overhead panel
Steps you've made to test the Pull Request:

1. Loaded cold and dark in EIDW, started up as normal. Observed which switches were pressed in already and noticed all were there as expected.
2. Pressed all of the buttons on the overhead panel to check for the sounds to see if they all worked.
3. Made the time of day night to observe if the lights work as before, to which they did
4. Landed as normal, everything seemed to be working as it should.

Flight notes (When done a full flight): LIFY6A LIFFY Q37 MALUD MIRS2B

Media: 
Screenshot_11


Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: I encountered no issues in my flight, all functionality seemed to be there and the buttons have a more realistic look to them and produce a better sound than before.

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 27/12/2021
Version of the sim: 1.12.13.0
PR Tested: #1877 
Tier of testing: n/a
Changes to observe: Momentary pushbuttons, position of buttons and sounds
Testing technique: 

Steps you've made to test the Pull Request:
- C&D Load
- Powerup and test of all the changed buttons
- observed position of all overhead buttons to check for any 

Issues (If Any): 
- I think the GPWS LDG Flap 3 button is in wrong default position. When clicking it, it goes OUT and ON. Shouldnt that be the other way around?
- In the PR the EXT PWR button is not marked as momentarily, but it is ingame. 
- I honestly cant remember how those are IRL :D Too long no flight :(

Overall Rating: LGTM except the above mentioned
Conclusions of the testing: Please check GPWS Flap 3 und EXT PWR wether those are correct.

**Pull request merged**
