### PR TITLE
[CDU] Add approach waypoints in DCT page

### LINKED ISSUE #522: [REQUEST] DIR functionality for all waypoints
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to go direct to waypoints on an approach, such as the initial approach fix or final approach fix. This is particularly an issue when flying online, as we cannot accept direct to commands. This issue also makes runway changes a hassle as NAV will turn to the IAF even if it is behind the aircraft.

**Describe the feature you'd like to see implemented**
The DIR page should list all waypoints of the flight plan including approach fixes, and allow them to be selected and flown direct to.

**References**
http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.3.0.html

### PR DESCRIPTION
**Pull request by lengyc0208**
Fixes #522, partially #1150

## Summary of Changes

The PR adds approach waypoints on MCDU DCT page. Detailed changes includes : 
- Added approach waypoint count and method in flight plan manager ;
- When updating DCT page, total waypoints count includes en-route, arrival and appraoch.
- Added logic to start the list from current active waypoint.

## Screenshots (if necessary)

**Before :** 
Microsoft Flight Simulator Screenshot 2020 10 07 - 00 52 56 62
Approach waypoints loaded (waypoints between DHP to KMIA).
Microsoft Flight Simulator Screenshot 2020 10 07 - 00 53 16 17
Approach waypoints not appear in DCT page (waypoints between DHP to KMIA).
**After :** 
Microsoft Flight Simulator Screenshot 2020 10 07 - 01 04 40 100

## References

http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.3.0.html

## Additional context

Discord username (if different from GitHub): lyc

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by AdenFlorian** [comment]
tested and LGTM! The approach waypoints show up on the DIR TO page and i can select them and it works (sometimes). sometimes  waypoints before the new dir to waypoint arent getting removed and then the flight plan gets all weird like this:
image
image

But i think that can be worked on in a future PR.

**Comment by ErikNL80** [comment]
The feature is working, but the aircraft won't follow the waypoints. I prefilled a flight from ENGM to EKCH with ILS22L approach. Everything was set-up OK, until I arrived near Copenhagen and the plane started to fly straight out.

**Comment by lengyc0208** [comment]
Indeed, I'm aware of the problem of improper removal of former waypoints and the not following waypoint issue, however they relate more to how flight plan is managed when DCT changes active waypoint. I may study this more and fix these issues in another PR.

@ErikNL80 I had exactly the issue yesterday at EKCH ! I was using Flytampa's EKCH, what about you ? I'm also wondering there might be a problem with Navdata in addons airports. Another issue is that I have problem with auto tunning ILS freq both in EKCH and LOWW. (I didn't seriously study this, so I'm probably wrong)

**Comment by ErikNL80** [comment]
> @ErikNL80 I had exactly the issue yesterday at EKCH ! I was using Flytampa's EKCH, what about you ? I'm also wondering there might be a problem with Navdata in addons airports. Another issue is that I have problem with auto tunning ILS freq both in EKCH and LOWW. (I didn't seriously study this, so I'm probably wrong)

Yes, I am also using FlyTampa's Copenhagen, and in previous master versions everything was OK. Manual tuning of the ILS is a known issue, happens with every add-on airport out there. Asobo needs to fix that...

**Pull request merged**
