### PR TITLE
[Lights] DIM/BRT Lights | Overhead Fixed

### PR DESCRIPTION
**Pull request by Snapmatics**
## Summary of Changes
**Interior Lights**

- I have re-worked the interior lights adding a more realistic look. You can now see the overhead as well based on which option you have set it to. (Dim or Bright)

# Screenshots
### **DIM Lights**
Microsoft Flight Simulator 10_11_2020 2_52_52 PM
Microsoft Flight Simulator 10_11_2020 2_54_28 PM (1)
Microsoft Flight Simulator 10_11_2020 2_55_48 PM

### **BRT Lights**
Microsoft Flight Simulator 10_11_2020 2_56_06 PM
Microsoft Flight Simulator 10_11_2020 2_54_45 PM
Microsoft Flight Simulator 10_11_2020 2_53_02 PM

# BEFORE
Screenshot_82

## References

Cockpit Screenshots showing the DIM/BRT are lacking. However, I managed to ask a few IRL Pilots to approve my work.
[FSLabs Reference](https://youtu.be/HZMrkJFLeso?t=117)

image
image

## Additional Context

Discord Username: `Harry ✈#0001`

Please let me know your feedback/opinions so I can make changes to this PR.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The `build.py` will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
2. Click on the **Checks** tab on the PR
3. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by markusa380** [comment]
The actual lamp seems too bright on dim, I'd expect it to be less emissive - but that might just be my personal feeling.

**Comment by Snapmatics** [comment]
> 
> 
> The actual lamp seems too bright on dim, I'd expect it to be less emissive - but that might just be my personal feeling.

That cannot be changed. Even with 1 intensity the lamp gets too bright.

**Comment by tareksabet** [comment]
Name: tarek_sabet#7946
Date of testing: 11/10/2020
Version of the sim: 1930
PR Tested: #1249 

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane C&D,
3. Inspected the cockpit from different angles. 
2. Did a short flight while looking around cockpit 

Overall Rating: Good
Conclusions of the testing: Very good job, nothing is affected and everything works as described.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 11/10/2020
Version of the sim: 1930
PR Tested: #1249

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane C&D at night
2. Inspected the cockpit from different angles and cameras
3. Changed time of day to different lighting conditions

Overall Rating: Good
Conclusions of the testing: Looks good to me! This was very much needed thank you very much!

**Comment by Benjozork** [comment]
LGTM thanks !

**Comment by Snapmatics** [comment]
> LGTM thanks !
> 
> @Snapmatics please resolve conflicts

### 
- [ ] Conflicts Resolved

**Review by Carter633 — COMMENTED** [review]
Name: Carter633 #1436
Date of testing: 11/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1249

Testing technique: Full flight from Cold and Dark
Steps you've made to test the Pull Request:
1. Spawned at EGKK for a full flight to EGCC - then respawned, full flight EGCC to EHAM
2. Started A/C power etc, checked all lighting in different environments

Overall Rating: Good
Conclusions of the testing: Tested yesterday - issues before writing up meant I was unable to write up promptly to apologies for the delay - seen merged already but figured I'd complete the report anyway! No issues found, looks good!

**Pull request merged**
