### PR TITLE
fix(chrono): pause chrono when sim is paused using escape key

### PR DESCRIPTION
**Pull request by ManyPandas**
Fixes #[issue_no]

## Summary of Changes

When the sim is paused with the escape key, the chronometer now pauses as well. 

## Additional context

Discord username (if different from GitHub):
ManyPandas#0839

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ManyPandas** [comment]
@davidwalschots This PR needs some work from you. Currently, the chronometer is reading a simvar which requires an event listener for when the game is paused with esc. This cannot be done directly inside the chrono itself. Would you mind taking a look and possibly implement a listener which updates the simvar I'm looking for?

**Comment by ErickSharp** [comment]
There are different variations of 'Pause' but I am sure we will get it ironed out!

**Comment by davidwalschots** [comment]
There are various forms of pausing. Currently we don't support any of them in the aircraft. I'm not planning on working on supporting pausing any time soon. If anyone else feels like looking at it they should feel free to do so.

**Comment by MisterChocker** [comment]
Hopping onto the discussion after sharing my thoughts in discord.. _(just to have this documented idea somewhere related)_

I have had the idea to add a check for pauses to the `updateThrottler`, so that the systems won't be updated while paused.

**Comment by ErickSharp** [comment]
> There are various forms of pausing. Currently we don't support any of them in the aircraft. I'm not planning on working on supporting pausing any time soon. If anyone else feels like looking at it they should feel free to do so. However, it should be noted that pausing is in fact a concern not just affecting the chrono, but all parts of the aircraft. As such, I do not recommend moving forward with this PR, and instead recommend solving the problem throughout the whole aircraft.

ManyPandas opened this draft PR to wait for someone to eventually implement listening for a Pause event. He himself won't actually be able to proceed in doing that himself as he just doesn't have the knowledge of how to do so yet.

**Comment by davidwalschots** [comment]
If that's the case then I'd recommend closing this PR at the moment. Draft PRs aren't really intended for waiting on another PR which will come at an undetermined point in the future 😀.

**Comment by ManyPandas** [comment]
Closed at the recommendation of @davidwalschots

**Pull request closed without merging**
