### PR TITLE
chore: remove Christmas livery

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

- Removed Christmas livery.

## Additional context
Discord username (if different from GitHub): Imenes#8739

## Testing instructions
Just deleted the XMAS livery folder. Not sure if any testing is needed if it is just check that the livery is not present anymore, and no unforeseen issues are present. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by ErikNL80** [comment]
Folder needs to be removed and json file needs to be updated, thats all...

**Comment by davidwalschots** [comment]
@ErikNL80 Git doesn't store folders. Could you indicate which JSON file you're referring to?

**Comment by ErikNL80** [comment]
> @ErikNL80 Git doesn't store folders. Could you indicate which JSON file you're referring to?



> @ErikNL80 Git doesn't store folders. Could you indicate which JSON file you're referring to?

O, sorry David... I meant in the file structure after downloading. I guess if you remove the folder, the layout.json is generated afterwards so there will be no issue.

**Comment by davidwalschots** [comment]
@ErikNL80 😃 I'm still not sure what you are referring to. The build package does not contain any XMAS folder, nor does the `layout.json` refer to anything with XMAS.

**Review by davidwalschots — APPROVED** [review]
LGTM

**Comment by ErikNL80** [comment]
Never mind. :) Change is OK

**Pull request merged**
