### PR TITLE
Fix incomplete switch from node-sass

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

This is a developer-only change, following up on #2307. It ensures that optional dependencies are no longer installed by default, otherwise `rollup-plugin-scss` will pull in node-sass. It also fixes the rollup config to actually start using the `sass` package instead of `node-sass`, because the wrong config key was used.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by beheh** [comment]
Briefly marked as ready for review to check that CI succeeds.

**Comment by beheh** [comment]
Just to make sure this does not break anything else:

### Instructions for QA

Once this is marked `Ready to Test`, load up the version from this PR and make sure the DCDU still works and shows `INOP.` when you press any button, as that is the system that would be affected by a breakage here:

image

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 14/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2367
Object of test: DCDU

Steps you've made to test the Pull Request: I have done exactly this
> ### Instructions for QA
> 
> This is a quick one: Load up the version from this PR and make sure the DCDU still works and shows `INOP.` when you press any button, as that is the system that would be affected by a breakage here:
> 
> image
> 
> Everything else should be unaffected, but you're free to check that other stuff works as usual.

- Checked brightness control -> Working!
- Pushed every button on both sides and waited each time until INOP. disappeared. -> Working!


Overall Rating: Good
Conclusions of the testing: Everything works, seems like nothing got broken.

**Comment by kberg93** [comment]
Not aviable for download atm :)

**Comment by Noxleee** [comment]
> 
> 
> Not aviable for download atm :)

https://github.com/flybywiresim/a32nx/pull/2367/checks?check_run_id=1539817474

Klick on Artifacts ;)

**Comment by kberg93** [comment]
> > Not aviable for download atm :)
> 
> https://github.com/flybywiresim/a32nx/pull/2367/checks?check_run_id=1539817474
> 
> Klick on Artifacts ;)

must have been a bug when i click checks then :S cus its no artifacts there when i click the checks tab(see SC) but its there in ur link xD
chrome_eLXdDfHTio

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 12/14/2020
Version of the sim: 1.11.7.0
PR Tested: #2367 
Object of test: Fix incomplete switch from node-sass

Testing technique: Click buttons on the DCDU

Steps you've made to test the Pull Request: 
1. Loaded the plane into the sim.
2. Clicked all buttons and got "INOP." on the DCDU as it should.
Flight notes (If required): 

Issues (If Any): 

Overall Rating: Good.

Conclusions of the testing: Worked like described.

**Pull request merged**
