### PR TITLE
[ND] Move MFD icons from asobo and change colors

### PR DESCRIPTION
**Pull request by ilyeshammadi**
Fixes #[issue_no]

## Summary of Changes

The main change in this PR is the move of the `SVG` and `png` images of the MFD, this will make it easy to change these images in the future. I've also changed the `magenta` colors to match the one we're using in our style.

Bye bye anoying harsh old magenta color 😆

**What has been done:**
- [x] Move MFD icons from asobo to a32nx.
- [x] Change the default `magenta` color to match the one we have.

## Screenshots (if necessary)

Screenshot 2020-12-05 054034
Screenshot 2020-12-05 054131
Screenshot 2020-12-05 054209

## Additional context

Discord username (if different from GitHub): Union Araken#4083

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
QA, just test that no icons are missing from the ND

**Comment by ilyeshammadi** [comment]
@Benjozork I don't think that CHANGELOG are needed for this PR since it's not a new feature or a major fix.

**Comment by Benjozork** [comment]
Just add one for the color change not the icons then

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date 5/12/20
Version of the sim: latest
PR Tested: #2234 
Object of test: ND

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned in on gate
2. Took off
3. flew for 2 hours
4.during this time observed the icons on the ND
5.Didn't manage to land had to go after starting descent

Flight notes (If required): IDK if this is required but here is the flight plan anyway 
EGNT/25 GIRLI3X GIRLI P18 GASKO P16 RIBEL UP16 CROFT UL612 HON L15
BIG UL9 KONAN UL607 REMBA DCT LIRSU DCT NONKO UL607 UTABA M738 MADEB
MADEB1B LOWI/26


Issues (If Any): I'm not sure if this is an issue or not but when pressing on vor mode or ndb mode or waypoint mode(and the others) on the buttons at the top I had to move the zoom under/over 40 or just moving it (was a little random really) to get the icons to appear
Overall Rating: To be improved
Conclusions of the testing: There is the issue where the icons don't show up, the flight plan icons are perfectly fine, if that was present before then there are no issues with this pr but if it is caused by this pr that the icons don't appear then there is some improvement to be done

**Comment by ilyeshammadi** [comment]
@FlightSimmer7700 thanks for testing. The issue you mentioned is not related to this PR. You can confirm this by doing the same test in ‘master’

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1] tjburni #0409
Date of testing: Current date 06.12.2020
Version of the sim: 1.11.6
PR Tested: #2234
Object of test: Move MFD icons from asobo and change colors

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. started C&D at gate at eddh
2. took off
3. looked at the icons of the ND while flight
4. did a go around at eddv 
5. landed at eddv

Flight notes (If required):

Issues (If Any): none
Overall Rating: Good
Conclusions of the testing: the icons are great. No problems with my tests

**Comment by FlightSimmer7700** [comment]
> @FlightSimmer7700 thanks for testing. The issue you mentioned is not related to this PR. You can confirm this by doing the same test in **master** (latest dev version )

ok then this pr is good to go

**Pull request merged**
