### PR TITLE
[ECAM REWRITE] COND page

### PR DESCRIPTION
**Pull request by RichardPilbery**
Fixes #[issue_no]

## Summary of Changes

Rewritten COND page in React.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by wpine215** [comment]
Looks like there's a lot of other pages also touched by this PR, is that intended?

**Comment by tracernz** [comment]
The pull should be against the `ecam_rewrite` branch I think, not `master`.

**Comment by Benjozork** [comment]
@wpine215 @tracernz fixed.

**Comment by RichardPilbery** [comment]
Thanks @Benjozork, my mistake.

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 12/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2933 
Object of test: ECAM Cond page

Testing technique: Ground test
Steps you've made to test the Pull Request:
1. Tested all Knobs and buttons -> Changes are displayed on the ECAM COND Page
2. Start from cold and dark -> ECAM shows correctly how temp. is rising slowly.
3. Tested weight changes -> Changes are displayed as expected on the ECAM COND Page
4. Test start with climb to FL300
5. Tested all knobs and buttons while inflight -> Everything is working as expected.


Overall Rating: Good
Conclusions of the testing: I guess I tested everything on ground and inflight. Could not find any issue. LGTM!

**Pull request merged**
