### PR TITLE
feat: Decals better fonts and improved emissive

### PR DESCRIPTION
**Pull request by FoxinTale**
Put the proper font on the cockpit decals and remade the airframe decals.

## Summary of Changes

	Increased the thickness of the emissive decals around the switches and buttons.
	Made the square box have clean curves.
	Changed the shade of blue of the "ON" indicator to be more correct.
	A fair amount of font changes, to have a more accurate font instead of Arial, listed below.
	Font changes:
		UNLK
		AUTO LAND (Currently, only visible when all indicators turned on)
		MASTER WARN
		MASTER CAUT 
		DECEL
		SYS ON
		GPWS
		HOT (Brake fan indicator)
		G/S 
		All ON and OFF boxes
		Sidestick priority indicators

	Changed the font of the ON indicators to be more accurate.
       Made the FAULT indicator more orange-y
	Remade the entirety of the cockpit decals alpha, which includes the "Oxygen mask" and "Waste" labels.
	Removed the stitch decals from the edge trim of the cockpit seats. They looked odd to begin with.

## Screenshots (if necessary)

The Seats:
Before:  (Look very closely at the centre of the edge trim for the seam)
Old Seats

After: (Notice there's no random seam down the middle.
New Seats

Auto Brake Panel:
Before:
Old Auto Brk

After:
New Auto Brk

Lighting, Anti-Ice and APU switches:
Before:
Old Switches

After: 
New Switches

Master warning and caution:
Before: 
Old Warn

After:
New WarnCaut

The decal/label things:
Before:
Old Labels

After:
New Labels

And finally, the overhead panel:
Before:
Old Overhead

After:
New Overhead

## Additional context

Some of the textures may appear off centre. Perfect centering is really difficult to achieve. If someone else wishes to do that, by all means, go for it. 

Discord username (if different from GitHub):	Aubrey Jane#7563

## Testing instructions

		Check night and day, and integ lighting. All indicator lighting and make sure that nothing is flickering or bugging out.
		Should be all that needs to be done. Feel free to do more testing if desired.
	
They may appear clearer than the screenshots suggest. My monitor is 1600 x 900, so it may appear sharper on higher resolutions.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by hotshotp — APPROVED** [review]
LGTM

**Comment by Lazarus320** [comment]
@FoxinTale Hey, I'm getting this behaviour with most lights could you check into that please? 
image

**Comment by beheh** [comment]
Great job putting all this together! How about also getting some pilots to chime in through #pilot-feedback?

Personally the blue seems a bit very heavy to me comparing it to references. Didn't we figure out in Discord that this deep shade of blue was rarely used in reality?

**Comment by flythebest** [comment]
IRL A320 Pilot.

Nice job. beheh is right, the blue is too heavy. As discussed in discord, this dark blue exists in some airplane but is rare and not standart.

**Comment by marcman86** [comment]
The actual PR Artifact has better blue lights.

**Comment by hotshotp** [comment]
> Great job putting all this together! How about also getting some pilots to chime in through #pilot-feedback?
> 
> Personally the blue seems a bit very heavy to me comparing it to references. Didn't we figure out in Discord that this deep shade of blue was rarely used in reality?

These are fixed in the PR, there just isn't a picture that she took for the "after" screenshots that includes the reverted blue changes

**Comment by FoxinTale** [comment]
> > Great job putting all this together! How about also getting some pilots to chime in through #pilot-feedback?
> > Personally the blue seems a bit very heavy to me comparing it to references. Didn't we figure out in Discord that this deep shade of blue was rarely used in reality?
> 
> These are fixed in the PR, there just isn't a picture that she took for the "after" screenshots that includes the reverted blue changes

Exactly. I fixed it late last night and didn't feel like restarting the sim and retaking all the screenshots.

**Comment by FoxinTale** [comment]
> @FoxinTale Hey, I'm getting this behaviour with most lights could you check into that please?
> image

I've seen that while making the textures, when one has the current font, and the other does not. It's usually the base colour that doesn't have the updated font(s) while the emissive does. I'll double check to make sure I didn't mess that up.

**Comment by beheh** [comment]
> Exactly. I fixed it late last night and didn't feel like restarting the sim and retaking all the screenshots.

Great, thank you!

**Comment by SaqibSiddiqi** [comment]
Did a flight, the overlap of lights text is still present

**Comment by FoxinTale** [comment]
> Did a flight, the overlap of lights text is still present

You updated the texture files, right? I made a change to the ALBD file. I assume they were, but does not hurt to double check.

**Comment by SaqibSiddiqi** [comment]
> 
> 
> > Did a flight, the overlap of lights text is still present
> 
> You updated the texture files, right? I made a change to the ALBD file. I assume they were, but does not hurt to double check.

I had just copied the artifact, I wasn't aware I had to copy something else.

**Comment by FoxinTale** [comment]
> > > Did a flight, the overlap of lights text is still present
> > 
> > 
> > You updated the texture files, right? I made a change to the ALBD file. I assume they were, but does not hurt to double check.
> 
> I had just copied the artifact, I wasn't aware I had to copy something else.

Ah. I meant you may have to update / redownload the artifact. Not too sure how it all works for QA on the "back end".

**Comment by marcman86** [comment]
Checked: It is fixed in the artifact.

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 24.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3693
Tier of testing: 1
Changes to observe: Button decals
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C%D at EDDP
2.) Turned on bat. and ext. power
3.) Did ANN LT Test

Compared with references from Issue #956

Most of the issues are model issues like ATC MSG and SIDE STICK PRIORITY arrows and not part of this PR.

Media:


Image1


Image2

Issues: 
- Engine fire extinguisher are dim (maybe not part of this PR, Image1)
- Double dots do iluminate (Image2) 
- Panelsection with wrong colors compared to reference (Image2)

Overall Rating: -

Conclusions of the testing: Most Decals look nice. Blue color is like reference.

Hope this helps :-)

**Pull request merged**
