### PR TITLE
make core speed computation an util

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

Made computation of speed from core speeds an util.
This allows better usage of speed computation.

Will be used by #1824 and #2304

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MisterChocker** [comment]
For QA check if F, S and GD marker are visible, and check auto computed TO speeds.

**Comment by Benjozork** [comment]
QA: Just test that speeds still work

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 09/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2291 
Object of test: Speeds

Testing technique: Test Flight ESGG ENGM
Steps you've made to test the Pull Request:
1. Programmed FMC
2. Checked V-Speeds -> calculated correctly, weight changes were recognised 
3. Take off -> V-Speeds and S-Speed were shown correctly
4. Approach & Landing:
- S-Speed was shown but was above the Speed of Flaps 2 (never seen before)
- F Speed was shown correctly, 
- VLS was calculated to 138 -> Vapp 144, that’s VLS+6, I thought it should be VLS+5?
- Vapp was shown correctly 

Issues (If Any): I found a few things described above, but that also could be correct, I am not a pilot.
Overall Rating: No Rating, since I am not sure

**Comment by MisterChocker** [comment]
> * VLS was calculated to 138 -> Vapp 144, that’s VLS+6, I thought it should be VLS+5?

the calculation of Vapp depends on the wind, the formula is `1 / 3 steady headwind`, you are right that the Vapp computation on your test was wrong, it took only the head wind component into account. However Vapp is min Vls + 5 and max Vls + 15.

**Pull request merged**
