### PR TITLE
feat(elec): power consumption and batteries

### PR DESCRIPTION
**Pull request by davidwalschots**
## Summary of Changes
The electrical system developed in #2582 does not yet include power consumption. This means the load on origins of electric potential is always 0%. This PR aims to provide a semi-realistic power consumption simulation. It does so by:

- Approximately simulating power consumption during different phases of flight, based on data provided by @komp1821.
- Providing programmatic types to simulate power usage of individual components, such that the approximate simulation above can slowly be replaced by an exact variant.

## Review recommendations
This PR is rather large. For code reviewing I have the following recommendations in terms of files to review:
- [src/systems/a320_systems/src/power_consumption.rs](https://github.com/flybywiresim/a32nx/pull/3625/files#diff-7cc551d958928ec423f659ddb4a65de17e83f520ba101d467cf99be51ed4c62b)
- [src/systems/systems/src/electrical/battery.rs](https://github.com/flybywiresim/a32nx/pull/3625/files#diff-6f6ac61925c52a35b92ca7ca8199e65df85885e5074eb99fcbeeeadc8de8ca16)
- [src/systems/systems/src/electrical/battery_charge_limiter.rs](https://github.com/flybywiresim/a32nx/pull/3625/files#diff-6f6ac61925c52a35b92ca7ca8199e65df85885e5074eb99fcbeeeadc8de8ca16)
- [src/systems/systems/src/electrical/consumption.rs](https://github.com/flybywiresim/a32nx/pull/3625/files#diff-6f6ac61925c52a35b92ca7ca8199e65df85885e5074eb99fcbeeeadc8de8ca16)
- [src/systems/systems/src/electrical/mod.rs](https://github.com/flybywiresim/a32nx/pull/3625/files#diff-c36ef03a9c19212e4229162e88bd2c7e9a8a46a615b662bd4b74b7e238f51265) regarding the `Potential` type.
- [src/systems/systems/src/simulation/test.rs](https://github.com/flybywiresim/a32nx/pull/3625/files#diff-6f6ac61925c52a35b92ca7ca8199e65df85885e5074eb99fcbeeeadc8de8ca16)

## Technical changes

- [x] Testing of types implementing `SimulationElement` is easier with a `SimulationTestBed` which invokes all the functions as they would be invoked when running in the simulator itself.

## Functionality
- [x] Power consumption during different phases of flight, with randomisation of consumption over time (i.e. base usage lookup table for phase of flight where randomisation sets actual consumption to 90-110% of base usage every 5 to 30 seconds).

### Battery
- [x] The battery charges.
- [x] The battery discharges.
- [x] The battery's charge/discharge _I_ is calculated and displayed on the ECAM.
- [x] When the battery contactor is closed, and I<sub>disch</sub> >= 1A for over 15 seconds, an amber arrow from the battery towards the DC BAT BUS is displayed.
- [x] When the battery contactor is closed, and I<sub>disch</sub> >= 1A for over 15 seconds, the _I_ is displayed in amber.
- [x] When the battery contactor is closed, and  I<sub>ch</sub> >= 1A for over 15 seconds, an arrow from the DC BAT BUS to the battery is displayed.
- [x] When the battery contactor is closed, and I < 1A, a line without an arrow is displayed between the battery and the DC BAT BUS.
- [x] When the battery contactor is open. No line is displayed between the battery and the DC BAT BUS.
- [x] Batteries charge each other in certain situations.

### Battery bus
- [x] DC BAT BUS legend becomes amber when U<sub>BATBUS</sub> <= 25V.

### Battery Charge Limiter
The BCL manages the battery contactor of a battery. Information provided by @komp1821.

It should close the contactor when:
- [x] U<sub>BAT</sub> < 26.5V AND U<sub>BATBUS</sub> > 27V for 225 milliseconds or more.
- [x] The APU MASTER SW is ON.

It shouldn't close the contactor when in APU start inhibition during EMER ELEC (AC1 and AC2 unpowered, IAS > 100 knots), and:
- [x] Less than 45 seconds have passed since entering EMER ELEC and emergency generator not available.
- [x] Landing gear is not up.

It should open the contactor when:
- [x] On the ground and I<sub>ch</sub> < 4A for 10 seconds, unless APU started (see below).
- [x] Speed > 100 knots and I<sub>ch</sub> < 4A for 30 minutes.
- [x] Following an APU start and I<sub>ch</sub> < 4A for 30 minutes.
- [x] On the ground and U<sub>BAT</sub> < 23V for 15 seconds (complete discharge protection).
- [x] In EMER ELEC CONFIG, unless starting the APU and then only within the limitations outlined above.
- [x] When in EMER ELEC over three minutes have passed with the APU MASTER SW in the ON position.

When the battery push button is in the OFF position, the BCL is not powered. This means that any conditions which depend on external factors (such as APU start) or the timers for certain conditions are not remembered.

### Other potential providers
- [x] The APU generator's _load %_ is calculated and displayed on the ECAM.
- [x] The engine generator's _load %_ is calculated and displayed on the ECAM.
- [x] The static inverter consumes power from BAT 1.
- [x] The transformer rectifiers' _I_ is calculated and displayed on the ECAM.
  - [x] TR output _I_ depends on DC consumption on buses supplied by the transformer rectifier.
  - [x] The TR consumes AC power from the GEN or EXT PWR source powering it.
- [x] The contactor associated with a generator only closes when the generator's electrical parameters are normal (and the associated button on the overhead panel isn't in the OFF position). At the moment the APU is the only generator for which one can test this, as all other generators are either fully OFF (0Hz, 0V) or fully on (400Hz, 115V). The way to test it is during an ELEC EMER situation, where you can observe the APU's potential and frequency climbing near the end of its start.

### APU
- Cannot be started in EMER ELEC config, unless:
  - [x] 45 seconds have passed, or
  - [x] EMER GEN is available.
- [x] Cannot be started when in EMER ELEC config with the gear down.
- [x] Start is aborted when in EMER ELEC config, N<sub>APU</sub> < 55% and the gear is brought out of the up and locked position.
- [x] Start is aborted when the aircraft enters EMER ELEC during the APU start.

#### Starter motor
- [x] Realistic power consumption of the starter motor during APU start.

## Remaining work for another PR

- Battery charging thermal runaway protection. As the current battery implementation cannot have a thermal runaway there was no point in implementing it as of yet. The battery contactor should open when one of the following conditions is met:
  - I<sub>ch</sub> > 10A and ΔI<sub>ch</sub> > 0.375A/min
  - I<sub>ch</sub> > 150A for 90 seconds
- This PR uses FWC flight phases for the power consumption declarations. Recently FMGC flight phases became available. The combination of both FWC and FMGC allows for more fine-grained power consumption profiles to be implemented.
- Electrical parameter fluctuation based on load (i.e. Hz and V briefly changing slightly as power usage fluctuates).
- The transformer rectifiers should be limited to 300A. During APU start with supplied AC power 300A is exceeded. On the real aircraft the remaining current should come from the batteries.

## Additional context

Discord username (if different from GitHub): SjotgunSjonnie#9623

## Testing instructions
One can use the specifications outlined above for testing. Note that some things will be difficult to test, as the aircraft starts with full batteries on every flight at the moment. Another difficulty is that the EMER GEN always comes online after 8 seconds at the moment, thus not leaving much time to test the up to 45 seconds condition.

I guess we'll just have to trust the unit tests I wrote 😉.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by beheh** [comment]
This requires #2582 to be merged, right? I'll review that today.

**Comment by davidwalschots** [comment]
@beheh Yes. It does. Not sure if we need a tag for this. Given that this PR is a draft and thus far only contains a CHANGELOG change 🙂.

**Comment by beheh** [comment]
Sure, I thought I might help people speed up #2582 if they want to see this land :smile:

**Comment by komp1821** [comment]
And here is my _formal approval_ again:

As far as possible, every item has been crosschecked with the aircraft documentation by me and is consistent with the real behavior. It also matches the videos of the ECAM ELEC page I made for that purpose. I have a few remarks to add though:

### Other potential providers

> When generators or the static inverter are outside of normal parameters in terms of frequency (Hz) and potential (V) their contactor closes. This can only be tested during an APU start in EMER ELEC at the moment, as the APU is the only source for which increasing potential and frequency is implemented.

I'm pretty sure you mean _When generators or the static inverter are outside of normal parameters [...] their contactor **opens**._ ;)
I'm also having trouble understanding the test conditions. The Generator Line Contactors would be open anyways during EMER ELEC config and the STATIC INVERTER doesn't have very much load on it during an APU start. Most of the energy is coming from the DC side. Correct me if I'm missing something here.

### APU

>  Start is aborted when in EMER ELEC config, NAPU < 55% and the gear is brought out of the up and locked position.

> Start is aborted when the aircraft enters EMER ELEC during the APU start.

These are extremely unlikely edge-cases.
We are not 1000% sure about this, because the system descriptions don't contain this information explicitly. I have been digging very deep into the wiring diagrams and couldn't find anything that would prevent this from happening. Of course we cannot rule out it isn't handled in a different way. It's just based on the related behavior in other situations (e.g. APU start inhibited for 45s during RAT extension), my system knowledge and common sense. However, we are unable to prove this ultimately for obvious reasons.
I had a nice chat with our Airbus rep about something similar a while ago and he said something very important: _"It is all about probabilities. There are lots of ways to get into a dangerous situation by just a few button presses. The main questions are: What are the odds that this is happening? And how catastrophic would the outcome be? This is all being considered during a risk assessment and depending on these questions it is decided whether or not it is worth the effort to add another line of defense."_

That's it for now. In-sim testing by me is still pending. I'll do that tomorrow.

**Comment by davidwalschots** [comment]
@komp1821 Hah yes. The contactor should be open at that point. I've adapted the text and hope it's clearer now.

**Comment by komp1821** [comment]
Testing finished. Checked every point and I have a "black box" screen recording if needed. While most of it looked good, I experienced two problems:

- Charging of the batteries should be faster. I managed to drain the batteries to 26.3 V by repeatedly starting the APU on batteries. Charging cycle begins correctly after switching EXT power on, but it seems to be slow. I_charge remained at 10A the whole time (>5min) and the voltage had not really increased when I set the batteries to off for a brief moment to check. 

- Battery voltage doesn't drop enough during APU start. It stayed at 27V with I_disch > 100A. This load should make it drop more, around 23-24V. The video of the ELEC page during APU start should give you an idea. It's also in the plotted Excel file I made from that. 

**Following items have not been checked:**

> [Battery contactor should open when] On the ground and UBAT < 23V for 15 seconds (complete discharge protection)

Bringing the batteries down to 23V would take too long. As long as your coded test confirms it works, I'm fine with it.

> The static inverter consumes power from BAT 1.

There is no actual indication for this. There is the "> STAT INV" next to battery 1, which works correctly, but this does not really prove that the static inverter consumes power from BAT 1 and not from BAT 2 because the indication cannot be elsewher. If it's coded correctly, I have no reason to doubt it.

**Comment by davidwalschots** [comment]
Thanks for testing @komp1821!

The internals of the batteries related to its resistance and charging rate aren't fully implemented. @tracernz has more knowledge on this particular area and I am expecting he might at some point improve this. For now the maximum charge rate is set at 10A. I put it on this limit as I noticed the thermal runaway condition includes that if charging _I_ is above 10A and ΔIch > 0.375A/min the battery would automatically be disconnected. What would you consider an acceptable charge rate for now?

With regards to your second point, note that the _remaining work for another PR_ lists:
> Electrical parameter fluctuation based on load (i.e. Hz and V briefly changing slightly as power usage fluctuates).

This does include battery _U_ dropping as well. So that not being implemented is expected at this point.

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
