### PR TITLE
feat: custom BAT font

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Added custom BAT font

## Screenshots (if necessary)

image

## References

image

## Additional context

Due to a model issue, the displays are wider in the sim than there are in real life.

## Testing instructions

Make sure the new font is accurate.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by nistei — APPROVED** [review]

**Comment by beheh** [comment]
image

Do we have a theory for this difference? Is the model wrong?

**Comment by tyler58546** [comment]
> Do we have a theory for this difference? Is the model wrong?

Asobo made the display too wide.

**Comment by beheh** [comment]
Actually looking at some photos, it might not even be quite wide enough, but it's severely lacking height in the sim. It needs to be as high as the button outline, and that is missing as well right now.

image

So in any case, sounds like this won't be quite right until we get the model fixed. At that time we'll just need to increase the screen size here.

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 18.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3582
Tier of testing: 1
Changes to observe: new BAT font
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Looked at BAT displays (Image1)
3.) Did ANN LT Test (Image2)

Media:


Image1


Image2

The alignment is a little to the top. But also the refence shows that. So its OK.

Issues: None

Overall Rating: Good

Conclusions of the testing: Looks good!

Hope this helps :-)

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 2/18/2021
Version of the sim: 1.13.16.0
PR Tested: #3592 
Tier of testing: 1
Changes to observe:
Added custom BAT font

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned C&D at kmsy
2. Checked battery font for any issues


Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.


Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: All good NOVA and TYLER

**Pull request merged**
