### PR TITLE
feat(camera): added new interior views

### PR DESCRIPTION
**Pull request by Snapmatics**
## Summary of Changes
This PR adds new showcase/internal views for people that do not want to deal with the camera.cfg file and custom cameras.

> **Yes, the sounds are interior as well.**

## Screenshots
Microsoft Flight Simulator 2_25_2021 1_13_57 AM
Microsoft Flight Simulator 2_25_2021 1_14_08 AM
Microsoft Flight Simulator 2_25_2021 1_14_24 AM
Microsoft Flight Simulator 2_25_2021 1_14_16 AM
Microsoft Flight Simulator 2_25_2021 1_14_45 AM
Microsoft Flight Simulator 2_25_2021 1_14_31 AM
Microsoft Flight Simulator 2_25_2021 1_15_02 AM
Microsoft Flight Simulator 2_25_2021 1_14_54 AM

Discord Username: `Harry [Z+2]#9872`

## Testing Instructions
- Load at a gate
- Open Camera Panel
- Showcase
  - Fixed Camera
  - From External 13 until External 19
  
 ## Note
 It conflicts with #3367 because he/she is using the same value for the EFB camera.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by pepperoni505 — APPROVED** [review]
LGTM

**Comment by Samueleonard** [comment]
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: Current date 24/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3702
Tier of testing: 1
Changes to observe: check new views
Testing technique: Tryout

Steps you've made to test the Pull Request:
1. load in and switch to view 13
2. check each view - notes below

Flight notes (When done a full flight):
13. fine - uses existing window frame 
14. too wide angle - should be zoomed slightly OR mirrored of view 15
15. okay - if view 15 is view 14 mirrored, then the camera may need zooming slightly
16. okay - not a fan of these types of views but angle is fine
17. okay - - not a fan of these types of views but angle is fine
18. okay
19. same position as exisiting view 12, could delete view 12 and move this view to use the existing window frame

Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A

Issues (If Any): Write any issues
as described above

Steps to achieve the issue
N/A

Overall Rating: To be improved

Conclusions of the testing:
good overall, just a few minor tweaks needed

**Comment by hotshotp** [comment]
> 19. same position as exisiting view 12, could delete view 12 and move this view to use the existing window frame
view 12 is not showing the entire sharklet, this one is

**Comment by Snapmatics** [comment]
> 
> 
> Category: QA Trial
> Name: 1samueleonard1#0001
> Date of testing: Current date 24/02/2021
> Version of the sim: 1.13.16.0
> PR Tested: #3702
> Tier of testing: 1
> Changes to observe: check new views
> Testing technique: Tryout
> 
> Steps you've made to test the Pull Request:
> 
>     1. load in and switch to view 13
> 
>     2. check each view - notes below
> 
> 
> Flight notes (When done a full flight):
> 13. fine - uses existing window frame
> 14. too wide angle - should be zoomed slightly OR mirrored of view 15
> 15. okay - if view 15 is view 14 mirrored, then the camera may need zooming slightly
> 16. okay - not a fan of these types of views but angle is fine
> 17. okay - - not a fan of these types of views but angle is fine
> 18. okay
> 19. same position as exisiting view 12, could delete view 12 and move this view to use the existing window frame
> 
> Media: Insert screenshots, recordings, or anything relevant to the review here.
> N/A
> 
> Issues (If Any): Write any issues
> as described above
> 
> Steps to achieve the issue
> N/A
> 
> Overall Rating: To be improved
> 
> Conclusions of the testing:
> good overall, just a few minor tweaks needed

I have updated the cameras again and also changed the screenshots with the new ones. Let me know for any changes,

**Comment by Kacper848** [comment]
Maybe zoom out a bit on this preset so the whole engine can be seen?
image
This is the sort of thing that I'm thinking of:
Screenshot_20210224_232702

**Comment by hotshotp** [comment]
> Maybe zoom out a bit on this preset so the whole engine can be seen?
> image
> This is the sort of thing that I'm thinking of:
> Screenshot_20210224_232702

no - that looks terrible. we want a nicer FOV, so its more realistic. this looks waaaay zoomed out

**Comment by tracernz** [comment]
> It conflicts with #3367 because he/she is using the same value for the EFB camera.

I might just close that one because it's not possible to make it perfect (roll doesn't work), and it doesn't seem to have much interest.

**Comment by Snapmatics** [comment]
> > It conflicts with #3367 because he/she is using the same value for the EFB camera.
> 
> 
> 
> I might just close that one because it's not possible to make it perfect (roll doesn't work), and it doesn't seem to have much interest.

Will see what I can do then if you need me to help.

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 26.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3702
Tier of testing: 1
Changes to observe: Ext. lights
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned runway at EDDP
2.) Looked for fixed showcase views 13-19
3.) Start Engines, listend to int. sound in all views

Issues: -

Overall Rating: Good

Conclusions of the testing: Viewing Angles are good and consistent between left and right side.

Hope this helps :-)

**Comment by NonstopFlying** [comment]
Category: QA Trial
Name: NonstopFlying (Henrik) #6771
Date of testing: Current date 27/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3702
Tier of testing: 1
Changes to observe: New views
Testing technique: Showcase Camera

Steps you've made to test the Pull Request:

Showcase
Fixed Camera
From External 13 until External 19

Media: 
wad
Capture


Issues (If Any): Don't know if this is a know issue or just with this PR, if you look at the 20, LS and off they have pixilated "glitches"

Overall Rating: Good

Conclusions of the testing:
Camers are looking good even tho I don't like the ones that go straight over the wings but that's just my personal preference, other than that if that issue is not related with the PR then i'd say it's good to go.

**Comment by marcman86** [comment]
> Issues (If Any): Don't know if this is a know issue or just with this PR, if you look at the 20, LS and off they have pixilated "glitches"

Cheching while testing other PR: Same, not related to this PR.

**Comment by Snapmatics** [comment]
> 
> 
> Category: QA Trial
> Name: NonstopFlying (Henrik) #6771
> Date of testing: Current date 27/02/2021
> Version of the sim: 1.13.16.0
> PR Tested: #3702
> Tier of testing: 1
> Changes to observe: New views
> Testing technique: Showcase Camera
> 
> Steps you've made to test the Pull Request:
> 
> Showcase
> Fixed Camera
> From External 13 until External 19
> 
> Media:
> wad
> Capture
> 
> Issues (If Any): Don't know if this is a know issue or just with this PR, if you look at the 20, LS and off they have pixilated "glitches"
> 
> Overall Rating: Good
> 
> Conclusions of the testing:
> Camers are looking good even tho I don't like the ones that go straight over the wings but that's just my personal preference, other than that if that issue is not related with the PR then i'd say it's good to go.

The "pixilated "glitches"" do exist in-general. We can't fix those without the exporter.

**Pull request merged**
