### PR TITLE
feat: attach tiller plate emissive to a potentiometer

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

-  Attached tiller plate emissive to the rest of the pedestal integral lighting   

## References

image

## Additional context
While looking at the references I realized the tiller is backlit. Confirmed by pilots that the backlight is controlled with the rest of the pedestal integral lights.

Improves #3188 

Discord username: Imenes#8739

## Testing instructions
Check if the tiller plate backlight is controlled with the pedestal lighting knob and works correctly. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Pleasure0102** [comment]
it sucks (i am joking, delete me imenes :D)

**Review by theomessin — APPROVED** [review]
LGTM

**Comment by Samueleonard** [comment]
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: 25/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3684
Tier of testing: 1
Changes to observe: tiller lighting turns on with pedestal integ lights
Testing technique: Tryout

Steps you've made to test the Pull Request:
1. loaded in
2. turned off ped integ lights, confirmed tiller was dark
3. turned on ped integ lights, tiller lighting came on

Flight notes (When done a full flight):
N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
image
tiller lighting on with integ lights

Issues (If Any): Write any issues
N/A

Steps to achieve the issue
N/A

Overall Rating: Good

Conclusions of the testing: small and quick change, LGTM

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 25.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3684
Tier of testing: 1
Changes to observe: Tiller light
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat and ext. power
3.) Test tiller lighing by turning INTEG LT knob

Off and dim to bright

Issues: More black screen flicker than normal

Overall Rating: -

Conclusions of the testing: Function works. Black screen flickering is maybe unrelated to this PR...?

Hope this helps :-)

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 25/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3684 
Tier of testing: 1
Changes to observe: Tiller lighting
Testing technique: 
Steps you've made to test the Pull Request:
1. Loaded up at night
2. checked lighting of tiller degree plate

Media:

Issues (If Any): - 

Overall Rating: LGTM

Conclusions of the testing: Works

**Review by anel86 — APPROVED** [review]

**Pull request merged**
