### PR TITLE
fix(efb): simbridge remote setting fix

### LINKED ISSUE #7933: Remote Simbridge does not reset if enabled then disabled
### Aircraft Version

Development/Experimental

### Describe the bug

If you set the simbridge host machine to a remote PC, enter a custom IP, then disable the remote simbridge feature (i.e. localhost only), local simbridge will no longer work.

To restore it, you must reenable remote simbridge, enter ``localhost`` as the IP address, then disable remote simbridge.

### Expected behavior

Remote Simbridge toggle restores local simbridge without having to override the IP address manually (workaround)

### Steps to reproduce

1. Open EFB Settings Page > Sim Options 
2. Select ``Remote PC`` for the Simbridge Host Machine option
3. Enter a custom IP for Simbridge
4. Select ``This PC`` for Simbridge Host Machine
5. Start local simbridge
6. Simbridge will no longer connect if hosted locally

To fix: 

7. Select ``Remote PC`` for the Simbridge Host Machine option
8. Rename the custom IP back to ``localhost``
9. Select ``This PC`` for Simbridge Host Machine
10. Start local simbridge
11. Simbridge (local) will now work as per normal (use EFB setting to force connection if it has timed out).

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

2Cas#1022

### PR DESCRIPTION
**Pull request by DevonDF**
Fixes #7933

## Summary of Changes

Added extra logic to the getSimBridgeUrl() function to default to 'localhost' for the IP address when the SimBridge is in local mode rather than remote. This way, a user switching between 'This PC' and 'Remote PC' under the FlyPad Sim Options doesn't need to manually change the IP to 'localhost' for local SimBridge to work and can retain the saved IP for switching back.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Load into Aircraft on runway
- Start SimBridge server
- Observe that SimBridge connects automatically (assuming correct settings)
- Open Remote MCDU or any other means of testing SimBridge connection
- Go to FlyPad -> Settings -> Sim Options -> Set 'SimBridge Host Machine' to 'Remote PC' and enter a bogus IP address below
- Observe that SimBridge connection disconnects (Remote MCDU stops working)
- Go to FlyPad -> Settings -> Sim Options -> Set 'SimBridge Host Machine' to 'This PC'
- Observe that SimBridge reconnects as intended (Remote MCDU starts working again)
- Go to FlyPad -> Settings -> Sim Options -> Set 'SimBridge Host Machine' to 'Remote PC' and observe the IP address is retained 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by brewers10** [comment]
Quality Assurance Tester Report

Discord: brewers_10#5706
Object of testing: #7989 
Tier of Testing  : 1
Date: 09/05/2023

Testing Process: 
Load into Aircraft on runway - **OK**
Start SimBridge server - **OK**
Observe that SimBridge connects automatically (assuming correct settings) - **OK**
Open Remote MCDU or any other means of testing SimBridge connection - **OK**
Go to FlyPad -> Settings -> Sim Options -> Set 'SimBridge Host Machine' to 'Remote PC' and enter a bogus IP address below - **OK**
Observe that SimBridge connection disconnects (Remote MCDU stops working) - **OK**
Go to FlyPad -> Settings -> Sim Options -> Set 'SimBridge Host Machine' to 'This PC'
Observe that SimBridge reconnects as intended (Remote MCDU starts working again) - **FAIL**
Go to FlyPad -> Settings -> Sim Options -> Set 'SimBridge Host Machine' to 'Remote PC' and observe the IP address is retained - **OK**

Negatives:       
When I set the SimBridge Host Machine back to "This PC" remote MCDU did not start working again.

Testing Results: 
Not Passed

Conclusions: 
Just that one issue, other than that all is well.

**Comment by DevonDF** [comment]
@brewers10 I wasn't able to replicate the failure. However, I've added another commit that should hopefully speed-up the time it takes for the reconnection of SimBridge incase this was the issue. It typically took around 2-5 seconds for the connection to re-establish after changing settings.

**Comment by brewers10** [comment]
> @brewers10 I wasn't able to replicate the failure. However, I've added another commit that should hopefully speed-up the time it takes for the reconnection of SimBridge incase this was the issue. It typically took around 2-5 seconds for the connection to re-establish after changing settings.

Ok thanks, I’ll have another go this evening.

**Comment by brewers10** [comment]
Quality Assurance Tester Report

Discord: brewers_10#5706
Object of testing: #7989 
Tier of Testing  : 1
Date: 09/05/2023

Testing Process: 
Load into Aircraft on runway - **OK**
Start SimBridge server - **OK**
Observe that SimBridge connects automatically (assuming correct settings) - **OK**
Open Remote MCDU or any other means of testing SimBridge connection - **OK**
Go to FlyPad -> Settings -> Sim Options -> Set 'SimBridge Host Machine' to 'Remote PC' and enter a bogus IP address below - **OK**
Observe that SimBridge connection disconnects (Remote MCDU stops working) - **OK**
Go to FlyPad -> Settings -> Sim Options -> Set 'SimBridge Host Machine' to 'This PC'
Observe that SimBridge reconnects as intended (Remote MCDU starts working again) - **OK**
Go to FlyPad -> Settings -> Sim Options -> Set 'SimBridge Host Machine' to 'Remote PC' and observe the IP address is retained - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Sorry for the prior test, I had mistakenly installed the latest experimental version alongside your PR: which made it not work. 

It works as is expected now!

LGTM - let's merge!

**Comment by Benjozork** [comment]
@DevonDF Can you add a changelog entry? When that is done, we can merge 😄

**Comment by DevonDF** [comment]
@Benjozork Done :)

**Pull request merged**
