### PR TITLE
[LIGHTS] Flickering Issue | Fixed

### LINKED ISSUE #1286: [BUG] [MSFS 1.9.5] Flickering lights in the cockpit
**Mod Version**

master @ 16f5d53

**Describe the bug**

https://cdn.discordapp.com/attachments/738864300818432023/765597295022309406/2020-10-13_17-29-48.mp4

**To Reproduce**
1. Load in a flight
2. Observer cockpit is flickering

**Was this working before/when did the issue start occurring?** After MSFS 1.9.5.

**Is this a problem in the vanilla unmodded game?** No.

Discord username (if different from GitHub): someperson#4953

### PR DESCRIPTION
**Pull request by Snapmatics**
Fixes #1286 

## Summary of Changes
- The flickering issue caused by the screen-blue lights has been fixed.

Discord Username: `Harry ✈#0001`

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The `build.py` will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by armankir** [comment]
Works.

**Review by lukecologne — APPROVED** [review]
Fixes the issue, LGTM

**Comment by 2hwk** [comment]
Testing, will report back.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 13/10/2020
Version of the sim: 1950
PR Tested: #1287

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane C&D
2. Looked for flickering


Overall Rating: Good
Conclusions of the testing:Fixes the issue. Looks good to me! Thank you for your work!

**Pull request merged**
