### PR TITLE
Change pitchPID + headingPID to default values

### PR DESCRIPTION
**Pull request by Saschl**
## Summary of Changes

Reverts the values for headingPID introduced by #2140 to the default Asobo values as the Asobo AP has been fixed in the last update (correct me if I'm wrong). Also the value for pitchPID has changed, which is ported now.

Maybe this also improves behaviour with the deadzones but this is just speculations for now..(I did a complete flight without deadzones set but this could be a random success :D )

## References
Vanilla files

Discord: saschl#9432

## Testing instructions
Do a flight and check that the AP is not doing any weird things (going off course, spiraling..)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by pepperoni505 — APPROVED** [review]
LGTM

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 31/12/2020 (Happy New Year by the way)
Version of the sim: 1.12.13.0
PR Tested: #2819 
Object of test: PID reversions

Testing technique:  Full Flight from LEMH to EGGD on VATSIM - livestreamed
Steps you've made to test the Pull Request:
1. Spawned C & D at Mahon LEMH
2. Set up aircraft for flight using Simbrief integration
3. Departed, flew to Bristol
4. Descended using selecting altitude mode, flew the NDB ILS procedure and made use of speedbrakes, and a steep NDB procedure turn at EGGD
5. Flew ILS - flew manually from 1000ft - landed

Flight notes (If required):
Routing LEMH MERO3D MEROS UN853 LUMAS UM976 CLM DCT MEBAL DCT KESAX UT421 KUNAV T421 BIG UL9 CPT BRI1C EGGD

Issues (If Any):  None at all
Overall Rating: Good 
Conclusions of the testing: All worked exactly as expected - no issues found during entire full flight.

**Comment by iamdefective1** [comment]
Category: QA Tester
Name: IAMDEFECTIVE1#9293
Date of testing: 31/12/20
Version of the sim: 1.12.13.0
PR Tested: #2819
Object of test: PID rework

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Complete a flight
2. Observe ND.

Flight notes (If required):
DCT BERGI L602 SUPUR L60 OTBED ROSU1F

Screenshots: 
image
image
image
image


Issues (If Any): When cornering waypoints, plane deviates. See screenshots
Overall Rating: Small Improvements needed
Conclusions of the testing: plane is shown to deviate flightplan while making corners

**Comment by pepperoni505** [comment]
Can someone check if there is any oscilation

**Comment by Saschl** [comment]
@iamdefective1 thanks for the test! Does it correct itself after some time? And do you know if it happens also with the latest dev?

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 31/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2819
Object of test: Test PID value changes
Testing technique: Full flight

Steps you've made to test the Pull Request:
1. Spawned at VOBL, C/D
2. Turned on battery, external power. Prepared the aircraft for a normal IFR flight
3. Departed out of RWY 09L 
4. Flew IFR to VABB
5. ILS 27 approach into VABB
6. Landed with no issues



Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: The flight was pretty stable overall. There weren't any abnormalities with the AP.

**Comment by BritishAvgeek** [comment]
> Can someone check if there is any oscilation

I had NO oscillation at all during my entire 3 stream earlier - 2 hour flight time and it was bang on the entire way

**Comment by BritishAvgeek** [comment]
> Thanks for the test! Does it correct itself after some time? And do you know if it happens also with the latest dev?

Looks like he's selected 10nm range mode so small differences will show up but he's also turned on a waypoint with crosswind - the bird at the top suggests he'd make it back on track.

During my test flight earlier I had tail winds and a crosswind and a headwind too and at no point did it struggle to fly the line

**Comment by Saschl** [comment]
Yup that makes sense, thanks. I had the same experience @BritishAvgeek.  I’m just curious if the little deviation also happens with the current dev version. Different winds etc. make a comparison a bit harder.

**Comment by crisk73** [comment]
Unless a waypoint is published as a fly-over type the plane should not pass through it but leave it aside (fly-by type). In fact the true depiction of the turn band should be slightly curved and not angled. So the shown behavior might be correct in my opinion. I agree that current dev should be tried as well to see if it's the same.

**Comment by iamdefective1** [comment]
> Thanks for the test! Does it correct itself after some time? And do you know if it happens also with the latest dev?

for me, it happened with the lasted dev version.
It did correct itself, but it didnt fly the exact line, it made a sharp left and kept at a heading to capture the line again.

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919
Date of testing: 1/2/2021
Version of the sim: 1.12.13.0
PR Tested: #2819
Object of test: Auto Pilot

Testing technique: Tried out
Steps you've made to test the Pull Request:
1. Spawned C&D at KSEA
2. Full Flight to KSFO
3. Moniterd ND and FD to make sure I was not going off track
4. Landed at KSFO with no issues

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Looks good to me did a full flight with no issues. Keep up the good work.

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 03/01/2020
Version of the sim: 1.12.13.0
PR Tested: #2819
Object of test: PID reversions - TEST 2

Testing technique: Full Flight from EGCC to LGMK on VATSIM - livestreamed
Steps you've made to test the Pull Request:

1. Spawned C & D at Manchester EGCC
2. Set up aircraft for flight using Simbrief integration
3. Departed and flew to Mykonos - half way got ATC climb to FL370 for traffic avoidance
4. During most of the cruise I had a varying 20-50kt crosswind component - aircraft dealt with it fine, no more than 0.5nm drift off track line
5. Descended according to planned route - over Athens got a direct to STAR entry for the VOR Z 34 - planned for VOR Y so amended MCDU - no issues
5. Flew the VOR Z 'teardrop' and positioning to a manual visual landing for Runway 16

Flight notes (If required):
Routing LISTO1S LISTO HON L15 BIG UL9 KONAN UL607 KOK M150 PITES DCT EDISA/N0454F370 DCT UTABA DCT IRBIR DCT UMVEG DCT VEKEN DCT SABAD DCT NERRA DCT PETAK DCT PINDO UL607 KEA R19 VARIX VARI1P 

Issues (If Any): None at all
Overall Rating: Good
Conclusions of the testing: All worked exactly as expected - no issues found during entire full flight. During the variable crosswind it behaved as expected and had no issues with pitch or heading.

I altered the weather a few times between UnrealWeather and MSFS live Wx too to get the "violent wx change" we get when switching between the two specifically to see if it would throw it off a lot and cause issues. After a few seconds, aircraft stabilised and all readings stayed normal and as expected

**Pull request merged**
