### PR TITLE
feat: improved interior lights

### PR DESCRIPTION
**Pull request by Snapmatics**
# Summary of Changes
The following PR changes the overall interior lighting of the aircraft, including a few text positioning fixes.

## Interior Lighting

- [ ] Reduce Pedestal Lighting
- [ ] Reduce DOM Lights
- [ ] Reduce Flood Lights
- [ ] Increase "Table" Light
- [ ] Console/Floor Light

## Interior Light Fixes
- [ ] Position of FCU Text

# How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
2. Click on the Checks tab on the PR
3. On the right side, click on the Artifacts drop down and click the A32NX link

### CODE REVIEW

**Comment by mikecbr** [comment]
Is this pr working on the lights  of the main panel flood ? Lowest setting it's so much..... also most of the knobs shouldnt have settings to adjust it , it should twist like the speed knob or the HDG knob

**Comment by wpine215** [comment]
Is this still in progress or can it be closed?

**Comment by Snapmatics** [comment]
> Is this still in progress or can it be closed?

In-progress from my side, just not pushed yet.

**Comment by Snapmatics** [comment]
> > Is this still in progress or can it be closed?
> 
> In-progress from my side, just not pushed yet. I was waiting for some references from komp.

**Comment by Benjozork** [comment]
Is this still relevant?

**Pull request closed without merging**
