### PR TITLE
fix: correct FCU ALT Increment Selector emissive behaviour

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

- FCU  ALT Increment Selector emissive now adjustable by panel lighting brightness knob

No changelog added since this builds on top of #3295 

## Screenshots (if necessary)

https://user-images.githubusercontent.com/71195324/107670240-d33dcd80-6c92-11eb-921e-856f357198bd.mp4

## References
Thanks to komp, we now know that the selector is backlit so I added the emissive back and tied it to the rest of the panel lighting so it is not on with no power. 

(This is the QNH knob, but the selector notch is backlit on both in the same fashion)  
image

Discord username: Imenes#8739

## Testing instructions
Check the behavior of the altitude increment selector switch emissive. Should be off with no power and you should be able to adjust its brightness with the rest of the FCU backlights. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by beheh — APPROVED** [review]

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 12.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3471 
Tier of testing: 1

### Changes to observe: ALT Increment Selector emissive behaviour

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned C/D at VABB gate 4
2. Turned on external power, batteries
3. Turned on DOME lights
4. Checked FCU ALT Selector illumination
5. Turned up the FCU Panel brightness and checked again.

### Media:
image
image

### Issues (If Any): None

### Overall Rating: Good

### Conclusions of the testing: Short PR, checked and works as expected. Good to go!

**Comment by tino135** [comment]
ImenesFBW:master

**Comment by tino135** [comment]
ImenesFBW:master.diff

**Comment by marcman86** [comment]
Name: marcman86
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested:  #3471
Tier of testing: 1
Changes to observe: FCU ALT Increment Selector emissive goes with rest of panel
Testing technique: Tryout

Steps you've made to test the Pull Request:

1.) Spawn C&D EDDP
2.) Without power no lights, no matter what position of the dimming knop
3.) Turn on Bat.
4.) Panel light off (Image 1), dim (Image 2) and up to no dimming (Image 3)

Media:


Image1


Image2


Image3

Issues (If Any): None

Overall Rating: Good

Conclusions of the testing: Looks good! Gives visualisation of selector state in the dark. Behaves like rest of the panel illumination.

Hope this helps :-)

**Pull request merged**
