### PR TITLE
changed roughness map of glareshield

### PR DESCRIPTION
**Pull request by Pleasure0102**
Fixes #[issue_no]

**Summary of Changes**

Changed roughness map of glareshield (A320NEO_COCKPIT_MAINPANEL_COMP.PNG.DDS) 

**Screenshots (if necessary)**

Before:
image
After:
image

**Additional context**

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by NathanInnes** [comment]
Looks good

**Comment by Benjozork** [comment]
Hello, please take note that we have started including a CHANGELOG.md file that requires every PR to add a change-log line that describes its changes. As your PR is not merged yet, we kindly ask that you add this information following the included directives in the file.

Disclaimer: This is a copy-and-pasted message.

**Comment by AdenFlorian** [comment]
please make your before and after screenshots have the same context/settings/angle/size so we can more easily tell what changed, and provide a reference pic

**Comment by Pleasure0102** [comment]
Before (dark):
image
After (dark):
image
Before (daylight):
image
After (daylight):
image

Reference Pics:
image
image

**Comment by DarkOfNova** [comment]
The patchy roughness is removed which is correct, however, I still think it should be a little more reflective. Not much but just a little @Pleasure0102

**Comment by Pleasure0102** [comment]
hope i did it correctly should be new version now

**Review by DarkOfNova — APPROVED** [review]
Works as expected removing patchy roughness from the bottom of the glareshield and adds more reflectivity matching its real-life counterpart. Approved and ready to be merged.

**Comment by ImenesFBW** [comment]
Some more after pics.
Screenshot (301)
Screenshot (302)
Screenshot (306)


Looks cool to me. Thanks you!

**Pull request merged**
