### PR TITLE
Fix radio altimeter only updating every second

### LINKED ISSUE #1098: [BUG] Radio altimeter only updates every second
**Mod Version**

Master

**Describe the bug**

Radio Altimeter only updates every second

**To Reproduce**

1. Start on runway
2. Take off
3. Watch the radio altimeter

**Expected behavior**

Radio altimeter updates every five/ten feet depending on altitude

**Actual behavior**

Radio altimeter only updates every second

**References**

grafik

**Additional context**

* Got a fix coming up

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes #1098 

**Summary of Changes**

* Radio altimeter now updates properly

**Screenshots (if necessary)**

**Additional context**

* It looks like Asobo has implemented caching behaviour in Simplane.getAltitudeAboveGround() in 1.9.3 which causes the radio altimeter to only update every second. This forces a simvar call every time the Simplane method is called.

### CODE REVIEW

**Comment by NathanInnes** [comment]
Include changelog please

**Comment by starvingjavi** [comment]
Give instructions on how to test

**Comment by Meqolo** [comment]
It should be pretty obvious what, and how to test. Just check the radio altimeter actually updates more than once a second

**Comment by Carter633** [comment]
I'll take a look - it's quite an easy test to be fair! I'll run a flight from cold and dark as I always do.
Discord: Carter633 #1436

**Review by Carter633 — APPROVED** [review]
Name: Carter633 #1436
Date of testing: Current date 05/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1099

Testing technique: 2x Full flight from Cold and Dark
Steps you've made to test the Pull Request:
1. Ran a short flight from cold and dark, then flew Malaga to Gatwick from cold and dark also
2. Started at the gate, took off and checked RAD ALT increase during initial climb after taking off
3. put AP on early to trigger the bug which pushes the nose down - got 'don't sink' and also Rad Alt decreases
4. continued flight and checked during final approach and landing.

Overall Rating: Good
Conclusions of the testing: Works as described

**Comment by HugoTro** [comment]
Name: Hugo #3307
Date of testing: Current date 05/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1099

Testing technique: Spawning in approach
Steps you've made to test the Pull Request:

1) spawned in approach of rwy 03 at LFRS (set only the arrival to spawn in approach)
2) descended faster than normal (with 27 kts of crosswind too) and the radio altimeter was updating faster than once a second

Overall Rating: Good
Conclusions of the testing: Works as described

**Comment by lukecologne** [comment]
> 
> 
> Include changelog please

Done

**Pull request merged**
