### PR TITLE
fix: Adjust landing gear suspension to be stiffer

### PR DESCRIPTION
**Pull request by wpine215**
## Summary of Changes

Decreased static compression, increased max/static compression ratio, and increased damping ratio closer to 1 for landing gear contact points.

## Screenshots (if necessary)

N/A

## References

https://aviation.stackexchange.com/questions/30583/how-much-does-the-landing-gear-compress-on-a-fully-loaded-airliner-on-the-ground - which uses references from the official Airbus aircraft characteristics for airport planning document.

Discord username (if different from GitHub): Iceman#5540

## Testing instructions

Attempt a high-speed taxi, regular take-off, rejected-take-off, and landing, all while observing the steering capabilities of the aircraft. The steering handling should be slightly improved, since the suspension has been altered to be stiffer based on the above documentation/references.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: 31/1/2021
Version of the sim: 1.12.13.0
PR Tested: #3251 
Tier of testing: 1

Changes to observe:

-  Steering handling improvement.

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Tested steering during high speed taxi.
2. Tested steering regular take-off.
3. Tested steering RTO. 
4. Tested steering after landing and vacating. 

Flight notes: N/A

Media: N/A

Issues: N/A  

Overall Rating: Good
Conclusions of the testing: I really like this one, it makes the ac more stable on the taxiline/centerline unlike before where it sometimes go all over the place, great job.

**Comment by donstim** [comment]
I've been looking into this for a while myself, and although I am certainly no expert in this area, I don't think the numbers you are using are correct. Or at least, they aren't consistent with the description of the variables in the flight_model.cfg file. I also think there are some other default values in the same line that are incorrect and should probably be changed at the same time. However, there is also the matter of having accurate values and having the result provide an accurate "feel." While I am at the point of suggesting accurate numbers, I haven't done enough testing to know whether or not their use in the sim will result in accurate ground handling, including taxi, takeoff, landing touchdown, ground accel/decel, and turning capability.

With those caveats, here is what I think accurate values for the parameters should be:
The static compression is defined as the distance the landing gear is compressed when the airplane is empty. In the reference you provided, the empty airplane heights are in the column labeled 41,000 kg. I think this should be compared to the heights shown for when the airplane is supported on jacks (the rightmost column) to get the static compression value. For the nose gear, if you use point F1 as the point on the fuselage nearest the nose gear, the static compression would be 7.97-5.97=2.0 feet. For the main gear, using point BF1, the value would be 7.41-5.64=1.77 feet.  Seems like a lot compression for an empty airplane, but isn't that the correct way to do it -- i.e.,, compare it to the airplane supported by jacks?

For the max to static compression ratio, the max compression would be the highest additional compression at max ramp weight divided by the static compression. For the nose gear, this would be (5.97-5.64+2.0)/2.0=1.65. For the main gear, it would be (5.64-5.25+1.77)/1.77=1.22.

The other default values in the contact point lines are the distance from the nose of the airplane to the tail, the distance from the nose to the main gear (actually tire contact point), the distance between the nose and main gear, and the wheel radii. From the same airplane planning document you referenced the distance between the nose and tail of the airplane should be 123.27 feet. In looking at the contact points on the model, I think the tail contact point is "more correct" in comparison to the model than the nose contact point. So, I propose the longitudinal component of contact pont 6 be changed from 45 to 44.07 (123.27-79.2). The nose gear contact point should be 16.63 ft behind the nose and the main landing gear contact point should be 41.47 feet behind the nose gear contact point. This would mean the longitudinal value for contact points 0, 1, and 2, should be changed to 27.44, -14.03.and -14.03, respectively.

The same airport planning document also has the wheel sizes. The wheel diameter for the nose gear is 15 inches and for the main gear, 20 inches. The SDK says the values in the cfg file should be the wheel radius. It looks like Asobo used the wheel diameter (though even that is not exactly the right value). So the wheel radius values should be (15/2)/12=0.625 for the nose gear, and (20/2)/12=0.833 for the main gear (instead of 1.53 and 1.68.

Lastly, due to the above changes (I think), the tires appear to be partly sunk into the ground. To fix that, I propose changing the vertical position of the nose and main gear contact points from -9.3 and -9.58, respectively, to -10.2 and -10.0.

The contact points would then look like this (with changes to 0, 1, 2 and 6:
point.0 = 1, 27.44, 0, -10.2, 800, 0, 0.625, 75, 2.0, 1.316, 0.9, 10.6, 9.4, 0, 0, 0, 2
point.1 = 1, -14.03, -14, -10.0, 1200, 1, 0.833, 0, 1.77, 1.22, 0.86, 11.1, 9.9, 2, 0, 0, 2
point.2 = 1, -14.03, 14, -10.0, 1200, 2, 0.833, 0, 1.77, 1.22, 0.86, 11.1, 9.9, 3, 0, 0, 2
point.3 = 2, -26, -57, 6, 100, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 1
point.4 = 2, -26, 57, 6, 100, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 1
point.5 = 2, -79.2, 0, 8, 100, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 1
point.6 = 2, 44.07, 0, 2, 720, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 1
point.7 = 2, -68, 0, 4.1, 100, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 1
point.8 = 2, -75.2, 0, 32.3, 100, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 1

Feel free to use or ignore any portion of this comment!

**Comment by wpine215** [comment]
> Feel free to use or ignore any portion of this comment! And if you need me to post screenshots of the specific pages of the airport planning document to support the dimension and wheel size info, just let me know.

Went ahead and incorporated these changes. @Lazarus320 - feel free to re-test this and record your observations with these new changes.

**Comment by wpine215** [comment]
Just an update - it seems the landing gear heights with the change need a bit of tweaking. Currently seem to be floating in the sim.

image

Otherwise, I ran a quick test and the ground handling still seems improved over the current development branch and my previous iteration of this PR.

**Comment by sidnov** [comment]
Waiting for the next commit :excited:

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 31.1.2021
Version of the sim: 1.12.13
PR Tested: #3251
Tier of testing: 1
Changes to observe:Steering handling

Testing technique:tested?
Steps you've made to test the Pull Request:
1. tested steering while high speed taxiing 
2. tested steering during takeoff
3. tested steering while landing


Flight notes (When done a full flight):


Issues (If Any):none

Overall Rating: Good
Conclusions of the testing:Works as expected. Steering feels better and more sable now. Thanks for the Pr!

**Comment by Lazarus320** [comment]
> Went ahead and incorporated these changes. @Lazarus320 - feel free to re-test this and record your observations with these new changes.

@wpine215 Just re-tested and it actually handles a lot better now. 👍

**Comment by SaqibSiddiqi** [comment]
Category: QA Tester/Trial
Name: Discord User AssassinXpq#1079
Date of testing: Current date 31/1/2021
A version of the sim: 1.12.13.0
PR Tested: 3251
Tier of testing: 1
Changes to observe :  Steering handling improvement.

Testing technique: Ran timed test of steering High-speed taxi, RTO, takeoff, the landing of real-life neo, non-pr build and pr build
Steps:
Real Life:
	@EGKK
	Taxi = 11.35 seconds
	The lineup for takeoff = 17 seconds
	RTO not found
	@EKCH
	Landing = 5.80 seconds
Non-Pr Build:
	@EGKK
	Taxi = 8.20 seconds
	Lineup = 12.2 seconds
	RTO = 6.8 seconds
	Landing = 5.7 seconds
Pr Build
	@EGKK
	Taxi = 10 seconds
	Lineup = 15 seconds
	RTO = 4 seconds
	Landing = 5 seconds
	NOTE: Rounded Off PR build-time values to the lowest due to forgetting to record flight
	
Time Accuracy give or take 1 second

Non-Pr build - @30 knots required 100% rudder input for 6 seconds to complete turn
Pr build - @30 knots required 100% rudder input for 10 seconds to complete turn
(Used Joystick Gremlin to calculate Values)

Plus All wheels touching the ground, an issue brought up before


Flight notes (When done a full flight): EGKK DCT EGLL

Media: 
Real Life A320NEO: https://www.youtube.com/watch?v=XfhQu7GEQZM | https://www.youtube.com/watch?v=b7YfxSxJWzs
Real Life A320: https://www.youtube.com/watch?v=CHlO6bsjln4

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: PR build simulates better handling after confirming using time test. The plane is now more controllable during TAXI operations

**Review by pepperoni505 — APPROVED** [review]

**Review by nelsondani — COMMENTED** [review]
[15999]()

**Pull request merged**
