### PR TITLE
New custom-ish default views

### LINKED ISSUE #1486: [REQUEST] New default cockpit view / seat position
**Describe the feature you'd like to see implemented**

Default seating position is way too low and too far back. I would like to see the default cockpit view/seat position to be adjusted according the real seat flight position. Like the screenshot below. I adjusted to match with the seating position balls in the middle. Glareshield model is a bit off, thats why I couldnt put it like I do IRL. But this is a way better and more realistic view onto the instruments

**References**

Before
image
After
image

**Additional context**

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by ZigTag**
Fixes #1486

## Summary of Changes
This is a overhaul of some of the default views. 

Checklist:
- [x] Pilot
- [x] First Officer
- [x] ECAM
- [x] PFD
- [x] Overhead
- [ ] Pedestal
- [ ] MCDU
- [ ] Radios

## Screenshots (if necessary)

Before

After

Current Views (Some are **not** new):

## References

#1486

Will add screenshots from discord as well

## Additional context

Discord username (if different from GitHub): Falcon#5815

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by St54Kevin** [comment]
Good work. Pilot and FO view just need a bit more FOV so you are able to see/control the whole FCU (until VS knob). For me thats one mouse wheel click zoom out. You can then also readjust pitch so that the lower PFD border lines up again. Makes the horizon feel a bit more natural. Then the view would be perfect. Im on 1440p 16:9

**Comment by ZigTag** [comment]
Will do, thanks for letting me know.

**Comment by Lessar277** [comment]
Just going out on a limb here, but could cabin views (the ones overlooking the engines/wings from the inside) be added as well somehow? Or is this out of scope for this PR? I know they can be added manually, but having them by default would be more comfortable, and surely better than switching to the showcase cam.

**Comment by ZigTag** [comment]
I'll look into it, shouldn't be a problem problem though

**Comment by St54Kevin** [comment]
Just tested the new views. I really like them now Pilot and copilot views are perfect as long as you have default view settings in MSFS options (height 50). I wouldnt create new ones for Radios, MCDU, overhead etc. They are already perfect. Except Upper and Lower Pedestal. I would Merge them into one so you can see the whole Pedestal. Splitting them into lower and upper is not necessary. 
So I´m for merging this. Pilot View was the most important one!

**Comment by lukecologne** [comment]
I just tested this a bit, and I also really like the changes. LGTM!

**Pull request merged**
