### PR TITLE
[PFD] PFD Rework

### PR DESCRIPTION
**Pull request by lukecologne**
## Summary of Changes

* I plan on redoing the PFD as an SVG in the HTML, without creating elements in JS. 
* Currently no changes, I'm still in the process of creating the SVG.

Credit to https://bitbarrelmedia.wordpress.com/2017/11/01/real-time-efis-vector-graphics/ for reference images.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by stevex77** [comment]
@lukecologne could you please review / take in account this issue https://github.com/flybywiresim/a32nx/issues/1813 I've reported 3 days ago? Under some environment lighting conditions and with brightness set between 50 % and 100 %, some PFD parts seem to be "overexposed", therefore some information (especially on tapes) is hardly readable. Thanks.

In any case, I look forward to testing your work.

Btw. Do you expect any performance footprint / gain of this rework?

**Comment by lukecologne** [comment]
At the moment I'm just creating the SVG, no styling. I'll definetely test the visibility of the display, but it may be difficult to tune it for all situations. About the performance improvement: We'll see. At the very least it won't be worse than previously, but I hope it will look much better. Also, this will make it more accessible and easy to edit down the road, maybe even for the A380.

**Comment by MisterChocker** [comment]
@lukecologne @stevex77 mfs lighting conditions are having a huge impact on the brightness of the screen. The only way (I currently know) is adjusting the brightness via the knobs. So for daylight 1 is perfectly fine, but in the night, 0.5 to 0.2 are a good range depending on light conditions again.

**Comment by MisterChocker** [comment]
I hope this change #2003 isn't conflicting with your work, if so, please go ahead and tell me how to continue.

**Comment by MisterChocker** [comment]
| Currently: | How it should be |
| ----- | ----- |
| image | image |

**Comment by lukecologne** [comment]
Closing in favor of #3049.

**Pull request closed without merging**
