### PR TITLE
fix: Optimized/fixed strobe handling in aircraft presets

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes
This PR optimizes/fixes strobe handling in Aircraft Presets

Discord username (if different from GitHub): Cdr_Maverick#6475

## Testing instructions
Preset "Cold & Dark" - Strobe should be OFF
Preset "Powered", "Ready for Pushback", "Ready for Taxi" - Strobe should be AUTO
Preset "Ready for Take Off" - Strobe should be ON

Switching between Presets should always result in the correct Strobe setting.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by brewers10** [comment]
Quality Assurance Tester Report

Discord: brewers_10#5706
Object of testing: #8008 
Tier of Testing  : 1
Date: 09/05/2023

Testing Process: 
Preset "Cold & Dark" - Strobe should be OFF - **OK**
Preset "Powered", "Ready for Pushback", "Ready for Taxi" - Strobe should be AUTO - **OK,FAIL,FAIL**
Preset "Ready for Take Off" - Strobe should be ON - **OK**

Switching between Presets should always result in the correct Strobe setting. - **INCONSISTENT**

Negatives:       
The strobe light behaves as expected when selecting Cold and Dark and Powered and R.F Takeoff presets. However the issue is when the R.F Pushback and R.F Taxi presets are selected the strobe lights are switching ON. 

Testing Results: 
Not Passed

Conclusions: 
Just 2 presets to look at.

**Comment by frankkopp** [comment]
> Quality Assurance Tester Report
> 
> Discord: brewers_10#5706 Object of testing: #8008 Tier of Testing : 1 Date: 09/05/2023
> 
> Testing Process: Preset "Cold & Dark" - Strobe should be OFF - **OK** Preset "Powered", "Ready for Pushback", "Ready for Taxi" - Strobe should be AUTO - **OK,FAIL,FAIL** Preset "Ready for Take Off" - Strobe should be ON - **OK**
> 
> Switching between Presets should always result in the correct Strobe setting. - **INCONSISTENT**
> 
> Negatives: The strobe light behaves as expected when selecting Cold and Dark and Powered and R.F Takeoff presets. However the issue is when the R.F Pushback and R.F Taxi presets are selected the strobe lights are switching ON.
> 
> Testing Results: Not Passed
> 
> Conclusions: Just 2 presets to look at.

I can not reproduce this - this works fine for me - see video. 
Can you please check your test method and describe in more detail how you tested?
https://youtu.be/iWWd2c5nwlc

(Btw. the numbers are use in the LVAR debug correspond to the presets 1-5 (Cold&Dark, Powered, ..., Ready for TakeOff)

**Comment by brewers10** [comment]
Quality Assurance Tester/Trainee Report

Discord: brewers_10#5706
Object of testing: #8008 
Tier of Testing: 1
Date: 09/05/2023

Testing Process: 
Preset "Cold & Dark" - Strobe should be OFF - **OK**
Preset "Powered", "Ready for Pushback", "Ready for Taxi" - Strobe should be AUTO - **
OK**
Preset "Ready for Take Off" - Strobe should be ON - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Sorry about yesterday's test, I was using the experimental version of the A32NX as well as your PR, hence why it wasn't working. It's all working fine now! 

LGTM- Let's Merge!

**Comment by frankkopp** [comment]
> Quality Assurance Tester/Trainee Report
> 
> Discord: brewers_10#5706 Object of testing: #8008 Tier of Testing: 1 Date: 09/05/2023
> 
> Testing Process: Preset "Cold & Dark" - Strobe should be OFF - **OK** Preset "Powered", "Ready for Pushback", "Ready for Taxi" - Strobe should be AUTO - ** OK** Preset "Ready for Take Off" - Strobe should be ON - **OK**
> 
> Negatives: N/A
> 
> Testing Results: Passed
> 
> Conclusions: Sorry about yesterday's test, I was using the experimental version of the A32NX as well as your PR, hence why it wasn't working. It's all working fine now!
> 
> LGTM- Let's Merge!

Cool, thanks for re-testing. Glad it worked out!

**Pull request merged**
