### PR TITLE
[ECAM] Stop updating the ECAM pages twice

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

Right now, the EICAS/ECAM code is shared between the lower and the upper DU. This is mostly fine, except for updating pages when it's not needed. Most critically, `getActiveFailures` calls a lot of simvars to check the active ECAM failures, and is run from the bottom screen. This is completely unnecessary. My upcoming PR on the FWC #1943 also runs twice without this.

Note that while testing, in some cases I've seen the new page briefly flash with old data. This issue existed previously, and the inactive pages were never updated previously. This change purely disabled:

- the top ECAM screen being silently refreshed the bottom screen
- the bottom page being silently refreshed the top screen

I'm not sure this is worth a CHANGELOG entry - it's hidden to users, but may have a slight performance improvement.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by beheh** [comment]
While I'm touching the files, I've dropped two remaining source map comments that were missed in #1651.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
For QA: Do a full flight paying particular attention to ECAM usage

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 16/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1965 
Object of test: ECAM

Testing technique: Flight from ENGM to ESGG
Route: -ENGM/19R F290 OKSAT6D OKSAT L996 KELIN KELIN2T ESGG/21
Steps you've made to test the Pull Request: 
1. load up A/C Cold and Dark
2. Programmed MCDU
3. Fly
4. Monitored the ECAMs

Issues (If Any): No issue found
Overall Rating: Good
Conclusions of the testing: I have monitored the ECAMS a lot during flight and switched between the pages. Did not find any issue.

**Pull request merged**
