### PR TITLE
fix: getConstraintAltitude() function crash

### PR DESCRIPTION
**Pull request by SergeySoprykin**
## Summary of Changes

Fixed a crash found while debugging the code. Root cause: negative array index and access to undefined object.
It is unknown how this bug affected a user.

Also moved few lines after return for performance improvement.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Fly an descent/approach (which has constraints) in managed descent mode.
Use the devkit console to observe the error message no longer appears.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by MisterChocker** [comment]
> Also moved few lines after return for performance improvement.

This method is not called very often, it's only called on defined events and therefore not multiple times a second.

It's correct tho to return 0 in case the list is empty.

Please add a changelog.

**Comment by tracernz** [comment]
Just ran into this too when changing runway mid-arrival. LGTM. 👍

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 04/03/2021 (report on 5/3)
Version of the sim: 1.13.17.0
PR Tested: #3784 
Tier of testing: 2
Changes to observe: Check for ConstraintAltitude() function error on approach

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Prepared for a full IFR flight from VABB-VOHS
2. Enabled webui devkit for ND and MFD
3. Observed for any abnormalities on approach
4. Flew a STAR (NAMSA8) for VOR DME Approach 09L with constraints

### Media:
MCDU

### Issues (If Any): None

### Overall Rating: Good

### Conclusions of the testing:
Would have liked a little more on testing instructions to try out multiple scenarios, but with the current methods, looks good to go! :D

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 6.3.2021
Version of the sim: 1.13.17.0
PR Tested: #3784
Tier of testing: 2
Changes to observe: MCDU function crash
Testing technique: Tryout

Steps made to test the Pull Request:



1.) Spawned Runway at EDDP
2.) Took off to EDDB (9000ft)
3.) To EDDB25L APPR
4.) APPR got Alt restrictions
5.) Land

Media:


Image1

Overall Rating: Good

Conclusions of the testing: No red error messages on MCDU at APPR

Hope this helps :-)

**Comment by St54Kevin** [comment]
I am unable to load this PR as it has 10fps for me on ground. Ive crosscheckd couple of times with current cFBW version (55fps) and I can reproduce by installing this PR

**Comment by MisterChocker** [comment]
> @SergeySoprykin I am unable to load this PR as it has 10fps for me on ground. Ive crosscheckd couple of times with current cFBW version (55fps) and I can reproduce by installing this PR

Very likely unrelated to the changes of this pr.

**Comment by St54Kevin** [comment]
> > @SergeySoprykin I am unable to load this PR as it has 10fps for me on ground. Ive crosscheckd couple of times with current cFBW version (55fps) and I can reproduce by installing this PR
> 
> Very likely unrelated to the changes of this pr.

Im switching back and forth to current master and to other PRs and it only happens with this one strangely

**Comment by MisterChocker** [comment]
@St54Kevin I've updated the current one to match master, maybe we had some recent pushes that may improved performance. (Hint, new flight phase manager)

**Comment by St54Kevin** [comment]
@SergeySoprykin Could you please rebase this PR so I can do a proper retest?

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 16/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3784 
Tier of testing: 2
Changes to observe: webkit failures on approach

Steps you've made to test the Pull Request:

This PR is hard to test because of the NAV mode problems on STAR/APPR :D But tried my best to let it fly over waypoints in NAV mode.

1. Loaded up on runway EDDF 25C
2. Made up a continous Flight Plan back to RW 25R
3. Flew approach in managed. It has simple ALT constraints
4. Observed devkit console

Media:
image

Issues (If Any): 
Please check wether this is related: I was not able to open the VERT REV page on approach. In this case they were the DF waypoints on the approach. Im unsure wether this is a problem in current dev 

Overall Rating: LGTM

Conclusions of the testing: no error messages in the dev console. Looks all good

**Pull request merged**
