### PR TITLE
fix: engine oscillations at high temperature conditions

### PR DESCRIPTION
**Pull request by Taz5150**
Fixes #[issue_no]

## Summary of Changes

At some extreme environmental conditions (high altitude airports and high temperatures), the engine oscillated violently. The issue was the internal EGT limiter taking over and not letting the engine go to higher RPMs. The issue has been solved by getting rid if the internal limiter until we have the new EGT limit in the FADEC code.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Go to a high altitude airport (i.e. KDEN)
2. Set engine power to 50% N1 and give it some time for temperature to build up
3. Accelerate to TOGA
4. No more oscillations will be observed

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by myselfaaryan — APPROVED** [review]
GTG! 🚀

**Review by MisterChocker — APPROVED** [review]
LGTM

**Review by aguther — CHANGES_REQUESTED** [review]
Please do not remove the version indicator on the top instead update it. It’s quite helpful to have it.

**Review by aguther — APPROVED** [review]

**Comment by sidnov** [comment]
Category: QA Tester/Contributor
Name: sidnov#8337
Date of testing: 24.04.2021
Version of the sim: 1.15.8.0
PR Tested: #4553 
Tier of testing: 1

### Changes to observe: No more engine oscillations

### Testing technique: Tryout

### Steps made to test the Pull Request:

1. Spawned cold and dark at an airport with fairly high temps. (VAAH in this case)
2. Quickly ran through pre-flight, with APU on, engines on idle.
3. Pushed back and departed after 20 minutes of idling on ground
4. Flew runway heading maintaining 320kts indicated.
5. Observed engine characteristics for any bounce/oscillations

### Media:
image

### Issues:
None

### Overall Rating: Good

### Conclusions of the testing:
The engine oscillations due to limiting in higher temps is fixed. To confirm, I departed from the same airport where I faced this problem yesterday under similar conditions. LGTM: Lets Get This Merged! 😄

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 24/04/2021
Version of the sim: 1.15.8.0
PR Tested: #4553 
Tier of testing: 1
Changes to observe: Check engine oscillations with high temp/high alt conditions

Testing technique: Spawned and tested on the ground
Steps you've made to test the Pull Request:
1. Spawned at SLLP La Paz - 13,300ft approx altitude
2. Checked engine temps and vib
3. Increased throttle to 50% N1, monitored temperature rise for a few mins as requested
4. Accelerated to TOGA, monitored vibrations
5. Restarted the test and increased temp to 32 degrees C and repeated steps above

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): None found

Overall Rating: Good
Conclusions of the testing: No issues found! Thanks

**Comment by mreza1st** [comment]
Hi all,

Has this been updated in the experimental version. I had this issue tonight as I was landing at OIAA with temp. around 25 (near sea level) and the engine kept oscillating up and down and hard to keep the plane in the air. Thanks for taking care of this.

**Comment by sidnov** [comment]
> Hi all,
> 
> Has this been updated in the experimental version. I had this issue tonight as I was landing at OIAA with temp. around 25 (near sea level) and the engine kept oscillating up and down and hard to keep the plane in the air. Thanks for taking care of this.

The experimental is now the development version, merged 2 days ago. And the fix for oscillations is in the development version already. Please try updating, or try contacting over #support channel on the FBW Discord for quick assistance

**Comment by tracernz** [comment]
> Has this been updated in the experimental version.

Further to the above, the experimental version is not currently being updated, and will soon switch to a different focus (flight plan manager).

**Pull request merged**
