### PR TITLE
fix(api): DOME light switch doesn't move when set to "dim" via SimConnect

### LINKED ISSUE #6402: Dome Light via SimConnect set to "DIM" does not move the switch
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-16T15:31:39+00:00",
  "ref": "master",
  "sha": "ceb8298db8861369aeed76c9582418a3930f86fd",
  "actor": "BlueberryKing",
  "event_name": "manual"
}
```

### Describe the bug

I am able to set the Dome light via SimConnect.TransmitClientEvent() to "OFF", "DIM" and "BRT". The light itself works as expected, but the switch only moves to either "OFF" or "BRT". If the light is set via SimConnect to "DIM", the switch does not move to the correct position.

I am setting the Dome light with two events as follows:

```
OFF: CABIN_LIGHTS_SET to 0 + LIGHT_POTENTIOMETER_7_SET to 0
DIM: CABIN_LIGHTS_SET to 1 + LIGHT_POTENTIOMETER_7_SET to 50
BRT: CABIN_LIGHTS_SET to 1 + LIGHT_POTENTIOMETER_7_SET to 100
```
These are also the exact values that I get in the corresponding Simulation Variables `LIGHT CABIN` and `LIGHT POTENTIOMETER:7`, when I move the switch in the Overhead panel.

What looks strange to me, is the content of the file A320_NEO_INTERIOR.XML:
https://github.com/flybywiresim/a32nx/blob/c29987db65566a0b3098abc2f80b7710a2d73864/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml#L1542-L1547

The variable `LIGHT CABIN` (which is of type `bool`) is compared with `0.5`.

### Expected behavior

The switch should move into the position "DIM" if set via SimConnect and the light is indeed "dim".

### Steps to reproduce

See in description.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by pre-martin**
Fixes #6402 

## Summary of Changes

The XML uses two events and two variables to set and track the state of the DOME light switch.
* LIGHT POTENTIOMETER 7 takes one of the values 0, 50 or 100 for "off", "dim" or "bright"
* LIGHT CABIN (which is of type bool) has to be 0 for "off" or "1" for "dim" or "bright"

But actually the variable LIGHT CABIN was compared with "0.5" and the event CABIN_LIGHT_SET fired with "0.5". If the event is fired via SimConnect, the XML does not recognize the combination of LIGHT CABIN = 1 and LIGHT POTENTIOMETER 7 = 50.

## Screenshots (if necessary)

No visual changes. But here is a screenshot from the MSFS SDK Sample "SimvarWatcher", when the DOME light is set in the airplane (!) to DIM:

dome-dim

It clearly shows that the simulator internally is indeed working with a bool for LIGHT CABIN, which takes the value "1" even for "dim".

## Additional context

Discord username (if different from GitHub):

## Testing instructions

You need a SimConnect client (or some other tool to send SDK events). When sending the events "CABIN_LIGHTS_SET = 1" and "LIGHT_POTENTIOMETER_7_SET = 50", the switch does not move at all. With this fix applied, the switch will move into the middle position "dim".

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by BlueberryKing — APPROVED** [review]
Nice fix!

**Comment by pre-martin** [comment]
Linting failed when I merged the master onto my PR. My first commit passed the linter. So I assume that there is either a problem with the linting process itself (because it shows no error message) or with the master.

**Comment by BlueberryKing** [comment]
Yeah, the linter is a bit temperamental sometimes 😄. Looks like it worked this time.

**Comment by davidwalschots** [comment]
@pre-martin in the interest of getting this tested. Could you recommend a "SimConnect client" through which one might send these SDK events?

**Comment by pre-martin** [comment]
I will check what you could use.

**Comment by frankkopp** [comment]
> @pre-martin in the interest of getting this tested. Could you recommend a "SimConnect client" through which one might send these SDK events?

I can test it with SPAD now

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #6407
Tier of Testing: 1
Date: 6.2.2022

Testing Process: 
C&D only BAT & EXT on
Using SPAD to control Dome light:
Step 1:
- send TOGGLE_CABIN_LIGHT event
- set LIGHT POTENTIOMETER:7 to 50
Step 2:
- set  LIGHT POTENTIOMETER:7 to 100
Step 3: 
- set LIGHT POTENTIOMETER:7 to 0
- send TOGGLE_CABIN_LIGHTS event

Check if switch moves correctly

Negatives: none

Testing Results: Passed

Conclusions: LGTM

Media:

https://user-images.githubusercontent.com/16833201/152685849-bf016e85-5da6-4724-a215-5fd6fdb38213.mp4

**Pull request merged**
