### PR TITLE
refactor(Ecam): Convert Bleed page to React

### PR DESCRIPTION
**Pull request by Kimbyeoungjang**
Fixes #[issue_no]

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
Keep in mind someone is working on BLEED system, so do not spend too much time simulating it.

**Comment by Kimbyeoungjang** [comment]
Bleed PR looks almost done. So I'll also finish this :D

**Comment by davidwalschots** [comment]
It's been a while since anything happened in this PR. I'd be curious to know if you plan on continuing with this?

**Comment by Kimbyeoungjang** [comment]
> It's been a while since anything happened in this PR. I'd be curious to know if you plan on continuing with this?

sry I was got a covid.

I can start work on this weekend :D

**Comment by davidwalschots** [comment]
> sry I was got a covid.

No need to apologise for that of course! I hope you're doing well and feeling healthy again?

**Comment by Kimbyeoungjang** [comment]
Due to my main computer dead, So I can't work about this.

So I close this PR. I wish someone continue this work :D

**Comment by BlueberryKing** [comment]
Thank you for the update! For anyone picking this up, the default bleed system has now been replaced as of PR https://github.com/flybywiresim/a32nx/pull/5384. It is advisable we use the representative SimVars on the new Bleed page.

Feel free to contact me on Discord (BluberryKing#6641) or on here if you have any questions regarding the new system.

**Pull request closed without merging**
