### PR TITLE
Minor vertical offset correction to Flight Director

### LINKED ISSUE #923: [BUG] PFD attitude marker doesn't match vertically with FD
**Mod Version**

master/0.3.0

Change which introduced the problem https://github.com/flybywiresim/a32nx/pull/846/commits/5e3c694bdabf17d02e99361436e16fc9e0a4f279.

**Describe the bug**

PFD attitude and aircraft wing symbols were adjusted vertically and now Flight Director does not align with them.

**To Reproduce**

1. Use autopilot and Flight Director
2. Allow plane to fly until it is completely stabilized
3. Check Flight Director against PFD attitude marker

**Expected behavior**

Flight Director should match exactly with PFD attitude marker in the middle.

**Actual behavior**

FD drives slightly below PFD attitude marker since marker has been moved upwards.

FD should be corrected vertically to match PFD attitude marker change.

**References**

kuva

**Additional context**

**Was this working before/when did the issue start occurring?**
This has been working correctly in 0.2.0.

**Is this a problem in the vanilla unmodded game?**
No

Discord username (if different from GitHub): VeGe-#4631

### PR DESCRIPTION
**Pull request by veikkos**
Fixes #923 

**Summary of Changes**

Adjust vertical Flight Director offset. Attitude indicator was slightly updated in https://github.com/flybywiresim/a32nx/commit/5e3c694bdabf17d02e99361436e16fc9e0a4f279. In the end the offset adjustment needs to be very tiny but every detail matters!

**Screenshots (if necessary)**

Images taken by faking FD to dead center 0, 0 in code since difference small as this is difficult to notice while flying. Look carefully to the center rectangle which is now as as close as it visually can.

**Before**
before

**After**
after

**References**

Common knowledge I think.

**Additional context**

Discord username (if different from GitHub): VeGe-#4631

### CODE REVIEW

**Comment by lousybyte** [comment]
Honestly I looked at this for 3 days and can't see the difference, if anyone with better eyes could review this. 
Code wise, haven't looked into it, but any chance this can be corrected via HTML/CSS?

**Comment by NathanInnes** [comment]
He means 

Before:
image

After:
image

A very minute change in the centre.

**Comment by veikkos** [comment]
Yep, tiny change in the middle of the cross vertically. 😅

kuva

**Comment by camilo625** [comment]
Name: Camilo625 #5575
Date of testing: Current date 04/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1030 

Testing technique: Check FD on ground and in the air
Steps you've made to test the Pull Request:
1. Spaw
2. Check FD
3. Takeoff
4. Check FD
5. Land

Overall Rating: Good
Conclusions of the testing: Works as described

**Comment by NathanInnes** [comment]
Include a changelog and this should be good to go! :)

**Comment by Benjozork** [comment]
@NathanInnes I added the changelog myself as stated in the contribution guide. @veikkos, please add change logs for future PRs 😃

**Comment by veikkos** [comment]
> @NathanInnes I added the changelog myself as stated in the contribution guide. @veikkos, please add change logs for future PRs 😃

Thanks mate! Missed the new guidance and did not yet have time to add it, but next time I know!

**Pull request merged**
