### PR TITLE
[OPTIONS] Initialize unit conversion only start up

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- first #2762 needs to add two missing ecam pages

When changing the aircrafts weight unit from KG to LBS or vice versa, these changes now only become active after reloading the aircraft.
When changing the weight unit a message in amber will appear that informs the pilot to reload the aircraft.
This is done to reduce redundant checks and comparisons because the unit system of the aircraft most likely is not changed very frequent, so we figured it's smart to just initialize the unit system once on loading the aircraft.

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

1. Change the aircraft weight unit via the mcdu menu.
2. Check Upper ECAM and ECAM Pages, check mcdu readouts and entries (e.g. on fuel pred page)
   Units should not have changed.
3. Reload Aircraft
4. Repeat step 2.
   Units should now have changed.

5. Repeat steps 1 to 4 as often as you want.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by wpine215** [comment]
#2762 has been merged

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 08/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2824 
Object of test: Unit Conversion changes only after Aircraft Reload
Testing technique: Tryout

Steps you've made to test the Pull Request:

1. Spawned at VABB gates, C/D
2. Turned on battery, external power. Waited for ECAM Self Test to complete.
3. Changed option from FMGC menu and switched units to KG.
4. Observed no change in FOB units, message displayed on MCDU (Screenshot)
5. Reloaded aircraft and saw units changed to KG.

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Works as expected. A message is shown to prompt A/C reload after unit change.

image

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 12/1/21
Version of the sim: 1.12.13.0
PR Tested: #2824
Object of test: MCDU unit conversion

Testing technique: Loaded in twice and tested
Steps you've made to test the Pull Request:
1. Loaded in
2. Changed the unit from KG to LBS and looked for warning
image
3. Pressed restart after hitting ESC
4.Checked that the conversion happened in the next flight 
image
5.Changed back to KG and restarted the flight again
image


Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Works as expected

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by DFWSupertrooper** [comment]
Can someone explain why this was done?  What was wrong with switching units WITHOUT reloading the A/C?  I ask because as far as I know that forces me to reload to the main menu and wait every time I want to transfer between flying around Europe or North America and it seems like it added required effort for no gain, but was something gained I just don't know?  Thx.

**Comment by MisterChocker** [comment]
@DFWSupertrooper We saw no need on checking ever frame whether the unit system changed or not.
Also having a unit system initialization on start up is much more accurate and practicable than checking ever frame.
If you do feel it's needed, please feel free to open an issue request.
Regards Leon

**Pull request merged**
