### PR TITLE
[Texture]Higher resolution Main Panel Texture and glareshield texture fix

### PR DESCRIPTION
**Pull request by Pleasure0102**
**Summary of Changes**
Added 4k Texture for the Main panel, texture is completely made from scratch, so please check closely.

**Screenshots (if necessary)**
Before1:
FlightSimulator_2020-10-05_15-07-49
After1:
FlightSimulator_2020-10-05_15-05-23
Before2:
FlightSimulator_2020-10-05_15-10-45
After2:
FlightSimulator_2020-10-05_15-14-33

**References**

Multiple cockpit images, i tried to stay close to the original, just increase resolution. So hard to post references in this case

**Additional context**
Please check FPS ! Since the Texture was changed from 2k -> 4k
i would like to have some FPS tests if possible. If the cost is too high, i will reduce to 2k and try to get quality still as good as i can.

### CODE REVIEW

**Comment by Pleasure0102** [comment]
i know changes are hard to see in the screenshots, please pull :) and please don't forget to record fps.

**Comment by hotshotp** [comment]
looking much better! I could count the individual pixels on the one before. There is no FPS difference that I notice.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 5/10/2020
Version of the sim: 1930
PR Tested: #1112

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane C&D,
3. Inspected the cockpit from different angles. 
2. Did a short flight while looking around cockpit 

Overall Rating: Good
Conclusions of the testing: LGTM! No noticeable performance impact on my end. Great work as always. It was my pleasure testing this PR!

**Comment by Pleasure0102** [comment]
added 2k texture to source, with readme, how to change to a 2k texture if people have an old gpu.

image

same texture, just scaled down to 2k for more performance

**Comment by aboodilatif** [comment]
I see that the Chrono labels (CHR, UTC & ET) are missing, not sure if this is intended or not.

**Comment by Pleasure0102** [comment]
> I see that the Chrono labels (CHR, UTC & ET) are missing, not sure if this is intended or not.

i am not sure where you see the labels missing ? they are there for me in the screenshots

**Comment by Pleasure0102** [comment]
@aboodilatif fixed in latest version:
image

thanks for reporting

**Comment by tareksabet** [comment]
Name: tarek_sabet#7946
Date of testing: 06/10/2020
Version of the sim: 1930
PR Tested: #1112

Testing technique: Try-out
Steps made to test the Pull Request:

loaded the plane in Cold & Dark, it didn't affect the FPS 

Overall Rating: Good
Conclusions of the testing: Nothing is wrong everything worked well

**Comment by Herrgrube123** [comment]
Name: hansmeller#8988
Date of testing: 6/10/2020
Version of the sim: 1930
PR Tested: #1112

Testing technique: Try-out
Steps made to test the Pull Request:

Loaded the plane on a random airport
Did a short flight and did a look around the cockpit
Turned FPS on and fly around and zoom in and out

Overall Rating: Good
Conclusions of the testing: Looks very nice! No fps hit at all for me!

**Comment by hansmeller12345** [comment]
Name: hansmeller#8988
Date of testing: 6/10/2020
Version of the sim: 1930
PR Tested: #1112

Testing technique: Try-out
Steps made to test the Pull Request:

Loaded the plane on a random airport
Did a short flight and did a look around the cockpit
Turned FPS on and fly around and zoom in and out

Overall Rating: Good
Conclusions of the testing: Looks very nice! No fps hit at all for me!

**Review by Benjozork — APPROVED** [review]

**Pull request merged**
