### PR TITLE
[ECAM] Add icing related ECAM warnings and memos

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

This PR introduces 3 icing-related ECAM warnings and memos:

- ICE DETECTED
- SEVERE ICE DETECTED
- ICE NOT DETECTED

The icing model in MSFS is a little simple and agressive, so we're just making do with what we have here. The ENG ANTI ICE buttons don't seem to actually do anything in the sim, but we'll just trigger that warning anyway as a first sign of some ice happening.

Works great together with #2246.

## Screenshots (if necessary)

ANTI ICE DETECTED

SEVERE ICE DETECTED

ICE NOT DET

## References

image
image
image

## Additional context

QA: Please ensure that all the new warnings here work, and especially also that they don't appear under unexpected circumstances. Some of them (like ICE NOT DET) have a significant delay built into them (>2 minutes), so you may need to wait a bit for them to appear.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by tyler58546** [comment]
Please add references.

**Comment by beheh** [comment]
See #dev-team.

**Comment by beheh** [comment]
Done.

**Review by wpine215 — APPROVED** [review]

**Comment by wpine215** [comment]
Tested all conditions, works as described and code LGTM.

**Comment by Watsi01** [comment]
Just want to add: this is a really nice feature.

**Pull request merged**
