### PR TITLE
fix: gear thump sound not playing on some occasions

### PR DESCRIPTION
**Pull request by hotshotp**
Fixes #[issue_no]

## Summary of Changes

Before sometimes the sound of the gear thump would not play on certain conditions, now this has been reworked with better code and will play correctly.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Raise gear, wait until fully reaches the up position, lower gear.

repeat and listen that the clunk sound plays every time

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested:  #3508
Tier of testing: 2
Changes to observe: Listen to glorious clunk sounds
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawn on Runway EDDP
2.) Take off with fixed heading and altitude (3000FT)
3.) Raised and lowerd the gear about 30 times normaly(clunk sound plays every time)
4.) Moved the lever fast up and down. 

As long as the gear is in an end position the clunk sound appears with a short delay (like 0.5s) after start. If you switch faster back or the gear is in the middle of movement the sound don't appears.

Issues (If Any): None

Overall Rating: Good

Conclusions of the testing: Seems to work.

Hope this helps :-)

**Comment by hotshotp** [comment]
> As long as the gear is in an end position the clunk sound appears with a short delay (like 0.5s) after start. If you switch faster back or the gear is in the middle of movement the sound don't appears.


yep, this is correct behaviour. great to hear it works!

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 14.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3508 
Tier of testing: 2

### Changes to observe: Gear clunk sound heard in every correct situation

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on runway at VABB
2. Departed straight and climbed 2500ft
3. Retracted gear, observed gear clunk sound, waited for cycle to complete.
4. Extended gear again, heard the sound, waited for cycle to complete.
5. Repeated 10-15 times, Variations such as retracting midway in cycle was tested. No clunk sound was observed in such cases

### Issues (If Any): None

### Overall Rating: Good

### Conclusions of the testing: The logic for the clunk sound seems to be fixed, good to go!

**Pull request merged**
