### PR TITLE
[Texture]Glareshield Texture Update

### PR DESCRIPTION
**Pull request by Pleasure0102**
Fixes #[issue_no]

**Summary of Changes**
changed  Glareshield Texture to be more like the real plane.

**Screenshots (if necessary)**
BEFORE inside:
image
AFTER inside:
image
BEFORE Outside:
image
AFTER Outside:
image

**References**
image

**Additional context**
Please use pull request, not only images before giving feedback, as the lighting changes how the texture looks.

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by camilo625** [comment]
Name: Camilo625 #5575
Date of testing: Current date 04/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1082 

Testing technique: Spawn and check textures
Steps you've made to test the Pull Request:
1. Spawn
2. Check textures
3. Change lighting
4. Check again

Overall Rating: Good
Conclusions of the testing: Look great!

**Comment by NathanInnes** [comment]
I understand the joke here and it's funny but I really don't think it should be included in the master. Your love for Tarek can be expressed in many other ways <3

image

**Comment by wuperguy** [comment]
> I understand the joke here and it's funny but I really don't think it should be included in the master. Your love for Tarek can be expressed in many other ways <3
> 
> image

Agreed, got a good laugh but it would be much better with just clean textures. Thanks!

**Review by wuperguy — CHANGES_REQUESTED** [review]
Remove "tarek" engrained in texture.

**Comment by Pleasure0102** [comment]
yeah :D i actually did not think anybody will see it but okay :) will remove

**Comment by Pleasure0102** [comment]
New Before and after shots because of new details:

Before inside:
image
After inside:
image
Before outside:
image
After outside:
image

For reference image check OP please.

**Review by wuperguy — APPROVED** [review]

**Comment by NathanInnes** [comment]
Tested and looks good to me!

**Review by NathanInnes — APPROVED** [review]
Tested and works well!

**Pull request merged**
