### PR TITLE
Sounds for startup

### PR DESCRIPTION
**Pull request by hotshotp**
**Summary of Changes**

I have added sounds in the startup for:
The external power relay clunk
The CIDS chimes (cabin chimes) when batteries are connected
Changed avionics ventilation sounds (both startup and loop)
Added triple click about a minute after start up (self-test of FMGC)
Added a 50/50 chance of a quick one second master warning to play also one minute after startup (IRL bug on the a320 family)

**Screenshots (if necessary)**

**References**

I consulted several pilots and engineers. Big thanks to Komp and PaRaBaS for providing me with information and sounds.

**Additional context**

There is one issue with this that I do not know how to fix. So IRL, the CIDS chimes (cabin chimes) that you hear after turning on the batteries is supposed to happen after turning on BOTH of the batteries. I have tried changing that with a couple of simvars. So master bus voltage is always 25 if either battery is on, doesn't matter if its one or two. Battery voltage shows the same for all indeces (indexes?) from 0-2 even if only one is on and then battery master indices from 0-2 also all show the same thing. In fact battery master always shows a value of one and doesn't change if the batteries are both off. If anyone could help me fix this issue that would be awesome.

Discord username (if different from GitHub):

Boris#9134

### CODE REVIEW

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 3/10/2020
Version of the sim: 1930
PR Tested: #1048

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane C&D, tried different startups.

Overall Rating: Good
Conclusions of the testing: Working as documented! Thank you! Another great addition to the mod!

**Review by wuperguy — APPROVED** [review]
Sounds great as always. Good work!

**Comment by Pleasure0102** [comment]
i kinda feel the sounds could be a bit louder for the click / clunk 
check this video iceman posted, really loud one for the first battery, and the ext power i think clearly louder
https://www.youtube.com/watch?v=A7Dz0fHs42A

**Comment by Brandidiot** [comment]
I agree with 

> 
> 
> i kinda feel the sounds could be a bit louder for the click / clunk
> check this video iceman posted, really loud one for the first battery, and the ext power i think clearly louder
> https://www.youtube.com/watch?v=A7Dz0fHs42A

I agree, sounds are good though!

**Comment by Pleasure0102** [comment]
okay, love it,

can you take a look tarek if sounds are accurately loud for volume ?

**Comment by tareksabet** [comment]
I lovvveeee ittttt 
works very good

**Comment by liebbe10** [comment]
> i kinda feel the sounds could be a bit louder for the click / clunk
> check this video iceman posted, really loud one for the first battery, and the ext power i think clearly louder
> https://www.youtube.com/watch?v=A7Dz0fHs42A

The avionic fans in the Sim first start very similar to the video, but get "very" quiet after a short amount of time and also they change their tone. I don't know if this is the real behavior, that after a while they turn down, but in the video it sounds as if they remain at their level and pitch after turning on.
Also don't know if this is part of this PR but the first clunk of the first battery sounds a bit louder/harder in the video and there was also a quieter sound for the second battery.

Besides that I really love the sounds and every sound improvement!!! Thx for the great work :D

**Comment by hotshotp** [comment]
> > i kinda feel the sounds could be a bit louder for the click / clunk
> > check this video iceman posted, really loud one for the first battery, and the ext power i think clearly louder
> > https://www.youtube.com/watch?v=A7Dz0fHs42A
> 
> The avionic fans in the Sim first start very similar to the video, but get "very" quiet after a short amount of time and also they change their tone. I don't know if this is the real behavior, that after a while they turn down, but in the video it sounds as if they remain at their level and pitch after turning on.
> Also don't know if this is part of this PR but the first clunk of the first battery sounds a bit louder/harder in the video and there was also a quieter sound for the second battery.
> 
> Besides that I really love the sounds and every sound improvement!!! Thx for the great work :D

thank you! One thing about this, so basically it is the same story with the wind sounds. I would turn them up higher but people would complain that they are too loud and annoying to play with. So for now I will keep this.

**Comment by h-rezaei** [comment]
> > > i kinda feel the sounds could be a bit louder for the click / clunk
> > > check this video iceman posted, really loud one for the first battery, and the ext power i think clearly louder
> > > https://www.youtube.com/watch?v=A7Dz0fHs42A
> > 
> > 
> > The avionic fans in the Sim first start very similar to the video, but get "very" quiet after a short amount of time and also they change their tone. I don't know if this is the real behavior, that after a while they turn down, but in the video it sounds as if they remain at their level and pitch after turning on.
> > Also don't know if this is part of this PR but the first clunk of the first battery sounds a bit louder/harder in the video and there was also a quieter sound for the second battery.
> > Besides that I really love the sounds and every sound improvement!!! Thx for the great work :D
> 
> thank you! One thing about this, so basically it is the same story with the wind sounds. I would turn them up higher but people would complain that they are too loud and annoying to play with. So for now I will keep this. One more thing, the battery relay clank I can not change until the new elec system is implemented because for some reason there actually is no simvar that shows if each individual battery is on.


Was talking about this on discord
Agreed about the avionics fans being too loud can be annoying. Remember that hearing a recording through a microphone is different than hearing something in person. You can choose to go either way,  either simulate the sounds as if you are there or  make it similar to a microphone/video  recording. I personally would choose the former.
I hope that @hotshotp manages to make the avionics fan sound stereo. at the moment, they sound quite mono to me, so  you will hear the fans all coming from the very  center, not around you. I have not heard the raw file. perhaps using an audio editor you can give it a little bit of width. alternatively, a dual or multiple microphone recording of the fans would be so much better. It feels like a downgrade to the  default asobo sounds because of that. besides that  very good job! Keep up the good work!

**Comment by sebbenandsebben** [comment]
For the sake of clarity (or another noise to consider) as well, one of the noises you will hear on power-on I believe is also the flight-deck door lock relay clunking on power up.

See this time-stamp for the clunk https://youtu.be/ROIH3KCEIvs?t=139

**Pull request merged**
