### PR TITLE
[ECAM] Getter/Setter for cabin temperature

### PR DESCRIPTION
**Pull request by RichardPilbery**
## Summary of Changes

At present the cruise and COND page on the ECAM, cabin temperatures are either 0 or 24 since the SimVars for cockpit, forward and aft temperatures have not been set for the COND page (will be sorted when the packs code is written) and they are hard coded in the html cruise page.

I've added the 3 temperature variables into the LocalVarUpdater.js file and linked them to the air conditioning knobs on the overhead panel. 

This will synchronise the temperatures shown on both ECAM pages and is easy to remove once the packs code has been completed.

## Screenshots (if necessary)

cond-page

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
Hello, local variables should be prefixed with `L:A32NX_`

**Comment by RichardPilbery** [comment]
Roger

**Comment by Benjozork** [comment]
LGTM

**Review by Benjozork — APPROVED** [review]

**Review by NathanInnes — APPROVED** [review]
Tested and working well for me: 

- Started from C&D 
- Casual flight while adjusting temps.

**Pull request merged**
