### PR TITLE
fix(cdu): ILS frequency autofill

### PR DESCRIPTION
**Pull request by pareil6**
## Summary of Changes
Fixes an out-of-sequence flight plan version update causing ILS frequency not to autofill on the RAD NAV page after selecting an approach. Note this doesn't fix the frequency not autofilling on 3rd-party sceneries - this only fixes the regression from the flight plan performance improvements that was causing it to not autofill at all.

## Screenshots (if necessary)
Before:

After:

## References
N/A

## Additional context

Discord username (if different from GitHub): pareil6#0990

## Testing instructions
Check selecting an approach at default airports now autofills the ILS frequency. Also ideally, use it for a full flight and check this doesn't cause any weird behaviour when transitioning onto the STAR and from the STAR to the approach.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by tracernz** [comment]
cc. @St54Kevin

**Comment by MisterChocker** [comment]
@St54Kevin what are your 2 cents on how we should continue, do you need this to be merged first or should this pr build ontop of your refactored code?

**Comment by pareil6** [comment]
> @St54Kevin what are your 2 cents on how we should continue, do you need this to be merged first or should this pr build ontop of your refactored code?
> 
> @pareil6 I noticed that the autofill does not automatically fill/define the LS Ident.

This isn't actually touching the RAD NAV page code at all though - this is just fixing a bug in the flight plan manager throttling that was causing the approach not to be visible to the callback immediately after it's selected. It should be orthogonal to @St54Kevin's work - his PR is fixing the RAD NAV page, this is just fixing the underlying FPM logic to make the frequency available as soon as the approach is selected.

Correct on the ident not showing - it's restoring the same behaviour as before (the ident only fills once you're in range), rather than trying to completely fix the autofill.

**Comment by St54Kevin** [comment]
> @St54Kevin what are your 2 cents on how we should continue, do you need this to be merged first or should this pr build ontop of your refactored code?
> 
> @pareil6 I noticed that the autofill does not automatically fill/define the LS Ident.

Yes totally unrelalted. You can see in the code he is not touching the RADNAV page while I edited ONLY the RADNAV page.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 19.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3599
Tier of testing: 2
Changes to observe: ILS set in RAD NAV when spawning on APP
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned APP to EDDP 08R
2.) Looked at RAD NAV page (Image1)
1.) Spawned APP IFR to EDDP ILS08R
2.) Looked at RAD NAV page (Image2)

Media:


Image1


Image2

Issues: None

Overall Rating: Good!

Conclusions of the testing: When ILS APP is selected tthe frequency is ready in RAD NAV. 

Hope this helps :-)

**Comment by Samueleonard** [comment]
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: Current date 20/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3599 
Tier of testing: 2

Changes to observe:
ILS autotunes on RADNAV after selecting an approach

Testing technique: Description of how you tested the Pull Request
full flight
Steps you've made to test the Pull Request:
1. loaded in at EGKK (default scenery)
2. set up aircraft + entered flightplan to EGCC
3. took off from EGKK, climbed out as normal
4. once at cruise, entered arrival into EGCC, dayne2a, ILS23R
5. verified that 109.5 was entered - see notes 2
6. did normal ILS appr to EGCC, landed 

Flight notes (When done a full flight):

PREFLIGHT - would expect 26L (110.9) to be tuned when departure is put in, would expect 23R (109.5, crs232) to be tuned when approach is put in

1 - probably out of the scope of this PR, but after selecting a departure from EGKK, the ILS for 26L did not tune, when it shouldve to make a return to the airport easier - this would then activate the RWY fma on takeoff.

2 - 109.5 is a common ILS freq in the UK, so the incorrect identifier was showed initially, however it retuned during the flight and eventually was the correct identifier

Media: Insert screenshots, recordings, or anything relevant to the review here.
image
109,5 tuned correctly, however the incorrect identifier, which i think is okay, i dont think it tunes for an identifier, but rather the frequency, maybe check with a real pilot

Issues (If Any):
apart from the above mentioned, none

Steps to achieve the issue
N/A

Overall Rating: Good

Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.

LGTM - thank you for fixing this issue, its an important one

**Comment by Recka50** [comment]
Category: QA Tester/Trial
Name: Bepis#6926
Date of testing: Current date 20/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3599
Tier of testing: 2
Changes to observe: ILS Frequency automatically adding to RAD NAV page when selecting approach

Testing technique: Full flight from cold and dark from YBRK to YBBN

Steps you've made to test the Pull Request:
1. Spawned cold and dark
2. Flew normal flight from YBRK to YBBN, setting the approach in the flight plan page and observing the RAD NAV page for changed
3. RAD NAV page showed ILS frequency
4. Confirmed magenta diamonds show on approach with LS display selected
5. No issues found

Flight notes (When done a full flight): SimBrief flight from YBRK to YBBN, Route: BUDGI2 BUDGI V111 RUROX Y177 SMOKA SMOK8A

Media: Insert screenshots, recordings, or anything relevant to the review here.
Pre-Flight: 
image
image

On approach:
Magenta diamonds appear
image
Glideslope and Localiser captured with no manual inputs to RADNAV Page
image

Issues (If Any): No issues

Overall Rating: Good
Conclusions of the testing: The fix seems to have resolved the issue of the ILS frequency not being automatically implemented in to the RAD NAV page once the approach is selected

**Comment by CAC14** [comment]
Category: QA Tester
Name: Discord User #9027
Date of testing: Current date 02/20/2021
Version of the sim: Version the tester uses
PR Tested: #3599
Tier of testing: 1/2/3  ???? unknown
Changes to observe:
Check that after selecting approach in mfc it automatically adds it to coms page

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Started on runway 25 at Korl (already running).  Set up approach to kmco ils 17L.  Checked frequencies and it did auto add.  Took off and used auto pilot to climb to 4000.  Clicked LS.  Selected approach mode on mfc and verified approach in perf. Selected config 3.    ILS was loaded correctly.  Followed approach until on final.  Clicked appr.  It immediately grabbed the loc and soon after grabbed the glide slope as the diamond went down.  Landing was fine but some unrelated glitches were noticed.  
2. Loaded at gate at KJFK.  Set destination as kewr in fms.  Took of on runway 22l.  set up landing in air instead of on ground.  Plane performed fine.  I changed ils freq and then re added it a few time to try and mess it up.  No problem.  On landing I did not have green nav/g/s but it worked fine.    Found out it was due to fd being off.
3.   Did same flight again, different runways.  Different approach.  With fd on it worked great. I could not make the auto add feature not work.  I even tried giving flight sim low priority and loading up my ram to see if low memory would cause problems.  Other then low fps it worked fine and added fine.  Kept changing it and messing with the flight plant to try and make it act up.  Set computer back to normal and landed fine.  All normal.  New feature works.  
4.
5.

Flight notes (When done a full flight):  Worked as expected.  I tried to break it and couldn’t.  Tried on 4 different airport and 6 different runways.  Started form cold and dark and started on runway.  Made my computer act over loaded then set it back to normal.  Did mid air changes.  Messed with freq manually and then reset it automatically.  It works.  Double checked freq vs approach chart, all correct.

Media: 2nd flight you tube link: https://youtu.be/h-bEigVCCl8

Issues (If Any): Write any issues NONE
Steps to achieve the issue

Overall Rating: Good/To be improved GOOD
Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.  Good, ready to implement!

**Pull request merged**
