### PR TITLE
Creating "Bandit Mask" livery version

### PR DESCRIPTION
**Pull request by gabrielefronze**
## Summary of Changes
This PR adds another livery implementing the A350 "bandit mask" over the FBW A320 Neo livery. Just few cents to this project I fell in love with!

## Screenshots (if necessary)

Thumbnails:
thumbnail
thumbnail

Screenshots:

## References
- A350 and A330 "Bandit mask" (officially Shades) livery: https://www.airbus.com/newsroom/press-releases/en/2015/11/shades-livery-now-also-on-new-a330neo.html
- A320 Neo SAS livery with "Bandit mask": https://community.infiniteflight.com/t/scandinavian-airlines-sas-airbus-a320neo-new-livery/383583

## Additional context
Few cents of mine to a totally awesome project!
Discord username (if different from GitHub): Slidspitfire

## Testing instructions
- Download the A32NX artifact
- Install it as usual
- Should be P&P with Flight Simulator

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by pepperoni505** [comment]
This is great! One little suggestion, expand the space between the window and the edge of the mask in the corner (see attached picture below)

image

**Review by pepperoni505 — APPROVED** [review]

**Comment by ChruutvoLuzi** [comment]
Hi, great Idea! If you want, i could provide you a self made high quality racoon mask that you can use. Asobos UVs are quite special and took a bit of trickery to create a perfect mask. Feel free to DM me on Discord

**Comment by gabrielefronze** [comment]
> This is great! One little suggestion, expand the space between the window and the edge of the mask in the corner (see attached picture below)
> 
> image

Hi @pepperoni505!
Nice catch, yesterday I was too tired to notice that, but now I can see that. I'll fix it!

**Comment by gabrielefronze** [comment]
> Hi, great Idea! If you want, i could provide you a self made high quality racoon mask that you can use. Asobos UVs are quite special and took a bit of trickery to create a perfect mask. Feel free to DM me on Discord

Thanks a lot @ChruutvoLuzi ! I'll ping you on Discord. Cheers!

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 07/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2917 
Object of test: Bandit Mask Livery
Testing technique: Tryout

Steps you've made to test the Pull Request:

1. Spawned at VABB RWY27
2. Checked external of the Bandit Mask livery


Issues (If Any): The white border issue seems to be fixed, although the quality of the mask tex looks a little less. In other words, the edges don't look as sharp. Could also be an issue on my end, would wait for another QA test to confirm.

Overall Rating: Good
Conclusions of the testing: If it is found that the mask texture is a little lower quality, it may be improved. Apart from that. good to go. Attached screenshot

image

**Comment by pepperoni505** [comment]
Would some other contributors mind sharing their opinions on adding this?

**Comment by gabrielefronze** [comment]
Hey there!
I’m trying to improve the “mask” resolution as suggested. Keep it out from master until I’m done with that, I’ll state that clearly when done 🙂

**Comment by MapleNAV-TCASFAULT** [comment]
I like the idea of this, but the whole livery would have to be higher res. Wouldn't really want to see an 8k part of a livery then a 1080p part, I think the consistency is the main issue now.

**Comment by gabrielefronze** [comment]
> I like the idea of this, but the whole livery would have to be higher res. Wouldn't really want to see an 8k part of a livery then a 1080p part, I think the consistency is the main issue now.

Totally agree. I guess there is something wrong with my DDS plugin for photoshop. Can anyone provide me the dds already converted to 8k png or something like that? Since I can save to DDS with no problems I guess the problem here is the first import to Photoshop causing the downscaling.

**Comment by easyjetsimpilot** [comment]
Flew (& streamed) full 2hr flight with this livery. No issues from a technical point of view or conflicts created. 

Video available here:-  https://youtu.be/mEQJUz08O9c

**Comment by gabrielefronze** [comment]
> Flew (& streamed) full 2hr flight with this livery. No issues from a technical point of view or conflicts created.
> 
> Video available here:- https://youtu.be/mEQJUz08O9c

Awesome! Subscribed 👍 
I saw some comments about the low res of the mask, I guess it'll get better with tonight update!

**Comment by easyjetsimpilot** [comment]
Hello!

I saw that you'd updated the res so didn't comment on it as you were
already on it.

Great work 👍 thank you.

Kind regards,
Gavin

**Comment by gabrielefronze** [comment]
Hey there,
A little update. I tried to apply antialias to the mask to improve the quality, but even doing so I think the pixels will still be visible.
In the following pictures you can see the differences (actually no difference imho) between the quality of the waves and other details and the mask.

Screenshot 2021-01-08 at 01 23 34
Screenshot 2021-01-08 at 01 24 28

Now I created an SVG out of the mask shape and imported it directly into the DDS, so I am quite confident I cannot do more but adding some antialiasing which I did.

I think sticking to the mask applied to the texture we won't go any further than this, BUT I discovered the decals and the file describing where to put all of them and apparently the decals are much higher resolution than the base paint job.

My plan is to try to figure how do the decals work and maybe use them for the mask and also for replacing other parts of your original texture which look a bit pixellated (e.g. doors and tail lines).

Cheers!

**Comment by devsnek** [comment]
I'd be interested in seeing if we can make this a decal instead of a whole separate livery. If we did that, it could be toggled on and off in the sim through the efb. It would require adding a texture around that area, modifying https://github.com/flybywiresim/a32nx/blob/master/A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg, and then adding a small html file which is basically just a black background.

**Comment by lukecologne** [comment]
Why a gauge? You can toggle node visibility via Simvars and XML, so it should be fine to just add a new decal and hide/show it based on a simvar

**Comment by devsnek** [comment]
@lukecologne even better, didn't know you could do that :+1:

**Comment by gabrielefronze** [comment]
@devsnek and @lukecologne these are great ideas! Is there some SDK documentation I can start from?

**Comment by gabrielefronze** [comment]
I noticed some highly detailed textures from other developers are 8K, while the DDS I unpacked from this repo are 2K.
As an additional attempt I tried to upscale the existing texture to 8192x8192 and apply the racoon mask.
By doing so the mask should be super smooth, but ofc the logo and other parts will be a little bit crunchier. In case that helps with the model and texture quality I will upscale manually (aka remodeling waves, writing and other details) the whole texture.
Stay tuned!

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: 08.1.2021
Version of the sim: 1.12.13
PR Tested: #2917
Object of test: New Livery Version

Testing technique: Tested?
Steps you've made to test the Pull Request:
1. Started C&D at Gate
2. Observed the Livery while taxiing and flight
3. 
4.
5.

Flight notes (If required):

Issues (If Any): none
Overall Rating: Good
Conclusions of the testing: Looks good i had no issues. Thanks for the new Livery!

**Comment by HugoTro** [comment]
Name: Hugo #3307
Date of testing: Current date 09/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2917

Testing technique: Looking at
Steps you've made to test the Pull Request:
1. Spawned on a runway
2. Took off and admired the beauty
3. Took some screenshots

Overall Rating: Good...
Conclusions of the testing: It looks really good but i don't know if the "irregularity" of the lines could be fixed on the mask?
Capture d’écran (332)_LI

**Comment by gabrielefronze** [comment]
Hey there!
Thanks a lot @tjburni and @HugoTro for testing!
I spent my day upscaling the missing details not yet at 8K resolution and I am testing it right now myself.
I think the mask weirdness you see is due to the fact that the underlying model has some angles which cause the texture to show such edges. I think the new version can improve on that as well but I am about to know that!
Cheers,

**Comment by gabrielefronze** [comment]
Few screenshots of the latest version of the texture. I can inject the same 8K texture without the bandit mask and replace the standard one if anybody loves that!

The upscaled parts are:
- main door lines
- emergency exit lines
- elevator black lines
- the bandit mask
- the standard livery waves (now they have no blur at all!)
- the tail lines under the APU down to the belly
- the "flybywire" writing

**Comment by ko-zone** [comment]
Is it possible to get airbus branding off the aircraft, just to avoid any potential licensing problems and play it safe.

**Comment by gabrielefronze** [comment]
> Is it possible to get airbus branding off the aircraft, just to avoid any potential licensing problems and play it safe.

Definitely possible, even if I like it a lot...
Let's wait for some more comments on that, but I can remove them quite easily!

**Comment by MapleNAV-TCASFAULT** [comment]
If I were to add it, It would be nice to make it very subtle, instead of a sharp blue. Maybe make it a translucent grey and put it under the layer of the FBW livery with only the word "NEO" in a larger font. (if it's possible)

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: ChristopherXie#3904
Date of testing: Current date 10/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2917 
Object of test: New livery

Testing technique: Entered the sim and conducted a look around
Steps you've made to test the Pull Request: 
1. Spawned on a runway at CYYZ
2. Took off
3. Did a pattern and landed
4. Inspected the livery for any visual glitches or bugs
5. look for FPS hit

Flight notes (If required):

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: The upscaled livery is really good, no more pixely edges. No FPS hit, so that's good. But just like what KO said, best to remove the airbus markings. The "racoon mask" makes it look a lot better. Great work!

**Comment by gabrielefronze** [comment]
> If I were to add it, It would be nice to make it very subtle, instead of a sharp blue. Maybe make it a translucent grey and put it under the layer of the FBW livery with only the word "NEO" in a larger font. (if it's possible)

Thanks a lot for your comment!
I can definitely make the whole thing a little more subtle, and even completely remove the airbus markings.

Let’s just wait for some more comments on that.
Would it make sense to use his upscaled texture version also for the default liveries? I can do that with almost no effort!

**Pull request closed without merging**
