### PR TITLE
Ground cursor improvements

### PR DESCRIPTION
**Pull request by veikkos**
No issue but one can be created if needed.

**Summary of Changes**

Update ground cursor visuals and its limits. Not 100% perfect but should be way better anyway. Let me know if you'd like to see some additional tweaks to be made.

**Screenshots (if necessary)**

**Before**
original
original_2

**After**
new
new_2

**Additional context**

[Reference](https://youtu.be/cv41hm4JEB8?t=98)
kuva

Discord username (if different from GitHub): VeGe-#4631

### CODE REVIEW

**Review by AdenFlorian — APPROVED** [review]
ready to test!

**Comment by GlitchedYT** [comment]
Small little improvement to make it more realistic, cursor should go halfway through the box as referenced in this photo from the FSLabs in P3D. Could find any photos from irl but this should be how it looks

https://imgur.com/a/qrZLBQJ

**Comment by lukecologne** [comment]
Maybe this is out of scope for this PR, but if you are on it already, can you raise the yellow-black aircraft symbol so that it is inline with the yellow bar next to the altitude indicator? This would also align it with the horizon properly I think, look at the red line I drew in the pictures
uSsV1Nd
94190831-506bd000-feb5-11ea-88b0-ff7705b6aebc

**Comment by AdenFlorian** [comment]
im working on the fixes

**Pull request merged**
