### PR TITLE
fix(lights): Add FLOOD LT PED light + new stepless potentiometer

### PR DESCRIPTION
**Pull request by bouveng**
## Summary of Changes

* Adds new FLOOD LT MAIN PED light with subtle indirect light/ambience.
* Adds a new stepless, silent, precision potentiometer for use with various lights.
* Light have a great dimmable range and can be adjusted with clicks for precision setup or with longpress for rapid change of intensity

## Screenshots

stepless-potentiometer
Stepless potentiometer

Microsoft Flight Simulator 2021-06-22 02_47_17
Pedestal at maximum flood light setting

## Video example
https://user-images.githubusercontent.com/433429/122844047-1a069880-d301-11eb-90c3-d55d72ff75fb.mp4

Shows pedestal flood light and its subtle ambient light

## References
TBD

## Additional context
Minor changes to light compared to prior version. Just less intense.

## Testing instructions
1, Spawn C&D, somewhere dark, with as little external lights as possible (on RW at ESME for example)
2, Power aircraft in suitable way.
3, Turn of any interfering lights, integrated lights, screens, etc to your liking.
4, Try out the FLOOD LT PED

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by davidwalschots — APPROVED** [review]

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5182 
Tier of Testing: 1
Date: 22/06/2021

**Testing Process:**
1. Loaded C&D in the night
2. Tested various knob positions in different lighting conditions

**Negatives:** 
- Same as with the other PRs, mouse wheel is pretty ineffective. I would like to have a faster mouse wheel speed and then click for precision.
- Also here the light progression doesnt seem to be linear withing the whole knob range. Turning beyond the 11 o clock mark doesnt do much.
**Testing Results:** Not Passed, lets see what the other QAs say

**Comment by bouveng** [comment]
Hi K!

> * Same as with the other PRs, mouse wheel is pretty ineffective. I would like to have a faster mouse wheel speed and then click for precision.

Since the knob now has 100 "steps" instead of 10, I can imagine the mouse wheel experience becomes a bit hard.
I use my mouse-wheel to zoom so I never thought of this.

But, this must be a problem for all the other "stepless" dials, like the 3 temperature knobs on the overhead?
Do they work better with mouse-wheel?

If you know a dial or knob that behaves nice with mouse-wheel and have more than 10 steps, let mw know and I can investigate it.

I do not know how to split klicks and mouse-wheel interactions so we can get "bigger" steps when using mouse-wheel.
So I do not know how to resolve this mouse-wheel issue at the moment.

> * Also here the light progression doesnt seem to be linear withing the whole knob range. Turning beyond the 11 o clock mark doesnt do much.
>   **Testing Results:** Not Passed, lets see what the other QAs say

The knob itself is linear 0-100% and you see bigger differences in the lower ranges than the upper.
In contrast to what I wrote in the other PR's, this is not an emissive, so I could perhaps increase the intensity so there is more "room" in the upper range.

But if you look at the gif + video above, it is possible to see that something is happening along the whole range.

Suggestions and desired behaviour is welcome. =)

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5182
Tier of Testing: 1
Date: 23.6.2021

Testing Process: 
C&D at gate at night - tested FLOOR knob

Negatives:
As already mentioned after half turn of the knob effect is barely noticeable any more.
Also it takes ages to scroll from 0 to 100 - this is not practical

Testing Results: Not passed - spending 15 sec to turn on a light is not acceptable

Conclusions: Like the step-less knob idea but needs to be improved to be practical when setting up cockpit. 

Media: 

Tried to scroll as fast as I can:
https://user-images.githubusercontent.com/16833201/123009244-a32ed580-d3bc-11eb-92da-2337e3e39c31.mp4

**Comment by bouveng** [comment]
Hi man!

> As already mentioned after half turn of the knob effect is barely noticeable any more.

I do not think it is possible to make the light non-linear so there is an "even" dimming effect over the whole range.
Intensity is a function of voltage, but that result is not really linear.

> Also it takes ages to scroll from 0 to 100 - this is not practical
> spending 15 sec to turn on a light is not acceptable

It would only take 3.5sec if you click instead of using mouse-wheel. 🙈

As I have written in the other similiar PR's with these knobs. I can try to change it from 0-100 "steps" to 0-50, with the risk that the "stepless" feeling disappears.

**Comment by bouveng** [comment]
**UPDATE!**

Hi testers!

I have been digging around in the codebase and I think I will be able to turn the knobs differently when using the mouse-wheel.

There is `WheelUp` and `WheelDown` events!

I will have to do my own template for this. That is a good idea anyway since this will be used in a few places.
Give me a couple of days to build this.
Expect updated PR towards/in the weekend.

**Comment by frankkopp** [comment]
> > Also it takes ages to scroll from 0 to 100 - this is not practical
> > spending 15 sec to turn on a light is not acceptable
> 
> It would only take 3.5sec if you click instead of using mouse-wheel. 🙈

Hi, 
sorry - didn't even know it had the click functionality 🤦 I always scroll. With this I would have passed it.
My fault!
Looking forward to your change anyway.
Cheers

**Comment by bouveng** [comment]
This PR has been **closed** and **replaced** by #5244

**Pull request closed without merging**
