### PR TITLE
refactor(fmgc): re-add fixed decouple flight phase code

### PR DESCRIPTION
**Pull request by globin**
Fixes flight phase switching

## Summary of Changes
The nextPhase would not be correctly reinitialised

## Additional context
This was broken by #6654 

## Testing instructions
Test flight phase switching, especially edge cases like rejected takeoff and subsequent flight

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by aguther** [comment]
Please re-add also the original commit because it was reverted on master.

**Comment by globin** [comment]
Original refactoring commit re-added. Sorry for the hassle!

**Comment by aguther** [comment]
Good, no worries!

**Review by aguther — APPROVED** [review]
Checked the fix and should be fine.

**Pull request merged**
