### PR TITLE
feat: add extra ways to delete text in mcdu scratchpad with keyboard

### PR DESCRIPTION
**Pull request by ErickSharp**
## Summary of Changes

Adds the ability for the user to do CTRL + Backspace to delete words, CTRL + SHIFT + Backspace to delete the entire contents of the scratchpad, and CTRL + A to toggle a mode that allows the user to delete the entire line by just using backspace and no additional key combo.

## Additional context

Discord username (if different from GitHub): Erick [Z-6]#6484

## Testing instructions

Try using the commands Control and Backspace to delete a word in the MCDU scratchpad; as well as Control, Shift, and Backspace to delete the entire line; and finally doing CTRL + A which should toggle a mode that makes backspace delete the entire line, and the background of the scratchpad input field a red color, making sure that no previous MCDU functionality is compromised by the PR.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ErickSharp** [comment]
rtt

**Comment by ErickSharp** [comment]
ok now its actually rtt...

**Review by 2hwk — APPROVED** [review]

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5335 
Tier of Testing: 1/2
Date: 18/07/2021

**Testing Process:**
1. Loaded onto RW, enable keyboard input, reloaded
2. input random stuff
3. deleted them with the options in this PR

**Negatives:** N/A
**Testing Results:** Passed

**Comment by 2supersanjay** [comment]
**Quality Assurance Trainee Report**

Object of testing: #5335
Tier of Testing: 1/2
Date: 19/07/2021

**Testing Process:**

Loaded onto Runway
Attempted to use CTRL + Shift + Backspace on multiple messages on scratchpad
Attempted to use CTRL + Shift + Backspace on fully filled out INIT page
Imputed words into the scratchpad
Deleted them with CTRL + Backspace
Imputed more words into the scratchpad
Activated CTRL + A command 

**Negatives:** 
I believe the CTRL + Shift + Backspace is not working. This is because when I loaded into the aircraft, there was multiple messages in the scratchpad, I used the command, but it did not have any effect in the scratchpad. I also imputed information into the INIT page and did the command, still didn't work. However, that may not be how the command is to be used, if it is to be used like this then the command doesn't function properly. 

**Testing Results:** Not Passed

**Conclusion:** 
This PR has worked properly and the commands function as expected besides possibly the CTRL + Shift + Backspace command. However, Good job!

**Comment by St54Kevin** [comment]
The CTR +  SHIFT + BAKCSPACE word deletion worked flawlessly for me

**Comment by TheSquirtingPantin** [comment]
Quality Assurance Tester

Discord: Remi#8871
Object of testing: #5335
Tier of Testing: 1
Date: 22/07/2021

Testing Process:
1) C/D at CYLW
2) Navigate through the MCDU
3) Tested keyboard inputs on several pages
4) Tested backspace, and CTRL+SHIFT+BACKSPACE mode
5) Activated the CTRL+A mode. Checked BACKSPACE clearing full line.
6) Checked reversion out of CTRL+A mode.

Negatives: N/A

Conclusions: PASS. MCDU was behaving as expected in the PR. Reversion from and out of CTRL+A mode as expected. 
Media: N/A

**Comment by Benjozork** [comment]
cc @Valastiri need to update flybywiresim/docs

**Pull request merged**
