### PR TITLE
Added Fire Buttons lighting up on test

### PR DESCRIPTION
**Pull request by oliverpope03**
Fixes #[issue_no]

**Summary of Changes**

Added Fire Buttons lighting up on test

**Screenshots (if necessary)**

https://gyazo.com/dd5465cd15b773ba046f5b58925d574e
https://gyazo.com/95a326eed86a2187eefec06d1dffa25e
https://gyazo.com/bde1951b5f8b48d65d97ea905c28508e

**Additional context**

Not the prettiest solution but they dont have any emmisive parts so its the best we can do i believe

### CODE REVIEW

**Comment by tyler58546** [comment]
I don't think this will work with #582

**Comment by wpine215** [comment]
Just reviewed and merged #582. I guess try to merge the changes from master back into this branch and see if it conflicts?

**Comment by oliverpope03** [comment]
Ill see if i can make it work now #582 is in sorry didnt notice that :)

**Comment by oliverpope03** [comment]
Works with #582

**Review by tyler58546 — APPROVED** [review]

**Pull request merged**
