### PR TITLE
feat(efb): add power button

### PR DESCRIPTION
**Pull request by ErickSharp**
## Summary of Changes

Add power button to replace the current functionality of clicking on the battery icon to turn the EFB off as it makes no sense

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
Please provide a screenshot of the updated UI.

**Review by 2hwk — APPROVED** [review]

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5624
Tier of Testing: 1
Date: 13/08/2021

Testing Process:
- Loaded in on runway at EGSS, turned on EFB, 
- Checked for new power button and tested other functions worked as normal
- Checked still able to turn on EFB by clicking anywhere on the screen

Negatives: N/A
Testing Results: Passed

Conclusions: Adds a power button we didn't have, no complaints there! The question of how to power cycle the EFB comes up a lot more than expected in #support, so this will be a great help, and a nice bit of extra immersion having an actual button rather than just clicking the right spot. Great stuff! 

Media: 
image

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5624
Tier of Testing: 1
Date: 14.8.21

Testing Process: 
C&D at gate - turning on and off repeatedly, smoke testing all pages. 

Negatives: None
Testing Results: Passed
Conclusions: Works 😄

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #5624 
Tier of Testing: 1
Date: 14/8/21

Testing Process: 
Loaded in and turned the efb on and off from multiple pages and after having it on for a while
Negatives: N/A
Testing Results: Passed

Conclusions: Works as expected so Tarek took me on a tour around the landing calculator while I pretended I was testing 😂 (joke, actually works as expected and tested properly)
Media: 
image

**Pull request merged**
