### PR TITLE
Fix Wind Indicator

### LINKED ISSUE #403: [BUG] GS on ND should be 0 once ADIRS is fully aligned
**Branch**
master

**Describe the bug**
GS on ND should be 0 once ADIRS is fully aligned

currently it stays as --- until the plane moves

**To Reproduce**
1. spawn cold and dark
align ADIRS

**Expected behavior**
once aligned the GS should say 0, but it stays at --- until the plane moves

**Screenshots or Videos**

**Additional context**
CC: @NathanInnes

### PR DESCRIPTION
**Pull request by NathanInnes**
Fixes #403 

**Summary of Changes**

Extra patch for #227 where GS was not updating unless you moved once ADIRS are aligned.

**Screenshots (if necessary)**

**Additional context**

### CODE REVIEW

**Review by AdenFlorian — APPROVED** [review]
tested and looks good!

**Comment by griffon55** [comment]
Wind indicator always at 225 degrees 3 knots

**Comment by NathanInnes** [comment]
This is not a bug with the plane. It's showing you the winds in the sim. Check the MSFS forums as it's a known issue to them as live weather doesn't update.

**Comment by griffon55** [comment]
Ok sorry

Le lun. 7 sept. 2020 14 h 31, Nathan Innes <notifications@github.com> a
écrit :

**Pull request merged**
