### PR TITLE
Cockpit door switch

### PR DESCRIPTION
**Pull request by oliverpope03**
**Summary of Changes**

Added Cockpit Door switch (spring loaded)  + Open Light
Variable = A32NX_COCKPIT_DOOR_LOCKED
Starts "OPEN" on Apron start else is Locked

**Screenshots (if necessary)**

image

**Additional context**

- [x]  Make switch lock into LOCK position

- [x]  Verify starting in NORM position

### CODE REVIEW

**Comment by sharksfan166269** [comment]
Works as intended, although the animation is a little slow, but not really sure if that matters

**Comment by oliverpope03** [comment]
> Works as intended, although the animation is a little slow, but not really sure if that matters

Ill see if i can speed it up not sure though 👍

**Comment by younesseQAtester** [comment]
working perfectly  ! 
FlightSimulator 9-13-2020 12-43-15 AM-50

**Comment by oliverpope03** [comment]
Waiting on one more merge for sound fix and possible increase animation time

**Comment by younesseQAtester** [comment]
Is it possible to change the color ?
image

**Comment by oliverpope03** [comment]
Ill contact the Texture squad and find out

**Comment by camilo625** [comment]
Works as described. Something i did find, the deflection animation seems to be tied to the "click" itself, meaning if you click fast, you only get part of the animation, if you hold the click, you get the full animation.

**Comment by oliverpope03** [comment]
> Works as described. Something i did find, the deflection animation seems to be tied to the "click" itself, meaning if you click fast, you only get part of the animation, if you hold the click, you get the full animation.

Ill take a look if this is fixable but it could be in the base design of the sim

**Comment by sharksfan166269** [comment]
Animation speed is good, sound is good. Apart from the color, I believe this is working perfectly now

**Comment by oliverpope03** [comment]
Colour has been reported and will be sorted by @DarkOfNova when they have time to do so

**Comment by ImenesFBW** [comment]
Works as documented. If we are able to sort the color as said above it will be perfect! Thanks for your work!

**Comment by DarkOfNova** [comment]
Colour fixed!

**Comment by younesseQAtester** [comment]
perfect guys !

**Review by AdenFlorian — APPROVED** [review]
thanks!

**Comment by DarkOfNova** [comment]
I'm sorry to say but I have to revert the change I made to the colour correction as it also affects the colour of the XFEED open sign. In the future when we have the model I'll fix it :)

**Comment by Carter633** [comment]
This hasn't worked for me - not properly anyway from my understanding. On the ground the Open light is illuminated as I'd expect but when should it revert to Lock in normal operating? I currently cycle the lock switch then back to norm before pushback to engage the cockpit door lock.

During flight I've noticed this too:-

When you unlock the cockpit door the switch operates normally and reverts back to Norm, positioning it to Lock works correctly also however when you move the switch to Unlock, and the OPEN light illuminates, the door should lock after 5-10 seconds (can't remember exactly) at which point the door locks and the open light deactivates. Currently this isn't happening for me - the open light stays illuminated the whole time unless I physically cycle the lock switch to Lock and back to Norm

**Pull request merged**
