### PR TITLE
fix: cockpit decals added and corrected

### PR DESCRIPTION
**Pull request by ImenesFBW**
#### Cockpit decals 
* [x]  Fixed landing gear decals. 
* [x]  Added text to manual seat adjustment knobs.
* [x]  Added MASTER text above engine master switches.  
* [x]  Moved and readjusted the heading knob triangle from INPUTS02 to DECALSTEXT_ALBD following ASOBO change.   

## Screenshots 

BEFOREAFTER2

## References

REFREF

Discord username (if different from GitHub): Imenes#8739

## Testing instructions
Check the four changed cockpit decals and inspect the rest of the cockpit for any conflict or bug. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by SaqibSiddiqi** [comment]
Category: QA Tester/Trial
Name: Discord User AssassinXpq#1079
Date of testing: Current date 1/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3273
Tier of testing: 1
Changes to observe: Check the four changed cockpit decals and inspect the rest of the cockpit for any conflict or bug.


Testing technique: 
Started Flight @EGKK and performed a right hand traffic, in offline
	Day time:-
		Landing Gear
		
		Engine Master
		

		Seat

		FCU


	Nighttime:-
		Landing Gear


		Engine Master

		Seat
		Not visible 
		
		FCU

	
 


Flight notes (When done a full flight): EGKK Pattern Flight

Media: 

Issues (If Any): 

Overall Rating: Good
Conclusions of the testing: All Textures have been improved and no visual Bug has been noticed while parked or during flight

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 2.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3273 
Tier of testing: 2
Changes to observe: Cockpit decal changes
Testing technique: Tryout
Steps you've made to test the Pull Request:

1. Spawned C/D in dark environment.
2. Checked heading knob triangle
3. Checked landing gear decal color change
4. Checked Engine Master text
5. Checked seat text
6. Repeated same steps after restarting and spawning in daytime.

Media:
image
image
image
image
image
image
image
image
image


Issues (If Any): None.
Conclusions of the testing: Textures fixed/added are good to go!

**Comment by ImenesFBW** [comment]
While looking at the reference photos and after pictures, I noticed there is a significant spacing between the two landing gear arrows so I decided to squeeze that change in before this gets merged. 
Before:
puscica after
After:
image

**Pull request merged**
