### PR TITLE
fix(lights): Improve initial light switch settings in the various spawn conditions

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

This PR updates the spawn presets for more accurate initial light switch settings:

1. [x] The WING light will be OFF, as it's only used in reality when visually inspecting the wings for icing
2. [x] The RWY TURN OFF light will be ON when starting on the ground or on approach (not cold and dark)
3. [ ] The NOSE light will be TAXI (instead of T.O) when on approach
4. [x] The STROBE light will be ON (instead of AUTO) when in the air or on a runway
5. [x] The LAND lights will be ON when appropriate (on runway, on approach) and RETRACTed otherwise

### Before (Runway)

image

### After (Runway)

image

## References

1. [WING light being usually off](https://www.youtube.com/watch?v=L9XUHepoFDg#t=22m53s)
2. [RWY TURN OFF lights being used when taxiing](https://www.youtube.com/watch?v=L9XUHepoFDg#t=10m10s)

## Testing instructions

This PR modifies the various state files that MSFS uses to initialize the aircraft depending on where the user spawns. For each of the spawn states, check the position of the light switches. Please make yourself familiar with when and how all 8 switches are used, e.g. [using this video](https://www.youtube.com/watch?v=L9XUHepoFDg). If it's unclear why a specific state was chosen (AUTO vs. ON) please ask me.
1. Test the Cold and Dark state by selecting a parking position for departure.
2. Test the Runway state by selecting an airport or a runway for departure
3. Test the Approach state by selecting a runway as arrival, without selecting a departure
4. Test the Cruise state by selecting a random point in the air as departure
5. It's unclear if the `final` or the `taxi` states can be tested.

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by beheh** [comment]
Not quite sure how I can get strobes to start in ON rather than AUTO. `STROBE_1_Auto` did not seem to have an effect.

**Comment by Snapmatics** [comment]
What I have noticed is that you need ON all the time to see them. It probably has to do with .FLT files.

**Comment by tareksabet** [comment]
@beheh the Runway turn off lights it's on before takeoff with landings lights to reduce birds strike  hazard. 
It's in the Procedures in the FCOM.

**Comment by beheh** [comment]
@tareksabet That's already how I'm I'm doing it! Thanks.

**Comment by Benjozork** [comment]
Is this still being worked on ?

**Comment by beheh** [comment]
Well, it's a simple change, but I'm blocked on the Strobe light switch. I was not able to find a SimVar for it. Might have to do XML changes to make that controllable? How do things like YourControls sync this button?

**Comment by Watsi01** [comment]
Just out of the blue. There is an STROBE_1_AUTO=1 under [LocalVars.0]. Did you try something like STROBE_1_ON=1 or maybe STROBE_1_AUTO_=2?

**Comment by beheh** [comment]
Thanks, `STROBE_1_AUTO=0` was indeed the fix.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 24/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2268 
Tier of testing: 1
Changes to observe: Initial light switch settings

Testing technique: Tryout

Steps you've made to test the Pull Request:

1. Spawn C/D at VIDP gate 201. Checked light switch settings

image

2. Spawn at RWY10 VIDP, checked light settings

image

3. Spawn at approach for VIDP RWY10. Checked light settings

image


Issues (If Any): Write any issues


Overall Rating: 
Conclusions of the testing:

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 26/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2268
Tier of testing: 1
Changes to observe: Initial light switch settings changes

Testing technique: Spawn mid-flight 13000ft with a preplanned arrival 30mins ahead towards LOWI

Steps you've made to test the Pull Request:
1. Spawn 13,000ft inbound MADEB - 40nm to the West
2. Observed light panel
3. Noted Landing Lights already positioned to OFF over 10,000ft

Issues (If Any): None - more a query - I specifically spawned over 10,000ft towards LOWI... Landing Lights were positioned to OFF but surely they should be Retracted? is there a way to set this specific to instances where one may spawn above 10,000ft?

Overall Rating: Good
Conclusions of the testing: Switch positions as shown in the screenshotted image attached... query above may be worth exploring/considering if it is appropriate

image

**Comment by Corse-eSports** [comment]
Category: QA Tester
Name: Captain Rafael#0001
Date of testing: 26/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2268
Tier of testing: 1
Changes to observe: Initial light switch settings changes

Testing technique: Spawn at LFRS at the gate

Steps you've made to test the Pull Request:

Spawn  at LFRS
Observed light panel
Issues (If Any): None - more a query -
Rating: Good
Conclusions of the testing: Switch positions  are in the correct position

**Comment by beheh** [comment]
> Issues (If Any): None - more a query - I specifically spawned over 10,000ft towards LOWI... Landing Lights were positioned to OFF but surely they should be Retracted? is there a way to set this specific to instances where one may spawn above 10,000ft?

Could you let me know how you spawned over 10.000ft? Just the 5.000ft + ground elevation? We can't easily detect that unfortunately, it's the same "spawn scenario". I guess I'm not sure what we generally want in this case, but it should probably be either retracted or on. I'm fine going with either retracted or on for the 5.000ft spawn, and with on for the approach spawn.

**Comment by stescouse** [comment]
Category: QA Tester
Name: Discord User stescouse#7271
Date of testing: 26.1.2021
Version of the sim: 1.12.13.0
PR Tested: #2268
Tier of testing: 1
Changes to observe: Initial light switch settings changes

Testing technique: TryOut
Steps you've made to test the Pull Request:

1. Spawned C&D at SKBO checked lights position.

lights setttings


2. Spawned at runway SKBO checked lights position.

lights setttings 2

3. Spawned on APPR at 3500 ft to LFPG checked lights.

lights setttings 3



Flight notes (If required: none

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: Lights in position as outlined in PR.

**Comment by BritishAvgeek** [comment]
> > Issues (If Any): None - more a query - I specifically spawned over 10,000ft towards LOWI... Landing Lights were positioned to OFF but surely they should be Retracted? is there a way to set this specific to instances where one may spawn above 10,000ft?
> 
> Could you let me know how you spawned over 10.000ft? Just the 5.000ft + ground elevation? We can't easily detect that unfortunately, it's the same "spawn scenario". I guess I'm not sure what we generally want in this case, but it should probably be either retracted or on. I'm fine going with either retracted or on for the 5.000ft spawn, and with on for the approach spawn.

I literally clicked on a custom waypoint, hit depart and then I connected that to "high altitude airways" straight into the MADEB arrival at LOWI.... on the right hand side of the map it has a "nav data" bit where you can go in and see the waypoints etc... change that cruise value to 15000ft and hit enter. That got me to spawn high.

I guess spawning in the way I did is a little extreme and unlikely to be a factor for most so leave it as is I suppose! I just went "outside the box" with the test

**Comment by Benjozork** [comment]
Is this still being worked on?

**Comment by beheh** [comment]
Yes. I'll get back to this, it just requires one more tiny change.

**Comment by beheh** [comment]
Alright, fixed the landing light issue. One last test, and then this can be merged.

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 10/03/2021
Version of the sim: 1.14.5.0
PR Tested: #2268 
Tier of testing: 1
Changes to observe: Lights Position
Steps you've made to test the Pull Request:
Media:
**Cold & Dark**
image
**Runway**
image
**Approach**
image

Issues (If Any): 
- On Approach, whith gear down, RWY TURN OFF should also be ON. I dont know what is stated in the FBW procedures, but on my airline we turn on RWY TURN OFF LT everytime we turn on the NOSE LT.

Overall Rating: LGTM

Conclusions of the testing: All good.

**Comment by pepperoni505** [comment]
Is this still being worked on?

**Comment by beheh** [comment]
Not at this time as I'm busy with RL work for a few more weeks. I'll get back to this then. We can close this, or leave it open until I get back to it.

**Comment by raeliass** [comment]
On the 2 companies sop i 
 Worked on, taxi light was used on TO position on both takeoff and landing (on before takeoff roll and after gear down on approach

**Comment by MisterChocker** [comment]
> On the 2 companies sop i Worked on, taxi light was used on TO position on both takeoff and landing (on before takeoff roll and after gear down on approach

this is also my experience

**Comment by MisterChocker** [comment]
@beheh What is the status of this? What is missing to get it ready for review?

**Comment by Illuminati270** [comment]
> On the 2 companies sop i Worked on, taxi light was used on TO position on both takeoff and landing (on before takeoff roll and after gear down on approach

Same for me!

**Comment by Benjozork** [comment]
Is this still relevant?

**Comment by beheh** [comment]
It is, but we can close this for the time being as I'm currently working mostly on Rust code outside of the simulator. Someone else can pick this up in future.

**Pull request closed without merging**
