### PR TITLE
fix: Standby Compass decal text extraneous S

### PR DESCRIPTION
**Pull request by FoxinTale**
Fixes #[issue_no]

## Summary of Changes

Removed a random additional S from standby compass. That's it. Small fix.

## Screenshots (if necessary)

Before:
image

After:
image

## Additional context

Discord username (if different from GitHub):
Aubrey Jane#7563

## Testing instructions

If I'm not mistaken, all that needs to be checked is that I didn't screw up anything else, and that there is no longer three S by standby compass. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by pepperoni505** [comment]
Please include a before & after

**Comment by FoxinTale** [comment]
Before/after added now, after an escapade of derpiness on my end.

**Review by davidwalschots — APPROVED** [review]
LGTM

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 28.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3221 
Tier of testing: 1
Changes to observe: Standby Compass text

Testing technique: Tryout
Steps you've made to test the Pull Request:

1. Spawned at RWY27 VABB
2. Observed STBY COMPASS switch text.
3. Glitching observed
4. Repeated steps with dark environment and lights on.

Media: 
image
image


Issues (If Any): Same as in media. Glitchy text observed
Overall Rating: Needs improvement

**Review by DarkOfNova — CHANGES_REQUESTED** [review]
Aubrey, it looks like there's a conflict between the emissive and albedo. I think the best option is to use the default Asobo one as a reference and overlay it on top of ours then change the font and colour accordingly so everything fits.

**Comment by FoxinTale** [comment]
> Aubrey, it looks like there's a conflict between the emissive and albedo. I think the best option is to use the default Asobo one as a reference and overlay it on top of ours then change the font and colour accordingly so everything fits.

That's what I've done for this though.  In the gimp projects, the default is there and I used it as a reference. I did notice something wrong with the not emissive when I submitted this, but the emissive is a carbon copy, just with the proper colours and font.

**Comment by ImenesFBW** [comment]
If you are having problems with this one, I still have my files ready to go. 
 
image

**Comment by ImenesFBW** [comment]
You seem to have exported in 2048 instead 4096 and the heading knob blue triangle  that we added before so it overlaps, we can remove it from input2, but should be in same PR:
image

Also those ( ) might overlap somewhere since we don't use that in our emissive, need to check and make sure where that is used:

image

**Comment by ImenesFBW** [comment]
Opened #3236 that should fix this and some other issues.

**Comment by pepperoni505** [comment]
Closing this in favor of #3236

**Pull request closed without merging**
