### PR TITLE
fix: PFD backlight color

### PR DESCRIPTION
**Pull request by wpine215**
## Summary of Changes

Fixes PFD backlight coloration issues that occurred after reverting pixel changes.

## Screenshots (if necessary)

Before:
image

After:
image

## Additional context

Discord username (if different from GitHub): Iceman#5540

## Testing instructions

Load into sim at night. Turn up PFD & ND backlights. Ensure background colors match,

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #6335 
Tier of Testing: 1
Date: 09/12/2021

**Testing Process:**
1. Loaded in at night and checked displays

**Negatives:** 
- I do have blue borders around all front displays

**Testing Results:** Not Passed

**Media:**
image

**Comment by bouveng** [comment]
> * I do have blue borders around all front displays, colors do match though
> **Testing Results:** Not Passed

@St54Kevin Hi Kevin. What does not pass in this PR? 👀 

Br.

/J

**Comment by St54Kevin** [comment]
> > * I do have blue borders around all front displays, colors do match though
> >   **Testing Results:** Not Passed
> 
> @St54Kevin Hi Kevin. What does not pass in this PR? 👀
> 
> Br.
> 
> /J

It creates borders around all displays that are NOT present in the current dev version. So it somehow is related, its up to @wpine215 to decide wether thats something to look over or not. I was just testing and experienced that bug :P

**Comment by davidnorfolk96** [comment]
Quality Assurance Report

Discord: !davidn123#0001
Object of testing: #6335
Tier of Testing: 1
Date: 14/12/2021

Testing Process: Loaded into EGKK 26Lat night & tested the following 

Load into sim at night. Turn up PFD & ND backlights. Ensure background colors match-PASSED


Negatives: n/a

Testing Results: Passed

Conclusions: All tested & worked as intended. Played with the dimmers to ensure the correct brightness was the same across all screens. 

Media: 
Screenshot_2

**Comment by jcalor** [comment]
Quality Assurance Tester Report

Discord          : Calo#6816
Object of testing: #6335 
Tier of Testing  : 1
Date             : 14/12/2021

Testing Process: 

- Spawned at night and checked PFD color.

Negatives:  N/A

Testing Results: Passed

Conclusions: Nothing to add. Quite simple PR.

Media:

image

**Comment by tareksabet** [comment]
Quality Assurance Tester Report

Discord          : tarek_sabet#7946
Object of testing: #6335 
Tier of Testing  : 1
Date             : 22/12/2021

Testing Process: 
* Spawned at night having PFD in full brightness and changed the time of the day 

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Working as intended to be, LGTM easy work !

Media:       
Microsoft Flight Simulator Screenshot 2021 12 22 - 02 55 11 44
Microsoft Flight Simulator Screenshot 2021 12 22 - 02 56 02 42

**Pull request merged**
