### PR TITLE
refactor: rename package from A32NX to flybywire-aircraft-a32nx

### PR DESCRIPTION
**Pull request by pepperoni505**
Fixes #[issue_no]

## Summary of Changes

This PR changes the package name from A32NX to flybywire-aircraft-a32nx. The reason for this is the old package name was made before we knew of the proper naming conventions.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

There are no new features, and nothing was removed. This is just a simple rename. Make sure nothing is broken and everything behaves the way that it should.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **flybywire-aircraft-a32nx** link

### CODE REVIEW

**Comment by nistei** [comment]
This will break the installer

**Comment by pepperoni505** [comment]
> This will break the installer

Would we just need to change the target directory in the mod definition?

**Comment by nistei** [comment]
> > This will break the installer
> 
> Would we just need to change the target directory in the mod definition?

Yes, but what would the transition look like then?

**Comment by Watsi01** [comment]
I totally agree with the idea of adapting to the naming conventions of the community folder.
Although we would need to uninstall the A32NX folder in the users community-folder first. Best method would be automatically with the installer itself. But that would mean additional programming. We also could tell people to manually uninstall A32NX first (through the installer?). 

Then I see many issues coming "A32NX mod not working anymore...."

"...please uninstall..."

**Comment by FoxtrotSierra6829** [comment]
We could add some lines in the installer which deletes the A32NX folder on updating, but we would need to update all versions at once, stable as well, to avoid any inferference. I think we should maybe prepare for a renaming that happens on the next stable release (which could already be on tuesday, who knows what they are going to to with WU3)

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 14/2/21
Version of the sim: 1.12.13.0
PR Tested: #3516 
Tier of testing: 1
Changes to observe:
File name change and behaviour in sim
Testing technique: Loaded in
Steps you've made to test the Pull Request:
1. Put the new file into community
2. Loaded in
3. Turned on external power

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
image
image
image


Issues (If Any): When putting the file in community it says some file names are too long (starts with the file shown and does it for a lot more but not the main file), because of this it is missing out some files and so as shown above in Media:

- Batteries show 0.0V
- With external and batteries on displays will not turn on

Steps to achieve the issue

Overall Rating: To be improved
Conclusions of the testing: This is causing a lot of issues which I have not experienced before when downloading the mod

**Comment by vkrizan** [comment]
Hi @pepperoni505, have you thought about renaming the folder just for the built ZIP file? End user would get it named as desired, and developers would not need to undergo conflict fixing (on the opened PRs).

**Comment by bbelliot** [comment]
Category: QA Trial
Name: Elliot#7195
Date of testing: Current date 15/02/2021
Version of the sim: 
PR Tested: #4103
Tier of testing: 1
Changes to observe: File name change, observe if mod behaves normally

Testing technique: Installed and performed cold and dark startup
Steps you've made to test the Pull Request:
1. Start up on gate cold and dark
2. Completed a full startup as per the checklist
3. Taxi to runway
4. Took off departing 
5. Looped around to land performed an ILS arrival touch and go
6. Looped around to land performed a RNAV arrival touch and go
7. Looped around to land performed a DME arrival full stop
8. Taxi to gate
9. Shutdown the aircraft as per the checklists
10. Started back up from cold and dark state, end of test

Flight notes: EGCC 23R- ILS 23R EGCC

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues: No issues, modification performing as expected

Overall Rating: Good
Conclusions of the testing: When compared to the current build this modification works perfectly, no performance issues located and all of the systems are working as they should.

**Comment by beheh** [comment]
@ pepperoni505 I'll remove RTT for now as we have two tests, one that encountered issues, and it seems like this should be retested anyway once we're very close to doing this and have rebased the changes.

**Comment by pepperoni505** [comment]
> @ pepperoni505 I'll remove RTT for now as we have two tests, one that encountered issues, and it seems like this should be retested anyway once we're very close to doing this and have rebased the changes.

Alright, sounds good

**Comment by pepperoni505** [comment]
@FlightSimmer7700 Can you send your path to your community folder?

**Pull request closed without merging**
