### PR TITLE
[LIGHTS] Interior Lights - Big Changes & Fixes

### PR DESCRIPTION
**Pull request by Snapmatics**
# Summary of Changes

## Interior Lighting Improvements

- [x] FCU Display Backlighting
- [x] ATC Displays Backlighting
- [ ] Squawk Code Text Improvements

+ More Incoming

## Interior Lights (Fixes)

- [x] Chronometer
- [x] Rudder Trim
- [x] "PULL STD" Text
- [ ] TCAS Backlight

+ More Incoming

# Screenshots
## PULL STD
Screenshot_235

## RUDDER TRIM
Screenshot_236

## FCU Backlighting
Screenshot_234

# How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

    1. Make sure you are signed in to GitHub
    2. Click on the Checks tab on the PR
    3. On the right side, click on the Artifacts drop down and click the A32NX link

### CODE REVIEW

**Comment by St54Kevin** [comment]
Could you please recheck the Main Panel flood lights again. They are way too bright on the lowest and highest setting IMO

**Comment by Snapmatics** [comment]
> Could you also please recheck the Main Panel flood lights again. They are way too bright on the lowest and highest setting IMO

Will do

**Comment by NathanInnes** [comment]
Add a changelog when you have time also :). Good work

**Comment by Snapmatics** [comment]
> 
> 
> Add a changelog when you have time also :). Good work



> 
> 
> Add a changelog when you have time also :). Good work

Thanks mate, your second PR would create conflicts since it's not just the backlight I would have changed on the TCAs area but the text itself and the edges around the purple thing.

**Comment by Snapmatics** [comment]
> 
> 
> > Add a changelog when you have time also :). Good work
> 
> Thanks mate, your second PR would create conflicts since it's not just the backlight I would have changed on the TCAs area but the text itself and the edges around the purple thing.

**Pull request closed without merging**
