### PR TITLE
fix: removed unusable fuel from refueling

### LINKED ISSUE #4569: Incorrect EFB Fuel Tank Capacities (Again)
**Aircraft Version**

```json
"built": "2021-04-24T19:05:06+00:00",
  "ref": "master",
  "sha": "43a8c41776d5b381af620ecc47fcfdaab29bee3b",
  "actor": "aguther",
  "event_name": "manual"
```

**Describe the bug**

The EFB fuel tank capacities are incorrect. The latest developer version of the mod reverted https://github.com/flybywiresim/a32nx/pull/4391, which had fixed them and closed https://github.com/flybywiresim/a32nx/issues/4322.  Due to changes in how the fuel flow system is used in the new developer version, the previous fix to this issue cannot be used in its entirety. (Portions of it could still be used to at least partly fix this issue.)

Someone who understands exactly what changes were made to fuel system that prevents the previous fix from working needs to address this, either by making changes that will allow the previous fix to be applied again, or by providing a new fix that will work with the new fuel system. I would be glad to work with whoever that may be to get this issue fixed (again).

This screenshot illustrates the issue. Note the differences between the fuel tank capacities shown in the EFB compared to the MSFS weight and balance window.
Screenshot (783)

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

For more information, see the previous issue and pr referenced above.
Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):donbikes#4084

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #4569

## Summary of Changes

Changes made in the fuel flow  caused the defueling via the efb to glitch out and rise to infinity.

Thanks to @Maximilian-Reuter @donstim for pointing out the fact that this was already fixed by https://github.com/flybywiresim/a32nx/pull/4391 but intentionally reverted after the merge of the experimental branch for compatibility with the updated fuel flow

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Spawn in and open the efb fuel page
2. Choose a lower amount than the current fuel and start defueling. It must not rise
3. Check that refueling works as before

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by donstim** [comment]
I think you mean it was fixed by https://github.com/flybywiresim/a32nx/pull/4391? That PR was reverted intentionally, not accidentally when the experimental version was merged to dev. See https://github.com/flybywiresim/a32nx/issues/4569. The reversion was done because setting the unusable fuel to zero in the flight model.cfg file would cause the fuel flow in the new fuel flow to go bonkers.

I was waiting for this pr to be merged, so I could get https://github.com/flybywiresim/a32nx/pull/4391reinstated. Your PR only reinstates a portion of 4391. Incorrect fuel quantities will still be shown in the EFB. I guess you can proceed with this pr, and I will open another pr to fix the rest of it.

**Comment by Saschl** [comment]
Oh yes you're right of course. I got quite a bit confused today with all the branches ;) I'd be willing to fix the issues you mentioned provided I understand all the changes that were made. To my knowledge #4658 removed the unusable fuel without touching the rest of the capacities (correct me if I'm wrong of course). I originally aimed only to adapt this changes  for the EFB but we can of course enhance the scope a bit. As you wish

**Comment by donstim** [comment]
Here is the whole story (well, a summary anyway). The actual fuel tank capacities for the airplane are contained in the flight model cfg file. They were not changed by any of these changes we are talking about. The EFB also contains fuel tank capacities, but those values don't affect the actual fuel tank capacities. The affect the EFB display of fuel quantities and refueling. The EFB tanks quantities were wrong (didn't match the flight model cfg values) and #4391 fixed that.

During the QA process for #4391, I found that a bug in the MSFS fuel system causes the unusable fuel to actually be used. Since the fuel tank is already empty by that time, it results in a negative fuel quantity when using the unusable fuel.  #4391 also set the unusable fuel to zero in both the flight model cfg file and the EFB to prevent this from happening.

Then the new fuel flow model, which was part of the custom autopilot build, came along. A zero unusable fuel value causes that model to go bonkers, so the entire #4391 pr was reverted when the custom autopilot build was merged into dev. I opened issue #4569 as a result. PR #4658 fixed the fuel flow model and reset the flight model cfg unusable fuel values to zero. I was waiting for that PR to get merged, so I could reinstate #4391. I wasn't paying close enough attention and didn't realize that it got merged a couple of days ago. 

So, I am hoping you can revise this pr to include the other changes made in #4391 to again fix the fuel tank capacity values shown in the EFB and fix #4569. You can see these changes in #4391. Specifically, it would be to change const totalFuelGallons = 6243 to 6267 in the refuel.js file, and change  const totalFuelGallons = 6243;
    const outerCellGallon = 227;
    const innerCellGallon = 1809;
    const centerTankGallon = 2173;
    to 
const totalFuelGallons = 6267;
    const outerCellGallon = 228;
    const innerCellGallon = 1816;
    const centerTankGallon = 2179;
in the FuelPage.tsx file.

Thanks!

**Comment by Saschl** [comment]
Thanks for the detailed explanation, I followed those PRs before but now the issues we had are clear! Changes are included now.

**Comment by donstim** [comment]
Not sure why this needs a code review. No code was changed; just some values of variables within the code.

**Comment by Saschl** [comment]
That’s again correct. If you say it’s fine it’s enough of a review. Just need an approval 👍

**Review by donstim — APPROVED** [review]

**Comment by donstim** [comment]
> That’s again correct. If you say it’s fine it’s enough of a review. Just need an approval 👍

Haha... Didn't even know I could do that!

**Comment by darkfury334** [comment]
Category: QA Trial
Name: DarkFury#4936
Date of testing: Current date 06/05/21
Version of the sim: 1.15.10.0
PR Tested: #4171
Tier of testing: 1
Changes to observe:
defueling via the efb

Testing technique: Test

Steps you've made to test the Pull Request:
1. Spawn in at LFPG & open the efb fuel page
2. Enter lower amount than the current fuel and start defueling
3. Check for defueling and that it does not rise
4. Restart and repeat steps 1 -3 with different lower fuel amount than current fuel on spawning
5. check for defueling

Flight notes (When done a full flight):N/A

Media:
Microsoft Flight Simulator Screenshot 2021 05 06 - 22 04 57 99


Issues (If Any): N/A

Overall Rating: Good
Conclusions of the testing: Works as intended. cheers

**Comment by ExampleWasTaken** [comment]
Category: QA Testers
Name: `ExampleWasTaken#0886`
Date of testing: 7/5/2021
Version of the sim: 1.15.10.0
PR Tested: #4717 
Tier of testing: 1
Changes to observe: removed unusable fuel from refueling

Testing technique:
1. Defueled 
2. Refueled

Overall Rating: Good
Conclusions of the testing: Even though @tshomas won't like it this is GTG. (<-- see https://discord.com/channels/738864299392630914/754130199804772372/839972200751693865) 🤪

**Review by aguther — APPROVED** [review]

**Pull request merged**
