### PR TITLE
fix(textures): remove black dots add parentheses, SELCAL CODE

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

This fixes a few small bugs introduced by the recent cockpit decal texture rework. And darkens the heading knob bug.

- Removed extraneous black dot and square covering up landing gear arrow and throttle lever deflection markers
- Added the parentheses (speed placard) that were removed by the cockpit decals rework 
- Made the heading bug knob triangle a darker shade of blue
- Added SELCAL CODE that was removed by the cockpit decals rework, downscaled DECALSALPHA_ALBD to 2K, and remade the SELCAL CODE following multiple references.  
- Added the emissive for the circle markings (SPEED MACH, VOR, TRK/FPA, METRIC ALT,... )

## Screenshots (if necessary)
screen1
screen2
screen3
screen5
screen7

## References

main-qimg-4631517aeef65d0cfc800842bb579945

image
image

## Additional context
The parentheses, circular markings emissive and SELCAL CODE were left behind with #3693 and there were two small bugs introduced. Since there is no real reason to have DECALSALPHA_ALBD in 4K I have also downscaled the DDS to 2K after discussion with @DarkOfNova . Modified SELCAL CODE to better fit references. They all look a bit different so I mostly followed one of the references with some adjustments. 

On the new cockpit textures, the heading knob triangle looks way too light so I darkened it by a significant margin to make it look closer to the one in the real cockpit.

Discord username: Imenes#8739

## Testing instructions

Inspect the cockpit decals to make sure the bugs are fixed and see if you spot any further regressions that can be fixed.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 25/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3712 
Tier of testing: 1
Changes to observe: Textures
Testing technique: 
Steps you've made to test the Pull Request:
1. Loaded up and checked the 4 textures

Media:
image

Issues (If Any): I do have a weird shimmering effect on the IAS letters from all angles. Looks like something is bleeding through

Overall Rating: See above

Conclusions of the testing: Works as described

**Comment by ImenesFBW** [comment]
That's, unfortunately, the same as the default placard (only the parentheses were added) while we use the default placard we can't edit it, but this will soon be made a decal by Nova and Tyler and then it will be nice and clean, but for now, we need to consider this beyond the scope of this PR.

**Comment by ImenesFBW** [comment]
Noticed SELCAL CODE also went missing so I have readded it and downscaled DECALSALPHA_ALBD to 2K.

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 25.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3712 
Tier of testing: 1
Changes to observe: Decal Fixes


Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Checked Selcal Plate
2. Checked Gear Arrow
3. Checked Heading Knob
4. Checked Throttle

Media:
Microsoft Flight Simulator Screenshot 2021 02 25 - 18 05 48 43
Microsoft Flight Simulator Screenshot 2021 02 25 - 18 06 01 38

Issues (If Any): none


Overall Rating: Good
Conclusions of the testing: Selcal is back, other decals are fixed, all good and as it should be.

**Comment by ImenesFBW** [comment]
Since we were using a pretty basic SELCAL CODE plate, I decided to redo it following multiple references. 
screen6

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 25.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3712
Tier of testing: 1
Changes to observe: Dots and Plates
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Looked for the decals

Media:


Image1

Issues: -

Overall Rating: Good

Conclusions of the testing: Looks good.

Hope this helps :-)

**Review by davidwalschots — APPROVED** [review]

**Comment by ImenesFBW** [comment]
Squeezed in one more fix for a bug found by @ChruutvoLuzi which is the circle markings emissive (SPEED MACH, VOR, TRK/FPA, METRIC ALT,... ).
screen7

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 26/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3712 
Tier of testing: 1
Changes to observe: "Fix" to cockpit texture black dots

Testing technique: Spawned C&D, checked with backlighting
Steps you've made to test the Pull Request:
1.  Spawned C&D
2.  Checked around cockpit for black dots or any issues with textures not already mentioned above - those above, checked for fixes
3. Turned backing lights on - checked for all emissives and relevant textures being correct including the fix mentioned above

Flight notes (When done a full flight): N/A

Media:  N/A

Issues (If Any): None found, fixes mentioned above were fine


Overall Rating: Good
Conclusions of the testing: No issues found.

**Pull request merged**
