### PR TITLE
refactor(pfd): move towards tsx

### PR DESCRIPTION
**Pull request by davidwalschots**
## Summary of Changes
To reduce unrelated changes in #5598, this PR moves the PFD from `*.jsx` to `*.tsx`. Note that some of its dependencies remain `*.jsx` for now. Note that I haven't added types throughout, only in locations where the editor (vscode) gave hints or complained.

## Additional context

Discord username (if different from GitHub): SjotgunSjonnie#9623

## Testing instructions
Does the PFD still work as it did before?

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM!

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5626
Tier of Testing: 1
Date: 13.8.21

Testing Process:
Full flight from C&D at gate to gate (EDDM-LOWI)

Negatives: None - worked as expected
Testing Results: Passed

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5626
Tier of Testing: 1
Date: 13/08/2021

Testing Process:
- Loaded in on runway at EGSS, Full flight conducted from EGSS-EGJJ.
- Observed PFD to check everything was working as normal. 

Negatives: N/A
Testing Results: Passed

Conclusions: Can't tell anything has changed, everything still works exactly the same as previously. Great stuff!

Media: 
image

**Comment by ewold** [comment]
Quality Assurance Tester/Trainee Report

Discord: E-wold#8195
Object of testing: #5626 
Tier of Testing: 1
Date: 13/08/2021

Testing Process:
Loaded in C+D. Performed a flight from PADQ to PAVD. PFD didnt have issues during flight/
Negatives N/A
Testing Results: Passed

Conclusions: Works like expected

**Pull request merged**
