### PR TITLE
feat(sound): add wwise events to glareshield chrono buttons

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

- added sound events to glareshield chrono buttons 

## References
@hotshotp 

Discord username: Imenes#8739

## Testing instructions
Check that both CP and FO chrono buttons produce sound, and retain the previous functionality. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by hotshotp — APPROVED** [review]
LGTM!

**Comment by Samueleonard** [comment]
Category: QA Tester
Name: 1Samueleonard1#0001
Date of testing: Current date 01/05/2021
Version of the sim: 1.15.8.0
PR Tested: #4673
Tier of testing: 1

Changes to observe: chrono buttons have sound/function

Testing technique: Tryout
1. loaded in C+D, powered up
2. pressed cpt chrono button - there was sound
3. pressed fo chrono button - there was sound
4. check cpt and fo chrono functions as before - they do

Flight notes: lgtm

Media: n/a

Issues: n/a

Steps to achieve the issue: n/a

Overall Rating: Good

Conclusions of the testing: small fix, lgtm

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 1.05.2021
Version of the sim: 1.15.8.0
PR Tested: #4673
Tier of testing: 1
Changes to observe: Glareshield chrono button sound and function

Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power
3.) Tested chrono buttons and listened for sound

Issues: -

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Comment by Mack674** [comment]
Category: QA Trial
Name: Mack674#2274
Date of testing: Current date 01.05.2021
Version of the sim: 1.15.8.0
PR Tested: #4673
Tier of testing: 1
Changes to observe:
- CP / FO chrono buttons have sound

Testing technique: Tryout

Steps you've made to test the Pull Request:
1. Spawned at EGKK
2. Started powering up according to procedures
3. Pressed both buttons and checked the sound and functionality

Flight notes: - 

Media: 

https://user-images.githubusercontent.com/62873705/116811108-d638b380-ab47-11eb-9a2b-754a836cd1de.mp4

Issues (If Any): No issues

Overall Rating: Good

Conclusions of the testing: Everything works as it should. The buttons have a sound and a stopwatch appears on the screens and it counts the time.

**Comment by easyjetsimpilot** [comment]
Category: QA Tester/Trial
Name: Gavin (easyjetsimpilot)
Date of testing: Current date 03/05/2021
Version of the sim: 1.15.8.0
PR Tested: #4673
Tier of testing: 1
Changes to observe: Check Chrono button functionality and sound 'click'

Testing technique: Test Chrono Button

1. Spawned C&D
2. Power up the A/C
3. click Chrono on FO/CPT sides
4. check both function as normal (start - stop - reset)
5. check 'click' sounds audible

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: PR worked as expected. Thank you.

**Pull request merged**
