### PR TITLE
Improved Build.py - crawls for .locpak and other modified root files, better validation

### LINKED ISSUE #763: [BUG] build.py sometimes wipes the entire manifest.json / layout.json
**Mod Version**

masterrrrrr

**Describe the bug**

build.py likes to clear manifest.json or layout.json completely and crashes partway through

**To Reproduce**

1. run build.py
2. 
3.

**Expected behavior**

build.py to generate the manifest/layout.json's

**Actual behavior**

build.py ends up corrupting the layout.json/manifest.json some of the time

**References**

python closes,

**Additional context**

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by 2hwk**
Potentially helps resolve #763 

**Summary of Changes**

* Crawls through root directory and grabs files to be listed in layout.json (except those listed in exclusion blacklist) - For loading of localisation files i.e. en-US.locPak
* Checks for valid data before writing to layout.json and manifest.json, error printout on failure to stderr
* Uses with statements to ensure proper management of file streams

**Screenshots (if necessary)**

**Additional context**

Currently custom locPak files do nothing, this is just preparation for when we can load into the sim and use our own localisation strings. Issue #763 is intermittent and hard to test, but these changes may help to resolve the issue and prevent corruption of layout.json and manifest.json in general.

Discord username (if different from GitHub): 2Cas#1022

### CODE REVIEW

**Comment by Benjozork** [comment]
Hello, please take note that we have started including a CHANGELOG.md file that requires every PR to add a change-log line that describes its changes. As your PR is not merged yet, we kindly ask that you add this information following the included directives in the file.

Disclaimer: This is a copy-and-pasted message.

**Comment by 2hwk** [comment]
build.py is our script, 100% chocolate no vanilla here.

**Comment by AdenFlorian** [comment]
FYI, this new build.py doesn't work with python 2, but the old one did

**Comment by AdenFlorian** [comment]
its probably fine, CI uses python 3, tested it a bit locally, LGTM!

**Pull request merged**
