### PR TITLE
fix: Update flaps in flight model for MSFS update 1.14.5.0

### LINKED ISSUE #3913: [BUG] Take off w/ flaps - Hard to gain speed at 10 degree pitch
**Mod Version**

**Describe the bug**

After Sim 3 update, the aircraft does not gain speed upon takeoff and at 10 degree pitch! Would think this is reported by other but I can't find this being reported! The speed stays at 140 knots.

**To Reproduce**

1. Do a take off at 10 degree pitch and flaps 1+f
2.
3.

**Expected behavior**

The plane was gaining speed before the Sim update 3. With fuel at 5,000 KG, these planes should gain speed quickly at 10-12 degree pitch.

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Yes, it was somewhat working before the Sim 3 update.
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by donstim**
Fixes #3913 

## Summary of Changes

**REVISED***
1. Changed flap entries to be compatible with MSFS update 1.14.5.0
2. Improved pitch angles for intermediate flap settings 
3. Reduced maximum N1 to provide more realistic takeoff N1 values
4. Reduced thrust at takeoff N1 and Mach to address comment from @Watsi01 below
5. Increased thrust at approach N1 and speed to provide more realistic N1 values at approach
6. Tailored flap drag to better match N1 values in unreliable airspeed table (which wasn't even attempted with the previous flight/engine mode), provide more accurate approach speed/path control, and reduce landing float that received a lot of comments below.
## References

Here are the target pitch angles for flaps down conditions:
Screenshot (697)

Here were the pitch angles that were achieved in the previous flight model:
Screenshot (699)
Here are the pitch angles and N1 values achieved with this PR:
Screenshot (718)
(See discussion below for the reason the CONF 1 pitch angles are not matched. For CONF 3, I placed more emphasis on matching the pitch angles during approach then during level off.)

## Additional context

An issue that we did not have before MSFS SU3 came to light during the development of this PR that limits the accuracy we can achieve with CONF 1 and 1+F lift and drag. As of SU3, we can no longer differentiate lift and drag in the flight model between these 2 configurations. So, not only can we not accurately model slats aerodynamically, we are now limited to having the same lift and drag for CONF 1 as CONF 1+F. I've tried my best to strike a balance between the two.

This ended up being a major rewrite of the flaps portion of the flight model instead of just an MSFS SU3 compatibility fix. It should be much more accurate than the previous flight model in that regard. But it needs more QA testing because of that to make sure there aren't any significant hidden issues. 

One known issue is the landing float issue brought up by many commenters on the first iteration of this PR. I think it has been reduced, but not eliminated. I tested a reduction in the ground effect lift that seemed to fix it pretty well, but it did not work well with the custom fbw version of the mod. So I left it out. Based on that, I think the remaining float issue with the dev division is more of an issue with having an incorrect and inappropriate flight control law active (and even that is not modeled all that well) in the default fbw system used by the dev and stable versions.

Discord username (if different from GitHub):donbikes#4084

## Testing instructions

This is a flight model change affecting flap lift and drag and takeoff and approach thrust/N1. Takeoffs and landings (including approaches) should be conducted in all approved takeoff (1+F, 2, and 3) and landing (3 and Full) configurations. It does not affect flaps up flight characteristics, so full flights are not necessary. 
Specifically look for:
1) The initial takeoff climb performance is modeled to hold approx V2+10 at a pitch angle of 15-18 degrees. Depending on your weight and pitch rate, you may overshoot V2+10, but it should hold speed at the 15-18 degree pitch angle.  It should be vastly improved over iteration 1, but I could only do a limited number of takeoffs at a limited number of locations.
2) Check pitch angles and N1 values in accordance with the tables above, but I am pretty confident that those are okay. Remember that CONF 1 and 1+F have the same lift and drag, so it is not possible to match pitch angles and N1 values precisely for those configurations.
3) Check approach path and speed control in the different flap and landing gear configurations. Because of the CONF 1/CONF 1+F MSFS issue, there is probably a bit more drag in CONF 1+F than IRL. Deceleration capability in CONF 2 is my interpretation of what I am hearing from our pilots -- i don't have any hard data to try to match.
4) Check to see whether the landing characteristics are adequate using the recommended procedures for the airplane or whether additional tweaking is needed. (Keep in mind the comments above regarding differences between the custom and default fbw systems).

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by Samueleonard** [comment]
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: 10/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3878
Tier of testing: 1
Changes to observe: flap + flight model fix
Testing technique: Tryout

Steps you've made to test the Pull Request:
1. load in on runway
2. takeoff and level out, clean config, stable flight
3. extend flaps and notice pitch changes
4. retract flaps to clean and notice pitch changes
5. position onto final
6. extend flaps and gear into landing config

Flight notes (When done a full flight):
flap 4 seems to generate a lot of lift, may be an isolated incident
otherwise no issues, seems to behave okay

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any):
noted above

Steps to achieve the issue

Overall Rating: Good

Conclusions of the testing:
small issue with flaps 4, may need to be investigated by others, otherwise fine

**Comment by donstim** [comment]
> Conclusions of the testing:
> small issue with flaps 4, may need to be investigated by others, otherwise fine

Good observation. It definitely does, but also did in the pre-update version. Too bad we can't do a back-to-back comparison anymore!

**Comment by SpeedDemon77** [comment]
Category: QA Tester
Name: Delta Zero#0115
Date of testing: 3/9/2021
Version of the sim: 1.14.5.0
PR Tested: #3878
Tier of testing: 3
Changes to observe: flap + flight model fix
Testing technique: Tryout

Steps you've made to test the Pull Request:

standard takeoff + landing
1. Loaded in on the runway
2.  Took off flaps 1
3.  Did a pattern and landed flaps 1
4. Touch and go at flaps 2
5. Did a pattern and landed at flaps 2
6. Touch and go at flaps 3
7. Did a pattern and landed at flaps 3
8. Touch and go at flaps 4
9. Did a pattern and landed at flaps 4
10.  Went back and started on the runway to takeoff flaps 4
11. Did a lap in the pattern and landed again with flaps 4
12. After a full stop, I took off flaps 1 and came in for a flaps 3 approach to retest
13. Landed to confirm that flaps 3 is working fine

Issues (If Any): Flaps 4 produces a lot of lift as other testers have noted.
Steps to achieve the issue:
Extend Flaps 4

Overall Rating: To be improved

Conclusions of the testing: Overall pretty good. This is a lot better than the stock after the update but I believe the airplane generates too much lift at flaps 4. I was at flaps 4 power idle, losing 100fpm while decreasing speed by 2kts(but it was fluctuating to maintain airspeed). I was able to allow the airplane to float nearly 3/4 of the runway with flaps 4 and power idle without sinking into the runway. Other flap settings appear to operate well. Flaps 4 is my only issue, everything else operates fine. Thank You!

**Comment by starvingjavi** [comment]
Category: QA Tester
Name: Javi#2557
Date of testing: 9/3/2021
Version of the sim: 1.14.5
PR Tested: #3878 
Tier of testing: 3
Changes to observe: Flight model fix. Check for no problems


Testing technique: Made 3 different turnaround flights between MMAA and MMMX
Steps you've made to test the Pull Request:
1. Do full flight MMAA -> MMMX with take off flaps at 1 and landing with full flaps. Check for pitch attitudes according to the tables in PR
2. Continued after landing for another flight back into MMAA. Took off with flaps 3 and landed with Flaps 3. Check for pitch attitudes according to the tables in PR.
3. Reloaded the sim back in MMAA. Set for take off flaps 2 and landed with flaps 4. Check for pitch attitudes according to the tables in PR.

Flight notes : Noticed that before even taking off it was needed to push the altitude knob to get the airplane into climb mode after take off. Otherwise it would dive and go into a descent into 5000 feet. Not related to PR


Issues (If Any): No issue with this PR.


Overall Rating: Good
Conclusions of the testing: Checked for more lift in flaps 4 but the airplane follows the pitch angles as described in the table for me

**Comment by SpeedDemon77** [comment]
Category: QA Tester
Name: Delta Zero#0115
Date of testing: 3/9/2021
Version of the sim: 1.14.5.0
PR Tested: #3878
Tier of testing: 3
Changes to observe: flap + flight model fix
Testing technique: Tryout

Steps you've made to test the Pull Request:

standard takeoff + landing

1. Loaded in on the runway
2. Took off flaps 1
3. Did a pattern and landed flaps 1
4. Touch and go at flaps 2
5. Did a pattern and landed at flaps 2
6. Touch and go at flaps 3
7.  Did a pattern and landed at flaps 3
8. Touch and go at flaps 4
9. Did a pattern and landed at flaps 4
10. Went back and started on the runway to takeoff flaps 4
11. Did a lap in the pattern and landed again with flaps 4
12. After a full stop, I took off flaps 1 and came in for a flaps 3 approach to retest
13. Landed to confirm that flaps 3 is working fine

Issues (If Any): Flaps 4 produces more lift than expected.
Steps to achieve the issue:
Extend Flaps 4

Overall Rating:  Good
Conclusions of the testing: Overall pretty good. This is a lot better than the stock after the update but I believe the airplane generates a little too much lift at flaps 4 as others have mentioned. Other flap settings appear to operate well. Thank You!

**Comment by donstim** [comment]
As a result of the comments about extended float on landing flare with full flaps, I have made an adjustment to increase the drag during the landing flare maneuver. This should help decelerate the airplane and settle it down onto the runway.  Changing the lift is outside the scope of this PR other than to hit the pitch angle targets. The lift and pitch angles on landing are pretty much unchanged from the pre-PR version.

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 10/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3878 
Tier of testing: 2
Changes to observe: Flight model with flaps
Steps you've made to test the Pull Request:
1. Spawned on RWY (ISA condition weather)
2. Took off, made some level flight test to check the reference doc (flaps, gear, 70t/60t/50t) see media
3. Flaps full approach and landing with 60t

Media: 
**I compared this table:**
image

**With my values (red marked are big difference, amber slightly difference:**
image

Issues (If Any): 
- Something is wrong with Flaps 1+F S speeds. They are the same as Flaps 1 speeds. The reference table shows different values though (15kt difference).
- Flaps 3 gear down level flight has slightly different pitch and speed values.
- Flaps 2 level flight has lower F speeds than in the reference table (I flew the reference speed to compare pitch, my F speed is in brackets)

Overall Rating: Needs improvements.

Conclusions of the testing:

**Comment by Watsi01** [comment]
Without filling out a full test report I checked this flaps PR (MSFS: 1.14.5.0) and recognized a much higher lift on takeoff/initial climb and climb. More lift or higher engine power with flaps (1+F) and without. At initial climb after lift off, I normaly
 climg with around 18-20° pitch up to hold according speed. This one was around 25° pitch up or more with this test. GW was 63.3t.  Also with flaps retracted, open climb and keeping 250kts, the v/s seems much higher than normal.
 highclb

It also took less time to reach CRZ alt (just a feeling) as the overall climbrate (open clb) was higher.

**Comment by donstim** [comment]
> Without filling out a full test report I checked this flaps PR (MSFS: 1.14.5.0) and recognized a much higher lift on takeoff/initial climb and climb. More lift or higher engine power with flaps (1+F) and without. At initial climb after lift off, I normaly
> climb with around 18-20° pitch up to hold according speed. This one was around 25° pitch up or more with this test. GW was 63.3t. Also with flaps retracted, open climb and keeping 250kts, the v/s seems much higher than normal.

> 
> It also took less time to reach CRZ alt (FL370) as the overall climbrate (open clb) was higher.

Thanks for the review!
For the takeoff pitch, if anything CONF 1+F lift was reduced a little bit. That may lead to a little higher pitch angle to maintain the same speed. I have before and after videos though, that show pretty much the same after takeoff pitch characteristics. 
Before:  https://1drv.ms/v/s!Ajsy7Ey4_8uFzh7u9N5D90G2R6Od?e=24OGVo
After: https://1drv.ms/u/s!Ajsy7Ey4_8uFzh-EGTy289HO9L09?e=R6wdGR
There is plenty of thrust, so you do need to get that pitch up to the 18-20 degrees promptly or you will accelerate quickly, leading to a higher pitch attitude to not accelerate too much. The engine side isn't changed by this PR, and I haven't heard of any engine changes in the MSFS update.

For the flaps retracted climb, there are no changes to the flaps up portion of the flight model or to the engine model and don't know of any changes in the MSFS update in this regard. Just to confirm, I performed a climb to FL390 to check against FCOM (or is it QRH?) data and previous test results against this data and did not see any difference in either time or distance to climb.

**Comment by donstim** [comment]
> **I compared this table:**
> image
> 
> **With my values (red marked are big difference, amber slightly difference):**
> image
> 
> Issues (If Any):
> 
> * Something is wrong with Flaps 1+F S speeds. They are the same as Flaps 1 speeds. The reference table shows different values though (15kt difference).
> * Flaps 3 gear down level flight has slightly different pitch and speed values.
> * Flaps 2 level flight has lower F speeds than in the reference table (I flew the reference speed to compare pitch, my F speed is in brackets)
> 
> Overall Rating: Needs improvements.
> 
> Conclusions of the testing: Please check S and F speeds and marked pitch values

Regarding S and F speeds - there is only one set of S speeds for the NEO, based on the flaps up reference stall speed. There are not separate S speeds for CONF 1 and 1+F. Similarly, there is only one set of F speeds for the NEO as well, based on CONF 1+F stall speeds.
Screenshot (701)

The unreliable airspeed chart gives the pitch angle for specific speeds and weights. I don't know why those speeds don't always align with the F and S speeds. Note they don't label those speeds as S or F speeds.  That's a question best asked of Airbus. My speculation (which isn't worth much) is that the unreliable airspeeds table is based on historical practices when S and F speeds may have been different.

**Comment by donstim** [comment]
Hey, just to let you know, I don't think the high after takeoff pitch attitude issue is a lift issue. I think it is a thrust-drag issue with too much acceleration leading to too high a rapid a nose up pitch attitude needed to keep the speed from increasing too much. I'm not going to mess with the engine file at this point, but I am adding drag to keep the acceleration after takeoff more reasonable.

Thanks again for the review and the comment.

**Comment by Watsi01** [comment]
@donstim Thanks for your replies. I also hadn't this specific PR in mind. I thought Asobo may have changed something else. E.g. the new custom settings in the aircraft menu. If they are in default, does that mean the aircraft behaves the same as before the sim update 3? I'm not sure. And yes, something with engine power **or drag** must have happened. I was on accel height 'in a second', after liftoff. I think I experienced higher climbrates in general, also in higher altitudes. But this can be my imagination.... :-)

**Comment by donstim** [comment]
Unfortunately, what I thought I was going to do ain't going to work. The bug in SU3 has shown itself. It seems that that flaps and slats for position 1 are no longer separated. Any lift or drag scalar I put in for the flap position one is also used for slats position one, even if flaps are up. So, if I increase the drag for 1+F, it also increases the drag on just 1. I'd like the approach flap to be pretty realistic, so I'm limited with what I can do for takeoff. I'll try to find a happy balance somewhere until Asobo fixes this.

Other than this bug, I believe the airplane should behave the same as before.

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 13/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3878
Tier of testing: 3
Changes to observe:Flaps and Engine flight model improvements

Testing technique: Full flight Gatwick to Zurich then to Heathrow
Steps you've made to test the Pull Request:
1. Spawned Cold and Dark and Gatwick, filed for flight to Zurich on VATSIM
2. Departed with route 1 as below, monitored V2+10 as best as possible, sustained it with 20degrees nose up at 65T 30% CoG, flaps retracted with no issue and it flew the climb very nicely. Smooth speed transition too. CONF1+F for TO
3. Thrust in cruise was around 48-50% which was great and 4 degrees.
4. Descent, no issues. Flaps 1 deployed flawlessly, drag issue removed entirely and it flew very nicely. Pitch was good (can't remember the value but it wasn't anything for me to say "hmm that's odd")
5. Flaps 2, Flaps 3 and F-Full all fine, and no issues on flare/rollout

6. Respawned at Zurich Cold and Dark, filed for flight to Heathrow on VATSIM
7. Departed 1+F and held 147kts V2+10 manually on climb, had about 20 degrees and pulled up harder this time to catch the speed better compared to takeoff on Sector 1, but significant gusting crosswinds etc too so no concerns there, flap retraction and speed affects all good
8. Cruise, thrust around 48-50% and 3 degrees nose up at 67T
9. Descent absolutely fine, F1, speed control no concerns and lift/drag seemed great, was also using speedbrake to descend at this point on VATSIM with speed restrictions
10. Flaps 2 input, more drag noticed as expected, good aircraft attitudes throughout with different speed restrictions by ATC including 180kts, 160kts etc
11. Flaps 3 input and Full Flaps all absolutely fine. Bigger pitch change with Flaps 4 for approach this time but speed held at 160kts prior and was still coming down, aircraft pitched down to hold the glideslope nicely
12. Landed. Again, no issues on flare/rollout.

Flight notes (When done a full flight):
Flight 1 - Gatwick to Zurich
BOGNA1X BOGNA BENBO UL612 RESMI UN491 MELKO UM606 BLM BLM2Z

Flight 2 - Zurich to Heathrow
VEBI3N VEBIT T51 LASUN UT10 RLP UL613 DIDOR UT10 ALESO ALES1H

Media: Streamed the entire flight - both sectors on the link below. No issues found so no relevant times to point out.
https://youtu.be/kXly29FjbRM

Issues (If Any): None
Personally I found no issues within the limits of the PR work (understanding Conf 1+F and it still climbs steeper than expected but addressed further above by donstim so no concern from me)

Overall Rating: Good
Conclusions of the testing: No issues found on either sector - flaps and engine performance were very very good indeed. Thanks for all your ongoing hard work!

**Comment by donstim** [comment]
Thanks for the extensive testing. Nice job on the flights! Looks like the takeoff climb is still a bit too quick on the acceleration. Will wait to see others' tests (hopefully someone could run a check at a high elevation airport) before possibly tweaking a bit more.

**Comment by mreza1st** [comment]
Is the change implemented on the dev. version now? I just did a flight at a high elevation airport and was having a hard time gaining speed after take off at a pitch of about 10 degrees (stayed around 140-150 knots). The flaps also have issues. My thought is it's still not implemented in the dev version.

**Comment by Saschl** [comment]
As long as you see 
image
it's still in progress/being tested

**Comment by DFWSupertrooper** [comment]
> Thanks for the extensive testing. Nice job on the flights! Looks like the takeoff climb is still a bit too quick on the acceleration. Will wait to see others' tests (hopefully someone could run a check at a high elevation airport) before possibly tweaking a bit more.

If I had time tonight, I'd grab it and depart KDEN, but I'm tied up.  If it's still not done in the morning, I don't mind jumping in and giving this a go.

**Comment by donstim** [comment]
After seeing these 2 videos showing the airplane accelerating to V2+20, I am now more comfortable with the airplane's takeoff acceleration performance with this PR.  Although the autopilot will control to V2+10 (or up to V2+15 if it is engaged at a speed higher than V2), it appears like it may be typical to go beyond that in manual flight.
https://youtu.be/s4E53KZnDAI?t=114
https://youtu.be/cv41hm4JEB8?t=207
Would appreciate any comments from our pilots.

**Comment by BritishAvgeek** [comment]
Naturally I'm not a pilot but from watching those videos, and basing that against the behaviour from my stream yesterday I'd say you've done an exceptional job - appears to be very very close indeed! For ref further to my test yesterday at V2+20 I was getting the same pitch as the videos had above

**Comment by DFWSupertrooper** [comment]
For what it's worth, I tested this departing KDCA to KORD this morning (couldn't resist a sunrise flight out of DC with Drzeweicki's stunning KDCA & landmarks :)) and the takeoff was slightly different than before but still felt natural.  The start of the roll seemed more sluggish than before but plenty of speed to hit V1 on RWY33 (and that could be because my throttle setup didn't translate from FBW Custom).  Flaps operated as expected and had the expected effect.  Hard to say if this is more or less realistic because I'm not an IRL pilot, but it _felt_ good and was definitely flyable.  Would love to fly this with the correct throttle configuration and departing KDEN (high altitude) back to KDCA.  I think it'll be perfect!

**Comment by Watsi01** [comment]
Tested it again with latest changes. Much better now, regarding takeoff, initial climb and climb. Same GW as above. Havn't had the behaviour described above. LGTM! I'm still on crz though. Will see how the approach is working out.

**Comment by donstim** [comment]
> For what it's worth, I tested this departing KDCA to KORD this morning (couldn't resist a sunrise flight out of DC with Drzeweicki's stunning KDCA & landmarks :)) and the takeoff was slightly different than before but still felt natural. The start of the roll seemed more sluggish than before but plenty of speed to hit V1 on RWY33 (and that could be because my throttle setup didn't translate from FBW Custom). Flaps operated as expected and had the expected effect. Hard to say if this is more or less realistic because I'm not an IRL pilot, but it _felt_ good and was definitely flyable. Would love to fly this with the correct throttle configuration and departing KDEN (high altitude) back to KDCA. I think it'll be perfect!

Takeoff thrust was reduced.

**Comment by mreza1st** [comment]
Hi all thanks for all the hard work. Anything is better than what the current public dev version is. I know you are still testing this, but can you release this updated model to the dev version so we can try it too and be able to do an actual flight? Based on what I am reading it should be significantly better than the current flight model.

**Comment by tshomas** [comment]
Category: Unofficial QA - RL A320 Pilot
Name: Shomas#2719
Date of testing: 14/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3878

Completed a full unreliable speed using company A320NEO QRH for LEAP NEO manufactured May 2020.

All flap settings tested as per QRH manual, at aircraft weight roughly 58000kg and 33% ZFWCG.

Data matched real life QRH in all settings except Flap 1, but that is to be expected with PR testing notes. Close to 5kts difference, negligible anyway.

Aircraft is perfectly flyable, suggest merging ASAP to allow stable to be remade, any other tweaks can be found in time.

**Comment by MisterChocker** [comment]
I performed a flight, TO-CLB-CRZ-STEPCLIMB-CRZ-DES-APPR-LANDING

CRZ FL340, then step to FL360.

During Climb, nothing abnormal happed.

My estimated descent distance was 113nm. From FL360 CDA, 250kt all the way through (nothing fancy). (GW 59.5t)
I ended 9nm "high". (flew a pattern to loose the additional height)
(I haven't tested flaps 1 drag)
As I was on the 3° G/S, I noticed too much drag on flaps config 2 (gear up).
The deceleration rate was really high (too high imo).

Other than that LGTM.

**Comment by danbw9** [comment]
Observed before the PR in development version as a result of changes made by SU3: flap 1 drag was similar if not the same as flap full drag so on initial climb, a strange and rapid deceleration occurs. 

I have been using the PR fix whilst flying, multiple times with different configs for take off. Multiple landings and approaches both stabilized and decelerated approaches to test; comparing how the flap and lift affects the aircraft, whilst flying level and also in a descent, all monitored closely together with engine N1. Standard 3° and also 3.8° approaches attempted. Results as expected, particularly when comparing the flap 2/speed management between the two. 

Only small detail. I'm a PW neo driver so I am not familiar with what N1 values to expect  eg. thrust compensating for the drag) but we concluded that N1 in the 40s is suitable for on final, flap full, on speed & on profile. This is the reference:
https://www.youtube.com/watch?v=FODhSJucbK0&t=107s

We can revisit this if more data becomes available from IRL feedback from LEAP neo operators.

Awesome work @donstim. Green to merge from my side.

**Comment by donstim** [comment]
> I performed a flight, TO-CLB-CRZ-STEPCLIMB-CRZ-DES-APPR-LANDING
> 
> CRZ FL340, then step to FL360.
> 
> During Climb, nothing abnormal happed.
> 
> My estimated descent distance was 113nm. From FL360 CDA, 250kt all the way through (nothing fancy). (GW 59.5t)
> I ended 9nm "high". (flew a pattern to loose the additional height)
> (I haven't tested flaps 1 drag)
> As I was on the 3° G/S, I noticed too much drag on flaps config 2 (gear up) (deceleration rates where really high) (idle thrust).
> The deceleration rate was really high (too high imo).
> 
> N1% during approach and in landing config looked good. (mid 40)
> 
> Other than that LGTM.

Thanks for the detailed comments. No change to flaps up lift/drag or idle thrust in the PR, so there should not be any difference in decent performance from the previous flight model. If there was, I wonder if there could be an effect on flaps up performance from SU3 that we didn't know about?

A bit of additional drag was given to CONF 2 based on pilot comments on the previous flight model In Discord. It will decelerate faster at higher speeds, but the rate should really come down before getting to F speed. Would like concentrate on this a bit more in the new flight model, so would like to know if the pilots also think the decel rate is too high.

**Comment by donstim** [comment]
> Observed before the PR in development version as a result of changes made by SU3: flap 1 drag was similar if not the same as flap full drag so on initial climb, a strange and rapid deceleration occurs.
> 
> I have been using the PR fix whilst flying, multiple times with different configs for take off. Multiple landings and approaches both stabilized and decelerated approaches to test; comparing how the flap and lift affects the aircraft, whilst flying level and also in a descent, all monitored closely together with engine N1. Standard 3° and also 3.8° approaches attempted. Results as expected, particularly when comparing the flap 2/speed management between the two.
> 
> Only small detail. I'm a PW neo driver so I am not familiar with what N1 values to expect eg. thrust compensating for the drag) but we concluded that N1 in the 40s is suitable for on final, flap full, on speed & on profile. This is the reference:
> https://www.youtube.com/watch?v=FODhSJucbK0&t=107s
> 
> We can revisit this if more data becomes available from IRL feedback from LEAP neo operators.
> 
> Awesome work @donstim. Green to merge from my side.

Thanks for the report! Under SU3 right now, CONF 1 and 1+F can't be differentiated, so lift and drag are the same for both. Hopefully can find maybe a better balance with the new flight/engine model to come.

Considering @MisterChocker 's report above, what are your thoughts on the CONF2 drag?

I actually had the full flap N1 on final at Vapp in the mid-40s, but found in the dev version that it made it tougher to land without floating. Settled on just trying to keep it under 50 at mid-wts (see my results in the PR instructions above). We'll correct this in the new flight/engine model.

**Comment by MisterChocker** [comment]
@donstim regarding the deceleration, well I haven't really measured the deceleration speed but I lost almost 1 knot a second (based on the speed trend arrow). The deceleration rate I experienced definitely is even faster than a ceo without winglets.
I sadly haven't recorded the flight (for analysis as I did as I made the first changes to the FM back in the day).
To put the deceleration I experienced into comparison (I flew with the clear weather preset) it felt like a conf 2 gear down + speed brake deceleration.
To explain the situation: I had selected speed set to vfen - 5 which in this case is 180 knots. F Speed is a bit less than 144 (GW ~59t). This is a gap of 36 knots. As I approached F - Speed (Still in cof 2, considering the distance to the field) the auto thrust went 5 or more knots below the speed target before managing to fly flap speed. (I am not saying this hasn't happened before, sometimes the AT is just a bit slow).
We know from IRL 320 pilots that the aircraft can be slippery on approach, especially the neo.
To give an example, it did not felt like flying an airplane, it felt like flying a brick.
I'll do more tests to get a better understand of whats happening. (I kinda was in a hurry as I did the test)

**Comment by donstim** [comment]
@MisterChocker Thanks, yes, I think CONF 2 has a bit too much drag. CONF 1 is both 1 and 1+F, so it is a bit trickier.  Here is what I was also using: 
`Once you have flap 2 out, pretty much any ILS is stable, we have some 3.5 degree slopes we do too. Tailwind of >20kts you may need a little more drag and you'll need to get the gear out to slow down to 160kts for the final approach fix ICAO speed limit as you'll stabilise around 180kts normally.

On descent any VS less than 800'/min should allow you to reduce speed, clean..`

and

`Flaps up gear up (clean) you can normally decelerate, sometimes at 1000'/min depending on your load. On the ILS ~>800'/min will tend to maintain speed
[7:00 PM]
at CONF 2, gear up`

**Comment by MisterChocker** [comment]
Yes thats what I was recalling and wasn't able to reproduce at all, on config 2 gear up I had 1200'/min and lost speed at what I call high rate (significant speed trend in stable air and wind)

**Comment by donstim** [comment]
At what speed?  If I remember right, it would stabilize by around 160 knots.

**Comment by MisterChocker** [comment]
~1200fpm is about 185 knots.

**Comment by donstim** [comment]
Ok. These are good comments. Can either update this flight model or save it for the new one.

**Comment by MisterChocker** [comment]
I'd like to see a small fix for the current one (only if not too time consuming) I am not talking major changes, just the small drag correction we were talking about.

**Comment by mreza1st** [comment]
I did four legs of flights after this update (OIII-OIAW-OIII-OITR-OIII). Overall the flight model has improved a lot from earlier today with the recent update. It's pretty much working now. My observations are as follows:
N1 rating for TOGA and CLMB are petty much the same (so when you pull back for climb, there really isn't any pulling back on N1). This wasn't the case before.
The plane drops a little right after taking off (after V2) so it can even slightly touch the ground. This wasn't an issue for me before.
AP engagement results in a very erratic quick turns to get to the flight plan. Almost afraid to engage it if the FD is not very close to the actual path. This wasn't an issue before.
During the approach, Flaps 1 and 2 work perfectly. However, Flap 3 pushes the nose up (w/ AP on) and Flap 4 corrects the issue and pushed the nose down (since AP is active). Check Flap 3.
None related issues:
AP did not follow the flight path at least in one occasion and near the approach. It drew a different path for approach or deleted the path on its own! This was somewhat an issue in the past but seems to be more pronounced now?
Stutters are significant and they seem to be related to FMC. I know you guts are working on this.
Hope this helps.

Thanks,

**Comment by BritishAvgeek** [comment]
> I did four legs of flights after this update (OIII-OIAW-OIII-OITR-OIII). Overall the flight model has improved a lot from earlier today with the recent update. It's pretty much working now. My observations are as follows:
> N1 rating for TOGA and CLMB are petty much the same (so when you pull back for climb, there really isn't any pulling back on N1). This wasn't the case before.
> The plane drops a little right after taking off (after V2) so it can even slightly touch the ground. This wasn't an issue for me before.
> AP engagement results in a very erratic quick turns to get to the flight plan. Almost afraid to engage it if the FD is not very close to the actual path. This wasn't an issue before.
> During the approach, Flaps 1 and 2 work perfectly. However, Flap 3 pushes the nose up (w/ AP on) and Flap 4 corrects the issue and pushed the nose down (since AP is active). Check Flap 3.
> None related issues:
> AP did not follow the flight path at least in one occasion and near the approach. It drew a different path for approach or deleted the path on its own! This was somewhat an issue in the past but seems to be more pronounced now?
> Stutters are significant and they seem to be related to FMC. I know you guts are working on this.
> Hope this helps.
> 
> Thanks,

Most of those issues are not related to this PR - flight path and approach plans is a wider issue to be dealt with elsewhere. The similarities with FLX and TOGA are also a known issue not dealt with in this PR.

**Comment by donstim** [comment]
Thanks for the testing and comments.

> N1 rating for TOGA and CLMB are petty much the same (so when you pull back for climb, there really isn't any pulling back on N1). This wasn't the case before.
Yes, not sure what is going on there. When I flew it, the N1 for CLB was higher than the rating value. Not sure if this was true before (but assume it was). Just like for TOGA, the CLB N1 it uses is too high. The coming new engine model will fix this.

> The plane drops a little right after taking off (after V2) so it can even slightly touch the ground. This wasn't an issue for me before.
While there is a bit of a "pause" in the climb rate after leaving ground effect, I've never had a loss of altitude. 

> AP engagement results in a very erratic quick turns to get to the flight plan. Almost afraid to engage it if the FD is not very close to the actual path. This wasn't an issue before.
This PR should not affect any lateral AP behavior.

> During the approach, Flaps 1 and 2 work perfectly. However, Flap 3 pushes the nose up (w/ AP on) and Flap 4 corrects the issue and pushed the nose down (since AP is active). Check Flap 3.
I haven't been able to reproduce this. Are you on managed speed descending on the glideslope, or in some other condition?
> None related issues:
> AP did not follow the flight path at least in one occasion and near the approach. It drew a different path for approach or deleted the path on its own! This was somewhat an issue in the past but seems to be more pronounced now?
Not related to this PR.
> Stutters are significant and they seem to be related to FMC. I know you guts are working on this.
> Hope this helps.
Thanks for your input.
> 
> Thanks,

**Pull request merged**
