### PR TITLE
[CDU][PFD] FIX managed speed calculation for F-Speed and VLS

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

Fixes wrong managed speed for F-Speed on approach (PFD)
Fixes wrong VLS calculation when FLAPS 3 selected (CDU)

## Screenshots (if necessary)

Before:
[PFD]
image

[CDU]
image

After:
image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by danbw9** [comment]
@MisterChocker Thanks for this. This seems to fix flap 3. 

Am I right in saying that you are not able to change the fact that flap 2 F speed going below VLS? (especially an issue in managed speed mode). Due to the flight model not being able to be properly changed in respect to VLS, Alpha prot, speed tape etc. 

The F speed is correct, its just the speed tape/VLS shooting up too high. This was mentioned in the your previous PR which got merged.

Have attached a screenshot

Screenshot (398)

**Comment by MisterChocker** [comment]
@danbw9 we are already working on this, I pretty much believe will be able to merge before v0.5.

**Comment by danbw9** [comment]
@MisterChocker Thanks a lot. Sounds good.

**Comment by MisterChocker** [comment]
Also green for merge.

**Comment by danbw9** [comment]
I think we need some more tests on this one for it to be merged. For others who do not know how to test this:

just check the managed speed (magenta speed bug) is same speed as F speed in flap 3. And check that the VLS speed in the PERF APP page is the same as VLS on the PFD when in flap 3. (VLS being the top of the light orange line).

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 27/10/2020
Version of the sim: 1950
PR Tested: #1522
Object of test: Testing F speed and VLS speed for flap 3

Testing technique: Try-out
Steps you've made to test the Pull Request:

1. Loaded C&D  
2. Did an ILS circuit 
3. Monitored  flap 3 F speed and VLS speed for inconsistencies.

Flight notes: N/A

Overall Rating: Good
Conclusions of the testing: LGTM, but might need some more eyes on it! Flap 3 behavior seems correct (as mentioned above still problems with flap 2). Thank you for your work!

**Comment by Carter633** [comment]
Name: British Avgeek YT --- Carter633#1436
Date of testing: 27/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1522
Object of test: Testing Managed F and VLS speed calc fix

Testing technique: Circuit at EGGD
Steps you've made to test the Pull Request:

1. Spawned C&D
2. Did a circuit at EGGD using ILS approach 
3. Checked F speed on PFD
4. Checked Flap 3 VL speed

Flight notes: Nothing of note, worked as expected and as described with the exception below which is already understood.

Overall Rating: Good
Conclusions of the testing: LGTM, though of note the Flap 2 issue exists still which hopefully can be dealt with in due course

**Comment by MisterChocker** [comment]
Thanks for testing!
I am not sure which issue you guys are talking about. This PR fixes the bug where when FLAPS3 selected wrong F-Speed (on PFD) as well as APP and VLS were shown in MCDU.

VLS, Vaprot and Vamax are resolved in the flight model redo which will come in another pr/draft until we have fixed a couple of issues to start testing on that baby as well.

**Comment by Carter633** [comment]
F speed and VL for Flap 3 were fine

I think we were just noting the same issue that danbw9 mentioned re: flap 2 but I get that'll be for another PR

**Comment by MisterChocker** [comment]
> I think we were just noting the same issue that danbw9 mentioned re: flap 2 but I get that'll be for another PR

No problem, it's just that I already wrote that earlier in this pr and it comes bouncing back.

**Comment by donstim** [comment]
VLS in the PFD speed tape is determined independently from the MCDU and comes from reference speed values in the flight model cfg file with margins applied. However, the wrong margin is applied for flaps up, and the flaps between up and full must be interpolated because only the up and full flap stall speeds at max weight appear as the reference speeds in the flight model cfg file. Adjusting the flight model can get closer, but to really fix the PFD speed tape display, it would be better to have code that would inject the correct VLS speed into the PFD code to replace what it currently uses. This could be from a table of weight vs VLS for each flap setting and would need to be done on some kind of step time basis.

**Comment by St54Kevin** [comment]
I cant determine how you did it in your screeshots but IRL the magenta speed bug goes all the way down to VAPP. The A/THR just stays at the appropriate S or F speed.

**Comment by MisterChocker** [comment]
> I cant determine how you did it in your screeshots but IRL the magenta speed bug goes all the way down to VAPP. The A/THR just stays at the appropriate S or F speed. Until you select next flap setting

Yes thats reallife, the sim does not and I just fixed the calculation for that speed.

**Comment by MisterChocker** [comment]
> I cant determine how you did it in your screeshots but IRL the magenta speed bug goes all the way down to VAPP. The A/THR just stays at the appropriate S or F speed. Until you select next flap setting

will work in that now.

**Comment by MisterChocker** [comment]
nmv I will do the work on a proper managed speed behavior for approach phase in a different pr.

**Pull request merged**
