### PR TITLE
feat: custom RMP font

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Added custom RMP font

## Screenshots (if necessary)

Before:
image
After:
image
image

## References

image

## Testing instructions

Make sure the new font is accurate.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by marinerhally** [comment]
Category: QA Trial
Name: Mariner Hally#0715
Date of testing: 15/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3535
Tier of testing: 1
Changes to observe: 
Added custom RMP font

Testing technique: Check
Steps you've made to test the Pull Request:
1. Spawned in C/D at EGGP
2. Checked Radio panels for new front (New font and custom panel).
3. Checked all button operable.
4. Spawned on RWY09 at EGGP.
5. Checked Radio panels and buttons.

Flight notes (When done a full flight): None

Media: 
Screenshot 2021-02-15 003630
Screenshot 2021-02-15 003742


Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: No problems at all that I could find.

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 15.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3535
Tier of testing: 1
Changes to observe: New RMP fonts and alignments
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power
3.) RMP at day (Image1)
4.) RMP at night (Image2)
5.) ANN LT Test (Image3)
6.) Compare to reference

Media:


Image1


Image2


Image2

Issues: 
- digit position is a little to low (not in center)

Issues (not part of this PR): 
- There is no backlight on the displays (like from the Rud Trim display)
- Not all button LEDs lit up on ANN LT Test

Overall Rating: To be improoved.

Conclusions of the testing: Nice, but one thing that is related to the font/digits.

Hope this helps :-)

**Comment by tyler58546** [comment]
> digit position is a little to low (not in center)

Fixed

image

**Comment by marcman86** [comment]
Looks good to me.

Nice job!

**Review by theomessin — APPROVED** [review]
LGTM

**Pull request merged**
