### PR TITLE
fix: Trim limits are now no longer able to be exceeded by using the right trim wheel

### LINKED ISSUE #4342: Able to move trim wheels beyond their stopping point.
**Mod Version**
Latest experimental, development, and most builds of v0.5.X

**Describe the bug**

You can move the left trim wheel all the way to its maximum and then keep on moving the right trim wheel.

**To Reproduce**

1. Put the trim on the left trim wheel to the highest downwards trim.
2. Try and trim the right trim wheel even further down.
3. Profit

**Expected behavior**

After going to the max trim, you shouldn't be able to move either of the trim wheels past the limit.

**Actual behavior**

You can keep on spinning the right-hand trim wheel. 

**References**

https://user-images.githubusercontent.com/30361843/113952059-82ea7400-97da-11eb-868d-cb8fb57bb4c1.mp4

**Additional context**

Was this working before/when did the issue start occurring?
Started happening a while ago, perhaps before the release of version 0.5.0, I just now decided to open a bug report.
Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub): Erick [Z-6]#6484

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes #4342

## Summary of Changes

* See title

## Additional context

Discord username (if different from GitHub):

## Testing instructions

* Make sure the trim wheel works as expected
* Try to turn the wheel past it limits (in both ways)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 13/04/2021
Version of the sim: 1.15.7.0
PR Tested: #4427 
Tier of testing: 1
Changes to observe: Trim wheel range

**Steps you've made to test the Pull Request:**
1. Loaded up onto a RW
2. Trimmed with Joystick buttons all the way to each end
3. Trimmed with mouse on each wheel to each end

**Media:**

**Issues (If Any):** 
- The lower end (DN) is not fixed when using trim keybinding. The trim scale does not move but the wheel does move further than 4 DN

**Conclusions of the testing:** See above. Only thing I found. Mouse trim usage is fixed.

**Comment by lukecologne** [comment]
This PR is not intended to adress any trim issues when using keybinds, only dragging with the mouse. Also, I'm not sure if this can be fixed, and if it can, I don't know how.

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 16/04/2021
Version of the sim: 1.15.7.0
PR Tested: #4427 
Tier of testing: 1
Changes to observe: Trim wheel range with mouse

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. Spawned in C&D
2. Tested the trim wheel both with mouse and keybinds


Media: https://user-images.githubusercontent.com/64845965/115028099-c9b82800-9ec4-11eb-8499-41da07fe0a87.mp4
When mouse is not moving, I'm using keybinds


Issues (If Any): None PR related

Overall Rating: Good
Conclusions of the testing: Trim limits with mouse have been fixed, as lukecologne said keybind limit problem is not supposed to be fixed in this PR

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 16.04.2021
Version of the sim: 1.15.7.0
PR Tested: #4427
Tier of testing: 1
Changes to observe: Trim wheel limitations

Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Try out trim wheel

Issues: -

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Comment by Philadelphia5105** [comment]
Category: QA Trial
Name: Philadelphia#5105
Date of testing: 04/16/2021
Version of the sim: 1.15.7.0
PR Tested: #4427
Tier of testing: 1
Changes to observe:
Trim wheel limits
Testing technique: 
1. Load Cold and Dark at gate 141 at KPHL
2. Turn on batteries and external power
3.  Move the trim wheel as far as I could with the mouse

Issues (If Any): Write any issues
N/A

Overall Rating: Good
Conclusions of the testing: 
Works as intended.

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek #1436
Date of testing: 16/04/2021
Version of the sim: 1.15.7.0
PR Tested: #4427
Tier of testing: 1
Changes to observe: Trim Limits

Testing technique: Spawn C&D 

1. Spawned Cold and Dark
2.  Checked rudder trim limits

Issues (If Any): N/A

Overall Rating: Good
Conclusions of the testing: Works as expected, no issues found

**Pull request merged**
