### PR TITLE
feat(efb): add button for forward pushback

### LINKED ISSUE #4801: Forward pushback button EFB
### Aircraft Version

Experimental

### Description

The EFB has three directional buttons for controlling the direction of pushback: straight backwards, left and right. However, there is no option for a forward direction, which the [PushbackHelper](https://github.com/metindikbas/msfs-pushback-helper-app) tool does have. It can be handy if you for example overshoot the taxiway centerline and want to correct the alignment of the aircraft easily.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Erik Vroon#0182

### PR DESCRIPTION
**Pull request by evroon**
Fixes #4801

## Summary of Changes
Adds a button to the Ground page of the EFB to pushback forwards.

Note: Setting the tug speed does not work yet, so this cannot be merged yet.

## Screenshots (if necessary)

Screenshot 2021-05-15 153410

## Additional context

Discord username: Erik Vroon#0182

## Testing instructions

Just click on the forward pushback button on the EFB.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by evroon** [comment]
I'm afraid this is not (yet) possible using the current MSFS SDK. The `KEY_TUG_SPEED` does not seem to control anything. In the [PushbackHelper](https://github.com/metindikbas/msfs-pushback-helper-app) tool, this is solved by setting the z velocity of the aircraft itself. However, this gives quite erratic behavior and I don't think it would be a neat solution. So hopefully Microsoft will improve the pushback system.

**Comment by scoopscode** [comment]
@hiaaryan does the flyPad 2.0 have this same page? Or has it been completed changed. Just wanted clarification as this PR may need to have some changes for new EFB.

**Comment by hiaaryan** [comment]
> @hiaaryan does the flyPad 2.0 have this same page? Or has it been completed changed. Just wanted clarification as this PR may need to have some changes for new EFB.

It does, will merge the changes once done. Just have to adjust placement of the button.

**Comment by tracernz** [comment]
> @hiaaryan does the flyPad 2.0 have this same page? Or has it been completed changed. Just wanted clarification as this PR may need to have some changes for new EFB.

Seems like a moot point given:
> I'm afraid this is not (yet) possible using the current MSFS SDK.

**Comment by evroon** [comment]
As I don't know how to implement the forward feedback, I have closed the issue. If someone knows a possible solution, feel free to share it.

**Pull request closed without merging**
