### PR TITLE
feat(textures): fire panel corrections

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes
- Added a white dot to the fire test buttons
- Corrected the alignment of the DISCH decals

## Screenshots (if necessary)
BEFORE:
beforeoff
beforeon

AFTER:
afteroff
afteron

CLOSE-UP BEFORE/AFTER:
Untitled-1

## References
ref1

Discord username (if different from GitHub): Imenes#0001

## Testing instructions
Check the changes on the overhead fire panel, and check the rest of the cockpit textures for possible related conflicts. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by DarkOfNova — APPROVED** [review]
LGTM - Note: dots are also added to the cockpit door control panel however this cannot be changed atm and it is mostly correct anyway.

**Comment by tracernz** [comment]
Will conflict with https://github.com/flybywiresim/a32nx/pull/5100. Will have to redo whichever merges last.

**Comment by ImenesFBW** [comment]
> Will conflict with #5100. Will have to redo whichever merges last.

Indeed, I'll adjust mine after that one gets merged since Tylers was up first.

**Comment by marcman86** [comment]
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #5111
Tier of Testing: 1
Date: 14/06/2021

Testing Process: 
- Spawn C&D at EDDP
- Turn on bat. and ext. power
- ANN LT TEST (Fig1)
- Function test of buttons (so far possibe)

Negatives: -
Testing Results: Passed
Conclusions: Looks nice
Media:


Fig1

Hope this helps :-)

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5111 
Tier of Testing: 1
Date: 14/06/2021

**Testing Process:**
1. Checked Fire Panel DISCH label and Test button dot in different lighting conditions
2. Checked Cockpit textures for possible conflicts

Negatives: Are the Test button dots lit? I dont know :D

**Testing Results:** Passed

Media: 
image
image

**Comment by ImenesFBW** [comment]
> Negatives: Are the Test button dots lit? I dont know :D

Thanks for testing! On the references, I checked it does not. 

image

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #5111 
Tier of Testing: 1
Date: 14/6/21

Testing Process: 
Loaded in C&D and tried with all different lighting conditions and looked around the whole cockpit
Negatives: The dot on the test button is not centred 
Testing Results: Passed

Conclusions: The new dot is there and the DISCH looks good but the dot is a bit off centre
Media: 
You can see its not 100% centred, not sure if it possible to
image
image
image

**Comment by ImenesFBW** [comment]
> Negatives: The dot on the test button is not centred

I'll push it down a tiny smidge after #5100 gets merged, thanks for the help!

**Comment by ImenesFBW** [comment]
Dot moved closer to the center position. Should close #5117 but I would appreciate it if @FlightSimmer7700 takes another look at it when he has the time.

Also removed the "do-not-merge" tag since @tracernz has notified me the autoland PR is gonna take a bit more time.

image

**Comment by FlightSimmer7700** [comment]
> Dot moved closer to the center position. Should close #5117 but I would appreciate it if @FlightSimmer7700 takes another look at it when he has the time.
> 
> Also removed the "do-not-merge" tag since @tracernz has notified me the autoland PR is gonna take a bit more time.
> 
> image

Can confirm it now looks centred, good job!!

**Pull request merged**
