### PR TITLE
[ECAM REWRITE] Add doors page

### PR DESCRIPTION
**Pull request by RichardPilbery**
Fixes #[issue_no]

## Summary of Changes

Porting existing ECAM doors page over to React

## Testing instructions

* Verify that DOOR/OXY page functionality still works correctly and faithfully.

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — CHANGES_REQUESTED** [review]

**Comment by RichardPilbery** [comment]
@Benjozork Do you want any SimVars used adding to SIMVAR_TYPES?

**Comment by Benjozork** [comment]
> 
> 
> @Benjozork Do you want any SimVars used adding to SIMVAR_TYPES?

Not necessary.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
Might wanna change `useSimVar` to `getSimVar` in the permanent area though.

**Comment by BritishAvgeek** [comment]
This doesn't look build yet - got no "checks" on my end so no artifact to download

**Comment by sidnov** [comment]
> This doesn't look 'built' yet - got no "checks" on my end so no artifact to download

Same, 0 artifacts available to test

**Comment by valenzz2004** [comment]
^

**Comment by Benjozork** [comment]
Forgot to change the pipelines. Standby

**Comment by sidnov** [comment]
Is it just me or the artifact still doesn't show?

**Comment by Benjozork** [comment]
Maintainers please do not add RTT while I figure out the workflow issue

**Comment by iamdefective1** [comment]
Category: QA Tester
Name: IAMDEFECTIVE1#9293
Date of testing: 29/12/20
Version of the sim: 1.12.13.0
PR Tested: #2461
Object of test: ECAM Door Page

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. spawn egkk
2. power up
3. check page

Screenshots:
image
image
image
image

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: page is okay, and door combos show up

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date 29/12/20
Version of the sim: 1.12.13.0
PR Tested: #2461 
Object of test: ECAM door page

Testing technique: Spawned in and took a look
Steps you've made to test the Pull Request:
1. Spawned in
2. Opened the cargo door, front and back door

Screenshot 2020-12-29 220146

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: LGTM

**Pull request merged**
