### PR TITLE
fix(isis): updated ECAM font for ISIS

### LINKED ISSUE #7129: isis: arrow symbols missing from font
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-30T05:58:36+00:00",
  "ref": "HEAD",
  "sha": "b2d7668d7dcbef695cf7462635c9800234b5967c",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual",
  "pretty_release_name": "master:b2d7668d"
}
```

### Describe the bug

Since https://github.com/flybywiresim/a32nx/pull/6009 the arrow symbols used on the bugs page have been missing.

Before:
image
After:
image

### Expected behavior

Arrows to be visible.

### Steps to reproduce

1. Go to bugs page on ISIS.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by aweissoertel**
Fixes #7129

## Summary of Changes

Updated the ECAM font used by the ISIS to include left, right, up and down arrows

## Screenshots (if necessary)

screen2

## Additional context

Discord username (if different from GitHub): Alexibexi#7550

## Testing instructions

1. Spawn on runway
2. On the ISIS, click the little "BUGS" button at the top

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by sidnov — APPROVED** [review]
Should be a good temporary solution 👍🏻

**Comment by BlueberryKing** [comment]
Hi, thank you for your contribution! I have just quickly tried out your PR, but it seems I'm not getting better results with the arrows than before.

image

Is it possible I'm missing something in the build process? To confirm, you did not make any additional changes apart from the files you checked in?

**Comment by aweissoertel** [comment]
Hi, thanks for testing @BlueberryKing :)
That's really strange... I just verified again myself and it still works for me, as you can see:
image
I'm on the fix branch (isis-font-fix), don't have any changes in git and just did a fresh build

Am I missing something? It's very likely my fault as this is my first contribution to this project, but I can't spot the issue

**Comment by tracernz** [comment]
Please also check in the .sfd source file when making any font changes, or they will be lost the next time somebody edits the font.

**Comment by tracernz** [comment]
Rather than modifying the ECAM font, which currently contains only real EIS characters, perhaps it's a better idea to create a copy of it specifically for the ISIS and modify that.

**Comment by sidnov** [comment]
Seems like it does work indeed. Latest experimental 
image

**Comment by aweissoertel** [comment]
Thanks for the feedback everyone!
What I did now:
- reverted my changes on the ECAM font
- created a copy of it (ISISFontTemporary)
- included the arrows from the Honeywell font
- also added the .sfd file for the temporary font
- verified that it works

**Review by sidnov — APPROVED** [review]
LGTM

**Comment by tracernz** [comment]
> Thanks for the feedback everyone! What I did now:

Great work! Thanks!

**Comment by 2hwk** [comment]
Quality Assurance Report

Discord : 2Cas#1022
Object of testing: https://github.com/flybywiresim/a32nx/pull/7074
Tier of Testing : 1
Date : 16/07/2022

Testing Process:
  - [x] Spawn on runway
  - [x] On the ISIS, click the little "BUGS" button at the top

Negatives:
- N/A

Testing Results:
Passed

LGTM merging

**Comment by 2hwk** [comment]
Congratulations on your first accepted pull request to the A32NX project

**Pull request merged**
