### PR TITLE
fix: Flight model update to reduce flap drag

### PR DESCRIPTION
**Pull request by donstim**
## Summary of Changes

@MisterChocker noticed during testing of PR #3878  that there was excessive flap drag in all flap configurations during approach. Because that PR was an important fix for the MSFS SU3 update that caused major issues with CONF 1 and 1+F, it was decided to go ahead and merge that PR, but provide a further update to fix the flap drag levels. That is the purpose of this PR. It reduces flap drag by variable amounts depending on flap detent to provide more accurate deceleration characteristics on approach. Engine N1-thrust has been adjusted to provide accurate N1 levels for the new drag levels.

CONF 1 and 1+F continue to be challenging since MSFS SU3 does not differentiate between them. The drag level has been set to be appropriate for CONF 1 on approach, so it is lower than it should be for CONF 1+F on takeoff. This leads to overshooting the target takeoff climbout speed and results in high pitch angles to limit the overshoot. To alleviate this issue, the lift for CONF 1 and 1+F has been increased a bit and takeoff thrust and N1 has been reduced. This will lead to more instances where N1 will not be reduced when the thrust levers are pulled back from TOGA to CLB. (It was present before, but it will be more common now.)

As in the previous PR, there are no changes to flaps up lift or drag, or to any other flight characteristic.

## Screenshots (if necessary)

Here is the same comparison of target pitch angles and N1 values shown in PR #387, but updated for the flight/engine models in this PR:
Screenshot (697)
Screenshot (727)

## Additional context

Discord username (if different from GitHub):donbikes#4084

## Testing instructions

Takeoff and landing tests are needed at different flap settings, different weights, and different airport elevations to find and resolve any remaining issues. Particular attention should be paid to takeoff climbout characteristics, deceleration during approaches, and landing "float" behavior. (In general, any kind of aggressive landing flare will result in an extended float.)

In general, on a 3 degree glideslope at around 60T (or the default MSFS weight), the following deceleration characteristics should occur:

CONF 1 - start of descent = small speed gain for a bit, especially when first starting down the glideslope (can hold speed at lesser descent rates and decel at level flight or low descent rates)
CONF 2 = steady (but slow) speed loss until it stabilizes at around 180 KCAS or less
CONF2 + gear down = steady deceleration rate
CONF3 + gear down = very noticeable deceleration rate
Flaps Full = more prominent deceleration

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: 18/3/2021
Version of the sim: 1.14.5.0
PR Tested: #3979 
Tier of testing: 2
Changes to observe: 
Improved drag at different flap settings 
Improved N1 levels to adjust for the drag changes 


Testing technique: Did multiple takeoffs and landing at different weight, elevation and flap config. 
Steps you've made to test the Pull Request:
1. Tested normal 1+f takeoffs followed by flap 2 takeoffs  
2. Tested the A/C deceleration behavior with each flap setting   
3. Tested landing flare behavior at full config as well as flap 3 config 

Flight notes: N/A  

Media: N/A

Issues: N/A

Overall Rating: 
A really great addition, i was able to tell drag performance was much better right away with how the AC slows and sort of hangs in the air, no major floating issues were found while following the flare law however it's still possible to float with an aggressive or premature flare as mentioned in the description. Climbout performance was normal with the right N1% behavior mentioned. Overall there were no any abnormalities.    
Conclusions of the testing: Great work!

**Comment by donstim** [comment]
Thanks! Appreciate the test and report!

**Comment by starvingjavi** [comment]
Category: QA Tester
Name: Javi#2557
Date of testing: 18/3/2021
Version of the sim: 1.14.5.0
PR Tested: #3979
Tier of testing: 2
Changes to observe: Flaps and Flight Model

Testing technique: Performed flights between MMAA and MMMX with different configurations
Steps you've made to test the Pull Request:

1. Tested 2 and 1+f takeoffs
2. Compared pitch and N1 values to the table provided in PR

Media: N/A

Issues: N/A

Overall Rating: Good/LGTM
Drag was improved and it can finally catch up on speed in 1+F configuration.
No floating on runway upon landiing
Conclusions of the testing: Good job

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 22/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3979 
Tier of testing: 2
Changes to observe: Flap Drag in various situations

**Steps you've made to test the Pull Request:**
1. Loaded onto RW in ISA weather conditions
2. Takeoff with Flaps 1+F to 5000ft
3. Tested various Flap settings and weights at speeds specified in the FCOM reference table in level flight
4. Tested Flaps deceleration on glide - All look reasonable
5. Flaps 3 and FULL with differen weights to get pitch/power
6. results below
7. Tested Flaps 2 and Flaps 3 takeoff at 60T

**Media:**
image

**Issues (If Any):** 
- please have a look at the red marked values above wether they are relevant

**Conclusions of the testing:** Overall nice flaps drag on approach. There was nothing I found to be very inaccurate.

**Comment by donstim** [comment]
> **Conclusions of the testing:** Overall nice flaps drag on approach. There was nothing I found to be very inaccurate, xecept above mentioned values. But i think those are related to the Flap 1. 1+F problem

Thanks for the testing and report, Kevin!  You're right about the 1, 1+F issue. Two Asobo issues at play here:  1) Slats aren't modeled correctly, which messes up the pitch angle, especially for CONF 1 (slats only), and 2) CONF 1 and 1+F can no longer be differentiated. I chose to use lift closer to 1+F to help with takeoff and drag closer to 1 to give the right decel characteristics for approach. That's why the N1s are more accurate for 1, and the pitch a bit closer on 1+F (though still affected by the slat modeling issue).  Your results pretty much mirror mine, which are posted in the PR description above.

Flaps up is not affected by this PR.

**Pull request merged**
