### PR TITLE
Bug/2239 idle fuel flow

### PR DESCRIPTION
**Pull request by dcb99**
Fixes #[2239]

## Summary of Changes
Updated the `idle_fuel_flow` value in engines.cfg to 705

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by andrejetcat** [comment]
It would be nice, if you could change the "high_fuel_flow " and "max_fuel_Flow" a little bit, to increase crusie fuel flow a little, that it matches like between 1050kg/Hr and 1150kg/hr
without the change it is still under 1000kg @cruise with a typical load.

**Comment by MisterChocker** [comment]
> It would be nice, if you could change the "high_fuel_flow " and "max_fuel_Flow" a little bit, to increase crusie fuel flow a little, that it matches like between 1050kg/Hr and 1150kg/hr @cruise-level.
> without the change it is still under 1000kg @cruise with a typical load. Thats too low compared with the real A20N

This also changes the engine performance (N1%), I would not recommend that for now since it takes a ton of testing.

**Comment by pepperoni505** [comment]
Please rebase your fork (your fork is 2 months old) and open a new PR.

**Comment by dcb99** [comment]
> Please rebase your fork (your fork is 2 months old) and open a new PR.

I just forked this yesterday afternoon, how could it be 2 months behind?

**Comment by pepperoni505** [comment]
No idea, but I checked your fork and it is 2 months old.

**Comment by andrejetcat** [comment]
@MisterChocker thank you for your message. I what way does this value changes the performance? I change it by myself and I didn´t notice a difference in engine performance. I only see that the fuel flow is now more realistic and not too low.
thank you once again for this awesome project here! I there any plan to change the fuel flow in the future? idle flow is like the half compared to real life.

**Pull request closed without merging**
