### PR TITLE
feat: Button press sound for Remote MCDU clicks

### LINKED ISSUE #6632: Remote-MCDU button-sound on device
### Aircraft Version

Experimental

### Description

it would be awsome, if it would be possible to add a button sound on the remote-MCDU device. I don´t know if it is possible but awesome, if my tablet could give out a button sound by itself when clicking. 

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by frankkopp**
Closes #6632 

## Summary of Changes
Adds a button press sound to the Remote MCDU.
Sound can be turned on by adding "/sound" to the URL. 

## Screenshots (if necessary)
https://user-images.githubusercontent.com/16833201/153566539-32d1d0d2-6f85-4fb8-8cc1-e562c402d5c8.mp4

Discord username (if different from GitHub): Cdr_Maverick#6475

## Testing instructions
- Check that when Remote MCDU is loaded with http://localhost:8125/sound you can hear a button press sound with each click on a button.
- Check that there is no sound when not adding "/sound" to the URL. 
- Check that other parameters like "/fullscreen" still work
- General check if nothing else has been broken when using the Remote MCDU

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #6694 
Tier of Testing: 1
Date: 13/02/2022

**Testing Process:**
- Tested Remote MCDU sounds

**Negatives:** N/A
**Testing Results:**  Yep, works!
- There should be a hint for this options in the cmd window of the server.exe.

**Comment by tyler58546** [comment]
> Sound can be turned on by adding "/sound" to the URL.

Why not have it on by default? People can just mute their device or browser tab if they don't want it.

**Comment by frankkopp** [comment]
> > Sound can be turned on by adding "/sound" to the URL.
> 
> 
> 
> Why not have it on by default? People can just mute their device or browser tab if they don't want it.

Because for most people the sound from the cockpit should be sufficient and only the users who actually want to have sound on the remote can activate it. Yes, devices can be muted but I thought this is cleaner and allows for music or other sounds on the device.

**Comment by frankkopp** [comment]
> **Quality Assurance Tester**
> 
> 
> 
> Object of testing: #6694 
> 
> Tier of Testing: 1
> 
> Date: 13/02/2022
> 
> 
> 
> **Testing Process:**
> 
> - Tested Remote MCDU sounds
> 
> 
> 
> **Negatives:** N/A
> 
> **Testing Results:**  Yep, works!
> 
> - There should be a hint for this options in the cmd window of the server.exe.

Good idea.

**Comment by jcalor** [comment]
Quality Assurance Tester Report

Discord          : Calo#6816
Object of testing: #6694 
Tier of Testing  : 1
Date             : 16/02/2022

Testing Process: 

- Tested sounds - checked
- Tested fullscreen mode - checked
- Without `/sounds`, there are no sounds on Remote MCDU - checked
- Tested everything works properly (every MCDU key) - checked

Negatives: N/A

Testing Results: Passed

Conclusions: Works like a charm!

**Pull request merged**
