### PR TITLE
fix(fmgc): descent initiation and crz fl change

### LINKED ISSUE #4789: Cruise Level changes when new Alt is set on the AP panel
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-11T18:24:30+00:00",
  "ref": "master",
  "sha": "304755d87433eebe94b6936cca7ac41eee8dea69",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I get an altitude on Vatsim, say FL140, and even though the cruise level in the PROG and INIT page is FL380, a new cruise level gets validated (FL140) in the FMS. This happens with any altitude below the original cruise level. 

In the video in references, I put FL370 in the AP while my CL was FL380. 
Check -> "new crz alt" message.

**this happens both when using managed or selected ALT mode**

### Expected behavior

The original cruise level should not change in the system to the ALT I set on the AP panel, unless in case the new ALT is above the original CL.

### Steps to reproduce

Insert a cruise level for a random test flight or add a FP if preferred, and set any ALT below that cruise level when airborne.

I have yet to see whether this occurs during the descent phase, but I do not think so. Will update in case it does. 

### References (optional)

https://user-images.githubusercontent.com/84073735/117956284-31715f80-b319-11eb-9c7c-9142e7c112c1.mp4

### Additional info (optional)

_No response_

### Discord Username (optional)

Charley#9996

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #4789

## Summary of Changes

- Fixed descent initiation condition where it was impossible to enter descent phase (+200nm and below FL200)
- Fixed `NEW CRZ ALT - AAAAA` message appearing constantly
- Fixed descent initiation not able with FPA mode.

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Perform a flight as per usual and use the following functionalities:
- During climb increase the fcu target alt in steps, then set last fcu alt 2000ft higher as originally set/defined cruise altitude
_Setting the fcu alt 2000ft higher as crz alt will result in the message `NEW CRZ ALT - AAAAA`_
- After reaching your newly defined cruise altitude, perform a step climb
- Perform an early descent, descent initiation 200nm away from your destination

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by frankkopp** [comment]
Category: QA Tester
Name: Cdr_Maverick#6475
Date of testing: Current date 18.5.2021
Version of the sim: 1.15.10
PR Tested: #4826
Tier of testing: 2

Changes to observe:
During climb increase the fcu target alt in steps, then set last fcu alt 2000ft
higher as originally set/defined cruise altitude
Setting the fcu alt 2000ft
higher as crz alt will result in the message NEW CRZ ALT - AAAAA
After reaching your newly defined cruise altitude, perform a step climb
Perform an early descent, descent initiation 200nm away from your destination

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. C&D at gate with SOP until takeoff (simbrief)
2. TO - 5.000 - 12.000 - 16.000 - 20.000 - 24.000
3. Climb to 28.000
4. Descent 200+NM from destination in FPA mode


Flight notes (When done a full flight):
EDDB/25L F220 HLZ1N HLZ L980 TENLI L602 SPY DCT RAVLO Y70 OTBED ROSUN1F EGCC/23L

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any):
T.O. to 5.000: OK
Climb to 12.000 with managed climb: OK
Climb to 16.000 with OP CLB: NEW CRZ ALT - 16.000 displayed (although CRZ was 22.000) Phase change to CRZ
Climb to 20.000 and 24.000 - also NEW CRZ ALT displayed
Climb to 28.000 - also NEW CRZ ALT displayed
Descend at 490NM before destination with FPA 3.0: OK - phase changed to DES

Overall Rating: To be improved
Conclusions of the testing: "NEW CRZ ALT" message is displayed before climbing above the defined CRZ ALT
Descending 200+NM in FPA worked

**Comment by MisterChocker** [comment]
Addressed issue from @frankkopp

**Comment by FlyingCarpet7** [comment]
Tested this PR now. Step climbing up towards preset CRZ level did not trigger a NEW CRZ ALT so behaviour correct at least for me.
Started a descend outside 200 NM from dest. When selecting FL190 descend phase was activated correctly.

**Comment by frankkopp** [comment]
Re-tested it as described above:
- During step climb no more "NEW CRZ ALT" displayed apart from when exceeding defined CRZ ALT: OK
- Phase remains CLB until CRZ ALT is reached: OK
- Displays "NEW CRZ ALT" if at CRZ ALT a climb is done to a higher CRZ ALT: OK
- Descent at 490+NM from destination with FPA: OK

Overall Rating: Good - all issues from last test are fixed

Conclusions of the testing: LGTM

**Comment by MisterChocker** [comment]
@frankkopp @Samueleonard @FlyingCarpet7 
Thanks for testing and the feedback!

**Comment by FlyingCarpet7** [comment]
This PR is merged into Dev now, right? 
I just made a dev flight. FL380, 140 NM inbound destination I got a descend clearance to FL 260. Activated managed descend and received "New Crz Alt  FL260" message and remained in CRZ phase...

**Comment by MisterChocker** [comment]
> This PR is merged into Dev now, right?
> I just made a dev flight. FL380, 140 NM inbound destination I got a descend clearance to FL 260. Activated managed descend and received "New Crz Alt FL260" message and remained in CRZ phase...

I'll look into it, Thanks for testing

**Pull request merged**
