### PR TITLE
Changed AIRCOND knobs starting position to 12 o'clock

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

Changed AIRCOND knobs starting position to 12 o'clock for all starting positions. Pilots have been giving feedback about how they rarely touch the air conditioning knobs and usually find them in the 10-12 o'clock position in a cold&dark cockpit.
## Screenshots (if necessary)
Starting position BEFORE:
olknbpture

Starting position AFTER:
neKNpture

## References

Changes made with real-world operator feedback given.

Discord username (if different from GitHub):
Imenes#8739
## Testing instructions

This should be a quick "Tier 1" check. Just test if the air conditioning knobs are at the 12 o'clock position in all starting configurations and check the functionality.  

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by ImenesFBW** [comment]
This may inadvertently fix #1763 since the position is centered at the start, when the user moves it back and forth by the increment set they should be able to hit the centered position.  I didn't include "fixes #1763" since I wasn't sure if I should.

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 20.1.2021
Version of the sim: 1.12.13
PR Tested: #3118
Tier of testing: 1
Changes to observe: AIRCOND knobs starting position at 12 o'clock


Testing technique: tested?
Steps you've made to test the Pull Request:
1. started at ate and runway
2. observed the AIRCOND knobs

Issues (If Any):none

Overall Rating: Good
Conclusions of the testing: Works as expected! Thanks for the PR

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 20.01.2021
Version of the sim: 1.12.13.0
PR Tested: #3118 
Tier of testing: 1
Changes to observe: 
Default Aircon Switch Position

Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned C&D in LSZH, A44
2. Checked overhead panel
3. Spawned on RWY34
4. Checked Overhead again

Flight notes (When done a full flight): n/a

Media: n/a 

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Works as described, good to go

**Comment by aviationenthusiast** [comment]
Can you make it so that each time you start C&D, you find the knobs in random position between 10 and 12 o'clock for example? I think that should add to the realism, when all three are not the same exact value over and over, as if no human ever touches them.
And maybe a random 1 in 10 chance (or whatever you learn from pilots' feedback) that you find the knobs in a position outside the 10 - 12 range, as if a previous pilot dialed in an unusual value.

**Comment by MisterChocker** [comment]
@aviationenthusiast please open a request issue and don't comment below a closed/merged pr.

**Pull request merged**
