### PR TITLE
fix(mcdu): multiple small changes for re-initialization

### LINKED ISSUE #5112: ATC does not use the correct callsign after calling ground services when landed
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-14T09:02:20+00:00",
  "ref": "master",
  "sha": "4eaf1e43033d8ce8ae96027ab4449462121417fc",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

I think this issue started occuring after PR #5048. I did a flight as EASY 2057. After landing and parking I set the parking brake, shut down engines and call the ground services. Normally, the ATC would call me EASY 2057, but now uses AIRBUS instead. This is probably caused by the fact the FMC is cleared?

### Expected behavior

I would expect to call the ground services using my original callsign 'EASY 2057'. 

### Steps to reproduce

1. Start a short IFR flight and check the callsign and flightnumber
2. Use the ATC to guide you during the flight
3. After parking call ground services and ask for i.e. baggage
4. Verify ATC is using the default AIRBUS callsign

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### LINKED ISSUE #5215: baro not clearing from PFD
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-25T14:50:34+00:00",
  "ref": "master",
  "sha": "1f9462ceda1a2c63c61437cd67ed60bc7b30cd2c",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

When completing a flight from a location to the next and when you shut down the engines and the MCDU and every reset and go back to how it looks in cold and dark, the PFD still shows the baro inputted but if you go to the PERF Arrival page it is blank
FlightSimulator_W5eIi1croa

### Expected behavior

It should clear like everything else does in the MCDU or correspond with the MCDU

### Steps to reproduce

1. Do one flight to and from a airport with all the arrival information inputted
2. After shutdown of the engines and the MCDU goes back to cold and dark state, look at your PFD
3. Then check the PERF landing page and see if any data is there

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Beedan🎗#3838

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #5112
Fixes #5215

## Summary of Changes

- ATC now using correct callsign
- Some vars are now being properly defined

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Perform a flight as per usual, observe linked issues are fixed.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by beheh — APPROVED** [review]

**Comment by sidnov** [comment]
QA Report

Object of testing: #5143 
Tier of Testing: 1
Date: 25/06/2021

Testing Process:
Followed the same procedure as #5048: Short IFR Circuit pattern with fully filled flightplan (departure, arrival, one enroute waypoint). Spawned C/D, filled INIT A and B, FPLN, PERF. Departed VABB runway 27, hand-flew a circuit pattern manually. Filled APPR PERF on downwind, and did a full stop landing. After ROLLOUT phase, MCDU resets to the initial page. All entered data resets with amber boxes, PERF page reset to TAKE OFF, ND shows PPOS on wpt indicator as all other waypoints are deleted.

In addition to this, used the in-game ATC to observe any callsign discrepancies post arrival. None observed. ATC used the registration of the aircraft throughout the flight. Ground services use the correct callsign as well.

Negatives: None
Testing Results: Passed

Conclusions: Works as described 👍🏻

**Comment by tracernz** [comment]
Can you also set the DH/DA simvars for https://github.com/flybywiresim/a32nx/issues/5215?

**Review by tracernz — APPROVED** [review]

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5143
Tier of Testing: 1
Date: 26/06/2021

Testing Process:

1. Spawned C&D
2. Filled MCDU for normal operation
3. Performed a circuit (KFLL)
4. Observed reinitialization and verified linked issues have been fixed

Negatives: 

- Can not fill out "FLT NBR" in INIT page, FMS. (check media)

Testing Results: Not Passed
Conclusions: Although reinitialization is completed with no issues, not being able to fill in the FLT NBR needs to be fixed. (Though, ATC did register and address with the correct callsign inputted into the FMS.)
Media: 

https://user-images.githubusercontent.com/72807945/123517503-5888b400-d66f-11eb-89d0-6d4c356d745c.mp4

**Comment by MisterChocker** [comment]
@AviationSpotter Thanks for testing and finding this issue, I've fixed the issue.

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5143
Tier of Testing: 1
Date: 26/06/2021

Testing Process:

1. Spawned C&D
2. Filled MCDU for normal operation
3. Performed a circuit (KPHX)
4. Observed reinitialization and verified previous and linked issues have been fixed

Negatives: N/A
Testing Results: Passed

Conclusions: Can confirm previous and linked issues have been fixed!

**Pull request merged**
