### PR TITLE
feat(checklist): add Fuel Pumps checkpoint 

### LINKED ISSUE #4513: No fuelpump on checklist before engine and apu startup
**Is your feature request related to a problem? Please describe.**

I am a newbie in MSFS and did want to start up the 320 via CHECKLIST. But there was no "fuel pump on" on either of those checklists before "Engine Start". Maybe im blind, but i did use following checklists in this order: 
- preliminary cockpit prep.
- cockpit preperation
- before start (non-interactive)
- engine startup
- after engine startup

**Describe the feature you'd like to see implemented**

add the checkpoints to turn on fuel pump for engines and apu

**References**

**Additional context**

As stated before im a beginner, but i think this is missing? When im wrong and those points are in the checklists, i did not find them... 
ANYWAY Thank you sooo much for this mod and the hard work!!! 

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

### PR DESCRIPTION
**Pull request by sidnov**
Fixes #4513 

## Summary of Changes

- [x] Added a checkpoint for fuel pumps in the ~~Engine Startup~~ Cockpit Preparation flow with highlighted nodes.
- [x] Linked checklist item from the Parking flow

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub): sidnov#8337

## Testing instructions

1. Spawn C/D or on a runway. (You may have to Reset Page before testing if you spawn on runway)
2. Find the new checklist item in the OVERHEAD section of Cockpit Preparation flow. 
3. Click the (eye)con on the right and make sure the fuel pump switches are highlighted in blue

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by davidwalschots — APPROVED** [review]

**Comment by tracernz** [comment]
Should go at the near the start of cockpit prep (covered by extinguish all white lights on overhead panel on the real SOP). Engine start is much later.

**Comment by sidnov** [comment]
> Should go at the near the start of cockpit prep (covered by extinguish all white lights on overhead panel on the real SOP) AFAICT. Engine start is much later.

Will change it to "CHECK" instead of "ON" in the cockpit preparation flow, since the switching on part is technically covered when extinguishing all white lights on the overhead scan.

**Comment by Samueleonard** [comment]
Category: QA Tester
Name: 1Samueleonard1#0001
Date of testing: Current date 21/04/2021
Version of the sim: 1.15.8.0
PR Tested: #4516
Tier of testing: 1

Changes to observe: fuel pumps on checklist

Testing technique: Tryout
1. loaded in and followed checklist to set up
2. got to fuel pump item
3. pressed on 'eye' - all fuel pumps lit up
4. ticked fuel pump item
5. went through checklist - looking for other fuel pump items

Flight notes: in the 'parking' checklist - there is a fuel pump reference but no way to 'view' the fuel pumps

Media: n/a

Issues: n/a

Steps to achieve the issue:  n/a

Overall Rating: Changes needed

Conclusions of the testing: slight tweak needed but not the target of this PR

**Comment by sidnov** [comment]
> Category: QA Tester
> Name: 1Samueleonard1#1
> Date of testing: Current date 21/04/2021
> Version of the sim: 1.15.8.0
> PR Tested: #4516
> Tier of testing: 1
> 
> Changes to observe: fuel pumps on checklist
> 
> Testing technique: Tryout
> 
> 1. loaded in and followed checklist to set up
> 2. got to fuel pump item
> 3. pressed on 'eye' - all fuel pumps lit up
> 4. ticked fuel pump item
> 5. went through checklist - looking for other fuel pump items
> 
> Flight notes: in the 'parking' checklist - there is a fuel pump reference but no way to 'view' the fuel pumps
> 
> Media: n/a
> 
> Issues: n/a
> 
> Steps to achieve the issue: n/a
> 
> Overall Rating: Changes needed
> 
> Conclusions of the testing: slight tweak needed but not the target of this PR

Thanks for the test! I think I can include that item too with this PR.

**Pull request merged**
