### PR TITLE
[ATC] CLR input for squawk code

### LINKED ISSUE #1127: [BUG] Functionality of the ATC “CLR” key
**Mod Version**

0.3.1

**Describe the bug**

With the CLR key today just one digit at a time is cleared and replaced with a dash.

**To Reproduce**

**Expected behavior**

The correct functionality of the ATC “CLR” key is as follows:
Press The CLR key one time delete the last entered number.
Press a second time deletes all entered numbers.
There should not be dashes in stead of numbers when cleared.
If not a full set of four numbers are inserted within a certain time (not sure but estimate to 5 seconds) the previous code will be displayed again.

Note: The code “2000” is a normal code to have at startup. It is often selected just prior going from Auto/On to Stand By.

**Actual behavior**

With the CLR key today just one digit at a time is cleared and replaced with a dash.

**References**

I am a IRL A320 pilot.
From FCOM:
CLR Key
The flight crew uses this key to clear the code display.
Note: As long as the four figures of the new code are not entirely written, the previous code remains.

**Additional context**

Was this working before/when did the issue start occurring?
Never worked before

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by paul92ilm**
Fixes #1127 

## Summary of Changes
- Push CLR button 2 times in a row fully delete the squawk code

## Screenshots (if necessary)
Before :
image
image

After :
image
image

## References
Issue reported by IRL pilot (see issues #1126, #1127, #1192)

## Additional context
Discord username (if different from GitHub): Lussion

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

**Comment by b757cb** [comment]
Works as expected. Entered multiple squawk codes and double clicked CLR and entire code was deleted.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 27/10/2020
Version of the sim: 1950
PR Tested: #1570
Object of test: Testing if pushing CLR button 2 times in a row fully deletes the squawk code

Testing technique: Try-out
Steps you've made to test the Pull Request:

1. Loaded C&D  
2. Pressed CLR two times then re-entered the squawk code and tried again
3. Same test for start on runway.

Flight notes: N/A

Overall Rating: Good
Conclusions of the testing: Working as described, LGTM. Thank you for your work!

**Comment by FlyingCarpet7** [comment]
Hi!
Are you able to remove the dashes ?

**Comment by paul92ilm** [comment]
Hi, I focused on the bug described about CLR button
It will be easy to change dash to empty but I need information before
If squawk code is cleared and you input a digit, where does this first digit appear ? (left or right)

For example if I enter 6452 squawk code, does it look like that ?
image
image

Or digits appear like before with dashes ?

**Comment by FlyingCarpet7** [comment]
0ED70D73-6960-4AB3-AFFD-283690ED298F
Something like this

**Comment by FlyingCarpet7** [comment]
The font and size I guess is for someone else to fix?
Font looks ok, but size should be a tad bigger.

**Comment by Benjozork** [comment]
@paul92ilm please don't mark PRs as closing an issue if it does not address all of it. alternatively, use the word "Addresses" as that won't make GitHub close the issue.

**Comment by paul92ilm** [comment]
> @paul92ilm please don't mark PRs as closing an issue if it does not address all of it. alternatively, use the word "Addresses" as that won't make GitHub close the issue.

Well, this PR fix bug described in title and description ("CLR" key).
Maybe I focused too much on title and not on expectation, sorry about that.

**Pull request merged**
