### PR TITLE
feat: aileron droop and anti-droop

### LINKED ISSUE #4805: Aileron Droop
### Aircraft Version

Development

### Description

Newer 320's come with modified Flight Control Computers which can have the aileron droop when flaps are deployed or have the ailerons undroop during ground spoiler deployment. The ailerons can both droop (aileron lowers to increase lift) or undroop (aileron rises to reduce lift). Currently, the ailerons do not droop and I believe it should due to the fact that the "aileron droop" is becoming more common, modified on newer 320's, and also because it looks nice.

### References (optional)

image

https://www.youtube.com/watch?v=CmHPzIs38sY
Timestamp: 
1:30 - First notch of flaps and aileron droop.
4:12 - Ground spoilers deployed alongside with aileron undroop.
5:28 - Spoilers retracted and end of aileron undroop.
5:39 - Video ends but ailerons were still drooped because of flaps. Aileron drooping will end when the flaps have been fully retracted.

### Additional info (optional)

Aileron drooping reacts with flaps and not slats!

### Discord Username (optional)

Aviation Spotter#9102

### PR DESCRIPTION
**Pull request by aguther**
Fixes #4805

## Summary of Changes
This PR introduces **visual** aileron droop and anti-droop function:
- the ailerons are drooping 5° down on both sides when flaps are extended
- the ailerons are anti-drooping when ground spoilers are fully applied / deployed (not on partial deployment)

### What means visual?
Visual means that the droop and anti-droop of the ailerons is visible on the 3D model and on the FCTL SD page but it's not visible in simulation variables and also has no impact on the flight model.

## References

https://www.youtube.com/watch?v=fEyOEUGiBi0
https://www.youtube.com/watch?v=CmHPzIs38sY

## Testing instructions

- test if ailerons move properly in normal flight and with AP on and off
- test if ailerons droop with flaps (and only with flaps)
- test if ailerons anti-droop when **all** of the following conditions are true:
  - ground spoilers fully deployed (rejected take-off or on landing)
  - Autopilot off
  - Flaps/Slats deployed
  - pitch attitude < 2.5°

### Compatibility
It would be good to know how the custom animation of the ailerons is interacting with third party tools. Therefore please make a test with a replay tool if you have one and do a flight with a tool like YourControls if you have time and it's possible for you.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
Code LGTM.

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #4903 
Tier of Testing: 1
Date: 26/05/2021

**Testing Process:** (no 3rd party tools)
1. Loaded up onto RW
2. Checked droop with flaps. Retracted flaps, checked no droop.
3. Rejected takeoff. Checked undroop with spoilers and droop with spoiler retraction
4. Takeoff and short flight test for aileron functionality
5. Approach and autoland
6. Another manual landing

**Negatives: **
- So you say that with AP on, there should not be droop, right? After takeoff, selecting AP on, droop will stay
- Same with setting Flaps 1 airborne with AP on, there is droop
- while autolanding ailreons stayed drooped, not anti-droop. They came up just before I came to a standstill (watched the landing in showcase mode)
- same on manual landing

**Testing Results:** Not Passed. Please check above. The only info in my docs I can find was "The ailerons extend 5° down when the flaps are extended". Nothing about AP requirements

**Comment by aguther** [comment]
The requirement for autopilot is related to anti-droop and not droop.

**Comment by AviationSpotter** [comment]
Name: Aviation Spotter#9102
Date of testing: Current date 26/05/21
Version of the sim: 1.16.2.0
PR Tested: #4903
Tier of testing: 1
Changes to observe:
Aileron droop and anti-droop

Testing technique: Spawned on runway (spotting the obvious)

Steps you've made to test the Pull Request:

1. Checked aileron droop with all flap positions
2. Takeoff while monitoring drooping from a wing view
3. Landing while monitoring anti-drooping from wing view

Flight notes (When done a full flight): n/a

Media: 

Aileron Droop and Anti-Droop Comparison

https://user-images.githubusercontent.com/72807945/119634023-4ef5fd00-bde0-11eb-8b80-389d94e0c639.mp4

Aileron Anti-Droop Reacting with Reverse Thrust

https://user-images.githubusercontent.com/72807945/119638593-cfb6f800-bde4-11eb-87ef-3c1453e7c82b.mp4



Issues: 
• During transition of flaps to the 0 position, aileron drooping ends too early. Aileron drooping should not beat the flaps from retraction. (Left a video about this in media).
• During retraction of ground spoiler, aileron anti-drooping ends before ground spoiler retraction transition begins. (Left a video about this in media).
• During aileron anti-drooping with ground spoilers, the ailerons aren't reacting to aileron input. Aileron input is still priority and if there to be aileron input, only one aileron is called to give input while the other stays anti-drooped.

Overall Rating: To Be Improved
Conclusions of the testing: When aileron drooping is called they're behaved as expected and just a few things occur that aren't the same to references. Also, aileron anti-droop usually doesn't deploy as fast as the ground spoilers until reverse thrust are in action. Though, not possible until the implementation of ground spoilers deploying automatically when reverse thrust is deployed (left a video about this in media).

**Comment by aguther** [comment]
> During transition of flaps to the 0 position, aileron drooping ends too early. Aileron drooping should not beat the flaps from retraction. (Left a video about this in media).

Ok, I will search for more references to be sure they retract differently than they deploy.

> During retraction of ground spoiler, aileron anti-drooping ends before ground spoiler retraction transition begins. (Left a video about this in media).

Yes true, but I think this is mainly related to the animation of the ground spoilers being in the upper most position before real deployment is finished. It‘s the same when you disarm ground spoilers after landing, while retraction directly starts the animation does not start immediately. Maybe this can be improved with a custom animation of the spoilers later, but in this PR I will not fix it or make the logic extremely complicated just for that.

> During aileron anti-drooping with ground spoilers, the ailerons aren't reacting to aileron input. Aileron input is still priority and if there to be aileron input, only one aileron is called to give input while the other stays anti-drooped.

Do you have a reference or proof that this is the case? Up to now it does not seem to me that way, also probably a reason why with AP on the whole function is disabled.

> Overall Rating: To Be Improved
> Conclusions of the testing: When aileron drooping is called they're behaved as expected and just a few things occur that aren't the same to references. Also, aileron anti-droop usually doesn't deploy as fast as the ground spoilers until reverse thrust are in action. Though, not possible until the implementation of ground spoilers deploying automatically when reverse thrust is deployed (left a video about this in media).

I‘ve seen your video, but according to FCOM reverse thrust is not a condition for the anti-droop. While it looks like this, I think the reason why it deploys later is because the aircraft was coming below 2.5° of pitch. This is implemented by the way.

**Comment by aguther** [comment]
I did a short check and I can confirm that retraction seems different than deployment.

My assumption is that flaps need to be retracted/deployed for a certain time for the aileron droop to retract/deploy.

I will do the following updates:
- adapt logic for droop function to be time based
- add inhibit condition for AP so that when disabling the AP after an automatic landing the anti-droop is not done
- use rate limiters for droop and anti-droop bias

**Comment by AviationSpotter** [comment]
> Do you have a reference or proof that this should be the case? Up to now it does not seem to me that way, also probably a reason why with AP on the whole function is disabled.

This is one video that sort of sticks out. 

https://www.youtube.com/watch?v=BbsN6pOzdic&t

Timestamps: 
Skip to 10:05
Aileron anti-drooped at 10:07
Looks to be Aileron input from 10:08-10:18

**Comment by ExampleWasTaken** [comment]
Quality Assurance Tester

Object of testing: #4903 
Tier of Testing: 1
Date: 26/05/2021

Testing Process: 
* Tested aileron droop - ✔️ 
* Tested aileron anti-droop - ✔️ 

Negatives: I could confirm the issues raised by @AviationSpotter 
Testing Results: Not Passed

Conclusions: Once the current issues are resolved it's GTG.
Media:
[Landing Video](https://streamable.com/e7ohr3) (don't judge my landing :D had to do it manually from the passenger seat...)

Additional Information:
The free replay tool from flightsim.to does not show the ailerons.

**Comment by aguther** [comment]
Changes have been incorporated. Please retest.

**Comment by donstim** [comment]
I'm not totally convinced that video shows aileron input overriding the anti-droop feature. It could just as well be some condition causing the anti-droop to not fully engage for a short time period after spoiler deployment.  What is happening on the opposite wing? Is this a roll right command, where the right aileron is kept at full deflection, while the left aileron (the one shown in the video) has its upward deflection reduced by an amount commensurate with the input (with it possibly going downward with full input)? Could be that way, but there is no corresponding decrease in the spoiler deflection angles, which would presumably also be used for roll control. It can't be a roll centering or roll left command as that presumably would not command a decrease in the default full aileron deflected anti-droop state.

It sure would be nice to have full documentation on the feature. Without more complete information, I would lean toward the ailerons being like the ground spoilers and no longer being available for roll control once the feature is fully activated. After all, that's what the ailerons have become. And I believe their effect is included in the RTO and landing distances, which implies that they would have to remain in the fully deflected position once activated.

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Object of testing: #4903 
Tier of Testing: 2
Date: 26/5/21

Testing Process: 
- Did a full flight while looking at ailerons throughout the flight
- Spawned on approach and tested anti-droop with ap on/off, tried with a pitch higher than 2.5 degrees and without arming spoilers
- Spawned on the runway and checked that droop was there
Negatives: N/A
Testing Results: Passed

Conclusions: Everything looked to work as expected, don't know exactly how it's supposed to work but looks like it follows everything in the testing instructions and videos provided.

**Comment by dragold** [comment]
Name: Mr.Blank#2638
Date of testing:26-27/05/21
Version of the sim: 1.16.2.0
PR Tested: #4903
Tier of testing: 1
Changes to observe:
Aileron droop and anti-droop

Testing technique: tryout
Methodology-
touch and goes landings 
touch full stop and goes
touch and goes landings early pitch up of the airplane
SOP flight

Negatives: In relation to PR NIL
Flight notes (When done a full flight): n/a
Testing Results: (Passed)
Conclusions: All Observations where are expected

**Pull request merged**
