### PR TITLE
Fix more things for the ANN LT TEST

### PR DESCRIPTION
**Pull request by AdenFlorian**
makes progress on #528

**Summary of Changes**

 FCU
 IRL has a decimal point to the left of every number, but the game FCU only has one's that are actually used, so we will have to add the other decimal elements to match IRL
 BARO display

Chronometer should have lots of 88888

radio thing should show all 88888888

ATC FAIL light should be on

TCAS display should be 8888

Had to copy over some more vanilla files to make this happen.

**Screenshots (if necessary)**

image
image
image
image

**Additional context**

### CODE REVIEW

**Comment by camilo625** [comment]
Maybe i am doing something wrong, but i don't get any screen working on this PR (EFIS, ECAM, ND, COM, AP, CHRONO, etc).

**Comment by AdenFlorian** [comment]
I'll take a look!

**Comment by AdenFlorian** [comment]
ah, its because i didnt push the layoutjson stuff, and i added new files. I pushed them now so it should work for you.

**Comment by younesseQAtester** [comment]
working as described ! 

FlightSimulator 9-14-2020 12-53-34 AM-715
FlightSimulator 9-14-2020 12-54-05 AM-345
FlightSimulator 9-14-2020 12-53-58 AM-150
FlightSimulator 9-14-2020 12-53-46 AM-961

**Comment by camilo625** [comment]
Works as described, great work!

**Review by DoToAdventures — APPROVED** [review]
Looks good, but probably best to remove the layout and manifest files before merging just to be safe. CI should take care of it?

**Review by UncleClapton — APPROVED** [review]
LGTM!

**Pull request merged**
