### PR TITLE
fix(sound): pack opening condition

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Removed 30 sec timer to reopen packs
- Added open packs after both engines running

cc @hotshotp 

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check for the following conditions (pack sounds audible):
- Not audible during engine start
- audible when engine mode selector set to ignition or crank but both engines are running and available.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by hotshotp — APPROVED** [review]
LGTM

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 15/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3532 
Tier of testing: 1
Changes to observe: Packs behavior on ENG start
Testing technique: 
Steps you've made to test the Pull Request:

1. Loaded C&D
2. Started APU/BLEED - Packs open
image

3. ENG mode Sel ING - **Packs stay open**
image

4. Started ENG 2 - packs closing
image

5. Started ENG 1 - packs stay closed
6. Both ENG avail - packs sound comes on, but Pack valves stay closed
image

7. turn off APU/Bleed - Left pack opens, right stays closed
image

Media:

Issues (If Any):

Overall Rating: LGTM if the author didnt touch the display

Conclusions of the testing: Something is wrong with the Bleed display. If the immediate packs sound after engine start is due to this PR, then its working as intended.

**Comment by MisterChocker** [comment]
@St54Kevin yes, this pr does not touch the ecam page, it only sets the "state" of the bleed sound.

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: 16/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3532 
Tier of testing: 1
Changes to observe:

- Packs are audible during engine start
- Packs are not audible when both engines are running and engine mode selector is set to ignition or crank. 

Testing technique: Loaded c/d and tested the new changes
Steps you've made to test the Pull Request:
1. Started apu and apu bleed    
2. Set eng mode selector to ign and started the engines normally 
3. Tested the new sounds 

Flight notes: N/A

Media:  
Packs sound
Note: During this clip the engines and cockpict volumes were set to 0 for clarity  

https://user-images.githubusercontent.com/74972083/107980718-b5a69600-6ffb-11eb-83ff-f448c3275e48.mp4


Issues: N/A 

Overall Rating: Good
Conclusions of the testing: LGTM good job!

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 15.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3532
Tier of testing: 1
Changes to observe: pack sound plays in ignition and crank when both engines are availabe
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat., ext. power
3.) Set engine and cockpitsound to 0
4.) Turned on APU and APU Bleed (Packs become audible)
5.) Set engine mode selector to ignition (Packs get mute) and startet engines 1 (Packs are still mute)
6.) When engine 1 was AVAIL Packs sound was still mute
7.) Startet engines 2 (Packs are still mute)
8.) When both engines where AVAIL Packs sound becomes audible (without delay)
9.) Switches to norm and crank sound still audible
10.) On crank switched off Packs and back on again. They become audible without delay.

Issues: None

Overall Rating: Good

Conclusions of the testing: Seems to work

Hope this helps :-)

**Pull request merged**
