### PR TITLE
[CDU] Get the actual correct active waypoint for the systems that need it

### LINKED ISSUE #707: [BUG]FMGC  flightplan waypoints do not match waypoint in focus on NAV screen
**Mod Version**
Latest Master Version

**Describe the bug**
Flight plan in FMGC does not correspond to the waypoint in focus on the NAV.
As can be seen in below image on the FMGC. Next target ed waypoint is RIVET
However the NAV screen shows TARAL as the highlighted waypoint.

Also as a result of these not being in synch the targeted flight plan altitude constraints are not correct or being met. The plane sees to achieve the altitude constraints for the FMGC targeted waypoint (which is one way point ahead on the NAV).

Microsoft Flight Simulator 16_09_2020 9_42_45 PM

**To Reproduce**
1.    Create a flight plan in the FMGC as per normal (via MSFS flight planning page
2.    Take off and activate autopilot NAV mode
3.    Observe waypoint targeted and compare to NAV screen (they do not match).

**Expected behavior**

The highlighted FMGC target flightplan waypoint should match the highlighted waypoint on the  NAV screen.
The altitude constraints for the highlighted waypoint on the NAV screen are not met as the aircraft is targetting the altitude constraint for the FMGC waypoint. So the decent or climb profile is always one waypoint ahead instead of matching the current waypoint on the NAV.

**Actual behavior**
For example Taral has an altitude constraint of FL19450 (refer FMGC), however the aircraft decent path is targetting the RIVET 
Altitude constraints  140000ft. This happens throughout the flight with the FMGC waypoints and altitidues being targetted  tii early (always one waypoint ahead( when in managed altitude / managed nav / autopilot mode.

This is incorrect. The two waypoints should correlate / be corresponding.

This is making it very difficult to manage step climbs and step descents to match the flight plan. Have to always override autopilot currently to keep the plan on target.

**Really needs to be fixed as very annoying. Surprised this hasnt been raised yet.**

### PR DESCRIPTION
**Pull request by lousybyte**
Fixes #707

**Summary of Changes**

Correct the  `getActiveWaypoint()` function to properly return the active waypoint, it's now inline with other related functions. 
Fixes both UI and autopilot navigation issues that are dependent on a correct waypoint.

**Screenshots (if necessary)**

image text

**References**

Part of the `getActiveWaypoint()` function was relying on ` this.getGPSActiveWaypointIndex()` to get the active waypoint, but upon testing it became clear that was highly inaccurate and could even return waypoints that were not on the flight plan. 
After inspection, came to the conclusion that this was the only place in the code that used this GPS method of acquiring the waypoint, every other related functions such as `getPreviousActiveWaypoint()`, `getNextActiveWaypoint()` or `getActiveWaypointIdent` (and many others) all use an ident based lookup that correctly returns the desired value, thus this change.

**Additional context**

Requires `build.py`.

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by lawfulrocky** [comment]
I try your commits and all displays are not showing at all no backlight and not able to see anything
Screenshot (7)

**Comment by lousybyte** [comment]
Did you run `build.py`?

**Comment by lawfulrocky** [comment]
no

**Comment by lawfulrocky** [comment]
Name: Discord User lawfulrocky#4343
Date of testing: Current date 09/26/2020
Version of the sim: Version the tester uses
PR Tested: #893

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. tested on flight plan kchs/katl it fixes turns on approach
2. tested on flight plan kmia/kmco it fixes intersected paths to approach. which stay on plan instead switches to the closest waypoint
3. tested on flight plan kchs/kchs stays on flight plan and does turn on final


Overall Rating: Great work works as intended. Fixes bugs on waypoint where going on to approach it stays on plan and doesnt switches to closest waypoint
Conclusions of the testing: Ready to be merge. Just need Adim to check code

**Comment by Snapmatics** [comment]
You should always build.py before you pull a request. Do not forget that please.

**Comment by Benjozork** [comment]
Hello, please take note that we have started including a CHANGELOG.md file that requires every PR to add a change-log line that describes its changes. As your PR is not merged yet, we kindly ask that you add this information following the included directives in the file.

Disclaimer: This is a copy-and-pasted message.

**Comment by AdenFlorian** [comment]
please provide a reference, thanks!

**Comment by lousybyte** [comment]
Updated.

**Pull request merged**
