### PR TITLE
[TEXTURE] Chronometer Text (Overlapping Issue)

### LINKED ISSUE #2679: [BUG] Overlapping text on clock
**Mod Version**

0.5.1

**Describe the bug**

1. See the clock after avionics on
2.
3.

**Expected behavior**

Adjust clock display

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Works before last FS2020 update

Is this a problem in the vanilla unmodded game?
Not tested without nx

### PR DESCRIPTION
**Pull request by Snapmatics**
Fixes #2679
## Summary of Changes

Fixed the overlapping text on the chronometer.

### Before
image

### After
Screenshot_240

## Additional context

Discord Username: `Snapmatics#2424`

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by tareksabet** [comment]
#2679

**Comment by Snapmatics** [comment]
> 
> 
> fixes issue #2679

I searched for the issues but never found it lol.

**Comment by tareksabet** [comment]
> > fixes issue #2679
> 
> I searched for the issue but never found it lol. Thanks

you can filter issues by choosing a specific label for the issue

**Comment by ImenesFBW** [comment]
Credit to @DarkOfNova

**Comment by Snapmatics** [comment]
> 
> 
> Credit to @DarkOfNova

He said that he didn't want to. I asked him. But it's fine.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: Current date 07/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2924
Object of test: Checking the chrono texture fix 
Testing technique: Try-out 

## Steps you've made to test the Pull Request:

 * Loaded on RWY and checked the chrono texture at day and at night

## Overall Rating: Good

#### Conclusions of the testing:

 * Looks good to me! thanks to Harry for making the PR and Dark for fixing the textures.

#### Pictures:

chrono2
chrono1

**Comment by Snapmatics** [comment]
No worries <3

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 07/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2924 
Object of test: Chronometer Text Fix
Testing technique: Tryout

Steps you've made to test the Pull Request:
1. Spawned at VABB at night time, C/D
2. Turned on battery, external power. Turned on Dome Lights.
3. Checked Chronometer Text. No overlap
4. Changed time to Day. Checked Chrono text again, same result


Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: The overlap on the Chronometer text is rectified. Good to go!

**Comment by Benjozork** [comment]
Is the SET label supposed to be backlit IRL ?

**Comment by Snapmatics** [comment]
> Is the SET label supposed to be backlit IRL ?

Yes. Btw none one the middle text in the chronometer light up but there is no way to remove them since they are using the letters in the DDS file.

**Comment by Snapmatics** [comment]
> Is the SET label supposed to be backlit IRL ?

Btw this PR has nothing to do with the SET label. It's just to fix the double text generated by Asobo. Weird...

**Review by Benjozork — APPROVED** [review]
LGTM

**Pull request merged**
