### PR TITLE
feat: flight model improvements

### PR DESCRIPTION
**Pull request by donstim**
## Summary of Changes

This PR improves the flight model in 3 main areas:
1) The landing gear parameters have been adjusted to provide more gear suspension travel and to match the amount of travel for the real airplane between empty weight and maximum ramp weight.; and 
2) Changed the stability of the airplane in pitch and roll with respect to the local air mass. This should provide both more of a feeling of inertia when hand flying and increase the effect of turbulence/gusty winds on the airplane (reducing the "flying on rails" feeling.
3) Slightly reducing ground effect overall and reducing it further as Mach increases. The Mach dependency has always been available in the MSFS flight model, but until this point we have not taken advantage of it. This new implementation will result in less ground effect, for example, at higher elevation airports or with increased landing speeds.
4) Changed the lift and drag parameters for CONF 1+F to obtain better a better match with pitch and N1 targets and incorporate a pitch up characteristic when going from CONF 1+F to UP.

Other ancillary changes were made to braking and pitch trim effectiveness as a result of the above changes to retain accuracy in those areas.
## References

For the landing gear changes:
Screenshot (2098)_LI
The position C1 was used for the nosegear suspension travel, and BF1 was used for the main gear suspension travel. The difference between the heights at C1 and BF1 at MRW and at 41T at the respective CG positions was used to set the spring constant exponential value. Comparison of A32NX after this PR to the Airbus document:
Screenshot (2099)

## Additional context

These changes are relatively subjective as they affect the feel of the airplane. Although the relative gear travel for the different loading conditions was objectively determined as shown above, the relative flexibility/rigidity of the gear, that is, the speed at which it compresses and rebounds, can be tuned separately from the amount of travel. 

The feel of the airplane while hand flying and the airplane's responsiveness to turbulence/gusty winds is also subjective. In addition, it is not easy to find or produce some sort of standardized/known levels of turbulence/wind gusts replicating known real world conditions for making a comparison. In order to provide a realistic feel in relatively calm conditions, the airplane reaction in very gusty (but real) conditions may be overdone. On the other hand, providing a better feel in these very gusty conditions can result in that too stable, flying on rails feeling in more calm conditions.

The reduction in ground effect should slightly reduce the "float" on landing. According to our pilot feedback, the current flight model is very close to providing the correct feel, but tends to float a little too easily. Hopefully, this will improve the situation. It should also end up in a bit more control input being needed at higher elevation airports.

Discord username (if different from GitHub): donbikes#4084

## Testing instructions

For the landing gear changes, make sure the airplane handles correctly during taxi, takeoff, and landing, and that the chocks still work the same. Conduct some landings with different landing rates of descent and pass judgement on whether the gear reaction is adequate. (It should not result in the airplane bouncing up and down on the gear, but it should also provide more compression and rebound than the current airplane.)

For the flying quality changes, this would best be tested by some of our IRL A320neo pilots. In any case, check to see whether there is more of a feeling of inertia in hand flying and whether the airplane responds more to turbulence/gusty winds. For the latter, if flying with real weather, it is probably best to try this in mountainous terrain, or when landing during the day in areas where convection heating causes updrafts/turbulence. (Not always easy to find, but can maybe use this to help: https://www.badbadweather.com/.)

Also, check to see if the ground effect changes improve the accuracy of the landing flare, don't cause issues elsewhere (like takeoff), and that the airplane does not rotate prematurely when using allowable IRL takeoff speeds and the trim setting per the chart at the bottom of the A32NX checklist.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Approved but note this will need more feedback and testing by pilot group as well as testing any autoflight impacts before this can be merged.

**Comment by donstim** [comment]
This PR has been revised since it was added to the experimental version. Can someone add the new version to experimental?

**Comment by 2hwk** [comment]
> This PR has been revised since it was added to the experimental version. Can someone add the new version to experimental?

Incoming

**Comment by dragold** [comment]
Category: QA Tester trainee
Name: Mr.Blank#6197
Date of testing MM/DD/YYYY:06/14/2022
The version of the sim: 1.25.9.0
PR Tested: #5314
Tier of testing: 2

Changes to observe:
The landing gear parameters have been adjusted to provide more gear suspension travel and to match the amount of travel for the real airplane between empty weight and maximum ramp weight.; and
Increased the stability of the airplane in all 3 axes (pitch, roll, and yaw) with respect to the local air mass. This should provide both more of a feeling of inertia when hand flying and increase the effect of turbulence/gusty winds on the airplane (reducing the "flying on rails" feeling.
Slightly reducing ground effect overall and reducing it further as Mach increases. The Mach dependency has always been available in the MSFS flight model, but until this point, we have not taken advantage of it. This new implementation will result in less ground effect, for example, at higher elevation airports or with increased landing speeds.
Testing instructions
For the landing gear changes, make sure the airplane handles correctly during taxi, takeoff, and landing, and that the chocks still work the same. Conduct some landings with different landing rates of descent and pass judgment on whether the gear reaction is adequate. (It should not result in the airplane bouncing up and down on the gear, but it should also provide more compression and rebound than the current airplane.)
For the flying quality changes, this would best be tested by some of our IRL A320neo pilots. In any case, check to see whether there is more of a feeling of inertia in hand flying and whether the airplane responds more to turbulence/gusty winds. For the latter, if flying in real weather, it is probably best to try this in mountainous terrain, or when landing during the day in areas where convection heating causes updrafts/turbulence. (Not always easy to find, but can maybe use this to help: https://www.badbadweather.com/.)
Also, check to see if the ground effect changes improve the accuracy of the landing flare, don't cause issues elsewhere (like takeoff), and that the airplane does not rotate prematurely when using allowable IRL takeoff speeds and the trim setting per the chart at the bottom of the A32NX checklist.

Testing technique: Tryout and cross-Simulator comparison 

Methodology:
All as per Testing instructions 
consistency Test,  full sop flight
consistency Test, Quickstart full flight
consistency Test, from Air, reload from RWY
consistency Test, Taxi (SOP& Non-SOP)
consistency Test, Fast Taxi (SOP& Non-SOP)
rejected takeoff
rejected takeoff breaks only
touch and goes
Ground effect consistency Test, flying at ground effect region of flight envelop for max time with idle throttle
Ground effect exit consistency Test, flying at ground effect region of flight envelop for max time with TOGA throttle to observe the flight exiting characters from ground effect region of flight envelope with 0 pitch angle
Break action test for TOGA and full brake pressure /parking breaks

Remark- all test results were compared to FSLabs and Toless, within error of margin
Negatives: NIL
Testing Results: conclusive, Pass
Conclusions: All tests as per Methodology were of similar results as compared to Xplane and P3D, Hence Pass, 
PS Good Job

**Comment by rockpapst1** [comment]
Quality Assurance Tester/Trainee Report
Discord:(rockpapst#3585)
Object of testing: 7258
Tier of Testing: 1
Date: 14/06/2022
Testing Process:TAXI on Ground with a lot of turns and breaking (SLOW and FAST 30kt+)
                Touch an GO at KLAX
                Rejected Takeoff
                highspeed Landing with no autobrake
                TOGA Takeoff
                Flaps 2 Landing
                Flaps 3 Landing
                Short Flight from KLAX to KLAS 
                
                (all in one session)
Positive: - The diving of the Damper when breaking looks and feel very nice and smooth 
         - The Flight Model Feels and react excellent 5 of 5!
	   - Controlling and Braking on Ground Looks and feels good. 
Negatives: - Aircraft goes Soft Up and down at the ground, looks like "Breathing" - no Boarding or anything else applied
Testing Results: Passed, All Tests went excellent, i Compared the Taxing to The Fenix A320 and it looked Similar.

**Comment by donstim** [comment]
**Updated** based on comments from pinatacolada in the Discord pilot feedback channel. Revised:
1)  Increased MOIs to increase feeling of inertia, 
2) Increased the stiffness damping of the nose gear to prevent it from springing back quickly when forward stick pressure during the takeoff roll is relaxed at 100 knots
3) Reduced elevator effectiveness by inclusion of an elevator lift coefficient value that is lower than the default value. Also incorporated the IRL elevator max deflection angles and removed the effect of the elevator elasticity table per #5971. However, the changes to the FBW system from that PR are not included here. Also, since the elevator trim elasticity table is being used to address a different issue (see #7198 , that change is also not included here. @lukecologne 
4) Reduced roll damping and aileron effectiveness

These changes have been made to facilitate further pilot evaluation. DO NOT MERGE THIS PR. Also, these changes are not compatible with the hydraulics system in the experimental version, so this update should not be put in the experimental version at this time.

**Comment by donstim** [comment]
Another iteration responding to pinatacolada's most recent comments. Thank you! Continued work-in-progress. Decided to remove the changes to the elevator elasticity table and elevator deflection limits from #5971, so it should be okay to put this into the experimental version. I decided to defer those changes for now. The primary goals of this update are: 1) to further reduce any pitch-up during the takeoff roll when forward stick pressure is removed at 100 kts; and 2) Try to reduce in-flight pitch sensitivity to elevator input.

**Comment by donstim** [comment]
For some reason, changing the elevator lift coefficient slope to achieve the desired pitch characteristics affected the aerodynamics of the airplane in level flight. I used the flight tuning parameters available in the flight_model.cfg file to re-tune the flaps up lift and drag. 

The other change made with this revision is to reduce the lift and drag on CONF 1. Not only does this result in a better match of the pitch angle for CONF 1, it also causes a pitch up when going from CONF 1 to UP. This was requested by one our A320neo pilots.

**Comment by donstim** [comment]
We don't appear to be getting any more pilot comments, so I guess the DO NOT MERGE label can be removed.

**Comment by donstim** [comment]
Update to trim elasticity table to regain match with cruise data from https://github.com/flybywiresim/a32nx/pull/7198

**Comment by donstim** [comment]
Converting to draft. This flight model has some issues and should not be merged. Was intending to replace it with an updated version, but now that is not happening. Will leave this on draft for a little while before closing.

**Pull request closed without merging**
