### PR TITLE
[CDU] Changing CRZ and DES speed to allow and hold any speed restriction 

### LINKED ISSUE #2655: [BUG] Odd A/T Behavior On/Close to Descent
**Stable 0.5.1**

**Describe the bug**
When approaching TOD (perhaps when planned for descent to begin whether or not descent actually begun), A/T shifts into deceleration.  When descending, the A/T seems to bounce between idle/thrust wildly as if it cannot seem to decide upon a descent rate.

**To Reproduce**
1. Cruise with IFR flight plan active towards descent into any airport (I flew into KDEN).
2. When approaching descent observe throttle activity.
3. When cleared to begin descent by ATC, observe throttle activity.

**Expected behavior**
Relatively smooth descent maintaining planned descent speed profile.

**Actual behavior**
Volatile throttle engage/disengage every 5-7 seconds with dramatic speed and pitch changes resulting.  When engaging the speed knob instead, descent smoothed.  Thx.

**References**
N/A

**Additional context**
Also noted the wobbling left to right is somewhat back even while descending thru FL100 at 250K or less (noted in another report at CRZ).

**Was this working before/when did the issue start occurring?**
This was working prior to MSFS v1.12 update 12/22 using FBW v0.5.0.  Began after MSFS update.

**Is this a problem in the vanilla unmodded game?**
No.  Does not occur in default A320 to my knowledge (only attempted one flight after update while waiting for v0.5.1).

### LINKED ISSUE #2864: [BUG] Cruise speed oscillating between 170 and 290 when reaching cruise altitude in managed mode.
**Mod Version**

master

{
  "built": "2021-01-03T01:18:30+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**

I was doing a flight from KLAX - KLAS.  25R ORCKA5 departure MISEN transition, into KEPEC6 arrival MISEN transition into ILS 01L.  Fully programmed the MCDU.  Init page was set to Cruise Alt FL290.  Perf takeoff page set to flaps 1, Flight plan set as specified.  Cost Index 30. Weather was set to live weather, and time set to 9am.  there were fog, and clouds present.

I took off on 25R turned left, and did a managed climb to cruise altitude via the SID.

When i reach cruise altitude, The cruise speed kept oscillating between 170 and 290 on the speed tape.  If i looked at the cruise perf page, the speed was changing between *170 and *290.  You can see this behavior in the video in this link:

https://www.youtube.com/watch?v=1v-3bZlko_k

**To Reproduce**

1. program MCDU as specified above ( i used the default fuel/weight numbers when programming the Init B page)
2.set weather/time (not sure if this has anything to do with it.  On the help discord, someone said it might have to do with clouds being present,
3.follow sid, climb to cruise in managed mode (speed, heading, and altitude), experience speed oscillation at cruise.

**Expected behavior**

Managed speed to be set to the value calculated, for the cost index. (~290 kts)

**Actual behavior**

Managed speed setting oscillates between 170 and 290 kts.

**References**

Video of issue here:
https://www.youtube.com/watch?v=1v-3bZlko_k

**Additional context**

Was this working before/when did the issue start occurring?

This has been an issue in the master builds for at least the last week at time of this posting.

Is this a problem in the vanilla unmodded game?
don't know, haven't trying stock 320.

Discord username (if different from GitHub):
TheJoe88

### PR DESCRIPTION
**Pull request by Watsi01**
Fixes #2864
Fixes #2655

## Summary of Changes
Right now, when there is a speed restriction, the managed speed jumps back and forth between flightphase speed and speed restriction during cruise or descent.

I changed flightphase CRZ and DES speeds to acknowledge and hold any speed restriction and go back to normal flightphase speed, when no speed restriction is given for the next waypoint(s).

Also removed some unfinished code from MisterChocker (by his own wish).

## Additional context

Discord username (if different from GitHub): RogePete

## Testing instructions
If you like, you can program the following testroute in your MCDU to test. There are some speed restrictions involved to see, if manages speed holds the restrictions and comes back to normal flightphase speed, if no restriction is set for a waypoint.

KLAX/KLAS, CRZ Level FL290, CI30

KLAX 25R via ORCKA5 SID Trans MISEN
then
OINKS HEINY SERUE COOLS (I made that little loop to see if the change between restr and normal flightphase speed works)
and finaly
KLAS ILS01L via KEPEC6 STAR and Trans MISEN

The route should now look like this:
test

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Watsi01** [comment]
@Benjozork SORRY! would you please take a look at this again. MisterChocker talked to me and he wanted some code (regarding speed constraints) to be removed, since it isn't working right now. Closed the previous PR and made a new one. This should be good now.

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 05/01/2020
Version of the sim: 1.12.13.0
PR Tested: #2876
Object of test: CRZ and DES speed restriction changes

Testing technique: Full two sector flight's. Southend to Hamburg
Steps you've made to test the Pull Request:
1. Spawned Cold and Dark, Flight planned via SimBrief - departed Southend
2. During descent into Hamburg with some speed restrictions (in constraints active too), it reduced speed to 220kts but then afterwards went back to the unrestricted speed so I had to intervene
3. Checked the MCDU and verified the speed constraint was there at 220kts
4. Went back into managed speed... A/T tried to accelerate back to 250kts (below 10000ft) - intervened again to keep to 220kts
5. Landed

Flight notes (If required):
Route: CLN P44 RATLO M197 REDFA L620 TULIP Y12 SPY N873 GRONY M105 EEL N125 REVLA T907 SORUN T903 RIBSO RIBS5A Runway 05 arrival

Issues (If Any): As noted above, a speed constraint of 220kts exists for RIBS5A from the second waypoint in on the STAR... it didn't keep to it unfortunately either before or after passing
Overall Rating: To be Improved
Conclusions of the testing: As above - would need more testing by others to see if it's an isolated issue or a regular issue.

**Comment by MisterChocker** [comment]
> As noted above, a speed constraint of 220kts exists for RIBS5A from the second waypoint in on the STAR... it didn't keep to it unfortunately either before or after passing

Sounds dump, but this is intentional, there might be another pr that will introduce an appropriate algorithm make exactly what you have pointed out.

**Comment by BritishAvgeek** [comment]
😂 in that case I think it worked as expected!

**Comment by Watsi01** [comment]
@BritishAvgeek  Before, when there was a speed restriction, the managed speed jumped back and forth between flightphase speed and speed restriction during cruise or descent. This should be fixed with this PR. 

When exactly to reduce speed for the restriction and how long to hold it, is another project, as MisterChocker mentioned.

**Comment by BritishAvgeek** [comment]
Thanks, when I read it over a few times I thought it was referring to holding the constraint - what you've since pointed out though DID work as expected 👍 I just thought I was looking for the extra bits as well when clearly I didn't need to 😂

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 06/01/2020
Version of the sim: 1.12.13.0
PR Tested: #2876
Object of test: CRZ and DES speed restriction changes TEST 2 of 2

Testing technique: Full Flight from Gatwick to Bergen
Steps you've made to test the Pull Request:

1. Spawned Cold and Dark, Flight planned via SimBrief - departed Gatwick
2. Monitored Constraints on Departure
3. During initial descent it picked up the first speed constraint on entry to the STAR and set that as the speed target and stuck to it
4. Continued up to the next constraint change and stuck to that too
5. On entry to the STAR, runway was changed so I amended the MCDU with a new STAR and the new runway - didn't break it
6. Flew ILS and landed

Flight notes (If required):
Route: FRAN1Z FRANE M604 LARGA Z278 UNBUD Z322 ALUVA ALUV2N - RUNWAY change resulting in STAR change to ALUV2P

Issues (If Any): No issues found 
Overall Rating: Good

Conclusions of the testing: continuing from the test from yesterday I rechecked again today with a new route with different constraints etc during the arrival. No issues came about from it and it worked as expected. Had no jumping speeds.

**Comment by Watsi01** [comment]
@BritishAvgeek   Thx.

**Pull request merged**
