### PR TITLE
fix: revert cockpit decal textures, add speed placard decal

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

-  Updated cockpit text emissive and albedo.  Added parenthesis to the albedo and reverted the outdated decals that were merged with the texture rework.
- Reenabled the speed placard decal.

No changelog included since this is mostly a revert of changes that were already committed. 

## Screenshots

ere

## References
This PR reintroduces the changes made with previous cockpit decal PRs that were removed when the texture rework from @MoreRightRudder got merged. 

It also adds the speed placard decal that was blocked before since ours was redone in textures. This is a temporary change as @DarkOfNova will be reworking the speed placard and making it a decal. There are small issues with placard right now. If you zoom in you can see L overlaps the screw and the numbers and letters aren't perfect since this is using the default decal layout. But as I said this will shortly be changed to a separate decal. 

## Additional context
Closes issues caused by #3431.

Discord username: Imenes#8739

## Testing instructions

Besides the speed placard, make sure you check that all the decals (qnh units, throttle detent markers, landing gear arrow,...etc) that went missing with the texture rework are back in place and are up to date to textures before the rework was merged..

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by tyler58546 — APPROVED** [review]
LGTM

**Comment by NonstopFlying** [comment]
Category: QA Trial
Name: NonstopFlying #6771
Date of testing: Current date 17/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3571
Tier of testing: 1
Changes to observe: 

revert of cockpit decals and textures that were removed from via the update


Testing technique: 
Spawned in at Leeds and looked at the different decals
Steps you've made to test the Pull Request:
1. Spawned at Leeds
2. Looked at Throttle
3. Placard
4. Throttle
5. QNH and other decals

Media: 
placard
Throttle
FMC

Overall Rating: Good/To be improved
Good but like you said just need to replace that L so it's not overlapping the screw, other than that it's good

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3571 
Tier of testing: 1

### Changes to observe: revert cockpit decal tex, speed placard decal

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on runway at VABB
2. Checked the speed placard
3. Checked Throttle indent
4. QNH and other decals

### Media:
image
image
image
image

### Overall Rating: Good

Conclusions of the testing: The mentioned decals were checked. Good to go!

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3571
Tier of testing: 1
Changes to observe: Decals are back
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP


Decals visible:

- Speedplate
- Throttle detent
- QNH
- Alt knob increment pin
- Blue panel markers
- chair adjustment knobs

Issues (if related to this PR): Blue panel markers are missing

Overall Rating: -

Conclusions of the testing: When the blue markers are no (missing) decals, the PR is fine.

Hope this helps :-)

**Comment by ImenesFBW** [comment]
The L overlap and blue markings are out of the scope of this PR, since they will be added in as separate decals by another PR in the future by @tyler58546 and @DarkOfNova

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3571 
Tier of testing: n/a
Changes to observe: reimplement decals


Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned at EGGP
2. Turned on the Light
3. Checked Speed Placard
4. Checked FCU
5. Checked gear arrow
6. checked throttle

Media:
Microsoft Flight Simulator Screenshot 2021 02 17 - 20 51 00 18

Microsoft Flight Simulator Screenshot 2021 02 17 - 20 51 30 69


Issues (If Any): none

Overall Rating: very good
Conclusions of the testing: adds alot more to the already great cockpit. no issues found apart the known ones (flickering)

**Comment by ImenesFBW** [comment]
Taking a look at what is happening with the chrono.

**Comment by ImenesFBW** [comment]
@ChruutvoLuzi can you take a look at the same conditions in the development version. I seem to see problems there as well. I think it might be the metalness or roughness of the new texture that is overlaping it.

image

**Comment by ImenesFBW** [comment]
This is good to merge in my opinion. All the QA problems found are either not related to this PR (chrono) or are beyond the scope of this PR (blue markings and overlapping L) and will be added in a separate PR.

**Comment by kberg93** [comment]
Getting CTD with this PR installed, no issue with other PR's or without! (just a heads up)

**Comment by kberg93** [comment]
Now it doesnt CTD before main menu but it doesnt show up.

FlightSimulator_OBGh7EiMq8
FlightSimulator_gyAoYsmAHq

**Comment by marcman86** [comment]
Tested: CTD while MSFS loading screen for me.

**Comment by ImenesFBW** [comment]
@kberg93 and @marcman86 thanks for notifying me!

There was an issue with the rebase that should now be solved. If you get the time please redownload and give it another try.

**Comment by kberg93** [comment]
> @kberg93 and @marcman86 thanks for notifying me!
> 
> 
> 
> There was an issue with the rebase that should now be solved. If you get the time please redownload and give it another try. 

Will do tomorrow if it isnt merged yet. 😄

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 20.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3571
Tier of testing: 1
Changes to observe: Decals everywhere
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D to EDDP 08R
2.) Decals work
3.) Clock with daylight (Image1)
4.) Clock on flashlight (Image2)
5.) Clock on int. light (Image3)

Media:


Image1


Image2


Image3

Issues: None (when clock is to another PR)

Overall Rating: Good!

Conclusions of the testing: Works. Decals like before in my first test.

Hope this helps :-)

**Comment by kberg93** [comment]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/20/2021
Version of the sim: 1.13.16.0
PR Tested: #3571 
Tier of testing: 1
Changes to observe:
Revert cockpit decal textures, add speed placard decal.

Testing technique: Look around.

Steps you've made to test the Pull Request: 
1. Spawn at airport.
2. Look around the cockpit.

Flight notes (When done a full flight): Parked.

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None related to this PR.

Overall Rating: Good.
Conclusions of the testing: All decals i know is visible, and this PR does whats intended.

**Comment by Watsi01** [comment]
Just for me: why is this reverted? Cause it worked for me. At least I didn't find any issues.

**Comment by ImenesFBW** [comment]
> Just for me: why is this reverted? Cause it worked for me. At least I didn't find any issues.

It was merged not reverted.

**Comment by Watsi01** [comment]
Thanks. It sounded to me that this is a revert.

**Comment by ImenesFBW** [comment]
> Thanks. It sounded to me that this is a revert.

No worries the revert in the title is meant as reverting the older cockpit decals that were merged with the cockpit texture rework. That one was merged with the older decals so it took away some fixes that we made to decals. Hope that makes sense.

**Pull request merged**
