### PR TITLE
Desynced wiper animation

### LINKED ISSUE #171: wipers should be independent
windshield wipers should be independent between captain and FO

### PR DESCRIPTION
**Pull request by pepperoni505**
Fixes #171

## Summary of Changes

This PR desyncs the windshield wipers as well as the knobs

To dive a little deeper in the changes, a few things have been renamed:

- On the interior, the animation `HANDLING_Switch_Wipers` has been split into two animations: `HANDLING_Switch_Wiper_left` and `HANDLING_Switch_Wiper_right`
- On the exterior, the animation `HANDLING_Wipers` has been split into two animations: `HANDLING_Wiper_left` and `HANDLING_Wiper_right`
- The left wiper switch node has been renamed from `HANDLING_Switch_Wipers` to `HANDLING_Switch_Wiper_left`
- The right wiper switch node has been renamed from `HANDLING_Switch_Wipers_1` to `HANDLING_Switch_Wiper_right`

## Screenshots (if necessary)

https://streamable.com/fzolsj

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by pepperoni505** [comment]
@lukecologne would you mind pushing the knob changes?

**Comment by myselfaaryan** [comment]
Category: QA Tester
Name: myselfaaryan#0001
Date of testing: Current date 08/12/2000
Version of the sim: 1.11.6.0
PR Tested: #2243 
Object of test: Check Desynced Wipers

Testing technique: Try Out
Steps you've made to test the Pull Request:
1. Spawn C/D
2. Use Captain's Wiper at Different Speeds
3. Use First Officer's Wiper at Different Speeds

Flight notes (If required): N/A

Issues (If Any): N/A
Overall Rating: Good
Conclusions of the testing: Great PR! Cheers 🎉 People flying shared cockpit will have so much fun with this.

**Comment by pepperoni505** [comment]
I added the do not merge tag because how this gets merged depends on if #2246 is merged before or after this PR, since it contains an older version of the model.

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919
Date of testing: 12/7/2020
Version of the sim: 1.11.6.0
PR Tested: #2243 
Object of test: Windshield wipers.
Testing technique: Tried out.
Steps you've made to test the Pull Request:
1. Spwaned in C&D at kiad while raining.
2. Turned on both wipers at different speeds to make sure they would not both go to the same speed.
3. Tried with one wiper on and one-off on both sides.
4. Repeated testing above while looking outside at the exterior model.


Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Pr works really well no issues found can't wait for it to be merged. Also, I cant wait for the wipers to actually move the rain. Keep up the good work.

**Comment by Highflyer2010** [comment]
Category: QA Tester
Name: Discord Highflyer2010 #8932
Date of testing: Current date 08/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2243 
Object of test: Independant Wiper Animation

Testing technique: used the knobs to test each wiper

Steps you've made to test the Pull Request:
1. Spawned on runway at EGNT so engines already running
2. Moved left wiper knob slow/fast
3. Moved right wiper knob slow/fast
4. Turned right wiper off
5. Turned left wiper off 

Flight notes (If required):

Issues (If Any): N/A
Overall Rating: Good

Conclusions of the testing: Good work, i'm not too sure about the setting slow on the wiper are they still a bit fast? i'm not too sure i've attatched a pic to show that the wiper are working as in dependant
Screenshot 2020-12-08 170823

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#8145
Date of testing: 12/8/2020
Version of the sim: 1.11.6.0
PR Tested: #2243
Object of test: Testing Windshield Wipers
Testing technique: Checked and tested the desync at multiple speed levels.
Steps you've made to test the Pull Request:

Spawned cold and dark in Detroit with rainy weather.
Turned on power
Engaged left wiper knob, all speeds worked.
Engaged right wiper knob, all speeds worked.

Flight notes (If required): No notes, just tested wipers then moved on.

Issues (If Any):
Overall Rating: Good
Conclusions of the testing: Great work pepperoni! This works like a charm, keep it up!

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919
Date of testing: 12/8/2020
Version of the sim: 1.11.7.0
PR Tested: #2243 
Object of test: Windshield wipers.
Testing technique: Tried out.
Steps you've made to test the Pull Request:

1. Spawned in C&D at kdca while raining.
2. Turned on both wipers at different speeds to make sure they would not both go to the same speed.
3. Tried with one wiper on and one-off on both sides.
4. Repeated testing above while looking outside at the exterior model.

Flight notes (If required):

Issues (If Any):
Overall Rating: Good
Conclusions of the testing: Pr looks good tested it the same way I did yesterday. I say this pr is epic and should be merged.

**Pull request merged**
