### PR TITLE
fix(pf): replace dh/mda with radio/baro

### PR DESCRIPTION
**Pull request by tracernz**
## Summary of Changes

Change MDA and DH on FMA to BARO and RADIO per EIS2. Follow-up on #3643.
## Screenshots (if necessary)

pfd-baro
pfd-radio

## References

image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Setup ILS approach in F-PLN, and set BARO, check PFD, then set RADIO and check PFD.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by pepperoni505 — APPROVED** [review]
LGTM

**Comment by darkfury334** [comment]
Category: QA Trial
Name: DarkFury#4936
Date of testing: Current date 28/03/2021
Version of the sim: 1.14.6.0
PR Tested: #4166
Tier of testing: 1
Change MDA and DH on FMA to BARO and RADIO

Testing technique: insert and check (try)
Steps you've made to test the Pull Request:
1. spawned on rwy at EGLL
2. took off heading south for ILS rwy 08R
3. Configured for ILS approach
4. Entered different values in radio /baro then checked pfd
5. Landed

Flight notes (When done a full flight): EGLL DCT TIMBA KONA2G EGKK/08R
Media: Insert screenshots, recordings, or anything relevant to the review here.
Microsoft Flight Simulator Screenshot 2021 03 28 - 10 52 27 82
Microsoft Flight Simulator Screenshot 2021 03 28 - 10 54 17 06
Microsoft Flight Simulator Screenshot 2021 03 28 - 10 55 20 54

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: It does work. Can input different values into Baro/Radio and will show correctly on PFD. Im unsure about he reference picture of the CAT 3 dual with Baro I could not get as soon as I had LOC with a value in Baro it would come up as CAT 3 Single.

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 28.3.2021
Version of the sim: 1.14.6.0
PR Tested: #2545
Tier of testing: 1
Changes to observe: PERF/W&B and fuel prediction page inputs
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned on runway at EDDP
2.) Took off to land again on EDDP ILS08R
3.) Entered Baro
4.) Looked at PFD for Baro at Landing (Image1)
5.) Spawned on runway at EDDP
6.) Took off to land again on EDDP ILS08R
7.) Entered Radio
8.) Looked at PFD for Radio at Landing (Image2)

Media:


Image1


Image2

Issues: -

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 28/03/2021
Version of the sim: 1.14.6.0
PR Tested: #4166
Tier of testing: 1
Changes to observe: Changed MDA/DH to Baro/Radio

Testing technique: Full flight Helsinki to Berlin Brandenburg

Steps you've made to test the Pull Request:
1. Spawned Cold and Dark at EFHK and configured MCDU for full flight to Berlin
2. During cruise, amended Radio and Baro decision heights
3. Checked PFD on approach to ensure they displayed as they should
4. Landed with ILS approach runway 25R

Flight notes (When done a full flight): No issues found - it triggered when entering into Descent Phase automatically

Media: Livestreamed the test here
https://youtu.be/13c5QBhmxKY

image


Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: No issues, obviously already merged into Master but I've been testing it so wanted to add the report nevertheless!

**Pull request merged**
