### PR TITLE
fix: rudder trim text position

### PR DESCRIPTION
**Pull request by Snapmatics**
## Summary of Changes
The following PR fixes the position for the Rudder Trim display.
##  Rudder Trim
image

Discord Username: `Snapmatics#0001`

## Testing Instructions

- Turn ON external power
- Check if the Rudder Trim text position is fixed

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by ko-zone — APPROVED** [review]
LGTM

**Review by pepperoni505 — CHANGES_REQUESTED** [review]
If it's possible, can you use an .SVG instead of a .PNG

**Comment by ExampleWasTaken** [comment]
Category: QA Trial
Name: ExampleWasTaken#0886
Date of testing: 9/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3448
Tier of testing: 1
Changes to observe:
fix: chronometer and rudder trim text position + backlight

Testing technique: 
Steps you've made to test the Pull Request:
1. Loaded C&D at night
2. Powered up
3. Turned main panel integrated lights on
4. Checked chronometer and rudder display
5. Changed time to day
6. Turned off integrated lights 
7. Checked chronometer and rudder display

Flight notes (When done a full flight): N/A

Media: 
Microsoft Flight Simulator Screenshot 2021 02 09 - 22 13 13 22
Desktop Screenshot 2021 02 09 - 22 36 02 17
Desktop Screenshot 2021 02 09 - 22 23 43 03
Desktop Screenshot 2021 02 09 - 22 36 52 01


Issues (If Any): N/A


Overall Rating: Good
Conclusions of the testing: Works as described

**Comment by cianwhite** [comment]
Category: QA Tester
Name: Cian#3596
Date of testing: 09/02/21
Version of the sim: 1.12.13.0
PR Tested: #3448 
Tier of testing: 1/2/3
Changes to observe:
(Insert the Summary of changes, in order to remind what is to test)

Testing technique: Started on the runway at KJFK
Steps you've made to test the Pull Request:
1. Started on runway 04R at KJFK
2. Observed rudder trim changes at day
3. Observed chrono changes at day
4. Observed rudder trim changes at night
5. Observed chrono changes at night

Flight notes (When done a full flight): N/A

Media: 
Screenshot_1
Screenshot_3
Screenshot_6
Screenshot_2





Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: Lighting changes work as outlined. LGTM

**Comment by starvingjavi** [comment]
Category: QA Tester
Name: Javi#2557
Date of testing: 11/02/21
Version of the sim: 1.12.13.0
PR Tested: #3448
Tier of testing: 1
Changes to observe: Changes to the numbers in Chrono and Rudder Trim, lighting and position

Testing technique: Started on gate on MMAA and changed lighting conditions
Steps you've made to test the Pull Request:

1. Started on ramp in MMAA
2. Start airplane to get electrical power
3. Check lighting on chronometer numbers during day and night
4. Check lighting and position of rudder trim numbers during day and night

Flight notes (When done a full flight): N/A

Media:
Captura de pantalla 2021-02-11 102511
Captura de pantalla 2021-02-11 102544
Captura de pantalla 2021-02-11 102615
Captura de pantalla 2021-02-11 102636

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: LGTM

**Comment by theflyingexpert** [comment]
Category: QA Tester/Trial
Name: Discord User #5118
Date of testing: Current date 07/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3448
Tier of testing: 1
Changes to observe: Lighting changes in Chrono and Rudder Trim

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:

1. Started A32NX cold & dark (daytime)
2. Turned external power ON
3. Checked chronometer text position
4. Checked rudder trim text position
5. Set night time
6. Checked chronometer backlight

Flight notes (When done a full flight): -

Media:

image
image
image
image

Issues (If Any): Write any issues
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: -

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 12/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3448 
Tier of testing: 1
Changes to observe: chronometer & rudder trim text position & backlight

Testing technique: Look-at
Steps you've made to test the Pull Request:
1. Spawned in C&D and powered up the aircraft
2. Looked at chronometer & rudder trim in the day
3. Looked at chronometer & rudder trim in the night with backlight


Media: 
Capture d’écran (410)
Capture d’écran (407)
Capture d’écran (408)
Capture d’écran (409)





Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: LGTM 👍

**Comment by bbelliot** [comment]
Category: QA Trial
Name: Elliot#7195
Date of testing: Current date DD/MM/YYYY
Version of the sim: 1.12.13.0
PR Tested: #3448
Tier of testing: 1
Changes to observe: Changed Chrono and Rudder positions and backlights

Testing technique: Look at
Steps you've made to test the Pull Request:
1. Loaded onto a gate cold and dark - Night time on a dark stand
2. Checked the backlight on the chronometer after turning batt & external power one
3. Compared new positioning to old positioning
4. Changed time to day
5. Checked backlight still visible 

Flight notes (When done a full flight): N/A

Media: 
download (10)
download (11)
download (12)

Issues (If Any): None to note
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: Ready to be merged to master

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested:  #3448
Tier of testing: 1
Changes to observe: Position of trim and chronometer values. LCD style backlight.
Testing technique: Tryout

Steps you've made to test the Pull Request:

1.) Spawn at day C&D EDDP
2.) Without power trim and chrono display (backlights) are not turning on.
3.) Turned on Bat. This turns on both displays. Backlight barely visible (good).
4.) Set time to night. Backlight becomes more visible (Image1, Image2).

Media:


Image1


Image2

Issues (If Any): None

Overall Rating: Good

Conclusions of the testing: Nice backlight, value positions fits the displays.

Hope this helps :-)

**Comment by pepperoni505** [comment]
Holding back on merging until you switch to an .svg

**Comment by Snapmatics** [comment]
> 
> 
> Holding back on merging until you switch to an .svg

Roger, you are also free to convert it to a draft PR until I switch it over to a .svg.

**Comment by Snapmatics** [comment]
> 
> 
> Holding back on merging until you switch to an .svg

I was told that the 3 dots that the backlight has are not visible for pilots but only via cameras. I will be deleting it, and I will keep the fix for the Rudder Trim position text.

**Comment by Snapmatics** [comment]
> 
> 
> > Holding back on merging until you switch to an .svg
> 
> I was told that the 3 dots that the backlight has are not visible for pilots but only via a camera. I will be deleting it, and I will keep the fix for the Rudder Trim position text. + The text's positioning for the chronometer has slightly been improved by Tyler by adding the new font (good job by him). 👍

Whenever you feel this PR is ready, you can open it and merge it (if tested).

**Review by pepperoni505 — APPROVED** [review]
LGTM

**Comment by pepperoni505** [comment]
I'd like to get one more QA test in before we merge

**Comment by Snapmatics** [comment]
> I'd like to get one more QA test in before we merge

Roger, thanks for reviewing again. 🤝

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 15.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3448
Tier of testing: 1
Changes to observe: Rud Trim digit position
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power
3.) Looked at Rud Trim display (Image1)
4.) Did ANN LT Test (Image2)


Media:


Image1


Image2

Issues: ANN LT Test not working

Overall Rating: -

Conclusions of the testing: Digits are aligned in the center. If ANN LT is part of this PR please fix.

Hope this helps :-)

**Comment by Snapmatics** [comment]
> 
> 
> Name: marcman86#4907
> Date of testing: 15.2.2021
> Version of the sim: 1.12.13.0
> PR Tested: #3448
> Tier of testing: 1
> Changes to observe: Rud Trim digit position
> Testing technique: Tryout
> 
> Steps made to test the Pull Request:
> 
> 1.) Spawned C&D at EDDP
> 2.) Turned on bat. and ext. power
> 3.) Looked at Rud Trim display (Image1)
> 4.) Did ANN LT Test (Image2)
> 
> Media:
> 
> 
> Image1
> 
> 
> Image2
> 
> Issues: ANN LT Test not working
> 
> Overall Rating: -
> 
> Conclusions of the testing: Digits are aligned in the center. If ANN LT is part of this PR please fix.
> 
> Hope this helps :-)

Blocked Merge!

**Comment by Benjozork** [comment]
@Snapmatics is this still being worked on?

**Comment by Snapmatics** [comment]
> @Snapmatics is this still being worked on?

Yeah it will be pushed together with interior. Just keeping it in another PR.

**Comment by MisterChocker** [comment]
How is the relation of this pr to https://github.com/flybywiresim/a32nx/pull/3794/?

**Comment by MisterChocker** [comment]
#3794 has been merged.

**Pull request closed without merging**
