### PR TITLE
fix(core:speeds): Vls computation during Take Off

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Take Off Vls table is now only used while in initial take off configuration.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

During Take Off, after transitioning into climb phase, the Vls indication on the PFD should no longer "jump up".

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by beheh — APPROVED** [review]
LGTM

**Comment by donstim** [comment]
Is it possible to incorporate some other changes to the speed tape behavior in this pr, or should any other changes go into another pr?  What I am think of are:
1) According to the FCOM, "VLS information is inhibited from touchdown until 10 s after liftoff." (page 1663 of the FCOM PDF file we have)  We have it appearing much sooner. Can you guys verify if this is correct and adjust if necessary?

2) I think we may have a really minor issue with the CONF 3 VLS for takeoff. The VLS speeds and takeoff speeds were done at different time, and I must have missed checking them against one another. VLS should never be less than V2 (for obvious reasons), and for weights of 65T and above, they are by a knot or two. Not a big deal, and you may not be able to tell on on the small PFD, but can the VLS speeds be reduced to be equal to the V2 speeds for these weights? My mistake.

3) It looks like the takeoff VLS's are incorrectly being used for CONF 2 and 1+F after a CONF 3 takeoff and for CONF 1+F after a CONF 2 takeoff. When flaps are retracted 1 step from the takeoff setting, VLS=1.23 VS (the "in-flight" value), not 1.13 VS (the "takeoff" value should be used.  The takeoff value should only be used for the CONF at which the takeoff is being conducted.  (VLS also incorrectly goes to the takeoff value if you try to do an immediate return landing, where, for example, you clean up, then extend the flaps again for landing before reaching the acceleration height. (Probably not a realistic scenario, but again the "in-flight" values should always be used except during takeoff and only for that takeoff config.  (Maybe need to use an on-ground vs in-air variable?)

**Comment by MisterChocker** [comment]
> 1. According to the FCOM, "VLS information is inhibited from touchdown until 10 s after liftoff." (page 1663 of the FCOM PDF file we have)  We have it appearing much sooner. Can you guys verify if this is correct and adjust if necessary?

This is already implemented in the PFD rework.

> 2\. I think we may have a really minor issue with the CONF 3 VLS for takeoff. The VLS speeds and takeoff speeds were done at different time, and I must have missed checking them against one another. VLS should never be less than V2 (for obvious reasons), and for weights of 65T and above, they are by a knot or two. Not a big deal, and you may not be able to tell on on the small PFD, but can the VLS speeds be reduced to be equal to the V2 speeds for these weights? My mistake.

Yes this can be implemented easily. Can you tell me where it is in our Docs, so I can look it up and make a pr?

> 3\. It looks like the takeoff VLS's are incorrectly being used for CONF 2 and 1+F after a CONF 3 takeoff and for CONF 1+F after a CONF 2 takeoff. When flaps are retracted 1 step from the takeoff setting, VLS=1.23 VS (the "in-flight" value), not 1.13 VS (the "takeoff" value should be used.  The takeoff value should only be used for the CONF at which the takeoff is being conducted.  (VLS also incorrectly goes to the takeoff value if you try to do an immediate return landing, where, for example, you clean up, then extend the flaps again for landing before reaching the acceleration height. (Probably not a realistic scenario, but again the "in-flight" values should always be used except during takeoff and only for that takeoff config.  (Maybe need to use an on-ground vs in-air variable?)

This is also a good catch, I can implement this as well.

**Comment by donstim** [comment]
> 
> Yes this can be implemented easily. Can you tell me where it is in our Docs, so I can look it up and make a pr?

The takeoff speeds are shown near the bottom of this issue: https://github.com/flybywiresim/a32nx/issues/1777

**Comment by MisterChocker** [comment]
> > Yes this can be implemented easily. Can you tell me where it is in our Docs, so I can look it up and make a pr?
> 
> The takeoff speeds are shown near the bottom of this issue: #1777

I meant the rules on when to check for Vls < V2. Or this always applied (I assume yes).

**Comment by donstim** [comment]
> > > Yes this can be implemented easily. Can you tell me where it is in our Docs, so I can look it up and make a pr?
> > 
> > 
> > The takeoff speeds are shown near the bottom of this issue: #1777
> 
> I meant the rules on when to check for Vls < V2. Or this always applied (I assume it is).

Don't know what you mean by "rules" in our docs on when to check for this condition.  Yes, it should always be applied. you simply cannot have an operating speed that would be less than VLS. Once we have realistic autothrust, you would never be able to target V2 if it is less than VLS.

VLS is 1.13 Vs1g as shown on page 330 of the FCOM PDF file. V2 must be at least 1.13 Vs1g as shown on page 343 of that file.  (V2 will be higher where V2 is limited by VMU/VMCA. Since we don't have a definitive plot of Vs1g for the NEO, I used 2 different methods to estimate it since my V2 and VLS calcs were done at 2 different times.  The speeds are within 1-3 knots depending on the method used.

**Comment by MisterChocker** [comment]
> VLS is 1.13 Vs1g as shown on page 330 of the FCOM PDF file. V2 must be at least 1.13 Vs1g as shown on page 343 of that file. (V2 will be higher where V2 is limited by VMU/VMCA.) Since we don't have a definitive plot of Vs1g for the NEO, I used 2 different methods to estimate it since my V2 and VLS calcs were done at 2 different times. The speeds are within 1-3 knots depending on the method used.

Well this sounds like something for @beheh to be intercorporate into the take off page or ecam (I know there is a check for TO SPEEDS TO LOW).
But that has nothing todo with what's being displayed on the PFD.

**Comment by donstim** [comment]
> > VLS is 1.13 Vs1g as shown on page 330 of the FCOM PDF file. V2 must be at least 1.13 Vs1g as shown on page 343 of that file. (V2 will be higher where V2 is limited by VMU/VMCA.) Since we don't have a definitive plot of Vs1g for the NEO, I used 2 different methods to estimate it since my V2 and VLS calcs were done at 2 different times. The speeds are within 1-3 knots depending on the method used.
> 
> Well this sounds like something for @beheh to intercorporate into the take off page or ecam (I know there is a check for TO SPEEDS TO LOW).
> But that has nothing todo with what's being displayed on the PFD.
> 
> I have improved the recognition on when to use the Take Off Vls table and when now to. (Solves donstims points 1. and 3.)
> 
> Point 2. is out of scope of this pr.

I don't understand this response. It is not a check that needs to be made anywhere. It is an error in the VLS speed table we are using for CONF 3 for takeoff. It needs to be changed to be consistent with the V2 speeds were are using for CONF 3.

**Comment by MisterChocker** [comment]
https://github.com/flybywiresim/a32nx/pull/3291 takes care of the config 3 TO Vls.

**Comment by cianwhite** [comment]
Category: QA Tester
Name: Cian#3596
Date of testing: 05/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3287 
Tier of testing: 1/2/3
Changes to observe: VLS not jumping up on take off
(Insert the Summary of changes, in order to remind what is to test)

Testing technique: Started on the runway at EGLL and observed VLS on take-off
Steps you've made to test the Pull Request:
1. Start on the runway at EGLL, program MCDU for take-off and enter V1/V2/VR speeds
2. Observed the VLS on transition to the climb phase not jumping


Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Speed no longer jumps up from take-off to initial climb transition. LGTM

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 7/2/21
Version of the sim: 1.12.13.0
PR Tested: #3287 
Tier of testing: 1/2/3
Changes to observe:
VLS speed

Testing technique: Did a few take offs
Steps you've made to test the Pull Request:
1. Loaded in cold and dark
2. Took off
3. Loaded in on the runway
4.Took off

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: VLS speed smoothly rises after flaps are retracted as expected. LGTM

**Comment by stescouse** [comment]
Category: QA Tester
Name: stescouse#7271
Date of testing: 8/2/21
Version of the sim: 1.12.13.0
PR Tested: #3287
Tier of testing: 1/2/3
Changes to observe: VLS speed

Testing technique: TryOut Took off 3 times from MUHA
Steps you've made to test the Pull Request:

1. Spawned C&D at MUHA 
2. Programmed the MCDU for takeoff and V speeds.
3. Took off and observed no jumping in transition to Climb from VLS.


Flight notes (If required: none

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: VLS performed as outlined in PR.

**Pull request merged**
