### PR TITLE
refactor(fcu): rewrite using react

### LINKED ISSUE #2918: [BUG] V/S and FPA do not override altitude hold
**Mod Version**

{
  "built": "2021-01-06T07:07:41+00:00",
  "ref": "",
  "sha": "",
  "actor": "devsnek <me@gus.host>",
  "event_name": "manual"
}

**Describe the bug**

Pulling the V/S button should override altitude hold and trigger a descent or climb even if the plane is at the FCU altitude.

**To Reproduce**

1. Use the autopilot to maintain an altitude of 5000'.
2. Turn the V/S FPA button to select a vertical speed of -1000fpm.
3. Pull the V/S button.
4. Watch the aircraft maintain its altitude and the digits in V/S window become dashes.

**Expected behavior**

The autopilot should command a descent with a vertical speed of -1000fpm.

**Actual behavior**

The aircraft maintains altitude.

**References**

https://youtu.be/_zs9x_hfXjY?t=1083
https://youtu.be/1IhzbfB-8pI?t=359

**Additional context**

Pulling the V/S FPA button should override FCU altitude. When doing non-precision approaches, you would arrive a given altitude, say 4.000'. On final track you would select the missed approach altitude of 5000' and at the descent point you would initiate a descent with a given FPA, say 3.0 degrees. In current state, the airplane will maintain 4.000' and not descent.

Was this working before/when did the issue start occurring?
I do not know.

Is this a problem in the vanilla unmodded game?
Yes, but differently. The vanilla version does not even allow a V/S speed to be selected when in level flight.

Discord username (if different from GitHub): froemmelm

### PR DESCRIPTION
**Pull request by theomessin**
Fixes #2918

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by theomessin** [comment]
Check out the Speed and Heading accelerated push pull knobs working using just the React code 😄 
https://streamable.com/o61na9

**Comment by MisterChocker** [comment]
One rotation for the Speed knob is 32 knots or mach 0.32
image

**Comment by theomessin** [comment]
@MisterChocker not sure whether it's a good idea to simulate this. In real life you can spin the knob very very quickly. If we stuck to this without acceleration it would be very difficult to set the value you want (see the way the heading knob works in TRACK mode in  `master` - similar to #2002)

**Comment by MisterChocker** [comment]
This should happen after autopilot integration

**Comment by MisterChocker** [comment]
Since ap is now on master, I don't see any technical issues holding this back.
Please communicate with @aguther to ensure compatibility and functionality through the process.

**Pull request closed without merging**
