### PR TITLE
build: update to igniter 1.2.0 and limit worker count to 4 on GitHub Actions

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

This is an attempt to reduce memory load, particularly during `instruments` build on GitHub Actions.

There have been many failed workflows recently, both on production builds and PR QA builds. Local testing that some instrument builds can balloon up to 2GB of memory usage at times. I initially suspected a leak in `rollup-plugin-msfs`, but tests without it showed the same memory consumption.

This patch effectively limits igniter to 4 workers in GitHub Actions. Local users are not affected.

Discord username (if different from GitHub): someperson#4953

## Testing instructions

* Make sure plane still works, avionics and systems load

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
Seems like this also improves the CI build time 😉

**Review by ZigTag — APPROVED** [review]
LGTM

**Comment by SkylarHutter** [comment]
Checks out on my side, seems fine!

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5342 
Tier of Testing: 1
Date: 18/07/2021

**Testing Process:**
1. Loaded C&D
2. Full Normal procedure up to takeoff, tried to use a lot of functionalities
3. One traffic pattern
4. Landing and shutdown

**Negatives:** N/A
**Testing Results:** Passed

**Pull request merged**
