### PR TITLE
fix: disable tiller plate emissive

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

- Disables left steering tiller emissive since the tiller deflection plate should not be illuminated.

## Screenshots (if necessary)
BEFORE:
image

AFTER:
afterpudhe

## References
The Tiller plate is not backlit as confirmed by IRL A320 pilots.

## Additional context

Discord username: Imenes#8739

## Testing instructions

Tier 1. Make sure that the left steering tiller deflection plate is not illuminated. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by tyler58546 — APPROVED** [review]
LGTM

**Comment by ErickSharp** [comment]
Category: QA Tester
Name: Erick [Z-6]#6484
Date of testing: 26/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3188 
Tier of testing: 1
Changes to observe: Changes to emissive texture of tiller 

Testing technique: Loaded in at Madeira on the runway and checked to see if the texture was emissive. 
Steps you've made to test the Pull Request:
1. Loaded in at Madeira on the runway and checked to see if the tiller had emissive light.


Flight notes (When done a full flight): None

Media: 
Screenshot 2021-01-26 030707


Issues (If Any): None
Steps to achieve the issue: None

Overall Rating: Good
Conclusions of the testing: Juicer PR that solves the issue of the tiller being emissive. Good work!

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 26.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3188 
Tier of testing: 1
Changes to observe: Tiller plate emissive disabled

Testing technique: Tryout
Steps you've made to test the Pull Request:

1. Spawned C/D at gates, turned on batteries and external power.
2. Turned on dome lights, integrated panel lights.
3. Checked emissive tex disabled on tiller plate
4. Repeated same steps after restarting and spawning on runway.
5. Checked the texture again.

Media:
image


Issues (If Any): None.
Conclusions of the testing: Emissive texture on the tiller plate is disabled as seen on the screenshot. Good to go

**Comment by stescouse** [comment]
Category: QA Tester
Name: stescouse#7271
Date of testing: 26.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3188
Tier of testing: 1
Changes to observe: disable tiller plate emissive

Testing technique: TryOut
Steps you've made to test the Pull Request:

1. Spawned C&D at SKBO checked Tiller was unlit.  Started up plane ready for taxi.

tiller 1

2. Spawned on runway at SKBO checked Tiller was unilt.

tiller 2


Flight notes (If required: none

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: Tiller remained unlit as outlined in PR good work.

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 26.1.2121
Version of the sim:1.12.13
PR Tested: #3188
Tier of testing: 1
Changes to observe:
tiller plate emissive

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. spawned at gtae and runway 
2. checked if the Tiller plate emissive is disabled




Issues (If Any): none


Overall Rating: Good
Works as expected! Thanks for the PR!

**Pull request merged**
