### PR TITLE
[CDU] Cleanup

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Removed duplicate code
- Removed unused code
- Created NXConstants
- Created NXFunctions
- Fixed some errors
- Simplified some code
- ~~Eventually refactor/rebase the files~~ won't do caused some issues

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Ensure that everything works as intended or the same way as before.
To give some examples:
- Check that mcdu inputs and messages work
- Check for flight phase changes,
- Check for AP
- Check for AT

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 31/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2788
Object of test: [CDU] Cleanup, Check for normal functions
Testing technique: Spawn C/D at gates, normal startup

Steps you've made to test the Pull Request:
1. Spawned at VOBL C/D
2. Turned on battery, external power.
3. Setup cockpit lights, display brightness
4. Tried filling INIT page. Unable to input anything
5. Respawned at runway. Same issue


Issues (If Any): MCDU Inputs not working
Overall Rating: Needs improvement
Conclusions of the testing: The MCDU was not taking any inputs, neither was it displaying anything on the display while being typed.

**Comment by MisterChocker** [comment]
will check on that

**Comment by MisterChocker** [comment]
@sidnov Works now, I must have unintentionally reverted some changes ^^

**Comment by sidnov** [comment]
> @sidnov Works now, I must have unintentionally reverted some changes ^^

Will test and update the review in a few hours from now!

**Comment by ErickSharp** [comment]
Category: QA Tester
Name: Erick [Z-5]#6484
Date of testing: 1/1/2020
Version of the sim: 1.12.13.0
PR Tested: #2788
Object of test: (ECAM Page or Flight model or views or anything, what the PR modifies)

Testing technique: Loaded in at LGSM, and tested the PR in both a cold and dark state and spawned in at the runway.
Steps you've made to test the Pull Request:
1.Loaded in cold and dark, and made cockpit preparations such as turning on APU and adjusting cockpit lighting. 
2. Go through inputting data into MCDU as normal.
3. Request weather from AOC menu.
4. Takeoff and do circuits around the airport, verifying that flight mode changes.
5. Adjust speeds through autopilot control panel.
6. Go back to main menu and select a runway spawn. Follow same steps done after previous cold and dark setup.

Flight notes (If required):None
Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: The systems in this PR maintain their original functionality and no noticeable negative effects were found. Overall, the changes made by the PR were unnoticeable and as such seem like they are good to go!

**Comment by sidnov** [comment]
There seems to be an issue with following STAR into airports. Doing some more tests with updated artifacts.

**Comment by MisterChocker** [comment]
> There seems to be an issue with following STAR into airports. Doing some more tests with updated artifacts.

Like this or the linked issues to that? https://github.com/flybywiresim/a32nx/issues/939

**Comment by sidnov** [comment]
> > There seems to be an issue with following STAR into airports. Doing some more tests with updated artifacts.
> 
> Like this or the linked issues to that? #939

Same as these.

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
