### PR TITLE
Increase types.d.ts coverage

### PR DESCRIPTION
**Pull request by davidwalschots**
## Summary of Changes

I'm creating this draft PR to indicate to everyone that I'm working on increasing the available type information in the project. As this is quite a tedious task, I thought it would be good to let everybody know before someone else picks this up as well :D.

- [x] Avionics.js
- [x] buttons.js
- [x] coherent.js
- [x] common.js
- [x] dataStorage.js
- [x] debug.js
- [x] Flight.js
- [x] Inputs.js
- [x] JavaScript.js
- [x] NetBingMap.js
- [x] SimPlane.js
- [x] simvar.js
- [x] slider.js
- [x] SortedList.js
- [x] TestSimVar.js
- [x] Types.js
- [x] WasmSimCanvas.js
- [x] widgetsContainer.js
- [x] Scour files for customElements.define to declare Document.createElement types.
- [ ] Finalize PR.

Services and libs directory ignored for now.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
Could we possibly split this into multiple files ?

**Comment by davidwalschots** [comment]
Definitely! I'll make sure to do that before marking the PR as ready for review.

**Comment by davidwalschots** [comment]
@Benjozork Could we maybe consider creating a separate project for the type definitions and publishing them as npm packages? That way this work is reusable for other projects and can be maintained by more people.

**Comment by lars-reimann** [comment]
Would this be something that could go to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)? I guess not since their [contribution guide](http://definitelytyped.org/guides/contributing.html) states this:

> We do not support exposing undocumented internal implementation details of libraries in .d.ts files. We follow this more strictly for popular libraries with good documentation e.g. jquery, angular, node etc.

But maybe someone knows for sure.

**Comment by davidwalschots** [comment]
@lars-reimann I'm sure it's not possible to move it to DT for the reason you stated.

**Comment by lars-reimann** [comment]
I was mainly asking because there are declaration files for some payware products, like [this one](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/accedo__accedo-one/index.d.ts) that seemingly have no public documentation. But the statement is, of course, pretty explicit.

**Comment by Benjozork** [comment]
> @Benjozork Could we maybe consider creating a separate project for the type definitions and publishing them as npm packages? That way this work is reusable for other projects and can be maintained by more people.

Yes, I'll see if I can create a separate repo after this is merged.

**Pull request closed without merging**
