### PR TITLE
Engine sound reworks, and others such as packs

### PR DESCRIPTION
**Pull request by hotshotp**
## Summary of Changes

This is a huge PR that will make a lot of changes. I will outline the engine sound changes first:

- [x] Make the engine sounds come from the engine nodes and not center
- [x] Rework engine startup sounds
- [x] Rework engine spool up sounds
- [x] Replace all the samples for whines and buzzsaw
- [x] Make engine sounds fade out with speed
- [x] Add new rumble

Other changes:

- [x] Make packs play with the correct simvar (so it plays during flight)
- [x] Improve gear clunk and sound
- [x] Make cabin wind sound pitch change depending on slat position
- [x] Change every main gear touchdown sound

This is a draft, but anyone who wants to test it out, they can download and build it, not too many bugs as of now.

## References

I used youtube videos as reference for engine sounds and real engineer references for things like packs.

## Additional context

Discord username (if different from GitHub):

Boris#9134

## Testing instructions

Startup engine, listen on interior (exterior did not change)
Taxi, takeoff, cruise, descend, and last, and listen to engines on interior (exterior did not change)
Listen to pack sounds after starting one engine (the packs turn on after one engine is started even with mode selector in ignition) - packs will last the whole time in flight.
Put gear up and listen to new clunk and whine
Touch down and listen to the sound of the touchdown
Go to cabin and extend the flaps all the way and listen to the sound, then retract.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by pepperoni505 — APPROVED** [review]

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: ChristopherXie#3904
Date of testing: Current date 01/22/2021
Version of the sim: 1.12.13.0
PR Tested: #3124 and during draft phase 
Object of test: Sounds of the aircraft

Testing technique: Takeoffs and landings, full flights
Steps you've made to test the Pull Request:
1. Did takeoffs and landings at CYYZ runway 23 to test:
-  spool up
-  whine and buzzsaw
-  rumble
-  engine volume fading with speed
-  gear clunks 
-  touchdown sounds
-  wind pitch with flap and slat positions
2. Completed a full flight from KPHL - CYYZ, where on takeoffs and landings I reviewed with Hotshotp/Boris on a VC. In this flight I tested the new startup sounds, ensuring that the pack sounds were played at the correct moments, and that the sounds were coming from the engine nodes. 

Flight notes (If required):

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Everything sounds substantially better, mixing is a lot better and quality of the sounds is clearer. No sound artifacting nor pops were heard during my testing. Great work Boris!

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 22.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3124 
Tier of testing: 2
Changes to observe: Various new Sound Improvements


Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned at LSPMP
2. checked engine startup
2. Checked Nodes with Drone outside
3. Checked packs (Packs off, APU Bleed etc.)
4. took off
5. checked gear sound (very noice and crispy)
6. checked flaps wind sounds inflight
7. changing engine sounds with different speeds, noticed
8. checked flaps on approach again
9. touchdown sounds, checked and good
10. shutdown sound, again very nice

Flight notes (When done a full flight):
All went as expected


Issues (If Any): None
Steps to achieve the issue

Overall Rating: Very Good
Conclusions of the testing: Very nice improvement, you can hear the upgrade in quality, especially the engines. Found an for me unusual hissing in the cockpit but its confirmed to be normal by boris

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 22/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3124 
Tier of testing: 2
Changes to observe: Sounds

Testing technique: "Rapid" flight
Steps you've made to test the Pull Request:
1. Spawned in C&D at LFRS
2. Started up the airplane, Listened to the engine starting
3. Did some spool ups on the rwy
4. Climbed to FL310
5. Descended and landed at the same airport

Flight notes :
These are very good sounds 

Media: [https://youtu.be/LyqvN9VOjcs](url)   (might be innacessible the first minutes, YouTube is slow atm)

Issues (If Any): Flaps sounds almost inaudible from the right side of the cabin, but it doesn't seem to be in the subject of this exact PR
Steps to achieve the issue: Retract and/or extend flaps while being on the right view of the cabin

Overall Rating: Good
Conclusions of the testing: These are really helping bringing the A32NX even closer to reality, and the flaps sounds sounds much better to me.

**Comment by hotshotp** [comment]
> Issues (If Any): Flaps sounds almost inaudible from the right side of the cabin, but it doesn't seem to be in the subject of this exact PR
> Steps to achieve the issue: Retract and/or extend flaps while being on the right view of the cabin


will fix in my next PR!

**Comment by stescouse** [comment]
Category: QA Tester
Name: Discord User stescouse#7271
Date of testing: 22.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3124
Tier of testing: 2
Changes to observe: Various new Sound Improvements

Testing technique: TryOut
Steps you've made to test the Pull Request:

1. Spawned C&D at EDDF
2. Checked APU start up from back of plane deeper richer sound.
3. Checked APU bleed inside and out of plane noticeable difference.
4. Checked Packs on and off within cabin clear difference in sound.
5. Checked engine start up inside and out.
6  Checked flaps from camera 12 on Showcase sound noticeable, great.
7. Checked 250 and 290 speeds below and above FL100 noticeable difference.
8. Tested sound on speed break descent on camera 12 window, noticeably louder.
9. Checked sound on landing and reverse thrust, sound defiantly louder.
10. Retracted full flaps on landing full stop good sound from camera 12.
11. Shut down engines sound good inside and out.  

Flight notes (If required: Full flight from EDDF to LFPG.

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: Great improvement, sounds are fuller and add more to realism.  Great work.

**Pull request merged**
