### PR TITLE
cleanup: cdu/fms code

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Removed unused code.

## Additional context

This is the beginning 

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Perform normal flights, check for bugs or anything unusual (if not already known)

Looking from a developer point of view, these are symptoms to look for:
- Altitude misbehavior during climb
- Speed misbehavior during climb
- Speed misbehavior during cruise
- TOD misbehavior

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by tracernz** [comment]
Maybe also https://github.com/flybywiresim/a32nx/blob/1d53c836a41940838d9649f75686ef76f98ebdcb/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L1620-L1633

Called here
https://github.com/flybywiresim/a32nx/blob/1d53c836a41940838d9649f75686ef76f98ebdcb/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L3260
but I think that should call getManagedApproachSpeedMcdu if still needed.

**Comment by tracernz** [comment]
This should call getPerfGreenDotSpeed if still needed:
https://github.com/flybywiresim/a32nx/blob/1d53c836a41940838d9649f75686ef76f98ebdcb/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L1636

Which would then get rid of this old calc: 
https://github.com/flybywiresim/a32nx/blob/1d53c836a41940838d9649f75686ef76f98ebdcb/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L1613-L1618

**Comment by MisterChocker** [comment]
@tracernz Yes, there is a lot of code like ~1000 lines left to remove and a couple of hundred to refactor. But I am doing this step by step in smaller chunks.

This pr removes code marked as unused only.

**Comment by tracernz** [comment]
No worries. I had noticed the above while chasing down the approach speed code we discussed last week.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 17.1.2021
Version of the sim: 1.12.13
PR Tested: #2984
Tier of testing: 3
Changes to observe:
Altitude misbehavior during climb
Speed misbehavior during climb
Speed misbehavior during cruise
TOD misbehavior

Testing technique: Full C&D IFR
Steps you've made to test the Pull Request:
1. Started at gate
2. took off
3. observed for Altitude misbehavior during climb
4.observed for Speed misbehavior during climb
5.observed for Speed misbehavior during cruise
6.TOD misbehavior

Flight notes (When done a full flight): flight from LGRP to LTAI

Issues (If Any): none
Steps to achieve the issue

Overall Rating: Good
Works as expected! Had no issues! Thanks for the PR!

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date DD/MM/YYYY
Version of the sim: 1.12.13.0
PR Tested: #2984 
Tier of testing: 2
Changes to observe:

- Altitude misbehaviour during climb
- Speed misbehaviour during climb
- Speed misbehaviour during cruise
- TOD misbehaviour
- any bugs

Testing technique: Did a whole flight with the pr
Steps you've made to test the Pull Request:
1. Loaded in
2. Flew from LIEO to LGKR 
3. Looked periodically
4.found no issues

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): Write any issues
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: Did a flight and found no issues

**Comment by stescouse** [comment]
Category: QA Tester
Name: Discord User stescouse#7271
Date of testing: Current date 15/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2984
Tier of testing: 3
Object of test: Flights to test cleanup: cdu/fms code

Testing technique: C&D IFR.  TryOut Altitude and speed in takeoff, climb and cruise looking for misbehavior. 

Steps you've made to test the Pull Request:
1. Spawned C&D.
2. After takeoff on reaching FL150 rate of climb stuck on 500 ft per minute.
 
A32NX helsinki test


3. Switched to V/S of 2400 ft per minute and continued climbing towards FL230.


A32NX helsinki test 2


4. Switched back to OP CLIMB and rate of ascent stopped.
 
A32NX helsinki test 3

5. Switched to V/S climb and climbed to FL230.  Switched back to OP CLIMB to FL330 rate of ascent stuck again. and speed started to go down.

6. After applying V/S of 1400 ft per minute and also switching to OP CLIMB Altitude did not climb and speed slowed down towards the green dot.  Tried to increase speed manually with no effect.

A32NX helsinki test 4

7. Engine rev's normal for climb but with no effect on OP CLIMB.

cdu clean up engine speed (2)





Flight notes (If required): Route: -EDDF/36 F360 MARUN9D MARUN Y150 TOLGI DCT OKAGA DCT ALAMI P606 DIVAM DIVAM1W EFHK/33 for all five flights.
Issues (If Any): Loss of speed and unable to climb to required altitude from FL150 onwards either with OP CLIMB or V/S unable to continue flight due to these issues. Center of Gravity and weight were well within limits.

cdu clean up weight and cog




Overall Rating: To be improved
Conclusions of the testing: Sudden loss of speed and climb V/S gave no indication in warnings or on ECAM memo.  Plane performed normally on next four flights with replicated conditions.  There were no issues in cruise or TOD or climb on the four subsequent full flights and I could not replicate this error.

**Comment by MisterChocker** [comment]
@stescouse would have been nice to see the ecam in this scenario as well.
From the one ECAM picture you send I can extract that the THR lever were not at CLB detent, there are ~4% lower than they should've been.
I'd need more information on whats the response from ATHR was at every action you made, with the engine N1s etc.

**Comment by stescouse** [comment]
> @stescouse would have been nice to see the ecam in this scenario as well.
> From the one ECAM picture you send I can extract that the THR lever were not at CLB detent, they are ~4% lower than they should've been.
> This may be the reason that you were unable to reproduce, because on the other flights the thrust lever were put correctly into the CLB detent. (The real airbus throws a master caution if this is the case with 'THR LIM' or something like that to inform the pilot the ATHR range has been manually limited by the physical thrust lever position)
> I'd need more information on whats the response from ATHR was at every action you made, with the engine N1s etc.

@MisterChocker 

Yes I thought of this as the only way to replicate the error, that's why I did the same flight another 4 times to see if the error would replicate, but everything went as normal.  As it didn't I thought it might be my error.   I was sure I would have had the throttle in the correct detent but I may be wrong. 

I was looking at the THR CLM on the top of the PFD so I didn't look at the thrust levers assuming their were on the correct detent after clicking them into place after flex thrust, I know it can be off sometimes without noticing.  I was puzzled at the performance of the plane.  The N1s appeared to be operating normally I didn't take screenshots which I should have.

I was hesitant to submit the report, but thought you should have the feedback anyway just in case as the PR was looking for misbehaviour.  I'm happy to withdraw the report if that would help in light of the 4 other flights being fine, in case it was my error.

**Comment by MisterChocker** [comment]
The thing is the default AP only reacts to thrust and commanded speed.
So if the engine or AT are not providing any thrust, the AP will not increase the pitch to allow for climb/positive vs.

**Comment by mattstertx** [comment]
Category: QA Tester/Trial
Name:  Mattstertx#7410
Date of testing: Current date 18/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2984
Tier of testing: 2
Changes to observe:
Removed unused code.

Testing technique: Full C&D Flight
Steps you've made to test the Pull Request:
1. Spawned C&D at KDFW
2. Took off From KDFW for KIAH
3. Observed Altitude and Speed for misbehavior during climb.
4. Observed for speed misbehavior during cruise.
5. Observed for any TOD misbehavior.

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Works great no unusual speed or altitude issues at all!

**Comment by cianwhite** [comment]
Category: QA Tester
Name: Cian#3596
Date of testing: 19/1/2021
Version of the sim: 1.12.13.0
PR Tested: #2984
Tier of testing: 2
Changes to observe: Testing potential inaccuracies and bugs as a result of removing unused code 

Testing technique: Flight from EIDW - EGLL, and a midair start to test out new code.
Steps you've made to test the Pull Request:

1. Loaded in at EIDW and started as normal
2. Took off and begun a climb to FL310
3. Checked for any bugs along my cruise, climb and descent but couldn’t find any
4. Landed as expected
5. Loaded in mid air on and everything worked fine, I could climb descent and nothing out of the ordinary was experienced.
Flight notes (When done a full flight): DEXEN1A DEXEN DCT NUGRA NUGRA1H (BNN transition)

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Performed a flight and found no issues.

**Review by beheh — APPROVED** [review]

**Comment by MisterChocker** [comment]
@tjburni @FlightSimmer7700 @stescouse @mattstertx @cianwhite
Thanks for testing!

**Pull request merged**
