### PR TITLE
[CDU] Fix athr targeting flap speed on climb

### LINKED ISSUE #565: [BUG] S-speed shouldn't be targeted when climbing with flaps
**Mod Version**
master

**Describe the bug**
When climbing with flaps extended, the S-speed is taken as the overall speed limit, which is incorrect.

**To Reproduce**
See https://youtu.be/Zsk72luNZvc?t=1098

**Expected behavior**
The airplane should keep accelerating (unless there's some alterior speed limit set, but that's unrelated to the S-speed anyway).

**Actual behavior**
The aircraft keeps S-speed until the flaps are retracted.

### LINKED ISSUE #782: SRS and managed speed modes not working correctly.[BUG]
**Mod Version**
Master

**Describe the bug**

Aircraft should maintain v2+10 in SRS mode until Thrust reduction attitude once out of SRS mode and the thrust levers set to the CL detent the aircraft will not accelerate past S speed for min slat retraction even with  MAN TOGA thrust. The airspeed will settle and maintain 160 knots give or take. Also, The managed speed bug should not be at S speed once out of SRS, it should be set to 250 knots if below 10 or set managed cruise climb speed. The only way to make the aircraft accelerate is to retract the slats which almost triggers A. Floor being as it is to low of an airspeed to select FLAPS 0. Once selecting FLAPS 0 the aircraft will then accelerate and maintain an airspeed 10-15 knots lower than what is managed. I.E 250 knots or 320 knots above 10k.

**To Reproduce**

1. takeoff 
2.
3.

**Expected behavior**

The following video is what it should look like. 
https://www.youtube.com/watch?reload=9&v=ECV3IBkzZLc

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):
Please message me on discord if you have any questions and I can better explain this issue Ares#3394

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #565
Fixes #782
Fixes some one part of #422
Fixes some one part of #760

## Summary of Changes

- ATHR now targets climb speed for managed speed mode instead of next flap retraction speed
_ATHR now accelerates past F and S speed marker as it should do_

## Screenshots (if necessary)

image
image
image

## References

https://www.youtube.com/watch?v=gLBlHOEQrIM&feature=youtu.be

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by tareksabet** [comment]
is it ready to test ?

**Comment by MisterChocker** [comment]
Yey, I asked in QA for testing already.

**Comment by tareksabet** [comment]
@MisterChocker can you link this PR also to #422

**Comment by MisterChocker** [comment]
> @MisterChocker can you link this PR also to #422

yes, but this pr will only fix a port of the other issue. I might as well look into the other part of the issue in another pr.

**Comment by tareksabet** [comment]
@MisterChocker also issue #565 same thing I think

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 15/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1944 
Object of test: Testing the speed behaviour on take off after THR RED/ACC ALT

Testing technique: 

Testing multiple scenarios for comparison and consistency - did multiple take offs out of EGKK
- FLX take off
- TOGA take off
- Flap 1 vs Flap 2

The results were consistent and 250 knots managed was the speed target on every occasion.

Flew airbus SOP, pitch climb via SRS orders to THR RED/ACC ALT then pitch down, when positive speed trend on PFD sufficient, reduce to THR CLB and see the speed target go after climb speed (into the barbers pole - but normal)

Also tried a take off with a SID that has a speed constraint - in this case ADMAG2X out of EGKK RWY26L with a max speed round a tight corner of 220 knots and magenta 220 was not the target speed but this is another issue in itself I believe.

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: LGTM. Thanks @MisterChocker for this simple fix. Speed behaviour much better. It was pretty annoying having the aircraft reduce thrust to idle to target F or S speed and sometimes start a descent in the initial departure climb which is not good given prescribed climb gradients for SIDs

**Comment by MisterChocker** [comment]
> Also tried a take off with a SID that has a speed constraint - in this case ADMAG2X out of EGKK RWY26L with a max speed round a tight corner of 220 knots and magenta 220 was not the target speed but this is another issue in itself I believe.

I doubt that was working before. Or implemented at all ^^

**Comment by tareksabet** [comment]
@MisterChocker sorry man I've been annoying this night cz I cleaning GitHub can you also confirm that this PR can be related to 
issue #760

**Comment by MisterChocker** [comment]
> @MisterChocker sorry man I've been annoying this night cz I cleaning GitHub can you also confirm that this PR can be related to
> issue #760 and #782

You are fine. 782 is indeed fixed by this pr. However the thrust mode ´thrust clb´ misbehavior still exists. (ATHR reduces thrust to not exceed target speed, however IRL ATHR provides climb thrust as stated by FMA. I tried to look into it, but looks like I can not fix this issue yet, it might even be impossible to solve without own ATHR software.

**Comment by MisterChocker** [comment]
So #760 needs to maintain open, because its entirely not fixed by this pr

**Comment by ChruutvoLuzi** [comment]
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: Current date 15.11.2020
Version of the sim: 1.10.11.0
PR Tested: #1944 
Object of test: ATHR target after TO

Testing technique: Try out
Steps you've made to test the Pull Request:
1.  Started up the Aircraft at gate A44 in zurich
2.  created a flightplan from LSZH to LFSB with Simbrief
3.  created take off datas with the take off performance calculator
4. took off in FLEX and put the Throttle in to CLB after the Thrust Out Altitude
5. finished the flight

Flight notes (If required):

Take off/Climb:
The Transition from Takeoff feels much more fluent now, thanks for this fix

Issues (If Any): none
Overall Rating: Very nice fix
Conclusions of the testing: No Improvements needed, works as described

**Pull request merged**
