### PR TITLE
fix: condition for F/CTL FLAP/MCDU DISAGREE

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Fixed condition for check

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Spawn on runway, observe no master caution is displayed saying `F/CTL FLAP/MCDU DISAGREE`.
Go to TAKE OFF PERF PAGE and enter e.g. 1 for FLAPS and set FLAPS HANDLE to e.g. 2.
Observe master caution + ecam message `F/CTL FLAP/MCDU DISAGREE`.
Test completed and good.

Only the above response is acceptable as result.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 20.1.2021
Version of the sim:1.12.13
PR Tested: #3115
Tier of testing: 1
Changes to observe:condition for F/CTL FLAP/MCDU DISAGREE
(Insert the Summary of changes, in order to remind what is to test)

Testing technique: tested?
Steps you've made to test the Pull Request:
1. started on runway
2. changed flpas on perf page to 1 and set flaps to 2
3. observed master caution and ecam message


Issues (If Any): none

Overall Rating: Good
Conclusions of the testing: Works as expected thanks for the PR!

**Comment by cianwhite** [comment]
Category: QA Tester
Name: Cian#3596
Date of testing: 20/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3115 
Tier of testing: 1
Changes to observe: FLT CTRL FLAP/MCDU DISAGREE appears when the wrong flap is selected compared to the MCDU
Testing technique: Started C+D and at the runway and tested multiple configs
Steps you've made to test the Pull Request:
1. Started C+D at KMIA and started as normal. Selected Flaps 1, 2 and 3 on the TO PERF page and looked for error messages when I was in the wrong config.
2. All work as expected (e.g I get the message when on Flaps 2 and the MCDU is on Flaps 1 etc)
3. Spawn at the runway at KMIA
4. Do the same tests as before, changing the config observing the error comes up/disappears when it should.

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: The ECAM memo appears when you are in the wrong flaps setting in comparison to your MCDU and when you put the right flaps in the correct position the memo disappears.

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 20/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3115
Tier of testing: 1
Changes to observe: Condition for F/CTL FLAP/MCDU DISAGREE

Testing technique: Tested using the specific testing instructions in the PR Summary
Steps you've made to test the Pull Request:
1. Spawn on runway - checked no master caution is display of F/CTL FLAP/MCDU DISAGREE
2. Amended MCDU TO Perf to Flaps 1 - moved Flap Position to 2
3. Master caution + ecam message F/CTL FLAP/MCDU DISAGREE displayed

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Found no issues with it - ran it a couple of times

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: 20/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3115 
Tier of testing: 1
Changes to observe: ECAM -> F/CTL FLAP/MCDU DISAGREE

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1.  Load ac on RW with flaps 1
2. Tried different Flaps settings in MCDU
3. Moved Flaps lever do different pos.


Issues (If Any): No Issues Found

Overall Rating: Good
Conclusions of the testing: The memo appears only if there is a mismatch between MCDU Flaps settings and the actual flaps setting. Tried every possibility and found no issue.

**Comment by MisterChocker** [comment]
@tjburni @cianwhite @BritishAvgeek @Noxleee Thanks for the quick testing

**Pull request merged**
