### PR TITLE
feat: remove asobo sound and tweak some others

### PR DESCRIPTION
**Pull request by hotshotp**
Fixes #[issue_no]

## Summary of Changes

I removed the asobo sounds! We now have 100% custom sounds.

I have also changed the APU run sound to be more like the real thing because i applied way too much post processing on it. Reference attached. Also did some slight changes to engine. 

I have also created a cockpit door open/close sound change! When the door is unlocked, it counts as open. You will hear the open sound/clunk. Same with closing. so far it slightly affects the sound of the cabin fans, and also the chimes for seatbelt and cabin calls.

## References

https://cdn.discordapp.com/attachments/748761999747579944/877265848245583873/apu_operation_and_shutdown.wav VOLUME WARNING - real apu recording

## Additional context

Discord username (if different from GitHub):

Boris#9134

## Testing instructions

Lock and unlock the door and hit the seatbelt switch, the cabin call switch. try with door closed and unlocked, and listen for the volume change. 

Start up the APU and listen to the change in its run sound and its slight change in startup sound. 

Do a whole flight and check for the sounds! The asobo ones have been removed. the only sounds currently not there in our sounds is the exterior touchdown squeak and the belly landing screech. I considered these unimportant and i will add them later. To test out, check if stuff is missing - i have replaced every warning and every sound. Let me know on discord if I missed something, because i to be honest do not know if i missed any.

This is a QA tier 2 pull request, while anyone can test it, please do a high quality test, making sure none of the sounds are missing.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by ko-zone — APPROVED** [review]
LGTM

**Review by beheh — CHANGES_REQUESTED** [review]
Are the .wav's really required in this repository? Files like

> BIN +62.9 MB src/sound/Originals/SFX/OnhearingthefirstcuckooinSpringGroves (1).wav 

and

> BIN +83.9 MB src/sound/Originals/SFX/In The Steppes Of Central Asia.wav 

will (by default) *permanently* increase the size of this repository for every future clone, even if these files are removed in future.

This makes cloning more annoying, GitHub actions and other CI tasks will be slower, and eventually it can become a real challenge to work with Git.

Are these all files that are critically required to be in this repository?

Already today a clone of the repository is mostly made up of huge .wav files and the re-re-re-re-re-re-done .PCK file:

image

**Comment by Samueleonard** [comment]
Quality Assurance Tester Report

Discord: 1samueleonard1
Object of testing: (#5680)
Tier of Testing: (1)
Date: (18/08/2021)

Testing Process: 
. loaded in c+d
. started up, pressed buttons - listened for sounds
. opened + closed door, tested sound changes with fans/belts etc
. watched irl apu start video, started apu and listened - very nice

Negatives: n/a
Testing Results: (Passed/Not Passed) UNABLE YET

Conclusions: NO FULL FLIGHT MADE YET
Media: n/a

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5680
Tier of Testing: 2
Date: 19/08/2021

Testing Process:
- Loaded in C+D at EGSS, planned flight to EKCH.
- Locked and unlocked door, observed door sounds on open and closed - sound great. - PASS 
- Checked difference in volume from call chimes when door open and closed. - PASS
- Tested all other functions in flight deck for any missing sounds. - PASS

APU:
- Started up APU and listened from external view, directly behind.
- Compared to reference audio as per the PR reference. 
Sounded almost identical, when switching between the recording linked in Media, and the reference, was difficult to tell a real difference, sounds brill. - PASS

Continued with full flight to EKCH:
- Lined up on the runway with no flaps set, parking break on and TOGA thrust to check warnings present. Started flight with TCAS on STBY to raise that caution, all sounds as normal. - PASS
- Inconvenienced the passengers to raise various other warnings, all okay!
- Tested A/P disconnect sound. - Sounds great! PASS
- Continued to test everything I could push throughout the flight, no issues found.

Negatives: N/A
Testing Results: PASS

Conclusions: The door sounds are brill, and the APU sounds so realistic compared to the reference, I wouldn't be able to tell you which was the reference in a blind test. Really great work, and 100% FBW! Having reduced cabin sounds with the doors locked and vice versa is a great touch, gives some really good insight into how other cabin sounds can fit in nicely in future! 

Media:
Recorded APU sound, cockpit door lock and unlock and call sounds in both states, uploaded at: https://youtu.be/VSRY27gnrLE

**Comment by KeepGamingLP** [comment]
Quality Assurance Trainee Report

Object of testing: (#5680)
Tier of Testing: (2)
Date: (18/08/2021)

Testing Process:
Loaded at LIRF C+D
Testes various Buttons (Cabin, Door etc.). Passed!
Startet APU and listend to the new Sound.
No diffrence between Sample and ingame. Passed!
Done full flight to LIEO, turned AP on and off and tested various warnings.
Passed.

Negatives: n/a
Testing Results: Passed!

Conclusions: very great work done! The sounds are amazing!

Media: n/a

**Comment by John-UK** [comment]
Quality Assurance Tester(trainee) Report

Discord: john P Maguire#9027
Object of testing: (#5680)
Tier of Testing: (2)
Date: (19/08/2021)

Testing Process:
This is a huge PR. The testing is too large to pass or fail in one QA. These are my observations.
As expected:
Loaded in C&D in a storm.
Competed standard flows - listened for sounds both aircraft and environment. Amazing listening to APU in a storm.
Checked door closed and open. Noticed a difference.
Master warning with flaps and stats not in take off config.
Flaps over speed warning.
Overspeed warning
Don't sink pull up

Not as expected:
The sound file attached to cabin ready push. The tone was heard on pushing the button. The speech was prohibited by the stats and flaps warning, I think. It played after I had set the flaps AND cleared the ECAM warning. 
Connected tug. If any sound is attached did not hear it. Same with detaching the tug.

**Comment by FlightSimmer7700** [comment]
Engine start tested and can confirm that the apu check valve is once again audible!!!! Good to merge I think

**Comment by kaese5128** [comment]
great new sounds ! Is it possible to manage the volume of the AP disconnect sound ? In my view it is a little bit oversteering?

**Comment by hotshotp** [comment]
> great new sounds ! Is it possible to manage the volume of the AP disconnect sound ? In my view it is a little bit oversteering? 

The warning slider in the msfs sound settings should affect it. Irl the AP disconnect sound is very loud as it's an important warning, so I matched it's volume with the master warning. I might lower it a little bit in my next PR though

**Pull request merged**
