### PR TITLE
feat: Add script to enable counting & dumping of object hierarchy

### PR DESCRIPTION
**Pull request by XSJoJo**
## Summary of Changes
Add script to enable counting & dumping of object hierarchy

## Testing instructions
Follow src/tools/heapdump/README.md and check whether you get an object dump.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
I'll have to add infra to the authorized prefixes in the tite lint.

Also, is there a way we can make this run by default ? Like, if someone reports an issue, have them quickly run the script to get a dump. This way, no waiting for a reproduction.

**Comment by XSJoJo** [comment]
> I'll have to add infra to the authorized prefixes in the tite lint.
> 
> Also, is there a way we can make this run by default ? Like, if someone reports an issue, have them quickly run the script to get a dump. This way, no waiting for a reproduction.
> 
> Given user consent, we could even automatically take those dumps and upload them if they do not have a big impact on performance.

Thanks for the feedback! Hmm, every instrument pinging the server every couple of seconds..that may have some impact on performance, and I think I've observed some of it already. Maybe we should add an option to the EFB to enable/disable this dynamically?

**Comment by XSJoJo** [comment]
FWIW, dumping itself is incredibly expensive and leads to huge frame drops.

**Comment by Watsi01** [comment]
@XSJoJo Yes, I recognized. I can give you some dumps pretty soon.

**Comment by Watsi01** [comment]
@XSJoJo @Benjozork 
Ok, here are 4 dumps. Please notice, that the last dump (60mins inflight) is grown 10x in filesize, in comparison to the others.
[Dumps_Watsi01.zip](https://github.com/flybywiresim/a32nx/files/5981817/Dumps_Watsi01.zip)

**Comment by XSJoJo** [comment]
Hmm, looks like the dumps except the last one don't contain all instruments...

Maybe the timeout I use on the server isn't long enough in case dumping in MSFS takes..that long?

**Comment by Watsi01** [comment]
I made new dumps with longer timeout settings and sent them to @XSJoJo.

**Comment by XSJoJo** [comment]
@Benjozork Could we merge this as-is for now? I know that enabling this ad-hoc would be nice, but needs a bit more thought how we'd make this possible for non-devs.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
@XSJoJo can you fix your lint errors ?

**Pull request merged**
