### PR TITLE
fix no route on ND by copying in missed NavSystem changes from 1.8.3

### LINKED ISSUE #976: [BUG] Route not visible on ND
related #964
**Mod Version**

master, after all our porting changes were merged.

**Describe the bug**

**To Reproduce**

spawn on runway
add from/to in mcdu
add a SID to the flight plan
look at ND

**Expected behavior**

should see green line with waypoints on ND

**Actual behavior**

no green line, no waypoints, but TOC and TOD seem to be visible?

### PR DESCRIPTION
**Pull request by AdenFlorian**
Fixes #976

**Summary of Changes**

copied from my discord rambling:
> another missed change from the previous patch
> kind of
> i think what happened was
> around the time when the last patch dropped a couple weks agoi
> someone had a PR opened which copied NavSystem.js from vanilla into our codebase
> but they opened the pr before the patch dropped
> so it was the old version
> then got merged later
> surprised it didnt cause issues until now
> the reason we didnt see an error was because its inside a promise callback
> i palced a bunch of console logs throughout flight plan manager, and noticed some stopp logging after my waypoints were added
>then put a geiant try catch block in and caught and logged the error

**Screenshots (if necessary)**

image

**References**

**Additional context**

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by HiddenCitizen** [comment]
I'm sorry I'm a bit slow, is this resolved? If so do we need to modify any files?

**Comment by sepiroth887** [comment]
never been so happy to see lines. esp for a one liner fix :) awesome

**Comment by sepiroth887** [comment]
@HiddenCitizen pull master it should already be there. or fix the file as shown in the diff if you don't want master?

**Comment by HiddenCitizen** [comment]
Gottcha. I'm new to Github. Thanks!

**Pull request merged**
