### PR TITLE
feat: registration decal

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Added registration decal
    * Added PSD to customize folder

## Screenshots (if necessary)

image

## Additional context

Make sure the decal looks right.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by DarkOfNova — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3570
Tier of testing: 1
Changes to observe: Registration number decal
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Looked for the registration number (Image1)

Media:


Image1

Issues: None

Overall Rating: Good

Conclusions of the testing: 
- Decal is on plate
- Not clipping
- When the big letters should be centered between the plate screws they need to be a little more to the right

Hope this helps :-)

**Comment by tracernz** [comment]
Maybe a dumb question, but is it wise to share the texture with anything else? If we ever change that texture all the repaints will need fixed again..

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 17.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3570 
Tier of testing: 1

### Changes to observe: Registration Decal

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on runway at VABB
2. Checked the registration decal

### Media:
image

### Overall Rating: Good

### Conclusions of the testing: The decal is placed properly on the metal plate. Looks good to go!

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3570 
Tier of testing: 1
Changes to observe: Registration/Selcal placard


Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned LSZH A44
2. Checked Placard

Media:
Microsoft Flight Simulator Screenshot 2021 02 17 - 19 53 55 86


Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Nice to have it back. Works as described and found no new issues

**Comment by beheh** [comment]
@tyler58546 This is about ready to merge. Could you fix the final conflicts?

**Pull request merged**
