### PR TITLE
fix(fuel): turnaround fuel used reset

### LINKED ISSUE #6862: Aircraft Turnaround State Values
### Aircraft Version

Development

### Description

I would love to see that when I click on "Delete all" on the MCDU after a flight is completed that the W&B Passenger Values are set to 0 and also that the Fuel Used Values on the FUEL ECAM Page are set to 0 again.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by Taz5150**
Fixes #6862 (partially)

## Summary of Changes

With the new EGT cooling constant, the engine maintains a "shutting" state for a long time (instead of switching to "off" state once N2 gets to zero). Due to this change in the engine state model, fuel used was not being reset. This issue is being solved with this PR.

## Additional context

Discord username (if different from GitHub): TazX [Z+2]#0405

## Testing instructions

One way to do it:
1. Start aircraft on runway
2. Switch SD to ENG and burn some fuel (until it is shown in the SD)
3. Turn Engine 2 OFF (Master Off) and let it roll back
4. Switch igniter ON
5. Start Engine 2
6. Used fuel should reset to 0

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by John-UK** [comment]
Tested this in the usual situations where an engine would be shut down on the ground. Restarted the engine and fuel used was reset to zero. Tested both eng 1 and 2. Also tested in the air. System worked as expected fuel used was not reset to zero in the air.

A nice fix to a couple of questions in the support channel recently. Exceptionally efficient code change.

Looks good to go to QA if needed probably does not.

**Review by Saschl — COMMENTED** [review]
Just a small remark (not related to this PR).

I noticed https://github.com/flybywiresim/a32nx/blob/eae165b508f398a07c92bd1e340eba8db37f455a/src/fadec/src/EngineControl.h#L1126 `animationDeltaTime` is never initialized. You probably wanted to use the class member `animationDeltaTime` here?
https://github.com/flybywiresim/a32nx/blob/eae165b508f398a07c92bd1e340eba8db37f455a/src/fadec/src/EngineControl.h#L18

Anyway not related to this PR but I thought I'd note it.

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #6876
Tier of Testing  : 1
Date             : 10/03/2022

Testing Process: 
Started the engine, shut down the engine, restarted the engine and fuel got reset. It works. 🚀 
Does not work in the air, as intended.

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Magnificent efficiency in coding 🤣

**Comment by Taz5150** [comment]
> Just a small remark (not related to this PR).
> 
> I noticed
> 
> https://github.com/flybywiresim/a32nx/blob/eae165b508f398a07c92bd1e340eba8db37f455a/src/fadec/src/EngineControl.h#L1126
> 
> `animationDeltaTime` is never initialized. You probably wanted to use the class member `animationDeltaTime` here?
> https://github.com/flybywiresim/a32nx/blob/eae165b508f398a07c92bd1e340eba8db37f455a/src/fadec/src/EngineControl.h#L18
> 
> Anyway not related to this PR but I thought I'd note it.

Your are completely right. I used to work with animationDeltaTime to detect pauses, but that is obsolete now. Will make changes in subsequent PRs (need to make sure there is nothing depending on that variable).

Thanks!!!

**Review by bouveng — APPROVED** [review]

**Pull request merged**
