### PR TITLE
fix(atsu): LSK6L ATSU DLK return in ATC MENU

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes the following issue:
https://discord.com/channels/738864299392630914/785976111875751956/1022941254687916132

## Summary of Changes
This pr fixes  LSK6L in ATC MENU not returning to ATSU Datalink Page.

## References
Honeywell H3/H4 FCOM of FANS A+B & C equipped aircraft:
FCOM

## Additional context

Discord username (if different from GitHub): Bruno_pt99#5802

## Testing instructions
Check that pressing LSK6L on ATC MENU page returns to the ATSU Datalink Page.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
LGTM 👍

**Comment by tracernz** [comment]
Couple of issues picked up by the linter:
```
/external/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Menu.js
  68:1   error  Trailing spaces not allowed  no-trailing-spaces
  71:10  error  Missing semicolon            semi
  75:1   error  Trailing spaces not allowed  no-trailing-spaces
```
You can check on your local machine with `.\scripts\dev-env\run.cmd npm run lint`.

**Comment by BravoMike99** [comment]
> Couple of issues picked up by the linter:
> 
> ```
> /external/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Menu.js
>   68:1   error  Trailing spaces not allowed  no-trailing-spaces
>   71:10  error  Missing semicolon            semi
>   75:1   error  Trailing spaces not allowed  no-trailing-spaces
> ```
> 
> You can check on your local machine with `.\scripts\dev-env\run.cmd npm run lint`.

Oops, should be fixed now.

**Comment by marcman86** [comment]
Quality Assurance Report

Discord: marcman86#4907
Object of testing: #7642
Tier of Testing: 1
Date: 9/12/2022

Testing Process:
- Spawned at gate at EDDP
- Turned on bat. and external power
- Checked ATC MENU Return returnes to ATSU Datalink page
- Checked ATC sub pages for correct return to ATC MENU page

Negatives: -

Testing Results: Passed
Conclusions: Works for me

Hope this helps :-)

**Pull request merged**
