### PR TITLE
Improve upper ECAM visuals

### LINKED ISSUE #867: [BUG] Upper ECAM is hard to read
**Mod Version**

master

**Describe the bug**

The upper ECAM is hard to read and does not look like in a real plane.

To iterate:
* Indicated numbers and their labels (N1, EGT, N2, FF) are larger, roughly the same font size as the FOB counter.
* The box around the N1 and EGT number is thinner and dimmer.
* Units (e.g. KG/H, KG, °C) are smaller font size than their values, most noticeable on the FOB counter.
* The current thrust state (CLB, MCT, ...) in the top right is left-aligned with the current thrust limit percentage underneath it.
* Notches on the N1 gauge are smaller, the EGT gauge has three little notches and the red area is smaller.
* The slats/flaps indicator is brighter/has more contrast.
* Text and numbers (e.g. number values, status and memo messages) are brighter/have more contrast.

I feel like the low brightness/contrast is also true for a lot of the lower ECAM.

**To Reproduce**

1. Spawn in plane and turn up brightness for upper ECAM

**Expected behavior**

see above

**Actual behavior**

see above

**References**

Current state in sim: https://cdn.discordapp.com/attachments/742814829680656496/758805201389092874/Desktop_Screenshot_2020.09.24_-_23.38.48.50.png

Real planes:
* https://forums.flightsimlabs.com/uploads/monthly_2017_03/1887874.jpg.e870cd6a773c4ba68031c33f94488d26.jpg
* https://i.pinimg.com/originals/e9/fd/8c/e9fd8ccc45e761a0d134dae41814b906.jpg
* https://www.vier-im-pott.com/images/2019/10/12/a320_professional_training_devices.jpg (real sim)

**Additional context**

Was this working before/when did the issue start occurring?
Never worked.

Is this a problem in the vanilla unmodded game?
Yes?

Discord username (if different from GitHub): Cobra#5370

### PR DESCRIPTION
**Pull request by wpine215**
Fixes #867

**Changelog**

- Increased flap/slat SVG thickness and updated colors
- Changed flap/slat markers from circles to parallelograms
- Increased text sizes for all elements
- Updated bounding box for N1 and EGT gauge values
- Decreased thickness and length of N1 and EGT inner markers
- Modified ECAM thrust state position and alignment
- Modified ECAM memo separator position and thickness; added rounded ends

**Screenshots (if necessary)**

**Before:** 
image

**After:**
image

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by Benjozork** [comment]
Hello, please take note that we have started including a CHANGELOG.md file that requires every PR to add a change-log line that describes its changes. As your PR is not merged yet, we kindly ask that you add this information following the included directives in the file.

Disclaimer: This is a copy-and-pasted message.

**Comment by wpine215** [comment]
Done.

**Comment by Benjozork** [comment]
I think you forgot to push :upside_down_face:

**Review by AdenFlorian — APPROVED** [review]
ready to test!

**Comment by AdenFlorian** [comment]
@wpine215 still needs the changes to the changelog.md tho

**Comment by AdenFlorian** [comment]
please make your before and after screenshots have the same context/settings/angle/size so we can more easily tell what changed, and provide a reference pic

**Comment by NathanInnes** [comment]
Before reference: 
image

**Review by NathanInnes — COMMENTED** [review]
EGT not turning red. 

Appears to be a problem before the change. Only turns red when EGT reduces
image

**Review by NathanInnes — APPROVED** [review]
Everything looks good! I will make a seperate issue for EGT not turning red.

**Pull request merged**
