### PR TITLE
Fix spoiler auto-retract on landing

### PR DESCRIPTION
**Pull request by donstim**
## Summary of Changes

This PR disables the auto-retraction of spoilers after landing.
## References

https://youtu.be/ZRP06Ec86e8?t=411

## Additional context

In the most recent Asobo changes to the vanilla A320neo, they disabled the auto-retraction of spoilers after landing. This PR picks up that change.
KNOWN ISSUE:  The spoilers should automatically retract when the thrust levers are placed above the CLB detent. This is not modeled (yet?), and this PR does not affect that.

Discord username (if different from GitHub):donbikes#4084

## Testing instructions

Conduct landings with and without the change made by this PR.
Note the position of the ground spoilers after decelerating after landing.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by donstim** [comment]
What does it take to get this reviewed?  This should be a simple one to merge as: (1) It implements a change made by Asobo to the vanilla A320neo; (2) It makes the sim match the real airplane in regards to spoiler retraction after landing; and (3) It doesn't affect anything else.

**Comment by lukecologne** [comment]
Why does this also have the changes from #2748?

**Comment by Snapmatics** [comment]
When you change something (flight model for example) which changes the way things work on the airplane after you touch the ground, it will need to be tested by the QA Testers. No matter if it's good or not or even 1000% realistic.

**Comment by Snapmatics** [comment]
> What does it take to get this reviewed?  This should be a simple one to merge as: (1) It implements a change made by Asobo to the vanilla A320neo; (2) It makes the sim match the real airplane in regards to spoiler retraction after landing; and (3) It doesn't affect anything else.

When you change something (flight model for example) which changes the way things work on the airplane after you touch the ground, it will need to be tested by the QA Testers. No matter if it's good or not or even 1000% realistic.

**Comment by donstim** [comment]
> Why does this also have the changes from #2748?

Oops, because I made it from that branch. Fixed now.

**Comment by donstim** [comment]
> > What does it take to get this reviewed?  This should be a simple one to merge as: (1) It implements a change made by Asobo to the vanilla A320neo; (2) It makes the sim match the real airplane in regards to spoiler retraction after landing; and (3) It doesn't affect anything else.
> 
> When you change something (flight model for example) which changes the way things work on the airplane after you touch the ground, it will need to be tested by the QA Testers. No matter if it's good or not or even 1000% realistic.

Well, I was wondering why it was not marked ready to test after sitting there for a couple of days.

**Review by lukecologne — APPROVED** [review]

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: 5/1/2021
Version of the sim: 1.12.13.0
PR Tested: #2857 
Object of test: Fix spoiler auto-retract on landing

Testing technique: Attempted few approaches to test the spoiler position during landing roll. 

Steps you've made to test the Pull Request:
1. Tested the ground spoilers position after touchdown. 
103605659-75112280-4f4f-11eb-92dd-4419646b1f76.mp4
Flight notes (If required): N/A

Issues (If Any): N/A
Overall Rating: Good.
Conclusions of the testing: As mentioned, a simple change but important nonetheless and working as intended.

**Comment by NickFarin** [comment]
Category: QA Trial
Name: Discord User: Nick F[Z+8] #5327
Date of testing: Current date: 05/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2857 
Object of test: Spoiler lever auto retract after landing
Testing technique: Performed landings at RPLP and monitored spoilers
Steps you've made to test the Pull Request:
1. Spawned at the gate in RPLP and started the plane up
2. Took off and did some landings
3. After landing, I checked if the spoiler lever is still in the armed detent.
4. After verifying that the spoiler lever is still in the armed detent, I taxied back and repeated the process 2 more times

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: The lever works as intended and the test went normal.

**Comment by donstim** [comment]
Thanks for the tests, guys!

**Pull request merged**
