### PR TITLE
fix: changes requested by navigraph

### PR DESCRIPTION
**Pull request by ZigTag**
Fixes #[issue_no]

## Summary of Changes

Refactored some calls and overall made the efb handle navigraph much better. 

## Additional context

Some code was very sub-par and had to be rewritten as per Navigraph's request.

Discord username (if different from GitHub): Falcon#5815

## Testing instructions

- Just make sure that all the default features work properly. These changes should be unnoticeable in the user.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by hiaaryan — APPROVED** [review]
GTG! 🚀

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5318
Tier of Testing: 1
Date: 15.7.2021

Testing Process: 

Check Navigraph charts by tryout

Fresh start at gate first time auth ==> OK
Restart sim
2nd Test ==> had to re-auth
Restart sim
3rd ==> had to re-auth
Turned off Developer Mode. Changes PTU setting to see if this is persisted.
Restart sim
4th ==> PTU has been persisted but Navigraph auth is gone 
Restart sim
5th ==> OK - PUT setting was persisted and Navigraph auth as well 

Negatives: inconsistent results
Testing Results: not passed
Conclusions: needs more testing to understand when it persists the authentication and when not.

**Comment by Benjozork** [comment]
Keep in mind settings are only persisted if you exist the sim via the main menu.

Did you press ALT+F4 or the X ? In that case, they won't be stored.

**Comment by frankkopp** [comment]
> Keep in mind settings are only persisted if you exist the sim via the main menu.
> 
> 
> 
> Did you press ALT+F4 or the X ? In that case, they won't be stored.

I never use Alt+F4 because of this. I always closed the sim via the menu especially for this test.

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5318
Tier of Testing: 1
Date: 16.7.2021

Testing Process:
Re-test with focus on auth (before last lint fix build):

Loaded FBW and started flyPad.
Had to do authentication - worked.
Back to Main Menu - loaded other aircraft - back to main menu
Loaded FBW again and started flyPad - still workjed - no auth required
Back to main menu and quit to desktop.
Restarted sim and loaded FBW and started flyPad -- did not work, had to re-authenticate again

Testing Results: not passed

**Pull request merged**
