### PR TITLE
fix(inst): chrono & ET behavior on time shift

### PR DESCRIPTION
**Pull request by vkrizan**
Fixes #[issue_no]

## Summary of Changes

Fixes elapsed time and chrono (on clock and on ND) to work with time shift by debouncing on diff more than 60s.

In simulation the elapsed time should be kept intact when changing simulated time and/or sun orientation.

## Additional context

Chrono and ET Clock use `E:ABSOLUTE TIME` to compute elapsed time, however if there is a time shift the absolute time changes with it.

The 60 seconds mark was selected as a compromise, to detect a time change. MSFS UI seems to have steps by 2min.

This is a workaround until/unless there is some other time reference that can be used to count elapsed time.

Discord username (if different from GitHub): coolll.sk

## Testing instructions

Chrono on ND and on Clock, as well as Elapsed Time, should be closer to real time.
That is:
* on unchanged time conditions
* on time shift forward
* on time shift backwards

Please note that when making a time shift/change, the chrono/timer would pause briefly until next frame.

Test Clock Chrono/CHR (on center panel, NOT on ND):
1. push CHR on clock in simulator
1. start stopwatch externally
1. time shift forward
1. time shit backwards
1. set time simulated time to original or LIVE
1. compare time with the stopwatch

Test Elapsed Time (on center panel):
1. move knob on ET to RUN in simulator
1. start stopwatch externally
1. time shift forward
1. time shit backwards
1. set time simulated time to original or LIVE
1. compare time with the stopwatch

Test Chrono on ND:
1. push Chrono above ND
1.  start stopwatch externally
1. time shift forward
1. time shit backwards
1. set time simulated time to original or LIVE
1. compare time with the stopwatch

Test for no regressions:
* do a full flight with Chrono (on ND and on CLK) and ET started
* start stopwatch externally
* compare time with the stopwatch

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by BlueberryKing — APPROVED** [review]
Nice work! 🚀

**Comment by marcman86** [comment]
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #6175
Tier of Testing: 1
Date: 22/11/2021

Testing Process:
- Spawned C&D at EDDP
- Turned on bat. and ext. power
- Tested CHR and ET on center clock > independent from time shift
- Tested timer on captain ND > independent from time shift
- Tested timer on F/O ND > independent from time shift
- Lots of time shifts
- Timer measured to external stop watch over 10min 

Negatives: -

Testing Results: Passed
Conclusions: Works for me. As off the small timer freeze at time shift  timer lags are add up when time shifting happen to often. But i think this is not a usual use for time shifting (time shift while time stopping).

Hope this helps :-)

**Comment by BlueberryKing** [comment]
Would be great if we could get a full flight test on this to quantify the time drift over longer intervals. :)

**Comment by vkrizan** [comment]
I'd have to update the conflicts after the merge of cFMS. Basically the the new ND would use `debouncedTimeDelta` fn.

**Comment by BlueberryKing** [comment]
Ah, yeah, the timing is a bit unfortunate. Do you think you could adapt your new changes to the new ND? That would be great! :)

**Comment by vkrizan** [comment]
For sure, I was counting on the new ND but did not known that it would be merged. I'll update it, but unfortunately I would not be able to test them in simulator this week.

**Comment by vkrizan** [comment]
@BlueberryKing Updated.

**Comment by davidnorfolk96** [comment]
Quality Assurance Trainee Report

Discord: !davidn123#0001
Object of testing: #6175
Tier of Testing: 1
Date: 01/12/2021

Testing Process: 
Loaded in at EGKK 26L & tested the following :
Chrono on ND and on Clock, as well as Elapsed Time, should be closer to real time.
That is:

on unchanged time conditions-PASSED
on time shift forward-PASSED
on time shift backwards-PASSED

Test Clock Chrono/CHR (on center panel, NOT on ND):- PASSED

push CHR on clock in simulator-PASSED
start stopwatch externally-PASSED
time shift forward-PASSED
time shit backwards-PASSED
set time simulated time to original or LIVE-PASSED
compare time with the stopwatch-PASSED
Test Elapsed Time (on center panel):-PASSED

move knob on ET to RUN in simulator- PASSED
start stopwatch externally-PASSED
time shift forward-PASSED
time shit backwards-PASSED
set time simulated time to original or LIVE-PASSED
compare time with the stopwatch-PASSED
Test Chrono on ND:-PASSED

push Chrono above ND-PASSED
start stopwatch externally-PASSED
time shift forward-PASSED
time shit backwards-PASSED
set time simulated time to original or LIVE-PASSED
compare time with the stopwatch-PASSED



Negatives:n/a
Testing Results: Passed

Conclusions: All test passed, nothing found to be broken.

**Comment by John-UK** [comment]
Quality Assurance Report

Discord: john P Maguire#9027
Object of testing: #6175
Tier of Testing: 2
Date: 02/12/2021

Testing Process:
Prior to the test flight Spawned at EGJJ 08 and observed the behavior of Chrono (ND and clock) and ET when time shift applied. Chrono moved forward to 59:59 or 00:00 if shift exceeded 60 mins or prior to the start time of the chrono.

Spawned at EGJJ 08 for a full flight. Time shifted on the RW and observed that the clock time show the correct sim time. ET and Chronos were elapsed time consistent with the external elapsed time.

Set real time in the sim clock reverted to real time and reset ET and both chronos.

Started ET, chronos and stopwatch then departed EGJJ for a short flight to EGLL ( run both chronos and EL for a full flight). Sim timers were checked against stopwatch during the flight. No regressions were identified. 

Arrived at Heathrow into stand. Logging ACARS recorded the same in flight times as stopwatch, ET and chronos. 

Negatives: None noted.
Testing Results: Passed

Conclusions: Performed as required by the PR. No regressions.

**Pull request merged**
