### PR TITLE
refactor(fms): some cleanup

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- removed unused simvar
- added update throttler

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Perform a flight as per usual.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
LGTM

**Review by davidwalschots — APPROVED** [review]

**Comment by ExampleWasTaken** [comment]
Category: QA Tester
Name: ExampleWasTaken#0886
Date of testing: 13/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3908
Tier of testing: 1
Changes to observe:
FMS refactoring

Testing technique:
1. Performed full flight YSSY-NZAA (Stand to stand)

Flight notes (When done a full flight): 
Route: WOL2 WOL DCT GEROS L521 LUNBI DCT ARADI ARAD6B

Media: N/A

Issues (If Any): I imported the route from SimBrief and it loaded the part `LUNBI DCT ARADI` twice.

Overall Rating: Probably good to go
Conclusions of the testing: I am not sure the mentioned issue is caused by this PR or is the general buggy FMGS. If it is not it's a "good" from me.

**Comment by MisterChocker** [comment]
@ExampleWasTaken Unrelated to this pr.

**Comment by ExampleWasTaken** [comment]
> @ExampleWasTaken Unrelated to this pr.

Thought so.

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 14.3.2021
Version of the sim: 1.14.5.0
PR Tested: #3908
Tier of testing: 2
Changes to observe: FMS
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at KBOS, used FS flight planer 
2.) Did a full flight to CYYZ
3.) Watched FMS

Issues: -

Overall Rating: Good

Conclusions of the testing: "Works" is the wrong word, so i write "behaves the same" ;-)

Hope this helps :-)

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 14/3/21
Version of the sim: 1.14.5.0
PR Tested: #3908 
Tier of testing: 1/2/3
Changes to observe:
FMS

Testing technique: Full flight
Steps you've made to test the Pull Request:
1. loaded flight plan through simbrief
2. did flight
3. rnav arrival
4. looked at mcdu throughout

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: LGTM

**Pull request merged**
