### PR TITLE
fix: improve overall brightness

### PR DESCRIPTION
**Pull request by sidnov**
Fixes #[issue_no]

## Summary of Changes

Turns up the brightness on most displays by 2 notches, improved for visibility in bright sunlight conditions. 

## Screenshots (if necessary)

Screenshot 2022-03-38 215057
image
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Test the visibility of letters and indications on the PFD,ND,ECAM
Test the visibility of the MCDU display
Max brightness should make the displays look just about readable during daylight, at night the displays should look slightly overexposed when set to max brightness

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by bouveng — APPROVED** [review]

**Comment by Watsi01** [comment]
Thanks Sid. Speaking of this: I couldn't find where to turn up the MCDU default brightness. Didn't find it in the respective .FLT files. I think this should be turned up a bit too (I mean the brightness 'pre-setting' when you spawn into the aircraft).

**Comment by jcalor** [comment]
Quality Assurance Tester Report

Discord          : Calo#6816
Object of testing: #6981 
Tier of Testing  : 1
Date             : 29/03/2022

Testing Process: 

- Compared day brightness on PR version vs without PR version - checked
- Max brightness looks overexposed at night - checked

Negatives:       

Testing Results: Passed

Conclusions: Looks better!

Media:

**No PR**
image
**PR**
image
**At night**
image

**Comment by sidnov** [comment]
> Thanks Sid. Speaking of this: I couldn't find where to turn up the MCDU default brightness. Didn't find it in the respective .FLT files. I think this should be turned up a bit too (I mean the brightness 'pre-setting' when you spawn into the aircraft).

Done, thanks for the tip @Watsi01 👍🏻

**Comment by alexr4339** [comment]
Quality Assurance Tester/Trainee Report

Discord : Alex R#6663
Object of testing: PR #6981
Tier of Testing : 1
Date : 30/03/2022

**Testing Process:**


Started the flight on runway, checked on day with clouds, set the time to night, displays were overexposed, then back to day without clouds.

**Negatives:**


Especially during night, the biggest change of intensity is around 50% knobwise, with the knob turned brighter than 50% a change of intensity is barely noticable

**Testing Results:** 

Passed

**Conclusions:** 


All in all it seems better, still hard to read when "looking" to the horizon, but thats how the real eye would work as well.

**Media:**

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#5438
Object of testing: #6981
Tier of Testing: 1
Date: 30/3/22

Testing Process: Loaded in and completed a full flight under live weather and then changed the conditions and display brightness while in the air and on the apron to test 
Negatives: 
Noticed some flickering while flying through clouds on approach
Testing Results: Passed

Conclusions: Looks great but might want to double check with everyone that the possibility of the flickering happening is ok
Media: (Pictures/videos if applicable - delete line if not applicable)
image
image
image

**Comment by AdamNZ** [comment]
MCDU brightness is fine for me - but only when turned up to maximum.
However - the flickering when passing through clouds was pretty bad on my system. I suspect it's mainly as Asobo problem though <??>.

**Comment by tracernz** [comment]
> However - the flickering when passing through clouds was pretty bad on my system. I suspect it's an Asobo problem though .

It's the reason we removed the glass previously.

**Comment by sidnov** [comment]
I'll leave it upto the devteam and maintainers to take further action (merging or closing) on this PR as per the discussions in modeling channels

**Review by Saschl — APPROVED** [review]
I'd say let's go with this for now until we have other solutions, especially as we already have this change on experimental.

**Pull request merged**
