### PR TITLE
Added "F/O Side Stick Priority" Push button

### PR DESCRIPTION
**Pull request by oliverpope03**
**Summary of Changes**

Added Push button for F/O Side Stick Priority, lights synced on left and right, both sides clickable, animations seperate, unsure if an ecam message is linked with this IRL

**Screenshots (if necessary)**

https://gyazo.com/3bc8c5971a85f3055e70e1ba60fce53c

**Additional context**

For immersion only not sure if its really able to change stuff but thought it was a nice button to have :)

### CODE REVIEW

**Comment by Coralec** [comment]
Working as described. I don't see any reason this shouldn't be merged. Thanks for the work @oliverpope03.

**Comment by younesseQAtester** [comment]
Working !

**Comment by ImenesFBW** [comment]
Working as intended! Thanks!

**Comment by JackZ974** [comment]
Errr... Sorry, but this is not the way it works IRL.
- The light should be CAPT on the captain side and F/O on the F/O side. 
- This is a light only, not a pushbutton.

And this light is for information only, this light is NOT used for sidestick take over, which is done via the red button on the stick itself.
image
image

**Comment by oliverpope03** [comment]
Okay sorry my bad xD

**Pull request closed without merging**
