### PR TITLE
refactor: include remaining files from asobo-aircraft-a320-neo

### PR DESCRIPTION
**Pull request by Benjozork**
Addresses #1215 

## Summary of Changes

* Bring in what I think is all remaining files from the `asobo-aircraft-a320-neo` package

Discord username (if different from GitHub): someperson#4953

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
For QA:

TEMPORARILY REMOVE THE `asobo-aircraft-a320-neo` PACKAGE FROM YOUR `Official` DIRECTORY BEFORE TESTING !

Please perform flights that use as many of the aircraft's functionality as possible, including new sounds, new avionics functionality brought in by the mod. We need to make sure this doesn't break anything.

**Comment by tjburni** [comment]
Category: QA Tester
Name: tjburni #0409
Date of testing: Current date 24.11.2020
Version of the sim: 1.10.11.0
PR Tested: #2079
Object of test: (ECAM Page or Flight model or views or anything, what the PR modifies)

Testing technique: removed asobo-aircraft-a320-neo then tested 
Steps you've made to test the Pull Request:
1.removed asobo-aircraft-a320-neo
2. started at gate
3. started the a320
4. flew 2 go arounds
5.shut down engines midair and restarted them
6.tested A/P
7.flew to airport
8.landed
9.shut plane down
10.restarted plane and flew 1 go around
11.landed

Flight notes (If required):

Issues (If Any): i had 10 to 15% lower fps then latest master ( don't know if its only me) but thats ok
Overall Rating: Good
Conclusions of the testing:plane works good

**Comment by CaptainR3X** [comment]
Category: QA Tester
Name: GustavRex #4347
Date of testing: Current date 24/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2079
Object of test: Test aircraft functionality using as many functionalities as possible (with deleted asobo a320 file)

Testing technique: Flight; EKCH-ESGG ; ESGG-ESSA ; ESSA-EKCH
Steps you've made to test the Pull Request:
1. Preflight chekcs, flight programming, takeoff at EKCH - Arrival planning, descent, approach, GA, ILS approach and landing at ESGG
2. Flight programming, takeoff at ESSG - Manuverability tests, AP functionality tests (HDG mode, V/S climb, selected and managed speed) - Arrival programming, descent, approach and landing at ESSA
3. Light tests externally and internally, Flight programming, takeoff at ESSA - Arrival planning, descent, manual approach, GA, ILS approach and landing

During all tests: Monitoring cockpit displays and listening for sound bugs

Flight notes (If required): Online, VatSim

Issues (If Any): AP went rouge from track upon descent into EKCH, could fix it with a DIR to next waypoint (not sure if this is a common bug)
Overall Rating: Good
Conclusions of the testing: Did not experience major errors. The plane handeled all flights well and performed as it shoud. I was unable to identify any unknown bugs in the cockpit, with the displays and MCDU and furthermore no issues with the sound pack. The only minor issue i encountered was the rouge operation of the AP on descent. It turned away from track and was able to be fixed with a simple DIR to the next waypoint, however I am not sure whether this is a known bug. The manuverability of the aircraft felt fine (considering #1580 is not implemented yet).

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 12/05/2020
Version of the sim: 1.11.6.0
PR Tested: #2079 
Object of test: refactor: include remaining files from asobo-aircraft-a320-neo

Testing technique: C&D flight from ENGM to ENVA

Steps you've made to test the Pull Request: 
1. C&D at ENGM taking off from RWY01L doing RIBE1A and continues flight plan to ENVA as normal.
2. T/D and starts starts the descent everything seems normal so far.
3. Landing ILS RWY09 on ENVA without any noticeable issues.
4. Shuts down the plane and starts up to just try a normal takeoff just to see if anything happend due to that, but all is fine. 



Flight notes (If required): 

Issues (If Any): Had a little issue with FD banking right after takeoff wich screwd up the AP on first try but couldnt reproduce the other 3 times so idk why it happend.

Overall Rating: Good

Conclusions of the testing: Cant find anything significant fault on my side 👍🏻 

Screenshots:

**Comment by Highflyer2010** [comment]
Category: QA Tester
Name: Discord User Highflyer #8932
Date of testing: Current date 07/12/2020
Version of the sim: Version the tester uses 1.11.6.0
PR Tested: #2079 
Object of test:  Removing the asobo-aircraft-a320-neo file to test aircraft compatiability 

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. removed the file from C:\Users\snayl\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Official\OneStore
2. C&D start from EGNT to EIDW
3. Selected aircraft
4. loaded in C & D turned external power on everything seems fine
5. setup Aircraft then taxi to rwy
6. take off initiated
7.turned AP on

Flight notes (If required): if i did not take manual control of the aircraft i would of crashed plumiting to the ground. Banked right then started to decend rapidly. 

Issues (If Any):
1. Christmas Livery Vanished
2. zoomed in of MCDU and the Radio panel goes dead but zoom out and it appears think not by mouse by keyboard button this is the same i've noticed on Dev Build
3.after take off i turn autopilot on aircraft banked to the right, i turned AP off then on and still would not correct it self. I tried to use HDG and even that would not let me control the aircraft. I had to quit the flight.
4. Would not follow flight plan
Screenshot 2020-12-07 122017
Screenshot 2020-12-07 122206



Overall Rating: Very Poor
Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.

**Comment by Benjozork** [comment]
Closing as outdated and gonna be done in another way

**Pull request closed without merging**
