### PR TITLE
[Textures]4k Texture upgrade (Pedestal and Throttle Unit)

### PR DESCRIPTION
**Pull request by Pleasure0102**
Fixes #[issue_no]

## Summary of Changes

Created 4k variants of the pedestal and throttle unit textures, cleaned up a bit.
Throttle unit a tiny bit more glossy as realistic.

## Screenshots (if necessary)

**BEFORE**
FlightSimulator_2020-11-05_20-19-34
FlightSimulator_2020-11-05_20-19-52
FlightSimulator_2020-11-05_20-20-09
**AFTER**
FlightSimulator_2020-11-05_20-06-45
FlightSimulator_2020-11-05_20-05-26
FlightSimulator_2020-11-05_20-06-06

## References

image

## Additional context

Please check for quality / color etc.

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
> gimme bit time :)

never

**Comment by Oberstumfuher** [comment]
nice work M8!

**Comment by Pushok154** [comment]
Hi guys, nice work, but i think you should  make some corrections to trim wheel scale in accordance with real scale of 320-251(NEO)
image

**Comment by Pleasure0102** [comment]
> Hi guys, nice work, but i think you should make some corrections to trim wheel scale in accordance with real scale of 320-251(NEO)
> image

not currently possible, as they are done via decals, we would have to move. We can look at that once we can do that though

**Comment by stevex77** [comment]
I like this new "clean" textures, but noticed couple of things based on your before / after screenshot and some reference images (incl. yours). I'm looking at it on calibrated EIZO 10 bit panel display:

- New texture seems to be maybe to much "bluish", saturated and "vivid"

- Reference images show this panels more "greyish", less vivid and with little bit more green toning - see provided images
a32n_2
a32n_3
a32n_4
a32n_1

- This little frame around NAV button has still the original color:
NAV_button

Thanks

**Comment by stevex77** [comment]
I've just tried (just quickly, not preciselly) to adjust one of your's "after"
 screenshots to better match these reference images (incl. that one you provided). Please review it on your display / environment and let me know your opinion. Thanks.

x

**Comment by Pleasure0102** [comment]
@stevex77 so on color there are actually afaik 3 options of colors.
RAL 5014 (This is what i chose according to the default color)
RAL 7011
RAL 7031

so the color should be correct. Most images i have for the panels confirm that:
It might look a bit more blueish because of light that you get at that particular time i will ask some pilots to look at it again. And tweak if needed, but technically the color itself is 100% correct :)
image

The Nav frame i did indeed miss :) thank  you. Will update that tomorrow

**Comment by stevex77** [comment]
Thanks for clarification, @Pleasure0102. Lighting was one of my suspects, but I didn't mention it in my comment - sorry. :) The most recent screenshot you posted in your last reply looks great, even on my eizo, almost exactlz what I originally expected/imaginated!

Bottomline: If I would choose from listed RALs, my personal "first" choice will be 7031. 7011 is really neutral/grey - far off from reality. But based on your latest scrnsht I understand your choice (5014), despite fact it seems to be quite blue in real swatches.

**Comment by stevex77** [comment]
So I did some "complex" in-mod testing under different lighting conditions and looks really good.

Day, August 1st 2020, at the gate, about 9:00 AM local timer at KMCO.

CAVOK:
CAVOK

FEW:
Few

SCATTERED:
Scattered

BROKEN:
Broken

OVERCAST:
Overcast

Night, 2:00 AM, away from gate lights

DOME light OFF:
Night_Dome_OFF

DOME light BRIGHT:
Night_Dome_BRT

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 6/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1771
Object of test: Testing new pedestal textures 


Testing technique: Try-out (multiple tests)
Steps you've made to test the Pull Request:

1. Started cold and dark and checked the pedestal textures under different light conditions 
2. Started mid flight while changing the time of day and weather conditions while checking the textures
3. Flew a short flight and did the same.

Flight notes: n/a

Overall Rating: Good

Conclusions of the testing: Another excellent texture upgrade by Pleasure. No noticeable perf drops and looks great to me, thank you!

Pics:
pl11pture
pl22pture
pl33pture

**Comment by SavageHaters** [comment]
Name: Savage_haters#3680
Date of testing: Current date 06/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1771
Object of test: 4k Texture upgrade (Pedestal and Throttle Unit) observsation. 

Testing technique:Looking at it with different light conditions and weather presets
Steps you've made to test the Pull Request:

1. Started cold and dark and checked the pedestal textures under different light conditions
2. Started mid flight while changing the time of day and weather conditions while checking the textures


Flight notes: None

Issues (If Any):None
 
Overall Rating: Good

Conclusions of the testing: Look's beautiful but someone needs to test the FPS impact. Other than that it is brilliant!

**Comment by Pleasure0102** [comment]
@stevex77 
nice and thorough test. You should think about applying as QA :) hit me up on discord if you interested, i will guide you to the right person

**Comment by stevex77** [comment]
@Pleasure0102 thank you for your nice appreciation, I'm just trying. :) Anyway, it would be honor for me (as both pilot and quite 20+ years experienced software developer / team leader and solution architect) to be somehow official part of this excellent and exemplary organized project.

Sorry for OT here - Trying to explain my background and haven't an account on Discord yet but definitely will create one today. ;)

**Comment by Pleasure0102** [comment]
image

fixed. Ready to merge, after confirmation

**Comment by Pleasure0102** [comment]
@stevex77 just pm me there "Pleasure#2299"

**Comment by flythebest** [comment]
A320 IRL Pilot.
Guys, with your graphic changes (VC textures, display unit etc...) you are reproducing the aerosoft airbus. It's almost identical to Aerosoft airbus pro now. But Aerosoft Airbus Pro is far from being a faithful reproduction of an Airbus A320. Do not copy Aerosoft, copy the real Airbus.

**Comment by Benjozork** [comment]
Hello, are you in our discord ? those changes have been approved by IRL pilots and pictures provided by engineers and pilots too.

**Comment by flythebest** [comment]
Yes I'am in discord. 
Even the colors used in the MCDU by the fonts are a copied from aerosoft... You are going in the wrong way guys and that's really a pity because all of you are very talented...

Real Airbus color :
https://fr.wikipedia.org/wiki/Fichier:CP_MCDU.jpg

Aerosoft airbus mcdu fonts color :

https://www.flightsim.com/vbfs/showthread.php?292493-Aerosoft-Airbus-A318-quot-Waypoint-Not-in-Database-quot-Help!!

FBW mcdu font color :

https://user-images.githubusercontent.com/5894146/98079253-c62f6800-1e73-11eb-9f83-10ea337898fa.png


Oh and I forgot, the blue color of Display Unit ! :

https://cute766.info/aerosoft-a320-cold-and-dark-startup-and-mcdu-setup/

Even the new VC cockpit textures seems to be inspired by the one from Aerosoft Airbus.

**Comment by stevex77** [comment]
@flythebest, I can clearly see some inaccuracies in your provided references:

- Image "Real Airbus color" from Wikipedia was uploaded 2012 while first A320neo airborn flight was 2014. Buttons are pretty "scuffed", so this wasn't a brand new aircraft. It's not an A320neo cockipt at all. Moreover, photo was taken with flash and seems to be little bit overexposed / unbalanced.

- This video for example shows A320neo in action (3:10 - 3:49): https://www.youtube.com/watch?v=bdTGF8kLU20, but still, it's taken by small camera and colos aren't therefore accurate. Maybe ours are little bit more staurated which can be simply tweaked.

- There is also the PR (pending at the moment) https://github.com/flybywiresim/a32nx/pull/1342 here which plans to replace MCDU font / colors with one very similar to reality, so please review and consult this PR first, before starting your criticism towards authors within this PR that wasn't related to DUs.

- This work isn't inspired by Aerosoft's. It's based on real-world A320neo references and consultations wih IRL pilots / maintainers of this bird. So it's rather co-incidence than the intention.

- If you're talking about panels color (what was the original scope of this PR), please provide some IRL photos of NEO, better with real color specification (RAL / RGB / ...), so we can re-open this one and tweak it more.

Please provide your Discord nick so we can discuss this more comfortably and with others there.
And btw. These guys are definitely going the good way, btw... ;)

Thanks

**Comment by flythebest** [comment]
Discord : flythebest

Listen, I'm not going to waste any more time explaining something simple to some people who refuse to see and hear and who only insists on copying another project instead of faithfully reproducing reality.

You know nearly nothing about Airbus, you ask for help from experienced pilots and behave like lesson givers. So in this case keep behaving like immature kids and you will see where your project ends.

For your information, but you should know it if you knew the Airbus A320, the color of the panel has not changed since this first a320 model which was a A320-100 back in 1987...

**Comment by wpine215** [comment]
> 
> 
> Discord : flythebest
> 
> Listen, I'm not going to waste any more time explaining something simple to some people who refuse to see and hear and who only insists on copying another project instead of faithfully reproducing reality.
> 
> You know nearly nothing about Airbus, you ask for help from experienced pilots and behave like lesson givers. So in this case keep behaving like immature kids and you will see where your project ends.
> 
> For your information, but you should know it if you knew the Airbus A320, the color of the panel has not changed since this first a320 model which was a A320-100 back in 1987...

Please remain civil and polite in all github discussions. We have a total of 30+ other verified A320 pilots in our server who provide us comprehensive feedback and point out when any of our work is not accurate to the real plane. We also have countless engineers who work even more in-depth with the A320 who provide reference photos for our modelers to use. I don't believe anyone on our core development team even owns the Aerosoft A320, and we most certainly don't use it as a reference considering how lacking it is in faithful reproduction and systems depth.

The MCDU reference pictures you provided show a clear difference in the green text color between our aircraft and the Aerosoft aircraft as well. The bluish display backlighting hue is present in almost any non-OLED and non-CRT display, and has also been confirmed by IRL A320 pilots and has had its color perfected based on their feedback.

If you wish to discuss further, feel free to talk in the #general-displays channel on discord, or DM me (Iceman#5540) and I'm sure we can find some common ground and resolve this.

**Comment by Pleasure0102** [comment]
> Discord : flythebest
> 
> Listen, I'm not going to waste any more time explaining something simple to some people who refuse to see and hear and who only insists on copying another project instead of faithfully reproducing reality.
> 
> You know nearly nothing about Airbus, you ask for help from experienced pilots and behave like lesson givers. So in this case keep behaving like immature kids and you will see where your project ends.
> 
> For your information, but you should know it if you knew the Airbus A320, the color of the panel has not changed since this first a320 model which was a A320-100 back in 1987...

the color used is RAL5014 which from feedback was the correct color, depending on light settings ofc things might look different. I did not look at any aerosoft model... 
that is all i am going to say about that

**Pull request merged**
