### PR TITLE
fix:  windshield wipers animation

### LINKED ISSUE #2716: [REQUEST] Wiper speed is too fast
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Wiper speed is too fast, hope to refer to the real A320.

**References**

sim2020:
https://user-images.githubusercontent.com/11674129/103143067-7a4dc080-474a-11eb-84d5-ef4707228015.mp4

real:
https://user-images.githubusercontent.com/11674129/103143027-78373200-4749-11eb-97a8-b7cc79263a00.mp4

**Additional context**

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by Inexorable95**
Fixes #2716

## Summary of Changes
Improves the speed and movement of the wipers so that they operate more realistically.
⚠ This will not fix the issue about the wipers not wiping the rain drops away, that is an Asobo issue we can't fix ⚠
## Videos
**All the videos are recorded using the Slow mode on the wipers**
**Before :**

https://user-images.githubusercontent.com/76154362/108213471-59dd2980-712f-11eb-8738-64bb8b720d81.mp4

**After (the recording made my sim stutter a bit) :**

https://user-images.githubusercontent.com/76154362/108213476-5c3f8380-712f-11eb-8ae1-37d8ddd97230.mp4

## References

Original video from #2716 :

https://user-images.githubusercontent.com/76154362/108213500-63ff2800-712f-11eb-8b66-97ced95b91e3.mp4

## Additional context
Discord username (if different from GitHub): Inexorable

## Testing instructions

- Turn the wiper rotary knob to "Slow" and check how the wipers behave
- Turn the wiper rotary knob to "Fast" and check how the wipers behave

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by hotshotp — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3577
Tier of testing: 1
Changes to observe: Wipers animation
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned in Rain C&D at EDDP
2.) Turned on bat. and ext. power
3.) Set wipers to slow (compared animation to video)
4.) Set wipers to fast (speed is about double)

The following needs reference, as i'm not a pilot...

Issues: From the video the RL wipers seem to be synced in angle. So start from down at the same moment.

Overall Rating: -

Conclusions of the testing: Speed on slow fits the reference video. Needs more references for the rest.

Hope this helps :-)

**Comment by hotshotp** [comment]
> Issues: From the video the RL wipers seem to be synced in angle. So start from down at the same moment.

This is not correct. See this video https://www.youtube.com/watch?v=Qe4S0LQ4668 at 2:30.

This is solely dependant on how fast both the fo and captain turn on their wipers, they do not sync with each other.

**Comment by marcman86** [comment]
Thx for the reference!

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3577 
Tier of testing: 1

### Changes to observe: Windshield wiper animation

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on runway at VABB
2. Set weather to Rain (for the vibes)
3. Turned on each of the wipers to observe slow and fast movements.

### Overall Rating: Good

### Conclusions of the testing: The wipers (desynced) replicate similar movements on slow and fast modes, which are much more realistic than the original animations. Good to go!

**Comment by kberg93** [comment]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/19/2021
Version of the sim: 1.13.16.0
PR Tested: #3577 
Tier of testing: 1
Changes to observe:
Wipers animation.

Testing technique: Tryout

Steps you've made to test the Pull Request: 
1. Spawn at airport.
2. Run wipers on slow, look for any visual bugs.
3. Run wipers on fast, look for any visual bugs.

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None.

Overall Rating: Good.

Conclusions of the testing: Looks nice and no seen issues for me.

**Comment by OverKillProductions** [comment]
Category: QA Tester/Trial
Name: Discord User #4687
Date of testing: Current date 02/04/2021
Version of the sim: 1.13.16.0
PR Tested: #3577
Tier of testing: 1
Changes to observe:

fix: windshield wipers animation

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
(Testing was done after deleting A32NX from community folder and reinstalling the PR)

TEST 1
1. Cold and Dark 
2. Batteries on
3. Wipers on Fast and Slow
--- Both look great! 
TEST 2
1. Air start
2. Wipers Fast or Slow
---- Don't function at all. 
Test 3
1. Runway start
2. Wipers function as expected and look great!


Flight notes (When done a full flight): N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): From a cold start the wipers look and function great. Though I thought I would try from a hot start and determined the wipers will not function at all when used from the Airstart condition. They work fine from a runway start. 

Overall Rating: Good

Conclusions of the testing: Not sure if this is Asobo or not but I would recommend testing from the airstart position. I know this is likely the least used startup for this kind of aircraft but thought it was worth mentioning.

**Comment by lukecologne** [comment]
@OverKillProductions At what speed were you flying? The wipers can't be operated above 230kts.

**Comment by OverKillProductions** [comment]
> @OverKillProductions At what speed were you flying? The wipers can't be operated above 230kts.

OOOF!! That's right! Disregard TEST 2 = FAIL!

**Pull request merged**
