### PR TITLE
fix(mcdu): appr qnh entry bug

### LINKED ISSUE #4468: Approach Performance QNH ending on 0 not accepted
**Mod Version**

```json
{
  "built": "2021-04-15T21:44:03+00:00",
  "ref": "experimental",
  "sha": "d1026985aa101b317cc2ca0f2c710816a1d4dd06",
  "actor": "aguther",
  "event_name": "manual"
}

```

**Describe the bug**

entering a qnh ending in 0 (29.70) returns format error

**To Reproduce**

1. load into sim
2. MCDU APPR PERF Page 
3. enter qnh inHg ending in 0

**Expected behavior**

value accepted

**Actual behavior**

value not accepted

**References**

https://user-images.githubusercontent.com/72888738/115117634-e1181380-9f9f-11eb-8a04-ba1609fb2e7d.mp4

**Additional context**

Was this working before/when did the issue start occurring?
unknown

Is this a problem in the vanilla unmodded game?
unknown

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #4468

## Summary of Changes

QNH entries in in.Hg with a decimal point and ending in a zero are not accepted. The bug was originally introduced in #1583, the first support for in.Hg. The regex is tested on the parsed float (so it is coerced back to a string), rather than on the original entered string, and the string representation of 29.70 is 29.7, which doesn't meet the format requirements.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Enter QNHs in HPA and in.Hg formats, especially with zeros at the end.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 18.04.2021
Version of the sim: 1.15.8.0
PR Tested: #4478
Tier of testing: 1
Changes to observe: APPR page QNH formats

Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power
3.) Test APPR page QNH formats

- 30, 30.0, 29 or 29.0 shows FORMAT ERROR
- 30.00 or 29.00 is accepted
- 3000 or 2900 is accepted

Issues: -

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Comment by ExampleWasTaken** [comment]
Category: QA Trial
Name: `ExampleWasTaken#0886`
Date of testing: 18/04/2021
Version of the sim: 1.15.7.0 (it didn't update yet)
PR Tested: #4478 
Tier of testing: 1
Changes to observe: fix(mcdu): appr qnh entry bug

Testing technique:
1. Loaded C&D
2. Powered up
3. Entered various formats in APPR QNH page

Issues (If Any): 
- If an invalid inHG is entered it says `FORMAT ERROR` whereas it says `ENTRY OUT OF RANGE` for invalid entered HPA

Overall Rating: Almost GTG
Conclusions of the testing: In order to be consistent I would change the inHG to give the entry message too.

**Comment by ExampleWasTaken** [comment]
I now got the 1.15.8.0. Let me know if I should test again.

**Comment by tracernz** [comment]
Which value are you expecting an entry out of range error for? FMS software rev. 2 accepts in.Hg inputs without the decimal point and attempts to stop you accidentally entering a temperature as in.Hg so... 
- if you enter 4 digits
  - and it starts with 0 or 1, it's treated as hPa and checked against hPa range
  - if it starts with 2 or 3, it's treated as in.Hg and checked against in.Hg range
- if you enter 2 digits starting with 2 or 3, decimal point, then 2 digits, it's treated as in.Hg and checked against in.Hg range
- if you enter 3 digits it's treated as hPa and checked against hPa range
- anything else is a format error

**Comment by ExampleWasTaken** [comment]
> 
> 
> Which value are you expecting an entry out of range error for? FMS software rev. 2 accepts in.Hg inputs without the decimal point and attempts to stop you accidentally entering a temperature as in.Hg so...
> 
>     * if you enter 4 digits
>       
>       * and it starts with 0 or 1, it's treated as hPa and checked against hPa range
>       * if it starts with 2 or 3, it's treated as in.Hg and checked against in.Hg range
> 
>     * if you enter 2 digits starting with 2 or 3, decimal point, then 2 digits, it's treated as in.Hg and checked against in.Hg range (this case maybe should not check if it starts with 2 or 3, but it's actually a special case of the previous one in the code)
> 
>     * if you enter 3 digits it's treated as hPa and checked against hPa range
> 
>     * anything else is a format error

Testing against these conditions again right now.

**Comment by ExampleWasTaken** [comment]
Based on the above conditions everything is met. However, regarding
> * if you enter 2 digits starting with 2 or 3, decimal point, then 2 digits, it's treated as in.Hg and checked against in.Hg range (this case maybe should not check if it starts with 2 or 3, but it's actually a special case of the previous one in the code)

wouldn't it make more sense to treat every entered string of the format `xx.xx` as inHG and then ?

**Comment by tracernz** [comment]
> Based on the above conditions everything is met. However, regarding
> 
> > * if you enter 2 digits starting with 2 or 3, decimal point, then 2 digits, it's treated as in.Hg and checked against in.Hg range (this case maybe should not check if it starts with 2 or 3, but it's actually a special case of the previous one in the code)
> 
> wouldn't it make more sense to treat every entered string of the format `xx.xx` as inHG?

There will be a difference in handling of in.Hg with or without a decimal point if I make it so. Perhaps I should see if I can get one of our FMS rev. 2 pilots to test.

**Comment by sidnov** [comment]
Category: QA Tester/Contributor
Name: sidnov#8337
Date of testing: 19.04.2021
Version of the sim: 1.15.8.0
PR Tested: #4478
Tier of testing: 1
### Changes to observe: QNH input formats

### Testing technique: Tryout

### Steps made to test the Pull Request:

1. Spawned on runway
2. Tested input with valid formats (2992, 29.92, 1024, 992, 0992) Worked as expected
3. Tested input with invalid formats (28, 28.0), gave "FORMAT ERROR"
4. Tested out of range values (1095, 650, 270 etc), gave "ENTRY OUT OF RANGE"


### Issues: -
Anything above 3999 (4500, 4212 etc) input without decimals gives FORMAT ERROR, not sure if this is expected

### Overall Rating: Good

### Conclusions of the testing: 
Fixes the input issues as expected. Might need some cross-checking about the error message.

**Comment by tracernz** [comment]
I didn't get any references, but I decided to make the suggested change (https://github.com/flybywiresim/a32nx/pull/4478/commits/e64b1fa763ed527818b08d150dbfb015852e60c0). Will need a new test please @ExampleWasTaken.

**Comment by ExampleWasTaken** [comment]
> I didn't get any references, but I decided to make the suggested change (https://github.com/flybywiresim/a32nx/pull/4478/commits/e64b1fa763ed527818b08d150dbfb015852e60c0). Will need a new test please @ExampleWasTaken.

Will test it in about 60 minutes.

**Comment by ExampleWasTaken** [comment]
Category: QA Trial
Name: `ExampleWasTaken#0886`
Date of testing: 22/04/2021
Version of the sim: 1.15.8.0
PR Tested: #4478  
Tier of testing: 1
Changes to observe: fix(mcdu): appr qnh entry bug

Testing technique:
1. Loaded C&D
2. Entered various HPA and in.HG values especially with 0s at the end
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: Works as expected. Great work! 👍

**Comment by sidnov** [comment]
### Update to the review:

Tested with the updates in place. Extreme values in "xx.xx" format now throws the out of range error. LGTM! 🚀

**Pull request merged**
