### PR TITLE
fix(mcdu): limit scratchpad to 22 characters

### LINKED ISSUE #4202: MCDU Scratchpad allows infinite number of symbols
**Mod Version**

{
  "built": "2021-03-29T22:59:15+00:00",
  "ref": "autopilot",
  "sha": "d76765816421af5f95a5a239c91b6e58cbd53e7c",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

The MCDU scratchpad allows for inputs that exceeds its physical space.

**To Reproduce**

1. Type in many symbols into the scratchpad until you reach the end and beyond
2. You can type further without seeing it
3.

**Expected behavior**

Length should be limited to the actual scratchpad width.

**Actual behavior**

It goes infinite
image

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by tyler58546**
Fixes #4202

## Summary of Changes

* Limited MCDU scratchpad to 22 characters

## Screenshots (if necessary)

image

## References

image
image

## Additional context

The display can fit up to 24 characters, but the last 2 are reserved for the vertical slew arrows.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by TheSquirtingPantin** [comment]
Category: QA Trial
Name: Discord User Rémi #8871
Date of testing: Current date 07/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4335
Tier of testing: 1
Changes to observe:
Character limitation for MCDU (22 characters)

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. C/D at KDEN
2. Trying to enter more than 22 characters in the MCDU scratchpad
3. 
4.
5.

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): All is working as expected. Limited to 22 characters. Logic of MCDU scratchpad is good.

Overall Rating: 

Conclusions of the testing: LGTM.

**Comment by easyjetsimpilot** [comment]
Category: QA Trial
Name: Discord User Gavin (easyjetsimpilot)
Date of testing: Current date 07/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4335
Tier of testing: 1
Changes to observe: Character limitation on MCDU

Steps you've made to test the Pull Request: Launched A/C in flight over the Atlantic (enables quick spawning). Attempted to enter more than 22 charictoers in the scratchpad on multiple pages. Would not allow and limited to 22 as expected. Well done. 



Overall Rating: Good. 
Conclusions of the testing: Works perfectly well.

**Comment by MisterChocker** [comment]
> Overall Rating:

@TheSquirtingPantin don't forget to add the over all rating of your qa test.

**Pull request merged**
