### PR TITLE
[CDU] Update the waypoint distance and time data on the flight plan

### LINKED ISSUE #248: FMS distance page does not update
FMS distance page does not update

### LINKED ISSUE #1363: [BUG] ETAs wrong in MCDU (either all zeros or going back in time)
**Mod Version**

 
master as of 13.10.2020

**Describe the bug**

The estimated time of arrival at a point is wrong on several intermediate points on the MCDU.

**To Reproduce**

1. Start a flight (probably best C&D and start the plane)
2. Enter a flight into the MCDU, for example EPGD/EPWA
3. Add SID and STAR
4. Add intermediate points (generated by SimBrief or some other flight planner)
5. Look at the ETAs for each point

**Expected behavior**

ETAs beside every waypoint show approximate time of arrival at the waypoint.

**Actual behavior**

It seems like the ETAs are correct for SID, but they are either all zeros or go back in time for the intermediate points. I believe that STAR isn't all correct either, but can't check right now (can't start the game for now)

**References**

Sorry, unfortunately none

**Additional context**

Was this working before/when did the issue start occurring? I have always seen this manifest itself in the flight

Is this a problem in the vanilla unmodded game? I think so, yes, but I haven't played the latest vanilla.

Discord username (if different from GitHub): acro#2421

### LINKED ISSUE #1518: FMC distance to destination not changing during flight[BUG]
**Mod Version**

latest developer version build_info.txt file not found - use auto installer

**Describe the bug**

FMC distance to destination not changing during flight - it stays the same and should be showing nm remaining during flight

**To Reproduce**

1. open any flight plan
2. load into FMC
3. fly the plan

**Expected behavior**
it stays the same and should be showing nm remaining during flight

**Actual behavior**
it stays the same distance at all times

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by lousybyte**
Fixes #248
Fixes #1363 
Fixes #1518

## Summary of Changes

EDITED:

- Time shown will now change from relative to UTC depending on conditions
- Distance to the active waypoint is now updated
- Distance to DEST is now updated
- Distance between waypoints are now differential instead of cumulative
- The ETA for each waypoint is now updated, including ones that were previous 0000
- The ETA to DEST is now updated
- The time when the previous waypoint was reached is now showed
- Updated some colors to be more inline with real life

## Screenshots (if necessary)

EDITED:

Video: [https://youtu.be/NYKhTa4xabM](https://youtu.be/NYKhTa4xabM)

## Additional context

Can ignore this if a bigger change that includes this is coming soon, didn't see any draft or milestone about it.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by armankir** [comment]
Name: Arman#8145
Date of testing: Current date 23/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1505 

Testing technique: Created a flight plan, flew to one waypoint.

Steps you've made to test the Pull Request:

Spawn C&D
Make Flightplan on Simbrief
Input into MCDU
Test distances
Fly to one waypoint and verify functionality

Overall Rating: Good
Conclusions of the testing: No comments besides good work, these minor changes make the plane a whole lot better!

**Comment by Snapmatics** [comment]
Can you do it for the ARRIVAL as well?

**Comment by lousybyte** [comment]
@Snapmatics Not familiar with it, is there an issue opened about it?

**Comment by Snapmatics** [comment]
> @Snapmatics Not familiar with it, is there an issue opened about it?

For example, it stays there all the time. It's hardcoded while you are flying.
image

**Comment by ThePilot916** [comment]
Time to destination seems incorrect on the 2nd half of the screenshot

**Comment by starvingjavi** [comment]
Name: Javi#2557
Date of testing: 24/10/2020
Version of the sim: 1.9.5
PR Tested: #1505 
Object of test: Waypoint distance and time data on MCDU

Testing technique: Start a flight from C&D in IVAO
Steps you've made to test the Pull Request:
1. Start flight from C&D in EDDK
2. Check the MCDU for distance and flight time
3. Continue flying and check for updated waypoint distance and time

Flight notes

Startup: Everything normal

Taxi/Takeoff : Everything normal

Cruise: Everything normal

Descent/Landing: Everything normal

Shutdown: Everything Normal

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Works as described on the references

**Comment by Benjozork** [comment]
rel. #1518

**Comment by lousybyte** [comment]
@ThePilot916 My bad, pushed the wrong one, updated now.
@Snapmatics Those are included as well, can see in the updated screenshot.

**Comment by FartherBranch55** [comment]
This is not working for me; distance not changing on FMC after installing latest version;

2020-10-25 11_46_19-Window
2020-10-25 11_44_57-Window

**Comment by beheh** [comment]
The video does not match the reference.

> When takeoff power is applied, the time changes to UTC and the other displayed times change to ETA (estimated time of arrival) for the waypoints and pseudo waypoints.

I read this as:
- before takeoff, the times are shown in relative terms, with the origin airport being 0000 and the subsequent waypoints being the incremental time (e.g. 0005, 0010 etc.), and
- after takeoff and during the flight, the times are all shown in UTC and as estimated UTC times of arrival - so for example takeoff at 1335, and the next waypoints as 1340 and 1345 respectively.

The video, however, shows an aircraft in flight with relative times.

**Comment by beheh** [comment]
Also, referencing https://www.youtube.com/watch?v=4_IXjoSwdMc#t=3m16s (at 3m16s), you can see:

1. In flight, the UTC label is used both at the top and bottom of the FPLN page together with absolute times
2. Only the currently sequenced (next) waypoint is showing relative distance. The remaining waypoints are shown as incremental distances to each other (this is why the incremental waypoint shows 120nm, but the next ones show 20, 33 and 5nm respectively - the distance between MAXOS and RIXOT is 5nm, not 5nm from current position)

**Comment by lousybyte** [comment]
In my view, it clearly says _"and **the other** displayed **times** change to ETA (estimated time of arrival) **for the waypoints and pseudo waypoints.**"_, but if a real A320 pilot could give a solid feedback on this it would be great.

**Comment by beheh** [comment]
Yeah, I think the choice of words in the document with regards to ETA is poor because it's so ambiguous. I think in the non-literal sense ETA usually refers to a an absolute clock time, not remaining time.

**Comment by lbaron123** [comment]
> Yeah, I think the choice of words in the document with regards to ETA is poor because it's so ambiguous. I think in the non-literal sense ETA usually refers to a an absolute clock time, not remaining time. Real pilot input should help clarify this.

Yes you are right

**Comment by FartherBranch55** [comment]
Is there a procedure on how to test the PR?

**Comment by lousybyte** [comment]
Updated the behavior, new video attached: [https://youtu.be/nNOH13nYl44](https://youtu.be/nNOH13nYl44)

**Comment by beheh** [comment]
The initial switch between TIME and UTC looks great now! The inflight reversion to TIME seems odd, because my understanding from similar addon aircraft is that the reversion to time is mostly just because it doesn't help before takeoff as it would change every minute, so the UTC switch only happens once you're underway. Once you're in the air and go to IDLE you're still underway. I would bet there's an additional "...OR is_in_flight" behavior here in the real aircraft. More detailed documentation or real pilot input may shed more light on this.

Side note: I also seem to remember that a pilot may enter an estimated takeoff time constraint to the departure airport, but I'm not sure how this affects this and it is probably also out of scope for this PR. I could imagine that a pilot manually supplying an estimated takeoff time switches to UTC before takeoff.

My only other remaining concern now is the distances for the waypoints after the sequenced one. From my understanding and using similar addons the distance should only by updated live for the immediately sequenced waypoint, and the remaining ones show the (static) distance between the two waypoints above and below, not the distance from the current aircraft position to the waypoint.

Based on the waypoints in your linked video then I would expect the distances to (very roughly) look like this:

LROP 
35 _(this decreases live to 0 as the aircraft approaches BUKEL)_
BUKEL
16 _(remains static)_
PELUR
37 _(static)_
EDETA
8 _(static)_
MOBRA
...
EDDT08L ... 771 _(decreases live to 0 as the aircraft approaches EDDT)_

...but I would also suggest looking at docs detailing this or getting real pilot input.

**Comment by lousybyte** [comment]
> The inflight reversion to TIME seems odd, because my understanding from similar addon aircraft is that the reversion to time is mostly just because it doesn't help before takeoff as it would change every minute, so the UTC switch only happens once you're underway. Once you're in the air and go to IDLE you're still underway. I would bet there's an additional "...OR is_in_flight" behavior here in the real aircraft. More detailed documentation or real pilot input may shed more light on this.

If you are referring to that quick switch back and forth once in the air, that is due to a flight phase switch, noticed it after I uploaded, currently thinking what's the best way to deal with it since a proper fix breaks other changes.


> My only other remaining concern now is the distances for the waypoints after the sequenced one. From my understanding and using similar addons the distance should only by updated live for the immediately sequenced waypoint, and the remaining ones show the (static) distance between the two waypoints above and below, not the distance from the current aircraft position to the waypoint.

Currently the distances are along the flight path, not direct to. Couldn't find anything specific about this in the Honeywell manual, if anyone can provide input about this would be great, would be easy change.

**Comment by armankir** [comment]
LGTM

**Comment by beheh** [comment]
> If you are referring to that quick switch back and forth once in the air, that is due to a flight phase switch, noticed it after I uploaded, currently thinking what's the best way to deal with it since a proper fix breaks other changes.

Ah, I see it in the code now. Yeah, if the flight phases are bugged themselves then this is fine.

> Currently the distances are along the flight path, not direct to. Couldn't find anything specific about this in the Honeywell manual, if anyone can provide input about this would be great, would be easy change.

The best reference I have is that on various screenshots and videos you'll see that the intermediate waypoints are not strictly incrementing. If the current logic were correct, unless you would be flying a >90° turn, the numbers should always increase, as waypoint N+1 will always be further from the current position than waypoint N. However in the real footage you'll notice that the intermediate waypoints vary wildly ([for example here at 3m16s](https://www.youtube.com/watch?v=4_IXjoSwdMc#t=3m16s) you can see 120 - 20 - 33 - 5 instead of numbers that only go up). If I find any documentation I'll post it here, otherwise a real pilot would probably help.

**Comment by lousybyte** [comment]
Video with the pending changes if it gets confirmed: [https://youtu.be/cqOYT52Tqs0](https://youtu.be/cqOYT52Tqs0)
Changed colors as well.

**Comment by beheh** [comment]
That looks in line with I'd expect with regards to ranges. Let's wait on confirmation there.

And one final thing I noticed: I believe the UTC time for the last waypoint (in the video EDDM) is memorized. So it would stay 1507 until it disappears when ERMEL is reached. The only reference I have for that is my video above yet again where the time on the bottom of the Lower ECAM shows 1121, yet the FPLN shows 1120.

**Comment by lousybyte** [comment]
Was confirmed by two pilots in the Discord, also set the origin UTC static on takeoff. As for additional colors I think it's better for another PR that overhauls the whole design of the page, including font sizes and whatnot.
[https://www.youtube.com/watch?v=NYKhTa4xabM](https://www.youtube.com/watch?v=NYKhTa4xabM)

**Comment by beheh** [comment]
Yep, I agree that that is probably better handled in a separate PR.

I think the memorization also applies to things like executing a DIR to, where the top line is replaced with PPOS or T-P. I'd suggest to also get some feedback from pilots there. Otherwise LGTM from what I can see.

**Comment by FartherBranch55** [comment]
Name: FartherBranch55
Date of testing: 27/10/2020
Version of the sim: 1.9.5
PR Tested: #1518  
Object of test: FMC distance to destination not changing during flight[BUG] #1518

Testing technique: Start a flight from C&D 

Steps you've made to test the Pull Request:

    Start flight from C&D in EDDF
    Check the MCDU for distance to go
    Continue flying and check for updated distance to go

Flight notes

Startup: Everything normal

Taxi/Takeoff : Everything normal

Cruise: Everything normal

Descent/Landing: Everything normal

Shutdown: Everything Normal

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Works as described on the references

2020-10-27 21_57_16-Microsoft Flight Simulator - 1 9 5 0

**Comment by lousybyte** [comment]
Updated after pilot confirmation, updated the PR description as well. Should be the final version now, unless there are any bugs discovered.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 28/10/2020
Version of the sim: 1950
PR Tested: #1505
Object of test: Testing distance and time data on the F-PLN.

Testing technique: Try-out (multiple tests)
Steps you've made to test the Pull Request:

1. Loaded C&D  
2. Completed a full flight from EDDT - LOWW
3. Monitored the time and distance in F-PLN

Flight notes

Startup: All good

Taxi/Takeoff : All good

Cruise: All good

Descent/Landing: All good

Shutdown: All good

Overall Rating: Good
Conclusions of the testing: LGTM, very nice addition to the mod. Thank you for your work!

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 27/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1518
Object of test: Checking MCDU F-PLAN dynamic waypoint distance and time data.

Testing technique: Over last couple days done several flights - short and long ones -  to check functionality. Made complete flight from UAAA to LTFM like normal with time and distance checks en-route. 

Steps you've made to test the Pull Request:

C&D, normal startup, taxi, take off, CLB, CRZ, APP, LDG - to test 
Cross checked distances between waypoints, ETA for waypoints versus OFP and SID/STAR charts, as well as destination ETA. Did the math manually as well for some legs and it made sense. 
All looked fine, used some mentioned references including those above to confirm the changes made. 


Startup: Everything normal. 

Taxi/Takeoff/CLB : Everything normal. The Destination (LTFM35R) waypoint ETA was off and kept changing a lot (bringing it forward) during the flight but mainly during the CLB but without me changing the route. Paying close attention to the switch from Relative time from 0000 to UTC times and that was correct.

Cruise: Everything normal. Cross check values from MCDU to OFP and EN ROUTE charts.

Descent/Landing: Everything normal

Shutdown: Everything Normal

Issues : Keep an eye on destination RWY UTC changing on F-PLAN page. Not major. It was just listed as having been updated in the PR. 
Overall Rating: Good
Conclusions of the testing: Works as described on the references. Dynamic distance to go gives accurate track miles for descent. UTC time for destination RWY was not accurate enough in my opinion until the latter stages of the flight. A great addition to the mod bringing it closer to reality and pretty useful in a practical sense. Thank you!

**Comment by Benjozork** [comment]
Gonna merge this for now, minor issue can be fixed later.

**Comment by danbw9** [comment]
If flight starts before 0000 UTC and ends after it does it seems to want to count the wrong way...destination ETA on F-PLAN page.

Screenshot (453)

**Comment by lousybyte** [comment]
It looks like a problem with the existing function that parses seconds into UTC, will take a look at it.

**Pull request merged**
