### PR TITLE
fix(model): remove blue highlights in lock mode

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Removes the blue highlights on hovering mouse areas in the flight deck with the lock interaction mode. Drilling down through all the Asobo templates, these eventually drive an undocumented param `HighlightNodeId` on the `MouseRect`.

Create a tiny package that can be installed to re-enable the highlighting for the small number of users who desire this (`flybywire-aircraft-a320-neo-lock-highlight`).

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check that there are no blue highlights when hovering controls using lock mode, and that everything works normally. Try legacy mode as well.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by crotchetycoder** [comment]
Does this remove all highlighting in lock mode?  😭 

I might not be representative of the majority of users (that use lock mode), but personally I see the highlighting as one of the main reasons to use lock mode in the first place. Being able to exactly see which button/knob/lever I'm going to be interacting with is extremely helpful to me. Especially for elements in close proximity to each other (e.g. outer/inner knobs, guards next to buttons, ...).

I understand there's most likely a very good reason to do this. I'll see if I can mod this back in on my install somehow.

**Comment by ErickSharp** [comment]
> Does this remove all highlighting in lock mode? 😭
> 
> I might not be representative of the majority of users (that use lock mode), but personally I see the highlighting as one of the main reasons to use lock mode in the first place. Being able to exactly see which button/knob/lever I'm going to be interacting with is extremely helpful to me. Especially for elements in close proximity to each other (e.g. outer/inner knobs, guards next to buttons, ...).
> 
> I understand there's most likely a very good reason to do this. I'll see if I can mod this back in on my install somehow.

@tracernz I do agree that this could be of use to a lot of people for accessibility or simply preferential reasons. Is there a way that we could read from a SimVar in the XML and make this configurable, or is this something that is intentionally fixed in place?

**Comment by tracernz** [comment]
Seems to need to be static, at least with the way the Asobo templates are written.

**Review by bouveng — APPROVED** [review]

**Comment by 2hwk** [comment]
IMO this needs more consideration, so I'm moving it into the relevant project spaces/tags

**Comment by tracernz** [comment]
This is disappointing and unfortunate.

**Comment by ErickSharp** [comment]
> This is disappointing and unfortunate.

☹️☹️

**Comment by Genau6502** [comment]
Much as it appears to fix an issue, it also removes the most useful feature of lock mode: the highlighting. Perhaps it should be reconsidered whether that is something worth fixing, given the issue can be solved by switching to legacy (as I understand it), and that it removes the key feature of lock mode. I'm sure most lock mode users would be willing to accept some issues in return for keeping that feature.

(From discord)

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7338
Tier of Testing  : 1
Date             : 04/08/2022

Testing Process: 
Check that there are no blue highlights when hovering controls using lock mode, and that everything works normally. - **OK**
Try legacy mode as well. - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Quality Assurance Report

Discord: 2Cas#1022
Object of testing: https://github.com/flybywiresim/a32nx/pull/7338
Tier of Testing: 1
Date: 12/08/2022

Testing Process:
- [x] Check that there are no blue highlights when hovering controls using lock mode, and that everything works normally. Try legacy mode as well. 

Negatives: N/A

Testing Results: Pass

**Comment by tracernz** [comment]
> Does this remove all highlighting in lock mode? 😭
> 
> I might not be representative of the majority of users (that use lock mode), but personally I see the highlighting as one of the main reasons to use lock mode in the first place. Being able to exactly see which button/knob/lever I'm going to be interacting with is extremely helpful to me. Especially for elements in close proximity to each other (e.g. outer/inner knobs, guards next to buttons, ...).
> 
> I understand there's most likely a very good reason to do this. I'll see if I can mod this back in on my install somehow.

Package to re-enable highlights in lock mode (built from a32nx master):
[flybywire-aircraft-a320-neo-lock-highlight.zip](https://github.com/flybywiresim/a32nx/files/9331234/flybywire-aircraft-a320-neo-lock-highlight.zip)
Drop in your community folder.

**Pull request merged**
