### PR TITLE
fix: model script issues

### PR DESCRIPTION
**Pull request by tyler58546**
Replaces #4851 

## Summary of Changes

* Fixed invalid material references in some LODs
* Fixed invalid byte offsets
* Fixed nodes existing more than once in the hierarchy
* Fixed extensions not being added to `extensionsUsed`
* Removed duplicate materials

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Make sure there are no issues with model modifications.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by pepperoni505 — APPROVED** [review]

**Comment by St54Kevin** [comment]
@tyler58546 So what do we have to look for specifically? I dont know what model modifications we have

**Comment by tyler58546** [comment]
> 
> 
> @tyler58546 So what do we have to look for specifically? I dont know what model modifications we have
here are some of the things added:
- adirs on bat light
- efb
- printer
- display glass
- coffee cup
- brake fan button
- registration decal
- dome lights
just make sure they all look correct and there's no new issues related to the model

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 20/05/2021
Version of the sim: 1.15.10.0
PR Tested: #4857 
Tier of testing: 1
Changes to observe: correct model mods

**Steps you've made to test the Pull Request:**

1. Loaded onto gate and powered up
2. Checked:
- adirs on bat light
- efb
- printer
- display glass
- coffee cup
- brake fan button
- registration decal
- dome lights

**Media:**

**Issues (If Any):** - 

**Conclusions of the testing:** LGTM

**Comment by ElonKerman** [comment]
Category: QA Tester
Name: Elon Kerman#9253
Date of testing: 20/05/2021
Version of the sim: 1.15.10.0
PR Tested: #4857
Tier of testing: 1
Changes to observe: correct model mods


Steps you've made to test the Pull Request:


Loaded onto gate and powered up
Checked:
adirs on bat light
efb
printer
display glass
coffee cup
brake fan button
registration decal
dome lights

Media: N/A

Issues (If Any): none


Conclusions of the testing: LGTM

**Comment by ItzCryptiic** [comment]
Category: QA Trial
Name: Cryptiic#8175
Date of testing: 18/05/2021
Version of the sim: 1.15.10.0
PR Tested: #4857

Tier of testing: 1

Changes to observe: correct model mods

Steps you've made to test the Pull Request:

  1. Spawned Cold & Dark at EDDS
  2. Started aircraft up (Before start up Checklist)
  3. Checked the Following things:
   3.1 adirs on bat light (Needs Improvement)
   3.2 efb (Good)
   3.3 printer (Good)
   3.4 display glass (Good)
   3.5 coffee cup (Good)
   3.6 brake fan button (Good)
   3.7 registration decal (Good)
   3.8 dome lights (Good)

Media: N/A

Issues (If Any):
ADIRS On Bat light turns on after turning ALL the knobs to NAV, I waited if I just need to wait, but it does not appear when I'm just turning one knob.

Overall Rating: Needs Improvement
Conclusions of the testing: ADIRS ON Bat light is only turning on after every knob got turned to NAV.

**Comment by tracernz** [comment]
> ADIRS On Bat light turns on after turning ALL the knobs to NAV, I waited if I just need to wait, but it does not appear when I'm just turning one knob.

It turns on with one, at least last time I checked, but there is a 10 second gap between turning the knob to NAV, and the ON BAT test, per our neo references (there are plenty of videos with older ceo ADIRS being much faster).

**Comment by ItzCryptiic** [comment]
> > ADIRS On Bat light turns on after turning ALL the knobs to NAV, I waited if I just need to wait, but it does not appear when I'm just turning one knob.
> 
> It turns on with one, at least last time I checked, but there is a 10 second gap between turning the knob to NAV, and the ON BAT test, per our neo references (there are plenty of videos with older ceo ADIRS being much faster).

Hey sorry just noticed that. I was a bit confused because I some Videos which it was much faster and the 3 knob was aligned much faster. However thanks for telling me the PR is changed to the correct information.

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 21/05/2021
Version of the sim: 1.15.10.0
PR Tested: #4857
Tier of testing: 1
Changes to observe: Check fixes for correct model script *stuff*

Steps you've made to test the Pull Request:

1. Spawned C&D - power to a/c
2. Checked ADIRD On Bat Light function, EFB, Printer, Display, Coffee Cups and Reg Decal, Brake Fan button, and Dome Lights throughout
3. Full Flight Corfu to Samos
4. Tested wider general functionality of aircraft in conjunction with this PR
5. Landed, taxi to gate, shut down

Media: N/A

Issues (If Any): None found

Conclusions of the testing: LGTM

**Pull request merged**
