### PR TITLE
[CDU] Add support for magenta text color and correct some elements in the vertical revision page

### PR DESCRIPTION
**Pull request by lousybyte**
N/A

**Summary of Changes**

Add the ability to highlight the text in magenta in the CDU and also use that to improve the vertical revision page.

**Screenshots (if necessary)**

BEFORE
AFTER

**References**
[https://www.theairlinepilots.com/forumarchive/a320/a320-fms-pages.pdf](https://www.theairlinepilots.com/forumarchive/a320/a320-fms-pages.pdf)

**Additional context**

For testers make sure to run `build.py` before starting the game since a new file was added.

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by nasjoh** [comment]
When I tried to color match with another A320 MCDU, the magenta should be a little bit stronger, it's a bit to whitish

**Comment by Lucky38i** [comment]
have you tried colors going from magenta back to something else like white,blue, etc. I think the FMCMainDisplay has a color list and since magenta isn't there it won't be able to remove it

**Comment by lousybyte** [comment]
All the colors are a bit washed out, chose one to be inline with the general aspect. If anyone is up to change them all for a better look that would be great.

**Comment by Externoak** [comment]
Is it decided that the FMCMainDisplay.js is moved to A32NX_FMCMainDisplay.js?

**Comment by Benjozork** [comment]
Hello, please take note that we have started including a CHANGELOG.md file that requires every PR to add a change-log line that describes its changes. As your PR is not merged yet, we kindly ask that you add this information following the included directives in the file.

Disclaimer: This is a copy-and-pasted message.

**Comment by lousybyte** [comment]
Updated.

**Comment by lousybyte** [comment]
Hold this until #888 is merged, can commit a better color value in this same PR after.

**Comment by Lucky38i** [comment]
> Hold this until #888 is merged, can commit a better color value in this same PR after.

are the colors off?

**Comment by lousybyte** [comment]
No, will have to correct this magenta color to be in line with the new colors from that PR.

**Comment by AdenFlorian** [comment]
#888 has been merged

**Comment by lousybyte** [comment]
Will open a new PR to keep commits clean, a lot has changed.

**Pull request closed without merging**
