### PR TITLE
[MCDU] Fixed bad error message handling (critical bug)

### LINKED ISSUE #1916: [BUG] MCDU duplicated input
**Mod Version**
 current master(2020/11/14)

**Describe the bug**

when i input some value(let's value1) to MCDU some page, and i change page and try to write some value, value 1 value still remain MCDU

**To Reproduce**

1. for example, insert VOR freq on RAD NAV page on MCDU
2. going to INIT page
3. try to write Cost Index but there is a value still remaining

i write vor freq on RAD NAV page and going to init

when i press 4 for change costindex but there still value remain on mcdu

**Expected behavior**

must no value remain on mcdu

**Actual behavior**

remain on mcdu

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #1916

## Summary of Changes

- Fixed scratchpad gets deleted (empty error message was shown, was not a bug, just a bad error message)
- Improved error message handling

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
Have you tested this yourself ?

**Comment by MisterChocker** [comment]
yes

**Comment by Benjozork** [comment]
Gonna merge it quickly since it's quite important

**Comment by MisterChocker** [comment]
The problem was, that an empty error message was used to clear the error message display in mcdu menu and to clear possible user input.

**Comment by Kimbyeoungjang** [comment]
wow... fast hotfix! thank you for your work :)

**Comment by MisterChocker** [comment]
Thx, not sure how this slipped through testing.

**Comment by stevex77** [comment]
Confirm working perfectly! Thanks for quick hotfix!

**Pull request merged**
