### PR TITLE
[CDU] Fix airways page after 1.8.3

### LINKED ISSUE #798: [BUG] MCDU not able to show added waypoints or airways into flightplan
**Mod Version**
master

**Describe the bug**
When making adding a flight plan manually in the MCDU, when trying to add airways or waypoints they will not appear after being added, even though the page seems to have accepted the waypoint.

**To Reproduce**

1. Start flight at gate
2. Start airplane normally
3. Input FROM/TO on MCDU
4. Select F-PLAN button
5. Select starting airport. Select DEPARTURES. Select the departure runway and procedure. Select "TMPY INSERT*"
6. Select the last waypoint on flight plan. Select "AIRWAYS>". Write the next waypoint in the flightplan and write it under "TO".

**Expected behavior**
Airway or waypoint would appear after they are input in the MCDU.

**Actual behavior**
If the bug happens you won't be able to see what you just input, but the you will get a message to insert said waypoints into the flightplan

**References**
Captura de pantalla 2020-09-21 231211
Captura de pantalla 2020-09-21 231228

Discord username (if different from GitHub): javi#2557

### PR DESCRIPTION
**Pull request by lousybyte**
Fixes #798

**Summary of Changes**

Fixes the airways page after the most recent update, should work as before now.

**Screenshots (if necessary)**

https://youtu.be/VSqSoNgb8-k

**Additional context**

Discord username (if different from GitHub):

### CODE REVIEW

**Review by UncleClapton — APPROVED** [review]
LGTM! Ready for QA

**Comment by noga-aviator** [comment]
just tested seems to be working

**Review by AdenFlorian — APPROVED** [review]
ready to test!

**Comment by tareksabet** [comment]
Everything works fine

**Comment by NathanInnes** [comment]
Are we sure this is working? I seem to be having issues inserting data into airways page.

I click on a VOR. Insert airway and doesn't do anything.

**Pull request merged**
