### PR TITLE
[PFD] Add QNH Flashing when reach transition altitude

### LINKED ISSUE #2006: [REQUEST] PFD - QNH/STD should blink when QNH/STD-selection is not correct
**Mod Version**

master

**Describe the bug**

On the PFD below the speed tape, there is a QNH value with the selected QNH or "STD" when in STD mode. 
This text should flash, if
* in climb mode, above transition altitude and still QNH selected
* in descent / approach, below transition level and still STD selected

**To Reproduce**

1. Climb above transition altitude, keep QNH selected instead of STD

**Expected behavior**

s. above

**Actual behavior**

QNH / STD is always static, no blinking

**References**

from FCOM, DSC-31-40
image

**Additional context**

n/a

Was this working before/when did the issue start occurring?
n/a

Is this a problem in the vanilla unmodded game?
don't know

Discord username (if different from GitHub):
n/a

### PR DESCRIPTION
**Pull request by Kimbyeoungjang**
Fixes #2006

## Summary of Changes

add qnh flashing when reach transition altitude

## References

https://www.youtube.com/watch?v=UWLYjD6P-RU

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Kimbyeoungjang** [comment]
i'm working this(that commits are my old repo, just ignore it XD)

**Comment by Kimbyeoungjang** [comment]
finished my work :)

**Comment by Snapmatics** [comment]
> finished my work :)

Read to Test?

**Comment by Kimbyeoungjang** [comment]
> > finished my work :)
> 
> Ready to Test?

yes!

**Comment by Lucky38i** [comment]
> > > finished my work :)
> > 
> > 
> > Ready to Test?
> 
> yes!
@Kimbyeoungjang 
if you can please squash all your commits. Makes it easier for the core dev to reverse changes if needed

**Comment by Kimbyeoungjang** [comment]
> > > > finished my work :)
> > > 
> > > 
> > > Ready to Test?
> > 
> > 
> > yes!
> > @Kimbyeoungjang
> > if you can please squash all your commits. Makes it easier for the core dev to reverse changes if needed

ok. but i have to remove all pr and repo(because i'm working on branch master, i'm idiot). please wait

**Comment by Kimbyeoungjang** [comment]
recreate pr for cleanup

**Pull request closed without merging**
