### PR TITLE
[CDU] Added ATSU ATC Pages

### PR DESCRIPTION
**Pull request by chloe1192**
## Summary of Changes

- [x] [ATSU] ATC pages
- [x] [ATSU] Connection Status page
- [x] [ATSU] Connection Notification page
- [x] [ATSU] Position Report page
- [x] [ATSU] Departure Request page
- [x] [ATSU] Comm Menu page
- [x] [ATSU] Datalink Status page
- [x] [ATSU] Request page

## References

https://youtu.be/E8IjkgQjw2M?t=1240
https://www.youtube.com/watch?v=6rLeQklVoAk

## Additional context

Discord username (if different from GitHub): chl0e#9587

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
cc. @wpine215

**Comment by wpine215** [comment]
Based on the reference, looks like the second page is missing the "-----ATS623 PAGE------" subheading under the main title - would be nice to add. Otherwise LGTM!

**Comment by Snapmatics** [comment]
If pages are not operational make sure to change the text to a grey color. If your intentions are to make them operational then it's fine. LGTM, just read what Wpine sent above.

**Comment by chloe1192** [comment]
> 
> 
> If pages are not operational make sure to change the text to a grey color. If your intentions are to make them operational then it's fine. LGTM, just read what Wpine sent above.

I plan to add them if i find any reference, but ill change them to grey for now.

**Comment by chloe1192** [comment]
> 
> 
> Based on the reference, looks like the second page is missing the "-----ATS623 PAGE------" subheading under the main title - would be nice to add. Otherwise LGTM so far!

added

**Comment by wpine215** [comment]
>     * [ ]  Integrate with Hoppie
> 

Just a heads up: at the moment, we don't have any plans to integrate CPDLC with Hoppie, considering it's a fairly outdated system. I believe some virtual ATC networks are planning to introduce their own integrated CPDLC system sometime next year, so we'll probably hold off until then before implementing any functionality on our side.

**Comment by chloe1192** [comment]
> 
> 
> > ```
> > * [ ]  Integrate with Hoppie
> > ```
> 
> Just a heads up: at the moment, we don't have any plans to integrate CPDLC with Hoppie, considering it's a fairly outdated system. I believe some virtual ATC networks are planning to introduce their own integrated CPDLC system sometime next year, so we'll probably hold off until then before implementing any functionality on our side.

Ok, so ill just keep with the visual things for now.

**Review by wpine215 — APPROVED** [review]

**Comment by Benjozork** [comment]
@chloe1192 can we mark this ready for review ?

**Comment by chloe1192** [comment]
> 
> 
> @chloe1192 can we mark this ready for review ?

Still need some minor changes, probably will be ready tomorrow.

**Comment by z0rgmeister** [comment]
Category: QA Tester
Name: z0rgmeister#8972
Date of testing: 02/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2019
Object of test: Test Added ATSU Pages

Testing technique: Started at runway, accessed pages as per PR
Steps you've made to test the Pull Request:
1. Spawned at runway EGCC
2. Accessed MCDU ATC pages
3. Verified pages active

Flight notes (If required): NA

Issues (If Any): NONE (not sure what functionality is required for these pages but assuming these are just placeholder for future implementation)
Overall Rating: Good
Conclusions of the testing: LGTM

**Comment by beheh** [comment]
Why was the `.husky/pre-commit` file removed as part of this PR? Why was `FINALFLAPS.wav` added?

**Comment by chloe1192** [comment]
> 
> 
> Why was the `.husky/pre-commit` file removed as part of this PR? Why was `FINALFLAPS.wav` added?

The ".husky/pre-commit" was because i couldn't commit the changes and probably the change got pushed into the PR by mistake. The "FINALFLAPS.wav" might be something i merged by mistake while trying to base on the latest master branch.

Since it was the first time using GitHub properly i might have done some mistakes when pushing commits.

**Comment by Benjozork** [comment]
The file is indeed here to prevent you from committing bad code that contains formatting / code problems. Not to criticize your code at all, but that might be why you couldn't commit.

I suggest in the future you ask for assistance on Discord when encountering such problems

**Pull request merged**
