### PR TITLE
docs(readme): updated simbrief profile to A20N

### PR DESCRIPTION
**Pull request by St54Kevin**
## Summary of Changes

Simbrief recently integrated a new A20N profile with correct performance and fuel flow parameters. This PR takes over the weight values of our "old" simbrief profile into a new one with the correct airframe. This should fix wrong fuel calculations in the future and will set the correct airframe when prefiling an online network flight plan.

**Profile Link:**
https://www.simbrief.com/system/dispatch.php?sharefleet=eyJ0cyI6IjE2MjAxMzg2MDY1NDQiLCJiYXNldHlwZSI6IkEyME4iLCJjb21tZW50cyI6IkZCVyBBMzJOWCIsImljYW8iOiJBMjBOIiwibmFtZSI6IkEzMjBORU8gRkJXIiwiZW5naW5lcyI6IkxFQVAtMUEyNiIsInJlZyI6IkQtQUZCVyIsImZpbiI6IiIsInNlbGNhbCI6IiIsImhleGNvZGUiOiIiLCJjYXQiOiJNIiwicGVyIjoiQyIsImVxdWlwIjoiU0RFMkUzRkdISUoxUldYWSIsInRyYW5zcG9uZGVyIjoiTEIxIiwicGJuIjoiQTFCMUMxRDFPMVMyIiwiZXh0cmFybWsiOiIiLCJtYXhwYXgiOiIxODAiLCJ3Z3R1bml0cyI6IktHUyIsIm9ldyI6IjQxMDA1IiwibXpmdyI6IjY0MzAwIiwibXRvdyI6Ijc5NDAwIiwibWx3IjoiNjc0MDAiLCJtYXhmdWVsIjoiMTkwNDUiLCJwYXh3Z3QiOiIxMDQiLCJkZWZhdWx0Y2kiOiIiLCJmdWVsZmFjdG9yIjoiUDAwIiwiY3J1aXNlb2Zmc2V0IjoiUDAwMDAifQ--

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Click the new link and see if you can save the airframe to your simbrief aircrafts.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
A couple of the weights here look a little off for WV-055. This should be correct: https://github.com/flybywiresim/a32nx/pull/3474/commits/8d07c4a5adb8ed21e50493adb7928ceb0122af95#diff-509e17daa25aa908f9f86baee0f0a67728139f975f8742ef11aab5872df3f436R18-R25

For fuel, I'm not sure how we should handle the difference in volume->weight conversion (see testing instructions on https://github.com/flybywiresim/a32nx/pull/4391 for more).

**Comment by St54Kevin** [comment]
> A couple of the weights here look a little off for WV-055. This should be correct: [8d07c4a#diff-509e17daa25aa908f9f86baee0f0a67728139f975f8742ef11aab5872df3f436R18-R25](https://github.com/flybywiresim/a32nx/commit/8d07c4a5adb8ed21e50493adb7928ceb0122af95#diff-509e17daa25aa908f9f86baee0f0a67728139f975f8742ef11aab5872df3f436R18-R25)
> 
> For fuel, I'm not sure how we should handle the difference in volume->weight conversion (see testing instructions on #4391 for more).

Updated the weights to the ones provided by you. I need to check ingame again to adjust total fuel and empty weight

**Comment by MisterChocker** [comment]
Btw the official Reg is D-AFBW

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by donstim** [comment]
You have the maximum ramp weight in the for the maximum takeoff weight. The maximum takeoff weight is 79 T even. Otherwise, looks great!

**Pull request merged**
