### PR TITLE
build: cargo workspace at the project root

### PR DESCRIPTION
**Pull request by davidwalschots**
## Summary of Changes
By having the cargo workspace at the project root, one can develop in
our whole codebase at the same time. Earlier one needed to have two
instances of e.g. vscode open to work on both HTML/JS and Rust.

## Additional context
Discord username (if different from GitHub): SjotgunSjonnie#9623

## Testing instructions
No testing necessary.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by ZigTag — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
Is this not really a vscode issue ?

**Comment by davidwalschots** [comment]
@Benjozork I don't know what other editors expect. I'm assuming they also don't like having the Cargo workspace defined in a subsubsub directory. Basically this is equal to putting `package.json`, `.editorconfig`, `jsconfig.json`, and others at the root; such that editors can pick it up.

**Comment by Benjozork** [comment]
It works in my editor without any issues.

I'm fine with the PR, just confused as to why it's a problem in the first place. I thought we could eventually move everything to sub directories where they belong, but if vscode can't handle that...

**Pull request merged**
