### PR TITLE
fix: reduce aggressiveness of the auto sim rate reduction

### LINKED ISSUE #5849: automatical simrate reduce mechanism not optimal
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-18T17:47:55+00:00",
  "ref": "master",
  "sha": "363a5fac10e2790fa29ee9628c62a0fa8f742cd4",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

Since the introduction of the automatic reduction of the simualtion rate from 4x -> 2x -> 1x, the use of higher rates is no longer possible in a meaningful way. 

I have a high performance setup 
i7-10000k @ 5.2
rtx3080 @ 60fps stable @ ultra

In a longer test I noticed that in different situations e.g. ATC requests or every few minutes it comes to small frame drops. This causes the reduction of the newly implented mechanism. Despite this, the frame rate is on average around 60fps. 

### Expected behavior

The use of a maximum sim rate of 2x / 4x , or at least have the decision to use it. 

I understand the reason behind it, but at least more experienced users should be given the opportunity to use this feature, even if it could cause performance problems. 

### Steps to reproduce

1. full flight EGPE -> ENAT
EPGE DCT PIPEM L613 BAMRA DCT RIXUN/M079F370 DCT BARUD/N0452F370 DCT NOGBO/N0447F390 T65 GILEN DCT BDF Z205 BADIX BADI1Q ENAT
2. multiplayer live & 3. weather disabled (clear sky)
3. using 4x over the sea between UK and Norway

### References (optional)

_No response_

### Additional info (optional)

I never had problems with the higher sim rate (max. 4x). Never oszilation or other issues. 

### Discord Username (optional)

MIHU#8724

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes #5849

## Summary of Changes

This PR changes the following things: 
* it reduces the minimum required simulated before the simrate is reduced, from around 17 * simrate fps, to 9 * simrate fps. (So for example at 4x simrate, a minimum of 9 * 4 = 36fps is required)
* it introduces a frame counter, which begins to count up once the actual FPS is below the required FPS.
  Once the counter increases above 10 frames, the sim rate will be reduced. If the FPS increases above the threshold again, the counter will be reset. This is done to stop a reduction of the simrate at short low-FPS spikes, which would not compromise the stability of the control laws.
* it reduces sim rate also in abnormal situations:
  * Pitch: more than 20° or less than -10°
  * Bank: more than 33°
  * Protections: high speed, high angle of attack or AP speed protection
* it allows to disable performance / abnormal situation based simulation rate reduction by setting parameter `SIMULATION_RATE_REDUCTION_ENABLED` in section `AUTOPILOT` in configuration file `ModelConfiguration.ini` to `false`.

All in all, the amount of nuisance sim rate reductions should be significantly reduced, while also ensuring stability of the FBW and AP systems.

## Additional context

* These changes were originally tested by me in conjunction with the roll law introduced in #5842. Stability with the current roll law in master cannot be guaranteed.

Discord username (if different from GitHub): lukecologne#1156

## Testing instructions

* Fly the aircraft both in manual flight and with AP engaged, at multiple different simrates, FPS, and flight situations and make sure that no oscillations occur, in the roll axis or otherwise.
* Also make sure that for example in cruise, the simrate is not falsely reduced although the FPS criterion explained in the summary of changes was met.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
It would be nice to display a notification when the sim rate is reduced

**Comment by lukecologne** [comment]
Currently a message will be written to the console when the simrate is reduced, but that is obviously not ideal. Not sure how it could be improved, maybe with the sims message system, but I don't know if that can be accessed from WASM

**Comment by 2hwk** [comment]
> Currently a message will be written to the console when the simrate is reduced, but that is obviously not ideal. Not sure how it could be improved, maybe with the sims message system, but I don't know if that can be accessed from WASM

Possible in JS/React, see https://github.com/flybywiresim/a32nx/pull/5261

**Review by aguther — APPROVED** [review]

**Comment by ShadowFrost3** [comment]
Quality Assurance Trainee Report


Object of testing: #5863
Tier of Testing:
Date: 21/09/2021

Testing Process: 
C&D Start
Could time accel to x4 with ~40+ frames
verified bank limits
verified pitch limits
verified overspeed limit
verified AOA protection limit
Negatives:
Testing Results: N/A
Conclusions: Was tested with the new roll control laws as well and passed, will retest with this PR only. 
Media:

**Comment by stmihajlo** [comment]
I created a ModelConfiguration.ini file in the work folder and put in the line to disable the automatic sim rate reduction. I'm well informed that this can cause some Autopilot issues. Now i have a problem, as I was able to use a sim rate of 4 times in cruise phase in the older versions of the A32NX currently I'm not anymore. After reaching about 10000 feet at simrate x4 my plane starts to roll unrecoverably to the left and right and than crashes. Once again I am aware of the own risk when disabling the auto reduction but my question is, will this be fixed in the near future so I can use a simrate of 4x again. It will be really sad if this will stay like this. Maybe its someting to do with the new implemented roll law. In the older experimental versions I was able to cruise with simrate 4x and I had no problems with the crazy Autopilot at all. I had a really nice experience right then and I hope this will be able again. Thanks in advance and I'm really sorry I'm not trying to speed up the proces or be inpatient but I'm only wondering if this will be fixed.

**Comment by ShadowFrost3** [comment]
Ill go ahead and ask so I can test to recreate, all the information you can think of. What departure, what star, altitude it started at, frame rate, level of time accel (4x), did time accel stop at a bank limit and the aircraft regain controllability? Did the aircraft remain in an upset state? Message me on discord if necessary @ Shadowfrost3

**Comment by aguther** [comment]
What frame rate do you have?

**Pull request merged**
