### PR TITLE
Improvements to Flightmodel, PFD Speedband and calculations for various speeds

### LINKED ISSUE #2027: [BUG] Aircraft regains altitude at nose up before touchdown
**Mod Version**

{ "built": "2020-11-19T14:59:45+00:00", "ref": "refs/heads/master", "sha": "5e57e8dd9fbcf3cbbefd119606df2576da85bd7e", "actor": "Benjozork", "event_name": "push" }

**Describe the bug**

I won't use very technical words because I'm not a pilot at all. During an approach, just before touchdown, as soon as I raise the nose of the plane a little bit to put the rear landing gear before the front, the plane goes up instead of continuing to descend the last feet.

**To Reproduce**

1. Doing an ILS approach (but I don't think this is related to the type of approach)
2. Approach at a speed of about 132 kts in a normal landing configuration
3. Disable the AP before the minimums
4. Just before touching, raise your nose a little

**Expected behavior**

With Flight Factor's A320 Ultimate, I don't see the same behavior, the plane continues to descend smoothly.

**Actual behavior**

The plane regains altitude despite the low speed and the approach.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Sorry, I don't know.

Is this a problem in the vanilla unmodded game?
I can't say because I haven't tested.

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #2027

## Known Issues
Slats are currently not being simulated correctly by the engine. Therefore we had to find compromises, see [Stall Speeds and Pitch Angles](https://github.com/flybywiresim/a32nx/files/5579383/Stall.Speeds.and.Pitch.Angles.pdf) for reference.

## Summary of Changes

- Flightmodel
   - Reworked Coefficient Lift vs Angle of Attack table.
   - Reworked FLAPS
   - Reworked Pitch for all phases of flight.
   - Adjusted Drag/Thrust balancing

- PFD
   - VLS, Vaprot, Vamax and Vs are now calculated by us.
   - Visual improvements to Vls and Vaprot
      - Increased stroke size, tweaked gap-sizes
   - added mach correction
   - changed green dot calculation
   - v1 disappears now after liftoff
   - GD only visible in clean config

- Moved speed calculations to Core
   - Vs
   - Vamax
   - Vaprot
   - Vls
   - F
   - S
   - GD
   - added simple calculation for V2 based of #1777

## Screenshots (if necessary)

| Takeoff | Approach (FLAPS3, Speedmode Managed) | Cruise |
| ----- | ----- | ----- |
| image | image | image |

| GD before | GD after |
| ----- | ----- |
| image | image |

| At cruise level and cruise speed |  |
| ----- | ----- |
| image |  |

## References

[vs and vls speeds](https://github.com/flybywiresim/a32nx/files/5590480/A320_Stall_and_VLS_speeds_rev.pdf)
### -251:
[320NEO_2.zip](https://github.com/flybywiresim/a32nx/files/5469381/320NEO_2.zip)
[A320-251_flight_performance.zip](https://github.com/flybywiresim/a32nx/files/5469382/A320-251_flight_performance.zip)
image
image
image
image

### -214:
[crz_A320-214.txt](https://github.com/flybywiresim/a32nx/files/5469384/crz_A320-214.txt)
[dsc_A320-214_1.txt](https://github.com/flybywiresim/a32nx/files/5469385/dsc_A320-214_1.txt)
[clb_A320-214_1.txt](https://github.com/flybywiresim/a32nx/files/5469386/clb_A320-214_1.txt)

## Additional context

Optimizing drag/thrust ratio to work with current engine model.

Discord username (if different from GitHub): 
- @donstim donbikes#4084
- @MisterChocker DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by donstim** [comment]
Also corrects CLmax to provide match of 1g stall speeds with the real airplane. This will provide better handling at low speed/high angle-of-attack and prevent the airplane from stalling before the high-angle-of-attack protection can do its job.

PFD speed tape VLS, V alpha prot, and V alpha max indications should be improved a bit, but they will still not be correct. This will need some external coding to correct (hint, hint for you coders). VLS indication for Conf FULL should be pretty good. Not so good for intermediate flaps, and is incorrect for flaps up because Asobo apparently used. 1.23 *Vs1g clean instead of 1.28.

**Comment by lousybyte** [comment]
I remember some discussion about flap drag being too low and causing overshoot on approach due to not enough -VS, is this having any impact on that?

**Comment by MisterChocker** [comment]
> I remember some discussion about flap drag being too low and causing overshoot on approach due to not enough -VS, is this having any impact on that?

Well actually no, the drag the plane creates is realistic. It can be hard to fly an 320 without any knowledge.

**Comment by starvingjavi** [comment]
Is this one good to test in the new version?

**Comment by MisterChocker** [comment]
@starvingjavi yes should work now.

**Comment by starvingjavi** [comment]
Name: Javi#2557
Date of testing: Current date 1/11/2020
Version of the sim: 1.10.8
PR Tested: #1580 
Object of test: Flight model changes

Testing technique: Full flight in IVAO from MMAA to MMGL
Steps you've made to test the Pull Request:
1. Start C&D in MMAA
2. Follow procedures and continue flight
3. Check during various phases of flight that pitch, thrust, altitude, and weight, matched with the sources for PR
4. Complete flight

Flight notes

Startup: Normal

Taxi/Takeoff : Normal

Cruise: Normal

Descent/Landing : A bit more slippery than usual but this sounds close to what pilots have said about the airplane itself. Flare mode during autoland pushed nose down instead of doing a proper flare (known issue)

Shutdown: Normal.

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Everything looks good. No issues with PR and everything works as described

**Comment by MisterChocker** [comment]
@starvingjavi 
> A bit more slippery than usual but this sounds close to what pilots have said about the airplane itself. Flare mode during autoland pushed nose down instead of doing a proper flare (known issue)

Can you describe this with a bit more details? Do you compared drag/thrust with v0.4.0 or with latest master?

**Review by Carter633 — APPROVED** [review]
Name: British Avgeek YT -- Carter633 #1436
Date of testing: Current date 02/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1580 
Object of test: Improvements to flight model, GD, Vapp, VL characteristics and rudder effectiveness

Testing technique: Full VATSIM flight EGKK -> EGJJ from Cold & Dark
Steps you've made to test the Pull Request:
1.  Spawned C&D at EGKK on VATSIM - full flight to Jersey EGJJ
2. Startup, taxi, takeoff all fine - take-off felt a bit smoother (AoA changes?) though noticed this time the IAS got towards V1, then dropped briefly 5-10kts before returning
3. Climb performance and general aircraft behaviour with AP etc. was fine
4. Descent to Jersey with the JERS1W STAR - all fine, felt smoother - can see how speed could get away from you easier with this now though
5. Approach set up and landing felt a lot better - V speeds seemed more natural and the attitude was better too in managed speed mode.

Flight notes

Startup: Everything was normal

Taxi/Takeoff : Everything was normal except for IAS speed getting towards V1, it then dropped down 5-10kts for a second before returning at V1

Cruise: I noticed (wasn't in the latest master) that during Cruise I was getting the old wobbly autopilot again with constant left/right for the entire cruise. No fuel imbalance, no odd Wx behaviour - checked master again and didn't have the issue?

Descent/Landing : Worked as expected

Shutdown: N/A

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: I noticed half way through my flight this test had been dropped back to Draft but no notes as to why - however I continued the test and the report is as above - LGTM - thanks for your work.

Notes from Javi Re: the aircraft being a bit more slippery - I'd probably agree it feels a small bit more slippery/efficient - it certainly feels more efficient. Not sure if anyone else experiences the AP being shaky again - only noticed it pre-patch in this PR (as mentioned above, was fine in the master version when comparing)

**Comment by MisterChocker** [comment]
@Carter633 I've set this back to draft because we not got 251 documentation on AOA etc. So we will now try to match the documents.

And to your question, yes we reworked the entire AOA table.

**Comment by starvingjavi** [comment]
> @starvingjavi
> 
> > A bit more slippery than usual but this sounds close to what pilots have said about the airplane itself.
> 
> Can you describe this with a bit more details? Do you compared drag/thrust with v0.4.0 or with latest master?

When trying to descend ir would be hard to slow down the plane, so if I didn't slow it down before descending I would find myself using flight detent during most of the approach. However, that has been my experience with all study level A320 for P3D and xplane

> > Flare mode during autoland pushed nose down instead of doing a proper flare (known issue)
> 
> I believe that a proper FBW will solve that problem.

Yeah, just mentioning what happened during the flight

Everything acted just like the reference documents you posted, though. So no problems with your PR at all

**Comment by RikvanD1997** [comment]
Name: Rienk ᕕ( ᐛ )ᕗ#1337
Date of testing: Current date 2/11/2020
Version of the sim: 1.10.8
PR Tested: #1580
Object of test: Flight model changes

Testing technique: Full flight from C&D in GCTS to parking at the gate in EHAM

In case it's needed for reproducing the oscillations:

Block Fuel: 9409 KG
TOW: 70363 KG
MAC (Center of Gravity): 24,7%

Steps you've made to test the Pull Request:

Start C&D in GCTS
Follow checklists to go from C&D to taxi for take-off
Take off and monitor behaviour of the aircraft
Cruise at FL360
Land and taxi to the gate in EHAM

Startup: Normal

Taxi/Takeoff : Normal

Cruise: When nearing cruise altitude, the plane started to oscillate in the roll axis. In my infinite wisdom I forgot to record this, but imagine about a -3 to +3 degrees oscillation happening at about 2-3 oscillations per second. This continued until a few thousand feet into the descent. In every other aspect, the cruise works as expected.

Descent/Landing : Mild oscillations as described above for the first thousand feet of descent. Normal after.

Shutdown: Normal

Issues (If Any): Oscillations as described above
Overall Rating: Good
Conclusions of the testing: The aircraft performs as expected during all stages of flight. It's just the oscillations that seem to be a bit of an oddity. I got these in an earlier test, but decided I would test with both master and this change again in case it was weather related or something. It appears it is not, and it only occurs with these changes. If this could be fixed, I would have no further comments.

**Comment by MisterChocker** [comment]
@RikvanD1997 Your testing results are still useful. We are now going to rework the aoa table again with new documents.
This may take a couple of weeks until we are ready for testing again.

**Comment by donstim** [comment]
The flight model has been further re-worked to re-verify correct stall speeds with all stall protection systems de-activated and to match the pitch angles from the unreliable airspeed charts shown above. This flight model increases CLmax relative to the MSFS flight model, so it should improve airplane handling during landing (no more premature stalls).

Known issues:
1) Pitch angles for level-off at intermediate configurations (1, 1+F, 2, and 3) still do not match the pitch for unreliable airspeed table. This is a consequence of the MSFS flight model.  At this point, you can match flaps up pitch for climb, cruise, and descent, or intermediate flap pitch for level-off, but not both.
2) PFD low speed warning indications (amber, yellow-and-black, and red bands) are based on a stall speed determination independent of the actual flight stall speeds for the flight model. They are based on referenced speeds in the flight model cfg file for CONF Full and Up at max weight and interpolated for the other CONFS. Matching both the actual flight stall speeds and this other stall speed calculation for the PFD speed tape indications is pretty difficult -- I chose to math the actual flight stall speeds. 
  - Therefore, the stall speeds used for the PFD speed tape indications are incorrect for the intermediate flap settings. The stall speed used for these configurations is higher than the actual stall speed, so VLS, alpha max, and alpha prot indications will be at higher speeds than they should be. 
   - The method by which the PFD speed tape indications are done does not differentiate between CONF 1 and CONF 1+F. The same stall speed is used for both, and it is the higher CONF 1 stall speed (which is already higher than the real CONF 1 stall speed). This could be problematic for CONF 1+F takeoffs because it is likely that the real V2 speed will be lower than the displayed VLS and may well be within the yellow-and-amber band.  I am not sure where the higher V2 speed that MSFS currently uses is relative to the PFD low speed indications.
   - For flaps up, although the stall speed used for the PFD speed indications is correct, MSFS uses the wrong speed multiple for VLS (1.23 instead of 1.28 times the stall speed), so the VLS indication is a bit higher than it should be.
    - For Flaps full, the stall speed used for the PFD is also correct as is the multiple used for VLS, so at least for this important configuration, VLS should be displayed correctly (within a knot or two) of the actual VLS.
    - Ultimately, I think the solution for the PFD low speed speed tape indications will be to code it ourselves.

**Review by Benjozork — CHANGES_REQUESTED** [review]
Code LGTM. Can you just remove the commented code ? Thanks.

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 24/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1580 
Object of test: Flight model, PFD

Testing technique: Test Flight -> EGNT - EINN
Route: EGNT/25 F340 GIRLI1Y GIRLI P18 GASKO P16 RIBEL UP16 CROFT Y70 KOLID UL70 PENIL M144 BAGSO DCT PELIG DCT DIGAN DIGAN2E EINN/06
Steps you've made to test the Pull Request:
1. Load up AC at EGNT at Stand
2. Programmed MCDU
3. Fly

Flight notes: 
- The AoA in flight: ~2.5° at FL340 at Mach .78
- During Descend: AoA constant ~-1.5° at ~287 IAS
- At FL080 at 250 IAS: AoA ~6° (maybe little high) Flaps 0
- at FL060 at 250 IAS: AoA ~2° (better than before) Flaps 0
- At Approach Established ILS: AoA constant ~-1° very stable through all Flap settings


Issues (If Any):
1. After Aligning the NAVs GPS Primary appears only on PFD, not in the MCDU, it’s not possible to clear it in the PFD
2. LDG Memo appeared after Take-off (maybe not related to this PR)
3. After Setting Flaps 1->Up the AC Pitched down very hard. The active mode was VS (+2000fpm) with Speed Set to 250, happened while accelerating. Since VS and Speed was activaed, AC Should not pitch down for acceleration. After this first pitch down, it went back to normal climb and accelerating
4. STO was blinking all the time even after set to STD (maybe not related to this PR)

Overall Rating: To be improved
Conclusions of the testing: I found a few issues that are mentioned above. Besides that, the AC felt much better on approach, no significant pitch down wen flaps set. Speeds were shown correctly on the PFD. I was not able to look at everything, cause its very much. So that is what I found/observed so far. Overall feeling is much better than before.

**Comment by donstim** [comment]
Thanks for testing @Noxleee . I don't think any of the issues you identified are connected with this PR. Sounds like the first one may have been a one-off? The 3rd one sounds like an autopilot issue. Have you tried it without this PR?

On your flight notes, are you quoting AOAs (from the simtuning debug window) or pitch angle from the PFD (or pitch debug window)? I assume it is pitch angle from the PFD. If so, it would be nice to know the weight for the FL080 and FL060 conditions. Pitch should be about 5 degrees with flaps up at green dot speed. I am surprised that you saw a difference of 5 degrees between the FL080 and FL060 conditions at the same speed. I would like to double-check that if you could provide the weight or weights (if they were different) for those 2 conditions.

On final approach at Vapp flaps full, the pitch should be between 2.5 and 3 degrees, so if you saw a stable 1 degree, that is also concerning. Weight?

Thanks again!

**Comment by Noxleee** [comment]
@donstim I corrected my report. Of cause I meant the Pitch and not the AoA! Sadly, I have no weights beside my Block and ZFW. But a few additions:

> - at FL060 at 250 IAS: Pitch ~2° (better than before) Flaps 0
> - At Approach Established ILS: Pitch constant ~-1° very stable through all Flap settings

Both situations where near the end of the flight and they followed each other with a time difference of 5-10 minutes, So the fuel was relatively the same. I would guess the remaining fuel was 1-1.5.

> - At Approach Established ILS: Pitch constant ~-1° very stable through all Flap settings

On my Approach I was a little too fast and the Aircraft was decelerating nearly until the end. Maybe this is the reason for the stable 1-degree pitch. Remaining fuel could be around 1.

**Comment by St54Kevin** [comment]
@MisterChocker Hi man. Great PR. Looks massive. How would you think an accuracy check looks like? All the calculations are hard to crosscheck but I could give the overall feeling of the aircraft a try

**Comment by MisterChocker** [comment]
@St54Kevin this pr is still in "closed" testing as said in QA. We have a specific testing documentation. Please do go ahead and contact @Inaxair to get access.

**Comment by St54Kevin** [comment]
> @St54Kevin this pr is still in "closed" testing as said in QA. We have a specific testing documentation. Please do go ahead and contact @Inaxair to get access.

Oh okay. Then please remove the accuracy check needed flag. That's for us pilots

**Comment by Benjozork** [comment]
> 
> 
> > @St54Kevin this pr is still in "closed" testing as said in QA. We have a specific testing documentation. Please do go ahead and contact @Inaxair to get access.
> 
> Oh okay. Then please remove the accuracy check needed flag. That's for us pilots

The flag is there because accuracy check will be needed, added so that a maintainer does not merge the PR once QA (closed or not) does its thing.

**Comment by wpine215** [comment]
M E R G I N G

**Comment by MisterChocker** [comment]
Oh boy here we go!

**Comment by hotshotp** [comment]
Heck yeah!

**Pull request merged**
