### PR TITLE
chore: Repo refactor to accommodate multiple aircraft types

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes
This PR proposes a new repository monorepo structure to allow developing and build mulitple aircraft types using dedicated and shared code.

### Why / Why Now
A discussed before a monorepo is the best way to move forward and speeding up development for multiple aircraft which will share common code. 

We are at a point where our A380 development suffers the separation of the repos for commonly used systems. To prepare to merge the repos this restructuring has to be done and should be robust before we do the actual merge. 

### New Proposed Structure

<details>
<summary>Repo Structure tree</summary>

```
a32nx (repo)                                     <flybywire monorepo - will be renamed eventually>
├── docs                                         <documentation for the repo - e.g. this structure>
├── fbw-a32nx                                    <A32NX project files>
│   ├── docs                                     <documentation for the A32NX project>
│   ├── out										 <folder the final aircraft package will be build into>
│   └── src                                      <A32NX project source code>
│       ├── base                                 <msfs package base files>
│       │   └── flybywire-aircraft-a320-neo
│       ├── behavior                             <behavior source files>
│       ├── fonts                                <font files>
│       ├── model                                <model source files>
│       ├── systems                              <non-wasm system source files>
│       │   ├── atsu
│       │   ├── failures
│       │   ├── fmgc
│       │   ├── instruments
│       │   ├── sentry-client
│       │   ├── shared
│       │   ├── simbridge-client
│       │   └── tcas
│       ├── textures                             <texture files>
│       └── wasm                                 <wasm system source files>
│           ├── fadec_a320
│           ├── fbw_a320
│           ├── flypad-backend
│           └── systems
│               ├── a320_systems
│               └── a320_systems_wasm
├── fbw-a380x
│   ├── docs                                     <documentation for the A380NX project>
│   ├── out                                      <folder the final aircraft package will be build into>
│   └── src                                      <A32NX project source code>
│       ├── base                                 <msfs package base files>
│       ├── systems                              <non-wasm system source files>
│       └── wasm                                 <wasm system source files>
│           ├── fadec_a380
│           ├── fbw_a380
│           └── systems
│               ├── a380_systems
│               └── a380_systems_wasm
├── fbw-common                                   <common code and libs>
│   ├── msfs-avionics-mirror
│   └── src
│       ├── jest
│       ├── typings                              <msfs specific typings>
│       └── wasm
│           ├── fadec_common
│           ├── fbw_common
│           └── systems
│               ├── systems
│               └── systems_wasm
├── scripts                                      <all build scripts>
└── tools                                        <tools files>
    ├── fdr2csv
    └── heapdump
└── ...                                          <repo config files>
```

</details>

### Roadmap

- [x] Create a working restructured branch (“repo-refactor”)
	- [x] Move folders
	- [x] Update build scripts for a32nx
	- [x] Build a32nx successfully 
	- [x] Build a380x wasm successfully
- [x] Build in feedback on new structure from team
- [x] Agree with team on timeline
	- ~~[ ] Depending on how well rebasing will work we might require a master freeze~~
	- [x] If “repo-refactor “ branch can be rebased keep it updated
	- [x] Team will have time to complete open PRs until merge date
- [x] Update “repo-refactor” branch
    - [x] Test build on GitHub with CDN upload
    - [x] Create Installer Config
    - [ ] Adapt and test github scripts
  	- [ ] Test exhaustively
    - [ ] (Force?) push to master
	- [ ] Test exhaustively
- [ ] Create and release new A32NX Development on new structure
- [ ] Devs needs to adapt open PRs (or create new ones and transfer changes)
- [ ] Create new Experimental with updated PRs
- [ ] Create and release new A32NX Stable on new structure
- [ ] Agree on time for bringing in A380 repo
	- [ ] Merge in A380 rep (needs team decision to make A380 repo public)
	- [ ] Update build scripts for a380x
	- [ ] Build a380x successfully 

## Discord username:
someperson#4953 (Holland)
Cdr_Maverick#6475

## Testing instructions

This needs considerable testing by developers and testers!

You can use the Installer to download and install this version. Use this configuration:
https://flybywiresim.b-cdn.net/installer/config/repo-refactor.json
Ask on Discord in the #development or QA channels on how to change the config for the Installer. 

### Testers
Check full flights - this build should not behave any different from the latest Development. 
Any differences are probably because of some build problems which aren't obviouse.
If you find an issue pls also test on Development first to see if there is a difference.

### Developers 
Review and test the build scripts including package.json builds and igniter builds. 
Familiarize yourself with the new structure and maybe test rebasing open PRs against.
Making this change possible required changing and fixing of many build scripts. I have also liberally edited and hopefully improved building  scripts and other configurations (eslint, etc.)
It uses a new dev-env which now includes rsync for faster synchronization of the base files to the out folder.

## ISSUES found during testing
- ~~Gear Handle is up (gate, runway) and gear retracts immediately after take off~~ fixed

### CODE REVIEW

**Comment by Eagle941** [comment]
The new structure is very intuitive with clear separation of projects. Would it make sense to rename the repo to something generic?

**Comment by frankkopp** [comment]
> The new structure is very intuitive with clear separation of projects. 
Thanks

> Would it make sense to rename the repo to something generic?
Will be done eventually - but this has many implications. Not sure if there is a soft way with braking forks/clones/links etc.

**Comment by frankkopp** [comment]
> > Will be done eventually - but this has many implications. Not sure if there is a soft way with braking forks/clones/links etc.
> 
> GitHub is very good about this. It will automatically redirect HTTP links, and forks & clones will be forwarded to the new location automatically. Git will print a notice when users update their local version that the location has changed.

Awesome - didn't know - then we can do this after the merge - wouldn't want to do this at the same time :)

**Comment by brewers10** [comment]
Quality Assurance Trainee Report

Discord          : brewers_10#5706
Object of testing: #7677 
Tier of Testing  : 2
Date             : 23/01/2023

Testing Process: 
Full flight from EGPH - BIKF

Loaded into stand 16A at EGPH.
Cockpit prep satisfactory 
Start-up satisfactory 
Climb out/LNAV/VNAV excellent
Systems all performing as expected
No VNAV (Don't think VNAV is in dev version anyway so no issues here)
Descent went well, speeds were followed nicely
Approach followed nicely by LNAV
ILSZ19 captured perfectly at BIKF

Negatives:       
Slightly sensitive throttles even after calibration, quite tricky to get into the perfect CLB detent.

Testing Results: 
Passed

Media:       
Although tier 2, nothing really to show. Very standard and successful flight.

**Review by tracernz — APPROVED** [review]
Approved as a formality. Large process ongoing for some time.

**Comment by dragold** [comment]
QA Tester Report 

Name: Mr.Blank#7677
Date of testing MM/DD/YYYY:01/18/2023-1/29/2023
PR Tested: 7677
Tier of testing:2

Testing technique: tryouts
Test Instructions:
Check full flights - this build should not behave any different from the latest Development.
Any differences are probably because of some build problems which aren't obviouse.
If you find an issue pls also test on Development first to see if there is a difference.

Methodology
All as per insturction  
Full Sop flights under various routes (VOTV-VOMM)(VOTV-VOCI-VIDP) (OMDB-VOTV)(PHNL-KMIA)
Non SOP Flights (Short)only (OERK-OKBK-OMDB)
Random input test
Negatives: NIL

Testing Results: PASS 
Conclusions: results were of normal outputs

**Pull request merged**
