### PR TITLE
feat: Upscaled FBW livery, removed A32NX text and the horrid green stripe from the engines.

### PR DESCRIPTION
**Pull request by FoxinTale**
## Summary of Changes

Upscaled the fuselage to 8K and the engines & wings to 4k.
Removed the A32NX and the green stripe from the engines.

I have since fixed the strange thing on the "y" in 'fly' by the right side of the door.

While essentially a duplicate, this is the one to use. I made a mistake when pushing the changes (deleted my fork, recreated the branch, and it wouldn't let me push the changes because it was already up to date) and this was the easiest way to fix it.
## Screenshots (if necessary)

See #3797.

## Additional context

On my system, I can manage low-medium (Ryzen 5 1600AF, RX 580, 16 Gb ram) , and my monitor is 1600 x 900. there may be little, if any visual difference between before and after. See testing instructions for further. 

Discord username (if different from GitHub): Aubrey Jane#7563

## Testing instructions

Especially those who can run the sim on all medium settings and up on a 1080p or higher monitor, please take screenshots before and after, and compare them yourselves. Pay close attention to the "flybywire" text on both sides of the aircraft, make sure the stripe and text are gone on the engines, and anywhere else you think would be of importance.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by kiwi2021** [comment]
Category: Admin
Name: Discord User kiwi2022#0001
Date of testing: Current date 05/04/2021
Version of the sim: 1.14.6.0
PR Tested: 4281
Tier of testing: 1
Changes to observe: Resolution, FlyByWire Text, Engine stripe and text delete.

Testing technique:
Loaded into EGLL C/D
Observed the livery via External and Showcase camera



Media: (Click to view larger image)

**Left side FBW Text;**
Before
Text Left

After
Left Text

**Right side FBW Text;**
Before
Text Right

After
Right Text

**Engine Strip & Text Removal; (External Showcase - 15)**
Before
External 15 Old-min (2)

After
External Camera - 15-min



Issues (If Any):
On the fuselage there seems to be a joint where the livery meets. The old version covers this up pretty well, however the new upscaled livery seems to show a more clear 'step' between the two components. The images below show this better than I can describe.

**Location (Mirrored);**
Issue


**Issue Before (Left);**
Artifact Left

**Issue After (Left);**
Left Side - Artifact


**Issue Before (Right);**
Artifact Right

**Issue After (Right);**
Right Side - Artifact


I think this is to be noted and looked at for a future rework of the livery. The upscale has purely made this more visible. Overall the PR is great and the aircraft does look cleaner overall., fantastic work.

**Comment by MapleNAV-TCASFAULT** [comment]
The green ring should be black compared to the grey that you used. Also farther behind the engine should be a very pale blue, but that maybe caused by lighting conditions.
image

**Comment by FoxinTale** [comment]
> The green ring should be black compared to the grey that you used. Also farther behind the engine should be a very pale blue, but that maybe caused by lighting conditions.
> image

So...turn what was the green ring black, basically?

**Comment by FoxinTale** [comment]
Well, I think I screwed up adding the stripe again. At least, the merging/commiting and updating branches.

**Comment by tracernz** [comment]
The green stripe isn't really horrid, it's just that it's for PW1100G rather than LEAP-1A. The part behind it is lighter and more of a blue grey than it seems in your screenshot. e.g. @MapleNAV-TCASFAULT's photo above, and:
https://www.airliners.net/photo/Nas-Air/Airbus-A320-251N/6341039/L
https://www.airliners.net/photo/China-Eastern-Airlines/Airbus-A320-251N/6347873/L

**Comment by FoxinTale** [comment]
> The green stripe isn't really horrid, it's just that it's for PW1100G rather than LEAP-1A. The part behind it is lighter and more of a blue grey than it seems in your screenshot. e.g. @MapleNAV-TCASFAULT's photo above, and:
> https://www.airliners.net/photo/Nas-Air/Airbus-A320-251N/6341039/L
> https://www.airliners.net/photo/China-Eastern-Airlines/Airbus-A320-251N/6347873/L
> 
> For interest's sake, a PW1100G: https://www.airliners.net/photo/Lufthansa/Airbus-A320-271N/6252379/L

I know it's not horrid.  It didn't look too bad to begin with. It was bugging me that it was incorrect for the engine we had.  Meant more tongue in cheek "horrid"

**Comment by tracernz** [comment]
> I know it's not horrid. It didn't look too bad to begin with. It was bugging me that it was incorrect for the engine we had. Meant more tongue in cheek "horrid"

Haha :D. There is a silver ring in between the front carbon part, and the green ring that doesn't seem to be there on the real one too. Any chance you know where that is on the texture?

**Comment by FoxinTale** [comment]
> Haha :D. There is a silver ring in between the front carbon part, and the green ring that doesn't seem to be there on the real one too. Any chance you know where that is on the texture?

This is where it would be. I essentially overwrote the green strip that was there.
image

**Comment by felixharnstrom** [comment]
Great work on the textures :) I just wanted to let you know that Github seems to be under the impression that you've changed a bunch of sources files as well since a number of commits by other authors have been included in the PR. Not sure if something went wrong when you merged the upstream changes or if it's just the the Github UI that's confusing me.

image

Just wanted to let you know in case it's something that needs to be fixed before merging this.

**Comment by FoxinTale** [comment]
> Great work on the textures :) I just wanted to let you know that Github seems to be under the impression that you've changed a bunch of sources files as well since a number of commits by other authors have been included in the PR. Not sure if something went wrong when the upstream changes were merged or if it's just the Github UI that's confusing me.
> 
> image
> 
> Just wanted to let you know in case it's something that needs to be fixed before merging this.

It is upstream changes, yes. Not sure how to resolve them myself unfortunately. without making a new form/branch.

**Comment by davidwalschots** [comment]
@FoxinTale I don't think anyone will review this with all the unrelated changes. So I highly recommend force pushing a cleaner history.

**Comment by FlyingCarpet7** [comment]
Add this picture here for reference. Notice the black and grey colours.
6D1FBB19-03BD-4E97-83ED-5F6668FCDFD2

**Comment by FoxinTale** [comment]
> @FoxinTale I don't think anyone will review this with all the unrelated changes. So I highly recommend force pushing a cleaner history.

Honestly, I'm not sure how to do that. And I would really like to avoid having to make a fourth PR for the same thing. Currently, the only was I know how to do that is delete the fork and remake it. Again, I'm not doing this a fourth time.

**Comment by FoxinTale** [comment]
> > @FoxinTale I don't think anyone will review this with all the unrelated changes. So I highly recommend force pushing a cleaner history.
> 
> Honestly, I'm not sure how to do that. And I would really like to avoid having to make a fourth PR for the same thing. Currently, the only was I know how to do that is delete the fork and remake it. Again, I'm not doing this a fourth time.

Update: Seems Github Desktop now allows rebasing. Yay. Did that and it did good things now. I think this is what was needed, anyways.

**Review by tracernz — APPROVED** [review]
LGTM

**Comment by tracernz** [comment]
No green ring, crisp text.
fbw

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 20/04/2021
Version of the sim: 1.15.8.0
PR Tested: #4281
Tier of testing: 1
Changes to observe: upscaled livery, engine band and A32nx removal

Testing technique:
Loaded into EGBB Cold and Dark on a remote stand and checked the livery

Steps for testing:
1. Spawned C&D at EGBB on stand, used external camera and drone camera
2. Moved about noting comments above from others
3. Checked stripe removal and A32nx removal areas

Media: N/A

Issues (If Any):
None

Overall Rating: Good
Considerations of testing: absolutely fine - removal of stripe and A32nx on cowling have no problems around those sections from what I can see. Appears much crisper now.

**Review by davidwalschots — APPROVED** [review]

**Pull request merged**
