### PR TITLE
fix(rmp): sync COM frequency display with actual value

### LINKED ISSUE #2709: [BUG] COM frequency does not update with in-game button function
**Mod Version**
0.5.1 Stable & Dev
{
  "built": "2020-12-25T10:12:36+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**
The standby frequency does not change, if you push a button mapped to increase or decrease the frequency. Neither whole, nor fract nor fract,carry mode works. The frequency is also not updated in ATC menu if you switch for crosscheck (displays what was the standby frequency before), so it's not an issue with the displays.

**To Reproduce**
1. Launch FBW A32NX
2. Map any button to Increase[Decrease] COM1 (Whole[Fract][Fract,Carry])
3. Press the buttons
4. See nothing happening

**Expected behavior**
Standby Frequency should increase[decrease] by xx1.xxx on whole, increase[decrease] by xxx.x25 on fract, and increase[decrease] by xxx.x25 with increasing[decreasing] xx1.xxx when applicable on fract, carry

**Actual behavior**
Nothing happening

**Additional context**
Might be related to #1079 

Was this working before/when did the issue start occurring?
unknown

Is this a problem in the vanilla unmodded game?
No (as long as you are not stuck with 124.850)

Discord username (if different from GitHub):
Foxtrot Sierra#6420

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #2709

## Summary of Changes

Asobo added this functionality at some point and I ported it in this PR. This might be an intermediate solution until the RMP rewrite is finished.

## Additional context

Discord username (if different from GitHub): saschl#9432

## Testing instructions

Use a radio panel or configure bindings for COM1 and COM2 increase/decrease on any device. The displays should now be updated correctly. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Saschl** [comment]
Don’t know if this needs a changelog entry as it mainly contains changes from asobo

**Comment by Benjozork** [comment]
> 
> 
> Don’t know if this needs a changelog entry as it mainly contains changes from asobo

Yes

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Lazarus320** [comment]
Category: QA Tester 
Name: Lazarus#4286
Date of testing: Current date 25/1/2021
Version of the sim: 1.12.13.0
PR Tested: #3157 
Tier of testing: 1
Changes to observe: Com radios displays correct inputs from binds.

Testing technique: Loaded a casual flight from c/d and tried configuring the radio frequencies using keybinds only throughout the flight. 
Steps you've made to test the Pull Request:
1. Tested COM 1 
2. Tested COM 2  

Flight notes : N/A

Media: 

COM1 

https://user-images.githubusercontent.com/74972083/105646645-ef441f80-5edb-11eb-8b78-10a515c80a83.mp4

COM 2 

https://user-images.githubusercontent.com/74972083/105646689-3b8f5f80-5edc-11eb-9fa7-d7fb1bb51d52.mp4

Issues (If Any): N/A
 
Overall Rating: Good
Conclusions of the testing: Great QoL honestly, helped a lot with Vatsim during testing good work.

**Comment by St54Kevin** [comment]
Is it possible to get RMP2 coms with that? I like to fly from FO seat and have to change view everytime i want to change the frequencies

**Comment by tyler58546** [comment]
> 
> 
> Is it possible to get RMP2 coms with that? I like to fly from FO seat and have to change view everytime i want to change the frequencies

This will be fixed by #2980, although I'm not sure if that's still being worked on.

**Comment by Saschl** [comment]
Tyler is right, I only added some changes so the display is being updated.

**Comment by gleclere** [comment]
@Saschl I did a quick test yesterday with a device using [X-Touch-Mini-FS2020](https://github.com/maartentamboer/X-Touch-Mini-FS2020), it works perfectly. Great job, can't wait to have it in master!

**Comment by Lunatic104** [comment]
Category: QA Tester
Name: Lunatic#7920
Date of testing: Current date 30/1/2021
Version of the sim: 1.12.13.0
PR Tested: #3157
Tier of testing: 1
Changes to observe: Com radios displays correct inputs from binds.

Testing technique: Loaded a casual flight from hotstart.
Steps you've made to test the Pull Request:

Tested COM 1 with com 1 active
Tested COM 2 with com 2 active
Tested COM 1 with com 2 active
Tested COM 2 with com 1 active

Works as described. No issues.

Flight notes : N/A

Media:

**Comment by Saschl** [comment]
I believe this won’t be necessary anymore as the RMP has been rewritten completely and beautifully :) Thanks for testing anyway!

**Pull request closed without merging**
