### PR TITLE
[CDU] Fix CRZ FL unintentionally changed by fcu

### LINKED ISSUE #1952: [BUG] CRZ FL changes when selecting altitude with FCU during CLIMB phase
**Mod Version**

master
{ "built": "2020-11-15T03:35:23+00:00", "ref": "refs/heads/master", "sha": "71806ad3f76a80f55019c0548bc08049a50d435b", "actor": "Benjozork", "event_name": "push" }

**Describe the bug**

When selecting a managed speed with the FCU (selected speed not tested) during CLIMB phase, the MCDU changes the cruise FL to this speed. This is not correct and often leads to a cruise FL of the first cleared FL (like FL080...).

Only when already in CRUISE phase (aircraft in soft alt mode), the cruise FL should be changed when selecting a higher managed altitude.

**To Reproduce**

1. Start a flight in IFR mode
2. Select some lower altitude (like 8000ft) using managed mode
3. CRZ FL (e.g. on the INIT A and the PROG page) changes to FL080

Could be flaky and happen just in some cases?

**Expected behavior**

CRZ FL should not change (only when changed manually in the appropriate fields on the INIT A or PROG page)

**Actual behavior**

see above

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):
n/a

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #1952

## Summary of Changes

- Displayed FL during climb displays fcu selected altitude or constraint altitude if lower than crz fl and no cruise fl is set.
_before turning the altitude knob changed crz fl_
- When CRZ FL has been changed because the FCU selected altitude is above the crz altitude, the crz altitude changes and the message "NEW CRZ AL-" will appear.
- [x] make message type II
- [x] use new alt ctn variable

This pr fixes newly implemented features by #1757 (I can add a change log if needed)

## References

image
image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MisterChocker** [comment]
Waiting for both #1951 (for the Message Type II be displayed correctly) and #1985 to make usage of new constraint distribution.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by kberg93** [comment]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 11/29/2020
Version of the sim: 11.6.0
PR Tested: #1998 
Object of test: Check if CRZ FL unintentional changes by FCU

Testing technique: Changing CRZ FL on FCU after reaching CRZ ALT

Steps you've made to test the Pull Request:
1. C&D startup at ENVA
2. Did take off from rwy27 and climbed to FL100 first to see if it did change INIT-A but it didnt wich is correct afaik.
    Then i procceded the climb to FL280.
3. Climbed to CRZ FL and checked if its unchanged in INIT-A then did a step climb from FL280 to FL300 using the FCU.
    It changed the CRZ FL in INIT-A and in PROG and it showed "NEW CRZ ALT-30000" as a message on the MCDU.
4. Then i did a decent down to FL280, the CRZ FL got deleted in INIT-A and PROG as it should do if i understood the reference 
    note correctly. :) 



Flight notes (If required): Everything seemed to work as it should.

Issues (If Any): Did find another thing that wasnt mentioned. The CRZ FL on INIT-A gets Deleted if i go into PROG and check 
                        there (screenshots before and after). This does not happend on Master build.

Overall Rating: Good, the message showed as it should but have a look at that other thing i found if its normal or not. 

Conclusions of the testing: It works.

Screenshots:
After setting in CRZ FL
FlightSimulator_vODwYBLdC2
Checking PROG page
DsrkWrcCIz
After checking PROG page
79Rzta2LTO

**Comment by MisterChocker** [comment]
Thanks for the testing. I found one error I made in my code that could have lead to the described error. I also removed one variable assignment which may have also caused the deletion of the CZR FL on the INIT-A Page.
The CRZ FL on INIT-A should never be deleted/cleared by the system in flight.

**Review by kberg93 — APPROVED** [review]
All seems fine and works as it should do on the fix this is ment for. (not the AP tho thats wanna bank right now but thats probably nothing with this since it worked fine yesterday just the deleting of CRZ FL via PROG) 👍🏻

**Comment by mikecbr** [comment]
> All seems fine and works as it should do on the fix this is ment for. (not the AP tho thats wanna bank right now but thats probably nothing with this since it worked fine yesterday just the deleting of CRZ FL via PROG) 👍🏻

What do you mean it banks right now ? is not working the AP ?  @kberg93

**Comment by kberg93** [comment]
> > All seems fine and works as it should do on the fix this is ment for. (not the AP tho thats wanna bank right now but thats probably nothing with this since it worked fine yesterday just the deleting of CRZ FL via PROG) 👍🏻
> 
> What do you mean it banks right now ? is not working the AP ? @kberg93

Thats before the AP fix last night.

**Pull request merged**
