### PR TITLE
feat(sound): add custom sounds to multiple buttons and throttle lever reverse locks

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

- added custom sound to the Throttle Lever Reverse Locks
- added custom sound to Master Warning, Master Caution, Terrain on ND, and Autobrake buttons. 

## Video
https://user-images.githubusercontent.com/71195324/108618744-d5d1bd00-7420-11eb-9c4e-3796bc9b88a6.mp4

## Additional context
These sound changes were requested and checked by @hotshotp .
Thanks to @tyler58546 and @pepperoni505 for helping me out! 

## Testing instructions
Check that all the sounds mentioned above (Throttle Lever Reverse Locks, Master Warning, Master Caution, Terrain on ND, and Autobrake buttons) work correctly. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by hotshotp — APPROVED** [review]
LGTM, uses correct wwise events and correct templates

**Comment by Samueleonard** [comment]
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: Current date 21/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3659 
Tier of testing: 1
Changes to observe:
.Check that Throttle Lever Reverse Locks, Master Warning, Master Caution, Terrain on ND, and Autobrake buttons work correctly + have sounds.

Steps you've made to test the Pull Request:
1. load up at pmdy, default livery, live time/clear skies
2. shut down engines and made cold and dark
3. moved throttles through full motion + into reverse - sounds played as expected
4. pressed master warn/caut buttons on left side- heard sounds
5. pressed master warn/caut buttons on left side- heard sounds
6. pressed TERR ON ND - heard sounds
7. pressed all auto brk settings + depressed - heard sounds

Flight notes (When done a full flight):
N/A - just loaded up and tested

Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A

Issues (If Any): Write any issues
my only issue is that there are, from what I can hear, almost no variations in some button sounds. for example the master warn and caut buttons have exactly the same sound, I feel there should be a slight variation to make it more lifelike. i can hear that other buttons have different sounds, for example the brk fan and autobrk have different sounds.

they could potentially be different samples and just sound very similar, because they are the same type of button, but its not a huge problem, I still hear new sounds

Steps to achieve the issue
N/A
Overall Rating: Good

Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.
LGTM - apart from the suggestion above that could be done another time, if at all

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 21.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3659
Tier of testing: 1
Changes to observe: More button sounds
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP

Tested:

- Throttle lever reverse locks
- Master warning
- Master caution
- Terrain on ND
- Autobrake buttons

Issues: -

Overall Rating: Good

Conclusions of the testing: Works!

Hope this helps :-)

**Comment by hotshotp** [comment]
> Category: QA Trial
> Name: 1samueleonard1#0001
> Date of testing: Current date 21/02/2021
> Version of the sim: 1.13.16.0
> PR Tested: #3659
> Tier of testing: 1
> Changes to observe:
> .Check that Throttle Lever Reverse Locks, Master Warning, Master Caution, Terrain on ND, and Autobrake buttons work correctly + have sounds.
> 
> Steps you've made to test the Pull Request:
> 
> 1. load up at pmdy, default livery, live time/clear skies
> 2. shut down engines and made cold and dark
> 3. moved throttles through full motion + into reverse - sounds played as expected
> 4. pressed master warn/caut buttons on left side- heard sounds
> 5. pressed master warn/caut buttons on left side- heard sounds
> 6. pressed TERR ON ND - heard sounds
> 7. pressed all auto brk settings + depressed - heard sounds
> 
> Flight notes (When done a full flight):
> N/A - just loaded up and tested
> 
> Media: Insert screenshots, recordings, or anything relevant to the review here.
> N/A
> 
> Issues (If Any): Write any issues
> my only issue is that there are, from what I can hear, almost no variations in some button sounds. for example the master warn and caut buttons have exactly the same sound, I feel there should be a slight variation to make it more lifelike. i can hear that other buttons have different sounds, for example the brk fan and autobrk have different sounds.
> 
> they could potentially be different samples and just sound very similar, because they are the same type of button, but its not a huge problem, I still hear new sounds
> 
> Steps to achieve the issue
> N/A
> Overall Rating: Good
> 
> Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.
> LGTM - apart from the suggestion above that could be done another time, if at all

samuel, those button sounds are the exact same, because they are the same type of button this is recorded with 4 samples of both on and off, they sound nearly the exact same IRL. hope this clears it up

**Comment by marinerhally** [comment]
Category: QA Trial
Name: Mariner Hally#0715
Date of testing: 22/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3659
Tier of testing: 1
Changes to observe:
added custom sound to the Throttle Lever Reverse Locks
added custom sound to Master Warning, Master Caution, Terrain on ND, and Autobrake buttons.

Testing technique: Test out C/D
Steps you've made to test the Pull Request:
1. Spawned in C/D at EGCC
2. Tested all required buttons(Throttle lever reverse locks, Master Warning and Caution, Terrain on ND, and Autobrake buttons).
3. All buttons sound as expected.

Flight notes (When done a full flight):N/A

Media: N/A

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: They sound awesome, well done team :)

**Comment by dc1ps2** [comment]
In the real-world A320 cabin, is the button sound so loud? After watching the video, I think the sound seems too loud, especially the sound of pressing the button and rebounding

**Comment by hotshotp** [comment]
> In the real-world A320 cabin, is the button sound so loud? After watching the video, I think the sound seems too loud, especially the sound of pressing the button and rebounding

Button sound levels are confirmed to be realistic

**Pull request merged**
