### PR TITLE
[FMS] Add ground speed mini

### LINKED ISSUE #1994: [REQUEST] Implement Ground speed Mini
**Is your feature request related to a problem? Please describe.**

_

**Describe the feature you'd like to see implemented**

Ground speed Mini is a feature that (on final approach) compares the head wind and the wind entered in the PERF page and adds the differance in head wind to the approach speed to keep the aircraft out of a low speed situation if the head wind should suddenly change. (For better explaination watch the Video below)

**References**

Here is a great video from 320 Sim Pilot explaining the feature https://youtu.be/7QwY0Nytyds

**Additional context**

And I just want to thank you guys for the exccelent work you have done to that plane. I really love that mod :)

Discord username (if different from GitHub): Alex_123_Cool#4633

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #1994

## Summary of Changes

- Added ground speed mini
- TWR Headwind will be recomputed on rwy or app wind change

To break down the computation:
`Vapp + 1/3 * (current headwind - tower headwind)`

## References

image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by donstim** [comment]
This is another exciting enhancement! Nice! A few questions/comments, though (not directly related to just to the ground speed mini calc alone:  For this example, did you enter the Vapp (overriding the auto-calc'd Vapp)? It seems like the calculated Vapp should be around 132 depending on the difference mag variation at the runway (Vls + 1/3 the steady tower headwind component on LSK 3L). But it looks like you may have overwritten the calculated value because the value of Vapp is in large font? Just to be sure, the calculated Vapp should be Vls +1/3 of the headwind component in the true runway direction (corrected if necessary from the magnetic direction provided in LSK 3L, with a minimum of Vls + 5 and a maximum of Vls +15. It is my understanding that, in keeping with FMGC convention, the calculated Vapp would be in small font, while a pilot entered value would be in large font.

Vapp matters to the ground speed mini function because GS mini = Vapp - Tower headwind component (headwind component in runway axis of wind value in LSK 3L). So, in the above example, if the headwind component in the true runway direction is 20 knots, Vapp would be 132, and GS mini would be 112, instead of 130 and 110.. The target airspeed is then GS mini + current instantaneous headwind component (not the headwind component of the value in LSK 3L - which I know you know, but just wanted to be complete).

Your ground speed mini implementation looks amazing! Just the question about Vapp.

**Comment by Watsi01** [comment]
Great. We might have to do some explaining, when implementing this. Cause otherwise, we'll get many issue reports, that VAPP "is broken".

**Comment by MisterChocker** [comment]
> This is another exciting enhancement! Nice! I have a question about Vapp in the example you provided. For this example, did you enter the Vapp (overriding the auto-calc'd Vapp)? It seems like the calculated Vapp should be around 132 depending on the mag variation difference at the runway (Vls + 1/3 the steady tower headwind component on LSK 3L). But it looks like you may have overwritten the calculated value because the value of Vapp is in large font? Just to be sure, the calculated Vapp should be Vls +1/3 of the headwind component in the true runway direction (corrected if necessary from the magnetic direction provided in LSK 3L, with a minimum of Vls + 5 and a maximum of Vls +15. It is my understanding that, in keeping with FMGC convention, the calculated Vapp would be in small font, while a pilot entered value would be in large font.

Yes you are right, I will change that

**Comment by MisterChocker** [comment]
> Great. We might have to do some explaining, when implementing this. Cause otherwise, we'll get many issue reports, that VAPP "is broken".

We will get sooooo many false reports anyways, we might need some mods only for github to maintain issues xD

**Comment by MisterChocker** [comment]
23894ae03b8110daee79ec7f619556f83732e6a1 I've corrected the steady headwind 1/3, it was without the 1/3 before. Good catch.

**Comment by MisterChocker** [comment]
Once this pr is ready to test, I will fly do some more testing in crazy wind setups and see if the result is satisfying or terrifying.

**Comment by tareksabet** [comment]
as soon as I can I will test this PR for sure

**Comment by donstim** [comment]
Make sure to do some quartering winds and not just straight on headwinds as well!

**Comment by MisterChocker** [comment]
> Make sure to do some quartering winds and not just straight on headwinds as well!

Please explain in more detail what you mean by this.

**Comment by donstim** [comment]
Actually, winds at several different angles, like 15,45,90 relative to the direction of travel, and tailwinds, just to check that all the math is done correctly and only the headwind component is used.

**Comment by MisterChocker** [comment]
> Actually, winds at several different angles, like 15,45,90 relative to the direction of travel, and tailwinds, just to check that all the math is done correctly and only the headwind component is used.

Oh, well yeah, we don't have multiple sensors so we can just access a variable xD, I could do this math but it wouldn't change anything.

**Comment by donstim** [comment]
Oh, can you get just the headwind component from the sim? In that case, I guess you can do those tests to verify that it's correct.

For Vapp, though since the wind there is a reported wind (which also can be altered by the pilot), don't you have to calculate the headwind component of that one? 

Also, I was wondering if there is any filtering going on in the real airplane, or what the update rate is, to keep the target airspeed from jumping all other the place in really gusty conditions.

**Comment by MisterChocker** [comment]
> For Vapp, though since the wind there is a reported wind (which also can be altered by the pilot), don't you have to calculate the headwind component of that one?

yes I am doing this. I am accessing the rwy heading of the selected runway to get the headwind component.

> Also, I was wondering if there is any filtering going on in the real airplane, or what the update rate is, to keep the target airspeed from jumping all other the place in really gusty conditions.

If this is a real issue, I already thought of some dampening.

**Comment by donstim** [comment]
> > For Vapp, though since the wind there is a reported wind (which also can be altered by the pilot), don't you have to calculate the headwind component of that one?
> 
> yes I am doing this. I am accessing the rwy heading of the selected runway to get the headwind component.
> 
Great, does it do that calculation continuously, or at least at some interval, so that, for example, if the pilot changes the wind magnitude or direction at any time in the APPR page of the MCDU, then Vapp, GS mini, and the target airspeed get updated? Or if the pilot puts in a new Vapp at any time, then GS mini and the target speed get updated?

**Comment by MisterChocker** [comment]
> > > For Vapp, though since the wind there is a reported wind (which also can be altered by the pilot), don't you have to calculate the headwind component of that one?
> > 
> > 
> > yes I am doing this. I am accessing the rwy heading of the selected runway to get the headwind component.
> 
> Great, does it do that calculation continuously, or at least at some interval, so that, for example, if the pilot changes the wind magnitude or direction at any time in the APPR page of the MCDU, then Vapp, GS mini, and the target airspeed get updated? Or if the pilot puts in a new Vapp at any time, then GS mini and the target speed get updated?

currently the computation for this is done continuously, I might want to change this to only update whether the runway has changed or the entered speed has changed.

The Ground Speed Mini gets calculated continuously by the autopilot.

**Comment by donstim** [comment]
First test -- just testing Vapp shown on PERF APPR page in MCDU. Spotted some issues, not all of which are associated with this PR.

1. Displayed approach speed was changing with actual headwind, not with the headwind component calculated in the true runway axis from the wind data entered into LSK 3L. Because of this, Vapp kept changing with gusts, which is it not intended to include.
2. Pilot entered Vapp remained a constant, which is correct behavior.
3. When I attempted to clear a pilot entered Vapp, I got a "NOT ALLOWED" message in the scratchpad, Clearing the pilot entered Vapp should return to the FMS computed value. Although I received that error message that should not appear, Vapp did revert, but to the incorrect actual wind-based value rather than the value computed for the pilot entered winds.
4. I was able to enter a value of "1" for Vapp. The allowable data range is 90 to Vmo for Vapp (although I am surprised that it may allow you to enter a value less than Vls? maybe check with a pilot).

Screenshot (387)

Screenshot (388)

**Comment by MisterChocker** [comment]
For 3 and 4, thats part of #1824

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: Current date 11/12/2020
Version of the sim: 1.11.7
PR Tested: #2304 
Object of test: Ground speed mini 

Testing technique: Did a normal approach with direct headwind for testing
Steps you've made to test the Pull Request:
1. Set perf page; during this approach winds were 300/7kts, vls was 131 hence vapp= 136 (vls+5 since headwind component is less than 5)  
2. Tested gs mini baseline; GS mini base= vapp-wind entered in perf page=136-7=129 
image

3. V target speed test; V target (the speed that the AC needs to maintain)= GS mini baseline+adirs wind value 

To test if the gs mini is functioning correctly we need to test if the AC is targeting the right speed in order to maintain a constant ground speed mini baseline, this varies according to the adirs wind value hence, that is why the IAS is not always vapp, in this example adirs wind on the nd was 10 kts (3kts higher) so the target speed should be 129(gs mini base)+10(adirs wind value)=139
Desktop Screenshot 2020 12 11 - 16 28 14 10
  


Flight notes (If required): N/A

Issues (If Any): N/A
Overall Rating: The maths adds up so LGTM 
Conclusions of the testing: Great work, good job!

**Comment by MisterChocker** [comment]
@Lazarus320 thanks for the feedback, I just spotted an mistake by me.
Tower headwind shall be maximum 10knots:
Min[tower headwind, 10]
But this what I did:
Max[tower headwind, 10]

That's why the vtarget was at 136

I've corrected this now.

**Comment by MisterChocker** [comment]
Btw the easiest way to check for correct vtarget is to fly at a higher speed so that the vtarget will be outside range and displayed as number below the speedband.

**Comment by donstim** [comment]
I think that the MCDU Vapp is still not working right.  First, in reference to comment above about tower headwind component, I am probably not understanding what you meant, but there is no limitation on what can be input for the tower headwind component. The only "limits" are on: (1) the value of GS mini (for tailwinds or tower headwind components of less that 10 knots; and (2) the maximum wind correction applied to Vapp.

I know you have already coded to the formula in the reference screenshot, but I think it would have actually been easier (less chance of mistake) to code to the algorithm provided in the FCOM. Both end up with the same target speed, but for some reason the GS  mini calculation is different.

1. For my test, I started with a tower reported wind of 0/0, and a landing runway of 16R at KSEA (mag hdg 164 deg). Vapp was correctly shown as Vls +5, 
2. I then input a tower wind of 164/15, and Vapp correctly did not change. I then input a tower wind of 164/45, and Vapp showed a speed of Vls+10. This is incorrect. Vapp should be Vls + 1/3 the tower reported headwind component in the direction of the runway, limited to Vls + 15. 1/3 of 45 is 15, so Vapp in this case should have been Vls + 15.
3. I then put 164/12 in, and a Vapp equal to Vls+10 was returned. It should have been Vls + 5 -- the computation is Vls + 1/3  but limited to a minimum of Vls+5 and a max of Vl+15. Vls + 1/3 of 12 is 4, sho Vapp should have been Vls+5.
4.  I then put 344/10 in, and Vapp remained at Vls+10. This is incorrect as it would be a tailwind in the runway axis, so Vapp should again just be Vls + 5.

How are you determining the runway heading? Since Vapp depends on the headwind component in the runway axis, that **implies** (though I have not found a clear statement in our reference documents to include here) that the runway must be entered in the flight plan in order to calculate Vapp. This further **implies
** that white dashes should be shown for Vapp when a runway has not been entered in the flight plan. A pilot (or someone with better documentation) needs to be consulted to verify the correct behavior in this regard.

 LSK 1R in the PERF APPR page shows the final approach selected, which also contains the runway that will be used. I do not know if you can select a runway without an approach, but if you haven't selected an approach, this field will be blank. It is also blank, of course, if no arrival runway has been selected. Depending on whether you can select an arrival runway without an approach, it may be possible to use this field to determine the arrival runway in order to compute Vapp.
 
Screenshot (392)
Screenshot (393)_LI
Screenshot (394)_LI
Screenshot (380)
Screenshot (381)

**Comment by MisterChocker** [comment]
@donstim tower headwind for Vapp no longer has max limitation, limitation of max 10kt tower headwind still applies for gs mini.

**Comment by donstim** [comment]
@MisterChocker Ok, but that's not how it should be. There shouldn't be any limitation at all on the tower headwind. The limitations should be on the min and max additives to Vls for Vapp and the minimum target speed accounting for GS Mini (and on GS mini if you really want to stick with the more complex formulation of GS mini and not go with the FCOM formula).

Are you still working on the other issues I identified? Here are screenshots using the current version that still show issues with the Vapp computation:
With mag wind input, mag heading of 16R at KSEA is 164 deg according to the approach chart. With input wind of 164/45, Vapp shown is Vls + 13 instead of the expected Vl+15. Maybe an issue with navdata runway hdg vs chart?
Screenshot (401)

With 165/45 entered as wind, I now get the expected Vls+15. But cos 1 deg is 0.999, so how did that make 2 knots difference in the Vapp speed correction?
Screenshot (403)

With 100/45 entered, Vapp = Vls+5. However, a 100 deg wind should still have a headwind component of almost 20 knots, so I expected a Vapp of Vls + 7 (or at least +6).

With a wind of 344/45 entered, Vapp shown is Vls+15.  This is a direct tailwind, so Vapp should be Vls+5, regardless of the magnitude of the wind. (Yes, I know a 45 knot tower-reported tailwind is not realistic, and even if it was, is outside the tailwind limitation for the airplane.)
Screenshot (405)

It is important to get Vapp and the tower reported headwind correct because that is what GS mini is calculated from.

**Comment by MisterChocker** [comment]
> With input wind of 164/45, Vapp shown is Vls + 13 instead of the expected Vl+15.

`141 - 126 = 15` where do you see vls + 13?

> @MisterChocker Ok, but that's not how it should be. There shouldn't be any limitation at all on the tower headwind. The limitations should be on the min and max additives to Vls for Vapp and the minimum target speed accounting for GS Mini (and on GS mini if you stick with the more complex formulation of GS mini and not go with the FCOM formula).
> 
> Here are screenshots using the current version that still show issues with the Vapp computation:
> With mag wind input, mag heading of 16R at KSEA is 164 deg according to the approach chart. With input wind of 164/45, Vapp shown is Vls + 13 instead of the expected Vl+15. Maybe an issue with navdata runway hdg vs chart?
> Screenshot (401)
> 
> With 165/45 entered as wind, I now get the expected Vls+15. But cos 1 deg is 0.999, so how did that make 2 knots difference in the Vapp speed correction?
> Screenshot (403)
> 
> With 100/45 entered, Vapp = Vls+5. However, a 100 deg wind should still have a headwind component of almost 20 knots, so I expected a Vapp of Vls + 7 (or at least +6).
> 
> With a wind of 344/45 entered, Vapp shown is Vls+15. This is a direct tailwind, so Vapp should be Vls+5, regardless of the magnitude of the wind. (Yes, I know a 45 knot tower-reported tailwind is not realistic, and even if it was, is outside the tailwind limitation for the airplane.)
> Screenshot (405)
> 
> It is important to get Vapp and the tower reported headwind correct because that is what GS mini is calculated from.

This might be due to `Math.abs(v * Math.cos(a))` I need to check why I added it, if it's not needed, removing the abs will result in vls + 5

**Comment by donstim** [comment]
> > With input wind of 164/45, Vapp shown is Vls + 13 instead of the expected Vl+15.
> 
> `141 - 126 = 15` where do you see vls + 13?
Sorry, wrong screenshot
Screenshot (402)

**Comment by MisterChocker** [comment]
Quick update, just found out JS Math.cos uses RAD instead of DEG... I need to sort that out

**Comment by MisterChocker** [comment]
vapp is now vls + 7, vtarget is now vapp + 10, because max tower headwind for gs mini is 10kt.
image

**Comment by donstim** [comment]
> wind is steady 20kt from 270.
> vapp is now vls + 7, vtarget is now vapp + 10, because max tower headwind for gs mini is 10kt.
> But I do have a concern, because vtarget will now always be too high or never target vapp in greater wind speeds.
> I am removing the max tower headwind limitation for gs mini since it makes no sense.

I've been saying that there is max tower headwind limitation!  xD:
Any time the current headwind component is greater than the tower reported headwind component, the target airspeed should be higher than Vapp (by the amount the current HWC exceeds the THWC). 

Conversely, any time the current HWC is less than the THWC, Vtarget should be Vapp.

See FCOM equations and descriptions.

**Comment by Lazarus320** [comment]
@MisterChocker This might help 
image

**Comment by donstim** [comment]
@Lazarus320 This chart appears to agree with the info in the reference page at the top of this PR, but appears to disagree with the FCOM and Honeywell pages I added. According to this picture, for any tower reported wind of 10 knots or less, Vtarget will be Vapp + IRS HW -10 (with a minimum of Vapp).  But, according to the FCOM and Honeywell manuals, it appears to me that Vtarget is always Vapp + IRS HW (with a minimum of Vapp). For example, Vapp=127, TRHWC=0, IRS HWC= 10, Vtarget picture=127-10+10=127, but Vtarget FCOM = 127+10=137.

Am I reading this wrong? Does one source represent a more recent version of the GS mini correction than the other? For example, is what you supplied more recent, and Airbus decided to lower the Vtarget increase for TRHWC of less than 10 knots?

**Comment by Lazarus320** [comment]
@donstim The image I attached earlier might be confusing apologies, yes Vtarget is Vapp+ADIRS wind , the reduction of GS-mini to Vapp -10 happens when the headwind component in the PERF page is 10 kts or less or there's a tailwind.
  image
 
image

**Comment by MisterChocker** [comment]
Alright, so I added 
- Vtarget max is Vmax
- GS mini min tower headwind is 10, so below 10kt twr headwind, Vapp - 10

**Comment by donstim** [comment]
> @donstim The image I attached earlier might be confusing apologies, yes Vtarget is Vapp+ADIRS wind , the reduction of GS-mini to Vapp -10 happens when the headwind component in the PERF page is 10 kts or less or there's a tailwind.

@Lazarus320 The figure you attached was not confusing to me at all. Maybe I wasn't clear in my response. What I am troubled by is that the screenshots you posted contradict what is in the FCOM and Honeywell documents we have been using.  According to your info, if THwC = 0 and IRS HWC = 10, then GS mini = Vapp-10 and Vtarget = Vapp.  According to the FCOM and Honeywell info, for the same conditions, GS mini = Vapp and Vtarget = Vapp + 10.

What is the source of your information and what is its date? If I am not reading the FCOM and Honeywell info correctly (see my screenshots above), it appears that the GS mini correction has changed over time. But, which one is current?

**Comment by donstim** [comment]
Thanks for changing this! The overall algorithm now matches the FCOM with just the new 1/3 factor on the wind additive to Vtarget for the neo.  I tried it with various combinations of headwinds, tailwinds,  and no wind entered in the MCDU and MSFS weather. Seemed to work perfectly.

A note to other testers:  If you want to get a steady wind in MSFS to check the corresponding target speed, delete the gust value, but don't enter 0 or it will revert back to 50%!

I hope this important enhancement will be QA'd quickly!

**Comment by Lazarus320** [comment]
> > @donstim The image I attached earlier might be confusing apologies, yes Vtarget is Vapp+ADIRS wind , the reduction of GS-mini to Vapp -10 happens when the headwind component in the PERF page is 10 kts or less or there's a tailwind.
> 
> @Lazarus320 The figure you attached was not confusing to me at all. Maybe I wasn't clear in my response. What I am troubled by is that the screenshots you posted contradict what is in the FCOM/FCTM we have been using. According to your info, if THwC = 0 and IRS HWC = 10, then GS mini = Vapp-10 and Vtarget = Vapp. According to the FCOM and FCTM info, for the same conditions, GS mini = Vapp and Vtarget = Vapp + 10.
> 
> What is the source of your information and what is its date? If I am not reading the FCOM info correctly (see my screenshots above), it appears that the GS mini correction may have changed over time. But, which one is current? Either that of the FCOM/FCTM info just left out the nuance that 10 knots HW is assumed.

I'm really sorry it turned out I was looking at an older fcom and upon checking the latest one turns out it does not include the 10 kt mandatory HW I pointed out, apologies!

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date 13/12/20
Version of the sim: 1.11.7.0
PR Tested: #2304 
Object of test: FMS

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Did a full flight 
2. did a few spawns on approach 

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Looks good to me with the info I have received on what it should be doing

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: Current date 13/12/20
Version of the sim: 1.11.7.0
PR Tested: #2304
Object of test: GND Speed Mini 

Testing technique: Full Flight from EGKK to LOWI
Steps you've made to test the Pull Request:

1. Full Flight from C&D from EGKK to LOWI on VATSIM
2. RNP Z 08 assigned by approach
3. Descent through the valley with early full config 
4. During manual base turn through the valley and turn onto finals, speed mini adjusted to take account of the wind direction with heading change
5. Landed 

Flight notes (If required):

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Appears to be working as described, had no issues and it changed dynamically 1-2kts as I made turns through the valley into LOWI. Thanks for the nice addition!

**Pull request merged**
