### PR TITLE
[CDU] Fix double arrows on INIT FUEL PRED page

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Fixed double arrows showing on the INIT FUEL PRED page

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Complete both the INIT A and INIT B pages of the MCDU
2. The INIT B page will change to INIT FUEL PRED, make sure there is only one set of arrows in the upper right corner when this happens.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]
LGTM. Don't forget to add changelog.

**Comment by tyler58546** [comment]
> 
> 
> LGTM. Don't forget to add readme.

I assume you meant changelog. Not needed because this is not an issue in stable.

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 12.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3012 
Object of test: Double Arrow (lego Train Symbol) on INIT FUEL PRED

Testing technique: TryOut, about the same order when i found the issue
Steps you've made to test the Pull Request:
1. loaded in C&D at LSZH A44
2. turned on batteries and ext power
3. imported INIT A
4. Filed FPLN
5. Loaded all weights in the AOC
6. filed out INIT B

Flight notes (If required): n/a

Issues (If Any): Arrow is a bit close to the text 
Overall Rating: If not realistic: to be improved.
Conclusions of the testing: Fixes the original Issue of a doubble arrow, however, now the arrow almost touches the text, which looks a bit weird. 

Microsoft Flight Simulator Screenshot 2021 01 12 - 22 12 52 39

**Comment by mattstertx** [comment]
Category: QA Tester/Trial
Name:  Mattstertx#7410
Date of testing: Current date 17/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3012
Tier of testing: 2
Changes to observe: Fixed double arrows showing on the INIT FUEL PRED page


Testing technique: Followed Testing Instructions
Steps you've made to test the Pull Request:
1. Loaded into KDFW C&D
2. Turned on batteries and Ext Power
3. Loaded flight plan from simbrief
4. Loaded Fuel and Payload
5. Filled out Block Fuel and ZFW and Trip Wind

Flight notes (When done a full flight): N/A

Media: Microsoft Flight Simulator Screenshot 2021 01 17 - 19 02 48 57


Issues (If Any): Left Arrow is really close to the N in prediction
Could Shrink text size slightly to give a bit of gap. 

Overall Rating: To be improved
Conclusions of the testing: Issue is fixed aside from the slight issue of the arrows being close to text.

**Comment by tyler58546** [comment]
The spacing issue has been fixed.
image

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 23.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3012 
Tier of testing: 1
Changes to observe: Fixed Double Arrows and Spacing on INIT Fuel Pred


Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned C&D at LSZH, A44
2. Started up the A/C
3. Setup all data needed to go to the Init Fuel Pred Page
4. Checked the Page

Flight notes (When done a full flight): n/a

Media:
Microsoft Flight Simulator Screenshot 2021 01 23 - 14 01 25 80

Overall Rating: Good
Conclusions of the testing: Works as expected, all issues have been resolved. Good to go

**Pull request merged**
