### PR TITLE
[CDU] Implement airway to airway insertion

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Added airway to airway insert option
- Solved wrong `AWY/WPT MISMATCH` caused by not refreshing waypoints airway(s).

## Screenshots (if necessary)

airways_improvements

## References

image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Teslix** [comment]
Category: QA Tester
Name: Teslix#8746
Date of testing: 27/11/2020
Version of the sim: 1.11.6.0
PR Tested: #2110
Object of test: Verify implementation of airway to airway insertion

Testing technique:
Steps you've made to test the Pull Request:
1. Spawn C&D in CYVR
2. Apply power and init MCDU (to/from/align IRS)
3. Enter Flight Plan CYVR to KMIA (YVR J52 FQF J80 GLD J182 ICT RZC MEM MGM J41 PIE CYY1)
4. Ensure using airway-to-airway function to input airways.

Issues (If Any): They worked eventually. Sometimes I would get an AWY/WPT MISMATCH and would take 2 or 3 entry attempts for it to stick. Unsure if this is a problem with the implementation, but I've also had issues in the master trying to put in waypoints lately as well (just not taking and needing to input them 2 or 3 times to stick).
Overall Rating: Good
Conclusions of the testing: Once the points stuck, it worked flawlessly.

awys

**Comment by MisterChocker** [comment]
> They worked eventually. Sometimes I would get an AWY/WPT MISMATCH and would take 2 or 3 entry attempts for it to stick. Unsure if this is a problem with the implementation, but I've also had issues in the master trying to put in waypoints lately as well (just not taking and needing to input them 2 or 3 times to stick)

yes I have noticed that too, but thats this way before too. I will look at it and try to get rid of that bug.

**Comment by MisterChocker** [comment]
Alright I found a nice workaround, these should be no longer an issue at all.
Either it's waypoint mismatch or it's a valid waypoint/airway.

**Comment by beheh** [comment]
Currently, your error message is always `AWY/WPT MISMATCH"`. However that only applies if you enter airway + waypoint. If you enter two airways the error should be `NO INTERSECTION FOUND`:

image

image

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: Current date 27.11.2020
Version of the sim: 1.11.6.0
PR Tested: #2110 
Object of test: Airways to Airways insertion

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Loaded up at gate A44 in LSZH
2. Created a Flightplan from LSZH to KDEN
3. tried to enter the airways


Flight notes (If required): 
Route: LSZH/34 VEBI1K VEBIT T51 LASUN UT10 RLP UL613 SOVAT L613 SANDY UN601 LESTA UP6 RODOL UL28 PENIL M144 BAGSO DOGAL NATA ELSIR CEFOU YXI DBQ J128 OBH KOHOE4.OBH KDEN/16R

Issues (If Any): Somehow, when entering multiple Airways, it takes takes the whole airway instead of a small leg on the route. The last Airway entered also doesnt appear to be entered (In this Case UN601)

https://cdn.discordapp.com/attachments/314015589595086848/781948336416227348/Microsoft_Flight_Simulator_2020.11.27_-_19.19.57.01.mp4

Picture1

Picture2

Overall Rating: To be improved (if it turns out to be an error indeed)
Conclusions of the testing: With these described issues, its impossible to use this feature when entering more than 2 Airways

**Comment by marinerhally** [comment]
Category: QA Tester
Name: Discord User Mariner Hally#0715
Date of testing: 28/11/2020
Version of the sim: 1.11.6.0
PR Tested: #2110
Object of test: Testing airway to airway insert into MCDU

Testing technique: 
Steps you've made to test the Pull Request:
1. Spawned C/D
2. Powered up aircraft and instruments
3. Inputted flight plan below from EGNM/LIPZ
4. LAMI2W LAMIX L603 LAMSO DCT EVELI DCT COL UZ738 RIDSU UL607 UTABA M738 ADOSA L612 ALBET ALB1X
5. Inputted Airways to Airways

Flight notes (If required):

Issues (If Any): No issues here, works fine :)
Overall Rating: Good
Conclusions of the testing:

**Comment by valenzz2004** [comment]
Category: QA Tester
Name: Valenzz2004#7802
Date of testing: 28/11/2020
Version of the sim: 1.11.6.0
PR Tested: #2110
Object of test: Airway to airway insertion

Testing technique: Description of how author tested the Pull Request
Steps you've made to test the Pull Request:

1. spawned c/d at EGKK
2. applied external power 
3. manually inputted EGKK-EDDM
4. ODVI2Z ODVIK Y311 DVR UL9 KONAN UL607 KOK MATUG MOVUM T109 HAREM T104 ANORA ANOR3A

Flight notes (If required): 

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: all fine with me working as planned

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#8145
Date of testing: Current date 11/28/2020
Version of the sim: 1.11.6
PR Tested: #2110 
Object of test: Airway to Airway insertion.

Testing technique: Actually used above testers method. Loaded in the plan he had at his airports.
Steps you've made to test the Pull Request:
1. Used @valenzz2004 steps.
2. ODVI2Z ODVIK Y311 DVR UL9 KONAN UL607 KOK MATUG MOVUM T109 HAREM T104 ANORA ANOR3A

Flight notes (If required): None. Worked like a charm.

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: LGTM.

**Pull request merged**
