### PR TITLE
Tie Switches/Buttons Local Variables to Animations

### PR DESCRIPTION
**Pull request by Sequal32**
## Summary of Changes

Functionally, these changes should not affect much.

- Simplifies the fire guard/button switches, and ties a var tagged `TOGGLE_VAR` to animations
- Instead of using `LEFT_SINGLE_CODE` for dummy switches to set local variables, I changed it to use the built in template's `SWITCH_POSITION_TYPE` and `SWITCH_POSITION_VAR` (mainly for guard switches)
  - The FLT files have been changed to reflect this

## Additional context

This helps the support of the shared cockpit program YourControls change the state of these buttons/guard switches without having to include its own modified files.

Discord username (if different from GitHub): Sequal#9050

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
For QA: just verify that overhead panel switches remain functional

**Comment by Lazarus320** [comment]
> For QA: just verify that overhead panel switches remain functional

LGTM

**Comment by myselfaaryan** [comment]
Category: QA Tester
Name: myselfaaryan#0001
Date of testing: 7/12/2000
Version of the sim: 1.11.6.0
PR Tested: #2236 
Object of test: To test if the overhead switches work for this PR

Testing technique: Try Out
Steps you've made to test the Pull Request:
1. Spawned C/D
2. Checked all overhead switches
3. Checked all upper overhead switches as well

Flight notes (If required): N/A

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Works as described. No changes required.

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 07/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2236
Object of test: To test the tying of Switches/Buttons Local Variables to Animations

Testing technique: Tryout
Steps you've made to test the Pull Request:
1. Spawn at the gates C&D
2. Turned on Batteries, GPU
3. All overhead switches work as expected
4. Completed a 1-hour flight
5. Checked again after parking, same result

Flight notes (If required): N/A

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Feature works as expected

**Pull request merged**
