### PR TITLE
fix(nd): prettier ND with more formatting

### PR DESCRIPTION
**Pull request by sidnov**
## Summary of Changes

- [x] Separated degree symbol from waypointTrack variable
- [x] Aligned the value and symbol for waypointTrack
- [x] Created a new class for DegreeSymbol
- [x] Separate distance display logic (greater than and less than 20)
- [x] Adjusted values to smoothen transition for VORDME distance info on ND
- [x] ND Chronometer background
- [x] ROSE VOR and LS Page fixes with proper formatting and color
- [x] PPOS (Present position, when waypoint not loaded and C/D)
- [x] Black masking behind left VOR indicator to prevent drawn flight route from showing through

NOTE: 
1. ADF section wasn't modified individually as the variables are tied with VOR.

2. ~~On IRL displays, decimals have a smaller size on both Waypoint Distance indicator (top right) and VOR DME distance (bottom), it is left untouched for now.~~ Added decimal split and resizing wherever applicable, credits to @tracernz 🎉 

3. PPOS has not been implemented true to logic. It will only appear when no waypoint is loaded for now. Will implement logic with flightphase changes in a different PR.

### BEFORE:
image
image

### AFTER:
image
image
image
image
image
image

## References

image
image
image
image

https://youtu.be/TEi-WX08ov8?t=17
https://youtu.be/syr4G3pokgU?t=99

## Additional context

Discord username (if different from GitHub): sidnov#8337

## Testing instructions

1. Spawn C&D, check the updated ND
2. Align ADIRS, see the changes
3. Add VORs, waypoints, and fly through them.
4. Observe for any overlap in ARC, ROSE VOR and ILS distances/names/values on the top right of ND.
5. Observe distance decimal values appear only when Waypoint<20NM
6. Additionally, check VOR DME distance displayed on the bottom of the ND, updated with the same logic/value.
7. ND Chronometer has an improved background.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by myselfaaryan — APPROVED** [review]
GTG!

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 11.3.2021
Version of the sim: 1.14.5.0
PR Tested: #3870
Tier of testing: 2
Changes to observe: ND drawings
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned on runway at EDDP
2.) Took off and get to next waypoint
3.) Set a VOR 
4.) Set a ADF

Media:


Image1

Issues: 

- VOR distance can jump in 0.2 steps of fast speeds
- Tracks a drawn behind the ND chrono (?) (Image1)
- ADF distance is not shown (?) (Image1)


Overall Rating: -

Conclusions of the testing: Looks good. Small issues found.

Hope this helps :-)

**Comment by TheSquirtingPantin** [comment]
Category: QA Trial
Name: Discord User Rémi#8871
Date of testing: 11/03/2021
Version of the sim: V 1.14.5.0
PR Tested: #3870
Tier of testing: 1
Changes to observe: Validate ND new formatting. 

Testing technique: 
1. C/D on the ramp
2. Selection of different navaids (with the IDENT or manually entering frequency)
3. Field validation and MCDU/ND crosscheck.

Flight notes: N/A

Media:
ND_VORbug

MCDU_NavRad

Issues (If Any):
	- When manually entering a frequency in the RAD/NAV MCDU page (i.e 116.95 MHz), the value displayed on the ND is rounded up to nearest whole number (i.e: 117)
	- When entering any value with .00 as decimal, the ND VOR value is showing a whole number.

Overall Rating: To be improved
Conclusions of the testing:
Expecting manually entered value to be displayed with format "nnn.nn" rather than "nnn".

Have a good night !

**Comment by sidnov** [comment]
> * VOR distance can jump in 0.2 steps on fast speeds
> * Tracks a drawn behind the ND chrono (?) (Image1)

For the first one, can't really do much about it, since that's how the sim is processing the distance from the navaid variables. It increments/decrements 0.2 if speed is high probably due to radio inaccuracies.
I'll try and find a possible fix for the 2nd one. Should be able to add a temporary mask to the Chrono.

**Comment by sidnov** [comment]
> Issues (If Any):
> - When manually entering a frequency in the RAD/NAV MCDU page (i.e 116.95 MHz), the value displayed on the ND is rounded up to nearest whole number (i.e: 117)
> - When entering any value with .00 as decimal, the ND VOR value is showing a whole number.

This is interesting, maybe I mixed up 2 conversion functions, because the rounding off is not necessary here. Will have a look, thanks for testing :)

**Comment by marcman86** [comment]
> I'll try and find a possible fix for the 2nd one. Should be able to add a temporary mask to the Chrono. Thanks for testing! :)

Please ask the pilots first if this is a thing or not :-)

**Comment by sidnov** [comment]
> > I'll try and find a possible fix for the 2nd one. Should be able to add a temporary mask to the Chrono. Thanks for testing! :)
> 
> Please ask the pilots first if this is a thing or not :-)

It is, I checked a few references. You were correct, the flight path line shouldn't show behind both the left navaid and chrono.

**Comment by sidnov** [comment]
image

Fixed the VOR decimal issue (was an entirely different bug, something I hadn't noticed or touched before) and the mask behind the ND Chrono.

**Comment by marcman86** [comment]
I tested again. Works fine so far. Two things i noticed:
- The "M"s of the VOR and ADF is not masked
- When VOR1 = VOR2 the distance show differences (due to the radio inaccuracy "simulation")

**Comment by sidnov** [comment]
> I tested again. Works fine so far. Two things i noticed:
> 
> * The "M"s of the VOR and ADF is not masked
> * When VOR1 = VOR2 the distance show differences (visible when <20NM, due to the radio inaccuracy "simulation")


1. Expected. The mask as verified from IRL footages indicated they start somewhere right in middle of the VOR Mode indicator 
image

2. I have noticed the difference too. Probably a simulated difference between the radios (I honestly liked that part, because IRL it isn't really that accurate compared to other systems like GPS, so didn't really investigate it :P)

Thanks once again for testing! 🚀

**Comment by marcman86** [comment]
Then i think its good to go! :-)

**Comment by TheSquirtingPantin** [comment]
Category: QA Trial
Name: Discord User Rémi#8871
Date of testing: 14/03/2021
Version of the sim: V 1.14.5.0
PR Tested: #3870
Tier of testing: 1
Changes to observe:
Validate ND new formatting. 

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. C/D on the ramp
2. Selection of different navaids (with the IDENT or manually entering frequency)
3. Field validation and MCDU/ND crosscheck.
4.
5.

Flight notes (When done a full flight):N/A

Media:

ND_IDBug


Number_ND_Spacing

AFC_PND



Issues (If Any):
	- Spacing between the manually entered frequencies (either ADF or VOR) and ADF/VOR symbols too tight. Especially for the VOR/ADF 1 section on the left side of the ND. Ride side seems better knowing that we are limited by font size for decimals. 
	- Weird formatting detected when displaying the NDBs on the ND (See picture "PND" NDB near PDX INTL airport). Other NDBs checked, no issues (LFBO airport: TOE, TLF, TS shown with normal spacing). Sim reloaded no change. Checked for potential dual navaids on the smae spot/ nothing found.


Overall Rating: To be improved
Conclusions of the testing:
	- Some cosmetic change required for better user experience (spacing for manually entered frequencies)
	- Wrong formatting of some NDBs ID with no procedure or specific way to replicate. Some NDBs are showing properly some other are incorrectly displayed. 

Have a good day !

**Comment by TheSquirtingPantin** [comment]
Did an extra zoom for on the ND picture for the NDB issue. Looks like the NDB type (LO or HI)is showing under the ident. Going to run some additional test tonight.

**Comment by sidnov** [comment]
@TheSquirtingPantin Thanks for the testing and feedback! Fixed now 

image

**Comment by TobitFR** [comment]
Hello, on the references I found that the decimals numbers are on a smaller size, it could be great to have it (I added some lines to be easier to see)
image

Seen here https://youtu.be/TEi-WX08ov8?t=69

**Comment by sidnov** [comment]
> Hello, on the references I found that the decimals numbers are on a smaller size, it could be great to have it (I added some lines to be easier to see)
> image
> 
> Seen here https://youtu.be/TEi-WX08ov8?t=69
> 

Hi there! Thanks for the feedback. I did have plans initially to do this, but it involves a lot of code separation and changes which I'm currently trying to avoid, as I think a complete rewrite of the instrument code is imminent.

**Comment by sidnov** [comment]
@tracernz Would love to hear your thoughts on this, if there is a way to reduce the size of the decimal without affecting global update functions or messing around a lot with the MFD code. (Have tried Math.Floor, splitting as a string, etc. till now and none of these worked 100% accurately, it gives function errors at some point or the other)

**Comment by tracernz** [comment]
> 
> 
> @tracernz Would love to hear your thoughts on this, if there is a way to reduce the size of the decimal without affecting global update functions or messing around a lot with the MFD code. (Have tried Math.Floor, splitting as a string, etc. till now and none of these worked 100% accurately, it gives function errors at some point or the other)

Try this patch and see what you think:
https://gist.github.com/tracernz/eac9a2b3677c5be2a2786888bedb698b

image

**Comment by sidnov** [comment]
> > 
> > 
> > @tracernz Would love to hear your thoughts on this, if there is a way to reduce the size of the decimal without affecting global update functions or messing around a lot with the MFD code. (Have tried Math.Floor, splitting as a string, etc. till now and none of these worked 100% accurately, it gives function errors at some point or the other)
> 
> Try this patch and see what you think:
> https://gist.github.com/tracernz/eac9a2b3677c5be2a2786888bedb698b
> 
> image
> 

This looks great! Will run a few tests and try to implement it for the VOR distance too. Thanks a million @tracernz 😀

**Comment by tracernz** [comment]
> This looks great! Will run a few tests and try to implement it for the VOR distance too.

Should already be done I think. Basically I positioned the left hand stuff all relative to it's left hand side, and the right hand stuff all relative to it's right hand side. I also positioned the ident/frequency and distance on the bottom rather than the middle so the big and little numbers line up at the bottom.

**Comment by wpine215** [comment]
Is this ready to merge?

**Comment by sidnov** [comment]
> Is this ready to merge?

Just one more commit remaining for the decimals, should be good to go.

**Comment by sidnov** [comment]
Doing a final check on this one with a short flight, will update once done

**Comment by myselfaaryan** [comment]
Merging, as notified via Discord.

**Pull request merged**
