### PR TITLE
fix: hotfix for hook dependencies

### LINKED ISSUE #7216: ND issues after #7180
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-05-18T19:03:16+00:00",
    "ref": "refs/heads/master",
    "sha": "9b67261c0e10ea026958e179c6132c80388da893",
    "actor": "aguther",
    "event_name": "manual",
    "pretty_release_name": "master:9b67261c"
}
```

### Describe the bug

I just did a first flight after #7180 was merged. Noticed issues of the ND not properly refreshing. My refresh rate setting is set to medium. Also the T/O config button is not responsive and needed a few extra clicks in order to work.

### Expected behavior

I would expect the ND to work properly and responsive.

### Steps to reproduce

1. Start a flight cold and dark
2.  Set-up the aircraft and taxi out
3. Observe ND and check other button functionality

### References (optional)

Here is the view when on runway 14L at EDDK:

EDDK

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #7216

## Summary of Changes

Fixes issues caused by PR #7180 (See issue 7216)

## Additional context

Discord username (if different from GitHub): 2Cas#1022

## Testing instructions

- Check that ND arc mode refresh updates as expected
- Check that T/O CONFIG responds correctly.
- Check that SELECTED HDG bug is working on ND

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by 2hwk** [comment]
Seems there are some more fundamental issues at play, closing for now

**Review by ErickSharp — APPROVED** [review]
LGTM!

**Review by davidwalschots — APPROVED** [review]
Seems fine! Maybe for future work this code:
```typescript
let systemStatus = false;
if (engine1Generator && engine2Generator && !greenLP && !yellowLP && !blueLP && eng1pumpPBisAuto && eng2pumpPBisAuto) {
    systemStatus = true;
}
```
Can be replaced with:
```typescript
const systemStatus = engine1Generator && engine2Generator && !greenLP && !yellowLP && !blueLP && eng1pumpPBisAuto && eng2pumpPBisAuto;
```

**Comment by 2hwk** [comment]
@davidwalschots agreed, will probably have to wait for another PR though, this is just a hotfix to fix the dev branch for users

**Comment by Saschl** [comment]
ND works!

**Pull request merged**
