### PR TITLE
fix: Flight model changes to fix pitch oscillation (better transitions between flight modes)

### PR DESCRIPTION
**Pull request by MapleNAV-TCASFAULT**
Fixes #[N/A]

## Summary of Changes

Fixed, the pitch oscillation, during flare mode, and partially removed the hard banking to one side during flare too. This should also partially fix the weird transition between during rotation (the aircraft not wanting to pitch higher up than 10 degrees). This is a temporary fix, and the new FBW system will probably iron everything out

## References

References were from previous experience with airbuses in FSX and X-Plane. (Aerosoft and ToLiss)

## Additional context

Discord username (if different from GitHub): ChristopherXie #3904

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Snapmatics** [comment]
Is it ready for testing?

**Comment by MapleNAV-TCASFAULT** [comment]
> Is it ready for testing?

Yup, ready to go!

**Comment by MisterChocker** [comment]
Are you aware of #1580? I haven't seen anything on the discord regarding the development of this pr? Are you on our discord server? I would like to get a conversation doing on there.

**Comment by MapleNAV-TCASFAULT** [comment]
> Are you aware of #1580? I haven't seen anything on the discord regarding the development of this pr? Are you on our discord server? I would like to get a conversation going on there.

Yes I am on the discord server. This is just a quick PR as I found that my flight_model.cfg tweaks seemed to fix a few issues for me and maybe others too. I can possibly close this PR and merge it with yours.

**Comment by MisterChocker** [comment]
@MapleNAV-TCASFAULT can you please join the discord discussion?

**Comment by krangerich** [comment]
Why are the stabilities at odd values like 5.25 and 3.25? Even if such sudden large increments >10x would be reasonable, I'd go with rounded values like 5.0 and 3.0, unless the values are somehow precisely calculated or taken from official tables.

**Comment by danbw9** [comment]
Category: QA Test
Name: danbw9#7028
Date of testing: Current date 19/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2016
Object of test: Testing fixed pitch oscillation

Testing technique: Spawn on approach and make 3 approaches and landings
Steps you've made to test the Pull Request:

Coordinated with @MapleNAV-TCASFAULT for what results to look for via discord VC.
Spawn C&D on approach for 22L EKCH. 3 degrees glide path and 700 FPM ROD - with no pre flare, per FCTM. Also corrected VAPP speed to give 2.5 degrees nose up for best simulation. 
Ensure clear skies with 0 wind for objective test.  
- 1st flared like I did before the PR (15-20FT RAD ALT) with same flare point and stick input and resulted in hard landing
- 2nd attempt: anticipated the need to flare higher up as would in the real aircraft and with a continuous flare at the correct speed, and feeling was all fine. Stable and no oscillation with pitch.
- 3rd attempt: pilot induced roll left and right on short final and into the range of 30-50FT to check for the previous bug with the wing and complete lack of lateral authority. 

Also asked for feedback from h20genie on discord who tested the PR with an Xbox controller and the feedback on his experience was positive and said it was much better than before. 

Issues (If Any): None. 
Overall Rating: Good
Conclusions of the testing: Great work by @MapleNAV-TCASFAULT. The plane feels a lot more stable though compared to without the PR I am flaring a much more appropriate height at around 20-30 FT RAD ALT where as before 10-20 FT. I know every simmer would have their own landing technique so this change would catch people out initially until they get used to it. With the changes of this PR, the inertia with a 60 T plane is a lot more noticeable.

**Comment by tareksabet** [comment]
Category: QA Tester
Name: Discord User: tarek_sabet#7946
Date of testing: Current date 20/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2016 
Object of test: Testing fixed pitch oscillation

Testing technique: did landings (spawned on approach) with different loadout and different takeoffs
Steps you've made to test the Pull Request:

- In the beginning of testing It was sensitive for me but then changed some stuff in the settings.

- spawned on approach several times did the flare around  a height of 30ft with different weights of plane and made sure that the Vapp was correct and 0 wind and also did couple of Takeoffs


Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Really good job @MapleNAV-TCASFAULT I love your work keep it up, Now it fixed the weird banking I had in my landings.

**Pull request merged**
