### PR TITLE
fix(efb): UI fixes, dev server

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

* Use a common navbar component
  * Fixes some navbars not having hover styling
  * Removes unnecessary code execution 
* Load font correctly
* Fix dashboard heading size
* Fix letter spacing
* Add rollup-based development server with live-reloading to run EFB in browser

Discord username (if different from GitHub): someperson#4953

## Testing instructions

* Make sure UI is functional
* Make sure navbar links are FBW blue on hover

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by ZigTag — APPROVED** [review]
LGTM

**Comment by boierito** [comment]
image
image

Everything works except scrolling the Loadsheet menu. Also, after several attempts, the map recognized my location within the simulator. On the other hand, something negative ... if one enters any of the links on the map, they break the tablet leaving it unusable, even so the same does not happen with the plane. This stops happening if one restarts the flight, completely rendering the entire plane inoperable. (picture 2)

**Comment by Benjozork** [comment]
@boierito this PR does not address any of the issues you mention. please report issues in a proper issue ticket

**Comment by boierito** [comment]
> @boierito this PR does not address any of the issues you mention. please report issues in a proper issue ticket



> @boierito this PR does not address any of the issues you mention. please report issues in a proper issue ticket

The only thing I did was show you that it worked in what you worked, also I added things that would be good to be fixed, since this is a PR of EFB fixes. But hey, I'll see where I'll leave my opinion. Good work and regards!

**Comment by Benjozork** [comment]
I'm aware, and thanks for your testing. But we ask to keep conversation and issue reporting in the right places, as it gets confusing when people report issues in PRs that are not related.

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 03/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3300 
Tier of testing: 1
Changes to observe: EFB UI, letter spacing, blue on hover

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned on rwy at EGKK
2. Took off
3. Looked at the EFB and tested hover

Media:
https://user-images.githubusercontent.com/64845965/106778207-00143400-6646-11eb-9ff4-774f8f7b7cfd.mp4

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: The text becomes blue on every menu when you hover it, letter spacing is good, UI is functional (Video attached is one of my 2 tests)

**Pull request merged**
