### PR TITLE
Cockpit decals enhanced.

### PR DESCRIPTION
**Pull request by FoxinTale**
Changed the resolution of cockpit decals from 1k to 2k.

## Summary of Changes

Remade the cockpit decals text in 4k, downscaled to 2k as requested.

## Screenshots (if necessary)

Before, Daytime pedestal: https://photos.app.goo.gl/rSKQwXQ3cavyEfNd8
After, Daytime pedestal: https://photos.app.goo.gl/C9NEHf14PV5frSyV9

Before, Daytime overhead: https://photos.app.goo.gl/4Fk4SGxgELjBMFpm9
After, Daytime overhead: https://photos.app.goo.gl/2UsMm1cktoAtLLNa6

Before, Nighttime pedestal: https://photos.app.goo.gl/dU1u8Ymf2L1HBGAT9
After, Nighttime pedestal: https://photos.app.goo.gl/V3Rxm2E5H2y5fzsh8

Before, Nighttime overhead: https://photos.app.goo.gl/9u1TtZkon5Cpg5WK9
Afterwards, nighttime overhead: https://photos.app.goo.gl/vKGdacTasKXMXUQr6

## References

No references, visual enhancement.

## Additional context

Discord username (if different from GitHub):
Aubrey Jane #7563

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Pleasure0102** [comment]
@QA please check decal accuracy. Position. Spelling errors. Color of emmisive. Font will most likely change once engineer sends us closeups of letters. If it is merged before it can easily be adjusted later too.

**Comment by armankir** [comment]
Name: Arman#8145
Date of testing: Current date 24/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1512 

Testing technique: Load and examine in different settings (eg. day and night)

Steps you've made to test the Pull Request:

Spawn C&D
Start aircraft
Take notes on any performance hits
Check night time and other settings

Overall Rating: Inconclusive

Conclusions of the testing: See I can notice a difference with the visuals. Did not notice any errors on my examination, what I did notice (possibly unrelated) was a **5-7 FPS drop** when looking down at my pedestal. I cannot confirm if this has anything to do with this pull request, but it might.

Additional Note: _We could use another few testers on this, especially someone to verify a noticeable drop in frames._

**Comment by hotshotp** [comment]
Name: Boris#9134
Date of testing: 10/25/20
Sim version: 1.9.5.0
Pr: #1512 

Testing technique: Load in and look around every part of the cockpit at day and night time. No FPS observed, specs 1080ti and i7-8700k. All of the text and textures look a lot more crisp and higher resolution and I love it, adds more eye candy and is way more pleasurable to look at!

Overall rating: Perfect, love it! Thank you for your work!

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 26/10/2020
Version of the sim: 1950
PR Tested: #1512
Object of test: Testing performance / error checking

Testing technique: Try-out
Steps you've made to test the Pull Request:

1. Loaded the master noted my FPS  
2. Loaded the PR noted my FPS
3. Checked for any errors 

Flight notes: N/A

Overall Rating: Good
Conclusions of the testing: Checked mostly the performance side of this PR and I haven't noted any drop in performance. The rest also LGTM. 
Congratulations on you first PR, great work! Thanks!

**Comment by MultiMediaWIll** [comment]
Hey I am wondering if the white notch line is supposed to be removed these new decals? See old version here: [https://imgur.com/a/ykZNGfS](url)

**Comment by Watsi01** [comment]
> 
> 
> Hey I am wondering if the white notch line is supposed to be removed these new decals? See old version here: https://imgur.com/a/ykZNGfS

Yepp, wondered myself. It's more difficult to check the lever position.

**Comment by Lessar277** [comment]
Is there anything I can do to to fix my decals looking blurry when zoomed out? 
https://cdn.discordapp.com/attachments/748731242912022649/770781661393584158/unknown.png

**Comment by MultiMediaWIll** [comment]
> Is there anything I can do to to fix my decals looking blurry when zoomed out?
> https://cdn.discordapp.com/attachments/748731242912022649/770781661393584158/unknown.png

This is an issue playing in 1080p. See here for a fix: https://github.com/flybywiresim/a32nx/issues/1560

**Pull request merged**
