### PR TITLE
feat: engine startup enhancements and others

### LINKED ISSUE #5157: (new) shime fades out to quick
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-19T04:23:24+00:00",
  "ref": "master",
  "sha": "ff9f83e498bfbfd90edd3335f99daf1575fcd5fd",
  "actor": "wpine215",
  "event_name": "manual"
}
```

### Describe the bug

after the new sound-update i recognize, that the Shime fades out to quick compared to the previous version. To my mind the previous version was the more realistic one. I work on an A319/A320 and I hear it every day a couple of times. It would be nice to have the old one back to have more realism. 

### Expected behavior

old shime was the more realistic one

### Steps to reproduce

1. compare old to new

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by hotshotp**
Fixes #5157 

## Summary of Changes

Changes in this PR: 

- Made the seatbelt sign chime/initial 4 chimes fade out longer and more realistic than before
- Made TSUS TA/RA sounds louder
- Changed the high power exterior whine sound at above 60%-TOGA
- Changed engine startup completely on both interior and exterior, it now matches the reference very well
- Changed fuel pumps on outside and inside
- Added the sounds for wipers

## References

https://www.youtube.com/watch?v=bebx6yjLt8Q

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Start up aircraft, listen to new chimes. Turn on wipers on both sides at different speeds. I AM NOT ABLE TO SYNC THE WIPERS SOUNDS WITH ANIMATIONS PROPERLY - I cannot find a way. So I did not think it was that big of a deal if it was a bit desynced.  Turn on fuel pumps and listen over wings inside and outside. Startup one engine on inside, and one on outside. Note - on interior, the startup is a lot louder behind the wing/engine than in front which is true to life. If you are at the back cabin at the very end of the startup and you hear repeated clacking, that is the APU check valve and not random noise. On takeoff, listen to new whine at high power OUTSIDE the plane.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by ImenesFBW — APPROVED** [review]
LGTM! ♥

**Comment by Samueleonard** [comment]
Quality Assurance Tester Report

Discord: 1samueleonard1
Object of testing: (#5239)
Tier of Testing: (1)
Date: (29/06/2021)

Testing Process:
loaded in + powered up 
**TESTING**
seatbelts - far better, great now
fuel pumps - sound fine
WIPERS POGGERS - finally but issue below
startup - amazing.
spoolup - i think its correct, but when spooling , it sounds like the sound jumps(?) about 60% n1, sounds like there is a lot of airflow after 60%, but then none below

Negatives: wipers seem very very loud, ik they are loud, but perhaps too loud?
Testing Results: (Passed)

Conclusions: just when i thought you couldnt make them any better, you do it again :) nothing game breaking, just the issues above, but not stopping the merge imo
Media: n/a

**Comment by hotshotp** [comment]
> Quality Assurance Tester Report
> 
> Discord: 1samueleonard1
> Object of testing: (#5239)
> Tier of Testing: (1)
> Date: (29/06/2021)
> 
> Testing Process:
> loaded in + powered up 
> **TESTING**
> seatbelts - far better, great now
> fuel pumps - sound fine
> WIPERS POGGERS - finally but issue below
> startup - amazing.
> spoolup - i think its correct, but when spooling , it sounds like the sound jumps(?) about 60% n1, sounds like there is a lot of airflow after 60%, but then none below
> 
> Negatives: wipers seem very very loud, ik they are loud, but perhaps too loud?
> Testing Results: (Passed)
> 
> Conclusions: just when i thought you couldnt make them any better, you do it again :) nothing game breaking, just the issues above, but not stopping the merge imo
> Media: n/a

Thanks for the test! About the transition at 60%, it was more or less the same before, I tried to match how it was. I think it's fine for now, if more people disapprove of it I'll change it up. As for the wiper volume I confirmed with komp who is the engineer who originally recorded them for me and he said they were perfect, they are indeed very loud irl.

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5239
Tier of Testing: 1
Date: 29/06/2021

Testing Process:

1. Spawned C&D
2. While on ground, tested: wiper speeds low and high, each fuel pump, chimes, engine startup from interior & exterior.
3. While in air, tested: whine

Negatives: N/A
Testing Results: Passed

Conclusions: Sounds have been improved!

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5239
Tier of Testing: 1
Date: 30.6.2021

Testing Process: 

Start up aircraft, listen to new chimes. ==> OK

Turn on wipers on both sides at different speeds. ==> very nice :) OK
Turn on fuel pumps and listen over wings inside and outside. ==> left/right OK / center not audible on neos

Startup one engine on inside and one on outside. 
On interior, the startup is a lot louder behind the wing/engine than in front which is true to life. ==> confirmed

If you are at the back cabin at the very end of the startup and you hear repeated clacking, that is the APU check valve and not random noise. ==> couldn't hear this. 

On takeoff, listen to new whine at high power OUTSIDE the plane. ==> OK

Negatives: 
Pumps appear a bit loud compared to the engine itself - but I have no real live experience apart from being a frequent flyer before covid - never noticed the pumps that loud inside. Especially inside on wings level. 

Testing Results: Passed - all sounds are fine which is of course very subjective :) - awesome sound experience. 

Conclusions:  LGTM

**Comment by hotshotp** [comment]
> Quality Assurance Tester Report
> 
> Discord: Cdr_Maverick#6475
> Object of testing: #5239
> Tier of Testing: 1
> Date: 30.6.2021
> 
> Testing Process:
> 
> Start up aircraft, listen to new chimes. ==> OK
> 
> Turn on wipers on both sides at different speeds. ==> very nice :) OK
> Turn on fuel pumps and listen over wings inside and outside. ==> left/right OK / center not audible on neos
> 
> Startup one engine on inside and one on outside.
> On interior, the startup is a lot louder behind the wing/engine than in front which is true to life. ==> confirmed
> 
> If you are at the back cabin at the very end of the startup and you hear repeated clacking, that is the APU check valve and not random noise. ==> couldn't hear this.
> 
> On takeoff, listen to new whine at high power OUTSIDE the plane. ==> OK
> 
> Negatives:
> Pumps appear a bit loud compared to the engine itself - but I have no real live experience apart from being a frequent flyer before covid - never noticed the pumps that loud inside. Especially inside on wings level.
> 
> Testing Results: Passed - all sounds are fine which is of course very subjective :) - awesome sound experience.
> 
> Conclusions: LGTM

Thank you for testing! The clacking is hard to notice so if you didn't hear it that is fine. As for pumps i confirmed with engineers that it is correct volume wise.

**Comment by BritishAvgeek** [comment]
Quality Assurance Tester Report

Object of testing: #5239 
Tier of Testing: 1
Date: 01/07/2021

Testing Process: 
1. Spawned Cold and Dark on stand
2. Began to go through all sounds to see how the wider experience feels in addition to this PR updating some sounds
3. Specifically listened out for engine startup improvements, one inside, and one outside for startup
4. Restarted and listed for startup in cabin and from another exterior angle
5. Seatbelts - lovely jubbley
6. Wipers, loud like a few mentioned before but again subjective and sounds fantastic
7. Pumps - lovely jubbley!

Negatives: N/A
Testing Results: Passed

Conclusions: Fabulous!

**Comment by sidnov** [comment]
QA Report

Object of testing: #5239 
Tier of Testing: 1
Date: 01/07/2021

Testing Process:

Elements Tested
- [ ] Seatbelt/Startup chimes
- [ ] Wipers (Asynced, different speeds, one off+one on)
- [ ] Fuel Pumps (different wingviews, drone cam, exterior, underbody)
- [ ] Engine Startup and sound intensity depending on position (Cockpit, wingviews, front/rear seats, external)
- [ ] APU Clanking
- [ ] Takeoff Whine- N1 60-TOGA on exterior view

Negatives: None
Testing Results: No artifacts, glitches. Smooth transitions and volume balance. Sounds great as always!

Conclusions: LGTM 🚀

**Comment by FlyingCarpet7** [comment]
View 14 in front engine is my favourite (most real and balanced) when it comes to aircond, fuelpumps and startup. 
View 13 in front of wing root is my favourite for spoolup and higher power.
I have about 70 % volume on my speakers and reduce the interior engine slider in the FlyPad down by -30. This gets a better real life feel of the volume for me.
I know komp recorded the vipers so the sound is accurate, but it is to loud still.
I would  love in the future to have a more unison sound with only small variation between front and back of cabin. I know you can change and improve things for ever. It’s a never ending tweaking progress as long as You still want to put all the effort into this. Don’t burn yourself out. It should be enjoyable. No obligations at all.
Overall it’s a very good sound right now. Better the all other out there!

**Pull request merged**
