### PR TITLE
feat(efb): FlyPadOS v2 👀

### PR DESCRIPTION
**Pull request by myselfaaryan**
## Summary of Changes

FlyPadOS v2. Full Layout & UI Rewrite.

- [x] Add New Layout.
- [ ] Adjust All Pages.

## Screenshots (if necessary)

image

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Snapmatics** [comment]
Awesome work and it's nice to see the progress of the EFB. 🥇

**Comment by sidnov** [comment]
Woooohoo, good one @myselfaaryan ! 🎉

**Comment by Benjozork** [comment]
@pepperoni505 this will allow you to add the CIDS settings

**Comment by pepperoni505** [comment]
> @pepperoni505 this will allow you to add the CIDS settings

Should I wait until this is merged or push to this? (assuming aaryan is ok with that)

**Comment by viniciusfont** [comment]
May impact a bit https://github.com/flybywiresim/a32nx/pull/3744 and https://github.com/flybywiresim/a32nx/pull/3474.
Are you using components from? https://github.com/flybywiresim/react-components

**Comment by myselfaaryan** [comment]
> May impact a bit #3744 and #3474.
> Are you using components from? https://github.com/flybywiresim/react-components

My PR doesn't change the page content but the layout only. 😀 So probably be merged after those.

**Comment by Inexorable95** [comment]
> > May impact a bit #3744 and #3474.
> > Are you using components from? https://github.com/flybywiresim/react-components
> 
> My PR doesn't change the page content but the layout only. 😀 So probably be merged after those.

This PR changes the available space for the page content (we'll have more vertical space and a bit less horizontal space)
So it will most likely impact PRs in progress
Just let me know before you merge, I'll fix the fuel page if it needs any fixing (I'm Inexorable on discord)
Thanks!

**Pull request closed without merging**
