### PR TITLE
optically working hold page, missing wp insert + routing

### PR DESCRIPTION
**Pull request by sepiroth887**
Starts implementing #673 

**Summary of Changes**

Added Hold page and some functionality to set and validate input values. 
Missing waypoint routing logic, so purely cosmetic so far.
**Screenshots (if necessary)**

No before as the page is new. 
image

**References**

[A320DP Docs](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.17.html)
**Additional context**

[Hold Page Demo YT](https://youtu.be/D2iNDQohwDk?t=46)

Discord username (if different from GitHub): s3p1r0th#8483

### CODE REVIEW

**Review by AdenFlorian — APPROVED** [review]
code looks fine, isolated change, ready to test!

**Comment by Noxleee** [comment]
Name: Noxlee #7727
Date of testing: Current date 01/10/2020
Version of the sim: 1.9.3.0
PR Tested: #995 

Testing technique: Testflight
Steps you've made to test the Pull Request:
1. Loadup airplane at gate 8 RJFU
2. All screens are staying dark
3. Reinstall mod
4. Same Issue
5. Tried lastest master (for reference)
6. Master is working

Overall Rating: not working
Conclusions of the testing: At least on my machine it's not working due to the screen issue. I think the mod has to be ported to 1.9.3.0, maybe somebody else could test it too.

**Comment by Noxleee** [comment]
Name: Noxlee #7727
Date of testing: Current date 01/10/2020
Version of the sim: 1.9.3.0
PR Tested: #995 

Testing technique: Reproduce YT Video and check Honeywell FMS System guide for reference
Steps you've made to test the Pull Request:
1. load up at RJFU Gate 8
2. Inserted F-Plan
3. Testing functions as in the YT Video and check FCOM

Overall Rating: good, but could be improved
Conclusions of the testing: Everything is working as in the YT Video. But due to ref material, Last Exit, utc and fuel are at the wrong position. The insert logic for time/distance should be different. The Pilot can insert a time in minutes XX, a distance with /YY or both XX/YY.Revert to computed/database is also missing.

Reference Honeywell FMS System guide. Avail in MCDU Chat, its pinned-> Pages 360 and following. 
Since a don't know if it's allowed to share, I will not provide the material here.

**Comment by veikkos** [comment]
> 
> 
> It would be better if you delayed it until you finish the waypoint logic that's my suggestion

No, it's better to get logical pieces integrated to avoid huge Pull Requests. It's better to integrate often when there is something which brings project forward and someone else can potentially continue if original author loses interest or otherwise is no longer able to continue.

**Comment by AdenFlorian** [comment]
this can be improved in future PRs, thanks!

**Comment by sepiroth887** [comment]
Uhm. I wasn't really expecting a merge here sorry. Should probably read the contribution guide again. Just added to keep it tracking master easier and motivate me. 

I agree with all the above. Made good progress on the gui parts and some of the logic to get holds started and exited without breaking things, but the waypointing is proving tricky to say the least and will take some time. 

Esp testing is extremely  tedious as I have to keep flying and modding sometimes it needs a reload and then another takeoff etc. Anyone got suggestions to make this dev cycle quicker im all ears. 

Thanks for the feedback, really appreciated 👍

**Comment by sepiroth887** [comment]
@Noxleee very much appreciated. I fought the layout and lost the first round. 

Database is something I explicitly ommited for now but I should probably add a white text for it to indicate it should be there but inop. 

Im curious about the time and distance input as when I thought about it it made no sense to me :D but I was lacking ref material, so definitely  going to checkout the mcdu docs in discord

**Pull request merged**
