### PR TITLE
[PFD] switch to core speed calculations

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Made F and S speeds using speeds delivered by core speed.
- Moved GD zeroing to PFD.

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by beheh** [comment]
This needs to be updated for #2226 (`A32NX_SS` => `A32NX_SPEEDS_S`, `A32NX_FS` => `A32NX_SPEEDS_F`)

**Comment by Benjozork** [comment]
QA, just check speeds still work fine.

**Review by kberg93 — COMMENTED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 12/07/2020
Version of the sim: 1.11.6.0
PR Tested: #2231 
Object of test: Checking speeds on a small flight.

Testing technique: C&D from ENVA to ENML full autopilot but manual final approach.

Steps you've made to test the Pull Request: 
1. C&D on ENVA punched in flightplan with both DEP/ARR data since it was a very short flight.
2. Take off from ENVA RWY27, checked PFD and saw the S logo on almost 190 (thought it shouldve been on 160 according to the take off reference. see screenshots)
3. Started approach to ENML RWY25.
4. Seeing the dot on the PFD speed i set flaps 1 when hitting that dot on 207kn. Then the "S" appeard on 188kn.
5. When hitting 188kn i set flaps 2, and the "F" appeard on 145kn.

Flight notes (If required): Not 100% sure if this is how it shouldve been tested but afaik everything seemed normal apart from the "S" on take off (maybe it was because of man toga?).

Issues (If Any): Not as i know.

Overall Rating: Good and issue free.

Conclusions of the testing: Look at the screenshots and let me know if im wrong or something, im learnig at the same time to. :) 

Screenshots:
Take off data:
R2QyojLaAm
The "S" on take off:
FlightSimulator_QCEwqPFsdG
Approach data:
FlightSimulator_w7eGoeVrSZ
The "dot thingy" on approach:
q8M0fR9aIV
The "S" on approach:
n3PpEA8zqm
The "F" on approach:
UQwMmJOpmK

**Comment by beheh** [comment]
The MCDU is using a different data source for now. It will be using much more accurate numbers as part of #1824 (this PR sets that up).

**Comment by kberg93** [comment]
> The MCDU is using a different data source for now. It will be using much more accurate numbers as part of #1824 (this PR sets that up).

So then everything on this PR looks ok then? :)

**Comment by MisterChocker** [comment]
> So then everything on this PR looks ok then? :)

When you saw GD, F and S speeds, then yes ;)

**Review by kberg93 — APPROVED** [review]
Did see the GD, S and F so all good 😄

**Pull request merged**
