### PR TITLE
feat: Standby Instrument - Emergency Power Stays ON

### LINKED ISSUE #1233: [META] standby instrument (ISIS)
**Is your feature request related to a problem? Please describe.**

Someperson#4953 keeps dming me ISIS material on discord, please help. 

**Describe the feature you'd like to see implemented**

# ELECTRIC

## Description 

logic

Currently ISIS Indicator will switch off even in flight if the batteries and all other main electric systems are switched off. This is incorrect, as the ISIS indicator draws power from both the dc ess bus which supplies critical systems as well as a hot bus (which constantly supplies power until the batteries are entirely drained). The power supply from the hot bus is only active if the calibrated air speed is above 50 knots. 

## Checks 

- [ ] ISIS ELEC
  - [ ] Correct implementation of Standby Instrument Power System (Partially Implemented)
  - [x] Should check if calculated air speed is >50 knots, and keep the instrument ON even if battery is off as long as emergency power is avail.
    - ``(if (cas > 50 knots) AND HOT BUS ON ) OR DC ESS BUS ON``
  - [ ] Display does not immediately power off, delay of 50-200ms where the display will stay on if power is supplied in that interval. (Partially Implemented)

Transparency time for the ISIS indicator is between 50ms - 200 ms. Display is lost during power supply cut off if power is not supplied in this time.
 
# SYSTEMS

## Description

**A. System Performance**

The parameter computation frequency is sufficient to respect the required performances and to avoid important gap between two consecutive displayed values. The elasped time between the acquisition of air data and the display of parameters is less than 200 ms. 

_(1) Standby airspeed indicator function_

The ISIS indicator can operate from 0 to 600 knots without deterioration.

_(2) Standby altimeter function_

The ISIS indicator can operate from -2500 to 55,000 ft and at 40,000 ft/min speed variation without deterioration

_(3) Standby horizon function_

The ISIS indicator can operate from -180 deg to +180 deg. in pitch and roll without deterioration.

- Gyrometers (3): the indicator can follow a 100 deg./s pitch or roll variation, a 10,000 deg./square second angular acceleration. The associated monitoring is triggered when angular speeds become higher than 100 deg./s

- Accelerometers (2): The aassociated monitoring is triggered when the constant acceleration in the x and/or y axis becomes greater than 2.5g. If this monitoring is triggered, the "WAIT ATT" message is displayed.

If the condition becomes normal again and if the attitude monitoring is triggered when the constant acceleration in x and/or y axis becomes greater than 2.5g. If this monitoring is triggered, the "WAIT ATT" message is displayed.

If the condition becomes normal again and if the attitude performance remains adequete for 10 seconds, the "WAIT ATT" message disappears and is replaced by the horizon display.

Otherwise, after 10 seconds or if the attitude performance is affected, the attitude function is considered as failed and the "ATT:RST" message is displayed in place of the "WATT ATT" message (Ref. Fig. 023)

Pressing the RST pushbutton switch more than 2 seconds in steady flight quickly resets the attitude information.

## Checks 

- [ ] ATT RESET - Correct current incorrect behaviour
   - [ ] 2 second push and hold instead of push
- [ ] Will start to lose calibration if plane goes well outside of stated envelope.
- [ ] WAIT ATT
   - [ ] Correctly formatted message box
   - [ ] Pauses display refresh when triggered
   - [ ] If attitude performance goes out of spec for 10 seconds, failure occurs (ATT:RESET)
- [ ] ATT:RESET
    - [ ] Correctly formatted message box
    - [ ] Blacks out display?
    - [ ] Requires use of ATT RESET push button (press and hold 2 seconds)

**References**

https://www.pprune.org/showthread.php?p=6817862
Someperson#4953 on discord

**Additional context**

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by 2hwk**
Partially Resolves #1233 

## Summary of Changes

~~- More realistic cursor display and horizon colors - See screenshots~~
- Standby Instrument now powered by HOT BUS, correct as per documentation. (See #1233) 
- Standby Instrument no longer switches OFF if emergency power should be maintained.
- Standby Instrument no longer enters self-test if aircraft is spawned in mid-flight.
- Housekeeping of code - Now uses basic state machine implementation to manage status.
- Implemented FrameCounter and StateMachine functions in A32NX_Utils

## Screenshots (if necessary)

[Power On Above 50 Knots CAS](https://i.imgur.com/faZLKiE.mp4)

## References

See #1233 

## Additional context

More accurate, but not perfect yet, am waiting on the ELEC overhaul to implement proper HOT BUSS/DC ESS BUS logic. For now, just draws power from HOT BUS 1, without caring for DC ESS BUS. 

Note: Do not close #1233 when merging.

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by jakluk** [comment]
You didn't do much with the visuals. I suggest that you leave them out of this PR, hopefully I might be able to submit my PR today or tomorrow after some more changes related to the new font.

My version:
image

**Comment by 2hwk** [comment]
Ok, I am removing the cosmetic changes in A320_Neo_SAI_AltimeterIndicator

**Comment by camilo625** [comment]
Name: Camilo625 #5575
Date of testing: Current date 13/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1252 

Testing technique: Spawn and test ESIS
Steps you've made to test the Pull Request:
1. Spawn C&D
2. Test ESIS

Overall Rating: Good
Conclusions of the testing: Works as described

**Comment by camilo625** [comment]
Name: Camilo625 #5575
Date of testing: Current date 13/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1261

Testing technique: Spawn and test ESIS
Steps you've made to test the Pull Request:
1. Spawn C&D
2. Test ESIS

Overall Rating: Good
Conclusions of the testing: Works as described

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 14/10/2020
Version of the sim: 1950
PR Tested: #1261

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane in different start positions (C&D, on RWY, in the air, on app)
2. Tested the back-up instruments with emergency power



Overall Rating: Good
Conclusions of the testing: Working as described! Thank you for your work!

**Pull request merged**
