### PR TITLE
fix(model): landing light animation

### LINKED ISSUE #1022: [BUG] One LDG light switch extends both halfway
**Mod Version**

master

**Describe the bug**

If you use one LDG light switch and set it to on while leaving the other one in off both extend halfway.

**To Reproduce**

1.Power up the Acft
2.Use only one LDG light switch

**Expected behavior**

Only one of them should extend fully.

**Actual behavior**

Both extend halfway.

**References**

Screenshot 2020-10-01 205239

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Probably, not checked.

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #1022
Partial #3387

## Summary of Changes

Landing lights operate independently and fully retract when the other is not retracted (half-retracted before).

## Screenshots (if necessary)

Left retracted, right on.
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check that landing lights extend and retract independently.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by bouveng — APPROVED** [review]
LGTM!

**Comment by ShadowFrost3** [comment]
Quality Assurance Trainee Report


Object of testing: #5913
Tier of Testing:1
Date: 26/09/2021

Testing Process: Air spawn
Play with landing lights, make sure they can be retracted independently, turned on and off independently - checked
Negatives: 
Testing Results: Passed
Conclusions:

**Comment by xZreai** [comment]
Quality Assurance Trainee Report

Discord: Cleon#5802
Object of testing: #5913 
Tier of Testing: (1)
Date: (26/09/2021)

Testing Process: 
Started C/D at Airport Gate
Turned aircraft on - batteries and external power
Tested each landing light seperately
Aircraft landing light animations and lighting work as intended


Negatives: Nil


Testing Results: Pass


Conclusions:
Works as intended

Media:
Retracted
image
Landing Lights Off
image
Landing Lights On
image

**Comment by John-UK** [comment]
Quality Assurance Trainee Report

Discord: john P Maguire#9027
Object of testing: #5913
Tier of Testing: (1)
Date: (26/09/2021)

Testing Process:
Started C/D at Gate
Normal start procedures up to runway hold. 

Holding short of RW tested landing light switches. Used both in sim switches separately in all possible combinations and external hardware to operate landing lights. Animations were applied to each side correctly. Lights operated individually and correctly IAW the switch positions. 

Testing Results: Pass

Conclusions:
Works as intended in PR, Not sure if a PR is in separately for this. The lights do extend and retract with no power applied, batteries off.

**Comment by tracernz** [comment]
> The lights do extend and retract with no power applied, batteries off.

Yes, that will still need fixed. I didn't want to get side-tracked on this for too long though so I didn't go looking for the refs I'd need to do that.

**Pull request merged**
