### PR TITLE
fix(nd): use correct font for waypoints

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Waypoints on the ND now use the correct font.

## Screenshots (if necessary)

Before:
image
After:
image

## Testing instructions

Make sure waypoints on the ND use the correct font.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Category: 
Name: marcman86
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested:  #3498
Tier of testing: 1
Changes to observe: Change of WP font in ND 
Testing technique: Tryout

Steps you've made to test the Pull Request:

1.) Spawn C&D EDDP-EDDF
2.) Turn on Bat. and ext. Pwr.
3.) Go to Plan (Image 1+3)
4.) Align IRS
3.) Go to Arc, turn on Airports (Image 2+4)

Media:

Before:


Image1


Image2

After:


Image3


Image4

Issues (If Any): None

Overall Rating: Good

Conclusions of the testing: Looks good! New font on all waypoints and Decel, also for Airports.

Hope this helps :-)

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 13/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3498 
Tier of testing: 1
Changes to observe: ND waypoints font

Testing technique: Before/After with the current dev version
Steps you've made to test the Pull Request (**did the exact same thing for 2 versions, dev and this PR**):
1. Spawned in C&D at LFRS
2. Powered up the aircraft
3. Imported the following SimBrief route LFRS ANG3N ANG UN741 KEPER UT182 ROMGO ROMG7P LFPG
4. Went into PLAN mode and tried to switch waypoints

Media: [https://youtu.be/oiP_F6dThsw](url)
Before:
Capture d’écran (411)
Capture d’écran (412)
After:
Capture d’écran (413)

Issues (If Any): - Couldn't switch waypoints
                        - SimBrief route wasn't complete with the PR only (exact same route with the dev version, it was working)
Steps to achieve the issue
Just try to switch waypoints in PLAN mode & import the said route

Overall Rating: To be improved
Conclusions of the testing: Other than the issues that I reported, the font works

**Comment by tyler58546** [comment]
> SimBrief route wasn't complete with the PR only

Is anyone else able to reproduce this issue? I think it's very unlikely to be caused by this PR since I only changed the font.

**Comment by marcman86** [comment]
Hi, 
in my test i was able to scroll to the flight plan with the MCDU and the ND was following (see image 3), but i just used a MSFS plan. I can repeat the testing with a Simbrief plan, if necessary.

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested:  #3498
Tier of testing: 1
Changes to observe: Change of WP font in ND 
Testing technique: Tryout

Steps you've made to test the Pull Request:

1.) Spawned C&D at EDDB
2.) Turned on Bat., ext. Pwr. and aligned IRS
3.) Init Simbrief FP (EDDB>...>EDDP)
4.) Go to Plan
3.) Scrolled through FP via MCDU (Image1)

Media:


Image1


Issues (If Any): None

Overall Rating: Good

Conclusions of the testing: Scrolling through FP works.

Hope this helps :-)

**Comment by MisterChocker** [comment]
> > SimBrief route wasn't complete with the PR only
> 
> Is anyone else able to reproduce this issue? I think it's very unlikely to be caused by this PR since I only changed the font.

I also think it's very unlikely to be caused by this pr.

**Review by sl3awy — COMMENTED** [review]
You are boss

**Comment by sl3awy** [comment]
[]()

**Pull request merged**
