### PR TITLE
fix(model): ecam pushbuttons light colour

### PR DESCRIPTION
**Pull request by tracernz**
Another check on #1410

## Summary of Changes

The buttons in the ECAM Control Panel incorrectly used the same green illumination as the FCU buttons. These PR fixes the color and gives them the warm white they should have.

## Screenshots (if necessary)

ECP

## References

image

Video reference: https://www.youtube.com/watch?v=rTlaA7JpV5Y

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Start a new flight
2. Interact with the ECAM buttons, verify the color is accurate. The buttons, when illuminated, should light up in a warm white.
3. Verify the similar button in the FCU still have the original color
4. Ensure the ANN LT TEST works as expected

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by beheh** [comment]
As far as I can tell, in reality the buttons have a warmish glow, maybe slightly orange, rather than being pure white. I've added a photo and video reference to the PR. Maybe we could get some pilots chiming in after we have an updated in-sim reference.

**Review by beheh — APPROVED** [review]
The color change looks good, and I tested it in-sim. After speaking to various pilots and engineers on #pilot-feedback we opted to make the color slightly orange, instead of pure white. I've updated the PR with the references and an in-sim screenshot.

Looking further, these buttons will in future also need an update to the layout (exact text position and light position), but that's out of scope for this PR.

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5638 
Tier of Testing: 1
Date: 14/08/2021

**Testing Process:**
1. Inspected ECAM buttons in daylight and nighttime

**Negatives:** 
- I dont know wether this was a "problem" before, but the CLR buttons do not light up, when there is a ECAM message

**Testing Results:** Passed (check above)

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5638
Tier of Testing: 1
Date: 14/08/2021

Testing Process:
- Loaded in on runway at EGSS.
- Tested ECAM buttons and checked colours. - Passed
- Checked FCU buttons to ensure they remained original colour (Green). - Passed
- Tested ANN LT TEST - checked over all lights to check they looked the same as before. - Passed

Negatives: N/A
Testing Results: Pass

Conclusions: Works exactly as intended, a nice improvement and looks very clean! Great stuff!

Media:
With ANN LT TEST ON
image
image

**Pull request merged**
