### PR TITLE
fix: compatibility with 1.21.18 hotfix

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #[issue_no]

## Summary of Changes

Looks like system gauges need at least 1 pixel width and height to be loaded...

## References

CJ4(https://github.com/Working-Title-MSFS-Mods/fspackages/blob/main/src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/panel/panel.cfg) and CRJ panel.cfg

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Verify the aircraft loads into the game and all systems are running (screens on, throttle and engines responding)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
Will test this on GA release

**Comment by stevex77** [comment]
Just FYI, if it helps: Quickly checked by applying this simple hotfix manually, directly withing my community folder and can confirm that I successfully spawned C&D at the gate of KMCO. Turned on external power and all seems to work at the first look, all systems are responding.

**Comment by motishow** [comment]
where is the fix to download? thanks

**Review by Benjozork — APPROVED** [review]

**Comment by Benjozork** [comment]
Reported as working in the release version by Mav.

**Pull request merged**
