### PR TITLE
fix: v2 table conf3

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Fixed V2 computation for GW 65t+

Conf 3 Table
| GW | 60 | 65 | 70 | 75 | 80 |
| ----- | ----- | ----- |  ----- | ----- | ----- |
| V2 | 125 | 128 | 132 | 137 | 141 |

## References

https://github.com/flybywiresim/a32nx/issues/1777#issuecomment-723537305

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Spawn on gate or runway with 70, 75 and 80t GW, select config 3 as take off config in the mcdu, request V2 speed.
Cross check with table provided

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 08/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3414 
Tier of testing: 1
Changes to observe: V2 computed speed with GW +65t

Testing technique: Try-out
Steps you've made to test the Pull Request:
1. Spawned in C&D and powered up the aircraft
2. Entered 3 in the flaps section in the PERF page
3. modified the weight of the plane to match 65, 70, 75 and 80
4. Each time requested V2

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: All speeds were matching the tables with the weights, LGTM 👍

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/08/2021
Version of the sim: 1.12.13.0
PR Tested: #3414 
Tier of testing: 1
Changes to observe: Spawn on gate or runway with 70, 75 and 80t GW, select config 3 as take off config in the mcdu, request V2 speed.
Cross check with table provided.

Testing technique: Adjusting weight and putting in take off data.

Steps you've made to test the Pull Request: 
1. Spawned and did put in take off data to see that V2 got changed according to the new calcs. 
2. Changed weight to max and it worked like described.

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None.
Overall Rating: Good.
Conclusions of the testing: LGTM.

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 8.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3414 
Tier of testing: 1
### Changes to observe: V2 table config3

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on runway
2. Set weight 60 tons, checked V2
3. Repeated with weights 65,70,75,80 tons and observed and verified V2 values with table

Issues (If Any): None

### Overall Rating: Good
### Conclusions of the testing: Values checked and verified with the table. Good to go!

**Review by Benjozork — APPROVED** [review]
LGTM

**Pull request merged**
