### PR TITLE
feat(sd/ewd): improve visual accuracy for static components

### LINKED ISSUE #8036: Colour accuracy fix accros all ECAMs
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-05-17T19:05:00+00:00",
    "ref": "refs/heads/experimental",
    "sha": "e2da961b511bf8d5c29524ff135cfbe41aa2d83f",
    "actor": "beheh",
    "event_name": "manual",
    "pretty_release_name": "experimental:e2da961b",
    "version": "v0.10.0-exp.e2da961"
}
```

### Describe the bug

It was found that there has been a possible regression about some visuals on ECAMs. 
Some elements are in white instead of grey, they are listed below :
> EWD :
- Lines between N2 Values
- Lines between FF
- Lines dividing the EWD sections
> ND :
- Squares at the bottom (GPS PRIMARY / TA ONLY / ...) 
> Bottom SD pages :
- Lines dividing the temperature, time and GW sections
> BLEED :
- Square around values for air to air exchanger
> ELEC :
- Squares around any TR/GEN/APU/EXT/BAT and ESS TR
> FUEL :
- Fuel tank symbology
- Sqare around FOB (not the text inside)
- Lines between F. USED
> APU :
- Square around bleed pressure from APU
> DOOR :
Well it is hard to find either the SLIDE text should be white, and the aircraft symbology is in grey as it should either aircraft symbology is in white and should be grey and SLIDE text doesn't pop to the eyes enoughµ

All of those should be in grey instead of white (like the wing on the EWD for flaps/slats).

### Expected behavior

See above description and all red circles in the attached files

### Steps to reproduce

Start the aircraft
Look at ECAMs

### References (optional)

For Dev Team, feel free to ask in appropriate chanels.
Capture d'écran 2023-05-20 142840
Capture d'écran 2023-05-20 142946
Capture d'écran 2023-05-20 143122
Capture d'écran 2023-05-20 143229
Capture d'écran 2023-05-20 143338
Capture d'écran 2023-05-20 143503
Capture d'écran 2023-05-20 143558
Capture d'écran 2023-05-20 143746

### Additional info (optional)

_No response_

### Discord Username (optional)

AXWB [Z+2]#4622

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes #8036 

## Summary of Changes

This PR primarily aims to improve the accuracy of static components (lines, boxes, aircraft shapes etc.) on the SD, EWD and ND. See the screenshots and the mentioned issue for a list of changes. Also note that there may be other inaccuracies on some of the affected SD pages,
but only the issue with grey lines is addressed here.

## Screenshots (if necessary)

| Before  | After  |
|---|---|
| grafik | grafik  |
| grafik | grafik |
| grafik  | grafik  |
| grafik  | grafik  |
| grafik  | grafik  |
| grafik  | grafik  |
| grafik  | grafik  |
| grafik | grafik |
| grafik | grafik |

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by lukecologne** [comment]
Hm, I think the STATUS page vertical seperator should be grey as well, looks like this was missed in #8036

**Comment by tracernz** [comment]
Please also do the TCAS/WXR and FM messages on the ND now.

**Comment by lukecologne** [comment]
Done.

**Comment by AnXWB** [comment]
Review done, comply with reference.
All good for me, thanks for the work !

**Pull request merged**
