### PR TITLE
fix(fmgc): use station declination where required

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Use station declination where required to calculate true course.

## Screenshots (if necessary)

Before:
image

After:
image

## References

ICAO PANS OPS Vol. 2
ARINC 424

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check various SIDs, STARs and approaches to make sure legs are aligned... especially SIDs and approaches.
Check a DME arc or two.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7193
Tier of Testing  : 1
Date             : 13/05/2022

Testing Process: 
Tried KSFO departure in question and a bunch of arcs at LGKR. All OK.

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

**Comment by tracernz** [comment]
I've marked this Do Not Merge for a little while as I'd like to let it sit on exp and make sure no new issues arrise.

**Comment by 2hwk** [comment]
KSFO 28L OFFSHR2
FlightSimulator_1yRdgevgp5

LFPG 09R PTV5K
FlightSimulator_5bIcJg4yMC

RJAA 16R SUNN2
image

**Comment by tracernz** [comment]
The RJAA one is bugged because the missed approach point is not the runway threshold but the flight planning system strings the runway threshold at the end of every approach no matter what. Same reason we can't do vertical profile for non-precision approaches properly.

**Comment by tracernz** [comment]
Zero issues reported in exp. 🥳

**Pull request merged**
