### PR TITLE
fix(mcdu): Remove PAX on INIT A page

### PR DESCRIPTION
**Pull request by Awemeter**
## Summary of Changes

- Remove pax from INT A

## Screenshots (if necessary)

Before:
 
After:
image

## References

Capture

## Additional context

Discord username (if different from GitHub): Awemeter#7919

## Testing instructions

Load in and check for visual bugs on the INT A page

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
This is incorrect.

image

**Review by ZigTag — APPROVED** [review]
LGTM

**Comment by OverKillProductions** [comment]
Category: QA Tester/Trial
Name: Discord User #4687
Date of testing: Current date 02/03/2021
Version of the sim: 1.12.13.0
PR Tested: #3325
Tier of testing: 1
Changes to observe:

fix(mcdu): Remove PAX on INT A page

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
(Testing was done after deleting A32NX from community folder and reinstalling the PR)

1. Cold and Dark state
2. Batteries ADIRS Ground Power
3. INIT Page
4. PAX Count is gone


Flight notes (When done a full flight): N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): 

Overall Rating: Good

Conclusions of the testing: PAX count has been removed from the INIT Page
2021-02-03 20_26_50-Microsoft Flight Simulator - 1 12 13 0

**Comment by MapleNAV-TCASFAULT** [comment]
Change the title, I believe it's supposed to say INIT A and not INT A.

**Pull request merged**
