### PR TITLE
fix: FCU baro knob overlapping text and emissive removed

### LINKED ISSUE #2687: [BUG] Baro knob lit in cold and dark
**Mod Version**

{
  "built": "2020-12-24T07:44:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "donstim <70166617+donstim@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

When starting cold and dark, the cockpit is dark expect the baro knob (see screenshot)

**To Reproduce**

1. Start a flight at night at a gate
2. When in cockpit observe baro knob
3. Baro knob is lit

**Expected behavior**

I would expect the baro knob to be dark.

**Actual behavior**

The knob is lit, even though there is no power on the aircraft.

**References**

LOWW

### PR DESCRIPTION
**Pull request by ImenesFBW**
Fixes #2687

## Summary of Changes
- Removes overlapping text on the FCU Baro knob ( credit to @DarkOfNova for the texture fix)
- Adds additional template to prevent the FCU Baro knob emissive to load since the Baro knob is not backlit. 
## Screenshots (if necessary)

BEFORE:
image

before

AFTER:
knob
after

## References

Baro knob should not be backlit. Confirmed by multiple real-world pilots.

Discord username (if different from GitHub):
DarkOfNova#2688
Imenes#8739

## Testing instructions

Tier 1 test required. Make sure the FCU baro knob does not light up at any point and test the functionality of the knob.
Check the text on the knob to make sure the overlapping text issue is fixed. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by pepperoni505 — APPROVED** [review]
LGTM

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 21.01.2021
Version of the sim: 1.12.13.0
PR Tested: #3130 
Tier of testing: Tier 1 conducted
Changes to observe: FCU Baro Know Emmisive Decal


Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned C&D LSZH A44
2. Checked FCU Baro Knob if off
3. Turned the A/C on
4. Checked Baro Knob again

Media:
Microsoft Flight Simulator Screenshot 2021 01 21 - 21 36 21 96

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Works as described, good to merge

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 1/21/2021
Version of the sim: 1.12.13.0
PR Tested: #3130 
Tier of testing: 1
Changes to observe: Removes overlapping text on the FCU Baro knob ( credit to @DarkOfNova for the texture fix)
Adds additional template to prevent the FCU Baro knob emissive to load since the Baro knob is not backlit.


Testing technique: Tried out
Steps you've made to test the Pull Request:
1.  Spawned C&D at KATL and looked at STD knob for light
2.  Turned on integrated lights and looked at STD knob for light
3.  Spawned on Runway at KATL and looked at STD knob for lights
4.  Turned on integrated lights and looked at STD knob for light

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
image

Issues (If Any): When you spawn on the runway your integrated lower panel light knob will already be halfway on


Overall Rating: Good
Conclusions of the testing: Great pr Imemes and Nova keep up the good work

**Comment by stescouse** [comment]
Category: QA Tester
Name: Discord User stescouse#7271
Date of testing: 21/1/2021
Version of the sim: 1.12.13.0
PR Tested: #3130
Tier of testing: 1
Changes to observe: Test FCU baro knob does not light up and its functuanlity operates normally. 

Testing technique: TryOut
Steps you've made to test the Pull Request:

1. Spawned C&D at LFPG 

button test 3


2. Started electrics to test if light remained out on FCU baro knob.

button test 4

3. Pulled baro knob to STD to test if remained unlit.

button test 5

4. Spawned on runway to test baro knob.

button test 1

5. Pulled baro knob on runway to STD to test if stayed unlit.


Issues (If Any): None.

Overall Rating: Good
Conclusions of the testing: Worked as stated in PR good job.

**Comment by mtjones83** [comment]
Hi - has anyone noticed this change appears to have lost the baro labels?
'in Hg' and 'hPa' are missing from the FCU now.

Thanks,
Mike

**Comment by ImenesFBW** [comment]
> Hi - has anyone noticed this change appears to have lost the baro labels?
> 'in Hg' and 'hPa' are missing from the FCU now.
> 
> Thanks,
> Mike

You are right. We have not noticed! I'll take a look if I can correct this tomorrow.

**Pull request merged**
