### PR TITLE
feat: add ROPS

### PR DESCRIPTION
**Pull request by ExampleWasTaken**
Fixes #[issue_no]

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
Please do this in the FMGC.

**Comment by ExampleWasTaken** [comment]
> Please do this in the FMGC (`src/fmgc/`).

Since there is no folder called `fmgc` I should create that, correct?

**Comment by Benjozork** [comment]
Yes, we in fact only want TS there.

**Comment by Benjozork** [comment]
Is this still being worked on ?

**Comment by Benjozork** [comment]
It seems like the branch is quite full of unrelated commits.

**Comment by ExampleWasTaken** [comment]
> 
> 
> It seems like the branch is quite full of unrelated commits.

yep haven't rebased in a while

**Comment by ExampleWasTaken** [comment]
> Is this still being worked on ?

Yeah totally. I'm currently waiting on tracer to finish his API for facilities.

**Comment by aguther** [comment]
This PR is quite outdated. Please open a new PR is you want to work on it again.

**Pull request closed without merging**
