### PR TITLE
fix: visual error on COND page when hot air pressure valve is off

### LINKED ISSUE #4018: HOT AIR pushbutton ECAM representation
**Mod Version**

  "built": "2021-03-17T21:42:54+00:00",
  "ref": "master",
  "sha": "5882d47b8e8dc4ce3e011dd9c8d32aaec4181ad5",
  "actor": "MisterChocker",
  "event_name": "manual"

**Describe the bug**

According to the FCOM, when the HOT AIR pb is depressed and OFF, the COND page should show the valve as closed in amber. It currently shows the valve as closed in green.

**To Reproduce**

1. Spawn in C&D, runway or in the air.
2. Switch the lower ECAM page to COND
3. Depress the HOT AIR pb in the AIR COND overhead panel and observe what happens on the ECAM display

**Expected behavior**

The COND page should show the valve closed in amber instead of green.

**Actual behavior**

The COND page shows the hot air valve closed in green.

**References**

image
image

**Additional context**

Was this working before/when did the issue start occurring?
To my knowledge this hasn't been changed since the introduction of the COND page to the mod.

Is this a problem in the vanilla unmodded game?
Yes, no other mods installed.

Discord username (if different from GitHub): Commander Ga#1548

### PR DESCRIPTION
**Pull request by RichardPilbery**
Fixes #4018

## Summary of Changes

Minor css modification to hot air valve and air duct. Thanks to @mjuhe for picking this up.

## Screenshots (if necessary)

**Before** See #4018 

**After**

ECAM-COND-valve-closed

## Additional context

Discord username (if different from GitHub): tricky_dicky

## Testing instructions

1. C&D
2. Battery and external power on
3. Push Hot Air button on AIR COND panel

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by marcman86** [comment]
Hi, whats with the reference in the original PR #1917? There the line is green with HOT AIR valve off. This is why i didn't wrote an issue on the React COND page QA test.

**Comment by mjuhe** [comment]
> 
> 
> Hi, whats with the reference in the original PR #1917? There the line is green with HOT AIR valve off. This is why i didn't wrote an issue on the React COND page QA test.

The valve can show closed in green as long as the HOT AIR pushbutton is set to auto. My understanding is that manually setting the pb to off always shuts off the valve and turns the representation of it to amber.

image

I don't think the whole line would go amber though, I think it would be just the valve (as per the image on PR #1917). But I haven't been able to find any references.

**Comment by RichardPilbery** [comment]
I've checked a more contemporary reference and it appears that the line turns amber in this instance (hot air valve push button is depressed).

**Review by davidwalschots — APPROVED** [review]

**Comment by darkfury334** [comment]
Category: QA Trial
Name:DarkFury#4936
Date of testing: Current date 20/03/2021
PR Tested: #4022
Tier of testing: 1
Changes to observe:
modification to hot air valve and air duct.

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1.Spawned C&D at EGCC
2.Turn Battery and external power on
3.Push Hot Air button on / off AIR COND panel
4.Check lower ECAM COND page after each turn on/off


Flight notes (When done a full flight):N/A

Media: 
Microsoft Flight Simulator Screenshot 2021 03 20 - 11 31 37 21

Issues (If Any): N/A
Overall Rating: Good
Conclusions of the testing: All Good.

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 20.3.2021
Version of the sim: 1.14.5.0
PR Tested: #4022
Tier of testing: 1
Changes to observe: COND line amber when HOT AIR valve is off
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power
3.) Switched to COND page and tested with HOT AIR button off (Image1)

Media:


Image1 

Issues: -

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Pull request merged**
