### PR TITLE
feat: toogle switches with mousewheel

### LINKED ISSUE #5298: Make All Toggle Switches Operable With Mouse Wheel
### Aircraft Version

Development

### Description

The three position toggle switches on the overhead are operable with the mouse wheel, but the two position ones are not. Operating them with the mouse wheel is more convenient and less error prone.

Toggle switches that are not operable with the mouse wheel are circled in red:
image

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by patsta32**
Fixes #5298

## Summary of Changes

1. Added new modelBehavior template for switch interaction with mousewheel and left click.
2. Updated 2 Way overhead switches as referenced in #5298 to be controllable with mousewheel up/down and left click.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

[Issue](https://github.com/flybywiresim/a32nx/issues/5298) Buttons with red circles should now work with mousewheel up/down and left click. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
Very pleased to see this one! I am away for the next few days but I will try to have a look when I get some downtime.

**Comment by bouveng** [comment]
It should still use the anim-template, just feed your stuff through it. Br. J

**Review by bouveng — CHANGES_REQUESTED** [review]
Use animation interaction template.

**Comment by patsta32** [comment]
@bouveng Thanks for the review. I totally forgot to wrap the interactions again!

**Review by bouveng — APPROVED** [review]
🤓 ✈️

**Comment by frankkopp** [comment]
Love this PR - we needed that.

But can I be so bold and ask to include all switches in the Cockpit. Went through all of them and these below are not yet covered.
image
image
image
image

And maybe these: 
image
Not 100% sure about these as they have a protection irl so you need to lift the switch. Maybe a simple mouse wheel would be to easy to switch these accidentally. 

Happy to help if you want - I learned from your PR already :) 
Discord: Cdr_Maverick#6475

**Comment by patsta32** [comment]
@frankkopp sure! I will have a look into those buttons too

**Comment by patsta32** [comment]
@frankkopp I updated your marked switches excluding the engine 1&2 master. 
I don't know if we should update those, as you mentioned, they are relatively critical, so just a mousewheel could be too easy to switch them accidentally.

**Comment by frankkopp** [comment]
> @frankkopp I updated your marked switches excluding the engine 1&2 master. I don't know if we should update those, as you mentioned, they are relatively critical, so just a mousewheel could be too easy to switch them accidentally.

That's ok - leave them - is probably better.
I will test this PR later again.

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #7605
Tier of Testing: 1
Date: 25/11/2022

Testing Process: 
Testing all switches using mouse wheel and left mouse button

Negatives: None

Testing Results: Passed

Conclusions: LGTM

**Comment by frankkopp** [comment]
Can you update the branch - happy to merge it afterwards.

**Comment by ShadowFrost3** [comment]
Quality Assurance Tester Report


Object of testing: #7605
Tier of Testing:(1
Date: 25/11/2022

Testing Process: Test all the switches
Noted: Engine Ignition switches cannot be switched via mouse wheel. However, given the possibility of an accidently mouse wheel movement. If intentional, I am okay with them being click only to reduce the chance of an accident. 

Testing Results: Passed

(Also the fact that there were no inverted switches found is very good, A+)

**Comment by frankkopp** [comment]
@patsta32 what is your Discord user name? Or ping me on Discord: Cdr_Maverick#6475

**Comment by michael60634** [comment]
I recommend adding a toggle for this option in the flyPad. I'm not sure about other people, but I know that I personally accidentally toggle switches when trying to zoom in or out with the mouse wheel all the time.

**Comment by frankkopp** [comment]
> I recommend adding a toggle for this option in the flyPad. I'm not sure about other people, but I know that I personally accidentally toggle switches when trying to zoom in or out with the mouse wheel all the time. Otherwise, this is a good addition.

I don't think that makes sense as already most swtiches and knobs already use the mouse wheel. This PR simply makes the few which didn't also be usable for the wheel. 

Btw. I have changed my zoom mapping to a combination of another mouse button (I have one one the side) plus the wheel as zooming already often hits a switch/knobs.

**Comment by michael60634** [comment]
@frankkopp I replied to your comment in the issue I created.

**Pull request merged**
