### PR TITLE
[Sounds] Made fuel pumps 5 db quieter

### PR DESCRIPTION
**Pull request by hotshotp**
Made fuel pumps 5 db quieter

## Summary of Changes

I have changed the fuel pumps to be 5 db quieter. This was complained about by a few people, including real life pilots so I turned it down so it is barely audible.

## References

As written before, a few pilots and engineers said it was too loud.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by lukecologne** [comment]
I think you have forgot to commit the changes to the WWise project?

**Comment by hotshotp** [comment]
> I think you have forgot to commit the changes to the WWise project?

I am not going to do that for such a simple fix, that will add many new files and just be overall annoying. Unless it is required then sure but for now I don't think i am going to

**Comment by AdenFlorian** [comment]
i mean, either the files are needed or they arent right? would anyone ever need those files to make changes to this sound in the future?

**Comment by lukecologne** [comment]
But if someone else wants to work on it, and builds the package file again, the sound will be loud again? You are just commiting the the compiled pack files without the source changes

**Comment by hotshotp** [comment]
> But if someone else wants to work on it, and builds the package file again, the sound will be loud again? You are just commiting the the compiled pack files without the source changes

okay fair enough i will add it

**Comment by lukecologne** [comment]
> 
> 
> > I think you have forgot to commit the changes to the WWise project?
> 
> I am not going to do that for such a simple fix, that will add many new files and just be overall annoying. Unless it is required then sure but for now I don't think i am going to

I mean you are not adding new files right? It isn't really annoying, for me at least

**Comment by AdenFlorian** [comment]
Thanks!

**Pull request merged**
