### PR TITLE
Hotfix qnh flashing

### LINKED ISSUE #2081: [BUG] [MCDU] Unable to enter a TA lower than 4500 in the MCDU APR page
**Mod Version**
{ "built": "2020-11-24T00:05:32+00:00", "ref": "refs/heads/master", "sha": "444ed6f93d2915b76f97a07d2ecf0d545ebcf198", "actor": "wpine215", "event_name": "push" }

**Describe the bug**
Unable to enter a TA lower than 4500 feet in the APR page of the MCDU

**To Reproduce**
1. Enter a TA lower than 4500 feet in the APR page of the MCDU
2. FORMAT ERROR appears

**Expected behavior**
MCDU should accept TA lower than 4500

**Actual behavior**
MCDU did not accept TA lower than 4500

**References**

image

Was this working before/when did the issue start occurring?

Yes

Is this a problem in the vanilla unmodded game?

I don't know.

### PR DESCRIPTION
**Pull request by Kimbyeoungjang**
Fixes #2081

## Summary of Changes

change trans lvl to trans alt

## Additional context

due to my wrong reference, qnh logic is wrong when appr phase. i fix that problem

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by St54Kevin** [comment]
What exactly changed?

**Comment by Kimbyeoungjang** [comment]
> What exactly changed?

I accidentally add missed logic. MCDU can add large appr trans alt than takeoff page trans alt but i was setting that is not working. And change simvar name :)

**Comment by St54Kevin** [comment]
> > What exactly changed?
> 
> I accidentally add missed logic. MCDU can add large appr trans alt than takeoff page trans alt but i was setting that is not working. And change simvar name :)

Again I did not understand. Sorry it's a little hard to understand your English. So you can change trans alt on approach page now which did noch work before?

**Comment by Kimbyeoungjang** [comment]
> > > What exactly changed?
> > 
> > 
> > I accidentally add missed logic. MCDU can add large appr trans alt than takeoff page trans alt but i was setting that is not working. And change simvar name :)
> 
> Again I did not understand. Sorry it's a little hard to understand your English. So you can change trans alt on approach page now which did noch work before?

A before qnh logic, can't add trans alt on APPR phase when that value smaller than Takeoff trans alt.
because i add stupid logic on FMC, can't insert that value because i missed that APPR phase have a Trans LVL not a trans alt. (i just think "oh APPR phase have a trans lvl! so that shoud lager than Takeoff Trans alt!" so that think is wrong)

so i remove that logic and change var name(i just change it).

**Comment by St54Kevin** [comment]
You should be able to insert ANY value. Long flights could lead to very different trans alt. Like 12000 vs 3000 or vise versa

**Comment by Kimbyeoungjang** [comment]
> You should be able to insert ANY value. Long flights could lead to very different trans alt. Like 12000 vs 3000 or vise versa

yes i fix that on this pr.

after asobo nav data can receive transition altitude or transition level, i'll add that logic also

**Comment by Teslix** [comment]
Category: QA Tester
Name: Teslix#8746
Date of testing: 27/11/2020
Version of the sim: 1.11.6.0
PR Tested: #2085
Object of test: Ability to set lower trans alt in appr phase, QNH flashes on passing.

Testing technique:
Steps you've made to test the Pull Request:
1. Startup C&D, initialize MCDU, insert to/from/align IRS, create flight plan
2. Set fake trans alt of 6000' on Take Off Perf page and fake trans alt of 4000' on Appr Perf page

mcdu_to
mcdu_appr

3. Departed and climbed to 7000', noted 29.90 pressure flashing on FD passing 6000', indicating to change to STD
4. Set approach phase and decended to 3000'
5. Passing through 4000' QNH on FD flashing STD indicating I should set local QNH.

afterapprtrans

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Works as advertised, no issues. Blue altitude settings display FLXXX in STD and regular altitude while at local QNH.

**Comment by Kimbyeoungjang** [comment]
hmm... this is very simple change. need more testing?

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 12/1/2020
Version of the sim: 1.11.6.0
PR Tested: #2085
Object of test: Ability to set lower trans alt in appr phase, QNH flashes on passing.

Testing technique: Flight from EGCC to EGLL
Steps you've made to test the Pull Request: 
1. Load up c&d with flight plan already loaded from the menu
2. Programmed MCDU
3. Set TO. Trans ALt to: 10000:
Microsoft Flight Simulator Screenshot 2020 12 01 - 10 00 14 96 (2)

4. Set APPR Trans ALT to: 5000:
Microsoft Flight Simulator Screenshot 2020 12 01 - 10 00 22 65 (2)

5. Done the flight

Flight notes: 
- QNH started blinking after climbing through 10.000ft
- STD started blinking after descending through 5.000ft 

Issues: No issues found 
Overall Rating: Good
Conclusions of the testing: Works as described. I can enter every Trans alt. and the blinking works correct.

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 1.12.2020
Version of the sim: 1.11.6.0
PR Tested: #2085 
Object of test: qnh flashing with lower TRL

Testing technique: Try out
Steps you've made to test the Pull Request:
1. Loaded up at LSZH C&D
2. Set up a flight from LSZH to LSGG (TA 5000ft TL 4000ft
3. flew the flight

Flight notes (If required):
qnh flashes at 5000ft while climbing and at 4000ft when descending

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Works as described, no issues found

**Pull request merged**
