### PR TITLE
Master warning

### PR DESCRIPTION
**Pull request by oliverpope03**
**Summary of Changes**

Added Correct Caution and Warning audio
Fixed audios to be affected by ingame UI settings

**Screenshots (if necessary)**

**Additional context**

[Video.zip](https://github.com/flybywiresim/a32nx/files/5226517/Video.zip)

Lots of Changes Due to editting the WWise Project which isnt preventable :)

Discord username: OliverPope03#8087

### CODE REVIEW

**Comment by wpine215** [comment]
Might just be my impression but the warning/caution chimes should be a bit more louder and ear-piercing. Perhaps an IRL A320 pilot can "chime" in here and give their feedback.

Here's a reference I pulled up just now: https://www.youtube.com/watch?v=MbiVuPWX5K8

**Comment by oliverpope03** [comment]
i can turn it up also noticed that my master caution stopped working after rebasing my branch so will fix that too
yeah i agree should be louder just turned down when editting because it kept locking on and my ears where like hurting from it ill fix it now :D

**Comment by armankir** [comment]
A little on the quiet side?

**Comment by Benjozork** [comment]
Do you have credit and attribution for those sounds ? What license are they under ? credits.txt should be used.

**Comment by wpine215** [comment]
> 
> 
> Do you have credit and attribution for those sounds ? What license are they under ? credits.txt should be used.

Jayzee made them from scratch.

**Comment by Benjozork** [comment]
@wpine215 okay thanks !

**Comment by Coralec** [comment]
Tested and working properly. Unless somebody objects to the sounds themselves then this should be ready to merge.

**Comment by tyler58546** [comment]
Why did you replace NavSystem.js?

**Comment by oliverpope03** [comment]
> Why did you replace NavSystem.js?

That is where the caution audio's are called from, i only touched the sound parts none of the functionality changed

**Pull request merged**
