### PR TITLE
Changed MDA and DH to BARO and RADIO in PERF APRR Page

### LINKED ISSUE #1799: [REQUEST] Depiction of the minimum fields is incorrect.
**Is your feature request related to a problem? Please describe.**

Current depiction of the minimum fields at perf aprr page is incorrect.

**Describe the feature you'd like to see implemented**

The Honeywell FMS2 release 1a and rlease2 has Baro/Radio fields instead of MDA/DH at perf aprr page, consequently we have BARO/RADIO instead of MDA/DH at FMA minimum Column

**References**

image

**Additional context**

Dear developers, in generall it seems that you make thales FMS1 (older version of FMGS), nowadays all airbus aircraft are equipped with honeywell FMS2 release1a, and all NEO aircraft equipped with FMS2 release2

image

Discord username (if different from GitHub):
Антон Пушков#0240

### PR DESCRIPTION
**Pull request by tareksabet**
Fixes #1799 

## Summary of Changes

Changed the appearance of MDA and DH in PERF APPR Page to BARO and RADIO
## Screenshots (if necessary)
Before 

unknown

After 

Desktop Screenshot 2020 12 21 - 01 36 53 63

## References

Desktop Screenshot 2020 12 21 - 01 10 07 19

From Honeywell Pegasus Step 1A manual

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
Small enough fix, merging

**Comment by MisterChocker** [comment]
Has this been changed on the FMAs as well?
Also MDA, DH are not the same as RADIO and BARO afaik. We had a discussion about that.

**Comment by MisterChocker** [comment]
this is real life reference

image

**Pull request merged**
