### PR TITLE
refactor: import asobo templates

### LINKED ISSUE #2689: Adding A32NX mod to community folder breaks the FMC on the default 747 aircraft
**Mod Version**

"built": "2020-12-24T07:44:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "donstim <70166617+donstim@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**

Whenever the Stable or Dev versions are loaded into the community folder there is an issue caused with the default 747-8. The issue is that the FMC is blank and cannot be used. The mod does not impact the FMC on the A32NX and that aircraft appears to be fully functional. 
As soon as the FBW mod is removed from the Community folder the FMC on the 747 returns to normal functionality

**To Reproduce**

1. Empty community folder of all mods
2. Check functionality of 747 FMC in FS2020
3. Install the Dev or Stable version of the FBW aircraft
4. Return to FS2020 and check functionality of the FMC

**Expected behavior**

747 aircraft will work as expected including the ability to use the FMC

**Actual behavior**

The FMC on the 747 is blank and cannot be used.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This has only started happening since the December update to FS2020
Is this a problem in the vanilla unmodded game?
Yes

IMG_0183

### PR DESCRIPTION
**Pull request by Benjozork**
Addresses #1215
Fixes #2689

## Summary of Changes

* Imports templates from `ModelBehaviorDefs/Asobo` and renames them

## Additional context

Discord username (if different from GitHub):

## Testing instructions

* Test MCDU buttons functionality - do the buttons work ?
* Test FCU functionality - do the buttons and displays work ?
* Test transponder and radio panel functionality
* Test as much functionality related to physical buttons, switches and knobs as possible

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Lazarus320** [comment]
| Category: QA Tester  |
|----------------------|
| Name: Lazarus#4286   |
| Date of testing:  24/12/2020|
| Version of the sim: 1.12.13|
| PR Tested: #2672 |
| Object of test: Import and rename templates from Asobo |

| Testing technique: Loaded c&d and tested all operative buttons/switches along with MCDU functionality|
|-|

| Steps to test the Pull Request:|   |
|-|-|
| 1 | Tested all switches and buttons including MCDU. Full testing: https://youtu.be/0y6c9q9op_Q |


| Flight notes: N/A |
| --- |

| Issues: Transponder is inop. except for TCAS as well as F/O MCDU. For reference: Transponder https://user-images.githubusercontent.com/74972083/103084448-f4325c80-4619-11eb-8206-ab149da49edc.mp4 MCDU: https://user-images.githubusercontent.com/74972083/103084467-001e1e80-461a-11eb-85ce-b65e7ab15ff1.mp4|
| --- |

| Overall rating: | Needs adjustment |
|-|-|

| Conclusions of the testing: | Transponder issue is crucial so it needs to be sorted out along with the MCDU|
|-|-|

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: Current date 24/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2672 
Object of test: Check all buttons/switches/dials etc work as before with this PR

Testing technique: Spawned C&D for a full flight
Steps you've made to test the Pull Request:
1. Spawned C&D at Skiathos for a flight to Zakynthos
2. During initial setup - everything worked well EXCEPT for transponder.
3. Unable to continue on VATSIM as transponder could not be set - see 'Issues'
4. Test ended - checked against another PR which worked fine.

Flight notes (If required): N/A

Issues (If Any): The Transponder seems to have been affected by this PR though I'm not sure how... the buttons for the transponder code no longer work and the animations/sounds for them do not work either. The transponder code is unable to be changed. Additionally, the XPDR Standby/On/Alt switch is inop - as are Alt Rep and ATC switches on the transponder box. Ident is also Inop.
The TCAS switches however work and are animated.
Overall Rating: To be improved
Conclusions of the testing: Everything I tested worked fine except for the Transponder box as noted above in Issues.

**Comment by Benjozork** [comment]
@Lazarus320 the FO side MCDU was never operational before this PR.

Thanks both of you, will fix the transponder issue.

**Comment by Benjozork** [comment]
Transponder should now work.

**Comment by Lazarus320** [comment]
> Transponder should now work.

LGTM well done. 

ezgif com-gif-maker

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
