### PR TITLE
fix: correct fueling rate by using deltaTime

### PR DESCRIPTION
**Pull request by Maximilian-Reuter**
## Summary of Changes
The current version of the refueling system does not take into account the deltaTime between update calls. Since the throttling pr has changed the deltaTime, the current version takes too long. 

I have adapted the refueling system to use deltaTime and also got rid of a double use of the REFUEL_FACTOR constant.

## References
see #3744 

## Additional context

Discord username (if different from GitHub): Chaoz#3065

## Testing instructions

As can be seen in the references, normal fueling time for the wing tanks from empty to full should be 17 min.
Center tank adds 3 mins.

So for testing, either the full loading or any fraction of that can be used.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
Nice to have the rate constant, and in engineering units. 👍

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: /2021
Version of the sim: 1.14.6.0
PR Tested: #4216 
Tier of testing: 1 
Changes to observe: Refuel time changes 

Testing technique: Loaded C/D with empty fuel tanks did a full refuel 
Steps you've made to test the Pull Request:
1. Measured the time taken for the wing tanks to be full
2. Measured the time taken for the center tank to be full 

Flight notes: N/A 

Media: 

Wing tanks: 

image

Center tank: 
image


Issues: N/A 


Overall Rating: Good
Conclusions of the testing: LGTM good job!

**Comment by easyjetsimpilot** [comment]
Category: QA Tester
Name: Gavin (easyjetsimpilot)
Date of testing: 1/4/2021
Version of the sim: 1.14.6.0
PR Tested: #4216
Tier of testing: 1
Changes to observe: Refuel time changes

Testing technique: Loaded C/D with all tanks empty. Timed the time taken to refuel wing then center tanks

Wing Tanks:- 17:03 
Center Tanks:- 3:23

Overall Rating: Good
Conclusions of the testing: Works exactly as expected. Thank you. !

**Comment by darkfury334** [comment]
Category: QA Trial
Name: DarkFury#4936
Date of testing: Current date 01/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4216
Tier of testing: 1
Changes to observe: Refuel time changes

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Loaded C&D at EGCC with no fuel
2. Timed how long to fill up wing tanks
3. Timed how long to fill center tank

Wing Tanks - 17:03
Center Tank - 3:03

Flight notes (When done a full flight):N/A
Issues (If Any): N/A

Overall Rating: Good
Conclusions of the testing: Works as intended. Awesome

**Comment by Samueleonard** [comment]
Category: QA Tester
Name: 1Samueleonard1#0001
Date of testing: Current date 01/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4216
Tier of testing: 1

Changes to observe: correct refueling times through EFB

Testing technique: Tryout
1. loaded up c+d - set up acft (STARTED WITH 9420kgs)
2.  instant refueling (9430 -> 9869) - instant fueled as expected
3. fast refueling (9860 -> 10438) - est 0.5mins, act 15 secs (probably correct but not long enough time period to tell)
4. real refueling (10436 -> 12147) est 2mins, act 2min 27 (notes below but works regardless)

Flight notes: out of the scope for this PR but should 2min27 not be rounded up to 2.5 mins? 

Media: N/A

Issues: N/A
Steps to achieve the issue N/A

Overall Rating: Good

Conclusions of the testing: LGTM

**Pull request merged**
