### PR TITLE
Upper ECAM Thrust lever position fix

### PR DESCRIPTION
**Pull request by RichardPilbery**
## Summary of Changes

In the Upper ECAM, around the outside of the N1 gauge is a circle which represents the thrust lever position. However, its position currently seems to be calculated based on the N1 percentage. This PR fixes that and uses the Simplane.getEngineThrottle() function to determine the throttle lever position for each engine.

## Screenshots (if necessary)

**BEFORE**

orig-throttle-idle

orig-throttle-max

**AFTER**

after-throttle-idle

after-throttle-max

## References

Screenshot 2020-10-19 at 19 21 11

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
@RichardPilbery is this ready ? If you're still working on it, please mark the PR as draft.

**Comment by RichardPilbery** [comment]
Yes it is.

**Comment by RichardPilbery** [comment]
If I'm doing something wrong with status setting, please let me know. I don't tend to submit a PR unless it's revision is ready to submit.

**Comment by nobodyn0se** [comment]
In my last test, the thrust lever position lagged the N1 indicator (levers at 25% and N1 at 49%) until FLX/TOGA. I'll try again with a clean branch.

**Comment by RichardPilbery** [comment]
Thanks for testing this @nobodyn0se. The thrust indicator is independent of N1. It *should* reflect the position of the thrust lever i.e at 10 when TOGA, 5 when halfway between Idle and TOGA.

**Comment by nobodyn0se** [comment]
Is this correct? 
ThrustLimit

**Comment by RichardPilbery** [comment]
@nobodyn0se Can you post a picture of this screen and your throttles?

**Comment by Benjozork** [comment]
@RichardPilbery - your reference is from both an EIS1 (CRT screens) and from the wrong engine (IAE V2500; we model the LEAP 1-A). Please find a reference for an A320neo with the LEAP-1A engines.

**Comment by ChruutvoLuzi** [comment]
Name:  ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 22.10.2020
Version of the sim: PR Tested: #1477
Testing technique: Try Out

Steps you've made to test the Pull Request:
 - Spawned C&D
 - Started up everything
 - Started up the apu and engines on pushback
 - Moved the Thrustlevers during the flight and checked the thrust lever position on ecam

Overall Rating: Good, works without any problems

Conclusions of the testing: No issues occured, works as described
nice little fix, gj

**Comment by Benjozork** [comment]
@RichardPilbery - my bad, I confused this PR with another that did cosmetic changes.

This is good to go

**Comment by RichardPilbery** [comment]
No worries. Planning on doing a bit more flying and less PRs in the next week or two!

**Pull request merged**
