### PR TITLE
fix(efb): unresponsive buttons and deactivated doors

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #[issue_no]

## Summary of Changes

Changed event used by the Button component to remove the need of clicking multiple times in order to activate it.

Also fixed a bug in ground services that left doors inpoerable after it was disconnected manually by the game

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Check that all buttons on the EFB work as intendend and do not require multiple clicks.
2. Activate the pax ramp and catering on the ground services page and wait until they are finished.
3. Check that the fwd and aft door are still operable
4. Verify that pushback directions only work after the tug was requested

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 08/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4295 
Tier of testing: 1
Changes to observe: EFB functionality

**Steps you've made to test the Pull Request:**
1. Loaded up at the Gate
2. Powered EFB up and checked every function
3. Explicit check of ground services on Gate and on a Stand

**Media:**

**Issues (If Any):**
 - On a stand, after stairs and catering is finished, I called the pushback truck and then opened the doors again, but couldnt close them. Only after disconnecting the truck, which weirdly turn the door buttons to blue, I could click them again and close the doors.

**Conclusions of the testing:** LGTM except the above door bug. Fixes of this PR do work.

**Comment by Saschl** [comment]
Thanks for the test, I'll have a look into the issue you found

**Comment by Saschl** [comment]
Alright, should be fixed.

**Pull request merged**
