### PR TITLE
Fix #333 No Gear Up on Ground

### LINKED ISSUE #333: BRK LEVER shouldn't be able to be moved UP on the Ground
In the real Airplane, there is an electromechanical lock that prevent accidental operation of the gear lever when the A/C is on the ground. 
Not implemented in MSFS, but can be implemented in code

### PR DESCRIPTION
**Pull request by NathanInnes**
Fixes #333 

**Summary of Changes**

Gear lever is no longer able to come up when on ground.

**Screenshots (if necessary)**

**Additional context**

Discord username (if different from GitHub): Sabes#8668

### CODE REVIEW

**Comment by Snapmatics** [comment]
I will test it right now.

**Comment by Snapmatics** [comment]
Works 10%

**Comment by CoffeePanda0** [comment]
> 
> 
> Works 10%

haha you mean 100?

**Comment by UncleClapton** [comment]
LUL it turned out to be THAT easy?

**Comment by Snapmatics** [comment]
> > Works 10%
> 
> haha you mean 100?

oops, yes

**Comment by JackZ974** [comment]
Nice find in the aircraft.cfg! 
Have found some other parameters for the steering that need to be tweaked as well, will open a separate PR for this.

**Comment by NathanInnes** [comment]
Asobo really do be strange sometimes.

**Pull request merged**
