### PR TITLE
Added two captain to cabin crew calls

### PR DESCRIPTION
**Pull request by oliverpope03**
**Summary of Changes**

Adds "Cabin Crew seats for landing please" when chime is first pressed after entering the landing phase
Adds "Cabin Crew Seats for takeoff please" when "cabin......Check" and "TO Config" are green on takeoff memo

**Screenshots (if necessary)**

**Additional context**

Suggested by Iceman

### CODE REVIEW

**Comment by Benjozork** [comment]
Are these files royalty-free ?

**Comment by oliverpope03** [comment]
Someone in our discord recorded them all references are in the sound spreadsheet

**Comment by AdenFlorian** [comment]
please find a way to remove any audio files that aren't needed for the new crew call sounds. And please add a README.md in the Originals/SFX folder with credits for each sound file, thanks!

**Review by wpine215 — APPROVED** [review]

**Comment by wpine215** [comment]
LGTM, I'll just remove the unneeded /.cache/ folder and add a gitignore rule for it going forward

**Comment by oliverpope03** [comment]
> LGTM, I'll just remove the unneeded /.cache/ folder and add a gitignore rule for it going forward

Thank you i was going to do the same once i had got up, im righting a credits.txt with names of people who provided sounds included ect

**Comment by ukflyer** [comment]
is it possible to add the captain announcements as an option as i already have them in the 'Self-Loading Cargo' program

**Pull request merged**
