### PR TITLE
feat(textures): overhead panel decal improvements

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes
Improves the general look of the overhead panel decals and fixes a few issues.

- Remade the green arrow/line decals from scratch and adjusted the color to better fit neo references.
- Remade and corrected the position of the rectangle decal

Screenshot (79)

## Screenshots (if necessary)
Before:

fullBEORE

After:

fullAFTER

Close-up comparison: 
arrowsBEFORE
arrowsAFTER
kvadratbefore
kvadrataftter

## References

IMG_0101

Discord username: Imenes#8739

## Testing instructions

Check the overhead panel and inspect the decals, if you find an issue make sure to compare it to dev first to make sure it is related to this PR. Inspect the rest of the cockpit decals to make sure there are no conflicts or new issues that have arrisen. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by DarkOfNova — APPROVED** [review]
LGTM

**Comment by St54Kevin** [comment]
Arrow from AC EES Feed to AC ESS BUS should be a thin one looking at your reference photo

**Comment by DarkOfNova** [comment]
> Arrow from AC EES Feed to AC ESS BUS should be a thin one looking at your reference photo. I can see actually a lot of differences. Are your Screenshots not finished ones?

Sadly we can't individually edit the thickness of lines. We are aware though so when we can we'll be sure to change it.

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 28.02.2021
Version of the sim: 1.13.16.0
PR Tested: #3755 
Tier of testing: 1
Changes to observe: New Green Decals

Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned at A44 LSZH
2. Started up the Aircraft
3. Checked new Decals
4. Checked for other faults

Media:
Microsoft Flight Simulator Screenshot 2021 02 28 - 17 39 01 98

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Works as described and looks really good

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 28.2.2021
Version of the sim: 1.13.16.0
PR Tested: #2755
Tier of testing: 1
Changes to observe: OH decals
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP 
2.) Turned on bat. and ext. power
3.) Looked at OH decals (Image1)

Media:


Image1

PR fixes green color, labelboxes line width and cleans up stuttering connector lines. 
 
Issues (not off this PR): Missing lines and wrong label positions

Overall Rating: Good

Conclusions of the testing: Looks nice!

Hope this helps :-)

**Comment by tareksabet** [comment]
* Category: QA Tester
* Name: tarek_sabet#7946
* Date of testing: 28/02/2021
* Version of the sim: 1.13.16.0
* PR Tested: #3755 
* Tier of testing: 1
# Changes to observe:
### New Green line decals and new square decals on the Overhead Panel

* Testing technique: Tryout
# Steps you've made to test the Pull Request:
### 1. Spawned at HECA in C&D state
### 2. Changed the time from Day to Night 
### 3. Turned on and off the OVHD INTEG LT 

## Flight notes (When done a full flight):
### N/A

# Media: 
* Image 1: (Night, OVHD INTEG LT ON and DOME LT OFF)
Microsoft Flight Simulator Screenshot 2021 02 28 - 19 18 42 85

* Image 2: (Day, OVHD INTEG LT ON and DOME LT OFF)
Microsoft Flight Simulator Screenshot 2021 02 28 - 19 33 19 15

* image 3: (Day, OVHD INTEG LT OFF and DOME LT OFF)
Microsoft Flight Simulator Screenshot 2021 02 28 - 19 33 27 92

* Image 4: (Night, OVHD INTEG LT OFF and DOME LT OFF)
Microsoft Flight Simulator Screenshot 2021 02 28 - 19 37 27 81

* Image 5: (Night, OVHD INTEG LT ON and DOME LT ON)
Microsoft Flight Simulator Screenshot 2021 02 28 - 19 50 59 100

# Issues (If Any): 

N/A

# Overall Rating: Good
# Conclusions of the testing: 
everything looks good, looks very good job Imenes love it, keep up the good work :clap:

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 01/03/2021
Version of the sim: 1.13.16.0
PR Tested: #3755 
Tier of testing: 1
Changes to observe: Overhead Panel decal improvements

Testing technique: Spawned in midair and flew into Split, Croatia to check against different light conditions compared to all previous tests above
Steps you've made to test the Pull Request:
1. Spawned 50nm North West of Split Kastela airport, checked overhead panel in clear bright sky in live MSFS weather
2. Checked with overhead "lighting" turned up and also off
3. Checked from a few different angles
4. Worked through entire panel to see if anything is missing, rough or broken - nothing found

Flight notes (When done a full flight): N/A

Media: 
Microsoft Flight Simulator 01_03_2021 11_20_57
Microsoft Flight Simulator 01_03_2021 11_21_13
Microsoft Flight Simulator 01_03_2021 11_21_25
Microsoft Flight Simulator 01_03_2021 11_21_04

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Nice improvements!

**Comment by DavidEGTE** [comment]
Category: QA Tester 
Name: David#2177
Date of testing: 01/03/2021
Version of the sim: 1.13.16.0
PR Tested: #3755 
Changes to observe: OVH decals
Testing technique: Try-out

Steps made to test the Pull Request:

1.) Spawned C&D at LFPG
2.) Turned on bat. and ext. power, oxy, nav, arm EL
3.) Try different modes of the day/dawn/night
4.) Full brightness on OVHD INTEG LT at dawn time
4.) Night time full FLOOD LT (MAIN PNL) with OVHD INTEG LT

Microsoft Flight Simulator Screenshot 2021 03 01 - 13 32 00 57
Microsoft Flight Simulator Screenshot 2021 03 01 - 13 33 06 96
Microsoft Flight Simulator Screenshot 2021 03 01 - 13 33 28 15
Microsoft Flight Simulator Screenshot 2021 03 01 - 13 34 11 09
Microsoft Flight Simulator Screenshot 2021 03 01 - 13 34 52 82
Microsoft Flight Simulator Screenshot 2021 03 01 - 13 35 29 37
Microsoft Flight Simulator Screenshot 2021 03 01 - 13 37 27 60

Observation 2nd last photo, GEN1 LINE is a bit out-of-line

Overall Rating: Good
Conclusions of the testing: Absolutely good job

**Comment by beheh** [comment]
> Observation 2nd last photo, GEN1 LINE is a bit out-of-line

This is unrelated to this PR apparently.

**Pull request merged**
