### PR TITLE
ENG 1(2) OIL LO PR checklist

### PR DESCRIPTION
**Pull request by toffee2000**
**Summary of Changes**

Adds ENG 1(2) OIL LO PR checklist, with correct closed-loop items and status messages.

**Screenshots (if necessary)**

image

**Additional context**

image

### CODE REVIEW

**Review by tyler58546 — CHANGES_REQUESTED** [review]
This failure should be added to the existing ENG 1(2) category, not to a new one. You also created a duplicate SHUT DOWN message for each engine which needs to be removed.

**Comment by toffee2000** [comment]
I’ll try that and inform you when I make the necessary changes. Thanks!

**Comment by toffee2000** [comment]
@tyler58546 
Removed the duplicates. However ENG 1(2) SHUTDOWN does not show after ENG 1(2) OIL LO PR is completed. I'm at a loss here, since my original (duplicate) code worked. Could you help me?

**Comment by tyler58546** [comment]
According to https://www.ipadecam.co.uk/, the message should read `ENG 1(2) LO OIL PR` (not sure which is correct) and should be shown as a level 3 warning (red). It should not trigger any secondary failures and the white text should not be indented.
image

**Comment by toffee2000** [comment]
Interesting, because my (admittedly outdated) FCOM shows ENG 1(2) SHUTDOWN after.

**Comment by toffee2000** [comment]
I think I've figured out the ENG 1(2) SHUTDOWN not showing. Will test it and see.

**Comment by Benjozork** [comment]
Hello, please take note that we have started including a CHANGELOG.md file that requires every PR to add a change-log line that describes its changes. As your PR is not merged yet, we kindly ask that you add this information following the included directives in the file.

Disclaimer: This is a copy-and-pasted message.

**Comment by NathanInnes** [comment]
Also please remove layout.json from PR as it isn't needed.

**Comment by AdenFlorian** [comment]
@toffee2000 are you still working on this?

**Comment by toffee2000** [comment]
Yes, but I really can't say when it'll work. I was getting ready for the previous release and then they dropped the new one. Maybe close it for now, I'll reopen when I get it sorted properly. Sorry!

**Comment by NathanInnes** [comment]
No worries just re-open whenever it's ready to go.

**Pull request closed without merging**
