### PR TITLE
Fix to the lateral swaying in cruise

### LINKED ISSUE #2005: [BUG] Aileron rocking at cruise
**Mod Version**
 0.4.1

**Describe the bug**

At cruise on autopilot the airplane rolls subtly back and forth. You can see the ailerons moving up and down fairly rapidly.

**To Reproduce**

Climb to cruise on autopilot. For me it starts rocking during the climb or at cruise and continues until I start descent.

**Expected behavior**

Smooth flight

**Actual behavior**

See above

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I downloaded yesterday and it has happened on all four flights I've done

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub): nhvtmedic

### PR DESCRIPTION
**Pull request by crisk73**
Fixes #2005 

## Summary of Changes

Increases the derivative Dk term of AP PID controller for roll, thus attempting to eliminate the persistent oscillations.
## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: Current date 04/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2216
Object of test: Testing if this fixes the lateral swaying issue 
Testing technique: Try-out (multiple tests)

## Steps you've made to test the Pull Request:

 * Full flight from C&D over the Alps since the issues seem to happen most when flying over the mountains/ turbulent areas.
 * Flight from Paro over the Himalayas 
 * Issue did not pop up for me in all of the tests.

## Overall Rating: Good
 
#### Conclusions of the testing:
 * This fixes the swaying issue, thank you for your contribution! See ya later SEC1.

**Comment by Awemeter** [comment]
Category: Trial QA Tester
Name: Awemeter#7919
Date of testing: 12/3/2020
Version of the sim: 1.11.6.0
PR Tested: #2216 
Object of test: Auto Pilot 

Testing technique: Tried out
Steps you've made to test the Pull Request:
1. C&D flight from Kiad to Katl
2.  No issue during the cruise.
3. Landed at katl.


Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Fixed the swaying issue and no other bugs found. Great job.

**Comment by donstim** [comment]
Will you still get a bit of a wing rock (not a constant swaying) from turbulence or wind gusts?

**Comment by Awemeter** [comment]
> Will you still get a bit of a wing rock (not a constant swaying) from turbulence or wind gusts?

Yes, you will in fact when I tested it was swaying due to turbulence.

**Comment by donstim** [comment]
Congrats! I think this will make a lot of people happy!

**Comment by Gamma36** [comment]
I've done a diff for ai.cfg from the latest dev and the Asobo patch yesterday.

They have further reduced roll gain and pitch I boundary.

The FBW heading integration gain makes sense, Asobo's I and D boundaries are different.

ai_diff

**Comment by crisk73** [comment]
Shown Asobo's I and D boundaries for heading are those prior to the fix by Sebastian of Asobo.
Maybe it's worth trying the lesser gain for roll but I would't touch it unless other problems are encountered.
Thanks.

**Comment by Mega-Touk** [comment]
> 
> 
> > Will you still get a bit of a wing rock (not a constant swaying) from turbulence or wind gusts?
> 
> Yes, you will in fact when I tested it was swaying due to turbulence.

that pure pleasure seeing my plane going straight and swaying on the wind is awesome. the fix is working great !

**Comment by Hundredabove** [comment]
SO how can i make this work ? Just installing the latest master branch as always? Thats it ?

**Comment by Benjozork** [comment]
Yes.

**Pull request merged**
