### PR TITLE
Fix incorrect slat position after 1.8.3

### LINKED ISSUE #751: [BUG] Slat position incorrect
**Mod Version**

Newest Master

**Describe the bug**

Slats are in a wrong position in every flaps config

**To Reproduce**

1. Spawn on runway
2. Look at upper ECAM

**Expected behavior**

grafik

**Actual behavior**

grafik
grafik
grafik
grafik

**References**

**Additional context**

* Does not occur in c1b040ad5ddb0eaa1fbf225fbdd8048eb29c379d
* I think this actually represents the slat position, so the indicator isn't wrong, but the actual slat position is.

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes #751

**Summary of Changes**

* Fix incorrect Slat position introduced by #720 after update 1.8.3

#720 also changed slats lift scalar, should be tested

**Screenshots (if necessary)**

Source: 
grafik
Before: 
grafik

### CODE REVIEW

**Review by AdenFlorian — APPROVED** [review]
ready to test!

**Comment by Coralec** [comment]
Tested. The slat position is now working properly.

**Comment by lukecologne** [comment]
Everyone who is testing this: make sure to also check the lift caused by the slats/flaps, because Asobo changed the slat lift/drag scalars as well, and I am just setting the slat postion back to normal, while leaving the changed scalars. Maybe we will have to reset those as well.

**Comment by AdenFlorian** [comment]
@lukecologne how would one test the lift?

**Comment by lukecologne** [comment]
I don't know. It's especially a problem since they changed the flaps scalars as well, so I think the only way to test the slats indivdually may be config 1. I was hoping a IRL pilot could comment on the "feel"

**Comment by Coralec** [comment]
Any issues with the lift performance of the slats/flaps would really be a separate issue. We can keep an eye out for issues with lift performance in future testing but at least this pull fixes the indicators.

**Comment by AdenFlorian** [comment]
I had Ares take a look at this PR, and he's not even sure how he wouold test it, so I'll go ahead and merge it. There's so much wrong with how the plane flies right now, that I think we have to wait until a lot of things are fixed and then we'll start doing flight model passes.

**Comment by DABUS320** [comment]
I have no way to test this issue... I cannot tell you if it feels right since its a virtual game.

**Pull request merged**
