### PR TITLE
feat: new glareshield textures by Repsol

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

- Adds new glareshield textures by Repsol

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub): someperson#4953

## Testing instructions

* Make sure textures work

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Pushok154** [comment]
what sense of redrawing textures? if glareshield model is completley wrong, it must be straight, not curved like in actual model =( it completely spoil the impression.

**Review by bouveng — APPROVED** [review]

**Comment by Benjozork** [comment]
@Pushok154 Textures cannot change geometry. A new model is being done from the ground-up as we announced. In the mean time, we won't pass on some new textures...

**Comment by Pushok154** [comment]
> we won't pass on some new textures...

oh, =) now i see you i see you.

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#5438
Object of testing: #6298 
Tier of Testing: 1
Date: 5/12/21

Testing Process: Loaded in and looked at the glareshield to check new texture was there
Negatives: N/A
Testing Results: Passed

Conclusions: LGTM
Media:
image

**Comment by mehoygg** [comment]
Quality Assurance Tester/Trainee Report

Discord          : mehoygg#1242
Object of testing: #6298
Tier of Testing  : 1
Date             : 05/12/21

Testing Process: 
I spawned in at KLAX on the runway with live time so about 12:30PM PST. With the sunlight facing the cockpit.  Using the camera to pan around and move looking at the screens you can see the glare move and can see the glare when looking at the screens. 

I then spawned in C/D and started up the plane.  You can see the glare once the screens are lit up.  Brightening the screens show the glare more.  Glare does move around depending on the view angle.

Negatives:       
N/A

Testing Results: 
PASSED

Conclusions: 
Glare at first was a bit hard to spot.  But I wasn’t looking close enough or moving.  Once light starts traveling or you’re looking around etc, glare is there. Works good and looks good too!

Media:       
N/A

**Comment by mehoygg** [comment]
Quality Assurance Tester/Trainee Report

Discord          : mehoygg#1242
Object of testing: #6298 
Tier of Testing  : 1
Date             : 05/12/21

Testing Process: 
Spawned into KLAX on the runway in Dev, took a screenshot. Did the same with this PR and Texture is there for 6298 and a very noticeable difference.
Negatives:       
N/A

Testing Results: 
PASSED

Conclusions: 
Providing report to rectify the mistake from earlier. Texture looks really good.

Media:       
Microsoft Flight Simulator Screenshot 2021 12 05 - 15 03 56 55

**Pull request merged**
