### PR TITLE
TOP OF DESCENT (MCDU predictions and pseudo waypoints)

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Added pseudo waypoints:
    * (LIM)
    * (T/C)
    * (T/D)
    * (DECEL)
* Added ETA predictions for all waypoints and pseudo waypoints
* Added altitude predictions for waypoints in climb and cruise
* Added speed predictions for all waypoints
* Predictions will only be available if all necessary data has been inserted on the init page

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by chromkoo** [comment]
Thanks for all your efforts, the A320 really needs this! I hope to see this finished asap :)

**Comment by snaylor111** [comment]
Can't wait for implementation

**Comment by Yodap10** [comment]
Great, can't wait for this big milestone! :)

**Comment by Hundredabove** [comment]
So why this is not moving forward.....

**Comment by Benjozork** [comment]
> So why this is not moving forward.....

Because everyone here works in their free time and sometimes people don't have the time to work on things. If you want to offer your help to work on this functionality, feel free to hit us up on Discord.

**Comment by karim11379** [comment]
any update in this topic ?
do you have feedback guys ? it's important to have T/C and T/D waypoints on MCDU

**Comment by Benjozork** [comment]
It's Christmas my friend, people aren't working.

Also, #2597

**Comment by jsid87** [comment]
Hi,first thanks for hard work...do you have any time line when this could be implemented?

**Comment by Benjozork** [comment]
Please do not comment asking when Top of descent is coming. Let people work.

**Comment by wpine215** [comment]
Good to close this PR since VNAV/ToD will be handled in a separate PR once autopilot + flight plan manager is in dev?

**Pull request closed without merging**
