### PR TITLE
fix(adirs): delay "on bat" activation

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes
In the [video supplied by Parorng[Z+7]#4524](https://discord.com/channels/738864299392630914/739225362642501672/825628162271477760) the ON BAT light doesn't activate until approx. 10.5 seconds after the ADIRS selectors are moved to the NAV position. Adjust the ADIRS on bat timer to match this.

## References

https://discord.com/channels/738864299392630914/739225362642501672/825628162271477760

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Power up aircraft, and switch an ADIRS on. Observe 10.5 second delay until ON BAT light illumination (note, alignment time is not affected), and 5 seconds later extinguishment.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by myselfaaryan — APPROVED** [review]
LGTM!

**Comment by myselfaaryan** [comment]
@tracernz Nice PR! Not sure about this, but I think, the extinguishment of ON BATT itself takes around 6-7 seconds.

**Comment by tracernz** [comment]
> 
> 
> @tracernz Nice PR! Not sure about this, but I think, the extinguishment of ON BATT itself takes around 6-7 seconds.

It's currently 5 seconds... maybe that is a little short compared to the video..

**Comment by myselfaaryan** [comment]
> It's currently 5 seconds... maybe that is a little short compared to the video..

Yeah seems like it. Its 7 seconds in the video.

**Comment by beheh** [comment]
Could @komp1821 chime in on this re accuracy? I wonder if this is something that's specific to the type of ADIRS unit being used, or a specific CEO or NEO behavior.

**Comment by ExampleWasTaken** [comment]
> ON BAT not showing when airplane is powered up by batteries only (either BAT 1+2 or any combination of battery). Not sure the PR is supposed to cover the ADIRS logic.

I can't reproduce that. If the aircraft is powered by BATs only ON BAT still lights up.

**Comment by ExampleWasTaken** [comment]
Category: QA Trial
Name: `ExampleWasTaken#0886`
Date of testing: 31/03/2021
Version of the sim: 1.14.6.0
PR Tested: #4210
Tier of testing: 1
Changes to observe:
delay ON BAT activation

Testing technique:
1. Loaded C&D
2. Turned on BAT 1 & 2
3. Turned on EXT PWR 
4. Set IRS 1 to NAV - ON BAT lights up after about 10.5-11 secs and extinguishes after about 5
5. Set IRS 2 to NAV - ON BAT lights up after about 10.5-11 secs and extinguishes after about 5
6. Set IRS 3 to NAV - ON BAT lights up after about 10.5-11 secs and extinguishes after about 5
7. Turned off EXT PWR 
8. Repeated step 4 - same behavior 
9. Restarted flight
10. Repeated step 2 and 4 without step 3 to reproduce second issue mentioned in [previous review](https://github.com/flybywiresim/a32nx/pull/4210#issuecomment-811109286)

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): N/A

Overall Rating: Good
Conclusions of the testing: Once the timing has been verified/corrected it's GTG

**Comment by ExampleWasTaken** [comment]
Adding to:
> ON BAT showing as expected during the initialisation procedure (10sec off then ON for 5sec) but is disappearing and not showing anymore when airplane is powered up by batteries only (either BAT 1+2 or any combination of battery, EXT PWR OFF no APU). Not sure the PR is supposed to cover the ADIRS logic.

grafik

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 31/03/2021
Version of the sim: 1.14.6.0
PR Tested: #4210
Tier of testing: 1

Changes to observe:
(adirs): delay "on bat" activation

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. Spawned C&D
2. EXT. PWR + BAT1+2 
3. Checking timing for ADIRS ON BAT indication


Flight notes (When done a full flight):
N/A
Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A
Issues (If Any): Write any issues
N/A
Steps to achieve the issue:
N/A

Overall Rating: Good
Conclusions of the testing: Works as video supplied in PR reference, GTG

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 5/4/21
Version of the sim: 1.14.6.0
PR Tested: #4210 
Tier of testing: 1
Changes to observe:
Adir On Bat light

Testing technique: Loaded in and looked
Steps you've made to test the Pull Request:
1. Watched reference
2. marked times
3. tried in sim while checking it was similar/same timing 

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: LGTM

**Comment by tracernz** [comment]
This will need a changelog now that it's targeted for 0.7 so I tagged.

**Comment by tracernz** [comment]
This one is rather quick: https://www.youtube.com/watch?v=7o3_zDGEN6A

**Comment by beheh** [comment]
Yeah, although those are older generation ADIRS with the extra buttons. In any case that's why I'd like to see more references or anecdotes, especially from NEOs, before we land this.

**Comment by FlyingCarpet7** [comment]
Just put this link to my video in here as well for references.
https://youtu.be/97XUgUnWo1s

**Comment by tracernz** [comment]
> 
> 
> Just put this link to my video in here as well for references.
> https://youtu.be/97XUgUnWo1s

Yours is a neo and also quite a long time (about 10.5 seconds). What do you think @beheh?

**Comment by ExampleWasTaken** [comment]
> 
> 
> > Just put this link to my video in here as well for references.
> > https://youtu.be/97XUgUnWo1s
> 
> Thanks! Yours is also a neo and also quite a long time (about 10.5 seconds). What do you think @beheh?

I think it's kinda hard to tell the exact times because he doesn't wait for the ON BAT light to extinguish.

**Comment by beheh** [comment]
komp was confirmed on Discord that across 4 aircraft the timing was around 10 seconds each. Looks like the change is confirmed, then.

**Comment by tracernz** [comment]
Rebased and added changelog. The single line change hasn't changed since all the previous tests so I think this is good to merge?

**Pull request merged**
