### PR TITLE
fix(hyd): fix tca autobrake button after SU5

### LINKED ISSUE #5516: Autobrake issue (Buttons dont stay illuminated) with TCA Quadrant Add-on
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-02T01:07:42+00:00",
  "ref": "master",
  "sha": "738f163b180942ba00b626c1f6ca947bd1997103",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Reposting of Topic, as requested by AGuther,

When selecting an Autobrake value (lo/med/max), the button lights up, but without further activities it will stop glowing after a while. Sometimes it will illuminate again, and go off again.. in an interval of a few seconds to up to 20-30 seconds.
This results in set autobrakes on final that then don't work after touchdown because the button somehow deactivated.

I know the Autobrake logic was altered after it didnt work anymore some time before SU5, but now it seems to require attention once again.

(key bindings were checked and found to be correct)

When using the Stock Boeings (with a knob in the cockpit), the functionality is flawless.

The problem is even worse in the Stock Asobo A320, where the Autobrake knob has no functionality anymore at all.

Still, the TCA Quadrant was built to give an experience of great immersion for the A320(nx), so i would appreciate if a way for this to work again could be found.

Pre Sim Update 5, the Autobrakes via TCA Quadrant worked flawlessly.

### Expected behavior

Knob on TCA Addon should dial in the Autobrake setting, Setting should be permanent, if nothing in Plane/flight altered.

### Steps to reproduce

1.) Spawn on Runway
2.) Set Autobrake to max
3.) Wait / Read something on the EFB
4.) Watch Button Light turn off and maybe back on later

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by crocket63**
Fixes #5516

## Summary of Changes

Longer delay to avoid retrigger. 
Drawback is you can't change autobrake setting for 1.5s after you first hit a button.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check that all autobrake modes (except MAX in flight) can be armed when clicking buttons / using key bindings / using thrustmaster TCA quadrant.
Check that any armed mode won't disarm by itself after some time be it seconds or minutes (unless it's max mode self disarming after 10s airborne)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ErikNL80** [comment]
Did a test flight from ESGG gate 15 to EKCH gate F96.
- Started the flight cold and dark at the gate
- After engines start set t/o config and autobrake test, everything works as intended [OK]
- Set autobrake to MAX [OK]
- Before take-off check autobrake MAX still illuminated [OK]
- After take-off autobrake automatically disengages, manually put TCA knob to disarm [OK]
- On descent set autobrake to MED [OK]
- Changed it to LOW/MED and tried MAX (not possible in flight) [OK]
- Before touchdown check autobrake MED still illuminated [OK]
- After touchdown and roll-out manual braking disarms autobrake [OK]
- Manually put TCA knob to disarm [OK]

Overall conclusion: everything works as it should! Could not spot any disconnect!

**Comment by crocket63** [comment]
I don't like too much when I don't know why it works though...  Anyone have spotted what's the difference in how key events are coming to the sim? 
1,5 second feels long...

**Review by 2hwk — APPROVED** [review]

**Comment by ErikNL80** [comment]
> I don't like too much when I don't know why it works though... Anyone have spotted what's the difference in how key events are coming to the sim?
> 1,5 second feels long...

With the TCA I do not have a 1,5sec. delay on the buttons. Seems to be reacting very instantly and stable.

**Comment by crocket63** [comment]
> > I don't like too much when I don't know why it works though... Anyone have spotted what's the difference in how key events are coming to the sim?
> > 1,5 second feels long...
> 
> With the TCA I do not have a 1,5sec. delay on the buttons. Seems to be reacting very instantly and stable.

Mentioned delay is not reaction to first input which is instant. It's the delay it takes the sim to first send that first input, then wait a delay, then it constantly send the input.

**Comment by ewold** [comment]
Quality Assurance Tester/Trainee Report

Discord: E-wold#8195
Object of testing: #5584 
Tier of Testing: 1
Date: 09/08/2021

Testing Process: Spawned C+D , did a flight from LOWI to ESVA. 

Negatives N.A
Testing Results: Passed
Autobrake MAX when taxiing, didnt turn off halfway taxi (/) 
Autobrake came off after Liftoff
Selecting in flight LOW/MED worked, MAX didnt go on (/)
On landing used MED Brakes, turned off when pressing brake. 
Will do  a run with hotas buttons assigned today if i can find the bindings. 

Conclusions: Worked as expected

**Pull request merged**
