### PR TITLE
feat: incorporate new model changes

### PR DESCRIPTION
**Pull request by pepperoni505**
## Summary of Changes

In sim update 2, Asobo updated the interior model and I think the exterior, so I included both. This works with the wiper changes after renaming some nodes and splitting animations.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

* Check speed placard is not overlayed with another one from the default A320
* Check that BRK FAN button has a normal cursor and says `(Inop.)`

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
We need to correct the speed placard texture too

**Comment by Benjozork** [comment]
And add an inop. label to the brake fan for now

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
Works good, tested it myself

**Comment by tyler58546** [comment]
This PR is missing the model changes from #934 and #2172

**Comment by pepperoni505** [comment]
@tyler58546 Would you mind making a new PR adding those changes?

**Pull request merged**
