### PR TITLE
Improved engine startup and spool up sound, added cabin wind

### PR DESCRIPTION
**Pull request by hotshotp**
## Summary of Changes

Hello, I have been tweaking the startup for a long time recently to create something nearly perfect. Here are the changes for the PR.

On the exterior, the fuel flow introduction sound is a lot bassier like in the references section

On the Interior, the fuel flow sound has a different pitch curve + a quieter end to it so the cutoff doesn't seem so abrupt, should be more like the video in references

Made the interior initial spool up bassier and less digitized and pleasant.

I also added a different sound for the wind in the cabin than the cockpit since the wind in the cabin is more muffled due to it not hitting the front of the plane head on like in the cockpit.

## References

https://www.youtube.com/watch?v=Ulq4-SfOIlk exterior
https://www.youtube.com/watch?v=i3y6F2zVD5Q interior

## Additional context

Please tell me if you find any pops or clicks, i tried to remove most of them but if I missed some please tell me.

Discord username (if different from GitHub):
Boris#9134

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
Please add a proper title

**Comment by hotshotp** [comment]
> Please add a proper title 

I could have sworn I added one before but guess not. Fixes now

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: ChristopherXie#3904
Date of testing: Current date 12/07/2020
Version of the sim: 1.11.6.0
PR Tested: #2280 
Object of test: Sounds 

Testing technique: Entered the sim to test the PR
Steps you've made to test the Pull Request:
1. Spawned cold and dark at CYYZ and started the engines
2. Taxied to 33R and did a TOGA takeoff
3. Slewed to fl350 and listened to wind sounds in cabin and cockpit, and external sounds too
4. Landed on runway 24L and turned off the engines, restarted them to check for the new external startup
5.

Flight notes (If required):

Issues (If Any): No audio pops or clicks
Overall Rating: Good
Conclusions of the testing: Always a joy to QA your PRs. What I did find was that the wind in the cockpit was extremely loud, a bit too overpowering IMO, not sure if its true to life or not. Loved the spool up! Great job Boris, excited for the next!

**Comment by hotshotp** [comment]
No changelog needed, just changing already existing sounds

**Comment by myselfaaryan** [comment]
Category: QA Tester
Name: myselfaaryan#0001
Date of testing: Current date 08/12/2000
Version of the sim: 1.11.6.0
PR Tested: #2280 
Object of test: To Test the New Sounds

Testing technique: Quick Circuit
Steps you've made to test the Pull Request:
1. Spawn at Gate C/D
2. Startup Engines
3. Listen Spool & Startup of Both Engines Exterior & Interior
4. Take Off
5. Switch to Cabin for Wind Sounds

Flight notes (If required): N/A

Issues (If Any): N/A
Overall Rating: Good
Conclusions of the testing: Works Great! Always Love the Sound Improvements, Great Job 🎉

**Pull request merged**
