### PR TITLE
docs: license switch

### PR DESCRIPTION
**Pull request by wpine215**

### CODE REVIEW

**Comment by beheh** [comment]
I am not a layer. However, as personal preference, I would suggest move the `MIT License` line below for clarity, and have a clearer preamble. You could also move the MSFS text to the bottom.

```
Different licenses apply to parts of this repository. The license below applies to the entire repository EXCEPT for the top-level "src" directory, which has its own, compatible license.

MIT License

<Copyright>

<Rest of license text>

Microsoft Flight Simulator © Microsoft Corporation. The FlyByWire Simulations A32NX was created under Microsoft's "Game Content Usage Rules" using assets from Microsoft Flight Simulator, and it is not endorsed by or affiliated with Microsoft.
```

Otherwise you might read "MIT License" and stop reading. It's also not great practice to pull apart the original license template.

**Comment by wpine215** [comment]
> 
> 
> I am not a layer. However, as personal preference, I would suggest move the `MIT License` line below for clarity, and have a clearer preamble. You could also move the MSFS text to the bottom.
> 
> ```
> Different licenses apply to parts of this repository. The license below
> applies to the entire repository EXCEPT for the top-level "src" directory,
> which has its own, compatible license.
> 
> MIT License
> 
> <Copyright>
> 
> <Rest of license text>
> 
> Microsoft Flight Simulator © Microsoft Corporation. The FlyByWire Simulations
> A32NX was created under Microsoft's "Game Content Usage Rules" using assets
> from Microsoft Flight Simulator, and it is not endorsed by or affiliated with
> Microsoft.
> ```
> 
> Otherwise you might read "MIT License" and stop reading. It's also not great practice to pull apart the original license template.

Included these changes

**Comment by davidwalschots** [comment]
Probably want to write. As lawyers might otherwise claim only the directory is LGPL, not the content.

> Different licenses apply to parts of this repository. The license below
applies to the entire repository EXCEPT for the top-level "src" directory and its content,
which has its own, compatible license.

**Comment by Benjozork** [comment]
Need to figure out who we have to ask for permission to license `src/` under LGPL. Should not be a ton of people.

**Review by aguther — APPROVED** [review]

**Review by davidwalschots — APPROVED** [review]

**Pull request closed without merging**
