### PR TITLE
feat: ptu sounds, engine sound enhancements, and some fixes

### PR DESCRIPTION
**Pull request by hotshotp**
## Summary of Changes

First the small things:

- Fixed AP disconnect being blaringly loud
- Added another power transfer/generator clunk sound to the pool of random ones
- Made gear door clunk more noticeable
- Fixed spoiler drag not audible

Now for the juice:

- For the engine startup, improved the initial, pre ignition bass. Up to around 25% ish N1, it should sound different, a lot more bassier and natural sounding. Also made the idle a bit more natural.
- The engine spool up from about 40% is better now, with a slightly different 40-50% sample and a whole new and improved takeoff whine and buzzsaw
- Added PTU sounds to other conditions than just engine start, specifically to running yellow elec pump on ground with no engines running
- Made the yellow pump change pitch dynamically with the displacement, with every ptu burst
- Improved the ptu sample on engine startup and is now using the correct logic
- Changed the flap sound to a better one

## References

I as always used real videos and engineer recordings to compare and sample, there are too many references to post here, and its mostly improving the current sounds with higher quality samples.

## Additional context

I am removing the wwise project from this repo to move it to another repo.

Another important note: the current yellow pump pitch dip speed is not that right, it is too slow because I am using a temporary simvar. When we get displacement/rpm from davy, we will be able to use that for a more realistic speed of the yellow pump dropping pitch.

Discord username (if different from GitHub):

boris#8008

## Testing instructions

Start cold and dark and check if you hear the new generator clunk when turning on ext pwr. 

After avionics fans have stabilized, turn on the yellow elec pump via the pushbutton on the overhead and go to the cabin. You should be able to hear a repeating ptu sound and a yellow electric pump dropping in pitch every burst. 

Go to the cockpit and check if its audible with the PTU in cockpit option enabled. Turn off yellow elec pump.

 Start up one engine. Listen that the PTU sound does not play (which is correct) - then turn the other engine master switch to on, and you will hear the PTU (this is now the correct logic). You should also be able to hear this with the PTU in cockpit option. Listen to the engine startup from cockpit and cabin and hear the new bass, and slightly improved idle. 

After both engines turned on, go to wingview and select flaps, and listen to new sound. On takeoff, spool up to 40-50% and listen to a slight improvement over the previous version. Spool up to takeoff thrust and listen to the new whine and buzzsaw. After rotation, listen to the sound of the gear clunk after selecting gear up, and notice how much more noticeable it is. Switch to exterior and make sure that it sounds good at the front and doesn't resonate too much.

Then at your discretion, test the spoiler drag sounds and the autopilot disconnect warning - both bugs should be fixed as mentioned in the PR.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by bouveng — APPROVED** [review]
LGTM!

**Comment by xZreai** [comment]
Non QA Team Member Report [Individual]

Discord: Cleon#5802
Object of testing: (#5796)
Tier of testing: N/A
Date: (09/09/2021)

Testing Process:
1. Loaded in C/D
2. Turned on batteries and turned on and checked EXT power sound
3. Turned on yellow pump and listened to PTU as directed in Testing instructions
4. Checked for PTU sound while starting engines
5. Checked flaps sounds
6. Set up MCDU and took off RWY 34L YSSY - Listened to new Engine 40-50% N1 sounds
7. Listened to Gear up sound on takeoff
8. Listened to new spoilers and AP disconnect sounds
9. Continued full flight to NZAA

Conclusions: All new sounds work as intended and sound great - AP disconnect sound is more pleasant and suitable, Flaps, Engine new buzzsaw sounds much better and nice, EXT power as well except for PTU - I am not able to get any PTU sounds in the wing view - only a long whine similar to cargo door sound

Testing Results: NOT PASSED 

Media: [Videos sent to Boris]

**Comment by hotshotp** [comment]
Very weird. Will take a look.

**Review by bouveng — APPROVED** [review]

**Comment by xZreai** [comment]
Non QA Team Member Report [Individual]

Discord: Cleon#5802
Object of testing: (#5796)
Tier of testing: N/A
Date: (10/09/2021)

Testing Process:

Loaded in C/D
Turned on batteries and turned on and checked EXT power sound
Turned on yellow pump and listened to PTU as directed in Testing instructions
Checked for PTU sound while starting engines
Checked flaps sounds
Set up MCDU and took off - Listened to new Engine 40-50% N1 sounds
Listened to Gear up sound on takeoff
Listened to new spoilers and AP disconnect sounds


Conclusions: All new sounds work as intended and sound great - AP disconnect sound is more pleasant and suitable, Flaps, Engine new buzzsaw sounds much better and nice, EXT power as well as PTU - PTU sounds work when the yellow elec pump is turned on, the sound does not play when only 1 engine is started [correct behaviour according to testing procedure] and PTU sounds are played when 2nd engine is started - Sounds also play in cockpit with PTU in cockpit option enabled

Testing Results: PASSED

Media: N/A

**Comment by Samueleonard** [comment]
Quality Assurance Tester Report

Discord: 1samueleonard1
Object of testing: (#5796 )
Tier of Testing: (1)
Date: (10/09/2021)

Testing Process: 
. started c+d
. powered up - listened to clunk
. started up - checked new ptu logic (did not check with efb setting on)
. listened to flap sounds from different angles (internal/external etc)
. spooled engines up and down
. took off - heard new whine + gear clunk
. tested spoiler drag
. tested ap disconnect

Negatives: n/a - ptu is now fixed
Testing Results: (Passed)

Conclusions: lgtm, i really like the new engine sounds particularly
Media: n/a

**Comment by davidnorfolk96** [comment]
Quality Assurance Trainee Report

Discord: !davidn123#0001
Object of testing: #5796
Tier of Testing: 2
Date: 10/09/2021

Testing Process: (Detail is needed)
Loaded up C&D at LGGW & tested the following;

Start cold and dark and check if you hear the new generator clunk when turning on ext pwr.-PASS

After avionics fans have stabilized, turn on the yellow elec pump via the pushbutton on the overhead and go to the cabin. You should be able to hear a repeating ptu sound and a yellow electric pump dropping in pitch every burst.-PASS

Go to the cockpit and check if its audible with the PTU in cockpit option enabled. Turn off yellow elec pump.-PASS

Start up one engine. Listen that the PTU sound does not play (which is correct) - then turn the other engine master switch to on, and you will hear the PTU (this is now the correct logic). You should also be able to hear this with the PTU in cockpit option. Listen to the engine startup from cockpit and cabin and hear the new bass, and slightly improved idle.-PASS

After both engines turned on, go to wingview and select flaps, and listen to new sound. On takeoff, spool up to 40-50% and listen to a slight improvement over the previous version. Spool up to takeoff thrust and listen to the new whine and buzzsaw. After rotation, listen to the sound of the gear clunk after selecting gear up, and notice how much more noticeable it is. Switch to exterior and make sure that it sounds good at the front and doesn't resonate too much.-PASS DO NOT CHANGE THESE PLS BORIS <3 

Then at your discretion, test the spoiler drag sounds and the autopilot disconnect warning - both bugs should be fixed as mentioned in the PR.-PASS



Negatives: No issues found 
Testing Results: Passed

Conclusions: All sounds work as intended, However i do feel the sound of the spoilers dragging in the air could be abit louder. They're abit quiet compared to IRL. Nice work my brother!

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5796
Tier of Testing: 1
Date: 10/09/2021

Testing Process:
- Loaded in cold and dark at Paro.
- Activated yellow elec pump and switched to cabin views, heard both the dog/PTU and yellow elec pump whine. After hearing a fair few references, this sounds insanely accurate.
- Enabled PTU audible in cockpit via EFB, PTU audible in cockpit although reduced.
- Started up engine number 1 and listened to engine start up in each camera view. - Sounds incredible as soon as starter switch is flicked, a much smoother start up but sounds a lot more realistic! No PTU heard, idle sounds lovely.
- Started engine number 2, sat in awe again. PTU heard during engine number 2 start up as expected. 
- Set flaps while in wing view, new sounds! - Sounds brill yet again. 
- Gave engines a few short power ups while parked.

- Lined up on the runway, full TOGA take off, switching between wing view and cockpit  while rolling and trying to stay on the runway. - The improvements for this are insane, buzzsaw sounds brilliant. 
- Observed gear sounds, loud clunk, very noticable and sounds a lot like references seen. 
- Spoiler drag sounds are quiet but noticable from wing views, autopilot disconnect sound tested and sounds much better, still loud enough to be very noticable but not quite as ear penetrating. 


Negatives: N/A
Testing Results: PASS 

Conclusions: No other issues noted, the A32NX somehow yet again sounds a million times better than before, great stuff!

**Pull request merged**
