### PR TITLE
fixed cabin wind leaking into cockpit

### PR DESCRIPTION
**Pull request by hotshotp**
## Summary of Changes

Yesterday I made a PR which made a new cabin wind sound. The cabin wind actually leaked into the cockpit which made everything too loud. Now the wind in cabin and cockpit is separate and should not leak.

## Additional context

Discord username (if different from GitHub):
Boris#9134

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: ChristopherXie#3904
Date of testing: Current date 12/08/2020
Version of the sim: Version the tester uses
PR Tested: #2289 
Object of test: Sounds, specifically the wind sound
Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request: Entered the sim 
1. Spawned on a runway and took off
2. Slewed to fl170-300 and listened for any attenuation leaks
3. 
4.
5.

Flight notes (If required): 

Issues (If Any): Wind sounds in the front of the wing in the cabin is louder than the rear. Will be added in the next PR stated by hotshotp/Boris
Overall Rating: Good
Conclusions of the testing: Wind sounds have been fixed, PR did its job!

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919
Date of testing: 12/8/2020
Version of the sim: 1.11.7.0
PR Tested: #2289 
Object of test: Cabin wind sound.

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request: Tried out
1. Spawned in C&D at kdca and slewed up to fl250 going 300kts
2. Went in wing view and back to cockpit view to look for any sound leaks. Found none.


Flight notes (If required):

Issues (If Any): Wind is louder in front of the wing than in the back of the wing.
Overall Rating: Good
Conclusions of the testing: Sounds good fixes bleeding issue. Keep up the good work juice master.

**Comment by Snapmatics** [comment]
Category: QA Tester
Name: Snapmatics#0001
Date of Testing: Current date 12/08/2020
The version of the Simulator: 1.11.7.0
PR Tested: #2289
The object of test: Wind Sound leaking in the cockpit (too loud)
Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request: Entered the sim

Spawned on a runway and took off
Slewed very high to see if the issue still exists
Flight notes (If required):

Issues (If Any): No problem regarding that PR; works as described!
Overall Rating: Good
Conclusions of the testing: Wind sounds have been fixed.

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#8145
Date of Testing: Current date 12/08/2020
The version of the Simulator: 1.11.7.0
PR Tested: #2289
The object of test: Wind Sound leaking in the cockpit (too loud)

Testing technique: Slewed to high alt and tested wind noises.

Steps you've made to test the Pull Request: 

Spawned into KDTW
Slewed to ~25,000 feet
Listened carefully.

Flight notes (If required):

Issues (If Any):
Overall Rating: Good
Conclusions of the testing: Fixes issues, thanks, and good work.

**Pull request merged**
