### PR TITLE
fix(mcdu): Weather request airports not changeable in flight (#3413)

### LINKED ISSUE #3413: [BUG] [AOC] Weather request airports not changeable in flight
**Mod Version**

Current Custom FBW 8th Feb 21, 8419210

**Describe the bug**

Dep and Arr field will turn green in the AOC METAR request page, when taking off. They are not editable

**To Reproduce**

1. Request METARs on ground (Havent tested another airport than Dep Arr)
2. Takeoff
3. Both airports turn green and are not editable

**Expected behavior**

They should stay blue and be able to be deleted or modified.
**NOTE:** Im used to IRL Thales MCDU. But I think this is the same with Honeywell

**Actual behavior**

Stays green 

**References**

image

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by SergeySoprykin**
Fixes #3413

## Summary of Changes

~Made departure and destination airports editable on MCDU Weather Request page.~
- [ ] Create array with Airports and type (fmgc auto populated or manually added)
- [ ] Add fmgc airports (DEP, ARR, ALTN) on init.
- [ ] Adjust handling to follow reference
The above tasks are done in #5137

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Actions:
1. Fill departure/arrival airports on INIT-A page
2. Go to Weather request page. MCDU MENU -> ATSU -> AOC MENU -> WX REQUEST
3. Clear departure and arrival airport codes
4. Exit and re-enter into Weather Request page
5. Change departure and arrival airport codes to any other airport codes
6. Exit and re-enter into Weather Request page
7. Press SEND*, wait for COMPANY MSG on ECAM display
8. Go to AOC MENU -> RECEIVED MESSAGES

Result:
1.
2. Departure and arrival airport codes are in blue color
3. The codes cleared
4. Departure and arrival airport codes are seen again in blue color
5. Changed.
6. Departure and arrival airport codes are seen again in blue color
7. 
8. Weather received for selected airport

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by SergeySoprykin** [comment]
Video from real aircraft. The airport are shown in blue.
https://www.youtube.com/watch?v=77g8NzBCXzA&ab_channel=JacquesZahar
Not sure about MCDU version...

**Comment by tracernz** [comment]
This is a nice QoL improvement. 👍 Can you edit the original message to add your reference?

I suspect the real MCDU would retain any changes even after you leave the page and come back, and only add the origin/destination when they are changed, but only guessing... You should try to check that on #pilot-feedback.

**Comment by DavidEGTE** [comment]
Category: QA Trial
Name: David#2177
Date of testing: 05/03/2021
Version of the sim: 1.13.17.0
PR Tested: #3450 
Tier of testing: 1

Changes to observe:
N/A

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. Spawned C&D at gate @ LFPG
2. Checklist for start-up aircraft
3. Followed steps as PULL instructions

Flight notes (When done a full flight):
N/A (flight can be done if needed)

Media:
N/A (but can be provided with a video for future review)

Issues (If Any): 
None

Steps to achieve the issue:
N/A

Overall Rating: Good
Conclusions of the testing: LGTM, works as described.

**Comment by Benjozork** [comment]
I will try to get pilots to check this

**Comment by MisterChocker** [comment]
Whats the status on this?

**Comment by Benjozork** [comment]
@SergeySoprykin ^

**Comment by Illuminati270** [comment]
> I will try to get pilots to check this

Hi Benzo. A320neo pilot here. The actual model is correct! Blue for manually inserted airports, green for FMGS-gathered airports (FROM/TO and ALTN)

**Comment by MisterChocker** [comment]
@SergeySoprykin Are you able to work with the statement from @Illuminati270 
If you have further questions please ask them!

@Illuminati270 
When you CLR a green marked airport, what does happen to it? Does it disappear? Does it only disappear until you "reload"/reaccess the page or is it permanently cleared of the page?

**Comment by Illuminati270** [comment]
@MisterChocker 

It is cleared permanently!

**Comment by MisterChocker** [comment]
@Illuminati270 I assume when I'll add the airport back it will be cyan?

**Comment by Illuminati270** [comment]
> @Illuminati270 I assume when I'll add the airport back it will be cyan?

Precisely!

**Comment by MisterChocker** [comment]
Closing since the author doesn't allow maintainers to push into his branches.
Therefore new pr: #5137

**Pull request closed without merging**
