### PR TITLE
[ND] Navigration display improvements

### LINKED ISSUE #2153: [BUG] Terrain ND mode not working
**Mod Version**
A320NX Master 2020-11-30T21:11:53+00:00

**Describe the bug**
Terrain mode not working

**To Reproduce**
1.Start on the runway
2.take off
3.Turn Terrain mode on

**Expected behavior**
Display colours for the terrain

**Actual behavior**
Nothing
Screenshot (54)

### PR DESCRIPTION
**Pull request by ilyeshammadi**
Fixes #2153 #1939

## Summary of Changes

**What has been done**
- [x] Fix Weather/Terrain radar conflicting 
- [x] Do not show **Mode Changed** when switching Radar Mode or enabling Weather/Terr Radar modes.
- [x] Add **TERR** label with cyan color.
- [x] Small changes to the front size of `GS` `TAS` and wind data to match real world ND
#### Description
- The weather terrain issue now should not be present. Terr will override and show on the display when the weather is selected.
- The **Mode Changed** text does not show anymore when weather/radar is enabled/disabled and weather radar mode changed.

## Screenshots (if necessary)

**QA please watch the video to get more context about the changes.**
https://youtu.be/1Ak1xF0cMyc

### Before
Screenshot 2020-12-04 195432

### After
Screenshot 2020-12-04 195235
Screenshot 2020-12-04 185921 (2)

## References

**TERR** label is present and in Cyan color.

## Additional context

Discord username (if different from GitHub): Union Araken#4083

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Snapmatics** [comment]
Do you even sleep bro? I feel like you are working on the project 24/7! 😂

**Comment by beheh** [comment]
When the Terrain is visible, the ND should show TERR in the bottom right (or at least not WX / WX+T):

image

**Comment by ilyeshammadi** [comment]
> When the Terrain is visible, the ND should show TERR in the bottom right (or at least not WX / WX+T):
> 
> image
> 
> It would also be good to have references for the other changes (documentation, footage...). The PR does not give any as-is (and neither do the linked issues).

I don't have references to the changes included. My plan was to have an IRL 320 pilot to confirm this changes.

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: Current date 04/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2218 
Object of test: ND Improvements

Testing technique: Full Flight on VATSIM Livestreamed
Steps you've made to test the Pull Request:
1. Spawned C&D at EBBR, set up aircraft with route, fuel planning etc
2. Departed EBBR, Wx on during climb and switching functions to see if any issues became apparent
3. Monitored during descent as I descended through cloud/weather linked to frequently updated METARS using unrealweather
4. Monitored as it pulled new METARS to see how the ND would change as the weather was updated
5. Landed EGCC

Flight notes (If required): None

Issues (If Any): No issues found
Overall Rating: Good
Conclusions of the testing: Worked as expected, thanks!

**Comment by beheh** [comment]
> My plan was to have an IRL 320 pilot to confirm this changes.

@Benjozork Could you please tag this as "Needs Accuracy Check"? (or whichever other tag is appropriate)

**Comment by ilyeshammadi** [comment]
@Benjozork I will suggest adding the IRL tag since I couldn't find a resource that confirms my changes. I hope a pilot can take a look. I've also made a [demo video](https://youtu.be/1Ak1xF0cMyc) to demo my changes

**Comment by ilyeshammadi** [comment]
@Benjozork @beheh 
Screenshot_20201205-013235_Discord

**Pull request merged**
