### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by patmack14**
This issue fixes a bug that was brought to my attention by BlueberryKing as a good first project to tackle.  The CRUISE page should NOT be viewable while on the ground at any time.  

Fixes #[6806]

## References

This issue was verified by danbw8 and PinataColada in the #pilot-feedback channel

## Additional context

PatM

## Testing instructions

Attempt to cycle to the CRUISE page in different stages of flight and ensure that it is only available at the proper times.  It should NOT be available at any point while on the ground but should be while in the air.  

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
You probably didn't mean to do this

**Comment by patmack14** [comment]
Yes this is the first time I have done a pull request.  I was currently
modifying it when you closed

**Comment by Benjozork** [comment]
You made it from experimental

**Comment by davidwalschots** [comment]
Your fork doesn't seem to have any branches with the changes you're describing here. Please ensure you have pushed the branch with your changes from your computer to GitHub. Thereafter, create a pull request from your newly created branch into `master`.

**Comment by patmack14** [comment]
Can this PR please be deleted and I will start a new one today that is
filled in properly?

Would like to ask a few questions so that I can better understand how this
works.

**Pull request closed without merging**
