### PR TITLE
feat: custom FCU font

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Added custom FCU font
    * ~The new font is only for the numbers, not the labels above them~

## Screenshots (if necessary)

image

## References

https://cdn.discordapp.com/attachments/758126266859388948/810248599946002462/P1020360.JPG
https://cdn.discordapp.com/attachments/758126266859388948/810248612147101706/P1020359.JPG
https://cdn.discordapp.com/attachments/758126266859388948/810248615343161354/P1020364.JPG

## Testing instructions

* Make sure the new font is accurate
* Make sure the decimal points behave as expected

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by GlitchedYT** [comment]
Category: QA Tester
Name: Glitched#0740
Date of testing: Current date 02/13/2021
Version of the sim: 1.12.13.0
PR Tested: #3515
Tier of testing: 2
Changes to observe: Added custom FCU font, the new font is only for the numbers, not the labels above them
(Insert the Summary of changes, in order to remind what is to test)

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned at runway at KJFK
2. Loaded flight from KJFK - KJFK
3. Did patterns around KJFK and changed to all different modes on FCU
4.
5.

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
Microsoft Flight Simulator Screenshot 2021 02 13 - 19 50 26 93
Microsoft Flight Simulator Screenshot 2021 02 13 - 19 50 49 35
Microsoft Flight Simulator Screenshot 2021 02 13 - 19 51 35 29
Microsoft Flight Simulator Screenshot 2021 02 13 - 19 52 09 64
Microsoft Flight Simulator Screenshot 2021 02 13 - 19 52 51 24
Microsoft Flight Simulator Screenshot 2021 02 13 - 19 53 17 02
Microsoft Flight Simulator Screenshot 2021 02 13 - 19 54 21 36
Screenshot 2021-02-13 195706

Issues (If Any): Write any issues
Steps to achieve the issue

Overall Rating: 
To be improved, "+/-" font only has the arrow on the left side of the "-"
Decimal points missing from HDG/TRK/LAT part of the FCU while in test mode.

Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3515
Tier of testing: 2
Changes to observe: New FCU font for numbers
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawn C&D at EDDP
2.) Turn on Bat. and ext. Pwr.
3.) Scrolled to FCU numbers (Image1) and QNH numbers (Image2)
4.) Switched to TRK mode (looks good) 
4.) Did ANN LT TEST (Image3)

Media:


Image1


Image2


Image3

Issues: 

- V/S "+" is a little short to the right side
- Decimal points missing from HDG/TRK/LAT while ANN LT TEST

Overall Rating: -

Conclusions of the testing: Needs to be improved

Hope this helps :-)

**Comment by tyler58546** [comment]
> Issues:
> * V/S "+" is a little short to the right side
>* Decimal points missing from HDG/TRK/LAT while ANN LT TEST

Fixed
image

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 14.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3515 
Tier of testing: 2

### Changes to observe: FCU Font changes

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on runway at VABB
2. Turned on lights to TEST mode
3. Screenshots compared with reference

### Issues (If Any): Alignment and size issues

### Media:

ALT and VS

As you can see, the upper image is the PR, lower is the reference, on side-by-side comparison. yellow arrows from left to right denote:
1. Space between ALT etc. text labels and the digits
2. LVL bracket alignment with the 4th digit of ALT value
3. Dot alignment with "L/" of the text label
4. + sign alignment with "CH" label

The red line on RHS basically confirms the size mismatch, on the PR it comes somewhere close to the halfway mark, on the reference it is closer to the 3/4th mark.

QNH comparison

Since the PR doesn't touch the text font I guess the circling can be ignored, but marking it, just in case. The alignment of the QNH value is more towards the right, when it should be aligned to the center

SPD

Similar observations for SPD panel, yellow arrows denote alignment references.

### Overall Rating: Needs improvement

### Conclusions of the testing: Not very sure if these issues (alignment) concern this PR (focusing on font improvement) but hope the observations and comparisons are helpful.

**Comment by tyler58546** [comment]
I made the numbers slightly bigger and found a new font for the labels.
image

The real font for the labels is Futura, which is not free. I found a free font called Poppins which is very similar so I am using that. Its not a perfect match, but I tried to align it as best I could.

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3515
Tier of testing: 2
Changes to observe: New FCU fonts and alignments
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power
3.) FCU at day (Image1)
4.) FCU at night (Image2)
5.) ANN LT Test (Image3)
6.) Compare to reference (Image4)


Media:


Image1


Image2


Image3


Image4

Issues: None

Overall Rating: Good

Conclusions of the testing: Everything is on point!

Hope this helps :-)

**Comment by sidnov** [comment]
@tyler58546 Amazing work on the quick fixes, very impressive!

A few things I noticed:

1. On researching a bit, I found few another free font "Glacial Indifference-Bold" which looks slightly more bolder.

image
image

or else, you can retain Poppins, with the bolder variant (semi-bold 600)

image

2. Can the '/' be chopped or tilted a bit more to match the line?

image

Apart from this, the previous issues are fixed pretty well. Great job once again!

(Hope I am not sounding nitpicky here, just trying to get it as close to perfect as possible 😄)

**Comment by sidnov** [comment]
I think you should retain Poppins, with a bolder variant. Was looking over it again and it is closer to reference.

**Comment by tyler58546** [comment]
> I think you should retain Poppins, with a bolder variant. Was looking over it again and it is closer to reference. 

Alright, I'll use that and see if I can do anything about the slash.

**Comment by tyler58546** [comment]
Done
image

**Comment by marcman86** [comment]
Awesome!

The line from LVL/CH to V/SFPA looks very close to the V. Als maybe the linewidth of those lines could be la liite thicker.

**Comment by tyler58546** [comment]
> The line from LVL/CH to V/SFPA looks very close to the V.

Yeah, I'm not sure what is causing that. The `V` should be closer to the `/` but there isn't any extra space on the `V` or `/` character. There's probably some advanced kerning settings somewhere but I'm not sure how to fix it.

> Also maybe the linewidth of those lines could be la little thicker.

I agree, I'll make them a bit thicker.

**Comment by marcman86** [comment]
Maybe push ALT,--LVL/CH--, a little to the left

**Comment by tyler58546** [comment]
image

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 15.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3515
Tier of testing: 2
Changes to observe: New FCU fonts and alignments
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power
3.) FCU at day
4.) FCU at night
5.) ANN LT Test
6.) Compare to reference (Image1)
7.) Played with all modes (Image2)

Media:


Image1


Image2

Issues: Level Off 0000 is a digid to the left.

Overall Rating: Good, just one bug.

Conclusions of the testing: Super close to reference. Just one thing.

Hope this helps :-)

**Comment by tyler58546** [comment]
> Issues: Level Off 0000 is a digid to the left.

Fixed

**Comment by marcman86** [comment]
Works now!

Awesome job Tayler!

**Comment by DarkOfNova** [comment]
> 
> 
> Works now!
> 
> Awesome job Tayler!

Tayler is amazing

**Comment by sidnov** [comment]
Awesome! Looks good to go!💯

**Comment by beheh** [comment]
> Yeah, I'm not sure what is causing that. The V should be closer to the / but there isn't any extra space on the V or / character. There's probably some advanced kerning settings somewhere but I'm not sure how to fix it.

For now you could also fix this in CSS with a negative letter-spacing (i.e. -2px or similar) in a <tspan> around the affected characters.

**Comment by beheh** [comment]
Not merging yet so @tyler58546 can respond, he may want to incorporate this.

**Comment by tyler58546** [comment]
> Not merging yet so @tyler58546 can respond, he may want to incorporate this.

I already figured something out but thanks for the suggestion.

**Comment by DFWSupertrooper** [comment]
Hey, I have Futura font family if it helps?  My work uses it as an official branding guideline.

**Comment by DFWSupertrooper** [comment]
> Hey, I have Futura font family if it helps? My work uses it as an official branding guideline. Just let me know and I'll logon from my work PC and attach the file.

Just in case it helps @tyler58546...here are the base fonts (no italic versions)...

[FuturaStd-CondensedBold.zip](https://github.com/flybywiresim/a32nx/files/5988916/FuturaStd-CondensedBold.zip)

**Pull request merged**
