### PR TITLE
feat(sound): ECAM buttons custom sound event

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes
Changed the wwise event for ECAM buttons to our custom one.

## Additional context

Discord username: Imenes

## Testing instructions
Check that all ECAM buttons now trigger the custom sound event.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by hotshotp — APPROVED** [review]
LGTM!

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5266
Tier of Testing: 1
Date: 04/07/2021

**Testing Process:**
1. Laoded up C&D
2. Tested all ECAM buttons 

**Negatives:** 
- Nitpicking: I guess you used IRL recordings for these buttons? There are two different sounds that are randomly played, a "click" and more of a "clunk". Personally I dont think the clunk sound fits to the type of button we have here (short travel, hard keystroke). 
**Testing Results:** Passed, as this PR only activated the sounds

**Comment by hotshotp** [comment]
> **Quality Assurance Tester**
> 
> Object of testing: #5266
> Tier of Testing: 1
> Date: 04/07/2021
> 
> **Testing Process:**
> 1. Laoded up C&D
> 2. Tested all ECAM buttons 
> 
> **Negatives:** 
> - Nitpicking: I guess you used IRL recordings for these buttons? There are two different sounds that are randomly played, a "click" and more of a "clunk". Personally I dont think the clunk sound fits to the type of button we have here (short travel, hard keystroke). 
> **Testing Results:** Passed, as this PR only activated the sounds

The IRL recordings are there indeed. Every time you press a button it will sound different, it does add variety for the click and clunk to be there rather than having it sound the same.

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5266
Tier of Testing: 1
Date: 05/07/2021

Testing Process: 

1. Spawned on runway
2. Pressed and tested every ECAM button

Negatives: N/A
Testing Results: Passed

Conclusions: The button sounds were improved from the previous!

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #5266 
Tier of Testing: 1
Date: 5/7/21

Testing Process: 
Loaded in and tried clicking on the buttons
Negatives: N/A
Testing Results: Passed

Conclusions: LGTM, should be ready for merge

**Pull request merged**
