### PR TITLE
fix: correct printer animation speed

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

- Changed printer animation speed to be closer to reality

## References

https://cdn.discordapp.com/attachments/747571985831297145/803079088318578778/video0.mp4

## Additional context

Changelog is not needed as this issue does not affect the stable version.

## Testing instructions

Ensure that the printer animation speed matches the reference.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by ErickSharp** [comment]
Category: QA Tester
Name: Erick [Z-6]#6484
Date of testing: Current date 25/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3174
Tier of testing: 1
Changes to observe: Speed of page printout

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawn in cold and dark at LFPG
2. Prepared cockpit and connected to ground power
3. Printed out WX Request and monitored print speed
4. Print speed is now slower, closely matching the reference that you gave! 

Flight notes (When done a full flight): None
Media: None
Issues (If Any): None
Steps to achieve the issue
None
Overall Rating: Good
Conclusions of the testing: Good PR that changes the print-speed. It very closely matches the reference that you provided in the description, good job!

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: Current date 25/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3174
Tier of testing: 1
Changes to observe: Printer Speed changes

Testing technique: Printed multiple pages over a short flight to check speed of printer
Steps you've made to test the Pull Request:
1. Spawned C&D, set up for flight and printed metar data out
2. During flight, re-requested Wx Data and printed those, checking short and long printouts
3. Monitored speed of printing

Flight notes (When done a full flight): N/A
Media: N/A
Issues (If Any): None
Steps to achieve the issue N/A

Overall Rating: Good
Conclusions of the testing: No issues, printer speed is much much better! Just need the really loud printing noises now!

**Comment by stescouse** [comment]
Category: QA Tester
Name: Discord User stescouse#7271
Date of testing: 25.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3174
Tier of testing: 1
Changes to observe: Speed of Printer test.

Testing technique: TryOut
Steps you've made to test the Pull Request:

1. Spawned C&D at SKBO
2. Printed out METAR weather observed speed of printing.
3. Printed out TAF weather observed speed of printing.
4. Requested TAF for Weather at LDDU and LFPG.


Flight notes (If required: none

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: Speed of printing more realistic now well done.

**Pull request merged**
