### PR TITLE
fix(misc): Change of default switch positions for RAM AIR, WX Mode, TCAS ALT RPTG and TCAS Threat

### LINKED ISSUE #3965: ATC/TCAS Panel Default Switch Positions
**Mod Version**
{
  "built": "2021-03-14T16:34:50+00:00",
  "ref": "fbw",
  "sha": "bb815b6684d344563b6d16ee2136f81d9b9ff7d8",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
Default spawning of aircraft has TCAS/Transponder switches in incorrect positions.

**To Reproduce**

1. Spawn aircraft C&D
2. Observe ATC/TCAS panel.
3.

**Expected behavior**
ATC panel switch positions for an IRL aircraft would have: 
ALT RPTG => ON
TCAS targets => ALL or ABV

**Actual behavior**
ALT RPTG set to Off by default and TCAS targets set as THRT only.

**References**
Real world operation of Airbus A3xx family.

**Additional context**
SOPs rarely require changing these two values, with the exception of during flight in the climb ABV may be selected for TCAS or BLW during the descent. 

Was this working before/when did the issue start occurring? N/A

Is this a problem in the vanilla unmodded game? Yes.

Discord username (if different from GitHub): AirbusA320Pro

### PR DESCRIPTION
**Pull request by tshomas**
Fixes #3965 

## Summary of Changes
Fixes the default loading positions of Pushbutton RAM AIR, WX Radar Mode, TCAS ALT RPTG and TCAS threat selector by editing the FLT files.

RAM AIR - Changed from ON with no light to OFF with no light, guard remains on. (All FLT files)
A32NX_AIRCOND_RAMAIR_TOGGLE=0

WX Radar Mode - Changed from WX to WX+T. (All FLT files)
XMLVAR_A320_WEATHERRADAR_MODE = 1

TCAS ALT RPTG - Added code into the xml of the ATC panel to repair the original missing call from the sim variables, FLT files were already trying to set it to on, but this missing code wasn't there.
Used: https://github.com/flybywiresim/a32nx/blob/2a0dfd9b78a87127ee71438dc214c1d7286bf230/docs/i-vars.md as found by Saschl#9432

TCAS Threat Selector - Changed from THRT to ABV. (FLT files from Cold and Dark until Cruise)
TCAS Threat Selector - Changed from THRT to BLW. (FLT files from Cruise to Landing)
A32NX_SWITCH_TCAS_TRAFFIC_POSITION = 2 (for ABV)
A32NX_SWITCH_TCAS_TRAFFIC_POSITION = 3 (for BLW)

## References

RAM AIR
RamAir1
RamAir2

WX Radar MODE
WXRadar1
WXRadar2

TCAS
TCAS1
TCAS2

## Additional context
RAM AIR is only on for emergency use only, and should not be on in normal operation.

WX Mode is not defined for selections in manuals, but only AS REQUIRED. However, to have a weather radar with a functioning Turbulence mode is expected to be left in that switch position by all crews, otherwise the effectiveness of the system is downgraded.

TCAS ALT RPTG, should be left on at all times to not allow the mistake of departing without the Mode C reporting altitude, is never turned off unless under unusual data corruption operations.

TCAS THRT, only explicitly told in Airline OMB (SOP manual) as has to be in ABV for cockpit setup. This is however taught as being ABV up until the cruise, as it shows targets you may be climbing into, and then switched to BLW when cruise established, as to allow the identification of aircraft below you for descent or possible emergency descent. This could also be substituted for ALL if we model off another airline operations, but either is better than it being left on THRT.

**Additional: This is my first real PR into the master, please be very cautious in case I have edited anything in by mistake, extra precaution required even for the small amount of changes done.**

Discord username (if different from GitHub): Shomas#2719

## Testing instructions
1) Load the aircraft in different situations, cold and dark, on runway, in cruise, airborne and approach.
2) Note position of overhead guarded switch RAM AIR, which should have a cover closed on it.
3) Open cover to check that RAM AIR pushbutton is in the OFF position.
4) Check WX radar panel that the mode WX+T is selected on the left hand dial.
5) Check TCAS panel that ALT RPTG is on.
5) Check TCAS panel that THRT switch, is in ABV if loaded on ground or in climb, and in BLW if loading in cruise or onwards to landing.

Notes: Early QA tests have shown that people aren’t aware of how to jump between different flight loading states, this can be done by creating a basic flight plan on the in game map and then using the toolbar at the top to jump to different stages of flight, such as taxi, runway, cruise etc etc 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by lukecologne — APPROVED** [review]

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 15/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3985 
Tier of testing: 1

Changes to observe:
Load the aircraft in different situations, cold and dark, on runway, in cruise, airborne and approach.
Note position of overhead guarded switch RAM AIR, which should have a cover closed on it.
Open cover to check that RAM AIR pushbutton is in the OFF position.
Check WX radar panel that the mode WX+T is selected on the left hand dial.
Check TCAS panel that ALT RPTG is on.
Check TCAS panel that THRT switch, is in ABV if loaded on ground or in climb, and in BLW if loading in cruise or onwards to landing.

Testing technique: Try-out as PR instructions

Steps you've made to test the Pull Request
1. 1st try C&D 
2. 2nd run on runway
1+2 checked RAM guard + TCAS

Flight notes (When done a full flight):
N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
Microsoft Flight Simulator Screenshot 2021 03 15 - 23 36 08 94
Load C&D
Microsoft Flight Simulator Screenshot 2021 03 15 - 23 41 26 04
Load on runway

Issues (If Any): Write any issues
N/A
Steps to achieve the issue:
N/A

Overall Rating: My POV, couldn't do in cruise, airborne and approach, as for me it doesn't make any sense if you can only (for the moment) load C&D or on RWY or occasionally 5000ft from a custom point of the map.

Conclusions of the testing: LGTM

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 16/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3985 
Tier of testing: 1
Changes to observe: Switch Positions
Steps you've made to test the Pull Request:
1. Loaded C&D EDDW Gate01
2. Checked switch and button positions - THRT ABV
3. Loaded runway EDDW RW27
4. Checked switch and button positions - THRT ABV
5. Loaded airborne 5000ft
6. Checked switch and button positions - THRT BLW
7. Loaded approach RW27
8. Checked switch and button positions - THRT BLW

Media:

Issues (If Any): - 

Overall Rating: LGTM

Conclusions of the testing: Buttons work as described. I didnt find a way to load into a cruise state though

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 17.3.2021
Version of the sim: 1.14.5.0
PR Tested: #3985
Tier of testing: 1
Changes to observe: TCAS, WX, and RAM AIR default position 
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
- RAM AIR: OFF, no lights, guard closed
- WX Radar Mode: WX+T
- TCAS ALT RPTG on
- TCAS Threat Selector: ABV

2.) Spawned on runway at EDDP
- RAM AIR: OFF, no lights, guard closed
- WX Radar Mode: WX+T
- TCAS ALT RPTG on
- TCAS Threat Selector: ABV

3.) Jumped to CRZ
- RAM AIR: OFF, no lights, guard closed
- WX Radar Mode: WX+T
- TCAS ALT RPTG on
- TCAS Threat Selector: BLW

5.) Jumped to APPR
- RAM AIR: OFF, no lights, guard closed
- WX Radar Mode: WX+T
- TCAS ALT RPTG on
- TCAS Threat Selector: BLW

Issues: -

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Comment by tracernz** [comment]
The Wx radar should not be on in apron.flt (cold and dark/gate) right?

**Comment by tshomas** [comment]
> The Wx radar should not be on in apron.flt (cold and dark/gate) right?

The actual radar system shouldn't be on no, but that’s outside this PR, I altered the mode setting in these changes to set WX+TURB as the default toggle position instead of just WX which it was before!

**Comment by tracernz** [comment]
> 
> 
> > The Wx radar should not be on in apron.flt (cold and dark/gate) right?
> 
> The actual radar system shouldn't be on no, but that’s outside this PR, I altered the mode setting in these changes to set WX+TURB as the default toggle position instead of just WX which it was before!

Sorry to bother you... I found the problem is actually only in the CFPM branch. The old ND directly set the Wx radar off itself during init 🤦. We deleted the old ND 😁 . We should set `XMLVAR_A320_WeatherRadar_Sys` to the appropriate state in each .flt file instead.

**Pull request merged**
