### PR TITLE
port Asobo changes from 1.8.3.0 for PFD Instruments

### PR DESCRIPTION
**Pull request by UncleClapton**
**Summary of Changes**

* Updates instrument files (where appropriate)
* Removes a ton of code for other aircraft. All of these files are loaded independently, and not used by the other aircraft. There is no need for us to maintain and hold onto this code really. 
* Introduce `A32NX_Avionics`, a package that holds customized Avionics classes.

### CODE REVIEW

**Comment by Benjozork** [comment]
Testing this on request of @UncleClapton

**Comment by Benjozork** [comment]
LGTM

**Comment by UncleClapton** [comment]
To QA: this one should be easy to test for the most part. Just make sure the PFD Altimeter, speedometer, and ILS overlay work as expected.

**Comment by hansmeller12345** [comment]
Everything works as it should! Good work!

**Pull request merged**
