### PR TITLE
feat: engine sound enhancements and other huge changes

### PR DESCRIPTION
**Pull request by hotshotp**
## Summary of Changes

In this PR I have reworked the engine sounds from idle to TOGA, in both exterior and interior settings.

improved the brake fan, in both ext and int.

added the yellow and blue elec hydraulic pump sounds - both are audible in the cabin mostly.

added new sounds to avionics fans, and added a shutdown to them.

added the sound of the ground service bus - every time you load in, you will hear a clunk and a small whine.

added TCAS and ROPS wwise events - these are not in yet, and you will not be able to hear them, these are for the developers to implement logic for them to be played.

## References

I do not have a specific reference, but I did get engineer and pilot feedback on those things that could be given, otherwise the sounds are just improved samples on already realistic existing ones.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Start cold and dark, listen for the whine in the background. Turn on external power and listen to new fans. Turn on brake fans and listen to new brake fans, they should be a lot more resonant now that we have two brake fans instead of just one. On the overhead, turn on the yellow electric pump with the pushbutton, or alternatively, call up the cargo truck and listen to when the door opens; the pump is mostly audible in cabin and outside. When engines have started pay attention to sounds when taxiing and taking off in interior and exterior. If possible, do a few flybys at different thrust levels. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by ImenesFBW — APPROVED** [review]
SGTM!

**Comment by Samueleonard** [comment]
Quality Assurance Tester Report

Discord: 1samueleonard1
Object of testing: (#5149)
Tier of Testing: (2)
Date: (18/06/2021)

Testing Process: 
 .loaded in C+D
 .powered up listened to new fans, powered down - EXTRACT PB still doesnt work (not part of this PR?)
. turned on brake fans, listened, turned off
. tested Y+B hydraulics
. started engines
. ran engines up + down

Negatives: seatbelt signs have changed? sound worse than before imo
Testing Results: (Passed)

Conclusions: sounds great, esp the hydraulics, good to have them in now. 1 question above but even with that, SGTM
Media: n/a

**Comment by dragold** [comment]
Category: QA Tester trainee
Name: Mr.Blank#0001
Date of testing:06/18/2021
The version of the sim: 1.17.3.0
PR Tested: #5149
Tier of testing: 2

Changes to observe:
-engine sounds from idle to TOGA, (exterior/interior)
-improved the brake fan(exterior/interior)
-added the yellow and blue elec hydraulic pump sounds(interior)
-sounds to avionics fans
-sound of the ground service bus - every time you load in, you will hear a clunk and a small whine.

Testing technique: Tryout, audio check --loaded in C+D

Methodology:
-Full SOP flight 
--Start cold and dark
--external power(Turn on/off)
--brake fans(Turn on/off)(exterior/interior)
--yellow electric pump (Turn on/off)
--call up the cargo truck for cargo doors
--Engines Sound(Startup, Taxi, Takeoff, Landing, Go around, Shut Down)(exterior/interior)
Route- OMDB/30L DCT DB707 DCT DB408 DCT VEKAL DCT NITRI DCT VEKOV DCT EGROP
DCT OBTOL DCT OMAA/31L

Negatives: NIL
Testing Results: Passed

Conclusions: All observations were as expected, However still suggest checking it in with a real-life pilot..., Best wishes

**Comment by hotshotp** [comment]
> Negatives: seatbelt signs have changed? sound worse than before imo


Didn't mention this because it was so small, but I did indeed change it and so many more people said the new one sounds better. The new one is a real recording while the old one is just a sine wave. Thanks for testing

**Comment by Hadi-1624** [comment]
Very excellent and exciting update. For those who use headphones you will notice the iconic powerful avionics fans come alive from all around you, as they were updated to a stereo output. IT is not a static stereo playback however, you can pan the camera and hear the sounds change according to camera movement the the position of the panels.
Big engine sound changes as well, both from interior and exterior sides; They sound quite more powerful now, more brighter and boris has made changes that has made them even closer to the signature of the CFM LEAP. The jet exhaust sounds much close to its real counterpart; do a flyby to hear them with its all glory.
Well done!

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5149
Tier of Testing: 2
Date: 18/06/2021

Testing Process:

1. Spawned C&D
2. While on the ground, tested: External Power, Avionic Fans, Ventilation System, Hydraulics System, Brake Fans, Hydraulic events called by Cargo Doors, Engine Startup, Taxi Sounds. Sounds were tested from Cockpit, Exterior, & Cabin.
3. Performed two circuits
4. While in air, tested: Engine Sounds in, Engine from CLB -> MCT -> TOGA, Fly by Sounds at different Thrust Levels. Sounds were tested from Cockpit, Exterior, & Cabin.
5. Afterwards Performed a Full Flight. Routing: KLAS/08L TRALR9 VERKN DCT PROMT Q88 CHESZ DCT DBL DCT LBF DCT OBH
DCT IOW DCT GIJ J146 PLAIN DCT DORET DCT JHW DCT MEMMS Q82 PONCT
JFUND2 KBOS/22L

Negatives: N/A
Testing Results: Passed

Conclusions: The sounds added and improved represent the A320NEO's sounds in the real world very well.
Media: N/A

**Comment by MapleNAV-TCASFAULT** [comment]
Category: Moderator at FBW
Name: 𝕄𝕒𝕡𝕝𝕖#3904
Date of testing: 06/18/2021
The version of the sim: 1.17.3.0
PR Tested: #5149
Tier of testing: 2

Changes to observe:
- AV fans
- Ground service bus
- Brake fans
- Hydraulic pumps
- improved brake fan

Testing technique: Spawning on a runway testing audio quality

Methodology:
- Spawned on runway and listened to interior and exterior spool up
- Took off and listened to approach flyby sounds (-3 degree glidepath with a/thr on at 140 sel) and takeoff at TOGA thrust
- Back on the ground, listened to hydraulic pumps startup and shutdown
- Spawned at a ramp cold and dark and heard the ground service bus with the 'whine' (no issues), turned on the elec pump and listened to exterior/interior startup and shutdown (also no problems)

NVIDIA SHADOWPLAY WAS ACTING UP TODAY SO I HAD TO USE OBS INSTEAD, EXCUSE MY STREAM OVERLAY AND ACTIVE WEBCAM

https://user-images.githubusercontent.com/72575144/122629361-5d0b0680-d08a-11eb-9b59-88d2e2103dce.mp4 Spoolup

https://user-images.githubusercontent.com/72575144/122629368-698f5f00-d08a-11eb-9bb4-3c4d55dcb8f2.mp4 Takeoff flyby

https://user-images.githubusercontent.com/72575144/122629376-76ac4e00-d08a-11eb-8a7a-b786eee5995b.mp4 Approach flyby

Negatives: NIL
Testing Results: Passed

Conclusions: Sounds are really good, probably the PR that fixed all the issues I previously had. As always, great job Boris!

**Comment by TheSledge-SLEJ** [comment]
Great flybys! Those green rims though...I fixed that on my version if anyone wants the file

**Comment by tracernz** [comment]
Wizz have PW1100s according to airfleets, so the green rims are about the only accurate thing about the engines here. 😛

**Comment by TheSledge-SLEJ** [comment]
Haha! But...they're LEAPs! Touché :) They offend my sensibilities so they gone for good! Whoever designed that colour scheme for the PWs should be shot #justsayin

**Comment by hotshotp** [comment]
> Wizz have PW1100s according to airfleets, so the green rims are about the only accurate thing about the engines here. 😛

Green rims are PW only xD

**Comment by hotshotp** [comment]
> Great flybys! Those green rims though...I fixed that on my version if anyone wants the file

It's just up to the livery makers, not that hard to fix, I'm just not doing it yet for this livery

**Comment by Amorisia** [comment]
Also got weird seat belt and non smoking signs sound. Worse than preivous version.

**Comment by hotshotp** [comment]
> Also got weird seat belt and non smoking signs sound. Worse than previous version.

Again I talked to multiple people and all preferred the new one. It is more punchy sounding and less flat. The only issue I can see is that it ends too quick, maybe I can try to extend that next update

**Comment by Amorisia** [comment]
> > Also got weird seat belt and non smoking signs sound. Worse than previous version.
> 
> Again I talked to multiple people and all preferred the new one. It is more punchy sounding and less flat. The only issue I can see is that it ends too quick, maybe I can try to extend that next update

Thanks for your answer. Yes seems that this is not a sound quality issue but as you said, it seems to end too quickly.  Also seems to be the same kind of issue with the four bips, ending too quickly, when starting batteries and external power. But yeah, better to confirm with real a320 pilots as I have not been in a real one for long.

**Comment by patbuser** [comment]
you probably are already aware of this video featuring the 4 ding sound when turning on the batteries. As a reference.
https://www.youtube.com/watch?v=ZiyR4juG1hE

**Pull request merged**
