### PR TITLE
[CDU] Fix dynamic error message shows old scratchpad clear

### LINKED ISSUE #1916: [BUG] MCDU duplicated input
**Mod Version**
 current master(2020/11/14)

**Describe the bug**

when i input some value(let's value1) to MCDU some page, and i change page and try to write some value, value 1 value still remain MCDU

**To Reproduce**

1. for example, insert VOR freq on RAD NAV page on MCDU
2. going to INIT page
3. try to write Cost Index but there is a value still remaining

i write vor freq on RAD NAV page and going to init

when i press 4 for change costindex but there still value remain on mcdu

**Expected behavior**

must no value remain on mcdu

**Actual behavior**

remain on mcdu

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #1916

## Summary of Changes

- After clearing messages like GPS PRIMARY, old scratchpad content no longer gets display.

_I created a function which gets called after user input is handled for 1-6L and 1-6R and clears the last user input cache if no error message is being displayed._

#### Faulty Behavior (before) _(I have forced the error message by turning off all 3 ADIRSs)_
| Action 1 | Message | Clear Button Used |
| ----- | ----- | ----- |
| Inserted CI 20 | image | image |

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MisterChocker** [comment]
This is ready to test.

**Comment by stevex77** [comment]
**Category:** QA Tester
**Name:** SteveX77 [Z+0!]#1407
**Date of testing:** 11/15/2020
**Version of the sim:** 1.10.11.0
**PR Tested:** #1946
**Object of test:** [CDU] Fix dynamic error message shows old scratchpad clear

**Testing technique:**
Type a new value to MCDU scratchpad after 1. previusly entered value and 2. error / other info message displayed.
No previously entered value should re-appear on scratchpad.

**Steps you've made to test the Pull Request:**
1. Spawn at the gate and power on ACFT
2. Try to type a new value after error / other message
3. Only newly entered value should be there

**Notes:**
I'm able to write to scratchpad even error message is displayed.
Unable to see what I'm writing (error still displayed), but after CLR newly entered value is displayed.
Not sure if this should be possible, so just commented here.

**Issues:**
No issues found, except bahavior describer in Notes above.

**Overall Rating:** GOOD
**Conclusions of the testing:** LGTM

**Comment by MisterChocker** [comment]
@stevex77 not sure if this is correct behavior, I will need docs on that. I'd like to address this in another pr tho.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by z0rgmeister** [comment]
Category: QA Tester
Name: z0rgmeister#8972
Date of testing: 15/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1946
Object of test: [CDU] Fix dynamic error message shows old scratchpad clear

Testing technique:
Enter values on scratchpad and verify they are still there after induced error message.

Steps you've made to test the Pull Request:

    Spawn on runway
    Typed into Scratchpad
    Forced Error Message by switching off all 3 ADIRS
    Press CLR, entered value still displayed after error message cleared
    Repeat and verify still functioning.

   Re-Tested typing during message display, still able to. Outside the scope of PR.
    

Notes:
None of note, as per above.
Issues:
None

Overall Rating: GOOD
Conclusions of the testing: LGTM

**Comment by MisterChocker** [comment]
@z0rgmeister thats what #1951 is for

**Pull request merged**
