### PR TITLE
feat(nd): fixed bearing markers on rose

### LINKED ISSUE #4071: small white triangles missing in ND ROSE modes
**Is your feature request related to a problem? Please describe.**
the are small fixed white triangles pointing towards 45, 90, 135, 180, 225, 270 and 315 degrees on the outside or ROSE modes on ND that are missing.

**Describe the feature you'd like to see implemented**

**References**
enclosing a pic with the references in red circles
ND ROSE triangles

**Additional context**

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #4071

## Summary of Changes

Add fixed markers at 45 degree angles on the ND rose displays (except 12 o'clock). I have made these the same size as the long graduations, per both of my references, but our graduation ticks are really not the right length... in general you can see our ND needs a lot of visual improvement..

## Screenshots (if necessary)

image

## References

https://www.youtube.com/watch?v=vL60msOxA3w
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Test ND rose modes (ILS, VOR, NAV) and ensure fixed triangle markers appear and stay fixed as the rose rotates.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by beheh** [comment]
The code looks fine, the question is just if we're happy with the visuals, but as you say the needs lots of improvement.

**Review by beheh — APPROVED** [review]

**Comment by tracernz** [comment]
> The code looks fine, the question is just if we're happy with the visuals, but as you say the needs lots of improvement.

I started looking at a bigger revamp of the SVG... I think I may do the low hanging fruit in a follow-up PR which will make it a lot closer to IRL, then the remainer can wait for whatever we decide to do with the ND in the long-term.

**Comment by MisterChocker** [comment]
Question (unrelated to the pr) the dots in the (from the ILS MODE) are aligned in a right angle to the rwy heading. Do we have recreated that already?

**Comment by tracernz** [comment]
I am going to close this, and open a PR making a range of small improvements to the ND.

**Pull request closed without merging**
