### PR TITLE
[Fix] Remove glow from tiller

### LINKED ISSUE #1350: [BUG] Modelling - Steering tiller glowing disconnect button
**Mod Version**

Dev version:
built: 2020-10-14T20:06:03+00:00
ref: refs/heads/master
sha: 3906ea82ef00d54f85387430444c583238144621
actor: Benjozork
event_name: push

**Describe the bug**

The steering tiller disconnect button glows at night. There's no ambient light coming from it, so I don't think this is intentional.

**To Reproduce**

1. Load up at night
2. Apply electrical power (batteries?)
3. Increase main panel and pedestal integral lighting
4. Look at steering tiller

**Expected behavior**

No glowing parts

**Actual behavior**

Steering tiller disconnect button glows.

**References**

No battery power:
image

Battery 1 and 2 on:
image

Main panel and pedestal integral lighting:
image
image
I don't think the button should be glowing...

**Additional context**

Was this working before/when did the issue start occurring?
Unsure

Is this a problem in the vanilla unmodded game?
Unsure

Discord username (if different from GitHub):
Eefoe#0570

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes #1350

## Summary of Changes

* Removes the glow from the steering tillers.
* This also removes the text integrated lighting, since the button model and text are in the same mesh. I don't know if the text should have integrated lighting anyways, so it would be nice if someone could comment on that.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Pleasure0102** [comment]
@lukecologne what you mean by model and text in the same mesh ? AFAIK the text is as decal, not the same mesh.

**Comment by lukecologne** [comment]
You can look at the model, normally it is like this, yes, but not on the tiller. That is why they made it so the whole tiller is glowing

**Comment by Pleasure0102** [comment]
yeah, i actually checke myself again, you are correct.. oh my god we really have to fix that when we can edit the model, but i think for now disabling glow is better than the weird glowing tiller model

**Comment by DarkOfNova** [comment]
> yeah, i actually checke myself again, you are correct.. oh my god we really have to fix that when we can edit the model, but i think for now disabling glow is better than the weird glowing tiller model

Agreed as it's inop anyway, no point in being an eye sore

**Comment by lukecologne** [comment]
Sure, i'll merge it then.

**Pull request merged**
