### PR TITLE
Basic airways support

### LINKED ISSUE #925: [REQUEST] Airways are not developped in the A320 FMGC FPLN
**Mod Version**

**Describe the bug**

Entering an airway in the A320 FMGC F-PLN is not functional: only the entry and the endpoint of the airway are displayed in the flightplan

**To Reproduce**

1. GOTO FMGC F-PLN page
2. Select a route using airway from a waypoint
3. Enter VIA / TO
4. GOTO F-PLN Page

**Expected behavior**

When entering an airway, all the waypoints between the entry point and the endpoint of the airway should be added in the flightplan list

**Actual behavior**

Only the entry point and the endpoint of the airway are displayed in the flightplan and the intermediate points do not appear

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by Lessar277**
Fixes #925 
## Summary of Changes
This PR adds basic (crude) airways support to the FMS. Needs further refinement in terms of performance (for long airways it takes up to 10-15 seconds) and Airways page layout (all airway waypoints are visible in that page, they should not be visible there).

## Screenshots (if necessary)
https://streamable.com/vkvpty

## Additional context
This is a basic port of the changes done by the WorkingTitle team to their CJ4. Solves a big issue with the current navigation, but requires further work for polish. I am not a programmer, so I will leave performance and layout optimizations to others more experienced than myself.

All credit goes to the WorkingTitle team, I received their permission to port these changes.

Discord username (if different from GitHub): Lessar27#1112

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by wined2310** [comment]
I've tested it successfully on two flights and want to say thank you! 
Works as described

**Comment by Lessar277** [comment]
Marked this as ready for review, as I think it solves a big issue but I do not have the time nor the knowledge to carry on with further optimisations. The initial two big issues (performance when loading an airway and airways from waypoint page layout after the waypoints are loaded) will need a separate PR.

**Comment by armankir** [comment]
**Name:** @Arman#8602
**Date of testing:** 19/10/2020
**Version of the sim:** 1.9.5.0
**PR Tested:** #1435 

**Testing technique:** Cold Dark, imputing multiple airways in different airports.

**Steps you've made to test the Pull Request:** 

1. Loaded into the sim.
2. Made a flight plan with airways using Navigraph.
3. Attempted inputting complete Flightplan with Airways.
4. Attempted to fly those airways.

**Overall Rating:** This is where it's interesting, this PR is great, but at a cost. I had to sit through 21 seconds before my airway loaded (timed using Chrono) and there were a lot of fixes needed besides that. It does do the job of creating airways, and for that, I have to give it credit. 

If someone with the skill could fix up this PR, it would definitely be one of the best improvements of the month to the A20N.

**Conclusions of the testing:** _Ready to merge, but needs many additional changes and fixes._

**Comment by wined2310** [comment]
can we please merge this?
The inconvinience of delay only applies to those using the Airway feature and has no negative effect to anyone not using it.
It is such a great PR, too good to not use it at all till it is polished

**Comment by ChruutvoLuzi** [comment]
Name: ChruutvoLuzi | SD-PB.ch#8902 (!--Not a QA Tester--!)
Date of testing: 19/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1435

Testing technique: Started C&D, made a flight on my daily routine from ESGG to ESSA

Steps you've made to test the Pull Request:

- Started Cold and Dark
- Filled out the Flightplan in the mcdu

Overall Rating: Finally fixes the issue with the airways, which made it a pain entering every singel waypoint, altough it needs some improvements (as stated by the creator: it shouldnt show each waypoint on the airways page)
Processing was flawless (loaded 4 Waypoints on Airway N873 almost instantly)

Conclusions of the testing: Despite the few minor issues, a huge improvement

**Comment by Benjozork** [comment]
@wined2310, our standard QA process has to complete before merge unless it's a critical fix.

**Comment by ImenesFBW** [comment]
This seems to not work for me when using the navigraph navdata. Thought I should mention as a lot of people who are interested in this PR might be using navigraph navdata.

**Comment by Lessar277** [comment]
Does no route work for you when using Navigraph or a select few? Do those routes work on default navdata but not on Navigraph? I tested on Navigraph and almost forgot to delete Navigraph and check if it works with the default navdata. I did eventually check both.

I am aware that some of the routes do not work (not sure why), both with default and with Navigraph, but I crosschecked with the WorkingTitle implementation (their initial one, not the improved one) and in each case it did not work for them either. I believe they did refine this further, as stated in my PR, It's likely that  #1460 will further fix these issues.

Does it give out any errors in the MCDU or what is the exact behavior? I set an error message when `insertWaypointsAlongAirway `fails to show NOT ON AIRWAY in the MCDU, because the error messages of `insertWaypointsAlongAirway` were cryptic. But that message can be removed when debugging. If that message appears, the worst case scenario is that the user will need to revert to using the workaround that they have to use now, which is entering waypoints manually.

**Comment by ImenesFBW** [comment]
Hey @Lessar277 I edited my msg above after discussing this with the author of #1460 there are problems if the waypoints are VORs like in the route above, it did not work both with default data or navigraph

**Comment by Lessar277** [comment]
Closing PR, as #1460 fixes a lot more issues way faster than what I imagined when opening this PR.

**Pull request closed without merging**
