### PR TITLE
feat: glass reflections and dust

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Added glass reflections and dust (credit to @MoreRightRudder for the textures)

## Screenshots (if necessary)

image

## References

image
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Observe the glass and look for any issues.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 1/27/2020
Version of the sim: 1.12.13.0
PR Tested: #3204 
Tier of testing: 1
Changes to observe: Added glass reflections and dust


Testing technique: Tried out
Steps you've made to test the Pull Request:
1. Spawned in C&D at KDEN
2. Started the plane and looked at cockpit screens for any errors.


Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.



image

Issues (If Any): 


Overall Rating: To be improved.
Conclusions of the testing: I am so excited to see this be implemented great work. I did notice that every display except the fcu had this reflectivity/scratch effect. I feel that the fcu should also have this. I think the reflectivity is barely seen so I think that should be increased.

**Comment by St54Kevin** [comment]
Just tested it. I really like the dust but I cant see refelctions. Are those in?

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: ChristopherXie #3904
Date of testing: Current date 27/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3204 
Tier of testing: 1
Changes to observe: Reflections, dust and smudges on all glass displays

Testing technique: Spawning on runway
Steps you've made to test the Pull Request:
1. Spawned on a runway at CYYZ
2. Looked at all glass displays comparing it with the references looking at them at different angles and changing the brightness of them too.
3. changed the time to night to make sure no weird glitches are seen

Flight notes (When done a full flight):

Media: Identical results as awemeter's screenshots

Issues (If Any): Reflections are close to none

Overall Rating: Good
Conclusions of the testing: The smudges and dust on the displays defo adds depth to the displays. But one thing that I find off is that the displays should have a darker tint of purple and they seem dull still as if they're missing reflections. Other than that, I like it, and i'm excited to see this in the upcoming dev versions.

**Comment by Awemeter** [comment]
> Just tested it. I really like the dust but I cant see refelctions. Are those in? 

The reflection is there but it is close to non. It only reflects white lines of light and does not represent how it looks in real life. If you look at the reference picture it reflects the whole caption in 4k UHD

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#5297
Date of testing: 1/27/2021
Version of the sim: 1.12.13.0
PR Tested: #3204
Tier of testing: 1
Changes to observe: Reflections on glass displays and (dirt effect on screens?) 

Testing technique: C&D at DTW, full daylight.
Steps you've made to test the Pull Request:

Spawned in KDTW
Full daylight, clear skies (12 PM)

Media: At request, Awemeter already sent good screenshots.

Issues (If Any): Reflections are super dull and almost non-existent, need to really be amped up, currently unrealistic.

Overall Rating: TBI
Conclusions of the testing: The reflections seem really dull and almost non-existent, need to be notched up IMO. But good work. Can reload and send SS at request.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 2.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3204 
Tier of testing: 1
Changes to observe:

Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Loaded The Aircraft in the Hangar => no pink screens anymore
2. Loaded the Aircraft in the World
3. Checked if all Displays have the effect applied
4. Checked different Times and Weather Conditions

Media:

CAVOK
Microsoft Flight Simulator Screenshot 2021 02 02 - 20 54 41 07

Few
Microsoft Flight Simulator Screenshot 2021 02 02 - 20 54 59 60
Microsoft Flight Simulator Screenshot 2021 02 02 - 20 58 49 100

Overcast
Microsoft Flight Simulator Screenshot 2021 02 02 - 20 55 10 93




Issues (If Any): The Reflections do not actually reflect the cockpit but straight up see through it, i believe thats a non fixable issue for now?
Overall Rating: If fixable= To be improved, if not, good but needs decision from Maintainers
Conclusions of the testing: Works partially as described see other infos above

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#5297
Date of testing: 2/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3204
Tier of testing: 1
Changes to observe: Reflections on glass displays and dust effect (Second test)

Testing technique: C&D at NZQN
Steps you've made to test the Pull Request:

**Spawned in NZQN WITHOUT reflections:**

Microsoft Flight Simulator Screenshot 2021 02 02 - 15 42 30 71
Microsoft Flight Simulator Screenshot 2021 02 02 - 15 42 48 25
Microsoft Flight Simulator Screenshot 2021 02 02 - 15 42 52 40


**Spawned in NZQN WITH reflections:**

Displays off:

Microsoft Flight Simulator Screenshot 2021 02 02 - 15 53 49 13
Microsoft Flight Simulator Screenshot 2021 02 02 - 15 54 05 68
Microsoft Flight Simulator Screenshot 2021 02 02 - 15 54 18 65


Displays on:

Microsoft Flight Simulator Screenshot 2021 02 02 - 15 55 05 78
Microsoft Flight Simulator Screenshot 2021 02 02 - 15 55 13 00
Microsoft Flight Simulator Screenshot 2021 02 02 - 15 55 43 29
Microsoft Flight Simulator Screenshot 2021 02 02 - 15 55 50 64
Microsoft Flight Simulator Screenshot 2021 02 02 - 15 56 03 07


Media: Above

Issues (If Any): Looks much better, reflections are directly from outside, no cockpit reflections. Example below:

Capture

Overall Rating: Good but Asoboed
Conclusions of the testing: Above we can see that @ChruutvoLuzi mentioned the reflections see straight through the cockpit, aka the reflections show the outside. I also have noticed this issue, but I believe it is an Asobo limitation so it should be up to developers. Other than that good work. No major noticeable FPS issues found on my end.

**Comment by tyler58546** [comment]
Wipes and fingerprints have been added and are now ready to test.

**Comment by wpine215** [comment]
merge merge merge

**Pull request merged**
