### PR TITLE
feat: registration decal setting

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Add an option to the EFB to disable the dynamic registration decal on the fuselage. The decal is generally not desirable for real world liveries that have a painted registration.

When reviewing, check the feat commit. The earlier ones are importing the Asobo files as-is, and reformatting them.

## Screenshots (if necessary)

image
image
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check that decal appears and disappears with the setting. Disable, then load a default aircraft and check it's unaffected.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Saschl — APPROVED** [review]
LGTM!

**Comment by marcman86** [comment]
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #6099
Tier of Testing: 1
Date: 30/10/2021

Testing Process:
- Spawned A32NX C&D at EDDP 
- Checked EFB > Tail number was disabled by default
- Enabled tail number > shows number
- Disabled tail number, spawned with the 747 > tail number was shown (uneffected from A32NX setting)

Negatives: -

Testing Results: Passed
Conclusions: Works for me

Hope this helps :-)

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #6099
Tier of Testing: 1
Date: 31.10.2021

Testing Process: 
c&d at gate - just turning on flyPad - switching "enabled"/"disabled" and confirming in external view. 

Negatives: none 

Testing Results: passed

Works as expected. 

PS: Doesn't do anything of course for liveries where this is already deactivated. :)

**Comment by tracernz** [comment]
> PS: Doesn't do anything of course for liveries where this is already deactivated. :)

The intent is that liveries should not need to ship a panel.cfg, so they don't break each time we change that. ;)

**Comment by bouveng** [comment]
> The intent is that liveries should not need to ship a panel.cfg, so they don't break each time we change that. ;)

@tracernz That is something that should be communicated in the documentation for livery creation.

**Comment by John-UK** [comment]
Quality Assurance Tester Report

Discord:john P Maguire#9027
Object of testing: #6099
Tier of Testing: 1
Date: 2/11/2021

Testing Process:

Spawned A32NX on RW at EGJJ 
Checked EFB that DRD was disabled by default
Enabled DRD quit to main menu and changed the livery. DRD was again initialised as disabled.
Enabled DRD the work around black line to hide the registration was shown on the aircraft. 

Negatives: Nothing observed.

Testing Results: Passed
Conclusions: LGTM and far better for livery makers.

Media: 
Pic 1 DRD enabled. Black line is the covering graphic.
6099 enabled

PIC 2 DRD disabled lovely clean paintwork.
6099 disableed

**Pull request merged**
