### PR TITLE
MFD/ND Text position fixes

### LINKED ISSUE #533: Overall ND visual design issues
This is the master tracking issue for visual fidelity issues on the ND, things like fonts, size, positions, etc.

- [ ] text in top left and right should be flush with corner of screen
- [ ] compass headings numbers font too thicc
- [ ] the circle dashes are to long and too spread apart
- [x] compass should spin when coming out of alignment - https://github.com/flybywiresim/a32nx/pull/538
- ...

### PR DESCRIPTION
**Pull request by enesaydogan**
Partially addresses #533 

**Summary of Changes**

fixes= "text in top left and right should be flush with corner of screen"
Allings title to top ( ILS, VOR TEXT )

**Screenshots (if necessary)**

mfd1
mfd2
mfd3

**Additional context**

### CODE REVIEW

**Comment by AdenFlorian** [comment]
current master for comparison:
image

IRL:
image

image

**Comment by AdenFlorian** [comment]
Thanks for your PR! Here are some issues I'm seeing from comparing your screenshots to current master, and IRL:
1. All of the text on the top line should always be in line with eachother, but in your shots, the top left text is higher than the middle and top right text
2. IRL texts are very very close to the screen edges, but the texts in your shots still have a big gap

Is it not possible to get them any closer to the edge?

**Review by AdenFlorian — CHANGES_REQUESTED** [review]
requested changes are in above comment

**Comment by enesaydogan** [comment]
Thans for feedback. I made the changes you wanted.

mfd4
mfd5

**Comment by enesaydogan** [comment]
> Thanks for your PR! Here are some issues I'm seeing from comparing your screenshots to current master, and IRL:
> 
> 1. All of the text on the top line should always be in line with eachother, but in your shots, the top left text is higher than the middle and top right text
> 2. IRL texts are very very close to the screen edges, but the texts in your shots still have a big gap
> 
> Is it not possible to get them any closer to the edge?

I was afraid of broking stuff. I am new to github and programing. Night of learning, breaking and fixing later i was able to made the changes. Thanks for your help.

**Comment by camilo625** [comment]
Works as described, nice work!

**Review by AdenFlorian — APPROVED** [review]

**Comment by AdenFlorian** [comment]
looks great, thanks!

**Pull request merged**
