### PR TITLE
Cabin Interior emissive decal changes

### PR DESCRIPTION
**Pull request by waveform2k**
Changed the saturation and brightness of the emission decals to more closely reflect real counterparts.

**Summary of Changes**

Altered the color and saturation of the decal atlas to better mimic real life lighting of buttons, linings and text in low light cabin conditions.
Used https://www.youtube.com/watch?v=ZqQIf9MvhgE as video reference

**Screenshots (if necessary)**

Before
unknown
After
Screenshot 2020-09-23 032528
Screenshot 2020-09-23 032748
Screenshot 2020-09-23 032845

**Additional context**

Lit conditions
Screenshot 2020-09-23 034534
Screenshot 2020-09-23 034716
Screenshot 2020-09-23 034904
image
image

Thanks for additional help @DarkOfNova 

Discord username (if different from GitHub): Ram#0001

### CODE REVIEW

**Comment by NathanInnes** [comment]
On my phone rn and can't help notice that on the overhead, the buttons border light doesn't match the rest. May just be a mobile issue.
image

**Comment by rcavinash123** [comment]
Yes it is, i can also see it from my phone.

**Comment by waveform2k** [comment]
@NathanInnes fixed in the latest commit.
image

**Comment by nasjoh** [comment]
Looks amazing!

**Comment by NathanInnes** [comment]
You beautiful man. Looks great

**Comment by cakequest** [comment]
Looks great on the screenshots. Haven't had time to test it in the sim yet but will do soon. However, I did notice in your screenshots that the down arrow next to the gear lever doesn't seem to be illuminated:
93950664-c6a0f300-fd4c-11ea-853f-e54d6142a1c3

See reference photo I found online:
a9144cd3e4fc5ae7c9eb53adf3162fb9

**Comment by Noxleee** [comment]
Name: Discord Noxlee#7727
Date of testing: Current date 23/09/2020
Version of the sim: 1.8.3.0
PR Tested: #814 
Testing technique: Try-out method
Steps you've made to test the Pull Request:
1. Load up aircraft in EKCH on RW 22R
2. Look around if every decal is illuminated correctly
3. varied light conditions


Overall Rating: to be improved
Conclusions of the testing: everything is working as described, but the down arrow next to the gear lever is completely black (the white line around is missing), see screenshot
Microsoft Flight Simulator Screenshot 2020 09 23 - 11 44 05 73

**Comment by NathanInnes** [comment]
Tested and works well. The landing gear emissive part can't be changed unless you have access to the model/uv maps.

**Review by NathanInnes — APPROVED** [review]

**Comment by NathanInnes** [comment]
Tested and works as stated. Issue with the L/G lever area can't be solved without model/uv map.

**Comment by DarkOfNova** [comment]
> Looks great on the screenshots. Haven't had time to test it in the sim yet but will do soon. However, I did notice in your screenshots that the down arrow next to the gear lever doesn't seem to be illuminated:
> 93950664-c6a0f300-fd4c-11ea-853f-e54d6142a1c3
> 
> See reference photo I found online:
> a9144cd3e4fc5ae7c9eb53adf3162fb9

That's because it doesn't exist, the arrow is not there. I have it noted and it will be fixed when we have the models, currently I can't do anything about it, I've tried.

**Comment by Benjozork** [comment]
@Noxleee, I am pretty sure this issue existed before the PR.

**Comment by Noxleee** [comment]
Okay, I just saw it because it was mentioned before. So the rest works fine and looks really awesome!
Correction:
Overall rating: very good

**Review by UncleClapton — APPROVED** [review]

**Review by DoToAdventures — APPROVED** [review]

**Comment by ImenesFBW** [comment]
Name: Discord Imenes#8739
Date of testing: 23/09/2020
Version of the sim: 1.8.3.0
PR Tested: #814
Testing technique: Try-out method
Steps you've made to test the Pull Request:

Tested from c/d on a flight from LOWW - EDDP
Looked at different cameras and positions.
General impression trough the flight.

Overall Rating:  Very good !
Conclusions of the testing: Can't wait to see it in the master! Thank you for your work!

**Pull request merged**
