### PR TITLE
feat(hyd): Flap/slat system hydraulic integration

### PR DESCRIPTION
**Pull request by crocket63**
Fixes #[issue_no]

## Summary of Changes

Flap / Slat movement will use a simple model that will only allow movement if there is hydraulic pressure.

The model takes a flap/slat surface position command from SFCC1 and SFCC2 computers. An unresponsive SFCC will cause its corresponding hydraulic motor to stop.

Note that only one duplicated SFCC is simulated in this PR, actual dual SFCC implementation will follow in a separate dedicated PR.

Flaps/Slats speed is converted into hydraulic motor speeds using the actual 1:314.98 actuator arm to torque shaft ratio.

It reports an angle in Feedback Position Pickup Unit (FPPU) degrees.

This is a simple model but yet will handle partial pressure from two circuits, and should have correct flow consumptions.
Transients in flow and motors RPM are just simplified low pass filters.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Normal operation should be as before. Check the motion of flaps and slats has no glitch when it's moving.

When only blue pressure is available, only slats will deploy in around 35s.

When only yellow epump + ptu is present, full slat/flap deployment should be extremely slow (more than a minute).

When only GREEN and YELLOW engine pumps are active and blue epump disabled, Flaps should move close to full speed, slats should move at half speed.

When only GREEN engine pump is active and blue epump disabled, Flaps should move at half speed, slats should move at half speed.

When only YELLOW engine pump is active and blue epump disabled, Flaps should move at half speed, slats should not move.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by beheh — APPROVED** [review]
Looks good from what I can see, but keep in mind that I'm not extremely proficient in Rust.

Just one question: Is any of @davidwalschots `Aspect` work applicable to this PR here?

**Comment by davidwalschots** [comment]
No, this PR doesn't contain anything related to that area. So it's good to go from that side.

**Comment by mico975** [comment]
Quality Assurance Trainee Report

Discord          : mico#3145
Object of testing: #6010 
Tier of Testing  : 1
Date             : 30/01/2022

Testing Process: 
Listed are deployement speeds from up to full.

Normal operation should be as before. Check the motion of flaps and slats has no glitch when it's moving. - Full in 18s

When only blue pressure is available, only slats will deploy in around 35s. - Slats 33s, flaps no movement
 
When only yellow epump + ptu is present, full slat/flap deployment should be extremely slow (more than a minute). - Flaps first in 30s, full deployment in 48s. Maybe a bit quick?

When only GREEN and YELLOW engine pumps are active and blue epump disabled, Flaps should move close to full speed, slats should move at half speed. - Flaps in 16s, slats in 31s.

When only GREEN engine pump is active and blue epump disabled, Flaps should move at half speed, slats should move at half speed. - With PTU flaps 16, slats 31s. Without PTU flaps 31s, slats 30s.

When only YELLOW engine pump is active and blue epump disabled, Flaps should move at half speed, slats should not move. - With PTU flaps 16s, slats 31s. Without PTU flaps 31s, slats no movement.

Reverse movement is affected the same.

Negatives:       
Maybe epump+ptu is a bit quick, but nothing major.

Testing Results: 
Passed

Conclusions: 
LGTM

**Comment by D4rknessCodez** [comment]
### Quality Assurance Trainee Report

 Discord : Darkness🍁#7734
Object of testing: #6010
Tier of Testing : 1
Date : 01/02/2022

### Testing Process:
- Observed normal operations of flaps and slats before the start of testing
- Disabled all but the Blue pressure, slats deployed after 31 seconds
- Disabled all but the Yellow Elec pump and the PTU, it doesn't appear as there is movement. (See negatives)
- Disabled all but the Green and Yellow pumps, flaps were at full speed whereas the slats deployed after 30 seconds 
- Disabled all but the Green pump, Slats moved at half speed however the flaps were normal.
- Disabled all but the Yellow pump, slats did not move and the flaps moved at half speed

### Negatives:
1. I waited 3 minutes when i disabled all but the Yellow Elec pump and the PTU and nothing happened, there was no movement. This may be an issue from my end as it was working for mico but i am uncertain.
2. When i disabled all but the Green pump, the slats moved as they were intended however the flaps moved normally. I tried again and again however the issue still stayed prevalent.

### Testing Results:
Not Passed

###Conclusions:
Most of the features worked as intended except for those two in the negatives. I have no clue if this was due to user error or an issue on my side. Maybe we can get more input when someone else does a PR on this.

**Comment by crocket63** [comment]
> 
> ### Negatives:
> 1. I waited 3 minutes when i disabled all but the Yellow Elec pump and the PTU and nothing happened, there was no movement. This may be an issue from my end as it was working for mico but i am uncertain.
> 2. When i disabled all but the Green pump, the slats moved as they were intended however the flaps moved normally. I tried again and again however the issue still stayed prevalent.
> 

We checked and confirmed this was caused by misunderstanding of the yellow epump use (button illuminated = pump ON)

**Comment by D4rknessCodez** [comment]
Quality Assurance Trainee Report
Discord : Darkness🍁#7734
Object of testing: #6010
Tier of Testing : 1
Date : 02/02/2022

Testing Process:
**Corrected the user errors i made**
Issue 1: Made sure the PTU was on along with the yellow elec pump. Results were as intended
Issue 2: Made sure no pumps were on except for green (Yellow elec pump was on in my last test).

Negatives:
N/A

Testing Results:
Passed

Conclusions:
The last issues were caused by user error during tested and have been resolved thanks to davy. Amazing work and I think its ready to merge.

**Pull request merged**
