### PR TITLE
fix(efb): Use monospace font to render OFP on EFB.

### LINKED ISSUE #4057: Loadsheet / OFP does not use monospace font
**Mod Version**

master

**Describe the bug**

The loadsheet / OFP imported from simbrief is hard to read, because it is formatted for use with a monospace font, but it is displayed with a variable space font.

**To Reproduce**

1. Create a flight plan on simbrief
2. Load the flight plan in the EFB
3. Navigate to Dispatch / OFP and see variable spaced output

**Expected behavior**

The OFP should be shown with a monospace font.

**Actual behavior**

The OFP is shown with a variable space font

**References**

EFB Dispatch OFP before

**Additional context**

I have a fix ready to go, will create the pull request soon. This is my first issue and pull request.

Was this working before/when did the issue start occurring?
n/a

Is this a problem in the vanilla unmodded game?
n/a

Discord username (if different from GitHub): Chriskgk#4359

### PR DESCRIPTION
**Pull request by chkgk**
Fixes #4057 

## Summary of Changes

I have added the "font-mono" class to the container div holding the loadsheet. This causes it to show in monospace font as intended.

## Screenshots (if necessary)

Before
EFB Dispatch OFP before
After
EFB Dispatch OFP after

## References

n/a

## Additional context

This is my first proper issue / pull request combination. Please be kind :-)

Discord username (if different from GitHub): Chriskgk#4359

## Testing instructions

Check if the OFP imported from simbrief is correctly shown with monospace font.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by myselfaaryan — APPROVED** [review]
LGTM!

**Comment by myselfaaryan** [comment]
Merging immediately since its a small fix and the effects are known.

**Comment by brunocfalcao** [comment]
Awesome work, @chkgk !

**Review by tracernz — COMMENTED** [review]
Does it need a changelog? It’s never been in a released version.

**Comment by chkgk** [comment]
I did not now that a CHANGELOG entry is only added if the element changed was already included in a previous stable release. Feel free to remove it with any of the future EFB PRs. It is such a minor addition anyway (although it enhances usability tremendously in my opinion).

Maybe we should update Contributing.md accordingly. It currently says: "Ensure that you include a CHANGELOG with your PR". Could be rephrased to: "Ensure that you include a CHANGELOG with your PR if your change affects an element that was previously included in a stable release".

**Comment by tracernz** [comment]
> 
> 
> I did not now that a CHANGELOG entry is only added if the element changed was already included in a previous stable release. Feel free to remove it with any of the future EFB PRs. It is such a minor addition anyway (although it enhances usability tremendously in my opinion).
> 
> Maybe we should update Contributing.md accordingly. It currently says: "Ensure that you include a CHANGELOG with your PR". Could be rephrased to: "Ensure that you include a CHANGELOG with your PR if your change affects an element that was previously included in a stable release".

I'm kinda asking a question as I'm not entirely sure myself. I don't think it will hurt to leave this one anyway. :)

**Comment by bouveng** [comment]
Just a small FYI, #5102 addresses this issue again since this implementation really never worked as it should and other stronger `*` selectors overrode this class. Also put a proper` mono`-fontstack in place since tailwindcss font stack made little sense in Coherent GT context.

**Pull request merged**
