### PR TITLE
refactor: MCDU model behaviors into src

### PR DESCRIPTION
**Pull request by theomessin**
## Summary of Changes
MCDU model behaviors XML has been refactored into `src`. Functionality should be the same, code has been reduced by ~70%

## Additional context
This change will help @davidwalschots add electrical bus functionality to the two MCDUs.

Discord username (if different from GitHub): Theodore Messinezis#6029

## Testing instructions
Just make sure that both MCDUs buttons still work.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by St54Kevin** [comment]
"/" button and "OVFY" button not working

**Comment by Lucky38i** [comment]
Is this the same as in the mcdu-rewrite?

**Comment by theomessin** [comment]
@Lucky38i same idea, not the same code though - your one uses different H: events.

**Comment by theomessin** [comment]
Hey @davidwalschots, I don't have time to work on this, feel free to amend or close as needed.

**Comment by davidwalschots** [comment]
@St54Kevin I've fixed the arrows and `/`. OVFY isn't implemented yet as far as I know (#2959), so that button not working should be normal.

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 30/03/2021
Version of the sim: 1.14.6.0
PR Tested: #4045 
Tier of testing: 1
Changes to observe: MCDU buttons

**Steps you've made to test the Pull Request:**
1. Tested all buttons of the MCDU except OVFY

**Media:**
image
image


**Issues (If Any):** - 

**Conclusions of the testing:** LGTM. Everyt button works

**Comment by Matse08** [comment]
Category: QA Tester
Name: Matse#7454
Date of testing: 30.03.21
Version of the sim: 1.14.6.0
PR Tested: #4045
Tier of testing: 1
Changes to observe: MCDU changes


Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Checked the whole MCDU for bugs



Issues (If Any):

Overall Rating: Good
Conclusions of the testing: Nice one

**Review by davidwalschots — APPROVED** [review]

**Pull request merged**
