### PR TITLE
feat: ISIS brightness buttons push&hold #4736

### LINKED ISSUE #4184: ISIS brightness buttons should be push&hold
**Mod Version**

{
  "built": "2021-03-28T16:25:26+00:00",
  "ref": "merge",
  "sha": "b280541409b0d46dd7513703640de179ccfb2126",
  "actor": "Duncan10",
  "event_name": "manual"
}

**Describe the bug**

The + and - brightness buttons on the ISIS need to be clicked repeatedly.
image

**To Reproduce**

1. Load up the plane
2. Change ISIS brightness
3.

**Expected behavior**

You should be able to click and hold the two buttons like you are able to with the MCDU brightness buttons

**Actual behavior**

**References**

IRL experience

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #4184 #4736 #4794 

## Summary of Changes
Brightness buttons can now be held down to increase/decrease brightness (push and hold). As per issue, time taken to increase brightness to full from minimum is roughly 4 seconds.

## Screenshots (if necessary)

aBr61h3TRS

## References

See PR #4736 #4794 
See Issue #4184 

https://discord.com/channels/738864299392630914/758126266859388948/832179131152203806

## Additional context

Discord username (if different from GitHub): 2Cas#1022

## Testing instructions

1. In the self-test and altimeter views, use standby instrument's brightness push buttons to adjust the brightness of the display. 
2. Pressing and holding as well as single sharp presses should both work as expected.
3. Press the BUGS button. In this mode, the standby instrument's brightness push buttons should move the cursor that selects the heading/altitude bugs that are being adjusted by the altimeter knob. The brightness should not change. 
4. Use the integrated panel emissive knob to adjust the brightness of the panel lighting. The buttons should light up or stop emitting light as expected.
5. Attempt to break the brightness control by clicking on both buttons randomly. The brightness adjustment should continue working.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by davidwalschots — APPROVED** [review]

**Comment by TheSquirtingPantin** [comment]
Category: QA Tester
Name: Discord User Rémi#8871
Date of testing: Current date 13/05/2021
Version of the sim: V 1.15.8.0
PR Tested: #4736
Tier of testing: 1
Changes to observe: ISIS brightness adjustment

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. C/D at LFBO
2. Adjustment of ISIS brightness with push and hold method
3. Checked integrated lighting during night conditions. 
 
Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Good Job, brightness control working as expected. Tested in day and night condition with no issues (good integrated lighting logic)

**Comment by 2hwk** [comment]
> Category: QA Tester
> Name: Discord User Rémi#8871
> Date of testing: Current date 13/05/2021
> Version of the sim: V 1.15.8.0
> PR Tested: #4736
> Tier of testing: 1
> Changes to observe: ISIS brightness adjustment
> 
> Testing technique: Description of how you tested the Pull Request
> Steps you've made to test the Pull Request:
> 
> 1. C/D at LFBO
> 2. Adjustment of ISIS brightness with push and hold method
> 3. Checked integrated lighting during night conditions.
> 
> Flight notes (When done a full flight): N/A
> 
> Media: N/A
> 
> Issues (If Any): None
> 
> Overall Rating: Good
> Conclusions of the testing: Good Job, brightness control working as expected. Tested in day and night condition with no issues (good integrated lighting logic)
> 
> Quick logic question: During the ISIS init phase, if we pushed once on BUGS then try to adjust the brigthness this is not working. Is it an expected behavior ?

It isn't but this is a bug with the bugs page (hah) and not related to this PR.

**Comment by dragold** [comment]
Category: QA Tester
Name: Mr.Blank#2638
Date of testing: Current date 13/05/2021
Version of the sim: 1.15.10.0
PR Tested: #4736
Tier of testing:2
Changes to observe ISIS brightness buttons push&hold 

Testing technique: Tryout
Methodology:
1 In the self-test and altimeter views, use the standby instrument's brightness push buttons to adjust the brightness of the display.
2 Pressing and holding, as well as single sharp presses, should both work as expected.
3 Press the BUGS button. In this mode, the standby instrument's brightness push buttons should move the cursor that selects the heading/altitude bugs that are being adjusted by the altimeter knob. The brightness should not change.
4 Use the integrated panel emissive knob to adjust the brightness of the panel lighting. The buttons should light up or stop emitting light as expected.
5 Attempt to break the brightness control by clicking on both buttons randomly. The brightness adjustment should continue working.
Scenario:
1.Operation Flight Scenario
 1.1. On ground
  1.1.1 Observation during regular startup from cold&dark
  1.1.2 ground power only
  1.1.3 BAT ON/OFF
   1.1.3.1 BAT1,2 On/OFF (ground power off)
   1.1.3.2 BAT1,2 On/OFF (ground power On)
  1.1.4  APU ON
   1.1.4.1 APU Gen On/Off (On ground power) 
   1.1.4.2 APU Gen On/Off (OFF ground power)
 1.2. In Flight 
  1.2.1 BAT ON/OFF 
   1.2.1.1 BAT1,2 Push button On/OFF (Engine/s Running Only*)
   1.2.1.2 BAT1,2 Push button On/OFF (APU Running Only*)
 1.1.3. Engine/s GEN (ON/OFF)
  1.3.1 Engine GEN1 (ON/OFF)
   1.3.1.1 Engine GEN1 (ON/OFF)
   1.3.1.1 Engine GEN1 (ON/OFF) (APU Running Only*)
  1.3.2 Engine GEN2 (ON/OFF)
   1.3.2.1 Engine GEN2 (ON/OFF)
   1.3.2.1 Engine GEN2 (ON/OFF) (APU Running Only*)
  1.3.3 Engine GEN1,2 (ON/OFF)
   1.3.3.1 Engine GEN1,2 (ON/OFF)
   1.3.3.1 Engine GEN1,2 (ON/OFF) (APU Running Only*)
2.SIM
 2.1. Day time
  2.1.1 Random time/s (Without Reshade)
  2.1.2 Random time/s (With Reshade)
 2.1. Night time
  2.2.1 Random time/s (Without Reshade)
  2.2.2 Random time/s (With Reshade) 


Flight notes: ROUTE ID: DEFRTE
KBFM/32 DCT LURDE DCT CEW DCT PIGON DCT MVC DCT NOTNE DCT KBFM/36

Media: NIL

Issues (If Any): NIL

Overall Rating: Good
Conclusions of the testing: All Observations were as expected no bugs found, Good luck... Best wish

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 13/5/21
Version of the sim: 1.15.10.0
PR Tested: #4797 
Tier of testing: 1
Changes to observe:
ISIS brightness push and hold

Testing technique: Loaded in at different locations and tried
Steps you've made to test the Pull Request:
1. Loaded C&D and tried
2. Loaded on runway
3. Loaded on approach

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: LGTM

**Comment by sidnov** [comment]
Category: Dev/QA Tester
Name: sidnov#8337
Date of testing: 14.05.2021
Version of the sim: 1.16.1.0p
PR Tested: #4797 
Tier of testing: 1

### Changes to observe: Standby instruments brightness push and hold

### Testing technique: Tryout

### Steps made to test the Pull Request:
1. Spawn C/D
2. Turn on batteries, ext. pwr
3. Check brightness buttons on the standby instrument
4. Check if INTEG LT controls emissive

### Media: 
image
image


### Issues:
None

### Overall Rating: Good
### Conclusions of the testing:
Fixes issues with the previous PR. LGTM! 👍🏻

**Pull request merged**
