### PR TITLE
fix(CDSS): cockpit door video toggle

### LINKED ISSUE #1318: [BUG] [CDSS] Video button has to be one-click
**Mod Version**

0.3.1 current **master** as of 14th Okt 20

**Describe the bug**

When clicking the CDSS Video button you have to hold it to have the video be displayed on the lower ECAM.

**To Reproduce**

1. Hold the button
2. Video shows
3. Release the button

**Expected behavior**

The Video button should be a one-click button. Click it once to show the camera, click it again to show camera 2 and then 3. THEN on the last click it disappears.

**Actual behavior**

Its a click and hold button

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by sidnov**
Fixes #1318

## Summary of Changes

Changed cockpit door video button to toggle instead of press and hold. Nothing major, found while fixing older issues.

## Additional context

Discord username (if different from GitHub): sidnov#8337

## Testing instructions

Press the cockpit door video button on the pedestal next to door controls, make sure it springs/reverts back to its original position after press and toggles the cockpit door video image on the lower ECAM. Press the button again and see if it toggles the door video image off.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by bouveng — APPROVED** [review]
LGTM

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5539 
Tier of Testing: 1
Date: 05/08/2021

Testing Process:
- Spawned in C+D at EGKK, connected ground power and batts.
- Pressed the cockpit door video button a fair few times, checking the button springs back to the original position.
- Checked lower ECAM for cockpit door video appearing and dissapearing on button push. 
- Checked cockpit door video button on overhead, disables the function as expected. 
- Continued to do a flight to LOWI - all as anticipated and no new issues observed.

Negatives: N/A
Testing Results: Passed

Conclusions: Great that it works as intended and as explained on the testing instructions. If it wasn't for this PR, who knows when I'd have noticed this feature! Great stuff. 

image
image

**Comment by Benjozork** [comment]
Please provide references that this is the correct behaviour as I remember it being held.

**Comment by sidnov** [comment]
> Please provide references that this is the correct behaviour as I remember it being held.

image
image

**Comment by sidnov** [comment]
Got an idea that I'll try fiddling with. We could possibly add views 2 and 3 and improve the press+ press and hold logic

**Review by Benjozork — APPROVED** [review]
The current panel in the Asobo model is from an older aircraft where you'd hold the pb. But since we are remodelling, we can use new panel behaviour for this tbh.

**Comment by sidnov** [comment]
> The current panel in the Asobo model is from an older aircraft where you'd hold the pb. But since we are remodelling, we can use new panel behaviour for this tbh.

Found some more interesting stuff. The current panel definitely belongs to a CEO, though it has the toggle behavior. The NEOs have a video selector switch.
image


I was planning to implement the 2-second delay with images 2 and 3 as well, but it is not worth since we are remodeling it anyway, as you mentioned. We can merge as it is for now.

**Comment by Benjozork** [comment]
What is this waiting for?

**Comment by sidnov** [comment]
> What is this waiting for?

For me, it's good to go. I thought we are waiting for another test.

I'll work on another advanced implementation once we start with the custom model

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5539 
Tier of Testing: 1
Date: 08/08/2021

**Testing Process:**
1. Loaded onto RW
2. Normal and rapid press test of CDSS button
3. observed ECAM video
4. Same test after C&D

**Negatives:** N/A
**Testing Results:** Passed

**Pull request merged**
