### PR TITLE
[CDU] Create definition for currently used messages

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Create definition for system messages
- Create general message handler for all messages
- Make type II messages use definitions and new handler
- Make type I messages use definitions and new handler
- Create definition for fictive messages
- Make remaining messages use fictive messages

## Additional context

Discord username (if different from GitHub): **DerL30N#3751**

## Testing instructions

Click through mcdu pages and check if messages appear as they should. As a small addition to check if error messages on bad input appear, try to feed the mcdu some wrong data. See if you can brute force something there ;)
Also check for inflight messages like `NEW CRZ ALT-` or `ENTER DEST DATA`.
I would suggest doing the exact same steps once on stable and once with this pr to check whether something broke or not.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 23/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2584
Object of test: Check CDU for currently used messages
Testing technique: Full Flight

Steps you've made to test the Pull Request:

1. Spawned at VAID ramp 5, C/D
2. Prepped an IFR Flight normally.
3. Cycled through different pages on the CDU as suggested on the PR
4. Observed messages "GPS PRIMARY LOST" and "GPS PRIMARY" after ADIRS alignment
5. Took off from RWY25, pretty uneventful flight. "ENTER DEST DATA" showed up normally inflight after setting up the initial approach and arrival runway details in the flightplan.
6. Cycled through all the CDU pages once again, inflight. 
7. Landed at VASU

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: The system messages show up accurately, both on ground and during flight phases. Attached a screenshot for reference.

DEST DATA

**Comment by MisterChocker** [comment]
@sidnov thanks. Have you tried to insert wrong data into fields to get error messages? We need some testing on that as well.
I will update testing instruction, looks like I forget to write that down.

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 23/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2584 
Object of test: MCDU functionality having created definitions for used messages

Testing technique: Full Flight from KSFO to KSAN on VATSIM livestreamed on my channel too
Steps you've made to test the Pull Request:
1. Spawned Cold and Dark at KSFO - set aircraft up for departure and used simbrief import for flight plan
2. All MCDU inputs checked and all worked as expected - no issues encountered at this point.... departed Runway 19R
3. During the flight, made some inputs into the MCDU and waited for it to trigger the "Enter Dest Data" warning and that worked as it should have
4. Flew inbound to KSAN via mission valley VOR checking MCDU, ND etc and used VOR1 and an outbound course from the VOR input into the MCDU for reference 
5. Then manually vectored round for the ILS which was input into the MCDU also. 
6. Landed, taxied to gates and shut down

Flight notes (If required): N/A - everything worked as expected

Issues (If Any): None found
Overall Rating: Good
Conclusions of the testing: Encountered no issues at all, everything worked as expected

**Comment by sidnov** [comment]
> @sidnov thanks. Have you tried to insert wrong data into fields to get error messages? We need some testing on that as well.
> I will update testing instruction, looks like I forget to write that down.

@MisterChocker Just tested that out. All such abnormal inputs get detected either with "Out of Range", "Not Allowed" or similar error messages.

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 23.12.2020
Version of the sim: 1.12.13.0
PR Tested: #2584 
Object of test: New definitions for CDU Messages

Testing technique: Try out
Steps you've made to test the Pull Request:
1. Loaded up the AC in KLAS
2. Tested through every single scenario on ground
3. Took of for a Pattern and tested every scenario airborne

Flight notes (If required): None

Issues (If Any): None found
Overall Rating: Good, works as described
Conclusions of the testing: Every message works as it did before

**Review by Benjozork — APPROVED** [review]
LGTM

**Pull request merged**
