### PR TITLE
[BUG] fix altitude button setting the speed on atc request

### PR DESCRIPTION
**Pull request by brookemckim**
## Summary of Changes

Fixes a bug where setting the FL/ALT on the ATC Request screen would set the SPD instead of the ALT. This was happening because the index for the ALT and the SPD were overlapping.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by tareksabet** [comment]
Can you rebase it on the latest master

**Comment by ErickSharp** [comment]
Category: QA Trial
Name: 🎄🎅Erick🎄🎅 [Feliz Navidad]#6484
Date of testing: Current date 26/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2486 
Object of test: ATC Request altitude fix

Testing technique: Loaded in cold and dark in Gatwick. Tested with the stable and the PR.
Steps you've made to test the Pull Request:
1. Load in cold and dark using stable version. 
2. Turn on external power so systems are alive.
3. Navigate to "Request" page and input "190" into "FL/ALT"
4. Take note of "FL/ALT" being unaltered but "SPD/MACH" having the input value.
Screenshot 2020-12-26 200701

5. Load in cold and dark using stable version.
6. Turn on external power so systems are alive.
7. Navigate to "Request" page and input "190" into "FL/ALT"
8. Take note of "FL/ALT" having the input value.

Screenshot 2020-12-26 202102

Flight notes (If required): All testing done cold and dark at Gatwick.
Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: PR does a good job of fixing the issue with the ATC Request. Minimal to no changes needed.

**Comment by MisterChocker** [comment]
don't forget to add the changes to the changelog

**Comment by iamdefective1** [comment]
Category: QA Tester
Name: IAMDEFECTIVE1#9293
Date of testing: 29/12/20
Version of the sim: 1.12.13.0
PR Tested: #2486
Object of test: ATC Req screen fix

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. spawn in egkk
2. power up
3. navigate to atsu page, atc menu
4. insert: speed 190, fl125, direct HON
5. no conflict 

Screenshots:.
image
image

Issues (If Any): yes **
Overall Rating: Good
Conclusions of the testing: No conflict from changing the values.
**One bug I observed is trying to clear the value, it puts the CLR into the box

**Comment by pepperoni505** [comment]
@Benjozork is this good to merge?

**Comment by Benjozork** [comment]
> @Benjozork is this good to merge?

Yes

**Pull request merged**
