### PR TITLE
Texture changes (Overhead, mainpanel, glareshield quality improvements)

### PR DESCRIPTION
**Pull request by Pleasure0102**
Fixes #[issue_no]

## Summary of Changes

added Plaque for Registration
added normals for glareshield
improved overall textures (overhead, mainpanel, glareshield)

## Screenshots (if necessary)

**BEFORE**
FlightSimulator_2020-11-02_13-28-21
FlightSimulator_2020-11-02_13-28-49
FlightSimulator_2020-11-02_13-29-07
FlightSimulator_2020-11-02_13-29-26

**AFTER:**
FlightSimulator_2020-11-02_12-04-51
FlightSimulator_2020-11-02_12-05-10
FlightSimulator_2020-11-02_12-06-10
FlightSimulator_2020-11-02_13-01-35
FlightSimulator_2020-11-02_13-02-08
FlightSimulator_2020-11-02_13-02-45

## References

REF: Glossiness of material when light shined on it : 
image

REF: Registration plaque (removed reg. for obvs reasons)
image

## Additional context

Please check texture quality on different lighting levels, check normal maps.
Question: Reduce dirt / damage on overhead ?

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by z0rgmeister** [comment]
Name: z0rgmeister#8972
Date of testing: 02/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1719
Object of test: Test texture changes for Reg plaque and glareshield normals

Steps taken: Single straight from runway flight at LPPT loaded with default loadout. Different times of day and lighting conditions tested. Onboard lighting on and off.

Flight notes: NA

Taxi/Takeoff : NA

Cruise: NA

Descent/Approach/Landing: NA

Shutdown: NA

Issues: None found.
Overall Rating: Good
Conclusions of the testing: No issues found,  good addition, great looking shine on the normal maps.

**Comment by Pleasure0102** [comment]
@z0rgmeister what you think about the amount of dirt on overhead ? reduce ? or good as is ?

**Comment by aviationenthusiast** [comment]
> 
> 
> @z0rgmeister what you think about the amount of dirt on overhead ? reduce ? or good as is ?

can things like dirt be dynamic? Like a random texture gets selected from multiple codes and changes whenever you hop into a new flight?

**Comment by Benjozork** [comment]
Please add a more specific title 😄

**Comment by Benjozork** [comment]
> can things like dirt be dynamic? Like a random texture gets selected from multiple codes and changes whenever you hop into a new flight?

Do not think that is easily possible with the current SDK.

**Comment by Pleasure0102** [comment]
> > @z0rgmeister what you think about the amount of dirt on overhead ? reduce ? or good as is ?
> 
> can things like dirt be dynamic? Like a random texture gets selected from multiple codes and changes whenever you hop into a new flight?

so technically i can add a transparent dirt texture, in a folder in our project, but programming side would have to make it so it gets overlayed.. im not sure that it is possible, so right now only talking about the wear / tear / dust that is permanent

**Comment by z0rgmeister** [comment]
> 
> 
> @z0rgmeister what you think about the amount of dirt on overhead ? reduce ? or good as is ?

Dirt seems acceptable for a regular use airplane. I mean these things get cleaned every so often so they shouldn't look like they've been left in the Sahara for months out in the elements. :)

**Comment by aviationenthusiast** [comment]
> 
> 
> > can things like dirt be dynamic? Like a random texture gets selected from multiple codes and changes whenever you hop into a new flight?
> 
> Do not think that is easily possible with the current SDK.



> 
> 
> > > @z0rgmeister what you think about the amount of dirt on overhead ? reduce ? or good as is ?
> > 
> > 
> > can things like dirt be dynamic? Like a random texture gets selected from multiple codes and changes whenever you hop into a new flight?
> 
> so technically i can add a transparent dirt texture, in a folder in our project, but programming side would have to make it so it gets overlayed.. im not sure that it is possible, so right now only talking about the wear / tear / dust that is permanent

Alright then. Thanks for you work^^

**Comment by starvingjavi** [comment]
Name: Javi#2557
Date of testing: Current date 1/11/2020
Version of the sim: 1.10.8
PR Tested: #1719 
Object of test: Texture changes

Testing technique: Full flight in IVAO from MMUN to KMIA

Steps you've made to test the Pull Request:

1. Start C&D at MMUN
2. Follow procedures and continue flight
3. Check for FPS problems
4. Complete flight

Flight notes

Startup: Normal

Taxi/Takeoff : Normal

Cruise: Normal

Descent/Landing : Normal

Shutdown: Normal.

Issues (If Any):
Overall Rating: Good
Conclusions of the testing: Everything looks good

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 02/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1719
Object of test: Check out the changed textures in flight deck 

Steps taken: 

Spawn on RWY at EKCH. Zoom in on texture changes and check for placard and that the ruleset works. Check the textures at different times of day and in different lighting/shadows. 

Flight notes: 

Taxi/Takeoff : NA

Cruise: NA

Descent/Approach/Landing: NA

Shutdown: NA

Issues: None
Overall Rating: Good
Conclusions of the testing: LGTM. Nice details.  @Pleasure0102 Thanks for this!

**Comment by Pleasure0102** [comment]
looks like its ready to merge @Benjozork once its merged i will do a PR for different versions of the placard for different airlines. People can just swap directly. My most tested pr xD

**Comment by ukflyer** [comment]
hi guys, any chance for the registration Plaque to be dynamic based on a/c registration - seems a bit odd to have a different registration to that on the outside of the a/c!!

**Pull request merged**
