### PR TITLE
[CDU] Wind page

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Added wind page to MCDU (can be accessed from init page)
    * Currently not used for any calculations but is needed for my VNAV PR.
    * Cruise wind cannot be set for individual waypoints for now.
    * History winds, wind request, and sat/alt inputs for cruise waypoints are inop.

## References

Honeywell Pegasus Step 1A (Rev 0), 2009 edition manual

## Screenshots
image

## Testing instructions

The new wind page can be accessed by selecting "WIND/TEMP>" on the init page or from the vertical revision page. Make sure you are able to access the page and input winds correctly and that the "<RETURN" button returns to the correct page.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Highflyer2010** [comment]
Category: QA Tester
Name: Discord User Highflyer2010#8932
Date of testing: Current date 22/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2597
Object of test: [CDU] Wind Page

Testing technique: checking the added wind page

Steps you've made to test the Pull Request:

1. Loaded Sim and loaded Aircraft C&D
 
2. Spawned at EGNT at a gate

3. Setup Aircraft , Ext Pwr, Batteries ect...
 
4. setup flight plan

5. Pressed INIT

6.Pressed WIND/TEMP

Flight notes (If required):

Issues (If Any): Pressing the wind/temp button does not allow me onto the page

Overall Rating:To be improved

Conclusions of the testing: pressing the Wind/Temp button within the INIT page does not work . I press and nothing happens

**Comment by MisterChocker** [comment]
@tyler58546  You forgot to add the new page to the cdu css file?

**Comment by tyler58546** [comment]
> @tyler58546  You forgot to add the new page to the cdu css file?

When I pushed I reverted my changes to the html file but I forgot to add back the new script. I will fix it tomorrow.

**Comment by Highflyer2010** [comment]
Category: QA Tester
Name: Discord User Highflyer2010#8932
Date of testing: Current date 23/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2597
Object of test:[CDU] Wind Page

Testing technique: Description of how you tested the Pull Request

Steps you've made to test the Pull Request:

1. Loaded Sim and loaded Aircraft C&D
 
2. Spawned at LSZH at a gate

3. Setup Aircraft , Ext Pwr, Batteries ect...
 
4. MCDU - Sorted fight plan

5. MCDU clicked on INIT and pressed WIND/TEMP

Flight notes (If required):N/A

Issues (If Any):N/A

Overall Rating: Good

Conclusions of the testing: all working good went through all phases but cannot click on Wind History & Wind Request as stated on the PR other then that all good

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 23/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2597
Object of test: Check the WIND page on CDU
Testing technique: Runway spawn and C/D

Steps you've made to test the Pull Request:
1. Spawned at VABB RWY27 with no flight plan. Checked WIND/TEMP under INIT page.
2. Checked the WIND pages for all 3 phases (CLIMB, CRZ, DESCENT)
3. Inserted values for winds as shown in the screenshots. Worked as expected.
4. Repeated same steps after spawning C/D at VABB, this time added a temporary F-PLN
5. Wind page input worked in C/D method as well.
6. Clicking "<RETURN" brings me back to the main INIT page.

Issues (If Any): Works as expected
Overall Rating: Good
Conclusions of the testing: Since the wind component values input in the WIND/TEMP values are not used for any calculations yet, this test was mostly about the visual/functionality of the page. Works as described!

Windpage2

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
