### PR TITLE
feat(efb/ui): refueling UI override and initialization

### PR DESCRIPTION
**Pull request by Taz5150**
Fixes #[issue_no]

## Summary of Changes

This PR completely overrides the use of MSFS's Fuel in-game menu, giving full and exclusive refuel/ defuel control to the EFB Dispatch fuel page.

Additionally, initial fuel quantity has been hardcoded and set randomly between 2,000 Kg & 3,000 Kg until persistence has been implemented.

IMPORTANT: Merging this PR will require our Comms&Marketing team to spread out the word about the change in functionality.

## Additional context

Discord username (if different from GitHub): TazX [Z+2]#405

## Testing instructions

1. Check Fuel in-game menu override:
    - Load a flight in any initial condition (parked, runway, in-flight)
    - Open the Fuel in-game menu and move around the fuel sliders
    - Although the sliders do move and seem to change fuel, in a matter of 1-3 seconds fuel levels should return to initial value
    - Go into the EFB->Dispatch->Fuel page
    - Change fuel level (refuel and defuel)
    - Check fuel levels do change accordingly
    
2. Check initial fuel quantity (random):
    - Restart the flight several times
    - Check fuel quantity is randomized between 2,000 Kg - 3,000 Kg (full outer tanks, zero center tank, rest within inner tanks)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by donstim** [comment]
Really nice piece of work. Will this be adaptable to the payload portion of the UI as well?

I do have a couple of comments:
1) The MCDU W&B refuel option does not appear to work with this PR.
2) I was able to get some wacky behavior by messing with the UI fuel sliders while fueling through the EFB was taking place.

Both of these comments can be observed in this video:  https://1drv.ms/v/s!Ajsy7Ey4_8uFz2cRYg4IBLrcxX77?e=sN4vP6

**Comment by Taz5150** [comment]
> Really nice piece of work. Will this be adaptable to the payload portion of the UI as well?
> 
> I do have a couple of comments:
> 
> 1. The MCDU W&B refuel option does not appear to work with this PR. (The PR says it gives full and exclusive refuel/defuel capability to the EFB. Should it also allow MCDU fueling, or should that capability be removed from the MCDU?) @sidnov
> 2. I was able to get some wacky behavior by messing with the UI fuel sliders while fueling through the EFB was taking place.
> 
> Both of these comments can be observed in this video: https://1drv.ms/v/s!Ajsy7Ey4_8uFz2cRYg4IBLrcxX77?e=sN4vP6

Great tests and comments on which I honestly didn't think of. As you suggest, and was commented in the #efb channel some time ago, this could be adapted to the payload portion of the UI as well if needed.

1. Did not take into account MCDU refueling. We'll wait for @sidnov to comment, and see what we can do. Is the W/B page in the MCDU realistic?

2. Yes, it makes sense and this should be dealt with more complex logic. Will see what I can do.

**Comment by sidnov** [comment]
@Taz5150 @donstim I don't mind removing page 1 on the W/B section on the MCDU. Since it refuels with one click, it's not very realistic as of now. 

One thing that needs to be ensured before removing the page is, Simbrief OFP fuel request on the EFB. I'm not entirely sure if pressing the "FROM SIMBRIEF" button on the EFB dashboard fetches and updates fuel in the EFB fuel page. I can check this and get back, but it may take a while since I've had a couple of errands to run since morning, and a few more to go 😄

**Comment by sidnov** [comment]
Following up on this, I checked if Simbrief import also adjusted the fuel amount on the EFB but seems like it doesn't. There are 3 things primarily on the W/B Fuel page on the MCDU- block fuel, taxi fuel and trip fuel, which is imported from Simbrief

**Comment by Taz5150** [comment]
Understood, thank you @sidnov. In order for me to overcome this situation, I 'd need to knoe if there is anyway to know when fuel is being set through the MCDU (an LVar for example).

**Comment by sidnov** [comment]
> Understood, thank you @sidnov. In order for me to overcome this situation, I 'd need to knoe if there is anyway to know when fuel is being set through the MCDU (an LVar for example).

There isn't any unfortunately. It directly updates the Fuel vars

**Pull request closed without merging**
