### PR TITLE
Changed avionics self test sound, made the ext pack sounds change pitch with ambient temp, and new wwise events

### PR DESCRIPTION
**Pull request by hotshotp**
## Summary of Changes

Changed avionics self test sound, it is now a bit quieter and higher quality. 
Added a new alternator/TR unit sound (the sound when you turn on batteries and external power)
Made exterior pack valves sounds change pitch the higher the ambient OAT is

Then, for @tyler58546 -
added printer wwise events:
printerloop
paperflip
papertear
papercrumble

these should be self explanatory

## References

Not really any references needed, this is just adding things that I got told by engineers (the pack valves) and the self test sound is just overall better now that it has a more pleasant sound without distortion that was present before due to high volume.

## Additional context

Discord username (if different from GitHub):

Boris#9134

## Testing instructions

Start battery, then external power and listen to the whine (alternator/TR Unit) and then listen to avionics ventillation self test.
Then start apu and apu bleed and listen on exterior view and change ambient temp using the weather menu and listen to pitch changes.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by ErickSharp** [comment]
Category: QA Tester
Name: Erick [Z-6]#6484
Date of testing: Current date 25/01/2020
Version of the sim: 1.12.13.0
PR Tested: #3171 
Object of test: Sound revisions
Testing technique: Spawned in cold and dark at Madeira and followed testing instructions
Steps you've made to test the Pull Request:
1. Spawn in cold and dark.
2. Start battery to listen for "clonk" sound.
3. Start APU and jump into external mode.
4. In the in-game weather panel, adjust outside temperature to listen for variations in the sound. 

Flight notes (If required): None
Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Juicer of a PR. The sound changes nicely fit in and I'm sure Tyler will love the wwise events.

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 1/25/2021
Version of the sim: 1.12.13.0
PR Tested: #3171 
Tier of testing: 1
Changes to observe:
Changed avionics self test sound, it is now a bit quieter and higher quality.
Added a new alternator/TR unit sound (the sound when you turn on batteries and external power)
Made exterior pack valves sounds change pitch the higher the ambient OAT is

Then, for @tyler58546 -
added printer wwise events:
printerloop
paperflip
papertear
papercrumble

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request: Tried out
1. Spawned C&D at kord and turned on aircraft and listened to Self test sounds.
2. Started APU and listened to pack sounds at -0.3C
3.  Turned APU bleed off and changed temp to 60C
4.  Turned APU bleed-on and listened to pac sounds
5.

Flight notes (When done a full flight):
This has nothing to do with this PR but I noticed @tyler58546 when I click the print button the paper spawns invisible inside of the printer then starts coming out. I think we should not be able to see the paper until it starts printing.
Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): Write any issues
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: Pr sounds really nice and I love the dynamic pack sounds. also maybe you can add a more realistic pack shut down sounds because right now it kinda just fades away. Great work Boris.

**Comment by cianwhite** [comment]
Category: QA Tester
Name: Cian#3596
Date of testing: 25/01/2021 
Version of the sim: 1.12.13.0
PR Tested: #3171
Object of test: Test for new pitch in sounds
Testing technique: Spawned in cold and dark at EIDW tested different temperatures and observed the changes
Steps you've made to test the Pull Request:

1. Loaded in cold and dark at EIDW
2. Started as normal at around 15 degrees OAT
3. Observed the sounds
4. Changed the temperature in the in game weather system to a higher temperature
5. Listened to the sounds and the pitch changes at higher OAT.

Flight notes (If required): None
Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Everything works as expected, the pitch changes at higher temperatures and the new start-up sounds are noticable.

**Review by davidwalschots — APPROVED** [review]
LGTM

**Pull request merged**
