### PR TITLE
fix(sound): add timer to basic packs logic

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

Added a 30sec timer to automatically open packs.
Requested by @hotshotp

(This only mimics a basic behavior and not the complex system behind it)

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 24.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3155 
Tier of testing: 1
Changes to observe: Timer for reopening packs

Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned C&D
2. Turned on APU and APU Bleed
3.  Switched Engine Mode to ignition
4. Waited 30 seconds
5. observed

Flight notes (When done a full flight):n/a

Media:n/a

Issues (If Any): The Pack Sound did not return at all
Steps to achieve the issue
turn Engine Mode to IGN and wait

Overall Rating: To Be Improved
Conclusions of the testing: Did not work as described. Either i am missing out something or it just really doesnt work

**Comment by hotshotp** [comment]
> Category: QA Tester
> Name: ChruutvoLuzi | SD-PB.ch#8902
> Date of testing: 24.1.2021
> Version of the sim: 1.12.13.0
> PR Tested: #3155
> Tier of testing: 1
> Changes to observe: Timer for reopening packs
> 
> Testing technique: TryOut
> Steps you've made to test the Pull Request:
> 
> 1. Spawned C&D
> 2. Turned on APU and APU Bleed
> 3. Switched Engine Mode to ignition
> 4. Waited 30 seconds
> 5. observed
> 
> Flight notes (When done a full flight):n/a
> 
> Media:n/a
> 
> Issues (If Any): The Pack Sound did not return at all
> Steps to achieve the issue
> turn Engine Mode to IGN and wait
> 
> Overall Rating: To Be Improved
> Conclusions of the testing: Did not work as described. Either i am missing out something or it just really doesnt work

not what the PR is about. The PR is that when you turn on one engine, the packs will come on 30 seconds later after one engine is avail

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 25.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3155
Tier of testing: 1
Changes to observe: PACKS opening timer

Testing technique: Tryout
Steps you've made to test the Pull Request:

1. Spawned C/D at gates, turned on batteries and external power
2. Turned APU, bleed and fuel pumps on.
3. Turned on Engine 2, observed 30 seconds before packs activated and sound was heard

Issues (If Any): None.
Conclusions of the testing: Pack sounds were audible after 30 seconds of engine start.

**Comment by stescouse** [comment]
Category: QA Tester
Name: Discord User stescouse#7271
Date of testing: 25.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3155
Tier of testing: 1
Changes to observe: 30sec timer to automatically open packs.

Testing technique: TryOut
Steps you've made to test the Pull Request:

1. Spawned C&D at SKBO
2. Started up APU and then APU Bleed.
3. Switched on engine ignition and turned on engine 1.
4. On engine available started timer to reach 30 seconds.
5. Listened for Packs starting up after 30 seconds.


Flight notes (If required: none

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: Packs sound clearly audible after 30 seconds of engine available.

**Pull request merged**
