### PR TITLE
fix(model): make sound nodes invisible

### LINKED ISSUE #5652: Blender Cube in plane.
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-14T06:41:53+00:00",
  "ref": "master",
  "sha": "a67f7ac36d9805949846f1531c14c16453e29ae3",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

A bunch of blender cubes on the engine cones and Foward and aft doors.

### Expected behavior

For there to not be blender cubes

### Steps to reproduce

Load the plane

### References (optional)

image
No blender cubes here (IRL IMAGE)

image
image
image

### Additional info (optional)

_No response_

### Discord Username (optional)

Awemeter#3110

### PR DESCRIPTION
**Pull request by pepperoni505**
Fixes #5652 

## Summary of Changes

Adds the invisible extension back to the node material

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Look in front and back galleys for any small gray cubes

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

**Comment by Benjozork** [comment]
@pepperoni505 please add testing instructions to this PR

**Review by Benjozork — APPROVED** [review]

**Comment by Awemeter** [comment]
Quality Assurance Trainee Report

Object of testing: #5655 
Tier of Testing: 1
Date: 8/16/2021

Testing Process: Spawned C&D into Gatwick and checked front cabin, rear cabin, and engines.
Negatives: The sound nodes/blender cubes are still there.
Testing Results: Not Passed

Conclusions: N/A
Media: N/A

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5655
Tier of Testing: 1
Date: 16/08/2021

**Testing Process:**
1. Loaded onto RW and searched the cabin for grey boxes

**Negatives:** 
- Found a small cube on the cockpit door curtain of both galleys
image

**Testing Results:** Not Passed

**Review by bouveng — CHANGES_REQUESTED** [review]
I do not understand. This is just a reformatting, nothing new is added or removed.
Is something missing from this PR?

Br.

**Comment by pepperoni505** [comment]
Whoops! I don't think I committed my actual changes. I'll fix this tomorrow as I'm not at my computer

**Comment by beheh** [comment]
Marked it as a draft again until this is resolved.

**Comment by pepperoni505** [comment]
Ok, this should be working now

**Review by bouveng — APPROVED** [review]

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5655
Tier of Testing: 1
Date: 18/08/2021

Testing Process:
- Loaded in on runway at EGCC, checked front and rear galleys for sound nodes: none visible from looking and none in the previously spotted places.

Negatives: N/A
Testing Results: Passed

Conclusions: Removes the small grey cubes, works as intended so great stuff! Not sure if related to this PR or already fixed - same cubes noted previously on engines are no longer there

Media:
image

**Pull request merged**
