### PR TITLE
fix(efb): introduce input component to EFB device and put it on simbrief page

### PR DESCRIPTION
**Pull request by arturkuma**
## Summary of Changes

Introduce better input component that can be used across all flyPad pages. 
New component uses react hooks.

## Screenshots (if necessary)

Before:
2021-02-03 17_55_22-Window

After:
2021-02-03 16_29_59-Window
2021-02-03 16_30_18-Window

## References
No strong reference as it's our own implementation of UX. Designed component uses colors and styles that matches already designed components.

## Additional context

This is my first PR in this project 🤙

Discord username (if different from GitHub): arturkuma#6639

## Testing instructions

1. Go to `Company` page in EFD
1. Check if input works

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
I would make this a bit smaller personally

**Comment by Snapmatics** [comment]
I would make it smaller, yes, but the title a bit bigger.

**Comment by Benjozork** [comment]
Also, can you use tailwind for styling so we are consistent ? I can convert it if needed.

**Comment by arturkuma** [comment]
Ok so overall size of input decreased

2021-02-03 21_52_13-Microsoft Flight Simulator - 1 12 13 0
2021-02-03 21_52_04-Microsoft Flight Simulator - 1 12 13 0

**Comment by arturkuma** [comment]
> Also, can you use tailwind for styling so we are consistent ? I can convert it if needed.

Hi, if you can convert then I'll take this as an example for my next changes :) 

and btw. I can see some overall project architecture changes (EFB) that we can make. I'm software dev for living so maybe we can discuss tham somehow somewhere? Discord? Feel free to contact me (my ID in PR description). Writing that here for people in future that also will want to join

**Comment by arturkuma** [comment]
thx @Benjozork , I'll follow that in next commits

**Review by ZigTag — APPROVED** [review]
LGTM

**Comment by cianwhite** [comment]
Category: QA Tester
Name: Cian#3596
Date of testing: 05/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3315 
Tier of testing: 1
Changes to observe: Simbrief input box in EFB

Testing technique: Started cold and dark and on a runway
Steps you've made to test the Pull Request:
1. Started cold and dark at EGLL, started EFB
2. Link simbrief to it and flight plan shows as expected
3. Started on the runway at EGLL and repeated above steps

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: The simbrief input component looks better than before and maintains the same level of functionality. LGTM

**Pull request merged**
