### PR TITLE
[CDU] Update the precomputed ZFW/ZFWCG values when weight parameters are changed

### LINKED ISSUE #1720: [BUG] MCDU does not update ZFW/ZFWCG
**Mod Version**
built: 2020-11-01T23:29:49+00:00
ref: refs/heads/master
sha: 037c98e85e1e69747e3f302aaa398111eaba8413
actor: Benjozork

All versions

**Describe the bug**
If the payload is changed at the gate (with the shortcut / menu on top), the MCDU keeps the old values, inserted with the MS flightplanner _before_ starting the flight.

**To Reproduce**

1. Plan an flight (or not) and keep the weight&balance as it is (check and remember the ZWF and CG there)
2. Start the flight at a gate
3. Power up the cockpit (ext power or APU). Don't make any input to the MCDU.
4. At gate, change the payload via the top menu button 
5. Go to the INIT B page in the MCDU and push the ZFW/ZFWCG button
6. Check ZWF and CG which is given there and compare.

**Expected behavior**
MCDU should update ZFW and CG after changed.

**Actual behavior**
see above

**Additional context**

Was this working before/when did the issue start occurring?
I think this never worked. 
Could be also a vanilla problem. I even don't know if this can be solved with the possibilities of FWB.

### PR DESCRIPTION
**Pull request by lousybyte**
Fixes #1720
## Summary of Changes

Fixed an issue where the precomputed ZFW/ZFWCG values were not properly updated if the weight load was changed from the game menu.

## Additional context

Details to reproduce and check are in the linked issue.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by wpine215 — APPROVED** [review]

**Comment by wpine215** [comment]
LGTM

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 16/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1972 
Object of test: MCDU

Testing technique: 
Steps you've made to test the Pull Request: 
1. load up A/C Cold and Dark
2. Varied fuel and ZFW and inserted precomputed ZFW/ZFWCG


Issues (If Any): Updating of ZFW/ZFWCG after Fuel Planning also updates the Block fuel without hitting RSK3
Overall Rating: to be improved
Conclusions of the testing: Precomputed values for ZFW/ZFWCG updating as described. Changing the ZFW changes ZFW/ZFWCG. Changing Fuel only changes only ZFWCG.

Reproducing the Issue: 
1. Insert precomputed ZFW/ZFWCG
2. Click RSK3 for fuel planning and confirm
3. Update ZFW or Fuel
4. Insert again precomputed ZFW/ZFWCG
5. Now the block fuel also changes

**Comment by danbw9** [comment]
@Noxleee The built in fuel planner seems to vary the fuel sometimes when you change Payload setting to ensure that the CoG is within limits I believe. So yes the block fuel in INIT B will change but will match your current fuel as is displayed in MSFS fuel planner. Tested this twice with two different flights from C&D and that was my conclusion.

**Comment by lousybyte** [comment]
Should be fine now, I think auto updating the fuel block should be its own thing to debate.

**Comment by Noxleee** [comment]
> 
> 
> Category: QA Tester
> Name: Noxlee #7727
> Date of testing: Current date 16/11/2020
> Version of the sim: 1.10.11.0
> PR Tested: #1972
> Object of test: MCDU
> 
> Testing technique:
> Steps you've made to test the Pull Request:
> 
>     1. load up A/C Cold and Dark
> 
>     2. Varied fuel and ZFW and inserted precomputed ZFW/ZFWCG
> 
> 
> Issues (If Any): Updating of ZFW/ZFWCG after Fuel Planning also updates the Block fuel
> Overall Rating: to be improved
> Conclusions of the testing: Precomputed values for ZFW/ZFWCG updating as described. Changing the ZFW changes ZFW/ZFWCG. Changing Fuel only changes only ZFWCG.
> 
> Reproducing the Issue:
> 
>     1. Insert precomputed ZFW/ZFWCG
> 
>     2. Click RSK3 for fuel planning and confirm
> 
>     3. Update ZFW or Fuel
> 
>     4. Insert again precomputed ZFW/ZFWCG
> 
>     5. Now the block fuel also changes

**Tested it again.**
Overall Rating: Good
Conclusions of the testing: The issue of my first test is fixed. Works now perfectly!

**Comment by danbw9** [comment]
Category: QA Test
Name: danbw9#7028
Date of testing: 16/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1972
Object of test: Testing the dynamic changes in ZFW and ZFWCG values precomputed

Testing technique: Try out

Load up C&D in EKCH on stand. Setting up as per usual.  - DIFRSIPP - on INIT B page. 
- first preload current figures via RSK1 but not input; same figures seen before
- change ZFW via MSFS fuel planner and try preload via RSK1 the figures into scratchpad and enter them in
- RSK3 for fuel planner and get a fuel figure which does not match the actual fuel. Can be corrected manually.
- Did another startup and got same result. 

Issues (If Any): Small bug as detailed below. 
Overall Rating: Good
Conclusions of the testing: Mostly good. Initially when it first made RTT I had the variable fuel issue as is noted above in another testing report. That has been updated. I did notice however in this version, when I click RSK3 after INIT ZFW/ZFW CoG input, that I get an automatic fuel figure that is lower than the figure set in the MSFS fuel planner. So had 10.4 T actual and it showed 3 T of fuel by default. This could be corrected by re inputting the correct fuel figure. Thanks for this fix! It ties in pretty nicely with the INIT B calculations which were merged recently so in flight fuel planning is proper now.

**Comment by lousybyte** [comment]
> I did notice however in this version, when I click RSK3 after INIT ZFW/ZFW CoG input, that I get an automatic fuel figure that is lower than the figure set in the MSFS fuel planner. So had 10.4 T actual and it showed 3 T of fuel by default. This could be corrected by re inputting the correct fuel figure.

Not sure what you mean, but if you're talking about the value in the BLOCK field after pressing the FUEL PLANNING button, that's not related to this PR, you get the same result without it if you enter the ZFW values manually.

**Pull request merged**
