### PR TITLE
fix(mcdu): on appr, show temp sign, remove fls/final app

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

In accordance with new PERF APPR pages photos on an A320 with Honeywell FMS software revision 2, add hard sign to the temperature (this is different to A330 FMS revision 2 I previously used as reference). I also removed FINAL APP/FLS selection, pending us actually adding that feature (it is not shown in a real aircraft without the FLS feature).

I also noted that the title shows RNV rather than RNAV like us, but I'm not sure if that's specific to the loaded nav data so I didn't make that change.

## Screenshots (if necessary)

Before:
image

After:
image
image

## References

Photo on Discord from Tolip#6487.
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Check approach page temperature field with various inputs (range is [-99, 99])
- Check alignment of fields while altering values in all fields

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by MisterChocker** [comment]
I noticed the center devision (O, F, S, VLS) are still using the center alignment, can you fix that so it works the same way the take off page does?

**Comment by beheh** [comment]
One more thing I spotted: In FULL/CONF3 the star should not be small. Right now it's small in the code, but if you look at the reference image it should be large so it correctly "floats" above CONF3.

image

**Comment by tracernz** [comment]
Rebased and addressed both feedback items. I've added annotated pictures to the main PR text.

**Review by beheh — APPROVED** [review]

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 08/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4305 
Tier of testing: 1
Changes to observe: MCDU APPR page

**Steps you've made to test the Pull Request:**
1. Loaded inflight with a flight plan
2. filled out the MCDU pages
3. checked APP PERF page temp inputs
4. checked different inputs and page´s format

**Media:**
image

**Issues (If Any):** - 

**Conclusions of the testing:** LGTM, PR changes do work

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 8.04.2021
Version of the sim: 1.14.6.0
PR Tested: #4305
Tier of testing: 1
Changes to observe: MCDU APPR page improvements
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned on runway at EDDP
2.) Took off to EDDB
3.) Set up APPR page (Image1)

Media:


Image1

Issues: -

Overall Rating: Good

Conclusions of the testing: Looks good

Hope this helps :-)

**Pull request merged**
