### PR TITLE
feat(fmgc): re-initialization of fmgc variables after landing

### LINKED ISSUE #288: Reset MCDU after finished flight
Would there be any way to reset the MCDU after a flight so it's ready for the next, for me to do a turnaround?
I input new from/to airports in INIT page but plane still thinks its on previous flight (Approach mode still activated etc..)
Thank you!

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #288

## Summary of Changes

This will introduce the reset of the fmgc after landing

- [x] create reusable variable initialization
- [x] add variable re-initialization to flight phase initialization
- [x] add flight plan reset/clear

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Perform a flight and monitor a "complete fmgc reset"* after landing when the fmgc transitions into done phase.

* Every entered value has to be cleared (will be cleared)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
This is the same approach I had in mind. Looks good so far. 👍

**Comment by MisterChocker** [comment]
> This is the same approach I had in mind. Looks good so far. 👍 

What I don't like about this approach tho is that you remove the proper deceleration of every variable. I am honestly thinking about adding all variables back to the constructor, but only not defining the variables "default" value. This way we follow JS proper variable declaration again and the IDE are also not longer confused, because they think the variable is not defined (they are kind of right)

**Review by tracernz — APPROVED** [review]
Code LGTM

**Comment by sidnov** [comment]
QA Report

Object of testing: #5048 
Tier of Testing: 1
Date: 12/06/2021

Testing Process: 
Short IFR Circuit pattern with fully filled flightplan (departure, arrival, one enroute waypoint). Spawned C/D, filled INIT A and B, FPLN, PERF. Departed VABB runway 27, flew a circuit pattern manually using AP/FCU. Filled APPR PERF on downwind, and did a full stop landing. After ROLLOUT phase, MCDU resets to the initial page. All entered data resets with amber boxes, PERF page reset to TAKE OFF, ND shows PPOS on wpt indicator as all waypoints are deleted.

Negatives: None
Testing Results: Passed

Conclusions: Much awaited feature! LGTM 😄

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5048
Tier of Testing: 1
Date: 12/6/2021

Testing Process:

1. Spawned on runway
2. Did a circuit (at KPHX)
3. After landing went through FMGC to verify reinitialization
4. Repeated steps 2 and 3 using autoland

Negatives: After FMGC reinitialization, the decelerate point on the navigation display is still present (easy fix?) (check media)
Testing Results: Passed

Conclusions: No further issues occurred during this testing.
Media: 
Capture

**Comment by MisterChocker** [comment]
@AviationSpotter I've addressed the issue.

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5048
Tier of Testing: 1
Date: 13/6/2021

Testing Process:

1. Spawned on runway
2. Circuited twice (KPHX)
3. Verified reinitialization

Negatives: N/A
Testing Results: Passed

Conclusions: Tested with two circuits, the reinitializations were checked and no issues were found. Confirmed previous issue has been fixed.

**Pull request merged**
