### PR TITLE
[ND] Fix weather radar not showing after switching to plan view

### LINKED ISSUE #2125: [BUG] ND - Meteo radar not displayed after a plan view
**Mod Version**

"2020-11-27T05:59:37+00:00"

**Describe the bug**

 when I switch to Plan view and return to Arc view mode for Navigation Display, Meteo is no longer displayed

**To Reproduce**

1.  in flight, on ND, I use  Arc view mode and WT+Turb view mode
2.  when I switch to Plan view and return to Arc view mode, Meteo is no longer displayed
3. in order to display meteo again, I shall change the meteo mode.

**Expected behavior**

Meteo shall stay displayed after a passage in Plan view mode.

**Actual behavior**

 when I switch to Plan view and return to Arc view mode for Navigation Display, Meteo is no longer displayed

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by ilyeshammadi**
Fixes #2125

## Summary of Changes

Fixed the issue of weather being selected but not showing-up after switching to PLAN mode.

## Additional context

Discord username (if different from GitHub): Union Araken#4083

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: Current date 30/11/2020
Version of the sim: 1.11.6
PR Tested: #2134
Object of test:  Weather radar not showing after switching to plan view

Testing technique: Loaded c/d and preformed a short flight. 
Steps you've made to test the Pull Request:
1. Found the airport with the worst weather conditions at the moment   
2. Enabled weather radar 
3. Switching modes on ground
ezgif com-gif-maker (1)
  
4. Switching modes in air
ezgif com-gif-maker (2)


Flight notes (If required): N/A

Issues (If Any): N/A 
Overall Rating: Good
Conclusions of the testing: Looks good to me

**Comment by tjburni** [comment]
Category: QA Tester
Name: tjburni #0409
Date of testing: Current date 30.11.2020
Version of the sim: 1.11.6
PR Tested: #2134
Object of test: Weather Radar not showing after plan view

Testing technique:
1. Loaded Weather Preset Rain 
2. turned weather radar on
3. switched between the modes in different phases of the flight
4. landed


Flight notes (If required):

Issues (If Any):none 
Overall Rating: Good
Conclusions of the testing: No problems for me. Looks good

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek #1436   (used to be Carter633 - now changed it FYI!)
Date of testing: Current date 30/11/2020
Version of the sim: 1.11.6.0
PR Tested: #2134
Object of test: Fix for Wx Radar sometimes not showing after switch to plan mode

Testing technique: Tested as best as I can given current conditions of the sim post-patch

1. Spawned Cold & Dark EGCC
2. During taxi, switched Wx Rad on/off to check display, switched to Plan and back to ARC, Wx on/off
3. Departed on the wild ride that we must now endure, checked Wx working against plan multiple times
4. Landed

Issues (If Any): None identified
Overall Rating: Good
Conclusions of the testing: No issues found with this.

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#8145
Date of testing: Current date 11/30/2020
Version of the sim: 1.11.6
PR Tested: #2134 
Object of test: Weather radar bug

Testing technique: Switched to PLAN then turned the radar on.
Steps you've made to test the Pull Request:

1. Loaded in at KARB (snowy day)
2. Turned WX on
3. Turned WX off
4 Switched to PLAN
5. Turned WX back on.

Flight notes (If required): None. Worked like a charm.

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: LGTM. Great work!

**Pull request merged**
