### PR TITLE
[ECAM] Improve packs indication

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #[issue_no]

## Summary of Changes

- Made activation condition for PACKS more advanced.
- Depended on if engines are on or off, if engine bleed is on or off, if X Bleed is open or closed and if packs are on or off

## Screenshots (if necessary)

image
image
Only if APU AVAIL and APU BLEED ON
image

## References

image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by HugoTro** [comment]
Name: Hugo #3307
Date of testing: Current date DD/MM/YYYY
Version of the sim: Version the tester uses
PR Tested: #2527 

Testing technique: Before/After
Steps you've made to test the Pull Request:
1. Spawned in C&D with the master 
2. Experienced a bit with the packs
3. Installed the PR
4. Launched the sim and respawned in C&D
5. Saw that conditions to have packs on were met (or not) and different results were observed with X bleed open, shut, eng packs on or off, etc

Overall Rating: Good!
Conclusions of the testing: I didn't find any issues that are PR related (Found a weird bug with liveries lol)

**Comment by valenzz2004** [comment]
Category: QA Tester
Name: Valenzz2004#7802
Date of testing: 20/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2527 
Object of test: test packs indication

Testing technique: full departure 
Steps you've made to test the Pull Request:

1. Loaded in to a stand at EGNT and prepped aircraft for circuits
2. turned packs off for engine start
3. push and start then i changed weather to snow( to check warnings)
4. departed and went into dense cloud with
5. flew touch and goes and message at top ecam only appeared on the ground, or thrust settings MCT/MAN FLEX/MAN TOGA
6. also tested if messages were able to appear independently


Flight notes (If required):

Issues (If Any):
Overall Rating: Good
Conclusions of the testing: worked as expected in accordance with spreadsheet provided in references and messages worked during engagement of the anti-ice systems
Screenshots( if any):

ENG start config
eng start config

Message on ecam after packs engaged after engine start
packs on ecam

on thrust mode TOGA after dep with anti ice on
packs

Tests on if messages show up independently 
wai
nai

**Comment by MisterChocker** [comment]
Thanks for the testing! Good to hear everything works as it should.

**Pull request merged**
