### PR TITLE
fix(mcdu): perf page

### LINKED ISSUE #3348: [BUG] Performance Pages DES and APP disappear and become [Untitled] after performing WX Request
**Mod Version**

"built": "2021-02-05T07:14:46+00:00",
  "ref": "master",
  "sha": "b0d5993637530589055bfed267d7586d3a846ce3",
  "actor": "ZigTag",
  "event_name": "manual"

**Describe the bug**

Performance Pages für DES and APP disappear and become [Untitled] after performing WX Request. 

**To Reproduce**

1. Started the A320N Cold and Dark and Initialized a flightbrief via the Simbrief connection of the A320NX
2. Initialized, set up speeds and values for each performance pages from Takeoff to Approach
3. Did a WX Request METAR and Printed it out
4. Re-checked the performance pages and DES and Approach were gone, replaced with a blank page that says  [untitled]

**Expected behavior**

 I expect the WX request not to have any effect on the performance pages

**Actual behavior**

Performance pages of MCDU disappeared

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #3348

## Summary of Changes

- Reason was `this.this`

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Do normal flight, observe perf page

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by ko-zone — APPROVED** [review]
LGTM

**Review by Benjozork — COMMENTED** [review]
LGTM

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 06/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3372 
Tier of testing: 2
Changes to observe: PERF pages after a WX request

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned in C&D
2. Request LFRS metar via the AOC menu
3. Printed it after receive
4. Checked all PERF pages



Media: https://youtu.be/tXHBQbqRHQA

Issues (If Any): None found

Overall Rating: Good
Conclusions of the testing: LGTM

**Review by tyler58546 — APPROVED** [review]

**Pull request merged**
