### PR TITLE
[CDU] Fix ascend constraint algorithm

### LINKED ISSUE #2390: [BUG] Altitude constraints from STAR are being used during departure
**Mod Version**
{
  "built": "2020-12-08T08:51:29+00:00",
  "ref": "",
  "sha": "",
  "actor": "pepperoni505 <49950581+pepperoni505@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

Altitude constraints from STAR being used by AP during departure
Using the following route which I entered manually
LSZH/16 VEBI3S VEBIT T51 LASUN UN176 LUMEL UT10 RLP UL613 DIDOR UT10 ALESO ALES1H EGLL/27R
FL360

The SID has 7 constraints
2000 not before D1.0 KLO
2500 at D2.1 KLO
+4000 at KLO R180/R360
+4000 at KLO R360
+5000 at BREGO
+6000 at ZH554
+7000 at ZH558

Initial clearance was FL100 - then I stopped using ATC and set to cruise (FL360) in managed climb mode, however the PFD showedFL180 in magenta and did not climb past it. The FL180 constraint is the first constraint from the ALES1H STAR (FL180 at ETVAX). I have had this issue on other flights where the STAR has altitude constraints.

**To Reproduce**
1. Enter flight plan as above
2. Takeoff and set altitude to anything above FL180

**Expected behavior**
Once passing D2.1 KLO - any altitude selected above FL70 (and also FL180) should be blue and the aircraft should continue to climb in managed climb mode

**Actual behavior**
Altitude above FL180 is magenta and aircraft will not climb past FL180 unless in open climb mode

**References**

[IMG_0716.zip](https://github.com/flybywiresim/a32nx/files/5683414/IMG_0716.zip)

**Additional context**

Was this working before/when did the issue start occurring?
It has been a problem for about 2 weeks

Is this a problem in the vanilla unmodded game?
I am not sure

Discord username (if different from GitHub):

This is my first issue report so apologies if it is not submitted correctly. I have searched both open and closed issues and I don't see one that directly matches this issue (although I can confirm that all constraints are being read as below xxx instead of at or above as applicable but I see that is a separate issue that is already reported).

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #2390

## Summary of Changes

- Added altitude prediction to get a rough estimate of TOC (NOT THE ONE VISIBLE ON ND)
- Added constraint refresh to departure and arrival modifications as well as CRZ FL change
- Added `mcdu.updateTowerHeadwind()` to the arrival change update

Goal of this PR: Fix interference of STAR constraints during climb

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by wpine215 — APPROVED** [review]

**Comment by MisterChocker** [comment]
For testing, this route previously didn't worked which should also be tested.
`LSZH/16 VEBI3S VEBIT T51 LASUN UN176 LUMEL UT10 RLP UL613 DIDOR UT10 ALESO ALES1H EGLL/27R`
CRZ FL360

**Comment by Highflyer2010** [comment]
Category: QA Tester
Name: Discord User Highflyer2010#8932
Date of testing: Current date 16/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2447 
Object of test: [CDU] Fix ascend constraint algorithm

Testing technique: Test the suggested route for constraint algorithm

Steps you've made to test the Pull Request:

1. Loaded Sim and loaded Aircraft C&D
 
2. Spawned at LSZH at a gate

3. Setup Aircraft , Ext Pwr, Batteries ect...
 
4. Created flightplan using Simbrief but using the suggested flightplan. LSZH/16 VEBI3S VEBIT T51 LASUN UN176 LUMEL UT10 RLP UL613 DIDOR UT10 ALESO ALES1H EGLL/27R
CRZ FL360

5. MCDU setup, Pushback, Taxi, Take off RWY 16

6. Autopilot on after take off 

7. set ALT for Decent

8. Pressed ALT knob for decent

9. turned autopilot off for landing 


Flight notes (If required): 

Issues (If Any): 

1. Ignores Alt constraints on climb
2. Climbing at a hight rate +5000 FPM









Overall Rating: Meh... 

Conclusions of the testing: although a few teething problems it did see the TOC icon it kept moving forward between 2nm to 2.5nm ahead until i actually reached TOC then it dissappeard. TOD is 104nm from the filed flight plan going by simbrief there was no TOD Icon. A nice steady decent with an altitude constrain of FL070 upon hitting TIGER -FL180 250kts waypoint i was at FL190. I kept getting a white arrow infront of the aircraft icon. the aircraft followed the constrain of FL070 but did not decent in time as i was too high for approach i had to press the OP DECENT for the aircraft to decend. I decended in time to catch the ils but was a rush i've attatched some screenshots

**Comment by MisterChocker** [comment]
> 1. Ignores Alt constraints on climb

That SID has no alt constraints.

> Climbing at a hight rate +5000 FPM

Not related to this pr

> problems it did see the TOC icon it kept moving forward between 2nm to 2.5nm ahead until i actually reached TOC then it dissappeard

I am not changing the TOC or anything on the ND

> D is 104nm from the filed flight plan going by simbrief there was no TOD Icon. A n

Again not related to this pr

Sorry to say but your QA test doesn't really show the flaws, please improve your testing and documentation technique because I can absolutely not follow anything because there is simply no documentation on whats actually happening.

**Comment by valenzz2004** [comment]
Category: QA Tester
Name: Valenzz2004#7802
Date of testing: 19/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2447
Object of test: [CDU] test ascend constraint algorithm

Testing technique: flew a full IFR flight (lppt-lemd)
Steps you've made to test the Pull Request:

1. Loaded in c/d at a stand at terminal 1 LPPT
2. used simbrief implementation to get fpl
3. selected to INBOM4N to test constraint refresh
3. selected IDBID4N SID with constraints
4. made sure constraints were identified (screenshots)
5. set initial climb 6000 (managed altitude mode)  on purpose to see if aircraft would comply with constraints 
6. planned arrival TLD6A
7.  taxied to active runway (RWY03)
8. departed and engaged autopilot at 1000ft
9. climbed to crz FL360 using Managed altitude mode
10. changed  crz FL380 on init page in MCDU
11. step climb to FL380 and ap acknowledged as the new crz level
12. did ils app and landed 18R
 

Flight notes (If required):

Issues (If Any):
-the constraint didn't actually hold me at the required altitude at the waypoint (idbid).
-couldnt find TOC (QA Tester error)
Overall Rating: Good
Conclusions of the testing: i believe this fixes the issue found in #2930 but not sure if related to this pr but i did also experience steep climb rates
Screenshots( if any):
navigraph sid pic
mcdu constraint pic

ARRIVAL
navigraph ss
Ac

**Comment by MisterChocker** [comment]
> -the constraint didn't actually hold me at the required altitude at the waypoint (idbid).

For SID I only see AT OR ABOVE 2000 and 4000ft constraints which are ignored by the ap in climb intentionally.

The actual functionality of the changes made by this pr cant be tested with the STAR you provided due to no AT OR BELOW constraints in that route.

**Comment by MisterChocker** [comment]
To give more instructions, if not using the example route, ensure you STAR has constraints type AT OR BELOW.

**Comment by Road-to-Hell9** [comment]
Category: QA Tester
Name: Road_to_Hell9 #1111
Date of testing: 19/12/2020

Version of the sim: 19/12/2020

PR Tested: #2447
Object of test:[CDU] Fix ascend constraint algorithm

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1.Hot start at LOWW RWY 11 Lugem 1 AR
2.Autopilot set to managed climb to FL 200 and speed managed
3.Takeoff
4.Autopilot on ASAP
5.

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Departure worked flawlessly
Screenshot (122)
Screenshot (123)
Charts 2 RWY 11
ND 1
Charts RWY11
Screenshot (121)

**Comment by MisterChocker** [comment]
@Road-to-Hell9 what was you STAR?

**Comment by Road-to-Hell9** [comment]
I haven't Made an approach, but u can if you want

**Comment by MisterChocker** [comment]
> I haven't Made an approach, but i can if you want

You don't need to fly an approach, you need to enter the data to see if the changes actually work.

**Comment by Road-to-Hell9** [comment]
Category: QA Tester
Name: Road_to_Hell9 #1111
Date of testing: 20/12/2020

Version of the sim: 20/12/2020

PR Tested: #2447
Object of test:[CDU] Fix ascend constraint algorithm

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1.Hot start at LOWI NANIT 2 A Star
2.Autopilot set to managed decent to 4000 FT and speed managed
3.
4.
5.

Flight notes (If required):

Issues (If Any): The autopilot ignores the CRTS, this could be due to the unfinished database of the FS
Overall Rating: Could be improved (to sure who to blame)
Conclusions of the testing: Arrival 
LOWI charts 3
LOWI charts 2
LOWI charts 1
Screenshot (129)
Screenshot (131)

**Comment by MisterChocker** [comment]
Not the target of this pr, also from the screenshots you provided the constraints shown are intentionally ignored.

**Comment by Road-to-Hell9** [comment]
So what schould I do to not block them

**Comment by MisterChocker** [comment]
You could insert them manually.

**Comment by Road-to-Hell9** [comment]
Where?

**Comment by MisterChocker** [comment]
> Where?

On the VERT REV Page of the waypoints but nvm we are currently not able to change those (the arrival fixes)

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 12/21/2020
Version of the sim: 1.11.7.0
PR Tested: #2447  
Object of test: [CDU] Fix ascend constraint algorithm.

Testing technique: Did the flight route approved.

Steps you've made to test the Pull Request: 
1. C&D - Flightplan insertion.
2. Take off and climb to 360.
3. Tried a Stepclimb to 380 without issues.
4. Descented to 10 000ft and did the fly in manually cus of some bad flightpath (not a issue due to this PR but just mentioning).



Flight notes (If required): Everything went well through take off, climb and descent.

Issues (If Any): Not related to this PR.

Overall Rating: Good.

Conclusions of the testing: All good 👍🏻 

Screenshots:

**Comment by Noxleee** [comment]
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 21/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2447 
Object of test: ascend constraint algorithm

Testing technique: Test departure with LAM2X SID at Gatwick
Steps you've made to test the Pull Request:
1. Load up AC on rw26r
2. Load flight plan with simbrief
3. Fly the SID

Flight notes (If required):
Flight plan -> EGKK LAM2X LAM N57 WELIN T420 TNT DAYN2A EGCC
Constrains -> All these (except the first) are AT or BELOW!
grafik
grafik
grafik

Issues (If Any): 

- No altitude prediction in the MCDU on Flight plan page, after SID first altitude is FL300
- The constraints of the SID are all at or above if you don't modify them.
- First waypoint after SID has no Altitude in the flight plan page (After departure, on ground it had FL300):
grafik


Overall Rating: To be improved
Conclusions of the testing: I tested the SID LAM2X out of London Gatwick. It has many at or below constrains. These constrains are automatically programmed in the MCDU, but with the wrong sign. All constrains have a + instead of –/no sign. So, you have to modify them. After modification, the AC respects all constrains.
I cannot find the mentioned prediction of the altitudes. The first waypoint after the SID has FL300, but after departure it changed to the value, as shown in the last screenshot.

**Pull request merged**
