### PR TITLE
[PFD]Port of AltimeterIndicator.js mods into 1.8.3.0 (WIP)

### PR DESCRIPTION
**Pull request by JackZ974**
Incorporated the previous mods into the latest altimeterIndicator.js code from Asobo, namely #616, #558, #515 and all the mods related to Altimeter.js into the PFS area
The Altimeter scale seems to be working, but see note below

IMPORTANT NOTE:

the Update_fail() routine code seem to cause problems in the new configuration (see console log picture). 

Fixes #[issue_no]
Ports #616 mod into 1.8.3.0 and added previous PR also
**Summary of Changes**

**Screenshots (if necessary)**

#616 is ok, but 
image

**Additional context**

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by UncleClapton** [comment]
Looks like there's multiple references to removed class variables which is causing the errors.

**Comment by JackZ974** [comment]
> 
> 
> Looks like there's multiple references to removed class variables which is causing the errors.

You are probably right, but I don't know how to track these, they are all over the place. For my added code, it's ok since it didn't called any ext class variables. 
I noticed that a lot of var were replaced by let in the new Asobo code, could be part of the problem?

**Comment by UncleClapton** [comment]
I have a branch that has a working `AltimeterIndicator` along with a WIP Airspeed, Attitude, and ILS indicators. Should we close this in favor of that?

**Comment by JackZ974** [comment]
sure if you've incorporated this WIP into yours

**Comment by AdenFlorian** [comment]
closing in favor of claptons PR: https://github.com/flybywiresim/a32nx/pull/770

**Pull request closed without merging**
