### PR TITLE
feat(mcdu): h3 init/fuel pred pages

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Update behaviour of init and fuel pred pages and the FUEL key to H3.

## References

Various docs, FCOM, pilot tests
init-fuel-pred-2
fuel-pred

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check that INIT FUEL PRED can only be accessed with engines off, **auto-switch from INIT FUEL PRED to FUEL PRED shortly after an engine start**. Ways to access INIT FUEL PRED with engines off are go to INIT A and scroll left or right, or press FUEL PRED key on the MCDU... to access FUEL PRED with engines on, same as for INIT FUEL PRED with engines off.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by bouveng — APPROVED** [review]

**Comment by mico975** [comment]
Passed after the fix, updated the test report above.

**Comment by beheh** [comment]
@tracernz How about we add a test case to be on INIT FUEL PRED, and then we start an engine? To my knowledge that should also redirect you to the normal FUEL PRED page.

**Comment by tracernz** [comment]
> @tracernz How about we add a test case to be on INIT FUEL PRED, and then we start an engine? To my knowledge that should also automatically redirect you to the normal FUEL PRED page.

I did briefly cover that in the test notes:
> auto-switch from INIT FUEL PRED to FUEL PRED shortly after an engine start

I've also tested it myself. I'll emphasize that part for any further tests..

**Comment by LeDerpLegend** [comment]
Quality Assurance Trainee Report

Discord : LeDerpLegend#1019
Object of testing: #6877 
Tier of Testing : 1
Date : 13/03/2022

Testing Process:
Check that INIT FUEL PRED can only be accessed with engines off - **GOOD**
Auto-switch from INIT FUEL PRED to FUEL PRED shortly after an engine start. - **GOOD**
Ways to access INIT FUEL PRED with engines off are go to INIT A and scroll left or right - **GOOD**
Or press FUEL PRED key on the MCDU - **GOOD**
To access FUEL PRED with engines on, same as for INIT FUEL PRED with engines off. - **GOOD**

Negatives:
N/A

Testing Results:
PASSED

Conclusions:
INIT FUEL PRED only accessible with engines off.
INIT FUEL PRED auto switches to FUEL PRED on engine start
FUEL PRED is the set page when engine(s) is/are running
INIT FUEL PRED is accessible again when engines are off

**Comment by mico975** [comment]
> @tracernz How about we add a test case to be on INIT FUEL PRED, and then we start an engine? To my knowledge that should also automatically redirect you to the normal FUEL PRED page.

I tried it with first test and it works 😄 just didn't emphasize it in the report

**Pull request merged**
