### PR TITLE
revert: remove pixels (after SU6)

### LINKED ISSUE #6097: Remove pixel filter to use native MSFS pixel filter
### Describe the bug

As title says. Issue requested by @bouveng.

### Discord Username (optional)

someperson#4953

### PR DESCRIPTION
**Pull request by 2hwk**
## Summary of Changes
Fixes #6097

Reverts our pixels implementation because of the new subpixel LCD effect that was added in SU6. Keeps the bleed effect + tint.

Discord username: 2Cas#1022

## Testing instructions
1, Spawn
2, Verify that the pixel filter is removed from PFD, ND, EICAS, MCDU and DCDU. (Subpixels should be there still).

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
We might need to lower LCDU resolution to 768x768 for MSFS pixels to be visible.

**Review by bouveng — APPROVED** [review]

**Comment by 2hwk** [comment]
> We might need to lower LCDU resolution to 768x768 for MSFS pixels to be visible.

Too much of a pain to work with the old JS displays, on afpm since only upper ECAM is affected this has been implemented.

**Comment by Benjozork** [comment]
> > We might need to lower LCDU resolution to 768x768 for MSFS pixels to be visible.
> 
> Too much of a pain to work with the old JS displays, on afpm since only upper ECAM is affected this has been implemented.

Can't we do the react displays at least ?

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #6110
Tier of Testing: 1
Date: 31.10.2021

Testing Process: 
C&D - power on, displays on and full brightness

Negatives: no sub pixels visible

Testing Results: it seems on purpose that the pixelation is gone reading the above comments 

Conclusions: Not passed if we want to keep the pixelated look. If we don't want to keep it it is passed. 

Media:

Before:
2021-10-31_12h09_45
2021-10-31_12h12_17

After:
2021-10-31_12h54_03
2021-10-31_12h54_21

**Comment by frankkopp** [comment]
Updated my test comment above.

**Review by davidwalschots — APPROVED** [review]

**Comment by John-UK** [comment]
Quality Assurance Tester Report

Discord: john P Maguire#9027
Object of testing: #6110
Tier of Testing: 1
Date: 3/11/2021

Testing Process:
C&D at EGLL same time of day compared ND at extreme zoom in experimental with PR 6110.  FBW pixilisation has been removed.

Testing Results: passed

Negatives: None IAW the PR

Conclusions:
No average user will seen the default pixilisation in normal use. See comparison pics on DISCORD QA.

Media
See comparison pics on DISCORD QA.

**Comment by John-UK** [comment]
Quality Assurance Tester Report

Discord: john P Maguire#9027
Object of testing: #6110
Tier of Testing: 1
Date: 3/11/2021

Testing Process:
C&D at EGLL same time of day compared experimental with PR 6110.  FBW pixilisation has been removed.

Testing Results: passed

Negatives: None IAW the PR



Conclusions:
No average user will seen the default pixilisation in normal use. See comparison pics on DISCORD QA.

Media
See comparison pics on DISCORD QA.

**Pull request merged**
