### PR TITLE
feat(hyd): Hydraulic leak measurement valves

### PR DESCRIPTION
**Pull request by crocket63**
Fixes #[issue_no]

## Summary of Changes

First basic implementation of hydraulic leak measurement valves.

While this is not really important for normal operations, some interesting behaviours can appear if they are simulated correctly, be it with failures or if their response time is too slow (moving ailerons when cargo door activated for example)

- [x] Connect overhead buttons to system
- [x] Basic implementation
- [x] Electrical supply
- [x] Automatic control logic (cargo door operation / plane speed...)

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Overview: 
Leak valves are separating the pressure sensor from the pressure system switch in the hydraulic system.

So when a leak valve is closed, we expect to still read nominal pressure from the system sensor as shown in simvar A32NX_HYD_{loop_name}_SYSTEM_1_SECTION_PRESSURE

BUT the pressure downstream of the valve will drop, and downstream switch will go OFF
A32NX_HYD_{loop_name}_SYSTEM_1_SECTION_PRESSURE_SWITCH

1. Check all possible hydraulic consumer, they should work as before and impact hydraulic system as before.

2. Yellow epump run from cargo door operation (by requesting baggage service) should not cause any flight control movement (leak measurement valve auto closed).

3. Yellow epump run manually (Yellow epump button illuminated ON) should impact flight controls as before (aileron/rudder/elevator go from droop to center position)

4. Closing any leak measurement valve on ground (full aft of overhead panel) should impact connected hydraulic consumers.
Looking at the reference below, for exemple all valve closed you should still have flaps/slats available, but no flight controls.
https://www.researchgate.net/profile/Aymen-Labidi/publication/342877726/figure/fig2/AS:912422856585217@1594549969679/Hydraulic-System-in-Airbus-A320-and-Skydrol-circulation-circuit.png

5. Closing leak measurement valves in flight shouldn't have any impact, all flight controls should respond (closing disabled at speed > 100kts)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by beheh — APPROVED** [review]

**Comment by beheh** [comment]
@crocket63 Could you update the testing instructions so they're a little clearer with regards to expected button illumination, display, etc.? Right now it's relatively hard for a non-hydraulics expert to perform the suggested testing instructions.

**Comment by crocket63** [comment]
> @crocket63 Could you update the testing instructions so they're a little clearer with regards to expected button illumination, displays, etc.? Right now it's relatively hard for a non-hydraulics expert to perform the suggested testing instructions.

Trying :p To be fair real pilots probably do not care about those valves either :D 

Sadly the more visual things will only come with ecam screen update.

**Comment by beheh** [comment]
Otherwise maybe any LVars people can look at?

**Comment by crocket63** [comment]
> Otherwise maybe any LVars people can look at?

Indeed! Less sexy than ECAM but should do the job :)

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #6342
Tier of Testing  : 1
Date             : 06/04/2022

Testing Process: 
So when a leak valve is closed, we expect to still read nominal pressure from the system sensor as shown in simvar A32NX_HYD_{loop_name}_SYSTEM_1_SECTION_PRESSURE - **OK**

BUT the pressure downstream of the valve will drop, and downstream switch will go OFF
A32NX_HYD_{loop_name}_SYSTEM_1_SECTION_PRESSURE_SWITCH - **OK**

Check all possible hydraulic consumer, they should work as before and impact hydraulic system as before. - **OK**

Yellow epump run from cargo door operation (by requesting baggage service) should not cause any flight control movement (leak measurement valve auto closed). - **OK**

Yellow epump run manually (Yellow epump button illuminated ON) should impact flight controls as before (aileron/rudder/elevator go from droop to center position) - **OK**

Closing any leak measurement valve on ground (full aft of overhead panel) should impact connected hydraulic consumers. - **OK**

Closing leak measurement valves in flight shouldn't have any impact, all flight controls should respond (closing disabled at speed > 100kts) - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Nice one

**Pull request merged**
