### PR TITLE
fix: update runs with deltaTime of -1

### PR DESCRIPTION
**Pull request by davidwalschots**
## Summary of Changes
The expression `_deltaTime === -1 && !KnobChanged` causes the update to run whenever the knob has changed. As the `updateThrottler.canUpdate` function might have returned `-1`, this could cause the update to run with a `-1` delta time.

This PR corrects that behaviour and makes it easier to force an update with the correct delta time.

## Additional context

Discord username (if different from GitHub): SjotgunSjonnie#9623

## Testing instructions

The displays still update as expected:
- The navigation displays updates at a quicker rate when making a turn.
- Turning the PFD, ND and ECAM displays ON/OFF is immediate.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]
LGTM

**Review by XSJoJo — APPROVED** [review]

**Review by tracernz — APPROVED** [review]
Good catch. 👍

**Comment by Samueleonard** [comment]
Category: QA Tester
Name: 1Samueleonard1#0001
Date of testing: Current date 10/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4367
Tier of testing: 1

Changes to observe: check displays still work

Testing technique: Tryout
1. loaded in C+D, turned on power
2.  switched screens on/off - no delay
3. changed ECAM pages - no delay


Flight notes: n/a - everything still works 

Media: n/a

Issues: n/a

Steps to achieve the issue n/a

Overall Rating: Good

Conclusions of the testing: still works - lgtm

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing:  11.4.2021
Version of the sim: 1.14.6.0
PR Tested: #4367 
Tier of testing: 1
Changes to observe: ND Update Changes

Testing technique: TryOut
Steps you've made to test the Pull Request:
1.  Spawned C&D at LSZR
2.  Turned on the Aircraft
3.  Switched and to different modes and ranges
4.  Drived the Acft around to see the nd when turning

Media: n/a
Issues (If Any): none

Overall Rating: Good
Conclusions of the testing: ND still works as it should and turns off immediately. Turns also look good and smooth.

**Pull request merged**
