### PR TITLE
fix(sim): only shown nav radio tip once

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Only show the tip when attempting to tune nav radios by key events while the FMGC is controlling them once. ~~Remove the tip when attempting to tune nav radios by key events while the FMGC is controlling them.~~ This is supposed to help people that have hardware setups to understand why they can't set the nav radios while the FMGC is controlling them, but it received a few complaints due to other software spamming these events. ~~Instead we silently ignore them.~~

## Additional context

Discord username (if different from GitHub):

## Testing instructions

None?

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by beheh — APPROVED** [review]

**Comment by frankkopp** [comment]
Maybe we should show it once and then remember that it has been shown?
The message makes sense for many users, right?

**Comment by sai-darshk** [comment]
Title: fix(sim): remove nav radio tip
Quality Assurance Tester/Trainee Report
Discord: sailuvsprans#1083
Object of testing: (#7975)
Tier of Testing  : (1)
Date: 2023-04-23


Testing Process: 
Simulator was started and the FMGC was enabled. I attempted to tune the nav radio by key events and the tip did not appear.
Negatives:       
N/A


Testing Results: 
(Passed)


Conclusions: 
The test was successful. No tip was displayed at any time. The change has been tested and it works as expected.

**Comment by tracernz** [comment]
Updated to only show the tip once. Please review @frankkopp

**Review by frankkopp — APPROVED** [review]
LGTM

**Pull request merged**
