### PR TITLE
fix(#7614): mousewheel switches

### LINKED ISSUE #7614: [Dev Version] Wing light not toggleable
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-11-26T14:29:23+00:00",
    "ref": "refs/heads/master",
    "sha": "7d9e36c551a73705a64662c318a145f2ea8aaff3",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:7d9e36c5"
}
```

### Describe the bug

Wing Light can be turnt on (only left wing), yet is stuck in "ON" position with light showing on the left wing.

### Expected behavior

Wing Light should be toggleable

### Steps to reproduce

1. Turn on Wing Lights
2. Try turning off Wing Lights

### References (optional)

https://user-images.githubusercontent.com/96501232/204109508-c7b8e312-f1ec-4a67-a440-8706a30a3371.mp4

### Additional info (optional)

_No response_

### Discord Username (optional)

Stuart#0420

### PR DESCRIPTION
**Pull request by patsta32**
Fixes #7614

## Summary of Changes

Fixed (closing) tags in switch modelbehaviour for nav lights and wing lights.
Wing Lights and Nav Lights switches should now work correctly

## Additional context

Videos of all switches changed in #7605 which should now work correctly!

https://user-images.githubusercontent.com/12295003/204154332-b2816930-de15-4a65-8894-0227496abb23.mp4

https://user-images.githubusercontent.com/12295003/204154408-8d22673f-bbbe-42d2-8086-0fab45ce3a32.mp4

https://user-images.githubusercontent.com/12295003/204154457-1d74231a-e8ac-4da6-8a89-f0c3409a02c1.mp4

https://user-images.githubusercontent.com/12295003/204155263-a589c9cc-789b-45a3-8b6f-79fad2be7f37.mp4

Discord username (if different from GitHub): patsta32

## Testing instructions

Try following switches for correct functionality (mousewheel/left-click):

### Switches

**Overhead Panels**

- Beacon: Beacon Lights on top and on the bottom of the aircraft should be switched on/off.
- Wing Lights: Lights illuminating both wings should be switched on on/off.
- Nav&Logo: Navigation (Red/Green left and right wing, white light on the tail) and Logo Lights should be switches on/off.
- Runway turn off: Left/Right runway turn off taxi lights on the nose landing gear should be switched on/off.
- Seatbelt: Seatbelt signs should be switched on/off.

**Radar Panel**

- Predictive windshear Off/Auto: switch should work and should be recognized by ecam

**RMP Panel**

- RMP Radio On/Off: Should switch radio and lights for panel on/off. (both sides independently)

#### Inoperable Switches:

**Radar Panel**

- Multiscans Man/Auto: switch should work
- GCS Off/Auto: switch should work

**Overhead Panels**

- Ice Indicator & Standby Compass (ICE IND & STBY COMPASS): switch should work
- Capt & Purs / Capt Only Evac Switch: switch should work

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by frankkopp — APPROVED** [review]

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #7618
Tier of Testing: 1
Date: 27.11.22

Testing Process: 
Testing all switches with click and mouse wheel and functional check. 

Negatives: 
WING LT click only turns on one light. Can't be turned off with click. See [0]

Testing Results: WING to be fixed. Rest seems ok. 

Conclusions: Not passed

Media:
[0]
https://user-images.githubusercontent.com/16833201/204159936-fba9f31d-183e-4468-90c8-2cc56745507d.mp4

**Comment by frankkopp** [comment]
Noticed that the switches are still inconsistent with the new "LOCK" interaction system - 2-way and 3-way switch behave differently. 
 
Although we usually recommend to use "LEGACY" to users I think if possible we should make the switches work well in the "LOCK" interaction system as well - mouse-wheel and clock. Although this could actually be the way users expect the LOCK system to work. I wouldn't know as I never use it. 

Observations:
- 3-way switches can be use drag or mouse-wheel - no click
- 2-way switches have click but not mouse wheel an no drag

@patsta32  Do you know how to do this and could you double check this?

**Comment by tracernz** [comment]
Definitely needs to work with mousewheel for lock. Legacy system is... legacy and inferior.

**Comment by chotaire** [comment]
In any case something needs to be merged because I find a huge number of switches no longer working in current development version.

**Comment by frankkopp** [comment]
> Definitely needs to work with mousewheel for lock. Legacy system is... legacy and inferior.

That is a matter of taste I assume - I find the LOCK system terrible :D

**Comment by frankkopp** [comment]
> In any case something needs to be merged because I find a huge number of switches no longer working in current development version.

What interaction system do you use?
I have test LEGACY and LOCK and all switches work in both for me with one of the methods (click, wheel, drag).
In any case is "huge number of switches" definitely not correct - we had on switch before this fix PR which did not work with click. Otherwise everything worked in LEGACY.
Which switches do not work for you?

**Comment by patsta32** [comment]
I would propose to merge this PR to fix the recently introduced bug on development.
After that i would happily look into #7624 to update all 2 Way switches to work with mousewheel, drag and left click for the LEGACY and LOCK systems.

**Comment by 2hwk** [comment]
Quality Assurance Tester Report

Discord: 2Cas#1022
Object of testing: https://github.com/flybywiresim/a32nx/pull/7618
Tier of Testing: 1
Date: 29/11/22

Testing Process:

Tested with Legacy (not working in lock mode noted)

**Overhead Panels**

- [x] Beacon: Beacon Lights on top and on the bottom of the aircraft should be switched on/off.
- [x] Wing Lights: Lights illuminating both wings should be switched on on/off.
- [x] Nav&Logo: Navigation (Red/Green left and right wing, white light on the tail) and Logo Lights should be switches on/off.
- [x] Runway turn off: Left/Right runway turn off taxi lights on the nose landing gear should be switched on/off.
- [x] Seatbelt: Seatbelt signs should be switched on/off. - Does not work in lock mode

**Radar Panel**

- [x] Predictive windshear Off/Auto: switch should work and should be recognized by ecam

**RMP Panel**

- [x] RMP Radio On/Off: Should switch radio and lights for panel on/off. (both sides independently)

#### Inoperable Switches:

**Radar Panel**

- [x] Multiscans Man/Auto: switch should work
- [x] GCS Off/Auto: switch should work

**Overhead Panels**

- [x] Ice Indicator & Standby Compass (ICE IND & STBY COMPASS): switch should work
- [x] Capt & Purs / Capt Only Evac Switch: switch should work


Negatives:
- N/A

Testing Results: Good

Conclusions: Passed

**Comment by 2hwk** [comment]
Concerns with lock mode vs legacy mode should be addressed in another PR, for a hotfix this is fine.

**Pull request merged**
