### PR TITLE
refactor: W&B and boarding logic prep for EFB

### PR DESCRIPTION
**Pull request by sidnov**
Fixes #[issue_no]

## Summary of Changes

- [x] Basic optimization and rewrite for Boarding and OFP Data processing on the MCDU
- [x] Improved conversion when using LBS
- [x] Changed conversion factors overall (uniform across code, this is an experimental change, can be reverted if known to cause unnecessary effects)

## Additional context

Discord username (if different from GitHub): sidnov# 8337

## Testing instructions

1. Test the MCDU ATSU AOC W/B pages and make sure they work normally
2. Values in cargo hold now depict either Metric Tons or Metric Pounds depending on the unit selected on the EFB Settings for aircraft configuration
3. Test Simbrief loading using OFPs generated in KGs and LBS units
4. Test Manual loading with both KGs and LBS units selected.
5. Make sure the unit selected on the EFB->aircraft config is the same as the unit in Simbrief OFP generation(right hand sidebar)/airframe settings
6. Match payload and ZFW values after loading with that given in the Simbrief OFP

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by MStallen** [comment]
I'm using pop-outs, a MCP/EFIS a commo-panel and the MCDU-server to a tablet for my flights. So please don't remove the boarding option from the MCDU with this update. I can now fly without having to go inside the virtual cockpit  and I will loose that.

**Comment by sidnov** [comment]
> I'm using pop-outs, a MCP/EFIS a commo-panel and the MCDU-server to a tablet for my flights. So please don't remove the boarding option from the MCDU with this update. I can now fly without having to go inside the virtual cockpit  and I will loose that.

We'll soon be able to view the EFB on a remote device, similar to the MCDU.

**Comment by MStallen** [comment]
Yes that is nice, but than I've to buy another tablet again. I'm using already one for the MCDU and the other for foreflight, So I ask please again.

**Comment by sidnov** [comment]
> Yes that is nice, but than I've to buy another tablet again. I'm using already one for the MCDU and the other for foreflight, So I ask please again. Make it an option?

Will discuss with the devteam and consider making it an option

**Review by 2hwk — CHANGES_REQUESTED** [review]

**Review by 2hwk — DISMISSED** [review]

**Comment by 2hwk** [comment]
@sidnov Fix merge conflict, then this can go to QA

**Review by 2hwk — APPROVED** [review]

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #6969
Tier of Testing  : 1
Date             : 30/05/2022

Testing Process: 
Test the MCDU ATSU AOC W/B pages and make sure they work normally - **OK**
Values in cargo hold now depict either Metric Tons or Metric Pounds depending on the unit selected on the EFB Settings for aircraft configuration - **OK**
Test Simbrief loading using OFPs generated in KGs and LBS units - **OK**
Test Manual loading with both KGs and LBS units selected. - **OK**
Make sure the unit selected on the EFB->aircraft config is the same as the unit in Simbrief OFP generation(right hand sidebar)/airframe settings
Match payload and ZFW values after loading with that given in the Simbrief OFP - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

Media:       
image

**Pull request merged**
