### PR TITLE
fix(efb): Fix display crash on incomplete Metar Data

### LINKED ISSUE #3343: [BUG] EFB crash on certain METAR code
**Mod Version**

Development a9c1b72

**Describe the bug**

After connect to simbrief EFB crashes or turn off/black, 

**To Reproduce**

1. Plan a flight LPLA to LPMA on Simbrief and make a OFP
2. aktual METAR of LPLA is SA  051000  /////KT 9999 BKN028 13/06 Q1028
3. load the Simbrief Data by click on blue button "load simbrief

**Expected behavior**

EFB shows the loaded flight and METAR on Dashboard

**Actual behavior**

EFB turns off/crash. reloading the plane activates the efb

**References**

https://user-images.githubusercontent.com/36174809/107026324-d32d6180-67aa-11eb-99a7-0023b63ff83d.mp4

**Additional context**

Was this working before/when did the issue start occurring?
Other flightplans with normal METAR work

Is this a problem in the vanilla unmodded game?
There is no EFB

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by akhileshmalini**
Fixes #3343

## Summary of Changes

Display N/A when No Data is Parsed from Metar Data
Minor Code Formatting

## Screenshots (if necessary)

Metar N:A

## Additional context

Discord username (if different from GitHub): Ewilcorp

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by ExampleWasTaken** [comment]
Category: QA Trial
Name: ExampleWasTaken#0886
Date of testing: 08/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3400
Tier of testing: 1
Changes to observe: Fix display crash on incomplete Metar Data

Testing technique: 
Steps I've made to test the Pull Request:
1. Generated OPF on simBrief.com
2. Loaded C&D
3. Powered A/C
4. Turned on EFB
5. Entered simBrief username
6. Imported OPF from simBrief
7. Edited OFP to verify the below mentioned issue


Flight notes (When done a full flight): N/A

Media: 
Microsoft Flight Simulator Screenshot 2021 02 08 - 12 40 25 51
Microsoft Flight Simulator Screenshot 2021 02 08 - 12 44 06 81


Issues (If Any): 
When no airline is specified in the OPF "[object Object] flight number" (without quotation marks) is displayed on the "Today's flight panel".

Overall Rating: To be improved
Conclusions of the testing: The above issue should be resolved. Other than everything works as expected.

**Comment by akhileshmalini** [comment]
@ExampleWasTaken I've Pushed a fix for the behavior described. 
Before
Screen Shot 2021-02-08 at 9 32 21 AM
 
After
Screen Shot 2021-02-08 at 9 29 30 AM

**Comment by ExampleWasTaken** [comment]
Will check it later today.

**Comment by ExampleWasTaken** [comment]
Category: QA Trial
Name: ExampleWasTaken#0886
Date of testing: 9/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3400
Tier of testing: 1
Changes to observe: "Today's flight" card displays [object Object] when no airline is specified in simBrief OFP

Testing technique: 
Steps I've made to test the Pull Request:
1. Created simBrief flight plan (LPLA-LPMA)
2. Loaded C&D
3. Powered the A/C up
4. Turned on EFB
5. Entered simbrief username
6. Loaded flight plan without specified airline --> behaved as expected
7. Loaded flight plan with specified airline --> behaved as expected

Flight notes (When done a full flight): N/A

Media: 
OFP without airline:
Microsoft Flight Simulator Screenshot 2021 02 09 - 00 32 11 20
OFP with airline:
Microsoft Flight Simulator Screenshot 2021 02 09 - 00 31 27 29


Issues (If Any): N/A

Overall Rating: Good
Conclusions of the testing: Everything is working as expected and previous issues have been resolved.

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 09.01.2021
Version of the sim: 1.12.13
PR Tested: #3400
Tier of testing: 1
Changes to observe: Fix display crash on incomplete Metar Data
(Insert the Summary of changes, in order to remind what is to test)

Testing technique: full C&D IFR
Steps you've made to test the Pull Request:
1. started at Gate
2. started efb
3. Entered simbrief username
4. loaded flightplan
5. observed decribed fixes

Issues (If Any): none

Overall Rating: Good
Conclusions of the testing:Works as expected! Thx for the PR!

**Comment by theflyingexpert** [comment]
Category: QA Tester/Trial
Name: Discord User #5118
Date of testing: Current date 11/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3400
Tier of testing: 1
Changes to observe: Fix display crash on incomplete Metar Data

Testing technique:

1. Start aircraft cold & dark, switch external power ON
2. Switch EFB on, enter Simbrief username
3. Pull flight plan without airline
4. Amend Simbrief flight plan to have an airline
5. Pull new flight plan with airline

Flight notes (When done a full flight): -

Media:

image
image

Issues (If Any): -

Overall Rating: Good
Conclusions of the testing: -

**Review by Benjozork — APPROVED** [review]
LGTM

**Pull request merged**
