### PR TITLE
Revert "[CDU] Cleanup (#2788)"

### LINKED ISSUE #2838: [BUG] PFD blinking mode indication
**Mod Version**
  "built": "2021-01-01T23:52:36+00:00",
  "ref": "",
  "sha": "",
  "actor": "Niklas Steiner <niklas@sbg.at>",
  "event_name": "manual"

**Describe the bug**
On final PFD mode indications (GS, LOC etc began blinking rapidly

**To Reproduce**
1. Fly ILS01R into Oslo
2.
3.

**Expected behavior**
For them not to blink, i never seen this in previous master or developer versions

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? Yes

Is this a problem in the vanilla unmodded game? Unsure, have not flown vanilla in a long time. 

Discord username (if different from GitHub): AAL311 Mark "Crabby" Crabtree

https://user-images.githubusercontent.com/76859649/103450916-e799ae00-4c82-11eb-9e99-eb7a7eb2e68f.mp4

### PR DESCRIPTION
**Pull request by Benjozork**
Fixes #2838 

This reverts commit eb6cdf61

## Additional context

Discord username (if different from GitHub):

## Testing instructions

* Perform ILS approaches at various airports. Check if #2838 still occurs.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by valenzz2004** [comment]
Category: QA Tester
Name: Valenzz2004#7802
Date of testing: 02/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2847 
Object of test: pfd behaviour on ils approaches

Testing technique: 20nm ils circuits
Steps you've made to test the Pull Request:

1. loaded in at EDDM
2. prepped for circuits with a full fpl to eddf and ils programmed for ILS26L
3. pushed taxied and departed no issues did left hand turns radius 15NM from eddm 
4. attempted to established ILS 26L
5. touch and go 
6. same for all other runways at munich (26R/08L/08R) 

Flight notes (If required):

Issues (If Any):
-on all arrivals fma worked as planned with no stuttering anouncing land, rollout etc on first attempt
-on second attempted ils approach the plane indicated screenshot one and on landing even though plane was configured for approach i got no fma messages such as land, rollout etc
Overall Rating: To be improved
Conclusions of the testing: worked fine on first landing however on second approach after going around something we wrong
Screenshots( if any):

xxl

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919
Date of testing: 1/2/2021
Version of the sim: 1.12.13.0
PR Tested: #2847 
Object of test: FMA

Testing technique: Tried out
Steps you've made to test the Pull Request:
1. Spwaned C&D at Klas. Did a full flight from Klas to Ksfo.
2. Moniterd FMA during take-off cruise and landing.
3. Landed at Ksfo with no disco.


Flight notes (If required):

Issues (If Any): N/A
Overall Rating: Good
Conclusions of the testing: Looks really good no disco was found. Also during the rest of the flight the Fma was working properly. Keep up the good work.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: Current date 03/01/2020
Version of the sim: 1.12.13.0
PR Tested: #2847
Object of test: Testing if disco FMAs are still there
Testing technique: Try-out (multiple tests)

## Steps you've made to test the Pull Request:

 * Two flights from C/D (LJMB-LJLJ / ESGG-ENGM)
 * One of the flights was to Oslo where the bug was first reported
 * Keept an eye on the FMAs when on ILS app.

## Overall Rating: Good
 
#### Conclusions of the testing:
 * Fixes the issue LGTM! Thanks!

#### Pictures:
ils2
ils1
ils3

**Review by pepperoni505 — APPROVED** [review]
LGTM

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
