### PR TITLE
fix(ecam/upper): adjusted engine gauges so cursor extends beyond radius of gauge

### PR DESCRIPTION
**Pull request by RichardPilbery**
## Summary of Changes

The cursors indicating the value on gauges on the upper ECAM and Engine page of the lower ECAM should extend beyond the radius arc of the gauge. Probably easier to show than explain!

## Screenshots (if necessary)

**Current sim**

orig-gauge

** After change **

new-cursor-idle

new-cursor-spool

new-cursor-powered

## References

Screenshot 2020-10-19 at 06 21 54 copy

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by HugoTro** [comment]
Name: Discord Hugo #3307
Date of testing: Current date 21/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1482 

Testing technique: Touch & Go's
Steps you've made to test the Pull Request:
1. Spawned at ENBR RWY 17
2. Tested Full reverse, 40%, CL ant TO/GA thrust with parking brake on
3. Took off and climbed to 10000 ft
4. Descended at idle and did a touch and go
5. repeated that and landed

Overall Rating: Good
Conclusions of the testing: Works as described

**Comment by MisterChocker** [comment]
Quick question (i know this is merged) after your merge my engine lever position indicator is not working. The lever is moved about 30%, no movement on the ECAM shown. After 30% lever indicator starts moving and is out of sync with engine N1% indicators.

**Comment by RichardPilbery** [comment]
Thanks @MisterChocker - I'll take a look and can generate a new PR if needed

**Comment by MisterChocker** [comment]
@RichardPilbery thanks for looking at it.

**Comment by RichardPilbery** [comment]
HI @MisterChocker I've just cloned the latest version of master and I cannot replicate your issue. I've tried manually moving the thrust levers in sim and by using my Thrustmaster throttle. The thrust lever indicator (small circle on the outside of the N1 gauge) moves as expected. It won't follow the N1 gauge exactly since it is am indicator of the position of the thrust lever and not the current N1 percentage. If you continue to have problems, do submit an issue as it might be someone else can replicate your issue.

**Comment by MisterChocker** [comment]
@RichardPilbery okay thanks for checking. I will monitor and open an issue if needed.

**Pull request merged**
