### PR TITLE
fix(nd): waypoint icon size

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Changed waypoint icon size

### Before:
image

### After:
image

## References

image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Review by tyler58546 — APPROVED** [review]
LGTM

**Comment by sl3awy** [comment]
> LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested:  #3513
Tier of testing: 1
Changes to observe: Look for small waypoint symbols on ND
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawn on Runway EDDB
2.) Took off to get to the first Waypoint
3.) Looked at ND (Nav, Arc and Plan)

Media:


Image1


Image2


Image3


Image4

Good: Symbols look the same on all pages

Issues:

- Linewidth is to thin, should be line trackline (Image1, Reference) 
- Symbols seem to have a black outline (Image1, Reference)
- Airport symbols (Stars) are to small (Image1, Reference)
- Decel symbol is to small (Image2, https://www.youtube.com/watch?v=TEi-WX08ov8)
- Waypoint to go is not white (Image1, Image3), but last waypoint is white. This seems a conflict with the new ND font (Image4)
- Text is to far away from the symbols

Overall Rating: -

Conclusions of the testing: Needs to be improved

Hope this helps :-)

**Comment by GlitchedYT** [comment]
Category: QA Tester
Name: Glitched#0740
Date of testing: Current date 02/13/2021
Version of the sim: 1.12.13.0
PR Tested: #3513
Tier of testing: 1
Changes to observe: Changed waypoint icon size
(Insert the Summary of changes, in order to remind what is to test)

Testing technique: Load flight and ensure waypoint icon size is smaller, closer to RL
Steps you've made to test the Pull Request:
1. Spawned C&D at EGLC
2. Loaded flight from EGLC - EKCH
3. Observed waypoint size changes on ND
4.
5.

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
Screenshot 2021-02-13 192736
Screenshot 2021-02-13 192631
Screenshot 2021-02-13 192609



Issues (If Any): 
Sizes of all icon's on the ND are now smaller, not just waypoint icons
Diamond for waypoint should be just a tad thicker to match IRL
Steps to achieve the issue

Overall Rating: To be improved
Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.

**Pull request closed without merging**
