### PR TITLE
make some FMAs have permanent box

### LINKED ISSUE #862: [BUG] MAN TOGA should always be boxed (and probably MAN FLX too)
**Mod Version**

master

**Describe the bug**

**To Reproduce**

spawn on runway
takeoff in TOGA

**Expected behavior**

MAN TOGA FMA always be boxed

**Actual behavior**

the box around MAN TOGA disappears after 10 seconds
image

**References**

https://www.youtube.com/watch?reload=9&v=ECV3IBkzZLc

### PR DESCRIPTION
**Pull request by AdenFlorian**
Fixes #862

**Summary of Changes**

Makes some FMAs have permanent boxes based on this site:
I believe if it has a box around it on that site, then it means it should always have a  box.
http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.0.html

Also fixes FMA box timers so that that last only 10 seconds instead of ~20 seconds.
I applied that fix to all PFD elements and ECAM pages.

Also fixes blinking FMAs, like LVR CLB so that it will blink.

Here is also a video showing that MAN TOGA seems to be permanent boxed: https://www.youtube.com/watch?reload=9&v=ECV3IBkzZLc

**Screenshots (if necessary)**

**Additional context**

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by Carter633** [comment]
Name: Carter633 #1436
Date of testing: Current date 25/09/2020
Version of the sim: 1.8.3.0
PR Tested: #864

Testing technique: Two take-offs, 1x runway, and 1x from Cold and Dark. Test progressed up to cruise.
Steps you've made to test the Pull Request:
1. First spawn on runway, take off as 2. states, then reset for full flight from Naples to Gatwick, starting cold and dark on stand
2. Take off - using MAN FLX box remains, similarly TOGA box remains for the duration too.
3. Turning FD On and Off to see how the displays change and see how the boxes react and checking timings of boxes after function changes. All timings are 10 seconds. LVR CLB also blinks consistently.
4. Continual review through to Cruise.

Overall Rating: Good
Conclusions of the testing: All the boxes appear in the right places and are all formed correctly. No issues found. Timings improved and permanent boxes for set settings remain.

**Review by Carter633 — APPROVED** [review]

**Review by NathanInnes — APPROVED** [review]
Tested and working well. Code looks good.

**Comment by JackZ974** [comment]
Nice.
For the 10 seconds delay, this is a good correction, but FYI some boxes stay longer (15 seconds instead of 10) when there is a PA mode change reversion (accompanied by the triple clic soin), as per FCOM.
0B331120-D0A1-4745-A6B9-67507033D03A

**Comment by AdenFlorian** [comment]
@JackZ974 I'll save for a future pr.

**Pull request merged**
