### PR TITLE
feat: custom chronometer font

### PR DESCRIPTION
**Pull request by tyler58546**
## Screenshots (if necessary)

Before:
image
After:
image

## References

IMG_20200913_025942

## Testing instructions

Make sure the new font is accurate and there are no issues with the chronometer.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 14.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3521
Tier of testing: 1
Changes to observe: Chronometer font
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned at day C&D at EDDP
2.) With no power the LCD is off. 
3.) Turned on Bat.
4.) Looked to chronometer (Image1)
5.) Set time to night (Image2)

LCD brightness is independent from INTEG LT.

Media:


Image1


Image2

Issues (very minor): Alignment of row one and two is a little up.

Overall Rating: Good

Conclusions of the testing: Looks nice!

Hope this helps :-)

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 14.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3508
Tier of testing: 1

### Changes to observe: CHRONO number font

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on runway at VABB
2. Turned on lights to TEST mode
3. Screenshots compared with reference

### Media:
image
image


### Issues (If Any): Position on row 1 and 2 needs slight adjustment as previously mentioned

### Overall Rating: Good

### Conclusions of the testing: The text looks accurate when compared to the reference. Good to go!

**Comment by tyler58546** [comment]
Is this better?
image

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 14.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3521
Tier of testing: 1
Changes to observe: Chronometer number alignment
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawn C&D at EDDB
2.) Turn on Bat.
3.) Looked at Chronometer at day (Image1)
4.) Looked at Chronometer at night (Image2)
5.) Did ANN LT TEST (Image3)

Media:

Image1


Image2


Image3

Issues: None

Overall Rating: Good

Conclusions of the testing: Alignemt is much better. Good to go!

Hope this helps :-)

**Comment by marcman86** [comment]
^ copy-paste error :-)

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 14.02.2021
Version of the sim: 1.12.13
PR Tested: #3521
Tier of testing: 1
Changes to observe:
Custom Chronometer Font

Testing technique: tested?
Steps you've made to test the Pull Request:
1. spawned on runway and gate
2. observed the Chronometer Font


Issues (If Any): none

Overall Rating: Good
Conclusions of the testing: Looks Good! Works as expected. Thx for the PR!

**Comment by sidnov** [comment]
@tyler58546 This one looks good to go! Updated review :)

**Comment by vpilotdesigns** [comment]
Name: V-Pilot#7116
Date of testing: 14.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3521
Tier of testing: 1
Changes to observe: Chronometer font
Testing technique: Tryout

Steps made to test the Pull Request:

1. Spawned
2. Started Plane
3. Look at Chronometer font

Overall Rating: Good
Conclusions of the testing: Looks Good
Microsoft Flight Simulator 2_14_2021 3_38_22 PM



Media:

**Pull request merged**
