### PR TITLE
feat: RAAS

### LINKED ISSUE #5035: RAAS Runway Awareness & Advisory System
### Aircraft Version

Development

### Description

Just saw yesterday a video of an airbus approach and the aircraft made a callout "Approaching Runway 09R". I think an optional RAAS would be a valuable assistant for flying the A32NX.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by Kimbyeoungjang**
Fixes #5035

## Summary of Changes

- [x] Add runway recognize logic
- [ ] Add runway area logic
- [ ] Add ground events( on taxiway / approaching xx / on runway xx / etc...)
- [ ] Add on-air evetns( approach xx / feets remaining / etc..._
- [x] Add options to turn on or off RAAS
- [ ] Remove JSON load part (if api is coming)

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Snapmatics** [comment]
Oh well... good luck to @MisterChocker.

**Comment by lolisec** [comment]
is this still be worked on its been almost half a year?

**Comment by Kimbyeoungjang** [comment]
> is this still being worked on its been almost half a year?

Working on ohter branch with cFPM.

**Comment by aguther** [comment]
Feel free to open a new PR when you want to work on it again.

**Pull request closed without merging**
