### PR TITLE
fix(fmgc): Sync FMGC go around flight phase with AP state

### LINKED ISSUE #5771: SRS/GA TRK issues
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-09-02T03:35:34+00:00",
  "ref": "HEAD",
  "sha": "ad8d4b1549903ba9727ac33e46b6c9a6178ade25",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}
```

### Describe the bug

On final approach, when MAN TOGA is entered for a moment and SRS GA/TRK is shown as engaged on the PFD, (i.e. autoflight has placed us into a go-around state) the MCDU will still show the current phase as approach even though GO AROUND has been initiated. 

To correct the abnormal state, you have to place the thrust lever to select TOGA power until GO AROUND is displayed on the MCDU.

### Expected behavior

FMA and FMGC should agree on the current flight phase, aka PFD and MCDU should indicate the go around state.

### Steps to reproduce

1. Push throttle lever to TOGA for a moment (very quickly), before returning to the CLB detent. 
2. MAN TOGA will flash, then SRS/GA TRK will activate, observe the PFD. 

To ensure that the exact condition has been reproduced, ensure that the MCDU does NOT show the current phase as GO-AROUND.

### References (optional)

https://clips.twitch.tv/SpeedyEnchantingTarsierKippa-TzE4NnovTbgv2C4a

### Additional info (optional)

 Yet to personally reproduce. See VOD. 

### Discord Username (optional)

2Cas#1022

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #5771

## Summary of Changes
Syncs FlightPhaseManager with the autopilot. 

In approach phase, checks for SRS and GA TRK to be engaged, rather than reading throttle lever position. If this condition is met, then the flight phase will be in GO AROUND, which is indicated visually by GO AROUND being shown on the title of the PERF page on the MCDU.

Before, it was possible to quickly move the throttle into TOGA and back to LVR CLB without triggering approach phase on the MCDU, which caused an unintentional bugged state where the flight phase remained in approach, but the autopilot is in a GO AROUND state. 

Now when go around thrust is selected, you are guaranteed to be properly engaged in the correct GO AROUND parameters, as well as being able to re-engage and prime for the approach by manually selecting APPROACH PHASE on the PERF page of the MCDU (and selecting the APPR push button).

## References

GO AROUND:

From APPROACH phase, activated when pitch go around mode is triggered

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Spawn in and chose a very short flight (or spawn in approach and manually enter in ILS and guidance parameters)
- Continue as normal until final approach
- On final approach, check that autopilot is engaged G/S* and LOC*. You can see this state on the PFD.
- Quickly set the thrust lever to TOGA power, and then back to the CLB detent. (Try to do this as fast as possible).
- The plane should now be fully engaged in GO AROUND. 
  - For the AP, check that the PFD is showing SRS and GA TRK.
  - Check that the MCDU PERF page shows the current flight phase as GO AROUND (should be the title) and that approach phase can be re-activated. 
- Fly a circuit (go around) and return to the approach and land as per normal operations. (Remember to arm approach phase and ensure that the APPR pushbutton is engaged on final approach). 

- Also test in fully manual flight with both flight directors and AP disabled. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by beheh** [comment]
Will this still work with flight directors and APs disabled?

**Comment by 2hwk** [comment]
> Will this still work with flight directors and APs disabled (i.e. no FMAs)?
> 
> Let's add a note for QA to test a go around in fully manual flight and document the expected behaviour there.

It should, and it did just now, I added one step for QA.

**Comment by aguther** [comment]
> Will this still work with flight directors and APs disabled (i.e. no FMAs)?
> 
> Let's add a note for QA to test a go around in fully manual flight and document the expected behaviour there.

The reason it should work is because GA engages both FDs.

Down the road it would be interesting how it’s solved when FDs are not available.

**Review by beheh — APPROVED** [review]

**Comment by xZreai** [comment]
Quality Assurance Trainee Report

Discord: Cleon#5802
Object of testing: (#5790)
Tier of Testing: (1)
Date: (14/09/2021)

Testing Process: 
1 Spawned in manually for RWY 27 at VABB

2 Put in ILS approach for RWY 27 and continued to final

3 Armed APPR button and plane was set on the localizer and glideslope

4 Approach phase was set and Approach perf page was filled

5 Throttle pushed to TOGA and back to CL detent on 3 DME to RWY 27 VABB

6 PFD showed SRS and GA TRK, MCDU PERF Page was set to GO AROUND

7 Did a circle around and armed approach again and activated approach phase

8 Landed ILS RWY 27 Autoland

9 Redid same with FDs and AP off

Negatives: Nil
Testing Results: PASSED

Conclusions: Works according to testing instructions, on manual flight with FD+AP off once Go around is initiated the FDs come on by themselves - not sure if this is correct behaviour or not but I'd believe it is, just wanted to point it out.

Media: N/A

**Comment by ShadowFrost3** [comment]
Quality Assurance Trainee Report


Object of testing: #5790 
Tier of Testing:1
Date: 17/09/2021

Testing Process: 
Spawn in air, enter ILS, fly approach.
(TOGA Button) Press TOGA button pushes throttles to max in an instant and then back out
Check for parameters SRS, GA TRK, and MCDU Page change
Profit
Repeat with FD and AP off
Profit
Negatives: N/A
Testing Results: Passed

Conclusions: Profit
I had a uncommanded go around due to most likely a ghost button press. It may be worthwhile to add a note to the build when this PR gets pushed to people with faulty controls (like mine) for potential bugs.

**Pull request merged**
