### PR TITLE
Improve ground handling, steering, and suspension

### PR DESCRIPTION
**Pull request by wpine215**
## Summary of Changes

- Changes max castering angle to 75 degrees (1.309 radians) to reflect IRL performance
- Updates gear damage FPM limits (nosewheel limit increased to 800 FPM, main gear decreased to 1200 FPM)
- Updates static compression values, static/max compression ratio, and dampening factor to more realistically model the suspension of the A320
- Gear extension time slightly increased to match IRL gear extension times
- Gear extension times for both left and right MLG now match each other
- ~~Rudder effectiveness decreased from 1.0 to 0.25~~

## Screenshots (if necessary)

N/A

## References

firefox_YI0shKBluC
firefox_crPSfDpbvO

+ A320 AMM, ATA Chapters 6 and 32

## Additional context

Needs pilot feedback.

Discord username (if different from GitHub): Iceman#5540

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MisterChocker** [comment]
I have made discoveries that the rudder effectiveness is also influenced by device inputs.
So changing this value, seems to change the effectiveness not equally for everyone.
Also @aguther uses 1 for the FBW. We need to make sure everything works fine.

**Comment by lukecologne** [comment]
Does the free caster setting actually do something? The previous setting would be 180°, and I have never seen the nose wheel rotated 180* in the sim. It looks like the actual nose wheel steering setting for non-free-castering wheels is the the 8th setting of the contact points, which is already set to 75.

**Comment by wpine215** [comment]
> 
> 
> I have made discoveries that the rudder effectiveness is also influenced by device inputs.
> So changing this value, seems to change the effectiveness not equally for everyone.
> Also @aguther uses 1 for the FBW. We need to make sure everything works fine.

Alright, reverted rudder_effectiveness to 1 as of right now. We can investigate this further down the road once custom FBW is in.

**Comment by wpine215** [comment]
> 
> 
> Does the free caster setting actually do something? The previous setting would be 180°, and I have never seen the nose wheel rotated 180* in the sim. It looks like the actual nose wheel steering setting for non-free-castering wheels is the the 8th setting of the contact points, which is already set to 75.

Not actually sure - it might just affect taildragger planes? I can't find documentation on it - so it can't hurt to keep it consistent with the 75 degree steering limit in case it is used down the road.

**Comment by z0rgmeister** [comment]
Category: QA Tester
Name: z0rgmeister#8972
Date of testing: Current date 25/11/2020
Version of the sim: 1.11.6.0
PR Tested: #2098
Object of test: Test Improved ground handling, steering and suspension

Testing technique: Full flight LPFR-LPPT from C&D
Steps you've made to test the Pull Request:
1. Regular flight procedures with special emphasis on ground handling
2. Thoroughly taxied the aircraft on departure noting improvement in low speed taxi (<20kts) handling
3. Gave the aircraft rudder inputs on takeoff (>40kts) to test high-speed handling, noted improvement and responsiveness
4. On landing purposedly landed right of centerline requiring immediate rudder input to centre. No difference noted.
5. High speed (30 kts) roll off runway noting improvement in responsiveness.

Flight notes (If required): None

Issues (If Any): None related to this PR
Overall Rating: Good
Conclusions of the testing: LGTM

**Comment by tjburni** [comment]
Category: QA Tester
Name: tjburni #0409
Date of testing: Current date 25.11.2020
Version of the sim: 1.11.6.0
PR Tested: #2098
Object of test: ground handling, steering and suspension

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. taxied at different speeds (10kn , 20kn 40kn 80kn)
2. took of( tested steering at 120 and 150 kn)
3. landed ( testes steering while landing)

Flight notes (If required):at lower speeds there were no difference. At higher speeds the handling improved

Issues (If Any):none
Overall Rating: Good
Conclusions of the testing:Works good. Handles better than before

**Pull request merged**
