### PR TITLE
Wind Indicator Fix

### LINKED ISSUE #216: Wind data on ND shows up below 100kts IAS
The wind data on the ND (Top left corner) should only show up above 100kts on the takeoff roll

### PR DESCRIPTION
**Pull request by NathanInnes**
Fix #216 

If you are below 100kts ground speed the wind indicator on the MFD will not show.

### CODE REVIEW

**Comment by nobodyn0se** [comment]
It seems that this code does not fetch the value of GS in var groundSpeed. Unless this issue is resolved, I can work on it.

**Comment by NathanInnes** [comment]
Thanks for the heads up, committing again

**Comment by AdenFlorian** [comment]
Please add before and after screenshots to the PR, thanks!

**Comment by NathanInnes** [comment]
If ADIRS are aligned and you're above 100kts GS the data will show.
image


- If below 100kts GS and ADIRS are aligned it will show GS only.
- If ADIRS are not aligned no data shows.

**Comment by AdenFlorian** [comment]
created a followup ticket for tomrrow so we can merge this now, thanks! https://github.com/flybywiresim/a32nx/issues/403

**Comment by AdenFlorian** [comment]
@NathanInnes Sorry, forgot to mention that you need to add the vanilla NDInfo.js in its own commit, then add your changes to it in your own commit, so that we can see what changed.

**Review by AdenFlorian — APPROVED** [review]

**Pull request merged**
