### PR TITLE
fix(lnav): sequence type 1 at ITP, not INP

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

* We change the sequencing method of Type 1 transitions. Instead of checking for both directed DTG to the TERM FIX and directed DTG to INP, we now simply check for directed DTG to ITP. This aligns with the system sequencing behaviour of the FMS, but NOT with the visual sequencing behaviour, which is less important right now.
* We make sure to also include the transition onto the active leg as part of the active path geometry, in order to guide along the transition after sequencing instead of guiding along the active leg
* Clean up various directed DTG calculations

Discord username (if different from GitHub): someperson#4953

## Testing instructions

* Ensure that sequencing works correctly with all leg types (try SIDs with MANUAL legs, try RNP approaches)
* Ensure there is no excessive sequencing

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5719
Tier of Testing: 1
Date: 28/08/2021

Testing Process:
- Loaded in C+D at the gate at CYYZ, prepared full flight to KJFK
Routing: CYYZ/15L KEPTA2 BMPAH DCT AEVON DCT EXTOL Q140 YODAA DCT IGN IGN1 KJFK/DPK.R31RZ

MANUAL leg on departure:
- Compared against navigraph charts: planned correctly, MANUAL leg infinite line shown, as well as the points along the SID after the manual leg.
- After departure NAV proceeded along the MANUAL leg until selected DIR TO KEPTA - DIR TO drawn correctly and previous legs cleared.

RNAV (RNP) 31RZ approach:
- Compared against navigraph charts - correctly displayed.
- Approach features another MANUAL leg, MANUAL leg sequenced as expected again as well as points on the RNP.
- Cleared MANUAL leg and the discontinuity below to tidy up the plan, redrew perfectly.
- Started the turn to LENDY slightly earlier than drawn but straightened out perfectly and flew nicely.
- Started the turnto PZULU slightly earlier than drawn but straightened out and flew just nicely again.
- Entered ILS frequency but flew the RNP on NAV - observed ILS diamonds and looked spot on the entire way down.
- Butter landing: PASS

Flew the remainder of the flight with no other issues observed - both departure and arrival properly sequenced and flown, AP went on at around 1000ft AGL and remained on until final. 

Negatives: N/A
Testing Results: PASS 

Conclusions: Lines on the two mentioned turns on arrival looked spot on but the aircraft turned earlier, although understood that the visual sequencing isn't the priority, so no complaints as the actual route flown was spot on. Really good flight!

Media: 

- TOP - Immediately after departure, just after climb constraint point of 1000ft displayed on ND,
- BOTTOM - After DIR TO KEPTA on departure.

image

- RNP arrival with MANUAL leg: 

image

- RNP arrival after clearing MANUAL leg and discontinuity:

image

- Early turn at DOORE:

image

- Early turn at DPK: 

image

**Comment by Benjozork** [comment]
Ok this is wrong

**Comment by Benjozork** [comment]
I will be investigating an issue with RAD before we can test this again

**Comment by Benjozork** [comment]
RAD issue was due to bad debug UI

**Pull request merged**
