### PR TITLE
fix(mcdu): fix race condition when spawning directly into approach

### PR DESCRIPTION
**Pull request by tracernz**
Fixes issue reported on Discord by danbw9#7028

## Summary of Changes

Fix a race condition on spawning directly into approach phase.

## Screenshots (if necessary)

PFD before when spawning directly into approach phase:
image

PFD healthy after fix:
image

## Additional context

No changelog needed since the bug never made it into a release I think?

Discord username (if different from GitHub): tracernz#3313

## Testing instructions

Spawn directly into approach at IAF and ensure PFD is operative.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by sidnov** [comment]
Thanks for the quick fix! Waiting for RTT to check it out

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by donstim** [comment]
The bug is definitely in a release -- it's in the current dev version. Not sure when it first appeared.

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 28.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3223 
Tier of testing: 1
Changes to observe: PFD working while spawn at approach, proper landing phase activation.

Testing technique: Tryout
Steps you've made to test the Pull Request:

1. Made the necessary changes to ....MainDisplay.js in the latest dev version
2. Spawned at approach for RWY27 VABB
3. Observed PFD working as expected
4. Landing phase activates correctly

Issues (If Any): None.
Conclusions of the testing: PFD works when spawning directly on approach. Thanks again for the quick fix!

**Review by davidwalschots — APPROVED** [review]
LGTM

**Comment by JolteonYellow** [comment]
Category: QA Trial
Name: JolteonYellow#7328
Date of testing: Current date 29/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3223
Tier of testing: 1
Changes to observe: PFD working when you spawn on approach, proper landing phase activation.

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Downloaded and installed the pull request
2. Spawned on 27R approach at EGLL
3. Observed PFD working and landing phase working as expected.

Issues (If Any): None observed.

Overall Rating: Excellent 
Conclusions of the testing: All working as expected.

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 29/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3223 
Tier of testing: 1
Changes to observe: systems working on approach

Testing technique: Try-out
Steps you've made to test the Pull Request:
1. Spawned in approach of different airports (Nantes, JFK and Nagasaki)
2. Observed instruments

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Looks good! (and it works that's the important part lol)

**Comment by h20genie** [comment]
Category: Contributor 
Name: h20genie#4343
Date of testing: Current date 29/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3223
Tier of testing: 1 or N/A
Changes to observe: PFD working when you spawn on approach, proper landing phase activation.

Testing technique: Description of how you tested the Pull Request. Spawned and selected various airport runways and approach only. 

Steps you've made to test the Pull Request:

Downloaded and installed the pull request
Spawned on 17R approach at KDEN, KDFW, and KPHX
Observed PFD showing all info prior to this bug/error. The landing phase is working as expected. PFD shows all info and approach phase for ILS at the mentioned airport works fine. Aircraft does not go into go around route when activating approach
Issues (If Any): None observed.

Overall Rating: Excellent
Conclusions of the testing: Everything is working as mentioned and expected.

**Pull request merged**
