### PR TITLE
feat(ap): improved spd/mach law model

### PR DESCRIPTION
**Pull request by IbrahimK42**
## Summary of Changes
The SPD/MACH law model in the autopilot is improved with this PR. 

- it is more soft and allows always descend or climb although speed acceleration or deceleration,
- energy angle is better estimated considering wind angle of attack effects during turn,
- transient behavior of speed changes during climb and descend.

Here is a small video

[https://streamable.com/cwmh09](https://streamable.com/cwmh09)

## Testing instructions

The new SPD/MACH law model should especially be tested by verified pilots, but of course all feedback would be helpful. The tests shall be done each in following weather conditions

A: No Wind
B: Crosswind (80-100 kts) and no turbulence
C: Turbulence weather

Following flight conditions should be tested:

Low Speed: Green Dot Speed
High Speed: 30% before max. Speed

1. Climb from low altitude to high altitude, change speed from low speed to high speed during climb, afterwards reduce speed
1. Descend from high altitude to low altitude, change speed from high speed to low speed, afterwards increase speed from low speed to high speed
1. Descend with all flaps set and speed brake and speed changes

Ensure the aircraft behaves the way you would expect.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by beheh — COMMENTED** [review]
I can't really give good feedback for this on a code-level, as I understand the code is autogenerated from our MATLAB models. So I'll defer the actual approval @aguther or someone else who is more familiar if the changes seem okay from a code perspective.

Behaviour-wise I've had the change to test this PR twice in various stages of development and feel like the behaviour is clearly optimized and seems smooth. At times I've personally felt the response to be a little sluggish, but as I have no real A320 experience I'm not qualified to judge that. It would be really good if we could have a few real A320 pilots test this one.

**Review by lukecologne — APPROVED** [review]

**Comment by FlyingCarpet7** [comment]
All right, I been flying this PR now for about an hour. Overall conclusion is that the behaviour is good! It feels accurate. I can not verify that all numbers are exactly correct because I never monitor it that closely. I have to go with the overall feeling compared to the real plane.

Just a few things that might have room for some fine tuning.
When pitching up, eg reducing speed during descend, the vs seems a bit rapid from passing about 1000 to 500 fpm. I can not see it directly on the pitch indicator, it’s more visible on the VS number that seems to change a bit to fast in that last part. 

Note: Using flaps, gear and speed brake right now creates way to little drag. I know the drag model is not tuned in this PR, so it’s just a side note, but do affect the testing of this PR in dirty config.

**Comment by IbrahimK42** [comment]
> All right, I been flying this PR now for about an hour. Overall conclusion is that the behaviour is good! It feels accurate. I can not verify that all numbers are exactly correct because I never monitor it that closely. I have to go with the overall feeling compared to the real plane.
> 
> Just a few things that might have room for some fine tuning. When pitching up, eg reducing speed during descend, the vs seems a bit rapid from passing about 1000 to 500 fpm. I can not see it directly on the pitch indicator, it’s more visible on the VS number that seems to change a bit to fast in that last part.
> 
> Note: Using flaps, gear and speed brake right now creates way to little drag. I know the drag model is not tuned in this PR, so it’s just a side note, but do affect the testing of this PR in dirty config.

Thank you for your feedback. I will do a small fine tuning regarding the fast vertical speed change during descend and speed deceleration. Could you estimate, how fast this change in real should happen for example from - 1000ft/min to - 500ft/min during descend and speed reduction?

**Comment by FlyingCarpet7** [comment]
The transitions are always smooth and never jerky in real life. Hard to estimate. 1000-800 in one second 600-500 in one second. So maybe three seconds.. it’s a logarithmic curve there..

**Comment by IbrahimK42** [comment]
> The transitions are always smooth and never jerky in real life. Hard to estimate. 1000-800 in one second 600-500 in one second. So maybe three seconds.. it’s a logarithmic curve there..

Thanks again for your feedback. I reduced the pitch sensibility in a new commit.

**Comment by ShadowFrost3** [comment]
Quality Assurance Tester Report


Object of testing: #5918
Tier of testing: 2
Date: 28/09/2021

Testing Process: 
C&D Full Flight KJFK-KDCA
Live weather 
Adjust speed (down, up, down, etc) during climb - aircraft responds well and adjusts to new conditions during climb - checked
No unusual items approaching cruising altitude - checked
Good 250 kt limit on transition - checked
Adjust speed during descent - aircraft responds well - checked
Speed brake descent checked - doesn't help aircraft as much as I would imagine - drag issue? not PR - checked
No issue with flaps 1 during descent - checked
speed increase during descent - slight (1-2 knot overshoot) very nice - checked
Adjustment from descent to level - no issues - checked
Adjustments of altitude and speed together for approach - checked

Hot spawn conditional testing

No wind
Adjust speed during climb(several tests, maximum overshoot of ~4 knots during initial capture to climb) - checked 
Adjust speed to green dot during climb - checked
Adjust speed close to overspeed during climb - checked
Tested with and without time accel - checked 
Adjust speed during descent - checked
Green dot transition during descent - checked
Close to overspeed during descent - checked 
Tested with and without time accel - checked 
No wind complete 

80 Knot cross wind
Adjust speed during descent - checked
Adjust speed to green dot during descent - checked
Adjust speed to near overspeed during descent - checked
Good altitude capture on speed (4 knot overshoot) - checked
Level to climb (10 knot overshoot, maybe more than ideal I'm not an a320 pilot) - checked
Adjust speed during climb - checked
Adjust speed to green dot during climb - checked
Adjust speed to near overspeed during climb - checked 
Good altitude intercept - checked 



Negatives: 
Testing Results: Passed

Conclusions: 
Media:

**Comment by donstim** [comment]
I'm a little confused about the comments regarding a seeming lack of drag from flaps, speed brakes, and gear. This PR does not change the drag and shouldn't need any drag "tuning." As I understand it, it only changes the proportion of deceleration vs descent rate when decelerating during a descent, or the inverse during a climb. How is this lack of drag manifesting itself? In a decelerating descent, is it an apparent lack of deceleration, or a lack of descent rate? The first would indicate that maybe the descent angle should be reduced a bit, while the latter would indicate that it should be increased a bit.

I've done just a few simple steady-state checks (i.e., constant speed and, depending on configuration, either constant altitude or a -3 degree flight path angle, and I'm hitting the numbers from the unreliable airspeed charts than the current pitch and drag models are based on for different flap and gear configurations. I haven't checked the speedbrake drag with an emergency descent check, but I did verify that the intended lift/drag effects are still being applied.

**Comment by IbrahimK42** [comment]
> I'm a little confused about the comments regarding a seeming lack of drag from flaps, speed brakes, and gear. This PR does not change the drag and shouldn't need any drag "tuning." As I understand it, it only changes the proportion of deceleration vs descent rate when decelerating during a descent, or the inverse during a climb. How is this lack of drag manifesting itself? In a decelerating descent, is it an apparent lack of deceleration, or a lack of descent rate? The first would indicate that maybe the descent angle should be reduced a bit, while the latter would indicate that it should be increased a bit.
> 
> I've done just a few simple steady-state checks (i.e., constant speed and, depending on configuration, either constant altitude or a -3 degree flight path angle, and I'm hitting the numbers from the unreliable airspeed charts than the current pitch and drag models are based on for different flap and gear configurations. I haven't checked the speedbrake drag with an emergency descent check, but I did verify that the intended lift/drag effects are still being applied.

This PR changes the proportion between deceleration/acceleration and path angle. I notified, that reducing from high speed to low speed (more drag to low drag) in descend results in decreasing of descend rate. @FlyingCarpet7 Are the descend rate you had during the descend with the PR and speedbrake like in real?

**Comment by donstim** [comment]
> 
> This PR changes the proportion between deceleration/acceleration and path angle. I notified, that reducing from high speed to >low speed (more drag to low drag) in descend results in decreasing of descend rate which makes sense. @FlyingCarpet7 Are >the descend rates you had during the descend with the PR and speedbrake like in real?

Prior to this PR, if I remember correctly, the descent angle when decelerating was less than with this PR. That is, the airplane would nearly level off to decelerate before resuming its descent. The descent rate was therefore less during that segment where the airplane is both decelerating and descending prior to this PR.  Adding drag during that time (by extending gear, flaps, or speedbrakes) would previously been used primarily to decelerate the airplane faster. Under this PR, that drag would be split 70% toward decelerating the airplane faster and 30% in increasing the descent angle (and hence the descent rate).  The same drag change is still there, it is just being used differently in terms of the relative proportions used for deceleration and descent rate.

It appears to me that the comments about lower speedbrake, gear, and flap drag may be in response to the lower deceleration rate, as more of the drag increase is now being used to increase the descent rate?

**Comment by IbrahimK42** [comment]
"The same drag change is still there, it is just being used differently in terms of the relative proportions used for deceleration and descent rate."

That is correct. The drag is the same. Prior to this PR, the aircraft has been nearly leveled off until reaching the desired speed. The deceleration was therefore faster. Now, the drag resulting from speed brake, gear, flaps reduce the kinetic energy of the aircraft. It must build up more potential energy to ensure same energy level (70% deccel and 30% descend). That would result in a higher sinkrate, but the right proportion is still existent.

**Comment by ShadowFrost3** [comment]
Given the conversation thread that has happened. I went and looked at descent profiles. 37,000 mach to 290 IAS descent is roughly 2,700 fpm. 10,000 to below it 1,700 fpm. No issues to report here, did not test with speedbrakes. I don't have any numbers to compare to but against a A319 1700&2400 is par for the course I imagine. 
https://youtu.be/j9p5AORcY8o

**Review by aguther — APPROVED** [review]

**Comment by IbrahimK42** [comment]
I added a new feature in case of less thrust during open climb. I will now record a video, which summarize the new SPD/MACH law.

**Comment by IbrahimK42** [comment]
I would have no further changes to this PR. QA is passed and the behavior is defined as accurate from two verified A320 Pilots.

**Comment by marcman86** [comment]
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #5918
Tier of Testing: 1
Date: 01/10/2021

Testing Process:
- Spawned in air over LA
- Set to 5000ft and 230kts
- Open climb to 15000ft > Accelerated climb to 15000ft and 290kts > law will reduce climb rate
- Open descent to 5000ft > Decelerated descent to 5000ft and 230kts > law will increase descent rate
- Set to 290kts
- Open climb to 15000ft > Decelerated climb to 15000ft and 230kts > law will increase climb rate
- Open descent to 5000ft > Accelerated descent to 5000ft and 290kts > law will reduce descent rate
- Open climb to 20000ft > LVR ASYM, idle oder reduced throttle > law will reduce climb rate

Negatives: -

Testing Results: Passed
Conclusions: Works for me

Hope this helps :-)

**Pull request merged**
