### PR TITLE
fix(nd): VOR/ADF info after Asobo update 1.14.5.0

### LINKED ISSUE #3880: [BUG] VOR/ADF on PFDs not showing on pilot side
**Mod Version**
{
  "built": "2021-03-09T19:00:13+00:00",
  "ref": "fbw",
  "sha": "ccb4e9c90cfdc727c4e5eb6165c3401dc271bac9",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
The VOR/ADF info is not showing on the pilot although switched ON.
On the FO side they are always showing although switched OFF
Switching to ADF still shows VOR on FO side

**To Reproduce**
1. Start C&D turn on EXT PWR
2. See VOR info displayed on FO side although switch is off
3. Switch VOR on on pilot side - no info is displyed

**Expected behavior**
VOR info displayed according to switches for pilot or FO side

**Actual behavior**
See above

**References**
image
image

Was this working before/when did the issue start occurring?
Yes - worked before fbw updates on 9th for MSFS 1.14.5

Is this a problem in the vanilla unmodded game?
unknown

Discord username (if different from GitHub): Cdr_Maverick

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #3880

## Summary of Changes

The signature of `Simplane.getAutoPilotNavAidState` changed, with addition of aircraft type as the first parameter. We use this to determine the status of the ADF/OFF/VOR switches.

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Check that VOR/ADF selector switches operate correct side on each ND.
- Check VOR and ADF displays okay on bottom corners.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 10/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3884
Tier of testing: 1

Changes to observe:
N/A

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. Spawned on runway @ LIRN
2. Added VOR and ADF
3. Flight run towards/far-away SOR TEA PTC

Flight notes (When done a full flight):
N/A
Media: Insert screenshots, recordings, or anything relevant to the review here.
Microsoft Flight Simulator Screenshot 2021 03 10 - 11 30 07 15
Microsoft Flight Simulator Screenshot 2021 03 10 - 11 33 29 05

Issues (If Any): Write any issues
N/A
Steps to achieve the issue:
N/A

Overall Rating: Good
Conclusions of the testing: LGTM

**Comment by Samueleonard** [comment]
More Resources 
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: 10/03/2021
Version of the sim: 1.13.17.0
PR Tested: #3884
Tier of testing: 1
Changes to observe: check vor/adf readouts appear on ND
Testing technique: Tryout

Steps you've made to test the Pull Request:
1. load in on runway
2. tune VOR and ADF 
3. turn needles on on both NDs
4. make sure readouts appear
5. change VOR/ADF readouts
6. confirm readouts change

Flight notes (When done a full flight):
N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
image

Issues (If Any):
none
Steps to achieve the issue
n/a

Overall Rating: Good

Conclusions of the testing:
simple fix - LGTM

**Comment by Benjozork** [comment]
@Samueleonard only PRs with Ready To Test or Testing Started labels should be tested.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 11/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3884 
Tier of testing: 1

### Changes to observe: VOR/ADF Info

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned at runway, tuned local VOR in RADNAV
2. Departed on runway heading, observed information updating properly.
3. Changed modes from ADF to VOR and vice-versa. Worked as expected.

### Overall Rating: Good

### Conclusions of the testing: The functions mentioned within the scope of the PR is achieved properly. ADF/VOR switches for the Captain side is active again, and the information is being displayed correctly. (There may be minor glitches with the arrow-indicator colors, which has been discussed already over Discord)

**Pull request merged**
