### PR TITLE
Made checklists mostly interactive

### LINKED ISSUE #594: [BUG] PFD went completely white when taxi checklist got to FMA
Version: master

As title says, Primary Flight Display went all white when checklist got to something Flight Mode Annunciator related on the taxi checklist, can't remember what exactly the name was, but ReferenceId of it is A320_TAXI_FLT_MODE_ANN. The game crashed shortly after.

To reproduce:
1. Follow standard before taxi procedures 
2. Follow the taxi checklist

Expected behavior: PFD should have a blue highlight as every instrument during checklist.

Actual behavior: PFD went all white, game crashed.

No screenshot taken, unfortunately.

### PR DESCRIPTION
**Pull request by DoToAdventures**
Fixes #594

**Summary of Changes**

I've added interactive functionality to every checklist point where it made sense and was possible for me to do. Most of them also have copilot actions assigned so they can be autocompleted if desired. I've also fixed a few minor issues that I've found here and there.
Currently this does not support buttons and knobs added by the Mod unfortunately because I either didn't find the simvars I needed or I did but it didn't work as expected without having any idea how to fix it, see Library.xml Line 191

**Screenshots (if necessary)**

https://i.imgur.com/ioUIh53.png

**Additional context**

### CODE REVIEW

**Comment by Coralec** [comment]
I have just tested this pull request. It is a very exciting addition to the project; thank you for this work @DoToAdventures. I have identified a number of items that will need to be added to the checklist at some point in the future. They are:

1.	Wipers switch status is not properly checked
2.	There is a strange pause for a few seconds after the APU start switch is turned on
3.	Probe/Window Heat switch is implemented in the mod but not checked and must be manually ticked 
4.	ADIRS switch status is not properly checked
5.	No Smoking Signs status is not properly checked
6.	Seatbelt Signs status is not properly checked
7.	Emergency Exit Lights status is not properly checked
8.	Battery 1 and 2 (off then on) – automatically completed when they are detected as on (this is a limitation of Asobo’s checklist system)
9.	Checklist does not guide any actions in the MCDU
10.	Crew (Oxygen) Supply switch is not properly checked
11.	WXR System selection switch is implemented but is not recognized by the checklist and must be manually ticked
12.	“Engine and Wing Anti-Ice” only highlights the Engine Anti-Ice switches, not the Wing Anti-Ice Switch
13.	Predictive Windshear System is labeled as automatically completable but does not switch to auto properly.
14.	Takeoff Config Pushbutton does not detect as pushed
15.	Landing Lights status is not properly checked (detecting as off when set to on in Climb checklist)
16.	GPWS Landing Flap 3 highlights the wrong switch
17.	It Would be nice if the Glareshield Integrated lights were pointed out by the Checklist
18.	Flight Director switch status detects as on when set to off
19.	“Engine Master Switch 2” is incorrectly highlighting and checking Engine Master Switch 1
20.	Autobrakes set to max check automatically completes without the Autobrakes being set
21.	Thrust Levers do not properly detect Climb setting

In addition that are a few critical mods that **_must_** be fixed before this pull is merged. They are:

1.	F"light Mode Annunciator" item in the checklist check turns the left PFD screen white
2.	Attempted autocompletion of Autothrottle to Flex/TOGA causes a crash to Desktop
3.	All checklist items are marked as completed when spawning on Runway.

If these three items are completed then the pull should be ready to be merged.

**Comment by DoToAdventures** [comment]
Huge thanks to your for your extensive feedback!

1. This is not possible because wipers don't have a simvar or at least I haven't found it.
2. No idea why this is caused. Rough guess is because the state of the button is not switched until the flap is open, not in my control I think.
3.  I will try to implement this tomorrow.
4/5/6/7. I don't know the simvars for the buttons implemented by the checklist, a limitation for now.
8. Asobo Checklist limitation, as you've said.
9. I'm aware. Guiding the user to do actions on the MCDU beyond clicking buttons the MCDU itself is currently not possible. Asobo limitation.
10. Also can't find the simvar for this.
11. The WXR simvars and part ID's are very complicated, I don't know how to implement this right now, to be honest. Parts that can be evaluated are different from parts that can be autocompleted, autocompletion requires an Event ID, the documentation on this is incomplete, so I hardly even have an idea of what an Event ID actually is.
12. I have yet to find the PartID for the Wing Anti-ice switch, I don't think it is labelled properly.
13. See 11, I'm missing the EventID for this, it is not in the documentation.
14. I'm not sure what causes this, the code implementation is correct. Perhaps missing the correct simvar?
15. I will check this tomorrow.
16. ""
17. "" Shouldn't be a problem
18. "" 
19. ""
20.  Might be an Asobo Issue, but I will also look into this.
21. ""

**Critical Bugs**
1. I will remove the highlighting of the screen tomorrow, currently highlighting monitors causes them to be completely white after.
2. Not reproducable for me, but I will look into this, might have to remove the evaluation for this.
3. Asobo Limitation, I can't change this right now.

**Comment by DoToAdventures** [comment]
Update: 

3. I cannot find the simvar responsible for this.
15. Fixed
16. Fixed
17. Fixed
18. Fixed (Hopefully)
19. Fixed
20. This is indeed an Asobo issue, the simvar used for determining the current state of the autobrake is faulty on the A320, it does not allow a value other than 1 or 0,  with 1 being off and 0 being on. This should be implementable once someone tackles the autobrake system itself. The Simvar works correctly in the 747. I was able to implement this by using an L var for the evaluation, however I can't use it for the Copilot action when using autocomplete. So for now only the evaluation works properly, no autocomplete.
21. Fixed

**Critical Bugs**
1. Fixed
2. Still not reproducable, but I've removed the autocompletion aspect of the thrust settings as it did not work for me anyway, at least not with anything other than idle.
3. I've looked at the .flt states, checklist states are not included in the files. I don't know where to possible change this.

I have also implemented #640

**Comment by DoToAdventures** [comment]
Loading a flight in different states now has the correct checklist for that state completed. If you spawn on the runway all checklists before takeoff have been completed, other states should work as well.

**Comment by Venorcis** [comment]
@DoToAdventures I've just did another final check, and noticed one more small issue. IMO the order of ECAM_MEMO and CABIN_CREW should be swapped both in the ILSAPPR and NONPAPPR checklists, as 'cabin crew informed' is actually part of the memo for landing.

**Comment by DoToAdventures** [comment]
@Venorcis Done!

**Pull request merged**
