### PR TITLE
fix: celcius -> celsius

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

This PR fixes a minor Typescript typo to normalize the English SI unit with the spelling "celsius" instead of "celcius" (the french word).
There's also a few typos in sound.xml, but those seem a little more dangerous and are therefore tracked in #7454.

## References

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Simulation_Variable_Units.htm?agt=index

## Additional context

Discord username (if different from GitHub):

## Testing instructions

This is a Typescript-only change and should not affect any behaviours in-sim.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by crocket63 — APPROVED** [review]

**Review by tracernz — APPROVED** [review]

**Comment by BlueberryKing** [comment]
Just did a quick project search and noticed that `sound.xml` still contains some references to "celcius". Is this correct?

**Comment by beheh** [comment]
@BlueberryKing 😉 

> There's also a few typos in sound.xml, but those seem a little more dangerous and are therefore tracked in https://github.com/flybywiresim/a32nx/pull/7454.

**Comment by BlueberryKing** [comment]
> @BlueberryKing 😉
> 
> > There's also a few typos in sound.xml, but those seem a little more dangerous and are therefore tracked in #7454.

Reading is hard. Apologies!

**Comment by davidwalschots** [comment]
Damn. I made that typo. Wasn't aware I could write French. Good to know 😀.

**Pull request merged**
