### PR TITLE
[FIX] retard callout playing on goaround

### PR DESCRIPTION
**Pull request by lukecologne**
## Summary of Changes
* This stops the retard callout from playing when goaround phase is entered. Previously, it would keep playing until the throttles were put in idle.
* The logic for retard (and the minimums and alt callouts as well) is still only an approximation, until the FWC is properly implemented.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
LGTM

**Review by Benjozork — APPROVED** [review]

**Comment by beheh** [comment]
Does this just need the exact FWC flight phase? I've implemented those over at #1943, so you could wait until that PR lands and then just reuse them.

**Comment by danbw9** [comment]
Category: QA Test
Name: danbw9#7028
Date of testing: 16/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1950
Object of test: Check out that there is no more 'retard' call when doing a go around

Testing technique: completing a variety of scenarios/go arounds 

Loaded up C&D for normal startup, taxi, take off for a pattern for RWY22L EKCH. 

3 different go around situations:
- low approach at ILS CAT 1 Minima (200 ft AGL)
- low approach and go around below ILS CAT 1 minima (≈100 ft AGL)
- simulated baulked landing after touchdown

In terms of the go around after touchdown the retard call was all normal until touchdown (as normal), and in the execution of go around after wheels contact, climbing out, it was not heard anymore.

Issues (If Any): None.
Overall Rating: Good
Conclusions of the testing: LGTM. I had tried go arounds before this PR and only once had the retard issue but on a balked landing only. I had the same issue as @Carter633 on just 2 of the 3 go around attemps - GPWS 'don't sink', which was supposedly fixed in another PR just on take off. The go around phase has been touched quite a bit in terms of phase and FMAs in past few days.

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo#3307
Date of testing: Current date 16/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1950
Object of test: Retard callouts 

Testing technique: Before/After
Steps you've made to test the Pull Request:
1. Spawned with the master in approach of LFRS RWY 03
2. Did a go-around when "retard" callout was pronounced 
3. Observed that the callout stayed even after 50 ft
4. Spawned with the PR #1950 in approach of LFRS RWY 03
5. Did a go-around when "retard" callout was pronounced

Flight notes :
Observed that it was working well, the callout stopped about 50ft above the runway when going around 

Issues: None that I observed 
Overall Rating: Good
Conclusions of the testing: Could be merged right now!

**Pull request merged**
