### PR TITLE
Engine Sounds

### PR DESCRIPTION
**Pull request by hotshotp**
## Summary of Changes

Hello all, since I really rushed the old engine sounds, here is my draft PR for the new engine sounds. I plan to have this in about 2 weeks or so and I want this to be as perfect as it can possibly be. These are the things I would need to finish:

- [x] Adjust volume and looping for the engines
- [x] Make thrust reverser sounds
- [x] Make high thrust vibration/power effect
- [x] Make interior sounds for idle through TOGA
- [x] Make exterior sounds for idle through TOGA
- [x] Make interior sounds for startup/shutdown
- [x] Make exterior sounds for startup/shutdown
- [x] Make throttle detent sounds

THESE ARE NOW DONE! The PR is ready for review, testing, and merging!

## References

Real engine sound samples, including video and audio. Real a320neo pilot feedback from people such as danbw9, st54kevin, flyingcarpet7. They said that the sound is accurate and just needs a bit of changes which are outlined above.

## Additional context

Please give me your harshest and most basic criticism, I will do my best to get these right as this is a really important part of the mod.

Discord username (if different from GitHub):

Boris#9134

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by joshbxd514** [comment]
Hi,

Ive tested the Following:

 Adjust volume and looping for the engines

 Make interior sounds for idle through TOGA

They sound great to me the volume is good and i cannot hear any obvious looping.

Date of test: 15/10/2020 16:50 Uk Time.

Thanks,

Joshbxd515#4978

**Comment by smukherj1** [comment]
Just tried this out. Loving the new jet whine! Also loving the buzzsaw at high N1s, something that was missing from the previous attempt (the PR that was reverted).

Great work! Can't wait for this to merge :)

**Comment by Watsi01** [comment]
Hello my friend. 
Tested out the new sounds, regarding they're not finished yet. I like the new wining sound. It sounds much better than the previous (removed) version. Much less of an "outside the aircraft" feeling in the cockpit. Chainsaw is great. As said in Discord, the avionic fans should be a little louder (**after** start up). Not finished, I know. I also would pull up the wind sound (>250kts) a bit. Now it's a bit too quiet in the cockpit during cruise (meaning wind and higher wind freq, the engines are good).  

All these are my personal views, as I'm not a real pilot.

GO BABY!

**Comment by Carter633** [comment]
Name: British Avgeek YT -- Carter633 #1436
Date of testing: Current date 12/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1352 - tested due to specific dev request

Testing technique: Full flight from Cold and Dark
Steps you've made to test the Pull Request:
1. Full flight from EHAM to EGGD
2. Engine start - NO external sounds except for APU, internal start up sounds appear quite quiet almost unreadable
3. Taxi - internal sounds good but no external sounds
4. Take-off and Cruise - sounds inside great but no external sounds
5. Same for landing, taxi in etc too

Overall Rating: Needs further work
Conclusions of the testing: Was asked to test this by the dev - internal sounds are great though engine start up etc is very quiet almost inaudible. All other sounds so far sound great - though you have broken the external sounds completely! No engine sounds or anything externally - just the winddddd.

**Comment by hotshotp** [comment]
> Name: British Avgeek YT -- Carter633 #1436
> Date of testing: Current date 12/10/2020
> Version of the sim: 1.9.5.0
> PR Tested: #1352 - tested due to specific dev request
> 
> Testing technique: Full flight from Cold and Dark
> Steps you've made to test the Pull Request:
> 1. Full flight from EHAM to EGGD
> 2. Engine start - NO external sounds except for APU, internal start up sounds appear quite quiet almost unreadable
> 3. Taxi - internal sounds good but no external sounds
> 4. Take-off and Cruise - sounds inside great but no external sounds
> 5. Same for landing, taxi in etc too
> 
> Overall Rating: Needs further work
> Conclusions of the testing: Was asked to test this by the dev - internal sounds are great though engine start up etc is very quiet almost inaudible. All other sounds so far sound great - though you have broken the external sounds completely! No engine sounds or anything externally - just the winddddd.

I have stated in the PR that there's nothing but interior idle through toga sound ;)

**Comment by Carter633** [comment]
Ah yes! I missed that line obviously my bad! I've edited my review to reflect that point 😎

**Comment by 2hwk** [comment]
LGTM, now to the exterior sounds.

**Comment by Watsi01** [comment]
Checked out your latest branch. Wind sounds good now. Av fan sounds much better. I know the engines are pretty silent in cockpit (on ground, idle). But I can hardly hear the startup. Are they really so quiet? (I'm not a pilot) If so, cockpit sound seems good for me. Thumbs up.

**Comment by hotshotp** [comment]
> Checked out your latest branch. Wind sounds good now. Av fan sounds much better. I know the engines are pretty silent in cockpit (on ground, idle). But I can hardly hear the startup. Are they really so quiet? (I'm not a pilot) If so, cockpit sound seems good for me. Thumbs up.

There is no startup sound at all. But the idle and on ground sounds are a good volume

**Comment by Watsi01** [comment]
> 
> There is no startup sound at all. But the idle and on ground sounds are a good volume

Yes!! I'm not deaf! I really thought, they were just veeerry quiet. lol

**Comment by hansmeller** [comment]
Name: hansmeller#8988
Date of testing: Current date 12/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1352 

Testing technique:  Flying around EDDH

Steps you've made to test the Pull Request:

1. Takeoff from cockpit 
2. takoff from outside
3. climb up to FL300 to simulate cruize
4. landing


Overall Rating: Very good
Conclusions of the testing: The sounds are just amazing! The Sounds outside could be a little louder but i think Boris already knows that

**Comment by RayPov** [comment]
I only did a takeoff and climb,  the sounds sound very good,  Idk if V1 and rotate will be added?

The only thing at this point I would like to add is when I did the press any key the game music stopped, midway through the next Mt Fuji screen it momentarily came on and then went off again.

**Comment by hotshotp** [comment]
> I only did a takeoff and climb, the sounds are very good, Idk if V1 and rotate will be added?
> 
> The only thing at this point I would like to add is when I did the press any key the game music stopped, midway through the next Mt Fuji screen it momentarily came on and then went off again.

v1 and rotate will be added. the sim menu has always been like that for me, and i didn't touch it

**Comment by smukherj1** [comment]
> The only thing at this point I would like to add is when I did the press any key the game music stopped, midway through the next Mt Fuji screen it momentarily came on and then went off again.

Hmm this doesn't happen for me, with or without the changes in this PR

**Comment by datrax** [comment]
> > The only thing at this point I would like to add is when I did the press any key the game music stopped, midway through the next Mt Fuji screen it momentarily came on and then went off again.
> 
> Hmm this doesn't happen for me, with or without the changes in this PR

It started happening to me after the last Asobo update.

**Comment by Smiths76245** [comment]
Sounds great so far. One thing noticed is that the throttle detent sounds for FLX and CLB are missing? When set to IDLE detent its there but bearly audible?

**Comment by Pheome** [comment]
* Are the throttle detent sounds for FLX and CLB missing? When set to IDLE detent its there but bearly audible?
It's in and it is loud enough to hear it well.
https://streamable.com/zy4th7

Boris the sounds are just amazing.Keep up the good work m8! :)

**Comment by hotshotp** [comment]
> Sounds great so far with regard to engine sound internal and external. 2 things though -
> 
> * Are the throttle detent sounds for FLX and CLB missing? When set to IDLE detent its there but bearly audible?
> * Runway center line is missing the reassuring thud as gain velocity. These 2 things perhaps using from Master later, sorry if mistaken. Edit - I could hear some thud sounds on the runway in the last flight, was a bit inconsistant during the roll but they do exist.

you might be on a very late version of the pr. I fixed all those problems about 2 days ago as they were noted

**Comment by RayPov** [comment]
I want to make sure I'm getting latest update,   do I follow the same checks > artifacts  download the latest version there path?

**Comment by CnRJay** [comment]
> I want to make sure I'm getting latest update, do I follow the same checks > artifacts download the latest version there path?

yes sir that is correct.

**Comment by danbw9** [comment]
Just tried the startup and shutdown engine sounds - very good and immersive and with 3D sound.

**Comment by Carter633** [comment]
Going to have a look at the progress of this later - can't wait to compare with the other day when we just had interior engine sounds! As you said it's a major part of the mod but you've really pulled it out of the bag so far! 💪

Keep up the great work Boris!

**Comment by armankir** [comment]
Name: Arman#8145
Date of testing: Current date 23/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1352

Testing technique: Take off and listen

Steps you've made to test the Pull Request:

Takeoff in cockpit view
Takeoff in external view
Takeoff in the wing view


Overall Rating: **_Excellent_**

Conclusions of the testing: Amazing work Borris! Even though you bully me on discord you do make the best sounds! Great work!

**Comment by Carter633** [comment]
Name: British Avgeek YT -- Carter633 #1436
Date of testing: 23/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1352 

Testing technique: Full Flight from Cold and Dark

Steps made to test the Pull Request:
1.Spawned Cold and Dark - worked through to push back and start in Vatsim
2. Reviewed all sounds throughout flight internally and externally

Overall Rating: Good - no, EXCEPTIONAL
Conclusions of the testing: Sounds are amazing. Incredible work Boris!

**Comment by FlightSimmer7700** [comment]
Name: FlightSimmer7700#3468
Date of testing: Current date 23/10/20
Version of the sim: 1.9.3
PR Tested: #1352 

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned at airport
2. Started up 
3. took off
4.Sim crashed
5.

Overall Rating: Amazing
Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.
Sounds all good to me maybe a IRL pilot could test just to make sure

**Comment by ChruutvoLuzi** [comment]
Name: ChruutvoLuzi#8902
Date of testing: 23/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1352

Testing technique: Started Colds and Dark but couldnt fly a flight with the latest PR due to time reasons yet, altough i flew lots of flight with the interior sound

Steps made to test the Pull Request:
1. Started Cold and Dark
2. tested all kinds of sound events


Overall Rating: very good, few minor Improvements required
Conclusions of the testing: All Sounds are very high fidelity and puts a big shadow over all other existing sound packages. However, there are a few minor quirks that i would like to adress, i may be wrong on some, as i am not a pilot:
GPWS Callouts such as Stall Stall, pull Up are audible in the cabin (probably the sound attenuations boris was talking about)
The engines are emitting sound from right or left in cabin view instead of direct emitting to the view as you basically look at the engine
Shutdown could (maybe?!) need a bit more bass (a pilot may confirm that)
 Thats all i can think of right now
**GJ BORIS**

**Comment by hotshotp** [comment]
> Name: ChruutvoLuzi#8902
> Date of testing: 23/10/2020
> Version of the sim: 1.9.5.0
> PR Tested: #1352
> 
> Testing technique: Started Colds and Dark but couldnt fly a flight with the latest PR due to time reasons yet, altough i flew lots of flight with the interior sound
> 
> Steps made to test the Pull Request:
> 1. Started Cold and Dark
> 2. tested all kinds of sound events
> 
> 
> Overall Rating: very good, few minor Improvements required
> Conclusions of the testing: All Sounds are very high fidelity and puts a big shadow over all other existing sound packages. However, there are a few minor quirks that i would like to adress, i may be wrong on some, as i am not a pilot:
> GPWS Callouts such as Stall Stall, pull Up are audible in the cabin (probably the sound attenuations boris was talking about)
> The engines are emitting sound from right or left in cabin view instead of direct emitting to the view as you basically look at the engine
> Shutdown could (maybe?!) need a bit more bass (a pilot may confirm that)
>  Thats all i can think of right now
> **GJ BORIS**

Gpws call-outs: that's an asobo issue and I plan to rewrite those much later as it will take me hours.

Emmiters: I can't really fully fix that as pretty much wwise emitters are a single point and if you like at one it will play it. Can't really fix that.

Shutdown sound is just as bassy as in startup. If I make it more bassy it will sound very bad, I've tried. It makes it very distorted.

Thank you!

**Comment by TenPatrol** [comment]
Name: Tenpatrol - _Patrol#9513
Date of testing: 24/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1352

Testing technique: Sound card Sound blaster Z & hadphones Creative Aurvana Live! From cold & dark to landing.
Steps you've made to test the Pull Request:
1. spawned cold & dark
2. engines start
3. taxi
4.take off
5. cruise
6 descent
7 landing
8 shutdown

Flight notes.

Startup: Amazing engines sound!
Taxi/Takeoff : as abowe.
Climb/Cruise: 
Showcase fixed camera - External 8 - sounds like air leak from tire.
External 12 and 13 - sound looping. Hard to explain.

Descent/Landing/Roll/Shutdown : Amazing engines sounds!

Conclusions of the testing: Engines sounds are ok but smth is wrong with sound looping and "air leak from tire" at climb and cruise.
Overall Rating: 9/10.

**Comment by hotshotp** [comment]
> Name: Tenpatrol - _Patrol#9513
> Date of testing: 24/10/2020
> Version of the sim: 1.9.5.0
> PR Tested: #1352
> 
> Testing technique: Sound card Sound blaster Z & hadphones Creative Aurvana Live! From cold & dark to landing.
> Steps you've made to test the Pull Request:
> 1 spawned cold & dark
> 2 engines start
> 3 taxi
> 4 take off
> 5 cruise
> 6 descent
> 7 landing
> 8 shutdown
> 
> Flight notes.
> 
> Startup: Amazing engines sound!
> Taxi/Takeoff : as abowe.
> Climb/Cruise:
> Showcase fixed camera - External 8 - sounds like air leak from tire.
> External 12 and 13 - sound looping. Hard to explain.
> 
> Descent/Landing/Roll/Shutdown : Amazing engines sounds!
> 
> Conclusions of the testing: Engines sounds are ok but smth is wrong with sound looping and "air leak from tire" at climb and cruise.
> Overall Rating: 9/10.

Air leak sound is the backwash of the engines and is present in the default asobo sounds, interior view isn't looping, the leap engine oscillates in real life forward and backward and makes that effect but the loop I used is very long. It isn't a problem with my sound but rather the actual leap engine ;)

**Comment by TenPatrol** [comment]
> Air leak sound is the backwash of the engines and is present in the default asobo sounds

2nd flight (same testing technique) and no air leak sound so maybe msfs bug or A32NX?

> (...) interior view isn't looping, the leap engine oscillates in real life forward and backward and makes that effect but the loop I used is very long. It isn't a problem with my sound but rather the actual leap engine ;)

What about exterior view (showcase > external 12)
I hear strange sound every second. File modified via magix samplitude professional.
[https://www.dropbox.com/s/hls7iwjmxssxy5a/cruise_external12.MP3?dl=0](url)

**Comment by hotshotp** [comment]
> > Air leak sound is the backwash of the engines and is present in the default asobo sounds
> 
> 2nd flight (same testing technique) and no air leak sound so maybe msfs bug or A32NX?
> 
> > (...) interior view isn't looping, the leap engine oscillates in real life forward and backward and makes that effect but the loop I used is very long. It isn't a problem with my sound but rather the actual leap engine ;)
> 
> What about showcase > external 12
> I hear strange sound every 2 seconds. File modified via magix samplitude professional.
> [https://www.dropbox.com/s/hls7iwjmxssxy5a/cruise_external12.MP3?dl=0](url)
> 
> 
> 

Oh crap... That does sound like a looping issue. I'll take a look, sounds like it's in my buzzsaw

**Comment by hotshotp** [comment]
> > Air leak sound is the backwash of the engines and is present in the default asobo sounds
> 
> 2nd flight (same testing technique) and no air leak sound so maybe msfs bug or A32NX?
> 
> > (...) interior view isn't looping, the leap engine oscillates in real life forward and backward and makes that effect but the loop I used is very long. It isn't a problem with my sound but rather the actual leap engine ;)
> 
> What about showcase > external 12
> I hear strange sound every 2 seconds. File modified via magix samplitude professional.
> [https://www.dropbox.com/s/hls7iwjmxssxy5a/cruise_external12.MP3?dl=0](url)

FIXED :)

**Comment by Derek-Lane** [comment]
Name: Derek Lane #6079
Date of testing: 24/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1352

Testing technique: Head phone and speaker testings
Steps you've made to test the Pull Request:
1 spawned cold & dark
2 engines start
3 taxi
4 take off
5 cruise
6 descent
7 landing
8 shutdown
9.various engine settings, start, idle, mid, full, all ranges though reverse.

Conclusions of the testing: Engines sounds are amazing. I didn't hear any specific issues
Overall Rating: 10/10.

**Comment by TenPatrol** [comment]
> FIXED :)

Thank You.
Almost perfect mate  9,5/10 ;)

Now I hear something new durning cruise and sometimes durning the descent.
**Smth like crackles on vinyl.**

Cruise - Camera showcase external 12
[https://www.dropbox.com/s/dbz3c2h0xqxxakj/cruise_external_12.MP3?dl=0](url)

Cruise - Camera showcase external 13
[https://www.dropbox.com/s/zxkytioeqvtqxg3/cruise_external_13.MP3?dl=0](url)

**Comment by hotshotp** [comment]
> > FIXED :)
> 
> Thank You.
> Almost perfect mate 9,5/10 ;)
> 
> Now I hear something new durning cruise and sometimes durning the descent.
> **Smth like crackles on vinyl.**
> 
> Cruise - Camera showcase external 12
> [https://www.dropbox.com/s/dbz3c2h0xqxxakj/cruise_external_12.MP3?dl=0](url)
> 
> Cruise - Camera showcase external 13
> [https://www.dropbox.com/s/zxkytioeqvtqxg3/cruise_external_13.MP3?dl=0](url)

just tested couldnt reproduce: oh and just a FYI, if users do hear any audio pops, its likely down to latency issue and a sudden choke on system performance. I occasionally get them if my CPU spikes 100% out of no where or fps drops below 30 sometimes, but this isn't related to the audio which i have done

**Comment by ukflyer** [comment]
these new engine sounds are awesome guys thank you

**Comment by TenPatrol** [comment]
>  oh and just a FYI, if users do hear any audio pops, its likely down to latency issue and a sudden choke on system performance. I occasionally get them if my CPU spikes 100% out of no where or fps drops below 30 sometimes, but this isn't related to the audio which i have done

My rig specs: i9 9900KF, RTX 2080 Super Gaming X Trio, 32GB ram, sound blaster Z and FPS always more than 30.
CPU usage not higher than 50/60/70%
For sure everything is ok with my cpu,gpu, drivers and system performance.

A320 neo_asobo_vanilla_cruise_showcase_fixed_camera_external_13
and everything is ok
https://www.dropbox.com/s/lj88g2prf15g732/vanilla_showcase_external_13.MP3?dl=0

A320 Neo_asobo_vanilla_cruise_showcasefixed_camera__external_12
and everything is ok
https://www.dropbox.com/s/nzapn2iikwz73y1/vanilla_showcase_external_12.MP3?dl=0


A32NX_PR#1352_cruise_showcase_fixed_camera_external_13
and crackles on vinyl
https://www.dropbox.com/s/m1vawxtlj7egvp5/PR%231352_showcase_external_13.MP3?dl=0


A32NX_PR#1352_cruise_showcase_fixed_camera_external_12
and crackles on vinyl
https://www.dropbox.com/s/kuj7bf134a844ko/PR%231352_showcase_external_12.MP3?dl=0


A32NX_latest dev built: 2020-10-25T03:41:28+00:00_cruise_showcase_fixed_camera_external_13
https://www.dropbox.com/s/gfzvft106gtruf3/Latest_dev_showcase_fixed_camera_external_13.MP3?dl=0
and crackles on vinyl



A32NX_latest dev built: 2020-10-25T03:41:28+00:00_cruise_showcase_fixed_camera_external_12
https://www.dropbox.com/s/mip7g3rks3igpgu/Latest_dev_showcase_fixed_camera_external_12.MP3?dl=0
and crackles on vinyl


**A32NX_mod_built: 2020-10-17T19:55:28+00:00
cruise_showcase_fixed_camera_external_13 and everything is ok**
https://www.dropbox.com/s/wfnya66afkjvfpl/dev_showcase_external_13.MP3?dl=0

**A32NX_mod_built: 2020-10-17T19:55:28+00:00
cruise_showcase_external_12 and everything is ok**
https://www.dropbox.com/s/2bg0qp6faddad1v/dev_showcase_external_12.MP3?dl=0


Can you merge your PR#1352 with build: 2020-10-17T19:55:28+00:00 and send me via DM on discord?
_Patrol#9513

**Comment by hotshotp** [comment]
> > oh and just a FYI, if users do hear any audio pops, its likely down to latency issue and a sudden choke on system performance. I occasionally get them if my CPU spikes 100% out of no where or fps drops below 30 sometimes, but this isn't related to the audio which i have done
> 
> My pc specs: i9 9900KF, RTX 2080 Super Gaming X Trio, 32GB ram, sound blaster Z and FPS always more than 30.
> CPU usage not higher than 50/60/70%
> For sure everything is ok with my cpu,gpu, drivers and system performance.
> 
> A320 neo_asobo_vanilla_cruise_showcase_fixed_camera_external_13
> and everything is ok
> https://www.dropbox.com/s/lj88g2prf15g732/vanilla_showcase_external_13.MP3?dl=0
> 
> A320 Neo_asobo_vanilla_cruise_showcasefixed_camera__external_12
> and everything is ok
> https://www.dropbox.com/s/nzapn2iikwz73y1/vanilla_showcase_external_12.MP3?dl=0
> 
> A32NX_PR#1352_cruise_showcase_fixed_camera_external_13
> and crackles on vinyl
> https://www.dropbox.com/s/m1vawxtlj7egvp5/PR%231352_showcase_external_13.MP3?dl=0
> 
> A32NX_PR#1352_cruise_showcase_fixed_camera_external_12
> and crackles on vinyl
> https://www.dropbox.com/s/kuj7bf134a844ko/PR%231352_showcase_external_12.MP3?dl=0
> 
> A32NX_latest dev built: 2020-10-25T03:41:28+00:00_cruise_showcase_fixed_camera_external_13
> https://www.dropbox.com/s/gfzvft106gtruf3/Latest_dev_showcase_fixed_camera_external_13.MP3?dl=0
> and crackles on vinyl
> 
> A32NX_latest dev built: 2020-10-25T03:41:28+00:00_cruise_showcase_fixed_camera_external_12
> https://www.dropbox.com/s/mip7g3rks3igpgu/Latest_dev_showcase_fixed_camera_external_12.MP3?dl=0
> and crackles on vinyl
> 
> **A32NX_mod_built: 2020-10-17T19:55:28+00:00 cruise_showcase_fixed_camera_external_13 and everything is ok**
> https://www.dropbox.com/s/wfnya66afkjvfpl/dev_showcase_external_13.MP3?dl=0
> 
> **A32NX_mod_built: 2020-10-17T19:55:28+00:00 cruise_showcase_external_12 and everything is ok**
> https://www.dropbox.com/s/2bg0qp6faddad1v/dev_showcase_external_12.MP3?dl=0
> 
> Can you merge your PR#1352 with build: 2020-10-17T19:55:28+00:00 and send me via DM on discord?
> _Patrol#9513

no because that build had other problems which I fixed, no one else has been having this issue with the crackling so it is on your end

**Comment by TenPatrol** [comment]
> (...) no one else has been having this issue with the crackling so it is on your end

I don't think so.
If everything is ok with vanilla and A32NX_mod_built: 2020-10-17T19:55:28+00:00 that means smth is wrong with your PR or dev version.

**Comment by hotshotp** [comment]
> > (...) no one else has been having this issue with the crackling so it is on your end
> 
> I don't think so.
> If everything is ok with vanilla and A32NX_mod_built: 2020-10-17T19:55:28+00:00 that means smth is wrong with your PR or dev version.
> 

Again I've asked several people and they all had no issues.

**Comment by TenPatrol** [comment]
> Again I've asked several people and they all had no issues.

So I'am one of a kind 😄  Thank You for your time.

**Pull request merged**
