### PR TITLE
Update usages of deltaTime to use time between update calls instead of time between frames.

### LINKED ISSUE #529: [BUG] Systems affected by screen refresh rate (deltaTime)
Master tracking issue for things that get broken by FPS mods. Checked items have been identified and fixed.

- [ ] Self test takes longer than it should
- [ ] un-aligned PFD messages flash slower than they should
- [ ] Mode Change on ND is slow
- [ ] Brake Temp decay (Wheel Page) (will be fixed by a32nxcore changeS)

### PR DESCRIPTION
**Pull request by UncleClapton**
Fixes #529 

**Summary of Changes**

* Add a util function for keeping track of local `deltaTime`.
* Prefer local update delta over frameDelta where it's needed.
* Make `A32NX_Core` a bit more extensible.

### CODE REVIEW

**Review by NathanInnes — COMMENTED** [review]
Tested and working well. Code review looks good to me but I would like a second opinion from someone.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: Current date 24/09/2020
Version of the sim: 1830
PR Tested: #811 

Testing technique: Try-out method
Steps you've made to test the Pull Request:

1. C/D start at EKCH and full flight to ENGM

Overall Rating: Very good
Conclusions of the testing: Haven't noticed any abnormal behaviour and I noticed a performance boost when running this PR

**Review by AdenFlorian — APPROVED** [review]
code looks good! ready to test!

Here's a list of things that look like they would be affected by the delta time stuff from Asobo's last patch.
I believe these items were happening slower than they hsould be, and this PR should make them faster again:

ADIRS align time
APU Flap time
screen self test time
ND mode change time
ND range change time
PFD flash rate of elements when not aligned
FMA highlight time
rollout FMA delay
reactive speed of elements on the PFD

**Comment by AdenFlorian** [comment]
I tested as well, and it looks good!

**Pull request merged**
