### PR TITLE
fix: FCU knobs sound and minor emissive fixes

### PR DESCRIPTION
**Pull request by ImenesFBW**
### Sound
- all FCU knobs now have our custom sound events attached to them (heading and VS knobs were attached to default turning sounds)
- added sound to Altitude Increment Selector (no sound was attached to 100/1000 switch)
- added sound to VS knob push/pull event (no sound was attached to VS push/pull )
- all FCU sounds now play our custom sound on push/pull (The push/pull sounds on all the knobs were playing the default sounds which are too loud)
### Emissive
- removed emissive from the Altitude Increment Selector knob
- fixed FO throttle detent lighting up with no power
## Videos (sound)
Before:

https://user-images.githubusercontent.com/71195324/106657277-1e255a00-659c-11eb-8d84-33f059cafce7.mp4

After:

https://user-images.githubusercontent.com/71195324/106657374-3ac19200-659c-11eb-8933-b81166319b5d.mp4
## Screenshots (emissive)

BAtitled-1

## Additional context

Most of these are fixes. The only real change is the push and pull sound which was changed to our QNHknob wwise event as suggested by @hotshotp, and the alt increment selector not being illuminated (behavior confirmed with the real world operators)

Discord username: Imenes#8739

## Testing instructions
Make sure all FCU knobs sounds work correctly now.  Check the same for the emissive changes.   

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by tyler58546 — APPROVED** [review]
LGTM

**Review by hotshotp — COMMENTED** [review]
LGTM

**Review by hotshotp — APPROVED** [review]

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 4.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3295 
Tier of testing: 1
### Changes to observe: FCU Knob sounds and emissive fixes
Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned C/D in dark environment.
2. Checked first officer's side of throttle detent decal.
3. Checked Altitude Knob indicator
4. Checked all the knobs and attached sounds on the FCU

### Media:
image
image

### Issues (If Any): None.
### Conclusions of the testing: Textures fixed and new sounds linked, good to go!

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/04/2021
Version of the sim: 1.12.13.0
PR Tested: #3295 
Tier of testing: 1
Changes to observe: FCU knobs sound and minor emissive fixes

Testing technique: Twisting/clicking knobs and checking for emissive light.

Steps you've made to test the Pull Request: 
1. Spawned at gate in dark enviroment to look for emissive on shown places. (all good).
2. Checked sounds on all knobs on the FCU. No hangup or any issues occured.

Flight notes (When done a full flight):

Media: 

Issues (If Any): None.

Overall Rating: Good.
Conclusions of the testing: Sounds good and looks fine.

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 06/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3295
Tier of testing: 1
Changes to observe: FCU knobs sounds & emissive

Testing technique: Look at
Steps you've made to test the Pull Request:
1. Spawned in C&D
2. Didn't power the aircraft up and checked throttle emissive & all FCU knobs sounds in the dark
3. Powered up the aircraft and checked altitude knob emissive

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: LGTM

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 6.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3295 
Tier of testing: 2
Changes to observe: FCU Knobs Sound and Emissive fixes


Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned C&D in LSZH at night
2. Checked Altitude increment Switch for emissive
3. Turned the Aircraft on
4. Checked the sounds of all FCU Knobs

Media:
Microsoft Flight Simulator Screenshot 2021 02 06 - 13 37 42 23

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Everything works as described, Altitude Increment Emissive is gone and the Potis all have sound attached to them.

**Pull request merged**
