### PR TITLE
Upper ECAM engine thrust rating modes logic rework

### LINKED ISSUE #1198: [REQUEST] Flex to Temp Indication in upper ECAM
**Is your feature request related to a problem? Please describe.**

The "auto" indication stands for TOGA and also will display as TOGA.
Note that "auto" is currently displayed at all flight phases.

**Describe the feature you'd like to see implemented**

Rename "auto" to TOGA
If Flex to Temp is set -> Display the Flex to Temp readout instead of the "auto" (TOGA) as seen in both pictures.
After Take-Off and the rest of the flight the readout will be "CLB" for Climb.

**References**

On Taxi to Take-off https://www.youtube.com/watch?v=cv41hm4JEB8&feature=youtu.be&t=100
Landing https://youtu.be/FODhSJucbK0?t=64

TOGA:
image
Flex to Temp:
image
CLB (Climb)
image

This shows the current situation:
image

**Additional context**

Discord username DerL30N#3751

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #1198

## Summary of Changes

- Added MREV for reverse.
- Added update condition for touch down and lift off.
- FLEX Temperature is being displayed on FLX thrust rating mode, however no thrust limit values are displayed because this feature is not implemented.
- Added thrust rating mode logic.
- Added thrust mode START.
- Applied FADEC power logic.

## Screenshots (if necessary)

(Before) Fictional auto can be seen.
image

(After) MREV, new engine mode thats displayed.
image

## References

https://youtu.be/FODhSJucbK0?t=102
https://youtu.be/cv41hm4JEB8?t=18

### Indicates the thrust rating mode based on:
- The position of the thrust levers,
- Aircraft on ground or in flight,
- The engine status, i.e. running or not running,
- The data entered in the T.O and CLB panels of the FMS ACTIVE/PERF page.

### Conditions
When on ground, thrust rating mode shall be TOGA unless FLEX TEMP is set and flight phase is before CLIMB PHASE and thrust lever position is not set to TOGA or thrust lever lever is in reverse, thrust rating mode shall be MREV.

When in air,
current flight phase has advanced TAKOFF PHASE, thrust rating mode shall be CLB unless thrust lever is set to MCT/FLX detent, thrust rating mode shall be MCT, or thrust lever is set to TOGA detent, thrust raing mode shall be TOGA.

### Notes
If flex to temp has been set before take off, after landing thrust rating mode will be FLX.
This happens because the mcdu keeps the take off content and flight phase gets reset.

Also:
Derated takeoff and soft toga are not implemented.

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
Don't forget to add a changelog.

**Comment by FlightSimmer7700** [comment]
Name: FlightSimmer7700#3468
Date of testing: Current date DD/MM/YYYY
Version of the sim: Version the tester uses
PR Tested: #1513
Object of test: (The engine thrust mode on the upper ECAM)

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned at the gate in Athens
2. Flew the flight
3. Landed in Skiathos
4.
5.

Flight notes

Startup: Notes on the startup (Everything is normal)

Taxi/Takeoff : Notes on the taxi an takeoff (Everything is normal)

Cruise: Notes on cruise (Everything is normal)

Descent/Landing : Notes on descent and landing (Work as expected)

Shutdown: Good

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: It does what it's supposed to and goes from TOGA when taxing and taking off to MCT(Can't remember exactly what its called I think it's that) when on the MCT detent and climb when on the climb detent and below

**Comment by MisterChocker** [comment]
@FlightSimmer7700 Thank for testing! From my side green for merge.

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 27/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1513
Object of test: The engine thrust mode on the upper ECAM. Check for current indications and accuracy.

Testing technique: Observe the engine thrust rating indications. 
Steps you've made to test the Pull Request:

Did a C&D, normal start, taxi, take off into a circuit at UAAA
Observing the thrust rating during initial start up, engine start, take off, whole circuit and checking landing MREV indications when not in idle reverse.

Startup: Everything is normal

Taxi/Takeoff : Everything is normal

Cruise: Everything is normal

Descent/Landing : Everything is Normal

Issues (If Any): only the limitations as mentioned in the notes section by the author. 
Overall Rating: Good
Conclusions of the testing: LGTM. Appreciate the work @MisterChocker. Another little detail related to engine thrust rating which could be added is on ENG START - as soon as FADEC is powered up (ENG mode to START) and all XXs disappear the upper ECAM engine thrust indication should show CLB and the corresponding percentage. then when 2nd engine master is switched to on, the engine thrust indication goes to the take off thrust setting (FLX or TOGA) and its corresponding percentage.

**Comment by MisterChocker** [comment]
@danbw9 Another little detail related to engine thrust rating which could be added is on ENG START - as soon as FADEC is powered up (ENG mode to START) and all XXs disappear the upper ECAM engine thrust indication should show CLB and the corresponding percentage. then when 2nd engine master is switched to on, the engine thrust indication goes to the take off thrust setting (FLX or TOGA) and its corresponding percentage.

To do so I would need conditions for ENG START, when does the engine thrust mode is START, e.g. both engines off, only on ground? And the mode to display would be CLB?
In terms of thrust rating values, this might be something for the future, more precisely, a feature that could/will come with our wip FADEC.

**Comment by lukecologne** [comment]
> 
> To do so I would need conditions for ENG START, when does the engine thrust mode is START, e.g. both engines off, only on ground? And the mode to display would be CLB?
> In terms of thrust rating values, this might be something for the future, more precisely, a feature that could/will come with our wip FADEC.

What was meant was that the engine mode selector is in the ign/start position. Also, FADEC power state is already simulated, though it only has an effect on the E/WD display and none of the systems IIRC

**Comment by MisterChocker** [comment]
I will now implement FADEC power logic for this one as well as it was not before.

**Comment by lukecologne** [comment]
Why do you want to implement logic that is already done? Just use this simvar: A32NX_FADEC_POWERED_ENG:ENG_ID

**Comment by MisterChocker** [comment]
> Why do you want to implement logic that is already done? Just use this simvar: A32NX_FADEC_POWERED_ENG:ENG_ID. Or did I misunderstand you?

You misunderstood me, thats exactly what I did, it was just not done before.

**Comment by lukecologne** [comment]
Ah, sorry, disregard then

**Comment by MisterChocker** [comment]
Implemented FADEC power logic and thrust mode START.

**Pull request merged**
