### PR TITLE
[ND] Add track line to ARC and NAV map mode

### PR DESCRIPTION
**Pull request by ilyeshammadi**
Fixes #[issue_no]

## Summary of Changes

I added a very important and missing feature which is the track line to ARC and NAV map mode.

#### What has been done:
- Added heading line to ARC and NAV mode
- Resize the diamond in NAV to be similar to the ARC mode (Was too big and unrealistic)

### Before
Screenshot 2020-11-22 205407
###
Screenshot 2020-11-22 205323

## References

https://youtu.be/TEi-WX08ov8?t=24

image0

## Additional context

Discord username (if different from GitHub): Union Araken#4083

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by mikecbr** [comment]
I think also there is something that misses , but thats another topic , The airplane right now does not show the runway one it is slected in the FP like in the picture you showd.
image

**Comment by lukecologne** [comment]
Correct me if I'm wrong, but it looks like you always show the track line. In reality, it is only shown when the lateral autopilot mode is HDG or TRK

**Comment by ilyeshammadi** [comment]
> Correct me if I'm wrong, but it looks like you always show the track line. In reality, it is only shown when the lateral autopilot mode is HDG or TRK

It only show-up when heading mode is selected.

**Comment by ilyeshammadi** [comment]
> Correct me if I'm wrong, but it looks like you always show the track line. In reality, it is only shown when the lateral autopilot mode is HDG or TRK

And for the **TRK** can not take it into consideration since that button is INOP for now.

**Review by wpine215 — APPROVED** [review]

**Review by Benjozork — APPROVED** [review]

**Comment by ilyeshammadi** [comment]
@Noxleee thank you for the testing, I'm not 100% sure that the 360 rotation is related to this PR and also not sure how to reproduce it.

**Comment by danbw9** [comment]
Category: QA Test
Name: danbw9#7028
Date of testing: 23/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2060
Object of test: Testing the added track line on ND

Testing technique: Normal flight - departure from RJTT 
Steps you've made to test the Pull Request:

Load up, spawning on RWY22 at RJTT. Setup for normal SID along RWY heading. 
- take off in NAV mode following the SID
- simulate being given a radar heading - press selected HDG and the track line correctly pops up
- tried adjusting the in game wind to get a larger cross wind component to see how it handles - all fine
- Confirmed the blue triangle heading bug is the correct size now using above references and via other photos
- Confirmed the track line is visible in the two modes ROSE NAV and ARC mode only.

Issues (If Any): None.
Overall Rating: Good
Conclusions of the testing: LGTM. Neat feature. It was definitely missing. Really useful when flying, so thanks for this @ilyeshammadi for your work. I checked the above reported behaviour by @Noxleee and I could not reproduce this, but I have seen this happen many times before the PR. Usually an occurrence when switching views from cockpit quickly to exterior and back to cockpit, the ND goes crazy, and takes 2-3 seconds to settle down on the actual heading. All good to merge from me.

**Comment by ilyeshammadi** [comment]
@danbw9 thank you for your testing. Indeed I also saw that behaviour before this PR and can reproduce it using the DevKit by restarting the display. So I will say it's more something to how the display refresh mechanism is in place, hope it will be fixed soon.

**Pull request merged**
