### PR TITLE
MCDU working menu page, atsu menu, basic weather request, basic aoc message functionality

### PR DESCRIPTION
**Pull request by edwinbrowwn**
Fixes #[issue_no]

**Summary of Changes**
Updated menu page
Added active system status on menu page (green system highlights)
Added ATSU menu
Added AOC menu
Added weather request page
Weather request prefills departure and arrival airports
Weather request only supports live reports at the moment
Weather request only supports metars at the moment (taf, taf+metar coming next)
Weather request output displays in received messages
Basic message pagination implemented
Occasional system lag for realism

**Screenshots (if necessary)**

https://i.imgur.com/iAQj6dC.jpg
https://i.imgur.com/vgTdk92.jpg
https://i.imgur.com/Cg4sr7y.jpg
https://i.imgur.com/ssDrCW2.jpg
https://i.imgur.com/VbSVDfY.jpg

**Additional context**
Currently using aviationweather.gov for weather reports. Data requesting using reverse proxy.
This is a basic framework of the weather request system. All modifications are non breaking.
A few minor bugs may be noticed.

Discord username (if different from GitHub): Edwin B#3166

### CODE REVIEW

**Comment by Benjozork** [comment]
Hello,

Can you clarify why you chose `https://weather.fs-2020.org/` ? It is unclear who owns this API and if we have permission to distribute a client for it to thousands of people.

**Comment by edwinbrowwn** [comment]
@Benjozork I own it. Its just a simple proxy for aviationweather.gov (cors issues). 
Resources used (Every request page is different per airline it seems):
- https://www.youtube.com/watch?v=Tel_jFm7wLg
- http://equicom.net/mcdu/
- FSLABS

**Comment by starvingjavi** [comment]
Tested and works as intended

**Comment by speedwaystar** [comment]
"Occasional system lag for realism". Yikes! :)

**Comment by armankir** [comment]
Ready to merge from my testing.

**Comment by starvingjavi** [comment]
The functionality works as described. However, I get a bug when trying to input data on the MCDU while testing this. For example, I would write for the TOW/CG "61.1/28.1" and input it with no problems. What I wrote would transfer to TOW/CG and disappear from where I would write. When I move to another page and try to input another thing, whatever I wrote previously would appear again and I would be writing on top of it. Continuing my example, if I try to now input the transtition altitude of wherever I am flying I would try to write "18000", but on the MCDU it would appear as "61.1/28.118000".

To test this bug:
1. Input cruise altitude in INIT A page
2 Change page to PERF and input a speed into V1
3. Check that the previous input doesn't reappear

**Comment by edwinbrowwn** [comment]
> The functionality works as described. However, I get a bug when trying to input data on the MCDU while testing this. For example, I would write for the TOW/CG "61.1/28.1" and input it with no problems. What I wrote would transfer to TOW/CG and disappear from where I would write. When I move to another page and try to input another thing, whatever I wrote previously would appear again and I would be writing on top of it. Continuing my example, if I try to now input the transtition altitude of wherever I am flying I would try to write "18000", but on the MCDU it would appear as "61.1/28.118000".
> 
> To test this bug:
> 
> 1. Input cruise altitude in INIT A page
>    2 Change page to PERF and input a speed into V1
> 2. Check that the previous input doesn't reappear

Thank You. I will check this out when I'm off, that is very odd. I can't think of a reason how that would be possible. 95% of the changes are new files. Does it also happen to other input fields?

**Comment by DoToAdventures** [comment]
Great work, looks good!

However.. I have concerns about this pulling the data from a website owned by an inividual, to be honest. What happens with this if you for whatever reason decide to not maintain that domain anymore or anything like that? We would lose a functionality of the mod.

But that's just my opinion, I don't know if anyone else shares it.

**Comment by UncleClapton** [comment]
I agree with DoTo. I'm against merging this PR as-is. If we need to run a proxy to handle CORS issues, then that should not be under the control of 3rd party individual. Nothing on you personally @edwinbrowwn. It's more about sticking to principals of network/application security.

**Pull request closed without merging**
