### PR TITLE
fix(mcdu): fuelpred running when inputting weights after engine start

### PR DESCRIPTION
**Pull request by Maximilian-Reuter**
Fixes #[issue_no]

## Summary of Changes
Currently the Fuel Prediction is not run when forgetting to put in Weights and CG before Engine start. 
This happens because `mcdu._fuelPredDone = true;` is never executed. 

This PR simply runs the same function that the INIT B page executes to set this value.

I am not sure if this is the cleanest way to resolve this, but this is only a quick fix and can be changed at a later date.
## Additional context

Discord username (if different from GitHub): Chaoz#3065

## Testing instructions

1. Start C/D
2. Perform normal setup without inserting Weights and CG and/or Blockfuel on the INIT B page
3. Start any Engine
4. INIT B page should switch to FUEL PRED with everything dashed except for FOB
5. Insert weights 
6. After a delay the page should populate with the prediction results

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
- [x] Start C/D
- [x] Perform normal setup without inserting Weights and CG on the INIT B page
- [x] Start any Engine
- [x] INIT B page should switch to FUEL PRED with everything dashed except for FOB
- [x] Insert weights
- [ ] After a delay the page should populate with the prediction results

Negatives:
Bug does not appear to have been fixed by this change

Test Results: 
Not Passed

**Comment by Maximilian-Reuter** [comment]
> * [x]  Start C/D
> * [x]  Perform normal setup without inserting Weights and CG on the INIT B page
> * [x]  Start any Engine
> * [x]  INIT B page should switch to FUEL PRED with everything dashed except for FOB
> * [x]  Insert weights
> * [ ]  After a delay the page should populate with the prediction results
> 
> Negatives: Bug does not appear to have been fixed by this change
> 
> Test Results: Not Passed

curious, but this is why we test. It works on my local build where this is the only change made.
I assume you didn't enter the block fuel as well. Cause that leads to it not working after engine start.
If you do, it should work. 
Will take a look at that.

**Comment by Maximilian-Reuter** [comment]
Now it should work even if neither ZFW & CG nor Blockfuel was entered

**Comment by Maximilian-Reuter** [comment]
> > Now it should work even if neither ZFW & CG nor Blockfuel was entered
> 
> How can the FM predict fuel burn without knowing the aircraft weight/CG (needs ZFW + ZFWCG)?

Maybe I wasn't clear enough, I was talking about the init b page having no weights entered. The bug meant even if you entered weights in the fuel prediction page after engine start you still didn't get a prediction. Now you do.

**Comment by tracernz** [comment]
Oh, haha. None of this logic should be in pages, but not worth fixing it until post-vnav merge.

**Comment by Tokyys** [comment]
### **Quality Assurance Trainee Report**

**Discord:** Tokyy#4279
**Object of testing:** #7896 
**Tier of Testing:** 1
**Date:** 29/03/2023

### **Testing Process:**

> 
> 1. Load to the game on stand when plane is in Cold&Dark state.
> 2. Perform normal setup without inserting Weights and CG and Blockfuel on the INIT B page
> 3. Start any engine
> 4. INIT B page switch to FUEL PRED with everything dashed except for FOB
> 5. Insert weights
> 6. Prediction results are loaded after few seconds

> Tested with flight plans LKPR - EGCC, LKPR - LHBP
> 
> Engine started - Fuel pred with everything dashed except for FOB
> FlightSimulator_D4vKbFfJDC
> 
> After inserting weights - Before prediction results loaded fully
> FlightSimulator_dH384EOY2i
> 
> After inserting weights - Loaded fully
> FlightSimulator_XBXXtIep5v


### **Negatives:** 

> **N/A**

### **Testing Results:**

> **PASS**

**Pull request merged**
