### PR TITLE
fix(nd): keep to-wpt-state on mode switch

### PR DESCRIPTION
**Pull request by globin**
## Summary of Changes
The ND would lose the to-waypoint-identifier when switching between modes until the next WPT change.

## References
n/a

## Additional context
This pulls up the wpt/vor/ils information and ident state to the ND so it is not lost on mode changes. Before this was received in the ToWaypointIndicator from a CoherentEvent (opposed to simvars like the other data), this state is now passed in as a prop in order to not lose it on mode switch (and ToWaypointIndicator recreation).

An alternative would be to set the ident as a simvar and receive it from there, but I'm not aware of the implications since I'm not to firm with flight simulator development yet.

## Testing instructions
* spawn c/d or on rwy
* enter a wpt
* switch between ND modes
* check to-waypoint-identifier is still displayed

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
Seems fine to me. We may use simvars later but no reason not to fix this right away. 👍

**Review by Lucky38i — APPROVED** [review]
LGTM

**Comment by globin** [comment]
Artefact for QA https://cloud.glob.in/s/DA6TG2gF4ytnHys

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #6637
Tier of Testing  : 1
Date             : 06/02/2022

Testing Process: 
Spawned on runway and C/D. - Next waypoint always stayed displayed in the corner of ND and waypoints sequenced correctly. See negatives for the issue. 

Negatives:       
Found a small bug where PPOS and first waypoint of the plan were superimposed on each other in ARC and rose NAV views with ADIRS not aligned. Also ILS and VOR are superimposed with PPOS on the ground (see last two photos). This issue is not present in experimental, so something with the keeping of the waypoint/ILS/VOR got messed up in this PR:

Testing Results:
Not passed

Conclusions: 
Works nicely, but the bug mentioned in negatives needs to be adressed.
Media:       
image

image

image

image

**Comment by globin** [comment]
@mico975 fixed, thanks for the report!

**Comment by mico975** [comment]
Updated the above test report. Now passed.

**Comment by globin** [comment]
@Lucky38i @tracernz @Benjozork anything missing here?

**Comment by Benjozork** [comment]
#6643

**Comment by globin** [comment]
Rebased and fixed conflict my other ND-fix-PR that was merged

**Comment by tracernz** [comment]
I've pushed a different fix to cfms-15, using simvars to send the ident (and the approach message), which should be nicer on perf. We'll keep this PR for a couple of days to make sure that code is good, then we can close.

**Pull request closed without merging**
