### PR TITLE
[PFD] Improved svg line length

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Corrected length of speed bands withe line.

## Screenshots (if necessary)

Before (left) After (right)
image
image

## References

image
image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by ilyeshammadi** [comment]
@MisterChocker great work, do you think you can include the changes for the altitude cursor stroke-width that is not uniform around the small numbers. For the record I've tried to change it but didn't know how to 😁

**Comment by MisterChocker** [comment]
> @MisterChocker great work, do you think you can include the changes for the altitude cursor stroke-width that is not uniform around the small numbers. For the record I've tried to change it but didn't know how to 😁

sorry can't follow your idea here.

**Comment by MisterChocker** [comment]
sorry, can't do, I don't understand these svg stuff. And actually don't want to. I am pretty sure that will be covered by #1866.

**Comment by ilyeshammadi** [comment]
> sorry, can't do, I don't understand these svg stuff. And actually don't want to. I am pretty sure that will be covered by #1866.

No problem.

**Comment by MisterChocker** [comment]
@atcopilot I already tried previously without any success. May be done in #1866, not sure about the scope of that pr yet.

**Comment by lukecologne** [comment]
Yes, it will. The scope is a complete redo of the PFD from scratch, except for the FMA.

**Review by Benjozork — APPROVED** [review]

**Comment by Benjozork** [comment]
SImple enough to be merged

**Pull request merged**
