### PR TITLE
[LIGHTS] ADD logo light logic (flybywiresim#1362)

### LINKED ISSUE #773: [REQUEST] Tail/Logo light behaviour
**Is your feature request related to a problem? Please describe.**

Currently the tail/logo light is on when the nav lights are on, also the cabin lights. This is not correct, since the tail/logo light is switched off automaticallly when the flaps are retraced and comes on automatically when the gear is lowered...

**Describe the feature you'd like to see implemented**

I would like to see that the tail/logo light is extinguished when flaps are retracted to 0 and the tail/logo light is on when the gear goes down.

**References**

http://www.smartcockpit.com/docs/A320-Lights.pdf

**Additional context**

Discord username (if different from GitHub):

### LINKED ISSUE #1362: [REQUEST] Logo light shall be off when gear up
**Is your feature request related to a problem? Please describe.**

In flight, we can see logo light on the tail

**Describe the feature you'd like to see implemented**

In flight, when gear is up, logo light shall be extinguished.

**References**

**Additional context**

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by linkeleven**
Fixes #773 [REQUEST] Tail/Logo light behaviour
Fixes #1362 [REQUEST] Logo light shall be off when gear up 

## Summary of Changes

Logo lights disable when airborn and the slats are retracted.
I connected the logic to the flaps handle.

## References

A320_Lights_NAVLOGO

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Rameyuk** [comment]
Ohh... bye bye tail logo.. I'll miss looking at you during night flying...

**Comment by armankir** [comment]
Tested earlier.

Works as described, after airborn logo light disabled and slats retracted.

No issues to report on my end, good work.

**Comment by armankir** [comment]
Name: Arman#8145
Date of testing: Current date 22/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1490 

Testing technique: Took off and looked if the logo light disabled after airborn.

Steps you've made to test the Pull Request:

Spawn C&D
Take off Runway 21L Copenhagen.
Look at the exterior view.
Verify it works as described.

Overall Rating: Good
Conclusions of the testing: No comments besides good work, these minor changes make the plane a whole lot better!

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: Current date 22/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1490

Testing technique: Departed and checked various scenarios

Steps you've made to test the Pull Request:

Spawned on RWY
Check logo light status on ground
Took off, gear up, leave slats out and check logo.
And in fully clean config, check logo again. 

Overall Rating: Good
Conclusions of the testing: Simple fix but adds to realism.

**Comment by Benjozork** [comment]
Sorry we forgot to add the label.

**Comment by Benjozork** [comment]
I'll merge this when I get to my computer

**Pull request merged**
