### PR TITLE
fix(textures): fuel panel decals

### LINKED ISSUE #4149: Minor Fuel Panel Visual Anomolies
**Mod Version**

{
  "built": "2021-03-27T05:01:07+00:00",
  "ref": "autopilot",
  "sha": "683d55037e05dab68ac80dff914854f9984f2d00",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

Minor visual anomolies on the Fuel panel. Left hand FUEL text appears to have a bracket next to it, and the Left Tank Pump 2 korry has the "OFF" box item clipped. 

**To Reproduce**

1. C&D, batteries on, External Power on.
2. Observe Fuel Panel.

**Expected behavior**

Fairly self explanatory.

**Actual behavior**

Minor visual anomolies.

**References**

Screenshot 2021-03-27 123902

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): AirbusA320Pro

### PR DESCRIPTION
**Pull request by ImenesFBW**
Fixes #4149 

## Summary of Changes
Fixed the clipping decals next to  HYD FUEL text on the fuel panel, and moved the OFF label up a few pixels to make the bottom line more visible on some buttons as much as possible without being able to edit the UV island for the label.

## Screenshots (if necessary)
Before:
image
After:
image

## Additional context

Discord username (if different from GitHub): Imenes#8739

## Testing instructions
Check that the extraneous line right of HYD FUEL is not there anymore. Make sure the upper line of OFF label is not clipping anywhere now that it was moved up a few pixels. And check for any other relevant decal issues.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by pepperoni505 — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 27.3.2021
Version of the sim: 1.14.6.0
PR Tested: #4152
Tier of testing: 1
Changes to observe: Fuel panel decals
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat.
3.) Looked at decals

Media:


Image1


Image2

Issues: 

Overall Rating: Good

Conclusions of the testing: Looks good

Hope this helps :-)

**Comment by Matse08** [comment]
Category: QA Tester
Name: Matse#7454
Date of testing: 27.03.21
Version of the sim: 1.14.6.0
PR Tested: #4152 
Tier of testing: 1
Changes to observe:Fuel panel decals


Testing technique: Try-out
Steps you've made to test the Pull Request:
1.Spawned C&D 
2. Turned on BAT
3. Turned on ANN LT
4. Looked after the changes




Media: 
Microsoft Flight Simulator 27 03 2021 22_40_38


Issue:

Overall Rating: Good
Conclusions of the testing: Think many people have noticed that ( I have) And nice that its fixed now

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 3/27/2020
Version of the sim: 1.14.6.0
PR Tested: #4152 
Tier of testing: 1
Changes to observe:
Fixed the clipping decals next to HYD FUEL text on the fuel panel, and moved the OFF label up a few pixels to make the bottom line more visible on some buttons as much as possible without being able to edit the UV island for the label.

Testing technique: Tried out
Steps you've made to test the Pull Request:
1. C&D at KDEN during the day and looked at decals
2. C&D at KDEN during the night and looked at decals
3. Power on at KDEN during the day and looked at decals
4. Power on at night and looked at decals


Flight notes (When done a full flight):

Media: 
image

image

image

image

Issues (If Any): Write any issues
The white line above xflow is hard to see/ goes away when zoomed out
image


Overall Rating: Good
Conclusions of the testing: Looks good other than the white line issue.

**Pull request merged**
