### PR TITLE
fix: door lock animation 

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

Fixes the cockpit door switch to pop back to NORM after LOCK is selected

## Screenshots (if necessary)

https://user-images.githubusercontent.com/71195324/104086065-ce7d9800-5254-11eb-8c81-3e399e6726bf.mp4

## References
Behavior confirmed by IRL A320 pilots

## Additional context

Imenes#8739

## Testing instructions
Should be a quick check, please check if the switch works correctly in all stages of flight.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by NathanInnes — APPROVED** [review]
LGTM! Ready to test

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 09/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2950 
Object of test: Check Door Lock Animation
Testing technique: Tryout

Steps you've made to test the Pull Request:

1.Spawned at VABB gates, C/D
2.Turned on battery, external power.
3. Checked door switch pop back to center after each lock/unlock

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Switch reverts to center position as expected. This was something I missed from the Aerosoft cockpits back on P3D and it's finally here. Good one Imenes! :)

**Comment by NickFarin** [comment]
Category: QA Trial
Name: Discord User: Nick F[Z+8] #5327
Date of testing:10/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2950 
Object of test: Door lock switch animation
Testing technique: Flicked switch and see if it returns to norm position
Steps you've made to test the Pull Request:
1. Spawned at RPLL
2. Started up and tested if the switch returned to the norm position after placing it at the unlocked and locked position at the gate and during taxi, cruise and after landing.

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: The test was normal and it works fine.

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 9.1.2021
Version of the sim: 1.12.13.0
PR Tested: #2950 
Object of test:Door Lock Animation Fix

Testing technique: Try Out
Steps you've made to test the Pull Request:
1. Spawned C&D
2. Tested the switch

Flight notes (If required): none

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Small fix, works as described

**Pull request merged**
