### PR TITLE
[CDU] RADNAV rework 1

### LINKED ISSUE #132: NAVAID Tuning
On the RAD NAV page you should be able to tune NAVAIDs with the Identifier. Currently only possible with the frequency.

### LINKED ISSUE #1200: [REQUEST] RAD NAV PAGE insert via IDENTIFIER (text insert option)
**Is your feature request related to a problem? Please describe.**

Atm when trying to insert via identifier this is action is "not allowed"

**Describe the feature you'd like to see implemented**

Entering FORs/NDBs or AFDs via their identifier.

**References**

Shows entry of VOR https://youtu.be/5uN1Rr-hGcQ?t=461 (Its a sim but SAME AS RL)
image
image

**Additional context**

Discord username DerL30N#3751

### PR DESCRIPTION
**Pull request by St54Kevin**
Fixes #1200
Fixes #132

## Summary of Changes

This is my first PR. As im starting to look into coding for the project this is my first try.
Im still learning so if you find something, please tell me :) Im happy to know what to do better!

This PR is supposed to improve RADNAV page. Main goal is IRL looks and behavior and the Ability to tune via the identifier.

- [X] Cosmetic improvements (font size, color, layout etc.)
- [X] Ability to disable/delete navaids
- [X] Frequency fetches identifier (when avail)
- [X] Tune via identifier (VOR/ADF)
- [X] Identifier fetches frequency
- [X] Add BFO Option (inop for now), when an ADF is set

**Known Bugs:**
- Identifier depending on signal:
The identifier display of Navaids on the RADNAV page will depend on the signal of that station. If its not reachable it will flicker or not be present.

**To be improved (in later PR):**
- Adjustable ILS CRS
- Correct font size depending on input
- Fix identifier display

Huge thanks to @beheh for his help!!

## Screenshots (if necessary)

**Before:**
image

**After:**
image

**Before:
image
After:**
image

## References

Honeywell_R1A_FMS_Pilot_Guide_Jan._2009.pdf

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by St54Kevin** [comment]
Ready to be tested!

**Review by Benjozork — APPROVED** [review]
LGTM

**Review by lukecologne — APPROVED** [review]

**Review by Carter633 — APPROVED** [review]
Name: British Avgeek UTube -- Carter633 #1436
Date of testing: Current date 20/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1960 
Object of test: RADNAV page updates

Testing technique: Full Flight EGCC - EGLL
Steps you've made to test the Pull Request:
1. Spawn Cold and Dark - input all flight data into MCDU
2. Checked RADNAV page - looks great
3. Checked data already input and added go-around VOR freq and a hold freq within the STAR at Bovingdon
4. All inputs went in correct - tried incorrect values, they were refused
5. Flew entire flight on VATSIM, checked for issues throughout

Flight notes
No issues


Issues (If Any):  No issues
Overall Rating: Good
Conclusions of the testing: Testing went well - short flight SANBA1R - HON - BNN4A ILS 27R for the quick route. RADNAV page worked well - tested VOR, ILS and ADF fields and all worked as described. New layout is much better too! Thanks

**Comment by lukecologne** [comment]
Tested and works very nicely. Going to merge.

**Comment by mikecbr** [comment]
I think I found another bug , In the navigation display , when you select VOR in the FCU , It does not show any indication of the closets VOR and it appears also and M Wich means that it is manual mode instead of automatic .
Are you working also on this ?

**Comment by St54Kevin** [comment]
> I think I found another bug , In the navigation display , when you select VOR in the FCU , It does not show any indication of the closets VOR and it appears also and M Wich means that it is manual mode instead of automatic .
> Are you working also on this ?
> 

I don't know what you mean. You mean that the automatic tuning is not working? Well that's because the plane currently doesn't have it implemented. But you said When you select a VOR. It will show in the ND

**Pull request merged**
