### PR TITLE
feat: SimBridge features for flyPad - local files

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes

Add the following SimBridge dependent features and fixes to the flyPad:

- [x] ~Health Status Icon in Status Bar~ (moved to #7445)
- [x] Local Files
  - [x] Images
  - [x] PDF
- [x] Fix pagination for PDF
- [ ] Fix horizontal and vertical zoom for mixed PDFs (landscape and portrait pages)
- [ ] Testing

## Screenshots (if necessary)
image

## Additional context
Requires SimBridge - therefore targeted against the Experimental branch for now.

Discord username (if different from GitHub): Cdr_Maverick#6475

## Testing instructions
TBD

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
this cannot be merged or put into exp before https://github.com/flybywiresim/simbridge/issues/30 is fixed

**Comment by Benjozork** [comment]
@Lucky38i

**Comment by frankkopp** [comment]
> this cannot be merged or put into exp before https://github.com/flybywiresim/simbridge/issues/30 is fixed

No problem - will take a while anyway. Zomming, rotating etc. needs to be fixed

**Comment by frankkopp** [comment]
Replaced by #7451

**Pull request closed without merging**
