### PR TITLE
feat(efb): TOD calculator improvements

### PR DESCRIPTION
**Pull request by arturkuma**
## Summary of Changes
TOD calculator improvements:
- move information about current altitude sync to store, so it won't restart on page change
- implement sync on:
  - distance (to next waypoint)
  - vertical speed **(available if current vertical speed is negative value)**
  - flight path angle **(available if current flight path angle is negative value)**
- desired vertical speed (in result component) should be negative value since we're descending
- predefined '-' sign in calculation inputs (for VS and FPA)

## Screenshots (if necessary)

Climbing, so SYNC available only for distance:
2021-02-20 19_01_55-Microsoft Flight Simulator - 1 13 16 0

Descending, SYNC available also for VS:
2021-02-20 19_07_39-Microsoft Flight Simulator - 1 13 16 0

SYNC enabled for VS:
2021-02-20 19_07_52-Microsoft Flight Simulator - 1 13 16 0

SYNC enabled for distance:
2021-02-20 19_08_51-Microsoft Flight Simulator - 1 13 16 0

Manual input for angle - can enable sync or clear input
2021-02-20 19_12_01-Microsoft Flight Simulator - 1 13 16 0

Manual input but no SYNC available - we are ascending
2021-02-20 19_13_27-Microsoft Flight Simulator - 1 13 16 0

## Testing instructions

There was no changes in calculation alghoritm.

I think it's worth to focus on new 'SYNC' functions - distance, vertical speed and angle.
Please remember, that SYNC for VS and angle is enabled only if plane is descending (negative values).
If SYNC is enabled and plane will climb for some reason, it'll automaticly disable and clear value.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 20.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3647
Tier of testing: 2
Changes to observe: TOD Improvements
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned Runway EDDP-LEPA
2.) Took off and get to CRZ Altitude and set Target Alt. to 5000ft
3.) SYNC GS, Current Alt. and DIST (Image1)
4.) SYNC GS, Current Alt. and ft/min, set V/S to -500ft/min (Image2)
5.) SYNC GS, Current Alt. and ft/min, set G/S to -2degrees (Image3)
6.) SYNC GS, Current Alt. and ft/min, set new altitude to 20000ft (Image4)

Media:


Image1


Image2


Image3


Image4

Tested: 
- Distance jumps to next waypoint whe crossing current one
- Page don't reset after changing pages

Issues: 
- When EFB turned off the Page don't reset
- In TRK mode with G/S: G/S and V/S is SYNCable; In HDG mode with V/S: Only V/S is SYNCable
- As font jumps down a bit when entered a value the "-" becomes off
- When just a new (lower) altitude is entered (no V/S or G/S): no V/S or G/S is SYNCable

Overall Rating: Good. Maybe small changes

Conclusions of the testing: Awesome improvements! A few things could be fixed.

Hope this helps :-)

**Comment by arturkuma** [comment]
Thank you :)

> When EFB turned off the Page don't reset

Fixed

> In TRK mode with G/S: G/S and V/S is SYNCable; In HDG mode with V/S: Only V/S is SYNCable

Unfortunately SIM does not provide us real G/S. It's set in TRK mode and we can read it from there.
Sim provides us vertical speed in any case, thats why we can read it anytime. To resume:

- G/S - only when TRK is ON
- V/S - always

I think we have to live with that for now. Eventually we can disable SYNC function on G/S at all. But I think it's better to live with what we have - still better than nothing.

> As font jumps down a bit when entered a value the "-" becomes off

Fixed

> When just a new (lower) altitude is entered (no V/S or G/S) only V/S is SYNCable

Not sure if thats what you meant but:
V/S becomes syncable when VS is lower than zero. However very often on cruise plane makes small adjustments and never holds perfect 0. I've added margin so VS will be syncable when actual VS is lower than -50. 

I think your case is not related to newer lower altitude entered. Maybe you also had bad impression about lack of G/S. The reson is like i described above.

**Comment by marcman86** [comment]
This explains that you can sync both in TRK mode and just V/S in all other modes. So this is good for now.

Will test the small fixes.

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 21.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3647
Tier of testing: 2
Changes to observe: EFB TOD improvements
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned at night C&D EDDP
2.) Turned on bat., ext. power and EFB, switch to TOD calculator
3.) Set some values (Image1), checked for the "-"
4.) Switched to another page and back, TOD don't reset
5.) Turned off EFB and back on again, TOD did reset

Media:


Image1


Image2

Issues: 
- Can you have a empty GS with new lines, like the other lines? So grey instead of 0. Min Alt. preselect to 0 is fine (gives an idea of the meaning) (Image2)

Overall Rating: Good

Conclusions of the testing: Almost perfect

Hope this helps :-)

**Comment by arturkuma** [comment]
> Can you have a empty GS with new lines, like the other lines? So grey instead of 0. Min Alt. preselect to 0 is fine (gives an idea of the meaning) (Image2)

Hi, I'm not sure if thats what you mean - but i've did it like this: when SYNC ground speed is 0, when you switch to manual mode, in first line you'll have min altitude 0 and GS **NOTHING** (before it was **0**)

2021-02-21 17_03_53-Microsoft Flight Simulator - 1 13 16 0

Hope thats it :)

> G/S angle shows "degrees °"

Fixed

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 21.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3647
Tier of testing: 2
Changes to observe: EFB TOD
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat., ext. power and EFB, switch to TOD page
3.) Played with different TOD modes

Issues: -

Overall Rating: Good

Conclusions of the testing: Good to go!

Hope this helps :-)

**Comment by arturkuma** [comment]
@Benjozork can we change label of this PR to Ready for test?

**Comment by starvingjavi** [comment]
Name: Javi#2557
Date of testing: 22.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3647
Tier of testing: 2
Changes to observe: EFB TOD improvements
Testing technique: Complete flight KSTL -> KDEN on VATSIM. 
Flight was FFT6514.
Flight Plan:
BRAKK5 HLV MCI J24 OATHE DANDD1

Steps made to test the Pull Request:

1.) Spawned at night in KSTL in C&D conditions
2.) Followed procedures to get the airplane running
3.) Set the EFB with simbrief username to get flight data. Checked changing pages between Performance page and other pages.
4.) Take off without any problems from runway 30L
5.) Continued with the departure BRAKK5
6.) Climbed to cruise level. Kept checking for loss of functionality when changing pages on EFB. Tried calculating descent rate and descent angle from current altitude on sync to the altitudes 1000, 500, -500, -1000.
7.) Continued on cruise different tests to calculate distance to start descent using vertical speed and flight path angle. The altitudes used were 1000, 500, -500, -1000.
8.) After those tests were done the calculator was used to plan for the descent to KDEN via DANDD1
9.) Continue approach
10.) Land
11.) Terminate flight

Media:
Captura de pantalla 2021-02-22 222248
Captura de pantalla 2021-02-22 222304
Captura de pantalla 2021-02-22 222343
Captura de pantalla 2021-02-22 222458
Captura de pantalla 2021-02-22 222517
Captura de pantalla 2021-02-22 222540
Captura de pantalla 2021-02-22 222556
Captura de pantalla 2021-02-22 222614
Captura de pantalla 2021-02-22 222629

Issues:
When trying to calculate the distance to start descending while setting any vertical speed for an altitude below 0ft (-500, and -1000ft), the calculator would not output any answers. No problems when using the angle or the distance.

Overall Rating: Sync works as described and the math works for most of the options. Check on the case of negative altitudes while selecting a vertical speed for descent.

Conclusions of the testing: Very good, needs polishing. I would also add more instructions to test the ground speed section.

**Comment by arturkuma** [comment]
Hi,

I think that the problem is with negative target altitude. It just has to be positive value

Screenshot 2021-02-23 at 09 03 05

Can u confirm that?

**Comment by arturkuma** [comment]
> I would also add more instructions to test the ground speed section.

I'm thinking about some document describing how calculations are done. I can see on some chats that people already are curious about that. Do we have some space for documentation like that yet @Benjozork ? Other options is just youtube video with some simple diagrams.

**Comment by starvingjavi** [comment]
> Can u confirm that?

Yes it works as you described

However there are some airports that have a negative altitude so I was testing for those. I was also trying to see what would be the breaking point of the calculator.

**Comment by easyjetsimpilot** [comment]
Category: QA Tester
Name: Gavin (easyjetsimpilot)
Date of testing: 23.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3647
Tier of testing: 2
Changes to observe: TOD Sync integration
Testing technique: Full Flight

Steps made to test the Pull Request:

1.) Set up to fly NZQN-NZHN
2.) Observed during climb Sync not available for V/S & Angle 
3.) Whilst cruising and planning TOD for the approach, upon syncing & altering the GS for decent, this seemed to cause major issues with the AP Navigation. Unsure as to whether this was related to the Sync coding, however, the AP started to pull left every time the Manual Input was selected for the GS. 

Please see the following stream from 1:21hrs in to witness the effect GS Sync and manual GS speed had on the aircraft. https://www.youtube.com/watch?v=Xh6lbksBGuM

Overall Rating: Unsuccessful. 

Conclusions of the testing: Needs investigating. 

FlyByWire on YouTube was also in the stream at the time (whoever holds the account :-) ) and witnessed this live.

**Comment by marcman86** [comment]
I tested this about 1/2 hour in air and had no problems. From video it looks like the classic MSFS deadzone problem.

**Comment by easyjetsimpilot** [comment]
> I tested this about 1/2 hour in air and had no problems. From video it looks like the classic MSFS deadzone problem.

Not a deadzone issue, but has been confirmed as a keybinding issue.

**Pull request merged**
