### PR TITLE
fix(nd): TCAS symbols correctly display in all nav/rose views, fixed TCAS related TypeError exception to console

### LINKED ISSUE #4581: Wrong ND TCAS Display Range
**Aircraft Version**

```json
{
  "built": "2021-04-24T19:05:06+00:00",
  "ref": "master",
  "sha": "43a8c41776d5b381af620ecc47fcfdaab29bee3b",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**
if u select a range more than 20 nm on ND you cant see the diamonds of the tcas traffic. 

**To Reproduce**

1.leave the pilots ND in 20nm range 
2.change the copilot side in more than 20nm range ND 
3. u will see all the traffic from tcas all the diamonds etc in all the altitudes working in the side of the pilot 
4.if u find a traffic symbol and u change from 20nm to 40nm the symbol is dissappear 

**Expected behavior**
to see the tcas symbols in all the range of ND from 10nm to 180nm

**Actual behavior**
u can see the tcas symbol (diamond or circle at every altitude but only in selected range of 20nm on ND

**References**

as u can see tcas is working for me at all altitudes and for all traffic 37000ft i just keep the pilot side always at 20nm range on ND

Microsoft Flight Simulator 25_4_2021 11_43_53
Microsoft Flight Simulator 25_4_2021 09_34_28

### LINKED ISSUE #4952: TCAS ND Display Error - stops displaying air traffic, exception prints to console
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-29T03:58:33+00:00",
  "ref": "HEAD",
  "sha": "823a86ff0d87b39db4108ba0b4fe9d29d7b2aa94",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

When around any airport with Live Traffic on, sometimes TCAS ND Display will bug out and stop displaying. A typerror - object is undefined exception is printed to js console.

### Expected behavior

TCAS should function normally, showing surrounding air traffic

### Steps to reproduce

Launch either at a gate or in mid-air at busy airport and wait for a plane to spawn in (May take some time)
Occasionally this will bug out the display

### References (optional)

image
image
image

### Additional info (optional)

Noticed it while sitting at YBAS while testing some other PRs. This is a fairly remote airport with little traffic, so I switched to various other busier locations and confirmed its a recurring and reproducible issue.

### Discord Username (optional)

2Cas#1022

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #4952
Fixes #4581

Note: This is not a complete TCAS overhaul, this is just to fix some semi-critical and long standing issues with the default Asobo TCAS ND display. A proper implementation of ADS-B / ATSAW (#5014) is coming. 

## Summary of Changes

- [x] Reproduce and fix TCAS related altText.textcontent TypeError exception - Caused by updateDraw() being called before createDraw() and trying to look up variables that have not been init
- [x] TCAS symbols drawn on the 40/80/160/320 ARC views
- [x] TCAS symbols drawn on the 40/80/160/320 nm ROSE view

This PR fixes two bugs, 

Firstly a frustrating and hard to reproduce bug where the JS console would be flooded with stack trace errors whenever an AI plane spawned in, sometimes causing the TCAS symbol for that plane to bug out. It's not entirely known how to reproduce this error, but ensuring that a certain bit of code is called **before** the problem causing code seems to solve the issue. 

Secondly a bug where the 40 nm ROSE/ARC view was not displaying TCAS symbols, because of the maximum TCAS NPC aircraft symbol display range being incorrectly processed.

## Screenshots (if necessary)

1. altText bug with error output to js console (Left) vs Fixed (Right)

FlightSimulator_JLqQXV3QCh

2. 40 nm ROSE/NAV view now displays TCAS symbols

FlightSimulator_0oDvF4HRcu

v85idg4Js2

(TCAS symbols display up to ~30 nm, this is correct behavior according to documentation and intended behaviour)

xu3narzuTD

## References

> G. Information Display The TCAS information is presented on the CAPT and F/O NDs of the EFIS
 system. Additional messages can also be presented on the display units ofthe ECAM system.
> (1) Traffic information on the ND
> Target aircraft are presented on the ND in ROSE or ARC mode but not in PLAN mode. Traffic indications show the situation in the zone. Aircraft present in this zone are represented by symbols whose shape and color correspond to the type of intruders defined in the TCAS. 
> ...
These indications are only presented for the 10, 20 and 40 NM selections. 
> ...

>TCAS intruders shall be displayed on ND Capt and F/O in all Rose modes and ARC mode:
>Full time option installed: For all ranges except in ZOOM ranges, NDRange > 9NM,
>Full time option not installed: For all ranges <=41 nm except ZOOM ranges: NDRANGE > 9nm
https://www.aviationmatters.co/tcas-guide/
http://a320dp.com/A320_DP/warning-systems/sys-16.3.2.html
https://www.icao.int/APAC/Meetings/2011_ADS_B_SITF10/SP07b_Airbus%20-%20ADS-B%20IN.pdf
https://www.aviatorsbuzz.com/techtalks/a320s-traffic-alert-and-collision-avoidance-system-tcas/

## Additional context

Really annoying to debug

Discord username (if different from GitHub): 2Cas#1022

## Testing instructions

1. Turn Live Traffic on in the options
2. Use Coherent GT Debugger (SDK) to observe the JS console (A320_Neo_MFD_1/A320_Neo_MFD_2)
3. Spawn in at a major airport with lots of AI traffic planes around. (i.e. Charles De Gaulle airport, JFK, etc.)
4. Start your plane as normal, turn TCAS to TA/RA 
5. Either fly a normal flight and try to stay within TCAS range of surrounding traffic, or use slew mode to position your aircraft facing a runway and adjusting altitude by slewing up/down to deliberately have TCAS intruding traffic.
6. Turn to the 40 nm NAV/ROSE views, these should show TCAS traffic symbols when intercepted by traffic. 
7. Check that the 20nm/10nm NAV/ROSE views still work as expected
8. Check that 80/160/320 views still do not show TCAS traffic
9. No exceptions should print to the console. Note: As this bug is hard to reproduce, around 10-15 minutes of traffic should pass without any TypeError javascript exceptions printing to the console. 
10. Turn TCAS to STDBY and check that this also does not cause errors to be printed to the console

Keep an eye out on regular flights outside of dedicated testing when you encounter traffic that the ND displays TCAS symbols as expected.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by aguther — APPROVED** [review]
LGTM

**Comment by Samueleonard** [comment]
Quality Assurance Tester Report

Discord: 1samueleonard1
Object of testing: #5059
Tier of Testing: 1
Date: 08/06/2021

Testing Process: 
live traffic on, spawn at LEBL, power up etc, tcas to ta/ra and observe traffic as decribed above - traffic appears on TCAS and does not cause issues, do full flight (lebl-lemh) and check TCAS functions as intended


Negatives: n/a
Testing Results: (Passed)

Conclusions: seems to work, possible i got lucky, needs more to confirm
Media: n/a

**Comment by 2hwk** [comment]
The documentation we referred to earlier is a bit incomplete, based on feedback from real world pilots, typically TCAS will be shown at all ranges. 
>TCAS intruders shall be displayed on ND Capt and F/O in all Rose modes and ARC mode:
>Full time option installed: For all ranges except in ZOOM ranges, NDRange > 9NM,
>Full time option not installed: For all ranges <=41 nm except ZOOM ranges: NDRANGE > 9nm

**Comment by marcman86** [comment]
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #5059
Tier of Testing: 1
Date: 10/06/2021

Testing Process: 
- Turned on real time live traffic
- Spawned in flight over KBOS
- Turned on TCAS to TA/RA
- Switched to ND modes and ranges
- Switched on weather and terrain (Fig1)

Negatives: -
Testing Results: Passed
Conclusions: Works

Media: 

Fig1

Hope this helps :-)

**Comment by Cryptic56** [comment]
Quality Assurance Tester/Trainee Report

Discord: Cryptic#4731
Object of testing: #5059
Tier of Testing: 1
Date: 12/06/2021

Testing Process: Spawned in to YSSY with live traffic on
Switched to TA/RA 
Changed TCAS to ALL
Observed traffic as described using different TCAS modes and ranged.
Slewed at different altitudes to intercept traffiv
Observed console

Negatives: n/a
Testing Results: Passed

Conclusions: LGTM, worked as expected

**Comment by BritishAvgeek** [comment]
Quality Assurance Tester Report
Discord: BritishAvgeek#1436
Object of testing: #5059
Tier of Testing: 1
Date: 12/06/2021

Testing Process: 
1. Spawned in at EGLL C&D and set up for a short flight to EGCC just for testing purposes
2. Switched to TA/RA and TCAS to ALL
4. Used different TCAS modes and ranges to check whether the PR worked
5. Flew about near to plenty of traffic to check the function of it all


Negatives: N/A
Testing Results: Passed

Thanks for your work!

**Pull request merged**
