### PR TITLE
fix(xml): Swapped altitude reporting knob state tooltips

### LINKED ISSUE #7994: Altitude Reporting Knob Tooltip is Backwards
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-04-27T17:10:27+00:00",
    "ref": "refs/heads/master",
    "sha": "f05684bcdea40e0a3ae14f6fcefd227d6a284f5f",
    "actor": "crocket63",
    "event_name": "manual",
    "pretty_release_name": "master:f05684bc",
    "version": "v0.10.0-dev.f05684b"
}
```

### Describe the bug

When you turn the knob for Altitude Reporting the tooltips are flipped (e.g. when turning off the tooltip says it will turn on).

### Expected behavior

Before you turn altitude reporting off, the tooltip should indicate that it will turn it off (and vice versa).

### Steps to reproduce

1. Load into the airplane
2. Hover over the Altitude Reporting knob
3. Note that it states the opposite of what it will do

### References (optional)

https://user-images.githubusercontent.com/9065136/235334785-0ea7a2c0-3e6e-408b-b86f-c21da9dd5f77.mp4

### Additional info (optional)

_No response_

### Discord Username (optional)

GamerKingFaiz#2501

### PR DESCRIPTION
**Pull request by GamerKingFaiz**
Fixes #7994 

## Summary of Changes
Swaps the tooltips for when the Altitude Reporting switch is turned.

### Before

https://user-images.githubusercontent.com/9065136/235335628-a7fd389a-4c8e-4f27-9718-8cf87e396582.mp4

### After

https://user-images.githubusercontent.com/9065136/235337314-cc42a572-bcad-405e-8ff8-210136e71f61.mp4

## Additional context

Discord username (if different from GitHub): GamerKingFaiz#2501

## Testing instructions

1. Load into the aircraft and hover over the Altitude Reporting switch.
1. When it is off, the tooltip should say "TURN ON ALT RPTG".
1. When it is on, the tooltip should say "TURN OFF ALT RPTG".

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by brewers10** [comment]
Quality Assurance Tester Report

Discord: brewers_10#5706
Object of testing: #7995 
Tier of Testing  : 1
Date: 09/05/2023

Testing Process: 
Load into the aircraft and hover over the Altitude Reporting switch. - **OK**
When it is off, the tooltip should say "TURN ON ALT RPTG". - **FAIL**
When it is on, the tooltip should say "TURN OFF ALT RPTG". - **FAIL**

Negatives:       
The tips are still the wrong way around for me.

Testing Results: 
Not Passed

Conclusions: 
Still the same issue as before the fix.

**Comment by GamerKingFaiz** [comment]
@brewers10 did you use the build that was generated in the Checks tab of this PR?
I used that and is how I captured the video of the "After" result that I posted in the original comment of this PR.

Maybe you used the wrong downloaded build in MSFS? To confirm, open this file in your build folder `ModelBehaviorDefs\A32NX\generated\A32NX_Interior_ATC.xml` and make sure the following is there (line 233 & 234):
```xml
                    <ANIMTIP_0>TT:COCKPIT.TOOLTIPS.ATC_ALT_RPTG_TURN_OFF</ANIMTIP_0>
                    <ANIMTIP_1>TT:COCKPIT.TOOLTIPS.ATC_ALT_RPTG_TURN_ON</ANIMTIP_1>
```

If it's not exactly like that you're not using the correct build for this PR.

**Comment by brewers10** [comment]
> @brewers10 did you use the build that was generated in the Checks tab of this PR? I used that and is how I captured the video of the "After" result that I posted in the original comment of this PR.
> 
> Maybe you used the wrong downloaded build in MSFS? To confirm, open this file in your build folder `ModelBehaviorDefs\A32NX\generated\A32NX_Interior_ATC.xml` and make sure the following is there (line 233 & 234):
> 
> ```
>                     <ANIMTIP_0>TT:COCKPIT.TOOLTIPS.ATC_ALT_RPTG_TURN_OFF</ANIMTIP_0>
>                     <ANIMTIP_1>TT:COCKPIT.TOOLTIPS.ATC_ALT_RPTG_TURN_ON</ANIMTIP_1>
> ```
> 
> If it's not exactly like that you're not using the correct build for this PR.

Ok Roger. I’ll have a look tonight and make sure 😁

**Comment by brewers10** [comment]
Quality Assurance Tester/Trainee Report

Discord: brewers_10#5706
Object of testing: #7995 
Tier of Testing: 1
Date: 09/05/2023

Testing Process: 
Load into the aircraft and hover over the Altitude Reporting switch. - **OK**
When it is off, the tooltip should say "TURN ON ALT RPTG". - **OK**
When it is on, the tooltip should say "TURN OFF ALT RPTG". - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Sorry for yesterday's test, I had the experimental build of the A32NX installed aswell as the PR. Oops. All working perfectly now :)

**Pull request merged**
