### PR TITLE
chore: hard-fork and package renaming

### LINKED ISSUE #1215: Hard Fork A32NX
# The Problem

Our mod replaces the vanilla A320neo in the game, making it more difficult for users to switch back and forth.

MSFS updates can, and usually do, break our mod, because the mod is still dependent on some vanilla files that we do not have in our repo.

# Solution

Copy all files needed into our repo, and rename them.

# Execution

- [ ] Port base aircraft SimObject files (PR #2079)
- [ ] Port base aircraft avionics files
- [ ] Move all files to new VFS directory

# Pros

- Easily switch between vanilla and modded aircraft
- Less chance of MSFS updates breaking the mod
- More freedom over how we structure our mod

# Cons

- This might make it more difficult to absorb asobo's updates into our mod.

# Notes

We haven't decided yet whether we will do this or not.

### PR DESCRIPTION
**Pull request by wpine215**
Fixes #1215

## Summary of Changes

The A32NX is now present in the sim as its own standalone package/aircraft.

Discord username (if different from GitHub):

## Testing instructions

- Test all normal procedures during a full flight, making use of all available displays (PFD, ND, ECAM's, MCDU, EFB, RMP, FCU, EFB, etc.)
- Make sure you are able to load into the default Asobo A320neo as a separate plane
- Existing A320neo liveries will not work at the moment since they will reference the old package.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
Still a few files duplicating Asobo ones: https://gist.github.com/tracernz/556c1da5777ae84e6e40b9b5fae7ba39
Here's the dodgy script I haxed to check for dup files if needed:
https://gist.github.com/tracernz/48480b0932a1c2f8f3062e3dc15a39a4

And these lines in .gitignore need s/Asobo/FlyByWire/:
```
/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire/_A320_NEO/model/*.gltf
/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/Asobo_A320_NEO/model/*.bin
```

**Comment by ExampleWasTaken** [comment]
Category: QA Trial
Name: `ExampleWasTaken#0886`
Date of testing: 02/04/2021
Version of the sim: 1.14.6.0
PR Tested: #3932
Tier of testing: 2
Changes to observe:
hard-fork and package renaming

Testing technique:
1. Checked that A32NX is a separate aircraft in sim
2. Loaded C&D (Airbus House livery) at EDHI (default scenery)
3. Powered up
4. Took off 
5. Performed normal flight to ENGM (default scenery)
6. Landed & parked at stand

Flight notes (When done a full flight): 
Route:
```
EDHI/23 HAM1W HAM RIPAM RIPA3L ENGM/01L
```

Media: N/A

Issues (If Any): Distance counter stuck at 35nm (possible bug of master)
Steps to achieve the issue: Perform normal flight - watch distance counter stuck around 35nm

Overall Rating: Good/To be improved
Conclusions of the testing: Should the above mentioned issue be present in the master branch, it should probably be addressed in a separate PR and this PR is GTG.

**Comment by Awemeter** [comment]
I noticed that the flybywire livery name says flybywire-a320neo and the house one says flybywire-a320 neo

**Comment by Awemeter** [comment]
sim freezes when switching back to the dashboard page on efb

**Comment by Matse08** [comment]
Category: QA Tester
Name: Matse#7454
Date of testing: 02.04.21
Version of the sim: 
PR Tested: #3932
Tier of testing:3
Changes to observe:
New package

Testing technique: Full flight
Steps you've made to test the Pull Request:
1.spawned C&D 
2. Did all checks/preperationS til takeoff
3. climbed to cruise
4. Landed  at EGBB
5. did shutdown prosedure

Flight notes (When done a full flight):This works nice but the autopilot seems to just set the heading itself

Media:
Volanta 02 04 2021 20_09_33
Microsoft Flight Simulator 02 04 2021 20_06_48



Issues (If Any):autopilot seems to just set the heading itself
Speed sets itself to 999 but I know this is a master bug  
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: Its nice to have both a320s in the sim. Just waiting till we getting some liverys

**Comment by ExampleWasTaken** [comment]
After doing the return flight from ENGM to EDHI on the latest master, I cannot reproduce the distance counter getting stuck.

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 4/2/2021
Version of the sim: 1.14.6.0
PR Tested: #3932 
Tier of testing: 2
Changes to observe: Hard fork

Testing technique: Tried out
Steps you've made to test the Pull Request:
1. Full flight from KLGA to KDCA


Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): flybywire livery name says flybywire-a320neo and the house one says flybywire-a320 neo



Overall Rating: Good
Conclusions of the testing: No big issues

**Comment by Samueleonard** [comment]
Category: QA Tester
Name: 1Samueleonard1#0001
Date of testing: Current date 02/04/2021
Version of the sim: 1.14.6.0
PR Tested: #3932
Tier of testing: 2
Changes to observe: check acft works after hard fork

Testing technique: Tryout
1. load in c+d - seperate plane as expected
2. check efb, check all works 
3. click all buttons in plane - all work as before
4. set up for flight (egcc-egkk) - all mcdu works as fine
5. fly and land, monitoring systems + mcdu etc

Flight notes: no issues - all good

Media: n/a

Issues: n/a

Steps to achieve the issue n/a

Overall Rating: Good

Conclusions of the testing: good, lgtm

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 02/04/2021
Version of the sim: 1.14.6.0
PR Tested: #3932 
Tier of testing: 2

Changes to observe:
hard-fork and package renaming

Testing technique: Try-out with full flight

Steps you've made to test the Pull Request:
1. Spawned C&D EGGD
2. Before and after start checklist
3. TO + CRZ + DES
4. Landed smoothly at EGGW

Flight notes (When done a full flight):
N/A
Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A
Issues (If Any): Write any issues
N/A
Steps to achieve the issue:
N/A

Overall Rating: Good
Conclusions of the testing: GTG

**Comment by darkfury334** [comment]
Category: QA Trial
Name: DarkFury#4936
Date of testing: Current date 02/04/2021
Version of the sim: 1.14.6.0
PR Tested: #3932
Tier of testing: 2
Changes to observe:
own standalone package

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawn C&D at LFBO into a32nx
2. Follow all normal procedures for flight
3. Check all available displays and systems
4. Land at LFSB

Flight notes (When done a full flight):LFBO/32L F320 MEN5B MEN UN871 KONOL Z59 LUMEL LUMEL8K LFSB/33

Media:
Microsoft Flight Simulator Screenshot 2021 04 02 - 21 43 41 51
Microsoft Flight Simulator Screenshot 2021 04 02 - 22 09 24 96
Microsoft Flight Simulator Screenshot 2021 04 02 - 22 09 28 70
Microsoft Flight Simulator Screenshot 2021 04 02 - 22 09 53 52

Issues (If Any): V/S on descent would not work. The fuel prediction page and FOB on f-pln went dashed. few visual issues

Overall Rating: To be improved

Conclusions of the testing: Overall good however did encounter a few issues which should be addressed. I do not get when using the dev or experimental version.

**Review by lukecologne — APPROVED** [review]

**Comment by Awemeter** [comment]
> Category: QA Trial
> Name: DarkFury#4936
> Date of testing: Current date 02/04/2021
> Version of the sim: 1.14.6.0
> PR Tested: #3932
> Tier of testing: 2
> Changes to observe:
> own standalone package
> 
> Testing technique: Description of how you tested the Pull Request
> Steps you've made to test the Pull Request:
> 
> 1. Spawn C&D at LFBO into a32nx
> 2. Follow all normal procedures for flight
> 3. Check all available displays and systems
> 4. Land at LFSB
> 
> Flight notes (When done a full flight):LFBO/32L F320 MEN5B MEN UN871 KONOL Z59 LUMEL LUMEL8K LFSB/33
> 
> Media:
> Microsoft Flight Simulator Screenshot 2021 04 02 - 21 43 41 51
> Microsoft Flight Simulator Screenshot 2021 04 02 - 22 09 24 96
> Microsoft Flight Simulator Screenshot 2021 04 02 - 22 09 28 70
> Microsoft Flight Simulator Screenshot 2021 04 02 - 22 09 53 52
> 
> Issues (If Any): V/S on descent would not work. The fuel prediction page and FOB on f-pln went dashed. few visual issues
> 
> Overall Rating: To be improved
> 
> Conclusions of the testing: Overall good however did encounter a few issues which should be addressed. I do not get when using the dev or experimental version.

I had the same issue with vs on descent it kept defaulting to plus5000

**Pull request merged**
