### PR TITLE
[FIX] Hide blurred spinner mesh

### PR DESCRIPTION
**Pull request by lukecologne**
## Summary of Changes

* Fix the engine rotation templates in order to hide the blur spinner mesh
* This causes the spinner spiral to properly show up when the "medium blur" mesh is shown (see videos)
* Show the "Slow" blur mesh now all the time, this is a workaround to the fact that we cannot add a spinner spiral to the fast blur mesh, and should be removed once we can do this.

## Screenshots (if necessary)

Before: https://streamable.com/iiidxt
After: https://streamable.com/6vvu1p
After, with the slow blurred mesh showing all the time: https://streamable.com/au7de2

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Pleasure0102** [comment]
Think it is better ! Still only a soloution until we can change the model i would say, but a good compromise for now.

**Comment by lukecologne** [comment]
What I can do is just use the "SLOW" blur mesh all the time. But I don't know if this will look wrong or not, I'll have to try it out

**Comment by lukecologne** [comment]
> 
> 
> Think it is better ! Still only a soloution until we can change the model i would say, but a good compromise for now.

We would only need to change the UV of the "BLUR" spinner, and the add a spiral to it's texture.

**Comment by lukecologne** [comment]
I updated the PR comment with a potential change, where the slow blur mesh would be shown even at high RPM. Let me know what you prefer

**Comment by lukecologne** [comment]
Alright, I asked in the discord which version looks better, and they agreed the version with the "Slow" blur mesh looked best. This is still only a temporary solution until we can fix the UVs for the "blur" spinner and add a spiral to it.

**Pull request merged**
