### PR TITLE
[FMA] fma modes when disconnecting ap and during GOAROUND

### LINKED ISSUE #1222: [BUG] ILS FMA changes when disconnecting AP
**Mod Version**

Latest master

**Describe the bug**

After intercepting the G/S and LOC with the AP on, I disconnected the AP. The FMA reverted to "CLB" instead of remaining on the glideslope so I had to press the "APPR" button again on the FDU to recapture. The autothrust mode also changed to "THR CLB" when it should remain in "SPEED" mode. The FMA/FD should stay in "G/S LOC" when disconnecting the AP.

**To Reproduce**

1. With AP on, hit APPR button to intercept the localizer and glideslope.
2.Once established on the ILS approach, disconnect the autopilot (using the red button on the sidestick).
3.Note the FMA change (THR CLB, CLB) and pitch flight director no longer is giving glideslope guidance.

**Expected behavior**

When disconnecting the AP on an ILS approach, the FMA/FD should stay in "G/S LOC" so that you can use the flight directors to hand-fly the ILS. The autothrust mode should also remain in "SPEED" mode.

**Actual behavior**

Plane correctly stays in "LOC"  but the pitch mode reverts to "CLB" which renders the pitch FD useless. The autothrust mode also switched to "THR CLB."

**References**

This was just after disconnecting the AP on the ILS 16C into KSEA:
Screenshot (93)

Here is V1 Simulations (Real airbus captain) disconnecting the AP on an ILS in the FFA320. Note the plane stays in (G/S LOC) and the autothrust stays in (SPEED):
https://youtu.be/FsROrvv9tJs?t=6847

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### LINKED ISSUE #1705: GS disappears on approach when AP off
**Mod Version**
built: 2020-11-01T01:01:54+00:00
ref: refs/heads/master
sha: af858b4cd6c37cf087a04545ff1aa6c2b931f3b7
actor: Benjozork
event_name: push

**Describe the bug**
On an ILS with APPR engaged and AP on i have LOC and GS modes active.  When I disconnect the AP to land, aircraft goes into CLB and THR CLB on FMA.  This should still be GS/Speed as the active mode.  The thrust did not change, but it seemed to be only an indication on the FMA.

**To Reproduce**
Fly an ILS approach and engage APPR.  Disconnect autopilot and look at the FMA.

**Expected behavior**
When AP off, should stay SPEED/GS/LOC on FMA

**Actual behavior**
When I diconnected the AP, THR CLB and CLB show on FMA

**References**
A-320 pilot 

Was this working before/when did the issue start occurring?
unsure

Is this a problem in the vanilla unmodded game?
unsure
<

### PR DESCRIPTION
**Pull request by antikythera288**
Fixes #1222 
Fixes #1705

## Summary of Changes

This will give proper FMA Modes during an ILS Approach.

## Screenshots (if necessary)

Push APPR Button will ARM the correct ILS Modes
Fix1_ARM
At some point, LOC will capture aswell as G/S
Fix1_Captured
Later, when we have a valid Glide Slope we will show "Tracked"
Fix1_Tracking
When disconnecting the AP, the FMA modes will still remain (normally APPR should still be active, but thats an asobo limitation i guess)
Fix1_APDISCO
correct FMA modes during LAND phase
Fix1_Land

## References

https://www.theairlinepilots.com/forumarchive/a320/a320-fma.pdf

https://youtu.be/FsROrvv9tJs?t=6847

## Additional context

Discord username (if different from GitHub): mrmercury#8898

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by antikythera288** [comment]
some help or idea would be great! @Benjozork 

_L:A32NX_GOAROUND_NAV_MODE_ / _L:A32NX_GOAROUND_HDG_MODE_ are set to **0** when going into GOAROUND (from previous APPROACH FlightPhase)

this is important, as those flags will be set to 1 for the **GA TRK** exit logic. Right now my problem is, that the place where we set those local variables to 1 is not good. I would like to set them when pressing / pulling the HDG Knob from the FCU.

The logic should be ...

When in GOAROUND Mode, show GA TRK in the 3rd FMA Column until user Pushes (MANAGED) or Pulls (SELECTED). Then, show NAV or HDG on FMA's 3rd Column ...

http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.36.html

any advice would be helpful, maybe you can set the local vars for me on the cockpit?

**Comment by Lucky38i** [comment]
> some help or idea would be great! @Benjozork
> 
> _L:A32NX_GOAROUND_NAV_MODE_ / _L:A32NX_GOAROUND_HDG_MODE_ are set to **0** when going into GOAROUND (from previous APPROACH FlightPhase)
> 
> this is important, as those flags will be set to 1 for the **GA TRK** exit logic. Right now my problem is, that the place where we set those local variables to 1 is not good. I would like to set them when pressing / pulling the HDG Knob from the FCU.
> 
> The logic should be ...
> 
> When in GOAROUND Mode, show GA TRK in the 3rd FMA Column until user Pushes (MANAGED) or Pulls (SELECTED). Then, show NAV or HDG on FMA's 3rd Column ...
> 
> http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.36.html
> 
> any advice would be helpful, maybe you can set the local vars for me on the cockpit?

You should find the SIMVAR for MANAGED AND SELECTED modes, it may just be an attribute as-well. From there you should just do a conditional if statement
```js
if (phase === GO_AROUND) {
    if (managed) {
        //code to show NAV on FMA
    } else if (selected) {
        //code to show HDG on FMA
    }
}
```

**Comment by Benjozork** [comment]
Sorry I'm busy as hell with the update and other projects here and school.

I'll implement the simvars as soon as I have time but we have many things to deal with today.

**Comment by antikythera288** [comment]
I just need an example on how to set a local var after interacting with the cockpit. So when I pull/push the HDG Knob I want to set a local var ....

**Comment by Lucky38i** [comment]
> 
> 
> I just need an example on how to set a local var after interacting with the cockpit. So when I pull/push the HDG Knob I want to set a local var ....

just create it. If you set a local simvar and it doesn't exist then it'll be created

**Comment by antikythera288** [comment]
> > 
> 
> > 
> 
> > I just need an example on how to set a local var after interacting with the cockpit. So when I pull/push the HDG Knob I want to set a local var ....
> 
> 
> 
> just create it. If you set a local simvar and it doesn't exist then it'll be created

I know "how" to set and read local cars, I am doing it already. What I don't find is the place / file / code where I can actually add it. 
So basically, where in the code is the place which will be executed when I push/pull the HDG knob? Sorry for the misunderstanding and best regards

**Comment by antikythera288** [comment]
This needs to be closed as something went terribly wrong when rebasing master into the branch. Just to make sure i created another PR from a new created branch to have again a clean diff ... @Benjozork @Lucky38i  can you please adjust the labels?
@wpine215 .8 hadnt any changes on the airbus, so i guess all fine for the newest version

https://github.com/flybywiresim/a32nx/pull/1715

**Comment by antikythera288** [comment]
This needs to be closed as something went terribly wrong when rebasing master into the branch. Just to make sure i created another PR from a new created branch to have again a clean diff ... @Benjozork @Lucky38i  can you please adjust the labels?
@wpine215 .8 hadnt any changes on the airbus, so i guess all fine for the newest version

https://github.com/flybywiresim/a32nx/pull/1715

**Pull request closed without merging**
