### PR TITLE
[ECAM] Add ECAM HYD page only

### PR DESCRIPTION
**Pull request by Kimbyeoungjang**
## Summary of Changes

Add down ECAM HYD Page

## Screenshots (if necessary)

캡처2

## References

캡처

## Additional context

i just wanna add page for someone who build backend for hydraulic. html & css only

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Kimbyeoungjang** [comment]
i'll upload in-game screenshot please wait...

**Comment by Benjozork** [comment]
I'm really sorry but this work has already been done by someone. Also, you're using a reference from an older display system.

Their work should have been made as a draft PR to show they are working on it, I asked them to do so.

I advise you ask in the Discord before starting work on major things.

**Comment by Benjozork** [comment]
The implementation is part of the WIP hydraulic system - you can talk with CPU_Blanc#6060 on discord if you wanna collaborate.

**Comment by Kimbyeoungjang** [comment]
> The implementation is part of the WIP hydraulic system - you can talk with CPU_Blanc#6060 on discord if you wanna collaborate.

oh i see, i'll close this pr.

**Pull request closed without merging**
