### PR TITLE
Corrected sounds & Cold and Dark State for Commercial and Galy&Cab Buttons on Overhead

### LINKED ISSUE #697: [BUG] Commercial and Gally & Cab buttons are silent when pressed
**Mod Version**

965374a (Master)

**Describe the bug**

The Commercial and Gally & Cab buttons do not make any sound when pressed. 

**To Reproduce**

1. Load into aircraft
2. Press Commercial and Gally & Cab buttons on overhead pannel
3.

**Expected behavior**

The buttons should use the same clicking sound that the rest of the overhead buttons use.

**Actual behavior**

No sound is made when they are pressed.

**References**

**Additional context**

Discord username:
@Coralec#5169

### PR DESCRIPTION
**Pull request by DoToAdventures**
Fixes #697 and #709 

**Summary of Changes**

Added sounds to Commercial and Galy&Cab buttons in the ELEC sections of the Overhead panel by adding wwise events to the buttons.
Also edited apron.flt file to make those buttons be on by default as requested in #709 

**Discord username (if different from GitHub):** DoTo#5564

### CODE REVIEW

**Comment by Carter633** [comment]
I'll take a look now

**Review by Carter633 — COMMENTED** [review]
I'm taking a look at the update now for this PR

**Review by Carter633 — APPROVED** [review]
Works well - noises are good, clicks when turning on and clicks when turning off. Cycled numerous times resulting in the same clicks each time. Only issue is when you click vigorously but that's not realistic or reasonable so not an issue. Buttons and lights still operable with the audible click - and the galley/comm button lights work with the ANN LT TEST function too. Good work!

**Comment by DoToAdventures** [comment]
See #711

**Pull request closed without merging**
