### PR TITLE
fix(fmgc): flight phase initialization

### LINKED ISSUE #5226: take-off phase in perf page mid-air
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-28T07:23:55+00:00",
  "ref": "master",
  "sha": "ac6847baf2d64bc836c9793bc224ae0e34910ae6",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

when I spawned mid-air inbound to land, the MCDU never registered that I took off, which means I could not progress from the take-off phase in the PERF page.

### Expected behavior

I expect y'all fix this, so when you spawn in the air inbound to land, you are already in the APPR phase.

### Steps to reproduce

1. i tried to learn autolanding
2. i could not do it, and after some testing i figured the reason i could not activate appr mode on the ap panel was because i was stuck in take-off phase in the perf page which stopped me from activating the approach phase.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

who#3220

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #5226

## Summary of Changes

Improved initialization of the flight phase manager.

- `A32NX_FlightPhaseManager` get constructed immediately and updates the flight phase based on flt state or defaults to preflight if not defined (this has not been changed)
- `A32NX_FlightPhaseManager` now has it's own init to initialize the initial flight phase which may need additional fmgc data which has not been processed, therefore the `flightPhaseManager.init()` is placed at the bottom of the fmgc initialization.

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Spawn on apron, runway, mid flight and approach and check for correct flight phases. (use the Prog and perf pages)
And also ensure that everything is working as normal.

- apron and runway: observe prog page shows TO and take off page is not green,
- mid flight: observe cruise phase is the current fmgc flight phase,
- approach: observe approach phase is the current fmgc flight phase.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ErikNL80** [comment]
Is this PR is also going to fix https://github.com/flybywiresim/a32nx/issues/5224

**Comment by MisterChocker** [comment]
> Is this PR is also going to fix #5224 ?

No, it's not.

**Review by 2hwk — APPROVED** [review]

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5236
Tier of Testing: 1
Date: 30.6.2021

Testing Process:

apron and runway: observe prog page shows TO and take off page is not green 
==> gate: OK, runway OK - after TO page green

mid flight: observe cruise phase is the current fmgc flight phase,
==> OK (also MCDU works)

approach: observe approach phase is the current fmgc flight phase.
==> OK

Negatives: None

Testing Results: Passed

Conclusions: LGTM. Nice fix - was annoying before when doing screenshots for documentation :)

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5236
Tier of Testing: 1
Date: 30/06/2021

Testing Process: 

1. Spawned C&D, checked & filled MCDU for regular operation, and performed circuit
2. Spawned on approach, checked & filled MCDU for regular operation, and performed landing
3. Spawned on runway, checked & filled MCDU for regular operations, and performed circuit
4. Spawned on cruise, checked & filled MCDU for regular operations, and performed landing

Negatives: N/A
Testing Results: Passed

Conclusions: Confirmed linked issue has been fixed.

**Pull request merged**
