### PR TITLE
Tcas traffic knob movement fix

### LINKED ISSUE #2742: [BUG] TCAS Traffic Mode Switch
**Mod Version**
"built": "2020-12-25T10:12:36+00:00"

**Describe the bug**
The THRT, ALL, ABV, BLW switch doesn't turn all the way .

**To Reproduce**
1.Spawn at an airport
2.Set up plane from C/D
3.Turn the traffic mode switch

**Expected behavior**
The switch to not turn all the way.

**Actual behavior**
The switch turned 4 times but didnt move much, when you turn the switch 4 time it goes to all.

**References**
https://www.loom.com/share/d7a26b50b2444b70b7d8de709ac0c610

**Additional context**
Spawned at egcc stand 11.

Was this working before/when did the issue start occurring?
When the latest dev build came out.
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
Sameer Ali#4139

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #2742

## Summary of Changes

I more or less accidentially stumbled across a second declaration for the tcas traffic switch which likely caused conflicts. After removing the one in AirlinerCommon.xml the switch moves fine again for me.

## Screenshots (if necessary)

First state
image

Last state
image

## Additional context

Discord username (if different from GitHub): saschl#9432

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by lukecologne — APPROVED** [review]
Sounds good, nice catch. Looks like this came from #2672, so it was indeed working when the TCAS PR got merged

**Comment by lukecologne** [comment]
Pretty simple to test, just make sure that the TCAS THRT knob animation works as expected

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date 3/1/21
Version of the sim: 1.12.13.0
PR Tested: #2855 
Object of test: TCAS traffic knob

Testing technique: Loaded in and tried it
Steps you've made to test the Pull Request:
1. Loaded in at EGPH
2. Turned the knob

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: The knob works as expected but there is a small texture issue where it is misaligned but it has nothing to do with this pr 
image

**Comment by NickFarin** [comment]
Category: QA Trial
Name: Discord User: Nick F[Z+8] #5327
Date of testing: Current date: 04/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2855 
Object of test: TCAS traffic knob
Testing technique: Spawned in and turned knob
Steps you've made to test the Pull Request:
1. Spawned at RPMD  
2. Turned knob to the 4 positions

Flight notes (If required):

Issues (If Any): There is a slight misalignment with the knob and the All detent
Overall Rating: Good
Conclusions of the testing: The knob is able to move into the 4 positions and the test went normal.

**Comment by ErickSharp** [comment]
Category: QA Tester
Name: Erick [Z-6]#6484
Date of testing: Current date 03/01/2021
Version of the sim: 1.12.13
PR Tested: #2855
Object of test: (ECAM Page or Flight model or views or anything, what the PR modifies)

Testing technique: Loaded in at PHNL and tested the transponder positions
Steps you've made to test the Pull Request:
1. Spawn in at PHNL 
2. Moved the knob on the TCAS panel. 

Flight notes (If required): None
Issues (If Any): Along with the other QA testers in this thread, I also noticed the very minor misalignment of the 
Overall Rating: Good
Conclusions of the testing: The knobs work as intended, and since the misalignment wasn't intended to be addressed in this PR, no additional work is needed.

**Comment by pepperoni505** [comment]
@Benjozork should this go on 0.5.2?

**Comment by Benjozork** [comment]
@Saschl can you show where the other declaration is ?

**Comment by lukecologne** [comment]
Template is here: https://github.com/flybywiresim/a32nx/blob/aef157b2e4228cc0f676e07baeb5e424f2118668/src/behavior/src/A32NX_Interior_Misc.xml#L451

UseTemplate is here: https://github.com/flybywiresim/a32nx/blob/aef157b2e4228cc0f676e07baeb5e424f2118668/A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml#L3196

**Comment by lukecologne** [comment]
> 
> 
> @Benjozork should this go on 0.5.2?

The breaking change occured after 0.5.1, so yes, it should be included.

**Comment by Benjozork** [comment]
Added a changelog entry, remember to add one next time 🙂

**Comment by Saschl** [comment]
Will do next time, thanks!

**Pull request merged**
