### PR TITLE
fix: Non-continuous Idle N1 calculation

### LINKED ISSUE #5262: Thrust response from idle too slow
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-24T13:54:04+00:00",
  "ref": "merge",
  "sha": "70bb38388d993123ebf6d7962e1d114d94f9c1f7",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

During turns with autopilot/autothrust engaged with idle thrust in CONF 2, thrust response is too slow to prevent speed from decaying to alpha prot. This can happen when approaching the level off altitude after an open descent.  Problem does not occur in level flight, where the engine response if very quick, nor in descent, where it just leads to a higher descent rate.

Issue first identified in this video (at 2:39:02 and again around 2:39:39): https://youtu.be/s841bTMG2Wo?t=9514

I replicated it in this video, which shows no issue with a turn in level flight, or in open descent. Only when the airplane is in idle near levelling off, where thrust must increase fast enough to both handle the level off and the drag increase due to the turn. https://1drv.ms/v/s!Ajsy7Ey4_8uFzy68wL5GBN7_dpUp?e=KxfpJ6

### Expected behavior

Thrust to increase fast enough to hold speed in this situation.

### Steps to reproduce

1. At 3000 ft, autopilot/autothrust engaged, APPR mode selected in MCDU, managed speed, CONF 2, 3, or 4 (speed decay happens with flaps up and CONF 1 as well, but there is a bit more margin to alpha prot).
2. Initiate an open descent to 2500 ft
3. At 50-100 feet before leveling off (i.e., before the thrust starts to increase), initiate a turn with the autopilot. Select a large enough heading or track change to cause the airplane to continue through the turn as it levels off.
4. Note speed decay

### References (optional)

_No response_

### Additional info (optional)

Issue brought up here: https://discord.com/channels/738864299392630914/738864300818432023/860825069357760542

### Discord Username (optional)

donbikes#4084

### PR DESCRIPTION
**Pull request by Taz5150**
## Summary of Changes

Idle N1 calculations are needed, among many other things, to define engine start-up limits, as well as many other fbw/ athr parameters and situations. Due to a mistake in the frequency the function was called, Idle N1 was not being calculated during non-ground situations. This very small code change fixes this issue.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Before this fix: A32NX_ENGINE_IDLE_N1 was 0 above ground.
With this fix: A32NX_ENGINE_IDLE_N1 is a non-zero (above 17%) value above ground

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by aguther** [comment]
It was not always 0, it was depending on an overall situation. It just stopped updating the variable. So the last value from ground was kept.

**Review by aguther — APPROVED** [review]

**Comment by beheh** [comment]
> Potentially Fixes #5262

GitHub will automatically close the references issue when this PR is merged at it only sees the Fixes + issue number (you can see that by the dotted underline in the PR). I would suggest using another wording if you want to avoid that issue being autoclosed.

**Comment by Taz5150** [comment]
> It was not always 0, it was depending on an overall situation. It just stopped updating the variable. So the last value from ground was kept.

This is correct. The PR is needed but it might not solve the AP issue.

**Comment by Taz5150** [comment]
> > Potentially Fixes #5262
> 
> GitHub will automatically close the references issue when this PR is merged at it only sees the Fixes + issue number. would suggest using another wording if you want to avoid that issue being autoclosed.

True. Will change since it does not solve 5262 completely (maybe not even partially)

**Comment by donstim** [comment]
Unfortunately, it doesn't appear to help much with issue #5262. Here is a test video showing level off from open descent with no turn and with a turn just before level off. CONF 2. https://1drv.ms/u/s!Ajsy7Ey4_8uFzy-VtSOPay8S4cF9?e=mAWISo

**Comment by St54Kevin** [comment]
Im a little confused on what and how to test this? So before, in-air Idle N1 was 0%? Never saw that I think

**Comment by Taz5150** [comment]
> Im a little confused on what and how to test this? So before, in-air Idle N1 was 0%? Never saw that I think

Idle N1, as seen on the ECAM, is fine. The issue is with the A32NX_ENGINE_IDLE_N1 variable which was defined ONLY on ground. If you start from ground (C&D or on runway), the variable will be calculated and maintained during the whole flight until you get to ground again. But if you start on Cruise, the the variable is not initialized and is kept at 0. This variable is being used by the FBW/ ATHR systems as well, so it has to be calculated continuously.

I hope I explained it better this time!

**Comment by St54Kevin** [comment]
> > Im a little confused on what and how to test this? So before, in-air Idle N1 was 0%? Never saw that I think
> 
> Idle N1, as seen on the ECAM, is fine. The issue is with the A32NX_ENGINE_IDLE_N1 variable which was defined ONLY on ground. If you start from ground (C&D or on runway), the variable will be calculated and maintained during the whole flight until you get to ground again. But if you start on Cruise, the the variable is not initialized and is kept at 0. This variable is being used by the FBW/ ATHR systems as well, so it has to be calculated continuously.
> 
> I hope I explained it better this time!

Oh okay I understand. But keep in mind that there is a significant difference in Idle N1% value in flight depending on the altitude. There is even an approach Idle value, to keep spool up short in a go around case

**Comment by Taz5150** [comment]
> > > Im a little confused on what and how to test this? So before, in-air Idle N1 was 0%? Never saw that I think
> > 
> > 
> > Idle N1, as seen on the ECAM, is fine. The issue is with the A32NX_ENGINE_IDLE_N1 variable which was defined ONLY on ground. If you start from ground (C&D or on runway), the variable will be calculated and maintained during the whole flight until you get to ground again. But if you start on Cruise, the the variable is not initialized and is kept at 0. This variable is being used by the FBW/ ATHR systems as well, so it has to be calculated continuously.
> > I hope I explained it better this time!
> 
> Oh okay I understand. But keep in mind that there is a significant difference in Idle N1% value in flight depending on the altitude. There is even an approach Idle value, to keep spool up short in a go around case

Yes, you are totally right. I have posted a few links and rationale on this in Discord (autoflight channel). Still, and getting back to this PR, although the initial intention was to solve that flight Idle issue (and although it does not solve it), we need it.

**Comment by TheSquirtingPantin** [comment]
Quality Assurance Tester

Discord: Remi#8871
Object of testing: #5263
Tier of Testing: 2?
Date: 5/07/2021

Testing Process:
1) Full Flight LFBO to LFBO 
2) Multiple check of the A32NX_ENGINE_IDLE_N1 LVAR in the Model Behavior

Negatives: N/A

Conclusions: PASS with A32NX_ENGINE_IDLE_N1 LVAR showing adjusment in both climb and descent as per PR target. Minimal change of idle value in flight due to constant atmosphere. Value displayed: 500ft@23°C --> 19.984 ; FL110@19°C --> 21.252 ; FL200@-13°C -->22.440 ; FL260@-24°C --> 23.109 ; FL320@-36° --> 23.759
Media: N/A

**Review by davidwalschots — APPROVED** [review]

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5263 
Tier of Testing: 1
Date: 12/07/2021

**Testing Process:**
1. Loaded up onto RW and took off to FL180 and descend back to airport and land
2. Monitored the A32NX_ENGINE_IDLE_N1 simvar

**Negatives:** N/A
**Testing Results:** Passed

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #5263 
Tier of Testing: 1
Date: 12/7/21

Testing Process:
- Loaded C&D and checked the N1 value and engine startup
- Loaded on runway and checked
- Took off and checked that the N1 value kept changing
- Climbed up to FL50 where the PFD stops counting and the N1 was still being calculated reaching somewhere in the region of 29%
- Descended back down and checked that N1 was reducing
Negatives: N/A
Testing Results: Passed

Conclusions: LGTM, good work!
Media: 
image
image
image

**Pull request merged**
