### PR TITLE
feat: add console/floor light switch functionality 

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes
In preparations for @Snapmatics interior lighting rework, this adds functionality to the console/floor light switch with a placeholder light effect. 

- Adds functionality to Console / Floor Lights switches

## Screenshots (if necessary)

Untitled-2

## Additional context
The light effect is only a temporary placeholder since @Snapmatics is waiting to receive additional references. But it will make future changes to the console/floor light easier and will enable @MoreRightRudder to take a look at how the textures behave themselves under the new light.

The animation for the FO switch does not cover the full range of motion, this is, unfortunately, a model issue and probably can't be addressed until we can edit it. It has three positions but they are between OFF and DIM. 

Discord username (if different from GitHub): Imenes#8739

## Testing instructions
Check the functionality of the console switches, and their initial position. It should be OFF for all starting configurations. Also, make sure that the console lights can't be used when no power is available. Please play around with all the different light switches to make sure no other switch affects the console lights.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Snapmatics** [comment]
Thank you a lot @ImenesFBW <3

**Review by davidwalschots — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 13.3.2021
Version of the sim: 1.14.5.0
PR Tested: #3930
Tier of testing: 1
Changes to observe: console light
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Tested the lights

Media:


Image1

Issues: 
- Reading and console lights turn on by only battery, is this correct?
- Whats with the other spotlights? (https://discord.com/channels/738864299392630914/771566410253074453/817789959577534464)

Overall Rating: -

Conclusions of the testing: Looks good, but needs a few checks

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 13.03.2021
Version of the sim: 1.14.5.0
PR Tested: #3930 
Tier of testing: 1
Changes to observe: Console Lights

Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned C&D at LSZH
2. Turned on Bat 1 and Bat 2
3. Checked all Lights
4. Spawned on Rwy 34 and checked state

Media:
Microsoft Flight Simulator Screenshot 2021 03 13 - 22 24 25 88

Overall Rating: Good
Conclusions of the testing: Works as described, all lights only turn on with Batterys on and initial states are off. Previously the Lights were able to light up with Battery only aswell so i suppose thats the correct Behaviour?

**Comment by darkfury334** [comment]
Category: QA Trial
Name: DarkFury#4936
Date of testing: Current date 13/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3930
Tier of testing: 1
Changes to observe:
initial position of the Console switch all starting configurations.
Console and reading lights can't be used when no power is connected.

Testing technique: Try out
Steps you've made to test the Pull Request:
1. Spawned in C&D at EGNX
2. Checked position of console switch 
3. Checked to see if console and reading light would turn on without power
4. Respawned on runway and checked position of console switch

Flight notes (When done a full flight):N/A

Media: 

Issues (If Any):


Overall Rating: Good
Conclusions of the testing: Does work as described, Console switch is off when load into different states. Console and reading
lights turn on with battery.

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 13/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3930 
Tier of testing: 1

Changes to observe:
console/floor light switch functionality

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. C&D @ EGLC
2. Followed PR instructions 

Flight notes (When done a full flight):
N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
Microsoft Flight Simulator Screenshot 2021 03 13 - 22 37 51 88
Microsoft Flight Simulator Screenshot 2021 03 13 - 22 39 30 33
Microsoft Flight Simulator Screenshot 2021 03 13 - 22 39 33 80


Issues (If Any): NONE!

Steps to achieve the issue:
N/A

Overall Rating: Perfect! Just need @MoreRightRudder for his magic :)
Conclusions of the testing: LGTM

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 13/3/21
Version of the sim: 1.14.5.0
PR Tested: #3930 
Tier of testing: 2
Changes to observe:
console/floor light

Testing technique: did a full flight
Steps you've made to test the Pull Request:
1. did a full flight
2. landed at night
3. had ext power and batt
4. turned off integral lights

Media: Insert screenshots, recordings, or anything relevant to the review here.

https://user-images.githubusercontent.com/70103461/111053295-8f3d1480-845a-11eb-9f1b-8646fdc004b7.mp4



Issues (If Any): When integral light is switched off, console/floor and reading light come off too or do not turn on in the first place
Steps to achieve the issue: 
turn on console/floor light without integral lights 
or
turn on integral lights and console light after then turn off integral lights

Overall Rating: To be improved
Conclusions of the testing: light and switch work but the integral light needs to be on

**Comment by CAC14** [comment]
Category: QA Tester
Name: Discord User #9027
Date of testing: Current date 14/03/21
Version of the sim: idk
PR Tested: #3930
Tier of testing: 1/2/3
Changes to observe:
Check the floor light is operational with power and doesnt work when power is off.  check the same for reading light

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned at gate kjfk, tested switch with power on and off. checked reading light
2. spawned on run way kjpk, tested switch.  turned off engion and tried again checked reading lights
3. 
4.
5.

Flight notes (When done a full flight):n/a

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): Worked as expected. switch turned on lights on dim and bright only when plane had power.  Reading light worked too but only when plane had power.

Overall Rating: Good

**Comment by ImenesFBW** [comment]
Investigating the integral light switch interfering with the console and reading lights, as reported by @FlightSimmer7700. 

This behavior is also present in the dev with reading lights so hopefully, I can figure out a way to solve it. 

PR marked as a draft for now.

**Comment by ImenesFBW** [comment]
The bug found by @FlightSimmer7700 should be resolved.

Removed the changes pertaining to reading lights since I wasn't able to fully resolve the issues with them.

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 14.3.2021
Version of the sim: 1.14.5.0
PR Tested: #3930
Tier of testing: 1
Changes to observe: Console light
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Tested console lights and tryed lots of light switch combinations

Issues: -

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Comment by Matse08** [comment]
Category: QATester
Name: Matse#7454
Date of testing: 15.03.21
Version of the sim:1.14.5.0
PR Tested:#3930
Tier of testing:2
Changes to observe:New lights


Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned at Cold and dark
2. tried to turn it on without power (Did not work)
3. turned on battery and every other light

Media:
Microsoft Flight Simulator 15 03 2021 19_57_55

Conclusion: Good job think people gonna like this one

Overall Rating: Good

**Comment by ImenesFBW** [comment]
Bumped the light index to 3 hopefully, this gets rid of any interference. I still have a suspicion there is a switch out there that interferes with the console switch, but I spent a lot of time flicking switches and couldn't identify it.

For QA tests from here on please try to flick all the light switches to see which one if any of the switches conflict with the newly added console switch.

@FlightSimmer7700 will hopefully find an interfering switch if it is outthere.

**Pull request merged**
