### PR TITLE
feat: 1.14.5.0 model changes

### PR DESCRIPTION
**Pull request by pepperoni505**
Fixes #[issue_no]

## Summary of Changes

This PR adds the exterior model changes from the 1.14.5.0 update
## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Make sure contrails are still visible
- Make sure the windshield wiper knobs control the proper wiper
- Check if anything looks wrong/isn't functional

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
@pepperoni505 please detail this line

> Make sure the windshield wipers work

**Comment by pepperoni505** [comment]
> @pepperoni505 please detail this line
> 
> 
> 
> > Make sure the windshield wipers work

Done

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 09/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3871
Tier of testing: 3

Changes to observe:
N/A

Testing technique: Try-out, full flight

Steps you've made to test the Pull Request:
1. Spawned C&D @ LIEO
2. Prepared manual F-PLAN from LIEO to LIRN
3. Preliminary check of the usage of the aircraft, buttons knobs (details/photo below)
4. Added SID straight out of RWY05 via ATNE7K
5. Added STAR before 100nm descent via PNZ2D trans ISKIA on ILS06-X
6. Manual landing into RWY06

Flight notes (When done a full flight): as above.
Contrails works a charm!!! (see last photo)
Windows wipers as well! (1st photo)
3. V/S not working stuck at 1500FPM takeoff/landing
4. EFB not working
5. CAPT side both 1/2 VOR/ADF not working, FO side 1/2 VOR/ADF works perfectly

Media: Insert screenshots, recordings, or anything relevant to the review here.
Microsoft Flight Simulator Screenshot 2021 03 09 - 20 56 03 08
Microsoft Flight Simulator Screenshot 2021 03 09 - 21 33 22 43
Microsoft Flight Simulator Screenshot 2021 03 09 - 22 05 31 11
Microsoft Flight Simulator Screenshot 2021 03 09 - 22 10 51 97
Microsoft Flight Simulator Screenshot 2021 03 09 - 21 58 40 94

Issues (If Any): 
FMS/MCDU not working correctly

Steps to achieve the issue:
1. added SID, inserted a USR waypoint instead of direct EO603
2. at 100nm before destination, added STAR, lost HDG but keeps route in straight line (no banks L/R) as in picture above then suddenly intercepts.

Overall Rating: To be improved
Conclusions of the testing: LGTM, the aircraft works, just needs a few fixes here and there.

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 10.3.2021
Version of the sim: 1.14.5.0
PR Tested: #3871
Tier of testing: 2
Changes to observe: Model fixes
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Took off to FL380
3.) Land at EDDP

- Tryed wipers
- Got contrails
- Looks for other model issues

Issues: -

Overall Rating: Good

Conclusions of the testing: Works. Lots of update issues unrelated to tis PR.

Hope this helps :-)

**Comment by MisterChocker** [comment]
@DavidEGTE MCDU is not relevant in this pr.

**Comment by DavidEGTE** [comment]
> @DavidEGTE MCDU is not relevant in this pr.

Sorry, I miss read the summary. but I hope it could help for future PR.

**Comment by marinerhally** [comment]
Category: QA Tester
Name: Mariner Hally#0715
Date of testing: 10/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3871
Tier of testing: 2
Changes to observe:
Exterior model changes from the 1.14.5.0 update

Testing technique: Short Flight
Steps you've made to test the Pull Request:
1. Spawned C/D EGCC
2. took off climbed FL250
3. Landed at EGKK ILS 26L

Flight notes (When done a full flight):
Wipers worked fine and also contrails were working also didn't see any other major problems with the flight model.

Media:

Issues (If Any):Issues with MCDU and ND but not related to this PR.

Overall Rating: Good
Conclusions of the testing: Works apart from the issues not related to this PR.

**Comment by MisterChocker** [comment]
@Benjozork are 3 goods enough?

**Pull request merged**
