### PR TITLE
Added sounds for a lot of things

### PR DESCRIPTION
**Pull request by hotshotp**
**Summary of Changes**

Added multiple sounds:
Fuel Pumps
Flaps
Ground roll
Ground roll rattles
Nose Wheel lift off "wobble"
Touchdown sounds
Wind sounds including change when gear is down

I also updated the Wwise project to include the new version to be able to add to it later as the Wwise project is in .src is the latest version.

**Screenshots (if necessary)**

**References**
Here are a few people that helped me and gave me feedback: CPU Blanc, Becas22, Theresa Green, Christopher Xie, Harry, Komp, LordP, FlyingCarpet7, Wuper, HSL, and Dave.  This should be pretty much everyone. 

I used royalty free sounds for almost every sound, every other sound was taken from real sounds of an a320 from other members of the discord server. I have over and over checked with irl pilots and engineers to make sure everything sounds right.

**Additional context**

Been working on this for a while, first PR so don't be harsh if I messed something up in github.

Discord username (if different from GitHub):
Boris#9134

### CODE REVIEW

**Review by wuperguy — APPROVED** [review]
Viewed many of the sound samples in Discord while in progress. Amazing job and we definitely need more sound enhancements! Thank you!

**Comment by Snapmatics** [comment]
Needs changes!

**Comment by hotshotp** [comment]
> Needs changes!

changed!

**Review by AdenFlorian — APPROVED** [review]
file changes look fine, ready to test!

**Comment by sebair10** [comment]
I don't know if this is intentional or even an issue with this PR, but I don't hear it in the master. It's like a "weee" sound whenever switching views back into the flight deck. Not exactly sure what causes it, but here is a clip. Excuse me if I made a mistake :). https://medal.tv/clips/33816672/d1337AskbMVx

**Comment by hotshotp** [comment]
> I don't know if this is intentional or even an issue with this PR, but I don't hear it in the master. It's like a "weee" sound whenever switching views back into the flight deck. Not exactly sure what causes it, but here is a clip. Excuse me if I made a mistake :). https://medal.tv/clips/33816672/d1337AskbMVx

Hey, so basically thats the sound of the fuel pumps starting. I couldn't find a way to stop it from doing that, so I am sorry.

**Comment by ImenesFBW** [comment]
Did one flight with it for now, and I must say it's a great addition to the mod, thank you for your work. Awesome first PR!

ver. 1930
Overall Rating: Good

**Comment by Brandidiot** [comment]
Sounds are nice, the wind sounds seem a little loud to me though...sounds like static almost and gets quite annoying. Could be just me though.

**Comment by sebair10** [comment]
> Sounds are nice, the wind sounds seem a little loud to me though...sounds like static almost and gets quite annoying. Could be just me though.

Yeah, I agree. I'm not an IRL A320 Pilot but it seems to be a bit much. The ground rolls sound amazing, fuel pumps work great, rollouts, etc. The only issue was the fuel pump audio restarting every time switching views, but like you said, I don't know if it is possible to fix. Awesome job its great!

**Comment by hotshotp** [comment]
> > Sounds are nice, the wind sounds seem a little loud to me though...sounds like static almost and gets quite annoying. Could be just me though.
> 
> Yeah, I agree. I'm not an IRL A320 Pilot but it seems to be a bit much. The ground rolls sound amazing, fuel pumps work great, rollouts, etc. The only issue was the fuel pump audio restarting every time switching views, but like you said, I don't know if it is possible to fix. Awesome job its great!



> Sounds are nice, the wind sounds seem a little loud to me though...sounds like static almost and gets quite annoying. Could be just me though.

I have made a change to tone down the wind by 5 decibels. I am not able to change the fuel pumps in any way, believe me i have tried :(

**Comment by flightsimsimon** [comment]
Tested - loved it just need the wind turning down a little

**Comment by hotshotp** [comment]
> > Sounds are nice, the wind sounds seem a little loud to me though...sounds like static almost and gets quite annoying. Could be just me though.
> 
> Yeah, I agree. I'm not an IRL A320 Pilot but it seems to be a bit much. The ground rolls sound amazing, fuel pumps work great, rollouts, etc. The only issue was the fuel pump audio restarting every time switching views, but like you said, I don't know if it is possible to fix. Awesome job its great!

Something awesome I found out. I can make the fuel pump sounds not restart every time you switch views. The downside is the fact that when you go into exterior you hear the fuel pumps. I think the positives outweigh the negatives on this one so I will make a change here.

**Comment by sebair10** [comment]
Yeah, I agree. I think it'll sound a bit better. I'll download the updated repository and try it out! Thanks so much!

**Comment by hotshotp** [comment]
> Yeah, I agree. I think it'll sound a bit better. I'll download the updated repository and try it out! Thanks so much!

how does it sound to you? I feel like it is much better now. At some point in the future i have to figure out how to make a certain node an emitter because for some reason NodeName doesn't work for me. I will make it so flaps can be attached to actual flaps and fuel pumps to the wings, etc.

**Review by wuperguy — APPROVED** [review]

**Review by DoToAdventures — APPROVED** [review]
Tested. LGTM

**Pull request merged**
