### PR TITLE
feat(tcas): TCAS TA/RA logic and annunciations

### PR DESCRIPTION
**Pull request by wpine215**
Fixes #[issue_no]

## Summary of Changes

This PR builds upon #2242, and will add RA generation and annunciations, proper detection of aircraft on ground, and support for relevant modifications to the PFD and ND displays.

### Features:
- [x] Add TA (traffic advisory) logic and annunciation
- [x] Add RA (resolution advisory) logic and annunciation for all possible RA callouts/variants
- [x] Integrate TA and RA annunciations with core sound manager for proper sound sequencing
- [x] Do not change sensitivity level during an active RA
- [ ] Inhibit RA's depending on altitude/other systems
    - [ ] Inhibit "increase descent" RA's below 1,550 ft AGL
    - [ ] Inhibit all "descend" RA's below 1,200 ft AGL at takeoff, and 1,000 ft AGL during approach
    - [x] Inhibit all RA's below 1,100 ft AGL in climb, 900 ft AGL in descent ("TA ONLY" message on ND)
    - [x] Inhibit all RA's as well as aural TA's below 600 ft. in climb, 400 ft. in descent
    - [ ] Inhibit all climb RA's at or above 39,000 ft
    - [ ] Inhibit all RA's when in windshear/stall condition or during GPWS "glideslope" warning ("TA ONLY" message on ND)
    - [ ] Inhibit all RA's for non-altitude reporting aircraft above 15,500 ft MSL (currently not possible given sim data)
- [x] Ignore aircraft on ground (below 380 ft. AGL when they are climbing, 400 ft. AGL when they are descending) when own altitude is less than 1650 AGL when descending, and 1750 AGL when climbing
- [ ] Implement HMD (horizontal miss distance) filtering
- [ ] Implement TVTHR support
- [x] Add green/red zones to PFD vertical speed display during an active RA which indicate the desired/forbidden vertical speed ranges, respectively
- [x] Add warning messages to ND (red during RA, amber during TA):
    - [x] "REDUCE RANGE" when EFIS range mode selector is above 40 NM (exclusive)
    - [x] "CHANGE MODE" when EFIS mode selector is in PLAN mode
- [ ] Add TCAS test

### Issues:
- [x] RA's are given "clear of conflict" then immediately return to RA state. Need to find a filter/hysteresis to hold the RA status until we're 100% sure we're clear of conflict. (Same with TA's).
- [x] "Maintain vertical speed" speed ranges are reversed (green range is negative when current VS is positive, and vice-versa
- [x] "Level off" is interrupted almost immediately by "Clear of Conflict" in some cases
- [x] Need to restrict annunciations/simvar setting to only one ND
- [x] "Climb"/"Descend" RA given immediately after weakening "Level Off" RA
- [x] Bug occurrence: "Climb" followed shortly by "increase descent" followed by "climb now" followed by "increase descent"
- [x] TA audio not playing for some reason
- [x] "Monitor vertical speed" RA initiated (red range 0 to 6000+) while in the red zone
- [x] Traffic icon remaining as TA despite being more than 4 seconds since TA ended and 6+ NM away
- [ ] Fix angle of preventative red zones on PFD
- [ ] "traffic traffic" call given right after RA resolution, on same aircraft
- [ ] some callouts not repeating as intended
- [ ] mask out traffic icons on PLAN mode

## Screenshots (if necessary)

https://streamable.com/h3n0es

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by davidwalschots** [comment]
#130 and #1097 are related to this PR. It's probably a good idea to clean and or split those issues up and link the relevant items to this PR.

**Comment by NitroMaxx72** [comment]
Screenshot_20210725-170835
pay attention to the plane icon and flight number

**Comment by tracernz** [comment]
That is ATSAW, not TCAS.

**Comment by NitroMaxx72** [comment]
> Это ATSAW, а не TCAS.

isn't this part of the same system?

**Comment by tracernz** [comment]
> 
> 
> > Это ATSAW, а не TCAS.
> 
> isn't this part of the same system?

Kind of... they are two different subsystems, using two different data sources, offering different information, and are represented differently on the EIS displays (note the different icon in your photo compared to a TCAS diamond). ATSAW gets it's data from ADS-B tranmissions. TCAS from mode-S transponder. The traffic API we're using in-sim for TCAS does not provide enough information for an ATSAW implementation at this stage.

**Comment by nathen148** [comment]
Any updates on when this will be worked on? Been really eager to try it out on vatsim

**Comment by Benjozork** [comment]
@nathen148 We do not provide estimates or timelines on when certain features will be worked on / available.

**Pull request closed without merging**
