### PR TITLE
[CDU] Redirect to fuel pred instead from INIT-A

### LINKED ISSUE #2449: [BUG] The INIT FUEL PRED. page via right arrow is not available to open to enter data
"built": "2020-12-14T07:18:52+00:00", and then the last update of the 13th december.

Describing:
After clicking on the INIT page of the MCDU I can not reach the INIT FUEL PRED. page with clicking right arrow to enter ZFW and trimming - not available line appears. 

To Reproduce:
1. Load the flight.
2. Fill the MCDU.
3. Go to the INIT page.
4. When in the INIT page click the right arrow to open the INIT FUEL PRED. page.

Expected behavior:
I see the  INIT FUEL PRED. page and able to enter there a data, for ex. ZFW/trimming.

Actual behavior:
After clicking on the INIT page of the MCDU I can not reach the INIT FUEL PRED. page with clicking right arrow to enter ZFW and trimming - not available line appears. 

Was this working before/when did the issue start occurring? No.

Is this a problem in the vanilla unmodded game? No.

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #2449

## Summary of Changes

- Now redirecting to FUEL PRED PAGE instead of showing message.
Since we have no documentation on this, this is probably the best way to go.

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by wpine215** [comment]
This behavior is correct according to documentation.

image

**Review by wpine215 — APPROVED** [review]

**Comment by pacha35** [comment]
We know that INIT B is not available after engine statr. But, in case of starting the aicraft on the runway, on FUEL PRED page, ZFW/ZFWCG is empty and it's impossible to fill it.
ZWF_01

**Comment by MisterChocker** [comment]
> We know that INIT B is not available after engine statr. But, in case of starting the aicraft on the runway, on FUEL PRED page, ZFW/ZFWCG is empty and it's impossible to fill it.
> 
> ZWF_01
> 
> 

That's flat wrong, you can fill the fuel pref page. It's fully operational.

**Comment by pacha35** [comment]
may be is a question of release, I have the dev 4.2 release dowload with the last installer

**Comment by MisterChocker** [comment]
sounds like you are suing stable 0.4.2, because our master aka dev version has no versioning.
You can check the build_info.json file.

**Pull request merged**
