### PR TITLE
Fix: Add Localisation files for aircraft info when using other languages than english

### LINKED ISSUE #1494: [BUG] Absent localization files causing show of MODEL and MANUFACTURER params in UI in different languages except english
**Mod Version**

master

**Describe the bug**

Model and manufacturer of A32NX does not shown correctly for any language except english

**To Reproduce**

1. Install mod (Use installer or just drag/drop files)
2. Launch a game
3. Navigate to World Map -> Aircraft -> Liners
4. Look at the Airbus A32NX

**Expected behavior**

Manufacturer and model shown correctly

**Actual behavior**

See the screenshot
issue

**Workaround/Possible fix**
1. Copy localization files from original ASOBO folder to A32NX folder
2. Edit layout to include files into mod

Was this working before/when did the issue start occurring? Yes, afair in 0.3.1 it worked correctly

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):
c0updegrace#8661

### PR DESCRIPTION
**Pull request by pessip**
Fixes #1494

## Summary of Changes
Copied localisation files from asobo

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by pessip** [comment]
I Forgot to add to changelog so will be closing this and opening a new one.

**Comment by devsnek** [comment]
@pessip For future reference, you can just modify your branch and this PR will include those changes automatically, no need to close and reopen.

**Comment by pessip** [comment]
@devsnek Thanks. I'm pretty new to git so I'll just reopen.

**Comment by Benjozork** [comment]
LGTM

**Comment by ChruutvoLuzi** [comment]
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: Current date 27.10.2020
Version of the sim: Version the tester uses
PR Tested: #1498
Object of test: using other languages

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Changed Language from US-EN to DE-DE
2. restarted game
3. checked A320


Flight notes
n/a
Startup: Notes on the startup (Everything is normal, or I noticed something weird)
n/a
Taxi/Takeoff : Notes on the taxi an takeoff (Everything is normal, or this time the climb rate seems bigger than usual)
n/a
Cruise: Notes on cruise (Everything is normal, or I noticed something)
n/a
Descent/Landing : Notes on descent and landing (Work as expected or this time the descent rate seems bigger than usual)
n/a
Shutdown: Notes on the shutdown of the aircraft
n/a
Issues (If Any): none
Overall Rating: Good to go, no issues
Conclusions of the testing: Nothing, works as described

**Comment by Benjozork** [comment]
@ChruutvoLuzi did you confirm the UI displayed the right information as the attached issue mentions ?

**Comment by ChruutvoLuzi** [comment]
> 
> 
> @ChruutvoLuzi did you confirm the UI displayed the right information as the attached issue mentions ?

yes, i tried it with german and it works fine for me

**Pull request merged**
