### PR TITLE
[MCDU] Fix takeoff vspeed

### LINKED ISSUE #1562: [BUG] [MCDU] Wrong takeoff performance calculation
**Mod Version**

ba01b5f

**Describe the bug**

The calculated V speeds increase when setting a higher flap level in the mcdu.

**To Reproduce**

1. Enter flaps setting the mcdu
2. Press the corresponding lsk to generate a v speed

**Expected behavior**

The calculated V speed should decrease with higher flap levels set in the mcdu

**Actual behavior**

The calculated V speeds increase when setting a higher flap level in the mcdu.

**References**

takeoff_calc_before

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by linkeleven**
Fixes #1562 [BUG] [MCDU] Wrong takeoff performance calculation 

## Summary of Changes

- before it was taking the config 3 speeds for config 1 and vice versa

## Screenshots (if necessary)

takeoff_calc_com

## References

V2 speed tables to see the behaviour:
takeoff_calc_ref_1
takeoff_calc_ref_2
takeoff_calc_ref_3

## Additional context

My PR doesn't change the V speed formula, it just uses the right config for calculation.

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
Why is the lower ECAM temperature / weight indication on the MCDU in your screenshots ?

**Comment by linkeleven** [comment]
i just added the lower ecam in the picture to show the gross weight for calculation reference. my editing is bad should have clearly seperated it, its not how it looks ingame.

**Review by Benjozork — APPROVED** [review]

**Comment by Noxleee** [comment]
Name: Noxlee #7727
Date of testing: Current date 27/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1563 
Object of test: MCDU - Perf Page Take Off

Testing technique: Input of different weights
Steps you've made to test the Pull Request:
1. Load up ac at EKCH, tested different weights -> Vspeeds were changing like they should. All V2 Speeds were always above the table’s minima
2. Test start -> Rotate at new Vr -> Good!
3. Load up ac at SEQM (~9000ft), tested different weights -> Vspeeds were changing like they should. All V2 Speeds were always above the table’s minima, but the actual hight does not matter to the Vspeeds, were the same as at EKCH
4. Test start -> Rotate at new Vr -> Good!


Issues (If Any): No issues found
Overall Rating: Good
Conclusions of the testing: This Vspeeds are much better than the previous ones. They are still not right, but this is not the goal of the PR, so it’s good!

**Comment by donstim** [comment]
@linkeleven You said you didn't change the "V speed formula." Are the V speeds calculated or are they read from a table?  If there is a formula, can you post it?

The tables of minimum V2 limited by VMU/VMCA that you posted, are they for the NEO? @Noxleee noted that the MCDU V2 speeds were always above these minima, which I don't think they always would be if those are tables for the NEO.

**Comment by St54Kevin** [comment]
I cannot confirm this is working. I tested it by copying over the A320_Neo_CDU_MainDisplay.js into the current master. Loaded up into EDDW RW27 with 68,4T GW. What I got was this: 
image
Tried to change flap setting in the MCDU, Weights are correctly input into INIT B. Couldnt find why the speeds are so high. I crosschecked with my Company PW1100 Performance Calc and got V1 134, Vr 137, V2 141. Thats off alot. Dont know whats the problem

**Comment by Noxleee** [comment]
@St54Kevin That's not the goal of the PR. It only Corrects the Config 1 and Config 3 Vspeeds, because they were the other way round. The Formular is still untouched.

**Comment by ChruutvoLuzi** [comment]
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 28.10.2020
Version of the sim: 1.9.5.0
PR Tested: #1563 
Object of test: V Speeds Behavior

Testing technique: Try out
Steps you've made to test the Pull Request:

Started on the Runway
Entered different Flap Settings

Flight notes

Startup: n/a
Taxi/Takeoff: n/a
Cruise: n/a
Descent/Landing: n/a
Shutdown: n/a

Issues (If Any): None
Overall Rating:  Works as described
Conclusions of the testing: Fixes the weird default Behavior of higher VSpeeds on higher Flap Config. Does not calculate the correct Values, as it is not goal of this PR

**Comment by donstim** [comment]
> @St54Kevin That's not the goal of the PR. It only Corrects the Config 1 and Config 3 Vspeeds, because they were the other way round. The Formular is still untouched.

Roger that, but do you know what is actually being used so we can fix that (as another PR I guess)?

**Comment by linkeleven** [comment]
@donstim  so currently the formula uses the ambient temperature to grab a base value out of a table. after that runway and weight coefficients are applied and finally per flap setting a fixed amount of 6 knots are added.

**Comment by donstim** [comment]
> @donstim so currently the formula uses the ambient temperature to grab a base value out of a table. after that runway and weight coefficients are applied and finally per flap setting a fixed amount of 6 knots are added.

Ok, I don't want to get this PR mixed up in this discussion, but would really like to carry this further. It would be nice to have a more accurate takeoff speed calculation. How can we proceed?

**Comment by St54Kevin** [comment]
Oh okay yeah you are right. Let this merge, create a new PR and start off there I would say

**Comment by donstim** [comment]
I have opened the following issue to hopefully provide a way forward toward improving the takeoff speeds provided in the MCDU:  https://github.com/flybywiresim/a32nx/issues/1777

**Pull request merged**
