### PR TITLE
[CDU] Change visuals for constraints on flight plan page

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Added magenta * before constraints
- Only displaying valid constraints

## Screenshots (if necessary)

Before:
image

After:
image

## References

image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by wpine215** [comment]
So, just to clarify, in this PR the magenta star will display next to all speed waypoints and all valid altitude constraints?

I found some more documentation that may help for approaches.

Acrobat_9E2ze2XNlB

Acrobat_I6sUHOlQJX

Acrobat_7VAteeuJqX

**Comment by MisterChocker** [comment]
> So, just to clarify, in this PR the magenta star will display next to all speed waypoints and all valid altitude constraints?

No only where specific speed and/or altitude constraints are present.
I am nothing no logic in this pr, just the visuals on how constraints are displayed on the flight plan page.

**Comment by MisterChocker** [comment]
Regarding you pictures, I had implemented this priority logic in #1985 but removed this features because currently the mfs has non editable approach waypoints with constraints that are 7000ft above gs and less than 10nm away from gs intercept.
When this "bug" is sorted out, we can implement the priority feature again.

**Comment by danbw9** [comment]
Category: QA Test
Name: danbw9#7028
Date of testing: 30/11/2020
Version of the sim: 1.11.6.0
PR Tested: #2070 
Object of test: Testing the change in visuals to constraint on F-PLAN page

Testing technique: Try out on 2 different tests
Steps you've made to test the Pull Request:

Spawn C&D in EGKK (tried with default nav data and navigraph dataset)
- Set up as normal and when get to F-PLAN page put in ADMAG2X SID off RWY26L. 
- first check the ND PLAN page for correct depiction
- cross check with info in F-PLAN page
- ALT constraints at every intersection were correct, cross checked via navigraph charts
- magenta asterix correctly next to each constraint, but no speed constraint (perhaps to do with the plane nav database read ability being the limiting thing here)

Spawn on RWY in OMDB (tried with default nav data and navigraph dataset)
- fill out INIT A fully
- F-PLAN page input RWY30R DAVMO4F SID
- confirm same behaviour as before with visuals with ALT constraints shown with magenta asterix. 
- ALT constraints were correct and checked versus charts

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: LGTM with regards to the ALT constraints. I tried to look for speed constraints on 4 different departures but no luck but I tried in detail the 2 SIDs as described in the steps. After the above discussion I assume I should be seeing speed constraints? Though as I mentioned above I am guessing that the plane can't read it from the nav data base (navigraph or default).

**Comment by MisterChocker** [comment]
@danbw9 sounds like the speed constraints were not set then, nothing I have influenced. Maybe speed constraints can't be read on SID? I believe I've only seen the mcdu show speed constraints for STAR etc.

**Comment by MisterChocker** [comment]
@wpine215 do we need more testing, since this is a pretty simple change?

**Pull request merged**
