### PR TITLE
feat: add functionality for some OVHD switches

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

* Add functionality and simvars to BLUE PUMP OVRD, HYD LEAK MEASUREMENT VALVES G/B/Y, ENG FADEC GND PWR 1/2 and APU AUTO EXITING TEST
* Add functionality to READING LIGHT knobs, assigned to "LIGHT POTENTIOMETER:96" and to "LIGHT POTENTIOMETER:97"
* Fix malformed XML in ModelBehaviors

## Screenshots (if necessary)

image

## References

N/A

## Additional context

N/A

Discord username (if different from GitHub): someperson#4953

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by lukecologne** [comment]
Potentiometer indices 94 and 95 are already taken by the WX/TERR ND brightness

**Comment by Benjozork** [comment]
@lukecologne fixed. using 96 and 97 now.

**Comment by Benjozork** [comment]
Will not add a changelog as no behavior is attached to those switches.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 12/10/2020
Version of the sim: 1930
PR Tested: #1272 

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane C&D
2. Inspected the buttons funcionality
3. Looked for conflicts with other buttons and switches 
4. Loaded on the runway and did a short flight while repeating the first 3 steps.

Overall Rating: Good
Conclusions of the testing: Looks good to me! Thank you for your work!

Additional comment: If we are able we should at one point correct the BLUE PUMP button to say ON instead of OFF

ON

**Comment by Pleasure0102** [comment]
so the biggest problem with the emmisive and colors is the following: you have only one "White ON" for example, if you change that particular color, you change the color of them all. This is something we can change once we can change the model, but until then you have to see what you can change and what you can't

**Comment by Benjozork** [comment]
@FlyingCarpet7 @lukecologne already reported this in #956 I think

**Review by NathanInnes — COMMENTED** [review]
Code looks good, ready to test

**Comment by HugoTro** [comment]
i would like to test it...  but where is the panel?

**Comment by joshbxd514** [comment]
Name: Joshbxd515 #4978
Date of testing: 14/10/2020 12:00 UK
Version of the sim: 1.9.5.0
PR Tested: 1272

Testing technique: Try out


Overall Rating: Good  

Conclusions of the testing:  All Light up a should no issues. Good Work.

**Comment by Carter633** [comment]
Name: British Avgeek YT -- Carter633#1436
Date of testing: Current date 14/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1272

Testing technique: Cold & Dark start up, switches on and off
Steps you've made to test the Pull Request:
1. Cold and Dark, start up and selecting each switch with Batt on - check functionality
2. Check each item on/off behaviour
3. APU on, repeated step 1 and 2
4. Engines on, using idle and TOGA power, repeating step 1 and 2
5. APU off, engines still on, repeated step 4

Overall Rating: Good
Conclusions of the testing: No issues found

**Comment by lukecologne** [comment]
Tested after the merge and it still works fine. LGTM.

**Pull request merged**
