### PR TITLE
Update

### PR DESCRIPTION
**Pull request by pilotdomee**
Changed engine starter ALL OFF to ALL CRANK, because Airbus uses CRANK instead of OFF.

Preflight part mistake

## Summary of Changes

Fixed preflight part. 

## References

Wizz Air offical A320 checklist.

## Additional context

Discord username (if different from GitHub): DominikC#7184

## Testing instructions

I recommend testing it by an airline employee who has access to their checklist. Probably various at different airlines.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
Please provide a title.

**Comment by lukecologne** [comment]
I don't understand this change, you change the engine master switch checklist item to crank, but the engine master switches only have an "ON" or "OFF" position, no crank. You probably mean the engine mode selecter, which has "IGN/START", "NORM" or "CRANK". But even then, it doesn't really make sense to put the engine mode selector in the crank position in the cockpit preperation checklist.

**Comment by ErickSharp** [comment]
Please close this pull request, the engine master switches are the 2-step switches that are either 'ON' or 'OFF'. The engine mode selector is the control with 'CRANK' 'OFF' and 'IGN/START'.

**Comment by davidwalschots** [comment]
No response. Closing this one.

**Pull request closed without merging**
