### PR TITLE
feat: Upscaled FBW livery, fixed missing flerg. 

### PR DESCRIPTION
**Pull request by FoxinTale**
## Summary of Changes

Upscaled the fuselage to 8K and the engines & wings to 4k.
Removed the A32NX and the green stripe from the engines.

I have since fixed the strange thing on the "y" in 'fly' by the right side of the door.

While essentially a duplicate, this is the one to use. I made a mistake when pushing the changes (deleted my fork, recreated the branch, and it wouldn't let me push the changes because it was already up to date)  and this was the easiest way to fix it. 

## Screenshots (if necessary)

See #3797 for screenshots. 

## Additional context

On my system, I can manage low-medium (Ryzen 5 1600AF, RX 580, 16 Gb ram) , and my monitor is 1600 x 900. there may be little, if any visual difference between before and after. See testing instructions for further.

Discord username (if different from GitHub): Aubrey Jane#7563

## Testing instructions

Especially those who can run the sim on all medium settings and up on a 1080p or higher monitor, please take screenshots before and after, and compare them yourselves. Pay close attention to the "flybywire" text on both sides of the aircraft, make sure the stripe and text are gone on the engines, and anywhere else you think would be of importance.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by pepperoni505** [comment]
IMO you should switch to use our official font. As great as your tracing job is, we need to stick to our own branding guidelines. Don't know if this qualifies as allowed or not. cc. @NathanInnes

**Comment by FoxinTale** [comment]
> IMO you should switch to use our official font. Here is a link: https://www.1001fonts.com/aileron-font.html. As great as your tracing job is, we need to stick to our own branding guidelines. Don't know if this qualifies as allowed or not. cc. @NathanInnes

Thing is, with the official font, letters did not line up 100%. The 'wire' part, especially the very last 'e' on the right side (above view, looking straight down) was the worst offender.  With both aileron normal and aileron narrow, it didn't line up without stretching the text as if it was an image. Some of the letters are aileron.  The ones it did not line up with were traced. I can say which ones if needed.

**Comment by Benjozork** [comment]
@FoxinTale needs rebase

**Comment by FoxinTale** [comment]
> @FoxinTale needs rebase

...How? I try to rebase via desktop and it just says "already up to date" which is a complete lie.

**Comment by FoxinTale** [comment]
Forget it. Just gonna closer this and make a third one.

**Pull request closed without merging**
