### PR TITLE
feat: exterior engine sound rework and other changes

### PR DESCRIPTION
**Pull request by hotshotp**
## Summary of Changes

I have completely reworked the exterior engine startup, spool up, and flyby sounds.

-The startup now has a better ignition sample, and an overall higher quality sound
-The spool up has many more layers and now is very realistic
-Flyby has a better exhaust sound and an overall more realistic sound
-Reverse sound is much better on exterior

Interior has got some small changes too.

-Startup has a completely reworked "before ignition" sound
-It now has a better transition between the ignition cutout and the idle sound (more easily heard in the cabin)
-It has a slight whale call sound between 20% and 27% n1
-It has a higher quality buzzsaw sound
-Reverse is a bit louder in cockpit now
-New nosewheel rotation/liftoff sound

Now for other changes:

-I have changed the APU initial startup sound to have a bit faster igniters, as a reference from komp. Before they were way too slow
-Pack sounds now come from the pack outflow valves
-Gear sounds now differ slightly for gear up and down
-The taxi sound now is a little higher quality, i removed some of the lower quality clicks

## References

Used a bunch of youtube videos and references from engineers. Apu video from komp and engine references from a lot of youtube videos.

## Additional context

Let me know of any suggestions or tweaks I can make, I will try to make them as quick as I can!

Discord username (if different from GitHub):

Boris#9134

## Testing instructions

1. Start batteries, then press APU master and starter switch and immediately go to exterior view and listen for igniters
2. Start APU bleed and listen for the pack sounds and that they are coming from the outflow valves
3. Start engine, preferrably listen from the cabin, and listen to the entire sequence. Then shut down the engine and listen again from the exterior view
4. Start both engines, and in the cabin listen for the quiet whale call sound at just above idle thrust
5. Go to exterior and spool up the engines to TOGA slowly and listen to the spool up
6. Take off and listen to gear up sound and see that it is different from the gear down
7. During takeoff, position your drone camera farther from the aircraft and turn off Follow Mode so the aircraft flies by and you hear the flyby sounds, try doing a flyby at 80-90% n1, and at around 50% n1 to hear how it sounds.
8. Listen to the buzzsaw at takeoff
9. On approach, check gear down sound
10. On landing, listen to reverse thrust from interior and exterior to confirm that the sound was louder on the interior and that it is much better on exterior than before

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by tyler58546 — CHANGES_REQUESTED** [review]
Needs changelog.

**Review by tyler58546 — APPROVED** [review]
LGTM

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: Maple#3904
Date of testing: Current date 12/02/
Version of the sim: Version the tester uses
PR Tested: #000
Tier of testing: 2
Changes to observe: Engine sounds
- engine sounds
- taxi/ground roll sounds
- gear sounds
- flyby sounds

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Started up the APU and listened to it on the exterior
2. Started engine two with packs off on the exterior
3. Started engine one with packs off on the interior
4. Spooled up the engine slowly to listen whale call that was added on taxi
5. Spooled up the engines to 50% listened to the interior and exterior
6. Spooled up the engines to FLX and listened to the interior and exterior
7. Listened to new nose wheel vibration sounds
8. Listened to the new buzzsaw
9. Turned on AP and listened to flyby on takeoff, climb, cruise, and descent
10. WILL CONTINUE STEPS AS FLIGHT PROGRESSES

Flight notes (When done a full flight): CYQT/25 DCT FEMOK V133 YQT DCT YBR J504 YDR DCT KEMKA KEMKA6 CYQR/31

Media: No footage was shown but streamed the full flight on General VC on the discord server with @hotshotp 

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Sounds are extremely well done and are a vast improvement from last PR. All is working as intended

**Comment by NonstopFlying** [comment]
Category: QA Tester
Discord: NonstopFlying#6771
Date of testing: Current date 12/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3496
Tier of testing: 2
Changes to observe: 
-Engine sounds
-APU
-Buzsaw
-Takeoff
-Engine Starting

Testing technique:

Started APU, went outside and listend 
-APU bleed
-Engine startup from the cabin
-Gear up and down from Cockpit and cabin 
-Flyby at 80% and 50%
-Landing sounds

Suggestions: Make the Gear sound a little bit louder as I think in reality it is much louder from inside the cabin/cockpit, In my opinion it's barely hearable.

Overall Rating: Good
Sounds are amazing just like Hotshot always does, from the first time you were in my streams and showed me the new sounds, to now, they have improved a lot. Keep doing what you're doing and listen to a lot of real life sounds. Thanks!

**Comment by hotshotp** [comment]
> Category: QA Tester
> Discord: NonstopFlying#6771
> Date of testing: Current date 12/02/2021
> Version of the sim: 1.12.13.0
> PR Tested: #3496
> Tier of testing: 2
> Changes to observe:
> -Engine sounds
> -APU
> -Buzsaw
> -Takeoff
> -Engine Starting
> 
> Testing technique:
> 
> Started APU, went outside and listend
> -APU bleed
> -Engine startup from the cabin
> -Gear up and down from Cockpit and cabin
> -Flyby at 80% and 50%
> -Landing sounds
> 
> Suggestions: Make the Gear sound a little bit louder as I think in reality it is much louder from inside the cabin/cockpit, In my opinion it's barely hearable.
> 
> Overall Rating: Good
> Sounds are amazing just like Hotshot always does, from the first time you were in my streams and showed me the new sounds, to now, they have improved a lot. Keep doing what you're doing and listen to a lot of real life sounds. Thanks!

thank you! i did not edit the volume of the gear, just the sound of it so it is realistic as it was before

**Comment by ExampleWasTaken** [comment]
Category: QA Tester
Name: ExampleWasTaken#0886
Date of testing: 13/02/2021z
Version of the sim: 1.12.13.0
PR Tested: #3496
Tier of testing: 2
Changes to observe:
Engine sound rework

Testing technique:
Steps you've made to test the Pull Request:
1. Loaded C&D
2. Listened to exterior APU start
3. Listened to exterior APU bleed/packs start
4. Listened to full engine startup from default cabin view right hand side
5. Listened to exterior engine spool up
6. Checked that gear up sound is different from gear down sound
7. Took off with drone camera placed at about V2 and listened to about 80% N1 as flyby
8. Performed flyby with about 50% N1
9. Listened to buzzsaw at takeoff (interior + exterior)
10. Listened to noticeably louder reverse thrust from interior and exterior

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): Absolutely nothing

Overall Rating: Incredible
Conclusions of the testing: Absolutely incredible work.

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: 13/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3496 
Tier of testing: 2
Changes to observe:
Reworked exterior engine startup, spool up, and flyby sounds

Testing technique: Loaded c/d and checked all the listed changes during different phases of flight
Steps you've made to test the Pull Request:
1. Tested apu starter sound 
2. Tested outflow valve sound 
3. Tested engine startup sound from both cabin and exterior view  
4. Tested engine spool up from TOGA in exterior view 
5. Tested whether gear up sound is different from gear down  
6. Tested flyby sound
7. Tested gear down sound
8. Tested whether reverse thrust is louder on the interior and improved in exterior

Flight notes: N/A

Media:

https://user-images.githubusercontent.com/74972083/107839695-97b51780-6de8-11eb-9c5d-4e28b7a9b28a.mp4

https://user-images.githubusercontent.com/74972083/107839704-ae5b6e80-6de8-11eb-897e-21991dca2b69.mp4

https://user-images.githubusercontent.com/74972083/107839750-07c39d80-6de9-11eb-94fe-fdfbf3de48b4.mp4

https://user-images.githubusercontent.com/74972083/107839776-232ea880-6de9-11eb-8271-b4bf97bec29a.mp4

https://user-images.githubusercontent.com/74972083/107839838-65f08080-6de9-11eb-87cc-7791e281cf2b.mp4


https://user-images.githubusercontent.com/74972083/107839883-a9e38580-6de9-11eb-8c19-9fa169f0a38b.mp4


Issues (If Any): N/A


Overall Rating: Good 
Conclusions of the testing: Great addition good job!

**Comment by danbw9** [comment]
Category: QA Test
Name: danbw9#7028
Date of testing: 13/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3496
Tier of testing: 2
Changes to observe: Engine sound rework

Testing technique: Try out and compare versus references (YouTube videos and other IRL pilots comments) as well as previous sound behaviour before this PR changes. 

Steps you've made to test the Pull Request:

- Start flight from C&D at LEMD. Start APU on batteries and right after APU start and right after move to external view right behind the APU and 
- APU Bleed on. Confirm the sound of the packs is from the correct position under the fuselage where the pack outlets are. And check for positional/distance based volume, that it's appropriate as I move away. 
- Started ENG2 and moved to external view drone, right next to the engine. Listened to full startup and the can hear the stages more distinctly and more realistic. Sounds a lot more crystal clear and in more detail. 
- Started ENG1 from the left default pax view. Again, more detail particularly the window vibration could be heard this time as well. 

Pushed back and taxied for take off.
- TOGA take off. In external view. Spooled up towards TOGA thrust, deliberately being more gradual than usual (also reflecting the actual spool up time for the real engine - in terms of sound). Sounds more polished up and buzzsaw is clear in both external and internal (cockpit) view. 
- nosewheel vibration changes observed
- Gear up sound is different to the gear down sound with this PR. 
- After take off, coordinated with Boris on how to do a flyby with the camera view. The sound is clean and sounds correct. Flown in TOGA for maximum effect with the difference in sounds over time. 
- Came back round to land and gear down is the same as before, different to the gear up. 
- Upon touch down, did Max reverse with external view ready, the sounds are louder and more pronounced. Also in the cockpit, whereas before it was barely noticeable amongst the other sounds. 

After some work from Boris testing some commits, confirmed that the APU flap & ignition/spool/start up sequence sounds are correct. Started APU in cockpit and right after went out into drone view right next to the APU. Electrical whirl, for a few seconds, linked to the flap opening is correct and nicely transitions into the ignition and start up. 

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): None. 

Overall Rating: Good
Conclusions of the testing: SGTM. With IRL experience flying with PW engines I cannot comment on the complete accuracy of the CFM LEAP engines, but from what I heard, there is nothing wrong. One thought I had which was confirmed by other IRL pilots was the reverse sounds being too loud. Apart from my own testing experience, I also chatted with Boris via Discord Voice chat to discuss what needed to be tested exactly and in what conditions. Great job!

**Pull request merged**
