### PR TITLE
chore(textures): downscale some textures to 2K

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

Downscaled some textures to 2K from 4K since they were unnecessarily large for what they are.  The textures selected were curated by @DarkOfNova, downscaled textures provided by @FoxinTale .

Downscaled textures are:

A320NEO_COCKPIT_INPUTS01_ALBD.PNG
A320NEO_COCKPIT_INPUTS01_COMP.PNG
A320NEO_COCKPIT_INPUTS01_NORM.PNG
A320NEO_COCKPIT_INPUTS02_ALBD.PNG
A320NEO_COCKPIT_INPUTS02_COMP.PNG
FLYPAD_ALBEDO.TIF
FLYPAD_COMP.PNG
FLYPAD_NORM.PNG 
GLASS_COMP.PNG
GLASS.PNG	            

## Testing instructions
Look around the cockpit and check the textures to make sure there are no problems caused by the downscale, and there is no significant visual fidelity loss noticed.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by DarkOfNova — CHANGES_REQUESTED** [review]
Normal texture is messed up for the 'FLYPAD_NORM' and 'INPUTS 1' textures.

**Review by DarkOfNova — APPROVED** [review]
LGTM

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 03/03/2021
Version of the sim: 1.13.17.0
PR Tested: #3786 
Tier of testing: 1
Changes to observe: Downscaled textures

Testing technique: Tryout

Steps you've made to test the Pull Request:

1. Tested the PR on a full flight from VEIM-VIDP
2. Observed cockpit textures, including flypad and the glass on the ECAM/Displays
3. No visual changes observed given the constraint of using a 1080p monitor
4. Reduction of stutters/FPS improvement was observed

Issues (If Any): None

Overall Rating: Good

Conclusions of the testing: A lot of users limited by GPU currently would feel a slight performance improvement with this PR, hope to see it retained in 2K if it does not really affect the visuals drastically

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 04/03/2021
Version of the sim: 1.13.17.0
PR Tested: #3786 
Tier of testing: 1
Changes to observe: Downscaled textures to 2K

Testing technique: Spawned and checked in day, dusk and night
Steps you've made to test the Pull Request:
1.  Spawned C&D at EGBB - daylight, checked texturing
2.  Changed to night, checked textures
3.  Changed to dusk, checked textures

Flight notes (When done a full flight): N/A
Media: N/A

Issues (If Any): None found

Overall Rating: Good
Conclusions of the testing: Personally, I'm limited by Main Thread so no impact here for me but reducing to 2K I couldn't see any difference, and any performance saved is only a good thing!

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 4.3.2021
Version of the sim: 1.13.16.0
PR Tested: #3786
Tier of testing: 1
Changes to observe: Texture downscaling
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
3.) Setuo: Textures on Ultra
2.) Looked at cockpit (especially displays and EFB) at different daytimes

Issues: -

Overall Rating: Good

Conclusions of the testing: Looks very similar to the textures without downscaling.

Hope this helps :-)

**Review by Benjozork — CHANGES_REQUESTED** [review]
Please add the original textures to `src/`

**Comment by ImenesFBW** [comment]
> Please add the original textures to `src/`

Done.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by CAC14** [comment]
Can someone tell me what parts of the cockpit were changed specifically?  I play in 4k and i think a few areas are blurry when zoomed out but i want to make sure i'm looking at the right spots before writing a full report.

**Comment by DavidEGTE** [comment]
may I say or ask a observation about  down-scaling from 4k to lower resolution, for some or for at least for me will be a handicap as I run full 4k on the sim will it not be better remaining on 4k for the time being and worry after for down-scalling so it could be opt-in/out via the installer?

**Comment by CAC14** [comment]
> 
> 
> may I say or ask a observation about down-scaling from 4k to lower resolution, for some or for at least for me will be a handicap as I run full 4k on the sim will it not be better remaining on 4k for the time being and worry after for down-scalling so it could be opt-in/out via the installer?

I'm thinking is 4k per panel and not 4k for the whole screen so you wouldn't notice the reduction unless the texture takes up more then half the screen?  But i.m not a developer so i don't know how it works.  IMO  it does seem grainier at certain zoom levels, but i want to make sure i'm looking at the right thing fist.

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 3/6/2021
Version of the sim: 1.13.17.0
PR Tested: #3786 
Tier of testing: 1
Changes to observe:
Downscaled textures are:

A320NEO_COCKPIT_INPUTS01_ALBD.PNG
A320NEO_COCKPIT_INPUTS01_COMP.PNG
A320NEO_COCKPIT_INPUTS01_NORM.PNG
A320NEO_COCKPIT_INPUTS02_ALBD.PNG
A320NEO_COCKPIT_INPUTS02_COMP.PNG
FLYPAD_ALBEDO.TIF
FLYPAD_COMP.PNG
FLYPAD_NORM.PNG
GLASS_COMP.PNG
GLASS.PNG

Testing technique: Tried out
Steps you've made to test the Pull Request:
1. Spawned C&D at Kdca in the airbus house livery 
2. Looked at the overhead textures 
3. Looked at the pedestal textures
4. Looked at the FCU textures


Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
image
Noticed textures around the buttons are kinda weird
image
Textures look paperish 

Issues (If Any): 
Textures look paperish 
Textures around the buttons are kinda weird
Overall Rating: Good
Conclusions of the testing: Noticed some small issues but is not really a show stopper.

**Comment by SpeedDemon77** [comment]
Category: Trial?
Name: **Delta Zero#0115**
Date of testing: Current date 06/03/2021
Version of the sim: **1.13.17.0**
PR Tested: **#3786**
Tier of testing: **1**
Changes to observe:
**Downscaled textures are:

A320NEO_COCKPIT_INPUTS01_ALBD.PNG
A320NEO_COCKPIT_INPUTS01_COMP.PNG
A320NEO_COCKPIT_INPUTS01_NORM.PNG
A320NEO_COCKPIT_INPUTS02_ALBD.PNG
A320NEO_COCKPIT_INPUTS02_COMP.PNG
FLYPAD_ALBEDO.TIF
FLYPAD_COMP.PNG
FLYPAD_NORM.PNG
GLASS_COMP.PNG
GLASS.PNG**

Testing technique: **Spawn in and look at the panels in question**
Steps you've made to test the Pull Request:
**1. Spawned in at an airport; on the runway
2. Looked at the modified panels**

Flight notes (When done a full flight): **None**

Media: Insert screenshots, recordings, or anything relevant to the review here.
**4k Textures:**
4k Center

**2k Textures:**
2k Center



Issues (If Any): **Textures look good, but around the knobs(i.e. radios) the black circle under the knob looks imperfect.** 

Overall Rating: Good
**Conclusions of the testing: Panels still look quite good and not noticeably downgraded for the most part. At certain zoom levels, it appears that some textures appear somewhat grainy, but hardly noticeable. A note on FPS as well, I was just looking to see if my FPS was affected(My system is an i9-9900k, 2080ti, and 32GB of ram), I noticed no FPS improvements(Although I'm aware I'm on the upper end of the spectrum and don't doubt the performance gains for other users, I just thought I should mention this).**

**Pull request merged**
