### PR TITLE
[CDU] Fix APPR/GO AROUND page order

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

I'm pulling #1824 apart to make it more digestible and get stuff landed.

This PR touches the PERF page for the following things:
- improve the display of the prev/next page buttons (and similarly activate/confirm approach phase)
- fix wrong character for confirm approach phase button (* over arrow)
- prevent calling up earlier pages during the approach and go around phase
- fix the go around/approach page order during the approach phase

## Screenshots (if necessary)

image
image

### In APPR

image
image

### In GO AROUND

image

## References

image
image
image
image

## Additional context

Note that this PR changes only the visuals and the button behaviour. It does not fix the transitions between flight phases itself. For example, when initiating a very high, pressing CONFIRM APPR PAGE might lead to a transient GO AROUND page before being returned to CLB. This behaviour will need improvement in a future PR.

Discord username (if different from GitHub):

## Testing instructions

Spawn in during preflight or on the runway, and make sure you can access all pages. The order should be:
TAKEOFF -> CLB -> CRZ -> DES -> APPR -> GO AROUND

Spawn in on an approach and verify the accessible PERF pages are only:
APPR -> GO AROUND

Execute a go around, and observe the PERF page order as follows:
GO AROUND -> APPR

If APPR is immediately replaced by CLB that is an unrelated bug that already exists today and will need to be fixed in a future PR.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 09/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2940 
Object of test: APPR/GO AROUND page
Testing technique: Straight-out departure from RWY

Steps you've made to test the Pull Request:

1. Spawned at VABB RWY27
2. Checked order of PERF pages: TAKEOFF -> CLB -> CRZ -> DES -> APPR -> GO AROUND
3. Departed RWY27, straight climb to 5000ft. Turned left for circuit pattern.
4. Observed PERF pages: CLB -> CRZ -> DES -> APPR -> GO AROUND
5. On downwind, descended to 2800ft and activated APPR PHASE.
6. Observed PERF pages: APPR -> GO AROUND
7. On finals, initiated Go Around, PERF page changed to GO AROUND with option to reactivate APPR PHASE
8. After activating APPR PHASE from the GO AROUND page, APPR page shows up, and the next page is GO AROUND.

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: The order of the PERF pages show up as described.

**Comment by sidnov** [comment]
Also, how exactly do we spawn directly at an approach? I could test that as well and update the review.

**Comment by beheh** [comment]
On the map, you can click on a runway and select "set arrival". Then, don't set any departure. The departure should default to something like "In the vicinity of <airport>, 1500ft", and then when you launch the simulation you're right on an approach.

**Comment by sidnov** [comment]
> On the map, you can click on a runway and select "set arrival". Then, don't set any departure. The departure should default to something like "In the vicinity of , 1500ft", and then when you launch the simulation you're right on an approach.

Sounds good. Trying it right now and updating review.

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by cianwhite** [comment]
Category: QA Tester
Name: Cian#3596
Date of testing: 11/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2940 
Object of test: To test the 

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request: Make sure APPR/GO ARR page is correct after a go around
1. Loaded in cold and dark at EIDW, all PERF pages are there and working as desired. The 
2. Taken off from RWY 28L and commence right hand traffic patterns, doing 5 landings in total.
3. Of the 5, 2 were TOGA G/A at 500ft above the runway, 2 were SOFT G/A at 500 ft and 1 was a late TOGA go around after initial touchdown.
4. On all of these go arounds the pages changed from APPR->GO AROUND and I was able to engage approach mode for the next approaches, leading me back to APPR. I can confirm that the changes to activating the APPR mode (* over an arrow) work as intended.
5. Spawned in the air on an approach for EGCC 23R and the only pages I could access were APPR and GO AROUND, I performed a TOGA go around and once more it changed from APPR->GO AROUND.

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: All pages show up as intended, and the PERF page follows the APPR->GO AROUND as desired, no matter from CTD or an aerial start.

**Pull request merged**
