### PR TITLE
feat(ecam): Add TCAS STBY warning

### PR DESCRIPTION
**Pull request by paul92ilm**
## Summary of Changes

- Add TCAS STBY warning 

## Screenshots (if necessary)

image
image

## References

image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- On ground, check that the TCAS STBY warning doesn't appeared with TCAS on STBY mode
- Take off with TCAS in STBY mode
- Check that the "TCAS STBY warning" appears passing 1500ft
- During the flight, try to change the TCAS mode and verify if the warning disappeared and appeared normally 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by tyler58546 — APPROVED** [review]
LGTM

**Review by tyler58546 — APPROVED** [review]

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/07/2021
Version of the sim: 1.12.13.0
PR Tested: #3378 
Tier of testing: 1
Changes to observe: 
- Check that the "TCAS STBY warning" appears passing 1500ft.
- During the flight, try to change the TCAS mode and verify if the warning disappeared and appeared normally.

Testing technique: Take off and climb while checking tcas

Steps you've made to test the Pull Request: 
1. Take off with TCAS STBY.
2. At 1500ft warning comes (see screenshot).
3. Turned on TCAS and warnings autoresets.
4. Turned off TCAS and warnings shows up again.

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
FlightSimulator_GjdWGCnnwl

Issues (If Any): None.

Overall Rating: Good.
Conclusions of the testing: LGTM

**Comment by RichardPilbery** [comment]
Category: QA Tester
Name: tricky_dicky#3571
Date of testing: Current date 02/07/2021
Version of the sim: 1.12.13.0
PR Tested: #3378
Tier of testing: 1
Changes to observe:

Check that the "TCAS STBY warning" appears passing 1500ft.
During the flight, try to change the TCAS mode and verify if the warning disappeared and appeared normally.
Testing technique: Take off and climb while checking tcas

Steps you've made to test the Pull Request:

1. Checked TCAS STBY message on in green while on ground
2. Took off with TCAS still in standby
3. Fettled with it in flight to check message went off (audible chime too)
4. Checked again once landed.

Flight notes (When done a full flight): LGTM

Media: Insert screenshots, recordings, or anything relevant to the review here.

**Before takeoff**
tcas-1

**Above 1500ft**
https://user-images.githubusercontent.com/5834254/107158145-02e19280-6980-11eb-8d0d-fac35629a85a.mp4

**After landing**
tcas-landing

**Comment by beheh** [comment]
The `NAV TCAS STBY `needs an additional flight phase 6 check, because the flight phase inhibitions can be overridden using the recall button, and this should never appear on the ground even when you press RECALL.

**Comment by beheh** [comment]
Filed #3492 to rectify this.

**Pull request merged**
