### PR TITLE
[ECAM REWRITE] Added SAT and TAT to SD

### PR DESCRIPTION
**Pull request by RichardPilbery**
Fixes #[issue_no]

## Summary of Changes

* Add SAT and TAT to reworked ECAM

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
I think `$font-size-large: 17px;` is closer to IRL for unit symbols:

image

image

**Comment by St54Kevin** [comment]
Also adding ISA deviation should be pretty easy to do. It's just a simple equation

**Comment by MisterChocker** [comment]
For ISA temp: `alt / 1000 * (-1.98) + 15`

**Comment by RichardPilbery** [comment]
But it's conditionally displayed right?

**Comment by lukecologne** [comment]
grafik

Displayed is the delta ISA, only when in STD altimeter mode. Also, it seems to be an optional feature, as indicated by the triangle with the star

**Comment by lukecologne** [comment]
Also, the sign is displayed for both negative and positive values, for all temperatures, and all the temperature values are clamped between -99 °C and 99°C

**Comment by wpine215** [comment]
Can the PR description include a brief summary of changes? Then I can go ahead and mark it as ready for testing. Thanks!

**Comment by Benjozork** [comment]
**note to maintainers:** This is for the ECAM rewrite

**Comment by Benjozork** [comment]
## For QA

This branch breaks everything except the ECAM. Please do not pay attention to other displays as they are expected to not work.

**Comment by donstim** [comment]
> For ISA temp: `alt / 1000 * (-1.98) + 15`

Just to be clear, the units in this equation are: 
ISA temp is in deg C; and
alt (should actually be height) is geopotential height in feet.
Since ISA temp will only be given in whole numbers (i.e., rounded off), it should be okay to use geometric height above mean sea level instead of calculating the geopotential height, which can be quite involved. Just **don't** use the airplane's pressure altitude from the altimeter reading, especially if the baro has been set the "Standard," unless the atmospheric conditions are actually standard (rare if using live weather). When set to STD, the altimeter gives you pressure altitude, which is a height above a standard datum plane, and is only the same as geometric altitude when the actual pressure variation on that day is the same as the standard. When the baro has been set to local pressure, it can still differ from geometric altitude due to temperature.

If you want a reference, see https://www.flyingmag.com/everything-explained-all-about-altitude/#:~:text=It%20is%20the%20height%20above,to%20the%20reported%20altimeter%20setting.&text=On%20that%20very%20rare%20%22standard,altitude%20will%20equal%20true%20altitude.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: Current date 15/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2405
Object of test: Checking SAT and TAT rework
Testing technique: Try-out (multiple tests)

## Steps you've made to test the Pull Request:

 * C&D start, observing lower ECAM.
 * Started mid-air, observing lower ECAM. 

### Flight notes

 * Startup: The temps do not show up after ADIRS align.

## Overall Rating: Needs improvement.

#### Issues (If Any):

 * The temps don't show up if you do C&D start and wait for ADIRS align.
 
#### Conclusions of the testing:

 * Everything seems to be working as documented, except the problem with temps not showing up after alignment. If this is due to systems not talking to each other and not the fault of this  PR consider this QA review as **GOOD**.                

#### Pictures:

**Comment by RichardPilbery** [comment]
Thanks for review @ImenesFBW. @Benjozork I have noticed that the L:A320_Neo_ADIRS_STATE SimVar does seem to be acting up. For example, if you log the value, it appears to work on initial start-up, but not subsequently (if you reset the panel) or, according to @ImenesFBW QA tests, if you spawn in-air. Do you think this is a quirk related to the rewrite or something else?

**Comment by RichardPilbery** [comment]
Touch wood, AIDRS issue is now fixed.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: Current date 17/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2405
Object of test: Checking SAT and TAT rework
Testing technique: Try-out (multiple tests)

## Steps you've made to test the Pull Request:

 * C&D start, observing lower ECAM.
 * Started mid-air, observing lower ECAM.
 * Started on the runway, observing lower ECAM.

## Overall Rating: Good

#### Conclusions of the testing:
 * LGTM, thank you for your work!

**Pull request merged**
