### PR TITLE
fix: brake force tuning

### PR DESCRIPTION
**Pull request by crocket63**
Fixes #[issue_no]

## Summary of Changes

This PR is aimed at fine tuning the brake performances to match the best we can real data

- [x] Find a base brake scale factor 
- [x] Adapt brake force to match real data in conf FULL and conf 3
- [x] Adapt autobrake deceleration slopes to match real world data
- [x] Adapt brake force friction curve for realistic alternate 1000psi limited brake

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Autobrake works properly
Plane brake distances are correct in flap conf FULL and conf 3
Plane brake distance is correct in Askid / off degraded mode

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ErikNL80** [comment]
Looking forward to this one, brake force is way too much right now...

**Comment by crocket63** [comment]
> Looking forward to this one, brake force is way too much right now...

Apparently we increased it to match real data :)

**Comment by donstim** [comment]
LGTM. I checked this against stopping distances derived from FlySmart landing distances provided by @tshomas for weights of 50, 55, and 66 T on a level, dry runway - both max manual braking and autobrake medium for CONF FULL and CONF 3. Hopefully, we can add more conditions in future tuning.

**Review by Benjozork — APPROVED** [review]

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #4992 
Tier of Testing: 1
Date: 19/07/2021

**Testing Process:**
1. Loaded onto approach RW27 in EDDW (2000m RW perfect for measuring)
2. Used my IRL EFB landing performance to get an unfactored landing distance for MANUAL, MED and LOW braking
3. Tried to touchdown right on the big bars, all with A/THR on to be consistent, Idle REV

4. **Measured from drone view (ISA WX), all -+50m due to touchdown:**
60T, FULL, LOW, 1578m calculated, 1460m landed -> -118m
60T, FULL, MED, 1280m calculated, 1100m landed -> -180m
60T, FULL, MAN, 1012m calculated, 880m landed -> -132m

60T, FLAP 3, LOW, 1799m calculated, 1820m landed -> +21m
60T, FLAP 3, MED, 1447m calculated, 1356m landed -> -91m
60T, FLAP 3, MAN, 1131m calculated, 1104m landed -> -27m

**A/SKID OFF**
60T, FULL, MAN (1000psi), 1714m calculated, 1590m landed -> -124m

**Negatives:** 
- I landed on the bars consitently and the distances in general seem a LITTLE too short with flaps FULL (little too strong brakes)

**Testing Results:** Passed, because I think its close enough

**Comment by crocket63** [comment]
> **Quality Assurance Tester**
> 
> Object of testing: #4992
> Tier of Testing: 1
> Date: 19/07/2021
> 
> **Testing Process:**
> 
> 1. Loaded onto approach RW27 in EDDW (2000m RW perfect for measuring)
> 2. Used my IRL EFB landing performance to get an unfactored landing distance for MANUAL, MED and LOW braking
> 3. Tried to touchdown right on the big bars, all with A/THR on to be consistent, Idle REV
> 4. **Measured from drone view (ISA WX), all -+30m due to touchdown:**
> 
> 60T, FULL, LOW, 1578m calculated, 1460m landed -> -118m
> 60T, FULL, MED, 1280m calculated, 1100m landed -> -180m
> 60T, FULL, MAN, 1012m calculated, 880m landed -> -132m
> 
> 60T, FLAP 3, LOW, 1799m calculated, 1820m landed -> +21m
> 60T, FLAP 3, MED, 1447m calculated, 1356m landed -> -91m
> 60T, FLAP 3, MAN, 1131m calculated, 1104m landed -> -27m
> 
> **A/SKID OFF**
> 60T, FULL, MAN (1000psi), 1714m calculated, 1590m landed -> -124m
> 
> **Negatives:**
> 
> * I landed on the bars consistently and the distances in general seem a LITTLE too short with flaps FULL (little too strong brakes)
> 
> **Testing Results:** Passed, because I think its close enough

@donstim Are those values consistent with those you were working with?

**Comment by donstim** [comment]
Yes, they are consistent. I will write a full explanation after I return home and can use a keyboard instead of my phone to write it.

**Comment by Benjozork** [comment]
@donstim do you think we can merge this now?

**Comment by donstim** [comment]
> @donstim do you think we can merge this now?

Give me a day to check one thing. We did not have IRL EFB landing distances for autobrake low to calibrate against. It should be good since it's just a different target decel rate and it looks pretty consistent with the autobrakes medium resukts, but I would like to have a chance to check it before the pr gets merged. (We were going to do it afterwards for possible further tuning, but since @St54Kevin provided the data...

I get home late tonight, so will try to do it early tomorrow PDT.

**Comment by St54Kevin** [comment]
The way I did measure was to land right on the markers (this was successfull at all landings) and wait until complete stop. Put up the drone and count the centerline stripes, which I identified as roughly 63m distance from stripe beginning to stripe beginning. And then just count them. Measuring error due to length of the touchdown markers should be around 20-40m

**Comment by crocket63** [comment]
Having low better in conf3 than full is surprising though as it just get to the same decel target.

**Comment by crocket63** [comment]
> What do you mean by "better?"

I meant 60T, FLAP 3, LOW, 1799m calculated, 1820m landed -> +21m looks closer than  60T, FULL, LOW, 1578m calculated, 1460m landed -> -118m.   While decel targets should be the same so don't know why there's such difference

**Comment by donstim** [comment]
All the CONF 3 distances exhibit that difference. I think it is an artifact of how the distances are calculated vs how the test was conducted.

**Comment by crocket63** [comment]
> All the CONF 3 distances exhibit that difference. I think it is an artifact of how the distances are calculated vs how the test was conducted.

True. If you think we're close enough for now let's merge :)

**Comment by St54Kevin** [comment]
Well it could as well be that Flap drag is off

**Comment by donstim** [comment]
@St54Kevin In the EFB numbers you quoted, is Vapp=VLS or maybe VLS+5?  Also, what cg, that is, is it <25% or >=25%?

**Comment by St54Kevin** [comment]
> @St54Kevin In the EFB numbers you quoted, is Vapp=VLS or maybe VLS+5? Also, what cg, that is, is it <25% or >=25%?

Vapp = Vls +5 (+wind) is what we use. And I chose >=25% because thats more common

**Comment by donstim** [comment]
> Well it could as well be that Flap drag is off

No, the toe brake scale values were based on the flight model CONF 3 drag, regardless of whether it is "right" or "wrong."

**Comment by donstim** [comment]
> > @St54Kevin In the EFB numbers you quoted, is Vapp=VLS or maybe VLS+5? Also, what cg, that is, is it <25% or >=25%?
> 
> Vapp = Vls +5 (+wind) is what we use. And I chose >=25% because thats more common

Great, thought so.

**Comment by St54Kevin** [comment]
Here is an example. Its an PW but that should be relevant:
image

**Comment by St54Kevin** [comment]
Here is an example. Its a PW but should not be relevant:
image

**Comment by donstim** [comment]
What do you mean, it's a PW?

**Comment by donstim** [comment]
The EFB landing distances contain a bit of conservatism to allow for small variations.  They are calculated values based on a standard methodology. The landing distance starts at 50 feet above the runway surface and ends when the airplane comes to a complete stop. The unfactored in-flight landing distances consist of 3 segments: (1) an air distance segment (flare distance) from 50 ft above the runway to touchdown, (2) a transition to full braking configuration segment; and (3) a full braking configuration stopping distance.  These segments are computed as follows: 
_Air distance_ is 7 seconds times the average speed during the segment. Touchdown is assumed to be 96% of the approach speed, so the average distance during the flare is assumed to be 98% of the approach speed.
_Transition distance_ Manufacturers have 2 options for computing this distance depending on whether they initiate braking after main gear touchdown or nose gear touchdown. Airbus distances are based on braking after main gear touchdown. A one second delay must be added to the time it takes for any pilot action to stop the airplane.
_Full braking configuration distance_ If the braking friction used to calculate this distance is based on a typical runway surface, including rubber contamination, that braking friction can be used without adjustment.

For calibrating/tuning the brakes, there is no effect on the air distance. Therefore, the tests used to tuned the brakes were all done on the ground with rejected takeoffs. The air distance portion of the landing distance was subtracted out. For the manual braking tests, with autospoilers armed, the airplane was accelerated to the touchdown speed, then thrust levers were put to idle, When the airplane decelerated back to the touchdown speed, a one second delay was applied (by saying one-one-thousand), and then full manual brakes were applied. The stopping distance from the touchdown speed to the point where the airplane came to a complete stop was compared to the EFT landing distance minus air distance. Distances were obtained by using the tracking debug window in MSFS developer mode.

For the autobrake tests, the airplane was accelerated to near the touchdown speed, then the thrust levers were reduced to just above idle. When the airplane decelerated to the touchdown speed, the thrust levers were brought to idle.

Specifically, the following procedure was used:
1. Start MSFS with the airplane on the specific runway for which the EFB numbers were run with the clear sky weather preset.
2. Set the airplane weight and CG position.
3. Set the wind speed to zero. (For some reason MSFS starts with 2 knots for the clear sky weather preset.)
4. Set the flaps, autospoilers, and autobrakes according to the test being run.
5. Go to external view so that you aren't distracted by any of the aural alerts.
6. In MSFS developer mode, with the aircraft editor open, select the speed and tracking debug windows.
7. Set TOGA thrust.
8. Release the brakes and start a video recording.
9. For manual braking, as the airplane accelerates through the pre-computed touchdown speed (96% of the approach speed), bring the thrust levers to idle. When the airplane decelerates to the touchdown speed, say "one-one-thousand" and then apply full brakes.
10. For autobrakes, as the airplane accelerates to the touchdown speed, bring the thrust levers to just above idle. When the airplane decelerates to the touchdown speed, bring the thrust levers to idle.
11. Read the total distance traveled from the tracking debug window. From the video, obtain the distance traveled to when the touchdown speed is reached during the deceleration from above the touchdown speed. Subtract this from the total distance traveled to obtain the stopping distance and compare this to the stopping distance (landing distance minus air distance) from the EFB.

**Comment by St54Kevin** [comment]
> What do you mean, it's a PW? Does that mean planned weight or PW engine? If PW engine, then that is relevant. The landing distance would be different if idle thrust is different (at least for max manual braking).

Yes PW Engines

**Comment by donstim** [comment]
Finished testing against the new data supplied by @St54Kevin. In my testing, all looked good, except A/B Low distances were a bit long (100-200 feet). If it uses the same ramp up as MED and the target decel rate is accurate, then I vote we go with it as is. (A/B Med distance was a little short on CONF 3, but was good for the EHAM data at 50, 55, and 66 T, so this looks like an outlier.)
Screenshot (1011)

**Comment by crocket63** [comment]
> Finished testing against the new data supplied by @St54Kevin. In my testing, all looked good, except A/B Low distances were a bit long (100-200 feet). If it uses the same ramp up as MED and the target decel rate is accurate, then I vote we go with it as is. (A/B Med distance was a little short on CONF 3, but was good for the EHAM data at 50, 55, and 66 T, so this looks like an outlier.)
> Screenshot (1011)

Med and low mode ramps are different indeed:
LOW_MODE_DECEL_PROFILE_ACCEL_MS2: [f64; 4] = [4., 4., 0., -2.];
LOW_MODE_DECEL_PROFILE_TIME_S: [f64; 4] = [0., 1.99, 2., 6.];

MED_MODE_DECEL_PROFILE_ACCEL_MS2: [f64; 5] = [4., 4., 0., -2., -3.];
MED_MODE_DECEL_PROFILE_TIME_S: [f64; 5] = [0., 1.99, 2., 2.5, 4.];

To make it clear, after 2 seconds on ground Low goes from 0 to -2m.s^2 in 4 seconds.  So ramp is pretty slow.

Med, after 2 seconds on ground goes from 0 to -2m.s^2 in half a second, then -2 to -3m.s^2 in 1.5s.  Way more aggressive.

If you feel we lack a bit of brakes, I can have the low mode ramp a tad more aggressive.

**Comment by donstim** [comment]
That would be great if you could make the low mode ramp a bit more aggressive. About the same amount of change you applied to the medium ramp relative to where it was before you made that a bit more aggressive since the stopping distance is off by about the same amount the medium setting was at one time.

**Comment by crocket63** [comment]
> That would be great if you could make the low mode ramp a bit more aggressive. About the same amount of change you applied to the medium ramp relative to where it was before you made that a bit more aggressive since the stopping distance is off by about the same amount the medium setting was at one time.

Gone from 4 seconds ramp to 2.5s in LOW.  If you can do a quick check, then we're good for the merge ( no impact on other distances with that change)

**Comment by donstim** [comment]
LGTM. Did a number of tests. Repeatability seems tougher at these low decel rates, but I'm convinced the low autobrake is now good to go. Great work!

**Pull request merged**
