### PR TITLE
feat(efb): make EFB have its own battery

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

* Add very basic battery logic to EFB

Discord username (if different from GitHub): someperson#4953

## Testing instructions

* Click on the EFB to turn it on (no need for aircraft DC or AC power)
* Observe startup sequence
* Turn off EFB by clicking on the yellow indicator on the top right
* Observe shutdown
* Observe turned off state
* Click on the EFB to turn it on
* Observe startup sequence

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by ZigTag — APPROVED** [review]
LGTM

**Comment by OverKillProductions** [comment]
Category: QA Tester/Trial
Name: Discord User #4687
Date of testing: Current date 02/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3628
Tier of testing: 1/2/3
Changes to observe:

Add very basic battery logic to EFB

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
(Testing was done after deleting A32NX from community folder and reinstalling the PR)

1. Cold and Dark state
2. Batteries off - EFB is off and no power light/button available
3. Aircraft Battery Power - ON
4. EFB turned on with AC battery power
5. Power button now visible and functional
6. Turned AC power off
7. Power button no longer visible or functional on EFB

Flight notes (When done a full flight): N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): EFB Power button was not available without the aircraft battery turned on

Overall Rating: To be improved

Conclusions of the testing: 

Basic battery function doesn't seem to be working as aircraft power is still required on my system
Batteries off
Batteries on

**Comment by boierito** [comment]
> Category: QA Tester/Trial
> Name: Discord User #4687
> Date of testing: Current date 02/02/2021
> Version of the sim: 1.12.13.0
> PR Tested: #3628
> Tier of testing: 1/2/3
> Changes to observe:
> 
> Add very basic battery logic to EFB
> 
> Testing technique: Description of how you tested the Pull Request
> Steps you've made to test the Pull Request:
> (Testing was done after deleting A32NX from community folder and reinstalling the PR)
> 
> 1. Cold and Dark state
> 2. Batteries off - EFB is off and no power light/button available
> 3. Aircraft Battery Power - ON
> 4. EFB turned on with AC battery power
> 5. Power button now visible and functional
> 6. Turned AC power off
> 7. Power button no longer visible or functional on EFB
> 
> Flight notes (When done a full flight): N/A
> 
> Media: Insert screenshots, recordings, or anything relevant to the review here.
> 
> Issues (If Any): EFB Power button was not available without the aircraft battery turned on
> 
> Overall Rating: To be improved
> 
> Conclusions of the testing:
> 
> Basic battery function doesn't seem to be working as aircraft power is still required on my system
> Batteries off
> Batteries on

The same happens to me

**Comment by Benjozork** [comment]
@boierito @OverKillProductions @ArmanKir this is RTT again

**Comment by boierito** [comment]
image
Now yes, it works as it should. Nice job!

**Comment by boierito** [comment]
One question, should there be a shutdown animation from what I understand or just go from ON to OFF instantly?

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#5297
Date of testing: Current date 2/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3296 
Tier of testing: 1
Changes to observe: Battery logic, shut off, turn on, etc.

Testing technique: Spawn and observe at gate (ENTO - Orbx)

Steps you've made to test the Pull Request:
1. Spawn into ENTO
2. Click to power on
3. Click to power off (battery icon)
4. Observe other additions


Flight notes (When done a full flight): N/A

Media: 

Microsoft Flight Simulator Screenshot 2021 02 02 - 17 21 47 02
Microsoft Flight Simulator Screenshot 2021 02 02 - 17 22 42 23


Issues (If Any): N/A

Overall Rating: Good
Conclusions of the testing: Nice PR Holand, good as always.

**Comment by Benjozork** [comment]
> 
> 
> One question, should there be a shutdown animation from what I understand or just go from ON to OFF instantly?

instantly.

**Pull request merged**
