### PR TITLE
Fix radio frequencies/squawk not being visible in default forward pedestal view

### LINKED ISSUE #717: [BUG] Dead displays on RADIO and TCAS panels (after MSFS Patch#2)
**Mod Version**

master / newest MSFS build

**Describe the bug**

Dead displays on RADIO and TCAS panels. Not showing numbers.

**To Reproduce**

1. Spawn at the gate in C&D state
2. Turn on Battery / External power switches
3. Switch to RADIO / TCAS cockpit view

**Expected behavior**

Displays should show numbers when there is electrical power on the bus.

**Actual behavior**

Just dark

**References**

No ref.

**Additional context**

Radios seems to be working but displays are dead when looking through some cockpit views.
When using free look on these views, displays turn on at some angles.
Seems to be related to some cockpit performance optimizations they did in Patch#2.
It's a ASOBO's bug - it's there even without a32nx mod being load.
Don't know if it's fixable here or should be fixed by ASOBO.

Discord username (if different from GitHub):
n/a

### PR DESCRIPTION
**Pull request by pareil6**
Fixes #717.

## Summary of Changes
Workaround for visual glitch where radio frequencies + squawk code aren't visible when using the upper pedestal camera (view 6), by raising the camera position slightly to where the glitch doesn't occur.

## Screenshots (if necessary)
Before:

After:

## References
N/A

## Additional context

Discord username (if different from GitHub): pareil6#0990

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by NathanInnes — APPROVED** [review]
Changes LGTM! Ready to test

**Comment by MisterChocker** [comment]
Also Fixes #2272

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name:ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 7.12.2020
Version of the sim: 1.11.6.0
PR Tested: #2277 
Object of test: Fix COMs and transponder Display invisible

Testing technique: Try Out
Steps you've made to test the Pull Request:
1. Loaded in C&D at LSZH
2. Started up the Aircraft
3. Turned on Comms and Transponder
4. Checked different angles

Flight notes (If required): none

Issues (If Any): Displays still go dark when in CTRL + 5 for example but work in CTRL + 6
CTRL + 5
Microsoft Flight Simulator Screenshot 2020 12 07 - 22 22 24 69
CTRL + 6
Microsoft Flight Simulator Screenshot 2020 12 07 - 22 22 52 24

Overall Rating: To be improved, i personally like to see the comms and CDU in one view when flying online
Conclusions of the testing: Fixes the issue in the default CTRL + 6 view (as described) but still has some black angles (CTRL + 5). GitHub Maintainers need to decide whether this is ok or not

**Comment by Highflyer2010** [comment]
Category: QA Tester
Name: Discord User Highflyer2010 #8932
Date of testing: Current date 08/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2277 
Object of test: radio frequencies/squawk not being visible in default forward pedestal view

Testing technique: changed my view from my current view to the CTRL+6 view 


Steps you've made to test the Pull Request:

1. C&D at EGNT
2. Setup Aircraft
3. moved camera to CTL+6
4. moved back to my default view
5.

Flight notes (If required):

Issues (If Any): 
Overall Rating:To be improved
Conclusions of the testing: Although the testing worked on this PR when changing the camera view there still went blank. 

[https://files.fm/f/gmty48wpw](url)

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#8165
Date of testing: 12/8/2020
Version of the sim: 1.11.6.0
PR Tested: #2277 
Object of test: Visibility issue of radio in pedestal view.
Testing technique: Loaded in and checked the pedestal view.

Steps you've made to test the Pull Request:

Loaded into KDTW, cold and dark.
Powered on aircraft.
Checked view 6, then checked other views as previous testers reported (view 5 in specific)

Flight notes (If required):

Issues (If Any):
Overall Rating: To be improved
Conclusions of the testing: Yes, it fixes view 6, but I think working on the other views would be best, until then I wouldn't merge.

**Comment by pareil6** [comment]
I originally didn't want to change view 5, since the camera needed to move significantly higher to avoid the glitch, but I realised earlier I could get the effective view to be the same by messing around with the zoom as well. Updated with the FMC camera (view 5) fixed to avoid the glitch (camera is higher but zoomed further in), and adjusted the forward pedestal camera (view 6) zoom to better match the view that was there before the camera was lifted.

**Comment by HugoTro** [comment]
Name: Hugo #3307
Date of testing: Current date 11/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2277 

Testing technique: Looked at
Steps you've made to test the Pull Request:
1. Spawned at KORD in C&D
2. Turned on batteries and external power
3. Looked at all the views with SHIFT+[number]
4. All the views were showing the radios **except SHIFT+4**

Overall Rating:                    Good but ↓
Conclusions of the testing: If shift+4 view is fixed, then it will be perfect to merge

**Comment by pareil6** [comment]
Do you have a screenshot of what view 4 is for you? It's the ECAM view for me which doesn't have the radio stack visible, but even zoomed out far enough, the displays render properly on my end...

**Comment by HugoTro** [comment]
If you move the camera you can see the radio screens off, sorry I can't send a screenshot rn

**Comment by pareil6** [comment]
> If you move the camera you can see the radio screens off, sorry I can't send a screenshot rn

Ah, I see what you mean now - will fix that shortly, thanks!

**Comment by pareil6** [comment]
Actually, view 4 doesn't look right to me now, will have another look.

**Comment by pareil6** [comment]
Better positioning for the ECAM view, and also tweaked the MFD view slightly to match it (so transitions between the two don't have a pull in with a zoom out, which felt a bit jarring).

**Comment by HugoTro** [comment]
Name: Hugo #3307
Date of testing: Current date 14/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2277 

Testing technique: Looked at
Steps you've made to test the Pull Request:
1. Spawned in C&D at LFMN gate 37
2. Turned on batteries and external power 
3. Looked at all the views with SHIFT+[number]
4. All the views were showing the radios without exception this time

Overall Rating: Good
Conclusions of the testing: Seems ready to merge

**Pull request merged**
