### PR TITLE
Fix #860 ND Sizes

### LINKED ISSUE #860: [BUG] ILS Title on ND Incorrect
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the feature you'd like to see implemented**

The APP type annunciator on ND should be in green.

330D73A2-1E5D-40B2-8751-41A6A3879F03

**References**

76C4C9C6-293B-4A6F-8A7E-434B9C356CDB

**Additional context**

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by NathanInnes**
Fixes #860

**Summary of Changes**

Change ND sizes

- Speed & Wind text size.
- Waypoint info size.
- Compass size.
- ILS Title colour.
- VOR/ADF size and position

**Screenshots (if necessary)**

### Before 
image
### After
image
**Additional context**

Discord username (if different from GitHub): Sabes#8668

### CODE REVIEW

**Comment by Benjozork** [comment]
Hello, please take note that we have started including a CHANGELOG.md file that requires every PR to add a change-log line that describes its changes. As your PR is not merged yet, we kindly ask that you add this information following the included directives in the file.

Disclaimer: This is a copy-and-pasted message.

**Comment by AdenFlorian** [comment]
please make your before and after screenshots have the same context/settings so we can more easily tell what changed, and provide a reference pic

**Comment by NathanInnes** [comment]
Before: 
image
*Everything on there is smaller and positions of ADF/VOR on bottom is incorrect*

After:
image
*Everything has been scaled up and matches closer to REF image.*

Ref Image:
image

**Comment by NathanInnes** [comment]
Awaiting #885 to be merged first so I can work on fixes for positions.

**Review by AdenFlorian — APPROVED** [review]
code looks good

**Comment by NathanInnes** [comment]
Now compatible.

**Comment by camilo625** [comment]
Name: Camilo625 #5575
Date of testing: Current date 30/09/2020
Version of the sim: 1.9.3.0
PR Tested: #910 

Testing technique: Spawn and do a short flight, test ND both on land and on flight.
Steps you've made to test the Pull Request:
1. Spawn on gate
2. Initialize airplane systems
3. Check ND working on land
4. Takeoff
5. Check ND working on the air

Overall Rating: Good
Conclusions of the testing: Seems to work perfectly

**Comment by tareksabet** [comment]
everything works fine despite the appr type above it should say i,e ILS04L not ILS RW04L

**Comment by AdenFlorian** [comment]
> everything works fine despite the appr type above it should say i,e ILS04L not ILS RW04L

i believe thats a separate issue

**Pull request merged**
