### PR TITLE
feat: improvements for FBW, AP and ATHR

### PR DESCRIPTION
**Pull request by aguther**
## Summary of Changes
This PR introduces several improvements for the FBW, AP and ATHR:
- changed ALT condition time to 0.8 s
- changed ALT condition to delta height of 40 ft
- added ALT* inhibit delay of 3 s after changing the FCU altitude
- reworked the conditions to arm ALT
- increased pitch rate of C* law, recommended sensivity is now +/- 30%
- separated nz limit for vertical guidance per law
- improved HDG and TRK law Phi limit for small Psi changes
- improved thrust limits
- FLX thrust is now limiting CLB on entry, transition to default CLB
  thrust is now with a delay of 10 s and a transition time of 30 s
- reduced speed of LOC ALIGN during Autoland
- reduced gain of ROLL OUT law
- improved thrust transition for (OP) CLB/DES
- when MCT is higher than TOGA on higher altitudes, use MCT as limit
- improved normal law flight path stability when speed is
  increased or decreased
- improved SPD/MACH law in edge cases and transitions
  (i.e. manual thrust)
- improved accuracy to achieve N1 target (N1 control base loop)
- improved SRS engagement condition
- do not disengage SRS/RWY when thrust levers are set to IDLE for RTO
- use different Nz target when V/S push to level off (0.1 g instead of 0.05 g)

## Additional context
The recommended sensitivity for the pitch axis is now +/- 30% and no longer linear. This reflects better the increased force that is needed when holding the real sidestick aft for full forward.

## Testing instructions
<to be detailed>

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by IbrahimK42 — APPROVED** [review]
The changes of this PR are since a week part of the experimental version. Up to now, no issues were reported. I have also done several flights in clear weather and turbulent weather condition and could not identify any issue. Overall, the changes significantly improve the AP, FBW, and ATHR .

**Comment by aguther** [comment]
One thing we should organize before merging: make support aware and update docs due to the changed sensitivity in pitch.

**Comment by frankkopp** [comment]
> One thing we should organize before merging: make support aware and update docs due to the changed sensitivity in pitch.
> 
> @frankkopp

So -30% as for the roll now, right?

**Comment by aguther** [comment]
> > One thing we should organize before merging: make support aware and update docs due to the changed sensitivity in pitch.
> > @frankkopp
> 
> So -30% as for the roll now, right?

No +/- 30% for the pitch axis. Roll is unchanged.

**Comment by frankkopp** [comment]
> > > One thing we should organize before merging: make support aware and update docs due to the changed sensitivity in pitch.
> 
> > > @frankkopp
> 
> > 
> 
> > So -30% as for the roll now, right?
> 
> 
> 
> No +/- 30% for the pitch axis. Roll is unchanged.

Saw that now, that's why I deleted the comment. 

Best place for this is probably the Custom AP page, right?

**Comment by donstim** [comment]
- when MCT is higher than TOGA on higher altitudes, use MCT as limit

This should not actually happen. TOGA is only specifically defined for lower altitudes to support the takeoff operating envelope. At higher altitudes, it just "blends into" MCT.

**Comment by donstim** [comment]
It looks like the thrust tables are missing the additional data from the 2nd page of each table?

**Comment by aguther** [comment]
@donstim Good spot, I indeed missed it for CLB and MCT. Will add it and also improve the extrapolation. Keep in mind that completely reworked limits are also in the works by @Taz5150.

**Comment by Taz5150** [comment]
> It looks like the thrust tables are missing the additional data from the 2nd page of each table in the FCOM?

Good call! I will include them right away!

**Comment by DanielSimon** [comment]
I’d like to comment on #6546 as well as I’d have been involved in data acquisition. I have finished my testing by now and must say the impressions we got from the FFS session have been replicated quite precisely. I am particularly happy with the modified C* law behavior on the pitch axis during different IAS, which I already expressed in the pilot-feedback thread regarding flare-law behavior. Roll and Yaw authority turned out to be spot on already and without the need for adjustments. I am particularly surprised that even the pitch up moment from 10-18 degrees during takeoff rotation now occurs just like on the real thing requiring you to ease you back stick to keep SRS pitch. I kept my stick sensitivity on linear though as sidestick deflection has a greater priority for me than spring force. All in all it seems like a further improvement of realism to me.

**Comment by go2theG** [comment]
There are contrary instructions regarding the sensitivity settings on this page: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/#steam-version

Unter section "Custom Autopilot and Autothrust System incl. new Engine model" it still says "It is recommended that the sidestick uses a linear sensitivity with only dead zone set appropriately."

This should be changed or completly removed as it does not fit with the new recommendation of +/-30%.

**Comment by frankkopp** [comment]
> There are contrary instructions regarding the sensitivity settings on this page: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/#steam-version
> 
> Unter section "Custom Autopilot and Autothrust System incl. new Engine model" it still says "It is recommended that the sidestick uses a linear sensitivity with only dead zone set appropriately."
> 
> This should be changed or completly removed as it does not fit with the new recommendation of +/-30%.

Fixed - an issue on the docs github issue list would have been better. Thanks.

**Pull request merged**
