### PR TITLE
Add altitude alert

### LINKED ISSUE #1227: [BUG] altitude alert
**Mod Version**
0.3.1.

**Describe the bug**

If you are reaching or leaving your preselect or managed altitude there should be an alert sound.

**To Reproduce**

1.set altitude
2.climb
3.reach altitude

**Expected behavior**

**Actual behavior**

**References**

- (redacted by admin)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by Kimbyeoungjang**
Fixes #1227

## Summary of Changes

add altitude alert when reach altitude

## References

image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Kimbyeoungjang** [comment]
@hotshotp can i ask about sound
A32NX have a altitude alert sound? or will merged to sound file?

**Comment by Benjozork** [comment]
Hello, thanks for your PR.

while it's still draft, can you make it use `A32NX_SoundManager` in `A32NX/html_ui/Pages/A32NX_Core` ?

**Comment by lukecologne** [comment]
No, I don't think so. I made that specifically for synthetic voice callouts, so that they overlap each other. I don't think it's necessary for this alert to be handled by it, coherent.call should be fine.

**Comment by ilyeshammadi** [comment]
@Kimbyeoungjang I'm glad that you're following up on this feature that I added. I thought I give some indications on where to trigger the calls for the warnings. First of all, do not use `===` operator for the altitude because the sim will not give you that value sometimes, and you can miss it and jump over it and not have your warning triggered. Maybe an example will make it clear: When you're expecting a 750 the sim can give you 749 and the next value is 751 which means your code won't work.

As you can see in the code I'm using ranges with a combination of flags to trigger the Yellow/Amber situation. All you need to do is to place your warning in the following functions: `_pulseYellow` and `_flashAmber`.
Here a generic solution that you can start with:
```javascript
 _pulseYellow() {
        this.cursorSVGShape.classList.add("pulse-yellow");
        // Stop Amber warning first
        // Trigger yellow warning (1.5) cchordshort
        // Should be triggered if AP is disabled
 }
 _flashAmber() {
        this.cursorSVGShape.classList.add("flash-amber");
        // Stop Yellow warning first
        // Trigger yellow Amber cchordloop
 }

// ....
   
_updateAltitudeAlert(indicatedAltitude) {
    // ....
    // Exit when selected altitude is being changed
    if (this.previousTargetAltitude !== targetAltitude) {
         this.previousTargetAltitude = targetAltitude;
         this._wasBellowThreshold = false;
         this._wasAboveThreshold = false;
         this._wasInRange = false;
         // Stop Yellow warning
         // Stop Amber warning
         return;
     }
   // ....
}

```

Let me know if you need more help with this.

**Pull request closed without merging**
