### PR TITLE
feat(efb): EFB Landing Performance ⚡

### PR DESCRIPTION
**Pull request by matt-winfield**
## Summary of Changes
Adds a landing performance page to the Performance section of the EFB. Previously raised in a PR with takeoff performance, but TO perf needed more work so merging seperately to keep the level of changes that needs reviewing small.

## Screenshots (if necessary)
image
image
image
image
image

## References
Quick Reference Handbook, In-Flight Performance, Landing Distance Without Failure (Applicable to: D-AVVI, D-AXAJ, F-WWTQ, PR-OBJ)
image
image
image

15% safety margin is determined from the recommended safety margin in the QRH:
image

## Additional context
Discord username: TheMightyMat#0585

## Testing instructions
* Ensure landing distances vary as expected with changes in input values.
* Ensure landing distances on runway visualisation match output data
* Ensure distances that are longer than LDA are highlighted in red
* Test for display issues for extreme values and realistic values
* Ensure inputs are limited to sensible values

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by donstim** [comment]
Thank you for splitting this out so we don't have to wait for the takeoff analysis portion, which will take a little longer. I have encountered a couple of minor issues and have a suggestions regarding units:

1. Is it only available in metric units?  Can it be synced with whatever units the user has chosen in the MCDU?
2. What is the input format for the wind information? When I try to input 050/05, it changed it to 50.
3. If the landing distance for 2 of the 3 options are close together (like Max Manual and Medium, the distance identifier labels don't show up:  
Screenshot (662)

At this point, I only checked one simple case, and the numbers for that looked good!

**Comment by matt-winfield** [comment]
>     2\. What is the input format for the wind information? When I try to input 050/05, it changed it to 50.

Thanks for spotting this, fixed. I've also split up the wind inputs into 2 (for direction and magnitude separately) since that's probably more intuitive and easier to enter than the dir/mag format in a single input.


>     1. Is it only available in metric units?  Can it be synced with whatever units the user has chosen in the MCDU?

I haven't looked much into this, but would it make sense to do this as part of the auto-fill feature, since presumably this will be obtained from a SimVar or local storage so is somewhat related to that change?



>     3\. If the landing distance for 2 of the 3 options are close together (like Max Manual and Medium, the distance identifier labels don't show up:

I did this because I thought it looked better than the labels overlapping each other/the lines, in which case you wouldn't be able to read it easily anyway. The distances are still available in the main output so I didn't think this would be an issue.

**Comment by donstim** [comment]
> > ```
> > 1. Is it only available in metric units?  Can it be synced with whatever units the user has chosen in the MCDU?
> > ```
> 
> I haven't looked much into this, but would it make sense to do this as part of the auto-fill feature, since presumably this will be obtained from a SimVar or local storage so is somewhat related to that change?

Does this PR help in showing how it might be done? https://discord.com/channels/772995770630406164/773650520098734091/812061302813753398
> 
> > ```
> > 3\. If the landing distance for 2 of the 3 options are close together (like Max Manual and Medium, the distance identifier labels don't show up:
> > ```
> 
> I did this because I thought it looked better than the labels overlapping each other/the lines, in which case you wouldn't be able to read it easily anyway. The distances are still available in the main output so I didn't think this would be an issue.

Okay. I didn't know if you did this intentionally. I think it would be better if you could find a way to move the identifiers above and below the respective distance lines, but I don't know how difficult that might be. But what you have is ok.

**Comment by matt-winfield** [comment]
> Does this PR help in showing how it might be done? https://discord.com/channels/772995770630406164/773650520098734091/812061302813753398

I don't have permission to view that link (seems to be a restricted channel on discord). Please could you post the github link directly? (Or if there's important context in the Discord message copy/paste the whole message)

**Comment by donstim** [comment]
> > Does this PR help in showing how it might be done? https://discord.com/channels/772995770630406164/773650520098734091/812061302813753398
> 
> I don't have permission to view that link (seems to be a restricted channel on discord). Please could you post the github link directly? (Or if there's important context in the Discord message copy/paste the whole message)

Oops, wrong link! 
https://github.com/flybywiresim/a32nx/pull/3545
It looks like you might have some input trapping in there, but I was able to enter alphabetical characters in each input field (accidentally of course), and it didn't alert me or cause any error messages. I was also able to put in a 40,000 meter LDA, and it looks like the min wt is a measly 1000 kg, etc.

**Comment by matt-winfield** [comment]
> Could you edit your response to remove the Discord link?

Done!

> It looks like you might have some input trapping in there, but I was able to enter alphabetical characters in each input field (accidentally of course), and it didn't alert me or cause any error messages. I was also able to put in a 40,000 meter LDA, and it looks like the min wt is a measly 1000 kg, etc.

I'll prevent non-numbers being entered. I chose 1000kg as the minimum simply because that prevents any confusion between KGs and tons, but I'll update this to 44000KG to reflect the empty weight. Perhaps could set max LDA to 6000m (Longest runway in the world is apparently ~5000m so add a bit in case someone builds a bigger one!) which would prevent someone putting in an extra zero by accident.

**Comment by donstim** [comment]
Empty weight is 41,005 kg (though that isn't a weight that would be possible for landing:-))

Might want to cap the max weight at max ramp weight of 79.400 kg with a possible message (if you can do it) to apply the overweight landing procedure for weights above the max landing weight of 67,400 kg (or just automatically apply it).

Max landing pressure altitude is 9,200 feet, and minimum is -2,000 feet. Min temperatures are -40 C at -2,000 feet varying linearly to -47 C at 9,200 feet. Max Max temps are 55 C at -2,000 feet varying linearly to 38 C at 9,200 feet. Min/max runway slopes are ±2%. Allowable Vapp speeds that can be entered in the MCDU are 90-350 KCAS (though I think anything above the max flap speeds (VFE) of 177 KCAS (CONF FULL) and 185 (CONF 3) and below VLS should be out of range here.

**Comment by oliverpope03** [comment]
After seeing the new TOD page, i was thinking would it be possible to have a sync option for the weight of the aircraft, which updated as fuel was used (like how the TOD page changed for synced airspeed as it decrease), Also syncing downloaded metar data for the arrival airport with a button too, i dont know if this was already suggested but might be quite usefull if possible

**Comment by matt-winfield** [comment]
I've merged in master to fix conflicts with the TOD changes, and updated to re-use the Card component that was added there. I've also added auto-fill functionality for the weather and aircraft weight fields.

**Comment by donstim** [comment]
FYI - Did a few landings just to see how our airplane's performance compares to the calculated numbers.  Currently, it looks like we're a bit short on performance, that is, the landing distances I achieved were longer than the calculated distances. Hopefully, we'll be able to fix that with the coming updates to the flight and engine models. The one thing we can't do anything about yet is braking friction.

Is it possible to enable a virtual keyboard into the EFB such that when you are making inputs to it that the sim doesn't take those keystrokes as commands? I would hate to have to unbind all my keyboard commands in order to make EFB inputs without potentially also making an unintentional MSFS command.

**Comment by Snapmatics** [comment]
> Is it possible to enable a virtual keyboard into the EFB such that when you are making inputs to it that the sim doesn't take those keystrokes as commands? I would hate to have to unbind all my keyboard commands in order to make EFB inputs without potentially also making an unintentional MSFS command.

That has been discussed, most likely yes.

**Comment by matt-winfield** [comment]
> Is it possible to enable a virtual keyboard into the EFB such that when you are making inputs to it that the sim doesn't take those keystrokes as commands? I would hate to have to unbind all my keyboard commands in order to make EFB inputs without potentially also making an unintentional MSFS command.

I believe someone else is working on this already!

**Comment by ZigTag** [comment]
> 
> 
> FYI - Did a few landings just to see how our airplane's performance compares to the calculated numbers. Currently, it looks like we're a bit short on performance, that is, the landing distances I achieved were longer than the calculated distances. Hopefully, we'll be able to fix that with the coming updates to the flight and engine models. The one thing we can't do anything about yet is braking friction.
> 
> Is it possible to enable a virtual keyboard into the EFB such that when you are making inputs to it that the sim doesn't take those keystrokes as commands? I would hate to have to unbind all my keyboard commands in order to make EFB inputs without potentially also making an unintentional MSFS command.

A temporary solution is to pop out the window with right alt + click, it stops inputting to the game and only to the panel

**Comment by omarsmak** [comment]
Will this PR be merged soon or it still needs some work ?

**Comment by marcman86** [comment]
There is no code review or a single QA test done so it needs some time.

**Comment by donstim** [comment]
A few comments:
1. I don't know if it's just me and my computer, but I'm having trouble with the popout window option. It won't allow me to place my cursor into any of the entry fields, so I can't make any inputs.
2. The Auto-fill button only works if an airport has been entered, but it doesn't autofill any airport data. I realize that implementation of getting the airport data is in work, but until then maybe allow autofill of the other data without putting an airport code in? A pilot can enter the airport info without inputting the code, right? For autofill. can you get the approach speed from the MCDU?
3. The word "ICAO" by itself for the airport code may confuse people. If there's room, maybe add something like "ICAO Airport Code?"
4. Shouldn't the wind direction value retain 3 digits even if the first one or two digits are zero?
5. For auto-fill of QNH, can the number be rounded off to say 2 digits after the decimal point?
6. The calculate button will only function if the necessary information is input. Otherwise, it normally just doesn't do anything. Can you have it go from a darker shade to a brighter shade when it is actionable? Should a calculation be possible at all without filling in all entry boxes (for example, see 8 below)?
7. Can you add a clear button?
8. After I manually cleared all the inputs, it would still calculate numbers and display them on a runway diagram that says "0m" for it's length, but the length displayed is obviously not zero. What are these numbers based on? Shouldn't they be reset to "no entry" and shouldn't the calculate button go back to being unactionable?

**Comment by MisterChocker** [comment]
What is the status of the pr?

**Comment by Snapmatics** [comment]
@matt-winfield Any status?

**Comment by matt-winfield** [comment]
> 
> 
> @matt-winfield Any status?

@myselfaaryan has kindly offered on Discord to pick up the outstanding work on this, unfortunately I've been a bit too busy recently to complete it myself

**Comment by Snapmatics** [comment]
> > @matt-winfield Any status?
> 
> @myselfaaryan has kindly offered on Discord to pick up the outstanding work on this, unfortunately I've been a bit too busy recently to complete it myself

I think he will be able to pick it up if the values are correct.
image

**Comment by matt-winfield** [comment]
> 
> 
> > > @matt-winfield Any status?
> > 
> > 
> > @myselfaaryan has kindly offered on Discord to pick up the outstanding work on this, unfortunately I've been a bit too busy recently to complete it myself
> 
> I think he will be able to pick it up if the values are correct.
> image

All of the relevant data for calculating landing performance from the QRH is there so should be good to go. As far as I'm aware the only changes that are still needed are the ones mentioned in @donstim 's last comment, i.e.


> * The Auto-fill button only works if an airport has been entered, but it doesn't autofill any airport data. I realize that implementation of getting the airport data is in work, but until then maybe allow autofill of the other data without putting an airport code in? A pilot can enter the airport info without inputting the code, right? For autofill. can you get the approach speed from the MCDU?
> 
> * The word "ICAO" by itself for the airport code may confuse people. If there's room, maybe add something like "ICAO Airport Code?"
> 
> * Shouldn't the wind direction value retain 3 digits even if the first one or two digits are zero?
> 
> * For auto-fill of QNH, can the number be rounded off to say 2 digits after the decimal point?
> 
> * The calculate button will only function if the necessary information is input. Otherwise, it normally just doesn't do anything. Can you have it go from a darker shade to a brighter shade when it is actionable? Should a calculation be possible at all without filling in all entry boxes (for example, see 8 below)?
> 
> * Can you add a clear button?
> 
> * After I manually cleared all the inputs, it would still calculate numbers and display them on a runway diagram that says "0m" for it's length, but the length displayed is obviously not zero. What are these numbers based on? Shouldn't they be reset to "no entry" and shouldn't the calculate button go back to being unactionable?

**Comment by myselfaaryan** [comment]
It would be better to finish this with flyPadOS v2. Hence, changed the base.

**Comment by matt-winfield** [comment]
I've pushed changes to fix most of the remaining suggestions that have been made. As far as I can tell there are 2 things that remain:

- Auto-fill approach speed from MCDU
- Auto-fill airport data (runway LDA, heading, slope)

I think it would be best to do these features as part of a separate PR, as they will likely be quite big and this PR is already large and has been open for quite a while. Since these suggestions aren't required for the calculator to work I think reviewing them separately will be best.

**Comment by hiaaryan** [comment]
@matt-winfield hi, can you resolve the conflicts so I can take a look :D thanks!

**Comment by matt-winfield** [comment]
@hiaaryan Conflicts fixed, ready for review

**Review by hiaaryan — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
