### PR TITLE
[CDU] General Bugfixes to INIT and FUEL PRED pages

### LINKED ISSUE #2296: [BUG] FORMAT ERROR catching trying to fill ZFW/ZFWCG
Dev. ver.

Describing the bug:
Catching the "FORMAT ERROR" message trying to fill the ZFW/ZFWCG at the FUEL PRED section of the MCDU in all possible formats. 

To Reproduce:
1. During preparing for departure go in the FUEL PRED section of the MCDU.
2.  Fill the ZFW/ZFWCG values.
3. Click the button near the ZFW/ZFWCG.

Expected behavior:
The ZFW/ZFWCG values become entered.

Actual behavior:
Catching the "FORMAT ERROR" message.

Is this a problem in the vanilla unmodded game? - No.

### PR DESCRIPTION
**Pull request by Lucky38i**
Fixes #2296

- [ ] Fix inability to enter ZFW/ZFWCG on FUEL PRED page
- [x] Output correct error message for ZFW/ZFWCG, Alternate, Final, Block, Cost Index and Taxi fuel
- [x] Prevent init B prediction for malformed INIT A data
>  Now shows dashed results
- [x] Add GND Temp (inop) on INIT A
- [x] Add EFOB BELOW MIN FOB Type II Message
- [x] Rename Wind to Wind/Temp on INIT A
- [x] Add auto-calc QOL feature to FUEL PRED for ZFW/ZFWCG
- [x] Refactor trySetAverageWind, it's honestly just a repetitious disaster
- [x] Predictions won't calculate unless, **BOTH** `altToUse` and `airDistance` are within range, previously it was either or
>  This should prevent users from making predictions that outside of the bounds the coeffecients are built for. This is an inherent issue with the MCDU predictions as it's limited to the performance data available.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
>  Fix inability to enter ZFW/ZFWCG on FUEL PRED page

Is this going to be worked on ? I see you marked the PR as ready for review.

**Comment by Lucky38i** [comment]
> > Fix inability to enter ZFW/ZFWCG on FUEL PRED page
> 
> Is this going to be worked on ? I see you marked the PR as ready for review.

It should be working, I just can't test my changes on the sim until this weekend, so in the mean time QA testers should be able to ensure it's working.

**Comment by tareksabet** [comment]
@Lucky38i can you link to issue #2296 thank you .

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by InhumanReactions** [comment]
Category: QA Tester
Name: InhumanReactions#0001
Date of testing: Current date 11/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2251
Object of test: Init pages and Fuel Prediction pages bug fixes and new messages.

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned in C&D at EGCC.
2. Loaded in the fuel prediction on the Init B page. Checked Init A to see if Ground Temp was present, (which it was).
3. Took off from EGCC.
4. Checked the EFOB for the end of the flight.
5. Landed at LGSK.

Flight notes (If required):Estimated EFOB is below minimum showed up. At first the prediction was innaccurate, but it got more accurate as the flight progressed.

Issues (If Any): At takeoff, the checklist did not appear up on the Upper ECAM. Not sure if this is related to the mod or if this is just a general bug.
Overall Rating: Good
Conclusions of the testing: This PR worked as intended and the fuel prediction it gave me at EGCC was accurate and left me with a suitable amount of fuel at shutdown. Great PR. Also I may not have tested some of the bug fix related features, but in the flight I didn't encounter any bugs so all looks good for this. It may be worth getting some more QA testers to take a look so every aspect of this PR is tested.

**Comment by AdmiralArtemiy** [comment]
What about the first line "Fix inability to enter ZFW/ZFWCG on FUEL PRED page"?

**Comment by Benjozork** [comment]
> What about the first line "Fix inability to enter ZFW/ZFWCG on FUEL PRED page"?

Read the previous comments.

**Pull request merged**
