### PR TITLE
Added "Align IRS" message to MCDU for quick IRS alignment

### PR DESCRIPTION
**Pull request by Externoak**
Issue: https://github.com/flybywiresim/a32nx/issues/610

**Summary of Changes**
Added a Align IRS option inside MCDU to quickly align IRS.
Option will only appear if IRS is actively aligning or isn't already aligned.
Also will clear ECAM IRS align message.

**Screenshots (if necessary)**
image

**Additional context**

### CODE REVIEW

**Comment by Benjozork** [comment]
Hmm. I think we should discusss whether we want that feature or not in the first place.

**Comment by oliverpope03** [comment]
> Hmm. I think we should discusss whether we want that feature or not in the first place.

I agree also i recommend if it is wanted that it is "ALIGN IRS>" like the wind below it to show the button is to activate it

**Comment by Externoak** [comment]
I agree as mentioned in https://github.com/flybywiresim/a32nx/issues/610 it is a QoL improvement. 
Also as said in https://github.com/flybywiresim/a32nx/issues/398 most payware level aircraft have a way to quickly align the IRS, if this method is to be used or another one is to be discussed.

**Comment by Externoak** [comment]
Now shown as:

image

**Comment by Benjozork** [comment]
> I agree as mentioned in #610 it is a QoL improvement.

What I mean is that those discussions need to take place in the community in a broader sense, because some people wanted this as a function of the EFB.

**Comment by wpine215** [comment]
The ToLiss A319/A321 features something similar. However, with a key difference. Instead of the "ALIGN IRS>" button instantly completing the alignment like the current behaviour of this PR, it could instead act as a prerequisite for the completion of alignment - the departure ICAO must be entered and the "ALIGN IRS>" button must be pressed during alignment, or else it won't complete. It should not instantly complete alignment or clear any relevant ECAM memos.

**Comment by Externoak** [comment]
@wpine215 
Should have this "ALIGN IRS>" button pressed during alignment like so [reference](https://youtu.be/uqKeSO6msDk?t=576) or as linked in https://github.com/flybywiresim/a32nx/issues/610#issuecomment-691621359 [reference](https://www.youtube.com/watch?v=o3--ALDKLUc&feature=youtu.be) as a "IRS INIT" page?

**Comment by Meqolo** [comment]
I think it would be best if you had it say "QUICK IRS ALIGN" or something of the sort, as its currently quite vague

**Comment by AdenFlorian** [comment]
I think any QoL features should be on a hidden MCDU page that you wouldn't be able to get to without knowing how.

**Comment by AdenFlorian** [comment]
Closing this as we originally decided to wait for an EFB before adding cheats. We can add them to the MCDU, but it should be in a way where players won't stumble upon it. Let's continue discussion in #398

**Pull request closed without merging**
