### PR TITLE
fix(engine): fuel flow and fuel consumption model

### LINKED ISSUE #4656: No Fuel Flow for #2 Engine
**Aircraft Version**

```json

  "built": "2021-04-30T08:56:44+00:00",
  "ref": "master",
  "sha": "e8a67944e800ea8910fee003ba06f7da39ff268b",
  "actor": "davidwalschots",
  "event_name": "manual"


```

**Describe the bug**

After landing , shutdown and taxi with engine #2 there was o fuel flow for that engine

**To Reproduce**

1.Land the aircraft
2.Shutown Engine#1
3.Observer fuel flow for engine 2

**Expected behavior**

Running engine should display the fuel flow

**Actual behavior**

running engine was displaying zero flow 

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by Taz5150**
Fixes #4656

## Summary of Changes

Fixed a couple of issues with fuel flow and fuel consumption model.
- Fuel flow: instead of staying at 0 at idle after start-up (does not happen on runway), it now ramps up from 0 to its idle figure
- Fuel consumption: fixed the infinite fuel issue and random fuel increases/ rebounds

Disclaimer: 
Fuel flow is ramping now during start-up but not as in real life (work in progress). 
Regarding fuel consumption, please disregard fuel feeding between tanks as this is being worked on by the team. Also, there are reports concerning auxiliary tanks not filling inner tanks when start fuel is below sensor threshold. This only happens when starting on runway (does not happen if starting C&D). This issue will also have to be taken care of with the new fuel model being designed. 

## Additional context

Discord username (if different from GitHub): TazX [Z+2]#0405

## Testing instructions

1. For fuel flow:
- Start C&D
- Proceed to Engine Start
- Watch engine spool up to idle and check fuel flow starts at 0 and increments up to around 300 Kg/h (700 lbs/h)

2. For fuel consumption:
- During flight and/ or on runway:
    - Check fuel burn corresponds to fuel flow figures
    - Check when tanks are empty, fuel is 0 and engines turn off

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by ElonKerman — APPROVED** [review]
Looks good

**Review by aguther — APPROVED** [review]
I did a first rough test and it seems to work. Both spawning on runway and C&D worked for me.

One observation:
When tanks were almost empty, the right tank was shifting between 0 and 20 kg, but as stated this might be part of the rework of the fuel system.

**Comment by donstim** [comment]
For the comment lines regarding the actual fuel tank total and unusable quantities, I meant for you to use those from the PR https://github.com/flybywiresim/a32nx/pull/4391. They were updated, more accurate values. Left and right main tanks are Total: 1823.75, Unusable: 7.75. Center Total: 2185.1, Unusable: 6.1, Left and right Aux Total: 228, Unusable: 0.

Would also like to reinstate the other files in that PR that were removed by the reversion, but I guess I can do that with another PR once this one is merged.

**Comment by Taz5150** [comment]
> For the comment lines regarding the actual fuel tank total and unusable quantities, I meant for you to use those from the PR #4391. They were updated, more accurate values. Left and right main tanks are Total: 1823.75, Unusable: 7.75. Center Total: 2185.1, Unusable: 6.1, Left and right Aux Total: 228, Unusable: 0.
> 
> Would also like to reinstate the other files in that PR that were removed by the reversion, but I guess I can do that with another PR once this one is merged.

Ok, I didn’t get you the first time. But since I will probably make some slight changes to this PR, I will change the usable fuel to accurate values and the comment line on unusable fuel as well. Thanks Don!

**Comment by Taz5150** [comment]
Updated the PR to take into account:

1. Comment in the flight_model.cfg with correct Total and Unusable fuel quantities to be taken into account in the future
2. Fuel bouncing issue when quantity reaches 0 (fixed)

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 2.05.2021
Version of the sim: 1.15.8.0
PR Tested: #4658
Tier of testing: 1
Changes to observe: Fuel flow on start up
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power:
3.) Start APU
4.) Start engine 1
- FF goes up in 20kg/h steps to 240kg/h

5.) Start engine 2
- FF goes up in 20kg/h steps to 260kg/h

6.) Turn off engines
- FF goes down in 20kg/h steps to 0kg/h

7.) Start engine 1+2
8.) Turn fuel to 0
- Engine 1 ramps down
- Engine 2 stays on till electric power turns off
- EGT stays at about 400°C

9.) Restart the flight
- EGT starts at about 390°C (?)


Question to the experts: 
- EGT starts at about 390°C (engines off). Fuel starts when EGT is at about 450°C. Where does the temperature comes from?
- On engine shutdown: Should fuel turn of instant to 0kg/h?

Issues: 
- On 0 fuel engine 2 stays on till electric power turns off.

Issues (not of this PR): 
- N2 value background changes on startup
- EGT high even with engines off

Overall Rating: -

Conclusions of the testing: Needs correction for engine 2 ramp down

Hope this helps :-)

**Comment by Taz5150** [comment]
@marcman86 Thank you for the test and feedback! Some answers to your findings:

1. Disregard EGT when engine is off (or during start-up); its been worked on for the start-up procedure. For a cold start, EGT should be close to ambient temperature, ramp-up during start above idle conditions (overshoot) and stabilize at around 520 Celsius at Idle.

2. Shutdown procedure will follow start-up, so parameters will be wrong. Nevertheless, it is a very good question that will need an answer when we get there.

Regarding the issues:

- I suspect these issues might be present on the vanilla version of the aircraft. Still I will test myself with the original Asobo to see if the PR introduced these issues.

Once again, thank you for the test and feedback 👍🏻

**Comment by Taz5150** [comment]
Just tested both issues on on the FBW and vanilla version of the aircraft:

1. I was not able to reproduce the issue where at 0 fuel, engine 2 stays on (neither on vanilla nor FBW with this PR). The only issue I found on vanilla was the fuel rebound due to the unusable fuel issue.

2. You are correct on the second issue, but it happens on Vanilla version as well!!! (did not test this event in the past). As far as I've tested, this happens not only when fuel goes to 0 and then manually increasing again. If you turn off the engines and then try to turn them on, N2 goes up to 25% and stays there: same in FBW and Vanilla. 

Please, if possible lets re-test the first issue since I was not able to reproduce it. Also, although not a direct issue due to this PR, I will investigate and try to solve the 25% N2 problem.

Thanks!

**Comment by aguther** [comment]
Now that it‘s clear that it‘s also an issue in the vanilla plane, I think we should merge this PR to make the improvements that it includes accessible to everyone. The other issues as the start-up and shutdown procedure should be worked on with new PRs.

**Comment by marcman86** [comment]
1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power:
3.) Start APU
4.) Start engine 1+2
5.) Set fuel to 0

Engine 2 is not ramping down

**Comment by aguther** [comment]
> 1.) Spawned C&D at EDDP
> 2.) Turned on bat. and ext. power:
> 3.) Start APU
> 4.) Start engine 1+2
> 5.) (ext. power and APU still on) Set fuel to 0
> 
> Engine 2 is not ramping down
> 
> 

Can you please retest if it also happens to you if you keep a quite small amount in the tanks and then let it run out of fuel?

**Comment by marcman86** [comment]
> Can you please retest if it also happens to you if you keep a quite small amount in the tanks and then let it run out of fuel?

This works :-)

**Comment by Taz5150** [comment]
Thanks @marcman86. Asobo's Fuel model and UI seems to be somewhat erratic. We've seen similar issues of fuel sensors not being triggered under certain conditions. This looks like something similar: when you let it run to 0, engine seems to behave as it should. But when you force it through the UI, something is not triggered.

Will have to investigate in the future.

**Pull request merged**
