### PR TITLE
feat: APU heat blur

### LINKED ISSUE #2821: [REQUEST] APU Exhaust Effect
**Describe the feature you'd like to see implemented**

Would it be possible to incorporate a heat shimmer exhaust effect to the APU when running, similar to the effect that is applied to the engine exhaust? 

**References**

**Additional context**

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by wpine215**
Fixes #2821

## Summary of Changes

Adds a heat blur effect to APU exhaust above 24% N

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub): Iceman#5540

## Testing instructions

Simply turn on the APU and observe heat blur effect at the beginning of start-up. Ensure effect disappears after shutdown.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #4986 
Tier of Testing: 1
Date: 03/06/21

Testing Process:
Loaded in C&D, on the runway, on approach and in the air and checked the blur at all different points
Negatives: N\A (some issues were discussed on discord https://discord.com/channels/738864299392630914/754130199804772372/849803576800968735)
Testing Results: Passed

Conclusions: Good work! Heat blur is finally here and it works as expected
Media: 
image
image
image

**Comment by Cryptic56** [comment]
Quality Assurance Tester/Trainee Report

Discord: Cryptic#4731
Object of testing: #4986
Tier of Testing: 1
Date: 03/06/2021

Testing Process:
 Load into aircraft at the gate
Turn on batteries and external power
Turn on APU master and APU start
Observe APU outside aircraft while checking temperature and N% values.
Switch of External power.
Switch off APU and check to make sure the effect turns off.

Negatives: the start and end of the effect are very sudden. the effect is coming from the NAV lights rather than APU (these issues were discussed on the discord channel)
Testing Results: Passed

Conclusions: Overall the effect works well and doesn't have any major issues. There are a couple of things mentioned above that could be tweaked if possible but overall this works very well.
Media:
Microsoft Flight Simulator Screenshot 2021 06 03 - 11 10 55 12

Microsoft Flight Simulator Screenshot 2021 06 03 - 11 11 00 52

Microsoft Flight Simulator Screenshot 2021 06 03 - 11 11 10 88

Microsoft Flight Simulator Screenshot 2021 06 03 - 11 11 33 16

**Comment by ItzCryptiic** [comment]
Quality Assurance Trainee Report

Object of testing: #4986
Tier of Testing: 1
Date: 03/06/2021

Testing Process:
 1. Spawned Cold & Dark
 2. Started aircraft up (Before Start-up Checklist + APU start)
 3. Checked when the blur is appearing
 4. Turned the APU off - checked when blur is disappearing
 
Negatives: N/A
Testing Results: Passed

Conclusions: Everything worked how it was expected to work - LGTM
Media:
Screenshot (197)
Screenshot (199)

**Comment by davidwalschots** [comment]
I think three testers seeing some effect appearing is more than enough 😉.

**Comment by davidwalschots** [comment]
A more realistic effect would take into account the `EGT` and `OAT`. The size of the plume would probably be affected by the `N`.

**Comment by wpine215** [comment]
The size/shape as well as beginning/end of the effect cannot be adjusted yet until Asobo adds support for this in the new visual effects editor. I tweaked the condition to enable the effect to occur when N% is greater than 3 (when fuel is introduced), and when the EGT s greater than or equal to 50C. Just needs code review/approval.

**Review by davidwalschots — APPROVED** [review]

**Pull request merged**
