### PR TITLE
feat: add basic door video functionality

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

Display a black-and-white image of the cabin near the cockpit door when the "VIDEO" button is held AND the "COCKPIT DOOR VIDEO" toggle is ON on the overhead panel.

This PR does not include all the correct functionality, but includes a basic simulation. Namely, switching between cameras is not done because of model limitations and the fact that the VIDEO knob is absent, making me use the camera switching button for displaying the image instead. Still, the functionality is somewhat there and can be improved on further in the future.

## Screenshots (if necessary)

image

## References

image

image

image

image

Note: the functionality present in those references is impossible to implement as of now.

## Additional context

N/A

Discord username (if different from GitHub): someperson#4953

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 9/10/2020
Version of the sim: 1930
PR Tested: #1213

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane C&D
2. Checked the functionality of the door camera and both buttons
3. Checked different screen configs 
4. Repeated the process with start on runway and in the air

Overall Rating: Good
Conclusions of the testing: LGTM! Thank you for your work!

**Review by NathanInnes — APPROVED** [review]
Code looks good. Just about to test for myself.

**Comment by NathanInnes** [comment]
Tested and works well.

**Comment by lalloretpilou** [comment]
It works, but we have to keep pressing the button to display the video on the screen. is it like that in reality? the most practical will be to leave the video on the screen when you press once and delete it when you press a second time again.

**Comment by Benjozork** [comment]
@lalloretpilou, as stated in the reference it is not.

I explained the reason this isn't reproduced here:

> This PR does not include all the correct functionality, but includes a basic simulation. Namely, switching between cameras is not done because of model limitations and the fact that the VIDEO knob is absent, making me use the camera switching button for displaying the image instead. Still, the functionality is somewhat there and can be improved on further in the future.

**Pull request merged**
