### PR TITLE
docs(readme): remove experimental download section

### PR DESCRIPTION
**Pull request by ExampleWasTaken**
## Summary of Changes

Due to the experimental version not being updated for now, I removed the download section. 
I also updated the link to the latest changes of the master branch to point to the commit history of the master branch because the old one 404ed.

## Additional context

Discord username (if different from GitHub): `ExampleWasTaken#0886`

## Testing instructions

Testing shouldn't be necessary.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by davidwalschots** [comment]
I think we should either accept or decline #4205. It has been open for a long time.

**Comment by scoopscode** [comment]
> I think we should either accept or decline #4205. It has been open for a long time.

@davidwalschots As I stated in #4205, I am waiting for the next experimental version to come out that way I am able to add warnings and such to it. It's purposely been open because of the drastic amount of changes that have occurred from the time I have opened the PR to now.

**Comment by ExampleWasTaken** [comment]
> 
> 
> > I think we should either accept or decline #4205. It has been open for a long time.
> 
> @davidwalschots As I stated in #4205, I am waiting for the next experimental version to come out that way I am able to add warnings and such to it. It's purposely been open because of the drastic amount of changes that have occurred from the time I have opened the PR to now.

Not really related to this PR, but I think @davidwalschots is right. It doesn't make sense to keep a PR open until a certain feature is implemented / a certain condition is met. Rather make one that fits in right now and another, new one once experimental comes back.
I'm happy to close this one in favor of #4205.

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by Annolago** [comment]
Does this mean that the Development version and Experimental versions will merge into one?
What is recommended for the people who don't want to keep use the Asobo autopilot?

**Comment by scoopscode** [comment]
> Does this mean that the Development version and Experimental versions will merge into one?
> 
> What is recommended for the people who don't want to keep use the Asobo autopilot?

No, it will be readdressed in #4205.

**Pull request merged**
