### PR TITLE
cleanup: cdu/fms code (part 2)

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Removed unused code
- Removed duplicate code 

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Do normal flights, look out for any kind of unknown error.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 20/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3114 
Tier of testing: 2
Changes to observe: Full Flight to observe any issues with code cleanup

Testing technique: Full Flight from EGLL to LXGB during Storm Christoph
Steps you've made to test the Pull Request:
1. Spawned C&D EGLL Stand 509 - checked all overhead panel and centre console functions, switches, lights. 
2. Worked through FCU and MCDU set up and imported Simbrief flight plan
3. Push and Start, flew entire way on VATSIM 
4. Used Heading Mode but during descent/approach used Track FPA with live weather (significantly bad weather as well)
5. Flew RNAV approach and weather was particularly bad - no visibility until 2500m 600ft cloud base.
6. At 600ft got visual with the approach lights just about at 2.5km ahead, manual control and flew manually for landing 
7. Landed, backtrack and parked on stand. APU back on, shut down engines and checked systems

Flight Notes: all done on VATSIM and livestreamed too.
Route: EGLL/27L GOGS2G GOGSI N621 SAM M195 MARUK N621 LELNA UN621 BASIK UN90 NOVAN UN864 DELOG DCT CRISA UN864 PIMOS RNAV27/LXGB

METAR: 201528Z 220/14G32 2500 RA FEW006 BKN010 15/13 Q1014 BCMG 5000 -RA RMK YLO1 BCMG GRN

Livestream Link: https://youtu.be/Cx5zAQV4jro

Issues (If Any): During entry into the STAR the MCDU decided to go Direct to the Runway again so I flew the entire STAR and approach using automation/charts but using Track FPA too.
During landing with the strong crosswinds I had to continually use aileron and rudder input and got a slight wing drop again on flare which I just about held onto.

Overall Rating: Good
Conclusions of the testing: Issues above are wider Asobo issues I believe so this was a good test, in particularly challenging conditions

**Review by beheh — APPROVED** [review]

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 20/1/21
Version of the sim: 1.12.13.0
PR Tested: #3114
Tier of testing: 2
Changes to observe: MCDU

Testing technique: Did a full flight
Steps you've made to test the Pull Request:
1. Loaded in
2. Did a flight
3. Looked at the mcdu and checked that everything worked fine throughout the flight
4. (used simbrief)


Flight notes (When done a full flight): EGPH-EGGW (forgot to descent and was high)

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): none
Overall Rating: Good
Conclusions of the testing: Did a full flight and everything worked fine

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 21/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3114
Tier of testing: 2
Changes to observe: Full Flight to observe any issues with code cleanup  - Test 2 of 2 in different conditions

Testing technique: Full Flight but short from LGMK to LGSM
Steps you've made to test the Pull Request:

1. Spawned directly on the runway hot and programmed MCDU for short flight to Samos for recording of a tutorial
2. Worked through FCU and MCDU set up and manually inserted route instead of using simbrief
3. Departed and manually tinkered with heading and altitude numerous times
4. Input MCDU data relevant to the VOR procedure into Samos with CTL
5. During arrival, used VOR ND mode and selected heading mode, switching to Track FPA mid-procedure
6. Tracked VOR DME using ND and made the turns for the procedure with AP on until the final legs
7. At 4DME I took over control and flew manually for the CTL procedure 09
8. Landed, taxi to stand with APU etc on. Shut down.

Flight Notes: No issues
Media: It will eventually be on the channel as a Samos CTL tutorial

Issues (If Any): Absolutely none

Overall Rating: Good
Conclusions of the testing: This is the second test on this PR with very different conditions and usage of the aircraft. No issues found

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 21/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3114
Tier of testing: 2
Changes to observe: Test for issues after cdu/fms code cleanup

Testing technique: Full Flight, Tryout

Steps you've made to test the Pull Request:

1. Spawned at VOMM gate 22, C/D
2. Turned on battery, external power. Prepared the aircraft for a normal IFR flight. Programmed the entire route before departure (including STAR based on real world data)
3. Departed out of RWY 07
4. Flew IFR to VABB (Flying time of about 1hr 35mins)
5. ILS 27 approach into VABB. No STAR misbehavior, jumping to random waypoints was observed
6. Landed with no issues

Flight Notes: 
Route: VOMM DOHIA DOLKI Q8 AGELA MOLG2A VABB
Weather addon: REX 6

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: The flight went normally. No issues were observed.

**Comment by MisterChocker** [comment]
> 5\. jumping to random waypoints was observed

What do you mean by this?

**Comment by sidnov** [comment]
> > 5. jumping to random waypoints was observed
> 
> What do you mean by this?

I think you got me wrong. "No STAR misbehavior or jumping to random waypoints was observed" Should have added an "or" in between. xD

**Comment by HugoTro** [comment]
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 21/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3114 
Tier of testing: 2
Changes to observe: Full Flight to observe any issues with code cleanup

Testing technique: Full flight from C&D
Steps you've made to test the Pull Request:
1. Spawned at LFRS in C&D
2. Checked the ECAM "all" button
3. Completed the full flight

Flight notes:
Route: LFRS LUGE3S LUGEN UM616 TUPAR UM184 CNA UN863 SECHE SECH6S LFBO

Issues: Had to fly the STAR manually because the default A/P is crap (not PR related)
           "all" button on the ECAM not working properly but checked master and it had the same problem

Overall Rating: Good
Conclusions of the testing: No issues that were PR related

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#5297
Date of testing: 1/21/2020
Version of the sim: 1.12.13.0
PR Tested: #3114
Tier of testing: 2
Changes to observe: Test for issues after cdu/fms code cleanup

Testing technique: Cold and dark short 15-minute flight.

Steps you've made to test the Pull Request:

DTW to LAN, cold and dark spawn DTW
Load in the flight plan and prepare Aircraft
Depart Runway 22L
Fly the flight, looking for errors.
Landed at LAN.
Parked and ended the flight.


Flight Notes:
Route: KAYLN2 KAYLN
Weather addon: REX 6

Issues (If Any): None

Overall Rating: Good

**Comment by Benjozork** [comment]
Thank you @armankir @HugoTro @sidnov @BritishAvgeek @FlightSimmer7700 for testing

**Pull request merged**
