### PR TITLE
fix: climb and approach landing lights

### PR DESCRIPTION
**Pull request by Asianblade**
## Summary of Changes
Landing lights turned on when spawning on climb and approach phase.

## References
3pmdeeee
ref2oldddd

## Additional context
Discord username (if different from GitHub): Wesley#0008 (Wesley#TripleZero8)

## Testing instructions
Spawn on climb, making sure that the landing lights are on.
Spawn on approach, making sure that the landing lights are on too.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
2. Click on the **Checks** tab on the PR
3. On the left side, click on the bottom **PR** tab
4. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by davidwalschots — APPROVED** [review]

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 08/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4346 
Tier of testing: 1
Changes to observe: Flight state lights position

**Steps you've made to test the Pull Request:**
1. Loaded onto Approach
2. Loaded on RW with short/long flight and used "Travel To" function to check flight stages
3. How do spawn on a climb though? :D

**Media:**

**Issues (If Any):** 
- When Loading a short hop flight and "Travel to" Cruise, the Landing lights are turned OFF even with the ALT below 10.000ft (8500ft in my case)
- Doing the same on a longer flight the landing lights stay OFF, while they should be RETRACTED

**Conclusions of the testing:** Please use the Travel To option of the top navbar to check in different flight stages.

**Comment by Asianblade** [comment]
> Category: QA Tester
> Name: St54Kevin#3583
> Date of testing: 08/04/2021
> Version of the sim: 1.14.6.0
> PR Tested: #4346
> Tier of testing: 1
> Changes to observe: Flight state lights position
> 
> **Steps you've made to test the Pull Request:**
> 
> 1. Loaded onto Approach
> 2. Loaded on RW with short/long flight and used "Travel To" function to check flight stages
> 3. How do spawn on a climb though? :D
> 
> **Media:**
> 
> **Issues (If Any):**
> 
> * When Loading a short hop flight and "Travel to" Cruise, the Landing lights are turned OFF even with the ALT below 10.000ft (8500ft in my case)
> * Doing the same on a longer flight the landing lights stay OFF, while they should be RETRACTED
> 
> **Conclusions of the testing:** Please use the Travel To option of the top navbar to check in different flight stages.

Noted, will change some stuff

**Comment by Asianblade** [comment]
Try it without the 'Travel To' function, fly it straight up to a CRZ level below 10000 ft. Will try and implement the logics once I figured out how to do it :) Thanks kevin

**Comment by beheh** [comment]
This has been started before at #2268, but we can land this PR here in isolation, that just thins the other one out.

**Comment by St54Kevin** [comment]
> This has been started before at #2268, but we can land this PR here in isolation, that just thins the other one out. I'll eventually get back to that.

I do think its better to just finish the one with all the lights then to avoid any complications

**Comment by Asianblade** [comment]
> > This has been started before at #2268, but we can land this PR here in isolation, that just thins the other one out. I'll eventually get back to that.
> 
> I do think its better to just finish the one with all the lights then to avoid any complications

its just waiting for another qa, to thin some stuff out

**Comment by St54Kevin** [comment]
> Try it without the 'Travel To' function, fly it straight up to a CRZ level below 10000 ft. Will try and implement the logics on a separate PR once I figured out how to do it :) also according to discord it works during approach phase - which is what this should be for. Thanks kevin!

I just did the test with the takeoff to CRZ below 10.000ft. I didnt know what to look out for but the landing lights stayed ON

**Comment by Asianblade** [comment]
> > Try it without the 'Travel To' function, fly it straight up to a CRZ level below 10000 ft. Will try and implement the logics on a separate PR once I figured out how to do it :) also according to discord it works during approach phase - which is what this should be for. Thanks kevin!
> 
> I just did the test with the takeoff to CRZ below 10.000ft. I didnt know what to look out for but the landing lights stayed ON

yes because you have to manually switch it to off

**Comment by Asianblade** [comment]
closing pr, will be doing a brand new one :) thanks for all the help!

**Pull request closed without merging**
