### PR TITLE
[CDU] Fix negative default takeoff speeds

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Made takeoff speeds not set by default

## Screenshots (if necessary)

Before:
image

After:
image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: Current date 1/12/2020
Version of the sim: 1.11.6
PR Tested: #2149
Object of test: Negative default takeoff speeds fix

Testing technique: Loaded c/d, set up init pages then testet v speeds in perf 
Steps you've made to test the Pull Request:
1. Loaded at gate 
2. Aligned adirs 
3. Configured init pages 
4. V speed test
Microsoft Flight Simulator Screenshot 2020 12 01 - 06 14 05 11
 

Flight notes (If required): N/A

Issues (If Any): N/A
Overall Rating: Good
Conclusions of the testing: Looks great, good job!

**Comment by MisterChocker** [comment]
> I think what was causing the negative values was not having an assigned runway for takeoff, not sure.

No it's caused the by the way the variable was initialized before.

**Comment by MisterChocker** [comment]
@Benjozork tested, works, simple fix. Merging?

**Pull request merged**
