### PR TITLE
fix: Improved default pilot view to better reflect head position and view

### LINKED ISSUE #7557: Co-pilot legs only appearing when clearly in sight
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-10-11T22:03:37+00:00",
    "ref": "refs/heads/experimental",
    "sha": "dce2d65204bf7bbb8204bcd4f664cb253719c318",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "experimental:dce2d652"
}
```

### Describe the bug

When looking at the right side of the cockpit toward co-pilot rudder pedals, co-pilots legs are not shown (cf. figure 1)
However when moving just a little bit more to the right, co-pilot is popping out.
Picture_1
Picture_2

### Expected behavior

Is it possible to decrease the angle of head rotation at which co-pilot is loading so co-pilot legs are visible and not suddently appearing? 

### Steps to reproduce

1. Slowly turn the cockpit camera to the right and to the co-pilot rudder pedals
2. Co-pilot legs will suddently appear when co-pilot is loaded 

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

gauthx

### PR DESCRIPTION
**Pull request by frankkopp**
Fixes #7557

## Summary of Changes
This PR changes the default pilot view (and CoPilot) to better reflect the real head/eye position and zoom. 
The current camera position is too far forward.
Also fixes an issue where the avatar's legs are hidden when camera is too far forward. 

## Screenshots (if necessary)

Pay attention to the head position in relation to the CoPilot avatar. 
Also see in the video that the avatar legs disappear when camera is too far forward. This is fixed in the new position. 

CURRENT:
2022-11-20_19h23_18
2022-11-20_19h23_30
https://user-images.githubusercontent.com/16833201/202919697-529b81ab-3c2c-4577-b429-0e3f0d8e0ee4.mp4

NEW:
2022-11-20_19h20_08
2022-11-20_19h20_22
https://user-images.githubusercontent.com/16833201/202925792-298ac2f5-7751-41bf-abb1-2161e6da5b15.mp4

Comparison Video: Current View -> New View - 2 times
https://user-images.githubusercontent.com/16833201/203042736-68dcac59-86d7-45f2-b097-bf8a9a6f9e3d.mp4

Discord username (if different from GitHub): Cdr_Maverick#6475

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ImenesFBW** [comment]
One thing to note here is that the seats are fully backward on the rails, They are way further back than they would be in flight. Moving the view back might make it look more accurate toward the avatars, but the actual pilot's viewpoint would not be as far back as the seats.

**Comment by Yellow118** [comment]
Changes to the default pilot view will result in significant changes to the flying experience.
It also affects peripherals and other 3rd party add-ons such as home cockpit placement, GSX marshaller placement, VDGS configured with LOD, etc., which were adjusted based on the previous pilot view.
I hope you will carefully consider applying this change.

**Comment by frankkopp** [comment]
> One thing to note here is that the seats are fully backward on the rails, They are way further back than they would be in flight. Moving the view back might make it look more accurate toward the avatars, but the actual pilot's viewpoint would not be as far back as the seats.  

That's a good point. The viewpoint indicator also shows this is a way. 

I was trying to fix the wide angle distortion and the vanishing avatars when then the view is too far farward. 

Would be interested in pilot feedback on what feel more natural to them.

**Comment by frankkopp** [comment]
> Changes to the default pilot view will result in significant changes to the flying experience.
> 
> It also affects peripherals and other 3rd party add-ons such as home cockpit placement, GSX marshaller placement, VDGS configured with LOD, etc., which were adjusted based on the previous pilot view.
> 
> I hope you will carefully consider applying this change.

Thanks for this feedback. 

The whole idea of this PR is to put it out there for users to look at it and give feedback. We would also put this on Experimental to get additional feedback on this change. 
That is if this even is a change we want - the disussion here will show.

**Comment by beheh** [comment]
> The viewpoint indicator (red/white balls) also shows that it is now too far back.

I think as other places in the 3D model have shown, the cockpit's accuracy is limited. I wouldn't trust the red/white balls too much, especially as the cockpit has clearly not been 3D-scanned.

**Comment by Kimbyeoungjang** [comment]
Just curiose about the msfs's camera

image

Normally human eye have a limited angles of view like above picture.
Is msfs have a camera fov or angle system?

cause both new or old picture looks wider than actuall human vision or camera angle(normally in full-frame camera, 50mm lens is looks like human eye sight but the picture for me, looks like 85mm lens with wider camera sensor)

**Comment by frankkopp** [comment]
> Just curiose about the msfs's camera
> 
> image
> 
> Normally human eye have a limited angles of view like above picture. Is msfs have a camera fov or angle system?
> 
> cause both new or old picture looks wider than actuall human vision or camera angle(normally in full-frame camera, 50mm lens is looks like human eye sight but the picture for me, looks like 85mm lens with wider camera sensor)

You can't judge fov from the screenshots as this also depends on screensize/resolution/ratio - in my case is a large monitor with 3440 x 1440 pixels. If I make the window (or screenshot) smaller this would change.

**Comment by frankkopp** [comment]
Closing as new view are no accurate and would cause additional problems for some users.

**Pull request closed without merging**
