### PR TITLE
feat(hyd): smooth nose steering during pushback

### PR DESCRIPTION
**Pull request by crocket63**
Fixes #[issue_no]

## Summary of Changes

Msfs sends immediate pushback steering angle resulting in instant nose wheel steering.

To make this a bit more realistic, the pushback angle is smoothed so that wheel is turning approximately at the same speed as the pushback tug.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Do various pushback operations and check that wheel is steered by the tug in a smooth way.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by davidwalschots — APPROVED** [review]
Lovely! 🚀

**Comment by AquazDev** [comment]
Quality Assurance Tester/Trainee Report

Discord: LunakisLeaks#7744
Object of testing: #PR 6838
Tier of Testing: 1
Date: 04/03/2022

Testing Process:

Started Cold and Dark - OK

Called ATC For Pushback - OK

Pushback Turned At Angle - Forward- OK

Pushback Turned At Angle - Reverse - OK

Negatives: N/A

Testing Results: Passed

Conclusions: Works


image

image

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#5438
Object of testing: #6838 
Tier of Testing: 1
Date: 4/3/21

Testing Process: Loaded in at gate and used pushback through the flypad and the toolbar pushback addon to test different types of pushback
Negatives: N/A
Testing Results: Passed

Conclusions: LGTM

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester/Trainee Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 6838
Tier of Testing: 1
Date: 04/03/2022

Testing Process: 
- Started C+D at EGKK, connected tug via flyPad, took a pushback trip around Gatwick testing pushback with quick turns left, right and straight, verified N/W follows tug - PASS.
 
- Connected up again using the Toolbar Pushback addon, tested forward and reverse at various speeds and differing turn angles, nose wheel keeps up with the turn direction of the aircraft - PASS.

Negatives: N/A

Testing Results: PASS

Conclusions: LGTM!

**Pull request merged**
