### PR TITLE
Remove engine heat blur

### LINKED ISSUE #1224: [BUG] Visual glitches from engine heat blur
**Mod Version**

It's been there all the time I think.

**Describe the bug**

The engine blast blur effect causes plane textures to glitch and white streaks of artifacts to appear along the outlines.

Screenshot 2020-10-09 162400
Screenshot 2020-10-09 162333
Screenshot 2020-10-09 164651

**To Reproduce**

1. Start a flight, preferably in day light.
2. When the engines are on, inspect the surfaces affected by the blast.

**Expected behavior**

No artifacts.

**Actual behavior**

Artifacts 

Was this working before/when did the issue start occurring?
has been there all the time.
Is this a problem in the vanilla unmodded game?
I think so.

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes #1224

## Summary of Changes

As the engine heat blur clips into the wing, and in general does not look to good, I have removed it.
I've done some digging and found out where the effects are being defined and assigned to simvars, so I was able to remove it without removing or renaming any file.
## Screenshots (if necessary)

Before:
https://streamable.com/om9xcm

After:
https://streamable.com/7aiq9a

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by ilyeshammadi** [comment]
I thought this was a nice feature, why removing it? Doesn't look real?

**Comment by omarsmak** [comment]
But honestly I don't see heat blur is a bad thing :/

**Comment by Snapmatics** [comment]
> But honestly I don't see heat blur as a bad thing :/

We see it as an unrealistic thing. Pilots have said it doesn't look good and it's overdone. We will have to delete it until we make something better.

**Comment by lukecologne** [comment]
It doesn't really look good in the wing view. It clips through the wing, and is too strong. Compare this https://streamable.com/om9xcm video I took from the sim to some real life footage of the wing. I agree that it there should be heat blur, but it is simply too much, and because of a limitation from the sim, we can't edit the effect to make it less pronounced, so we think it is best to remove it until we can introduce our own effect.

**Comment by markusa380** [comment]
Couldn't we make it optional?

**Comment by myselfaaryan** [comment]
> Couldn't we make it optional?

You can always revert this and manually build the mod :)

**Comment by markusa380** [comment]
@myselfaaryan That's bad reasoning - not everyone has the technical skill to do that, given that this is a mod for a game and not some programming library.

**Comment by myselfaaryan** [comment]
> @myselfaaryan That's bad reasoning - not everyone has the technical skill to do that, given that this is a mod for a game and not some programming library.

Sorry for that, but since the team has decided to do it, it's the only workaround :(

**Comment by markusa380** [comment]
@myselfaaryan So why not make it configurable, by some means?

**Comment by myselfaaryan** [comment]
> @myselfaaryan So why not make it configurable, by some means?

I would kinda agree, however I am neutral about this commit. I can however provide a step by step guide for you.

This is what I would follow since I like to click screenshots which would not look good without the heat blur:
1. Download the mod normally & extract it or use the installer
2. Go to your community folder & A32NX/SimObjects/AirPlanes/Asobo_A320_NEO
3. Open aircraft.cfg using any editor
4. Line 46 & 47 

`;effect.0 = FX_EXHAUST_LEFT#(A:GENERAL ENG COMBUSTION:1, boolean)#FX_ASOBO_HEAT_BIG
;effect.1 = FX_EXHAUST_RIGHT#(A:GENERAL ENG COMBUSTION:2, boolean)#FX_ASOBO_HEAT_BIG`

Remove the semicolons from the start of both the lines so it would look like this,

`effect.0 = FX_EXHAUST_LEFT#(A:GENERAL ENG COMBUSTION:1, boolean)#FX_ASOBO_HEAT_BIG
effect.1 = FX_EXHAUST_RIGHT#(A:GENERAL ENG COMBUSTION:2, boolean)#FX_ASOBO_HEAT_BIG`

Save the file

5. Profit 🎉

**Comment by markusa380** [comment]
> screenshots which would not look good without the heat blur

This is exactly why you need to reconsider this change.

**Comment by myselfaaryan** [comment]
Category: QA Tester
Name: myselfaaryan#0001
Date of testing: 04/12/2020
Version of the sim: dev/master
PR Tested: #2221 
Object of test: To check if the heat blur is removed

Testing technique: Downloaded the artifact & installed the mod.
Steps you've made to test the Pull Request:
1. Spawn at Runway
2. Check if heat blur is removed

Flight notes (If required): N/A

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Works as described. No changes needed.

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 4.12.2020
Version of the sim: 1.11.6.0
PR Tested: #2221
Object of test: Heat blur removal

Testing technique: Try out
Steps you've made to test the Pull Request:
1. Loaded the A320 on the runway
heatblur was removed
2. Loaded other Jets in to see if heat blur is still there
Heat blur is there


Flight notes (If required):

Issues (If Any): none
Overall Rating: Good
Conclusions of the testing: Works as described, no issues found

**Comment by snaylor111** [comment]
But then you would have to do the step by step instructions everytime theres a new update. Ive not had one commit i did not like until now i quite like the effect. Please consider leaving this implemented until you guys come up with a better effect! No real reason do delete it to be honest.

**Comment by ErikNL80** [comment]
You can also put it the other way round... People annoyed by the heat blur can remove the effect, and leave it in by default until you got a replacement!

**Comment by omarsmak** [comment]
I would also vote to leave it for now until replacement being made. It is not so crucial to remove it IMHO, things may look static like P3D. However to be fair, a poll in discord can be made as well

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919
Date of testing: 12/4/2020
Version of the sim: 1.11.6.0
PR Tested: #2221 
Object of test: Engine heat blur removal.

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned onto the runway at kiad with a320
2. Went into wing view and did not see


Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Really good Pr but I hope in the future heat blur will return.

**Comment by marinerhally** [comment]
Category: QA Tester
Name: Discord User Mariner Hally#0715
Date of testing: Current date 05/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2221
Object of test: Check engine heat blur is removed.

Testing technique: Try out
Steps you've made to test the Pull Request:
1. Spawned C/D at EGNM
2. Checked exterior camera for heat blur
3. Checked wing view for heat blur
4. Did not see any heat blur

Flight notes (If required):

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Worked well with no issues, personally I do think the heat blur was too much.

**Comment by InhumanReactions** [comment]
Category: QA Tester
Name: InhumanReactions#0001
Date of testing: Current date 05/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2221
Object of test: Check that engine heat blur is removed in different conditions.

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned in C&D at LSZH.
2. Set up the plane and pushed back.
3. Checked the exterior camera on the ground, the heat blur was gone.
4. After take-off I flew through some cloud. No heat blur effect in the cloud.
5. Landed at LIRQ, checked on the ground again and the heat blur was not present.

Flight notes (If required): N/A

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Works correctly, on the ground, in the air, and in thick cloud.

**Comment by Highflyer2010** [comment]
Category: QA Tester
Name: Discord User Highflyer2010 #8923
Date of testing: Current date 06/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2221
Object of test: Engine heat blur Removal

Testing technique: Cold and Dark 
Steps you've made to test the Pull Request:

    1.Spawned Cold and Dark at EGNT
    2.Checked window view for heat blur
    3.Checked Outside the aircraft for heat blur
    

Flight notes (If required):

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: No issues, I do like this feature but sadly it's gone for the time being

**Comment by Tawmu** [comment]
I agree with all the above. Even if it's unrealistic many people have come to expect it and quite like the effect it adds in-game, particularly for those coming from P3D where it didn't exist at all.

It should stay in until something better is ready to be merged.

**Comment by omarsmak** [comment]
> I agree with all the above. Even if it's unrealistic many people have come to expect it and quite like the effect it adds in-game, particularly for those coming from P3D where it didn't exist at all.
> 
> It should stay in until something better is ready to be merged.

Yes indeed, we do agree is bit much but is not _bad_ by any means that needs an immediate removal. IMHO removing it may make more people angry than keeping it at meantime. I'd really suggest again, just to keep this until a new effect is being created. Or even better this can be configurable from the new EFB or the new installer software along with other features like the custom fbw that is not yet in the master branch.

**Comment by lukecologne** [comment]
Closing as it looks like many people want it to stay.

**Pull request closed without merging**
