### PR TITLE
feat(mcdu): Check Take Off Data

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Added Check Take Off Data functionality

## References

Honeywell Step A1
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Change runway, flaps/ths, flex or weights to check message is being generated (will clear after entry of first speed) and previous v speeds being displayed in cyan next to the amber boxes.
Also test the confirm functionality via the LSK 1L, 2L, 3L or 6R.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by beheh** [comment]
Hm, are you sure this is how it works?

I interpret the following line:
> The CHECK TAKE OFF DATA message is cleared when either V1, VR, or V2 is re--entered or the CONFIRM TO DATA* prompt is selected in 6R.

...so that once any of these conditions apply, the small, old values also go away, with the rationale being that the pilots have redone their performance calculation and therefore have a new V1/VR/V2 triplet.

In your version it looks like the pilots are able to overwrite V1/VR/V2 individually. Maybe we need pilot confirmation here?

**Comment by MisterChocker** [comment]
I might be wrong but I understand it is (very simple)
Make a valid entry for 1L, 2L or 3L -> message will disappear
And the one that are not "checked" yet are still visible in cyan.
Or use the CONFIRM TO DATA* prompt and everything is done in one step.

**Review by beheh — APPROVED** [review]

**Comment by NonstopFlying** [comment]
Category: QA Trial
Name: NonstopFlying #6771
Date of testing: 03/02/2002
Version of the sim: 1.12.13.0
PR Tested: #3285
Tier of testing: 1
Changes to observe:

-Added Check Take Off Data functionality

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned in at EDDF, planned a flight and taxied to the runway
2. Inputed the V speeds and flaps
3. Changed the runway (Check take of data appeared, Cyan number appeared on the side as well as the amber boxes
4. Changed the falps/ths, flex (same outcome)
5.Tested 1L,2L,3L and 6R to see if that works (worked as descriped)


Overall Rating: Good
Conclusions of the testing: Does what it's supposed to in my observations

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/04/2021
Version of the sim: 1.12.13.0
PR Tested: #3285 
Tier of testing: 1
Changes to observe: Check Take Off Data message.

Testing technique: Putting in take off data and changing data.

Steps you've made to test the Pull Request: 
1. Spawned at gate, putting in take off data and Vspeeds. 
2. Changed weight, flaps, flex and rwy(individually).
3. Check Take Off Data showed up each time.
4. Resets as described using 1L,2L,3L or 6R.

Flight notes (When done a full flight):

Media: 
FlightSimulator_9vIxkk3jbr

Issues (If Any): None.

Overall Rating: Good.
Conclusions of the testing: "Check take off data" shows up as described in instructions.

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 7/2/21
Version of the sim: 1.12.13.0
PR Tested: #3285 
Tier of testing: 1
Changes to observe:
Check Take Off Data message on MCDU

Testing technique: Loaded in and checked
Steps you've made to test the Pull Request:
1. Loaded in
2. Checked that the message comes up

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

https://user-images.githubusercontent.com/70103461/107153007-2518e780-6963-11eb-9bd2-b9e2ef1674a8.mp4



Issues (If Any): When entering the zfw/zfwcg or flaps or the Flex temp before entering V speeds the number entered will enter but also pop back up on the scratchpad at the bottom (Only happens before entering v speeds, after v speeds have been entered and the flaps or flex is entered the check takeoff data message appears as expected)

Checked in latest dev and this does not occur^

Overall Rating: To be improved
Conclusions of the testing: Message pops up every time as expected but there is an unwanted side effect where the message entered pops back up after entering it, after that is fixed the pr is good to go.

**Comment by MisterChocker** [comment]
@FlightSimmer7700 Thanks for the feedback, can you please recheck with the changes I made?

**Comment by kberg93** [comment]
> @FlightSimmer7700 Thanks for the feedback, can you please recheck with the changes I made?

Teste now and it seems fine now :) merge 👍🏻

**Comment by FlightSimmer7700** [comment]
Just did a quick test and it's all good now! Good job!

**Pull request merged**
