### PR TITLE
fix: Outer tank fuel transfer behavior

### LINKED ISSUE #6965: Outer tank fuel transfer ocurring on only the right side
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-24T17:31:46+00:00",
  "ref": "master",
  "sha": "cdb1a6281a8da541cbce47ff45fd5edf66fccb08",
  "actor": "RichardPilbery",
  "event_name": "manual",
  "pretty_release_name": "master:cdb1a628"
}
```

### Describe the bug

Not sure if this is 100% a bug, but an outer tank fuel transfer started whilst taxiing into the gate (after landing). However when checking the FUEL page after shutdown a few minutes later, the fuel was only being transfered on the right fuel tanks. Not sure if this is related to the APU running on the left fuel tanks, but still strange that this can lead to such a fuel inbalance.

### Expected behavior

Either the fuel transfer not starting after landing or the transfer happening on both sides.

### Steps to reproduce

1. Land with fuel just about the transfer limit.
2. Taxi to the gate, getting below the transfer limit.
3. Start the APU, shutdown the engines, and observe the FUEL ECAM page.

### References (optional)

See https://www.twitch.tv/videos/1435505521?t=01h29m45s for the OUTR TK FUEL XFRD memo to appear for the first time on the ECAM. At https://www.twitch.tv/videos/1435505521?t=01h32m48s I check the ECAM fuel page to see only the right side being transferred.

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by donstim**
Fixes #6965 

## Summary of Changes

In the current version, left and right outer tank fuel transfer operations are independent. The left outer transfer valves open when the left inner tank reaches the trigger level for initiating the fuel transfer, and the right outer transfer valves open when the right inner tank reaches the trigger level. This can lead to asymmetric fuel transfer in some situations (e.g., see the referenced issue).

This PR changes the behavior of the fuel transfer valves such that whenever one of the inner tanks reaches the trigger level, the outer tank fuel transfer valves are opened for both left and right sides. The trigger value has also been adjusted slightly to 246.8 gallons, which should match the 750 kg trigger value better using MSFS unit conversions.
## References

Screenshot (2032)_LI

## Additional context

Discord username (if different from GitHub): donbikes#4084

## Testing instructions

Verify that the trigger level for outer to inner fuel tank transfer is initiated when either inner tank fuel level reaches 750 kg (with the outer tank fuel transfer valves closed initially and more than 750 kg of fuel in both inner tanks). This can be checked for the left and right tanks individually be shutting down the engine on one side.

Make sure there are no unwanted side effects with fuel loading, etc. and that it also works correctly when using Imperial units (lbs). The trigger level for the initiation of outer tank fuel transfer in pounds should be around 1653.5 using MSFS unit conversions.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7037
Tier of Testing  : 1
Date             : 13/04/2022

Testing Process: 
Verify that the trigger level for outer to inner fuel tank transfer is initiated when either inner tank fuel level reaches 750 kg (with the outer tank fuel transfer valves closed initially and more than 750 kg of fuel in both inner tanks). - **OK**
This can be checked for the left and right tanks individually be shutting down the engine on one side. - **OK**

Make sure there are no unwanted side effects with fuel loading, etc. and that it also works correctly when using Imperial units (lbs). The trigger level for the initiation of outer tank fuel transfer in pounds should be around 1653.5 using MSFS unit conversions. - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

**Comment by owen2007** [comment]
Trainee Report

Discord          : (owen_#4883)
Object of testing: (#PR 7037)
Tier of Testing  : (1)
Date             : (17/04/2022)

Testing Process: 
Verify that the trigger level for outer to inner fuel tank transfer is 
initiated when either inner tank fuel level reaches 750 kg (with the outer 
tank fuel transfer valves closed initially and more than 750 kg of fuel in
both inner tanks) - CHECKED

This can be checked for the left and right tanks individually
be shutting down the engine on one side - CHECKED

Make sure there are no unwanted side effects with fuel loading, etc. 
and that it also works correctly when using Imperial units (lbs). 
The trigger level for the initiation of outer tank fuel transfer 
in pounds should be around 1653.5 using MSFS unit conversions - CHECKED


Negatives:       
none recorded

Testing Results: 
Passed

Conclusions: 
works

**Comment by tracernz** [comment]
Ready to merge this @donstim?

**Comment by donstim** [comment]
> Ready to merge this @donstim?

yep

**Pull request merged**
