### PR TITLE
Added 3d sound emitters, cargo door, gear extension/retraction, mech horn, evac horn, and emer cabin call

### LINKED ISSUE #1113: [BUG] GPU Packs Audio delay after switching view
**Mod Version**

Latest Master Branch

**Describe the bug**

When you can hear the GPU air conditioning and switch view, the sound stops and there is a 10 second delay or so until the pax sounds start again

**To Reproduce**

1. Spawn cold and dark
2. Turn on GPU and batteries
3. Switch view to external and then back to cockpit
4. Listen and the air conditioning sound does not return for a few seconds

**Expected behavior**

The air conditioning sound in the cockpit is continuous

**Actual behavior**

After switching views, there is a delay until the sound starts again

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Latest master

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): obama#6262

### PR DESCRIPTION
**Pull request by hotshotp**
Fixes #1113 

## Summary of Changes
Firstly, this fixes the issue of the avionics fans taking a few seconds to start up in internal view after switching to external and back.
Then, this changes the avionics fans from the previous ones to be higher quality. Then it adds extra sounds for the battery relay, the cargo doors, gear extension and retraction, emer cabin call, mech horn, and evacuation horn. 
Finally, I have made every sound have a 3D position around the cockpit, so it is an "emitter". This will make the entire soundscape more alive.

Note: Evac horn shutoff button works only when holding it down as it only toggles the simvar when pressed. This can be easily fixed in the future by having that button have to "toggle" the simvar rather than "holding" it. So press the EVAC command button to stop it once you pressed it again.

## References

I have used real videos, samples, and took feedback from many IRL pilots and engineers to make sure the sounds are realistic.

## Additional context

There is one annoying issue that I cannot fix. This is, when you spawn on the runway or on approach all the startup sounds play in a sequence. There is no way that I could find to remove it, but I don't think this is that bad of an issue as it is only for about 10 seconds.

Another tiny issue, the CIDS chimes (the 2-6 chimes you hear in the cockpit after connecting battery power), these are played after only one battery is connected. While this is annoying, I cannot fix that until the new electrical system is added and it has new simvars for individual batteries being on.

Last and final issue, when you spam external power over and over the avionics fan self test sound starts from the middle. That is just how Wwise works and I cannot actually fix that, so just don't spam the ext power button :)

Discord username (if different from GitHub):

Boris#9134

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by hotshotp** [comment]
I messed up a lot of things in my previous PR, this should pretty much fix all the issues. Let me know if you guys find anything of concern in this iteration of the sound pack.

**Review by ImenesFBW — APPROVED** [review]
Name: Imenes#8739
Date of testing: 7/10/2020
Version of the sim: 1930
PR Tested: #1160 

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane C&D, Triggered and listened to the sounds.
2. Short test flight to check gear retraction and other airborne sounds. 
3, Spawned on the runway to check "hot start" behaviour 

Overall Rating: Good
Conclusions of the testing: Working as described. Boris strikes again expanding the soundscape of this mod!  Thank you for your work!

**Comment by Pleasure0102** [comment]
found a small bug i believe @hotshotp 

mech call does not seem to work for me

**Comment by hotshotp** [comment]
Okay! Added the two changes, it is safe to merge now after you guys test this.

**Comment by Pleasure0102** [comment]
> Okay! Added the two changes, it is safe to merge now after you guys test this.

what changed `? so we can look for that ?

**Comment by hotshotp** [comment]
> > Okay! Added the two changes, it is safe to merge now after you guys test this.
> 
> what changed `? so we can look for that ?

look at the commit: Made mech horn just a little bit louder in the cockpit, and made cargo door closing the same volume as the cargo door movement.

**Review by wuperguy — APPROVED** [review]

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 7/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1160

Testing technique: Initial check
Steps made to test the Pull Request:

Started from C&D and spawn on RWY to check any disparities between sounds in the takeoff and landing phase when starting from those scenarios. 

Overall Rating: Good
Conclusions of the testing: Working as described. The only issue which cannot be helped for the time being is how long you hear the yellow hydraulic pump sound for. But the current A320 model has the FWD cargo door opening for a very short time. When the HYD page is implemented it will be cool to see how it's all integrated as yellow pump is pressurized.

**Comment by tareksabet** [comment]
Name: tarek_sabet#7946
Date of testing: 7/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1160

Testing technique: Initial check
Steps made to test the Pull Request:

Started from C&D and spawn on RWY to check any differences between sounds in the takeoff and landing phase when starting from those scenarios and no problem. 

Overall Rating: Good
Conclusions of the testing: Working as described. Everything is good.

**Review by lukecologne — APPROVED** [review]
Sounds great, and confirmed by real pilots, so if nobody has anything against it, I'm gonna go ahead and merge

**Pull request merged**
