### PR TITLE
changed color of FD to correct color

### LINKED ISSUE #1257: [BUG][TEXTURE] FD Panel Wrong Color
**Mod Version**

Master

**Describe the bug**

FD Panel has wrong color and + missing

**To Reproduce**

1.Load MSFS
2.Look at the FD panel
3.

**Expected behavior**

have the correct color and +

**Actual behavior**

has wrong color and + is missing

**References**

Sim:
before
Real Photo:
image
image

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by Pleasure0102**
Fixes #1257

## Summary of Changes

Changed Texture of FD Panel
## Screenshots (if necessary)

BEFORE:
before
AFTER:
after

## References

image
image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by aviationenthusiast** [comment]
that looks nicer too!
may i ask about the significance of that blue + or airplane symbol?

**Comment by stevex77** [comment]
> that looks nicer too!
> may i ask about the significance of that blue + or airplane symbol?

Some "visual alignment reference point"? I really don't know, just guessing... :)

**Comment by Pleasure0102** [comment]
> that looks nicer too!
> may i ask about the significance of that blue + or airplane symbol?

i wish i knew, i did not even know about it until i got the pictures from engineer :)

**Comment by aviationenthusiast** [comment]
> 
> 
> > that looks nicer too!
> > may i ask about the significance of that blue + or airplane symbol?
> 
> i wish i knew, i did not even know about it until i got the pictures from engineer :)

i see, no problem:)

**Comment by lukecologne** [comment]
https://aviation.stackexchange.com/questions/43916/what-does-this-plus-cross-sign-on-this-electrical-panel-mean/43917

**Comment by FlightSimmer7700** [comment]
Name: FlightSimmer7700#3468
Date of testing: Current date 11/10/20
Version of the sim: Version the tester uses
PR Tested: #1258 

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned on a gate
2. Looked at the panel 
3. Spawned in midair
4.looked at the panel again
5.

Overall Rating: Good
Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.
If it looks realistic to IRL pilots then its good
Screenshot (202)

**Comment by aviationenthusiast** [comment]
> 
> 
> https://aviation.stackexchange.com/questions/43916/what-does-this-plus-cross-sign-on-this-electrical-panel-mean/43917

that's interesting. perhaps someone down the road should implement these random errors in times of turbulence and make that area pressure sensitive to get the panels reconnected to the circuit.

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
