### PR TITLE
fix: un-mirror sharklet textures

### PR DESCRIPTION
**Pull request by tracernz**
## Summary of Changes

Un-mirror the sharklet livery texture. A lot of repaints make this texture transparent and use the underlying wing texture to paint their livery on the sharklets, but some use the higher resolution livery texture. The texture has both sides, but the UV maps both point to the same side so the left is mirrored. This could potentially cause issues with some repaints if they didn't paint to left textures before.

## Screenshots (if necessary)

image

image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by bouveng — APPROVED** [review]
Looks good! Hard to judge the json-data, but having seen the script that generated it + pictures of the result, its approvable.

**Comment by bouveng** [comment]
unknown
Proof of functional PR on Grinde's SE-ROJ.

**Comment by Grinde81** [comment]
Just double-checking, does this change the UV's in all LOD's , or only LOD00?

**Comment by davidnorfolk96** [comment]
> unknown
> Proof of functional PR on Grinde's SE-ROJ.

Do you know where i can find this livery please? i've had zero luck hunting it down lmao

**Comment by ewold** [comment]
Quality Assurance Trainee Report

Discord: E-wold#8195
Object of testing: #5490 
Tier of Testing: (1)
Date: (05/08/2021)

Testing Process: Loaded a livery which has some graphics on the sharklet and compared the current version vs PR

Negatives: Some liveries are going to be adapted to this change since livery creaters don't mirror it standard in the paintfile it seems. See images from new version.   With the old version both sharklets had the logo. 
If automatic conversion takes place this can happen that the original a320neo would have mirrored sharklets and the a32nx not. 
Just to create awareness. 

Testing Results: Passed

Conclusions: Sharklets are not mirrored anymore but can lead to some liveries to be updated by creators. 

Media:
newleft
newright

**Comment by bouveng** [comment]
@ewold Hi just to clarify this to a non-livery-painter/modeler.

> Some liveries are going to be adapted to this change since livery creaters don't mirror it standard in the paintfile it seems.

What does this means in terms of current liveries painted?
Does it means that whatever that is on that area in the texture file, now will be moved to the sharklet?

That area should be empty for most, and not do any huge damage to current model?

I think many of them will be more than happy to fill it in and make their art better.

Br.

**Comment by ewold** [comment]
@bouveng , in the picture above the painter only put the logo twice which resulted it only being shown on 1 sharklet. 
To correct his the livery creator would make 4 logos on  the paint. 
I agree this fix is better , only wanted to point out that some paints can look different if they didnt mirror them beforehand in the livery. . But this is on the livery creator to fix for the N32X. 
I guess this only goes for a small part of the liveries since most of them doesnt have a logo or text in it and just painted in a certain color.

**Comment by Grinde81** [comment]
> What does this means in terms of current liveries painted?
> Does it means that whatever that is on that area in the texture file, now will be moved to the sharklet?
> 
> That area should be empty for most, and not do any huge damage to current model?

For those who have a decal on the winglet (some logos work fine mirrored, Lufthansa logo for instance):
The right winglet will be unchanged, while the left winglet will now be empty (no decal).

The left winglet needs to be repainted in the same way the right winglet once was, but on the left winglet UV / Texture space.

**Comment by dragold** [comment]
Category: QA Tester trainee
Name: Mr.Blank#1
Date of testing:08/10-11/2021
The version of the sim: 1.18.15.0
PR Tested: #5490
Tier of testing: 1
Changes to observe:
Un-mirror the shark livery texture
Testing instructions
NIL
Testing technique: Tryout
Methodology:
Surface finish Inspection
Surface reflection Inspection
Asymmetry Inspection
3rd party livery(random) Inspection 

Observations- All Inspections were as normal 

Testing Results: Passed

Conclusions: All Inspections were as normal but some 3rd party livery may have problems

**Comment by thesimpilot** [comment]
Quality Assurance Tester/Trainee Report

Object of testing: 5490
Tier of Testing: 1
Date: 11/08/2021
The version of the sim: 1.18.15.0

Testing Process: Loaded with a livery that has sharklet graphics (IRAN AIR, Scandinavian, Pegasus) and compared to current version.
Negatives: Some liveries might require the creator to unmirror sharklet graphics that are already mirrored to look correct. Or add both inner and outer graphics where there's one set.
Testing Results: Passed

Conclusions: No mirroring observed for liveries that has both inner and outer sharklet graphics. However, graphics were only drawn on right sharklet for liveries with only outer face textures. Current stable displays these graphics correctly without mirroring

Media: 
PR #5490
Microsoft Flight Simulator Screenshot 2021 08 11 - 21 17 49 23

Microsoft Flight Simulator Screenshot 2021 08 11 - 21 17 56 41

Stable 0.6.3
Right Wing
Microsoft Flight Simulator Screenshot 2021 08 11 - 21 25 10 38
Microsoft Flight Simulator Screenshot 2021 08 11 - 21 25 04 15

Left Wing
Microsoft Flight Simulator Screenshot 2021 08 11 - 21 25 26 29
Microsoft Flight Simulator Screenshot 2021 08 11 - 21 25 21 05

Livery Texture
A320NEO_AIRFRAME_LIVERY_ALBD

**Comment by tracernz** [comment]
Docs for livery creators in https://github.com/flybywiresim/docs/pull/165

**Pull request merged**
