### PR TITLE
Fixed throttle decal emissive

### PR DESCRIPTION
**Pull request by FoxinTale**
Fixes #[issue_no]

## Summary of Changes

Removed a tiny backwards comma thing on the emissive texture.
## Screenshots (if necessary)

Removed a backwards comma looking thing on the emissive decal.

## Additional context

image
^^That thing^^

Discord username (if different from GitHub):
Aubrey Jane#7563

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Pleasure0102** [comment]
QA Tester Please check this:
image
should no longer be glowing when turning on the integ Pedestal lights

**Comment by Pleasure0102** [comment]
some problems, gonna fix tomorrow with @FoxinTale

**Comment by Awemeter** [comment]
Category: 
Name: Awemeter#7919
Date of testing: 11/20/2020
Version of the sim: 1.10.11.0
PR Tested: #2020
Object of test: Throttle Decal 

Testing technique: Trying it out
Steps you've made to test the Pull Request:
1. Spawend at ksfo and started aircraft
2. Looked at the throttle level and check if the white mark on the throttle was glowing. It was not.
3. Tryed out in different times and weather conditions. 

Flight notes: N/A

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: No visual bugs found and glow is removed.

**Comment by tjburni** [comment]
Category: QA Tester
Name: tjburni # 0409
Date of testing: Current date 21.11.2020
Version of the sim:1.10.11.0
PR Tested: #2013
Object of test:Autopilot & A/THR warning and caution when disconnect 

Testing technique:
1.Started at Gate 
2.Climed to 30000 ft 
3.Disconnected Autothrottle
4.Disconnected AP 
5.looked at Ecam for the Warnings

Issues:None 
Overall Rating: Good
Conclusions of the testing:Works Good. No Problems

**Comment by CaptainR3X** [comment]
Category: QA Tester
Name: GustavRex #4347
Date of testing: Current date 22/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2020
Object of test: Throttle decal & white mark on throttle light test

Testing technique: Light test on ground, multiple time zones
Steps you've made to test the Pull Request:
1. Spawing in at 2 different airports, checking 4 timezones during the day at each airport (Morning, Midday, Late afternoon, Night) with all other lights turned off
2. Cross checking with pictures from different timezones to make sure that there is no glow
3. Speeding through day and night time with quickly changing light to make sure that there is no glow whatsoever

Flight notes (If required): 

Issues (If Any): None
Overall Rating: Good, Ready to go
Conclusions of the testing: At both airports, at all times during the day there was no glow to be found. When speeding through the day and night time, the quickly changing light did not affect the glow. Thus, there is no glow. It looks really good, nice work!

**Comment by ko-zone** [comment]
LGTM

**Pull request merged**
