### PR TITLE
[ND] Add missing altitude constraint symbol

### PR DESCRIPTION
**Pull request by ilyeshammadi**
## Summary of Changes

Add missing constraint symbol in the navigation display when CSTR is selected.

### Before
Screenshot (39)

### After
Screenshot 2020-11-17 231908

## References

Screenshot 2020-11-16 222252

Video: https://youtu.be/TEi-WX08ov8?t=243

## Additional context

Discord username (if different from GitHub): Union Araken#4083

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MisterChocker** [comment]
By any chance, do you know how we can get rid off that circle around the waypoints?
As far as my knowledge goes, only the older systems have it. Or adjust the color if that circle is correct, that would be great!

**Comment by ilyeshammadi** [comment]
> By any chance, do you know how we can get rid off that circle around the waypoints?
> As far as my knowledge goes, only the older systems have it. Or adjust the color if that circle is correct, that would be great!

@MisterChocker  Yes, It's an SVG file in asobo files, I can port it to A32NX and change the color if that's needed.

**Comment by MisterChocker** [comment]
@ilyeshammadi I think I was wrong, the circle indicates something. But yes, the color would be awesome.
I haven't looked at the nd and therefore have no clue where all that stuff is located ^^.
Would be awesome if you could adjust the color!

**Comment by MisterChocker** [comment]
Maybe do another pr were you do that, you could then also include the airports symbol color ;)

**Comment by ilyeshammadi** [comment]
@MisterChocker I will try to fix the color of the circle in this PR and for the airport maybe in another PR ;)

**Comment by MisterChocker** [comment]
Nice looking better for sure ;) with the colors match.

**Comment by Benjozork** [comment]
As discussed on discord, let's update the magenta colors in all displays.

**Comment by MisterChocker** [comment]
@Benjozork we just did that :o The only missing now is the airports * on the nd.

**Comment by Benjozork** [comment]
It doesn't use a shared color like `--displayMagenta`.

**Comment by ilyeshammadi** [comment]
@Benjozork I couldn't find how to update the airport color, I suggest keeping it outside the context of this PR. And for CSTR circle it's the same magenta color we're trying to use everywhere as @MisterChocker recommended.

**Comment by lukecologne** [comment]
> 
> 
> @Benjozork I couldn't find how to update the airport color, I suggest keeping it outside the context of this PR. And for CSTR circle it's the same magenta color we're trying to use everywhere as @MisterChocker recommended.

It's not using the shared color, though, it is defined as a constant in A32NX_Display_Common.css, you should use   --displayMagenta.

**Comment by MisterChocker** [comment]
like `stroke: --displayMagenta` ?

**Comment by Benjozork** [comment]
Color change was removed as discussed on Discord.

**Comment by stevex77** [comment]
> @ilyeshammadi I think I was wrong, **the circle indicates something**. But yes, the color would be awesome.
> I haven't looked at the nd and therefore have no clue where all that stuff is located ^^.
> Would be awesome if you could adjust the color!

Just small note on constranit circle color, according to Honeywell Pegasus A1 manual, referencing EFIS (ND):
- Constrainted waypoints has always a circle around them, the color differs
- MAGENTA - Constraint is predicted to be met
- AMBER - Constraint is predicted to be missed
- WHITE - Constraint is not being considered

Not sure if this logic is already implemented (by ASOBO), also not sure if it could be easily implemented.

**Comment by ilyeshammadi** [comment]
> > @ilyeshammadi I think I was wrong, **the circle indicates something**. But yes, the color would be awesome.
> > I haven't looked at the nd and therefore have no clue where all that stuff is located ^^.
> > Would be awesome if you could adjust the color!
> 
> Just small note on constranit circle color, according to Honeywell Pegasus A1 manual, referenced as EFIS symbols for Flight Plan (ND / Flight Plan mode):
> 
> * Constrainted waypoints has always a circle around them, the color differs
> * MAGENTA - Constraint is predicted to be met
> * AMBER - Constraint is predicted to be missed
> * WHITE - Constraint is not being considered
> 
> Not sure if this logic is already implemented (by ASOBO), also not sure if it could be easily implemented.

@stevex77 thanks for the information. Currently this logic is not in place, asobo on set the circle to Magenta.

**Comment by MisterChocker** [comment]
@ilyeshammadi this may be for a different pr. Also, I think we currently haven't implemented such a prediction yet.

**Comment by stevex77** [comment]
Agree with separate PR for this prediction logic / constraints coloring. As crawling through FMS manual, there is a LOT OF LOGIC to be implemented. :)

**Comment by stevex77** [comment]
**Category:** QA Tester
**Name:** SteveX77 [Z+0!]#1407
**Date of testing:** 11/18/2020
**Version of the sim:** 1.10.11.0
**PR Tested:** #1980
**Object of test:** [ND] Add missing altitude constraint symbol

**Testing technique:**
Perform a flight from KMCO to KMIA (ILS 27), plan with some ALT constraints and observe ND during all phases of flight, check for constraints presentation.
Different ND views (LS, VOR, NAV, ARC, PLAN) and modes (ARPT, NDB, WPT, VORD, CSTR) and zoom levels.
Check on both LEFT and RIGHT ND.

**Steps you've made to test the Pull Request:**
1. Spawn at the gate and power on ACFT
2. Plan the route (KMCO >>> KMIA, BLUFI STAR, ILS 27 via HENDN IAF), manually set some additional constraints (these for STARS should be there)
3. TAXI to HLDG RWY, T/O, CLB, LVL, DES, APPR, LAND, TAXI to gate
4. Check ND, play with different views and modes, zoom levels
5. Focus on constraints values / sign (+-) symbols and colors

**Notes:**
Can see constraint values incl. sign symbol where set. Values have right MAGENTA color.
Constraint circles still are wrong MAGENTA.

**Issues (If Any):**
Initially not set any constraint to BLUFI WPT, set it during the flight.
Can see constraint on F-PLN page of MCDU but no constraint on ND (even when changing modes, views, zoom levels).
Also tourned off - on ND - BLUFI still without any CSTR.

**Overall Rating:** GOOD, except of missing CSTR added in-flight.
**Conclusions of the testing:** LGTM

**Comment by MisterChocker** [comment]
@stevex77 Currently when adding or changing constraints you have to disable and enable the constraint mode on the nd in order to update them. We really need a fix for this at some point xD

**Comment by stevex77** [comment]
@MisterChocker Tried with disabling CTSR prior setting / changing ALT CSTR, then re-enabling CST on ND and it works as you described. I agree that there is really A LOT OF WORK here. :) LGTM then.

**Comment by ilyeshammadi** [comment]
> **Category:** QA Tester
> **Name:** SteveX77 [Z+0!]#1407
> **Date of testing:** 11/18/2020
> **Version of the sim:** 1.10.11.0
> **PR Tested:** #1980
> **Object of test:** [ND] Add missing altitude constraint symbol
> 
> **Testing technique:**
> Perform a flight from KMCO to KMIA (ILS 27), plan with some ALT constraints and observe ND during all phases of flight, check for constraints presentation.
> Different ND views (LS, VOR, NAV, ARC, PLAN) and modes (ARPT, NDB, WPT, VORD, CSTR) and zoom levels.
> Check on both LEFT and RIGHT ND.
> 
> **Steps you've made to test the Pull Request:**
> 
> 1. Spawn at the gate and power on ACFT
> 2. Plan the route (KMCO >>> KMIA, BLUFI STAR, ILS 27 via HENDN IAF), manually set some additional constraints (these for STARS should be there)
> 3. TAXI to HLDG RWY, T/O, CLB, LVL, DES, APPR, LAND, TAXI to gate
> 4. Check ND, play with different views and modes, zoom levels
> 5. Focus on constraints values / sign (+-) symbols and colors
> 
> **Notes:**
> Can see constraint values incl. sign symbol where set. Values have right MAGENTA color.
> Constraint circles still are wrong MAGENTA.
> 
> **Issues (If Any):**
> Initially not set any constraint to BLUFI WPT, set it during the flight.
> Can see constraint on F-PLN page of MCDU but no constraint on ND (even when changing modes, views, zoom levels).
> Also tourned off - on ND - BLUFI still without any CSTR.
> 
> **Overall Rating:** GOOD, except of missing CSTR added in-flight.
> **Conclusions of the testing:** LGTM

The change of the circle color is not included anymore in this PR it's only the constraints symbol. And in order to see the new constraints you need to toggle the CSTR button in order to see the new changes added.

**Comment by stevex77** [comment]
Edited my test report - removed issue and note about circle color. So LGTM. :)

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: Current date 04/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1980
Object of test: Testing the addition of the missing constraint symbol
Testing technique: Try-out 

## Steps you've made to test the Pull Request:

 * Full short flight from C&D.
 * Monitoring the constraints on the ND.
 
## Overall Rating: Good.

#### Conclusions of the testing:

 * Working as documented, LGTM. Thanks!

**Pull request merged**
