### PR TITLE
feat: turn pushback tug with rudder steering

### LINKED ISSUE #5522: Pushback steering via yaw input
### Aircraft Version

Development

### Description

It would be nice if we can steer the pushback left and right via the yaw input.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

KeepGamingLP#4346

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #5522

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ErickSharp** [comment]
Make sure to tie this functionality to a setting and comment it out so we can still have it when we get the cluttered settings page figured out! : D

**Comment by Saschl** [comment]
Good point! Well there’s still some space left :D but I’ll probably add the persistent setting already, thanks

**Comment by Benjozork** [comment]
Yeah someone needs to redesign the settings page with tabs xD

**Comment by wpine215** [comment]
Status of this PR?

**Comment by ErickSharp** [comment]
Saschl added this in FlyPad OS 3. Going to go ahead and close this out.

**Pull request closed without merging**
