### PR TITLE
fix: Quick flight model fix for 1.13.16.0

### LINKED ISSUE #3560: [BUG] A320 pulling up without rotating the joystick
**Mod Version**
I'm using the latest dev. Version.

**Describe the bug**
Since todays World Update UK the A320 is pulling up automaticly at around 120/130 KT without touching the joystick.

**To Reproduce**

1.Start a flight with the Flybywire A320 at any runway
2.Set Takeoff Thrust 
3.The airplane is going to the air without rotating between 110-130 KT. 

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Since the latest World Update UK. 

Is this a problem in the vanilla unmodded game?
Yes also in the official A320. 

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by donstim**
This is a quick fix for the increase in flap lift resulting from MSFS update 1.13.16.0. It also reduces the amount of ground effect floating.

Fixes #3560 

## Summary of Changes

Changes the amount of lift added by flaps. Affects all flap settings. Also reduces ground effect.
## Additional context

Discord username (if different from GitHub):donbikes#4084

## Testing instructions

Perform takeoffs and landings in all approved takeoff (1+F, 2, and 3) and landing (3 and Full) flap configurations and ensure you do not lift off prematurely in takeoff or float excessively in landing nor stall in either case. Use the trim wheel markings and your cg for setting takeoff trim, but it really should be okay with any setting in the green band.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by ZigTag — APPROVED** [review]

**Comment by h20genie** [comment]
Category: Contributer 
Name: h20genie#4343
Date of testing: Current date 16/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3564
Tier of testing: N/A (providing feedback to help)

Changes to observe:

(Perform take off and landings to test flap performance behavior with 1+F,2,3 and FULL. 
To test premature lift or heavy decent rates and pitch angles)

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:

1. Loaded a short flight from KLAS TO KPHX. Set Trim + Flaps to 1/UP1.0

2. SET V1 SPEED TO 140 VR TO 145 V2 TO 150. FLAPS 1 for TAKE OFF

3. Rotated aircraft at 145 with no premature lift or tail strike. 
Climbed at about 12.5 degrees of the pitch until engaging AP. 
Retracted flaps as indicated on PFD with no abnormal behavior and reduced thrust to climb.
Aircraft climbed at about 6 degrees of pitch to flight levels until cruising altitude.

4. Observed cruise behavior with aircraft maintaining 2.5 degrees of pitch.

5. Selected flaps during descent and approach as appropriate for speeds. 
CAT 3 SINGLE ILS Landing. Disconnected AP at 500FT AGL. Flew manually. 
Aircraft behaved normally when flaring with no float or extreme rate of descent. 

Flight notes (When done a full flight):

Modified aircraft CFG in custom FBW version. 
Observed no premature lift or struggle to take off when changes were done to aircraft CFG as described in the PR# 3564.
Observed no struggle to decent with selected flaps at appropriate speeds during descent or landing. 
No extreme floating or hard landing due to lack of lift.

Media: N/A

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good

Conclusions of the testing: Make a small description to areas where it needs to be improved and recommendations.

**Comment by Watsi01** [comment]
Category: Contributer
Name: Watsi01
Date of testing: 17/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3564
Tier of testing: N/A (providing feedback to help)

Changes to observe:

(Perform take off and landings to test flap performance behavior with 1+F,2,3 and FULL.
To test premature lift or heavy decent rates and pitch angles)

Steps you've made to test the Pull Request:

    Took a normal flight from EDLP to EGGP  - set flaps/trim to 1/---

    Set V speeds according to MCDU suggestions for TAKE OFF

    Rotated aircraft with no premature lift or tail strike (10° pitch up).
    Initial climb up to 17° pitch up until acc height. Pitch down as commanded to accelerate.
    Retracted flaps as indicated on PFD with no abnormal behavior and reduced thrust to climb.
 
    Observed cruise behavior (FL340) with aircraft maintaining 2.5-3.5° pitch (TO weight ~63t).

    Selected flaps during descent and approach as appropriate for speeds.
    CAT 3 SINGLE ILS Landing. Disconnected AP at 1000FT AGL. Flew manually.
    Aircraft behaved normally when flaring with no float or extreme rate of descent.

Flight notes (When done a full flight):
Observed no premature lift or struggle to take off.
Observed no struggle to decent with selected flaps at appropriate speeds during descent or landing.
No extreme floating or hard landing due to lack of lift.

Media: N/A

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good

Conclusions of the testing: All good.

**Comment by NonstopFlying** [comment]
Category: QA Trial
Name: NonstopFlying #6771
Date of testing: Current date 17/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3564
Tier of testing: 3
Changes to observe:

Perform takeoffs and landings in all approved takeoff (1+F, 2, and 3) and landing (3 and Full) flap configurations and ensure you do not lift off prematurely in takeoff or float excessively in landing nor stall in either case

Testing technique: Landed and started the airplane multiple times in Liverpool
Steps you've made to test the Pull Request:

1. Spawned in at Liverpool and inserted all the data into the MCDU, started the aircraft and taxied to the runway
2. Took off with Flaps 1+F, no issues
3. Landed with Flaps 3, no issues
4. Took off with Flaps 2, no issues
5. Landed with Flaps Full, no issues 
6. Took off with Flaps 3, no issue
7. Changed the cg and took off and landed, no issue

Overall Rating: Good
Conclusions of the testing: 
In my observation it fixed the issues that Asobo implemented with the Flaps, but after using this artifact the issues seem to be removed. I performed this for a longer amount of time and had no issues, feels just like how it was before the update.

**Comment by easyjetsimpilot** [comment]
Category: QA Tester
Name: Gavin (easyjetsimpilot)
Date of testing: Current date 17/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3564
Tier of testing: 
Changes to observe:

Performed a flight (4.15hrs). Set Trim + Flaps to 1 for dept with trim required for CoG

V speeds calculated in MCDU and performed take off - no pre-rotation observed and climbed normally. Flaps 0 resulted in normal behaviors. 

Flaps 1 (+F) selected on approach - NO ballooning affect caused, remained almost level flight. The same followed with further flap extension.

Flight notes (When done a full flight):
Aircraft performed as it should with all flaps settings (with the exception of Flaps 1+F still being deployed on approach (only Flaps 1 should be set on approach). 

Media: full flight available to see at:- https://youtu.be/koFn3h6mVlc
Issues (If Any): None

Overall Rating: Good

Conclusions of the testing: Good work and seems to have fixed the issue caused by the MSFS world update 3.

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3564 
Tier of testing: 3

### Changes to observe: flightmodel changes

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on runway at VABB for each test.
2. Departed 1 time each with Flaps 1+F, 2 and 3. 
3. Aircraft didn't lift on it's own even after passing Vr+20kts
4. Aircraft only lifts on pulling back the stick
5. Tried a few different approaches with different flap configs (3 and FULL)
6. Excess float is fixed. Aircraft is under control on ideal approaches.

### Overall Rating: Good

### Conclusions of the testing: An effective fix for the issue introduced in the flight model by the World Update.

**Comment by danbw9** [comment]
Category: Accuracy Check
Name: danbw9#7028
Date of testing: 16/02/2021 - 17/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3564
Tier of testing: Tier 3

What was initially observed:

Right after the UK World Update, flew the aircraft using the development and custom flybywire versions right after the update. Recognized that the pitch power settings in different configurations were noticeably off. First seen on approach: expecting a nose up atitutude of 2.5-3 degrees once stablized. Instead seeing the nose down attitude of 1 degree nose down. Then on landing, the normal flare didn't work as expected and aircraft floated. 

What was clear is that both changes to the flight model have created an exaggerated lift effect that creates a feel that with for example: 100 knots on approach would give correct visual picture as opposed to the computed VAPP of 130

Flying without flaps extended meant the usual pitch attitudes were observed so concluded the flap lift or drag parameters had to be edited on our end. 

The only changes that we have acknowledged at the time of writing this report are the following:
- Wrong flap lift coefficient values
- Wrong ground effect coefficient values.

Testing technique: Try-out multiple take offs, approaches, landings + full flight from ESGG to EKCH. Testing wide range of scenarios across the different branches to produce a value that would work for all. 

Steps you've made to test the Pull Request:

Tested development version, custom flybywire & custom autopilot branches in different airports/weather conditions/weight configurations to check for consistency. 

Took off in different flap configs (1+F, 2 & 3) and the expected behaviour was seen. No red flags. As a side test, tried the auto-flap retraction at 210 knots to monitor what would happen. No issues. 

Approaches: for all versions tried default payload + my own config with 3 T and full load (varying CoG)

Experimental custom flybywire:
- several approaches in flap 3 and flap full
- appropriate sidestick pressure to flare at 20-30 ft in a 700 fpm descent on non sloped RWY. All good.
- Tried both positive firm landing and a purposeful attempt to float for smoother touchdown; achieved what I expected. 
- The 'right' amount of ground effect is now experienced and floating is now more at the discretion/mistake of the pilot rather than the overexaggerated ground effect that the sim produced before. 

Development version:
- spawned on approach for flap 3 and flap full landings. Visual picture correct, looking out and on PFD too.
- compared to the experimental versions, having to use more sidestick pressure to achieve a proper flare (at 20 ft instead of 10ft ) but still with more a tendency to float (as like before world update)

Experimental Custom autopilot (autoland test):
- Flew an autoland into EKCH 22L. 13 knot X-wind from left. No issues seen. 
- Second autoland attempt into EGCC ILS 23R (with a hump in TDZ). No issues and the system handles the new ground effect behaviour fine, same as before the World Update in my eyes with the new changes to the FLARE law working very well. 


Flight notes (When done a full flight):

- CUSTOM AP. Normal start-up, taxi, take off, climb out off EKCH in FLAP 1+F. Acceleration with AP on to get past S speed was normal. 

- CRZ at FL330 and on speed and stable: 3 degree nose up attitude expected and observed. 

- Descending into ESGG for RWY21 and did approach like usual. CDA. Configuring flap 1 and 2 whilst in continuous descent. Flap 1 with slats, no drag. Flap 2 producing drag and a deceleration as what I would expect until on final approach.

- In my eyes whilst descending on the glide (3 degrees profile + 10 knots HWC), Flap 2 and gear down should produce more deceleration rather than the speed hanging around 160-170 knots - with a target of F speed for Flap 2 being around 140. IIRC, this was still an issue before though. 

- Gear down, then Flap 3 and full selected and seen what I expected. 

- Good WXR conditions  with light wind. Flare and touchdown all fine. No issues.

Media: N/A

Issues (If Any): None

Overall Rating: Good

Conclusions of the testing:

LGTM. Coordinated with @donstim the change in the values of ''lift_coef_flaps'' which was set on 2.4 on our end. After internal changes from Asobo, this was not appropriate for our mod packaged flight model cfg file. 1.45 was tried but we settled on 1.2. This final value was tested and confirmed to work fine with @aguther. 

Whilst I am happy with how the aircraft flight model performs after a few hours of testing with the PR changes, there will probably be other more complete fixes. I feel there are likely other changes made my Asobo, so those changes need to be investigated. On the surface it seems that only the flap lift is what created the odd pitch attitudes along with the ground effect changes when on RWY, but there is likely more to it...

As I have only flown the custom flybywire and custom autopilot branches for the past few months, the flight model behaviour in terms of the flare on landing for that is my reference point and what I compare to. I did several landings on the development, the flare needed more back pressure on the sidestick as it feels more 'sluggish', whilst this is not what users may have felt before the update, though it means that the pilot needs to flare at 20-30 ft (assuming normal descent rate) which is FCTM procedure. Instead of 10 ft. We decided to keep the values the same for all versions for now, maybe to be tweaked later once we have a more complete picture of what other aerodynamics/flight model changes were made. 

Thanks a lot to @donstim who we can always rely on this kinds of fixes.

**Comment by delta5150** [comment]
I am new here. First off thank you so much FBW team for everything you all do. It is amazing, thank you so much! I tried to find the new config file as stated above but I can't seem to find it. Please help. I truly enjoy flying this mod very much. Any help would be appreciated.

**Comment by marinerhally** [comment]
Category: QA Trial
Name: Mariner Hally#0715
Date of testing: 17/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3564
Tier of testing: 3
Changes to observe:
Changes the amount of lift added by flaps. Affects all flap settings. Also reduces ground effect.

Testing technique: Short Flights
Steps you've made to test the Pull Request:
1. Spawned in at EGNJ
2. Prepared aircraft and configured for Flap 1 T/O
3. Flew circuit and landed Full Flap Config
4. Spawned in at EGCN
5. Prepared aircraft and confirgured for Flap 2 T/O
6. Landed at EGNJ Full Flap Config
7. Spawned in at EGCC
8. Prepared aircraft and configured for Flap 3 T/O
9. Flew to EGGP and Landed Flap 3 config

Flight notes (When done a full flight):EGNJ(1 Circuit), EGCN-EGNJ, EGCC-EGGP

Media:

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: No problems on any T/O or Landing, fast fix after the update :)

**Pull request merged**
