### PR TITLE
[CDU] Implement proper flight plan data update and DECEL management

### LINKED ISSUE #248: FMS distance page does not update
FMS distance page does not update

### LINKED ISSUE #1363: [BUG] ETAs wrong in MCDU (either all zeros or going back in time)
**Mod Version**

 
master as of 13.10.2020

**Describe the bug**

The estimated time of arrival at a point is wrong on several intermediate points on the MCDU.

**To Reproduce**

1. Start a flight (probably best C&D and start the plane)
2. Enter a flight into the MCDU, for example EPGD/EPWA
3. Add SID and STAR
4. Add intermediate points (generated by SimBrief or some other flight planner)
5. Look at the ETAs for each point

**Expected behavior**

ETAs beside every waypoint show approximate time of arrival at the waypoint.

**Actual behavior**

It seems like the ETAs are correct for SID, but they are either all zeros or go back in time for the intermediate points. I believe that STAR isn't all correct either, but can't check right now (can't start the game for now)

**References**

Sorry, unfortunately none

**Additional context**

Was this working before/when did the issue start occurring? I have always seen this manifest itself in the flight

Is this a problem in the vanilla unmodded game? I think so, yes, but I haven't played the latest vanilla.

Discord username (if different from GitHub): acro#2421

### LINKED ISSUE #1518: FMC distance to destination not changing during flight[BUG]
**Mod Version**

latest developer version build_info.txt file not found - use auto installer

**Describe the bug**

FMC distance to destination not changing during flight - it stays the same and should be showing nm remaining during flight

**To Reproduce**

1. open any flight plan
2. load into FMC
3. fly the plan

**Expected behavior**
it stays the same and should be showing nm remaining during flight

**Actual behavior**
it stays the same distance at all times

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by lousybyte**
### Rework of #1505 with additional changes
Fixes #248
Fixes #1363 
Fixes #1518

## Summary of Changes

EDITED:

- Time shown will now change from relative to UTC depending on conditions
- Distance and time to the active waypoint are now updated
- Distance and time to DEST are now updated
- The time when the previous waypoint was reached is now showed
- Updated font size to be more inline with real life
- APPR phase managed activation now requires to be below 9500 AGL 
- DECEL time and distance are now updated
- DECEL will now always show in the right position in the flight plan
- DECEL altitude should be more closer to the descent path
- DECEL position should now be closer to the flight plan path
(Note: DECEL distance along the flight path was not changed, will be the scope of a separate PR since it requires some attention on its own, currently it's still at an arbitrary 32NM before DEST)
 
## Additional context

EDITED:
Please test as much as possible since there's a lot of code changes, also please include the flight plan if you encounter an issue and mention if you use Navigraph or default nav data.
Note: 1-2min or 1-3nm values inconsistencies are normal due to rounding errors and logic update speed.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by edubla20** [comment]
El FMC/CDU con la última actualización de fsx, no se enciende en A32 NX.

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 02/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1652
Object of test: Check functionality of the F-PLAN data in MCDU and new accurate DECEL indicator. 

Testing technique: 2 flights. UUDD to UAAA. And Flight starting C&D from UAAA to LTFM. Putting the changes made in this PR into practice - as if doing a normal flight. 

Steps taken:

Completed 2 different flights. Cross checking info and values in MCDU versus the Flight Plan. Some calculations are off probably due to no wind forecast implemented and the average wind component not working apart from as an input on INIT B. 

Info on preceding waypoint pretty useful for time checks.

Checking the transition from Relative time to UTC actual time checks out with take off thrust applied. 

DECEL indication is now correct and. However it was off when I loaded in from a saved flight (spawning midflight) and could not select STAR. DECEL indication was not on the green F-PLAN line.

Waypoint ETAs look a lot better being in the smaller font versus the waypoint names for example. 

Flight notes:

Startup: Everything normal. Once full route input checked. The Relative time from 0000 to DEST (UAAA) was way off. 03h50min flight showing 05h38min. Assuming 0 wind. 

Taxi/Takeoff : Everything normal

Cruise: Everything normal. Checking distances, times and see as they dynamically change as for example when spot winds are different to the forecast. 

Descent/Approach/Landing: Everything normal. keeping an eye on DECEL point. 

Shutdown: Everything normal

Issues: A small bug with DIRECT TO feature producing strange things in F-PLAN page (see image at end of comment) 
Overall Rating: Good
Conclusions of the testing: Thanks for your work! Some great additions here. A small issue as a result of a separate bug with when I was going DCT to waypoints - that function itself is buggy which is separate. It leads to the actual distance to go being inaccurate and higher than should be as it counts the backtracking of the route. In case others come across that. A small issue with this PR is that going direct to waypoints - it replaced the time UTC arrival time and put in some random data 'NA' (not available?).

Screenshot (532)

**Comment by lousybyte** [comment]
> ECEL indication is now correct and. However it was off when I loaded in from a saved flight (spawning midflight) and could not select STAR. DECEL indication was not on the green F-PLAN line.

Loading saved flights is very buggy, I remember the flight plan being completely erased and other things not being set up at all. I think a separate PR dedicated to this entirely is needed.

> The Relative time from 0000 to DEST (UAAA) was way off. 03h50min flight showing 05h38min. 

The ETA is calculated based on your current GS. Any chance you have the flight plan route to double check?

> A small issue as a result of a separate bug with when I was going DCT to waypoints - that function itself is buggy which is separate. It leads to the actual distance to go being inaccurate and higher than should be as it counts the backtracking of the route. In case others come across that. A small issue with this PR is that going direct to waypoints - it replaced the time UTC arrival time and put in some random data 'NA' (not available?).

Was this for cruise phase or approach? Changing anything once you entered approach, including initiating a DIRECT TO, is very buggy - I've noticed that even tho the plane appears to follow the path fine, once it reaches the DT waypoint, the whole plan gets reloaded and the plane steers back to the first waypoint of the flight plan. This behavior might be why you see huge distances again, and it's technically working as intended since the active waypoint is miles behind you. The solution I found was to force a DT again and manually delete the reloaded waypoints before it.

The NaN shouldn't be there tho, will look into it.
Again, if you by any chance can share the route it would be helpful.

**Comment by danbw9** [comment]
@lousybyte 

So yeah the FPL route I used for UUDD - UAAA is this one:

OKR14G RELTO B923 OGAPO T573 BEKAS L163 SIVKO M166 AKB R366 DZG W86 DIPEN DIPE5L

I had the issue in descent and approach when I was using the DCT to function. And yeah its super buggy! I do try to delete the waypoints preceding the waypoint I am going direct to but in the MCDU F-PLAN page it does not always let me. But you are correct! the distance is all correct its just the separate issue. 

And yeah the 300 kts in the calculation would give that time. Is the 300 kts documented in a manual somewhere? Often when I am flying IRL on the ground in setting up, I check the distance and estimated time for the flight (of course it has the wind to make it accurate too). It can calculate a TAS for the given FL expected as well as the temperature at that CRZ LVL. Then apply Wind forecast and get GS. Saying that, its not always totally accurate but not far off.

**Comment by lousybyte** [comment]
> And yeah the 300 kts in the calculation would give that time. Is the 300 kts documented in a manual somewhere? Often when I am flying IRL on the ground in setting up, I check the distance and estimated time for the flight (of course it has the wind to make it accurate too). It can calculate a TAS for the given FL expected as well as the temperature at that CRZ LVL. Then apply Wind forecast and get GS. Saying that, its not always totally accurate but not far off.

No official source, just needed to use a value until airborne, and chose that since it's usually at transition level, can bump it up to 400 if needed which would be closer to high altitude cruise speeds.
As far as I know there is a lot of work being put into getting predicted wind data that could be used in a lot of areas, including in better estimations for this, but until then it's just simple math for now. Also wind calculations will only work as long as the actual weather simulation is on point in the game, which is still having issues afaik, so we're a bit away from that.

**Comment by z0rgmeister** [comment]
Name: z0rgmeister#8972
Date of testing: 02/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1652
Object of test: To test flight plan data updates and DECEL management as per PR.
Steps taken: Full LEMD-LPPT flight from C&D.

Flight notes: From C&D Stand 600 LEMD to Shutdown at Gate 4 LPPT // Route used - LEMD/36R CCS4W CCS UL185 PORTA DCT IDBID IDBI7B LPPT/21 //FL280//. 

Taxi/Takeoff : Nothing to observe.

Climb/Cruise: Changed Climb and CRZ speed, observed waypoint and final destination ETA change accurately.

Descent/Approach/Landing: Managed SPD descent at 265 to FL100, 220 to FL4000, DECEL too early horizontally. Unclear vertically. Ended up too high on FAF having to apply manual speedbrakes to descend and bring the plane down.

Shutdown: NA

Issues: (DECEL) position not clear vertically. Long horizontally. 

Overall Rating: Good, some notes.

Conclusions of the testing: Good job on the TIME estimations for both waypoints and final destination as well as TIME at previous waypoint. 
Couldn't work out if I did a bad job of managing DECEL or if it was having issues calculating or adjusting where it should be. It did end up long (30NM from FAF and at 9200 ft with 5200 ft vertically to go to FAF). From my understanding it should bring us very close to the FAF altitude and position. Probably easier said than done, I know. On that note the (DECEL) waypoint was also outside the path but manageable as it was on a curve to a waypoint, not an issue per se.

On another note don't know how complicated it would be to keep the header (FROM TIME SPD/ALT) "frozen" when scrolling down the MCDU as I believe this is the implementation on the real thing, would have to be confirmed by people who actually have access to the airplane though.

**Comment by z0rgmeister** [comment]
Name: z0rgmeister#8972
Date of testing: 02/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1652
Object of test: To test flight plan data updates and DECEL management as per PR.
Steps taken: Full LEMD-LPPT flight from C&D.

Flight notes: From C&D Stand 600 LEMD to Shutdown at Gate 4 LPPT // Route used - LEMD/36R CCS4W CCS UL185 PORTA DCT IDBID IDBI7B LPPT/21 //FL280//. 

Taxi/Takeoff : Nothing to observe.

Climb/Cruise: Changed Climb and CRZ speed, observed waypoint and final destination ETA change accurately.

Descent/Approach/Landing: Managed SPD descent at 265 to FL100, 220 to FL4000, DECEL too early horizontally. Unclear vertically. Ended up too high on FAF having to apply manual speedbrakes to descend and bring the plane down.

Shutdown: NA

Issues: (DECEL) position not clear vertically. Long horizontally. 

Overall Rating: Good, some notes.

Conclusions of the testing: Good job on the TIME estimations for both waypoints and final destination as well as TIME at previous waypoint. 
Couldn't work out if I did a bad job of managing DECEL or if it was having issues calculating or adjusting where it should be. It did end up long (30NM from FAF and at 9200 ft with 5200 ft vertically to go to FAF). I don't believe the flight path should give us a -300 descent rate to FAF below 10,000. On that note the (DECEL) waypoint was also outside the path but manageable as it was on a curve to a waypoint, not an issue per se.

On another note don't know how complicated it would be to keep the header (FROM TIME SPD/ALT) "frozen" when scrolling down the MCDU as I believe this is the implementation on the real thing, would have to be confirmed by people who actually have access to the airplane though.

**Comment by lousybyte** [comment]
> Descent/Approach/Landing: Managed SPD descent at 265 to FL100, 220 to FL4000, DECEL too early horizontally. Unclear vertically. Ended up too high on FAF having to apply manual speedbrakes to descend and bring the plane down.

> Issues: (DECEL) position not clear vertically. Long horizontally.

> Conclusions of the testing: Good job on the TIME estimations for both waypoints and final destination as well as TIME at previous waypoint.
> Couldn't work out if I did a bad job of managing DECEL or if it was having issues calculating or adjusting where it should be. It did end up long (30NM from FAF and at 9200 ft with 5200 ft vertically to go to FAF). I don't believe the flight path should give us a -300 descent rate to FAF below 10,000. On that note the (DECEL) waypoint was also outside the path but manageable as it was on a curve to a waypoint, not an issue per se.

DECEL distance along the flight path was not changed, will be the scope of a separate PR since it requires some attention on its own, currently it's still at an arbitrary 32NM before DEST. Will add this to the PR description for future testers.
DECEL being outside the flight plan path is an issue and should not happen, will take a look at it - thank you for including the flight plan!

> On another note don't know how complicated it would be to keep the header (FROM TIME SPD/ALT) "frozen" when scrolling down the MCDU as I believe this is the implementation on the real thing, would have to be confirmed by people who actually have access to the airplane though.

It should be pretty easy to change if it gets confirmed, I'll poke around.

Thank you for testing!

**Comment by lousybyte** [comment]
> DECEL being outside the flight plan path is an issue and should not happen, will take a look at it - thank you for including the flight plan!

Looked at it and it seems it's a problem with the ND drawing the flight path, it misses the RINOR waypoint slightly when trying to curve around, and DECEL being so close it gets missed as well, since DECEL position is dependent on the waypoints surrounding it. 




It's outside the scope of this PR, might take a look at it after.

**Comment by Noxleee** [comment]
Name: Noxlee #7727
Date of testing: Current date 04/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1652
Object of test: To test flight plan data updates and DECEL management as per PR.

Testing technique: Flight from LFSB to LOWI -> LFSB/33 F230 ELBEG7N ELBEG Y715 AMRUP N491 DEGES UN871 GAMSA N871
MADEB MADEB1B LOWI/08
Steps you've made to test the Pull Request:
1. Load up AC
2. Program FMC
3. Fly

Flight notes

Startup: I could hear Pull Up from the EGPWS until nav was aligned.

Taxi/Takeoff : Everything is normal

Cruise: Everything is normal

Descent/Landing : Everything is normal

Shutdown:  I could hear Pull Up from the EGPWS when setting navs to off

Issues (If Any): 
Overall Rating: To be improved
Conclusions of the testing: 
First off all, everything’s gets updated like it is described. 
Predicted time was 25 mins and I needed 38 mins.
The predicted arrival time in flight was not that accurate, maybe because of this is a short route with many speed changes. I guess that could be only fixed with a proper L and VNAV system.
In this screenshot you can see that DECEL is behind ELMEM but the time at ELMEM is 0020 and DECEL is 0018. ELMEM and DECEL where at the same point on the route.
grafik

 
I found another Bug with the DECEL time:
grafik
DECEL time got a random number at some point.

And not to forget the described Sound from the EGPWS.

Besides that, this is a great PR and works well!

**Comment by lousybyte** [comment]
> Predicted time was 25 mins and I needed 38 mins.
> The predicted arrival time in flight was not that accurate, maybe because of this is a short route with many speed changes. I guess that could be only fixed with a proper L and VNAV system.

Indeed time prediction is a rough estimate and it's heavily dependent on your current speed at this moment.

> In this screenshot you can see that DECEL is behind ELMEM but the time at ELMEM is 0020 and DECEL is 0018. ELMEM and DECEL where at the same point on the route.
> 
> DECEL time got a random number at some point.

Will try to figure out what's happening there, shouldn't happen.

> And not to forget the described Sound from the EGPWS.

Not sure how that is triggered, shouldn't be impacted by this, will take a look.

Thank you for testing!

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 07/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1652
Object of test: Check updated functionality of the F-PLAN data in MCDU (including check on DECEL)

Testing technique: Try out in different scenarios (flying as usual with normal procedures) 2 flights. UACC to UAAA. 

Steps taken:

Completed 2 different flights over the last few days with this PR. Cross checking info and values in MCDU versus the Flight Plan. Some calculations are off probably due to no wind forecast implemented and the average wind component not working apart from as an input on INIT B.

Checked all functionality from before and works as per the PR items. 

Checking the transition from Relative time to UTC actual time checks out with take off thrust applied.

DECEL indication all fine.

Flight notes:

Startup: Everything normal. Once full route input checked cross checked the data from flight plan. The Relative time from 0000 to DEST (UAAA05R) was now much more accurate. I did a 1h24 min flight and 1h23mins (0123) was showing as the relative time estimate. Assuming 0 wind. Had a average tailwind component of 18 kts.

Taxi/Takeoff : Everything normal

Cruise: Everything normal. continued checking distances, times and see as they constantly change as for example when spot winds are different to the forecast.

Descent/Approach/Landing: Everything normal. Monitoring track miles to go to DEST RWY (in this case UAAA05R), able to accurately do a CDA with the dynamic distance to go.

Shutdown: Everything normal

Issues: None. Previous issues gone.
Overall Rating: Good
Conclusions of the testing: LGTM. Thank you for the corrections! I wrote up a testing report just under a week ago and remarked a couple bugs which I cannot recreate. No new issues reported. The revision of the average speed for time calculation through F-PLAN works very well compared to before. More reliable but of course without wind data its a little off. For long flights with unusually higher average tailwind or headwind components, it may be off, but for the most part works great.

**Comment by lousybyte** [comment]
> In this screenshot you can see that DECEL is behind ELMEM but the time at ELMEM is 0020 and DECEL is 0018. ELMEM and DECEL where at the same point on the route.
> 
> DECEL time got a random number at some point.

This should be fixed now.

> And not to forget the described Sound from the EGPWS.

I couldn't replicate this at all, might not be related to this PR.

**Comment by ashwath84** [comment]
> ### Rework of #1505 with additional changes
> Fixes #248
> Fixes #1363
> Fixes #1518
> 
> ## Summary of Changes
> EDITED:
> 
> * Time shown will now change from relative to UTC depending on conditions
> * Distance and time to the active waypoint are now updated
> * Distance and time to DEST are now updated
> * The time when the previous waypoint was reached is now showed
> * Updated some visuals to be more inline with real life
> * APPR phase managed activation now requires to be below 9500 AGL
> * DECEL time and distance are now updated
> * DECEL will now always show in the right position in the flight plan
> * DECEL altitude should be more closer to the descent path
> * DECEL position should now be closer to the flight plan path
>   (Note: DECEL distance along the flight path was not changed, will be the scope of a separate PR since it requires some attention on its own, currently it's still at an arbitrary 32NM before DEST)
> 
> ## Screenshots (if necessary)
> 
> 
> 
> 
> ## References
> 
> 
> 
> ## Additional context
> EDITED:
> Please test as much as possible since there's a lot of code changes, also please include the flight plan if you encounter an issue and mention if you use Navigraph or default nav data.
> Note: 1-2min or 1-3nm values inconsistencies are normal due to rounding errors and logic update speed.
> 
> ## How to download the PR for QA
> Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
> The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.
> 
> 1. Make sure you are signed in to GitHub
> 2. Click on the **Checks** tab on the PR
> 3. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

Hi..just tested this PR and noticed that an ILS Approach planned in the World Map is now loaded twice in the CDU inside the aircraft...this was working fine a couple of days back. Did a flight from EGLL 09L (SID - CPT4K) to EIDW 10R (STAR - LIPG1R). The SID was perfect while the STAR and ILS approaches were loaded twice in the CDU. Thanks for checking.

**Comment by ashwath84** [comment]
Hi..just tested this PR and noticed that an ILS Approach planned in the World Map is now loaded twice in the CDU inside the aircraft...this was working fine a couple of days back. Did a flight from EGLL 09L (SID - CPT4K) to EIDW 10R (STAR - LIPG1R). The SID was perfect while the STAR and ILS approaches were loaded twice in the CDU. Thanks for checking.

**Comment by lousybyte** [comment]
> Hi..just tested this PR and noticed that an ILS Approach planned in the World Map is now loaded twice in the CDU inside the aircraft...this was working fine a couple of days back. Did a flight from EGLL 09L (SID - CPT4K) to EIDW 10R (STAR - LIPG1R). The SID was perfect while the STAR and ILS approaches were loaded twice in the CDU. Thanks for checking.

Cannot replicate, and don't see how this PR could affect what waypoints are loaded, try a clean PR install and give a feedback after please.

**Comment by beheh** [comment]
This might be out of scope, but as you've adjusted the size of the time in the FPLN page I noticed a new visual discrepancy between the screenshots and the reference: the time is aligned to the top of the waypoint name in your screenshots, whereas in the reference it is aligned to the bottom of the waypoint name.

**Comment by flightsimsimon** [comment]
Name: Discord User FlightSimSimon#1370
Date of testing: Current date 07/11/2020
Version of the sim: Version the tester uses 1.10.7
PR Tested: #1652 
Object of test: (ECAM Page or Flight model or views or anything, what the PR modifies)

Time shown will now change from relative to UTC depending on conditions - Pass

Distance and time to the active waypoint are now updated - Pass

Distance and time to DEST are now updated - Pass

The time when the previous waypoint was reached is now showed - Pass

Updated some visuals to be more inline with real life - Please advise what visuals

APPR phase managed activation now requires to be below 9500 AGL - Pass

DECEL time and distance are now updated - Pass

DECEL will now always show in the right position in the flight plan - Pass

DECEL altitude should be more closer to the descent path - Pass

DECEL position should now be closer to the flight plan path - PASS
(Note: DECEL distance along the flight path was not changed, will be the scope of a separate PR since it requires some attention on its own, currently it's still at an arbitrary 32NM before DEST)

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Full flight from EGBB to EGPH manually adding flight plan
2. Using REX live weather, FS2CREW Pushback express
3. 
4.
5.

Flight notes

Startup: Notes on the startup (Everything is normal, or I noticed something weird)
All times show as zero before take off

Taxi/Takeoff : Notes on the taxi an takeoff (Everything is normal, or this time the climb rate seems bigger than usual)
nothing other than above

Cruise: Notes on cruise (Everything is normal, or I noticed something)
Times adjust on take off, everything is normal

Descent/Landing : Notes on descent and landing (Work as expected or this time the descent rate seems bigger than usual)
The DECEL time was wrong on the MCDU

image


Shutdown: Notes on the shutdown of the aircraft
All was OK and as expected
Issues (If Any): Wrong time on DECEL on the MCDU apart from that, all was OK

Overall Rating: Good/To be improved
No flight issues at all other than DECEL time wrong

Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.

FinalLight-NL, z0rgmeister, SmallLackey

**Comment by lousybyte** [comment]
> This might be out of scope, but as you've adjusted the size of the time in the FPLN page I noticed a new visual discrepancy between the screenshots and the reference: the time is aligned to the top of the waypoint name in your screenshots, whereas in the reference it is aligned to the bottom of the waypoint name.
> 
> Looking at the overall layout it seems like the middle (non-top/bottom) waypoint names are not correctly aligned to the right half of the FPLN page. First and last item look good though.

Reference SS includes the origin (same as prev wp), this one was scrolled down to show the approach waypoints, no alignment or top row visuals were changed.

**Comment by lousybyte** [comment]
@flightsimsimon do you have the flight plan by any chance? And was the approach preloaded or added during flight?
Thanks for testing!

**Comment by flightsimsimon** [comment]
The approach was loaded manually 

Flight plan 

EGBB/33 DCT LUVUM DCT TNT N57 POL UN601 INPIP DCT EGPH/06

**Comment by beheh** [comment]
>  Reference SS includes the origin (same as prev wp), this one was scrolled down to show the approach waypoints, no alignment or top row visuals were changed.

Sorry, I might've not been clear. The alignment of the top row matches the reference, but this PR adjusts the size of the UTC/Time rows for the non-top row, so that they are no longer aligned with the bottom of the waypoint name.

Please see the following screenshot which is made up of the reference and a screenshot from the top PR comment:

image

Note how in the reference, the small time (0002) is aligned to the bottom edge of the waypoint name (orange space is above 0002).
In your screenshot however, the small time (0013) is aligned to the top edge of the waypoint name (orange space is below 0013).
I've added the purple lines for clarity.

**Comment by ashwath84** [comment]
> > Hi..just tested this PR and noticed that an ILS Approach planned in the World Map is now loaded twice in the CDU inside the aircraft...this was working fine a couple of days back. Did a flight from EGLL 09L (SID - CPT4K) to EIDW 10R (STAR - LIPG1R). The SID was perfect while the STAR and ILS approaches were loaded twice in the CDU. Thanks for checking.
> 
> Cannot replicate, and don't see how this PR could affect what waypoints are loaded, try a clean PR install and give a feedback after please.
> 
> 

hi...I never test multiple PR's. This was the only PR I tested. But maybe it was a one off...let me try redownloading again now and testing...will report back

**Comment by ashwath84** [comment]
Hi...I can confirm that the issue still persists with the latest PR (only tested this PR). ILS Approaches load fine if entire flight plan is entered from scratch via CDU, however, the approaches are loaded twice if the flight plan is created in the world map. (Attaching some screenshots for reference):
Microsoft Flight Simulator 08-11-2020 15_28_41
Microsoft Flight Simulator 08-11-2020 15_38_53
Microsoft Flight Simulator 08-11-2020 15_39_17
Microsoft Flight Simulator 08-11-2020 15_39_36
As you can see, after ULTAG i have some waypoints that aren't even in the world map and OTNER is repeated twice. Never had this issue when I tested this PR a couple of days back. Only workaround now is to delete those additional waypoints. Thanks for checking.

**Comment by lousybyte** [comment]
@ashwath84 I can't replicate that at all, the total time is 0046 for me with no duplicates, are you on the latest MSFS 1.10.7 version?

**Comment by luke-stec** [comment]
@lousybyte Any way you can merge the latest master into this for testing?

**Comment by ashwath84** [comment]
> @ashwath84 I can't replicate that at all, the total time is 0046 for me with no duplicates, are you on the latest MSFS 1.10.7 version?

yep...I am using the latest windows store version (1.10.8). Strange that only I am reporting this issue. Everything else in the flightplan works flawlessly for me just the duplicate approach loading is a problem. I will use the workaround for now and perhaps wait for a more stable version :) thanks !!!

**Comment by Benjozork** [comment]
@luke-stec testing needs to be complete before merging to master

**Comment by Noxleee** [comment]
Name: Noxlee #7727
Date of testing: Current date 09/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1652
Object of test: To test flight plan data updates and DECEL management as per PR.

Testing technique: Flight from LFSB to LOWI -> LFSB/33 F230 ELBEG7N ELBEG Y715 AMRUP N491 DEGES UN871 GAMSA N871
MADEB MADEB1B LOWI/08 (same flight as first time)
Steps you've made to test the Pull Request:

   1. Load up AC
   2. Program FMC
   3. Fly


Issues (If Any):
Overall Rating: Good
Conclusions of the testing: I tested this PR the second time. All things that I mentioned before are fixed now, cannot find an issue anymore. Great work!

**Comment by Carter633** [comment]
@ashwath84 the issue you describe is an Asobo flight planning issue - it's on the official MSFS forums from back in August. Always been an issue where approaches or STARs get mucked up - especially in World Map. Interestingly it's more accurate if you plan it all in the MCDU point by point

**Review by Carter633 — APPROVED** [review]
Name: British Avgeek YT ---- Carter#1436
Date of testing: Current date 10/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1652
Object of test: Flight Plan Updates + Decel Management improvements

Testing technique: Flight from EGNM to EGLL comparing yesterday's flight without this PR - same route
ROUTE: POL2X POL DCT MCT DCT LISTO L612 HON BNN4A
Steps you've made to test the Pull Request:
1. Spawn C&D EGNM, configure MCDU for route as mentioned above - check flight plan in Plan mode on ND throughout input.
2. Make a revision to the STAR to see if it impacts the plan negatively or breaks it (sometimes does with Asobo planning)
2. Input all data for complete MCDU, push back start and taxi 
3. Takeoff - observe plan as aircraft flies it, checked WPT timings and estimated arrival
4. Tried to force activate App Mode during cruise at FL190 - refused. Tried again on descent through FL120 - refused. Good work!
5. Noted Decel on the flight plan through STAR - altitude seemed reasonable within the route too


Issues (If Any): None noted on this test!
Overall Rating: Good
Conclusions of the testing: Exact route flown yesterday using another PR for comparison which did not use any of this... Great improvements, couldn't find any issues with it and timings seemed reasonably close too! Good work!

**Comment by ashwath84** [comment]
> @ashwath84 the issue you describe is an Asobo flight planning issue - it's on the official MSFS forums from back in August. Always been an issue where approaches or STARs get mucked up - especially in World Map. Interestingly it's more accurate if you plan it all in the MCDU
> Discord: British Avgeek YT --- Carter#1436 (QA)

ok thank you...will try to use only the MCDU then...cheers !!! I love this PR and this community...keep up the good work team :)

**Pull request merged**
