### PR TITLE
fix(efb): restore interactivity after MSFS 1.14.5.0

### LINKED ISSUE #3887: [BUG] EFB flyPad not Working After Sim Update 3, MSFS Version 1.14.5.0
**Mod Version**

  I am using the Development Version
  "built": "2021-03-10T00:43:09+00:00",
  "ref": "master",
  "sha": "f26a1291f98e395d85427fa4caf9414ef663e0ca",
  "actor": "Benjozork",
  "event_name": "manual"

**Describe the bug**

After Sim Update 3, MSFS  Version 1.14.5.0 the flyPad is non responsive at all.  It turns on by clicking but when I click on any of the functions there is no response.  Also, the flyPad brightness is very dim.

**To Reproduce**

1.  Update sim to version 1.14.5.0, use the above A32NX version and check the flyPad.

### PR DESCRIPTION
**Pull request by Benjozork**
Fixes #3887

## Summary of Changes

* Remove `MouseRect` interactivity preventing use of touchscreen
* Handle interactivity directly inside of React

## Additional context

Discord username (if different from GitHub): someperson#4953

## Testing instructions

* Make sure the EFB can be turned on by clicking on it (tooltip is gone, unfortunate side effect)
* Make sure EFB can be turned off and turned back on

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by myselfaaryan — APPROVED** [review]
LGTM!

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 10/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3889 
Tier of testing: 1
Changes to observe: EFB useability
Testing technique: 
Steps you've made to test the Pull Request:
1. Loaded C&D
2. Played with EFB
3. EFB restart is possible

Media:

Issues (If Any): - 

Overall Rating: LGTM

Conclusions of the testing: Works all fine.

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 10/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3889 
Tier of testing: 1

Changes to observe:
(Insert the Summary of changes, in order to remind what is to test)

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. Spawned C&D at LIRN
2. Tested immediately the EFB
3. All section + Settings are working
4.
5.

Flight notes (When done a full flight):
N/A
Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A
Issues (If Any): Write any issues
N/A
Steps to achieve the issue:
N/A

Overall Rating: Perfect!
Conclusions of the testing: EFB is fully working again! Nice job boys!

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 3/10/2021
Version of the sim: 1.14.5.0
PR Tested: #3889 
Tier of testing: 1
Changes to observe:
Remove MouseRect interactivity preventing use of touchscreen
Handle interactivity directly inside of React

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned C&D at UKBB
2. Turned on plane
3. Turned on efb
4. Played with efb
5. Turned off efb

Flight notes (When done a full flight):

Media: 

Issues (If Any): 
Steps to achieve the issue

Overall Rating: Good/
Conclusions of the testing: No issues everying looks fine and works fine great work.

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 10/3/21
Version of the sim: 1.14.5.0
PR Tested: #3889 
Tier of testing: 1
Changes to observe:
EFB working

Testing technique: loaded in and tried it
Steps you've made to test the Pull Request:
1. Loaded in C&D
2. used EFB
3. Loaded in on runway
4. used EFB

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None
Overall Rating: To be improved
Conclusions of the testing: LGTM

**Comment by Matse08** [comment]
Category: QA Tester
Name:Matse#7454
Date of testing:10.03.21
Version of the sim: 1.14.5.0
PR Tested: #3889 
Tier of testing: 1
Changes to observe:
EFB working
Testing technique: Tried it
Steps you've made to test the Pull Request:
1. Loaded in cold and dark
2. Started EFB
3. Loaded from simbrief and checked many more things
4. Loaded in on approach used the EFB
Issues (If Any): No
Overall Rating:Good
Conclusions of the testing:LGTM

**Pull request merged**
