### PR TITLE
reworked engine start sound

### PR DESCRIPTION
**Pull request by hotshotp**
## Summary of Changes

If you are frustrated with me reworking it, I am sorry, this is probably the final time I do it. This time I spent a good 12 hours perfectly matching up pitches with IRL references to make it so the LEAP startup sounds the same as in the videos.

So the changes are:

Reworked fuel flow sound pitches to correspond to the stages
Reworked the fuel flow deep rumble harmonics to also follow the sound to match IRL
Reworked the ending wobble to be less overdone

Additionally I improved the taxi sound by making it a little less bassy and a little more trebly so it doesn't clip as much

## References

https://youtu.be/pDfmwRlfgHg?t=65 - 1:05 for the swoosh sound
https://www.youtube.com/watch?v=i3y6F2zVD5Q - 1:03 for fuel introduction - the pitches and harmonics for the startup

## Additional context

Discord username (if different from GitHub):

Boris#9134

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: ChristopherXie#3904
Date of testing: Current date 12/20/2020
Version of the sim: 1.11.7.0
PR Tested: #2576 
Object of test: Engine sounds

Testing technique: Spawned on the runway
Steps you've made to test the Pull Request:
1. Spawned on runway 23 at CYYZ, started the APU and turned off the engines
2. Turned on the engines (interior) and listened for changes and turned them off
3. Turned on the engines (exterior) and listened for changes and turned them off
4. Turned on the engines and taxied around
5.

Flight notes (If required):

Issues (If Any): none AFAIK
Overall Rating: Good
Conclusions of the testing: Great job Boris, engine startup is a lot more coherent, and I hope this is the last time you mess with the leaps FFS XD

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 12/21/2020
Version of the sim: 1.11.7.0
PR Tested: #2576 
Object of test: Reworked engine start sound

Testing technique: Startup and shutdown.

Steps you've made to test the Pull Request: 
1. Listened to eng startup and shutdown (Passenger)
2. Listened to eng startup and shutdown (Cockpit)
3. Listened to eng startup and shutdown (Exterior)



Flight notes (If required): Eng startup and shutdown only.

Issues (If Any): None.

Overall Rating: Good!

Conclusions of the testing: Sounds are great! :)

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by TheSledge-SLEJ** [comment]
Love it. Pretty much perfect

**Pull request merged**
