### PR TITLE
fix(isis): force css animations

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Force css animations on in the ISIS.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check that the selected bug in the bugs screen flashes with "menu animations" turned off in MSFS settings.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by BlueberryKing — APPROVED** [review]
LGTM! Although I do wonder if we should make a change like this on a higher level. I think the PFD could also benefit from enabling animations.

I am not the biggest fan of forcing the animations to be enabled to be honest, so maybe we can talk about a few options.

**Comment by tracernz** [comment]
> LGTM! Although I do wonder if we should make a change like this on a higher level. I think the PFD could also benefit from enabling animations.
 I did implement this in DisplayUnit which gets all the 6 display units... but not ISIS.

> I am not the biggest fan of forcing the animations to be enabled to be honest, so maybe we can talk about a few options.

Why? We 100% rely on animations working, so we can either enable them, or rely on a random MSFS setting with no clear linkage for the user to break our instruments.

**Comment by BlueberryKing** [comment]
> Why? We 100% rely on animations working, so we can either enable them, or rely on a random MSFS setting with no clear linkage for the user to break our instruments. This has no effect outside our instruments.

Yes, but I assume the setting is there for a reason. Overriding such a setting always has a risk of breaking something with no way for users to avoid it.

**Comment by tracernz** [comment]
I think they just didn’t consider that CSS animations could also be used in instruments. There’s a reason the setting is labelled “**menu** animations”.

**Pull request merged**
