### PR TITLE
feat(fmgc): runway-by-itself approaches

### LINKED ISSUE #954: [REQUEST] Non instrument (visual) approach
**Describe the feature you'd like to see implemented**

The ability to select a runway on the MCDU that is non RNAV / ILS approach etc. 

To be able to input a 3 or 5nm approach to a runway.

For example, to be able to conduct a visual approach to a runway while still tracking the runway centreline on the autopilot. 

**References**

Best reference I could find is this:

Untitled thumb jpg 962b18cc14981c6a26e848863cecf790

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #954

## Summary of Changes

Adds support runway-by-itself approach, which gives a CF leg on runway course 5 NM long.

Also fixes a small bug with final approaches that creates a lot of uncaught exceptions for RNAV approaches (sentry).

~~Draft as I'm awaiting confirmation of the approach naming... but could still be reviewed before that.~~
Confirmed that the 5 NM fix is simply called "CF", the approach name is just the runway number, and there is no approach message on the ND.

## Screenshots (if necessary)

image
image

## References

Honeywell pilot's guide. Honeywell pilot.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Try adding a runway-by-itself approach (bottom of the approaches list), check that it gives a 5 NM final leg
- Try "regular" approaches to ensure they still work okay

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #6995
Tier of Testing  : 1
Date             : 06/04/2022

Testing Process: 
Checked various approaches, all OK.

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

Media:       
image
image

**Comment by tareksabet** [comment]
Quality Assurance Tester Report

Discord : tarek_sabet#7946
Object of testing: #6995 
Tier of Testing : 1
Date : 06/04/2022

Testing Process:
Tried it by doing several circuits at LHKE 

Negatives:
N/A

Testing Results:
Passed

Conclusions:
LGTM

Media:
N/A

**Comment by tracernz** [comment]
> Quality Assurance Tester Report
> 
> Discord : mico#3145 Object of testing: #6995 Tier of Testing : 1 Date : 06/04/2022

Offset threshold at EHAM36C?

**Comment by mico975** [comment]
> > Quality Assurance Tester Report
> > Discord : mico#3145 Object of testing: #6995 Tier of Testing : 1 Date : 06/04/2022
> 
> Offset threshold at EHAM36C?

Yes.
image

**Pull request merged**
