### PR TITLE
docs: make changelog sorted per version

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

- Made changelog sorted by version

Discord username (if different from GitHub): someperson#4953

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MisterChocker** [comment]
I have noticed all my changes are listed as v0.4.0 changes. But they are actually for v0.5.0.
I am wondering if this is also true for other changes?

**Comment by MisterChocker** [comment]
To be more precise, I am talking about these
image

**Comment by Benjozork** [comment]
This is probably because people sometimes add their changelog lines in the middle of the list.

I'll fix it.

**Comment by MisterChocker** [comment]
Thx, I have added mine always on top of the corresponding month. Is that correct?

**Pull request merged**
