### PR TITLE
[FIX] Broken flap indicator

### LINKED ISSUE #2613: [BUG] Flaps are gray on upper ecam
**Mod Version**
Master at 3:12

**Describe the bug**

When you set flaps full you will see on the upper ecam it has turned gray.

**To Reproduce**

1. Spawn on the runway and set flaps to full. 
2. You should see the flaps come up gray on the upper ecam.

**Expected behavior**
For upper ecam to show flaps normally

**Actual behavior**
Flaps show up as grey on upper ecam

**References**
https://cdn.discordapp.com/attachments/748348078519746582/791036050738249759/Screenshot_1040.png

**Additional context**

Was this working before/when did the issue start occurring?
Before update 1.12.13.0
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes  #2613

## Summary of Changes

* The flaps indicator on the upper ECAM was broken after the Sim update 2. This fixes it.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by ErickSharp** [comment]
Category: QA Trial
Name: 🎄🎅Erick🎄🎅 [Z-5]#6484
Date of testing: Current date 22/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2615
Object of test: Abnormal ECAM flap indications

Testing technique: Spawned in at Madeira and tested flap indicator. Once with the development version, then with the PR meant to address the issue.
Steps you've made to test the Pull Request:
1. Spawned in at Madeira using the development version.
2. Spammed flap button to change between flap configurations.
3. Observed anomalies with flaps.
4. Spawned in at Madeira using PR.
5. Spammed flap button to change between flap configurations.
6. Observed no anomalies with flap indications.

Flight notes (If required): 
Development version screenshot of flap indication issue:
Screenshot 2020-12-22 155438
Issues (If Any): **NONE**
Overall Rating: Good
Conclusions of the testing: PR appropriately addresses flap indication issue. ECAM now properly indicates flap position. Ready for merger.

**Review by wpine215 — APPROVED** [review]

**Comment by ImenesFBW** [comment]
Did a quick test, working as described.

**GOOD**

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date 22/12/20
Version of the sim: Version the tester uses
PR Tested: #2615 
Object of test: Flap indicator

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned in at the runway
2. set flaps to full
3. 
4.
5.
image
Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Works, as expected, didn't have time to do a thorough test with a full flight but it works and also is the second test after the one from ErickSharp so the pr should be ready to be merged

**Comment by NickFarin** [comment]
Category: QA Tester
Name: Discord User: Nick F[Z+8] #5327
Date of testing: Current date 23/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2615 
Object of test: Broken flap indicator

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned at stand in KLAS in cold and dark
2. started the plane from cold and dark
3. once the engine were started, I put flaps full and retracted about 10 times
4. monitored the Flap indicator

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Flap indicator was functioning normally

**Pull request merged**
