### PR TITLE
ECAM status page and engine failures

### PR DESCRIPTION
**Pull request by tyler58546**
**Summary of Changes**

* Added ECAM status page
* Added new failures
    * ENG DUAL FAILURE
    * ENG 1(2) FIRE (airborne)
    * ENG 1(2) FAIL
    * ENG 1(2) SHUT DOWN
    * BRAKES HOT
* Added working engine fire buttons.
* Normal messages on the ECAM will now be hidden when a failure is shown
* The upper ECAM will now cache simvars to reduce lag
* Added ECAM overflow arrow
* Added ECAM status reminder
* Added automatic page switching during a failure

**Screenshots (if necessary)**

image
image

### CODE REVIEW

**Comment by wpine215** [comment]
If CLR is pressed, the lower ECAM won't hide the overflow from the upper ECAM warning. Not sure if this is intentional/expected behavior.

image


Also, IIRC "INOP SYS" should not display on right side when status is Normal and there are no inoperable systems.

**Comment by wpine215** [comment]
Also, there should be an STS indicator on the upper ECAM if there is a status memo:

![](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAwICRYVExgWFhcYFxgZGB4aGhoXGBkZFhgeLCYuLSsaHh0wNjk7MDM1NCkqPEY9NTs+QUJBJTFJT0g/TjlAQT4BDQ4OEhASHRUVHT4mJSZFPkE+PkA+Pj4+Pz4+Pj4+Sko+Pj4+Pj4+Pj4/Pj4+Pj4+Pj5KPj4+Pj4+Sj4+Pj4+Pv/AABEIANkA6AMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAAABAIDBQYBB//EAEIQAAIBAgQDBgMECAQGAwEAAAECAAMRBBIhMQVBUSJhcYGRoRMysQZSwdEUI0JTYnKS4RUz8PEkNEOCorJjwuIW/8QAGAEBAQEBAQAAAAAAAAAAAAAAAAECAwT/xAAgEQEBAQADAQEBAAMBAAAAAAAAARECITFBEgMiUWHR/9oADAMBAAIRAxEAPwDihQXoJMIJ5mhmnVzWWgDKs0M0C7NDNKc08LQLs0M0pzQzQLc08zSnNINWUbsB5wGM08LRNsco538LypuIDkCZNhlaGaeZ5mHGudgB6yBrVD+1b2k2LjULytsQo3YeszPhk7sfcz0URJ+lw62OUcyfASo8Q6AygKo5Dzkgw5Wk/VXI9OLqHYAeUgWc7tJwk2mKvhX3JMkKQk7SdOizaKpOoGg58vWDcVBR0mpwpVsdATM2P8JbtW/1tLPUvjUVf1FUfcdXHhYf3kuJ0hmRhsVP1/vLMKl3qL9+ifUH/wDUlX7WGpN0IB9CPrNss8rp4GFpYV0Phf8AGV2lFZH65h99AfPqIT2to9JuuZPxH1hGCjNPC0SfG/dF5UcQ52FvKZ2LlaOaBqgbmZhznczz4PUyauHmxaj9r0lbY5eQJi4pCehR0jTIm2OY7D11kDXqHnb0llOmzMFRSzMbBVBZmPQDeaY+z1YKWqNRogMFPxa6Bg1rhSouQba6gGTauRilWO7H1MBRE1sRwLEInxAq1UsWz0ai1Vte2YhSSBcEXIGoMQdGU2YFT0YEEeIk1VQpjpJACewkQQhCAR3h+CVlarVYpRQgEqAajtuKVMbZraknQDU3uAUiZtcQuKlLBm/wqQUuqlFYuVzVHDHQHUjU2sq3vYQInjzUndcMlKkhzIhFMGsRfRzUN2zW77anSQ/x+qyBay0sQM171qYapa2qioLMBz0IN5Ctw+n8QhKoKnVQFd3ta+UkDLcbGxtz2kkwNNQWYVKgUtdSVpXy/MCLsdAR03k2J+pPq3jOEw5QVcHcogC1QxYujHZrEXt+zcaXFrC4Jxps4jE06RQ0lUfEw+SqpDGysBudAWtfWxGx0I0yai5WK9CR/eJ06Zs0xgcQEFTcFksLFgQbg7juvGkxISoGy1C9SmqFGXIraBSb3ub2NtN7G+kp4XjFpM+e+Vkymwvz1HLcX8yLgyOJr/FC3VmexXMAoLHSwsBrb1Obumpyu5I89n+V2evV4W5LgZRkUPbNmuORBFwfzlXD3tUHl9ZfXxVSnW+IFFNsoAG4A2tY3t4aWttE6THOCdydZZ5P9tcf1e746nCtlr0jyLFD4Eae8kF/4eqv7tz6A3i7PZFf7pR/e59ppLS/XYhOTgN5EazVGQBKwJOmbgHqAZ4y6nxmoKcWP1Yb7lRT5HQwlldL0qg/gJHiDeEDCdbEjvnktxS2bxlU5VsQhCQEFUkgAEkkAAC5J5ADvhNH7P8AZxHxN/g06lYfzKpKnyax8oDeMrnA5qFI0zUZCtasCrliwsaSEXyhTobWJIudLCYQ6R/g2OFB2LBijIUcKBmYX1UG4y35kG4vsYgNtYDGExL0qqVEJzUyCti2mt7dbG5vbqes2OMFsWKtd6ZpVqOX4qWYIUJsrAHYjYjmDcbG+Xw3G/BZyQWV6b02CuENiNwcp2NjtuBrJYrHmtXFQqibAhb5bczrc63OnK4HKSz7nbfHvJb1SUCZ69rm21zbwnhErNmXGl/gGJGfNTKmmlR2DEAgIFLaeDKR1uLTNnUf/wBFVqqrfCpuaIawdmLMGphGBAsSDYnfS9tgJy7HXa3cL2HcP7y4ksuz/SL7HwM2uKtl4lUbka1/FW/sZjzpsatGilGrVyVsQKSKKatdNLhajn+XKLdV75L1GOfP85M21Z8CqKYfLSRVARS9QuWK2+VVuTsb25W6RKtXCBSxLZ+0DTpU1B7IFjcm1wRe6jcGRrYtnxArvWQroVBqDMFI1QKL23sQR1lOJxVI01pliwUEDLTJIF+RYjzsuu9piSz448f52XuequLrZk0ylc1Mi4NirXJBAG4YWsBEC19TrGsdjRVAGU/MWzMVJOgFrBRyA67RSbn/AF6ZsklTpPlZW07LA2IuDrzE0MfxFalMKoYFWDBiTvzI1O57za0zLwllsmM3jLZb8XYmv8Q5ioB/aIv2jzY/2lKm2vTWEIt1qTJkdNhlz0MvVSsdpVSa2Gqcq2GIP8wAMz+CNenbpY+39o0TalhmP/SxTUz4Em3sRN/GJ6odcruvR2Hle49pBhr5RrHplruOtm9rfVZQ67eY/GaiV5SW5t94FfUWhPUNiD0IMJcRicQSzeZH4iKTS4mml/A/hM2cr66TwQhCZUTS+z4zVzTG9ajVpL/MyHKPNrDzmbG+FMi16bVGamqsGzoLupGxA159xlLcl/4lwfh5xFTKM1spYkAGw7zcW8SZpjE4bCOBRUV6mxqVCDSQ/wAAAF7dfSQx3H1arlpL8LDlizooAZ7/ADFvwGw0mUDQW3Zq1OtytIena+omMt9cPzy/p3y6n+v/AFpsoWsAiJlOaxFNczMM3ZzNmtcrpY7RPjK/rAb3uti2naKsVv01C385GrxIt+xTOgF3z1CBy+Yke0WrYhntmIsoIUBVUAbmwAAlkrrxln1XCEJWllHEMl8jFbixtzHSVwhBk9EIQgE8LAbmbmA4QjYf9JfO4XNmpKArVLEaq33RftEAkHQb3FC/aGuistIrh1a2mHX4ZW3RwcxvzJJJF4llScpdz4ygwOxns0hxys3ZrkYlOYrj4jf9tT5x5ESrG4VMgrUSTTLBWViDUouRojHS4IBIawuAQQCCIUlCEIBCEIG39nn3XuP1/vNWpTzUMSvNXp1R3crjzWYPAqlqoHf+Fp01Bb1XT95h3HmDcexnSeM31DiwGdGH7SEe+g/8omw7N+8flG65zYai3QgHu0t9YuF0I7pqM1SBCTEJUIY9Lr5Ee2kxZ0OJXsnusff+85+otiR0JnPk6R5CEJhRCEIBCAHn3DcnoJr1a36H+rp2/SRpVrCxNI21o0jyIvYsNb3AIAuQqX7P4sqGNFkU7GqyUr+AYi/+0oxnCq9EZqlJ0XYPYNTJ6BxceV4u9VmFmZmBYt2iTc7Fj3keekswWMqUWLUnKXFmAsUcfdddiO4giBRCaOLopVpmvSUUypArUlvlQnaon8BOhH7JIGxFs6AT2mpY5VBY9FBJ9Jq/ZxUZqyuEL/BLUjUFIgOGGgD2XUE77W0m0/EqVIUnFU5QVptTpOGVE+FlqiwUD5gGFnIN72BgceZ6iFiFX5mIUeJP5yK7axjh9UJXpM3yrVRm8AwgPcRxzUsUfhHKtD9TT2tlU2Nx/EczHqWMrxuH+K+ejRqIrKCylbIrcwraC2xF+s9HZxbhXDZncCojXBLA2IPmPMGHC87liweorIwJsz6201sdib6kC4FyJLPrNkl/UnaheHNYszU1C2LWY1Co5E5L+9o1wtko4h6dbM9KoppuEA7YNirC/Q2YcwQO+N4iupUh/hglNfiOjFTrZQFzGwvpYA6AaCY+MZSwKNmsiAsAwBIXKbXA6cxzk7su9L/Plbd5R5jzTNVzSVlTN2Vc3YDoTrz75RaShNeSRu93UbQkpGEMcPfLUB/1e952dNsteg3LPlPgwI+tpw+HNnU94/KdfUf/AIdX3KBanmpufpN8fGOS4U7Yasv7pyfIG/0i1MazWNMHEYhOVRQw7wRqZkUDcDwHrNxmqk2t0nsky2dh5wlRTUW4ItuCPbT3nP4pe2e+xnSE2+swuJ08r26Ej30mOU6bhKFoT2c2nhhAwgaPANK5q2B+DTqVwDtmVezfwbLE6GHeoTlVnI1Y9O8nv7z1mjwPEYZBUFc1AaiGn2FUgLcG9+txba2skxoVKb0sPRqByA4LPnLWPyhQOhPpG95jH77ySkBg7fPUpL3Z/iN6Lf6iM/4cio7M1VgjZGyotOx5jUk6d4EXGBdT2ylMjXt1FDDyuT7RytjKWZzmYl1s2RWflYkFim/eptyku/Ftu9I8NxP6LiXBVXXtU2FQ9kpfc8thzuO69ojjsR8Wq9TKqZ2Jypoo8P8AXOGLqh6hYAgED5rE6AAk+J185TH5m79dP1/jIDG62Mz0lVsxZAFWxASw2uOoF/X1UmhgeEVKtM1RZaStkdzdipuugUXJvnBHWx10mpcYsly34z4RjH4X4VZ6WYPkYrmGgJ/C3PXQgxj/AAStYlfgsACSUxOGfTye8ikFYggg2IIII3B3BElWrM/zsz/zszW8JAS/A1glQFghGo7YJXbcix230BgtsmyaotJMpUkEEEbgixB6ETSxuOpsqBQSUYldCBbSwPiBrYDXvJiWMxJq1GcqFLWuBe17anmdfxkltZ48rfZiqE8BheVsTyF4QC87Dhn6zDlfFfUX/GcfOp+zNS9MjuH5Ga4+s8vGxhqhL4Z+dTD5T4rvEymV2Xo7el9PaMYc2pUj+5xTUz3BtR7NDHJau/fZva31E3HMlXFnHeBCTxY0U9DCbRQVmRxmnz8D7WPvNorM/itO6A9xX8R9ZizpqXtgQnsJydXkIGEIIQhAAJZ+jvmVcpDMLgMMtxyOtvy0ldo/iOIBijBTnXW7HS53UDofG/aMl1m271CVSmVYqwsQbEd89oIGdVZwik6uwYhR1IAJ9BCvWLsWNgTba9hpoBudu+Qlizc7PYurh1QpRRnNxetVOVj3JTBsoPeWNuku4HxKpSfItVqas1yVy3B0IJJvpcDzAmXL8Dg3rVVpUwC73AuQBtc3PgPbSWere5gxzs1V2ds7E6te4Omlj3DTyi5Ef4jwtqCIzsjfFBKhA9rA2JJIHPkNudtpDCcMq1RmQUzraxrUEb+ksD52tFIUhLsXhHpPkdcrAA2zK2nI3Fx7ymQegGxPIbnkJacI4UsVICkA30I25eY5W1HWW4LEhFcG5DqVy62J5Em428DpcaXvLcVxU1M/YUZ1AJBY27xrzAHpeS26xby3JOmfCEJWxCEIBN77LVO3l6gj8ZgzS4BVy1l/mHpex+s1PUvjqyP1eKXoKdYeINj/AOsY4oLsjD9pPx0/9oUad62XlVo1KfnYEfjCoc2GoNzFlPpY+4nT65kqy3TwtCWlOw3hCVCbiK45L0z3EH8D9RHmFwD3SmtSujDqp+lx7yXxqOSqCxI6EyMtxa2c99jKpydBCEJAQhCAQhCBcMKxpmpplBta/a3FzbxI9ZTLkxLCmyWFm5kdoajQHvIHLlKZJqTe9PUKeHRVeozVmIuKVK6KNrCpUI08EB8RLeD0mNX4yOKRpuCAozZb32vfYXve5sCdZmT0MRexIvvY79JqWb2cpbMlyteth0VlWqzFQpVFLXZRZjlOg3Y6aczvMrEBc7hdVzHL4X09pCEtu/GePGy7boAhCEy2ISdGgzmyKz23ygmw6n8zGm4TWH/TO19CrG3WwJi2RLZPuEoQhCiEIQCX4FrVB3gj8ZRJ0Ws6nvH1lnpX0FagD0KnIVU8g3ZPs0vSl/w9VP3dVvQNm+kzaLFsLcfMqG3ipuPpN2ioatiFG1VEqDvzLYzrXNlou48oQpm9j1AMJUKUdaY7p4F17p5g/lYSzLA5LidPK3hdfMGJzY4/SszHvDeo195jzlfXSeCEITKiEIQCEIQCEIQCEIQCEIQCBhCBsYvH0kRqSAVENr/MiAjnyJJOpJPQAWEXp8TsUPwaRyfJ/mXUXva+bXXrfeZ8LySTMYnCZgIhAamw1PQb+kcp8IrkZjTZF+9VtSXxuxHtK6E4R4YGkvz4imO6krVj62A9558XDL8tOrU76lRaa/0rf6whImX4fAVqnyU6jjqFOX1295eOKMv+WlKl3pSUv/U1z7xfEYupV+eo7/zszDyH5QOx4E16TK24bUaaXH53m1wxu1hm3zYdqRPejW195zH2Uqdkr/D9Db6GdHgmsqH91iyPJ1v9T7TrPGL6oqU8rsvRyB4X09oRniVO1Zu+ze1vqISssPCNZ/GMsuu8SpmxB75pOvOWowuP0rgHqhHmDec3Ow4wl6YPRvYjX3nIvSZRcg2uVB5EjcDw/Gc+Xrrx8RhJ0qTOQEVnJIUBVLEnkot15DnaSxOGem2WorU2sDldSptyNphVUJJ0K2vbUBtCDoRpex6ddRzjfDcGKme5sVQle0ou1rga8tOXUSW52nK53fCUJu5MMisAabZqY1+YhgGuRobX7JsCN97CxzuK11qVAy3bs6kixvckDyBA8ol34xx/peVyTotTpM3yqT4Anl+X0hVpMhyta46FW9xcRjA440ldQoYPa9+VjuP9flK8bjDUYM1hYWFr2te/Mnn5DSb6z/rUvL9ZnSiEZocNr1BdKVQj72UhP6jYe8tPDQv+ZXo0+oDGq48lB9yJlojCPD9FX99VPgtJD/7H6QPEFX/LoUk73U1XB6gtce0BShQeobIrOf4FZvwkWUglSLEEgg7g8wYzX4nWqCzVXI+6Gyr/AEiw9orAI7hKgWmSMOtUr81RzUZFB2BUED1vK69FRRpOo1Y1FfU7ggj2YekswNR8joltbOxLBbBQbjXqDrbXTpeS3InK2TY0UOLIYKy0FVgpWmop2OnNR36XOutrzOqYe2JVKrFjmUMxJub9D5+Y1jzGvVdgrLfJmK00Pkh0Gva0tfYcxeJcSo2yNdmVgbFibmx6EC2/eNd5mW291y48uVuW+tBhhaV1ZVJzC4NywFhcXudrmw7jqSJlYpCzOyhst82q2y9QfAnl1HWP1ayjMKVgaiDKqKGKsGBAzAX1F73101luOq1KucIjBXQHtsFNs1wQCSdRpvroe6SWyscbeNn/AFhQhCdXqbv2Wq2qAd5HqNPedam2IH/x06g8UbU+lpwvA6uWqD0s3oZ32FUfpCLyqLUpHzXNr/T7zc8c76Z4uO0jD9pPob//AGhCt28LQY7gBT6WI9VhNMuYtNKnqgMQI1PjHcKbp4GaqKeIJmov4X97/SY/Cnpq4+KFNNMTTZswVlCupUsQQRoQDqDOhK5uzyNx5WnJla4qfqVcsy5WCLm2Ol9DznH+k2deuv8AOyXtt8E40cocLVJpu7fCWnmStcoUYuAFBQoNSBoBbpMzj7UqroVanSSmpQXKZ7ZiwHw6eYCwNt7k3J1MUxGBrt/zFZE7q1cM3kgufaU/BwqfNVq1O6lTCL/U2vtMZb9dNkKV6pYgFiwQZEJvot9AB7275BVLGwBY9ALn0mpSqLcfCwin+KszVBz1I7K8juORlz18UF7VT4KFgv6sKgB6ALa+mu+1jfURsn1zvPj9pJeEV7ZmT4a/eqstIf8Alb2E9/QqK/PiEJ6UUap79ke8do8IVizO5Yo5D30Ngyi5OvI666aTO4lhxTqZRYdkEgXsp5jW/jqecTlLcjHH+nHlciz42GT5aNSp31auUf0rb6z0cXqL/lrSpd9Kkob+o3PvEISuizEYh6pvUd6h/jZm9JXCEAhCEAhCEByn2sK4/d1kfyZSp9wJVgM3xFC2u117Xy2Isb+RlvDtVrp96iWHihD/AEBi1CqyMGU2YbHppF8TlNlka36NUyIGqEMcwCKqhzludwbk9gWuOa2J1i2GVExDLUsyqXUZyLaHS52/32ilTEu5BZiSNQSdQdr+3tKpmSuc4XLLfWuMTQRiVY2KNTKohBtc2fluAvPxlJ4nbKUUXVAl2N7gHsmwtqLDcnbppM6Ev5iz+c+9iEISui/Ataqvfce35zv6Fbs0an3XpsfC4B9iZ87ptZgehB953WBu+GKjcBlHcdxOnHxnk6EU/wBRXT93WYjwzZvo0JbhGFRqltqtGnUHmpUn6QmmHLYxMtRh3y3BNuJZxVLVL9Rf8JRhTZhNfENZZyvHlZWcAkDPcgEgEHUAidYVmB9paWpNt0v5gzF8anpHD8MprTWoCHLKCFchVzEHQ6jmptqNdIktVaWIYoRkV2VTq3Z2BFrcuhBiRPttCcZL3tJws3buterxmwyqCyi+jnfW5ud9bsNTset4pW4k7AqLBdOz8wtYAb32Cjv36xOETjIcf5cZ8WVsS1QlmYsSbm/XraVwhLjpJkyCEIQCEIQCEIQCEIQHODsBiKd9mbIfBhlP1iZUqSp3BIPjsZ6rFSGG6kEePKN8XQDEVLbF848GGYexgJwhCAQhCAQhCATtvszVvTI8G9tZxM6f7KVeXcR53uPab43tOU6dpwVv+X/krUT/ANraey+8JTw97C/3MVTbydcp97wmnMvxlbojAf65TLpmxHjNnFKWw38v+0xZuI0T9Zmcep3VD3lfUf2mlSN1B/14RbiyXoMehDe9vpM2NRwBWxI6aQl2MW1RvG8pnKughCEgIQhAIQhAIQhAIQhAIQhAI5xHUUX+9RUHxUlT7KJPgnD1xFYU3c0xkLXAUlralRcjlc6nQA6GdImBwyJTRqTvlqVEUVVru18ucdlVQ9oai6MBY+MDjITS+0eGFPEuFVUUqjhUtkUlRcDwa406TNgE9tJJTY7A/h67RrD8Mq1NFUn+UFjLlOidp4ROjw32VqH57L/MwHsLmbmC+xqjVgx8FCD1Os1OFS8pHBpSZtlJ+nrNrglGpTzNtY3vqQNNb8p29LhGHpb/AAwfOq35Syq9AjLlaoOjHKvoJucMYvPXJ4+hnUMWe5Aa6dkr01hNziCq9MqiImlgEFtOkJrE1oYY3pOviR6fnMArN/h/7fgPxmE25kiG8I11t0MniKWam69VIHpK8Ds3jGV5+EVY+e8TXtA9RE5o8W/Z8TM4TlfXWeC0J7PDMghCEAhCEAhCEAhCEAhCTofOJQzwquaNZamQ1AMwKg5cwKlSA1iBoehmq/EK1QkU6FJdrXQ12Ww0spug8Qg3MUM7Dhv+SJucYlrnX4JiK75qxJawF3KrYDkFG1uQAE1cD9jL6kMfBQo9TOn4J88c4v8AJ5zc4xyvKsOh9n6FL5zTB771W9NvaNh6CiwV38SEX0EUhNsmv8QYaIqU/wCVRf1lDVHqblm9SJAb+k26HyxRl08A55W8TJnCIvzuPAb+mpjnFP8ALExhIHPj0k+RSx6tb+8IkYQP/9k=)

**Comment by tyler58546** [comment]
*** New changes:
* Fixed INOP SYS showing when there are no inop systens
* Added secondary failures and STS reminder
* Engine fires can now be extinguished
* Fixed NAV TCAS FAULT showing during ADIRS alignment (it should only show when the ADIRS are have not started alignment)
@wpine215

**Comment by armankir** [comment]
Tyler shouldn't the fire cover close back up if I click it? It doesn't seem to do that.

**Comment by CoffeePanda0** [comment]
image

I can't seem to get the status page to work for an engine fire, i'm gonna try and do the dual engine failure now and reply with results from that

**Comment by tyler58546** [comment]
> I can't seem to get the status page to work for an engine fire, i'm gonna try and do the dual engine failure now and reply with results from that

The status page will not show anything until you shut down the engine.

> Tyler shouldn't the fire cover close back up if I click it? It doesn't seem to do that.

I didn't think anyone would need to close it so I didn't bother adding the animation.

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
