### PR TITLE
[PFD] Add altitude constraints visual behavior

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Altitude indicator targets constraint altitude
- Added SVG design logic for FL and ALT (now changes appropriate between FL (when baro to STD) and ALT)
- ~~Push h-update on constraint change to update constraints on ND~~
- Added delay to FMAs, to test performance etc.
- Implemented FMA support for below constraints.

- FMA can now show (additionally):
`DES` / `OP DES` -> `ALT` *magenta*
`ALT CST*` and `ALT CST` -> `DES` or `CLB` *blue* and `G/S` *blue*

### Before
image
### After
image
image
image
image

<details>
  <summary>Older images</summary>
image
image
image
image
image
image
</details>

## References

image
image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
LGTM

**Review by Benjozork — APPROVED** [review]

**Comment by Carter633** [comment]
Name: British Avgeek YT -- Carter633 #1436
Date of testing: Current date 04/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1740 
Object of test: Alt constraint visual behaviour

Testing technique: Full Flight from EPGD to EGKK on VATSIM
Steps you've made to test the Pull Request:
1. Used SIMBRIEF and Skyvector to plan the route, spawned C&D, inputted all data into MCDU for the flight
2. Pushback, Start, Takeoff, en-route amended constraints for some waypoints
3. Checked behaviour through the flight

Flight notes
Startup: Everything normal
Taxi/Takeoff : Everything normal
Cruise: My amendments worked as described above
Descent/Landing : Worked as described
Shutdown: N/A

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Items mentioned as changed/improved in this PR seem to work fine for me, no erroneous behaviour or issues LGTM

**Comment by Noxleee** [comment]
Name: Noxlee #7727
Date of testing: Current date 04/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1740
Object of test: Alt constraint visual behaviour

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Test flight from LOWW -> LFSB: LOWW/29 F360 SOVIL1C SOVIL DCT SITNI DCT BAGSI DCT MATIG DCT TRAUN
L856 NEGRA UZ613 TRA T718 RIGVI DCT LFSB/33

Flight notes

Startup: Everything is normal

Taxi/Takeoff : Everything is normal

Cruise: Everything is normal

Descent/Landing : Could see the constrains on PFD and AC didn't fly lower than that in managed mode, works as described
Shutdown: Everything is normal

Issues (If Any): No issues found
Overall Rating: Good
Conclusions of the testing: PR works as described, could not find major issues

**Comment by MisterChocker** [comment]
Error on merge confligct, need to push update

**Comment by MisterChocker** [comment]
Fixed the missing `#` I accidental removed on resolving merge conflict.

**Comment by joshbxd514** [comment]
Name: joshbxd515#4978
Date of testing: 05/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1740
Object of test: Alt constraint visual behaviour

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawn C&D, at Gatwick with an IFR flight to Leeds
2. Pushback and start
3. Took off and autopilot followed correct constraints.
4. Descended using constraints 
5. Landed at Leeds no Issues

Flight notes

Startup: No issues

Taxi/Takeoff : No Issues

Cruise: Followed correct constraints all the way to cruise

Descent/Landing : Followed correct constraints all the way to Glideslope

Shutdown: No Issues

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: works as described, all constraints were correct in my flight good work yet again :)

**Comment by Pushok154** [comment]
in such case alt on fma will be magenta (DES / ALT MAGENTA --> ALT CST* / DES BLUE-->ALT CST / DES BLUE-->DES / ALT BLUE)

**Comment by Pushok154** [comment]
image
image

**Comment by MisterChocker** [comment]
@Pushok154 thanks for the screenshot, you are absolutely right.
I'll check how this works (in our script)

**Comment by MisterChocker** [comment]
Okay I checked our fma script and this actually is implemented. Or at least something. Now I need to understand how that stuff/code works.

**Comment by MisterChocker** [comment]
Update: ALT still blue
image
image

**Comment by MisterChocker** [comment]
I have added your request, FMA now says ALT in magenta, however its currently not able to show stuff like that:
image

But I am working on this!

For testing purpose I have added some eye candy, the FMAs now update with some slight delay. Please give me feedback on that as well.

**Comment by MisterChocker** [comment]
Alright did quite some changes, FMAs are now included as well.

**Comment by Benjozork** [comment]
Should be good

**Comment by MisterChocker** [comment]
@Benjozork Alright, so just you know, there was no milestone labeled, don't you use that to keep track of the prs?

**Comment by Benjozork** [comment]
Yeah, probably just forgot this one lol

**Comment by Benjozork** [comment]
If you don't want something to be merged, mark it as draft

**Comment by MisterChocker** [comment]
Yeah nah it's fine, wasn't wip, I was actually expecting some more testing since it was draft before and I did some changes.
Anyways I always check the stuff, if there are any bugs, we will find them and address them later.

**Comment by Pushok154** [comment]
at first quiqk look, looks great, but white frame at alt cst* collide with text, it should not be that

**Comment by MisterChocker** [comment]
> at first quiqk look, looks great, but white frame at alt cst* collide with text, it should not be that

yes, please open an issue.

**Pull request merged**
