### PR TITLE
[CDU] Added constraints symbols logic to flight plan

### LINKED ISSUE #499: [REQUEST] Let us enter Altitude Restrictions
**Is your feature request related to a problem? Please describe.**
On the real airbus you can enter speed and alt restrictions in the MCDU

**Describe the feature you'd like to see implemented**
 enter restrictions in mcdu 
(see link)

**References**

http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.13.html

**Additional context**

### PR DESCRIPTION
**Pull request by ilyeshammadi**
Fixes #499

## Summary of Changes

The goal of this PR is to be able to insert the constraints symbols that were always hardcoded before. The goal of this PR is not to update the AP behavior in order to follow those constraints but only to be able to insert and persist that data.

#### Note:
In order to see the new constraints and the symbols, you need to toggle the CSTR button until you see them, that issue if it's one in real life is not related to changes of this PR.

#### What has been done
- Update flight plan page to accepts `+`,  `-`  and non-symbols values.
- Persist the waypoint constraints symbols.
- Kept the already implemented asobo feature that sets the constraints symbols if not already set by the user.

## Screenshots (if necessary)

Screenshot 2020-11-24 015254

**Please watch the demo video in order to get more context about this PR.**
https://www.youtube.com/watch?v=Qoz-j4g87S8
## Additional context

Thanks to @MisterChocker for all the work he did on the constraints already 💯 

Discord username (if different from GitHub): Union Araken#4083

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by wpine215** [comment]
Related issue that's existed before this PR (if you're interested in tackling it here): if you change an altitude constraint when the CSTR EFIS filter is active, the updated constraint value is not updated on the navigation display unless the CSTR button is turned off then back on.

**Comment by ilyeshammadi** [comment]
> Related issue that's existed before this PR (if you're interested in tackling it here): if you change an altitude constraint when the CSTR EFIS filter is active, the updated constraint value is not updated on the navigation display unless the CSTR button is turned off then back on.

Indeed, but that's a separate issue that needs to be done sepratlly. From what I saw in the code the toggle is in place to avoid fetching the waypoint too often which can lead to a performance hit.

**Comment by wpine215** [comment]
Tested, works as described. Simple fix, merging.

**Comment by MisterChocker** [comment]
@ilyeshammadi sry for commenting below merged pr, but didn't you implemented type 4 constraints?
legAltitude1 will hold minAltConstraint, legAltitude2 will hold maxAltConstraint.

**Comment by ilyeshammadi** [comment]
@MisterChocker because I'm not aware of this. maybe you can explain in some details so that we do it in another PR, thanks.

**Pull request merged**
