### PR TITLE
fix(hyd): reverting gravity extension causing gear impacting doors

### PR DESCRIPTION
**Pull request by crocket63**
Fixes #[issue_no]

## Summary of Changes

Reverting gravity extension in flight was causing door closing ang gear retracting at the same time.
LGCIU state machine is corrected so it falls back to retraction if not actually in all uplocked state

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Gravity extension in flight. When all down locked, stow gravity extension.
Check on wheel ecam:
Gear should retract with door opened, then door should close after gear locked up

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by Mack674** [comment]
Quality Assurance Tester Report

Discord          : Mack#674
Object of testing: #7364
Tier of Testing  : 1
Date             : 31/07/2022

Testing Process: 
- Spawned C&D at LGKO
- Powered up
- Performed a low pass above runway
- During low pass used l/g emergency extension handle
- After extension of landing gear recracted emergency handle
- Switched landing gear normal handle in up poition
- Observed retraction from external view 

Negatives: N/A      

Testing Results: Passed

Conclusions: Landing gear extended and retracted normally. Good job!

**Comment by dragold** [comment]
Category: QA Tester
Name: Mr.Blank#6197
Date of testing MM/DD/YYYY:07/31/2022

PR Tested: 7364
Tier of testing:1

Testing technique:  Brute force tryouts
Test Instructions:
Gravity extension in flight. When all down locked, stow gravity extension.
Check on wheel ecam:
Gear should retract with the door opened, then the door should close after the gear is locked up

Methodology:
All as per Testing instructions
Non SOP Quick flight, with a high-performance climb, then gear test at +210 knots after level out above 8000 ft 
VOD-
 https://discord.com/channels/738864299392630914/754130199804772372/1003267816570491020

https://discord.com/channels/738864299392630914/754130199804772372/1003299042836619314

References- (Chat onwards) 
https://discord.com/channels/738864299392630914/754130199804772372/1003267816570491020


Remark-  Refer references 

Negatives: Sim Crash
Testing Results: Fail 
Conclusions: results were of abnormal outputs

**Comment by crocket63** [comment]
> Category: QA Tester Name: Mr.Blank#6197 Date of testing MM/DD/YYYY:07/31/2022
> 
> PR Tested: 7364 Tier of testing:1
> 
> Testing technique: Brute force tryouts Test Instructions: Gravity extension in flight. When all down locked, stow gravity extension. Check on wheel ecam: Gear should retract with the door opened, then the door should close after the gear is locked up
> 
> Methodology: All as per Testing instructions Non SOP Quick flight, with a high-performance climb, then gear test at +210 knots after level out above 8000 ft VOD- https://discord.com/channels/738864299392630914/754130199804772372/1003267816570491020
> 
> https://discord.com/channels/738864299392630914/754130199804772372/1003299042836619314
> 
> References- (Chat onwards) https://discord.com/channels/738864299392630914/754130199804772372/1003267816570491020
> 
> Remark- Refer references
> 
> Negatives: Sim Crash Testing Results: Fail Conclusions: results were of abnormal outputs

Can you retry with cockpit control in legacy mode? Crash is not relevant to that particular PR.
Thanks!

**Comment by dragold** [comment]
> > Category: QA Tester Name: Mr.Blank#6197 Date of testing MM/DD/YYYY:07/31/2022
> > PR Tested: 7364 Tier of testing:1
> > Testing technique: Brute force tryouts Test Instructions: Gravity extension in flight. When all down locked, stow gravity extension. Check on wheel ecam: Gear should retract with the door opened, then the door should close after the gear is locked up
> > Methodology: All as per Testing instructions Non SOP Quick flight, with a high-performance climb, then gear test at +210 knots after level out above 8000 ft VOD- https://discord.com/channels/738864299392630914/754130199804772372/1003267816570491020
> > https://discord.com/channels/738864299392630914/754130199804772372/1003299042836619314
> > References- (Chat onwards) https://discord.com/channels/738864299392630914/754130199804772372/1003267816570491020
> > Remark- Refer references
> > Negatives: Sim Crash Testing Results: Fail Conclusions: results were of abnormal outputs
> 
> Can you retry with cockpit control in legacy mode? Crash is not relevant to that particular PR. Thanks!

Works as expected

**Pull request merged**
