### PR TITLE
feat: cockpit texture overhaul

### PR DESCRIPTION
**Pull request by MoreRightRudder**
Fixes #[issue_no]

## Screenshots (if necessary)
image
image
image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by flythebest** [comment]
IRL Pilot. Flythebest on discord.

Very nice effort on this one, a great addition.
In my opinion, the texures of Glareshield and Main panel are too grey. They should be more blue, like the pedestal.

Good luck ;-)

**Comment by wpine215** [comment]
> 
> 
> IRL Pilot. Flythebest on discord.
> 
> Very nice effort on this one, a great addition.
> In my opinion, the texures of Glareshield and Main panel are too grey. They should be more blue, like the pedestal.
> 
> Good luck ;-)

A320neo's ship with an multiple cockpit color options from what I've seen, and we're currently aiming to recreate the light grey one (RAL7031). We tried blue before, but the problem is the current 3D model lets light leak through, and the blue light from the sky accentuated the blue textures, washing everything out.

The base color of all of the panels are pretty much the same (see below), the reason you see the pedestal blue is because it is incorrectly reflecting the sky. We are currently trying to fix this behavior.

image

**Review by wpine215 — APPROVED** [review]

**Review by ko-zone — APPROVED** [review]
LGTM

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 16.02.2021
Version of the sim:1.12.13
PR Tested: #3431
Tier of testing: 1
Changes to observe:
Cockpit textures

Testing technique:tested?
Steps you've made to test the Pull Request:
1. started at gate and on runway
2. observed the textures
3. did a short flight 
4. landed


Issues (If Any):none

Overall Rating: Good
Conclusions of the testing: Looks definitely better then before and I don't noticed less fps! Thanks for the PR!

**Comment by 1Revenger1** [comment]
Name: 1Revenger1#2952
Date of testing: Feb 16th, 2021
Version of sim: 1.12.13.0
PR Tested: #3431
Tier of testing: 1
Changes to observe: New cockpit textures

1) Spawned at Innsbruck on runway
2) Moved viewpoint around cockpit

Media:
image
image

Issues: None

Overall Rating: Good
Conclusions of testing: It looks *amazing*

**Comment by FlyingCarpet7** [comment]
I fly the same light grey color IRL so can compare the textures. I really like that you went with this color option. In the sim I selected overcast weather to not have the blue sky bleed in to the pedestal. There is a dark grey look in the sim compared to real life, but there was a reason for it Iceman explained? Will it be lighter eventually with updates? 
As you know and can see on the IRL pictures some panels, mostly not in use cover panels, are tiny off in color with a bluish hint. I see that you have it at some places but could be worked on more.


Skärmbild (26)



Skärmbild (25)

**Comment by davidfrp** [comment]
Lots of details that previously was contributed seems to have gone missing in these new textures. I suggest taking a look at some of them. #3273 #3212 
The backlight contact indicators, the small blue pluses thingy that used to be plastered all over, also seem to be missing.

**Comment by ImenesFBW** [comment]
> Lots of details that previously was contributed seems to have gone missing in these new textures. I suggest taking a look at some of them. #3273 #3212
> The backlight contact indicators, the small blue pluses thingy that used to be plastered all over, also seem to be missing.

The cockpit decals merged with this PR were out of date. We should be able to re-add them by merging the updated cockpit decals. We also need to add () for the speed placard, I will probably open a PR to fix most of these soon.

**Pull request merged**
