### PR TITLE
chore: Update stable to 0.6.2-rc

### LINKED ISSUE #5442: AA Causing Flickering on the buttons, etc.
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

AA Causing Flickering of buttons, text, etc.

TAA is currently the one I know of. Ill check the others soon.

### Expected behavior

No flicking

### Steps to reproduce

1. Settings preset to high-end
2. Look around the cockpit but don't zoom

### References (optional)

_No response_

### Additional info (optional)

This only started occurring after Sim Update 5.

It could be the sims fault but I don't see the issue in the stock a320.

### Discord Username (optional)

wizzerdkitty#7383

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #5442

## Summary of Changes

* fix(lights): switch compatibility

* fix: formatting

* fix: Console/Floor LT switch

* fix: workaround for "NOT IN DATABASE"

Co-authored-by: Saschl <sascharudolf46@gmail.com>

* feat: port updated touchdown fx

* fix: update simvar for ECAM message

* fix: logo LT update code

* fix: separate dome light emission

* fix: formatting

* fix: master warning and master caut pb

* fix: consistent ids in template

* fix: ann lt test for master caut and warn + prevent gear up on ground

* fix: add gear lever wwise event

* fix: formatting
* 
Co-authored-by: Saschl <sascharudolf46@gmail.com>
Co-authored-by: Taz5150 <70781153+Taz5150@users.noreply.github.com>

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Check that Master WARN/Caution can be pushed and work as expected
2. Check that landing lights and all light switches work, and that lights retract/extend as expected.
3. Check that flight plan is able to be loaded correctly (Simbrief or menu).
4. Check that every button in the cockpit has tooltips, can be interacted (with correct behaviour), every light knob/switch within the cockpit (pedestal lights, etc) all work. Exterior lights have some known issues, and that unfortunately will have to be mitigated in the future 0.7.0 release. 

Known Issue (Won't Fix): 
- Strobe Lights are not fully disabled when off, unusual/unexpected strobe behavior. 
- A/T is connected during TOGA

Fixing:
- Master Caution unable to be cleared
- Missing Tooltips (vs Development)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Trainee Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: (#PR 5460
Tier of Testing: (1)
Date: 29/07/2021

Testing Process: Spawned C+D at gate: Followed regular startup process while observering all functions and engine start.
-Tested all switches
-Tested Master WARN/Caution switches
-Loaded in a flight plan known to generate Not in D/B error pre SU5 (EGKK/LOWI).

Negatives: N/A
Testing Results: Passed

Conclusions: All switches worked as intended, any observed bugs due to SU5 are not present on the build. Console/floor light and overhead dome/emission lights worked as intended and engine start was as normal.

**Comment by donstim** [comment]
Please add `modern_fm_only = 1; 1 (true) forces use of modern flight model regardless of what user selected in MSFS options menu. 0 (false) allows use of user-selected flight model` in the [FLIGHT TUNING] section of flight_model.cfg

**Comment by donstim** [comment]
You don't want to update to the latest flight model unless you are going to update to the custom autopilot/fbw and engine model. Until that happens, only add the force modern flight model line.

**Comment by 2hwk** [comment]
Notice: As there is a hotfix incoming for MSFS, this PR will be delayed until after that patch.

**Comment by bouveng** [comment]
Why not adding more feat to this branch? 🙈

**Comment by SkylarHutter** [comment]
Quality Assurance Trainee Report

Discord: Skylar#0698
Object of testing: #5460 
Tier of Testing: (1)
Date: 30/07/2021

Testing Process: First load-in after hotfix today, with this build. Loaded in at gate E9 at KPHX, clicked to start EFB. Game crashed when clicking to turn on EFB.

Second test: Loaded up on runway at ABQ, airplane started up fine however the EFB is entirely white. Cannot turn on or off. (see imgur link one below)

Third test: Exited to main-menu, Loaded in C&D at ABQ gate, everything off EXCEPT EFB which is all white. Unable to power on or power off. Did NOT fully restart SIM (see imgur link 2 below)

Fourth test: Full restart of SIM. Loaded in at gate A3 at ABQ. Everything else is correctly off in a C&D, EFB is all white still. (see imgur link 3 below)

Negatives: EFB not working on runway load-in.
Testing Results: Failed
Screenshots: https://imgur.com/a/IsAciTs https://imgur.com/a/3gc6EAC https://imgur.com/a/kN3Jl02
Conclusions: Seems the hotfix today may have caused additional issues.

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Trainee Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5460
Tier of Testing: (1)
Date: 31/07/2021

Testing Process: Replicated previous testing to verify fixes applied as before after Sim update 5 hotfix. 

-Spawned C+D at gate: Followed regular startup process while observing all functions and engine start.
-Tested all switches
-Tested Master WARN/Caution switches
-Loaded in a flight plan known to generate Not in D/B error pre-SU5 (EGKK/LOWI).
-Started EFB and tested functions,
-Checked textures for issues.

Negatives: Strobe light is active in the ON and OFF positions, and inactive in the AUTO position. Tested against dev branch, the issue isn't present on the development build. 
 
Testing Results: partial pass - most issued resolved except strobe as noted.

Conclusions: Excluding strobes, all switches worked as intended, any observed bugs due to SU5 are not present on the build. Console/floor light and overhead dome/emission lights worked as intended and engine start was as normal. EFB no longer showed as a blank white page and texture bug resolved.

**Comment by 2hwk** [comment]
Unfortunately there is an issue with the Asobo strobe light template, so that will still be not working for now. It's quite a big change to deviate from that, so that won't be making it into this build.

**Comment by dragold** [comment]
Category: QA Tester trainee 
NOte- pre-fix(light):logo light
Name: Mr.Blank#1
Date of testing:07/31/2021
The version of the sim: 1.18.14.0
PR Tested: #54460
Tier of testing: 1

Changes to observe:
fix(lights): switch compatibility
fix: formatting
fix: Console/Floor LT switch
fix: workaround for "NOT IN DATABASE"
feat: port updated touchdown fx
fix: update simvar for ECAM message
fix: logo LT update code
fix: separate dome light emission
fix: formatting
fix: master warning and master caut pb
fix: consistent ids in template
fix: ann lt test for master caut and warn + prevent gear up on ground
fix: add gear lever wwise event
fix: formatting

Testing instructions
Check that Master WARN/Caution can be pushed
Check that landing lights and all light switches work, and that lights retract/extend as expected.
Check that the flight plan is able to be loaded correctly (Simbrief or menu).
Check that every button in the cockpit has tooltips, can be interacted with (with correct behavior), every light knob/switch within the cockpit (pedestal lights, etc) all work. Exterior lights have some known issues, and that unfortunately will have to be mitigated in the future 0.7.0 release.

Testing technique: Tryout

Methodology:
All as per Testing instructions
-consistency Test,  full sop fllight( Fail)

Observed observations-
-(below) cross over the adirs light found me sim problem
image
-(below)one side of the logolights is working
https://user-images.githubusercontent.com/47900069/127764183-8eba1b8a-9dc1-4200-bf8b-4b1a8df92cad.mp4

Testing Results: Fail ( pre- fix(light):logo light)

Conclusions: need more testing

**Comment by ShadowFrost3** [comment]
Quality Assurance Trainee Report


Object of testing: #5460
Tier of Testing:1
Date: 01/08/2021

Testing Process: C&D aircraft, load simbrief flight plan, test all switches for function, check switches highlight/tooltip on switches
Aircraft appears to function normally, no obvious, large issues, strobes work in auto correctly, overhead light panel overall appears to function correctly, tested gear up on ground, tested console light switches. 
 
Negatives: 

Actual concerns, 
Master caution/warning cannot be cleared through their corresponding buttons. 


Tool tip issues below, not really concerned about these references as the majority of them coincide with items not readily used or implemented. 

Autopilot turning knobs do not have references as to what they do (not sure if they are supposed to I admit) 
Pilot and Co-Pilot side, center panel, flood light switch does not provide tool tips without using the "lock" function. Majority of other switches provide tool tips outside of lock function. 
Cabin pressure switch panel does not provide tool tips
Nav Align Knobs 1-3 do not provide tool tips
IR 1-3 do not provide tool tips
EVAC panel horn shutoff and CAPT & PURS switch do not provide tool tips
Calls panel, MECH through AFT do not provide tool tips
AID Print and DFDR Event do not provide tool tips
Master warning clear does not provide a tool tip
Fire panel does not provide tool tips
Chrono buttons beside autopilot panel do not provide tool tips

Testing Results: Not Passed

Notes:  I do not have enough information on these below items to test. 

fix: workaround for "NOT IN DATABASE"
fix: consistent ids in template
fix: logo LT update code
fix: formatting

Do not have enough information or knowledge to test this item. 
fix: add gear lever wwise event

Conclusions: Master warning is unbearable when it can't be stopped...

**Comment by davidnorfolk96** [comment]
Quality Assurance Trainee Report

Discord: !davidn123#0001
Object of testing:5460
Tier of Testing: 1
Date: 02/08/2021

Testing Process: Followed the testing intructions given & as follows:

"Check that Master WARN/Caution can be pushed"-The button is pushable however it doesn't silence the alarm. Only way to clear them is by clearing the ECAM using CLR on the buttons by the throttles. (This is mentioned already in known issues.)

"Check that landing lights and all light switches work, and that lights retract/extend as expected"- Lights working as expected, nothing to report (apart from the ones already known) 


"Check that flight plan is able to be loaded correctly (Simbrief or menu)." - All worked as intended, nothing to report on this. 


"Check that every button in the cockpit has tooltips, can be interacted (with correct behaviour), every light knob/switch within the cockpit (pedestal lights, etc) all work. Exterior lights have some known issues, and that unfortunately will have to be mitigated in the future 0.7.0 release."- The majority of these do work. However, i have found some without tool tips.I have complied a list of the ones that don't show up. 

ADIRS 1,2,3 (Shows no tooltip) 
ENG fire panel (Overhead panel) (Shows no tooltip)
Chrono button (above side stick prioity) (Shows no tooltip)
digital chrono "run" button (Shows no tooltip)
Dome light switch (Shows no tool tip) 
MAN V/S CTL (Shows no tool tip) 


Negatives: As mentioned already, Master WRN/Caution can be pressed but does nothing. Alarms must be silenced by clearing it using "CLR" on the ECAM buttons. A few items do not have any tooltips. 

Testing Results: Not Passed

Conclusions: Nothing else to report apart from the above.

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5460
Tier of Testing: 2
Date: 03/08/2021

Testing Process: 
- Spawned in C+D at EGKK, -Performed flight from EGKK-EHAM in full, testing switches and tooltips throughout.
- loaded OFP to EHAM (EGKK was known trigger for the NOT IN DATABASE error) - Plan loaded manually and with simbrief - PASS
- Tested Master WARN/Caution switches: WARN - overspeed, clearable. Caution - TCAS standby, clearable. - PASS
- Started EFB and tested functions - PASS
- Checked textures for issues - PASS
- Tested all switches - PASS
- Tested all tooltips - PASS

Negatives: N/A
Testing Results: Passed

Conclusions: Fixes main SU5 bugs as before while addressing the WARN/CAUTION concerns. Previously missing tooltips are all sorted now, good stuff! 

Media:
Warnings cleared while overspeed and tcas warnings not resolved.

image

**Comment by sidnov** [comment]
QA Report

Object of testing: #5460
Tier of Testing: 1
Date: 3/8/2021

Testing Process:
Regular IFR/VFR Circuit patterns, testing individual switches and buttons. Test ECAM/MCDU functionality.

Negatives: Minor issues already noticed and mentioned above which can be fixed over time.

Testing Results: Passed

Conclusions: Good to go for a stable rc to fill in for the time being until the next version.

**Comment by davidnorfolk96** [comment]
Quality Assurance Trainee Report

Discord: !davidn123#0001
Object of testing: 5460
Tier of Testing:1
Date: 03/08/2021

Testing Process: Loaded in at LOWI with engines running & loaded a flightplan using simbrief & was done by using "init request" and i then went through the following checks. 

Check that Master WARN/Caution can be pushed and work as expected-PASSED

Check that landing lights and all light switches work, and that lights retract/extend as expected-PASSED

Check that flight plan is able to be loaded correctly (Simbrief or menu)-PASSED

Check that every button in the cockpit has tooltips, can be interacted (with correct behaviour), every light knob/switch within the cockpit (pedestal lights, etc) all work. Exterior lights have some known issues, and that unfortunately will have to be mitigated in the future 0.7.0 release.-PASSED


Negatives: N/A

Testing Results: Passed

Conclusions: No issues found & everything worked as intended. I did also try to replicate nuts issue as mentioned above however this did not reproduce for me. Nice work on this on mate!

**Pull request merged**
