### PR TITLE
[LIGHTS] Small Improvements & Changes

### PR DESCRIPTION
**Pull request by Snapmatics**
I basically changed a few values for the exterior lights. 

## References

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by wpine215** [comment]
Please include screenshots and a description of changes when this PR is ready to be tested.

**Comment by Snapmatics** [comment]
> 
> 
> Please include screenshots and a description of changes when this PR is ready to be tested.

Roger 👍

**Comment by Snapmatics** [comment]
> Please include screenshots and a description of changes when this PR is ready to be tested.

For some reason idk how to make this PR a draft. Can you do it please?

**Review by wpine215 — APPROVED** [review]

**Comment by tareksabet** [comment]
Name: tarek_sabet#7946
 Date of testing: Current date 17/12/2020
 Version of the sim: 1.11.7.0
 PR Tested: #2465 
 Object of test: checking exterior lights 
 Testing technique: Try-out (multiple tests)
 
 ## Steps you've made to test the Pull Request:
 * spawned on runway
 *did couple of takeoffs and landings 
 * and did a go-around to check the lights on the runway

 ## Overall Rating: Good
 #### Conclusions of the testing:
* Working as described, LGTM

**Pull request merged**
