### PR TITLE
fix: Prevent TCAS STBY warning from appearing in wrong flight phase

### LINKED ISSUE #3490: [BUG] Adirs do not align at CYYC airport
**Mod Version**

"built": "2021-02-12T06:54:37+00:00",
  "ref": "fbw",
  "sha": "2d2a45e7e53fb7d57c7c2394480bac5f690a8e4a",
  "actor": "aguther",
  "event_name": "manual"

**Describe the bug**

The ADIRS simply do not align anywhere at CYYC airport. Tried various gates. Simply says NAV TCAS STBY on the ECAM. 

**To Reproduce**

1. Load in C&D at a gate
2. Battery on -->external on--> Adirs to NAV
3. ADIRS never align

**Expected behavior**

Adirs should have aligned.

**Actual behavior**

 They did not

**References**

**Additional context**

Was this working before/when did the issue start occurring?
-First time loading into CYYC with the A32NX mod. 

Is this a problem in the vanilla unmodded game?
Dont think so. I dont think any of the default aircraft have adirs alignment.

Discord username (if different from GitHub):

Jer2929(PunchDkns99)

### PR DESCRIPTION
**Pull request by beheh**
Fixes #3490

## Summary of Changes

Fixes a missing explicit flight phase check from #3378. This prevents the message from spuriously being triggered on ground due to a flight phase change.

In addition I've removed it from the STS page, because after researching this more I believe there is no possible way that NAV TCAS STBY and STS TCAS can appear at the same time, due to the former TCAS FAULT to be false and the latter requiring TCAS FAULT to be true.

Not adding to CHANGELOG as I'm fixing something minor that was only added this release and already has a CHANGELOG entry.

## Additional context

Discord username (if different from GitHub): BehEh#1234

## Testing instructions

1. Spawn cold and dark
2. Ensure the TCAS switch is set to STBY
3. Observe no amber NAV TCAS STBY warning, only the green TCAS STBY memo (on the right)
4. Take off with TCAS remaining in STBY
5. Upon T.O INHIBIT disappearing, observe:  
NAV TCAS STBY warning in amber
TCAS STBY memo turning amber
6. Turn the ADIRS off and observe NAV TCAS STBYs disappearing and NAV TCAS FAULT appearing (TCAS STBY memo remains amber)
7. TCAS should appear on the STATUS page only together with TCAS FAULT (remains when clearing), but never together with NAV TCAS STBY

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by tyler58546 — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 14.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3492
Tier of testing: 1
Changes to observe: NAV TCAS STBY and STS TCAS warnings
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Prepared for take off
3.) Set TCAS to STBY
4.) Only green TCAS STBY momo on the right (Image1)
5.) Took off (Image2)
6.) After T.O INHIBIT (Image3)
7.) Turned ADIRS off (Image4)
8.) CLR Status (Image5)

Media:


Image1


Image2


Image3


Image4


Image5

Issues: None

Overall Rating: Good

Conclusions of the testing: Woks as in description!

Hope this helps :-)

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/14/2021
Version of the sim: 1.12.13.0
PR Tested: #3492 
Tier of testing: 1
Changes to observe: That TCAS STBY dont appear in wrong flight phase.

Testing technique: Checking TCAS STBY warnings behaviour.

Steps you've made to test the Pull Request: 
1. C&D startup and doing procedures as normal only with tcas off. 
2. T.O INHIBIT disappearing and warnings went amber with a ping sound. 
3. Turned off ADIRS mid flight and the NAV TCAS STBYs disappeared and NAV TCAS FAULT appeared. As well as TCAS FAULT came up int status page and remains after hitting clr.

Flight notes (When done a full flight): Take off and landings at ENVA only.

Media: Screenshots from marcman86 describes it visually :)

Issues (If Any): None.

Overall Rating: Good.
Conclusions of the testing: No issues all works as described. LGTM.

**Comment by beheh** [comment]
Small fix, tested and approved, I'm merging this.

**Pull request merged**
