### PR TITLE
feat: coffee cup

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Added coffee cups to cockpit
    * Can be shown/hidden by clicking on them

## Screenshots (if necessary)

image

## Testing instructions

Make sure there is a coffee cup next to the EFB.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by pepperoni505 — APPROVED** [review]
LGTM

**Comment by Darlack6** [comment]
Category: QA Trial
Name: Darlack#3281
Date of testing: 9/12/2021
Version of the sim: 1.12.13.0
PR Tested: #3448
Tier of testing: 1
Changes to observe:
Coffee cup.

Testing technique: Try out
Steps you've made to test the Pull Request:

1. Spawned Cold and Dark at CYYZ,
2. looked to the left and found the coffee cup

**Media**
https://user-images.githubusercontent.com/78220630/107733723-b2dd3580-6cc9-11eb-92a2-99b4fa04a76c.jpg

Issues (If Any): None
Overall Rating: Great, Can stay energized on long hauls now!
Conclusions of the testing: LGTM

**Comment by St54Kevin** [comment]
It is waay out of scale and doesnt fit into that cup holder. It needs to be smaller

**Comment by foxmike80** [comment]
Personally, I do not like the idea of adding more "eye-candy" objects. After all, they will cost some performance. I'd rather have a real cup of coffee on my desk and the plane not filled with things that serve no real purpose in terms of flying. Just my 2 cents.

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 12.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3479 
Tier of testing: 1

### Changes to observe: Coffeeeee!

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on runway
2. Checked coffee cup next to EFB

### Media:
image
image

### Issues (If Any): 
Size of the model needs to be fixed. Looks a bit bigger than the slot.

### Overall Rating: 
Needs slight improvement

### Conclusions of the testing: 
A visual add to the aircraft, doesn't affect the performance at all. Though the model is good enough, the size needs to be adjusted appropriately.

**Comment by ErikNL80** [comment]
Maybe it is an idea to link the coffee cup to a cabin FWD call? So pressing the call would play a sound (like the Aerosoft bus) and place the coffee cup? After that clicking the cup will remove it again?

**Comment by ExampleWasTaken** [comment]
> 
> 
> Maybe it is an idea to link the coffee cup to a cabin FWD call? So pressing the call would play a sound (like the Aerosoft bus) and place the coffee cup? After that clicking the cup will remove it again?

That would interfere with the cabin call for the ECAM LDG and T.O. memos, wouldn't it? You could implement something like `if there is no ECAM memo active place/remove cup` but I think that could cause bugs when the status is determined incorrectly.

**Comment by SaqibSiddiqi** [comment]
> 
> 
> > Maybe it is an idea to link the coffee cup to a cabin FWD call? So pressing the call would play a sound (like the Aerosoft bus) and place the coffee cup? After that clicking the cup will remove it again?
> 
> That would interfere with the cabin call for the ECAM LDG and T.O. memos, wouldn't it? You could implement something like `if there is no ECAM memo active place/remove cup` but I think that could cause bugs when the status is determined incorrectly.

or we could just do it when the all stations call button is pressed

**Comment by ErikNL80** [comment]
> > > Maybe it is an idea to link the coffee cup to a cabin FWD call? So pressing the call would play a sound (like the Aerosoft bus) and place the coffee cup? After that clicking the cup will remove it again?
> > 
> > 
> > That would interfere with the cabin call for the ECAM LDG and T.O. memos, wouldn't it? You could implement something like `if there is no ECAM memo active place/remove cup` but I think that could cause bugs when the status is determined incorrectly.
> 
> or we could just do it when the all stations call button is pressed

Correct, I use the ALL call now in flight, so FWD call can be used for coffee or vice versa ;)

**Comment by sidnov** [comment]
> Maybe it is an idea to link the coffee cup to a cabin FWD call? So pressing the call would play a sound (like the Aerosoft bus) and place the coffee cup? After that clicking the cup will remove it again?

Or maybe link it to the EFB again, like an ON/OFF switch. But since this is just an initial PR to get the cup model into the aircraft, I'd give it a shot as it doesn't really hamper the performance. At least it's more visually appealing than the Pilot/Copilot models

**Comment by Watsi01** [comment]
> At least it's more visually appealing than the Pilot/Copilot models

Don't blame them. They've been through a rough night.

**Comment by sidnov** [comment]
> > At least it's more visually appealing than the Pilot/Copilot models
> 
> Don't blame them. They've been through a rough night.

Not blaming anyone lol, but I just noticed it was a broken PR.

**Comment by ExampleWasTaken** [comment]
> 
> 
> > > > Maybe it is an idea to link the coffee cup to a cabin FWD call? So pressing the call would play a sound (like the Aerosoft bus) and place the coffee cup? After that clicking the cup will remove it again?
> > > 
> > > 
> > > That would interfere with the cabin call for the ECAM LDG and T.O. memos, wouldn't it? You could implement something like `if there is no ECAM memo active place/remove cup` but I think that could cause bugs when the status is determined incorrectly.
> > 
> > 
> > or we could just do it when the all stations call button is pressed
> 
> Correct, I use the ALL call now in flight, so FWD call can be used for coffee or vice versa ;)

Yep that's a great idea! Didn't think of that!

**Comment by Awemeter** [comment]
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 2/12/2021
Version of the sim: 1.12.13.0
PR Tested: #3479 
Tier of testing: 1
Changes to observe:
Add coffee cup.

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request: Tried out.
1. Loaded into the hanger and checked for the coffee cup.
2. Loaded into KLAX C&D and checked for the coffee cup.
3. Looked around the coffee cup to check for model conflicts.
4. Looked around the plane for any model issues.

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
image

Issues (If Any): Coffe cup goes inside of the plastic around the cup holder: 
image

Steps to achieve the issue
Spawn anywhere and look at the back of the coffee cup near the window.

Overall Rating: Good
Conclusions of the testing: I am so excited to have this on the plane great work Tyler. I think we should put the coffee cup on the FO side too.

**Comment by Awemeter** [comment]
> > > > > Maybe it is an idea to link the coffee cup to a cabin FWD call? So pressing the call would play a sound (like the Aerosoft bus) and place the coffee cup? After that clicking the cup will remove it again?
> > > > 
> > > > 
> > > > That would interfere with the cabin call for the ECAM LDG and T.O. memos, wouldn't it? You could implement something like `if there is no ECAM memo active place/remove cup` but I think that could cause bugs when the status is determined incorrectly.
> > > 
> > > 
> > > or we could just do it when the all stations call button is pressed
> > 
> > 
> > Correct, I use the ALL call now in flight, so FWD call can be used for coffee or vice versa ;)
> 
> Yep that's a great idea! Didn't think of that!

Sounds great but maybe we can put a setting in the efb or link it to the boarding door close or open.

**Comment by ExampleWasTaken** [comment]
Category: QA Tester/Trial
Name: ExampleWasTaken#0886
Date of testing: 12/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3479
Tier of testing: 1
Changes to observe:
implementation of the coffee cup


Testing technique:
Steps you've made to test the Pull Request:
1. Loaded C&D
2. Checked that there is a coffee cup

Flight notes (When done a full flight): N/A

Media: 
Microsoft Flight Simulator Screenshot 2021 02 12 - 13 08 05 16
Microsoft Flight Simulator Screenshot 2021 02 12 - 13 09 25 48


Issues (If Any): Coffee cup goes inside cockpit model on the outer side
Steps to achieve the issue:
Load into the aircraft > switch to the drone camera > check that the coffee cup goes inside the cockpit model on the outer side


Overall Rating: Good
Conclusions of the testing: The cup should fit properly in its holder. Other than that minor thing it's great!

**Comment by Benjozork** [comment]
I think we should have an option for this.

**Comment by Samueleonard** [comment]
is a click spot an option?

**Comment by DarkOfNova** [comment]
> is a click spot an option?
Yes it is

**Comment by tyler58546** [comment]
* Added cup to f/o side
* You can now show/hide the cup by clicking on it

**Comment by pepperoni505** [comment]
@tyler58546 Can you scale it down a bit?

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 12/2/21
Version of the sim: 1.12.13.0
PR Tested: #3479 
Tier of testing: 1
Changes to observe:
Coffee Cup

Testing technique: Loaded in and tried to remove/ place
Steps you've made to test the Pull Request:
1. Loaded in 
2. Looked at both 
3. Clicked to remove/add

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: Looks good, a scale-down would be quite nice as pointed out by pepperoni505 above

**Comment by tyler58546** [comment]
> 
> 
> @tyler58546 Can you scale it down a bit?

Forgot to mention I scaled it down by 10% when I added it to both sides. Do you think it should be scaled down even more?
image

**Comment by FlightSimmer7700** [comment]
in my opinion yes

**Comment by pepperoni505** [comment]
> > @tyler58546 Can you scale it down a bit?
> 
> Forgot to mention I scaled it down by 10% when I added it to both sides. Do you think it should be scaled down even more?
> image

Maybe a little bit

**Comment by tyler58546** [comment]
@pepperoni505 @FlightSimmer7700 How does this look?
image

**Comment by Kacper848** [comment]
> > @tyler58546 Can you scale it down a bit?
> 
> Forgot to mention I scaled it down by 10% when I added it to both sides. Do you think it should be scaled down even more?
> image

Personally, I think this looks good. Feels the cup is more stable than when its scaled down even more.

**Comment by pepperoni505** [comment]
> @pepperoni505 @FlightSimmer7700 How does this look?
> image

This looks a lot better

**Comment by tyler58546** [comment]
> 
> 
> Personally, I do not like the idea of adding more "eye-candy" objects. After all, they will cost some performance. I'd rather have a real cup of coffee on my desk and the plane not filled with things that serve no real purpose in terms of flying. Just my 2 cents. Or at least make it optional.

The cup has only 358 faces. There is no way it will cause any significant performance impact.

**Comment by foxmike80** [comment]
> > Personally, I do not like the idea of adding more "eye-candy" objects. After all, they will cost some performance. I'd rather have a real cup of coffee on my desk and the plane not filled with things that serve no real purpose in terms of flying. Just my 2 cents. Or at least make it optional.
> 
> The cup has only 358 faces. There is no way it will cause any significant performance impact.

Well, a coffee cup here, visible pilots there and who knows what will come next - it all sums up. For me this is the line between "flying a simulator" (everything should _work_ as if it were real) and "playing an airplane game" (everything should _look_ as if it were real). I would not trade one single millisecond of GPU time for the latter one. And again, just expressing my point of view.

All that aside, I just want to emphasize my deepest gratitude and sincerest appreciation for what the people of the FBW group have managed to achieve on the "work as if it were the real thing" side here.

**Comment by wpine215** [comment]
> 
> 
> > > Personally, I do not like the idea of adding more "eye-candy" objects. After all, they will cost some performance. I'd rather have a real cup of coffee on my desk and the plane not filled with things that serve no real purpose in terms of flying. Just my 2 cents. Or at least make it optional.
> > 
> > 
> > The cup has only 358 faces. There is no way it will cause any significant performance impact.
> 
> Well, a coffee cup here, visible pilots there and who knows what will come next - it all sums up. For me this is the line between "flying a simulator" (everything should _work_ as if it were real) and "playing an airplane game" (everything should _look_ as if it were real). I would not trade one single millisecond of GPU time for the latter one. And again, just expressing my point of view.
> 
> All that aside, I just want to emphasize my deepest gratitude and sincerest appreciation for what the people of the FBW group have managed to achieve on the "work as if it were the real thing" side here.

These two things are not mutually exclusive. With MSFS's engine, the additional vertices brought on by any of our model additions will have **zero** affect on performance. And the visible pilots is not currently in the development branch of the game, and it is optional and turned off by default.

**Comment by foxmike80** [comment]
> > > > Personally, I do not like the idea of adding more "eye-candy" objects. After all, they will cost some performance. I'd rather have a real cup of coffee on my desk and the plane not filled with things that serve no real purpose in terms of flying. Just my 2 cents. Or at least make it optional.
> > > 
> > > 
> > > The cup has only 358 faces. There is no way it will cause any significant performance impact.
> > 
> > 
> > Well, a coffee cup here, visible pilots there and who knows what will come next - it all sums up. For me this is the line between "flying a simulator" (everything should _work_ as if it were real) and "playing an airplane game" (everything should _look_ as if it were real). I would not trade one single millisecond of GPU time for the latter one. And again, just expressing my point of view.
> > All that aside, I just want to emphasize my deepest gratitude and sincerest appreciation for what the people of the FBW group have managed to achieve on the "work as if it were the real thing" side here.
> 
> These two things are not mutually exclusive. With MSFS's engine, the additional vertices brought on by any of our model additions will have **zero** affect on performance. And the visible pilots is not currently in the development branch of the A32NX, and it is optional and turned off by default.

Thank you, wpine215, for clarification. I'm really relieved to learn that these additions won't impact performance at all and that they will be be optional. Keep up the magnificent work.

**Comment by marcman86** [comment]
Name: marcman86
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested:  #3479
Tier of testing: 1
Changes to observe: Looking for coffee
Testing technique: Tryout

Steps you've made to test the Pull Request:

1.) Spawn C&D EDDP
2.) Found coffee for Captain and F/O (Image1)
3.) Clicked on them to hide them
4.) Clicked on them again to show them

Media:


Image1

Issues (If Any): None

Overall Rating: Good

Conclusions of the testing: Works and looks nice! Size fits to the cup holders. Shadows show and disappear with them.

Would be awesome in future to have a clickzone on top to play a sip sound :-D

Hope this helps :-)

**Comment by vpilotdesigns** [comment]
Category: QA Tester
Name: V-Pilot#7116
Date of testing: 2/13/21
Version of the sim: 1.12.13.0
PR Tested: #3479
Tier of testing: 1
Changes to observe:
Coffee Cup

Testing technique: Loaded Removed and Replaced

Loaded in
Removed both cups
Clicked to remove/add

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Microsoft Flight Simulator 2_13_2021 2_39_57 PM

**Comment by DarkJJE** [comment]
Would it possible to implement a function for two different cup designs for Capt and F/O?

**Pull request merged**
