### PR TITLE
fixed stripe on glareshield texture

### LINKED ISSUE #1212: [BUG] windshield divider dark texture
**Mod Version**

master

**Describe the bug**

bad texture

vanilla:
image

master:
image

**References**

image

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by Pleasure0102**
Fixes #1212

## Summary of Changes
changed texture to remove stripe. (color based on updated asobo color) to match with pedestal and main panel

## Screenshots (if necessary)
Before:
image
After:
image

## References
image

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by DarkOfNova** [comment]
@Pleasure0102  fixed his own mistake, looks fine once again xD 

Can be merged

**Comment by Pleasure0102** [comment]
@DarkOfNova you should have seen the mistake too :) when it was on PR, so should all of the QA :)

But yes it was my mistake, i own up to it.

**Review by Carter633 — APPROVED** [review]
Name: Carter633 #1436
Date of testing: Current date 09/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1216

Testing technique: Spawned at gate and checked centre pillar
Steps you've made to test the Pull Request:
1. Spawned at EGKK cold & dark, checked visuals of the centre beam
2. Moved camera around screen to check different angles
3. Amended weather/time of day and cockpit lighting to check issue fixed

Overall Rating: Good
Conclusions of the testing: Issue appears fixed, no problems found

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: Current date 09/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1216

Testing technique: Try-out
Steps you've made to test the Pull Request:

- Spawned at day 
- Spawned at night

Overall Rating: Good
Conclusions of the testing: LGTM, but what do I know I missed it the first time :D 

PIC:
c02
c03
c01

**Comment by lukecologne** [comment]
LGTM, no Tarek engraving in sight 😄

**Pull request merged**
