### PR TITLE
feat(efb): Flypadosv3 checklists

### LINKED ISSUE #4443: Checklists on EFB
**Is your feature request related to a problem? Please describe.**

Can we get checklist on EFB? I dont think its that hard to implement since its already on the toolbar. It would be great. 
**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

### PR DESCRIPTION
**Pull request by schmidHolger**
Fixes #4443

## Summary of Changes

Added support for checklists in EFB - following up on issue #4443 
- manual checked items that can be checked / unchecked by clicking on the item 
- automtically checked items based on the state of the aircraft (state could be overwritten by double clicking)
- setting a checklist complete and advancing to the next checklist in the sequence
- resetting already complete checklists

### Checklist in its inital state (e.g. "Before start" checklist)

01_Checklist_Start
- Before start checklist active
- No manual item checked yet - toggle check state by single clicking on them
- One automatic item already checked based on the state of the A/C (the automatic checked items are marked with *)

### Checklist with a few items already checked

02_Checklist_FewItemsChecked
- Few manual items are selected (items in green)

### Checklist with an overwritten automatic checked item

03_Checklist_AutomaticResultOverwritten
- One automatically checked item has been overwritten (ADIRS) and marked checked (colored in blue to distinguish from the manual items) - toggle the overwrite by double clicking onto this item

### Checklist with all items checked - not yet completed

04_Checklist_Complete
- All checklist items checked
- Checklist can be completed by clicking on the "Complete checklist" button

### One checklist completed

05_Checklist_AfterCompleteSelected
- After "Checklist complete" has been selected, the next checklist is automatically displayed
- After a checklist is complete, the automatically checked items are no longer evaluated

### Checklist reset

06_Checklist_ChecklistReset
- After a checklist has been set to complete, it can be reset by selecting "Reset checklist" in case you like to go over the items again.

## References

Using the checklist provided in #4443 

## Additional context

As discussed with EricSharp, I am creating this as a pull request for the flypadosv3 branch.

Discord username (if different from GitHub): geholger#9751

## Testing instructions

1. Open EFB after aircraft is started
2. Select Checklist from the Toolbar (the checkmark)
3. Select a checklist
4. Single click on a manual checklist items 
 - item will toggle between white (not checked) and green (checked)
5. Change condition for automatic checklist items, e.g. rudder trim, beacon, TCAS, ...) to toggle the state for those items
 - checklist item should be shown in white (no checked) resp. green (checked) if all conditions are ok
6. Overwrite a checked state for an unchecked automatic item 
 - e.g. set rudder trim set to non-zero --> checklist item should then be shown in white 
 - double clicking on this item --> item should be marked checked but shown in blue
7. Complete a checklist 
 - list should be marked green in the tabs
 - next checklist should be displayed automatically
 8. Reset a completed checklist
 - complete a checklist  / see 7,
 - select checklist again and click on "Reset checklist"
 - all manual items should be shown on white
 - automatic items show the current state of the condition for the item (white or green)
 - no automatic items are overwritten

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by CptBayer** [comment]
cool :-) !!!!

**Comment by tracernz** [comment]
Is it possible to disable the "automatic" function? I don't think a proper EFB has that. ;)

**Comment by Benjozork** [comment]
This is gonna need a bit of styling improvements (some elements have too low contrast) and some layout changes. Other than that. it seems you were using a pretty strict line length config to write this code which makes it hard to read at least for me.

Otherwise, great PR and thanks for the contribution.

**Comment by schmidHolger** [comment]
> Is it possible to disable the "automatic" function? I don't think a proper EFB has that. ;)

Unfortunately, I do not have access to a real life Airbus EFB. I was using this idea from Boeing 777 - at least PMDG’s implementation has that feature for their electronic checklist in their aircraft. But sure, this can be disabled - we could leave this as an option as well. Do you probably have a real life A320 pilot I could contact about?

**Comment by Benjozork** [comment]
@schmidHolger Do you have discord so we can discuss design in our channels?

**Comment by tracernz** [comment]
> > Is it possible to disable the "automatic" function? I don't think a proper EFB has that. ;)
> 
> Unfortunately, I do not have access to a real life Airbus EFB. I was using this idea from Boeing 777 - at least PMDG’s implementation has that feature for their electronic checklist in their aircraft. But sure, this can be disabled - we could leave this as an option as well. Do you probably have a real life A320 pilot I could contact about?

You can assume the tablet does not communicate with the aircraft.

**Comment by ErickSharp** [comment]
Hello, you were supposed to have opened a pull request on my fork's flypad os 3 branch 🙀

**Comment by ErickSharp** [comment]
> Is it possible to disable the "automatic" function? I don't think a proper EFB has that. ;)

I think this functionality can stay for those who would like it. It doesn't necessarily have to be a 1:1 interpretation of an EFB in real life! : )

**Comment by tracernz** [comment]
> I think this functionality can stay for those who would like it. It doesn't necessarily have to be a 1:1 interpretation of an EFB in real life! : )

I'm not suggesting getting rid of it... just making it possible to disable it as it will be quite annoying if you're used to doing checklists normally. :P

**Comment by schmidHolger** [comment]
> @schmidHolger Do you have discord so we can discuss design in our channels?

@Benjozork Just updated the info the description: geholger#9751. What's yours so I can contact you?

**Comment by Pushok154** [comment]
looks great, but imho, you have to do c/l like in real plane with airbus LPC conctpt in EFB`s eQRH app, if you need i would give you pictures of this programm
for examle

**Comment by tracernz** [comment]
> looks great, but imho, you have to do C/L style like in real plane with airbus LPC concept in EFB`s eQRH app, if you need i would give you pictures of this programm, and real A320 EFB C/L is not automatic, items are to be cheked manually. for examle

Thank you! That's exactly what I'd like to see. :D

**Comment by schmidHolger** [comment]
> looks great, but imho, you have to do C/L style like in real plane with airbus LPC concept in EFB`s eQRH app, if you need i would give you pictures of this programm, and real A320 EFB C/L is not automatic, items are to be cheked manually. for examle 

Thanks for your feedback. According to github, you a rated A32nx pilot :-). Are you talking about this eQRH App: https://apps.apple.com/de/app/airbus-electronic-qrh-eqrh/id1206864539

Is this app officially being used in the A32nx? If so, I would suggest that I will two changes:
- remove the automatic checks (although I like the personally but if this is not available IRL then this doesn't matter)
- do the design similar to the eQRH app @Pushok154 was suggesting 

@tracernz @Benjozork @ErickSharp: Are we running into any licensing, IP related issues for the a32nx if we have an app that is similar like the eQRH app? Do we need their (Navblue Inc.) ok to do it in a similar way?

**Comment by Pushok154** [comment]
> > looks great, but imho, you have to do C/L style like in real plane with airbus LPC concept in EFB`s eQRH app, if you need i would give you pictures of this programm, and real A320 EFB C/L is not automatic, items are to be cheked manually. for examle
> 
> Thanks for your feedback. According to github, you a rated A32nx pilot :-). Are you talking about this eQRH App: https://apps.apple.com/de/app/airbus-electronic-qrh-eqrh/id1206864539
> 
> Is this app officially being used in the A32nx? If so, I would suggest that I will two changes:

yep, this is official airbus software, doesn`t matter what airbus you fly, the content of eQRH depends on database which is provided by operator and tail number inserted during eQRH start.

**Comment by Benjozork** [comment]
I'm personally strongly against replicating this UI. It's not very attractive and is entirely different to the rest of the EFB. The concept behind our EFB is to have one unified UI that looks consistent, it's not like other sim EFBs where we have separate "apps".

Furthermore the EFB is allowed to be unrealistic. We already have simBrief import, ground services etc. that do not exist IRl. I don't think realism is a factor here except in terms of the checklist items and contents.

**Comment by ErickSharp** [comment]
> > looks great, but imho, you have to do C/L style like in real plane with airbus LPC concept in EFB`s eQRH app, if you need i would give you pictures of this programm, and real A320 EFB C/L is not automatic, items are to be cheked manually. for examle
> 
> Thanks for your feedback. According to github, you a rated A32nx pilot :-). Are you talking about this eQRH App: https://apps.apple.com/de/app/airbus-electronic-qrh-eqrh/id1206864539
> 
> Is this app officially being used in the A32nx? If so, I would suggest that I will two changes:
> 
> * remove the automatic checks (although I like the personally but if this is not available IRL then this doesn't matter)
> * do the design similar to the eQRH app @Pushok154 was suggesting
> 
> @tracernz @Benjozork @ErickSharp: Are we running into any licensing, IP related issues for the a32nx if we have an app that is similar like the eQRH app? Do we need their (Navblue Inc.) ok to do it in a similar way?

This is not something that we would really even explore, I don't see the need in pulling from an app like this 🤷

**Comment by tracernz** [comment]
The functionality and organisation is the important bit. Of course we can use our own common design.

**Comment by ErikNL80** [comment]
A typo on the screenshots, parking break should be parking brake!

**Comment by schmidHolger** [comment]
Give me a break ;-)))

**Comment by schmidHolger** [comment]
Setting  this PR to draft as we still have to agree on the final design.

**Comment by ErickSharp** [comment]
I incorporated some portions of your code into the recently done implementations of the checklist so I am going to close this down, but there is some functionality that I omitted for the time being, namely the flight phased influence so feel free to let me know if you would like to work on this feature sometime in the near future! 🤤

**Pull request closed without merging**
