### PR TITLE
feat: improved startup, idle, and cabin wind sound and added GPWS self test sound events

### PR DESCRIPTION
**Pull request by hotshotp**
Fixes #[issue_no]

## Summary of Changes

Heavily changed the startup bass, so it has two pitches going up during startup
Tweaked the sound of the idle from front and behind engine
Got a new cabin wind sound which reacts to flap changes and thrust levels
Replaced the GPWS callouts for too low terrain/gear/flaps, dont sink, and sink rate
Made the packs in the cabin more bassy

Changed the flight attendants seats for TO/Landing to V1 simulations voice - more PAs from him to come soon with the logic, but this is the first step

Added the wwise events for GPWS short and long test - GPWS_test_short, GPWS_test_long and for chronometer buttons

Renamed ASOBO_A320neo_Improved packages to FBW_A320neo
## References

Engineer feedback, and videos

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Turn on APU bleed and listen in cabin for bass. When starting engines pay attention to the sound of it, then check idle behind and in front of wing. When taking off, cruising, approaching, and landing check the cabin and cockpit wind levels. Cockpit wind should not be exactly different, maybe some volume tweaks- but cabin wind should be a lot higher quality. Lastly if you can, try to test out the GPWS callouts mentioned in the PR description.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by ImenesFBW — APPROVED** [review]
LGTM!

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5314
Tier of Testing: 1
Date: 13/07/2021

Testing Process:

1. Spawned C&D
2. Startup while in cabin view
3. Performed circuit (KPHX)
4. Arrived to gate to test rest of sounds
5. Also tested GPWS callouts

Negatives: N/A
Testing Results: Passed

Conclusions: Sounds have been improved (especially the startup)!

**Comment by MapleNAV-TCASFAULT** [comment]
Quality Trainee Report

Discord: 𝕄𝕒𝕡𝕝𝕖#3904
Object of testing: #5314
Tier of Testing: 1
Date: 13/07/2021

Testing Process: 
- Did whole flight from EGKK-EGJJ path: IMVU1Z IMVUR N63 LELNA JSY1W during the flight, I checked the following
     - Checked startup sounds from front and rear of the wing all seemed to be good, sounding really nice
     - Listened to the idle and the idle transitioning to spool on taxi, sounds good
     - Checked new voice from V1 sim in takeoff and landing announcements and while in the cabin I checked the new packs
     - New medium touchdown was added and landed at the perfect fpm to fortunately hear new touchdown sample
     - Parked at gate and did other tests after the flight (GPWS)

Negatives: All good
Testing Results: Passed

Conclusions: As always awesome work and always a pleasure to test these sounds!
Media: N/A but avail in the #sound channel at our discord server

**Comment by dragold** [comment]
Category: QA Tester trainee
Name: Mr.Blank#0001
Date of testing:07/14/2021
The version of the sim: 1.17.3.0
PR Tested: #5314
Tier of testing: 1

Changes to observe:
Heavily changed the startup bass, so it has two pitches going up during startup
Tweaked the sound of the idle from the front and behind the engine
Got a new cabin wind sound that reacts to flap changes and thrust levels
Replaced the GPWS callouts for too low terrain/gear/flaps, don't sink, and sink rate
Made the packs in the cabin more bassy
Changed the flight attendants seats for TO/Landing to V1 simulations voice - more PAs from him to come soon with the logic, but this is the first step
Added the wwise events for GPWS short and long test - GPWS_test_short, GPWS_test_long and for chronometer buttons
Renamed ASOBO_A320neo_Improved packages to FBW_A320neo
Testing instructions
Turn on APU bleed and listen in the cabin for bass. When starting engines pay attention to the sound of it, then check idle behind and in front of the wing. When taking off, cruising, approaching, and landing checks the cabin and cockpit wind levels. Cockpit wind should not be exactly different, maybe some volume tweaks- but cabin wind should be a lot higher quality. Lastly, if you can, try to test out the GPWS callouts mentioned in the PR description.

Testing technique: Tryout

Methodology:
-All as per Testing instructions 
--consistency Test,  Full sop fllight
--consistency Test, Quickstart full flight
--consistency Test, Quickstart by hand test

  
references: https://ptb.discord.com/channels/738864299392630914/754130199804772372/864803174153584680
Negatives: NIL
Testing Results: Passed

Conclusions: All observations whereas expected with this PR***.

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #5314 
Tier of Testing: 1
Date: 15/7/21

Testing Process: 
Loaded on runway, C&D, on approach to check sounds
Did a circuit to check all sounds
Negatives: N/A
Testing Results: Passed

Conclusions: LGTM, sounds great!

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5314
Tier of Testing: 1
Date: 15/07/2021

Testing Process: 
(Only tested items tweaked)
1. Spawned on runway
2. Takeoff ECAM MEMO no blue
3. Tested GPWS by triggering the warnings
4. Landing ECAM MEMO no blue

Negatives: N/A
Testing Results: Passed

Conclusions: Sounds have been improved and patches confirmed to have been fix.

**Pull request merged**
