### PR TITLE
Strobe, Nav and Beacon lights improvements

### LINKED ISSUE #905: [REQUEST] Strobes don't pulse as fast as irl
**Is your feature request related to a problem? Please describe.**

Faster Pulse 

**Describe the feature you'd like to see implemented**

Based on the IRL plane, LED bulbs tend to pulse alot quicker than the typical WF bulb. 

**References**

Any youtube video with a a320 & sharklets. 

**Additional context**

N/A

Discord username (if different from GitHub):
David Norfolk

### LINKED ISSUE #1013: [REQUEST] Strobe Light pulses to illuminate cloud and ground
**Is your feature request related to a problem? Please describe.**

No

**Describe the feature you'd like to see implemented**

The strobe lights should be capable of illuminating the surrounding clouds if one is inside cloud. Strobes are **very** high powered lights. In fact, some operators recommend turning the strobe lights off when in IMC to prevent the pilots from being disoriented. 

Right now, the strobe lights are just tiny dots on the wingtips. They should be far more obnoxious.

**References**

https://www.youtube.com/watch?v=7tnd-prQXgE

**Additional context**

Discord username (if different from GitHub):
Eefoe#0570

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes #905 and fixes #1013

**Summary of Changes**

* Decrease time between double strobes
* Tail strobe light is now single pulse
* Increase intensity of all strobe lights and navigation lights
* Make strobe lights volumetric
* Convert lower beacon to spotlight with a 180° cone, to fix light bleed issue into the showcase cameras

**Screenshots (if necessary)**

* Before
https://streamable.com/ri21xu
* After
https://streamable.com/tlw3za
https://streamable.com/h9werm

**References**

https://youtu.be/apiD-YMJnoY?t=139 (see a few seconds later for tail strobe lights)
https://youtu.be/7tnd-prQXgE?t=672

**Known issue**

* When starting on the runway, you need to switch the strobe light from auto to off once, otherwise the tail strobe effect will be played on the wing strobes (i.e single flash). It would be great if someone could help with that

### CODE REVIEW

**Comment by Snapmatics** [comment]
There are multiply views for cabin, and what about the cockpit? Is it bleeding into the cockpit?

**Comment by lukecologne** [comment]
Shouldn't, I took care of that by creating a new effect for the forward facing strobe and reducing it's range

**Comment by Snapmatics** [comment]
> Shouldn't, I took care of that by creating a new effect for the forward facing strobe and reducing it's range

Good, I will test it out :)

**Comment by Carter633** [comment]
Name: Carter633 #1436
Date of testing: Current date 03/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1049

Testing technique: Full flight from Cold and Dark Melbourne to Sydney
Steps you've made to test the Pull Request:
1. Spawned at the gate, checked lights on the ground with GPU and also APU separately.
2. Took off, strobes set to ON
3. Beacon, Nav lights appear working fine
4. No strobe lights at all visible?
5. Tried flicking strobes off/on/auto/on/off/on but still no strobes

Overall Rating: Needs Work
Conclusions of the testing: Strobes are non existent for me?

**Comment by lukecologne** [comment]
Please run build.py.

**Comment by Carter633** [comment]
working on it now

**Comment by Carter633** [comment]
Name: Carter633 #1436
Date of testing: Current date 03/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1049

Testing technique: Full flight from Cold and Dark Berlin Tegel to Heathrow
Steps you've made to test the Pull Request:
1. Spawned at Gate, Ext Pwr on, tested all lights - all functioned correctly and as described.
2. APU on, External pwr off, tested as above, all working as described
3. No bleed noticed in the flight deck
4. Checked during take off roll, all working as described
5. Checked during flight, all working as described - multiple times switched lights off and on again to check continuous on/off response throughout flight

Overall Rating: Good
Conclusions of the testing: I now know how to run build.py! Also, this is good!

**Review by Carter633 — APPROVED** [review]

**Comment by jooglestumpe** [comment]
With the merge to the latest master, strobes seem to reflect in the cockpit though

**Comment by lukecologne** [comment]
Are you sure? Can you take a video or something?

**Comment by lousybyte** [comment]
Can't replicate that, seems fine.

**Comment by jooglestumpe** [comment]
Just the latest master, apart from the Lufthansa livery (could this be related?). I noticed it during a night flight, quite off-putting...

**Comment by lukecologne** [comment]
I have tested my changes during the night, and have not seen any light bleed from the strobes into the cockpit.

**Comment by jooglestumpe** [comment]
That is strange... It's quite significant, but surely there's some explanation why I have it and you don't. Can't make a video at the moment unfortunately, will try again in a couple of hours.

**Comment by lousybyte** [comment]
I tested using a Lufthansa livery as well, if that makes any difference, although I just tested starting on runway. Not sure if being in the air makes any difference.

**Comment by fsxpilot777** [comment]
I have tested and im not getting any strobe light bleeding in the cockpit. On my end its working as described.

**Comment by RetroDreams** [comment]
Can confirm also experiencing same as @jooglestumpe describes, it does not happen on every flight making it difficult to debug I'm sure but it will reflect off of the frame inside the cockpit when no floods are turned on. Still visible with floods very dim but again, does not crop up on every flight.

**Comment by RetroDreams** [comment]
Next time it occurs I will try to capture video of it.

**Comment by waredrive** [comment]
@RetroDreams @jooglestumpe : Are you guys sure it's not the thunder bug you see? There is a bug in game which makes it thunder even when the weather is clear. Try to turn of the strobe light when you see it next time and see if the reflections are still showing in cockpit. If so, then it's the thunder bug.

**Comment by RetroDreams** [comment]
@waredrive I almost always fly with "scattered clouds" offline weather preset because of the bugged live weather system. Would this bug you're talking about occur even then?

**Comment by waredrive** [comment]
@RetroDreams: For me it occurs sporadically and independenty of the settings. I know I reacted to it when I saw the reflections a thought, as you did, that it was the strobes bleeding in, but the problem persisted even when I turned off the strobe lights. I could also faintly hear thunder in the background.

**Pull request merged**
