### PR TITLE
fix(efb): state persistence update for landing perf

### LINKED ISSUE #4575: EFB UI enhancement
**Is your feature request related to a problem? Please describe.**
I get frustrated when I can not read the efb due to colour scheme.

**Describe the feature you'd like to see implemented**
updated UI with better colour scheme to make easier to read and better icons or tabs.

**References**
efb

**Additional context**

Discord username DarkFury#4936

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

### PR DESCRIPTION
**Pull request by antonyisoardi**
Fixes #4575, Supports PR https://github.com/flybywiresim/a32nx/pull/4026

## Summary of Changes
- updated landing performance with reducer to persist state in session
- updated onchange function for select component to accept boolean as arg
- fix incorrect map theme on dashboard
- TODO: context and reducer for performance to be refactored in checklists pr

## Additional context

Discord username (if different from GitHub): antiso

## Testing instructions

- View Landing Performance view on EFB, change some values
- View another view on the EFB
- Navigate back to the Landing Performance view and observe values persisted

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by hiaaryan — APPROVED** [review]
GTG 🎉

**Comment by bouveng** [comment]
Hi! Could this not have been solved with `shouldComponentUpdate()` ?

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5104
Tier of Testing: 1
Date: 15/06/2021

**Testing Process:**
- View Landing Performance view on EFB, change some values
- View another view on the EFB
- Navigate back to the Landing Performance view and observe values persisted

**Negatives:** N/A
**Testing Results:** Passed

**Comment by Benjozork** [comment]
> 
> 
> Hi! Could this not have been solved with `shouldComponentUpdate()` ?

They are functional components

**Pull request merged**
