### PR TITLE
feat: add new sound nodes

### PR DESCRIPTION
**Pull request by pepperoni505**
Fixes #[issue_no]

## Summary of Changes

This adds 6 new nodes for sounds: `SOUND_PACK_OUTFLOW_LEFT`, `SOUND_PACK_OUTFLOW_RIGHT`, `SOUND_DOOR_FWD_LEFT`, `SOUND_DOOR_FWD_RIGHT`, `SOUND_DOOR_AFT_LEFT`, `SOUND_DOOR_AFT_RIGHT`, 

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by tyler58546 — CHANGES_REQUESTED** [review]
You need to add the model to `models.json`.

**Comment by pepperoni505** [comment]
> You need to add the model to `models.json`.

It already is - I had a previous PR adding sound_nodes (#3024). I just added a new object in this PR

**Comment by tyler58546** [comment]
> 
> 
> > You need to add the model to `models.json`.
> 
> It already is - I had a previous PR adding sound_nodes (#3024). I just added a new object in this PR

I see, my bad.

**Review by tyler58546 — APPROVED** [review]

**Comment by pepperoni505** [comment]
Don't merge this PR yet, I have to fix something

**Comment by beheh** [comment]
I've converted it back to a draft for you, you can do this in top right:

image

**Comment by pepperoni505** [comment]
> I've converted it back to a draft for you, you can do this in top right in future:
> 
> image

Sorry, I was on mobile and couldn't find the button

**Review by tyler58546 — APPROVED** [review]
LGTM

**Pull request merged**
