### PR TITLE
fix: ND waypoints, Airplane icon and Labelfontsize

### PR DESCRIPTION
**Pull request by marcman86**
Fixes #[issue_no]

## Summary of Changes

- Waypoint icon size
- Outlines on ND icons (waypoint, airports, VOR, VOR DME, constraints, Decel, other AC)
- New airplane icon
- Fix orientation on airport icons
- Label fontsize 

## References

image

## Additional context

Font on waypoint labels still overwrites with the wrong font family sometimes

Discord username (if different from GitHub):

## Testing instructions

- Do a flight plan and spawn the AC
- Look on ND for the icons (Waypoints, Decel, Airports, VOR, Constraints, ...)
- Waypoint icons should have the size of the reference image
- Icons should have outlines (visible with wether radar in the background)
- (Nearest) Airport icons should all have the same orientation
- Airplane icon should be bright yellow like the heading marker

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
why did you add so many files ? we already have most of them

**Comment by marcman86** [comment]
I did a new sub folder for the original asobo svg files as the map icon image folder gets to messy.

The only file i really add is the SvgWaypointElement.js to stop the airport icon orientation (line 236). Here github shows the lint errors. But i dont want to change the original code. Do i have to?

**Comment by marcman86** [comment]
Can someone please take a look at this? From my side this is ready (this time for real ;-)). 

Please tell me what to do to make this move on :-)

@MisterChocker @Benjozork

**Comment by Benjozork** [comment]
Do you actually use the Asobo icons anywhere?

**Comment by marcman86** [comment]
No. Its just as a backup, as i manipulate the original svg files with inkscape.

**Comment by MisterChocker** [comment]
Thanks to git you don't need to make backups.

**Comment by marcman86** [comment]
I did delete the backup files. hope this is ok like that.

Whats with the lint errors in the SvgWaypointElement.js? Do i need to change let to const for the variables shown in the lint debug log?

**Comment by MisterChocker** [comment]
@Benjozork
- Reference has been added.
- Label has been verified by @tyler58546 (see #4385)

**Comment by MisterChocker** [comment]
@marcman86 Why is the font in your screenshots different than before?

**Comment by marcman86** [comment]
Sorry for the late response. Thank you for looking into this.

The font got overwritten somewhere. I mentioned this in the additional context. Both images show the same route. Approach waypoint labels seem fine (Image2). I really looked for this. In SvgWaypointElement.js seems all labels get  "waypointLabelFontFamily": "ECAMFontRegular" from the mapConfig.json. But there is also other overwriting problems. f.e. most of the time the active (white) waypoint is one behind.

This i why i only said labelfontsize is changed.

**Comment by MisterChocker** [comment]
> Sorry for the late response. Thank you for looking into this.
> 
> 
> 
> The font got overwritten somewhere. I mentioned this in the additional context. Both images show the same route. Approach waypoint labels seem fine (Image2). I really looked for this. In SvgWaypointElement.js seems all labels get  "waypointLabelFontFamily": "ECAMFontRegular" from the mapConfig.json. But there is also other overwriting problems. f.e. most of the time the active (white) waypoint is one behind.
> 
> 
> 
> This is why i only said label fontsize is changed. 

The white waypoint is a general issue we need to solve, not a result for this pr.

**Comment by PillowPilot22** [comment]
Category: QA Tester/Trial
Name: PillowPilot#1914
Date of testing: Current date DD/MM/YYYY
Version of the sim: Version the tester uses
PR Tested: #000
Tier of testing: 1/2/3
Changes to observe:


Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Full cold and dark start up
2. Full Ifr Flight with simbrief pull requst for flight plan

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): Write any issues
Steps to achieve the issue

Overall Rating:To be improved
Conclusions of the testing: Sadly i didnt notice the amendments on testing

**Comment by marcman86** [comment]
> Conclusions of the testing: Sadly i didnt notice the amendments on testing

Hi, thanks for testing. I rechecked the PR. For me it works fine (Image), so it can be a problem on your side. Please ask for help on Discord how to test PRs (PR test labels, Installation, Mod conflicts, so on). Would be nice if you can retest it and correct your report when it works. Also please fill yout the test template completely, as its not possible to know what you tested, especially "Changes to observe:". You can also upload images. Hope this helps :-)

**Comment by PillowPilot22** [comment]
Ok, yeah i will have a look, been haing problems so i wil look again and try to stick to the file next time. thanks

**Comment by marcman86** [comment]
Hi, there is no progress on this for the last week. Would be nice if you can take a look at this PR.

Maybe something to the code review: There is not much code to review. Just changed images. Have a simple look at the ...\flybywire-aircraft-a320-neo\html_ui\Pages\VCockpit\Instruments\Airliners\FlyByWire_A320_Neo\MFD\Images folder.

The only thing we/i need confirmation is with the added SvgWaypointElement.js file as it gives PR/lint error. Do i need to change it?

**Comment by marcman86** [comment]
@MisterChocker @Benjozork 

Hi, i did this PR a month ago and it still waits for a review and the ready to test labels.

I don't know how to move on with this. 

If this PR is not wanted i can close it, just let me know.

**Comment by Benjozork** [comment]
Let's get it into testing again

**Review by Benjozork — APPROVED** [review]

**Comment by Benjozork** [comment]
Please also fix lint issues

**Comment by giridat** [comment]
Category: QA Trial
Name: Giridhar Raut #5534
Date of testing: Current date 16/05/2021
Version of the sim: 1.15.10
PR Tested: #4473
Tier of testing: 1
Changes to observe:

Waypoint icon size
Outlines on ND icons (waypoint, airports, VOR, VOR DME, constraints, Decel, other AC)
New airplane icon
Fix orientation on airport icons
Label fontsize

Testing technique: 
Full flight from VOMM to VCBI via flight plan route.
Screenshots have been attached for reference.

Steps you've made to test the Pull Request:
1. Spawned cold and dark at VOMM.
2. Setup MCDU and Flt pln.
3. Took off and cycled through different modes on ND as mentioned in summary.
4. Observed the text and font sizes, airplane icon, colors label fontsize.
5. Airport orientation and Airplane icon (Ok Tested).

Flight notes (When done a full flight): 
VOMM AKMIL BEBOK SAGOR CA IKONA KADIR ONIKO IGNIL VCBI 

Media: 
ALIGN
ARC
CO_ARC WPTS
CO_PLN
FONTS_TEXTS
NAV
NAV_02
NAV_03
OVR_LAP
PLN
PLN_02
PLN_03 jpg
PLN_04_CSTR
PLN_05_CSTR
Terr
Terr02
WPTS


Issues (If Any):  

A. Terr display on finals is too light greenish and makes it slightly difficult to see the final waypoints.

Steps to achieve the issue:
1. Conduct a flight and enable TERR on finals.
2. Observe the ND 

Overall Rating: Good 
Conclusions of the testing: Small changes to text size, boldness and color of the waypoints should polish it, I can't really make it out whether it is due to the cam POV but overall it is good to go. (OK Tested)

**Comment by MisterChocker** [comment]
> A. Terr display on finals is too light greenish and makes it slightly difficult to see the final waypoints.

To my knowledge these colors have not been changed.
You can reduce the brightness of the terrain and weather radar independently from the NDs brightness.

**Comment by frankkopp** [comment]
Category: QA Tester
Name: Cdr_Maverick#6475
Date of testing: Current date 16.05.2021
Version of the sim: 1.15.10
PR Tested: #4473
Tier of testing: 1

Changes to observe:
- Do a flight plan and spawn the AC
- Look on ND for the icons (Waypoints, Decel, Airports, VOR, Constraints, ...)
- Waypoint icons should have the size of the reference image
- Icons should have outlines (visible with weather radar in the background)
- (Nearest) Airport icons should all have the same orientation
- Airplane icon should be bright yellow like the heading marker

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Watched ND with different setting (CSTR/ARPT/...) and different weather radar
2. Sizes look good compared to reference
3. Outlines (black) visible with weather radar background
4. Airport icons all same orientation
5. Airplane has same color than heading marker

Media:
image
image

Issues (If Any): none

Overall Rating: Good
Conclusions of the testing: LGTM

**Pull request merged**
