### PR TITLE
feat(ecam): Show 'REV' in amber while reverser doors are in transit

### LINKED ISSUE #5103: Reverse Yellow
### Aircraft Version

Development

### Description

During reverse door opening/closing, the ECAM will show reverse yellow until the doors have finished opening/closing. The current version has only reverse green.

### References (optional)

Not the true color but is a reference
Capture

### Additional info (optional)

_No response_

### Discord Username (optional)

Aviation Spotter#9102

### PR DESCRIPTION
**Pull request by BlueberryKing**
Fixes #5103

## Summary of Changes
"REV" message on ECAM engine gauges is now shown in amber for two seconds while the reverser doors are opening. ~~If the thrust levers are put into reverse and immediately back to forward, the message will disappear again rather quickly. This is what is suspected to happen in the real aircraft, but is not what happens on our model (#4381).~~ This uses the same logic as the reverser door animation uses (#4381).

It might be worth it to refactor this logic and place it deeper in the FADEC logic, but this should model the basic behavior pilots see.

Sidenote 1: The "REV" seems a bit small compared to the reference image shown in the issue. Could be changed in the future.
Sidenote 2: The reverser doors are closed in idle reverse. I am not sure if this is what the real aircraft does.

## Screenshots (if necessary)

reverse-yellow

## References

- This video: https://youtu.be/WdMRFM5tOdE?t=339 . The reverser doors take about 2 seconds to open/close. This is also the amount of time used for the animation of the doors in #4381
- The image linked in issue #5103 is not a great reference, but it confirms the basic behavior of "REV" showing in amber.
- A Discord [reply](https://discord.com/channels/738864299392630914/754851312306487326/856825503759335444) indicating that the doors would probably start closing immediately during the opening process.

## Additional context

Discord username (if different from GitHub): BlueberryKing#6641

## Testing instructions

- Spawn in C/D.
- Start engines. Ensure "AVAIL" is shown in green once engines are up and running.
- Engage thrust reversers. Ensure "REV" is shown in two seconds before turning green.
- Stow away thrust reversers. Ensure "REV" is shown in amber for another two seconds before the message disappears.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5170
Tier of Testing: 1
Date: 25/6/2021

Testing Process: 

1. Spawned C&D
2. Did startup procedure and clarifying "AVAIL" still shows
3. Tested reverse thrust

Negatives: 

- Reverse idle shows reverse yellow and then reverse green while doors haven't opened (see media)
- The reverse yellow is not synchronized with the reverse door transition (see media)

Testing Results: Not Passed

Conclusions: The reverse yellow on the ECAM isn't showing if the doors are in motion. The event is only triggered by the thrust lever positions.
Media: 

https://user-images.githubusercontent.com/72807945/123381351-a19d1300-d55e-11eb-8f33-05fe9a827fec.mp4

**Review by RemineHD — APPROVED** [review]

**Comment by BlueberryKing** [comment]
@AviationSpotter Thank you for testing! I have changed to code now, so the message should show whenever the doors are in transit.

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5170
Tier of Testing: 1
Date: 25/06/2021

Testing Process: 

1. Spawned C&D
2. Did startup procedure and clarifying "AVAIL" still shows
3. Tested reverse thrust
4. Performed a normal landing while monitoring upper ECAM

Negatives: I've noticed a bug with the reverse thrust. If engines are on then reverse idle isn't possible (check media).
Testing Results: Passed

Conclusions: Regarding this test, I can confirm the previous issues have been fixed and the PR or reverse yellow now works as intended.
Media:

(THRUST LEVERS ARE MOVED AT THE SAME LEVEL USING KEYBOARD)

https://user-images.githubusercontent.com/72807945/123495136-6ba86f00-d5f0-11eb-9dfb-f9e79de5eb30.mp4

**Comment by Cryptic56** [comment]
Quality Assurance Trainee Report

Discord: Cryptic#4731
Object of testing: #5170 
Tier of Testing: 1
Date: 27/06/2021

Testing Process: Spawned cold and dark at KSAN
Started engines
Set to reverse thrust max
Checked upper ECAM.

Negatives: N/A
Testing Results: Passed

Conclusions: No issues, Great work.

**Comment by BlueberryKing** [comment]
Thank you for testing everyone and merging. Does this not need a changelog update?

**Comment by Benjozork** [comment]
Oops. Forgot about that.

Can you open a PR to add one ?

**Comment by BlueberryKing** [comment]
Did that here: https://github.com/flybywiresim/a32nx/pull/5232. Sorry!

**Pull request merged**
