### PR TITLE
feat: Christmas Livery

### PR DESCRIPTION
**Pull request by FlightSimmer7700**
Fixes #[issue_no]

## Summary of Changes

Added the christmas livery back
Special thank you to @Earthsam12 for the help
## Screenshots (if necessary)

image
image

## Additional context

Discord username (if different from GitHub): FlightSimmer7700#5438

## Testing instructions

Make sure the livery shows up as a separate selection and works as expected

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by ImenesFBW — APPROVED** [review]
LGTM!

**Comment by ShadowFrost3** [comment]
Quality Assurance Tester Report


Object of testing: #6394 
Tier of Testing:1
Date: 20/12/2021

Testing Process: 
image
image

Negatives: Maybe needs some slight tuning of reflection maps on the nose but I don't know better. Just worth mentioning, not a negative or positive because I don't pay attention to it otherwise. 

Testing Results: Passed

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #6394
Tier of Testing: 1
Date: 22.12.2021

Testing Process: 
Start C&D and runway
Night and day
Looking around with drone camera
Checking Registration Decal ON/OFF

Negatives: None functional

Testing Results: Passed

Conclusions: I find the livery detail/resolution a bit low

Media:
image

**Comment by notl3ks** [comment]
Just a tiny suggestion/thought. I think you should of (just for fun) re-named it "FlyByRudolph" and added a red nose to the front of the aircraft. Silly, but figured would be a funny to put in.

**Comment by Earthsam12** [comment]
> Just a tiny suggestion/thought. I think you should of (just for fun) re-named it "FlyByRudolph" and added a red nose to the front of the aircraft. Silly, but figured would be a funny to put in.

maybe for next year! we didn't really have time to make a new livery or really edit this one. from what I know, a new FBW livery is coming so maybe we can adopt this idea then.

**Pull request merged**
