### PR TITLE
DIR page visual rework

### PR DESCRIPTION
**Pull request by Lollo999**
## Summary of Changes
This PR aims to change the visual aspect of the DIR page to the Honeywell specs. 

NOTICE: WORK IN PROGRESS
currently not working

## Screenshots (if necessary)
For reference:
Cattura

## References
Honeywell Pegasus Step 1A manual

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by beheh** [comment]
Is work still being done on this? Is it ready? What's missing?

**Comment by wpine215** [comment]
@Lollo999 Any update?

**Comment by Lollo999** [comment]
> Is work still being done on this? Is it ready? What's missing?

I've been busy these weeks, btw I'm waiting for the new flight plan manager to be fully implemented, i think it will be easier to adapt the new page to the new fpm after it's done.

**Comment by MisterChocker** [comment]
Please consider direct integration with #4639 instead of making these changes afterwards.
However if you'd like to wait, it's fine but keep in mind the DIR page as well the FPLN page will be done from scratch within the process.

**Comment by MisterChocker** [comment]
Closing in favor of #4639 (#4953) since it looks like work came to a hold.

**Pull request closed without merging**
