### PR TITLE
Fix MCDU green dot speed

### PR DESCRIPTION
**Pull request by Evaske**
**Summary of Changes**
This fixes the green dot speed that is displayed on the PERF TAKEOFF and APPROACH pages of the MCDU. It utilises the formula from Airbus of:
`(gross weight in thousandths * 2) + 85kts`

It previously referenced random numbers added to the aircraft weight.

### CODE REVIEW

**Comment by tyler58546** [comment]
Does this change the green dot speed shown on the airspeed tape?

**Comment by Evaske** [comment]
> Does this change the green dot speed shown on the airspeed tape?

No. That is coming from a different function.

**Comment by Benjozork** [comment]
LGTM

**Comment by ImenesFBW** [comment]
Looks good to me! Tried different load-outs and din't run into any problems. Thanks !

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
