### PR TITLE
fix(mcdu): Import cost index into MCDU when importing from SimBrief

### LINKED ISSUE #3644: [BUG] Cost Index Not Displayed on MCDU Init Page After SimBrief Import
**Mod Version**

master @ f70e084 (HEAD as of now)

**Describe the bug**

After a SimBrief import, the cost index field remains amber and empty on the INIT page. It is however saved and displayed properly on other pages (e.g. PERF).
image
image

**To Reproduce**

1. Create a SimBrief OFP
2. Load UP A32NX at an airport with no flight plan
3. Turn on batts, and ext power
4. Go to MCDU init page and press init request
5. ???
6. Profit

**Expected behavior**

CI field on init page should show imported CI.

**Actual behavior**

CI field on init page is blank and amber (required entry)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Regression in approx. the last couple of weeks. Suspect #3434.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): tracernz

### PR DESCRIPTION
**Pull request by aviadnissel**
Fixes #3644

## Summary of Changes

Made sure the cost index set variable is set when importing from SimBrief.

## Additional context

Discord username (if different from GitHub): Avian#5239

## Testing instructions

- Import a flight plan from SimBrief and make sure the cost index is correct
- Create a normal flight plan from inside the simulator and make sure you can still enter cost index manually

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Kimbyeoungjang** [comment]
Change title to fix(mcdu): Import cost index into MCDU when importing from SimBrief
You can fix that title error ;)

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 25.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3649
Tier of testing: 1
Changes to observe: Import CI from SimBrief
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDB
2.) Turned on bat. and ext. power
3.) Init SimBrief F-PLN

Media:


Image1

Issues: -

Overall Rating: Good

Conclusions of the testing: Seems to work.

Hope this helps :-)

**Comment by ErikNL80** [comment]
To add on this, would you consider putting a default CI value via the EFB? This could autopopulate the MCDU when used. When using Simbrief, EFB value should be overwritten with Simvrief value.

**Comment by aviadnissel** [comment]
> To add on this, would you consider putting a default CI value via the EFB? This could autopopulate the MCDU when used. When using Simbrief, EFB value should be overwritten with Simvrief value.

As I am very new to everything here this is a minimal change that I figured I could start with :) more stuff can be added separately I think

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 27/2/21
Version of the sim: 1.13.16.0
PR Tested: #3649 
Tier of testing: 1
Changes to observe:
CI import with SimBrief

Testing technique: Loaded in and tried with multiple flights
Steps you've made to test the Pull Request:
1. Loaded in
2. Tried with one flight (CI8)
3. Another flight (CI27)
4.And another (CI100)

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Cost Index is imported as expected. LGTM

**Comment by omarsmak** [comment]
Can this PR be merged or does it need work?

**Comment by aviadnissel** [comment]
> Can this PR be merged or does it need work?

As far as I can tell - two QA tests, thumbs up for the code, so I think it's good to go?

**Comment by beheh** [comment]
@aviadnissel Could you fix the CHANGELOG conflict here? Then I can merge this.

**Pull request merged**
