### PR TITLE
fix(mcdu): waypoint deletion not showing in tmpy fp

### PR DESCRIPTION
**Pull request by pareil6**
## Summary of Changes
A flight plan version increment call got lost when Asobo's FPM changes from SU3 were imported, causing deleting a waypoint to not be reflected in the TMPY flight plan.

## Screenshots (if necessary)
Before:
image

After:
image

## References
N/A

## Additional context

Discord username (if different from GitHub): pareil6#0990

## Testing instructions
Try deleting a waypoint, check the TMPY flight plan updates with the change. Note that this does not fix any other waypoint deletion issues that were there before SU3 - it simply fixes a regression from SU3 changes being imported.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Saschl — APPROVED** [review]
LGTM

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by brunocfalcao** [comment]
Hope it gets merged soon 🙏

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 17.3.2021
Version of the sim: 1.14.5.0
PR Tested: #4003
Tier of testing: 1
Changes to observe: Clear waypoints in TMPY FP
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Did a simple flight plan with FS planer and spawned on runway at EDDP
2.) Cleared single waypoint and inserted new TMPY flight plan
3.) Cleared multible waypoints in TMPY flight plan and inserted new TMPY flight plan

Issues: -

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Comment by brunocfalcao** [comment]
@marcman86 Hi, did you also tested removing waypoints from the inserted SID or STAR ?

I noticed this might be different from the normal route waypoints lets say.

And can you also check if the GPS waypoints like "5244N" gets deleted ?

So, the three scenarios would be:

1. Delete a non-SID, non-STAR waypoint
2. Delete a waypoint that is part of the SID, or part of the Approach
3. Same for the STAR
4. Delete a custom waypoint, or a GPS waypoint.

Hope it helps.

**Comment by pareil6** [comment]
> @marcman86 Hi, did you also tested removing waypoints from the inserted SID or STAR ?
> 
> I noticed this might be different from the normal route waypoints lets say.
> 
> And can you also check if the GPS waypoints like "5244N" gets deleted ?
> 
> So, the scenarios I can think of are:
> 
> 1. Delete a non-SID, non-STAR waypoint
> 2. Delete a waypoint that is part of the SID, or part of the Approach
> 3. Same for the STAR
> 4. Delete a custom waypoint, or a GPS waypoint.
> 
> Hope it helps.

From the testing instructions:
>Note that this does not fix any other waypoint deletion issues that were there before SU3 - it simply fixes a regression from SU3 changes being imported.

This does not fix deleting waypoints in SIDs/STARs, that's a separate issue that will be solved by the rewritten flight plan manager. This is *specifically* solving a regression vs. before SU3, which is causing waypoint deletion not to show up *in the temporary flight plan* and nothing else.

**Comment by brunocfalcao** [comment]
Sorry I didn't know about that pre-SU3 issues. Thanks for the clarification.

**Comment by beheh** [comment]
Heads up: This change will be lost with the flight plan rewrite, as waypoint deletions on TMPY do not create a new TMPY flight plan, and existing TMPY flight plans will no longer be modifiable as per Honeywell logic.

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 17.3.2021
Version of the sim: 1.14.5.0
PR Tested: #4003
Tier of testing: 1
Changes to observe: Clear waypoints FPLN updating in TMPY FPL

### Testing technique: Tryout

### Steps made to test the Pull Request:

1. Spawned C/D, powered up the aircraft
2. Added random route on INIT page
3. Selected SID, added flightroute using airways and waypoints, selected STAR]
4. Hit CLR on MCDU, selected a random waypoint on the FPLN, checked if it deleted from TMPY FPLN
5. Repeated same steps for multiple waypoints.

### Issues (If Any): None

### Overall Rating: Good

### Conclusions of the testing: 
PR works as expected. Waypoints are also updated on the TMPY flight plan.

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 17/03/2021
Version of the sim: 1.14.5.0
PR Tested: #4003 
Tier of testing: 1

Changes to observe:
A flight plan version increment call got lost when Asobo's FPM changes from SU3 were imported, causing deleting a waypoint to not be reflected in the TMPY flight plan.

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. Spawned C&D at LSZH
2. Uplink simBrief F-PLN
3. Followed instructions as PR
4. USR waypoint added when inserting RWY + STAR
5. USR can be CLR + CLR some other waypoint STAR + some ROUTE WPT


Flight notes (When done a full flight):
N/A
Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A

Issues (If Any): Write any issues
USR waypoint 
Steps to achieve the issue:
as above

Overall Rating: Good
Conclusions of the testing: PR works as described, GTG

**Comment by MisterChocker** [comment]
Oh I see, nvm then.

**Pull request merged**
