### PR TITLE
feat(RMP): add illumination to the RMP volume knobs

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes
This adds integral illumination to the RMP knobs as seen on never RMP panels.

- added illumination for the RMP volume knobs controlled by integral light knob with the rest of pedestal integral lighting
- reduced the brightness of the RMP volume knobs when selected or with the annunciator test light on by a small amount

Thanks to @Benjozork and @NathanInnes for helping out!
## Screenshots (if necessary)

Untitled-2

## References

image

image

## Additional context
Brightness comparison :

end

Discord username (if different from GitHub): Imenes#8739

## Testing instructions

Make sure RMP volume knobs illuminate on both sides with the pedestal integral light knob and that they illuminate more brightly when the annul test light is on or they are pulled out.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by NathanInnes — APPROVED** [review]
LGTM! Ready to test

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 26.3.2021
Version of the sim: 1.14.5.0
PR Tested: #4118
Tier of testing: 1
Changes to observe: RMP illumination
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power
3.) Tested RMP panel at day and night
4.) Tested ANN LT (Image1)

Media:


Image1

Issues (not related to this PR): 

- shafts are not illuminated
- ANN LT don't adresses all RMP knobs (Image1)

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Comment by Matse08** [comment]
Category: QA Tester
Name: Matse#7454
Date of testing: 26.03.21
Version of the sim: 14.0.5.0
PR Tested: #4118
Tier of testing: 1
Changes to observe:
RMP Lights

Testing technique: try-out
Steps you've made to test the Pull Request:
1. spawned C&D
2. turned battery on
3. Turned panel lights on





Media: 
Microsoft Flight Simulator Screenshot 2021 03 26 - 15 47 58 10


Issues (If Any):Not working with ANN LT



Overall Rating:To be improved
Conclusions of the testing: Good enough

**Comment by ImenesFBW** [comment]
> Issues (If Any):Not working with ANN LT
> 
> Overall Rating:To be improved
> Conclusions of the testing: Good enough


What do you mean exactly by not working with ANN LT? The volume knobs should fully illuminate when the annunciators' test light is on.

**Comment by Matse08** [comment]
> > Issues (If Any):Not working with ANN LT
> > Overall Rating:To be improved
> > Conclusions of the testing: Good enough
> 
> What do you mean exactly by not working with ANN LT? The volume knobs should fully illuminate when the annunciators' test light is on.

I mean that The buttons dont illuminate when turning ANN LT on test

**Comment by NathanInnes** [comment]
> I mean that The buttons dont illuminate when turning ANN LT on test
Are you referring to the CALL buttons or the knobs? 
image
To be clear this image is the scope of this PR

**Comment by Matse08** [comment]
> > I mean that The buttons dont illuminate when turning ANN LT on test
> 
> Are you referring to the CALL buttons or the knobs?
> image
> To be clear this image is the scope of this PR

Sorry for not being clear i mean the call buttons

**Pull request merged**
