### PR TITLE
fix(mcdu): empty sids when scrolling on departures page

### LINKED ISSUE #3543: [BUG] Empty SIDs displayed on departures page when scrolling down
**Mod Version**

master

**Describe the bug**

Empty SIDs displayed on departures page when scrolling them down. Looks like many empty SIDs added to the actual list.

**To Reproduce**

1. Set UUDD as departure airport on INIT-A page
2. Go to F-PLN, select first line: UUDD -> DEPARTURE
3. Select 14L runway
4. Scroll down SIDs

**Expected behavior**

The scrolling stops at the "TOKN1M" SID. "Up" arrow at the bottom right disappears.

**Actual behavior**

The SIDs can be scrolled down to ~40 more empty lines.

**References**

**Additional context**

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub): SergeyS#7450

### PR DESCRIPTION
**Pull request by SergeySoprykin**
Fixes #3543

## Summary of Changes

Fixed SIDs out of range scrolling. Incorrect 'max pages' number was used to set bottom scrolling limit.

## Additional context

Discord username (if different from GitHub): SergeyS#7450

## Testing instructions

Actions:
1. Select KJFK as the departure airport on the INIT-A page
2. Go to F-PLN page, select 04L departure runway
3. Press Up button to scroll down to MERIT6

Result:
The scrolling ends at MERIT6 and "Up" arrow disappears at the bottom left of the screen.
SIDs listed: BETTE6, DEEZ5, GREKI6, HAPIE6, JFK5, MERIT6. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3557
Tier of testing: 1
Changes to observe: More SIDs on departure page
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at KJFK
2.) Started bat. and ext. power
3.) Init-A to KJFK/KLGA
4.) For departure selected 04L and scrolled down to MERIT6 (Image1)

Media:


Image1

Issues: None

Overall Rating: Good

Conclusions of the testing: Works!

Hope this helps :-)

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 
Version of the sim: 1.13.16.0
PR Tested: #3557
Tier of testing: 1
Changes to observe: SID scrolling


Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned C&D at KJFK
2. Started up the Aircraft
3. put KJFK/LSZH into INIT
4. Checked Departure Page from 04L

Media:
https://user-images.githubusercontent.com/70195216/108263424-8bbdb280-7166-11eb-9bd2-751c8d2a4f66.mp4

Issues (If Any): none

Overall Rating: Good
Conclusions of the testing: Scrolling works as one would expect. Looks good to me

**Comment by kberg93** [comment]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/19/2021
Version of the sim: 1.13.16.0
PR Tested: #3557 
Tier of testing: 1
Changes to observe:
Fixed SIDs out of range scrolling. Incorrect 'max pages' number was used to set bottom scrolling limit.

Testing technique: Tryout

Steps you've made to test the Pull Request: 
1. Spawn at KJFK.
2. Put in the data in MCDU and go to departure and scroll down to MERIT6. (see screenshots)

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
FlightSimulator_EPPWeTBxaT
FlightSimulator_Lg7z0tVGok
FlightSimulator_GeTiLI6QzB

Issues (If Any): None.

Overall Rating: Good.

Conclusions of the testing: Arrow shows as described, LGTM.

**Comment by davidwalschots** [comment]
Was putting this under `0.5.0` in the changelog intentional?

**Pull request merged**
