### PR TITLE
Added APU Bleed/pack sounds and improved engine rumbles

### LINKED ISSUE #1056: [REQUEST] PACKS (APU Bleed sound) disabled during Engine Mode to IGN/START
**Is your feature request related to a problem? Please describe.**
Because the APU bleed functionality has been implemented in this mod, we now have the sound of the 'PACKS' when the bleed is switched on. On the real aircraft, during engine start the air is completely diverted from the PACKS to the engine for start, so the PACK valves are closed. When the Engine Mode selected is switched to "IGN/START" the implemented APU bleed sound (which is really the sound the PACKS would be making) should stop.

**Describe the feature you'd like to see implemented**
As per the functionality of the real aircraft, the following logic (or as close to it) could be implemented:
- When the Engine Mode selector is set to IGN, when on ground, the PACKS (APU bleed noise) switch off.
- When the Engine Mode selector is set back to NORM after start, the PACKS (APU bleed noise) are switched back on.

**References**
Have confirmed my reference from the A330 FCOM 1 is correct with the A320 NEO as per "komp" in Discord. Full reference from the FCOM is:
The pack flow control valve is open when the PACK pb is selected ON (not currently simulated) except in the following cases:
<ommitted for brevity>
— Engine start sequence:
1. One valve (or both, if the crossbleed valve is open) closes when :
• The MODE selector is set to IGN, when on ground (valves reopen if
MASTER switch or MAN START pushbutton are not set to ON within
30 seconds) ;
• The MODE selector is set to IGN (or CRANK) and when, on either
engine :
— The MASTER switch is set to ON (or MAN START pushbutton is
set to ON), and
— The start valve is open, and
— N3 < 50 %.
2. On ground, reopening of the valves is delayed 1 minute to avoid an extra
pack closure cycle during subsequent engine start.
<ommited for brevity>

**Additional context**

Discord username (if different from GitHub): PhilKenSebben

### PR DESCRIPTION
**Pull request by hotshotp**
Fixes #1056

## Summary of Changes

I have changed the default a320 pack/apu bleed sounds and added a small bit of logic.

The logic is using a simple xmlvar that looks at the engine mode selector - if the mode sel is not in normal position, the packs will turn off.

As for the sounds themselves, I have added airflow sound to cockpit and cabin, and the actual pack whine is also heard in the cabin. The pack valve sound is also heard on the outside very loudly like the real aircraft.

I also changed the engine rumble to be a little louder and more bassy at higher n1 percentages.

I also added new taxi sounds for the ground roll

## References

Used real recordings from komp and used simple logic by asking pilot feedback about the engine mode selector relation to packs.

## Additional context

Let me know if there are any pops, I pretty much eliminated them all, but if some come up let me know.

Discord username (if different from GitHub):

Boris#9134

## Testing instructions

Start up apu, press apu bleed, listen in cockpit and cabin and outside the plane. Then try to take off and listen to the rumbles on take off power.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: ChristopherXie#3904
Date of testing: Current date 01/12/2021
Version of the sim: V1.12.13.0
PR Tested: #3010 
Object of test: (ECAM Page or Flight model or views or anything, what the PR modifies)

Testing technique: Entered the sim and spawned on a runway
Steps you've made to test the Pull Request:
1. Spawned on a runway at CYYZ
2. Turned on the APU and APU bleed
3. Moved the mode selector switch to IGN START and CRANK and checked the exterior sounds and moved the switch back to NORM
4. Moved the mode selector switch to IGN START and CRANK checked the cockpit sounds and moved the switch back to NORM
5. Moved the mode selector switch to IGN START and CRANK checked the cabin sounds and moved the switch back to NORM
6. Did a takeoff roll and listened to louder rumble, not much difference than before
Flight notes (If required):

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: I like the new pack sounds and the xmlvar seems to be doing its job well. One thing I think you missed in the desc was the new taxi sounds. For them they sound ok, but the old ones sounded more pleasant and dynamic compared to this one.

**Comment by NickFarin** [comment]
Category: QA Trial
Name: Discord User: Nick F[Z+8] #5327
Date of testing: Current date 1/13/2021
Version of the sim: 1.12.13.0
PR Tested: #3010 
Object of test: APU Bleed/pack sounds and improved engine rumbles
Testing technique: Spawned at VHHH and listened to sounds
Steps you've made to test the Pull Request:
1. Spawned at VHHH at cold and dark
2. Started APU and listened to sounds in the cockpit, cabin, and outside
3. Turned on APU bleed and listened to the sounds
4. Pushed from gate and started engines
5. Took off from runway and listened to the engine sounds in the cockpit, cabin, and outside

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: The test went normal and I like the new sounds.

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 12.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3010
Object of test: New APU Bleed Sound, new Engine Rumbling

Testing technique: try out
Steps you've made to test the Pull Request:
1. Spawned cold and dark LSZH A44
2. Started up the AC
3. Tested through every scenario with APU Bleed and ignition Switch
4. Took off RWY28


Flight notes (If required): 
Take off: Rumbling sounds very nice

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: No issues found so far, working as described

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: 13/1/2021
Version of the sim: 1.12.13.0
PR Tested: #3010 
Object of test: APU Bleed/pack sounds and improved engine rumble.
Testing technique: loaded c&d and tested the mentioned changes. 
Steps you've made to test the Pull Request:

1. Started apu and apu bleed 
2. Switched from normal engine mode to ignition
3. Checked the cabin flow sound from cockpit view and external view
4. Took off and repeated the sound check.

Issues (If Any): N/A 
Overall Rating: Good 
Conclusions of the testing: Everything sounds good and great addition especially the pack logic.

**Pull request merged**
