### PR TITLE
feat: Refined gear/flap drag increments

### PR DESCRIPTION
**Pull request by donstim**
Fixes #[issue_no]

## Summary of Changes

1. Gear drag increment has been increased (a small amount) and flap drag increment has been reduced, and
2. Comments have been added to note the spoiler lift/drag increments for different spoiler configurations (to be implemented later via external coding by @aguther 
## References

Flap/gear drag levels continue to be based on matching the N1 values from the QRH unreliable airspeed chart. The flap drag increment was reduced slightly to refine the difference between CONF 2 and CONF 3 drag levels. The gear drag then needed to be increased to maintain the QRH N1 values for CONF 3 and CONF FULL (gear down). All other flap drag levels were then adjusted such that the N1 levels continued to match the QRH unreliable airspeed chart.

## Additional context

The net result of this PR is that the N1 values (indicating the drag level) of all configurations covered by the QRH unreliable airspeed chart (Flaps up, CONF 1 (gear up), CONF 1+f (gear up), CONF 2 (gear up), CONF 3 (gear down), and CONF FULL (gear down) **did not change**. For Flaps up through CONF 2 with gear down, drag will be slightly higher. For CONF 3 and FULL with gear up, drag will be slightly lower.

All in all, not a significant PR, but a refinement I wanted to make to the gear drag before we implement the spoiler drag changes.

Discord username (if different from GitHub): donbikes#4084

## Testing instructions
Full flight to confirm that nothing flight model-wise was "broken" by this PR. Exercise flaps and landing gear.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #
Tier of Testing: 2
Date: 8.6.2021

Testing Process: (Detail is needed)
3 full pattern at ESGG with GoAround in between

Negatives: None
Testing Results: Passed
Conclusions: 
I'm didn't notice a difference but everything works as intended.

**Comment by TheSquirtingPantin** [comment]
Quality Assurance Tester

Discord: Remi#8871
Object of testing: #5027
Tier of Testing: 2
Date: 8/06/2021

Testing Process:
1) Full flight KIAD-KMIA
2) Routing JDUBB4 RRSIN DCT GSO Q75 SLOJO/N0451F390 Q83 EFFAY/N0452F380 Q83 JEVED Q97 KENLL DCT OMN HILEY7

Negatives: None.
Testing Results: Passed. 

Conclusions: LGTM. Overall airplane behavior is as expected. 
Media: N/A

**Comment by DavidEGTE** [comment]
Quality Assurance Trainee Report

Discord: David#2177
Object of testing: #5027 
Tier of Testing: 1
Date: 08/06/2021

Testing Process: Full Flight LEBB to LIEO
Negatives: N/A
Testing Results: Passed

Conclusions: LGTM, model/feat worked as expected had no issue from gate to gate

**Comment by easyjetsimpilot** [comment]
Quality Assurance Tester

Discord: easyjetsimpilot
Object of testing: #5027
Tier of Testing: 2
Date: 09/06/21

Testing Process: Full flight using real-ops protocols from Brasilia to Rio De Janero. Flaps 1 TOGA T/O and full flap landing. 
Negatives: N/A
Testing Results: Passed

Conclusions: No abnormal effects noted. All flew exactly as expected. 
Media: Full flight streamed at https://www.youtube.com/watch?v=d05BkGWFRlo

**Comment by sidnov** [comment]
QA Report

Object of testing: #5027 
Tier of Testing: 2
Date: 14/06/2021

Testing Process:
2 full flights, IFR with a quick turnaround
Route: VEBD-VEGT-VEIM
Weather: Default Live (Overall rainy/overcast enroute)
Did not observe any abnormal flightmodel behavior such as excess drag on flap deployment or landing gear extension. Flap transitions were smooth. Hand flew the approach and the aircraft behavior was firm and as expected 


Negatives: None
Testing Results: Passed

Conclusions: No negative effects observed on the flightmodel, either due to gear or flap extension. Normal behavior with turbulence as well. LGTM 👍🏻

**Pull request merged**
