### PR TITLE
feat(sound): replace default sound events

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

Replaced the following default sounds with custom sound effects from @hotshotp :

- [x]  FCU: ADF/VOR switches and Chrono push button
- [x] RMP + ACP(CALL) : buttons and switches
- [x] TCAS Panel: knobs and buttons
- [x] DCDU: brightness switch
- [x] Overhead panel: calls round pushbuttons, fire test buttons, rain repellent,  CVR erase and test,  cargo smoke covered and test
- [x] MISC: rudder trim reset button

## Additional context

No changelog since it can be later added to the initial cockpit sound event changes. 

Discord username: Imenes#0001

## Testing instructions
Check that all the listed custom sounds are audible and that they all still function as they did. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by hotshotp — APPROVED** [review]
I have checked with imenes via videos and such to make sure all buttons sound right, all LGTM!

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5323
Tier of Testing: 1
Date: 16.7.2021

Testing Process:

Check sounds:
- [x]  FCU: ADF/VOR switches and Chrono push button (even in stereo :) )
- [x]  RMP + ACP(CALL) : buttons and switches
- [x]  TCAS Panel: knobs and buttons
- [x]  DCDU: brightness switch
- [x]  Overhead panel: 
  - [x]  calls round pushbuttons (mech also sounds a tone)
  - [x]  fire test buttons
  - [x]  rain repellent
  - [x]  CVR erase and test
  - [x]  cargo smoke covered and test (right cover sound like button/switch) - left is ok
 
Negatives: Please double check DISCH cover right if correct - otherwise all sounds are there and good 

Testing Results: Passed (if DISCH cover is intended like this)

**Comment by ImenesFBW** [comment]
> Testing Results: Passed (if DISCH cover is intended like this)

Good find, we only had a template for one of the covers. I'll add the missing one and remove the sound, since @hotshotp mentioned they are essentially silent in the real plane.

**Comment by ImenesFBW** [comment]
Removed the cover sounds for those so they should both be silent. I'll remove the rest of the covers that have sound in the next PR in which I will attempt to remove any leftover default cockpit sounds.

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #5323 
Tier of Testing: 1
Date: 17/7/21

Testing Process: 
Loaded in and tested all buttons
Negatives: N/A (Rudder trim reset button discussed)
Testing Results: Passed

Conclusions: LGTM

**Comment by ImenesFBW** [comment]
Added rudder trim as noted by @FlightSimmer7700 and added RSTon/off for chrono RST since Boris now added it to pck, so it should be audible.

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #5323 
Tier of Testing: 1
Date: 17/7/21

Testing Process: 
Loaded in and tested rudder trim reset and chrono buttons + rechecked over older changes
Negatives: N/A
Testing Results: Passed

Conclusions: All good in my tests

**Comment by ImenesFBW** [comment]
Good to merge from my end! Thanks, everyone for testing!

**Pull request merged**
