### PR TITLE
fix: update UI_MANUFACTURER and UI_MODEL in locPak files

### PR DESCRIPTION
**Pull request by ExampleWasTaken**
## Summary of Changes

Updated `AIRCRAFT.UI_MANUFACTURER` and `AIRCRAFT.UI_MODEL` to "`FlyByWire Simulations`" and "`A320 (LEAP)`".

## Screenshots (if necessary)

**Image 1:**
hangar_title

**Image 2:**
aircraft_selector

**Image 3:**
facts_window_title

## Additional context

My first PR :)

Discord username (if different from GitHub): `ExampleWasTaken#0886`

## Testing instructions

1. Check that the title in the hangar matches the marking on image 1.
2. Check that the aircraft selector matches the marking on image 2.
3. Check that the title of the the window marked on image 3 matches the marking.
4. Check that the aircraft loads in sim.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
LGTM. This should help with converting liveries!

**Comment by ExampleWasTaken** [comment]
does it need a changelog entry?

**Comment by tracernz** [comment]
> does it need a changelog entry?

I don’t think so. We haven’t released a version without this (came from Asobo files in previous releases).

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 06/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4303 
Tier of testing: 1
Changes to observe: FBW labels

**Steps you've made to test the Pull Request:**

1. Check that the title in the hangar matches the marking on image 1.
2. Check that the aircraft selector matches the marking on image 2.
3. Check that the title of the the window marked on image 3 matches the marking.
4. Check that the aircraft loads in sim.
5. 
**Media:**

**Issues (If Any):** - 

**Conclusions of the testing:** LGTM

**Pull request merged**
