### PR TITLE
feat: 3d brake gauge

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Added 3D brake gauge
    * Functionality is the same. It still only responds to the parking brake
* Removed 2D brake gauge screen

## Screenshots (if necessary)

Before:
image
After:
image
image

## References

image
image

## Additional context

Model created by @DarkOfNova 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Giuse101 — APPROVED** [review]
LGTM

**Review by DarkOfNova — APPROVED** [review]
LGTM

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 11.4.2021
Version of the sim: 1.14.6.0
PR Tested: #4393 
Tier of testing: 2
Changes to observe: new 3D Brake Gauge

Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned at LSZR
2. Checked Gauge in different states and Times
3. Checked for no Model Glitches around the Aircraft 

Media:
View in the Hangar
Microsoft Flight Simulator Screenshot 2021 04 11 - 17 42 36 99
C&D at night
Microsoft Flight Simulator Screenshot 2021 04 11 - 17 46 41 42
Functionality at daytime
https://user-images.githubusercontent.com/70195216/114311238-2e9f0700-9aee-11eb-8c01-4b679fc994cb.mp4
Emmisives at night
https://user-images.githubusercontent.com/70195216/114311242-38c10580-9aee-11eb-911c-e656c131ef3c.mp4

Issues (If Any): None

Overall Rating: Amazing
Conclusions of the testing: Small Detail that adds so much to the general ambient feeling of the aircraft. Found no issues and it looks awesome

**Comment by JD202107** [comment]
Category: QA Tester
Name: animalcupid1073#0971
Date of testing: 11.4.2021
Version of the sim: 1.14.6.0
PR Tested: #4393
Tier of testing: 2
Changes to observe: new 3D Brake Gauge

Testing technique: Tryout
Steps you've made to test the Pull Request:

Spawned cold & dark at EGCC
Checked Gauge in Day and Night
applied and released parking brake a few times to ensure the gauge was working correctly 

Test conclusion: No issues found all seems to be working well.

Screenshot (51)
Screenshot (50)

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 11/4/21
Version of the sim: 1.14.6.0
PR Tested: #4393 
Tier of testing: 1
Changes to observe:
Brake Gauge

Testing technique: Loaded in and looked
Steps you've made to test the Pull Request:
1. Loaded in
2. looked at 3d gauge 
3. powered up
4. loaded in dev
5. looked at 2d version

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: LGTM

**Comment by beheh** [comment]
The text does not match the references, it has an extra whitespace (`PSIx1000` vs. `PSI x1000`). The distance will probably need to be hand-adjusted.

**Comment by crocket63** [comment]
Anyone could test this on triple screens + track IR?  I have a bug where needles totally disapear depending on viewing angle.

Bug disapears if I go windowed and reduce window on center screen.

**Pull request merged**
