### PR TITLE
fix(nd): quick fix for PPOS/Wpt when ADIRS not aligned

### PR DESCRIPTION
**Pull request by sidnov**
## Summary of Changes

A very short and quick fix for a bug I inadvertently introduced in #3870 where waypoint and it's details appeared instantly after setting it on the MCDU, even before ADIRS aligned. Added a separate condition to fix this.

## Screenshots (if necessary)

image
image

## Additional context

Discord username (if different from GitHub): sidnov#8337

## Testing instructions

1. Spawn C/D, power up the aircraft, align ADIRS, observe ND loads completely with waypoint set to PPOS and no other visible details.

2. Restart, spawn C/D, power up the aircraft, set departure/arrival airports on the MCDU. It should not instantly update waypoint name, time/distance on the ND (top-right corner). Should stay on "PPOS". Now, align ADIRS and wait, check the waypoint details appear only after alignment is complete.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by MisterChocker — APPROVED** [review]
LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 17.3.2021
Version of the sim: 1.14.5.0
PR Tested: #4012
Tier of testing: 1
Changes to observe: No waypoint info without ADIRS aligned
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Simple FS F-PLN and spawned C&D at EDDP
2.) Turned on bat. and ext. power (Image1)
3.) Aligned ADIRS (Image2)
4.) Spawned C&D at EDDP
5.) Turned on bat. and ext. power
6.) Setup a simple F-PLN before ADIRS align (Image3)
7.) Aligned ADIRS (Image4)


Media:


Image1


Image2


Image3


Image4

Issues: -

Overall Rating: Good

Conclusions of the testing: Works

Hope this helps :-)

**Comment by marinerhally** [comment]
Category: QA Tester
Name: Mariner Hally#0715
Date of testing: 17/03/2021
Version of the sim: 1.14.5.0
PR Tested: #4012
Tier of testing: 1
Changes to observe:
A very short and quick fix for a bug I inadvertently introduced in #3870 where waypoint and it's details appeared instantly after setting it on the MCDU, even before ADIRS aligned.

Testing technique: Try out
Steps you've made to test the Pull Request:
1. Spawned C/D EGCC
2. Aligned ADIRS and observed PPOS on ND
3. Re-spawned back in at EGCC
4. Aligned ADIRS and inputted EGCC/EGKK on INIT page.
5. Observed ND, PPOS showed until aligned then showed next waypoint.

Flight notes (When done a full flight): None

Media:
Screenshot 2021-03-17 181008

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Works well also tried inputting info first then aligning. No problems

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 17/03/2021
Version of the sim: 1.14.5.0
PR Tested: #4012 
Tier of testing: 1

Changes to observe:
quick fix for PPOS/WPT when ADIRS not aligned

Testing technique: Try-out

Steps you've made to test the Pull Request:
Test 1
1.) FS Plan & spawned C&D at gate LMPA
2.) Turned ext. power + batteries
3.) Aligned ADIRS

Test2
1.) Spawned C&D at gate LMPA
2.) Turned ext. power + batteries
3.) Setup a simple F-PLN before ADIRS align
4.) Aligned ADIRS

Flight notes (When done a full flight):
N/A
Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A
Issues (If Any): Write any issues
N/A
Steps to achieve the issue:
N/A

Overall Rating: Good, both tests works as described.
Conclusions of the testing: GTG

**Pull request merged**
