### PR TITLE
[ECAM] Improve inhibit and recall behaviour

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

This PR is a followup to #1943, incorporates some feedback from there and improves the ECAM inhibit and recall behavior to be more accurate. Where previously there was no distinction between inactive messages and inhibited message, this PR splits those two out so that the inhibit behavior can be implemented more accurately. This allows the flight phase inhibition to be correctly overridden using the recall button, and also ensures warnings stay visible during a flight phase change if they were visible previously.

The PR also provides some minor fixes to some ECAM messages themselves, by fixing colors and improving when and how some of the messages appear. See the full changelog below:

### User-facing Changes

- Active warnings persist through flight phase changes, even if they would be inhibited  
*For example, A/SKID N/WS OFF is inhibited above 80 knots until at 1500ft RA. If the A/SKID N/WS switch is turned off during this window, the associated warning won't appear until 1500ft RA. However, if A/SKID N/WS OFF appears before 80 knots it remains continuously visible.*
- The Recall button lifts flight phase inhibition for the current flight phase  
*For example, BRAKES HOT is inhibited between touchdown and last engine shutdown + 5 minutes. If the pilot presses the RCL button during this window, BRAKES HOT will appear immediately (as the pilot has lifted the flight phase inhibition), even if BRAKES HOT was not visible and cleared previously.*
- STROBE LT OFF has been added (in the air)
- IR IN ALIGN X MIN turns amber when at least one engine is running
- PRED W/S OFF now already turns amber when the T.O CONFIG is pressed before takeoff
- SPEED BRK turns amber after engines are started and before takeoff  
*Flashing and amber in the air during non-idle will come in a future PR*
- BRAKES HOT now calls up the WHEEL page
- CARGO SMOKE is inhibited during takeoff and landing while above 80 knots
- Make T.O CONFIG use more accurate flight phase logic
- IR(S) ALIGNED has been removed again  
*While this memo is described in the documentation, no pilot could recall having seen it. Upon further investigation the documentation contains logic that will never make this message appear (possibly only as a brief flash upon aligning completing). It may also just be a remnant of an old version.*
- IGNITION memo has been removed again  
*This memo is pretty complicated as it needs to appear only during continuous ignition and not during normal start. So we'll wait with this until we have a proper FADEC implementation.*
- TCAS FAULT is now hidden during flight phases 1 and 10 (as per FWC F8)  
*I know there's a lot of reference footage for Cold and Dark having TCAS FAULT out there, but after some discussion in [#pilot-feedback](https://discord.com/channels/738864299392630914/754851312306487326/779343095581638656) this appears to be fixed in more modern aircraft (probably most Neos).*
- Fixed a bug that could cause warnings to become permanently disabled for the rest of the flight
- Fixed warnings not overriding T.O/LDG Memo
- Fixed some ECAM actions being white instead of cyan

### Developer-facing Changes
- Button logic for Recall, Takeoff Memo, Takeoff Inhibit, Landing Memo and Landing Inhibit has moved to the FWC
- Generalized inhibit behaviour in the ECAM (using flightPhasesInhib)

## References

image

## Additional context

Discord username (if different from GitHub): BehEh#1234

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MisterChocker** [comment]
don't forget to add changelog

**Comment by beheh** [comment]
Thanks, I've just stopped doing them ahead of time before the PR is ready to minimize the constant merge conflicts.

**Comment by beheh** [comment]
Okay, so this PR has grown a little again, but it's ready now. I found and fixed one pesky bug that could cause some messages to become disabled for the rest of the flight that was already present before my previous PR, so I'm very happy about that because it caused my testing to behave very strangely sometimes until I fixed it.

Other than that, the ECAM is more accurate and reliable as ever.

**Comment by Snapmatics** [comment]
> Okay, so this PR has grown a little again, but it's ready now. I found and fixed one pesky bug that could cause some messages to become disabled for the rest of the flight that was already present before my previous PR, so I'm very happy about that because it caused my testing to behave very strangely sometimes until I fixed it.
> 
> Other than that, the ECAM is more accurate and reliable as ever.

Ready to be tested?

**Comment by beheh** [comment]
It was, but I literally just remembered one more thing, I promised Boris to add a SimVar for a new FWC self-test sound while I'm touching the FWC. I'll make as ready again once it's ready.

**Comment by Snapmatics** [comment]
> It was, but I literally just remembered one more thing, I promised Boris to add a SimVar for a new FWC self-test sound while I'm touching the FWC. I'll make as ready again once it's ready.

No worries, take your time, real-life first 💯

**Comment by beheh** [comment]
@Snapmatics The last changes are in. From my side this can be reviewed and tagged for testing.

**Review by wpine215 — APPROVED** [review]

**Comment by danbw9** [comment]
Category: QA Test
Name: danbw9#7028
Date of testing: 23/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2029
Object of test: Check out new/changed indications with inhibit and recall behaviour

Testing technique: Few quick flight tests, spawning on RWY + full flight checking item by item in PR for check. Very observant of ECAM memos and messages as the flight progresses through each FWC phase. 

Steps you've made to test the Pull Request:

Spawn on RWY at EKCH. Set up as normal for departure off RWY22L. Turn off A/SKID N/WS . Apply take off thrust. Going past 80 knots checking that ECAM caution remains. 

Restart flight on RWY and turn off A/SKID N/WS after 80 knots and no caution appears. After THR RED ALT is reached and THR CLB set, check that the caution then appears - all fine. 

Did a quick landing and taxi to gate after spawning on approach. I tried the example mentioned above with Recall button and BRAKES HOT ECAM message after a touchdown with hard braking. Works as described. in connection with this point checked that the 

During the take off and landing phases, I could still hear the CRC and get an ECAM message when CARGO SMOKE warning was tested though is there a way to test the failure item itself? This was 

**Full Flight from EKCH to EGLL**

On engine start with pushback, turned off all ADIRS and once ENG 2 was AVAIL, the amber IR IN ALIGN member popped up as expected.

Also after ENG 2 was AVAIL, the NAV TCAS FAULT ECAM caution appeared as expected as it is now possible in FWC phase 2, no longer in phase 1.

Before taxi, deployed speedbrake whilst both ENGs were running and ECAM caution popped up correctly. 

Strobe light off memo correctly appears in the air above 1500 RA after THR CLB set - could not find FCOM reference for this but it would make sense. 

A bug which would happen before is that the anti skid N/WS to off for example would not trigger an ECAM for example mid flight. In CLB, CRZ and DES phases I tried this and it would correctly bring up ECAM caution. 

Noticed some logic fixes to for example the PARK BRK ON CONFIG warning disappearing after parking brake is released after Take off power is applied with PARK BRK on. 

The memos for IR ALIGNED and IGNITION were not seen as described above. 

Issues (If Any): Small couple bugs. PWS system MEMO did not turn amber after I did TO CONFIG test on taxi out. And also after I landed I got the TO MEMO. 
Overall Rating: Good
Conclusions of the testing: LGTM. Quite a lot to test, and I would test other other ECAM messages for another flight. There was a lot to test, but I cross checked with FCOM where appropriate. Confirmed the flight phase inhibitions for the specific items that are 'testable' as failures in the sim at the moment. This PR will definitely need quite a bit of testing by others too. Thanks for your great work @beheh keep it up!

**Comment by beheh** [comment]
> During the take off and landing phases, I could still hear the CRC and get an ECAM message when CARGO SMOKE warning was tested though is there a way to test the failure item itself?

My changelog was a bit sloppy, and I've updated it since - this is only inhibited during takeoff and landing above 80 knots. Yes, the CARGO FIRE TEST button is the only way to test this.

> In relation to the bug with TO MEMO appearing after landing, it may have to do with me moving my thrust levers out of idle detent and far into the normal TLA range before back to idle.

This can be explained if you were in MCT or above, as the FWC then moves into flight phase 3 followed by flight phase 2 on a subsequent idle, at which point the T.O MEMO is appropriate.

> PWS system MEMO did not turn amber after I did TO CONFIG test on taxi out

Yeah, I did not touch this as part of this PR - it's a little hard to do, but I'll get it add it here.

**Comment by Benjozork** [comment]
> Yeah, I did not touch this as part of this PR - it's a little hard to do, but I'll get it added here.

As part of this PR ?

**Comment by beheh** [comment]
Yep, added now.

**Pull request merged**
