### PR TITLE
Quick hotfix for avionics fan loop playing in ext view

### PR DESCRIPTION
**Pull request by hotshotp**
VERY QUICK PR:

some people have been complaining about the continuous avionics ventilation loop being played on the external view of planes. I have added a very quick one line of code (ViewPoint="Inside") to mitigate this. I made a PR for this so soon because this felt like a pretty big issue.

### CODE REVIEW

**Comment by Benjozork** [comment]
I'm confused. This adds 40 files, did you commit something you shouldn't have ?

**Comment by hotshotp** [comment]
> I'm confused. This adds 40 files, did you commit something you shouldn't have ?

this changes two files, here i will message you on discord

**Comment by lukecologne** [comment]
There is something wrong with this PR, according to github the only filechanges are whitspace changes and a change in the changelog. Did you re-use your old branch from the last PR? If yes, you should create a new one based on current master, and do your changes in that one

**Comment by hotshotp** [comment]
Made a mistake with github, sorry

**Pull request closed without merging**
