### PR TITLE
feat: new flaps and reversers sounds

### PR DESCRIPTION
**Pull request by hotshotp**
Fixes #[issue_no]

## Summary of Changes

I improved the flap sound and the interior thrust reverser sound in this PR.

## References

https://www.youtube.com/watch?v=6_xuxGli4GA&t=80s - flaps

For reverse thrust, there really is no reference on youtube for full reverse. However iceman told me that the reversers even on LEAPs are very loud. I confirmed with a few pilots that they sound right.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Start engine, put flaps down and go to wingview and listen.
With engines started, try using idle reverse and full reverse and hear the volume difference on the interior.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by davidwalschots — APPROVED** [review]

**Comment by oim1** [comment]
Category: QA Trial
Name: oim,#0001
Date of testing: Current date 04/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4259
Tier of testing: 1
Changes to observe:
New flaps sound and difference in volume between reverse thrust idle and max reverse thrust. 

Testing technique: 
1. Started engines. listened to flaps go down at each individual setting (1, 2, 3 and full) as well as retracted to full in wing view. Also listened to retracting sound. 
2. Listened to reverse thrust idle in wing view. 
3. Listened to max reverse thrust in wing view. 
4. listened to idle reverse thrust and max reverse thrust in cockpit 


Overall Rating: Good
Conclusions of the testing: The difference between idle reverse and max reverse is noticeable. It is also louder compared to previous versions. The flaps sounds are also good and are very similar to the reference.

**Comment by sidnov** [comment]
Category: Contributor/QA Tester
Name: sidnov#8337
Date of testing: 04/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4259 
Tier of testing: 2

### Changes to observe: New flaps and reverser sounds

### Steps you've made to test the Pull Request:

1. Spawned on runway
2. Went to left and right wingviews, cycled between each switch
3. Observed flap sounds, on each increment and decrement
4. Checked reverse thrust sounds, difference between idle reverse and max reverse.


### Issues (If Any): Changing flap settings quickly before the previous change completes causes the sound to restart from the beginning, and not continuing. Not sure if that can be completely fixed or is in the scope of this PR.

### Overall Rating: Good

Conclusions of the testing: Great improvement on the reverser sounds. Good to go!

**Comment by hotshotp** [comment]
> ### Issues (If Any): 
> Changing flap settings quickly before the previous change completes causes the sound to restart from the beginning, and not continuing. Not sure if that can be completely fixed or is in the scope of this PR.


I cannot change this as I use a derived simvar for flap movement and when it changes from 1 to 0 for flap movement it stops the sound. Not a big issue I think

**Comment by pilotJesse** [comment]
Category:Trial QA
Name:Jessee#8759
Date of testing: 04/04/2021
Version of the sim: Version the tester uses
PR Tested: 1.14.6.0
Tier of testing: 2
I improved the flap sound and the interior thrust reverser sound in this PR

Testing technique: Aircraft tested both after pushback and on takeoff roll.

Steps you've made to test the Pull Request:
1. Pushed back aircraft and checked flap extension and retraction sounds from flight deck & wing view
2. Spawned on runway, performed RTO with both idle and full reverse.
3. Stowed reverses and listened to change in sound.


Flight notes: N/A

Media: N/A 

Issues: Flap sound animation resets when quickily changing flap selection.


Overall Rating: Good
Conclusions of the testing: Reverser sounds great, clear difference and proportionate sound when in different areas of aircraft, i.e flight deck and cabin. Flap selection also sounds great.

**Comment by sidnov** [comment]
> > ### Issues (If Any):
> > Changing flap settings quickly before the previous change completes causes the sound to restart from the beginning, and not continuing. Not sure if that can be completely fixed or is in the scope of this PR.
> 
> I cannot change this as I use a derived simvar for flap movement and when it changes from 1 to 0 for flap movement it stops the sound. Not a big issue I think

Definitely not a big issue, and it happens only on unrealistic movements (who would actually move the flap lever 15 times in 5 seconds? XD). Nevertheless, loved the growl on the reversers now! 👍🏻

**Comment by BritishAvgeek** [comment]
Category: QA
Name: BritishAvgeek#1436
Date of testing: 04/04/2021
Version of the sim: Version the tester uses
PR Tested: 1.14.6.0
Tier of testing: 2
Testing Objectives: Check new REV Thr sounds and flap sounds 

Testing technique: full flight on Vatsim

Steps you've made to test the Pull Request:
1. Spawned C&D at ENVA for full flight to EGCC
2. Push and start, listen to sounds
3. Flew the full flight and during descent and approach selected flaps 
4. Landed and used reverse thrust on a CONF3 landing
5. Vacated and retracted flaps 

Flight notes: N/A

Media: streamed live on my channel Trondheim to Manchester 

Issues: None with normal operation .

Overall Rating: Good
Conclusions of the testing: personally I had no issues with this, sounds are improved and the reverse thrust sounds are fantastic - loud and deep as expected

**Comment by Samueleonard** [comment]
Category: QA Tester
Name: 1Samueleonard1#0001
Date of testing: Current date 04/04/2021
Version of the sim: 1.14.6.0
PR Tested: #4259
Tier of testing: 2

Changes to observe: new flap/reverse sounds

Testing technique: Tryout
1. loaded in on runway and switched to rear wing view showcase
2. extended flaps step by step - listened to noise
3. retracted flaps step by step - listened to noise
4. extended reversers - listened to spool/de-spool in wing view - moved to different angles, both interior and exterior
5. extended reversers - listened to spool/de-spool in cockpit - from different positions/camera angles in cockpit

Flight notes: very nice, compared to yt videos/real experiences, its realisitc

Media: n/a
 
Issues: n/a

Steps to achieve the issue n/a

Overall Rating: Good
Conclusions of the testing: sounds very nice

**Pull request merged**
