### PR TITLE
fix(nd): remove label from smallest circle in arc mode

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

* Removed label from the smallest circle of the ND in arc mode

## Screenshots (if necessary)

Before:
image
After:
image

## References

image

## Testing instructions

Ensure that the label has been removed from smallest circle of the ND.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by beheh — APPROVED** [review]

**Comment by ExampleWasTaken** [comment]
Category: QA Tester/Trial
Name: ExampleWasTaken#0886
Date of testing: 07/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3405
Tier of testing: 1
Changes to observe: Remove label from smallest circle in arc mode

Testing technique:
Steps you've made to test the Pull Request:
1. Loading in C&D
2. Checked that label is not showing while ADIRS is not aligned 
3. Checked that label is not showing while ADIRS is aligned
4. Checked that label is not showing while in-flight

Flight notes (When done a full flight): N/A

Media:
Microsoft Flight Simulator Screenshot 2021 02 07 - 22 32 20 40
Microsoft Flight Simulator Screenshot 2021 02 07 - 22 32 37 09



Issues (If Any): N/A

Overall Rating: Good
Conclusions of the testing: Everything is working as expected.

**Comment by theflyingexpert** [comment]
Category: QA Tester/Trial
Name: Discord User #5118
Date of testing: Current date 07/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3405
Tier of testing: 1
Changes to observe: Removed label from the smallest circle of the ND in arc mode

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Started A32NX cold&dark at EDDF
2. Powered aircraft and set all 3 adirs to NAV, waited for IRS to complete
3. With ND to ARC mode, checked all ranges that label from the smallest circle is removed

Flight notes (When done a full flight): -

Media:
image
image
image
image
image
image

Issues (If Any): -

Overall Rating: Good
Conclusions of the testing: Everything as expected

**Comment by stescouse** [comment]
Category: QA Tester
Name: stescouse#7271
Date of testing: 8/2/21
Version of the sim: 1.12.13.0
PR Tested: #3405
Tier of testing: 1
Changes to observe: Removed label from the smallest circle of the ND in arc mode

Testing technique: TryOut
Steps you've made to test the Pull Request:

1. Spawned C&D at MUHA 
2. Switched on ADIRS to NAV , switched to ARC and observed small circle label removed in all ranges.

ffff


Flight notes (If required: none

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: performed as outlined in PR.

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 08/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3405
Tier of testing: 1
Changes to observe: Removal of smallest arc radius in ND

Testing technique: Full back to back return flight
Steps you've made to test the Pull Request:
1. Spawned EGKK cold and dark, input flight to LFBZ
2. Checked ND during plan mode, all good - departed, checked ND flight plan inner radius on different modes
3. Landed, turn around - input return to EGKK
4. Checked ND radius inner was not present again for all of return

Flight notes (When done a full flight): N/A

Media: Livestreamed here https://youtu.be/b0hYiT2MVvU

Issues (If Any): CTD at the beginning of stream at the exact moment I went to pushback but that was linked to the EGKK scenery NOT this PR.


Overall Rating: Good
Conclusions of the testing: This worked as expected and described, no issues!

**Pull request merged**
