### PR TITLE
feat(sec): ground spoiler logic improvements

### PR DESCRIPTION
**Pull request by lukecologne**
## Summary of Changes

* Fixes an issue with the ground spoiler full extension, where the spoilers would extend when only one thrust lever was at idle, instead of both.
* Adds a condition to the partial extension, to reduce a possible bounce in the case of improper thrust handling on landing: The spoilers will partially extend when
   * The Ground Spoilers are armed
   * Both thrust levers are below the CLB notch
   * Both MLGs are compressed

## References

https://safetyfirst.airbus.com/app/themes/mh_newsdesk/documents/archives/a320-family-evolution-of-ground-spoiler-logic.pdf

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by crocket63** [comment]
Adding an entry in changelog maybe?

**Comment by lukecologne** [comment]
Done

**Review by tracernz — APPROVED** [review]

**Comment by alexr4339** [comment]
Quality Assurance Tester Report

Discord          : Alex R#6663
Object of testing: #PR 7653
Tier of Testing  : 1
Date             : 22/12/2022

Testing Process: 
Updated A32NX to latest experimental.
Loaded the aircraft on the runway and took off. Armed ground spoilers and brought the bird to the landing config. Flew a cicuit and performed a normal approach and landing. Ground Spoilers extended normally and fully. Pushed levers to TOGA and went around. Spoilers retracted as expected. Brought it landing config again and flew the circuit. This time I did not flare and left the thrust levers around 45% N1. After (the hard) touchdown the spoilers extended halfway and RA showed 0. Due to the lift dumping as intended by Airbus in the PDF linked in this PR I did not even bounce so I pulled back and left the thrust where it was (45% N1) to simulate the bounce. I got in the air to about a RA of 2ft. Spoilers were still halfway extended and I really felt the lift dumping as intended by Airbus. Instead of touching down fully I ste TOGA thrust and went around, spoilers retracted fully as expected.

Negatives:       
N/A

Testing Results: 
Passed

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: (#PR Number)
Tier of Testing  : 1
Date             : 29/12/2022

Testing Process: 
Fixes an issue with the ground spoiler full extension, where the spoilers would extend when only one thrust lever was at idle, instead of both. - **OK**

Adds a condition to the partial extension, to reduce a possible bounce in the case of improper thrust handling on landing: The spoilers will partially extend when
The Ground Spoilers are armed
Both thrust levers are below the CLB notch
Both MLGs are compressed - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

**Pull request merged**
