### PR TITLE
fix(mcdu): remove replacement chars on aoc atis page

### PR DESCRIPTION
**Pull request by ExampleWasTaken**
Fixes #[issue_no]

## Summary of Changes

Small fix that removes the unicode replacement characters from AOC ATIS REQUEST page.

## Screenshots (if necessary)

**Before:**
Microsoft Flight Simulator Screenshot 2021 04 25 - 00 04 59 68 Microsoft Flight Simulator Screenshot 2021 04 25 - 00 05 07 30 Microsoft Flight Simulator Screenshot 2021 04 25 - 00 05 15 04

**After:**
Microsoft Flight Simulator Screenshot 2021 04 25 - 00 06 31 31 Microsoft Flight Simulator Screenshot 2021 04 25 - 00 06 38 76 
Microsoft Flight Simulator Screenshot 2021 04 25 - 00 06 47 57

Discord username (if different from GitHub): `ExampleWasTaken#0886`

## Testing instructions

- Make sure that the replacement characters are not displayed.
- Make sure the ATIS request feature still works. (It is important that you request the ATIS from an airport that currently has an ATIS! Check [this](https://vau.aero/fsmap/?osm) site for available ATISs)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by myselfaaryan — APPROVED** [review]
GTG! 🚀

**Comment by beheh** [comment]
Do we have a reference here on what these chars were trying to accomplish? I tried this originally in #3847 where I gathered that these were supposed to be whitespaces so the text indent matches even if no arrow is present, and therefore I replaced it there with the \xa0 protected whitespace.

**Comment by TheSquirtingPantin** [comment]
Category: QA Trial
Name: Discord User Rémi#8871
Date of testing: Current date 27/04/2021
Version of the sim: V 1.15.8.0
PR Tested: #4568
Tier of testing: 1
Changes to observe: Assess new characters on the AOC "ATIS" page.

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. C/D at KDEN
3. Requested ATIS thtought the ATSU AOC ATIS page
4. Visual analyse of MCDU screen.
5. Logic check. 

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any):
No issues with the MCDU AOC page. No "square" characters.
Correction was not applied to MCDU AOC "message received" page and message received were still showing squared characters (not in PR spectrum). 

Overall Rating: Good
Conclusions of the testing: LGTM, good job ! Fix need to still be applied to the "Message Received" section.

**Comment by ExampleWasTaken** [comment]
> 
> 
> Do we have a reference here on what these chars were trying to accomplish? I tried this originally in #3847 where I gathered that these were supposed to be whitespaces so the text indent matches even if no arrow is present, and therefore I replaced it there with the \xa0 protected whitespace.

@beheh 
In VS code they were displayed as `~`. I didn't look for references, as I did not think that there should be any character. I rather thought this to be an error. If there should be a whitespace I will add that.
I unfortunately don't have the manual for the Honeywell and could not find it on the internet. So I would be grateful if that could be sent to me for future reference.

**Comment by ExampleWasTaken** [comment]
@TheSquirtingPantin Thanks for the review I will take a look at the "message received" issue, once we have further references on what should actually be there.

**Comment by ExampleWasTaken** [comment]
I'd appreciate it if someone could add the `Do Not Merge` label, that would be appreciated, as there are still a few thing to sort out.

**Comment by ExampleWasTaken** [comment]
> Correction was not applied to MCDU AOC "message received" page and message received were still showing squared characters.  

This is not something that I can fix, as the invalid characters are included in the received ATIS. I've opened an issue about this with a proposal for a fix. #4627

> EDIT (27th APR 2021): Another bug was found. When requesting either a ARR, DEP or ENR ATIS with the ICAO left blank. Request is being processed with no error messages and the message received in the MCDU message received section is blank.

I am currently working on a fix for that. But this will be a separate PR.

**Review by myselfaaryan — APPROVED** [review]

**Pull request merged**
