### PR TITLE
Various fixes/additions to ECAM, FWC, and FMA

### LINKED ISSUE #2238: [REQUEST] ECAM to display "OUTR TK FUEL XFRD"
**Is your feature request related to a problem? Please describe.**

When the inner fuel tank is below 750kg, fuel is transferred from the outer fuel tanks of both wings.
This feature works fine.

**Describe the feature you'd like to see implemented**

While the fuel is being transferred, "OUTR TK FUEL XFRD" will be displayed on the upper ECAM.
Is it possible to have the feature implemented ?
Also, if you can add the following features to the lower ECAM, please implement them.
 The FUEL page on the lower ECAM will be marked with green triangles.
My mother tongue is not English, so I use translat ion software to write.

**References**

1.Summary
101237955-25f18b00-3720-11eb-83a5-c1739cd13ada

2.Upper ECAM
101237987-66e99f80-3720-11eb-9ac6-ebf52547f2fe

WS000008

3.(If possible)Lower ECAM Fuel Page 
101238084-1f174800-3721-11eb-9950-ec760ef8a75b
WS000006

Samples
fuel_6 (1)
fuel_7 (1)

**Additional context**

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by wpine215**
Fixes #2238

## Summary of Changes

- Added new options menu (CIDS) with option to replace "NO SMOKING" memo with "NO PORTABLE DEVICES", which are commonly found on Neo aircraft
- Added PACKS/NAI/WAI text indicator on upper ECAM, which is visible when thrust mode targets TOGA, FLEX/MCT, or SOFT GA.
- Added REFUELG left memo when fuel truck connected
- Added OUTR TK XFRD left memo when fuel is actively being transferred from outer to inner tanks
- Added CABIN READY right memo according to documentation (flight phases 2, 6, and 7)
- Added FUEL X FEED right memo when fuel cross-feed is on
- Added ADIRS SWTG right memo when either Air Data or IRS switching knobs on the pedestal are in use
- Adjusted position of AUTO BRK right memos to reflect documentation
- Adjusted positioning of N2 and FF text on the EWD, as it was previously asymmetrical
- Increased blinking interval of "LVR CLB" on FMA from 1s to 1.5s as it was blinking too quickly
- Fixed typo in WHEEL ECAM page where "AUTO BRAKE LO" was mislabeled as "AUTO BRAKE MIN"

## Screenshots (if necessary)

image

## References

Available upon request.

Discord username (if different from GitHub): Iceman#5540

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
It seems to be OUTR TK FUEL XFRD not OUTER TK FUEL XFRD

See #2238's references

See
image

**Comment by wpine215** [comment]
> 
> 
> It seems to be OUTR TK FUEL XFRD not OUTER TK FUEL XFRD
> 
> See #2238's references. Their FCOM is EIS1 though. so look at the IRL EIS2 pic.
> 
> See below for H2F9C FWC
> image

Fixed.

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing:  17/12/20
Version of the sim: 1.11.7.
PR Tested: #2479 
Object of test: ECAM, FWC and FMA

Testing technique: Did a whole flight and a few landings

Steps you've made to test the Pull Request:
1. Spawned in at Dublin
2. flew to Southampton 
3. Checked that all the things that should be there are there

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Everything works as expected and as described

**Comment by easyjetsimpilot** [comment]
Category: QA Tester
Name: Gavin
Date of testing: 17/12/20
Version of the sim: 1.11.7.
PR Tested: #2479
Object of test: ECAM, FWC and FMA

Did a flight and put the aircraft through phases that should test all changes. 

NO PORTABLE DEVICES  - working
REFUELG - working
CABIN READY - working 
PACKS - displayed on upper ECAM during TOGA T/O test
OUTR TK XFRD - working
FUEL X FEED right memo - working when P/B turned on
ADIRS SWTG - working when switched

LVR CLB - flashes twice at even interval, then delayed until restarting (second flash is only a quick one)
"DH" and "MDA" with "RADIO" and "BARO", respectively, on the FMA - working

**ERROR** - turning on LOC also give G/S standby in Blue on FMA - shouldn't be armed in LOC mode. 
**ERROR** - turning on LOC also captures G/s (green) - should not capture G/S in LOC mode, only in APPR mode

**Comment by lukecologne** [comment]
>   * Replaced "DH" and "MDA" with "RADIO" and "BARO", respectively, on the FMA

@wpine215  BARO/RADIO is an optional setting. If it is installed, the MCDU would also show BARO/RADIO instead of MDH/DH

**Comment by wpine215** [comment]
> 
> 
> > * Replaced "DH" and "MDA" with "RADIO" and "BARO", respectively, on the FMA
> 
> @wpine215 BARO/RADIO is an optional setting. If it is installed, the MCDU would also show BARO/RADIO instead of MDH/DH

Alright, removed it for now. Will add in future PR.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by donstim** [comment]
@wpine215 Any chance you could latch the "OUTR TK FUEL XFRD" so that it remains up once it is triggered? One of the pilots mentioned the other day on Discord that once it appears it remains in view until refueling. His comment is consistent with what is in the FCOM:
Screenshot (457)

Although MSFS transfers the fuel in "chunks," which I assume is what your message trigger is based on, once the valves open they are latched open to allow fuel IRL to continuously drain from outer to inner tanks.

**Pull request merged**
