### PR TITLE
fix(efb): Fix for missing icons in EFB Map

### LINKED ISSUE #4761: EFB Map Buttons show Boxes
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

EFB Map Buttons are Boxy

### Expected behavior

There should be a - / + or other buttons.

### Steps to reproduce

Power up EFB
Look on the lower right side of the map

### References (optional)

image

### Additional info (optional)

_No response_

### Discord Username (optional)

iunoi#8403

### PR DESCRIPTION
**Pull request by antonyisoardi**
Fixes #4761

## Summary of Changes

PR is to address the missing icons in the EFB Map. This has been done with the introduction of @flybywiresim/react-components, as well as this I've updated the Slider and Toggle components which were also migrated across to the component library.

* Added @flybywiresim/react-components
* Swapped and removed @flybywiresim/map for @flybywiresim/react-components in EFB Dashboard
* Replaced Slider and Toggle components with @flybywiresim/react-components

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Open the EFB, view the map, make sure that the icons are in the control panel in the bottom right of the map.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by hiaaryan — APPROVED** [review]
LGTM! 🚀

**Comment by marcman86** [comment]
Category: QA Tester
Name: marcman86#4907
Date of testing: 4.06.2021
Version of the sim: 1.16.2.0
PR Tested: #5003
Tier of testing: 1
Changes to observe: EFB Map buttons
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat., ext. power and EFB
3.) Tested EFB map buttons

Negatives: Unit button dont change to m or mi. Track and X have no functions. Airplane icon flickering.

Result: Zoom buttons work

Conclusion: If mentioned issues are not part of this PR, the PR is GTG.

Hope this helps :-)

**Comment by scoopscode** [comment]
Non QA Tester Report

Discord: Scoopy#1399
Object of testing: #5003 
Tier of Testing: 1
Date: 04/06/2021

Testing Process: 
- Spawned C&D at KDFW
- Turned on aircraft using GPU and Batteries
- Tested all EFB buttons
Negatives: Both nm -> m and "X" button do not function. nm -> m button does not change the range counter at the bottom left corner to m
Testing Results: Passed

Conclusions: Button icons are there, some functions arent working. If those were not working previously then LGTM in terms of icon change!
Media: 
Screenshot (72)

**Comment by Benjozork** [comment]
There's a convenient dev build you can use to test the found issues.

**Comment by antonyisoardi** [comment]
@marcman86 thanks for your review.

Issues persisting since current stable:
- Airplane icon flickers
- Unit button unit change

There are other issues relating to unit, see screenshot from current Stable release.

image

As for track and clear track, these functions are working in this PR.

**Comment by antonyisoardi** [comment]
Created issues #5010 and #5011 to address bugs raised.

**Pull request merged**
