### PR TITLE
feat: PTU, engine, and other sound changes

### LINKED ISSUE #6953: Seats for landing announcement does not play
### Aircraft Version

Development

### Build info

```json
dev/exp
```

### Describe the bug

Writing this for myself, flight attendants seats for landing does not play due to a strange condition.

### Expected behavior

Should play.

### Steps to reproduce

1. Drop gear during approach, listen for announcement

### References (optional)

_No response_

### Additional info (optional)

For tracking - likely a flight phase condition issue.

### Discord Username (optional)

_No response_

### LINKED ISSUE #7047: Blower Sound
### Aircraft Version

Experimental

### Build info

```json
no build_info.json Bug. I just hear the Bug without CTD crash. It is not realy an Bug, it is only an Wrong Button or reservrd sound.
```

### Describe the bug

With the blower in the overhead, the sound is exactly the wrong way around. When the blower is off, the cockpit should be quiet because the instrument cooling fans are off. Here the issue is presented exactly the wrong way around. Sounds like the sound file is just programmed wrong. 

### Expected behavior

That when I turn off the blower the cockpit goes quiet, the fan noise goes silent like real. When I turn the blower on, the cockpit should be acoustically louder again.

### Steps to reproduce

I usually turn the blower off when I am at the gate. Therefore, I noticed that the sound file is reversed. 

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Joko#3959

### LINKED ISSUE #7107: Brake Fan Sound still audible when MSFS window not in focus
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-24T16:47:29+00:00",
  "ref": "experimental",
  "sha": "e3fa07845050458284f6e1e7fa1abf1ec6bfd838",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:e3fa0784"
}
```

### Describe the bug

The brake fan sound is audible when the MSFS window isn't in focus. All other sounds mute while the window isn't in focus except for the brake fan.

### Expected behavior

It is expected that the brake fan is not audble when the game window isnt in focus.

### Steps to reproduce

1. Turn on the brake fan (any cockpit configuration)
2. Alt + Tab or click onto another window to assume focus away from MSFS
3. The brake fan audio should still be audible outside of the game

Note: It is a lot easier to hear the brake fan outside of the cockpit if you're having trouble hearing it when the camera is external.`

### References (optional)

https://youtu.be/cm-b3beIMrU

### Additional info (optional)

_No response_

### Discord Username (optional)

Pancake#3074

### PR DESCRIPTION
**Pull request by hotshotp**
Fixes #7047
Fixes #6953
Fixes #7107
## Summary of Changes

***important note***
This PR is meant to only go into the experimental version for now - however, once #6893 is in master, it will also be put into master.

- Changed exterior attenuation for engines, AEVC, packs, APU, fuel pumps, and all other exterior sounds (@mico975)
- Added landing light drag (@mico975)
- Killed sneezing passenger during boarding (he only sneezes once now)
- Fixed seats for landing announcement not playing after meeting the conditions
- Changed cabin touchdown samples for all three firmness cases
- Added dynamic PTU sounds with different bark strength sounds and continuous operation, dynamic depending on the hydraulic system code (Thanks @crocket63 !)
- Changed cockpit gear clunk sample
- General improvements to interior engine spool up (higher quality idle, volume balancing)
- Improved reverse thrust sample on interior
- Buzzsaw now changes depending on air density (mostly noticeable with climbs in altitude)

## Additional context

Discord username (if different from GitHub):

Boris#8008
Mico#3145

## Testing instructions

Start aircraft cold and dark and enable yellow electric pump - check PTU sounds in exterior, interior cabin, and cockpit with the option enabled. Move flight controls and flaps and hear the PTU change intensity. Especially when the flaps move, wiggle the flight controls violently to hear PTU in continuous operation.

On takeoff, listen to the engine spool up, buzzsaw from cabin (it isn't too obvious from cockpit), when taking off listen to the gear clunk sample from cockpit. The PTU might go continuous when the gear is coming up.

On climb, retract landing lights and observe the wind get quieter.

On landing when the gear comes down, observe that the seats for landing captain announcement is audible. Check reverser sounds on interior after landing. Generally report if anything sounds off or sounds broken.

Please also test if yellow electric pump sound and the spoiler drag (wind) sound works, as this PR has been problematic with these

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by crocket63** [comment]
With PTU randomness merged I guess this one should go in sooner than later as ptu sounds will be broken in the meantime

**Comment by hotshotp** [comment]
Still a few tiny issues with this PR

**Review by aguther — APPROVED** [review]
LGTM

**Comment by aguther** [comment]
✅ Landings lights sound
✅ Spoiler sound
✅ PTU sounds (internal, cockpit, external)
✅ Yellow electric pump (internal, external)

LGTM, I will add it to an RC for 0.8.0 but wait for a second report to confirm it working to merge it to master.

**Review by Lucky38i — APPROVED** [review]

**Pull request merged**
