### PR TITLE
refactor(efb): Restructured API files

### PR DESCRIPTION
**Pull request by MicahBCode**
## Summary of Changes

This PR has changed the folder structure of the APIs used for the EFB (e.g. Navigraph) and bundles them together in a separate folder. The Navigraphs Authentication/Authorization has been outsourced into the new folder structure to make it reusable for new integrations across the EFB.

## Additional context

This PR is part of the preparation for the PR #7702 .
In addition this is a part of the preceeding PR #7728 that caused problems for a few users. The rest of the PR will be redone and submitted in a new PR.

Discord username (if different from GitHub): Micah#3002

## Testing instructions

Please test the following functions:

- The Navigraph Authentication/Authorization is still working as intended.
- The Charts Integration still works as before the update.
- The Simbrief Integration still works as before the structural changes were made.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by auroraisluna** [comment]
CS/Contributor/Unofficial Test Report

Discord : Alepouna🌙#9824
Object of testing: #7984 
Tier of Testing : 1
Date : 18/05/2023

Testing Process: 
- Open EFB
- Import (and auto-import) Simbrief profile
- Attempt authentication & charts 

Negatives:       
- Could not use Navigraph Authentication/Authorization (infinite loading)
image
- Reset Navigraph Authentication inop 
- Could not use charts integration due to above 

Testing Results:
Not passed

**Comment by MicahBCode** [comment]
> CS/Contributor/Unofficial Test Report
> 
> Discord : Alepouna🌙#9824 Object of testing: #7984 Tier of Testing : 1 Date : 18/05/2023
> 
> Testing Process:
> 
> * Open EFB
> * Import (and auto-import) Simbrief profile
> * Attempt authentication & charts
> 
> Negatives:
> 
> * Could not use Navigraph Authentication/Authorization (infinite loading)
>   image
> * Reset Navigraph Authentication inop
> * Could not use charts integration due to above
> 
> Testing Results: Not passed
> 
> Notes: Mayhap a key is required for the authentication to work?

This is most likely to be a PR issue with the API keys used. They need to be stored securely and should never be visible. Therefore testing might have to be done using a local build by someone of the FBW Team with access to those secrets instead.

**Comment by MicahBCode** [comment]
> You shouldn't get this far if the API keys are not present. Instead the page just shows "insufficient env" or something to that effect.

You don't because the check for the ENV variables only checks if they are not present at all. But as I can see in the build process in the Github Actions for the PR builds it is written but as an empty string. Therefore this happens.

**Comment by Benjozork** [comment]
Dev Team Test Report

Object of testing: #7984 
Tier of Testing : 1
Date : 01/06/2023

Testing Process: 

**With client secret**
- Wake up EFB
- Test SimBrief import -✅
- Test authn and charts loading - works - ✅

**Without client secret (empty string)**
- Wake up EFB
- Test authn and charts loading - `Insufficient .env file` - ✅

Negatives:       
None

Testing Results:
Passed

**Pull request merged**
