### PR TITLE
Fix: (Revision 2) flight_model.cfg changes to mitigate pitch oscillation during flare

### PR DESCRIPTION
**Pull request by MapleNAV-TCASFAULT**
Fixes #[N/A]

## Summary of Changes

Changes to the flight_model.cfg should mitigate the oscillation during flare mode, and should make banking issue harder to occur. PLEASE TEST THE TAKEOFF too!

## References

Reference is from my previous experience with FSX in the Aerosoft A320

## Additional context

Discord username (if different from GitHub): ChristopherXie #3904

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by MapleNAV-TCASFAULT** [comment]
This PR will have to be left for a long time/until a new FBW system is added, as the current fbw system makes the plane unflyable with the current flight_model.cfg changes, if over 135 knots.

**Comment by tjburni** [comment]
Category: QA Tester
Name: tjburni #0409
Date of testing: Current date 20/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2023
Object of test: Flight model


1. Loaded into the sim
2. flew to an airport
3. landed




Issues :banked to the right 
Overall Rating: to be improved
Conclusions of the testing: oscillation during flare was gone but it banked to the right

**Comment by MapleNAV-TCASFAULT** [comment]
"Partially fix banking issue". Its caused by the terrible FBW transition, which is out of my knowledge to fix. Once a new FBW system is integrated, it should no longer exist. It will still occur no matter what sadly. I should change to "should make banking  on flare issue harder to cause" @tjburni

**Comment by tjburni** [comment]
> "Partially fix banking issue". Its caused by the terrible FBW transition, which is out of my knowledge to fix. Once a new FBW system is integrated, it should no longer exist. It will still occur no matter what sadly. I should change to "should make banking on flare issue harder to cause" @tjburni

yeah the problem was on 2 of 5 landings i did so its better that before

**Comment by HugoTro** [comment]
Name: Hugo #3307
Date of testing: Current date 20/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2023 

Testing technique: Testing?
Steps you've made to test the Pull Request:
1. Spawned in approach at LFRS RWY 03
2. Touch & Go x3
3. Landed

Overall Rating: Good
Conclusions of the testing: Seems right to me, didn't experience sensitivity x100 under 10ft with this PR but you need to consider the other tests too

**Comment by Awemeter** [comment]
Category:
Name: Awemeter#7919
Date of testing: 11/20/20
Version of the sim: 1.10.11.0
PR Tested: #2023
Object of test: Flight Model

Testing technique: Tested out
Steps you've made to test the Pull Request:
1. Spawned in at 9nm final for runway 28r at Kord
2. Landed and restarted approach x3
3. Taxied to runway and took off runway 28r at Kord. Rotation felt normal.
5.

Flight notes (If required):

Issues: Flight Controls are too sluggish. I had a small roll over to the right on the landing. 
Overall Rating: To Be improved
Conclusions of the testing: Nice job on your first PR needs work but I know you can do it

**Comment by joshbxd514** [comment]
Category: QA Tester
Name: joshbxd515#4978
Date of testing: 21/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2023 
Object of test: Flight Model

Testing technique: I completed a flight from EGLL - EGKK and then done a further 4 landings and takeoffs
Steps you've made to test the Pull Request:
1.  1 Take off - light weight
2.  1 landing - light weight
3.  1 Take off - medium weight 
4. 1 Landing - Medium weight
5. 1 Take off - Heavy weight
6. 1 Landing - Heavy Weight

Flight notes (If required):

Light Load Take off: Smooth Take off climbed very quick due to being very light. no issues and no banking
Light Load Landing: Felt a little sluggish than it should be for a light AC.

Medium Load  Take off: Again a very smooth take off, No issues or no banking
Medium Load Landing: Didnt feel as sluggish this time, and good flaring no banking issues.

Heavy Load Take off: No issues good take off and no banking
Heavy Load Landing: This again felt sluggish but this may be down to the weight? however was a good landing.



Issues (If Any):  I think it needs to be looked at regarding sensitivity and sluggishness depending on the weight of the AC
Overall Rating:: To be improved
Conclusions of the testing: Good work on the PR a little more work then i feel this could be a great addon the already great A32NX. I have attached my weights below for the take/offs and landings.


egll-egkk light trip




egkk takeoff Medium weight








egkk takeoff heavy

**Comment by MapleNAV-TCASFAULT** [comment]
Thanks for the in depth testing @joshbxd514. Greatly appreciated. I’ll implement changes to make the aircraft more sensitive!

**Comment by Carter633** [comment]
Category: QA Tester
Name: Carter633 #1436
Date of testing: Current date 22/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2023
Object of test: Flight model changes

Testing technique: Full Flight from EGLL to LOWW - 58T ZFW
Steps you've made to test the Pull Request:

1. Pushback was an issue - had Left rudder input but no Right Rudder input suddenly - only happened with this PR
2. Taxi was an issue - constant hard left rudder - required 70% right rudder input to keep straight
3. Same happened during take off roll, though takeoff was fine
4. A/P engaged without issue, rudder did not conflict at this time
4. STILL TESTING - will update at the end of the flight

Overall Rating: To be improved
Conclusions of the testing: See above steps - will update full report at end of flight

Live streamed here https://www.youtube.com/watch?v=9Gy-Ni4xZT0

**Comment by MapleNAV-TCASFAULT** [comment]
This PR will be closed and will be an addition to flightsim.to! Feel free to download it from there now!

**Pull request closed without merging**
