### PR TITLE
Fix FD in Taxi Checklist (fixes #1403)

### LINKED ISSUE #1403: [BUG] Taxi checklist: copilot turns off the FD
**Mod Version**

dev: 
built: 2020-10-16T00:15:31+00:00
ref: refs/heads/master
sha: e08f84b3c7db7767aab2c34c8a90ea059bd1f9fe
actor: lukecologne
event_name: push

**Describe the bug**

Taxi check list calls for flight director "on", but the copilot turns it off.

**To Reproduce**

1.Click FD on (as it would be from previous checklist)
2.Bring up the taxi checklist and select "Flight Director"
3.Click evaluation-->Nothing happens. Expected: Response should be "On" and checklist continues.
4. Turn off the FD-->Response is "On" and checklist continues.
5. If you autocomplete or let the copilot do it, the FD gets turned off.

**Expected behavior**

The FD should remain on, should not be turned off by the copilot and should not require being turned off to advance in the checklist.

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by Acrobot**
The current condition checks whether FD is turned OFF, instead of ON.

Fixes #1403

## Summary of Changes
The current condition in the checklist checks whether FD is turned OFF, instead of ON.

## Screenshots (if necessary)
n/a

## References
n/a

## Additional context
n/a

Discord username (if different from GitHub): acro#2421

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by ImenesFBW** [comment]
Hey there and thank you for your effort!
The only way to test that came to mind was to let the AI autocomplete the TAXI C/L but it seems to be unable to read the state of FD correctly 

image

**Comment by ImenesFBW** [comment]
Can you please merge the latest master branch to this PR, hard to test after update without the fixes in the master.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 31/10/2020
Version of the sim: 1.10.8.0
PR Tested: #1478
Object of test: Testing FD state via C/L

Testing technique: Try-out (multiple tests)
Steps you've made to test the Pull Request:

1. Started cold and set up the cockpit ran the C/L via autocomplete and manually. 
2. Started on the runway  and did the same.


Flight notes: N/A

Overall Rating: Fixes the issue but needs further testing after patch 5

Conclusions of the testing: This seems to fix the issue and it now checks the FD state correctly but it needs further testing after the
 UPDATE 6 and the following hotfix, also there is one more thing I wanted to ask; with autocomplete the FD is not turned on automatically by the autocomplete feature. It waits for manual input and then finishes successfully after manual input, is that
something that can be automated? Pic below. Thank you for your work!

image

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 31/10/2020
Version of the sim: 1.10.8.0
PR Tested: #1478
Object of test: Testing FD status with checklist

Testing technique: Try-out in two different scenarios
Steps you've made to test the Pull Request:

Started cold and set up the cockpit ran the C/L via autocomplete and manually.
Started on the runway and did the same.

2 Different scenarios to check for consistency:
- C&D Start and check the functionality of the FD check via the AI integrated auto complete function. And also done myself manually.
- Spawn on RWY. 

Flight notes: N/A

Overall Rating: Good

Conclusions of the testing: LGTM. It did appear to be a little glitchy as at first -  it did not show the 'ON' but showed blank. After that it all worked fine. but its good enough to be merged after the latest changes.

**Pull request merged**
