### PR TITLE
Cleanout pfd

### PR DESCRIPTION
**Pull request by 1Revenger1**
**Summary of Changes**

Remove a lot of lines of code from PFD which were related to other aircraft. This shouldn't change any functionality, and appears to work fine on my machine.

**Screenshots (if necessary)**

N/A

**Additional context**
N/A

Discord username (if different from GitHub): 1Revenger1

### CODE REVIEW

**Comment by Coralec** [comment]
I completed a full flight watching the pfd. Everything appears to be working normally. Should be ready for merge.

**Comment by Benjozork** [comment]
Hello, please take note that we have started including a CHANGELOG.md file that requires every PR to add a change-log line that describes its changes. As your PR is not merged yet, we kindly ask that you add this information following the included directives in the file.

Disclaimer: This is a copy-and-pasted message.

**Comment by 1Revenger1** [comment]
Updated CHANGELOG.md

**Review by AdenFlorian — APPROVED** [review]
lgtm

**Pull request merged**
