### PR TITLE
feat: auto print when "format for printer" option is selected

### LINKED ISSUE #3198: [BUG] Printer should print with printer ouput selected
**Mod Version**
26th Jan 21 dev version

**Describe the bug**

When requesting weather no matter what type and output format is set to Printer, the message should print itself without going into the received messages. Only when its selected to MCDU it will not print.
image

**To Reproduce**

1.
2.
3.

**Expected behavior**

Message should be printed automatically

**Actual behavior**

Message does not print

**References**

IRL experience

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by tyler58546**
Fixes #3198 

## Summary of Changes

* Requesting ATIS with the "FORMAT FOR PRINTER" option selection will now cause the message to go straight to the printer
* Changed default ATIS format from "PRINTER" to "MCDU"

## References

Based on feedback from @St54Kevin, a real world A320 pilot.

## Testing instructions

Request ATIS with the "FORMAT FOR" option set to "PRINTER" and make sure the message goes straight to the printer.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 27/12/2021
Version of the sim: 1.12.13.0
PR Tested: #3199 
Tier of testing: Tier 1
Changes to observe: Printer behavior

Testing technique: 
Steps you've made to test the Pull Request:
- Loaded up on the runway
- Sent ATIS request from an online VATSIM airport
- Message came in, went to Received messages, printed the ATIS
- selected "PRINTER" as output
- Sent again

Media:

Issues (If Any):
- MCDU ouput works
- But Printer output just prints the message, it should also trigger the "company msg" ECAM message for some seconds and it should be available in Received messages to print again later

Overall Rating: Needs improvements

Conclusions of the testing: ^^

**Comment by wpine215** [comment]
Any update on this PR?

**Comment by MisterChocker** [comment]
closing since I am not able to maintain the branch -> #5146

**Pull request closed without merging**
