### PR TITLE
fix(mcdu): check to data

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- `CHECK TO DATA` message appears when either v1/vr/v2 has been entered and FLAPS or THS or FLEX TEMP is changed.
- Confirm prompt only appears when changing TO RUNWAY

## Screenshots (if necessary)

image

## References

[Pilot Feedback](https://discord.com/channels/738864299392630914/754851312306487326/808681537834450946)
image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Pre conditions:
- Take Off runway is defined prior to performance page entries:
   1. Define Take Off runway
   2. Insert V1/VR/V2/FLEX TMP
   3. Change SID
   4. no confirm prompt and no message is displayed
   5. Change Take Off runway
   6. Confirm prompt is visible  (V1/VR/V2/FLEX TMP needs to be confirmed) and message are displayed
- Take Off runway is not defined prior to performance page entries:
   1. Insert V1/VR/V2/FLEX TMP
   2. Insert Take Off runway
   3. Conform prompt is visible (V1/VR/V2 needs to be confirmed) and message is displayed

Changing FLEX TEMP and FLAPS/THS only brings up the message.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by beheh — APPROVED** [review]

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 11.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3446
Tier of testing: 1

### Changes to observe: Check Takeoff Data warning

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned C/D at VABB gates, initialized ADIRS
2. Setup INIT page, departure set for RWY27
3. Set V speeds on PERF page, then added flaps setting. Warning observed
4. Set FLEX temp, warning observed
5. Changed departure runway to RWY14, warning observed
 
### Media:
image
image
image

### Issues (If Any): None

### Overall Rating: Good

### Conclusions of the testing: The CHECK TAKEOFF DATA warning appears on each of the above mentioned test cases. Good to go!

**Comment by MisterChocker** [comment]
@Benjozork no changelog needed since this is a fix to feature added two days ago.

**Comment by beheh** [comment]
I agree this does not require a changelog. I think we can merge this.

**Comment by beheh** [comment]
I was about to merge this, but I believe I discovered what I believe are two more missing piece of behavior:

1) Reentering the FLX temperature:  
image
Changing the runway should also make 4R become empty with the value next to it, and CONFIRM TO DATA* would fill it again, unless this is the first time the runway is specified.

2) Not triggering the check the first time a runway is entered: Based on the V1/VR/V2 text below:
image
...saying "runway is changed", I suspect that, similarly to above, if you have your V-speeds entered with no selected runway, and you select a runway for the first time, this TO CHECK should *not* be triggered.

Do these seem accurate? @St54Kevin?

@MisterChocker If they are, are these things you still want to implement as part of this, or do you prefer to get this merged and tackle those in a future PR?

**Comment by St54Kevin** [comment]
> I was about to merge this, but I believe I discovered what I believe are two more missing piece of behavior:
> 
> 1. Reentering the FLX temperature:
>    image
>    Changing the runway should also make 4R become empty with the value next to it, and CONFIRM TO DATA* would fill it again, unless this is the first time the runway is specified.
>    I was unable to find a visual Honeywell reference, but here's a Thales reference for this (which would match what I'd expect based on the text above), although it does have the derate option enabled so it's unclear if it would be `{small}65{end} []°`or more like `{small}65°{end} []°`.
>    image
> 2. Not triggering the check the first time a runway is entered: Based on the V1/VR/V2 text below:
>    image
>    ...saying "runway is changed", I suspect that, similarly to above, if you have your V-speeds entered with no selected runway, and you select a runway for the first time, this TO CHECK should _not_ be triggered.
> 
> Do these seem accurate? @St54Kevin?
> 
> @MisterChocker If they are, are these things you still want to implement as part of this, or do you prefer to get this merged to fix the original issues and tackle these in a future PR?

Sorry for the late reply. I didnt get a notification.

Well those are interesting question I cannot 100% answer. We should stick with the manual no matter what. The FLEX being part of the CONFRIRM TO DATA action after a runway change makes sense to me but I dont know how Honeywell is doing it.

Also I never experience a situation where I entered V speeds without a runway because that situation will NEVER occur due to operating procedures telling to do the PERF page last (SIF - copy RIP, Status, INIT A, FPLN, copy SEC, RadioNav, INIT B, PERF).

**Comment by MisterChocker** [comment]
@St54Kevin thanks for the response!

I also don't understand how you could possibly have the takeoff page filled before everything else, because it's literally the last step. As you said because of the procedure DIFRIP or SIDRIP, there are also procedures that with more steps in-between but they all follow the same flow.

**Comment by beheh** [comment]
As you mention PERF is usually only called up as one of the last pages after everything else has already been configured, but rather than just disable the page the manufacturer has chosen to implement at least *some* reasonable behavior.
While it's not encountered in day-to-day use and especially not from any pilots with real A320 experience, I believe the chances are high that sim pilots will encounter this, and as the real system does allow it we should just implemnet it where feasible and especially if it's described in the manual.

A bunch of my prior research on this PERF TAKE OFF page was exactly getting e.g. visual references from this page with no or very little data entered.

**Comment by St54Kevin** [comment]
> As you mention PERF is usually only called up as one of the last pages after everything else has already been configured, but rather than just disable the page the manufacturer has chosen to implement at least _some_ reasonable behavior.
> While it's not encountered in day-to-day use and especially not from any pilots with real A320 experience, I believe the chances are high that sim pilots will encounter this, and as the real system does allow it we should just implemnet it where feasible and especially if it's described in the manual.
> 
> A bunch of my prior research on this PERF TAKE OFF page was exactly getting e.g. visual references from this page with no or very little data entered.

When thinking about it, it should also show "Confirm T.O data" when there was no runway selected before, because that message is there to remind you to check wether your calculations are for the corrrect runway. And of course the system doesnt know wether you calculated for the runway not yet set. From that point of view i would say it should also come on in the case there was no runway selected before

**Comment by MisterChocker** [comment]
@beheh The exact option to enter data into the perf page (V1/VR/V2/FLEX) and then enter the runway is already supported.

This is how I made it "work".
The runway change `check to data` and prompt trigger requires the take off runway to be changed.
If no take off runway was defined before, the newly selected becomes the take off runway. This information is stored.
If a take off runway is defined, and the runway has changed, the message and prompt will be triggered.

**Comment by MisterChocker** [comment]
After reading that text again and again, I believe the message is always triggered when changing or entering the takeoff runway and to perf is already defined.

But only when entering the takeoff runway for the first time the flex temp will not be "cleared"

**Comment by MisterChocker** [comment]
> When thinking about it, it should also show "Confirm T.O data" when there was no runway selected before, because that message is there to remind you to check wether your calculations are for the corrrect runway. 

Totally agree with you, would only make sense.

**Comment by Samueleonard** [comment]
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: Current date 20/02/2021
Version of the sim: 1.13.16.0
PR Tested: #3446 
Tier of testing: 1
Changes to observe:
.CHECK TO DATA message appears when either v1/vr/v2 has been entered and FLAPS or THS or FLEX TEMP is changed.
.Confirm prompt only appears when changing TO RUNWAY

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. loaded in at PMDY as normal rwy24, default livery, live time, clear skies
2. entered pmdy/pmdy and basic init A (screenshot 1)
3. entered dep rwy24, no sid
4. quick filled init-b
5. entered perf page using quickfill LSK clicks (screenshot 2)
6. changed dep rwy to 06, verified that CHECK TO DATA appeared, as expected (screenshot 3)
7. re-entered takeoff data
8. changed takeoff runway back to rwy 24 - CHECK TO DATA appeared again, as expected

Flight notes (When done a full flight):
N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
https://i.imgur.com/wTL3GET.png (screenshot 1)
https://i.imgur.com/CsAno5a.png (screenshot 2)
https://i.imgur.com/2e9GPe3.png (screenshot 3)

Issues (If Any): Write any issues
N/A
Steps to achieve the issue
N/A

Overall Rating: Good
Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.
Works as intended. LGTM

**Pull request merged**
