### PR TITLE
fix(mcdu): do not round baro/radio, remove ILS check on PERF APPR

### PR DESCRIPTION
**Pull request by tracernz**
Fixes discord issue

## Summary of Changes

- Remove rounding inadvertently applied to BARO and RADIO during review fixes.
- Remove ILS check for RADIO (that's already in the UI code, but a slightly different check, don't want a disagreement)

## References

Honeywell Step1A data formats.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

On PERF APPR:
- Ensure values in BARO and RADIO fields are not rounded to nearest 10 feet
- Ensure RADIO height (DH) can be entered when an ILS approach is selected in the flight plan

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by beheh — APPROVED** [review]
I'm not opposed to the ILS check per se, but I don't feel strong about keeping it either.

**Comment by ExampleWasTaken** [comment]
Category: QA Trial
Name: ExampleWasTaken#0886
Date of testing: 24/03/2021
Version of the sim: 1.14.5.0
PR Tested: #4100
Tier of testing: 1
Changes to observe:
no decision height/altitude rounding, remove ILS check on PERF APPR

Testing technique:
1. Loaded into approach into EDHI
2. Check that RADIO and BARO values are not rounded
3. Verified that RADIO could be entered while an ILS appr was loaded in the flight plan

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): N/A

Overall Rating: Good
Conclusions of the testing: Worked perfectly fine

**Comment by Samueleonard** [comment]
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: 24/03/2021
Version of the sim: 1.14.5.0
PR Tested: #4100
Tier of testing: 1
Changes to observe: check baro/radio minima can be entered without rounding
Testing technique: Tryout

Steps you've made to test the Pull Request:
1. entered appr to eddb (25R)
2. entered minima (360)
3. entered non 0 minima (365)
4. checked no rounding
5. checked minima callout plays

Flight notes (When done a full flight): N/A

Issues (If Any): N/A

Overall Rating: Good

Conclusions of the testing: LGTM

**Comment by tracernz** [comment]
> I'm not opposed to the ILS check per se, but I don't feel strong about keeping it either.

It's in the UI, but a different way of checking... and I have a hunch they may disagree sometimes, for reasons I don't know, based on a report I got on Discord. So I removed this one to avoid a situation where it's displayed in the UI, but not allowed for entry.

**Comment by tracernz** [comment]
Simple fix with two good tests (thanks! :)), merging..

**Pull request merged**
