### PR TITLE
fix: hide colon when chrono stopped (#3237)

### LINKED ISSUE #3237: [REQUEST] 【Clock】 When the time is stopped by pressing the CHR button, there is no colon in center
**Is your feature request related to a problem? Please describe.**

Clock enhancements

**Describe the feature you'd like to see implemented**

I have a request regarding the chrono counter (CHR) function of the clock.
When the time is stopped by pressing the CHR button, the ":" is not displayed in the centres.
The ":" is only displayed if the clock is running.

**References**

WS000007

VIDEO (1:00~)
*There is backlighting and it is difficult to see.

https://www.youtube.com/watch?v=xczl6YiLRl0&t=70s

**Additional context**

I have researched FCOM. But for some reason I could not find a description.
So the only reference I have is a video. Sorry.

### PR DESCRIPTION
**Pull request by SergeySoprykin**
Fixes #3237

## Summary of Changes

Hide HH:MM separating colon when timer is stopped

## Additional context

Discord username (if different from GitHub): SergeyS#7450

## Testing instructions

Action:
1. Set ANN LT switch to TEST position on overhead panel
2. Set ANN LT switch to BRT or DIM position
3. Press CHR button on clock panel to start chrono
4. Press CHR button to stop chrono
5. Press CHR button to resume chrono
6. Wait one hour
7. Press CHR button to stop chrono

Result:
1. '88:88' displayed on chrono
2. Nothing displayed
3. Chrono started, the colon is seen
4. Chrono stopped, no colon seen
5. Chrono started, the colon is seen
6. MM:SS mode changed to HH:MM, colon is seen
7. Chrono stopped, no colon seen

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Cjarant2020 — APPROVED** [review]

**Review by beheh — APPROVED** [review]
I'm not a huge fan of doing the modulo/division math twice, but I believe this shouldn't matter. Performance impact should be minimal.

**Comment by starvingjavi** [comment]
Category: QA Trial
Name: Javi#2557
Date of testing: 12/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3469 
Tier of testing: 1
Changes to observe:
Fixes to chronometer, check everything works as described

Testing technique: Test list of instructions
Steps you've made to test the Pull Request: Spawn airplane on MMAA Cold and Dark

1. Set ANN LT switch to TEST position on overhead panel
       '88:88' displayed on chrono: Works as intended
2. Set ANN LT switch to BRT or DIM position
       Nothing displayed: Works as intended
3. Press CHR button on clock panel to start chrono
       Chrono started, the colon is seen: Works as intended
4. Press CHR button to stop chrono
       Chrono stopped, no colon seen: Works as intended
5. Press CHR button to resume chrono
       Chrono started, the colon is seen: Works as intended
6. Wait one hour
       MM:SS mode changed to HH:MM, colon is seen: Works as intended
7. Press CHR button to stop chrono
      Chrono stopped, no colon seen: Works as intended

Issues (If Any): None
Overall Rating: Works as described in the PR
Conclusions of the testing: LGTM

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 13.2.2021
Version of the sim: 1.12.13.0
PR Tested:  #3469
Tier of testing: 1
Changes to observe: Look at chronometer colon behavior
Testing technique: Tryout

Steps you've made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turn on bat. and external pwr.
3.) Started timer (Image1)
4.) Stopped timer (Image2)
5.) Resumed and waited till HH:MM (Image3)
6.) Stopped again (Image4)
7.) Resumed, stopped, resetted and repeated the MM:SS test

Media:


Image1


Image2


Image3


Image4

Issues (If Any): None

Overall Rating: Good

Conclusions of the testing: Works! Please be aware of PR #3448.

Hope this helps :-)

**Comment by cianwhite** [comment]
Category: QA Tester
Name: Cian#3596
Date of testing: 15/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3469 
Tier of testing: 1
Changes to observe: Colon is hidden when chrono is stopped

Testing technique: Started Cold and Dark and observed chrono changes
Steps you've made to test the Pull Request:
1. Started Cold and Dark at EIDW and started up as normal
2. Observed chrono changes
3. The colon is removed but the chrono font is too large, I suspect a conflict with #3521

Flight notes (When done a full flight): N/A

Media: 
Screenshot_21
Screenshot_22



Issues (If Any): Chrono font doesn't fit inside the chrono box
Steps to achieve the issue: Start the chrono with this PR and you can notice the difference

Overall Rating: To be improved
Conclusions of the testing: The colon does disappear when the chrono is stopped, however the chrono text is too large for the chrono itself.

**Comment by SergeySoprykin** [comment]
Resolved conflict.

**Comment by marcman86** [comment]
Name: marcman86#4907
Date of testing: 21.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3469
Tier of testing: 1
Changes to observe: Timer colon
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Turned on bat. and ext. power
3.) Tested timer MM:SS (Image1)

Media:


Image1

Issues: -

Overall Rating: Good

Conclusions of the testing: Conflict is resolved

Hope this helps :-)

**Comment by DavidEGTE** [comment]
Category: QA Trial
Name: David#2177
Date of testing: 03/03/2021
Version of the sim: 1.13.17.0
PR Tested: #3469
Tier of testing: 1
Changes to observe:
N/A

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. EXT PWR
2. OVH lights
3. BAT1&2 + FUEL PUMPS
4. check ANN LT (Inop.)
5. Start CHR (Inop)

Flight notes (When done a full flight):
N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
Microsoft Flight Simulator Screenshot 2021 03 03 - 22 33 23 96 (2)
Microsoft Flight Simulator Screenshot 2021 03 03 - 22 33 29 48 (2)

Issues (If Any): Button/Switches are Inop.

Steps to achieve the issue
>as above<

Overall Rating: N/A
Conclusions of the testing: Needs rework

**Comment by Benjozork** [comment]
@DavidEGTE you seem to not have the artifact installed.

You can ask for installation instructions in #qa-chat

**Comment by beheh** [comment]
@SergeySoprykin Could you please update the conflict in ` .github/CHANGELOG.md `? Then I can merge this.

**Pull request merged**
