### PR TITLE
feat: direct to with anticipated turn

### LINKED ISSUE #7016: ND line not drawn correctly after second direct to same point
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-07T09:44:59+00:00",
  "ref": "experimental",
  "sha": "472f73d68d6e97d0d4cb01a519c6fb6bf33b4544",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "experimental:472f73d6"
}
```

### Describe the bug

When you select a direct to a waypoint a second time, the ND line is not updated to the new T-P point. It seems like only the visual line is affected, but the aircraft is flying it correctly.

Wrong line on ND:
grafik

### Expected behavior

The line should be drawn from the new and now current T-P.

### Steps to reproduce

1. Spawn EDDM 26R, engines running, enter route EDDM-EDDM, route DM425,DM426,DM427,DM428,DM429, ILS26R.
2. Depart straight ahead, enter DCT DM425 (now the line is correctly drawn)
3. Switch back immediately to HDG mode and fly a few miles straight ahead on runway track
4. Enter again DCT DM425 (important that it's again the same waypoint)

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #7016 

## Screenshots (if necessary)

image
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Test various direct tos... waypoints in the flightplan, and not in the flight plan.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by FX5F** [comment]
Not sure what is calculated here. I am on the way from DM425 (previous waypoint) to DM429 (next waypoint). Setting a DCT to DM429 (which is exactly behind me).

grafik

**Comment by aguther** [comment]
Uploading 2022-04-28 17-47-28.mp4…

**Comment by FX5F** [comment]
> A wrong inital heading is used:
> 

Seems to be fixed with one of the updates above.

**Comment by FX5F** [comment]
I was flying in the opposite direction, entered a DCT to DM424, which was almost a 180 degrees turn and was working fine. When almost on course to DM424 i entered again a DCT to DM424. The calculation looked right, a new T-P point was set, but there was still the turn earlier drawn on the ND. Not sure if this is a correct behaviour.

grafik

**Comment by ShadowFrost3** [comment]
image
image

**Review by aguther — APPROVED** [review]
LGTM

**Pull request merged**
