### PR TITLE
fix: enable parking brake so aircraft won't move during pre flight

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #[issue_no]

## Summary of Changes

Enables parking brake in taxi.flt so the aircraft won't move in the pre-flight cinematics.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Spawn on runway, make sure the aircraft won't move.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
It's the most exciting part of the preflight cinematics! 😁

**Review by davidwalschots — APPROVED** [review]

**Comment by Saschl** [comment]
> It's the most exciting part of the preflight cinematics! 😁

I love being in the dirt! :D 

We could also let the MSFS AI steer our plane towards the runway👀

**Comment by 2hwk** [comment]
Just a note that this is a workaround and not a fix, it still will not work properly with the cinematic sequence but this is because we do not use the default MSFS parking brake system, and it is not possible to have the default parking brake system enabled and have custom parking brakes working. This is a sim issue and wont' be fixed.

**Comment by marcman86** [comment]
Quality Assurance Report

Discord: marcman86#4907
Object of testing: #7630
Tier of Testing: 1
Date: 9/12/2022

Testing Process:
- Spawned on runway 26R at EDDP
- Waited a bit in pre flight to spot if aircraft moves > it did not

Negatives: -

Testing Results: Passed
Conclusions: Works for me

Hope this helps :-)

**Comment by Hellfire-2345** [comment]
Quality Assurance Trainee Report 

Discord          : hellfire#7383
Object of testing: #7630
Tier of Testing  : 1
Date             : 14/12/2022

Testing Process: 
Runway 16R YSSY, had Parking brake on in preflight for some time and the aircraft didn't move 

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
aircraft worked well.

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7630
Tier of Testing  : 1
Date             : 11/01/2023

Testing Process: 
Spawn on runway, make sure the aircraft won't move. - **OK**

Negatives:       
N(A

Testing Results: 
Passed

Conclusions: 
LGTM

**Pull request merged**
