### PR TITLE
feat(bustie): Add animation, sounds, emission and SimVars to Elec pushbuttons

### PR DESCRIPTION
**Pull request by ramon54321**
**Summary of Changes**
This PR adds animation, sounds, emission and SimVar exposure to the Elec overhead panel buttons:

1. IDG Lock 1,2
2. IDG 1,2
3. BUS TIE
4. AC ESS FEED

The following SimVars have been exposed:

L:A32NX_ELEC_IDG1_FAULT
L:A32NX_ELEC_IDG1_TOGGLE
L:A32NX_ELEC_IDG2_FAULT
L:A32NX_ELEC_IDG2_TOGGLE
L:A32NX_ELEC_BUSTIE_TOGGLE
L:A32NX_ELEC_ACESSFEED_FAULT
L:A32NX_ELEC_ACESSFEED_TOGGLE
L:A32NX_ELEC_IDG1LOCK_TOGGLE
L:A32NX_ELEC_IDG2LOCK_TOGGLE

**Screenshots**
image

**Additional context**
This is needed for the electrical systems guys to hook into the buttons.

Discord username): Pineapple

### CODE REVIEW

**Comment by UncleClapton** [comment]
Hello and thanks for the PR! We are right now under a feature freeze until the mod is running stable under `1.8.3.0`. We'll merge this as soon as we can, but there may be conflicts at that point.

**Comment by Benjozork** [comment]
Can you also mention those simvars in `docs/a320-simvars.md` ? Thanks !

**Comment by camilo625** [comment]
Works as described

**Comment by armankir** [comment]
Tested, functional with no issues to report.

**Review by ThePilot916 — APPROVED** [review]
All good!

One suggestion would be to create a new template for common units(ex: IDGpush1/2, IDGlock1/2), that way you don't have write those many extra lines of code.

**Pull request merged**
