### PR TITLE
[CDU] Fix INIT-A CRZ FL/TEMP input

### LINKED ISSUE #2874: [BUG] MCDU - INIT A - can't enter CRZ FL/TEMP without FL using "/-<temp>" (minor issue)
**Mod Version**
latest fbw version
"built": "2021-01-04T09:05:01+00:00",
"actor": "Andreas Guther <andreas@guther.family>",

**Describe the bug**
In INIT A in the MCDU you can't just enter a new temperature with "/-<temp>". Only accepts full line with FL and Temp.

**To Reproduce**
1. Start C&D
2. Use SimBrief F-Plan
3. Go to INIT A try to change CRZ FL/TEMP with "/-40" 

**Expected behavior**
SHould accept and change temp only

**Actual behavior**
Not allowed

**References**
none

**Additional context**

Was this working before/when did the issue start occurring?
unknown

Is this a problem in the vanilla unmodded game?
n/a

Discord username Cdr_Maverick

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #2874

## Summary of Changes

- Fixed LSK6 input on INIT-A Page (CRZ FL/TMP)
- Allow M for minus (-) eg. M46 -> -46
- Fixed Manual override and auto calculation for temp
- Fixed Font size normal for manual temp insert and small for automatic temp
- Fixed formatting

## References

image
image
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Try to enter FL and TEMP or only FL or only TEMP.
Check for font change.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Lucky38i — COMMENTED** [review]
LGTM code wise

Also on a side note, what's the reason for casting the strings to explicit bools? This is a general curiosity nothing on the quality/correctness of the code.

**Review by Lucky38i — APPROVED** [review]

**Comment by MisterChocker** [comment]
> LGTM code wise
> 
> Also on a side note, what's the reason for casting the strings to explicit bools? This is a general curiosity nothing on the quality/correctness of the code.

It's a JS thing, as far as I learned.

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 9/1/21
Version of the sim: 1.12.13.0
PR Tested: #2897 
Object of test: MCDU INIT page

Testing technique: Loaded in and tried putting in the FL and temps
Steps you've made to test the Pull Request:
1. Loaded in
2. Tried putting in FL only (works)
3. Tried putting FL and temp (works)
4.Putting in only the temp
5.

Flight notes (If required):

Issues (If Any):  When putting in only the temp it would be better if it showed an error message (NOT ALLOWED) as at the moment it only disappears and looks like nothing happened
image

https://user-images.githubusercontent.com/70103461/104109031-c9a2fd80-52c1-11eb-8ffd-98e1b91bf4fc.mp4

Overall Rating: To be improved
Conclusions of the testing: An error message needs to be added when only putting the temperature in but the rest of the pr is good

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 10/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2879
Object of test: FL/TEMP on INIT-A page
Testing technique: Tryout

Steps you've made to test the Pull Request:

1. Spawned at VABB gates, C/D

2. Turned on battery, external power.

3. Entered INIT A details, inserted FL/TEMP in "FL350" format
image

4. Reloaded aircraft, repeated 1-3 with new format "FL350/-52", but received wrong output.
image

5. Reloaded aircraft, repeated 1-3 with new format "350"
image

6. Reloaded aircraft, repeated 1-3 with new format "FL350/M55", but received wrong output.
image

7. Reloaded aircraft, repeated 1-3 with new format "/-55" and "/M55", both assumed FL360 automatically instead of throwing error.
image

https://drive.google.com/file/d/16pjMBucYDd1a7jh1K4-6eYVusJSH_kA7/view?usp=sharing


Notes: Key here was to reload aircraft between each test to get the results. Could be an issue with an index being wrongly initialized (not sure if that's even the right terminology lol) but hope

Issues (If Any): In multiple test cases

Overall Rating: Needs improvement
Conclusions of the testing: There were multiple tests with different formats, and reloaded each time before testing. Needs a second look into it.

**Review by Benjozork — APPROVED** [review]
LGTM

**Pull request merged**
