### PR TITLE
Displays can be turned off & ECAM ignition more realistic

### PR DESCRIPTION
**Pull request by HorseGlass**
PFD, ND, EICAS displays can be turned off. ( Issue #165 )
Based on feedback ( #127 and 320 Sim Pilot's video ) ECAM Engine display is a bit more realistic. Left engine is using ingition A and only displays between N2% 18 and 55. Right engine is using ignition B and only displays between N2% 18 and 55

### CODE REVIEW

**Comment by lousybyte** [comment]
Some parts are reverting https://github.com/wpine215/msfs-a320neo/commit/43d4124ecb9abbcbdbee4e766709909a2eddcad4, is that intended or old base?

**Comment by wpine215** [comment]
Please do not merge this until the reversions are fixed, this will break the development branch.

**Comment by HorseGlass** [comment]
Sorry I noticed the issue. I fix it

**Comment by wpine215** [comment]
Still shows some commits being reverted

**Comment by HorseGlass** [comment]
I downloaded the newer version of the branch and replaced the old files. Is it ok now?

**Comment by AdenFlorian** [comment]
please resolve the merge conflicts

**Pull request closed without merging**
