### PR TITLE
fix(ecam): drop redundant CABIN READY memo

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

There are two places where the A320 has shown the cabin readiness in the past:
- the right column on the EWD, as a memo
- in the left column on the EWD as part of the T.O and LDG MEMO

After reviewing some references and footage, we think that CEOs originally only showed it in the right column, and eventually got an option to move it into the T.O/LDG MEMO instead. NEOs nowadays seem to always show it in the T.O/LDG MEMO, and the option does not really exist anymore.

In any case, showing the cabin readiness in two places seems nonsensical, and this PR drops the memo from the right column so that it's only showed in the T.O and LDG MEMO.

## References

https://discord.com/channels/738864299392630914/817470205260726322/885981452800491531

Video showing an A21N landing with the cabin readiness only in the LDG MEMO (not in the right column: https://www.youtube.com/watch?v=fR9iRUpbesU#t=5m58s

## Additional context

Discord username (if different from GitHub):

## Testing instructions

This is a trivial change and should barely require testing.

1. Spawn on the runway. Ensure that CABIN READY is only shown once in the left column of the EWD, not in the right.
2. Spawn on approach, and click the CABIN CALL in the OHP to make sure the cabin is ready. Observe the same as above (no CABIN READY in the right column)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
Verified with FWC data. LGTM

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5807 
Tier of Testing: 1
Date: 13/09/2021

**Testing Process:**
- Checked only left cabin memo on RW and Appr

RW
image

Appr
image

**Negatives:** N/A
**Testing Results:** Passed

**Comment by ewold** [comment]
Quality Assurance Trainee Report

Discord: E-wold#8195
Object of testing: #5807
Tier of Testing: 1
Date: 13/09/2021

Testing Process: 
Full flight EBBR/LPPT 
Checked memo and screens when taxiing to runway  
Checked memo and screens when approaching LPPT

Negatives: N/A
Testing Results: Passed

Conclusions: Full flight completed. worked as expected.

**Comment by beheh** [comment]
Thanks!

**Comment by TheSledge-SLEJ** [comment]
Excellent. Always bugged me! <3

**Pull request merged**
