### PR TITLE
Provide modern layout for instruments and port DCDU to react

### PR DESCRIPTION
**Pull request by devsnek**
## Summary of Changes

Create a system for writing instruments using more modern systems, then demonstrate it with the DCDU and react. Note that instruments do not have to use react, they are just provided a div (`renderElement`) that they can do whatever they want with.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
QA: only test if the DCDU interactivity still works properly

**Comment by Noxleee** [comment]
I just load up the sim with this PR for QA-Testing, but all screens are staying black.

**Comment by devsnek** [comment]
@Noxleee should be fixed

**Comment by Noxleee** [comment]
Name: Noxlee #7727
Date of testing: Current date 26/10/2020
Version of the sim: Version the/ tester uses
PR Tested: #1502
Object of test: DCDU

Testing technique: Try-out
Steps you've made to test the Pull Request:
1. Load up ac at EHEH
2. Ext. Power On
3. Check DCDU
    -> Self Test: OK
    -> Change brightness: OK
    -> Clicking every Button: OK
    -> Layout: OK
    -> Inop. Showing: Ok


Overall Rating: Good
Conclusions of the testing: Everything works like it should. Seems like the more modern system is working at least on the DCDU.

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 26/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1502 
Object of test: Confirm interactivity with DCDU is still the same after PR installed. 

Testing technique: Compare DCDU's (currently limited) functionality with latest dev version and with this PR installed
Steps you've made to test the Pull Request:

Start flight from C&D in ESGG
with latest dev version: check its limited functionality and use as benchmark for the PR testing

with PR: checking for the test mode and 'waiting for data' - that it's timely and appropriate. BRT and DIM functionality working. as well as the 'INOP' message when other buttons like 'PRINT' are pressed.

Flight notes

Startup: Everything normal

Taxi/Takeoff : N/A

Cruise: N/A

Descent/Landing: N/A

Shutdown: N/A

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: LGTM. Hopefully a platform for expanded functionality of DCDU. Thanks for your work.

**Comment by wpine215** [comment]
Can we reformat the JS in this PR to follow our existing convention of a 4 space indent? It's defined in the ESLint config I believe, not sure why the check passed.

**Comment by devsnek** [comment]
@wpine215 I installed a secondary eslint config which uses Airbnb and includes more rules for modern js stuff. airbnb defaults to 2 space indent but we can override it if you want.

**Comment by wpine215** [comment]
I'm not opinionated either way on 2 vs 4 spaces, but I believe we should be consistent with one or the other across all of our JS code, and it's probably easier to stick with since that's what's already used in the Asobo code.

**Comment by devsnek** [comment]
@wpine215 fixed

**Comment by Benjozork** [comment]
LGTM

**Pull request merged**
