### PR TITLE
[LIGHTS] General Improvements | Road Map

### PR DESCRIPTION
**Pull request by Snapmatics**
## Summary of Changes

#979 #1386 

**_Marked As Fixed_**
- [x] Lights bleed into the cockpit - Fixed a long time ago
- [x] Strobe Lights bleed in the cockpit - Fixed a long time ago.

**_New Features / Improvements_**
- [ ] Make DOME Lights realistic

## Additional context

_None_

Discord Username: `Snapmatics#0001`

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The `build.py` will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by lukecologne** [comment]
> * [ ]  Bleeding "Beacon" lights on sharklets

I've tried this by increasing the range and the strength of the top beacon light, but no luck. Maybe you can figure it out, it would look really nice

**Comment by Snapmatics** [comment]
> > * [ ]   Bleeding "Beacon" lights on sharklets
> 
> I've tried this by increasing the range and the strength of the top beacon light, but no luck. Maybe you can figure it out, it would look really nice

Yeah, I will give it a try.

**Comment by St54Kevin** [comment]
Rotating lights of the external GPU are also shining through the cockpit

**Comment by Snapmatics** [comment]
> > * [ ]   Bleeding "Beacon" lights on sharklets
> 
> I've tried this by increasing the range and the strength of the top beacon light, but no luck. Maybe you can figure it out, it would look really nice

Made it work but it's bleeding into the cabin. The lights improvements will continue after we implement the model. Until then we can't fix them.

**Comment by PuL9** [comment]
**Strobe Lights bleed in the cockpit**
Fixed it by deleting LIGHT_A32NX_StrobeDoubleInner.fx

**Pull request closed without merging**
