### PR TITLE
feat(model): add galley sound nodes

### PR DESCRIPTION
**Pull request by pepperoni505**
Fixes #[issue_no]

## Summary of Changes

This PR adds two new sound nodes: `SOUND_FWD_GALLEY` and `SOUND_AFT_GALLEY`
## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by davidwalschots — APPROVED** [review]

**Comment by St54Kevin** [comment]
How to test this? @pepperoni505

**Comment by hotshotp** [comment]
> How to test this? @pepperoni505 

You don't 😄 it's not ready to test, and it's for code review to see. No change for the user visible

**Comment by St54Kevin** [comment]
> > How to test this? @pepperoni505
> 
> You don't 😄 it's not ready to test, and it's for code review to see. No change for the user visible

image

**Comment by ErickSharp** [comment]
> > > How to test this? @pepperoni505
> > 
> > 
> > You don't 😄 it's not ready to test, and it's for code review to see. No change for the user visible
> 
> image

It's just an automated process. This pull request just adds additional sound nodes, not sounds that are fixed to those new sound nodes so you can't actually test it.

**Pull request merged**
