### PR TITLE
[FCU] Fix incrementing the QNH while in hPa mode

### LINKED ISSUE #138: When set to HPA multiple dial turns are required to increase/decrease by 1
When set to HPA multiple dial turns are required to increase/decrease by 1.

I assume you're always editing the dial in QNH and it's just translating the output? Resulting in requiring multiple turns of the dial to edit the HPA up or down by one.

### PR DESCRIPTION
**Pull request by lousybyte**
Fixes #138, #948

**Summary of Changes**

Changing the QNH while in hPa mode should properly increment/decrement by 1.

**Screenshots (if necessary)**

**References**

N/A

**Additional context**

QA: `build.py` required.

### CODE REVIEW

**Comment by Benjozork** [comment]
I think you are changing a common template, is that absolutely necessary ? We don't wanna affect other aircraft.

**Comment by lousybyte** [comment]
The file was integrated in the mod and there's a `<Case Value="A320">` enclosing the changed code, don't see how would affect other aircrafts.

**Comment by Benjozork** [comment]
Seems good then.

**Review by Carter633 — APPROVED** [review]
Name: Carter633 #1436
Date of testing: Current date 07/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1117

Testing technique: Quick flight from Cold and Dark
Steps you've made to test the Pull Request:
1. Spawned Cold & Dark, very short flight to test on ground and in flight
2. Changed hPa on the ground, increments worked nicely
3. Changed hPa in the air, increments worked nicely
4. No issues found

Overall Rating: Good
Conclusions of the testing: Works exactly as described

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: Current date 07/10/2020
Version of the sim: 1.9.3.0
PR Tested: #1117

Testing technique: Try-out
Steps you've made to test the Pull Request:

Spawned Cold & Dark changed hPaincrements

Overall Rating: Good / There is this one thing , where you do hear multiple (like 3) click per 1 unit change. Don't know if that is needed for the fix to work, or if it can be remedied.

Conclusions of the testing:  Otherwise working as documented, thank you for your work.

**Pull request merged**
