### PR TITLE
fix: Fix falsy SimVar values not being persisted properly

### LINKED ISSUE #5110: Refuel Time Option Not Saving
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-13T20:38:36+00:00",
  "ref": "master",
  "sha": "68dfae0ec88ef384acd87da748f52e66f59d9d7e",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

If left refuel time option to either "Instant" or "Fast" then the EFB will save to that option after exiting. Only one option will not save and that is the "Real" option. This occurred when I tried out the other options and afterwards my "Real" option would never save after exiting.

### Expected behavior

Refuel time options should save to Real as like it saves with Instant and Fast options. (If anything especially the "Real" refuel time option should save due to the fact that it will be used the most).

### Steps to reproduce

1. On the EFB, navigate to Dispatch -> Fuel
2. Set your refuel time to either Instant or Fast and afterwards set back to real
3. Go back to the main menu and load back in the aircraft (do not use the restart button as it's not the same as a complete exit)
4. Head back to EFB, navigate to Dispatch -> Fuel

### References (optional)

A video showing the bug

https://user-images.githubusercontent.com/72807945/121829934-df15bc80-cc91-11eb-844d-dfd33f4fbbdf.mp4

### Additional info (optional)

_No response_

### Discord Username (optional)

Aviation Spotter#9102

### PR DESCRIPTION
**Pull request by BlueberryKing**
Fixes #5110

## Summary of Changes
This addresses an issue where the value 0 would not be saved to persistent storage because it is considered falsy in JS. Consequently, when the refuel rate was set to "Real" on the EFB, this was encoded as a 0 and not saved properly, so when the plane was reloaded, the incorrect refuel rate was selected. Additionally, I noticed that the "PTU audible in cockpit" setting was also not saved properly due to the same issue. This has now been fixed.

## Additional context

Discord username (if different from GitHub): BlueberryKing#6641

## Testing instructions

1. Load up the airplane anywhere (cold & dark or not)
2. Set the refuel rate on the EFB to **something other than "Real"** and turn "PTU audible in cockpit" **on**.
3. Restart the flight and make sure both values were as you set them before reloading.
4. Now, set the refuel rate to **"Real"** and "PTU audible in cockpit" to **off**.
3. Restart the flight and make sure both values were as you set them before reloading.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by AviationSpotter** [comment]
Quality Assurance Trainee Report

Discord: Aviation Spotter#9102
Object of testing: #5118
Tier of Testing: 1
Date: 14/6/2021

Testing Process:

1. Spawned C&D
2. Set the refuel time option from Fast to Real (spawned with setting on fast)
3. Enabled "PTU audible in cockpit"
4. Backed out to main menu and loaded back in (C&D)
5. Disabled "PTU audible in cockpit"
6. Backed out to main menu and loaded back in (C&D)

Negatives: 

- Not sure if this PR broke the on switch for the PTU audible in cockpit option but it doesn't look right. (check media)

Testing Results: Passed
Conclusions: Other than the possible negative, this PR does as its titled correctly.
Media: 
OFF
Capture
ON
Capture2

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5118 
Tier of Testing: 1
Date: 15/06/2021

**Testing Process:**
- Load up the airplane anywhere (cold & dark or not)
- Set the refuel rate on the EFB to something other than "Real" and turn "PTU audible in cockpit" on.
- Restart the flight and make sure both values were as you set them before reloading.
- Now, set the refuel rate to "Real" and "PTU audible in cockpit" to off.
- Restart the flight and make sure both values were as you set them before reloading.

**Negatives:** 
- I can confirm the broken PTU button when ON. No other issues

**Testing Results:** Passed

**Comment by St54Kevin** [comment]
I can confirm the PTU button bug is also in the dev version. So unrelated

**Comment by BritishAvgeek** [comment]
Quality Assurance Tester
Discord: BritishAvgeek#1436
Object of testing: #5118
Tier of Testing: 1
Date: 15/06/2021

Testing Process:
1. Spawned C&D on Stand, set refuel rate on EFB something other than real - turned PTU audible ON
2. Restarted flight - both values were set as I had in the previous 'session'
3. Set refuel rate to Real and PTU Audible to OFF
4. Restarted flight - checked settings, Real and PTU Off saved

Negatives: N/A

Testing Results: Passed

**Pull request merged**
