### PR TITLE
[FCU] remember selected pressure mode when returning from Std mode

### PR DESCRIPTION
**Pull request by lhoenig**
## Summary of Changes

The air pressure selection knob has two modes for manual pressure: QNH and QFE. When returning from STD pressure to selected pressure, the selected mode is now remembered instead of defaulting to QFE.

## References

I was looking in the FCOM, looking on YouTube, but I couldn't find exact proof that the knob behaves this way. It absolutely makes sense to me though that it must be this way, it is even security critical for the knob to behave this way. Please, someone confirm this is actually the correct behaviour.

## Additional context

Discord username (if different from GitHub): lukas_#6140

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by lukecologne** [comment]
Tested and works nicely. One thing I don't really like is that you can't turn the knob when in STD. You should still be able to turn, it should just not affect baro setting

**Comment by lhoenig** [comment]
Thanks for the fast review! I'll check out the issue you describe!

**Comment by MisterChocker** [comment]
Don't forget changelog.

**Comment by lhoenig** [comment]
Changelog entry added, also for a previous PR where I forgot it.

**Comment by ChruutvoLuzi** [comment]
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: Current date 4.11.2020
Version of the sim: 1.10.8.0
PR Tested: #1750 
Object of test: (ECAM Page or Flight model or views or anything, what the PR modifies)

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. started C&D
2. Turned on bat and external power
3. tested the barometer

Flight notes

Startup: n/a

Taxi/Takeoff : n/a

Cruise: n/a

Descent/Landing : n/a

Shutdown: n/a

Issues (If Any): After switching back to barometric pressure, the Standard Values appear for a few milliseconds
Overall Rating: if it can be fixed then i would suggest to to that otherwise its good and works
Conclusions of the testing: Good

[Video](https://cdn.discordapp.com/attachments/314015589595086848/773624333355581440/Microsoft_Flight_Simulator_2020.11.04_-_20.05.46.01.mp4)

**Comment by lukecologne** [comment]
@lhoenig Did you find a fix for my issue? If not, consider setting this to draft so it doesn't get merged accidentally

**Comment by lhoenig** [comment]
@lukecologne I can't, apparently you need write access to set a PR to draft. I'll ask on Discord for someone to do it.

**Comment by lhoenig** [comment]
@ChruutvoLuzi thanks for the review, I'll try to fix that issue!

**Comment by lhoenig** [comment]
@ChruutvoLuzi @lukecologne I can happily say both of your issues were present in the base game and I was able to fix both! Please give it a try when you can.

**Comment by lukecologne** [comment]
Alright, tested again and works perfectly. LGTM

**Pull request merged**
