### PR TITLE
[MCDU/PFD/ND/ECAM] Update colors

### LINKED ISSUE #406: [BUG] Different Font on EICAS and PFD/ND
Stable 1.2.0

The font size and the green color type on PFD/ND and EICAS is not the same. The fonts aon the EICAS seems to be a litte bit smaller and darker, expecially the fonts for N1, EGT, N2 and FF are less readable.
dark

### LINKED ISSUE #944: [BUG] Shades of color on ECAMs are darker than PDF/ND
**Mod Version**

master

**Describe the bug**

The upper and lower ECAM use a darker shades of color for text and numbers than the PFD and ND use. This makes the ECAMs harder to read.

**To Reproduce**

1. Start at runway, turn brightnesses up

**Expected behavior**

see above

**Actual behavior**

see above

**References**

Current state in-sim, ECAM texts appear clearly darker:
img

Real airplane, ECAM texts appear at same shade/brightness as PFD/ND:
img
There seems to be some darkening happening towards the lower end of the upper ECAM, which I believe could be a camera (rolling shutter) problem.

**Additional context**

Was this working before/when did the issue start occurring? Always been this way I think.

Is this a problem in the vanilla unmodded game? Probably.

Discord username (if different from GitHub): Cobra#5370

Continuation of #867

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #406
Fixes #944

## Summary of Changes

Changes current colors of cyan, green and magenta to the one from mcdu preset.
- Changed display cyan and green to match MCDU.
- Changed mcdu magenta to match PFD/ND/ECAM.

### Before
image
image

### After
image
image
image
image
image
image

## References

https://www.youtube.com/watch?v=TEi-WX08ov8
image
image

## Additional context

image

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
Please provide screenshots.

**Review by TansyEliot — APPROVED** [review]
Great!

**Comment by MisterChocker** [comment]
I dunno git is trolling me with these changes in `A32NX/html_ui/CSS/A32NX_Display_Common.css`

**Comment by MisterChocker** [comment]
@Benjozork HELP ME PLS all these changes in the css files are not done by me. They happen automatically -.-

**Comment by Benjozork** [comment]
We use a 2-indent for CSS, this is fine.

**Comment by MisterChocker** [comment]
Waiting for #1604 to be merged.

**Comment by ChruutvoLuzi** [comment]
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: Current date 3.11.2020
Version of the sim: 1.10.8.0
PR Tested: #1672 
Object of test: (ECAM Page or Flight model or views or anything, what the PR modifies)

Testing technique: Try out
Steps you've made to test the Pull Request:
1.  Started Cold and Dark
2.  Fired up the aircraft
3.  Took off
4. Checked all Elements and ECAM pages
5.

Flight notes

Startup: Normal

Taxi/Takeoff : Normal

Cruise: Normal

Descent/Landing : Normal

Shutdown: Normal

Issues (If Any): 
Overall Rating: Works as described, one small issue
Conclusions of the testing: Everything runs as expected, however, it looks like TAT and SAT still uses the old green as well as the Status Normal text.

!https://media.discordapp.net/attachments/314015589595086848/773241213624647680/Desktop_Screenshot_2020.11.03_-_18.38.43.92.png?width=1204&height=677

!https://media.discordapp.net/attachments/314015589595086848/773241219979149352/Desktop_Screenshot_2020.11.03_-_18.43.21.38.png?width=1204&height=677

**Comment by MisterChocker** [comment]
> it looks like TAT and SAT still uses the old green as well as the Status Normal text.

Thanks for testing, will address this.

**Comment by MisterChocker** [comment]
@ChruutvoLuzi 
Replaced old green TAT and SAT color with new one.
Same for ECAM STATUS PAGE "Normal" text.

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: 3.11.2020
Version of the sim: 1.10.8.0
PR Tested: #1672
Object of test: Checking visual changes to the colours on various displays 

Testing technique: Try out
Steps you've made to test the Pull Request:

Spawn C&D and did normal flight from EKCH to ESGG. 

Observed the colours across MCDU PFD ND and ECAM displays and compared with previous versions of the mod through screenshots I had archived. Checked for consistency and accuracy. All good. 

Startup: Everything Normal

Taxi/Takeoff : Everything Normal

Cruise: Everything Normal

Descent/Landing : Everything Normal

Shutdown: Everything Normal

Issues (If Any):
Overall Rating: Good
Conclusions of the testing: LGTM. Saw the issue reported above - I double checked the issue with difference in colours reported on TAT and SAT text and that has been changed. All fine.

**Pull request merged**
