### PR TITLE
fix(utils:speeds): TO Vls config 3

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- TO Vls table was filled with "bad calculated numbers", this has been addressed now. (calculations by @donstim)

| GW | 40 | 45 | 50 | 55 | 60 | 65 | 70 | 75 | 80 |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Vls | 101 | 106 | 112 | 116 | 122 | 127 | 132 | 136 | 140 |

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Perform take offs with config 3, the V2 speed should not be below Vls anymore.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#5297
Date of testing: Current date 2/2/2021
Version of the sim: 1.12.13.0
PR Tested: #3291 
Tier of testing: 1
Changes to observe: Fixed conf 3 takeoffs, verify V2 and VLS speeds.

Testing technique: Circuits around YPKG
Steps you've made to test the Pull Request:
1. CONF3 takeoff at YPKG
2. Verify fixes.


Flight notes (When done a full flight): No issues.

Media: N/A

Issues (If Any): 

Overall Rating: Good
Conclusions of the testing: Works as described. Did 2 tests, thanks for the fix.

**Review by Lucky38i — APPROVED** [review]
LGTM code,wise

**Review by kberg93 — APPROVED** [review]
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 02/03/2021
Version of the sim: 1.12.13.0
PR Tested: #3291 
Tier of testing: 1
Changes to observe: V2 not being lower than VI

Testing technique: Takeoff in config 3

Steps you've made to test the Pull Request: 
1. Took off from TJSJ with config 3 all looked good

Flight notes (When done a full flight):

Media:

Issues (If Any): None.
Steps to achieve the issue:

Overall Rating: Good.

Conclusions of the testing: Works like described, nothing wrong noticed here.

**Review by kberg93 — APPROVED** [review]
Test number 2.

No issues found and it work nice like last test. Did a couple of take offs with different weight and it changed to be on the right side of the scale :) (before FlightSimmer7700 pointed out something at max payload. see attatched screenshot).

Waiting for MisterChocker response on disc :)

FlightSimulator_1zbGZICYfv

**Pull request merged**
