### PR TITLE
feat: force usage of modern flight model

### PR DESCRIPTION
**Pull request by aguther**
Fixes multiple issues of the past and potential in the future.

## Summary of Changes
This PR makes use of a new parameter that was introduced by SU4 to force the usage of the modern flight model independently of the user setting in the options.

In the past there have been many cases where legacy model was used by users and this setting will help to reduce this error.

### Expectation
Selection of any flight model in the MSFS options shall not affect the flight characteristics when using this PR. 

### Procedure
1. Using the current dev version of the mod, find a suitable scenario where use of any flight model other than modern will result in flight characteristics issues. (Typically, selection of CONF 2 in the dev version will cause all kinds of problems if the modern flight model is not being used.)
2. Confirm that the flight characteristics issues are not present when using this PR.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by ZigTag — COMMENTED** [review]
LGTM

**Review by crocket63 — APPROVED** [review]
Looks good! Let's get rid of that legacy model anyway!

**Review by crocket63 — APPROVED** [review]

**Review by ZigTag — APPROVED** [review]
LGTM

**Review by tracernz — APPROVED** [review]
#support-ops are going to ❤️ this.

**Comment by dragold** [comment]
Name: Mr.Blank#2638
Date of testing:28/05/21
Version of the sim: 1.16.2.0
PR Tested: #4930
Tier of testing: 1
Changes to observe:
Aileron droop and anti-droop

Testing technique: tryout
-Procedure
--Using the current dev version of the mod, find a suitable scenario where the use of any flight model other than modern will result in flight characteristics issues. (Typically, selection of CONF 2 in the dev version will cause all kinds of problems if the modern flight model is not being used.)
--Confirm that the flight characteristics issues are not present when using this PR.
-Methodology
--touch and goes landings
--touch full stop and goes
--SOP flight
--Observation for  Flap 2 behavior
--extreme flight envelope flight

Negatives: NIL
References(other):https://ptb.discord.com/channels/738864299392630914/754130199804772372/847898334168875028
Flight notes (When done a full flight): KBFM/32 DCT LURDE DCT CEW DCT PIGON DCT MVC DCT NOTNE DCT KBFM/36
Testing Results: (Passed)
Conclusions: All Observations where are expected..

**Pull request merged**
