### PR TITLE
fix(screens): Restore pixels on ISIS

### LINKED ISSUE #5637: Display pixelation not present in Standby Instrument
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-11T07:29:20+00:00",
  "ref": "master",
  "sha": "1c5335ec13ec6b7d29319db3371299da5e4fb880",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Moving close to the Standby Instrument does not show any display pixelation.

### Expected behavior

As it was before the react ISIS merge #5190 , where it would show the pixelation with the correct resolution as IRL.

### Steps to reproduce

1. Load into the plane
2. Move the camera close to the standby instrument and zoom in.
3.  Observe that the pixel effect is not present.

### References (optional)

https://media.discordapp.net/attachments/747571985831297145/864330512415981568/IMG_20210415_110629401.png?width=507&height=676

https://cdn.discordapp.com/attachments/758126266859388948/832179126055469106/VID_20210415_110204700.mp4

### Additional info (optional)

Tip: Use the old JS ISIS as a guide if you are implementing this (pull an older commit before #5190 was merged. 

### Discord Username (optional)

2Cas#1022

### PR DESCRIPTION
**Pull request by bouveng**
Fixes #5637

## Summary of Changes
Adds back pixels to ISIS screen that was lost during react conversion.

## Screenshots
Microsoft Flight Simulator 2021-08-16 06_14_15
<p align="right"><i>Before: no pixels</i></p>

Microsoft Flight Simulator 2021-08-16 06_13_34
<p align="right"><i>After: restored pixels (watch image at 100% to see effect properly)</i></p>

## Additional context

Discord username: @bouveng

## Testing instructions

1. Spawn
2. Move down and forwards as close to ISIS screen as possible.
3. Verify visible pixels
4. Verify that they disappear when moving back/zooming out

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5662
Tier of Testing: 1
Date: 16/08/2021

Testing Process:
- Loaded in on runway at EGCC. 
- Moved close to the ISIS display verified pixels - PASS
- Checked they dissapear when moving away - PASS
- Checked all other pixelated displays still working as expected and pixelated - PASS

Negatives: N/A
Testing Results: Passed

Conclusions: Does as intended, big fan of the pixels in general so great stuff! 

Media:
image

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #5662 
Tier of Testing: 1
Date: 16/8/21

Testing Process: Loaded in and checked the pixels
Negatives: N/A
Testing Results: Passed

Conclusions: LGTM good work!
Media:
image

**Comment by davidnorfolk96** [comment]
Quality Assurance Trainee Report

Discord: !davidn123#0001
Object of testing: 5637
Tier of Testing: 1
Date: 16/08/2021

Testing Process: 
1. Spawned in at LOWI on runway with engines running	

2. Move down and forwards as close to ISIS screen as possible.-PASS

3.Verify visible pixels- PASS

4. Verify that they disappear when moving back/zooming out-PASS

Negatives: N/A

Testing Results: Passed

Conclusions: Works as intended. Nothing to report in terms of breaks or glitches. 

Media:
Screenshot_6

**Comment by insubria** [comment]
these damn pixels. at various resolutions the resampling creates squares everywhere, it's better not to have all these interferences on the screen. look at all the artefacts in the photo here.
image

**Comment by Benjozork** [comment]
@insubria this place is not the place to aggressively complain, please keep your comments constructive and technical.

**Comment by TheSledge-SLEJ** [comment]
Beautiful. Nuances like this are really special. Thank you!

**Pull request merged**
