### PR TITLE
fix: remove invalid chars from atis report

### LINKED ISSUE #4627: Add comma char to MCDU font
**Is your feature request related to a problem? Please describe.**

The current font of the MCDU font does not include the char ','. This causes the char '&#9647;' to be displayed instead. 

**Describe the feature you'd like to see implemented**

Add the char ','.

## Additional context

Discord username (if different from GitHub): `ExampleWasTaken#0886`

### PR DESCRIPTION
**Pull request by ExampleWasTaken**
Refs #4627

## Summary of Changes

Just a simple PR that removes all commas from ATIS reports to prevent invalid characters.

## Screenshots (if necessary)

**Before:**
image

**After:**
image

## Additional context

Discord username (if different from GitHub): `ExampleWasTaken#0886`

## Testing instructions

* Request an ATIS that has commas in it (Possible ATIS can be found here: https://map.vatsim.net/atis) and make sure no invalid characters are displayed.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by beheh** [comment]
While I'm fine merging this, I would contest this actually fixes #4627. While this may fix the issue of the bad chars appearing, if commas are actually supported by the real MCDU and we're just missing them from the front, that issue is still outstanding even after this fix.

**Comment by ExampleWasTaken** [comment]
> 
> 
> While I'm fine with us merging this, I would contest this actually fixes #4627. While this may fix the issue of the bad chars appearing, if commas are actually supported by the real MCDU and we're just missing them from the front, that issue is still outstanding even after this "fix".

Good point. @tracernz suggested to just replace the comma. I understood that as "fix".

**Comment by beheh** [comment]
Okay. I've updated the PR description so it no longer will autoclose #4627 when this is merged.

**Review by MisterChocker — APPROVED** [review]

**Comment by TheSquirtingPantin** [comment]
Category: QA Tester
Name: Discord User Rémi#8871
Date of testing: Current date 13/05/2021
Version of the sim: V 1.15.8.0
PR Tested: #4788
Tier of testing: 1
Changes to observe: No incorrect chars on ATIS page

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. C/D at LFBO
2. Retrieve an ATIS via the MCDU AOC
3. Observe no incorrect chars displayed
 
Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any):NONE

Overall Rating: Good
Conclusions of the testing: LGTM. Retrieved ATIS not showing improper characters.

**Pull request merged**
