### PR TITLE
feat: add basic dcdu rigging

### PR DESCRIPTION
**Pull request by Benjozork**
## Summary of Changes

* Make both DCDU displays linked to an HTML template
* Add basic screen layout
* Add `SELF TEST IN PROGRESS`  to DCDUs when AC power comes online
* Add `Soon™️` indication for 3 seconds when pressing any of the buttons except the "BRT/DIM" switch
* Add ModelBehavior rigging for all buttons
* Make "BRT/DIM" switch change emissive intensity to 1 and 0.5 respectively 

## Screenshots (if necessary)

image

image

image

## References

N/A

## Additional context

N/A

Discord username (if different from GitHub): someperson#4953

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by stevex77** [comment]
Is it possible to fix these funny button labels from MS0+ MS0- POE+ POE- to MSG+MSG- PGE+ PGE- or is this a vanilla problem? :)

**Comment by Benjozork** [comment]
Thanks !

Sadly, due to our inability to edit the UV (the coordinates that define what part of the model uses what part of the texture) we cannot fix it. The "PO" part uses a common part of the texture also used by the "AIRPORT" button on the MCDU, and changing it yields this result:



(credit @Pleasure0102)

**Comment by stevex77** [comment]
Yup, this is really a "high level of optimization" they did. I'm familiar with 3D texturing, so this is double funny to me now. :) Thanks for explanation anyway.

**Comment by lukecologne** [comment]
grafik
Looks like it should say "Waiting for data (max 30 seconds)": https://www.youtube.com/watch?v=g_Mq0mI50GM&feature=emb_logo

**Comment by aviationenthusiast** [comment]
> 
> 
> grafik
> Looks like it should say "Waiting for data (max 30 seconds)": https://www.youtube.com/watch?v=g_Mq0mI50GM&feature=emb_logo

and according to the video, the displays shouldn't finish their self testing at the same time. and they go blank for a few seconds before displaying information.

**Comment by Benjozork** [comment]
@lukecologne will add, but the self test is also displayed. that video just doesn't show it.

@aviationenthusiast, I will implement that when I re-do the self-test for all displays.

**Comment by wpine215** [comment]
Also, right after the "Waiting for data" self test message disappears, another "No Data" message appears for about ~5 seconds, at least according to the video I saw.

vlc_bzTCYJT2xL

vlc_fXXWUsPqVi

Furthermore, I would wait until #1243 is merged in, so we can use that font/color definition here for consistency. I'm personally a fan of replacing "Soon" with "Not yet implemented" or "Inop", but we can put that up to a vote.

**Comment by aviationenthusiast** [comment]
> 
> 
> Also, right after the "Waiting for data" self test message disappears, another "No Data" message appears for about ~5 seconds, at least according to the video I saw.
> 
> vlc_bzTCYJT2xL
> 
> vlc_fXXWUsPqVi
> 
> Furthermore, I would wait until #1243 is merged in, so we can use that font/color definition here for consistency. I'm personally a fan of replacing "Soon" with "Not yet implemented" or "Inop", but we can put that up to a vote.

Soon™ is funnier thoughxD like the Blizzard meme.

**Comment by Benjozork** [comment]
@wpine215 the Soon™ is a joke, will be removed when PR ready for review (forgot to make it a draft !). I'm aware of the other screen, will add :)

**Comment by Benjozork** [comment]
@wpine215 @lukecologne added "WAITING FOR DATA".

**Comment by camilo625** [comment]
Name: Camilo625 #5575
Date of testing: Current date 13/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1252 

Testing technique: Spawn and test DCDU
Steps you've made to test the Pull Request:
1. Spawn C&D
2. Test DCDU

Overall Rating: Good
Conclusions of the testing: Works as described, although it seems textures are missing for me, don't know that could be the problem (i did use GitHub Desktop and run build.py)
image

**Comment by aviationenthusiast** [comment]
were the 

> 
> 
> Name: Camilo625 #5575
> Date of testing: Current date 13/10/2020
> Version of the sim: 1.9.5.0
> PR Tested: #1252
> 
> Testing technique: Spawn and test DCDU
> Steps you've made to test the Pull Request:
> 
>     1. Spawn C&D
> 
>     2. Test DCDU
> 
> 
> Overall Rating: Good
> Conclusions of the testing: Works as described, although it seems textures are missing for me, don't know what could be the problem (i did use GitHub Desktop and run build.py)
> image

same, unless the writing was intentionally removed.

**Comment by joshbxd514** [comment]
Name: Joshbxd515 #4978
Date of testing: 14/10/2020 12:39 UK
Version of the sim: 1.9.5.0
PR Tested: 1252

Testing technique: Start from C&D 

Steps you've made to test the Pull Request: Start from cold and dark and on gnd power.


Turn Bat 1&2 on and ground power.

Overall Rating: Good

Conclusions of the testing:  When i turned the batteries and ground power on it turned on and said.

Self test in progress max 10 seconds.

Then says self test.

once self test is completed it goes blank.

Textures on the buttons seem to be missing not sure if this is on purpose or not.

**Comment by camilo625** [comment]
> Name: Camilo625 #5575
> Date of testing: Current date 13/10/2020
> Version of the sim: 1.9.5.0
> PR Tested: #1252
> 
> Testing technique: Spawn and test DCDU
> Steps you've made to test the Pull Request:
> 
> 1. Spawn C&D
> 2. Test DCDU
> 
> Overall Rating: Good
> Conclusions of the testing: Works as described, although it seems textures are missing for me, don't know what could be the problem (i did use GitHub Desktop and run build.py)
> image

The textures are fine on #1322

**Pull request merged**
