### PR TITLE
fix: regressions for flight plan drawing throttling

### LINKED ISSUE #3379: [BUG] FP Page Distance not updating
**Mod Version**
LATEST DEV ,AND ALSO  AP CUSTOM BRANCH 

**Describe the bug**
The distance miles in the MCDU FP page its not moving , is stuck.

**To Reproduce**

1.Load  A FLIGHT PLAN
2.
3.

**Expected behavior**
get the exact miles , its not moving

**Actual behavior**
Stuck miles MCD FP PAGE

**References**

**Additional context**

Was this working before/when did the issue start occurring? NO , IT WAS WORKING YESTERDAY 

Is this a problem in the vanilla unmodded game? NO

Discord username (if different from GitHub):

### LINKED ISSUE #3380: [BUG] ND REFRESH VERY SLOW WHILE THE AC IS FLYING
**Mod Version**
LATEST DEV

**Describe the bug**
The aircraft , specially when its flying , the ND instead of refrsh while its moving nicely like it was doing it before , its like its jumping forward , I think its related because of the optimization performance on long fligh plan PR 

**To Reproduce**

1.LOAD A FP 
2. CHECK THE ND WHILE THE AIRCRAFT IS FLYING 
3.

**Expected behavior**
Work as it was working before performance optimizations PR nice refresh but with the same performance as the new PR 

**Actual behavior**
Refresh jumping , not refreshing nicely 

**References**

**Additional context**

Was this working before/when did the issue start occurring?yes , it started ocurring after performance optimization long flight plans PR

Is this a problem in the vanilla unmodded game?NO

Discord username (if different from GitHub):

### LINKED ISSUE #3397: [BUG] End of Flight Plan Not Appearing in MFD (After STAR Waypoints & Transition to Approach)
**Mod Version**
FBW Custom D/L 07-Feb 07:00am CDT

**Describe the bug**
When approaching end of route, the final waypoints of my route (after final STAR waypoint) are not visible.  Route appears to end (last 2/2 flights different airports).

**To Reproduce**
1. Build FPL using built in routing (example I used EFHK NUNT3P NUNTO DCT LOGNA DCT MILTA DCT DESON DCT VARUS DCT KEDUX DCT BALIT/K0817F360 DCT KUNER DCT BEZMI DCT XERBI DCT GOVEN/N0438F360 DCT BUKIG DCT KOBUS DCT RIKLU DCT MAREM DCT BAGMI BAGM5A).
2. Fly route via IFR.
3. Upon approaching BAGMI, note MFD route ends at MITNU (just prior to approach pattern beginning).  Remaining waypoints appear in MCDU (...LANDU, DM428, DM420, (DECEL), USR, BEGEN, FI08R, RW08R...) but do not appear in MFD.
4. Observe A/C turning towards RWY08R at end of mapped FPL.

**Expected behavior**
Entire route should be mapped and displayed in MFD, matching MCDU.

**Actual behavior**
Route ends too early in MFD map.

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Yes.

Is this a problem in the vanilla unmodded game?
No idea...guess not.

N/A

### PR DESCRIPTION
**Pull request by XSJoJo**
Fixes #3379
Fixes #3380 
Fixes #3397

## Summary of Changes
- Recompute distance and time on flight plan page periodically.
- Disable smoothing since it's buggy with higher refresh intervals.
- Reintroduce "tryAutoActivateApproach" as this seems needed for fplan to switch to approach waypoints.
- Update flight plan version when setting next waypoint.
- Properly load approach initially from MSFS.

## Screenshots (if necessary)
https://photos.app.goo.gl/DQtBviCVNQAEAGKa7

## References
n/a

## Additional context
Discord username (if different from GitHub): JoJo#7105

## Testing instructions
- Fly a flight plan, ensure that the ND functions correctly and that the flight plan line has a correct refresh rate.
- Ensure no other regressions.
- Go to FPLAN page and ensure ETA/Distance is updating.
- Fly a STAR with approach waypoints.

Note: When popping out the ND display (Alt Gr + Mouse Click), refresh rate seems to be unreasonably low. That is a separate issue that needs to be investigated, but is not related to this PR.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
Can we check #3397 as well ?

**Comment by XSJoJo** [comment]
> Can we check #3397 as well ?

Done - these issues should be fixed, but QA is definitely needed.

**Comment by mikecbr** [comment]
Cant Wait to try it out

**Comment by CaptainRafael** [comment]
Category: QA Tester/Trial
Name: Captain Rafael#0001
Date of testing: 07/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3396
Tier of testing: 1
Changes to observe:
Recompute distance and time on flight plan page periodically.
Disable smoothing since it's buggy with higher refresh intervals.
Reintroduce "tryAutoActivateApproach" as this seems needed for fplan to switch to approach waypoints.
Update flight plan version when setting next waypoint.

Testing technique: 

Steps you've made to test the Pull Request:
Spawn already a/c at LFKJ and loaded flp from simbrief : LFMN - LFKJ ( test the ND on the arrival )
Changed the simbrief to LFKJ-LFMN 
Try sid and stars in arc mode 
 
Flight notes (When done a full flight): N/A

Media:
image
image
image
image


Issues (If Any):  SID points not showing in LFMN - LFKJ ( note : I was spawned in LFKJ  and loaded from simbrief ) 
Distance to waypoint at some point corrected I was at 18.5nm the ND was saying 68.5 


Overall Rating: Needs improvement 
Conclusions of the testing: Flight plan refreshes as the video 
However needs improvement and more testing to know what's the issue

**Comment by XSJoJo** [comment]
>  SID points not showing in LFMN - LFKJ ( note : I was spawned in LFKJ and loaded from simbrief )
Distance to waypoint at some point corrected I was at 18.5nm the ND was saying 68.5

I think this is due to the fact that flight plan manager clears out the previous points from the flight plan already (without removing it on the ND, sigh) once the plane reached that waypoint. Can you retest when spawned in LFMN?

**Comment by XSJoJo** [comment]
Ok this should be ready for another QA round:
- Fixed issue when flight plan is loaded from MSFS UI.
- Fixed (DECEL) calculation updates. Note: It's still buggy for certain approaches, but that's not a regression.

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: 8/2/21
Version of the sim: 1.12.13.0
PR Tested: #3396 
Tier of testing: 2
Changes to observe:
Flight plan on ND

Testing technique: Did a full flight (3hr)
Steps you've made to test the Pull Request:
1. Loaded in
2. Took off
3. Did a star and approach

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.
Approach drawn with nothing missing
image

Issues (If Any): None
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: All good, sorry I did not check the ETA and distance updating and have not looked at the new changes just made but everything else seemed to work fine on my flight with no issues

**Comment by marinerhally** [comment]
Category: QA Tester
Name: Mariner Hally#0715
Date of testing: 09/02/2021
Version of the sim: 1.12.13.0
PR Tested: #3396
Tier of testing: 1
Changes to observe: Ensure that the ND functions correctly, Go to FPLAN page and ensure ETA/Distance is updating.

Testing technique: Flight
Steps you've made to test the Pull Request:
1. Spawned C/D at EGNT
2. Imported plan from simbrief and manually inserted SIDS/STARS.
3. Checked ND for flight plan line
4. Returned to main menu.
5. Loaded a flight back in from the MSFS UI. 
6. Flew this flight checking the ND on both sides for the flight plan line.
7. Landed at EGCC

Flight notes (When done a full flight):GIRL1T GIRLI P18 GASKO DCT SETEL ROSU2B

Media:

Issues (If Any): None, no issues loading in from the MSFS UI or Simbrief, both SIDS and STARS were shown, also the distance and time of arrival was correct too.

Overall Rating: Good

Conclusions of the testing: Flight plan was drawn in both scenarios.

**Comment by Benjozork** [comment]
Gonna wait for one more report on this one.

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 9.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3396 
Tier of testing: 2

### Changes to observe: Regressions for flight plan draw throttling

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned C/D at VOHS
2. Prepared for a regular IFR flight to VOMM
3. Set complete flightplan along with SID/STAR before departure
4. Normal departure and cruise, observed ND update rate
5. Observed distance update on the MCDU.
6. Tried DIRECT TO before entering STAR
7. Flightplan redraw without any issues. Aircraft entered STAR
8. Normal approach and landing at VOMM.

### Issues (If Any): None

### Overall Rating: Good

### Conclusions of the testing: Tried 2-3 different tests such as DIR to waypoint, switching between ND modes. Works well, refresh rate is ideal too. Good to go!

**Comment by stescouse** [comment]
Category: QA Tester
Name: stescouse#7271
Date of testing: 9.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3396
Tier of testing: 2

Testing technique: TryOut
Steps you've made to test the Pull Request:

1. Spawned C&D at SKBG
2. Imported flight plan direct from MSFS load screen not simbrief.  SKBG to SKBO.
3. Set SID and STAR 
4. Observed ND functioning correctly refreshing flight plan.
5. Checked distance was updating correctly.

gggg

jjjhh

6.  Changed runway and STAR and observed that flight plan was redrawn correctly.




Flight notes (If required: SKBG DCT SANLU DCT EJA UW91 ILSEV DCT TEMOB DCT BO804 DCT VULAM DCT SUR02 DCT SUR03 DCT AMVES DCT LOBEV DCT BO613 DCT SKBO.

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: performed as outlined in PR.

**Comment by omarsmak** [comment]
Can this be merged or it needs more tests?

**Comment by mikecbr** [comment]
> Can this be merged or it needs more tests?

I think @Benjozork  asked just for one more report and they have done 2 more , so I think it's done 🥰🥰

**Comment by mikecbr** [comment]
Miles on the MCDU working properly till the approach more less..... if you dont change anything in the MCDU like the runway or a DIR TO A WAYPOINT it stops suddeny counting , at least to me , it stopped at 75 nm i waited  5 mins and nothing , i changed to a DIR WAYPOINT and it solved the issue....  @Benjozork   @XSJoJo

**Pull request merged**
