### PR TITLE
fix: Added new tab to EFB "Realism"

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes

Added new tab to EFB "Realism" to move some options from Sim Options as the Sim Options page became too full and did not fit on e one page anymore.

This is a temporary solution until flyPadOS v3 is ready which will have a solution for this issue. 

## Screenshots (if necessary)
image
image

## References
N/A

Discord username (if different from GitHub): Cdr_Maverick#6475

## Testing instructions

- Test all options on the pages "Sim Options" and "Realism".
- Spot test other options on other pages. 
- Check docs page: 
  - https://github.com/flybywiresim/docs/pull/360
  - https://docs-git-fork-frankkopp-updt-efb-settings-flybywire.vercel.app/fbw-a32nx/feature-guides/flyPad/settings/#sim-options

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Saschl — APPROVED** [review]

**Comment by ShadowFrost3** [comment]
Quality Assurance Tester Report


Object of testing: #6382 
Tier of Testing:1
Date: 19/12/2021

Testing Process: 
C&D
Test options on Sim Objects and Realism page
ADIRS instant - checked
ADIRS fast - checked
ADIRS real - checked - takes forever so I assume is working
DMC instant - checked
DMC fast - checked
DMC real - checked
Boarding instant - checked
Boarding fast - checked
Boarding real - checked
Default Baro auto - checked
Default Baro in Hg - checked
Default Baro hPa - checked
Detents menu - checked
Dynamic Registration enabled - checked
Dynamic Registration disabled - checked

Spot checks in other pages 
Audio page (fully)- checked
Aircraft config page (fully) - checked - see notes 
Flypad page (fully) - checked


Separate tiller disabled - not checked (flight equipment not setup)
Separate tiller enabled - not checked 
Sync MSFS flight plan - not checked 

Negatives:
Portable devices switch? - unsure on its operation - not switching no smoking switch to portable devices but I don't know its true purpose so feel free to inform me
Testing Results: Passed

Conclusions: LGTM

**Comment by jcalor** [comment]
Quality Assurance Tester Report

Discord          : Calo#6816
Object of testing: #6382 
Tier of Testing  : 1
Date             : 21/12/2021

Testing Process: 

- Tested all modified options are working well - checked

Negatives:       

- On documentation - Realism, there´s 2 options regarding MCDU but no MCDU option are shown on Realism page

image
image


Testing Results: Passed (not passed for Docs)

Conclusions: Looks good, check documentation.

**Comment by frankkopp** [comment]
> Quality Assurance Tester Report

> Conclusions: Looks good, check documentation.

Thanks for checking. Will fix docs asap.

**Comment by frankkopp** [comment]
> Conclusions: Looks good, check documentation.

Issue was indeed that I accidently removed these options - they should be back in now. 
Image on docs will be updated.

**Comment by frankkopp** [comment]
https://docs-git-fork-frankkopp-updt-efb-settings-flybywire.vercel.app/fbw-a32nx/feature-guides/flyPad/settings/

**Comment by tareksabet** [comment]
# Quality Assurance Tester Report

Discord          : tarek_sabet#7946
Object of testing: #6382 
Date             : 22/12/2021

# Testing Process: 
## C&D :
### Realism Tab: 
* ADIRS: Instant (Passed) - Fast (Passed) - Real (Passed)
* DMC: Instant (Passed) - Fast (Passed) - Real (Passed0
* Passengers: Instant (Passed) - Fast (Passed) - Real (Passed)
* MCDU Keyboard Input: (Passed)
* Separate Tiller: (Passed)
### Sim options: 
* Checked all the options (Passed)
### Aircraft configuration: 
* Checked all the options (Passed)


# Negatives:       
### N/A

# Testing Results: 
### Passed

# Conclusions: 
Working as intended to be, LGTM, great work Mav 👏 Also I read the docs page all good 😄 
# Media:     
Microsoft Flight Simulator Screenshot 2021 12 22 - 04 08 42 94

**Comment by demonguy** [comment]
Why i cannot find realism settings in my EFB?
I cannot enable "Seperate tiller from rudder input". And cannot use my joystick to controll nose wheel

{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Comment by NUTTTTTTTT** [comment]
> Why i cannot find realism settings in my EFB? I cannot enable "Seperate tiller from rudder input". And cannot use my joystick to controll nose wheel
> 
> { "built": "2022-01-08T01:22:50+00:00", "ref": "v0.7.4", "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b", "actor": "Benjozork", "event_name": "manual" }

This feature is only available in the Development and Experimental versions

**Pull request merged**
