### PR TITLE
fix(sound): fix typos in sound.xml

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

Fix some minor typos in sound.xml that were flagged by the MSFS console. This may result in some unexpected sound, as I'm not sure how these sounds were interpreted previously. They may also just work fine.

## References

image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Need test instructions

**Comment by beheh** [comment]
I'd like to defer to @hotshotp on that. The sounds this touches are things like packs and vents and the fuel pump, but I'm not sure what would differentiate a successful test outcome from a failed one. We can go with "sounds as expected", but then I'd definitely want Boris to test this.

**Review by hotshotp — APPROVED** [review]
LGTM

**Comment by beheh** [comment]
@hotshotp Anything specific you want tested? Or do you think this can be merged as-is?

**Comment by hotshotp** [comment]
> @hotshotp Anything specific you want tested? Or do you think this can be merged as-is?

I'd say just merge

**Pull request merged**
