### PR TITLE
fix: port fuel system changes

### LINKED ISSUE #2609: Issues noted after MSFS Update: CANNOT START APU
**.5 Stable**

**Describe the bug**
#2 Pumps will not depress after MSFS update 1.12.

**To Reproduce**
1. Power up procedure start.
2. Clear pump white lights on O/H panel.
3. Press #2 switches (all three).

**Expected behavior**
White light should de-illuminate.

**Actual behavior**
Remains OFF with white light.

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Was working prior to MSFS update 1.12.

Is this a problem in the vanilla unmodded game?
Don't know but due to MSFS update changes no doubt.

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

### LINKED ISSUE #2610: [BUG] Fuel Pump won't start
**Mod Version**

Dev + Stable from the installer

**Describe the bug**

When I try to turn on the fuel pumps L TK PUMP 2, CTR TK PUMP 2 and R TK PUMP 2 stay off on the panel and on the ecam.

**To Reproduce**

1. Start the sim with an aircraft in cold and dark.
2. Switch BAT 1+2, EXT PWR, etc. on.
3. Switch all fuel pumps on.
4. The three from above will stay off.

**Expected behavior**

The white lights should turn off like the other pump switches.

**Actual behavior**

 L TK PUMP 2, CTR TK PUMP 2 and R TK PUMP 2 stay off.

**References**

Video will follow.

**Additional context**

Was this working before/when did the issue start occurring?
After an update of A32NX and FS2020.

Is this a problem in the vanilla unmodded game?
Not in general/I cannot undo the updates

Discord username (if different from GitHub):
xander

### PR DESCRIPTION
**Pull request by Benjozork**
Fixes #2610
Fixes #2609

## Summary of Changes

* Fixed APU and engines not starting

Discord username (if different from GitHub): someperson#4953

## Testing instructions

* Try to start/shutdown engines and APU in different situations
* Try to complete flights (use as many features as possible !)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by lukecologne — APPROVED** [review]

**Comment by maxpull82** [comment]
dopo l'aggiornamento di oggi la versione di msfs, l'A320 neo non funziona piu' a motori spenti l'apu non si avvia e se fai la prova in pista a motori accesi si chiude il simulatore. disinstallando l'aereo funziona normalmente.

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 22.12.2020
Version of the sim: 1.12.13
PR Tested: #2611
Object of test:  fix: port fuel system changes

Testing technique: Tested APU and Enigne start and shutdown. Full C&D
Steps you've made to test the Pull Request:
1. Started C&D
2. Started Apu and Engines
3. shutdown the engine while taxiing and restarted
4. took off
5. started APU.
6. Shut 1 Engines Down and restarted it. Shut both engines Down and restarted it.
7. Shut APU down
8. landed
9. Did 6. again
Flight notes (If required):

Issues (If Any): had a few A/P issues where the Plane took the nose up to 30 degrees but nothing related to this pr
Overall Rating: Good
Conclusions of the testing: Works good. Thanks for the fast fix

**Comment by danbw9** [comment]
Category: QA Test
Name: danbw9#7028
Date of testing: 22.12.2020
Version of the sim: 1.12.13
PR Tested: #2611
Object of test: fix: port fuel system changes

Testing technique: Tested APU and Enigne start and shutdown. Full flight from EKCH to ESGG. Normal procedures and playing with extra features. Compare previous behaviour before PR install to after.
Steps you've made to test the Pull Request: 

Tested multiple scenarios:
- C&D for full flight
- once in C&D, check cockpit indications for fuel/engine info
- Spawn on RWY
- Spawn on approach

Did a full normal flight spawned from C&D, followed normal procedures. At different stages of flight monitored the fuel pumps indications on overhead and fuel SD page as well as check ENG primary and secondary indications. No abnormals related to these two specifically. 

Confirmed that spawning on RWY does not produce CTD sometimes (probably created before by some file conflict before where it could not start engines)

Spawn on RWY and completed normal landing with no issues.

Issues (If Any): None. 
Overall Rating: Good
Conclusions of the testing: LGTM. Followed instructions above and checked against the bugs from before this PR. Thanks a lot Ben for your work on this.

**Comment by Lazarus320** [comment]
Category: QA Test
Name: Lazarus#4286
Date of testing: 22/12/2020
Version of the sim: 1.12.13
PR Tested: #2611
Object of test: fix: port fuel system changes

Testing technique: Tested APU and engine startup and shutdown during a short flight from HESH to HECA.  
Steps you've made to test the Pull Request:
1.C&D for full flight
2. Tested apu and fuel pumps functionality 
3. Flight as usual 
4. Turned on apu after touchdown 
5. Taxi to gate and turned off engines 

Issues (If Any): None.
Overall Rating: Good
Conclusions of the testing: LGTM great work!

**Comment by Road-to-Hell9** [comment]
Category: QA Tester
Name: Road_to_Hell9#1111
Date of testing: 22/12/2020
Version of the sim: 22/12/2020 After 21h00 UTC
PR Tested: #2611
Object of test: fix: port fuel system changes

Testing technique: Tested APU Startup
Steps you've made to test the Pull Request:
1.Cold start LOWW
2. Started APU
3. FP and usual protocol in checklist
4.
5. 

Issues (If Any): None.
Overall Rating: To be improved
Conclusions of the testing: Doesn't work as intended, APU doesn't start and Pumps No°2 do not turn on

**Comment by NickFarin** [comment]
Category: QA Tester
Name: Discord User: Nick F[Z+8] #5327
Date of testing: Current date DD/MM/YYYY
Version of the sim: 1.12.13.0
PR Tested: #2611 
Object of test: port fuel system changes

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned in at RPLL
2. started the plane from cold and dark
3. started the engines

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Test went normal. APU and Engine starts are normal

**Comment by ErickSharp** [comment]
Category: QA Tester
Name: 🎄🎅Erick🎄🎅 [Z-5]#6484
Date of testing: Current date 22/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2611 
Object of test: APU and engine startup 

Testing technique: Followed a typical flight, monitoring both APU and Engine functionality, as well as testing to see if other features were affected by changes in PR. [KLAX-KSFO]
Steps you've made to test the Pull Request:
1. Spawned in at gate (Cold and dark)
2. Prepared cockpit normally
3. Started APU normally
4. Monitored APU startup, as well as other ECAM pages for anomalies that were present before the PR
5. Started engines after APU Bleed available, monitoring engine startup.
6. Throughout the duration of the flight, I tested various systems to ensure that they were still operational.

Flight notes (If required):
Flight Plan (Simbrief): SUMMR1 STOKD DCT SERFR SERFR3
Issues (If Any): **NONE**
Overall Rating: Good
Conclusions of the testing: All issues properly addressed in PR, with no unexpected negative effects on other flight systems. READY FOR IMMEDIATE MERGER.

**Comment by NickFarin** [comment]
Category: QA Tester
Name: Discord User: Nick F[Z+8] #5327
Date of testing: 23/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2611
Object of test: port fuel system changes

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:

1. Spawned in at RPLL
2. started the plane from cold and dark
3. started the engines
4. performed traffic patterns
Flight notes (If required):

Issues (If Any):
Overall Rating: Good
Conclusions of the testing: Test went normal. APU and Engine starts are normal

**Comment by NickFarin** [comment]
Category: QA Tester
Name: Discord User: Nick F[Z+8] #5327
Date of testing: 23/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2611
Object of test: port fuel system changes

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:

1. Spawned in at RPLL
2. started the plane from cold and dark
3. started the engines
4. performed traffic patterns

Flight notes (If required):
Issues (If Any):
Overall Rating: Good
Conclusions of the testing: Test went normal. APU and Engine starts are normal

**Comment by marinerhally** [comment]
Category: QA Tester
Name: Discord User Mariner Hally#0715
Date of testing: Current date 22/12/2020
Version of the sim: 1.12.13.0
PR Tested: #2611
Object of test: Test engine start and APU start

Testing technique: Full flight from C/D
Steps you've made to test the Pull Request:
1. Spawned C/D EGNM
2. Set up flight (Programming MCDU,Starting APU etc)
3. Pushback and Started engines
4. Completed flight to EGKK halfway through shutdown engine 2 and restarted and coppied process for engine 1
5. Landed at EGKK
6. Started APU on taxi
7. Shutdown engines and APU at parking

Flight notes (If required):

Issues (If Any): None engines and apu started when requested
Overall Rating: Good
Conclusions of the testing: Worked well no issues.

**Pull request merged**
