### PR TITLE
build: use fragmenter for optimised distribution

### PR DESCRIPTION
**Pull request by nistei**
## Summary of Changes
After the normal build process, the artifact gets split up into multiple, smaller zip files and uploaded to a new CDN.

## Screenshots (if necessary)
N/A

## References
N/A

## Additional context

Discord username (if different from GitHub): nistei#1362

## Testing instructions

* Make sure the aircraft loads and functions (download the artiffact)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by nistei** [comment]
Using the PR action to test the upload to the new CDN since the new CDN isn't used in a released version of the installer.
This is also the reason this PR is not a draft (no actions) but rather has the label `Do not merge.`

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Samueleonard** [comment]
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: 03/03/2021
Version of the sim: 1.13.17.0
PR Tested: #3773
Tier of testing: 1
Changes to observe: check acft still works after fragmenter
Testing technique: Tryout

Steps you've made to test the Pull Request:
1. loaded onto rwy, engines running
2. checked all buttons + sounds still work
3. checked night lighting
4. filled in MCDU, simbrief import, check all pages
5. did circuit, landed and shutdown

Flight notes (When done a full flight):
N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A

Issues (If Any): Write any issues
none - acft still works as expected

Steps to achieve the issue
N/A

Overall Rating: Good

Conclusions of the testing: 
LGTM - everything works

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 03/03/2021
Version of the sim: 1.13.17.0
PR Tested: #3773 
Tier of testing: 1
Changes to observe: New packaging, check aircraft functions still work

Testing technique: No actual flight due to time issues on my side
Steps you've made to test the Pull Request:
1. Spawned C&D at EGKK
2. Loaded flightplan from simbrief EGKK - LEPA
3. Went through usual set up with power, pumps, configuration of MCDU etc including performance page. Input SID into the flight plan too
4. Pushback and Start - checked lights, seatbelt signs etc, checked overhead panel lights, switches and changed Radio and Transponder values
5. Taxiied about briefly and tuned the Mayfield and Midhurst VORs to see if they tuned in

Flight notes (When done a full flight): N/A - ended test shortly after a brief taxi due to time issues on my end. Unable to do full flight
Media: N/A

Issues (If Any): None found in what I tested

Overall Rating: Good
Conclusions of the testing: I found no issues in the limited test described above

**Comment by DavidEGTE** [comment]
Category: QA Trial
Name: David#2177
Date of testing: 03/03/2021
Version of the sim: 1.13.17.0
PR Tested: #3773
Tier of testing: 1
Changes to observe: Make sure the aircraft loads and functions
Testing technique: Tryout

Steps you've made to test the Pull Request:
1. Spawned C&D at LFPG
2. Checked lighting, checked most of the common buttons and functions I use, making sure APU works.
3. Loaded manually the flightplan for a circuit test at LFPG via MCDU
4. Did circuit flight
5. Shutdown

Flight notes (When done a full flight):
N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A

Issues (If Any): Worked as if it was new!

Overall Rating: Good
Conclusions of the testing: Everything works

**Pull request merged**
