### PR TITLE
fix: Strobe lights tooltip

### LINKED ISSUE #5258: Incorrect Strobe Light Tooltips
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-01T14:38:08+00:00",
  "ref": "master",
  "sha": "2a23f44e7faf992b6345bbae8bae43ab2031e022",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

The strobe light tooltips are incorrect. Hovering over the off action shows the turn on tooltip and hovering over the on action shows the turn off tooltip.

### Expected behavior

Hovering over the off action should show the turn off tooltip and same for hovering over the on action should show the turn on tooltip.

### Steps to reproduce

1. Spawn (anywhere of choice)
2. Hover over strobe light off and on tooltips

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Aviation Spotter#9102

### PR DESCRIPTION
**Pull request by AviationSpotter**
Fixes #5258

## Summary of Changes

This PR fixes the strobe light tooltip to give the correct positions.
## Screenshots (if necessary)

Capture
## Additional context

Discord username (if different from GitHub): Aviation Spotter#9102

## Testing instructions

1. Spawn (anywhere of choice)
2. Verify strobe light tooltips are correct
3. Verify other language settings do not have those tooltips broken (although they aren't translated)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by bouveng — CHANGES_REQUESTED** [review]
Could you perhaps swap them around for the other languages we support as well?

**Comment by AviationSpotter** [comment]
> Could you perhaps swap them around for the other languages we support as well?

@bouveng Will probably just keep the changes within the en-US. I'm not an expert at translating and wouldn't want to translate incorrectly.

**Review by Benjozork — APPROVED** [review]

**Comment by ErickSharp** [comment]
Remember to swap both `COCKPIT.TOOLTIPS.STROBE_LIGHT_OFF` with `COCKPIT.TOOLTIPS.STROBE_LIGHT_ON` in A320_NEO_INTERIOR.xml

**Comment by AviationSpotter** [comment]
> Remember to swap `COCKPIT.TOOLTIPS.STROBE_LIGHT_OFF` with `COCKPIT.TOOLTIPS.STROBE_LIGHT_ON` in A320_NEO_INTERIOR.xml

@ErickSharp I should have just swapped those instead. Sorry @bouveng I misunderstood your suggestion!

**Comment by ErickSharp** [comment]
> > Remember to swap `COCKPIT.TOOLTIPS.STROBE_LIGHT_OFF` with `COCKPIT.TOOLTIPS.STROBE_LIGHT_ON` in A320_NEO_INTERIOR.xml
> 
> @ErickSharp I should have just swapped those instead. Sorry @bouveng I misunderstood your suggestion!

Much better solution haha 🤤

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5259 
Tier of Testing: 1
Date: 05/07/2021

**Testing Process:**
1. Loaded in and checked Strobe Light tooltip

**Negatives:** N/A
**Testing Results:** Passed

**Pull request merged**
