### PR TITLE
fix(ovhd): correct decals on ovhd buttons

### LINKED ISSUE #4204: EVAC COMMAND lights does not illuminate
**Mod Version**
master

**Describe the bug**
The EVAC COMMAND button seems to not work as intended. The alarm sounds, but lights do not illuminate. The push button when pressed moves outward instead of inward.

**To Reproduce**
1. Remove the COMMAND guard.
2. Press the COMMAND button.

**Expected behavior**

- [ ] 1. The COMMAND button's ON light turns on.
- [ ] 2. The COMMAND button's EVAC light flashes in red.
- [x] 3. The COMMAND button is pushed inward.

**Actual behavior**

1. The COMMAND button's ON light does not turn on.
2. The COMMAND button's EVAC light does not turn on. 
3. ~~The COMMAND button is pushed outward.~~

**References**
The button in the pressed state:

image

Information on the intended behaviour of the button:

image

Discord username (if different from GitHub): SjotgunSjonnie#9623

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]
All Korry switch issues of https://github.com/flybywiresim/a32nx/issues/956
Fixes #4204
Some of #1410

## Summary of Changes

- See #956 for references, all Korry switches should be fixed
  - POG effort by @tyler58546 on creating the missing decals in the model!
- PA IN USE button illuminates during "cabin crew seats for takeoff" announcement
- EVAC and EMER call buttons flash when active
- EVAC HORN SHUT OFF button is no longer permanent

## Screenshots (if necessary)

Before OVHD:
image

After:
image

OVHD maint panel before:
image

After:
image

Before glareshield (note no ATC MSG lights):
image

After:
image

Cockpit door/engine indicators before (engine lights MIA):
image
After:
image

## References

https://github.com/flybywiresim/a32nx/issues/956

## Additional context

I gave this a quick test with #4898 merged on top, and all was well. 👍 

Discord username (if different from GitHub):

## Testing instructions

Check fixes mentioned in summary above.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by davidwalschots** [comment]
Fixes #4204.

**Review by ko-zone — APPROVED** [review]
LGTM

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #4929
Tier of Testing: 1
Date: 28.5.2021

Testing Process: visually compared panels in sim with screenshots in PR 

Negatives: GEN 1 Line seems to have FAULT and SMOKE and also OFF label is skewed
image

Testing Results: Not Passed

Conclusions: Otherwise all other buttons seem correct as per PR

**Comment by tracernz** [comment]
> 
> 
> Quality Assurance Tester Report
> 
> Discord: Cdr_Maverick#6475
> Object of testing: #4929
> Tier of Testing: 1
> Date: 28.5.2021
> 
> Testing Process: visually compared panels in sim with screenshots in PR
> 
> Negatives: GEN 1 Line seems to have FAULT and SMOKE and also OFF label is skewed
> image
> 
> Testing Results: Not Passed
> 
> Conclusions: Otherwise all other buttons seem correct as per PR

Good pickup! I had forgotten to delete an unneeded layer underneath the new SMOKE. Regarding the OFF label skew, most (all?) of the off decals are skewed on the side panels. This is a defect with the 3D model and I don't intend to fix it through the methods we're currently using. It can be fixed one day when we can properly edit the model in blender.

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #4929
Tier of Testing: 1
Date: 28.5.2021

Testing Process: Retest - visually compared panels in sim with screenshots in PR

Negatives: None
Testing Results: Passed
Conclusions: LGTM

**Comment by Mack674** [comment]
Quality Assurance Tester Report

Object of testing: PR #4929
Tier of Testing: 1
Date: 28.05.2021

Testing Process: 
- Spawned C&D at gate
- Compared panels with that from screenshots

Negatives: Gen 1 line button is corrupted: fault and smoke are on the same place (shown on last screenshot)
Testing Results: Passed

Conclusions: Almost all decals are correct, even it added more realism to the mod. Great work!
Media: 
Decals_1
Decals_2
Decals_3
Decals_4
Decals_5
Decals_6
Decals_7
Decals_8
Decals_9!

**Comment by tracernz** [comment]
> Negatives: Gen 1 line button is corrupted: fault and smoke are on the same place (shown on last screenshot)
> Testing Results: Passed
> 

Are you sure you're running the latest PR artifacts? This should have been fixed with the push 2 hours before your test report.

**Comment by St54Kevin** [comment]
As this PR is about the lit button labels, what about the CTR TK Pump 2 Fault light? I can see in the screenshots its missing. Maybe also able to fix with this PR?

**Comment by scoopscode** [comment]
Quality Assurance Tester Report

Object of testing: #4929
Tier of Testing: 1
Date: 30/05/2021

Testing Process:
- Spawned C&D at gate
- Turned on aircraft with GPU and Battery
- Switched ANN LT to TEST and observed entire cockpit decals
Negatives: None
Testing Results: Passed

Conclusions: Looks great and good to merge!
Media:
Screenshot (60)
Screenshot (61)
Screenshot (62)
Screenshot (63)

**Comment by DavidEGTE** [comment]
Quality Assurance Trainee Report

Discord: David#2177
Object of testing: #4929
Tier of Testing: 1
Date: 30/05/2021

Testing Process: 
- Spawned C&D at gate
- Turned on aircraft with GPU and Battery
- Switched ANN LT to TEST and observed entire cockpit decals

Negatives: N/A
Testing Results: Passed

Conclusions: LGTM
Media:
Microsoft Flight Simulator 30_05_2021 19_36_57
Microsoft Flight Simulator 30_05_2021 19_40_23
Microsoft Flight Simulator 30_05_2021 19_40_30
Microsoft Flight Simulator 30_05_2021 19_40_38
Microsoft Flight Simulator 30_05_2021 19_40_42

**Comment by dragold** [comment]
Category: QA Tester trainee
Name: Mr.Blank#2638
Date of testing:05/30/2021
Version of the sim: 1.16.2.0
PR Tested: #4929
Tier of testing: 1

Changes to observe:
-See #956 for references, all Korry switches should be fixed
--POG effort by @tyler58546 on creating the missing decals in the model!
-PA IN USE button illuminates during the "cabin crew seats for takeoff" announcement
-EVAC and EMER call buttons flash when active
-EVAC HORN SHUT OFF button is no longer permanent
-then following bug fixes

Testing technique: Tryout

Methodology:
-Turned on aircraft with Battery and GPU
-Switched ANN LT to TEST and observed entire cockpit decals
-Compared panels with that of IRL images of the panels 
Negatives: NIL
Testing Results: Passed

Conclusions: All observations whereas expected

**Pull request merged**
