### PR TITLE
Redesigned standby instrument

### PR DESCRIPTION
**Pull request by jakluk**
## Summary of Changes
This PR completely redesigns the standby instrument (ISIS) to match reality. Other than scaling and repositioning everything, following changes were made:
- **Speed**: marks only every 10 kt above 250 kt, removed speed mark at 25 kt
- **Altitude digits:** increments in 20 ft steps instead of 10 ft
- **Pitch:** fixed incorrect pitch being indicated compared to the PFD
- **Roll:** marks are now at 10, 20, 30, 45, and 60° (was 10, 20, 30, 40, 50)
- **Pressure:** aligned to the right, the number will no longer jump when switching between 999 and 1000 hPa

## Screenshots (if necessary)

Before:
image

After:
image

## References

image
image
image

Discord username (if different from GitHub): jakluk#1337

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
cc. @2hwk

**Comment by jakluk** [comment]
Now that I fixed the conflict in CHANGELOG.md, the checks have finally passed. From my side this is ready to be tested.

**Comment by joshbxd514** [comment]
Name: Joshbxd515 #4978
Date of testing: 18/10/2020 00:11 UK Time
Version of the sim: 1.9.5.0
PR Tested: #1328 

Testing technique: Ground testing (EGLC)

Steps you've made to test the Pull Request:

1. spawn C&D
2. turn on batt and gpu
3. wait for initialisation. 

Overall Rating: Good

Conclusions of the testing:  Works as described no issues good work :)

**Comment by 2hwk** [comment]
Name: 2Cas#1022
Date of testing: 18/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1328

Testing technique: Multiple Cold and Dark Flights, multiple spawns in-flight.

Steps you've made to test the Pull Request: Spawn C&D or enter through men, fly entire flight plan as per flight planner, taxi to the gate, exit. No ground services.

Overall Rating: Good

Conclusions of the testing: Works as described, does not seem to break any functionality.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 19/10/2020
Version of the sim: 1950
PR Tested: #1328

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane in C&D state
2. Inspected the backup IS on the ground 
3. Did a short flight while checking the behaviour of the backup IS


Overall Rating: Good
Conclusions of the testing: Wokring as documented, no issues spoted! Thank you for your work!

**Pull request merged**
