### PR TITLE
CRUISE and ELEC synoptics src

### PR DESCRIPTION
**Pull request by toffee2000**
**Summary of Changes**
Added CRUISE and ELEC synoptics in .svg format. Coding required to display on ECAM; only graphics provided.

**Screenshots (if necessary)**
image
image

### CODE REVIEW

**Comment by UncleClapton** [comment]
Hi was this PR made in cooperation with #439 at all?

**Comment by toffee2000** [comment]
> 
> 
> Hi was this PR made in cooperation with #439 at all?

No, independently. Feel free to pick whichever you prefer, I don't mind.

**Comment by JackZ974** [comment]
I guess the ELEC page is for teh CEO old version, judging by tthe ESS TR & EMER GEN form.
FYI i have also produced an svg for this ELEC Page.
ELEC PAGE 2
ELEC PAGE 1

**Comment by AdenFlorian** [comment]
@JackZ974 got a PR coming soon for your version of the elec page?

**Comment by JackZ974** [comment]
> 
> 
> @JackZ974 do you have a PR coming soon for your version of the elec page?

Well, if it's likely to be closed like the others, I'm wondering why I'm still bothering...  :-(
Anyways, I have made the ELEC page as a SVG file only, to be used by @ThePilot916 who is working on the Elec system. 
Will do a PR tomorrow if someone want to create the HTML and css files out of it.

**Comment by toffee2000** [comment]
Closing because no longer needed.

**Pull request closed without merging**
