### PR TITLE
[CDU] Create waypoint vertical revision page frontend and correct some flight plan displayed values

### PR DESCRIPTION
**Pull request by lousybyte**
Partially fixes and required for https://github.com/flybywiresim/a32nx/issues/499

**Summary of Changes**

- Create waypoint vertical revision page frontend
- Show proper constraints for waypoints in the flight plan page
- Switch to flight level display if alt is higher than trans alt in the flight plan page

**Screenshots (if necessary)**

[https://i.postimg.cc/qRWBvXmh/FP.png](https://i.postimg.cc/qRWBvXmh/FP.png)
[https://i.postimg.cc/G3knDCtS/vert.png](https://i.postimg.cc/G3knDCtS/vert.png)

**Additional context**

~~Edit logic NYI for vert rev page, read only for now.~~
UPDATE: Added limited altitude restriction editing functionality, see commit message for details.

### CODE REVIEW

**Comment by Snapmatics** [comment]
What do you mean read only? It's not simulated or something?

**Comment by lousybyte** [comment]
You cannot edit the waypoint restrictions at this moment, will come later if this gets approved.

**Comment by lousybyte** [comment]
Added the ability to change altitude restrictions to a certain degree, will have to wait for an API update to support additional features.

**Comment by wpine215** [comment]
Tested by Arman, LGTM

**Review by wpine215 — APPROVED** [review]

**Pull request merged**
