### PR TITLE
Improved Reverse Thrust, Added Turbulence Sound & Other Fixes

### LINKED ISSUE #2378: [BUG] Same wing sound as take-off on bounce of aircraft
**Mod Version**
Latest Dev version

**Describe the bug**
If an aircraft bounces, even minimally on the runway after touchdown, the same wing sound(vibration) is heard that is heard at T/O config during take-off. This sound should not be there during a bounce, as it is heard even on a small bounce.

**To Reproduce**

1. Land the A32NX, make a hard landing
2. Ensure that the aircraft bounces on the runway(even a small bounce would do)
3. Take-off wing sound heard as if we are taking off

**Expected behavior**
A separate/no sound for wings during a bounce

**Actual behavior**
Take-off wing sounds are heard on a bounce

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No, as there are no distinct take-off wing sounds on the vanilla A320NEO

VIDEO ATTACHED :

[Sample bounce.zip](https://github.com/flybywiresim/a32nx/files/5682697/Sample.bounce.zip)

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by hotshotp**
Fixes #2378

## Summary of Changes

This is a PR that I worked hard on, please give me extensive testing and honest feedback. As always, I will list the small changes listed here first:

- Fixed nose wheel vibration playing on touchdown
- Made cabin wind sound play throughout the whole cabin, including the back
- Made gear down thunk come in sooner, right after the gear lever motion
- Made throttle detents realistic: TOGA, Idle, and max reverse have no click, but clb and flx do have the click
- Made buzzsaw be almost silent on the ground, but when rising to 3000 feet, it continuously gets louder and more prominent to simulate realistic audio in progressively thinner air
- Fixed the pops that were present in the rumble sound
- Made hard touchdown sound for cockpit less sqeaky and more bassy
- Made the exterior engine startup and shutdown not play at the same time due to incorrect index

Now for the bigger changes:

- Completely remade interior reverse sound- has more bass and a more obvious wind rushing sound
- Added a new clattering sound for the ground roll, check references
- New turbulence rattling sound, different for both cockpit and cabin

## References

- [For the clattering of the ground roll](https://youtu.be/-mSSFCamk0I?t=133)
> Discussed turbulence with pilots and confirmed as realistic

- https://cdn.discordapp.com/attachments/753332968050786394/787325964760776714/Screenshot_2020-12-12_153158.png

## Additional context

I appreciate the testing and feedback, please feel free to message me on discord about any issues.

Discord username (if different from GitHub):

Boris#9134

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by z0rgmeister** [comment]
Category: QA Tester
Name: z0rgmeister#8972
Date of testing: 12/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2388
Object of test: Test Improved Reverse Thrust, Turbulence sound

Testing technique: C&D from EGCC, up to 15000, several touch and go landings. One final full stop landing.
Steps you've made to test the Pull Request:
1. Started C&D at EGCC. Noticed no pops when rolling.
2. Took off 23R, verified gear thunk as per PR. Also pushed the throttle detents all the way up to verify no click in MCT and TOGA as per PR.
3. Verified "buzzsaw" sound getting louder past 3000.
4. First touch and go hard (>600fpm), noticed a more bassy sound - good to go.
5. Second and third touch and go within normal limits. No change, all good.
6. Final touchdown with full reverse thrust, noticed new sounds (both thrust and clattering) working as intended.
7. All throughout there was the turbulece clattering whenever bank angle went over 5 degrees. 
8. During the final flight flew in and under heavy storm clouds to try and get turbulence but couldn't hear rattling even though the plane was clearly in turbulent air.
Flight notes (If required): NA

Issues (If Any): Turbulence rattling heard when bank angle >5º. Not heard when turbulence active.
Overall Rating: Good, see notes.
Conclusions of the testing: Overal a good addition to the already good sound work. Other than the turbulence being out of whack everything seems to be working as intended and adds to the immersion, as always.

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#8145
Date of testing: 12/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2388
Object of test: Testing improved sounds and fixes.

Testing technique: Cold and dark take off from ENVA to ENDU, on vatsim, it was very long so I got a good feel.

Steps you've made to test the Pull Request:

1. Cold and dark spawn into ENVA
2. Take off
3. Hand fly to 10000 feet to test turbulence noises
4. Flew rest of flight
5. Landed (buttered) into ENDU, tested reverse thrust.
6. Taxi to parking & shutdown.

Flight notes (If required): NA
Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Turbulence does rattle on turns, but as far as I know it is normal. Good work and great sounds as always Mr. Boris!

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: ChristopherXie#3904
Date of testing: Current date 12/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2388 
Object of test: Sounds

Testing technique: full flight from KPTK - CYYZ and spawned on a approach at CYYZ afterwards
Steps you've made to test the Pull Request:
1. Cold and dark startup.
2. hand flew to 10500 feet listening for turbulence sounds, there were huge gusts on departure so I was able to hear it :D. Also noticed the buzzsaw changes
3. Cruise (duh), wind sounds were audible throughout the whole cabin.
4. Landed on 15L at Pearson, no longer heard the nose wheel vibration and reversers sounds a lot better, gear thump was clearly delayed
5. Did an approach after the full flight to hear the changed hard landing sounds

Flight notes (If required):

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Great success Boris. This PR really completed your sounds, now go on making your PW and IAE sounds XD.

**Comment by FlightSimmer7700** [comment]
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date 12/12/20
Version of the sim: Version the tester uses
PR Tested: #2388 
Object of test: Sounds

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned in at Newcastle
2. flew a flight while in storm preset
3. changed to live weather too
4. landed in Leeds
5.

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: 
Nothing to complain about here as always. As a personal preference, I would like the turbulence and reversers to be louder but I understand that may be unrealistic.

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: Current date 13/12/2020
Version of the sim: 1.11.7
PR Tested: #2388 
Object of test: Improved Reverse Thrust, Added Turbulence Sound & Other Fixes
Testing technique: Tested the listed changes through different phases of flight by isolating each sound and muting everything else  (ex. while testing engine sound all other sounds were set to 0)
Steps you've made to test the Pull Request: (I'll list the changes list and the result of each test so it's easier)

- Fixed nose wheel vibration playing on touchdown :ballot_box_with_check:
- Made cabin wind sound play throughout the whole cabin, including the back :ballot_box_with_check:
- Made gear down thunk come in sooner, right after the gear lever motion :ballot_box_with_check:
- Made throttle detents realistic: TOGA, Idle, and max reverse have no click, but clb and flx do have the click :ballot_box_with_check:
- Made buzzsaw be almost silent on the ground, but when rising to 3000 feet, it continuously gets louder and more prominent to simulate realistic audio in progressively thinner air :ballot_box_with_check:
- Fixed the pops that were present in the rumble sound :ballot_box_with_check:
- Made hard touchdown sound for cockpit less squeaky and more bassy :ballot_box_with_check:
- Made the exterior engine startup and shutdown not play at the same time due to incorrect index :ballot_box_with_check:
- Completely remade interior reverse sound- has more bass and a more obvious wind rushing sound :ballot_box_with_check:
- Added a new clattering sound for the ground roll, check references :ballot_box_with_check:
- New turbulence rattling sound, different for both cockpit and cabin :ballot_box_with_check:

'''Issues (If Any): No issues but I'm wondering if some sounds are triggered randomly or during a specific events for example the clattering sound during ground roll, is it random or does it differ depending on the the surface?  

Flight notes (If required): Tested using REX weather and 7.1 surround sound

Conclusions of the testing: All sounds are great, good job!

**Comment by hotshotp** [comment]
> Category: QA Tester
> Name: Lazarus#4286
> Date of testing: Current date 13/12/2020
> Version of the sim: 1.11.7
> PR Tested: #2388
> Object of test: Improved Reverse Thrust, Added Turbulence Sound & Other Fixes
> Testing technique: Tested the listed changes through different phases of flight by isolating each sound and muting everything else (ex. while testing engine sound all other sounds were set to 0)
> 
> Steps you've made to test the Pull Request: (I'll list the changes and the result of each test so it's easier)
> 
> * Fixed nose wheel vibration playing on touchdown ☑️
> * Made cabin wind sound play throughout the whole cabin, including the back ☑️
> * Made gear down thunk come in sooner, right after the gear lever motion ☑️
> * Made throttle detents realistic: TOGA, Idle, and max reverse have no click, but clb and flx do have the click ☑️
> * Made buzzsaw be almost silent on the ground, but when rising to 3000 feet, it continuously gets louder and more prominent to simulate realistic audio in progressively thinner air ☑️
> * Fixed the pops that were present in the rumble sound ☑️
> * Made hard touchdown sound for cockpit less squeaky and more bassy ☑️
> * Made the exterior engine startup and shutdown not play at the same time due to incorrect index ☑️
> * Completely remade interior reverse sound- has more bass and a more obvious wind rushing sound ☑️
> * Added a new clattering sound for the ground roll, check references ☑️
> * New turbulence rattling sound, different for both cockpit and cabin ☑️
> 
> '''Issues (If Any): No issues but I'm wondering if some sounds are triggered randomly or during a specific events for example the clattering sound during ground roll, is it random or does it differ depending on the the surface?
> 
> Flight notes (If required): Tested using REX weather and 7.1 surround sound
> 
> Conclusions of the testing: All sounds are great, good job!

to answer your question, no, it is not random. Its not really needed as that sound is just the rattle of the cockpit door

**Pull request merged**
