### PR TITLE
refactor: Remove redundant bt setting

### LINKED ISSUE #7687: Redundant Boarding Rate Setting
### Aircraft Version

Development

### Description

{
      "built": "2023-01-02T11:51:15+00:00",
      "ref": "refs/heads/master",
      "sha": "2b2721a36a3e021db354f487a8222f00d4caaca5",
      "actor": "frankkopp",
      "event_name": "manual",
      "pretty_release_name": "master:2b2721a3"
}

### References (optional)

The boarding rate can be set in the settings page as well as the payload tab on the ground page in the EFB.
To keep it consistent to other rate settings, like the refueling rate, I would recommend removing the boarding rate setting from the settings page.

This keeps the EFB settings consistent and removes redundancy as well as complexity.

### Additional info (optional)

_No response_

### Discord Username (optional)

Micah#3002

### PR DESCRIPTION
**Pull request by MicahBCode**
Fixes #7687 

## Summary of Changes

Removed the boarding rate selection buttons in the Realism Settings Page as it is redudant. Boarding rate selection can be done on the payload page, just as the refueling rate can be done as well.

Discord username: MicahB#3002

## Testing instructions

1. Check the Settings Page
2. Navigate to the Realism Settings
3. Verify that the boarding rate setting has been removed.
4. Check the Ground Page
5. Navigate to the Payload Tab
6. Verify that the boarding rate can be selected at the bottom of the screen.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ExampleWasTaken** [comment]
Not sure this is a good idea. I'd rather add the fuel option to the realism page than removing the PAX option. Removing it causes similar settings to be distributed throughout the app which might not be very intuitive to users.

**Comment by MicahBCode** [comment]
My thought was just the other way round.

As this setting just affects the functionality on the same page i'm thinking it is very practical this way.
Sometimes you decide, that you want to board instantly for once. In that case you would have to switch to the settings, change it, go back to the payload page and start the boarding. And If you want to reset the settings to your normally preferred one you would have to do the same again, after the boarding process has finished. Isn't that just overhead?

I think the settings pages are very useful for settings affecting multiple functionalities or a functionality that is aircraft related and not flyPad related.

**Comment by ExampleWasTaken** [comment]
I'd pit them in both locations. Just for consistency

**Comment by tracernz** [comment]
I'd do away with the settings and make it just realistic, but with buttons on the pages "Complete Boarding Now" and "Complete Fueling Now"... everyone gets to pick what they want each time depending on how much time they have available that day.

**Comment by ExampleWasTaken** [comment]
> I'd do away with the settings and make it just realistic, but with buttons on the pages "Complete Boarding Now" and "Complete Fueling Now"...

Why remove a feature that already exists? Plus, that would break the general theme of `Realistic`, `Fast`, `Instant` for all things that need time to complete (e.g. ADIRS, etc.)

> everyone gets to pick what they want each time depending on how much time they have available that day.

That's how it is already. Why remove functionality from that?

**Comment by MicahBCode** [comment]
For the refueling process the ``Realistic``, ``Fast`` and ``Instant`` Buttons are also located on the Fuel page in the EFB, right next to where you start the refueling process. It just doesn't make sense to place these kind of "settings" in the settings page where you can configure all "real" system relevant settings.

With removing it from the settings page the functionality is not being removed completely. It is just redundant at the current state as the settings is now in two places. It will reduce redundancy and keep the UI cleaner. The functionality will still be available in the same way it is right now.

**Comment by tracernz** [comment]
> > I'd do away with the settings and make it just realistic, but with buttons on the pages "Complete Boarding Now" and "Complete Fueling Now"...
> 
> Why remove a feature that already exists? Plus, that would break the general theme of `Realistic`, `Fast`, `Instant` for all things that need time to complete (e.g. ADIRS, etc.)
> 
> > everyone gets to pick what they want each time depending on how much time they have available that day.
> 
> That's how it is already. Why remove functionality from that?

It’s quite tedious to change all of the different settings regularly. I just want a “ready now” button sometimes, and other times I want to go through the full process e.g. on the rare occasion when I’m doing a proper flight and not testing/developing things 🤣.

**Comment by MicahBCode** [comment]
Closed as there might be more suitable solutions.

**Pull request closed without merging**
