### PR TITLE
Fix: Clamp the selected altitude between 100ft and 49000ft

### LINKED ISSUE #1535: [BUG] Turning the altitude knob can decrease the selected altitude below zero even though the displayed value is clamped
**Mod Version**

built: 2020-10-25T03:41:28+00:00
ref: refs/heads/master
sha: 8794bc11701e452c57480bf1a13eac398d07419d
actor: Benjozork
event_name: push

**Describe the bug**

Turning the altitude knob on the FCU can decrease the selected altitude below zero even though the shown value on the PFD is clamped to zero and the one on the FCU to 100. This means to get the value up again you have to turn the knob up as much as you turned it down before.

**To Reproduce**

1. Spawn with everything running.
2. Decrease altitude on the FCU to 100.
3. Decrease altitude further.
4. Increase altitude again.

**Expected behavior**

The altitude should directly increase again in step 4.

**Actual behavior**

The altitude that is displayed on the FCU stays at 100 and the altitude that is displayed on the PFD stays at 0 until we turned the knob for a while.

**References**

https://www.youtube.com/watch?v=GtrjFRLxHN4&feature=youtu.be

In this video I'm first scrolling down to decrease the value and then slowly scrolling up to increase the value.

**Additional context**

Was this working before/when did the issue start occurring?
If I recall correctly, there was a change at some point to clamp the displayed value. I could not find the commit, though.

Is this a problem in the vanilla unmodded game?
No, at least not like this.

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by lars-reimann**
Fixes #1535 

## Summary of Changes

* Add custom behavior for the altitude knob on the FCU based on Asobo's templates
    * Remove code that does not target Airbus planes
    * Ensure the value for the selected altitude is between 100ft and 49000ft.

### Before

* https://youtu.be/GtrjFRLxHN4

### After
* [Selected altitude stays at or above ~~0ft~~](https://youtu.be/9sj9loWiC18) (now the minimum value is 100ft)
* [Selected altitude stays at or below ~~99900ft~~](https://youtu.be/oDw7ME4WpQg) (now the maximum value is 49000ft)

Range 100-49000 also confirmed by FlyingCarpet7 on Discord.

## Additional context

Discord username (if different from GitHub): Ignavia#1987

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by lukecologne** [comment]
I found this in the FCOM:
grafik

**Comment by lukecologne** [comment]
Also, you should consider moving this: https://github.com/flybywiresim/a32nx/blob/0c0e40c59e3fbd4ee4da7583033cebb939e9fb49/A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Misc.xml#L226 template to your new FCU file, since it also kind of belongs to the FCU

**Comment by lars-reimann** [comment]
Great, I'll change it accordingly.

**Comment by lars-reimann** [comment]
While testing I found a regression: The plane now instantly starts to ascend/descend when the altitude knob is turned, whereas in the current master branch the knob has to be pushed/pulled first. I'll look into what's causing it tomorrow.

**Comment by lukecologne** [comment]
Tested and looks good, do you want to change something or does it look good to you as well?

**Comment by lars-reimann** [comment]
I'm done with this.

**Pull request merged**
