### PR TITLE
feat: adjust ground services layout for flypados-v2

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #[issue_no]

## Summary of Changes

Just some spacing adjustments for the new layout.

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Benjozork** [comment]
I feel like we should make the aircraft take the entire height of the page (with appropriate padding ofc)

**Comment by Saschl** [comment]
Fixed I guess :D

**Comment by St54Kevin** [comment]
May we discuss the possibility of making the door buttons less wide to make them better to distinguish to an actual ground service?

**Comment by ZigTag** [comment]
> 
> 
> May we discuss the possibility of making the door buttons less wide to make them better to distinguish to an actual ground service?

I think its fine as it is

**Review by ZigTag — APPROVED** [review]

**Review by ZigTag — APPROVED** [review]

**Pull request merged**
