### PR TITLE
Fix ECAM N1 engine indicators/cosmetic changes #1197

### LINKED ISSUE #1197: [BUG] ECAM Engine Indications are wrong
**Mod Version**

master

**Describe the bug**

The range of the Engines N1 indication is wrong.
The Engine N1 "needle " at idle thrust has to be almost at the beginning of the arc (as seen in picture 1), not somewhere in the 1/4th.
Also the font seems to be a bit to thick, compared to the reference picture and what I am used to see.
However the EGT is lacking an amber vertical line as the Engine N1 has.
Also the red range seems to be longer as the one in the reference but this could be due to an different engine.

**To Reproduce**

1.Start Engines
2.
3.

**Expected behavior**

The idle Engine N1 is at or extremely close to the beginning of the arc.
image

**Actual behavior**

The idle Engine N1 is way to far off the beginning of the arc.
image

**References**

On Ground https://www.youtube.com/watch?v=cv41hm4JEB8&feature=youtu.be&t=100
In Air https://www.youtube.com/watch?v=FODhSJucbK0

**Additional context**

Was this working before/when did the issue start occurring?
Not working before
Is this a problem in the vanilla unmodded game?
Yes

DerL30N#3751

### PR DESCRIPTION
**Pull request by RichardPilbery**
Fixes #1197 

## Summary of Changes
All changes to Upper ECAM

1. N1 indicator now stays at lowest value until N1 exceeds 19.5%
2. Outermarker stroke width increased as per images below
3. Danger zone marking amended to match images below
4. Slight increase in spacing between elements on upper ECAM to better approximate images below

## Screenshots (if necessary)

Before shots in Issue #1197 

After shot:

Revised-upperECAM-page

## References

A320-NEO-Upper-ECAM-SAS-YT-Video 1

Source: https://www.youtube.com/watch?v=cv41hm4JEB

**Danger zone values from this LEAP-A1 document:**

leap-engine

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by St54Kevin** [comment]
There is a difference to your reference photo. The lowest indication for N1 is not at the very bottom. Your reference pic shows the indicator a little above even on the 0% engine

**Comment by RichardPilbery** [comment]
@St54Kevin You're right, it is just off the bottom of that gauge. I'll have a fettle and correct it.

**Comment by MisterChocker** [comment]
Is there as possibility that the decimal number is slightly smaller as seen in the reference pics?
(N1%, N2% and in the top right corner)

**Comment by RichardPilbery** [comment]
I'll see if I can change the gauge. This fix does not target the top-right hand corner values, so I'll leave those for another PR.

**Comment by Carter633** [comment]
Name: British Avgeek YT -- Carter633 #1436
Date of testing: 23/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1466 

Testing technique: Full Flight from Cold and Dark
Steps made to test the Pull Request: 

1.Spawned Cold and Dark
2. Monitored behaviour of N1 indicator during start up and throughout entire flight 
3. Reviewed the cosmetic details mentioned above throughout flight to see if any conditions caused issues
3. Works as described, no issues found

Overall Rating: Good
Conclusions of the testing: Works as described, nice work thanks!

**Comment by MisterChocker** [comment]
> I'll see if I can change the gauge. This fix does not target the top-right hand corner values, so I'll leave those for another PR.

@RichardPilbery gothu

**Comment by ImenesFBW** [comment]
Hey and thank you for your work.

I have a small problem when loading in C&D the upper ecam start like this:


then switches to the correct starting page after like 4min of waiting:

**Comment by ImenesFBW** [comment]
Concerning the upper comment. Apparently it is the same in the master, so it is not your PR that is doing this.

**Comment by RichardPilbery** [comment]
Thanks @ImenesFBW . I've found a couple of issues with the gauge logic, which I might try to fix once this PR is sorted.

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 23/10/2020
Version of the sim: 1950
PR Tested: #1466

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane in C&D.
2. Inspected the N1 on the upper ecam 
3. Monitored the N1 behaviour 

Overall Rating: Good 
Conclusions of the testing: Working as described (with noted bug that is not due to this PR), LGTM. Thank you for your work!

**Pull request merged**
