### PR TITLE
Fix potential EICAS crash from duplicate scripts

### PR DESCRIPTION
**Pull request by beheh**
## Summary of Changes

After the display performance PR (#2976) was merged I've been seeing warnings on my EICAS screens due to duplicate scripts. I've tried moving all referenced scripts from LowerECAM/UpperECAM to the top-level (EICAS), and that fixes the error for me locally at least. In some cases the error prevented the aircraft from starting up at all.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by XSJoJo** [comment]
LGTM, thanks for fixing!

**Comment by beheh** [comment]
Hm, is this obsolete now with #3054? I will retest later.

**Comment by XSJoJo** [comment]
No this change is still needed I think.

**Review by davidwalschots — APPROVED** [review]
LGTM. @beheh this change is still needed, as my PR only ensures resources are loaded in the declared order. There's nothing happening to remove duplicate imports 😃.

**Pull request merged**
