### PR TITLE
[CDU] allow entry of plus and minus in any position on the MCDU scratch line

### LINKED ISSUE #1326: [BUG] CRZ level and negative temp and wind - MCDU
**Mod Version**

Current master

**Describe the bug**
Right now it isn't possible to insert negative temps in the  CRZ FL / TEMP field (MCDU INIT page). Because behind the / (or any other entry) the minus won't work

**To Reproduce**

1. Enter cold&dark
2. get power on (APU or EXT)
3. go to the INIT page in MCDU
4. try to insert e.g. 320/-38 in the CRZ FL/ TMP field

**Expected behavior**
input of negative temps for higher alt

**Actual behavior**
see above

**Additional context**
EDIT: maybe the same problem: try to enter positiv winds in the INIT page 2 for "trip wind" (no minus in front of number). It's not working. Negative winds work here (??).

Was this working before/when did the issue start occurring?
Yesterday it worked. Seems to be a new one.

### LINKED ISSUE #1354: [BUG] Plus / Minus button on the MCDU does not take inputs
**Mod Version**

Stable release 0.4.0

**Describe the bug**

Plus / Minus button on the FMC does not function.

**To Reproduce**

1. Set up your flight on the INIT page of the FMC
2. When entering CRZ ALT/TEMP, attempt to enter the anticipated temperature at CRZ ALT (e.g. -50)
3.

**Expected behavior**

When clicking the button, a minus should appear in the text box. 

**Actual behavior**

A minus does not appear. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, up until the dev of the day before yesterday that button was still working as expected. 

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by lhoenig**
Fixes #1354
Fixes #1326

## Summary of Changes

Allow entry of plus/minus anywhere on the scratchpad line. 
If the scratchpad is empty or the current last character is neither "+" or "-", insert a "-". Otherwise toggle last char between "+" and "-".

## References

The requested Honeywell manual shows the plus/minus button as split, and does not describe these buttons further as far as I can see. Combined into one button seems to be more a Thales thing?
Still, every other unofficial source and note in the FCOM points to this being the correct behavior.
Confirmation from an IRL pilot would still be appreciated, of course. If you know more, let me know.

## Additional context

Discord username (if different from GitHub):  lukas_#6140

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Lucky38i** [comment]
A much more resilient solution to https://github.com/Lucky38i/a32nx/blob/2d6dd7054bda7eaffff9ebe1fc075379111cfd45/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L2159-L2163

**Comment by ImenesFBW** [comment]
For some reason when you load in and try to press the +/- btn after clearing the gps msg, it inputs a "-" even if you press it multiple times. If you press CLR again, you are then able to switch between "-" and "+".

Is that intended or needs fixing? Thank you for your effort!

**Comment by lhoenig** [comment]
@ImenesFBW Hmm, I can't reproduce, for me I can switch between "-" and "+" from the beginning.. I spawned on the runway and cleared the "GPS PRIMARY" message, then tried. Same with spawning C&D.

**Comment by ImenesFBW** [comment]
I pulled the PR again to make sure I can replicate it.

https://streamable.com/00wxge

**Comment by joshbxd514** [comment]
Hi all,

I have managed to reproduce the same issues imnesFBW is having.

After spawning from C&D and turning in battery and Ground power.

I cleared gps primary and i cannot switch between - & + unless i press CLR Again.

Thanks,

Joshbxd515#4978

**Comment by lhoenig** [comment]
Ok I was able to reproduce. Actually this is not the fault of my code but of the GPS PRIMARY error message code, which seems overcomplicated and leaves `mcdu.isDisplayingErrorMessage` on true after the message is dismissed. It's spaghetti code and should be properly refactored, but I don't have the time today..

**Comment by Derek-Lane** [comment]
Name: Discord User Derek Lane #6709
Date of testing: Current date 17/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1372 

Testing technique: Cold & Dark start, batt power on, mcdu input entry
Steps you've made to test the Pull Request:
1. Cold and Dark Start
2. Bat on
3. CLR on MCDU to remove GPS Message
4.Press +/- results in a "-" appearing in scratch pad, pressing +/- again does nothing, display remains as "-"
5.Pressing CLR again to clear scratch pad then pressing +/- results in a "-" appearing, a second press of the +/- results in the "+" appearing.

Overall Rating: Needs to be approved but appears others have already noted and will look into it. will test again once fixed
Conclusions of the testing: will test again once fixed

**Comment by St54Kevin** [comment]
I can confirm the above described bug. Otherwise it works flawlessly

**Comment by lhoenig** [comment]
I'm working on a refactor of the code causing the unintentional behaviour (GPS status messages on the CDU), but as I said it is not really connected to the logic of this PR's code, which is correct I think.

**Comment by lhoenig** [comment]
Done. I had to dig a little bit deeper to get to the bottom of it. But the resulting code is much, much cleaner and along the lines I discovered some small things and cleaned them up too, see the commits (and their messages).

**Comment by camilo625** [comment]
Name: Camilo625 #5575
Date of testing: Current date 19/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1372 

Testing technique: Spawn and test MCDU
Steps you've made to test the Pull Request:
1. Spawn C&D
2. Test MCDU

Overall Rating: Good
Conclusions of the testing: Works as described

**Comment by Benjozork** [comment]
@camilo625 can you confirm the issue that was mentioned before is fixed ?

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing: Current date 23/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1372

Testing technique: Spawn on RWY and spawn from C&D
Steps you've made to test the Pull Request:

In MCDU, tried inputting + or - at various places in scratchpad. All fine. GPS Primary does not interfere anymore and the + does now appear when button pressed twice.

Overall Rating: Good
Conclusions of the testing: LGTM. I checked through the previous issues and confirmed that they are not present anymore, particularly the behaviour around GPS Primary message.

**Comment by armankir** [comment]
Name: Arman#8145
Date of testing: Current date 23/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1372

Testing technique: Spawn C&D

Steps you've made to test the Pull Request:

Pressed +/- on multiple pages, no issues found. 

Overall Rating: Good
Conclusions of the testing: Operates fine, the older bugs seem to be ironed out. Great work.

**Comment by Carter633** [comment]
Name: British Avgeek YT -- Carter633 #1436
Date of testing: 23/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1372 

Testing technique: Spawn C&D, check MCDU

Steps made to test the Pull Request:
1.Spawned Cold and Dark - checked MCDU allowing plus and minus entry in multiple areas

Overall Rating: Good
Conclusions of the testing: works well and no issues found. Issue mentioned at the start of the PR isn't present anymore

**Pull request merged**
