### PR TITLE
feat: grid-layout same sized buttons on failure page

### PR DESCRIPTION
**Pull request by nathanmayall**
## Summary of Changes

EFB Failure buttons now look a lot more neat. Also uses a grid pattern, as more failures are added these will conform to the grid automatically.

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub): AbsoluteNath#9406

## Testing instructions

Go to the Failures page in the EFB and check the buttons look neat and are in a grid 4 columns wide.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ErickSharp** [comment]
Within this pull request, do you think you would be able to add some document event listeners to have some sort of dragging system? This would give us a lot of flexibility going forward but if not I can implement it shortly after this is merged.

**Comment by nathanmayall** [comment]
@ErickSharp Sure, can do. Leave it with me

**Comment by davidwalschots** [comment]
This view will over time have very different presentational requirements. It is merely a placeholder to build upon. I would deem it very unlikely the current way of failing things would persist, as having hundreds of buttons in a grid would not make sense. I would recommend reading through [this document](https://github.com/flybywiresim/rfcs/blob/1ed0dc339c3a43e95e6cd1636cf2619f007ee841/text/000-failures.md)'s requirements section to see what functionality we'd like to support at some point in the future. Does the grid change you propose now still fit with that, or would you take another approach?

I'd be curious to hear your thoughts!

> Within this pull request, do you think you would be able to add some document event listeners to have some sort of dragging system?
@ErickSharp this seems entirely unrelated to this PR and therefore shouldn't be added to it.

**Comment by nathanmayall** [comment]
@davidwalschots Hi David, thank you for the feedback. Initially I just wanted to make the change to improve the current layout as it is. However after reading the doc you sent, I agree that the grid layout would not be ideal as time goes on.

For what you have at the moment, it's fine, but in the future I'd like to see some sort of tabbed display with the different categories of failure, and a section for engaging different scenarios such as random, real-world, pre-programmed and no-failure god mode etc. 

Although I'm more than happy for this to be merged as an improved placeholder, and once the failure system is more mature, I can work on another PR with the UI for said categories etc.

Cheers,

**Review by davidwalschots — APPROVED** [review]
Sounds good Nathan! I'll approve this because it is an improvement indeed 😀.

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5792 
Tier of Testing: 1
Date: 08/09/2021

**Testing Process:**
1. Loaded onto RW and checked wether failures are shown in a 4 coumn grid

**Negatives:** N/A
**Testing Results:** Passed

**Pull request merged**
