### PR TITLE
fix(ecam/upper): fix thrust limit display

### LINKED ISSUE #909: [BUG] Thrust limit jumping to 92.8% every ~500ms until 3000ft / is stuck at 100% before being moved
**Mod Version**

master

**Describe the bug**

Throttle jumping to 92.8% every ~500ms until 3000ft after unfreezing it (ghost data from other airplanes again?)

**To Reproduce**

1. Start at EDDM (Munich) on the runway
2. Throttle will be at 92.% (like #748, just with this slightly lower number?)
3. Apply full throttle to un-freeze the throttle display
4. Throttle will jump back to 92.8% every 0.5s until you hit 3000ft

**Expected behavior**

Throttle should not jump

**Actual behavior**

Throttle will jump back to 92.8% every 0.5s until an altitude of 3000ft is reached (could be different for other airports, and maybe enough distance to the airport will also fix it)

**References**

https://gifyu.com/image/62TC

**Additional context**

Was this working before/when did the issue start occurring?
I just noticed it for the first time.

Is this a problem in the vanilla unmodded game?
No. In the unmodded game, the throttle will also be stuck at 92.8%, but after getting it unstuck, will behave normally.

Discord username (if different from GitHub):
lukas_#6140

### PR DESCRIPTION
**Pull request by Benjozork**
Fixes #909

## Summary of Changes

* Use throttle position instead of thrust limit simvar, because the latter is bugged (stays at 92.8% percent for no reason), and in practice they are the same exact value throughout the tests I performed
* Use "TOGA" instead of "TO/GA"

## References

* FCOM

image

Discord username (if different from GitHub): someperson#4953

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by donstim** [comment]
This may fix the issue in #909, but it raises issues of its own. The thrust rating is an N1 setting that varies with temperature, pressure altitude, and bleed condition. In other words, it is independent of throttle position. With this mod, for example, TOGA will always be 100% N1, which, of course, is incorrect (not that the displayed setting without the mod is correct, but it is better than 100%).

If the issue is the thrust value dropping out momentarily, is there a way to latch it or do a check that the new value is sufficiently close to the old value before allowing the new value to display or something?

**Comment by Benjozork** [comment]
@donstim, I tried using the actual thrust limit value but it seems to jump around a lot for no reason. I would have to implement logic to require it being constant for a certain amount of frames, and frankly that would be complicated.

I also compared the value of thrust limit and throttle position, and they seem to be exactly the same at all times.

This PR only fixes the initial value being 92.6% and the incorrect label - I'm aware the behaviour is wrong still, but we'll need more detailed engine systems to be modeled first.

**Comment by Carter633** [comment]
Name: British Avgeek YT -- Carter633 #1436
Date of testing: Current date 21/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1473 

Testing technique: Full flight from Cold and Dark
Steps you've made to test the Pull Request:
1. Spawned on stand C&D
2. Pushback, Eng Start, Taxi and Take off - monitor thrust limit area for changes
3. Use FLX and TOGA modes
4. Initial Climb checking MCT and CLB modes
4. Land and Taxi to Stand

Overall Rating: Good
Conclusions of the testing: From my understanding, throttle position has been given primacy for the values selecting the above modes and it's a fix for an issue pending further A32nx development. In this regard I found no issues with is working as described above and it got rid of the stuck 92.8% reading

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 21/10/2020
Version of the sim: 1950
PR Tested: #1473

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane in C&D.
2. Flown a quick ILS circuit 
3. Monitored the thrust rating read-out

Overall Rating: Good 
Conclusions of the testing: Working as described with noted behavior differences, LGTM. Thank you for your work!

**Comment by St54Kevin** [comment]
I dont understand why we changed that indication to a non realistic one? We have values that FLX and TOGA goes to when set. Those should be in there.

**Pull request merged**
