### PR TITLE
Changing CRZ and DES speed to allow and hold any speed restriction

### LINKED ISSUE #2655: [BUG] Odd A/T Behavior On/Close to Descent
**Stable 0.5.1**

**Describe the bug**
When approaching TOD (perhaps when planned for descent to begin whether or not descent actually begun), A/T shifts into deceleration.  When descending, the A/T seems to bounce between idle/thrust wildly as if it cannot seem to decide upon a descent rate.

**To Reproduce**
1. Cruise with IFR flight plan active towards descent into any airport (I flew into KDEN).
2. When approaching descent observe throttle activity.
3. When cleared to begin descent by ATC, observe throttle activity.

**Expected behavior**
Relatively smooth descent maintaining planned descent speed profile.

**Actual behavior**
Volatile throttle engage/disengage every 5-7 seconds with dramatic speed and pitch changes resulting.  When engaging the speed knob instead, descent smoothed.  Thx.

**References**
N/A

**Additional context**
Also noted the wobbling left to right is somewhat back even while descending thru FL100 at 250K or less (noted in another report at CRZ).

**Was this working before/when did the issue start occurring?**
This was working prior to MSFS v1.12 update 12/22 using FBW v0.5.0.  Began after MSFS update.

**Is this a problem in the vanilla unmodded game?**
No.  Does not occur in default A320 to my knowledge (only attempted one flight after update while waiting for v0.5.1).

### LINKED ISSUE #2864: [BUG] Cruise speed oscillating between 170 and 290 when reaching cruise altitude in managed mode.
**Mod Version**

master

{
  "built": "2021-01-03T01:18:30+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**

I was doing a flight from KLAX - KLAS.  25R ORCKA5 departure MISEN transition, into KEPEC6 arrival MISEN transition into ILS 01L.  Fully programmed the MCDU.  Init page was set to Cruise Alt FL290.  Perf takeoff page set to flaps 1, Flight plan set as specified.  Cost Index 30. Weather was set to live weather, and time set to 9am.  there were fog, and clouds present.

I took off on 25R turned left, and did a managed climb to cruise altitude via the SID.

When i reach cruise altitude, The cruise speed kept oscillating between 170 and 290 on the speed tape.  If i looked at the cruise perf page, the speed was changing between *170 and *290.  You can see this behavior in the video in this link:

https://www.youtube.com/watch?v=1v-3bZlko_k

**To Reproduce**

1. program MCDU as specified above ( i used the default fuel/weight numbers when programming the Init B page)
2.set weather/time (not sure if this has anything to do with it.  On the help discord, someone said it might have to do with clouds being present,
3.follow sid, climb to cruise in managed mode (speed, heading, and altitude), experience speed oscillation at cruise.

**Expected behavior**

Managed speed to be set to the value calculated, for the cost index. (~290 kts)

**Actual behavior**

Managed speed setting oscillates between 170 and 290 kts.

**References**

Video of issue here:
https://www.youtube.com/watch?v=1v-3bZlko_k

**Additional context**

Was this working before/when did the issue start occurring?

This has been an issue in the master builds for at least the last week at time of this posting.

Is this a problem in the vanilla unmodded game?
don't know, haven't trying stock 320.

Discord username (if different from GitHub):
TheJoe88

### PR DESCRIPTION
**Pull request by Watsi01**
Fixes #2864
Fixes #2655

## Summary of Changes
Right now, when there is a speed restriction, the managed speed jumps back and forth between CRZ speed and speed restriction during cruise.

I changed flightphase CRZ speed to allow and hold any speed restriction and go back to normal CRZ speed, when no speed restriction is given for the next waypoint(s).

**EDIT**: changed also the DES speed, cause it's the same problem there.

## Additional context

Discord username (if different from GitHub): RogePete

## Testing instructions
If you like, you can program the following testroute in your MCDU to test. There are some speed restrictions involved to see, if manages speed holds the restrictions and comes back to normal crz speed, if no restriction is set for a waypoint.

KLAX/KLAS, CRZ Level FL290, CI30

KLAX 25R via ORCKA5 SID Trans MISEN
then
OINKS HEINY SERUE COOLS (I made that little loop to see if the change between restr and normal CRZ speed works)
and finaly
KLAS ILS01L via KEPEC6 STAR and Trans MISEN

The route should now look like this:
test

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Watsi01** [comment]
@donstim Could you check this and give it a ready to test? Thx.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by Benjozork** [comment]
They don't have access yet, so I will

**Comment by Watsi01** [comment]
**EDIT**: additionally removed some unfinished code from @MisterChocker regarding speed constraints in MCDMaindisplay (he told me to do so).

**Comment by Watsi01** [comment]
Sorry, fucked that up. I'll make a new PR.

**Pull request closed without merging**
