### PR TITLE
[CDU] Allow input while message is shown, minor bug fixes and improvements

### PR DESCRIPTION
**Pull request by MisterChocker**
## Summary of Changes

- Changed input handling to LSK or RSK when message is shown.
- Added message override ability.
- Added queue position update checker on same message entry.
- Fixed `GPS PRIMARY` or `GPS PRIMARY LOST` only visible once.
- Added handler for the system to write onto the scratchpad.
- Swapped parameters for `addTypeTwoMessage` to be more convenient.

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by lukecologne — APPROVED** [review]

**Comment by MisterChocker** [comment]
I found some sort of bug, so I want to include a fix for that.

**Comment by MisterChocker** [comment]
### For testing
- Test if new messages gets displayed first/on top (checks last in first out functionality)
_for easy test, on PERF PAGE insert higher V1, then turn off ADIRS_
- Test if you can use LSK or RSK buttons while message is being displayed

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: Current date 29/11/2020
Version of the sim: 1.11.6
PR Tested: #2121
Object of test: Allow input while message is shown, test last in first out functionality 

Testing technique: Loaded at gate, changed IRS align time time to instant for faster testing 
Steps you've made to test the Pull Request:
1. Loaded at gate 
2. Aligned adirs 
3. Entered higher V1 speed in perf page  
Microsoft Flight Simulator Screenshot 2020 11 29 - 09 28 42 49

4.Turned off adirs 
5.Last in first out check 
Microsoft Flight Simulator Screenshot 2020 11 29 - 09 28 54 94

6.Tried using the mcdu's lsk and rsk, image on the left is testing next phase button, image on the right is manually adding input 
pjimage


Flight notes (If required): Using the lsk at the V1 part does not input the correct V1 speed into the scratchpad however manual input works fine. 

Issues (If Any): N/A 
Overall Rating: Good
Conclusions of the testing: Looks good to me except for part of getting the correct V speeds into the scratchpad (not sure if that's how it should be or not)

**Comment by MisterChocker** [comment]
@Lazarus320 didn't you got 145 for v1?

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#8145
Date of testing: 11/28/2020
Version of the sim: 1.11.6
PR Tested: #2121 
Object of test: Allow Input When Message Shown in MCDU.

Testing technique: Getting messages in MCDU and attempting to apply input while the message is shown.
Steps you've made to test the Pull Request:
1. Loaded into A32NX, test airport F45.
2. Got a message, for this case it was "GPS Primary Lost."
3. Attempted to input text.
4. Cleared message.
5. Verified the PR is functional.

P.S. I also checked the bug as mentioned above, does not seem to exist anymore.

Flight notes (If required): LGTM, good PR.

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Great PR, great work. The before-mentioned bug seems to now be fixed. Cheers.

**Comment by MisterChocker** [comment]
I haven't pushed the changes to the master yet :|

**Comment by armankir** [comment]
> I haven't pushed the changes to the branch yet :|

Didn't have his issue, but to be safe disregard and I'll retest.

**Comment by MisterChocker** [comment]
@armankir you will have the exact same issue, because there is no way it works without my changes ^^.

**Comment by armankir** [comment]
> @armankir you will have the exact same issue, because there is no way it works without my changes ^^.

Must have did something wrong, I'll try again once fixed.

Many apologies!

**Comment by MisterChocker** [comment]
> > @armankir you will have the exact same issue, because there is no way it works without my changes ^^.
> 
> Must have did something wrong, I'll try again once fixed.
> 
> Many apologies!

Np, it's ready to be tested again.

**Comment by Lazarus320** [comment]
> > > @armankir you will have the exact same issue, because there is no way it works without my changes ^^.
> > 
> > 
> > Must have did something wrong, I'll try again once fixed.
> > Many apologies!
> 
> Np, it's ready to be tested again.

Works fine now, good job! 
ezgif com-gif-maker

**Comment by armankir** [comment]
Category: QA Tester
Name: Arman#8145
Date of testing: Current date 11/30/2020
Version of the sim: 1.11.6
PR Tested: #2121 
Object of test: Input while shown message in MCDU + bug fixes.

Testing technique: Made messages appear, then tested if I could input.

Steps you've made to test the Pull Request: 

1. Spawned in.
2. Made the "GPS Primary Lost" message appear.
3. Attempted to input.
4. Made sure input was there.
5. Tested to make sure the previous bug is now gone.

Flight notes (If required): None. Worked like a charm.

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Great work! The bug is now fixed (I made sure this time lol)

**Comment by MisterChocker** [comment]
don't merge!

**Comment by MisterChocker** [comment]
@lukecologne do we need more testing or are we good to merge?

**Comment by lukecologne** [comment]
No, looks good to me, if you don't want to add anything

**Pull request merged**
